  {id:2101,word:"cardiologist",partOfSpeech:"名詞",meaning:"心臓専門医",
   meanings:["名|心臓専門医"],
   pronunciation:"/ˌkɑːrdiˈɑːlədʒɪst/",part:211,
   example:"The cardiologist checked my heart after I felt chest pain.",
   exampleJa:"胸の痛みを感じたあと、心臓専門医が私の心臓を調べた。",
   example2:"She wants to become a cardiologist and save many lives.",
   exampleJa2:"彼女は心臓専門医になって、多くの命を救いたいと思っている。",
   etymologyProcess:"cardi（心臓）＋ log（学問）＋ ist（人）→ 胸で脈打つ器官を研究する人は…？",
   etymologyConclusion:"cardi（心臓）＋ log（学問）＋ ist（人）→ 心臓を学問として調べ、その病気を治す医師＝心臓専門医",
   relatedWords:[
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）→ 生き物のしくみを調べる学問"},
     {word:"artist",meaning:"芸術家",breakdown:"art（技）＋ ist（人）→ 技を使って作品を作る人"},
     {word:"psychologist",meaning:"心理学者",breakdown:"psych（心）＋ log（学問）＋ ist（人）→ 心の働きを研究する人"},
     {synonym:true,word:"heart",meaning:"心臓；心",breakdown:"cardi と同じ大昔の語から英語に残った形。ふつうの「心臓」"}]},

  {id:2102,word:"kidney",partOfSpeech:"名詞",meaning:"腎臓",
   meanings:["名|腎臓"],
   pronunciation:"/ˈkɪdni/",part:211,
   example:"The doctor said that one of his kidneys was not working.",
   exampleJa:"医者は、彼の腎臓の片方がうまく働いていないと言った。",
   example2:"Drinking enough water every day is good for your kidneys.",
   exampleJa2:"毎日十分な水を飲むことは、腎臓によい。",
   etymologyProcess:"kidney（豆形の器官）→ 血をこして尿を作る器官は…？",
   etymologyConclusion:"kidney（豆形の器官）→ 腰の後ろに左右1つずつあり、血をこして尿を作る器官＝腎臓",
   hook:"語源ははっきりしない。kidney bean（インゲン豆）は、形が腎臓に似ているからこう呼ぶ。",
   relatedWords:[
     {synonym:true,word:"liver",meaning:"肝臓",breakdown:"栄養をたくわえ毒を分解する器官。kidney は血をこす"},
     {synonym:true,word:"stomach",meaning:"胃",breakdown:"食べ物をこなす袋。kidney は背中側にある"},
     {synonym:true,word:"heart",meaning:"心臓",breakdown:"血を送り出すポンプ。kidney はその血をきれいにする"},
     {synonym:true,word:"organ",meaning:"臓器，器官",breakdown:"体の中で役目を持つ部分の総称。kidney もその1つ"}]},

  {id:2103,word:"posture",partOfSpeech:"名詞",meaning:"（体の）姿勢，構え；態度",
   meanings:["名|（体の）姿勢，構え","名|（物事に対する）態度，心構え"],
   pronunciation:"/ˈpɑːstʃər/",part:211,
   example:"Good posture helps you breathe more easily when you sing.",
   exampleJa:"よい姿勢は、歌うときに呼吸を楽にしてくれる。",
   example2:"The government took a firm posture on the trade issue.",
   exampleJa2:"政府はその貿易問題に対して強硬な態度をとった。",
   etymologyProcess:"pos（置く）＋ ure（名詞）→ 体をどう置いているかは…？",
   etymologyConclusion:"pos（置く）＋ ure（名詞）→ 頭や背中や手足をどう置いているかという形＝（体の）姿勢，構え",
   etymologyMore:["体の構えを心の構えに広げる→（物事に対する）態度，心構え"],
   relatedWords:[
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ion（名詞）→ 物が置かれている場所"},
     {word:"opposite",meaning:"反対側の",breakdown:"op（向かい合って）＋ pos（置く）→ 向かい側に置かれた"},
     {word:"compose",meaning:"組み立てる",breakdown:"com（共に）＋ pos（置く）→ 部品を一緒に置いて組み立てる"},
     {word:"deposit",meaning:"預金；預ける",breakdown:"de（下へ）＋ pos（置く）→ 下に置いて預けておく"}]},

  {id:2104,word:"metabolism",partOfSpeech:"名詞",meaning:"（新陳）代謝",
   meanings:["名|（新陳）代謝"],
   pronunciation:"/məˈtæbəlɪzəm/",part:211,
   example:"Regular exercise can help speed up your body's metabolism.",
   exampleJa:"定期的な運動は、体の代謝を速める助けになる。",
   example2:"Babies usually have a faster metabolism than old people.",
   exampleJa2:"赤ちゃんはふつう、お年寄りよりも代謝が速い。",
   etymologyProcess:"meta（後を追って）＋ bol（投げる）→ 投げたあと別の物に変わると…？",
   etymologyConclusion:"meta（後を追って）＋ bol（投げる）→ 取り入れた物を体の中で別の物質に作りかえる働き＝（新陳）代謝",
   why:"【なぜ】ギリシャ語 metabolē は「投げて向きを変える」ことから「変化」を意味しました。19世紀の生物学者が、食べた物が体の中で次々に別の物質へ作りかえられる働きをこの語で呼び、「代謝」の意味になりました。\n【つながり】bol（投げる）は symbol（シンボル）と同じ。meta はもとは「後に」で、metamorphosis（変態）のように「後で別の形に」を表します。",
   relatedWords:[
     {word:"symbol",meaning:"象徴，シンボル",breakdown:"sym（共に）＋ bol（投げる）→ 割った札を投げ合わせて照らす印"},
     {synonym:true,word:"digest",meaning:"消化する",breakdown:"食べ物を体で分解すること。metabolism はその後の変化全体"},
     {synonym:true,word:"energy",meaning:"エネルギー，活力",breakdown:"代謝で作り出される力。metabolism が速いと多く使う"},
     {synonym:true,word:"diet",meaning:"食事；ダイエット",breakdown:"何を食べるか。metabolism は食べた物の使われ方"}]},

  {id:2105,word:"famine",partOfSpeech:"名詞",meaning:"飢饉，深刻な食糧不足",
   meanings:["名|飢饉，深刻な食糧不足"],
   pronunciation:"/ˈfæmɪn/",part:211,
   example:"The long drought caused a famine across the whole region.",
   exampleJa:"長い干ばつが、地域全体に飢饉を引き起こした。",
   example2:"Many families left Ireland during the Great Famine in the 1840s.",
   exampleJa2:"1840年代の大飢饉の間に、多くの家族がアイルランドを離れた。",
   etymologyProcess:"fames（飢え）＋ ine（もの）→ 国じゅうが飢えに苦しむと…？",
   etymologyConclusion:"fames（飢え）＋ ine（もの）→ 食べ物がなくなり、大勢の人が飢えに苦しむこと＝飢饉，深刻な食糧不足",
   spelling:"fames→fam（語尾が落ちて -ine が付いた）",
   relatedWords:[
     {word:"famished",meaning:"腹ぺこの",breakdown:"fames（飢え）→ 飢えてお腹がぺこぺこの"},
     {synonym:true,word:"hunger",meaning:"飢え，空腹",breakdown:"1人1人の空腹。famine は地域全体の食糧不足"},
     {synonym:true,word:"starve",meaning:"飢える",breakdown:"食べ物がなく苦しむ動き。famine はその災害そのもの"},
     {synonym:true,word:"shortage",meaning:"不足",breakdown:"物が足りないこと全般。famine は食べ物の深刻な不足"}]},

  {id:2106,word:"riot",partOfSpeech:"名詞",meaning:"暴動，騒動",
   meanings:["名|暴動，騒動","自|暴動を起こす"],
   pronunciation:"/ˈraɪət/",part:211,
   example:"The police tried to stop the riot in the city center.",
   exampleJa:"警察は、市の中心部で起きた暴動を止めようとした。",
   example2:"Angry fans rioted in the streets after their team lost.",
   exampleJa2:"チームが負けたあと、怒ったファンが通りで暴動を起こした。",
   etymologyProcess:"riot（騒ぎ）→ 大勢が暴れて町が荒れると…？",
   etymologyConclusion:"riot（騒ぎ）→ 大勢の人が集まって暴れ、町の秩序が乱れる騒ぎ＝暴動，騒動",
   hook:"もとは古いフランス語で「口げんか，大騒ぎ」。a riot of color（色の洪水）とも言う。",
   relatedWords:[
     {synonym:true,word:"protest",meaning:"抗議する；抗議",breakdown:"反対の意見を示すこと。riot は暴力をともなう"},
     {synonym:true,word:"violence",meaning:"暴力",breakdown:"力で傷つけること。riot は集団で起こす暴力"},
     {synonym:true,word:"crowd",meaning:"群衆",breakdown:"集まった大勢の人。それが暴れると riot になる"},
     {synonym:true,word:"rebellion",meaning:"反乱",breakdown:"支配する側に逆らう戦い。riot は突発的な騒ぎ"}]},

  {id:2107,word:"asylum",partOfSpeech:"名詞",meaning:"（政治的な）亡命，保護",
   meanings:["名|（政治的な）亡命，保護","名|避難所"],
   pronunciation:"/əˈsaɪləm/",part:211,
   example:"The journalist asked for political asylum in Canada.",
   exampleJa:"その記者は、カナダに政治的な亡命を求めた。",
   example2:"The country gave asylum to thousands of refugees last year.",
   exampleJa2:"その国は昨年、何千人もの難民に保護を与えた。",
   etymologyProcess:"asyl（奪われない場所）→ 追われた人が逃げこむと…？",
   etymologyConclusion:"asyl（奪われない場所）→ 追われた人が逃げこみ、だれにも手出しされず守られること＝（政治的な）亡命，保護",
   hook:"a（ない）＋ syl（奪う）。昔の神殿は、逃げこんだ人を捕まえてはいけない聖域だった。",
   relatedWords:[
     {synonym:true,word:"refugee",meaning:"難民",breakdown:"国を逃れた人。asylum はその人が受ける保護"},
     {synonym:true,word:"shelter",meaning:"避難所",breakdown:"雨風や危険から身を守る場所全般"},
     {synonym:true,word:"refuge",meaning:"避難所",breakdown:"逃げこむ場所。asylum は国が与える保護"},
     {synonym:true,word:"exile",meaning:"追放，亡命",breakdown:"国を追われること。asylum は受け入れる側の保護"}]},

  {id:2108,word:"workforce",partOfSpeech:"名詞",meaning:"労働力，労働人口；（会社の）全従業員",
   meanings:["名|労働力，労働人口","名|（会社の）全従業員"],
   pronunciation:"/ˈwɜːrkfɔːrs/",part:211,
   example:"Women now make up almost half of the country's workforce.",
   exampleJa:"今では女性が、その国の労働力のほぼ半分を占めている。",
   example2:"The company plans to cut its workforce by ten percent.",
   exampleJa2:"その会社は、全従業員を10パーセント減らす計画だ。",
   etymologyProcess:"work（仕事）＋ force（力）→ 働く人の力を全部合わせると…？",
   etymologyConclusion:"work（仕事）＋ force（力）→ 仕事をするために集まった人々の力全体＝労働力，労働人口",
   etymologyMore:["国全体の働き手を1つの会社で数える→（会社の）全従業員"],
   relatedWords:[
     {word:"housework",meaning:"家事",breakdown:"house（家）＋ work（仕事）→ 家の中でする仕事"},
     {word:"effort",meaning:"努力",breakdown:"ef（外へ）＋ fort（力）→ 力を外へ出しきること"},
     {word:"comfort",meaning:"慰め；快適さ",breakdown:"com（すっかり）＋ fort（力）→ すっかり力づけてほっとさせる"},
     {word:"enforce",meaning:"（法律を）施行する",breakdown:"en（～にする）＋ force（力）→ 力でもって守らせる"}]},

  {id:2109,word:"prefecture",partOfSpeech:"名詞",meaning:"県，府",
   meanings:["名|（日本などの）県，府"],
   pronunciation:"/ˈpriːfektʃər/",part:211,
   example:"Nagano Prefecture has many high mountains and very cold winters.",
   exampleJa:"長野県には高い山が多く、冬はとても寒い。",
   example2:"Students from every prefecture came to Tokyo for the national tournament.",
   exampleJa2:"全国大会のために、すべての県から生徒たちが東京に来た。",
   etymologyProcess:"pre（前へ）＋ fect（作る）＋ ure（名詞）→ 前に立てた長官が治める区域は…？",
   etymologyConclusion:"pre（前へ）＋ fect（作る）＋ ure（名詞）→ 人々の前に立てられた長官が治める区域＝県，府",
   why:"【なぜ】ラテン語 praefectus は「前に立てられた者」、つまり長官です。facere（作る）には「任じる」という意味もありました。その長官が受け持つ地域が praefectura で、フランスの県庁所在地などを指し、のちに日本の「県・府」の英訳に使われるようになりました。\n【つながり】fect は effect（効果）や perfect（完璧な）の「作る」と同じです。",
   relatedWords:[
     {word:"perfect",meaning:"完璧な",breakdown:"per（すっかり）＋ fect（作る）→ すっかり作り上げた"},
     {word:"effect",meaning:"効果",breakdown:"ef（外へ）＋ fect（作る）→ 外に作り出された結果"},
     {word:"prefer",meaning:"より好む",breakdown:"pre（前へ）＋ fer（運ぶ）→ 好きな方を前へ運んで選ぶ"},
     {word:"prepare",meaning:"準備する",breakdown:"pre（先に）＋ par（整える）→ 先に整えておく"}]},

  {id:2110,word:"hierarchy",partOfSpeech:"名詞",meaning:"（組織の）階層制，序列",
   meanings:["名|（組織の）階層制，序列"],
   pronunciation:"/ˈhaɪərɑːrki/",part:211,
   example:"Every company has a hierarchy, from new workers to the president.",
   exampleJa:"どの会社にも、新入社員から社長までの階層制がある。",
   example2:"In our club, there is no strict hierarchy between older and younger members.",
   exampleJa2:"私たちの部には、先輩と後輩の間の厳しい序列はない。",
   etymologyProcess:"hier（神聖な）＋ arch（支配する）→ 聖職者を上から順に並べると…？",
   etymologyConclusion:"hier（神聖な）＋ arch（支配する）＋ y（名詞）→ 位の高い者から低い者へ段々に並ぶしくみ＝（組織の）階層制，序列",
   why:"【なぜ】ギリシャ語 hierarkhia は「神聖なものを治めること」。もとは教会の聖職者の位の上下や、天使の9つの階級を指す言葉でした。そこから、上から下へ段々に位が並ぶ組織のしくみ全般を指すようになりました。\n【つながり】arch は monarch（君主）の「支配する」と同じ。hier は hieroglyph（神聖な文字＝象形文字）にも見られます。",
   relatedWords:[
     {word:"monarch",meaning:"君主",breakdown:"mono（1つ）＋ arch（支配する）→ ただ1人で国を治める人"},
     {word:"architect",meaning:"建築家",breakdown:"arch（主な）＋ tect（建てる）→ 建てる仕事の頭に立つ人"},
     {synonym:true,word:"rank",meaning:"地位，階級",breakdown:"1人1人の位。hierarchy はその位が並ぶしくみ全体"},
     {synonym:true,word:"level",meaning:"水準，段階",breakdown:"高さの段。hierarchy は人や役職の上下の段"}]},

  {id:2111,word:"autonomy",partOfSpeech:"名詞",meaning:"自治（権）；自主性",
   meanings:["名|自治（権）","名|自主性，自立"],
   pronunciation:"/ɔːˈtɑːnəmi/",part:212,
   example:"The region has long wanted more autonomy from the central government.",
   exampleJa:"その地域は長い間、中央政府からのより大きな自治権を求めてきた。",
   example2:"Our teacher gives us a lot of autonomy in choosing research topics.",
   exampleJa2:"先生は、研究テーマを選ぶことについて私たちに大きな自主性を認めてくれる。",
   etymologyProcess:"auto（自分）＋ nom（決まり）→ 自分たちで決まりを作ると…？",
   etymologyConclusion:"auto（自分）＋ nom（決まり）＋ y（名詞）→ 自分たちで決まりを作り、自分たちを治めること＝自治（権）",
   etymologyMore:["自分で決まりを決める力を1人に当てはめる→自主性，自立"],
   relatedWords:[
     {word:"autograph",meaning:"（有名人の）サイン",breakdown:"auto（自分）＋ graph（書く）→ 自分の手で書いた名前"},
     {word:"automobile",meaning:"自動車",breakdown:"auto（自分）＋ mob（動かす）→ 馬に引かれず自分で動く車"},
     {word:"economy",meaning:"経済",breakdown:"eco（家）＋ nom（切り盛りする）→ 家のやりくりが国の規模に"},
     {word:"astronomy",meaning:"天文学",breakdown:"astro（星）＋ nom（決まり）→ 星の動きの決まりを調べる学問"}]},

  {id:2112,word:"delegation",partOfSpeech:"名詞",meaning:"代表団，派遣団；（権限の）委任",
   meanings:["名|代表団，派遣団","名|（権限・仕事の）委任"],
   pronunciation:"/ˌdelɪˈɡeɪʃən/",part:212,
   example:"A delegation from China visited our school last week.",
   exampleJa:"先週、中国からの代表団が私たちの学校を訪れた。",
   example2:"Good leaders know that delegation of work helps the whole team grow.",
   exampleJa2:"よいリーダーは、仕事の委任がチーム全体を成長させることを知っている。",
   etymologyProcess:"de（離れて）＋ leg（任じる）→ 役目を任せて遠くへ送り出すと…？",
   etymologyConclusion:"de（離れて）＋ leg（任じる）＋ ation（名詞）→ 役目を任されて遠くへ送り出された人たち＝代表団，派遣団",
   etymologyMore:["任せて送り出すこと自体を指す→（権限・仕事の）委任"],
   relatedWords:[
     {word:"delegate",meaning:"代表者",breakdown:"de（離れて）＋ leg（任じる）＋ ate（動詞）→ 役目を託して送り出す人"},
     {word:"colleague",meaning:"同僚",breakdown:"col（共に）＋ leg（任じる）→ 同じ役目を共に任された仲間"},
     {word:"college",meaning:"大学",breakdown:"col（共に）＋ leg（任じる）→ 同じ学びを共に任された仲間の集まる場"},
     {synonym:true,word:"representative",meaning:"代表者",breakdown:"1人の代表。delegation は代表の人たちの集まり"}]},

  {id:2113,word:"congress",partOfSpeech:"名詞",meaning:"（米国の）議会；（専門家の）大会",
   meanings:["名|（米国の）議会","名|（専門家の）大会，会議"],
   pronunciation:"/ˈkɑːŋɡrəs/",part:212,
   example:"The new law must be approved by Congress before it takes effect.",
   exampleJa:"その新しい法律は、施行される前に米国議会で承認されなければならない。",
   example2:"Doctors from fifty countries attended the medical congress in Kyoto.",
   exampleJa2:"50か国の医師が、京都での医学の大会に出席した。",
   etymologyProcess:"con（共に）＋ gress（歩む）→ 各地から歩み寄って集まると…？",
   etymologyConclusion:"con（共に）＋ gress（歩む）→ 各地の代表が共に歩み寄って集まり、国の法律を決める場＝（米国の）議会",
   etymologyMore:["学者たちが各地から歩み寄って集まる→（専門家の）大会，会議"],
   relatedWords:[
     {word:"progress",meaning:"進歩する",breakdown:"pro（前へ）＋ gress（歩む）→ 前へ歩みを一段ずつ進める"},
     {word:"grade",meaning:"学年；等級",breakdown:"grad（歩み・段）→ 一歩ずつ上がっていく段"},
     {word:"graduate",meaning:"卒業する",breakdown:"grad（歩み・段）＋ ate（動詞）→ 最後の段を上りきる"},
     {synonym:true,word:"parliament",meaning:"議会（国会）",breakdown:"英国や日本などの議会。congress は米国の議会"}]},

  {id:2114,word:"census",partOfSpeech:"名詞",meaning:"国勢調査，人口調査",
   meanings:["名|国勢調査，人口調査"],
   pronunciation:"/ˈsensəs/",part:212,
   example:"Japan carries out a national census every five years.",
   exampleJa:"日本では5年ごとに国勢調査が行われる。",
   example2:"According to the census, the town's population has fallen by ten percent.",
   exampleJa2:"国勢調査によると、その町の人口は10パーセント減った。",
   etymologyProcess:"cens（見積もる）→ 国じゅうの人の数を見積もると…？",
   etymologyConclusion:"cens（見積もる）→ 国に住む人の数や暮らしを、国が一斉に見積もって調べること＝国勢調査，人口調査",
   relatedWords:[
     {word:"censor",meaning:"検閲官",breakdown:"cens（見積もる）＋ or（人）→ 中身を見積もって良し悪しを決める役人"},
     {synonym:true,word:"survey",meaning:"調査",breakdown:"全体を見渡して調べること。census は国が全員を数える"},
     {synonym:true,word:"population",meaning:"人口",breakdown:"住んでいる人の数。census はそれを数える調査"},
     {synonym:true,word:"count",meaning:"数える",breakdown:"1つずつ数えること。census は国じゅうを数える"}]},

  {id:2115,word:"monarch",partOfSpeech:"名詞",meaning:"君主，国王",
   meanings:["名|君主，国王，女王"],
   pronunciation:"/ˈmɑːnərk/",part:212,
   example:"The monarch appeared on the palace balcony to greet the crowd.",
   exampleJa:"君主は群衆にあいさつするため、宮殿のバルコニーに姿を見せた。",
   example2:"Britain's monarch has little real political power today.",
   exampleJa2:"今日、イギリスの君主には実際の政治的な力がほとんどない。",
   etymologyProcess:"mono（1つ）＋ arch（支配する）→ ただ1人で国を治める人は…？",
   etymologyConclusion:"mono（1つ）＋ arch（支配する）→ ただ1人で国全体を治める人＝君主，国王",
   relatedWords:[
     {word:"monologue",meaning:"独白，ひとり芝居",breakdown:"mono（1つ）＋ log（言葉）→ 1人だけで話す長いせりふ"},
     {word:"monarchy",meaning:"君主制",breakdown:"mono（1つ）＋ arch（支配する）＋ y（名詞）→ 君主1人が治めるしくみ"},
     {synonym:true,word:"king",meaning:"王",breakdown:"男の王。monarch は王も女王も含むかたい語"},
     {synonym:true,word:"emperor",meaning:"皇帝，天皇",breakdown:"多くの国や民族を治める君主。monarch より格が上"}]},

  {id:2116,word:"monopoly",partOfSpeech:"名詞",meaning:"（市場の）独占，独占権",
   meanings:["名|（市場の）独占，独占権","名|独占企業"],
   pronunciation:"/məˈnɑːpəli/",part:212,
   example:"The company had a monopoly on selling salt in that country.",
   exampleJa:"その会社は、その国で塩を売ることを独占していた。",
   example2:"Nobody has a monopoly on good ideas in our class.",
   exampleJa2:"私たちのクラスでは、よい考えをだれかが独占しているわけではない。",
   usage:["have a monopoly on 物（物を独占している）"],
   etymologyProcess:"mono（1つ）＋ poly（売る）→ 1社だけが売ってよいとなると…？",
   etymologyConclusion:"mono（1つ）＋ poly（売る）＋ y（名詞）→ 1社だけが売ることを許され、市場をひとり占めすること＝（市場の）独占，独占権",
   relatedWords:[
     {word:"monarch",meaning:"君主",breakdown:"mono（1つ）＋ arch（支配する）→ ただ1人で国を治める人"},
     {word:"monologue",meaning:"独白，ひとり芝居",breakdown:"mono（1つ）＋ log（言葉）→ 1人だけで話す長いせりふ"},
     {synonym:true,word:"own",meaning:"所有する",breakdown:"自分の物として持つこと。monopoly は1社だけが持つ"},
     {synonym:true,word:"market",meaning:"市場",breakdown:"売り買いの場。monopoly はそこを1社が占める状態"}]},

  {id:2117,word:"surplus",partOfSpeech:"名詞",meaning:"余剰（分），余り；黒字",
   meanings:["名|余剰（分），余り","名|（貿易などの）黒字","形|余った，余分の"],
   pronunciation:"/ˈsɜːrplʌs/",part:212,
   example:"The farmers sold their surplus rice to other countries.",
   exampleJa:"農家は、余剰分の米を他の国々に売った。",
   example2:"Last year the country had a large trade surplus.",
   exampleJa2:"昨年、その国は大きな貿易黒字を出した。",
   etymologyProcess:"sur（上を越えて）＋ plus（より多い）→ 必要な量を越えた分は…？",
   etymologyConclusion:"sur（上を越えて）＋ plus（より多い）→ 必要な量を越えて、さらに多く残った分＝余剰（分），余り",
   etymologyMore:["入るお金が出るお金を越えて残る→（貿易などの）黒字"],
   relatedWords:[
     {word:"plus",meaning:"～を加えて；プラス",breakdown:"plus（より多い）→ 足してより多くする記号「＋」"},
     {word:"survive",meaning:"生き残る",breakdown:"sur（上を越えて）＋ viv（生きる）→ 危機を越えて生き続ける"},
     {word:"surpass",meaning:"まさる，しのぐ",breakdown:"sur（上を越えて）＋ pass（通り抜ける）→ 相手の上を越えていく"},
     {synonym:true,word:"extra",meaning:"余分の",breakdown:"ふだんより多い分。surplus は使いきれず余った分"}]},

  {id:2118,word:"expertise",partOfSpeech:"名詞",meaning:"専門知識，専門技術",
   meanings:["名|専門知識，専門技術"],
   pronunciation:"/ˌekspərˈtiːz/",part:212,
   example:"We need someone with expertise in computer programming.",
   exampleJa:"私たちには、コンピュータプログラミングの専門知識を持つ人が必要だ。",
   example2:"Thanks to the coach's expertise, our team improved very quickly.",
   exampleJa2:"コーチの専門知識のおかげで、私たちのチームはとても早く上達した。",
   etymologyProcess:"ex（外へ）＋ peri（試す）→ 何度も試して身につけたものは…？",
   etymologyConclusion:"ex（外へ）＋ peri（試す）＋ ise（名詞）→ 何度も試して身につけた、その道の人ならではの知識＝専門知識，専門技術",
   spelling:"peri→per（i が落ちた）",
   relatedWords:[
     {word:"expert",meaning:"専門家",breakdown:"ex（外へ）＋ peri（試す）→ 多く試して詳しくなった人"},
     {word:"experience",meaning:"経験",breakdown:"ex（外へ）＋ peri（試す）＋ ence（名詞）→ 実際に試してみたこと"},
     {word:"experiment",meaning:"実験",breakdown:"ex（外へ）＋ peri（試す）→ 実際に試して確かめること"},
     {synonym:true,word:"skill",meaning:"技能，腕前",breakdown:"練習で身につけた腕前。expertise は専門家の深い知識"}]},

  {id:2119,word:"quota",partOfSpeech:"名詞",meaning:"割り当て（量），ノルマ",
   meanings:["名|割り当て（量），ノルマ","名|（受け入れの）定員，枠"],
   pronunciation:"/ˈkwoʊtə/",part:212,
   example:"Each fisherman has a strict quota for how many fish he can catch.",
   exampleJa:"漁師一人一人に、とってよい魚の数の厳しい割り当て量がある。",
   example2:"The salesman failed to meet his monthly quota again.",
   exampleJa2:"その営業マンは、またも月のノルマを達成できなかった。",
   etymologyProcess:"quot（いくつ）→ 一人いくつ分と決めると…？",
   etymologyConclusion:"quot（いくつ）→ 一人いくつ分と決めて、それぞれに振り分けた量＝割り当て（量），ノルマ",
   etymologyMore:["受け入れる人数をいくつと決める→（受け入れの）定員，枠"],
   relatedWords:[
     {word:"quote",meaning:"引用する",breakdown:"quot（いくつ）→ 何番目の章かを番号で示して引く"},
     {word:"quantity",meaning:"量",breakdown:"quant（どれだけ）＋ ity（名詞）→ どれだけあるかという量"},
     {synonym:true,word:"share",meaning:"分け前",breakdown:"分けて受け取る分。quota は上から決められた量"},
     {synonym:true,word:"task",meaning:"（課された）仕事",breakdown:"やるべき仕事。quota は達成すべき数や量"}]},

  {id:2120,word:"subordinate",partOfSpeech:"名詞",meaning:"部下；下位の，従属する",
   meanings:["名|部下","形|（to ～より）下位の，従属する"],
   pronunciation:"/səˈbɔːrdɪnət/",part:212,
   example:"The manager always treated her subordinates with respect.",
   exampleJa:"その部長は、いつも部下に敬意をもって接した。",
   example2:"In the army, a captain is subordinate to a major.",
   exampleJa2:"軍隊では、大尉は少佐より下位だ。",
   usage:["be subordinate to 人（人より下位にある）"],
   etymologyProcess:"sub（下で）＋ ord（順序）→ 順序の下のほうに置かれた人は…？",
   etymologyConclusion:"sub（下で）＋ ord（順序）＋ ate（形容詞）→ 順序の下のほうに位置づけられた人＝部下",
   relatedWords:[
     {word:"order",meaning:"順序；命令",breakdown:"ord（順序）→ きちんと並んでいる並び方"},
     {word:"ordinary",meaning:"ふつうの",breakdown:"ord（順序）＋ ary（形容詞）→ 決まった並びのとおりの"},
     {word:"coordinate",meaning:"調整する",breakdown:"co（共に）＋ ord（順序）＋ ate（動詞）→ 順序をそろえて共に動かす"},
     {word:"submit",meaning:"提出する",breakdown:"sub（下で）＋ mit（送る）→ 相手の下へ差し出す"}]},

  {id:2121,word:"warehouse",partOfSpeech:"名詞",meaning:"倉庫",
   meanings:["名|倉庫，（商品の）保管所"],
   pronunciation:"/ˈwerhaʊs/",part:213,
   example:"The goods are kept in a large warehouse near the port.",
   exampleJa:"その商品は、港の近くの大きな倉庫に保管されている。",
   example2:"My brother works part-time at an online shop's warehouse.",
   exampleJa2:"兄は、ネットショップの倉庫でアルバイトをしている。",
   etymologyProcess:"ware（見張る）＋ house（家）→ 大事な品を守っておく建物は…？",
   etymologyConclusion:"ware（見張る）＋ house（家）→ 売り物の品を大事に見張ってしまっておく建物＝倉庫",
   why:"【なぜ】ware は古英語 waru で「売り物，品物」のこと。「大切に見張っておく物」から来たと考えられています（はっきりしない部分もあります）。その品物（ware）をしまっておく家（house）なので「倉庫」になりました。\n【つながり】software（ソフトウェア）や kitchenware（台所用品）の ware も「品物」。aware（気づいている）とは遠い親戚です。",
   relatedWords:[
     {word:"aware",meaning:"気づいている",breakdown:"ware（見張る）→ 用心して見ていて、それに気づいている"},
     {word:"beware",meaning:"用心する",breakdown:"ware（見張る）→ 気をつけて見張っていろ、という呼びかけ"},
     {word:"housework",meaning:"家事",breakdown:"house（家）＋ work（仕事）→ 家の中でする仕事"},
     {word:"household",meaning:"家庭，世帯",breakdown:"house（家）＋ hold（持ち続ける）→ 1つの家で暮らしを保つ人々"}]},

  {id:2122,word:"peasant",partOfSpeech:"名詞",meaning:"（昔の）小作農，農民",
   meanings:["名|（昔の）小作農，農民"],
   pronunciation:"/ˈpezənt/",part:213,
   example:"In the Middle Ages, most peasants worked on land owned by lords.",
   exampleJa:"中世には、ほとんどの小作農が領主の持つ土地で働いた。",
   example2:"The novel tells the story of a poor peasant family in Russia.",
   exampleJa2:"その小説は、ロシアの貧しい農民一家の物語だ。",
   etymologyProcess:"pais（田舎）＋ ant（人）→ 田舎で土地を耕す人は…？",
   etymologyConclusion:"pais（田舎）＋ ant（人）→ 田舎に住み、地主の土地を耕して暮らす人＝（昔の）小作農，農民",
   spelling:"pais→peas（フランス語から英語に入って変化）",
   relatedWords:[
     {word:"servant",meaning:"召し使い",breakdown:"serv（仕える）＋ ant（人）→ 主人に仕える人"},
     {word:"immigrant",meaning:"移民",breakdown:"im（中へ）＋ migr（移る）＋ ant（人）→ よその国から移り住んだ人"},
     {synonym:true,word:"farmer",meaning:"農場主，農家",breakdown:"農業をする人全般。peasant は昔の貧しい小作の農民"},
     {synonym:true,word:"countryside",meaning:"田舎",breakdown:"町から離れた田園地帯。peasant が暮らした場所"}]},

  {id:2123,word:"correlation",partOfSpeech:"名詞",meaning:"相関（関係），相互関係",
   meanings:["名|相関（関係），相互関係"],
   pronunciation:"/ˌkɔːrəˈleɪʃən/",part:213,
   example:"There is a strong correlation between sleep and test scores.",
   exampleJa:"睡眠とテストの点数の間には、強い相関関係がある。",
   example2:"Scientists found no correlation between the two diseases.",
   exampleJa2:"科学者たちは、その2つの病気の間に相関関係を見つけなかった。",
   usage:["correlation between A and B（AとBの相関）"],
   etymologyProcess:"cor（共に）＋ re（後ろへ）＋ lat（運ぶ）→ 互いに結びついて動くと…？",
   etymologyConclusion:"cor（共に）＋ re（後ろへ）＋ lat（運ぶ）＋ ion（名詞）→ 一方が変わると他方も一緒に変わる結びつき＝相関（関係），相互関係",
   relatedWords:[
     {word:"relate",meaning:"関連づける",breakdown:"re（後ろへ）＋ lat（運ぶ）→ 2つのあいだに話を運んで結びつける"},
     {word:"relationship",meaning:"関係",breakdown:"re（後ろへ）＋ lat（運ぶ）＋ ship（名詞）→ 人と人との結びつき"},
     {word:"relative",meaning:"親類",breakdown:"re（後ろへ）＋ lat（運ぶ）＋ ive（～な性質の）→ 血のつながりで結ばれた人"},
     {word:"correspond",meaning:"一致する",breakdown:"cor（共に）＋ spond（誓う）→ 互いに答え合って合う"}]},

  {id:2124,word:"asymmetry",partOfSpeech:"名詞",meaning:"非対称；不均衡",
   meanings:["名|非対称","名|（力・情報などの）不均衡"],
   pronunciation:"/eɪˈsɪmətri/",part:213,
   example:"The asymmetry of the building makes it look modern and unique.",
   exampleJa:"その建物は非対称なので、現代的で独特に見える。",
   example2:"There is an asymmetry of information between sellers and buyers.",
   exampleJa2:"売り手と買い手の間には、情報の不均衡がある。",
   etymologyProcess:"sym（共に）＋ metr（測る）→ 左右が同じに測れないと…？",
   etymologyConclusion:"sym（共に）＋ metr（測る）＋ y（名詞）→ 先頭の a（～がない）で、左右の寸法がそろわない形＝非対称",
   etymologyMore:["形がそろわないことを力や量に広げる→（力・情報などの）不均衡"],
   relatedWords:[
     {word:"symmetry",meaning:"左右対称",breakdown:"sym（共に）＋ metr（測る）＋ y（名詞）→ 左右が同じ寸法に測れる形"},
     {word:"geometry",meaning:"幾何学",breakdown:"geo（大地）＋ metr（測る）→ 土地を測ることから生まれた学問"},
     {word:"sympathy",meaning:"同情",breakdown:"sym（共に）＋ path（感じる）→ 相手と同じ気持ちを感じる"},
     {word:"diameter",meaning:"直径",breakdown:"dia（間で）＋ metr（測る）→ 円を横切って測った長さ"}]},

  {id:2125,word:"disparity",partOfSpeech:"名詞",meaning:"（大きな）格差，相違",
   meanings:["名|（大きな）格差，相違"],
   pronunciation:"/dɪˈspærəti/",part:213,
   example:"There is a huge disparity between rich and poor in that country.",
   exampleJa:"その国では、豊かな人と貧しい人の間に大きな格差がある。",
   example2:"The disparity in test scores between the two classes surprised the teachers.",
   exampleJa2:"2つのクラスのテストの点数の相違に、先生たちは驚いた。",
   etymologyProcess:"dis（否定）＋ par（等しい）→ 等しくなく開きがあると…？",
   etymologyConclusion:"dis（否定）＋ par（等しい）＋ ity（名詞）→ 等しくなく、2つの間に大きな開きがあること＝（大きな）格差，相違",
   relatedWords:[
     {word:"pair",meaning:"1組",breakdown:"par（等しい）→ 等しいもの2つで1組"},
     {word:"compare",meaning:"比べる",breakdown:"com（共に）＋ par（等しい）→ 並べて等しいかを見くらべる"},
     {word:"disagree",meaning:"意見が合わない",breakdown:"dis（否定）＋ grat（心地よい）→ 心地よくそろわない"},
     {synonym:true,word:"gap",meaning:"すき間；隔たり",breakdown:"2つの間の開き。disparity は不公平な大きい差"}]},

  {id:2126,word:"divergence",partOfSpeech:"名詞",meaning:"（意見・進路などの）分岐，食い違い；逸脱",
   meanings:["名|（意見・進路などの）分岐，食い違い","名|（基準からの）逸脱"],
   pronunciation:"/daɪˈvɜːrdʒəns/",part:213,
   example:"There was a clear divergence of opinion among the committee members.",
   exampleJa:"委員の間には、はっきりとした意見の食い違いがあった。",
   example2:"Any divergence from the original plan must be approved by the teacher.",
   exampleJa2:"最初の計画からの逸脱は、すべて先生の承認を受けなければならない。",
   etymologyProcess:"di（離れて）＋ verg（傾く）→ 別々の向きへ傾いていくと…？",
   etymologyConclusion:"di（離れて）＋ verg（傾く）＋ ence（名詞）→ 1つの点から別々の向きへ傾いて離れていくこと＝（意見・進路などの）分岐，食い違い",
   etymologyMore:["決まった道から離れる方へ傾く→（基準からの）逸脱"],
   relatedWords:[
     {word:"diverge",meaning:"分かれる",breakdown:"di（離れて）＋ verg（傾く）→ 別々の向きへ傾いて分かれる"},
     {word:"converge",meaning:"1点に集まる",breakdown:"con（共に）＋ verg（傾く）→ みんなが同じ点へ傾いて集まる"},
     {synonym:true,word:"difference",meaning:"違い",breakdown:"違っていること全般。divergence は離れていく違い"},
     {synonym:true,word:"separate",meaning:"分ける；別々の",breakdown:"くっついていたものを分けること"}]},

  {id:2127,word:"clash",partOfSpeech:"名詞",meaning:"（意見・勢力の）衝突，ぶつかり合い；（予定の）重なり",
   meanings:["名|（意見・勢力の）衝突，ぶつかり合い","自|（with ～と）衝突する，対立する","自|（予定が）重なる"],
   pronunciation:"/klæʃ/",part:213,
   example:"There was a violent clash between the police and the protesters.",
   exampleJa:"警察とデモ参加者の間で、激しい衝突があった。",
   example2:"My piano lesson clashes with soccer practice on Friday.",
   exampleJa2:"金曜日は、ピアノのレッスンがサッカーの練習と重なっている。",
   usage:["clash with 人・物（～とぶつかる，～と重なる）"],
   etymologyProcess:"clash（ガチャンという音）→ 硬い物どうしがぶつかると…？",
   etymologyConclusion:"clash（ガチャンという音）→ 硬い物どうしがガチャンとぶつかり合うこと＝（意見・勢力の）衝突，ぶつかり合い",
   etymologyMore:["2つの予定が同じ時間にぶつかる→（予定が）重なる"],
   hook:"音から生まれた語。clap（パチッ）と crash（ガシャン）が混ざった響きと言われる。",
   relatedWords:[
     {synonym:true,word:"crash",meaning:"衝突する",breakdown:"これも音から生まれた語。激しくぶつかって壊れる"},
     {synonym:true,word:"conflict",meaning:"対立，衝突",breakdown:"長く続く対立。clash は一時的な激しいぶつかり合い"},
     {synonym:true,word:"collide",meaning:"衝突する",breakdown:"物どうしがぶつかること。clash は意見にも使う"},
     {synonym:true,word:"fight",meaning:"戦う；けんか",breakdown:"争うこと全般。clash はぶつかり合う瞬間"}]},

  {id:2128,word:"persecution",partOfSpeech:"名詞",meaning:"迫害",
   meanings:["名|（宗教・人種などによる）迫害"],
   pronunciation:"/ˌpɜːrsɪˈkjuːʃən/",part:213,
   example:"Many people fled the country to escape religious persecution.",
   exampleJa:"多くの人々が、宗教的な迫害を逃れるためにその国を離れた。",
   example2:"The persecution of the minority group lasted for many years.",
   exampleJa2:"その少数派の人々への迫害は、何年も続いた。",
   etymologyProcess:"per（通して）＋ secu（ついて行く）→ どこまでも追い回すと…？",
   etymologyConclusion:"per（通して）＋ secu（ついて行く）＋ tion（名詞）→ どこまでもしつこく追い回して苦しめること＝迫害",
   relatedWords:[
     {word:"second",meaning:"2番目の",breakdown:"sequ（ついて行く）→ 1番目のすぐ後についてくる"},
     {word:"sequence",meaning:"順序，連続",breakdown:"sequ（ついて行く）＋ ence（名詞）→ 次々についていく並び"},
     {word:"execute",meaning:"実行する",breakdown:"ex（外へ）＋ secu（ついて行く）→ 最後までついて行ってやり遂げる"},
     {word:"persecute",meaning:"迫害する",breakdown:"per（通して）＋ secu（ついて行く）→ しつこく追い回して苦しめる"}]},

  {id:2129,word:"genocide",partOfSpeech:"名詞",meaning:"（民族の）大量虐殺，ジェノサイド",
   meanings:["名|（民族の）大量虐殺，ジェノサイド"],
   pronunciation:"/ˈdʒenəsaɪd/",part:213,
   example:"The United Nations called the killing of the villagers genocide.",
   exampleJa:"国連は、その村人たちの殺害を大量虐殺と呼んだ。",
   example2:"We learned about the genocide in Rwanda in our history class.",
   exampleJa2:"私たちは歴史の授業で、ルワンダでの大量虐殺について学んだ。",
   etymologyProcess:"gen（生み出す）＋ cide（切る・殺す）→ 同じ生まれの人々を殺すと…？",
   etymologyConclusion:"gen（生み出す）＋ cide（切る・殺す）→ 同じ生まれの民族を丸ごと殺そうとすること＝（民族の）大量虐殺，ジェノサイド",
   why:"【なぜ】1944年、法律家のレムキンが、ギリシャ語 genos（生まれ，民族）とラテン語から来た -cide（殺すこと）を組み合わせて作った新しい語です。ナチスによるユダヤ人の大量殺害のように、ある民族をまるごと消し去ろうとする罪を名づけるためでした。\n【つながり】gen は gene（遺伝子）、cide は pesticide（殺虫剤）と同じです。",
   relatedWords:[
     {word:"gene",meaning:"遺伝子",breakdown:"gen（生み出す）→ 体の特徴を生み出すもとになるもの"},
     {word:"generation",meaning:"世代",breakdown:"gen（生み出す）＋ ation（名詞）→ 生み出されて続く一つの代"},
     {word:"pesticide",meaning:"殺虫剤",breakdown:"pest（害虫）＋ cide（切る・殺す）→ 害虫を殺す薬"},
     {synonym:true,word:"murder",meaning:"殺人",breakdown:"人を故意に殺すこと。genocide は民族全体をねらう"}]},

  {id:2130,word:"atrocity",partOfSpeech:"名詞",meaning:"残虐行為",
   meanings:["名|残虐行為，むごい仕打ち"],
   pronunciation:"/əˈtrɑːsəti/",part:213,
   example:"The attack on the village was an atrocity that shocked the world.",
   exampleJa:"その村への攻撃は、世界に衝撃を与えた残虐行為だった。",
   example2:"The museum shows photos of wartime atrocities so we never forget them.",
   exampleJa2:"その博物館は、私たちが決して忘れないよう、戦時中の残虐行為の写真を展示している。",
   etymologyProcess:"atroc（残忍な）＋ ity（名詞）→ むごたらしいふるまいは…？",
   etymologyConclusion:"atroc（残忍な）＋ ity（名詞）→ 人として許されない、むごたらしい行い＝残虐行為",
   relatedWords:[
     {word:"atrocious",meaning:"極悪な；ひどい",breakdown:"atroc（残忍な）＋ ious（形容詞）→ むごたらしいほどひどい"},
     {synonym:true,word:"cruelty",meaning:"残酷さ",breakdown:"人や動物を苦しめる性質。atrocity は実際のむごい行い"},
     {synonym:true,word:"violence",meaning:"暴力",breakdown:"力で傷つけること全般。atrocity はその極端な形"},
     {synonym:true,word:"crime",meaning:"犯罪",breakdown:"法を破る行い。atrocity は特にむごたらしいもの"}]},

  {id:2131,word:"bribe",partOfSpeech:"名詞",meaning:"賄賂；（賄賂で）買収する",
   meanings:["名|賄賂","他|（賄賂で）買収する"],
   pronunciation:"/braɪb/",part:214,
   example:"The politician was arrested for taking a bribe from a company.",
   exampleJa:"その政治家は、会社から賄賂を受け取ったとして逮捕された。",
   example2:"He tried to bribe the guard with money, but he failed.",
   exampleJa2:"彼はお金で守衛を買収しようとしたが、失敗した。",
   etymologyProcess:"bribe（パンのかけら）→ こっそり渡す不正な贈り物は…？",
   etymologyConclusion:"bribe（パンのかけら）→ 都合よく動いてもらうために、こっそり渡すお金や品＝賄賂",
   hook:"もとは古いフランス語で「物ごいに与えるパンのかけら」。その先の語源ははっきりしない。",
   relatedWords:[
     {word:"bribery",meaning:"贈収賄",breakdown:"bribe（パンのかけら）＋ ry（もの）→ 賄賂をやりとりする行い"},
     {synonym:true,word:"corruption",meaning:"汚職，腐敗",breakdown:"権力を持つ人が不正をすること。bribe はその道具"},
     {synonym:true,word:"gift",meaning:"贈り物",breakdown:"好意で渡す物。bribe は見返りを求める不正な物"},
     {synonym:true,word:"reward",meaning:"ほうび，報酬",breakdown:"したことへのお礼。bribe はさせるための先払い"}]},

  {id:2132,word:"culprit",partOfSpeech:"名詞",meaning:"犯人；（問題の）原因",
   meanings:["名|犯人，罪を犯した人","名|（問題の）原因，元凶"],
   pronunciation:"/ˈkʌlprɪt/",part:214,
   example:"The police finally caught the culprit who stole the paintings.",
   exampleJa:"警察はついに、絵を盗んだ犯人を捕まえた。",
   example2:"Too much sugar is often the real culprit behind bad teeth.",
   exampleJa2:"砂糖のとりすぎが、虫歯の本当の原因であることが多い。",
   etymologyProcess:"culp（罪）→ 罪があるとされる人は…？",
   etymologyConclusion:"culp（罪）→ 罪を犯したとして責められる人＝犯人",
   why:"【なぜ】昔のイギリスの法廷では、被告が無罪を主張すると、検察役が「cul. prit」と書きとめたとされます。culpable（有罪だ）と prest（証明する用意がある）を縮めた記録用の略語で、それがやがて「罪があるとされる人」を指す1語になりました。\n【つながり】culp は culpable（責められるべき）と同じ「罪」です。",
   etymologyMore:["悪いことを引き起こした張本人→（問題の）原因，元凶"],
   relatedWords:[
     {word:"culpable",meaning:"責められるべき",breakdown:"culp（罪）＋ able（～できる）→ 罪を責められて当然の"},
     {synonym:true,word:"criminal",meaning:"犯罪者",breakdown:"罪を犯した人全般。culprit は特定の事件の犯人"},
     {synonym:true,word:"thief",meaning:"泥棒",breakdown:"物を盗む人。culprit は罪を犯した人ならだれでも"},
     {synonym:true,word:"cause",meaning:"原因",breakdown:"何かを起こすもと。culprit は悪いことの原因"}]},

  {id:2133,word:"hostage",partOfSpeech:"名詞",meaning:"人質",
   meanings:["名|人質"],
   pronunciation:"/ˈhɑːstɪdʒ/",part:214,
   example:"The robbers held three bank workers hostage for five hours.",
   exampleJa:"強盗たちは、銀行員3人を5時間人質にとった。",
   example2:"All the hostages were safely released the next morning.",
   exampleJa2:"人質は全員、翌朝無事に解放された。",
   usage:["take 人 hostage（人を人質にとる）","hold 人 hostage（人を人質にしておく）"],
   etymologyProcess:"host（客をもてなす）＋ age（名詞）→ 客として預けられた人は…？",
   etymologyConclusion:"host（客をもてなす）＋ age（名詞）→ 約束の証として相手に預けられ、自由を奪われた人＝人質",
   why:"【なぜ】昔は約束を守る証として、王族などを相手の国に「客」として預けました。大切にもてなされる一方、約束が破られれば命が危ない身でした。hostage はこの「預かった客」を表す古いフランス語から来たとされますが、ラテン語 obses（人質）の影響もあり、はっきりしない部分があります。\n【つながり】host（主人役）も同じ仲間です。",
   relatedWords:[
     {word:"host",meaning:"（客をもてなす）主人役",breakdown:"host（客をもてなす）→ 客を迎えて世話をする主人役"},
     {word:"hospital",meaning:"病院",breakdown:"hosp（客をもてなす）＋ al（名詞）→ 旅人をもてなし世話した家"},
     {word:"hospitality",meaning:"おもてなし",breakdown:"hosp（客をもてなす）＋ ity（名詞）→ 客をもてなす心"},
     {synonym:true,word:"prisoner",meaning:"囚人，捕虜",breakdown:"とらわれている人。hostage は取引のために捕まった人"}]},

  {id:2134,word:"conspiracy",partOfSpeech:"名詞",meaning:"陰謀，共謀",
   meanings:["名|陰謀，共謀"],
   pronunciation:"/kənˈspɪrəsi/",part:214,
   example:"The men were found guilty of a conspiracy to kill the king.",
   exampleJa:"その男たちは、王を殺す陰謀を企てた罪で有罪となった。",
   example2:"Some people believe in strange conspiracy theories on the internet.",
   exampleJa2:"ネット上の奇妙な陰謀論を信じる人もいる。",
   etymologyProcess:"con（共に）＋ spir（息をする）→ 仲間と息を合わせてたくらむと…？",
   etymologyConclusion:"con（共に）＋ spir（息をする）＋ acy（名詞）→ 仲間と息を合わせ、ひそかに悪事をたくらむこと＝陰謀，共謀",
   why:"【なぜ】ラテン語 conspirare は「一緒に息をする」。顔を寄せ合って息をそろえる様子から「心を1つにする」、さらに「こっそり手を組んで悪いことをたくらむ」という意味に移りました。英語ではほとんど悪い意味で使われます。\n【つながり】spir は inspire（ひらめきを与える）や spirit（精神）と同じ「息」の仲間です。",
   relatedWords:[
     {word:"spirit",meaning:"精神，魂",breakdown:"spir（息をする）→ 体に息を通わせているもの"},
     {word:"inspire",meaning:"ひらめきを与える",breakdown:"in（中へ）＋ spir（息をする）→ 心の中へ息を吹きこむ"},
     {word:"expire",meaning:"期限が切れる",breakdown:"ex（外へ）＋ spir（息をする）→ 息を外へ吐ききって終わる"},
     {word:"conspire",meaning:"共謀する",breakdown:"con（共に）＋ spir（息をする）→ 息を合わせてたくらむ"}]},

  {id:2135,word:"peril",partOfSpeech:"名詞",meaning:"（差し迫った）大きな危険",
   meanings:["名|（差し迫った）大きな危険，危難"],
   pronunciation:"/ˈperəl/",part:214,
   example:"The sailors were in great peril when the storm hit.",
   exampleJa:"嵐が襲ったとき、船乗りたちは大きな危険にさらされていた。",
   example2:"Students who skip breakfast before exams do so at their peril.",
   exampleJa2:"試験前に朝食を抜く生徒は、大きな危険を承知でそうしているのだ。",
   usage:["in peril（危険にさらされて）","at one's peril（危険を覚悟で）"],
   etymologyProcess:"peri（試す）→ 身が試されるような場面は…？",
   etymologyConclusion:"peri（試す）→ 命や身の安全が試されるほどの差し迫った危うさ＝（差し迫った）大きな危険",
   why:"【なぜ】ラテン語 periculum は「試し，試み」。何かを試すときには失敗がつきものなので、「うまくいくか分からない危うさ」へ意味が移り、やがて「命にかかわるほどの危険」を表すようになりました。\n【つながり】experience（経験）や experiment（実験）も同じ「試す」の仲間。実際に試してみるのが経験、危うさの方に注目したのが peril です。",
   relatedWords:[
     {word:"experience",meaning:"経験",breakdown:"ex（外へ）＋ peri（試す）＋ ence（名詞）→ 実際に試してみたこと"},
     {word:"experiment",meaning:"実験",breakdown:"ex（外へ）＋ peri（試す）→ 実際に試して確かめること"},
     {word:"expert",meaning:"専門家",breakdown:"ex（外へ）＋ peri（試す）→ 多く試して詳しくなった人"},
     {synonym:true,word:"danger",meaning:"危険",breakdown:"危ないこと全般。peril は命にかかわる差し迫った危険"}]},

  {id:2136,word:"pitfall",partOfSpeech:"名詞",meaning:"（思わぬ）落とし穴",
   meanings:["名|（思わぬ）落とし穴，隠れた危険"],
   pronunciation:"/ˈpɪtfɔːl/",part:214,
   example:"This guide explains common pitfalls to avoid when learning English.",
   exampleJa:"このガイドは、英語学習で避けるべきよくある落とし穴を説明している。",
   example2:"One pitfall of online shopping is buying things you don't need.",
   exampleJa2:"ネットショッピングの落とし穴の1つは、必要のない物を買ってしまうことだ。",
   etymologyProcess:"pit（穴）＋ fall（落ちる）→ 気づかずに落ちる穴は…？",
   etymologyConclusion:"pit（穴）＋ fall（落ちる）→ 気づかずに落ちてしまう、隠れた穴＝（思わぬ）落とし穴",
   relatedWords:[
     {word:"fall",meaning:"落ちる",breakdown:"fall（落ちる）→ 上から下へ落ちていく"},
     {word:"waterfall",meaning:"滝",breakdown:"water（水）＋ fall（落ちる）→ 水が高い所から落ちる所"},
     {word:"pit",meaning:"（地面の）穴",breakdown:"pit（穴）→ 地面に掘られた深い穴"},
     {synonym:true,word:"trap",meaning:"わな",breakdown:"わざと仕掛けたわな。pitfall は気づきにくい危険"}]},

  {id:2137,word:"itinerary",partOfSpeech:"名詞",meaning:"旅程（表），旅行計画",
   meanings:["名|旅程（表），旅行計画"],
   pronunciation:"/aɪˈtɪnəreri/",part:214,
   example:"Our itinerary includes three days in Kyoto and two in Nara.",
   exampleJa:"私たちの旅程には、京都での3日間と奈良での2日間が含まれている。",
   example2:"The teacher handed out the itinerary for the school trip.",
   exampleJa2:"先生は、修学旅行の旅程表を配った。",
   etymologyProcess:"itiner（旅路）＋ ary（もの）→ 旅の道のりを書きならべると…？",
   etymologyConclusion:"itiner（旅路）＋ ary（もの）→ 旅でたどる道のりと予定を書きならべたもの＝旅程（表），旅行計画",
   relatedWords:[
     {word:"exit",meaning:"出口",breakdown:"ex（外へ）＋ it（行く）→ 外へ出て行く所。itiner も同じ「行く」から"},
     {word:"initial",meaning:"最初の",breakdown:"in（中へ）＋ it（行く）＋ al（形容詞）→ いちばん先に中へ入る"},
     {synonym:true,word:"schedule",meaning:"予定（表）",breakdown:"時間ごとの予定。itinerary は旅の道順と予定"},
     {synonym:true,word:"route",meaning:"道筋，ルート",breakdown:"たどる道。itinerary はそこに日程も加わる"}]},

  {id:2138,word:"upheaval",partOfSpeech:"名詞",meaning:"（社会の）大変動，激変",
   meanings:["名|（社会の）大変動，激変"],
   pronunciation:"/ʌpˈhiːvəl/",part:214,
   example:"The war caused a great upheaval in people's lives.",
   exampleJa:"その戦争は、人々の生活に大変動をもたらした。",
   example2:"Moving to a new school can be a big upheaval for children.",
   exampleJa2:"転校は、子どもにとって生活の大きな激変になりうる。",
   etymologyProcess:"up（上へ）＋ heav（持ち上げる）→ 足もとが持ち上がると…？",
   etymologyConclusion:"up（上へ）＋ heav（持ち上げる）＋ al（名詞）→ 地面が持ち上がるように、世の中がひっくり返ること＝（社会の）大変動，激変",
   relatedWords:[
     {word:"heavy",meaning:"重い",breakdown:"heav（持ち上げる）＋ y（形容詞）→ 持ち上げるのに力がいる"},
     {word:"upgrade",meaning:"格上げする",breakdown:"up（上へ）＋ grad（歩み・段）→ 一段上へ引き上げる"},
     {word:"upset",meaning:"動揺させる",breakdown:"up（上へ）＋ set（置く）→ ひっくり返して心を乱す"},
     {synonym:true,word:"revolution",meaning:"革命",breakdown:"社会のしくみがひっくり返ること。upheaval は大変動全般"}]},

  {id:2139,word:"commencement",partOfSpeech:"名詞",meaning:"（正式な）開始；（米国の）卒業式",
   meanings:["名|（正式な）開始","名|（米国の大学などの）卒業式"],
   pronunciation:"/kəˈmensmənt/",part:214,
   example:"The commencement of the ceremony was delayed because of the rain.",
   exampleJa:"雨のため、式典の開始が遅れた。",
   example2:"My cousin gave a speech at her college commencement in June.",
   exampleJa2:"いとこは6月の大学の卒業式でスピーチをした。",
   etymologyProcess:"com（すっかり）＋ in（中へ）＋ it（行く）→ 物事の中へ入っていくと…？",
   etymologyConclusion:"com（すっかり）＋ in（中へ）＋ it（行く）＋ ment（名詞）→ 新しい物事の中へすっかり入っていくこと＝（正式な）開始",
   spelling:"in＋it→menc（フランス語を通って変化）",
   etymologyMore:["学生が社会へ入っていく始まりの日→（米国の大学などの）卒業式"],
   relatedWords:[
     {word:"exit",meaning:"出口",breakdown:"ex（外へ）＋ it（行く）→ 外へ出て行く所"},
     {word:"initial",meaning:"最初の",breakdown:"in（中へ）＋ it（行く）＋ al（形容詞）→ いちばん先に中へ入る"},
     {word:"commence",meaning:"始める，始まる",breakdown:"com（すっかり）＋ in（中へ）＋ it（行く）→ 物事の中へ入っていく"},
     {synonym:true,word:"begin",meaning:"始める",breakdown:"ふつうの「始める」。commence はかたい場面で使う"}]},

  {id:2140,word:"threshold",partOfSpeech:"名詞",meaning:"敷居，戸口；（新しい段階の）入り口",
   meanings:["名|敷居，戸口","名|（新しい段階の）始まり，入り口","名|（反応が起こる）境目，限界値"],
   pronunciation:"/ˈθreʃhoʊld/",part:214,
   example:"She stopped at the threshold and looked back at her old room.",
   exampleJa:"彼女は敷居のところで立ち止まり、自分の古い部屋を振り返った。",
   example2:"Scientists are on the threshold of a major discovery.",
   exampleJa2:"科学者たちは、大発見の入り口に立っている。",
   usage:["on the threshold of 事（～の始まりに）"],
   etymologyProcess:"thresh（踏む）→ 家に入るとき足で踏む所は…？",
   etymologyConclusion:"thresh（踏む）→ 部屋に出入りするとき足で踏む、戸口の横木＝敷居，戸口",
   etymologyMore:["敷居をまたぐと新しい部屋に入る→（新しい段階の）始まり，入り口","ここを越えると様子が変わる線→（反応が起こる）境目，限界値"],
   hook:"語源ははっきりしない。前半は thresh（足で踏む）と考えられ、後半の意味は分かっていない。",
   relatedWords:[
     {word:"thresh",meaning:"脱穀する",breakdown:"thresh（踏む）→ 穀物を足で踏んで実を落とす"},
     {synonym:true,word:"doorway",meaning:"戸口，出入り口",breakdown:"ドアのある出入り口。threshold はその床の横木"},
     {synonym:true,word:"beginning",meaning:"始まり",breakdown:"ふつうの「始まり」。threshold は次の段階の入り口"},
     {synonym:true,word:"limit",meaning:"限界",breakdown:"それ以上いけない線。threshold は越えると変わる線"}]},

  {id:2141,word:"onset",partOfSpeech:"名詞",meaning:"（病気・悪いことの）始まり，到来",
   meanings:["名|（病気・悪いことの）始まり，到来"],
   pronunciation:"/ˈɑːnset/",part:215,
   example:"The onset of winter brought heavy snow to the village.",
   exampleJa:"冬の到来とともに、村に大雪が降った。",
   example2:"Early treatment can delay the onset of the disease.",
   exampleJa2:"早めの治療で、その病気の始まりを遅らせることができる。",
   etymologyProcess:"set（置く）→ 身の上に何かが降りかかり出すと…？",
   etymologyConclusion:"set（置く）→ on（～に向かって）と組んで「襲いかかる」、そこから悪い事の始まり＝（病気・悪いことの）始まり，到来",
   relatedWords:[
     {word:"set",meaning:"置く",breakdown:"set（置く）→ 決まった所にきちんと据える"},
     {word:"sunset",meaning:"日の入り",breakdown:"sun（太陽）＋ set（置く）→ 太陽が地平線に下りて据わる"},
     {word:"upset",meaning:"動揺させる",breakdown:"up（上へ）＋ set（置く）→ ひっくり返して心を乱す"},
     {synonym:true,word:"start",meaning:"始まり；始める",breakdown:"ふつうの「始まり」。onset は病気など悪いことに使う"}]},

  {id:2142,word:"momentum",partOfSpeech:"名詞",meaning:"勢い，はずみ；運動量",
   meanings:["名|勢い，はずみ","名|（物理の）運動量"],
   pronunciation:"/moʊˈmentəm/",part:215,
   example:"Our team gained momentum after scoring the first goal.",
   exampleJa:"最初のゴールを決めてから、私たちのチームは勢いに乗った。",
   example2:"The campaign lost momentum when its leader became ill.",
   exampleJa2:"リーダーが病気になると、その運動は勢いを失った。",
   etymologyProcess:"mov（動かす）＋ ment（名詞）→ 前へ前へと動かし続ける力は…？",
   etymologyConclusion:"mov（動かす）＋ ment（名詞）→ 一度動き出した物事を、前へ前へと動かし続ける力＝勢い，はずみ",
   spelling:"mov→mo（v が消えて縮まった）",
   etymologyMore:["動く物が持つ勢いを数で表す→（物理の）運動量"],
   relatedWords:[
     {word:"moment",meaning:"瞬間",breakdown:"mov（動かす）＋ ment（名詞）→ 針がわずかに動くほどの短い時"},
     {word:"motion",meaning:"動き",breakdown:"mot（動かす）＋ ion（名詞）→ 動いているということ"},
     {word:"remove",meaning:"取り除く",breakdown:"re（後ろへ）＋ mov（動かす）→ 元の場所から動かしてどける"},
     {word:"motor",meaning:"モーター，発動機",breakdown:"mot（動かす）＋ or（もの）→ 力を生んで物を動かし続ける装置"}]},

  {id:2143,word:"deterrent",partOfSpeech:"名詞",meaning:"抑止するもの，抑止力",
   meanings:["名|抑止するもの，抑止力","形|抑止する，思いとどまらせる"],
   pronunciation:"/dɪˈtɜːrənt/",part:215,
   example:"Security cameras act as a deterrent to shoplifting.",
   exampleJa:"防犯カメラは、万引きを抑止するものとして働く。",
   example2:"Some people believe that nuclear weapons are a deterrent against war.",
   exampleJa2:"核兵器は戦争の抑止力になると考える人もいる。",
   usage:["a deterrent to 事（事を抑止するもの）"],
   etymologyProcess:"de（離れて）＋ terr（恐れさせる）→ 怖がらせて遠ざけるものは…？",
   etymologyConclusion:"de（離れて）＋ terr（恐れさせる）＋ ent（もの）→ 恐れさせて悪い行いから遠ざけるもの＝抑止するもの，抑止力",
   relatedWords:[
     {word:"terrible",meaning:"ひどい",breakdown:"terr（恐れさせる）＋ ible（できる）→ 恐れさせるほどひどい"},
     {word:"terror",meaning:"恐怖",breakdown:"terr（恐れさせる）→ 心が凍るような恐れ"},
     {word:"terrify",meaning:"怖がらせる",breakdown:"terr（恐れさせる）＋ ify（する）→ ひどく怖がらせる"},
     {word:"deter",meaning:"思いとどまらせる",breakdown:"de（離れて）＋ terr（恐れさせる）→ 怖がらせて手を引かせる"}]},

  {id:2144,word:"geometry",partOfSpeech:"名詞",meaning:"幾何学",
   meanings:["名|幾何学","名|（物の）形状，配置"],
   pronunciation:"/dʒiˈɑːmətri/",part:215,
   example:"In geometry class, we learned how to find the area of circles.",
   exampleJa:"幾何学の授業で、私たちは円の面積の求め方を習った。",
   example2:"The ancient Egyptians used geometry to build the pyramids.",
   exampleJa2:"古代エジプト人は、ピラミッドを建てるのに幾何学を使った。",
   etymologyProcess:"geo（大地）＋ metr（測る）→ 土地を測る技術から生まれた学問は…？",
   etymologyConclusion:"geo（大地）＋ metr（測る）＋ y（名詞）→ 土地を測る技術から生まれた、図形を調べる学問＝幾何学",
   relatedWords:[
     {word:"geography",meaning:"地理（学）",breakdown:"geo（大地）＋ graph（書く）→ 大地の様子を書き表す学問"},
     {word:"symmetry",meaning:"左右対称",breakdown:"sym（共に）＋ metr（測る）＋ y（名詞）→ 左右が同じ寸法に測れる形"},
     {word:"diameter",meaning:"直径",breakdown:"dia（間で）＋ metr（測る）→ 円を横切って測った長さ"},
     {synonym:true,word:"math",meaning:"数学",breakdown:"数や図形を扱う学問全体。geometry はその図形の分野"}]},

  {id:2145,word:"anthropologist",partOfSpeech:"名詞",meaning:"人類学者",
   meanings:["名|人類学者"],
   pronunciation:"/ˌænθrəˈpɑːlədʒɪst/",part:215,
   example:"The anthropologist lived with the tribe for two years.",
   exampleJa:"その人類学者は、その部族と2年間生活を共にした。",
   example2:"She studied hard at university to become an anthropologist.",
   exampleJa2:"彼女は人類学者になるために、大学で懸命に学んだ。",
   etymologyProcess:"anthrop（人間）＋ log（学問）＋ ist（人）→ 人間そのものを研究する人は…？",
   etymologyConclusion:"anthrop（人間）＋ log（学問）＋ ist（人）→ 人間の文化や暮らしを学問として研究する人＝人類学者",
   relatedWords:[
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）→ 生き物のしくみを調べる学問"},
     {word:"psychologist",meaning:"心理学者",breakdown:"psych（心）＋ log（学問）＋ ist（人）→ 心の働きを研究する人"},
     {word:"cardiologist",meaning:"心臓専門医",breakdown:"cardi（心臓）＋ log（学問）＋ ist（人）→ 心臓を専門に研究し治す医師"},
     {word:"philanthropist",meaning:"慈善家",breakdown:"phil（愛する）＋ anthrop（人間）＋ ist（人）→ 人々を愛して助ける人"}]},

  {id:2146,word:"internship",partOfSpeech:"名詞",meaning:"実務研修，インターンシップ",
   meanings:["名|実務研修，インターンシップ"],
   pronunciation:"/ˈɪntɜːrnʃɪp/",part:215,
   example:"My sister did an internship at a TV station last summer.",
   exampleJa:"姉は去年の夏、テレビ局で実務研修をした。",
   example2:"Many students apply for internships to gain work experience.",
   exampleJa2:"多くの学生が、仕事の経験を積むためにインターンシップに応募する。",
   etymologyProcess:"intern（内側の）＋ ship（名詞）→ 会社の内側に入って学ぶ期間は…？",
   etymologyConclusion:"intern（内側の）＋ ship（名詞）→ 会社などの内側に入り、実際に働きながら学ぶ期間＝実務研修，インターンシップ",
   relatedWords:[
     {word:"internal",meaning:"内部の",breakdown:"intern（内側の）＋ al（形容詞）→ 中のほうの"},
     {synonym:true,word:"inside",meaning:"内側；内部に",breakdown:"中のほう。intern はもと組織の内側で働く人"},
     {word:"intern",meaning:"実習生",breakdown:"intern（内側の）→ 組織の内側に入って学ぶ人"},
     {synonym:true,word:"training",meaning:"訓練，研修",breakdown:"技を身につける練習全般。internship は職場に入って学ぶ"}]},

  {id:2147,word:"paradigm",partOfSpeech:"名詞",meaning:"（ものの見方の）枠組み，パラダイム；模範",
   meanings:["名|（ものの見方の）枠組み，パラダイム","名|模範，典型例"],
   pronunciation:"/ˈpærədaɪm/",part:215,
   example:"The internet created a new paradigm for how people communicate.",
   exampleJa:"インターネットは、人々のコミュニケーションの新しい枠組みを生み出した。",
   example2:"This school is a paradigm of good education in our city.",
   exampleJa2:"この学校は、私たちの市におけるよい教育の模範だ。",
   etymologyProcess:"para（そばで）＋ digm（見せる）→ そばに並べて見せる手本は…？",
   etymologyConclusion:"para（そばで）＋ digm（見せる）→ 並べて見せる手本から、物事を考えるときの型＝（ものの見方の）枠組み，パラダイム",
   why:"【なぜ】ギリシャ語 paradeigma は「そばに並べて見せるもの」、つまりお手本です。長く「模範，典型例」の意味で使われていましたが、1962年に科学史家クーンが、ある時代の科学者たちが共有する「ものの見方の枠組み」をこう呼び、今ではこちらの意味が中心になりました。\n【つながり】para は paragraph（段落）の「そばで」と同じです。",
   etymologyMore:["並べて見せた手本そのもの→模範，典型例"],
   relatedWords:[
     {word:"paragraph",meaning:"段落",breakdown:"para（そばで）＋ graph（書く）→ 区切りのそばに印を書いた"},
     {word:"parallel",meaning:"平行の",breakdown:"para（そばで）＋ allel（互いに）→ 互いのそばを並んで走る"},
     {synonym:true,word:"model",meaning:"模型；手本",breakdown:"まねるための手本。paradigm は考え方全体の型"},
     {synonym:true,word:"pattern",meaning:"型，パターン",breakdown:"くり返し現れる形。paradigm は時代の考え方の型"}]},

  {id:2148,word:"altruism",partOfSpeech:"名詞",meaning:"利他主義，利他的な行い",
   meanings:["名|利他主義，利他的な行い"],
   pronunciation:"/ˈæltruɪzəm/",part:215,
   example:"Donating blood to strangers is a simple example of altruism.",
   exampleJa:"見知らぬ人のために献血することは、利他主義の身近な例だ。",
   example2:"Scientists study altruism in animals such as dolphins and monkeys.",
   exampleJa2:"科学者たちは、イルカやサルなどの動物に見られる利他的な行いを研究している。",
   etymologyProcess:"alter（別の）＋ ism（主義）→ 自分より他人を大切にする考えは…？",
   etymologyConclusion:"alter（別の）＋ ism（主義）→ 自分より、他の人の幸せを大切にする考え方＝利他主義，利他的な行い",
   spelling:"alter→altru（イタリア語 altrui「他人」を通って変化）",
   relatedWords:[
     {word:"alter",meaning:"変える",breakdown:"alter（別の）→ 今のものを別のものにしてしまう"},
     {word:"alternative",meaning:"代わりの（もの）",breakdown:"alter（別の）＋ ive（形容詞）→ もう一つ別の選べるもの"},
     {word:"alternate",meaning:"交互に起こる",breakdown:"alter（別の）＋ ate（動詞）→ 別のものと代わる代わる入れかわる"},
     {synonym:true,word:"kindness",meaning:"親切",breakdown:"やさしくすること。altruism は見返りを求めない考え方"}]},

  {id:2149,word:"claustrophobia",partOfSpeech:"名詞",meaning:"閉所恐怖症",
   meanings:["名|閉所恐怖症"],
   pronunciation:"/ˌklɔːstrəˈfoʊbiə/",part:215,
   example:"Because of her claustrophobia, she never takes the elevator.",
   exampleJa:"閉所恐怖症なので、彼女は決してエレベーターに乗らない。",
   example2:"Small rooms without windows can cause claustrophobia in some people.",
   exampleJa2:"窓のない狭い部屋は、人によっては閉所恐怖症を引き起こす。",
   etymologyProcess:"claus（閉じる）＋ phob（恐れ）→ 閉じた狭い所を怖がると…？",
   etymologyConclusion:"claus（閉じる）＋ phob（恐れ）→ 閉ざされた狭い場所を、ひどく怖がること＝閉所恐怖症",
   relatedWords:[
     {word:"close",meaning:"閉じる",breakdown:"clos（閉じる）→ 開いていた口をぴたりと閉じる"},
     {word:"closet",meaning:"クローゼット，物置",breakdown:"clos（閉じる）＋ et（小さい）→ 閉じられた小部屋"},
     {word:"phobia",meaning:"（病的な）恐怖症",breakdown:"phob（恐れ）→ 特定の物を異常に怖がる症状"},
     {synonym:true,word:"fear",meaning:"恐れ",breakdown:"ふつうの「恐れ」。phobia は理屈を超えた強い恐れ"}]},

  {id:2150,word:"Antarctic",partOfSpeech:"名詞",meaning:"南極（地方）；南極の",
   meanings:["名|（the ～）南極（地方）","形|南極の"],
   pronunciation:"/ænˈtɑːrktɪk/",part:215,
   example:"Scientists from many countries do research in the Antarctic every year.",
   exampleJa:"毎年、多くの国の科学者が南極で研究を行っている。",
   example2:"The Antarctic Ocean is home to many whales and penguins.",
   exampleJa2:"南極海には、たくさんのクジラやペンギンがすんでいる。",
   etymologyProcess:"anti（逆に）＋ arct（熊）→ 北の空の熊の星座の反対側は…？",
   etymologyConclusion:"anti（逆に）＋ arct（熊）＋ ic（形容詞）→ 北の空の大熊座とは反対側にある地方＝南極（地方）",
   spelling:"anti→ant（i が消えた）",
   why:"【なぜ】ギリシャ語 arktos は「熊」。北の空に見える大熊座・小熊座から、arktikos は「熊の方の」＝「北の」を意味しました。その反対側（anti）なので、antarktikos は「北の反対」＝南極を表すようになりました。\n【つながり】Arctic（北極の）も同じ「熊」から。Antarctica（南極大陸）もこの仲間です。",
   relatedWords:[
     {word:"Arctic",meaning:"北極（の）",breakdown:"arct（熊）＋ ic（形容詞）→ 大熊座が見える北の方の"},
     {word:"antibiotic",meaning:"抗生物質",breakdown:"anti（逆に）＋ bio（生命）＋ ic（形容詞）→ 細菌の命に逆らう薬"},
     {synonym:true,word:"pole",meaning:"（地球の）極",breakdown:"北極・南極の「極」。the South Pole が南極点"},
     {synonym:true,word:"continent",meaning:"大陸",breakdown:"大きな陸地。南極は氷におおわれた大陸"}]},
