  {id:1951,word:"startle",partOfSpeech:"他動詞",meaning:"（不意に）びっくりさせる，ぎょっとさせる",
   meanings:["他|（不意に）びっくりさせる，ぎょっとさせる","名|（ぎょっとする）驚き"],
   pronunciation:"/ˈstɑːrtl/",part:196,
   example:"The sudden noise startled the cat, and it ran away.",
   exampleJa:"突然の物音が猫をびっくりさせ、猫は逃げ出した。",
   example2:"I was startled when my name was called in class.",
   exampleJa2:"授業中に名前を呼ばれて、私はぎょっとした。",
   etymologyProcess:"start（びくっと動く）→ 体が思わずびくっと跳ねると…？",
   etymologyConclusion:"start（びくっと動く）→ 不意をついて体をびくっと跳ね上がらせる＝（不意に）びっくりさせる",
   hook:"be startled by ～（～にぎょっとする）の受け身の形でよく使う。",
   relatedWords:[
     {word:"start",meaning:"始める；はっとする",breakdown:"start（びくっと動く）→ 急に動き出す。そこから「始める」"},
     {word:"startling",meaning:"びっくりするような",breakdown:"start（びくっと動く）＋ ing（～している）→ 思わず跳び上がるほどの"},
     {synonym:true,word:"surprise",meaning:"驚かせる",breakdown:"驚かせる全般。startle は不意をついてぎょっとさせる"},
     {synonym:true,word:"shock",meaning:"ぎょっとさせる，衝撃を与える",breakdown:"強い衝撃を与える。startle は一瞬びくっとさせる"}]},

  {id:1952,word:"thrill",partOfSpeech:"他動詞",meaning:"（喜び・興奮で）ぞくぞくさせる，わくわくさせる",
   meanings:["他|（喜び・興奮で）ぞくぞくさせる，わくわくさせる","名|スリル，ぞくぞくする感じ"],
   pronunciation:"/θrɪl/",part:196,
   example:"The fans were thrilled when their team scored in the last minute.",
   exampleJa:"最後の1分でチームが得点すると、ファンは喜びでぞくぞくした。",
   example2:"Riding the roller coaster gave my little brother a real thrill.",
   exampleJa2:"ジェットコースターに乗って、弟は本物のスリルを味わった。",
   etymologyProcess:"thrill（突き通す）→ 何かが体を突き抜けると…？",
   etymologyConclusion:"thrill（突き通す）→ 体を突き抜けるような感覚を走らせる＝（喜び・興奮で）ぞくぞくさせる",
   hook:"古い英語で「穴をあける」。nostril（鼻の穴）の tril と同じで、感動が体を突き抜ける。",
   relatedWords:[
     {word:"thriller",meaning:"スリラー（小説・映画）",breakdown:"thrill（突き通す）＋ er（もの）→ 背すじをぞくぞくが突き抜ける作品"},
     {word:"through",meaning:"～を通り抜けて",breakdown:"through（通して）→ 端から端まで突き抜ける。thrill の遠い親戚"},
     {word:"nostril",meaning:"鼻の穴",breakdown:"nos（鼻）＋ tril（突き通す）→ 鼻にあいた穴"},
     {synonym:true,word:"excite",meaning:"興奮させる",breakdown:"気持ちをかき立てる。thrill は体がぞくっとするほど強い"}]},

  {id:1953,word:"humiliate",partOfSpeech:"他動詞",meaning:"（人前で）恥をかかせる，屈辱を与える",
   meanings:["他|（人前で）恥をかかせる，屈辱を与える"],
   pronunciation:"/hjuːˈmɪlieɪt/",part:196,
   example:"The coach never tries to humiliate players in front of others.",
   exampleJa:"そのコーチは決して、人前で選手に恥をかかせようとはしない。",
   example2:"I felt humiliated when I fell over on the stage.",
   exampleJa2:"舞台で転んでしまい、私は屈辱を感じた。",
   etymologyProcess:"humil（低い）＋ ate（～にする）→ 相手を低い所へ落とすと…？",
   etymologyConclusion:"humil（低い）＋ ate（～にする）→ 人を地面まで低く落として面目を失わせる＝（人前で）恥をかかせる",
   relatedWords:[
     {word:"humble",meaning:"謙虚な；身分の低い",breakdown:"humil（低い）→ 自分を低いところに置く，おごらない"},
     {word:"humility",meaning:"謙虚さ",breakdown:"humil（低い）＋ ity（名詞）→ 自分を低く保つ心"},
     {word:"humiliation",meaning:"屈辱",breakdown:"humil（低い）＋ ation（名詞）→ 低く落とされてみじめなこと"},
     {synonym:true,word:"embarrass",meaning:"恥ずかしい思いをさせる",breakdown:"気まずくさせる。humiliate は誇りまで深く傷つける"}]},

  {id:1954,word:"adore",partOfSpeech:"他動詞",meaning:"心から愛する，熱愛する；大好きである",
   meanings:["他|心から愛する，熱愛する","他|（物・事が）大好きである"],
   pronunciation:"/əˈdɔːr/",part:196,
   example:"The little girl adores her grandfather and follows him everywhere.",
   exampleJa:"その少女はおじいさんを心から愛していて、どこへでもついて行く。",
   example2:"My sister adores Korean dramas and watches them every night.",
   exampleJa2:"姉は韓国ドラマが大好きで、毎晩見ている。",
   etymologyProcess:"ad（～へ）＋ ora（祈る）→ 相手に向かって祈るほど…？",
   etymologyConclusion:"ad（～へ）＋ ora（祈る）→ 神に祈るように相手を大切に思う＝心から愛する",
   why:"【なぜ】ラテン語 adorare は「～に向かって祈る」で、もとは神をあがめる言葉でした。祈りをささげるほど大切に思う気持ちが、やがて人への深い愛情にも使われるようになり、今では口語で「～が大好き」と軽くも言います。\n【つながり】adorable（かわいくてたまらない）は「あがめたくなるほど愛らしい」。oracle（神のお告げ）も同じ「祈る・語る」の仲間です。",
   spelling:"ora→or（語尾の a が落ちた）",
   relatedWords:[
     {word:"adorable",meaning:"とてもかわいい",breakdown:"ad（～へ）＋ ora（祈る）＋ able（できる）→ 大事にしたくなるほど愛らしい"},
     {word:"oracle",meaning:"神のお告げ",breakdown:"ora（祈る）＋ cle（もの）→ 祈りに答えて告げられる言葉"},
     {synonym:true,word:"love",meaning:"愛する",breakdown:"愛する全般。adore はあがめるほど強く愛する"},
     {synonym:true,word:"like",meaning:"好きである",breakdown:"ふつうの「好き」。adore はずっと強い"}]},

  {id:1955,word:"utter",partOfSpeech:"他動詞",meaning:"（声・言葉を）口に出す，発する；全くの",
   meanings:["他|（声・言葉を）口に出す，発する","形|全くの，完全な"],
   pronunciation:"/ˈʌtər/",part:196,
   example:"She was so shocked that she could not utter a word.",
   exampleJa:"彼女はショックのあまり、ひと言も口に出せなかった。",
   example2:"Our plan for the class trip ended in utter failure.",
   exampleJa2:"クラス旅行の計画は全くの失敗に終わった。",
   etymologyProcess:"out（外へ）→ 心の中の言葉を外へ出すと…？",
   etymologyConclusion:"out（外へ）→ 心の中にある言葉を声にして外へ出す＝（声・言葉を）口に出す",
   spelling:"out→ut（古い英語の形）",
   etymologyMore:["いちばん外側の端まで行き着いた→全くの，完全な"],
   hook:"outer（外側の）の古い形が ut。動詞も形容詞も「外へ」から出ている。",
   relatedWords:[
     {word:"outer",meaning:"外側の",breakdown:"out（外へ）＋ er（より）→ より外のほうにある"},
     {word:"utmost",meaning:"最大限の",breakdown:"out（外へ）＋ most（最も）→ いちばん外側の端まで"},
     {word:"utterance",meaning:"発言，発話",breakdown:"out（外へ）＋ ance（名詞）→ 口から外へ出た言葉"},
     {synonym:true,word:"say",meaning:"言う",breakdown:"言う全般。utter は声や言葉を一つ口から出すこと"}]},

  {id:1956,word:"exclaim",partOfSpeech:"他動詞・自動詞",meaning:"（驚き・喜びで）大声を上げる，叫ぶ",
   meanings:["自|（驚き・喜びで）大声を上げる，叫ぶ","他|～と叫ぶ"],
   pronunciation:"/ɪkˈskleɪm/",part:196,
   example:"She exclaimed with joy when she saw her test score.",
   exampleJa:"テストの点数を見て、彼女は喜びのあまり大声を上げた。",
   example2:"'We won!' exclaimed the captain as the final whistle blew.",
   exampleJa2:"試合終了の笛が鳴ると、キャプテンは「勝ったぞ！」と叫んだ。",
   etymologyProcess:"ex（外へ）＋ claim（叫ぶ）→ 思わず声を外へ…？",
   etymologyConclusion:"ex（外へ）＋ claim（叫ぶ）→ 驚きや喜びで思わず声を外へ放つ＝（驚き・喜びで）大声を上げる",
   relatedWords:[
     {word:"claim",meaning:"主張する，要求する",breakdown:"claim（叫ぶ）→ 声を上げて自分のものだと言い立てる"},
     {word:"exclamation",meaning:"叫び，感嘆",breakdown:"ex（外へ）＋ claim（叫ぶ）＋ ation（名詞）→ 思わず出た叫び。! の名前"},
     {word:"proclaim",meaning:"宣言する",breakdown:"pro（人前で）＋ claim（叫ぶ）→ 人々の前で大声で告げる"},
     {synonym:true,word:"shout",meaning:"大声で言う",breakdown:"大声を出す全般。exclaim は驚きや喜びで思わず"}]},

  {id:1957,word:"shed",partOfSpeech:"他動詞",meaning:"（涙・血を）流す；（葉・皮などを）落とす",
   meanings:["他|（涙・血を）流す","他|（葉・皮などを）落とす，脱ぎ捨てる","他|（光を）当てる，注ぐ"],
   pronunciation:"/ʃed/",part:196,
   example:"Many people shed tears at the end of the movie.",
   exampleJa:"映画の最後に、多くの人が涙を流した。",
   example2:"Many trees shed their leaves to survive the cold winter.",
   exampleJa2:"多くの木は、寒い冬を越すために葉を落とす。",
   etymologyProcess:"shed（分ける）→ 体から切り離して外へ出すと…？",
   etymologyConclusion:"shed（分ける）→ 体から切り離して外へこぼし出す＝（涙・血を）流す",
   etymologyMore:["いらなくなった部分を切り離す→（葉・皮などを）落とす，脱ぎ捨てる","光を周りへまき散らす→（光を）当てる，注ぐ"],
   hook:"過去形も過去分詞も shed のまま。shed light on ～ で「～を解明する」。",
   relatedWords:[
     {synonym:true,word:"drop",meaning:"落とす",breakdown:"落とす全般。shed は自然に体から離して落とす"},
     {synonym:true,word:"cry",meaning:"泣く",breakdown:"声を出して泣く。shed tears は涙を流すこと"},
     {synonym:true,word:"spill",meaning:"こぼす",breakdown:"うっかりこぼす。shed は涙や血を流す"},
     {synonym:true,word:"lose",meaning:"失う",breakdown:"なくす全般。shed weight なら「体重を落とす」"}]},

  {id:1958,word:"resent",partOfSpeech:"他動詞",meaning:"（不当だと）腹立たしく思う，憤慨する",
   meanings:["他|（不当だと）腹立たしく思う，憤慨する"],
   pronunciation:"/rɪˈzent/",part:196,
   example:"Many students resent having to clean the classroom every day.",
   exampleJa:"多くの生徒が、毎日教室を掃除しなければならないのを腹立たしく思っている。",
   example2:"He resented being treated like a child by his parents.",
   exampleJa2:"彼は両親に子ども扱いされることに憤慨した。",
   usage:["resent doing（～することに腹を立てる）"],
   etymologyProcess:"re（再び）＋ sens（感じる）→ 嫌なことを何度も感じ直すと…？",
   etymologyConclusion:"re（再び）＋ sens（感じる）→ 受けた仕打ちを何度も思い返して苦く感じる＝（不当だと）腹立たしく思う",
   why:"【なぜ】フランス語 ressentir は「強く感じ返す」で、もとはよい気持ちにも悪い気持ちにも使えました。受けたことを何度も感じ直すうちに、英語では「ひどい扱いを思い返しては腹が立つ」という悪い意味だけが残りました。\n【つながり】名詞は resentment（恨み）。sense（感覚）や sentiment（感情）も同じ「感じる」の仲間です。",
   spelling:"sens→sent（フランス語 sentir を通った形）",
   relatedWords:[
     {word:"sense",meaning:"感覚",breakdown:"sens（感じる）→ 体や心で感じとる力"},
     {word:"sensitive",meaning:"敏感な",breakdown:"sens（感じる）＋ ive（形容詞）→ 小さなことも感じとりやすい"},
     {word:"resentment",meaning:"恨み，憤り",breakdown:"re（再び）＋ sens（感じる）＋ ment（名詞）→ 思い返しては苦く感じる気持ち"},
     {synonym:true,word:"angry",meaning:"怒った",breakdown:"怒り全般。resent は不当な扱いへの長く残る怒り"}]},

  {id:1959,word:"plead",partOfSpeech:"自動詞",meaning:"（必死に）嘆願する；（法廷で）申し立てる",
   meanings:["自|（必死に）嘆願する，懇願する","他|（法廷で）申し立てる，主張する"],
   pronunciation:"/pliːd/",part:196,
   example:"The boy pleaded with his mother to buy him a new game.",
   exampleJa:"少年は、新しいゲームを買ってと母親に必死に嘆願した。",
   example2:"The man pleaded guilty to stealing the bicycle.",
   exampleJa2:"その男は、自転車を盗んだことについて有罪だと申し立てた。",
   usage:["plead with 人 to do（人に～してと嘆願する）","plead guilty（罪を認める）"],
   etymologyProcess:"pleas（喜ばせる）→ 裁く人によしとしてもらおうと…？",
   etymologyConclusion:"pleas（喜ばせる）→ 裁く人によい判断をしてもらおうと必死に訴える＝（必死に）嘆願する",
   why:"【なぜ】ラテン語 placitum は「（裁く人が）よしとしたこと」＝判決。フランス語でこれが「裁判」を指すようになり、英語の plead は「裁判で自分の言い分を訴える」になりました。そこから、法廷の外でも必死に訴えて頼む意味に広がりました。\n【つながり】plea（嘆願）は名詞形。please（喜ばせる）と同じ家族です。",
   spelling:"pleas→plea（フランス語 plaid を通った形）",
   relatedWords:[
     {word:"please",meaning:"喜ばせる",breakdown:"pleas（喜ばせる）→ 相手の心を満たして喜ばせる"},
     {word:"pleasant",meaning:"心地よい",breakdown:"pleas（喜ばせる）＋ ant（～な）→ 人を喜ばせるような"},
     {word:"plea",meaning:"嘆願",breakdown:"pleas（喜ばせる）→ 裁く人によしとしてほしいという訴え"},
     {synonym:true,word:"beg",meaning:"懇願する",breakdown:"ひたすら頼みこむ。plead は理由を挙げて必死に訴える"}]},

  {id:1960,word:"yearn",partOfSpeech:"自動詞",meaning:"（for ～を）強く恋しがる，あこがれる",
   meanings:["自|（for ～を）強く恋しがる，あこがれる","自|（to do）しきりに～したがる"],
   pronunciation:"/jɜːrn/",part:196,
   example:"After years abroad, she yearned for her mother's home cooking.",
   exampleJa:"何年も海外で暮らしたあと、彼女は母の手料理を強く恋しがった。",
   example2:"Many young players yearn to play for the national team.",
   exampleJa2:"多くの若い選手が、代表チームでプレーすることにあこがれている。",
   usage:["yearn for 物（物を強く求める）","yearn to do（しきりに～したがる）"],
   etymologyProcess:"yearn（強く求める）→ 胸の奥から何かを求め続けると…？",
   etymologyConclusion:"yearn（強く求める）→ 離れたものを胸が痛むほど求め続ける＝（for ～を）強く恋しがる",
   hook:"yearn for ～ の形で使う。手に入らないものを胸が痛むほど求める感じ。",
   relatedWords:[
     {synonym:true,word:"miss",meaning:"いなくて寂しく思う",breakdown:"いない人・ないものを寂しく思う。yearn はもっと強く求める"},
     {synonym:true,word:"wish",meaning:"願う",breakdown:"こうだといいと願う。yearn は胸が痛むほど"},
     {synonym:true,word:"long",meaning:"待ち焦がれる",breakdown:"long for ～ で yearn for ～ とほぼ同じ"},
     {synonym:true,word:"desire",meaning:"強く望む",breakdown:"やや硬い語。yearn は切なさがこもる"}]},

  {id:1961,word:"long",partOfSpeech:"自動詞",meaning:"（for ～を）待ち焦がれる，切望する",
   meanings:["自|（for ～を）待ち焦がれる，切望する","自|（to do）しきりに～したがる"],
   pronunciation:"/lɔːŋ/",part:197,
   example:"The children longed for the summer vacation to begin.",
   exampleJa:"子どもたちは夏休みが始まるのを待ち焦がれた。",
   example2:"I long to see my old friends from junior high school.",
   exampleJa2:"中学時代の友達に、しきりに会いたいと思う。",
   usage:["long for 物（物を待ち焦がれる）","long to do（しきりに～したがる）"],
   etymologyProcess:"long（沿って続く）→ 待つ時間が長く続くと…？",
   etymologyConclusion:"long（沿って続く）→ 待つ時間がとても長く感じられるほど強く求める＝（for ～を）待ち焦がれる",
   why:"【なぜ】古い英語 langian はもとは「長くなる」。会いたい人や待っている日を思うと、時間がとても長く感じられます。そこから「長く感じる→待ち遠しく思う→強く求める」と意味が移りました。\n【つながり】名詞 longing は「あこがれ」。形容詞の long（長い）と同じ語なので、つづりも発音も全く同じです。",
   relatedWords:[
     {word:"longing",meaning:"あこがれ，切望",breakdown:"long（沿って続く）＋ ing（名詞）→ 長く思い続ける気持ち"},
     {word:"length",meaning:"長さ",breakdown:"long（沿って続く）＋ th（名詞）→ どこまで続いているか"},
     {word:"along",meaning:"～に沿って",breakdown:"long（沿って続く）→ 長く伸びた道にそって進む"},
     {synonym:true,word:"yearn",meaning:"強く恋しがる",breakdown:"yearn for ～ は long for ～ とほぼ同じ。切なさが強い"}]},

  {id:1962,word:"immerse",partOfSpeech:"他動詞",meaning:"（in ～に）没頭させる；（液体に）すっかり浸す",
   meanings:["他|（in ～に）没頭させる","他|（液体に）すっかり浸す，沈める"],
   pronunciation:"/ɪˈmɜːrs/",part:197,
   example:"She immersed herself in her studies before the entrance exam.",
   exampleJa:"入試を前に、彼女は勉強に没頭した。",
   example2:"Immerse the tomatoes in boiling water for a few seconds.",
   exampleJa2:"トマトを数秒間、沸騰したお湯にすっかり浸しなさい。",
   usage:["be immersed in 事（事に没頭している）","immerse oneself in 事（事に打ちこむ）"],
   etymologyProcess:"in（中へ）＋ merg（沈める）→ 頭まですっぽり沈めると…？",
   etymologyConclusion:"in（中へ）＋ merg（沈める）→ 頭のてっぺんまで何かの中へすっぽり沈める＝（in ～に）没頭させる",
   spelling:"in→im（m の前で変化）、merg→mers（過去分詞の形）",
   etymologyMore:["液体の中へ体ごと沈める→（液体に）すっかり浸す，沈める"],
   relatedWords:[
     {word:"emergency",meaning:"緊急事態",breakdown:"e（外へ）＋ merg（沈める）＋ ency（名詞）→ 沈んでいたものが急に浮かび出た事態"},
     {word:"emerge",meaning:"現れる",breakdown:"e（外へ）＋ merg（沈める）→ 沈んだ所から外へ浮かび出る"},
     {synonym:true,word:"dip",meaning:"さっとつける",breakdown:"一瞬だけつける。immerse は全体をすっぽり沈める"},
     {synonym:true,word:"absorb",meaning:"夢中にさせる；吸収する",breakdown:"be absorbed in ～ も「～に夢中だ」。immerse は沈みこむ感じ"}]},

  {id:1963,word:"bewilder",partOfSpeech:"他動詞",meaning:"（ひどく）当惑させる，まごつかせる",
   meanings:["他|（ひどく）当惑させる，まごつかせる"],
   pronunciation:"/bɪˈwɪldər/",part:197,
   example:"The new rules bewildered many of the first-year students.",
   exampleJa:"新しい規則は、多くの1年生をひどく当惑させた。",
   example2:"He looked bewildered when the teacher spoke to him in French.",
   exampleJa2:"先生にフランス語で話しかけられて、彼は当惑した様子だった。",
   etymologyProcess:"be（すっかり）＋ wild（野生の）→ 荒れ野に迷いこんだように…？",
   etymologyConclusion:"be（すっかり）＋ wild（野生の）→ 荒れ野で道に迷わせるように頭を混乱させる＝（ひどく）当惑させる",
   relatedWords:[
     {word:"wild",meaning:"野生の，荒れた",breakdown:"wild（野生の）→ 人の手が入っていない，荒々しい"},
     {word:"wilderness",meaning:"荒れ野",breakdown:"wild（野生の）＋ ness（名詞）→ 人の住まない荒れた土地"},
     {word:"wildlife",meaning:"野生生物",breakdown:"wild（野生の）＋ life（命）→ 野に生きる動物や植物"},
     {synonym:true,word:"confuse",meaning:"混乱させる",breakdown:"頭をこんがらがらせる。bewilder は途方に暮れるほど"}]},

  {id:1964,word:"despise",partOfSpeech:"他動詞",meaning:"（ひどく）軽蔑する，見下す",
   meanings:["他|（ひどく）軽蔑する，見下す"],
   pronunciation:"/dɪˈspaɪz/",part:197,
   example:"She despises people who are rude to waiters.",
   exampleJa:"彼女は、店員に失礼な態度をとる人をひどく軽蔑している。",
   example2:"He was despised by his classmates for lying so often.",
   exampleJa2:"彼はうそばかりつくので、クラスメートに見下されていた。",
   etymologyProcess:"de（下へ）＋ spec（見る）→ 上から下へ見ると…？",
   etymologyConclusion:"de（下へ）＋ spec（見る）→ 相手を上から下へ見下ろす＝（ひどく）軽蔑する",
   spelling:"spec→spis（フランス語を通って変化）",
   relatedWords:[
     {word:"respect",meaning:"尊敬する",breakdown:"re（後ろへ）＋ spect（見る）→ 振り返って見直す。despise の反対"},
     {word:"expect",meaning:"予期する",breakdown:"ex（外へ）＋ spect（見る）→ 外を見て来るのを待ち受ける"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ or（人）→ 試合を見る人"},
     {synonym:true,word:"hate",meaning:"ひどく嫌う",breakdown:"憎む・嫌う。despise は価値がないと見下す"}]},

  {id:1965,word:"willing",partOfSpeech:"形容詞",meaning:"（to do）～するのをいとわない，嫌がらずに～する",
   meanings:["形|（to do）～するのをいとわない，嫌がらずに～する","形|進んで行う，自発的な"],
   pronunciation:"/ˈwɪlɪŋ/",part:197,
   example:"I am willing to help you with your homework.",
   exampleJa:"宿題を手伝うのはいとわないよ。",
   example2:"We need a few willing volunteers for the school festival.",
   exampleJa2:"文化祭のために、進んで手伝ってくれるボランティアが何人か必要だ。",
   usage:["be willing to do（～するのをいとわない）"],
   etymologyProcess:"will（望む）＋ ing（～している）→ 自分でそう望んでいると…？",
   etymologyConclusion:"will（望む）＋ ing（～している）→ 頼まれたことを自分でも望んで引き受ける＝（to do）～するのをいとわない",
   etymologyMore:["自分から望んで動く→進んで行う，自発的な"],
   relatedWords:[
     {word:"unwilling",meaning:"気が進まない",breakdown:"un（否定）＋ will（望む）＋ ing（～している）→ 望んでいない"},
     {word:"willingly",meaning:"進んで，快く",breakdown:"will（望む）＋ ing（～している）＋ ly（～に）→ 自分から望んで"},
     {word:"goodwill",meaning:"好意，善意",breakdown:"good（ふさわしい）＋ will（望む）→ 相手によかれと望む心"},
     {synonym:true,word:"ready",meaning:"進んで～する",breakdown:"be ready to do も「進んで～する」。準備ができている感じ"}]},

  {id:1966,word:"furious",partOfSpeech:"形容詞",meaning:"（with ～に）激怒した，かんかんに怒った",
   meanings:["形|（with ～に）激怒した，かんかんに怒った","形|（勢いが）猛烈な，激しい"],
   pronunciation:"/ˈfjʊriəs/",part:197,
   example:"My father was furious with me for breaking his camera.",
   exampleJa:"カメラを壊したことで、父は私に激怒した。",
   example2:"The runners kept a furious pace until the very end.",
   exampleJa2:"ランナーたちは最後の最後まで猛烈なペースを保った。",
   usage:["be furious with 人（人に激怒している）","be furious about 事（事に激怒している）"],
   etymologyProcess:"fur（怒り狂う）＋ ous（～に満ちた）→ 狂ったような怒りでいっぱいだと…？",
   etymologyConclusion:"fur（怒り狂う）＋ ous（～に満ちた）→ 狂ったような怒りで胸がいっぱいになっている＝（with ～に）激怒した",
   etymologyMore:["狂ったような激しい勢い→（勢いが）猛烈な，激しい"],
   relatedWords:[
     {word:"fury",meaning:"激しい怒り",breakdown:"fur（怒り狂う）＋ y（名詞）→ 我を忘れるほどの怒り"},
     {synonym:true,word:"angry",meaning:"怒った",breakdown:"怒り全般。furious は angry よりずっと激しい"},
     {synonym:true,word:"mad",meaning:"怒った；気が狂った",breakdown:"口語で「怒った」。furious と同じく狂うほどの怒り"},
     {synonym:true,word:"rage",meaning:"激怒",breakdown:"激しい怒りそのもの。furious は rage に燃えている状態"}]},

  {id:1967,word:"intimate",partOfSpeech:"形容詞",meaning:"親密な，（非常に）親しい",
   meanings:["形|親密な，（非常に）親しい","形|（知識が）詳しい，よく知っている","形|個人的な，私的な"],
   pronunciation:"/ˈɪntɪmət/",part:197,
   example:"They have been intimate friends since elementary school.",
   exampleJa:"彼らは小学校のころから親密な友人だ。",
   example2:"The old fisherman has an intimate knowledge of this sea.",
   exampleJa2:"その年老いた漁師は、この海について詳しい知識を持っている。",
   etymologyProcess:"intim（最も内側の）＋ ate（形容詞）→ 心のいちばん内側まで…？",
   etymologyConclusion:"intim（最も内側の）＋ ate（形容詞）→ 心のいちばん内側まで入り合っている＝親密な",
   etymologyMore:["内側の奥まで知っている→（知識が）詳しい，よく知っている","心の内側にしまっておく→個人的な，私的な"],
   relatedWords:[
     {synonym:true,word:"inside",meaning:"内側；内部に",breakdown:"中のほう。intern はもと組織の内側で働く人"},
     {word:"internal",meaning:"内部の",breakdown:"intern（内側の）＋ al（形容詞）→ 中のほうの"},
     {word:"intimacy",meaning:"親密さ",breakdown:"intim（最も内側の）＋ acy（名詞）→ 心の奥まで通う親しさ"},
     {synonym:true,word:"close",meaning:"親しい",breakdown:"親しい全般。intimate はもっと深く親密"}]},

  {id:1968,word:"aesthetic",partOfSpeech:"形容詞",meaning:"美的な，美に関する",
   meanings:["形|美的な，美に関する","名|美意識；美学"],
   pronunciation:"/esˈθetɪk/",part:197,
   example:"The old building has little aesthetic value but is very useful.",
   exampleJa:"その古い建物には美的な価値はほとんどないが、とても役に立つ。",
   example2:"Japanese gardens reflect a unique aesthetic of simplicity.",
   exampleJa2:"日本庭園は、簡素さという独特の美意識を表している。",
   etymologyProcess:"aesthe（感じとる）＋ ic（形容詞）→ 目や心で感じとる…？",
   etymologyConclusion:"aesthe（感じとる）＋ ic（形容詞）→ 目や心で美しさを感じとることに関する＝美的な",
   why:"【なぜ】ギリシャ語 aisthētikos は「感覚で感じとる」という意味で、美とは限りませんでした。18世紀のドイツの哲学者が「美を感じとる感覚の学問」を aesthetics と名づけたことから、「美に関する」意味で広まりました。\n【つながり】anesthesia（麻酔）は「感覚をなくすこと」で同じ仲間。美容の「エステ」もこの語から来ています。",
   relatedWords:[
     {word:"aesthetics",meaning:"美学",breakdown:"aesthe（感じとる）＋ ic（形容詞）→ 美を感じとるしくみを考える学問"},
     {synonym:true,word:"beautiful",meaning:"美しい",breakdown:"美しい全般。aesthetic は「美という点での」"},
     {synonym:true,word:"artistic",meaning:"芸術的な",breakdown:"芸術の。aesthetic は美しさそのものに注目"},
     {synonym:true,word:"taste",meaning:"好み，センス",breakdown:"good taste は「よいセンス」。aesthetic はより硬い語"}]},

  {id:1969,word:"conscience",partOfSpeech:"名詞",meaning:"良心，善悪の判断力",
   meanings:["名|良心，善悪の判断力","名|（良心の）とがめ"],
   pronunciation:"/ˈkɑːnʃəns/",part:197,
   example:"My conscience told me to return the wallet I found.",
   exampleJa:"拾った財布を返しなさいと、良心が私に告げた。",
   example2:"He had a guilty conscience after lying to his best friend.",
   exampleJa2:"親友にうそをついて、彼は良心のとがめを感じた。",
   etymologyProcess:"con（共に）＋ sci（知る）→ 自分のしたことを一緒に知っている…？",
   etymologyConclusion:"con（共に）＋ sci（知る）＋ ence（名詞）→ 自分のしたことを心の中で共に知っている声＝良心",
   why:"【なぜ】ラテン語 conscientia は「一緒に知っていること」。自分のしたことを、心の中のもう一人の自分が全部知っている――その内なる声が、善い悪いを判断する「良心」になりました。\n【つながり】conscious（意識している）も同じ成り立ちで、science（科学＝知ること）の仲間です。conscience と conscious はつづりが似ているので注意。",
   relatedWords:[
     {word:"science",meaning:"科学",breakdown:"sci（知る）＋ ence（名詞）→ 知ること，学問"},
     {word:"conscious",meaning:"意識している",breakdown:"con（共に）＋ sci（知る）＋ ous（形容詞）→ 自分で分かっている"},
     {word:"scientist",meaning:"科学者",breakdown:"sci（知る）＋ ist（人）→ 知ることを仕事にする人"},
     {synonym:true,word:"guilt",meaning:"罪悪感",breakdown:"悪いことをしたという気持ち。conscience が痛むと生まれる"}]},

  {id:1970,word:"mercy",partOfSpeech:"名詞",meaning:"慈悲，情け",
   meanings:["名|慈悲，情け，哀れみ","名|（幸運な）ありがたいこと"],
   pronunciation:"/ˈmɜːrsi/",part:197,
   example:"The king showed mercy and let the prisoners go free.",
   exampleJa:"王は慈悲を示し、囚人たちを解放した。",
   example2:"Our small boat was at the mercy of the strong waves.",
   exampleJa2:"私たちの小さな船は、強い波のなすがままだった。",
   usage:["at the mercy of ～（～のなすがままで）"],
   etymologyProcess:"merc（商品）→ 天から報いを受けられる施しとは…？",
   etymologyConclusion:"merc（商品）→ 天からの報いを受ける、弱い者への施しの心＝慈悲",
   why:"【なぜ】ラテン語 merces は「代金・報酬」で、merchant（商人）と同じ家族。キリスト教の時代に「弱い者に施せば天で報いを受ける」と考えたことから、「施し」「情け」を指すようになりました。\n【つながり】フランス語の merci（ありがとう）も同じ語。相手の情けに感謝する言葉から来ています。",
   relatedWords:[
     {word:"merchant",meaning:"商人",breakdown:"merc（商品）＋ ant（人）→ 商品を売り買いする人"},
     {word:"commerce",meaning:"商業",breakdown:"com（共に）＋ merc（商品）→ 商品をやり取りし合うこと"},
     {word:"merciful",meaning:"慈悲深い",breakdown:"merc（商品）＋ ful（満ちた）→ 情けに満ちた"},
     {synonym:true,word:"pity",meaning:"哀れみ",breakdown:"かわいそうに思う気持ち。mercy は罰を許す情け"}]},

  {id:1971,word:"compassion",partOfSpeech:"名詞",meaning:"（深い）同情，哀れみ",
   meanings:["名|（深い）同情，哀れみ"],
   pronunciation:"/kəmˈpæʃən/",part:198,
   example:"We should show compassion for people who have lost their homes.",
   exampleJa:"家を失った人々に、深い同情を示すべきだ。",
   example2:"The nurse treated every patient with warmth and compassion.",
   exampleJa2:"その看護師は、どの患者にも温かさと思いやりをもって接した。",
   etymologyProcess:"com（共に）＋ pat（耐える）→ 相手の苦しみを一緒に耐えると…？",
   etymologyConclusion:"com（共に）＋ pat（耐える）＋ ion（名詞）→ 相手の苦しみを自分も共に感じて耐える＝（深い）同情",
   spelling:"pat→pass（過去分詞 passus の形）",
   relatedWords:[
     {word:"patient",meaning:"患者；忍耐強い",breakdown:"pat（耐える）＋ ent（人）→ 痛みに耐えている人"},
     {word:"patience",meaning:"忍耐",breakdown:"pat（耐える）＋ ence（名詞）→ じっと耐える力"},
     {word:"passion",meaning:"情熱",breakdown:"pat（耐える）＋ ion（名詞）→ 苦しみも耐えられるほどの強い思い"},
     {synonym:true,word:"sympathy",meaning:"同情，思いやり",breakdown:"気持ちを分かち合う。compassion は助けたいと思うほど深い"}]},

  {id:1972,word:"impulse",partOfSpeech:"名詞",meaning:"（突然の）衝動，出来心",
   meanings:["名|（突然の）衝動，出来心","名|（外からの）刺激，はずみ"],
   pronunciation:"/ˈɪmpʌls/",part:198,
   example:"She felt a sudden impulse to laugh during the quiet ceremony.",
   exampleJa:"静かな式の最中に、彼女は急に笑いたい衝動に駆られた。",
   example2:"I bought this jacket on impulse, and now I regret it.",
   exampleJa2:"このジャケットは衝動買いしたが、今は後悔している。",
   usage:["on impulse（衝動的に，思わず）"],
   etymologyProcess:"in（中へ）＋ puls（押しやる）→ 心の内側から急に押されると…？",
   etymologyConclusion:"in（中へ）＋ puls（押しやる）→ 心の内側から急にぐいと押し出される力＝（突然の）衝動",
   spelling:"in→im（p の前で変化）",
   etymologyMore:["外からぐいと押されて動き出す→（外からの）刺激，はずみ"],
   relatedWords:[
     {word:"pulse",meaning:"脈拍",breakdown:"puls（押しやる）→ 心臓が血を押し出すたびに打つ脈"},
     {word:"push",meaning:"押す",breakdown:"puls（押しやる）→ フランス語を通って形が変わった。ぐいと押す"},
     {word:"compulsory",meaning:"義務的な",breakdown:"com（すっかり）＋ puls（押しやる）＋ ory（形容詞）→ 無理やり押しやられる"},
     {synonym:true,word:"urge",meaning:"強い衝動",breakdown:"何かをしたい強い気持ち。impulse は考える前の突然の衝動"}]},

  {id:1973,word:"aspiration",partOfSpeech:"名詞",meaning:"熱望，（高い）志",
   meanings:["名|熱望，（高い）志"],
   pronunciation:"/ˌæspəˈreɪʃən/",part:198,
   example:"Her aspiration is to become a doctor in her hometown.",
   exampleJa:"彼女の熱望は、故郷で医者になることだ。",
   example2:"The school supports students with high aspirations for the future.",
   exampleJa2:"その学校は、将来に高い志を持つ生徒を支援している。",
   etymologyProcess:"ad（～へ）＋ spir（息をする）→ 目標に向かって息をはずませると…？",
   etymologyConclusion:"ad（～へ）＋ spir（息をする）＋ ation（名詞）→ 目標に向かって息をはずませて求める気持ち＝熱望",
   why:"【なぜ】ラテン語 aspirare は「～に息を吹きかける」。何かを強く求めるとき、人は息をはずませて身を乗り出します。その姿から「～を求めてあえぐ」→「熱望する」と意味が移りました。\n【つながり】動詞は aspire（熱望する）。inspire（息を吹きこむ→ひらめかせる）、spirit（息→魂）も同じ「息」の仲間です。",
   spelling:"ad→a（s の前で d が消えた）",
   relatedWords:[
     {word:"inspire",meaning:"奮い立たせる",breakdown:"in（中へ）＋ spir（息をする）→ 心に息を吹きこむ"},
     {word:"spirit",meaning:"精神，魂",breakdown:"spir（息をする）＋ it（もの）→ 体に宿る命の息"},
     {word:"aspire",meaning:"熱望する",breakdown:"ad（～へ）＋ spir（息をする）→ 目標に向かって息をはずませる"},
     {synonym:true,word:"ambition",meaning:"願望，野望",breakdown:"成功したいという野心。aspiration はより高い志"}]},

  {id:1974,word:"grief",partOfSpeech:"名詞",meaning:"（深い）悲しみ，悲嘆",
   meanings:["名|（深い）悲しみ，悲嘆"],
   pronunciation:"/ɡriːf/",part:198,
   example:"She could not hide her grief after her dog died.",
   exampleJa:"飼い犬が死んだあと、彼女は深い悲しみを隠せなかった。",
   example2:"The whole town was filled with grief after the accident.",
   exampleJa2:"事故のあと、町全体が深い悲しみに包まれた。",
   etymologyProcess:"grav（重い）→ 心にずしりとのしかかると…？",
   etymologyConclusion:"grav（重い）→ 心にずしりと重くのしかかる悲しみ＝（深い）悲しみ",
   spelling:"grav→grie（フランス語を通って変化）",
   relatedWords:[
     {word:"gravity",meaning:"重力",breakdown:"grav（重い）＋ ity（名詞）→ 物を重くして引きつける力"},
     {word:"grave",meaning:"重大な",breakdown:"grav（重い）→ 重々しくて深刻な"},
     {word:"grieve",meaning:"深く悲しむ",breakdown:"grav（重い）→ 心が重くなって悲しむ"},
     {synonym:true,word:"sadness",meaning:"悲しさ",breakdown:"悲しさ全般。grief は死や別れによる深い悲しみ"}]},

  {id:1975,word:"contempt",partOfSpeech:"名詞",meaning:"軽蔑，さげすみ",
   meanings:["名|軽蔑，さげすみ"],
   pronunciation:"/kənˈtempt/",part:198,
   example:"He looked at the lazy players with contempt.",
   exampleJa:"彼は怠けている選手たちを軽蔑の目で見た。",
   example2:"Cheating on tests shows contempt for your hard-working classmates.",
   exampleJa2:"テストでのカンニングは、努力している級友へのさげすみを示している。",
   usage:["feel contempt for 人（人を軽蔑する）"],
   etymologyProcess:"con（すっかり）＋ temn（さげすむ）→ 取るに足りないと見なすと…？",
   etymologyConclusion:"con（すっかり）＋ temn（さげすむ）→ 相手をまるで取るに足りないものと見下す気持ち＝軽蔑",
   spelling:"temn→temp（過去分詞 temptus の形）",
   relatedWords:[
     {word:"contemptuous",meaning:"軽蔑的な",breakdown:"con（すっかり）＋ temn（さげすむ）＋ ous（形容詞）→ 人を見下すような"},
     {synonym:true,word:"despise",meaning:"軽蔑する",breakdown:"動詞で「見下す」。contempt はその気持ち"},
     {synonym:true,word:"look down on",meaning:"見下す",breakdown:"やさしい言い方。上から下へ見る"},
     {synonym:true,word:"hate",meaning:"ひどく嫌う",breakdown:"憎む。contempt は価値がないと見下す気持ち"}]},

  {id:1976,word:"insult",partOfSpeech:"名詞",meaning:"侮辱，無礼な言動；侮辱する",
   meanings:["名|侮辱，無礼な言動","他|侮辱する"],
   pronunciation:"/ˈɪnsʌlt/",part:198,
   example:"Calling him a coward was a terrible insult to his pride.",
   exampleJa:"彼を臆病者と呼ぶのは、彼のプライドへのひどい侮辱だった。",
   example2:"Please don't insult my friends in front of me.",
   exampleJa2:"私の目の前で友達を侮辱しないでください。",
   etymologyProcess:"in（上に）＋ sult（跳ぶ）→ 相手の上に跳び乗ると…？",
   etymologyConclusion:"in（上に）＋ sult（跳ぶ）→ 相手に跳びかかるように言葉で誇りを踏みつけること＝侮辱",
   why:"【なぜ】ラテン語 insultare は「～の上に跳び乗る」。倒れた相手の上で跳びはねるような、勝ち誇ってばかにする態度を表しました。そこから、言葉や態度で相手の誇りを踏みつける「侮辱」の意味になりました。\n【つながり】result（結果）は re（後ろへ）＋「跳ぶ」で「はね返ってきたもの」。somersault（宙返り）の sault も同じ「跳ぶ」です。",
   relatedWords:[
     {word:"result",meaning:"結果",breakdown:"re（後ろへ）＋ sult（跳ぶ）→ はね返ってきたもの"},
     {word:"somersault",meaning:"宙返り",breakdown:"super（上から）＋ sult（跳ぶ）→ 上へ跳んで宙で一回転する"},
     {synonym:true,word:"offend",meaning:"怒らせる",breakdown:"気を悪くさせる。insult はわざとばかにする"},
     {synonym:true,word:"rude",meaning:"無礼な",breakdown:"失礼な。insult は失礼な言葉や行いそのもの"}]},

  {id:1977,word:"nuisance",partOfSpeech:"名詞",meaning:"迷惑，厄介なもの［人］",
   meanings:["名|迷惑，厄介なもの［人］"],
   pronunciation:"/ˈnuːsns/",part:198,
   example:"The loud music from next door is a real nuisance.",
   exampleJa:"隣から聞こえる大音量の音楽は、本当に迷惑だ。",
   example2:"Stop making a nuisance of yourself during the lesson.",
   exampleJa2:"授業中に周りの迷惑になるのはやめなさい。",
   usage:["make a nuisance of oneself（迷惑をかける）"],
   etymologyProcess:"noc（傷つける）＋ ance（名詞）→ 周りに害を与えるものは…？",
   etymologyConclusion:"noc（傷つける）＋ ance（名詞）→ 周りの人に害を与えて困らせるもの＝迷惑",
   why:"【なぜ】ラテン語 nocere は「害を与える」。フランス語を通った nuisance も、はじめは「損害・害」という重い意味でした。それがしだいに軽くなり、今では「うるさい・困る」程度の迷惑を表すようになりました。\n【つながり】innocent（無罪の）は in（否定）＋「傷つける」で「害を与えない」。同じ家族の語です。",
   spelling:"noc→nuis（フランス語 nuire を通った形）",
   relatedWords:[
     {word:"innocent",meaning:"無罪の；無邪気な",breakdown:"in（否定）＋ noc（傷つける）＋ ent（形容詞）→ だれも傷つけていない"},
     {word:"innocence",meaning:"無罪；純真さ",breakdown:"in（否定）＋ noc（傷つける）＋ ence（名詞）→ 害のない清らかさ"},
     {synonym:true,word:"trouble",meaning:"面倒，困りごと",breakdown:"困ったこと全般。nuisance は周りに迷惑をかけるもの"},
     {synonym:true,word:"bother",meaning:"面倒，厄介",breakdown:"手間がかかる面倒。nuisance は迷惑の種そのもの"}]},

  {id:1978,word:"surge",partOfSpeech:"名詞",meaning:"（感情・数量の）高まり，急増",
   meanings:["名|（感情・数量の）高まり，急増","自|（波のように）押し寄せる"],
   pronunciation:"/sɜːrdʒ/",part:198,
   example:"There was a sudden surge in demand for masks that winter.",
   exampleJa:"その冬、マスクの需要に急な高まりが起きた。",
   example2:"Fans surged toward the stage when the band appeared.",
   exampleJa2:"バンドが現れると、ファンがステージに押し寄せた。",
   etymologyProcess:"surge（わき上がる）→ 下から波がぐっと盛り上がると…？",
   etymologyConclusion:"surge（わき上がる）→ 下から波のようにぐっと盛り上がること＝（感情・数量の）高まり",
   etymologyMore:["わき上がった波が前へ進む→（波のように）押し寄せる"],
   hook:"source（源）と同じ「わき上がる」の家族。大波がぐっと盛り上がる様子で覚える。",
   relatedWords:[
     {word:"source",meaning:"源，出どころ",breakdown:"source（わき出る）→ 水がわき出てくるところ"},
     {word:"resource",meaning:"資源",breakdown:"re（再び）＋ source（わき出る）→ 何度でもわき出る蓄え"},
     {synonym:true,word:"increase",meaning:"増加",breakdown:"増えること全般。surge は急にどっと増える"},
     {synonym:true,word:"rise",meaning:"上昇",breakdown:"上がること。surge は波のように一気に"}]},

  {id:1979,word:"incentive",partOfSpeech:"名詞",meaning:"（やる気を起こさせる）励み，刺激；報奨金",
   meanings:["名|（やる気を起こさせる）励み，刺激","名|報奨金，優遇措置"],
   pronunciation:"/ɪnˈsentɪv/",part:198,
   example:"Good grades are a strong incentive for students to study hard.",
   exampleJa:"よい成績は、生徒が一生懸命勉強する強い励みになる。",
   example2:"The company offers a cash incentive to workers who stop smoking.",
   exampleJa2:"その会社は、禁煙した社員に報奨金を出している。",
   etymologyProcess:"in（～に）＋ cant（歌う）→ 歌の調子をとって人を…？",
   etymologyConclusion:"in（～に）＋ cant（歌う）＋ ive（形容詞）→ 歌の調子をとって人をその気にさせるもの＝（やる気を起こさせる）励み",
   why:"【なぜ】ラテン語 incentivus は「歌の調子をとる」。最初の一節を歌って皆を歌い出させるように、人の気持ちに火をつけるものを指すようになりました。そこから「やる気を起こさせる励み」の意味になりました。\n【つながり】chant（詠唱）、accent（アクセント）も同じ「歌う」の仲間です。motive（動機）は自分の中の理由、incentive は外から与えられる励みです。",
   spelling:"cant→cent（ラテン語で母音が変化）",
   etymologyMore:["やる気を起こさせるために出すお金→報奨金，優遇措置"],
   relatedWords:[
     {word:"chant",meaning:"詠唱；くり返し唱える",breakdown:"cant（歌う）→ 同じ節をくり返し歌うように唱える"},
     {word:"accent",meaning:"アクセント，なまり",breakdown:"ad（～へ）＋ cant（歌う）→ 言葉に添える歌うような調子"},
     {word:"enchant",meaning:"魅了する",breakdown:"en（中へ）＋ cant（歌う）→ 歌で呪文をかけてうっとりさせる"},
     {synonym:true,word:"motivation",meaning:"やる気，動機づけ",breakdown:"やる気そのもの。incentive はやる気を起こさせる材料"}]},

  {id:1980,word:"outcome",partOfSpeech:"名詞",meaning:"（最終的な）結果，成り行き",
   meanings:["名|（最終的な）結果，成り行き"],
   pronunciation:"/ˈaʊtkʌm/",part:198,
   example:"Nobody could predict the outcome of the final match.",
   exampleJa:"決勝戦の最終的な結果は、だれにも予想できなかった。",
   example2:"We were happy with the outcome of the class discussion.",
   exampleJa2:"私たちはクラスの話し合いの結果に満足した。",
   etymologyProcess:"out（外へ）＋ come（来る）→ 最後に外へ出てきたものは…？",
   etymologyConclusion:"out（外へ）＋ come（来る）→ 物事の最後に外へ出てきたもの＝（最終的な）結果",
   relatedWords:[
     {word:"income",meaning:"収入",breakdown:"in（中へ）＋ come（来る）→ 手元に入って来るお金"},
     {word:"overcome",meaning:"克服する",breakdown:"over（越えて）＋ come（来る）→ 困難を乗り越えて来る"},
     {word:"outdoor",meaning:"屋外の",breakdown:"out（外へ）＋ door（戸）→ 戸の外の"},
     {synonym:true,word:"result",meaning:"結果",breakdown:"結果全般。outcome は最後にどうなったか"}]},

  {id:1981,word:"factor",partOfSpeech:"名詞",meaning:"（結果を生む）要因",
   meanings:["名|（結果を生む）要因","名|（数学の）因数"],
   pronunciation:"/ˈfæktər/",part:199,
   example:"Sleep is an important factor in doing well at school.",
   exampleJa:"睡眠は、学校でよい成績をとるための大切な要因だ。",
   example2:"Price was the main factor when I chose this phone.",
   exampleJa2:"このスマホを選んだとき、値段がいちばんの要因だった。",
   etymologyProcess:"fac（作る）＋ or（もの）→ ある結果を作り出しているものは…？",
   etymologyConclusion:"fac（作る）＋ or（もの）→ ある結果を作り出している一つ一つのもの＝（結果を生む）要因",
   etymologyMore:["かけ合わせてある数を作り上げるもの→（数学の）因数"],
   relatedWords:[
     {word:"factory",meaning:"工場",breakdown:"fac（作る）＋ ory（場所）→ 物を作る場所"},
     {word:"fact",meaning:"事実",breakdown:"fact（作る）→ 実際になされたこと"},
     {word:"manufacture",meaning:"製造する",breakdown:"manu（手）＋ fact（作る）→ 手で作る。今は機械で大量に作る"},
     {synonym:true,word:"cause",meaning:"原因",breakdown:"直接の原因。factor は結果に関わる要素の一つ"}]},

  {id:1982,word:"liable",partOfSpeech:"形容詞",meaning:"（to do）～しがちな，～しやすい；（法的に）責任がある",
   meanings:["形|（to do）～しがちな，～しやすい","形|（for ～に）法的に責任がある"],
   pronunciation:"/ˈlaɪəbl/",part:199,
   example:"This road is liable to flood after heavy rain.",
   exampleJa:"この道路は大雨のあと、冠水しがちだ。",
   example2:"Parents are liable for damage caused by their young children.",
   exampleJa2:"親は、幼い子どもが起こした損害に対して法的に責任がある。",
   usage:["be liable to do（～しがちだ）","be liable for 事（事に法的責任がある）"],
   etymologyProcess:"lig（結ぶ）＋ able（できる）→ ある結果に縛りつけられていると…？",
   etymologyConclusion:"lig（結ぶ）＋ able（できる）→ ある結果に縛られていて、そうなりやすい＝（to do）～しがちな",
   why:"【なぜ】フランス語 lier（縛る）から来て、もとは「法律に縛られている」＝責任を負う、という意味でした。「縛られていて逃れられない」ことから、「（悪いことに）さらされている」→「～しがちな」へと広がりました。\n【つながり】rely（頼る）は re ＋「結ぶ」で「しっかり結びついて頼る」。liable はよくないことに使うことが多い語です。",
   spelling:"lig→li（フランス語を通って g が消えた）",
   relatedWords:[
     {word:"rely",meaning:"頼る",breakdown:"re（再び）＋ lig（結ぶ）→ しっかり結びついて寄りかかる"},
     {word:"reliable",meaning:"信頼できる",breakdown:"re（再び）＋ lig（結ぶ）＋ able（できる）→ 頼ることができる"},
     {word:"liability",meaning:"法的責任",breakdown:"lig（結ぶ）＋ able（できる）＋ ity（名詞）→ 法に縛られて負う責任"},
     {synonym:true,word:"likely",meaning:"～しそうな",breakdown:"よいことにも使う。liable はよくないことに使う"}]},

  {id:1983,word:"thorough",partOfSpeech:"形容詞",meaning:"徹底的な，完全な",
   meanings:["形|徹底的な，完全な","形|（人が）きちょうめんな，念入りな"],
   pronunciation:"/ˈθɜːroʊ/",part:199,
   example:"The doctor gave me a thorough check before the marathon.",
   exampleJa:"マラソンの前に、医師が私に徹底的な検査をしてくれた。",
   example2:"She is very thorough, so she never misses small mistakes.",
   exampleJa2:"彼女はとてもきちょうめんなので、小さなミスも決して見逃さない。",
   etymologyProcess:"through（通して）→ 端から端まで通して行うと…？",
   etymologyConclusion:"through（通して）→ 端から端まで抜かりなく通して行う＝徹底的な",
   spelling:"through→thorough（古い英語の形が残った）",
   etymologyMore:["最初から最後まで気を配る→（人が）きちょうめんな，念入りな"],
   hook:"through と元は同じ語。つづりの違いと発音 /ˈθɜːroʊ/ に注意。",
   relatedWords:[
     {word:"through",meaning:"～を通り抜けて",breakdown:"through（通して）→ 端から端まで通り抜けて"},
     {word:"thoroughly",meaning:"徹底的に",breakdown:"through（通して）＋ ly（～に）→ すみずみまで通して"},
     {word:"breakthrough",meaning:"突破口，大発見",breakdown:"break（破る）＋ through（通して）→ 壁を突き破って通り抜ける"},
     {synonym:true,word:"complete",meaning:"完全な",breakdown:"欠けがない。thorough は細部まで抜かりがない"}]},

  {id:1984,word:"adequate",partOfSpeech:"形容詞",meaning:"（必要を満たすのに）十分な，適した",
   meanings:["形|（必要を満たすのに）十分な","形|（for ～に）適した，まずまずの"],
   pronunciation:"/ˈædɪkwət/",part:199,
   example:"You need adequate sleep to stay healthy during exams.",
   exampleJa:"試験の間も健康でいるには、十分な睡眠が必要だ。",
   example2:"The small room was adequate for our club meetings.",
   exampleJa2:"その小さな部屋は、部の集まりにはまずまず適していた。",
   etymologyProcess:"ad（～へ）＋ equ（等しい）→ 必要な量と等しくなると…？",
   etymologyConclusion:"ad（～へ）＋ equ（等しい）＋ ate（形容詞）→ 必要な量とちょうど等しくなっている＝（必要を満たすのに）十分な",
   relatedWords:[
     {word:"equal",meaning:"等しい",breakdown:"equ（等しい）＋ al（形容詞）→ 同じだけの"},
     {word:"equality",meaning:"平等",breakdown:"equ（等しい）＋ al（形容詞）＋ ity（名詞）→ みなが等しいこと"},
     {word:"inadequate",meaning:"不十分な",breakdown:"in（否定）＋ ad（～へ）＋ equ（等しい）＋ ate（形容詞）→ 必要に届かない"},
     {synonym:true,word:"enough",meaning:"十分な",breakdown:"足りている。adequate は必要な基準を満たしている"}]},

  {id:1985,word:"overall",partOfSpeech:"形容詞",meaning:"全体的な，総合的な",
   meanings:["形|全体的な，総合的な","副|全体として（は），概して"],
   pronunciation:"/ˌoʊvərˈɔːl/",part:199,
   example:"The overall result of the survey surprised the teachers.",
   exampleJa:"調査の全体的な結果は、先生たちを驚かせた。",
   example2:"Overall, our school trip was a great success.",
   exampleJa2:"全体として、修学旅行は大成功だった。",
   etymologyProcess:"over（越えて）＋ all（すっかり）→ 一つ一つを越えてすべてを見ると…？",
   etymologyConclusion:"over（越えて）＋ all（すっかり）→ 一つ一つを越えて、すべてをまとめて見渡した＝全体的な",
   relatedWords:[
     {word:"overflow",meaning:"あふれる",breakdown:"over（越えて）＋ flow（流れる）→ ふちを越えて流れ出る"},
     {word:"overweight",meaning:"太りすぎの",breakdown:"over（越えて）＋ weight（重さ）→ 重さが基準を越えた"},
     {word:"already",meaning:"すでに",breakdown:"all（すっかり）＋ ready（整った）→ すっかり用意ができている"},
     {synonym:true,word:"general",meaning:"全般的な",breakdown:"全体にわたる。overall は全部を合わせて見た"}]},

  {id:1986,word:"ultimate",partOfSpeech:"形容詞",meaning:"究極の，最終的な",
   meanings:["形|究極の，最終的な","形|最高の，この上ない"],
   pronunciation:"/ˈʌltɪmət/",part:199,
   example:"Her ultimate goal is to play in the Olympics.",
   exampleJa:"彼女の究極の目標は、オリンピックでプレーすることだ。",
   example2:"Climbing Mount Everest is the ultimate challenge for climbers.",
   exampleJa2:"エベレスト登山は、登山家にとって最高の挑戦だ。",
   etymologyProcess:"ultim（最も遠い）＋ ate（形容詞）→ いちばん遠い果てにあるのは…？",
   etymologyConclusion:"ultim（最も遠い）＋ ate（形容詞）→ いちばん遠くの行き着く果てにある＝究極の",
   etymologyMore:["それより先がないほどの→最高の，この上ない"],
   relatedWords:[
     {word:"ultimately",meaning:"最終的に",breakdown:"ultim（最も遠い）＋ ate（形容詞）＋ ly（～に）→ 行き着くところ"},
     {word:"ultraviolet",meaning:"紫外線（の）",breakdown:"ultra（越えて）＋ violet（紫）→ 紫を越えた先の光"},
     {synonym:true,word:"final",meaning:"最後の",breakdown:"最後の。ultimate は行き着く果ての"},
     {synonym:true,word:"last",meaning:"最後の",breakdown:"順番の最後。ultimate は目標や結果の最後"}]},

  {id:1987,word:"genuine",partOfSpeech:"形容詞",meaning:"（偽物でなく）本物の；心からの",
   meanings:["形|（偽物でなく）本物の，正真正銘の","形|心からの，偽りのない"],
   pronunciation:"/ˈdʒenjuɪn/",part:199,
   example:"Is this expensive bag made of genuine leather?",
   exampleJa:"この高いかばんは、本物の革でできているの？",
   example2:"She showed genuine interest in the history of our town.",
   exampleJa2:"彼女は私たちの町の歴史に、心からの興味を示した。",
   etymologyProcess:"gen（生み出す）＋ ine（～の）→ 生まれたままのものは…？",
   etymologyConclusion:"gen（生み出す）＋ ine（～の）→ 生まれたままで、作り物が混じっていない＝（偽物でなく）本物の",
   why:"【なぜ】ラテン語 genuinus は「生まれつきの，生まれたままの」。作り物ではなく生まれたときのままであることから「本物の」になりました。ただし語源ははっきりせず、genu（ひざ）から来たという説もあります。\n【つながり】gene（遺伝子）、generation（世代）も「生み出す」の仲間。気持ちに使うと「偽りのない」＝心からの、になります。",
   relatedWords:[
     {word:"gene",meaning:"遺伝子",breakdown:"gen（生み出す）→ 親から子へ生み伝えるもと"},
     {word:"generation",meaning:"世代",breakdown:"gener（生み出す）＋ ation（名詞）→ 同じころに生まれた人々"},
     {synonym:true,word:"real",meaning:"本当の，本物の",breakdown:"本当の。genuine は偽物でなく正真正銘の"},
     {synonym:true,word:"true",meaning:"真実の",breakdown:"うそでない。genuine は物にも気持ちにも使う"}]},

  {id:1988,word:"slight",partOfSpeech:"形容詞",meaning:"わずかな，ちょっとした",
   meanings:["形|わずかな，ちょっとした","形|（体が）ほっそりした"],
   pronunciation:"/slaɪt/",part:199,
   example:"There is a slight difference between these two colors.",
   exampleJa:"この2つの色には、わずかな違いがある。",
   example2:"I don't have the slightest idea where he went.",
   exampleJa2:"彼がどこへ行ったのか、私には少しも見当がつかない。",
   etymologyProcess:"slight（ほっそりした）→ 細くて小さいものは…？",
   etymologyConclusion:"slight（ほっそりした）→ 細くて、量も程度もごく小さい＝わずかな",
   etymologyMore:["もとの「細い」がそのまま残った→（体が）ほっそりした"],
   hook:"not the slightest ～ で「少しも～ない」。最上級にして強く打ち消す。",
   relatedWords:[
     {synonym:true,word:"small",meaning:"小さい",breakdown:"大きさが小さい。slight は程度がわずか"},
     {synonym:true,word:"little",meaning:"少しの",breakdown:"量が少ない。a slight cold は「軽いかぜ」"},
     {synonym:true,word:"minor",meaning:"小さいほうの，重要でない",breakdown:"重要度が低い。slight は差や変化がわずか"},
     {synonym:true,word:"tiny",meaning:"ごく小さい",breakdown:"見た目がとても小さい。slight は程度の話"}]},

  {id:1989,word:"radical",partOfSpeech:"形容詞",meaning:"（変化が）根本的な，抜本的な；過激な",
   meanings:["形|（変化が）根本的な，抜本的な","形|過激な，急進的な"],
   pronunciation:"/ˈrædɪkl/",part:199,
   example:"The new principal made radical changes to the school rules.",
   exampleJa:"新しい校長は、校則に根本的な変更を加えた。",
   example2:"Some members felt his ideas were too radical.",
   exampleJa2:"彼の考えは過激すぎると感じた部員もいた。",
   etymologyProcess:"radic（根）＋ al（形容詞）→ 物事の根っこにまで及ぶと…？",
   etymologyConclusion:"radic（根）＋ al（形容詞）→ 物事の根っこにまで及んで変える＝（変化が）根本的な",
   etymologyMore:["根っこから全部を変えようとする→過激な，急進的な"],
   relatedWords:[
     {word:"radish",meaning:"ラディッシュ，はつかだいこん",breakdown:"radic（根）→ 根を食べる野菜"},
     {word:"eradicate",meaning:"根絶する",breakdown:"e（外へ）＋ radic（根）＋ ate（動詞）→ 根こそぎ外へ抜く"},
     {synonym:true,word:"basic",meaning:"基本的な",breakdown:"土台の。radical は土台から変える"},
     {synonym:true,word:"extreme",meaning:"極端な",breakdown:"度が過ぎた。radical は根本から変えようとする"}]},

  {id:1990,word:"trivial",partOfSpeech:"形容詞",meaning:"ささいな，取るに足りない",
   meanings:["形|ささいな，取るに足りない"],
   pronunciation:"/ˈtrɪviəl/",part:199,
   example:"Let's not waste time arguing about such trivial matters.",
   exampleJa:"そんなささいなことで言い争って、時間を無駄にするのはやめよう。",
   example2:"What seemed trivial to me was very important to her.",
   exampleJa2:"私には取るに足りないと思えたことが、彼女にはとても大事だった。",
   etymologyProcess:"tri（3）＋ via（道）→ 三つ辻で交わされる話は…？",
   etymologyConclusion:"tri（3）＋ via（道）＋ al（形容詞）→ 三つ辻でだれもがするありふれた話のような＝ささいな",
   why:"【なぜ】ラテン語 trivium は「三本の道が交わる所」。そこは人が集まる場所で、だれでもするありふれたおしゃべりが交わされました。そこから「ありふれた」→「取るに足りない，ささいな」と意味が移りました。\n【つながり】trivia（雑学，トリビア）も同じ語から。via（～経由で）は「道」、triangle（三角形）の tri は「3」です。",
   relatedWords:[
     {word:"triangle",meaning:"三角形",breakdown:"tri（3）＋ angle（角）→ 三つの角をもつ形"},
     {word:"convey",meaning:"運ぶ，伝える",breakdown:"con（共に）＋ via（道）→ 道を一緒に進んで運ぶ"},
     {word:"trivia",meaning:"雑学，トリビア",breakdown:"tri（3）＋ via（道）→ 三つ辻で交わされる世間話"},
     {synonym:true,word:"minor",meaning:"重要でない",breakdown:"重要度が低い。trivial は問題にもならないほど"}]},

  {id:1991,word:"potent",partOfSpeech:"形容詞",meaning:"（薬などが）強力な，よく効く",
   meanings:["形|（薬などが）強力な，よく効く","形|（考え・言葉が）説得力のある"],
   pronunciation:"/ˈpoʊtnt/",part:200,
   example:"This medicine is very potent, so take only one tablet.",
   exampleJa:"この薬はとても強力なので、1錠だけ飲みなさい。",
   example2:"Her speech was a potent reminder of the value of peace.",
   exampleJa2:"彼女の演説は、平和の大切さを思い出させる説得力のあるものだった。",
   etymologyProcess:"pot（力がある）＋ ent（形容詞）→ 力が満ちていると…？",
   etymologyConclusion:"pot（力がある）＋ ent（形容詞）→ 中に力が満ちていて強く働く＝（薬などが）強力な",
   etymologyMore:["言葉に人を動かす力がある→（考え・言葉が）説得力のある"],
   relatedWords:[
     {word:"power",meaning:"力",breakdown:"pot（力がある）→ フランス語を通って形が変わった。物事を動かす力"},
     {word:"possible",meaning:"可能な",breakdown:"pot（力がある）＋ ible（できる）→ そうなる力がある"},
     {word:"potential",meaning:"可能性；潜在的な",breakdown:"pot（力がある）＋ ial（形容詞）→ 内に力を秘めている"},
     {synonym:true,word:"strong",meaning:"強い",breakdown:"強い全般。potent は薬や影響の効き目が強い"}]},

  {id:1992,word:"likewise",partOfSpeech:"副詞",meaning:"同様に，同じように",
   meanings:["副|同様に，同じように","副|（返事で）こちらこそ，私も"],
   pronunciation:"/ˈlaɪkwaɪz/",part:200,
   example:"My brother became a teacher, and I plan to do likewise.",
   exampleJa:"兄は教師になったが、私も同様にするつもりだ。",
   example2:"When she said 'Nice to meet you,' I answered 'Likewise.'",
   exampleJa2:"彼女が「はじめまして」と言ったので、私は「こちらこそ」と答えた。",
   etymologyProcess:"like（同じ形の）＋ wise（やり方）→ 同じやり方でするのは…？",
   etymologyConclusion:"like（同じ形の）＋ wise（やり方）→ 前の人と同じやり方で＝同様に",
   etymologyMore:["相手と同じ気持ちだと返す→（返事で）こちらこそ，私も"],
   relatedWords:[
     {word:"alike",meaning:"よく似ている",breakdown:"like（同じ形の）→ 形がそっくりな"},
     {word:"likely",meaning:"～しそうな",breakdown:"like（同じ形の）＋ ly（～のような）→ そうなりそうな形の"},
     {word:"otherwise",meaning:"さもなければ；別のやり方で",breakdown:"other（別の）＋ wise（やり方）→ 別のやり方で"},
     {synonym:true,word:"similarly",meaning:"同様に",breakdown:"似たように。likewise は「同じようにする」によく使う"}]},

  {id:1993,word:"virtually",partOfSpeech:"副詞",meaning:"事実上，ほとんど",
   meanings:["副|事実上，ほとんど","副|（コンピューター上の）仮想で"],
   pronunciation:"/ˈvɜːrtʃuəli/",part:200,
   example:"Virtually all the students passed the English test.",
   exampleJa:"事実上、全生徒が英語のテストに合格した。",
   example2:"You can visit the museum virtually from your computer at home.",
   exampleJa2:"自宅のパソコンから、その博物館を仮想で訪れることができる。",
   etymologyProcess:"virt（男らしい力）＋ al（形容詞）→ 実際の力の上ではそうだと…？",
   etymologyConclusion:"virt（男らしい力）＋ al（形容詞）＋ ly（～に）→ 名目はちがっても実際の力の上ではそうなっている＝事実上",
   why:"【なぜ】ラテン語 virtus は「男らしい力」→「効き目」。virtual は「名目はちがっても、実際の力（効き目）の上ではそうだ」という意味になり、virtually は「事実上，ほとんど」になりました。コンピューターの「仮想」も「本物と同じ働きをする」ことから来ています。\n【つながり】virtue（美徳）も同じ「力」の仲間です。",
   relatedWords:[
     {word:"virtue",meaning:"美徳",breakdown:"virt（男らしい力）→ 人にそなわるよい力"},
     {word:"virtual",meaning:"事実上の；仮想の",breakdown:"virt（男らしい力）＋ al（形容詞）→ 本物と同じ働きをする"},
     {synonym:true,word:"almost",meaning:"ほとんど",breakdown:"もう少しで全部。virtually は実質的には全部"},
     {synonym:true,word:"nearly",meaning:"ほぼ",breakdown:"あと少し。virtually とほぼ同じだがやや口語的"}]},

  {id:1994,word:"abruptly",partOfSpeech:"副詞",meaning:"不意に，突然",
   meanings:["副|不意に，突然","副|（態度が）ぶっきらぼうに"],
   pronunciation:"/əˈbrʌptli/",part:200,
   example:"The bus stopped abruptly, and everyone almost fell over.",
   exampleJa:"バスが不意に止まり、みんな転びそうになった。",
   example2:"He answered abruptly and left the room without saying goodbye.",
   exampleJa2:"彼はぶっきらぼうに答え、さよならも言わずに部屋を出た。",
   etymologyProcess:"ab（離れて）＋ rupt（破る）→ 途中でぷつりと破れると…？",
   etymologyConclusion:"ab（離れて）＋ rupt（破る）＋ ly（～に）→ 途中でぷつりと破れて切れるように＝不意に",
   etymologyMore:["言葉を途中でぷつりと切る→（態度が）ぶっきらぼうに"],
   relatedWords:[
     {word:"interrupt",meaning:"じゃまをする",breakdown:"inter（間の）＋ rupt（破る）→ 間に割って入って破る"},
     {word:"erupt",meaning:"噴火する",breakdown:"e（外へ）＋ rupt（破る）→ 破って外へ噴き出す"},
     {word:"abrupt",meaning:"突然の",breakdown:"ab（離れて）＋ rupt（破る）→ ぷつりと切れた"},
     {synonym:true,word:"suddenly",meaning:"突然",breakdown:"急に。abruptly は途中でぷつりと切れる感じ"}]},

  {id:1995,word:"deliberately",partOfSpeech:"副詞",meaning:"故意に，わざと；慎重に",
   meanings:["副|故意に，わざと","副|慎重に，落ち着いて"],
   pronunciation:"/dɪˈlɪbərətli/",part:200,
   example:"Did you break the vase deliberately or by accident?",
   exampleJa:"花びんを故意に割ったの、それとも事故だったの？",
   example2:"The old man spoke slowly and deliberately to the children.",
   exampleJa2:"その老人は子どもたちに、ゆっくりと慎重に話した。",
   etymologyProcess:"de（すっかり）＋ libr（はかり）→ はかりでよく量って考えると…？",
   etymologyConclusion:"de（すっかり）＋ libr（はかり）＋ ate（形容詞）＋ ly（～に）→ よくはかりにかけて考えたうえで＝故意に",
   why:"【なぜ】ラテン語 deliberare は「はかりにかけてよく量る」＝じっくり考える。よく考えて決めた行いは、うっかりではなく「わざと」したことになります。そこから「故意に」と「慎重に」の2つの意味が生まれました。\n【つながり】deliberate は形容詞で「故意の」。重さの単位ポンドの記号 lb も、同じ libra（はかり）から来ています。",
   spelling:"libr→liber（間に e が入った）",
   relatedWords:[
     {word:"deliberate",meaning:"故意の；熟考する",breakdown:"de（すっかり）＋ libr（はかり）＋ ate（形容詞）→ よく量って考えた"},
     {synonym:true,word:"on purpose",meaning:"わざと",breakdown:"やさしい言い方。deliberately とほぼ同じ"},
     {synonym:true,word:"carefully",meaning:"注意深く",breakdown:"気をつけて。deliberately は時間をかけて慎重に"},
     {synonym:true,word:"intentionally",meaning:"意図的に",breakdown:"意図して。deliberately はよく考えたうえで"}]},

  {id:1996,word:"exclusively",partOfSpeech:"副詞",meaning:"もっぱら，（～だけに）限って",
   meanings:["副|もっぱら，（～だけに）限って"],
   pronunciation:"/ɪkˈskluːsɪvli/",part:200,
   example:"This room is used exclusively by the brass band.",
   exampleJa:"この部屋は、もっぱら吹奏楽部が使っている。",
   example2:"The shop sells goods made exclusively in Japan.",
   exampleJa2:"その店は、日本だけに限って作られた商品を売っている。",
   etymologyProcess:"ex（外へ）＋ clude（閉じる）→ ほかを外に閉め出すと…？",
   etymologyConclusion:"ex（外へ）＋ clude（閉じる）＋ ive（形容詞）＋ ly（～に）→ ほかのものを外に閉め出して＝もっぱら",
   spelling:"clude→clus（過去分詞 clusus の形）",
   relatedWords:[
     {word:"include",meaning:"含む",breakdown:"in（中へ）＋ clude（閉じる）→ 中に閉じこめる"},
     {word:"exclude",meaning:"除外する",breakdown:"ex（外へ）＋ clude（閉じる）→ 外に閉め出す"},
     {word:"exclusive",meaning:"独占的な",breakdown:"ex（外へ）＋ clude（閉じる）＋ ive（形容詞）→ ほかを閉め出した"},
     {synonym:true,word:"only",meaning:"～だけ",breakdown:"～だけ。exclusively はほかを締め出して"}]},

  {id:1997,word:"hence",partOfSpeech:"副詞",meaning:"（前の内容を受けて）だから，それゆえ",
   meanings:["副|（前の内容を受けて）だから，それゆえ","副|今から（～後）"],
   pronunciation:"/hens/",part:200,
   example:"It rained all week, hence the small number of visitors.",
   exampleJa:"一週間ずっと雨だった。だから来場者が少なかった。",
   example2:"The final exam is two weeks hence, so start studying now.",
   exampleJa2:"期末試験は今から2週間後なので、今から勉強を始めなさい。",
   etymologyProcess:"hence（ここから）→ ここから先に続いて出てくるのは…？",
   etymologyConclusion:"hence（ここから）→ ここから先に当然続いて出てくる＝（前の内容を受けて）だから",
   etymologyMore:["今この時から先へ数えて→今から（～後）"],
   hook:"hence の後ろは名詞だけでもよい。hence the name で「だからその名がある」。",
   relatedWords:[
     {synonym:true,word:"therefore",meaning:"それゆえに",breakdown:"論理のつながりを示す。hence は後ろに名詞だけも置ける"},
     {synonym:true,word:"so",meaning:"だから",breakdown:"口語のふつうの「だから」。hence は硬い書き言葉"},
     {synonym:true,word:"thus",meaning:"このようにして，だから",breakdown:"hence とほぼ同じ硬い語。やり方も表す"},
     {synonym:true,word:"because",meaning:"なぜなら",breakdown:"理由を後ろに置く。hence は結果を後ろに置く"}]},

  {id:1998,word:"namely",partOfSpeech:"副詞",meaning:"すなわち，つまり",
   meanings:["副|すなわち，つまり"],
   pronunciation:"/ˈneɪmli/",part:200,
   example:"Two students were late today, namely Ken and Yuki.",
   exampleJa:"今日は生徒が2人遅刻した。すなわち、ケンとユキだ。",
   example2:"We need one thing to win, namely more practice.",
   exampleJa2:"勝つためには一つ必要なものがある。つまり、もっと練習することだ。",
   etymologyProcess:"name（名前）＋ ly（～に）→ はっきり名前を挙げて言えば…？",
   etymologyConclusion:"name（名前）＋ ly（～に）→ はっきり名前を挙げて言えば＝すなわち",
   relatedWords:[
     {word:"surname",meaning:"名字",breakdown:"sur（上から）＋ name（名前）→ 名前の上に付け足す名"},
     {word:"nickname",meaning:"あだ名",breakdown:"name（名前）→ 本名に付け足した呼び名"},
     {word:"rename",meaning:"名前を付け直す",breakdown:"re（再び）＋ name（名前）→ もう一度名前を付ける"},
     {synonym:true,word:"that is",meaning:"つまり",breakdown:"言いかえ。namely は具体的に名前や中身を挙げる"}]},

  {id:1999,word:"allegedly",partOfSpeech:"副詞",meaning:"（真偽は不明だが）伝えられるところによると",
   meanings:["副|（真偽は不明だが）伝えられるところによると"],
   pronunciation:"/əˈledʒɪdli/",part:200,
   example:"The man allegedly stole money from the school office.",
   exampleJa:"伝えられるところによると、その男は学校の事務室からお金を盗んだという。",
   example2:"The famous singer is allegedly planning to retire next year.",
   exampleJa2:"伝えられるところによると、その有名な歌手は来年引退する予定らしい。",
   etymologyProcess:"ad（～へ）＋ leg（任じる）→ 証拠として持ち出されただけだと…？",
   etymologyConclusion:"ad（～へ）＋ leg（任じる）＋ ed（～された）＋ ly（～に）→ 申し立てられただけで確かではないが＝（真偽は不明だが）伝えられるところによると",
   why:"【なぜ】ラテン語 allegare は「使いを送る」→「（証拠として）持ち出す」。allege は「証拠はまだないが…だと申し立てる」となり、allegedly は「本当かは分からないが、そう言われている」という報道でよく使う語になりました。フランス語の別の語が混じったという説もあります。\n【つながり】delegate（代表）も「使いを送る」の仲間です。",
   spelling:"ad→al（l の前で変化）",
   relatedWords:[
     {word:"allege",meaning:"（証拠なしに）申し立てる",breakdown:"ad（～へ）＋ leg（任じる）→ 証拠として持ち出す"},
     {word:"delegate",meaning:"代表",breakdown:"de（離れて）＋ leg（任じる）＋ ate（～にする）→ 任せて送り出された人"},
     {word:"colleague",meaning:"同僚",breakdown:"con（共に）＋ leg（任じる）→ 共に任された仲間"},
     {synonym:true,word:"rumor",meaning:"うわさ",breakdown:"確かでない話。allegedly はそう言われているが未確認"}]},

  {id:2000,word:"whereas",partOfSpeech:"接続詞",meaning:"～だが一方，～であるのに対して",
   meanings:["接|～だが一方，～であるのに対して"],
   pronunciation:"/werˈæz/",part:200,
   example:"My sister loves sports, whereas I prefer reading books at home.",
   exampleJa:"姉はスポーツが大好きだが一方、私は家で本を読むほうが好きだ。",
   example2:"Some students walk to school, whereas others come by bus.",
   exampleJa2:"歩いて通学する生徒もいるのに対して、バスで来る生徒もいる。",
   etymologyProcess:"where（どこ）→ 「この点では…、その点では」と並べると…？",
   etymologyConclusion:"where（どこ）→ 「こちらの点では」と二つを並べて比べる＝～だが一方",
   hook:"where ＋ as で「…の点では」。while と同じく前後の2つを対比する。",
   relatedWords:[
     {synonym:true,word:"while",meaning:"～する一方で",breakdown:"対比にも使う。whereas はより硬く、対比だけを表す"},
     {synonym:true,word:"but",meaning:"しかし",breakdown:"ふつうの逆接。whereas は2つを並べて比べる"},
     {synonym:true,word:"although",meaning:"～だけれども",breakdown:"譲歩を表す。whereas は対比を表す"},
     {synonym:true,word:"on the other hand",meaning:"他方では",breakdown:"文と文をつなぐ。whereas は1文の中でつなぐ"}]},
