  {id:1451,word:"paralyze",partOfSpeech:"他動詞",meaning:"麻痺させる；機能を止める",
   meanings:["他|（体を）麻痺させる","他|（交通などの）機能を止める"],
   pronunciation:"/ˈpærəlaɪz/",part:146,
   example:"A sudden stroke can paralyze the whole left side.",
   exampleJa:"突然の脳卒中は、左半身全体を麻痺させることがある。",
   example2:"Heavy snow paralyzed the city's train network for two days.",
   exampleJa2:"大雪が2日間、市の鉄道網の機能を止めた。",
   etymologyProcess:"para（そばで）＋ lys（ほどく）→ 体の片側で神経のつながりがほどけると…？",
   etymologyConclusion:"para（そばで）＋ lys（ほどく）→ 体の片側で神経のつながりがほどける＝麻痺させる",
   why:"【なぜ】ギリシャ語 paralysis は para（わきの・片側の）＋ lyein（ゆるめる）で「体の片側がゆるむこと」。もとは脳卒中で片側が動かなくなる状態を指し、そこから体の働きが止まること全体へ広がりました。\n【つながり】analyze（すっかりほどく）も lys の仲間。雪で電車が止まるように、組織や街の働きが止まるときにも使えます。",
   relatedWords:[
     {word:"analyze",meaning:"分析する",breakdown:"ana（すっかり）＋ lys（ほどく）→ 全体をすっかりほどいて中身を調べる"},
     {word:"analysis",meaning:"分析",breakdown:"ana（すっかり）＋ lys（ほどく）→ 全体をほどいて中身を並べること"},
     {word:"catalyst",meaning:"触媒；きっかけ",breakdown:"cata（下へ）＋ lys（ほどく）→ 結びつきをほどいて反応を進ませるもの"},
     {synonym:true,word:"numb",meaning:"感覚がない",breakdown:"寒さや薬で感覚が消えた状態。paralyze は動かせなくすること"}]},

  {id:1452,word:"prescribe",partOfSpeech:"他動詞",meaning:"（薬を）処方する；細かく指示する",
   meanings:["他|（薬）を処方する","他|（規則などが）～を細かく指示する"],
   pronunciation:"/prɪˈskraɪb/",part:146,
   example:"The doctor will prescribe a stronger medicine for your cough.",
   exampleJa:"医者はあなたのせきに、もっと強い薬を処方するだろう。",
   example2:"School rules prescribe exactly how students must wear their uniforms.",
   exampleJa2:"校則は、生徒が制服をどう着るべきかを細かく指示している。",
   etymologyProcess:"pre（先に）＋ scrib（書く）→ 医者が飲む前に紙へ書いて渡すのは…？",
   etymologyConclusion:"pre（先に）＋ scrib（書く）→ 患者が飲む前に医者が薬を紙に書いて示す＝処方する",
   relatedWords:[
     {word:"describe",meaning:"描写する",breakdown:"de（下へ）＋ scrib（書く）→ 見たままを紙の上へ書き写す"},
     {word:"subscribe",meaning:"定期購読する",breakdown:"sub（下で）＋ scrib（書く）→ 申込書の下に名前を書いて申しこむ"},
     {word:"script",meaning:"台本，文字",breakdown:"script（書く）→ 書かれたもの。役者のせりふを書いた紙"},
     {synonym:true,word:"order",meaning:"命じる",breakdown:"上から命じること。prescribe は医者や規則が細かく指定する"}]},

  {id:1453,word:"digest",partOfSpeech:"他動詞・自動詞",meaning:"消化する；（内容を）よく理解する",
   meanings:["他|（食べ物）を消化する","他|（情報）をよく理解する","自|消化する"],
   pronunciation:"/daɪˈdʒest/",part:146,
   example:"Warm milk helps the body digest food more easily.",
   exampleJa:"温かい牛乳は、体が食べ物をより楽に消化するのを助ける。",
   example2:"She digested the difficult article by reading it twice.",
   exampleJa2:"彼女はその難しい記事を、2回読んでよく理解した。",
   etymologyProcess:"di（離れて）＋ gest（運ぶ）→ 食べ物をばらばらにして運び分けると…？",
   etymologyConclusion:"di（離れて）＋ gest（運ぶ）→ 食べ物をばらばらにして体の各所へ運び分ける＝消化する",
   relatedWords:[
     {word:"suggest",meaning:"提案する",breakdown:"sug（下から）＋ gest（運ぶ）→ 下からそっと考えを差し出す"},
     {word:"gesture",meaning:"身ぶり",breakdown:"gest（運ぶ）＋ ure（名詞）→ 気持ちを体で運んで見せる動き"},
     {word:"register",meaning:"登録する",breakdown:"re（戻す）＋ gest（運ぶ）→ 記録として帳簿へ運び戻して書きとめる"},
     {synonym:true,word:"absorb",meaning:"吸収する",breakdown:"しみこませて取り込むこと。digest は分解してから取り込む"}]},

  {id:1454,word:"weary",partOfSpeech:"形容詞",meaning:"疲れ果てた；うんざりした",
   meanings:["形|疲れ果てた","形|（of ～で）～にうんざりした"],
   pronunciation:"/ˈwɪri/",part:146,
   example:"After the long march the soldiers looked very weary.",
   exampleJa:"長い行軍のあと、兵士たちはとても疲れ果てて見えた。",
   example2:"I grew weary of hearing the same excuse every morning.",
   exampleJa2:"毎朝同じ言い訳を聞かされて、私はうんざりした。",
   etymologyProcess:"weary（力が尽きた）→ 歩き続けて力が一滴も残っていないと…？",
   etymologyConclusion:"weary（力が尽きた）→ 歩き続けて力が一滴も残っていない＝疲れ果てた",
   hook:"古英語からの語で分解できない。be weary of ～（～にうんざりする）の形も大切。",
   relatedWords:[
     {synonym:true,word:"tired",meaning:"疲れた",breakdown:"ふつうの「疲れた」。weary は長く続いて力が尽きた状態"},
     {synonym:true,word:"exhausted",meaning:"疲れ果てた",breakdown:"力を全部くみ出された状態。weary は心のうんざり感も含む"},
     {synonym:true,word:"bored",meaning:"退屈した",breakdown:"あきていること。weary of ～ は「あきてうんざり」に近い"},
     {synonym:true,word:"fatigued",meaning:"疲労した",breakdown:"かたい言い方の「疲れた」。weary はうんざり感も含む"}]},

  {id:1455,word:"nourish",partOfSpeech:"他動詞",meaning:"栄養を与える；育む",
   meanings:["他|（体）に栄養を与える","他|（希望や才能）を育む"],
   pronunciation:"/ˈnɜːrɪʃ/",part:146,
   example:"Fresh vegetables nourish the body better than sweet snacks.",
   exampleJa:"新鮮な野菜は、甘いお菓子よりも体に栄養を与える。",
   example2:"Her kind words nourished my hope during that hard year.",
   exampleJa2:"彼女の優しい言葉は、つらい一年の間、私の希望を育んだ。",
   etymologyProcess:"nour（養い育てる）＋ ish（～にする）→ 食べ物を与えて体を育てると…？",
   etymologyConclusion:"nour（養い育てる）＋ ish（～にする）→ 食べ物を与えて体を育てる＝栄養を与える",
   relatedWords:[
     {word:"nurse",meaning:"看護師；世話をする",breakdown:"nurs（養い育てる）→ 弱った人を養い世話をする人"},
     {word:"nutrition",meaning:"栄養",breakdown:"nutri（養い育てる）＋ ion（名詞）→ 体を育てるもとになるもの"},
     {word:"nutritious",meaning:"栄養のある",breakdown:"nutri（養い育てる）＋ ous（形容詞）→ 体を育てる力を持った"},
     {synonym:true,word:"feed",meaning:"食べ物を与える",breakdown:"食べさせること。nourish は育つのに必要な栄養を与える"}]},

  {id:1456,word:"appalling",partOfSpeech:"形容詞",meaning:"ぞっとするような；ひどすぎる",
   meanings:["形|ぞっとするような","形|（質や態度が）ひどすぎる"],
   pronunciation:"/əˈpɔːlɪŋ/",part:146,
   example:"The living conditions in that camp were truly appalling.",
   exampleJa:"その収容所の生活環境は、本当にぞっとするようなものだった。",
   example2:"His appalling table manners shocked everyone at the party.",
   exampleJa2:"彼のひどすぎるテーブルマナーは、パーティーの全員を驚かせた。",
   etymologyProcess:"ap（～へ）＋ pall（青ざめる）＋ ing（形容詞）→ 顔から血の気が引くほどだと…？",
   etymologyConclusion:"ap（～へ）＋ pall（青ざめる）＋ ing（形容詞）→ 見た人の顔が青ざめるほどひどい＝ぞっとするような",
   relatedWords:[
     {word:"pale",meaning:"青白い，薄い",breakdown:"pall（青ざめる）→ 血の気が引いて色が白っぽい"},
     {synonym:true,word:"horrible",meaning:"恐ろしい",breakdown:"こわくていやな感じ。appalling は「ひどすぎる」と責める気持ちが強い"},
     {synonym:true,word:"shocking",meaning:"衝撃的な",breakdown:"強い驚きを与えること。appalling は不快さのほうが前に出る"},
     {synonym:true,word:"dreadful",meaning:"ひどい",breakdown:"very bad のかたい言い方。appalling はさらに程度が強い"}]},

  {id:1457,word:"flesh",partOfSpeech:"名詞",meaning:"（骨に対する）肉，身；果肉",
   meanings:["名|（骨に対する）肉，身","名|（果物の）果肉"],
   pronunciation:"/fleʃ/",part:146,
   example:"The sharp knife cut deep into the soft flesh.",
   exampleJa:"その鋭いナイフは、柔らかい肉に深く切りこんだ。",
   example2:"The flesh of this ripe peach is sweet and juicy.",
   exampleJa2:"この熟した桃の果肉は、甘くて汁が多い。",
   etymologyProcess:"flesh（体をおおう身）→ 皮の下、骨の上にあるやわらかい部分は…？",
   etymologyConclusion:"flesh（体をおおう身）→ 皮の下、骨の上についたやわらかい部分＝（骨に対する）肉，身",
   hook:"古英語 flæsc から。食べ物としての meat と違い、体についている「身」そのもの。",
   relatedWords:[
     {synonym:true,word:"meat",meaning:"食用の肉",breakdown:"食べ物としての肉。flesh は体についている生の身"},
     {synonym:true,word:"tissue",meaning:"（体の）組織",breakdown:"体をつくる細胞のまとまり。flesh は目に見える身の部分"},
     {synonym:true,word:"muscle",meaning:"筋肉",breakdown:"力を出す筋。flesh は皮と骨の間の部分全体を指す"},
     {synonym:true,word:"pulp",meaning:"果肉，どろどろしたもの",breakdown:"果物のやわらかい中身。flesh も果肉の意味で使える"}]},

  {id:1458,word:"limb",partOfSpeech:"名詞",meaning:"（腕や脚の）手足；大枝",
   meanings:["名|（腕や脚の一本を指して）手足","名|（木の）大枝"],
   pronunciation:"/lɪm/",part:146,
   example:"The accident left him unable to move one limb.",
   exampleJa:"その事故で彼は手足の一本を動かせなくなった。",
   example2:"A heavy limb broke off the old oak tree yesterday.",
   exampleJa2:"昨日、太い大枝がその古いオークの木から折れて落ちた。",
   etymologyProcess:"limb（体から伸びた部分）→ 胴から枝のように伸びているものは…？",
   etymologyConclusion:"limb（体から伸びた部分）→ 胴から枝のように伸びている部分＝（腕や脚の）手足",
   hook:"古英語 lim から。木の「大枝」も同じ語。体から枝分かれして出た部分、と覚える。",
   relatedWords:[
     {synonym:true,word:"arm",meaning:"腕",breakdown:"上の手足。limb は腕と脚をまとめて指す言い方"},
     {synonym:true,word:"leg",meaning:"脚",breakdown:"下の手足。limb は腕と脚のどちらにも使える"},
     {synonym:true,word:"branch",meaning:"枝",breakdown:"木の枝。limb はその中でも太い大枝を指す"},
     {synonym:true,word:"extremity",meaning:"手足（の先）",breakdown:"かたい語。limb は腕や脚の一本一本"}]},

  {id:1459,word:"erect",partOfSpeech:"形容詞",meaning:"直立した；姿勢がまっすぐな",
   meanings:["形|直立した，まっすぐ立った","他|（建物や像）を建てる"],
   pronunciation:"/ɪˈrekt/",part:146,
   example:"He stood erect in front of the whole class.",
   exampleJa:"彼はクラス全員の前で直立していた。",
   example2:"The city erected a tall bronze statue in the park.",
   exampleJa2:"市は公園に高いブロンズ像を建てた。",
   etymologyProcess:"e（外へ）＋ rect（まっすぐ）→ 体や柱をまっすぐ上へ起こすと…？",
   etymologyConclusion:"e（外へ）＋ rect（まっすぐ）→ 体や柱をまっすぐ上へ起こしてある＝直立した",
   relatedWords:[
     {word:"correct",meaning:"正しい；訂正する",breakdown:"com（すっかり）＋ rect（まっすぐ）→ 曲がりをすっかりまっすぐに直す"},
     {word:"direct",meaning:"直接の",breakdown:"di（離れて）＋ rect（まっすぐ）→ よそへそれずまっすぐ向かう"},
     {word:"rectangle",meaning:"長方形",breakdown:"rect（まっすぐ）＋ angle（角）→ 角がまっすぐに立った四角形"},
     {synonym:true,word:"upright",meaning:"まっすぐ立った",breakdown:"やさしい言い方。erect は硬い語で姿勢や建造物に使う"}]},

  {id:1460,word:"spinal",partOfSpeech:"形容詞",meaning:"背骨の，脊椎の",
   meanings:["形|背骨の，脊椎の"],
   pronunciation:"/ˈspaɪnl/",part:146,
   example:"The doctor carefully examined the young boy's spinal injury.",
   exampleJa:"医者はその少年の背骨のけがを注意深く調べた。",
   example2:"Regular swimming can reduce spinal pain caused by bad posture.",
   exampleJa2:"定期的に泳ぐことで、悪い姿勢による背骨の痛みを減らせる。",
   etymologyProcess:"spina（とげ）＋ al（形容詞）→ 背中に一列に並ぶ、とげのような骨なら…？",
   etymologyConclusion:"spina（とげ）＋ al（形容詞）→ 背中に一列に並ぶ、とげのような骨の＝背骨の，脊椎の",
   relatedWords:[
     {word:"spine",meaning:"背骨；とげ",breakdown:"spina（とげ）→ 背中を通る、とげのように尖った骨の列"},
     {synonym:true,word:"backbone",meaning:"背骨",breakdown:"やさしい言い方。spinal はその形容詞形で医学に使う"},
     {synonym:true,word:"vertebral",meaning:"脊椎の",breakdown:"医学のかたい語。spinal のほうがふつう"},
     {word:"spiny",meaning:"とげだらけの",breakdown:"spina（とげ）＋ y（形容詞）→ とげがいっぱい生えている"}]},

  {id:1461,word:"suck",partOfSpeech:"他動詞・自動詞",meaning:"吸う，吸い込む",
   meanings:["他|（液体など）を吸う，吸い込む","自|吸いつく"],
   pronunciation:"/sʌk/",part:147,
   example:"The baby began to suck milk from the bottle.",
   exampleJa:"赤ちゃんは哺乳びんからミルクを吸い始めた。",
   example2:"The powerful pump sucked all the muddy water out quickly.",
   exampleJa2:"その強力なポンプは、泥水をすべて素早く吸い出した。",
   etymologyProcess:"suck（口で吸い込む）→ 口や管をすぼめて中へ引き入れると…？",
   etymologyConclusion:"suck（口で吸い込む）→ 口や管をすぼめて液体を中へ引き入れる＝吸う",
   hook:"古英語 sucan から。吸う音をまねてできた語とされ、これ以上は分解できない。",
   relatedWords:[
     {synonym:true,word:"drink",meaning:"飲む",breakdown:"口から体へ入れること。suck は吸い込む動きそのものに注目する"},
     {synonym:true,word:"sip",meaning:"少しずつ飲む",breakdown:"ちびちび口にすること。suck は一気に引き入れる感じ"},
     {synonym:true,word:"absorb",meaning:"吸収する",breakdown:"しみこませて取り込むこと。suck は口や管で引き入れる"},
     {synonym:true,word:"inhale",meaning:"息を吸いこむ",breakdown:"空気を吸うこと。suck は液体や物を吸うときにも使う"}]},

  {id:1462,word:"shrug",partOfSpeech:"他動詞・自動詞",meaning:"肩をすくめる",
   meanings:["他|（肩）をすくめる","自|肩をすくめる"],
   pronunciation:"/ʃrʌɡ/",part:147,
   example:"He could only shrug his shoulders at my question.",
   exampleJa:"彼は私の質問に肩をすくめることしかできなかった。",
   example2:"She shrugged and walked away without saying a single word.",
   exampleJa2:"彼女は肩をすくめて、一言も言わずに歩き去った。",
   etymologyProcess:"shrug（肩を上げる）→ 分からないときに肩をひょいと上げると…？",
   etymologyConclusion:"shrug（肩を上げる）→ さあねという気持ちで肩をひょいと上げる＝肩をすくめる",
   hook:"中英語からの語で語源ははっきりしない。shrug off（～を軽く受け流す）も覚える。",
   relatedWords:[
     {synonym:true,word:"shoulder",meaning:"肩",breakdown:"上げる部分そのもの。shrug はその肩を上げる動作を表す"},
     {synonym:true,word:"nod",meaning:"うなずく",breakdown:"首で「はい」を示す。shrug は肩で「さあね」を示す"},
     {synonym:true,word:"gesture",meaning:"身ぶり",breakdown:"体で気持ちを伝える動き。shrug はその代表的な一つ"},
     {synonym:true,word:"frown",meaning:"顔をしかめる",breakdown:"眉を寄せて不満を示す。shrug は肩で「さあね」を示す"}]},

  {id:1463,word:"compensate",partOfSpeech:"他動詞・自動詞",meaning:"補償する；埋め合わせる",
   meanings:["他|（損害）を補償する","自|（for ～で）～を埋め合わせる"],
   pronunciation:"/ˈkɑːmpənseɪt/",part:147,
   example:"The company must compensate every worker for the lost wages.",
   exampleJa:"会社は失われた賃金について、全労働者に補償しなければならない。",
   example2:"She compensated for her small size with amazing speed.",
   exampleJa2:"彼女は体の小ささを、驚くような速さで埋め合わせた。",
   etymologyProcess:"com（共に）＋ pens（重さを量る）＋ ate（動詞）→ 減った分と同じ重さを返すと…？",
   etymologyConclusion:"com（共に）＋ pens（重さを量る）＋ ate（動詞）→ 減った分と釣り合う重さをのせて返す＝補償する",
   relatedWords:[
     {word:"expense",meaning:"費用",breakdown:"ex（外へ）＋ pens（重さを量る）→ 銀貨を量って外へ払い出すお金"},
     {word:"pension",meaning:"年金",breakdown:"pens（重さを量る）＋ ion（名詞）→ 量って定期的に渡されるお金"},
     {word:"dispense",meaning:"分配する",breakdown:"dis（離れて）＋ pens（重さを量る）→ 量って分けて配る"},
     {synonym:true,word:"repay",meaning:"返済する",breakdown:"借りを返すこと。compensate は損をした分を埋め合わせる"}]},

  {id:1464,word:"abuse",partOfSpeech:"名詞",meaning:"虐待，酷使；乱用",
   meanings:["名|虐待，酷使","名|（権力などの）乱用","他|～を虐待する，乱用する"],
   pronunciation:"/əˈbjuːs/",part:147,
   example:"The charity helps children who suffer abuse at home.",
   exampleJa:"その慈善団体は、家庭で虐待を受けている子どもを助けている。",
   example2:"The report described a clear abuse of political power.",
   exampleJa2:"その報告書は、政治権力の明らかな乱用を書いていた。",
   etymologyProcess:"ab（離れて）＋ use（使う）→ 正しい使い方から離れた扱いなら…？",
   etymologyConclusion:"ab（離れて）＋ use（使う）→ 正しい使い方から離れた、ひどい扱い＝虐待",
   relatedWords:[
     {word:"use",meaning:"使う",breakdown:"use（使う）→ 道具や力を役立てる"},
     {word:"useful",meaning:"役に立つ",breakdown:"use（使う）＋ ful（満ちた）→ 使いでがたっぷりある"},
     {word:"absent",meaning:"欠席の",breakdown:"ab（離れて）＋ sent（いる）→ その場から離れていて、そこにいない"},
     {synonym:true,word:"misuse",meaning:"誤用",breakdown:"間違った使い方。abuse は人を傷つけるほどひどい扱い"}]},

  {id:1465,word:"bias",partOfSpeech:"名詞",meaning:"（一方への）かたより，先入観",
   meanings:["名|（一方への）かたより，先入観","他|～をかたよらせる"],
   pronunciation:"/ˈbaɪəs/",part:147,
   example:"The report showed a clear bias against younger workers.",
   exampleJa:"その報告書は、若い労働者に対する明らかなかたよりを示していた。",
   example2:"A good judge must decide without personal bias or anger.",
   exampleJa2:"よい裁判官は、個人的なかたよりや怒りなしに判断しなければならない。",
   etymologyProcess:"bias（斜めに走る線）→ まっすぐでなく一方へ傾いていると…？",
   etymologyConclusion:"bias（斜めに走る線）→ まっすぐでなく、一方へ斜めに傾いている＝（一方への）かたより",
   hook:"布を「バイアス（斜め）に裁つ」の語。ボウルズで球が斜めに曲がる性質も bias と呼んだ。",
   relatedWords:[
     {synonym:true,word:"prejudice",meaning:"偏見",breakdown:"前もって決めつける悪い考え。bias は好みのかたよりにも使う"},
     {synonym:true,word:"partiality",meaning:"えこひいき",breakdown:"一方に肩入れすること。bias はかたより全般"},
     {synonym:true,word:"tendency",meaning:"傾向",breakdown:"そうなりやすいこと。bias は一方に偏った見方を指す"},
     {synonym:true,word:"slant",meaning:"傾き；かたよった見方",breakdown:"斜めであること。bias とほぼ同じ絵が浮かぶ語"}]},

  {id:1466,word:"prestige",partOfSpeech:"名詞",meaning:"（実績からくる）名声，威信",
   meanings:["名|（実績からくる）名声，威信"],
   pronunciation:"/preˈstiːʒ/",part:147,
   example:"That old university still enjoys great prestige in Europe.",
   exampleJa:"あの古い大学は今もヨーロッパで大きな名声を保っている。",
   example2:"Winning the national contest brought her prestige at school.",
   exampleJa2:"全国大会での優勝は、彼女に学校での名声をもたらした。",
   etymologyProcess:"pre（先に）＋ stig（締めつける）→ 見る人の目を先にくらませると…？",
   etymologyConclusion:"pre（先に）＋ stig（締めつける）→ 見る人の目をくらませ、逆らえなくさせる輝き＝名声",
   why:"【なぜ】ラテン語 praestigium はもと「手品・目くらまし」。praestringere（目を締めつけてくらませる）からできた語で、17世紀の英語でも「まやかし」を指しました。18世紀に「人を圧倒する魅力」へ移り、今の「名声」になりました。\n【つながり】strict や restrict と同じ「きつく締める」family。今も「近寄りがたい輝き」という手ざわりが残っています。",
   relatedWords:[
     {word:"strict",meaning:"厳しい",breakdown:"strict（締めつける）→ ゆるみを許さず、きつく締める"},
     {word:"restrict",meaning:"制限する",breakdown:"re（強く）＋ strict（締めつける）→ 範囲を強く締めて外へ出さない"},
     {word:"stress",meaning:"圧力，強調",breakdown:"stress（締めつける）→ 心や物をぎゅっと締めつける力"},
     {synonym:true,word:"reputation",meaning:"評判",breakdown:"世間の評価。prestige はうらやまれるほど高い評価を指す"}]},

  {id:1467,word:"privilege",partOfSpeech:"名詞",meaning:"特権，特別な権利",
   meanings:["名|特権，特別な権利"],
   pronunciation:"/ˈprɪvəlɪdʒ/",part:147,
   example:"Only members enjoy the privilege of using this old library.",
   exampleJa:"会員だけが、この古い図書館を使う特権を持っている。",
   example2:"Education should be a right, not a privilege for rich families.",
   exampleJa2:"教育は権利であるべきで、裕福な家庭のための特権であってはならない。",
   etymologyProcess:"privi（個人の）＋ leg（法）→ その人ひとりのために作られた法なら…？",
   etymologyConclusion:"privi（個人の）＋ leg（法）→ その人だけのために作られた法が認める権利＝特権",
   relatedWords:[
     {word:"private",meaning:"個人の，私的な",breakdown:"privi（個人の）＋ ate（形容詞）→ 自分ひとりのもので他人を入れない"},
     {word:"legal",meaning:"法律の",breakdown:"leg（法）＋ al（形容詞）→ 法で定められているとおりの"},
     {word:"deprive",meaning:"奪う",breakdown:"de（離して）＋ priv（個人の）→ その人のものを取り上げて切り離す"},
     {synonym:true,word:"right",meaning:"権利",breakdown:"だれもが持つ権利。privilege は一部の人だけに与えられる"}]},

  {id:1468,word:"feat",partOfSpeech:"名詞",meaning:"（見事な）偉業，離れ業",
   meanings:["名|（見事な）偉業，離れ業"],
   pronunciation:"/fiːt/",part:147,
   example:"Climbing that icy mountain alone was an amazing feat.",
   exampleJa:"あの氷の山にひとりで登ったのは、見事な偉業だった。",
   example2:"Her feat of memory impressed the whole science class.",
   exampleJa2:"彼女の記憶力の離れ業は、理科のクラス全体を感心させた。",
   etymologyProcess:"feat（作る）→ 作品と呼べるほど見事にやってのけた行いは…？",
   etymologyConclusion:"feat（作る）→ 作品と呼べるほど見事にやってのけた行い＝（見事な）偉業",
   relatedWords:[
     {word:"factory",meaning:"工場",breakdown:"fact（作る）＋ ory（場所）→ ものを作る場所"},
     {word:"perfect",meaning:"完全な",breakdown:"per（すっかり）＋ fect（作る）→ すっかり作り上げて足りないところがない"},
     {word:"manufacture",meaning:"製造する",breakdown:"manu（手）＋ fact（作る）→ もとは手で作ること。今は工場で大量に作る"},
     {synonym:true,word:"achievement",meaning:"業績",breakdown:"やりとげたこと。feat は見ていて驚くような離れ業を指す"}]},

  {id:1469,word:"dignity",partOfSpeech:"名詞",meaning:"威厳，尊厳",
   meanings:["名|威厳，尊厳"],
   pronunciation:"/ˈdɪɡnəti/",part:147,
   example:"The old teacher answered the rude question with quiet dignity.",
   exampleJa:"年老いた先生は、その失礼な質問に静かな威厳をもって答えた。",
   example2:"Every patient deserves to be treated with dignity and care.",
   exampleJa2:"どの患者も、尊厳と思いやりをもって扱われるに値する。",
   etymologyProcess:"dign（価値がある）＋ ity（名詞）→ この人は重んじるに値すると感じさせるのは…？",
   etymologyConclusion:"dign（価値がある）＋ ity（名詞）→ この人は重んじるに値すると感じさせる様子＝威厳",
   relatedWords:[
     {word:"indignant",meaning:"憤慨した",breakdown:"in（否定）＋ dign（価値がある）→ 自分の値打ちを認められず腹を立てる"},
     {word:"disdain",meaning:"軽蔑する",breakdown:"dis（否定）＋ dain（価値がある）→ 値打ちがないと決めつけて見下す"},
     {synonym:true,word:"pride",meaning:"誇り",breakdown:"自分を誇る気持ち。dignity は他人から重んじられる落ち着き"},
     {synonym:true,word:"respect",meaning:"尊敬",breakdown:"相手を重んじること。dignity はそれに値する本人の様子"}]},

  {id:1470,word:"virtue",partOfSpeech:"名詞",meaning:"美徳，徳；長所",
   meanings:["名|美徳，徳","名|長所，利点"],
   pronunciation:"/ˈvɜːrtʃuː/",part:147,
   example:"Patience is a virtue that every good teacher needs.",
   exampleJa:"忍耐は、よい教師ならだれもが必要とする美徳だ。",
   example2:"The main virtue of this plan is its simplicity.",
   exampleJa2:"この計画のいちばんの長所は、その簡単さだ。",
   etymologyProcess:"virt（男らしい力）→ 人として持つべき内側の強さと正しさは…？",
   etymologyConclusion:"virt（男らしい力）→ 人として持つべき、内側の強さと正しさ＝美徳",
   why:"【なぜ】ラテン語 virtus は vir（男）から出た語で、もとは「男らしさ・勇気」。ローマでは戦場での勇気を指しました。やがて戦い以外の場面へ広がり、キリスト教の時代に「人として持つべき正しさ」＝美徳になりました。\n【つながり】virtual（中身の力を持った）も同じ家族。by virtue of ～（～のおかげで）には「～の力によって」という古い意味が残っています。",
   relatedWords:[
     {word:"virtual",meaning:"事実上の；仮想の",breakdown:"virt（男らしい力）＋ al（形容詞）→ 見た目でなく中身の力を持った"},
     {word:"virtuous",meaning:"徳の高い",breakdown:"virt（男らしい力）＋ ous（形容詞）→ 正しさの力に満ちている"},
     {synonym:true,word:"honesty",meaning:"正直さ",breakdown:"うそをつかないこと。virtue は徳ぜんぱんをまとめて指す"},
     {synonym:true,word:"merit",meaning:"長所，利点",breakdown:"よい点。virtue も「長所」の意味で同じように使える"}]},

  {id:1471,word:"aristocracy",partOfSpeech:"名詞",meaning:"貴族（階級）",
   meanings:["名|貴族（階級）","名|貴族政治"],
   pronunciation:"/ˌærɪˈstɑːkrəsi/",part:148,
   example:"The old aristocracy still owns much land in the countryside.",
   exampleJa:"古い貴族階級は、今も田舎に多くの土地を持っている。",
   example2:"In that novel, the aristocracy looks down on merchants.",
   exampleJa2:"その小説では、貴族階級が商人を見下している。",
   etymologyProcess:"arist（最もすぐれた）＋ cracy（支配）→ 最もすぐれた者が国を支配すると…？",
   etymologyConclusion:"arist（最もすぐれた）＋ cracy（支配）→ 最もすぐれた者が国を支配する、その人たち＝貴族（階級）",
   relatedWords:[
     {word:"democracy",meaning:"民主主義",breakdown:"demo（民衆）＋ cracy（支配）→ 民衆が自分たちで国を治める仕組み"},
     {word:"aristocrat",meaning:"貴族の一員",breakdown:"arist（最もすぐれた）＋ crat（支配）→ 支配する側に生まれた人"},
     {synonym:true,word:"noble",meaning:"貴族の；高貴な",breakdown:"身分が高いこと。aristocracy はその人たち全体を指す"},
     {synonym:true,word:"nobility",meaning:"貴族（全体）",breakdown:"貴族の人たち全体。aristocracy は支配する特権階級という面が強い"}]},

  {id:1472,word:"rebel",partOfSpeech:"名詞",meaning:"反逆者，反抗する人",
   meanings:["名|反逆者，反抗する人","自|（against ～に）反抗する（発音は /rɪˈbel/）"],
   pronunciation:"/ˈrebl/",part:148,
   example:"A young rebel led the villagers against the cruel king.",
   exampleJa:"若い反逆者が、残酷な王に対して村人たちを率いた。",
   example2:"Teenagers often rebel against their parents' strict rules.",
   exampleJa2:"十代の若者は、親の厳しい決まりによく反抗する。",
   etymologyProcess:"re（再び）＋ bel（戦い）→ 負かされた者が再び戦いを起こすと…？",
   etymologyConclusion:"re（再び）＋ bel（戦い）→ 従わされた側が再び戦いを起こす人＝反逆者",
   relatedWords:[
     {word:"rebellion",meaning:"反乱",breakdown:"re（再び）＋ bel（戦い）＋ ion（名詞）→ 逆らって戦いを起こすこと"},
     {word:"rebellious",meaning:"反抗的な",breakdown:"re（再び）＋ bel（戦い）＋ ous（形容詞）→ 逆らって戦う気持ちに満ちた"},
     {synonym:true,word:"protest",meaning:"抗議する",breakdown:"反対の声を上げること。rebel は力で逆らうところまで行く"},
     {synonym:true,word:"revolt",meaning:"反乱を起こす",breakdown:"支配をひっくり返そうとすること。rebel は逆らう人そのもの"}]},

  {id:1473,word:"scheme",partOfSpeech:"名詞",meaning:"（周到な）計画；たくらみ",
   meanings:["名|（周到な）計画，制度","名|たくらみ，陰謀"],
   pronunciation:"/skiːm/",part:148,
   example:"The city announced a new scheme to reduce heavy traffic.",
   exampleJa:"市は、ひどい渋滞を減らすための新しい計画を発表した。",
   example2:"They invented a clever scheme to cheat the old man.",
   exampleJa2:"彼らは老人をだますための巧みなたくらみを考え出した。",
   etymologyProcess:"schem（形）→ 頭の中で組み立てた、きちんとした形のものは…？",
   etymologyConclusion:"schem（形）→ 頭の中で組み立てた、きちんとした形の段取り＝（周到な）計画",
   why:"【なぜ】ギリシャ語 skhēma は「形・すがた」。英語には16世紀に「図・組み立て図」として入り、そこから「頭の中で組み立てた段取り」＝計画になりました。裏で細かく組み立てるという感じが強いので、悪い「たくらみ」にも使われます。\n【つながり】図の意味を今も残しているのが schematic（図解の）です。よい計画にも悪だくみにも使える点に注意しましょう。",
   relatedWords:[
     {word:"schematic",meaning:"図解の",breakdown:"schem（形）＋ ic（形容詞）→ 形だけを取り出して図にした"},
     {synonym:true,word:"plan",meaning:"計画",breakdown:"ふつうの計画。scheme は細かく組み立てた大がかりなもの"},
     {synonym:true,word:"plot",meaning:"陰謀；筋書き",breakdown:"ひそかなたくらみ。scheme はよい計画にも使える"},
     {synonym:true,word:"project",meaning:"事業，計画",breakdown:"前へ投げ出す大きな企て。scheme は段取りの細かさが中心"}]},

  {id:1474,word:"convention",partOfSpeech:"名詞",meaning:"（大規模な）大会；慣習",
   meanings:["名|（大規模な）大会，集会","名|慣習，しきたり"],
   pronunciation:"/kənˈvenʃn/",part:148,
   example:"Thousands of doctors attended the medical convention last week.",
   exampleJa:"何千人もの医師が、先週その医学の大会に参加した。",
   example2:"Bowing is a long-standing convention in Japanese schools.",
   exampleJa2:"おじぎは、日本の学校の古くからの慣習だ。",
   etymologyProcess:"con（共に）＋ vent（来る）＋ ion（名詞）→ 大勢が一か所に集まってくると…？",
   etymologyConclusion:"con（共に）＋ vent（来る）＋ ion（名詞）→ 大勢が一か所に集まってくること＝（大規模な）大会",
   why:"【なぜ】ラテン語 convenire は「共に来る・集まる」。集まって話し合って決めたことが、そのまま「みんなの取り決め」になり、やがて「だれもが守るしきたり」＝慣習の意味が生まれました。\n【つながり】convenient（必要なものが一緒に来ていて都合がよい）も同じ家族。大会も慣習も「みんなで集まって合わせる」から出ています。",
   relatedWords:[
     {word:"convenient",meaning:"便利な",breakdown:"con（共に）＋ ven（来る）→ 必要なものが一緒に来ていて都合がよい"},
     {word:"event",meaning:"出来事",breakdown:"e（外へ）＋ vent（来る）→ 外に現れ出てきたこと"},
     {word:"invent",meaning:"発明する",breakdown:"in（上に）＋ vent（来る）→ ふと思いつきに行き当たって形にする"},
     {synonym:true,word:"custom",meaning:"慣習",breakdown:"昔からのならわし。convention は社会全体の暗黙の取り決め"}]},

  {id:1475,word:"conference",partOfSpeech:"名詞",meaning:"（話し合いのための）会議，協議会",
   meanings:["名|（話し合いのための）会議，協議会"],
   pronunciation:"/ˈkɑːnfərəns/",part:148,
   example:"The climate conference brought leaders from many countries together.",
   exampleJa:"その気候会議は、多くの国の指導者を一堂に集めた。",
   example2:"Our teachers hold a conference with parents every autumn.",
   exampleJa2:"うちの先生たちは、毎秋、保護者との会議を開く。",
   etymologyProcess:"con（共に）＋ fer（運ぶ）＋ ence（名詞）→ 意見を一か所へ運び寄せると…？",
   etymologyConclusion:"con（共に）＋ fer（運ぶ）＋ ence（名詞）→ 意見を一か所へ運び寄せる場＝（話し合いのための）会議，協議会",
   relatedWords:[
     {word:"transfer",meaning:"移す",breakdown:"trans（越えて）＋ fer（運ぶ）→ 境を越えて別の場所へ運ぶ"},
     {word:"offer",meaning:"申し出る",breakdown:"of（相手のほうへ）＋ fer（運ぶ）→ 差し出すようにして運ぶ"},
     {word:"prefer",meaning:"より好む",breakdown:"pre（先に）＋ fer（運ぶ）→ こちらを先に運び出すほど気に入る"},
     {synonym:true,word:"meeting",meaning:"会合",breakdown:"人が集まること全般。conference は正式で大きめの話し合い"}]},

  {id:1476,word:"consent",partOfSpeech:"名詞",meaning:"（正式な）同意，承諾",
   meanings:["名|（正式な）同意，承諾","自|（to ～に）同意する"],
   pronunciation:"/kənˈsent/",part:148,
   example:"The hospital needs written consent from both of the parents.",
   exampleJa:"病院は、両親そろっての書面での同意を必要としている。",
   example2:"She gave her consent to the plan without hesitating.",
   exampleJa2:"彼女はためらわずにその計画に同意した。",
   etymologyProcess:"con（共に）＋ sens（感じる）→ 相手と同じように感じていると示すと…？",
   etymologyConclusion:"con（共に）＋ sens（感じる）→ 相手と同じ気持ちだと示して認める＝（正式な）同意，承諾",
   relatedWords:[
     {word:"sense",meaning:"感覚；意味",breakdown:"sens（感じる）→ 体や心で受け取るはたらき"},
     {word:"sensitive",meaning:"敏感な",breakdown:"sens（感じる）＋ ive（形容詞）→ わずかな違いもすぐ感じ取る"},
     {word:"consensus",meaning:"（全員の）意見の一致",breakdown:"con（共に）＋ sens（感じる）→ 全員が同じように感じている状態"},
     {synonym:true,word:"permission",meaning:"許可",breakdown:"してよいと許すこと。consent は本人が納得して認めること"}]},

  {id:1477,word:"initiative",partOfSpeech:"名詞",meaning:"新構想；主導権",
   meanings:["名|新構想，新しい取り組み","名|主導権，率先"],
   pronunciation:"/ɪˈnɪʃətɪv/",part:148,
   example:"The government launched a new initiative to help young farmers.",
   exampleJa:"政府は、若い農家を助ける新構想を始めた。",
   example2:"She took the initiative and organized the whole school festival.",
   exampleJa2:"彼女は主導権を取って、学園祭全体をまとめ上げた。",
   etymologyProcess:"in（中へ）＋ it（行く）＋ ive（～な性質の）→ だれより先に中へ踏み込むなら…？",
   etymologyConclusion:"in（中へ）＋ it（行く）＋ ive（～な性質の）→ だれより先に中へ踏み込んで始めること＝新構想",
   why:"【なぜ】ラテン語 initium は in（中へ）＋ ire（行く）で「中へ入ること」＝始まり。そこから「最初に動き出すこと」の意味が生まれ、人について言えば「主導権」、事業について言えば「新しく始める取り組み」＝新構想になりました。\n【つながり】initial（最初の）、exit（外へ行く）も同じ ire の家族です。",
   relatedWords:[
     {word:"initial",meaning:"最初の",breakdown:"in（中へ）＋ it（行く）＋ al（形容詞）→ いちばん先に中へ入る"},
     {word:"exit",meaning:"出口",breakdown:"ex（外へ）＋ it（行く）→ 外へ出ていくところ"},
     {word:"transit",meaning:"通過，輸送",breakdown:"trans（越えて）＋ it（行く）→ 向こうへ越えて行くこと"},
     {synonym:true,word:"lead",meaning:"導く",breakdown:"先に立って進むこと。initiative は最初に動き出す力"}]},

  {id:1478,word:"province",partOfSpeech:"名詞",meaning:"（国の中の）州，地方",
   meanings:["名|（国の中の）州","名|（首都から離れた）地方"],
   pronunciation:"/ˈprɑːvɪns/",part:148,
   example:"Canada has ten provinces and three large northern territories.",
   exampleJa:"カナダには10の州と、3つの大きな北部準州がある。",
   example2:"He grew up in a quiet province far from the capital.",
   exampleJa2:"彼は首都から遠い静かな地方で育った。",
   etymologyProcess:"provinc（ローマが治めた地）→ 首都から離れ、総督が送られる土地は…？",
   etymologyConclusion:"provinc（ローマが治めた地）→ 首都から離れ、送られた総督が治める土地＝（国の中の）州",
   hook:"ラテン語 provincia（ローマが治める地方）から。それより前の語源ははっきりしない。",
   relatedWords:[
     {word:"provincial",meaning:"地方の；いなかくさい",breakdown:"provinc（ローマが治めた地）＋ al（形容詞）→ 首都から離れた土地の"},
     {synonym:true,word:"state",meaning:"州",breakdown:"アメリカなどの州。province はカナダや中国などで使う"},
     {synonym:true,word:"region",meaning:"地域",breakdown:"広がりとしての地域。province は行政で区切られた単位"},
     {synonym:true,word:"district",meaning:"地区",breakdown:"区切られた地域。province は国のすぐ下の大きな区分"}]},

  {id:1479,word:"colony",partOfSpeech:"名詞",meaning:"植民地；（生物の）群れ",
   meanings:["名|植民地","名|（アリなどの）群れ，集団"],
   pronunciation:"/ˈkɑːləni/",part:148,
   example:"That island was once a colony of a European country.",
   exampleJa:"あの島はかつて、あるヨーロッパの国の植民地だった。",
   example2:"A large colony of ants lives under our school yard.",
   exampleJa2:"大きなアリの群れが、うちの校庭の下に住んでいる。",
   etymologyProcess:"colon（耕す）＋ y（名詞）→ 人が移り住んで土地を耕す場所なら…？",
   etymologyConclusion:"colon（耕す）＋ y（名詞）→ 人が海を越えて移り住み、土地を耕す場所＝植民地",
   relatedWords:[
     {word:"culture",meaning:"文化；栽培",breakdown:"cult（耕す）＋ ure（名詞）→ 土地や心を耕して育てたもの"},
     {word:"agriculture",meaning:"農業",breakdown:"agri（畑）＋ cult（耕す）＋ ure（名詞）→ 畑を耕して作物を育てること"},
     {word:"colonial",meaning:"植民地の",breakdown:"colon（耕す）＋ ial（形容詞）→ 移り住んで耕した土地の"},
     {synonym:true,word:"settlement",meaning:"入植地",breakdown:"人が住みついた場所。colony は本国が支配し続ける土地"}]},

  {id:1480,word:"frontier",partOfSpeech:"名詞",meaning:"国境地帯，辺境；最先端",
   meanings:["名|国境地帯，辺境","名|（学問などの）未開の最先端"],
   pronunciation:"/frʌnˈtɪr/",part:148,
   example:"Soldiers guarded the frontier between the two old kingdoms.",
   exampleJa:"兵士たちは、二つの古い王国の間の国境地帯を守っていた。",
   example2:"Space is often called the last frontier left to science.",
   exampleJa2:"宇宙はしばしば、科学に残された最後の最先端（フロンティア）と呼ばれる。",
   etymologyProcess:"frontier（国の前のはし）→ 国のいちばん前に立つ境目なら…？",
   etymologyConclusion:"frontier（国の前のはし）→ 国のいちばん前に立ち、向こうと接する境目＝国境地帯",
   relatedWords:[
     {word:"front",meaning:"前面，正面",breakdown:"front（前）→ いちばん前に出ている面"},
     {word:"confront",meaning:"立ち向かう",breakdown:"con（共に）＋ front（前）→ 相手と前と前を向き合わせる"},
     {word:"frontal",meaning:"正面からの",breakdown:"front（前）＋ al（形容詞）→ 正面に向き合った"},
     {synonym:true,word:"border",meaning:"国境",breakdown:"線としての国境。frontier はその周りに広がる地帯"}]},

  {id:1481,word:"treaty",partOfSpeech:"名詞",meaning:"（国家間の）条約",
   meanings:["名|（国家間の）条約"],
   pronunciation:"/ˈtriːti/",part:149,
   example:"The two nations signed a peace treaty after the long war.",
   exampleJa:"長い戦争のあと、両国は平和条約に署名した。",
   example2:"The treaty was broken only three years later.",
   exampleJa2:"その条約は、わずか3年後に破られた。",
   etymologyProcess:"treat（引く）＋ y（名詞）→ 相手を話し合いへ引き寄せてまとめたものは…？",
   etymologyConclusion:"treat（引く）＋ y（名詞）→ 国どうしを話し合いへ引き寄せてまとめた取り決め＝（国家間の）条約",
   why:"【なぜ】ラテン語 tractare は trahere（引く）から出た語で「何度も手で引き回す」＝扱う。そこから「じっくり話し合う・交渉する」の意味が生まれ、交渉してまとめた取り決めが treaty＝条約になりました。\n【つながり】treat（扱う）、contract（契約）、tractor（引くもの）も同じ家族です。",
   relatedWords:[
     {word:"treat",meaning:"扱う",breakdown:"treat（引く）→ 手で引き回すように相手を扱う"},
     {word:"contract",meaning:"契約",breakdown:"con（共に）＋ tract（引く）→ 双方を引き寄せて結ぶ約束"},
     {word:"tractor",meaning:"トラクター",breakdown:"tract（引く）＋ or（もの）→ 重い農具を引っぱる車"},
     {synonym:true,word:"agreement",meaning:"協定，合意",breakdown:"取り決め全般。treaty は国どうしの正式な文書"}]},

  {id:1482,word:"tribe",partOfSpeech:"名詞",meaning:"部族，種族",
   meanings:["名|部族，種族"],
   pronunciation:"/traɪb/",part:149,
   example:"The tribe has lived in this forest for centuries.",
   exampleJa:"その部族は何世紀もの間この森で暮らしてきた。",
   example2:"Many tribes in the area speak their own languages.",
   exampleJa2:"その地域の多くの部族は、独自の言語を話す。",
   etymologyProcess:"tribe（ローマ市民の区分）→ 血筋や土地でまとまった人の集団は…？",
   etymologyConclusion:"tribe（ローマ市民の区分）→ 同じ祖先や土地でまとまった人々の集団＝部族",
   hook:"ラテン語 tribus（古代ローマ市民の区分）から。それより古い語源ははっきりしない。",
   relatedWords:[
     {word:"tribal",meaning:"部族の",breakdown:"tribe（ローマ市民の区分）＋ al（形容詞）→ 部族に関する"},
     {synonym:true,word:"clan",meaning:"一族",breakdown:"同じ祖先を持つ家の集まり。tribe はもっと大きな集団"},
     {synonym:true,word:"people",meaning:"民族",breakdown:"同じ文化を持つ人々。tribe は祖先や土地でまとまった集団"},
     {synonym:true,word:"community",meaning:"共同体",breakdown:"一緒に暮らす人の集まり。tribe は血筋や文化でつながる"}]},

  {id:1483,word:"pension",partOfSpeech:"名詞",meaning:"年金",
   meanings:["名|年金"],
   pronunciation:"/ˈpenʃn/",part:149,
   example:"My grandfather lives on a small pension from the government.",
   exampleJa:"祖父は政府からの少ない年金で暮らしている。",
   example2:"Young workers worry that pensions will be too small someday.",
   exampleJa2:"若い働き手たちは、いつか年金が少なすぎるようになると心配している。",
   etymologyProcess:"pens（重さを量る）＋ ion（名詞）→ 量って定期的に渡されるお金は…？",
   etymologyConclusion:"pens（重さを量る）＋ ion（名詞）→ 量って決まった時期に渡されるお金＝年金",
   relatedWords:[
     {word:"expense",meaning:"費用",breakdown:"ex（外へ）＋ pens（重さを量る）→ 銀貨を量って外へ払い出すお金"},
     {word:"expensive",meaning:"高価な",breakdown:"ex（外へ）＋ pens（重さを量る）＋ ive（形容詞）→ 払い出す額が大きい"},
     {word:"compensate",meaning:"補償する",breakdown:"com（共に）＋ pens（重さを量る）→ 減った分と釣り合う重さを返す"},
     {synonym:true,word:"salary",meaning:"給料",breakdown:"働いている間のお金。pension は働き終えたあとのお金"}]},

  {id:1484,word:"stake",partOfSpeech:"名詞",meaning:"（利害の）かかわり，出資；杭",
   meanings:["名|（利害の）かかわり，出資","熟|（at stake で）危うくなって，かかって","名|杭"],
   pronunciation:"/steɪk/",part:149,
   example:"Local farmers have a big stake in the new dam project.",
   exampleJa:"地元の農家は、新しいダム計画に大きなかかわりを持っている。",
   example2:"Our team's pride is at stake in tomorrow's final.",
   exampleJa2:"明日の決勝には、うちのチームの誇りがかかっている。",
   etymologyProcess:"stake（地面に打つ杭）→ 賭けの品を杭に掛けておくと…？",
   etymologyConclusion:"stake（地面に打つ杭）→ 賭けた物を杭に掛け、勝ち負けで得も損もする＝（利害の）かかわり",
   hook:"at stake は「賭けられて」危うい。杭に掛けた賭け金から、とする説がある。",
   relatedWords:[
     {synonym:true,word:"interest",meaning:"利害；興味",breakdown:"かかわりや得失。stake は自分も賭けている感じが強い"},
     {synonym:true,word:"share",meaning:"分け前，株",breakdown:"持ち分のこと。stake は出資した持ち分にも使う"},
     {synonym:true,word:"bet",meaning:"賭け",breakdown:"賭けること。stake はその賭けた物を指す"},
     {synonym:true,word:"investment",meaning:"投資，出資",breakdown:"お金を出すこと。stake は出して得た持ち分や利害"}]},

  {id:1485,word:"coverage",partOfSpeech:"名詞",meaning:"報道；（保険などの）補償範囲",
   meanings:["名|報道，取材","名|（保険などの）補償範囲"],
   pronunciation:"/ˈkʌvərɪdʒ/",part:149,
   example:"The election received wide coverage on television and online.",
   exampleJa:"その選挙は、テレビやネットで広く報道された。",
   example2:"This insurance gives full coverage for accidents abroad.",
   exampleJa2:"この保険は、海外での事故もすべて補償範囲に入っている。",
   etymologyProcess:"cover（覆う）＋ age（名詞）→ 出来事全体を記者が覆うように取材すると…？",
   etymologyConclusion:"cover（覆う）＋ age（名詞）→ 出来事全体を記者が覆うように取材して伝える＝報道",
   relatedWords:[
     {word:"cover",meaning:"覆う；取材する",breakdown:"cover（覆う）→ 上からすっぽりかぶせる"},
     {word:"discover",meaning:"発見する",breakdown:"dis（否定）＋ cover（覆う）→ 覆いを取って中を見つける"},
     {word:"uncover",meaning:"（覆いを取って）暴く",breakdown:"un（否定）＋ cover（覆う）→ 覆いを取り去って中を見せる"},
     {synonym:true,word:"report",meaning:"報道",breakdown:"一つひとつの知らせ。coverage は報道の量や広さ"}]},

  {id:1486,word:"obligation",partOfSpeech:"名詞",meaning:"（果たすべき）責務，義理",
   meanings:["名|（果たすべき）責務，義理"],
   pronunciation:"/ˌɑːblɪˈɡeɪʃn/",part:149,
   example:"Parents have an obligation to send their children to school.",
   exampleJa:"親には、子どもを学校に通わせる責務がある。",
   example2:"I felt no obligation to accept his expensive gift.",
   exampleJa2:"彼の高価な贈り物を受け取る義理はないと思った。",
   etymologyProcess:"ob（～に向かって）＋ lig（結ぶ）＋ ation（名詞）→ 相手に結びつけられていると…？",
   etymologyConclusion:"ob（～に向かって）＋ lig（結ぶ）＋ ation（名詞）→ 相手に向けて縛りつけられている務め＝（果たすべき）責務",
   relatedWords:[
     {word:"oblige",meaning:"義務づける",breakdown:"ob（～に向かって）＋ lig（結ぶ）→ 相手に縛りつけてやらせる"},
     {word:"obligatory",meaning:"義務的な",breakdown:"ob（～に向かって）＋ lig（結ぶ）＋ ory（形容詞）→ 縛られていて避けられない"},
     {synonym:true,word:"duty",meaning:"義務",breakdown:"当然すべきこと。obligation は約束や法で縛られた務め"},
     {synonym:true,word:"responsibility",meaning:"責任",breakdown:"引き受けている役目。obligation は外から課される"}]},

  {id:1487,word:"hygiene",partOfSpeech:"名詞",meaning:"衛生，清潔",
   meanings:["名|衛生，清潔"],
   pronunciation:"/ˈhaɪdʒiːn/",part:149,
   example:"Good hygiene helps stop the spread of colds at school.",
   exampleJa:"よい衛生は、学校での風邪の広がりを防ぐのに役立つ。",
   example2:"Dentists always stress the importance of mouth hygiene.",
   exampleJa2:"歯医者はいつも口の中の清潔の大切さを強調する。",
   etymologyProcess:"hygi（健康な）→ 健康を守るための心がけは…？",
   etymologyConclusion:"hygi（健康な）→ 体を清潔にして健康を守る心がけ＝衛生",
   why:"【なぜ】ギリシャ語 hygieinos（健康によい）から。ギリシャ神話の健康の女神ヒュギエイアもこの語から名づけられています。「健康によい技術」の意味から、病気を防ぐために体や身の回りを清潔に保つこと＝衛生になりました。\n【つながり】hygienic（衛生的な）が形容詞。薬局のマークにある蛇の杯は、この女神の持ち物です。",
   relatedWords:[
     {word:"hygienic",meaning:"衛生的な",breakdown:"hygi（健康な）＋ ic（形容詞）→ 健康を守れるほど清潔な"},
     {synonym:true,word:"sanitation",meaning:"公衆衛生",breakdown:"上下水道などの設備。hygiene は個人の清潔も含む"},
     {synonym:true,word:"cleanliness",meaning:"清潔さ",breakdown:"よごれがない状態。hygiene は病気を防ぐための清潔"}]},

  {id:1488,word:"supervisor",partOfSpeech:"名詞",meaning:"監督者，上司",
   meanings:["名|監督者，上司"],
   pronunciation:"/ˈsuːpərvaɪzər/",part:149,
   example:"Ask your supervisor before you leave work early.",
   exampleJa:"早退する前に、監督者に確認しなさい。",
   example2:"My part-time job supervisor is kind but very strict.",
   exampleJa2:"アルバイト先の上司は優しいけれど、とても厳しい。",
   etymologyProcess:"super（上から）＋ vis（見る）＋ or（人）→ 上から仕事を見守る人は…？",
   etymologyConclusion:"super（上から）＋ vis（見る）＋ or（人）→ 上から仕事ぶりを見守る人＝監督者",
   relatedWords:[
     {word:"supervise",meaning:"監督する",breakdown:"super（上から）＋ vis（見る）→ 上から全体を見張る"},
     {word:"vision",meaning:"視力；未来像",breakdown:"vis（見る）＋ ion（名詞）→ 見る力、先を見通す姿"},
     {word:"visible",meaning:"目に見える",breakdown:"vis（見る）＋ ible（できる）→ 目で見ることができる"},
     {synonym:true,word:"boss",meaning:"上司，ボス",breakdown:"くだけた言い方。supervisor は現場で監督する人"}]},

  {id:1489,word:"norm",partOfSpeech:"名詞",meaning:"（社会の）規範；ふつうのこと",
   meanings:["名|（社会の）規範","名|（the norm で）ふつうのこと"],
   pronunciation:"/nɔːrm/",part:149,
   example:"Social norms tell us how to behave in public places.",
   exampleJa:"社会の規範は、公共の場でのふるまい方を教えてくれる。",
   example2:"Working from home has become the norm for many people.",
   exampleJa2:"在宅勤務は多くの人にとってふつうのことになった。",
   etymologyProcess:"norm（決まり）→ みんなが従う物差しは…？",
   etymologyConclusion:"norm（決まり）→ みんなが当たり前として従う物差し＝（社会の）規範",
   relatedWords:[
     {word:"normal",meaning:"ふつうの",breakdown:"norm（決まり）＋ al（形容詞）→ 物差しどおりの"},
     {word:"abnormal",meaning:"異常な",breakdown:"ab（離れて）＋ norm（決まり）＋ al（形容詞）→ 物差しから外れた"},
     {word:"enormous",meaning:"巨大な",breakdown:"e（外へ）＋ norm（決まり）＋ ous（形容詞）→ 物差しをはみ出すほど大きい"},
     {synonym:true,word:"standard",meaning:"基準",breakdown:"比べるためのもと。norm は社会で当然とされる型"}]},

  {id:1490,word:"patent",partOfSpeech:"名詞",meaning:"特許（権）",
   meanings:["名|特許（権）","他|～の特許を取る"],
   pronunciation:"/ˈpætnt/",part:149,
   example:"The young inventor applied for a patent on her new battery.",
   exampleJa:"その若い発明家は、新しい電池の特許を申請した。",
   example2:"The company patented the design before selling the product.",
   exampleJa2:"その会社は製品を売り出す前に、そのデザインの特許を取った。",
   etymologyProcess:"patent（開かれた）→ 発明を公に開いて示すかわりに得るものは…？",
   etymologyConclusion:"patent（開かれた）→ 発明を公に開いて示すかわりに、まねを禁じてもらう権利＝特許（権）",
   hook:"形容詞では「明らかな」。だれの目にも開かれて見えている、という同じ絵から。",
   why:"【なぜ】ラテン語 patere（開いている）から。中世の王は、だれでも読めるよう封をせずに開いた公文書 letters patent で特別な権利を与えました。発明者の独占権もこの文書で与えられたので、patent＝特許になりました。\n【つながり】今も「発明の中身を公開する代わりに守ってもらう」仕組みで、「開かれた」の意味が生きています。",
   relatedWords:[
     {synonym:true,word:"invention",meaning:"発明",breakdown:"新しく考え出したもの。patent はそれを守る権利"},
     {synonym:true,word:"copyright",meaning:"著作権",breakdown:"作品を守る権利。patent は発明を守る権利"},
     {synonym:true,word:"right",meaning:"権利",breakdown:"何かをしてよい資格。patent は発明を独り占めできる権利"},
     {synonym:true,word:"trademark",meaning:"商標",breakdown:"会社の名前やマークを守る権利。patent は技術を守る"}]},

  {id:1491,word:"primitive",partOfSpeech:"形容詞",meaning:"原始的な，初期の",
   meanings:["形|原始的な，初期の","形|（道具などが）素朴な，粗末な"],
   pronunciation:"/ˈprɪmətɪv/",part:150,
   example:"Early humans made primitive tools from stone and bone.",
   exampleJa:"初期の人類は、石や骨から原始的な道具を作った。",
   example2:"The cabin had only a very primitive kitchen.",
   exampleJa2:"その小屋には、とても粗末な台所しかなかった。",
   etymologyProcess:"prim（第一の）＋ ive（形容詞）→ いちばん最初の段階のままだと…？",
   etymologyConclusion:"prim（第一の）＋ ive（形容詞）→ 物事のいちばん最初の段階にある＝原始的な",
   relatedWords:[
     {word:"primary",meaning:"第一の，主要な",breakdown:"prim（第一の）＋ ary（形容詞）→ 順番がいちばん先の"},
     {word:"prime",meaning:"最も重要な",breakdown:"prim（第一の）→ 一番目に来るほど大事な"},
     {synonym:true,word:"crude",meaning:"粗末な，未加工の",breakdown:"手が加わっていないこと。primitive は発達の初めの段階"},
     {synonym:true,word:"ancient",meaning:"古代の",breakdown:"ずっと昔の時代。primitive は発達の初めの段階を指す"}]},

  {id:1492,word:"ethnic",partOfSpeech:"形容詞",meaning:"民族の，民族的な",
   meanings:["形|民族の，民族的な"],
   pronunciation:"/ˈeθnɪk/",part:150,
   example:"The city is home to many different ethnic groups.",
   exampleJa:"その都市には、多くの異なる民族の集団が暮らしている。",
   example2:"We tried ethnic food from five countries at the festival.",
   exampleJa2:"私たちはお祭りで、5か国の民族料理を食べてみた。",
   etymologyProcess:"ethn（民族）＋ ic（形容詞）→ 言葉や文化でまとまった人々に関する…？",
   etymologyConclusion:"ethn（民族）＋ ic（形容詞）→ 言葉や文化を共にする人々のまとまりに関する＝民族の",
   relatedWords:[
     {word:"ethnicity",meaning:"民族性",breakdown:"ethn（民族）＋ ic（形容詞）＋ ity（名詞）→ どの民族に属するかということ"},
     {synonym:true,word:"racial",meaning:"人種の",breakdown:"体の特徴による区分。ethnic は言葉や文化による区分"},
     {word:"ethnically",meaning:"民族的に",breakdown:"ethn（民族）＋ ic（形容詞）＋ ly（副詞）→ 民族という点で"},
     {synonym:true,word:"tribal",meaning:"部族の",breakdown:"小さな部族の単位。ethnic はもっと広い民族の単位"}]},

  {id:1493,word:"anonymous",partOfSpeech:"形容詞",meaning:"匿名の，名前を伏せた",
   meanings:["形|匿名の，名前を伏せた"],
   pronunciation:"/əˈnɑːnɪməs/",part:150,
   example:"An anonymous donor gave the hospital a million dollars.",
   exampleJa:"匿名の寄付者が、その病院に100万ドルを贈った。",
   example2:"The survey is anonymous, so please answer honestly.",
   exampleJa2:"この調査は匿名なので、正直に答えてください。",
   etymologyProcess:"anonym（名前がない）＋ ous（形容詞）→ 名前が出ていないと…？",
   etymologyConclusion:"anonym（名前がない）＋ ous（形容詞）→ 名前を明かさず、だれか分からない＝匿名の",
   relatedWords:[
     {word:"synonym",meaning:"同義語",breakdown:"syn（共に）＋ onym（名前）→ 意味を共にする別の名前"},
     {word:"anonymity",meaning:"匿名であること",breakdown:"anonym（名前がない）＋ ity（名詞）→ 名前が知られていない状態"},
     {synonym:true,word:"unknown",meaning:"知られていない",breakdown:"だれにも知られていないこと。anonymous は名前だけを伏せる"},
     {synonym:true,word:"unnamed",meaning:"名前の出ていない",breakdown:"名前が示されていないこと。anonymous は名前を意図して伏せる"}]},

  {id:1494,word:"metropolitan",partOfSpeech:"形容詞",meaning:"大都市の，首都圏の",
   meanings:["形|大都市の，首都圏の"],
   pronunciation:"/ˌmetrəˈpɑːlɪtən/",part:150,
   example:"Housing is very expensive in the metropolitan area.",
   exampleJa:"大都市の地域では、住宅がとても高い。",
   example2:"About 37 million people live in the Tokyo metropolitan area.",
   exampleJa2:"東京の大都市圏には約3700万人が住んでいる。",
   etymologyProcess:"metro（母）＋ polit（都市）＋ an（～の）→ 周りの町を生んだ母なる都市の…？",
   etymologyConclusion:"metro（母）＋ polit（都市）＋ an（～の）→ 周りの町の母となる中心都市の＝大都市の",
   why:"【なぜ】ギリシャ語 mētropolis は mētēr（母）＋ polis（都市）で、もとは「植民地を送り出した母なる都市」。そこから「国や地方の中心になる大きな都市」の意味になり、metropolitan はその形容詞になりました。\n【つながり】「メトロ（地下鉄）」は metropolitan railway（大都市鉄道）を縮めた言い方。politics（政治）も polis の仲間です。",
   relatedWords:[
     {word:"metropolis",meaning:"大都市",breakdown:"metro（母）＋ polis（都市）→ 周りの町を生んだ母なる都市"},
     {word:"politics",meaning:"政治",breakdown:"polit（都市）＋ ics（名詞）→ 都市国家を治めるわざ"},
     {word:"police",meaning:"警察",breakdown:"polic（都市）→ 都市の秩序を守る組織"},
     {synonym:true,word:"urban",meaning:"都市の",breakdown:"都会に関すること全般。metropolitan は特に大都市圏"}]},

  {id:1495,word:"entitled",partOfSpeech:"形容詞",meaning:"（to ～の）権利がある，資格がある",
   meanings:["形|（to ～の / to do する）権利がある，資格がある","形|～という題名の"],
   pronunciation:"/ɪnˈtaɪtld/",part:150,
   example:"All students are entitled to use the school library.",
   exampleJa:"すべての生徒は学校の図書館を使う権利がある。",
   example2:"He read a book entitled \"The Power of Habit.\"",
   exampleJa2:"彼は『習慣の力』という題名の本を読んだ。",
   etymologyProcess:"en（～にする）＋ title（肩書き）＋ ed（～された）→ 正式な肩書きを与えられていると…？",
   etymologyConclusion:"en（～にする）＋ title（肩書き）＋ ed（～された）→ 正式な名目を与えられている＝（to ～の）権利がある",
   why:"【なぜ】ラテン語 titulus（札・表題）から title が生まれ、entitle はもと「本に題名をつける」こと。中世には「人に肩書きや名目を与える」意味になり、名目があれば堂々と求められることから「権利を与える」になりました。\n【つながり】今も「題名の」と「権利がある」の両方の意味で使われます。title には「タイトル」だけでなく「権利・所有権」の意味もあります。",
   relatedWords:[
     {word:"title",meaning:"題名；肩書き",breakdown:"title（肩書き）→ 本や人につける名札"},
     {word:"subtitle",meaning:"字幕；副題",breakdown:"sub（下で）＋ title（肩書き）→ 画面の下に出る文字"},
     {synonym:true,word:"eligible",meaning:"資格のある",breakdown:"条件を満たしていること。entitled は当然の権利がある"},
     {synonym:true,word:"qualified",meaning:"資格を持った",breakdown:"能力や免許があること。entitled は権利の側に重点"}]},

  {id:1496,word:"demographic",partOfSpeech:"形容詞",meaning:"人口構成の，人口統計の",
   meanings:["形|人口構成の，人口統計の","名|（特定の）年齢層，購買層"],
   pronunciation:"/ˌdeməˈɡræfɪk/",part:150,
   example:"Japan faces serious demographic changes as people age.",
   exampleJa:"日本は高齢化によって、人口構成の深刻な変化に直面している。",
   example2:"This app is popular with a young demographic.",
   exampleJa2:"このアプリは若い年齢層に人気がある。",
   etymologyProcess:"demo（民衆）＋ graph（書く）＋ ic（形容詞）→ 住む人々を数えて書き記すと…？",
   etymologyConclusion:"demo（民衆）＋ graph（書く）＋ ic（形容詞）→ 住む人々の数や年齢を書き記した＝人口構成の",
   relatedWords:[
     {word:"democracy",meaning:"民主主義",breakdown:"demo（民衆）＋ cracy（支配）→ 民衆が国を治める仕組み"},
     {word:"photograph",meaning:"写真",breakdown:"photo（光）＋ graph（書く）→ 光で書きとめた絵"},
     {word:"graph",meaning:"グラフ",breakdown:"graph（書く）→ 数を線で書き表した図"},
     {word:"demography",meaning:"人口統計学",breakdown:"demo（民衆）＋ graph（書く）＋ y（名詞）→ 人々の数を書き記して調べる学問"}]},

  {id:1497,word:"donate",partOfSpeech:"他動詞・自動詞",meaning:"寄付する，寄贈する",
   meanings:["他|～を寄付する，寄贈する","他|（血液や臓器）を提供する","自|寄付する"],
   pronunciation:"/ˈdoʊneɪt/",part:150,
   example:"Our class decided to donate old books to the library.",
   exampleJa:"私たちのクラスは、古本を図書館に寄付することにした。",
   example2:"Over a thousand people donated blood after the earthquake.",
   exampleJa2:"地震のあと、千人以上の人が献血した。",
   etymologyProcess:"don（与える）＋ ate（動詞）→ 見返りなしに与えると…？",
   etymologyConclusion:"don（与える）＋ ate（動詞）→ 見返りを求めずにお金や物を与える＝寄付する",
   relatedWords:[
     {word:"donor",meaning:"寄付者；提供者",breakdown:"don（与える）＋ or（人）→ 与える人"},
     {word:"donation",meaning:"寄付",breakdown:"don（与える）＋ ation（名詞）→ 与えたお金や物"},
     {word:"data",meaning:"データ",breakdown:"dat（与える）→ 与えられた事実"},
     {synonym:true,word:"contribute",meaning:"寄付する；貢献する",breakdown:"みんなと一緒に出すこと。donate は与えることそのもの"}]},

  {id:1498,word:"flourish",partOfSpeech:"自動詞",meaning:"栄える，繁盛する；よく育つ",
   meanings:["自|栄える，繁盛する","自|（植物が）よく育つ"],
   pronunciation:"/ˈflɜːrɪʃ/",part:150,
   example:"Trade began to flourish after the new port opened.",
   exampleJa:"新しい港が開くと、貿易が栄え始めた。",
   example2:"These plants flourished in the warm, wet climate.",
   exampleJa2:"これらの植物は、暖かく湿った気候でよく育った。",
   etymologyProcess:"flour（花）＋ ish（～にする）→ 花が咲きそろうように勢いづくと…？",
   etymologyConclusion:"flour（花）＋ ish（～にする）→ 花が咲きそろうように勢いがさかんになる＝栄える",
   relatedWords:[
     {word:"flower",meaning:"花",breakdown:"flower（花）→ 咲いた花。flour（小麦粉）も「粉の中の花＝最上の部分」から"},
     {word:"floral",meaning:"花の",breakdown:"flor（花）＋ al（形容詞）→ 花に関する、花柄の"},
     {word:"florist",meaning:"花屋",breakdown:"flor（花）＋ ist（人）→ 花を扱う人"},
     {synonym:true,word:"prosper",meaning:"繁栄する",breakdown:"成功して豊かになること。flourish は勢いよく伸びる感じ"}]},

  {id:1499,word:"conform",partOfSpeech:"自動詞",meaning:"（規則や慣習に）従う，合わせる",
   meanings:["自|（to ～に）従う，合わせる","自|（to ～に）一致する"],
   pronunciation:"/kənˈfɔːrm/",part:150,
   example:"New students must conform to the school's dress code.",
   exampleJa:"新入生は学校の服装規定に従わなければならない。",
   example2:"He refused to conform and wore his own style.",
   exampleJa2:"彼は周りに合わせるのを拒み、自分のスタイルを貫いた。",
   etymologyProcess:"con（共に）＋ form（形）→ みんなと同じ形にそろえると…？",
   etymologyConclusion:"con（共に）＋ form（形）→ みんなと同じ形に自分をそろえる＝（規則や慣習に）従う",
   relatedWords:[
     {word:"form",meaning:"形；形づくる",breakdown:"form（形）→ ものの外側のかたち"},
     {word:"uniform",meaning:"制服",breakdown:"uni（1つの）＋ form（形）→ みんな同じ一つの形の服"},
     {word:"reform",meaning:"改革する",breakdown:"re（再び）＋ form（形）→ もう一度形を作り直す"},
     {synonym:true,word:"obey",meaning:"従う",breakdown:"命令に従うこと。conform は周りの型に自分を合わせる"}]},

  {id:1500,word:"comply",partOfSpeech:"自動詞",meaning:"（規則や要求を）守る，応じる",
   meanings:["自|（with ～を）守る，～に応じる"],
   pronunciation:"/kəmˈplaɪ/",part:150,
   example:"All factories must comply with the new safety rules.",
   exampleJa:"すべての工場は、新しい安全規則を守らなければならない。",
   example2:"The singer complied with the fans' request for a photo.",
   exampleJa2:"その歌手は、写真を撮りたいというファンの頼みに応じた。",
   etymologyProcess:"com（すっかり）＋ ply（満たす）→ 求められたことをすっかり満たすと…？",
   etymologyConclusion:"com（すっかり）＋ ply（満たす）→ 求められたことをすっかり満たしてやる＝（規則や要求を）守る",
   relatedWords:[
     {word:"complete",meaning:"完成させる",breakdown:"com（すっかり）＋ ple（満たす）→ すっかり満たして仕上げる"},
     {word:"supply",meaning:"供給する",breakdown:"sup（下から）＋ ply（満たす）→ 足りない所を下から満たす"},
     {word:"compliment",meaning:"ほめ言葉",breakdown:"com（すっかり）＋ ple（満たす）＋ ment（名詞）→ 礼儀をすっかり満たす言葉"},
     {synonym:true,word:"obey",meaning:"従う",breakdown:"言われたとおりにすること。comply は規則や要求を満たす"}]},

  {id:1501,word:"legislation",partOfSpeech:"名詞",meaning:"（制定された）法律；立法",
   meanings:["名|（制定された）法律","名|立法，法律の制定"],
   pronunciation:"/ˌledʒɪsˈleɪʃn/",part:151,
   example:"New legislation bans smoking in all public buildings.",
   exampleJa:"新しい法律は、すべての公共の建物での喫煙を禁じている。",
   example2:"Parliament, not the king, holds the power of legislation.",
   exampleJa2:"立法の権限を持つのは、王ではなく議会だ。",
   etymologyProcess:"leg（法）＋ lat（運ぶ）＋ ion（名詞）→ 法を議会へ運んで提出すると…？",
   etymologyConclusion:"leg（法）＋ lat（運ぶ）＋ ion（名詞）→ 法を運び出して定めること、その法＝（制定された）法律",
   why:"【なぜ】ラテン語 legis latio は「法を運び出すこと」。古代ローマでは法案を民会へ持ち出して決めたので、「法を提案して定めること」＝立法になり、やがて定められた法律そのものも指すようになりました。\n【つながり】legal（法の）、legislature（立法府）が同じ家族。translate（向こうへ運ぶ）も lat の仲間です。",
   relatedWords:[
     {word:"legal",meaning:"法律の",breakdown:"leg（法）＋ al（形容詞）→ 法で定められているとおりの"},
     {word:"illegal",meaning:"違法の",breakdown:"in（否定）＋ leg（法）＋ al（形容詞）→ 法に合っていない"},
     {word:"translate",meaning:"翻訳する",breakdown:"trans（越えて）＋ lat（運ぶ）→ 言葉の境を越えて意味を運ぶ"},
     {synonym:true,word:"law",meaning:"法律",breakdown:"法全般。legislation は議会で作られた法律をまとめて指す"}]},

  {id:1502,word:"testimony",partOfSpeech:"名詞",meaning:"（法廷での）証言；証拠",
   meanings:["名|（法廷での）証言","名|（to ～の）証拠，あかし"],
   pronunciation:"/ˈtestɪmoʊni/",part:151,
   example:"The witness gave important testimony in court yesterday.",
   exampleJa:"その目撃者は昨日、法廷で重要な証言をした。",
   example2:"Her fast recovery is testimony to the doctors' skill.",
   exampleJa2:"彼女の早い回復は、医師たちの腕のよさのあかしだ。",
   etymologyProcess:"test（証言する）→ 法廷で「見たのはこれだ」と述べることは…？",
   etymologyConclusion:"test（証言する）→ 見聞きしたことを法廷で本当だと述べること＝（法廷での）証言",
   relatedWords:[
     {word:"protest",meaning:"抗議する",breakdown:"pro（前へ）＋ test（証言する）→ 人前で反対だとはっきり言う"},
     {word:"contest",meaning:"競技会；争う",breakdown:"con（共に）＋ test（証言する）→ 証人を立て合って争う"},
     {word:"testify",meaning:"証言する",breakdown:"test（証言する）＋ ify（する）→ 証人として述べる"},
     {synonym:true,word:"evidence",meaning:"証拠",breakdown:"事実を示すもの全般。testimony は人が語る証言"}]},

  {id:1503,word:"jury",partOfSpeech:"名詞",meaning:"陪審（員団）；審査員団",
   meanings:["名|陪審（員団）","名|（コンテストの）審査員団"],
   pronunciation:"/ˈdʒʊri/",part:151,
   example:"The jury decided that the man was not guilty.",
   exampleJa:"陪審はその男性が無罪だと判断した。",
   example2:"A jury of famous artists will choose the winning poster.",
   exampleJa2:"有名な芸術家たちの審査員団が、優勝ポスターを選ぶ。",
   etymologyProcess:"jur（正しい・法）→ 法廷で正しく裁くと誓う人たちは…？",
   etymologyConclusion:"jur（正しい・法）→ 法に照らして正しく裁くと誓った人たちの集まり＝陪審（員団）",
   why:"【なぜ】ラテン語 jurare（誓う）は jus（法・正しさ）から出た語。中世イギリスで「正直に答えると誓った住民の集まり」を jury と呼び、それが裁判で有罪か無罪かを決める陪審になりました。\n【つながり】justice（正義）、injury（正しくない仕打ち→けが）も同じ家族。今はコンテストの審査員団にも使います。",
   relatedWords:[
     {word:"justice",meaning:"正義；裁判",breakdown:"jus（正しい）＋ ice（名詞）→ 正しさを守ること"},
     {word:"injury",meaning:"けが",breakdown:"in（否定）＋ jur（正しい・法）＋ y（名詞）→ 不当な仕打ちで受けた傷"},
     {word:"jurisdiction",meaning:"管轄（権）",breakdown:"jur（正しい・法）＋ dict（言う）→ 法を言い渡せる範囲"},
     {synonym:true,word:"judge",meaning:"裁判官",breakdown:"一人で裁く人。jury は市民の集まりで判断する"}]},

  {id:1504,word:"legitimate",partOfSpeech:"形容詞",meaning:"正当な，合法の",
   meanings:["形|正当な，もっともな","形|合法の，正規の"],
   pronunciation:"/lɪˈdʒɪtɪmət/",part:151,
   example:"Being sick is a legitimate reason for missing school.",
   exampleJa:"病気は学校を休む正当な理由だ。",
   example2:"The company runs a legitimate business, not a scam.",
   exampleJa2:"その会社は詐欺ではなく、合法の商売をしている。",
   etymologyProcess:"leg（法）＋ ate（形容詞）→ 法に照らして認められると…？",
   etymologyConclusion:"leg（法）＋ ate（形容詞）→ 法やきまりに照らして認められる＝正当な",
   relatedWords:[
     {word:"legal",meaning:"法律の",breakdown:"leg（法）＋ al（形容詞）→ 法で定められているとおりの"},
     {word:"legislation",meaning:"法律；立法",breakdown:"leg（法）＋ lat（運ぶ）→ 法を運び出して定めること"},
     {word:"privilege",meaning:"特権",breakdown:"privi（個人の）＋ leg（法）→ その人だけのための法"},
     {synonym:true,word:"valid",meaning:"有効な",breakdown:"効力があること。legitimate は筋が通って認められる"}]},

  {id:1505,word:"enforce",partOfSpeech:"他動詞",meaning:"（法律を）施行する；強制する",
   meanings:["他|（法律）を施行する，守らせる","他|～を強制する"],
   pronunciation:"/ɪnˈfɔːrs/",part:151,
   example:"The government will enforce the new traffic law from April.",
   exampleJa:"政府は4月から新しい交通法を施行する。",
   example2:"Our coach enforced a strict no-phone rule during practice.",
   exampleJa2:"コーチは練習中、スマホ禁止のルールを厳しく守らせた。",
   etymologyProcess:"en（～にする）＋ force（力）→ 決まりに力を持たせると…？",
   etymologyConclusion:"en（～にする）＋ force（力）→ 決まりに力を持たせて実際に守らせる＝（法律を）施行する",
   relatedWords:[
     {word:"force",meaning:"力；強制する",breakdown:"force（力）→ ものを動かす強い力"},
     {word:"effort",meaning:"努力",breakdown:"ex（外へ）＋ fort（力）→ 力を外へ出しきること"},
     {word:"comfort",meaning:"慰め；快適さ",breakdown:"com（強く）＋ fort（力）→ 心に力をつけてやること"},
     {synonym:true,word:"impose",meaning:"課す",breakdown:"上から押しつけること。enforce はすでにある決まりを守らせる"}]},

  {id:1506,word:"regime",partOfSpeech:"名詞",meaning:"（独裁的な）政権，体制",
   meanings:["名|（独裁的な）政権，体制","名|（食事・運動などの）管理計画"],
   pronunciation:"/reɪˈʒiːm/",part:151,
   example:"The cruel regime finally fell after years of protests.",
   exampleJa:"その残酷な政権は、何年もの抗議のすえにようやく倒れた。",
   example2:"She follows a strict training regime before every marathon.",
   exampleJa2:"彼女はマラソンの前には必ず、厳しい練習計画をこなす。",
   etymologyProcess:"reg（治める）→ 国をどう治めるかの仕組みは…？",
   etymologyConclusion:"reg（治める）→ 国を上から治める仕組みと、その支配者たち＝（独裁的な）政権",
   relatedWords:[
     {word:"region",meaning:"地域",breakdown:"reg（治める）＋ ion（名詞）→ 一人の王が治める範囲"},
     {word:"reign",meaning:"治世；君臨する",breakdown:"reg（治める）→ 王として国を治めること"},
     {word:"regulate",meaning:"規制する",breakdown:"reg（治める）＋ ate（動詞）→ きまりで治めて整える"},
     {synonym:true,word:"government",meaning:"政府",breakdown:"国を動かす組織。regime は好ましくない政権によく使う"}]},

  {id:1507,word:"bureaucracy",partOfSpeech:"名詞",meaning:"官僚制度；お役所仕事",
   meanings:["名|官僚制度，官僚","名|（面倒な）お役所仕事"],
   pronunciation:"/bjʊˈrɑːkrəsi/",part:151,
   example:"The country's bureaucracy makes starting a business very slow.",
   exampleJa:"その国の官僚制度のせいで、起業にとても時間がかかる。",
   example2:"I had to fill in ten forms. What a lot of bureaucracy!",
   exampleJa2:"10枚も書類を書かされた。なんてお役所仕事だ！",
   etymologyProcess:"bureau（机）＋ cracy（支配）→ 役所の机の上の書類で国を動かすと…？",
   etymologyConclusion:"bureau（机）＋ cracy（支配）→ 役所の机で書類を回して国を治める仕組み＝官僚制度",
   why:"【なぜ】フランス語 bureau はもと「机にかける布」、そこから「机」「事務所」になりました。18世紀のフランスで、役人が机の上の書類で国を動かすことを皮肉って bureaucratie（机の支配）と呼んだのが始まりです。\n【つながり】democracy（民衆の支配）と同じ cracy。もとが皮肉なので「お役所仕事」という悪い意味でもよく使います。",
   relatedWords:[
     {word:"bureau",meaning:"局，事務所",breakdown:"bureau（机）→ 机を並べて仕事をする所"},
     {word:"democracy",meaning:"民主主義",breakdown:"demo（民衆）＋ cracy（支配）→ 民衆が国を治める仕組み"},
     {word:"aristocracy",meaning:"貴族（階級）",breakdown:"arist（最もすぐれた）＋ cracy（支配）→ 選ばれた者の支配"},
     {synonym:true,word:"red tape",meaning:"お役所仕事",breakdown:"書類をしばった赤いひもから。bureaucracy は仕組みそのもの"}]},

  {id:1508,word:"corruption",partOfSpeech:"名詞",meaning:"汚職，（政治などの）腐敗",
   meanings:["名|汚職，（政治などの）腐敗"],
   pronunciation:"/kəˈrʌpʃn/",part:151,
   example:"The mayor was arrested for corruption last month.",
   exampleJa:"市長は先月、汚職で逮捕された。",
   example2:"Voters are tired of corruption in the government.",
   exampleJa2:"有権者は政府の腐敗にうんざりしている。",
   etymologyProcess:"com（すっかり）＋ rupt（破る）＋ ion（名詞）→ 正しさがすっかり破れてしまうと…？",
   etymologyConclusion:"com（すっかり）＋ rupt（破る）＋ ion（名詞）→ 正しい心がすっかり破れてくずれること＝汚職",
   relatedWords:[
     {word:"interrupt",meaning:"じゃまをする",breakdown:"inter（間の）＋ rupt（破る）→ 話の間に割りこんで破る"},
     {word:"erupt",meaning:"噴火する",breakdown:"e（外へ）＋ rupt（破る）→ 山が内から破れて外へ噴き出す"},
     {word:"bankrupt",meaning:"倒産した",breakdown:"bank（両替台）＋ rupt（破る）→ 両替台をこわされた"},
     {synonym:true,word:"dishonesty",meaning:"不正",breakdown:"ずるいこと全般。corruption は権力を持つ人の不正"}]},

  {id:1509,word:"tyranny",partOfSpeech:"名詞",meaning:"圧政，暴政",
   meanings:["名|圧政，暴政","名|（人に対する）横暴"],
   pronunciation:"/ˈtɪrəni/",part:151,
   example:"The people finally rose up against years of tyranny.",
   exampleJa:"人々はついに、長年の圧政に立ち上がった。",
   example2:"The club captain's tyranny made many members quit.",
   exampleJa2:"部長の横暴のせいで、多くの部員がやめた。",
   etymologyProcess:"tyrann（独裁者）→ 一人の独裁者が好き勝手に治めると…？",
   etymologyConclusion:"tyrann（独裁者）→ 一人の独裁者が民を押さえつけて治めること＝圧政",
   hook:"ギリシャ語 tyrannos（力で権力を奪った王）から。恐竜の T.レックスも「暴君トカゲ」。",
   relatedWords:[
     {word:"tyrant",meaning:"暴君",breakdown:"tyrann（独裁者）→ 力で人々を押さえつける王"},
     {synonym:true,word:"dictatorship",meaning:"独裁政治",breakdown:"一人が全権を持つ政治の仕組み。tyranny はそのむごい治め方"},
     {synonym:true,word:"oppression",meaning:"抑圧",breakdown:"上から押さえつけること。tyranny は支配者による抑圧"},
     {synonym:true,word:"cruelty",meaning:"残酷さ",breakdown:"むごさ全般。tyranny は権力を持つ者のむごさ"}]},

  {id:1510,word:"sanction",partOfSpeech:"名詞",meaning:"（国際的な）制裁；認可",
   meanings:["名|（通例 sanctions で）（国際的な）制裁","名|（正式な）認可","他|～を認可する"],
   pronunciation:"/ˈsæŋkʃn/",part:151,
   example:"The United Nations imposed economic sanctions on the country.",
   exampleJa:"国連はその国に経済制裁を科した。",
   example2:"The trip was held with the principal's official sanction.",
   exampleJa2:"その旅行は、校長の正式な認可を得て行われた。",
   etymologyProcess:"sanct（神聖な）＋ ion（名詞）→ 神聖な決まりとして定め、破れば罰すると…？",
   etymologyConclusion:"sanct（神聖な）＋ ion（名詞）→ 神聖な決まりを破った者に科される罰＝（国際的な）制裁",
   why:"【なぜ】ラテン語 sancire（神聖なものとして定める）から。sanctio はもと「破れば罰を与えると定めた法の条文」でした。そこから「正式に認めること」＝認可と、「決まりを破った者への罰」＝制裁の、正反対に見える2つの意味が生まれました。\n【つながり】saint（聖人）、sanctuary（聖域）が同じ家族です。",
   relatedWords:[
     {word:"saint",meaning:"聖人",breakdown:"sanct（神聖な）→ 神聖と認められた人"},
     {word:"sanctuary",meaning:"聖域；保護区",breakdown:"sanct（神聖な）＋ ary（もの）→ 手を出してはならない神聖な場所"},
     {synonym:true,word:"penalty",meaning:"罰",breakdown:"決まりを破った罰全般。sanction は国に対する制裁に多い"},
     {synonym:true,word:"punishment",meaning:"処罰",breakdown:"罰を与えること。sanction は圧力をかけるための罰"}]},

  {id:1511,word:"candidate",partOfSpeech:"名詞",meaning:"（選挙などの）候補者；志願者",
   meanings:["名|（選挙などの）候補者","名|志願者，受験者"],
   pronunciation:"/ˈkændɪdət/",part:152,
   example:"Three candidates are running for mayor this year.",
   exampleJa:"今年は3人の候補者が市長選に立候補している。",
   example2:"She is a strong candidate for the team captain.",
   exampleJa2:"彼女はチームのキャプテンの有力な候補者だ。",
   etymologyProcess:"cand（白く輝く）＋ ate（～にする）→ 真っ白な服を着て人前に立つ人は…？",
   etymologyConclusion:"cand（白く輝く）＋ ate（～にする）→ 真っ白な服で身を包み、選ばれるのを待つ人＝（選挙などの）候補者",
   why:"【なぜ】ラテン語 candidus は「白く輝く」。古代ローマで役職に立候補する人は、けがれのなさを示すため白く光るトーガ（上着）を着て広場を歩きました。その人たちを candidatus（白い服を着た人）と呼んだのが始まりです。\n【つながり】candle（ろうそく）、candid（率直な＝白くて隠しごとがない）も同じ家族です。",
   relatedWords:[
     {word:"candle",meaning:"ろうそく",breakdown:"cand（白く輝く）＋ le（もの）→ 白く光る灯り"},
     {word:"candid",meaning:"率直な",breakdown:"cand（白く輝く）→ 白くて隠しごとのない"},
     {synonym:true,word:"applicant",meaning:"応募者",breakdown:"申し込んだ人。candidate は選ばれる候補になっている人"},
     {synonym:true,word:"nominee",meaning:"指名された人",breakdown:"推薦で名前が挙がった人。candidate は広く候補者を指す"}]},

  {id:1512,word:"senator",partOfSpeech:"名詞",meaning:"上院議員",
   meanings:["名|上院議員"],
   pronunciation:"/ˈsenətər/",part:152,
   example:"The senator gave a long speech about climate change.",
   exampleJa:"その上院議員は気候変動について長い演説をした。",
   example2:"Each state elects two senators to the national Senate.",
   exampleJa2:"各州は国の上院に2人の上院議員を選ぶ。",
   etymologyProcess:"sen（年をとった）＋ ate（名詞）＋ or（人）→ 長老たちの会議に出る人は…？",
   etymologyConclusion:"sen（年をとった）＋ ate（名詞）＋ or（人）→ 長老たちの会議である上院に出る人＝上院議員",
   why:"【なぜ】ラテン語 senex（年寄り）から。古代ローマの senatus はもと「長老たちの会議」で、経験を積んだ年長者が国の大事を話し合いました。その流れで今の上院を Senate、その議員を senator と呼んでいます。\n【つながり】senior（年上の）も sen の仲間。日本語の「元老院」はこの senatus の訳です。",
   relatedWords:[
     {word:"senior",meaning:"年上の；先輩",breakdown:"sen（年をとった）＋ ior（より～な）→ より年をとった"},
     {word:"senate",meaning:"上院",breakdown:"sen（年をとった）＋ ate（名詞）→ 長老たちの会議"},
     {synonym:true,word:"lawmaker",meaning:"議員，立法者",breakdown:"法律を作る人全般。senator はその中の上院議員"},
     {synonym:true,word:"politician",meaning:"政治家",breakdown:"政治にたずさわる人全般。senator はその中の上院議員"}]},

  {id:1513,word:"ambassador",partOfSpeech:"名詞",meaning:"大使；（非公式の）使節",
   meanings:["名|大使","名|（活動などの）使節，代表"],
   pronunciation:"/æmˈbæsədər/",part:152,
   example:"The Japanese ambassador met the president in Washington.",
   exampleJa:"日本の大使はワシントンで大統領と会った。",
   example2:"Our club chose her as an ambassador for the festival.",
   exampleJa2:"部はお祭りの代表として彼女を選んだ。",
   etymologyProcess:"ambass（仕える者）→ 王に仕えて外国へ送られる人は…？",
   etymologyConclusion:"ambass（仕える者）→ 国に仕え、その代わりとして外国へ送られる人＝大使",
   why:"【なぜ】ケルト語の ambactos（仕える者・家来）がラテン語 ambactus になり、イタリア語やフランス語を通って英語に入りました。もとは主人の用事で出かける「家来」。それが王や国の用事で外国へ送られる人を指すようになり、今の「大使」になりました。\n【つながり】embassy（大使館）も同じ語から。大使は今も「国に仕えて外国に送られる人」です。",
   relatedWords:[
     {word:"embassy",meaning:"大使館",breakdown:"ambass（仕える者）＋ y（名詞）→ 大使が仕事をする建物"},
     {synonym:true,word:"diplomat",meaning:"外交官",breakdown:"外交にたずさわる役人全般。ambassador はその最高位"},
     {synonym:true,word:"representative",meaning:"代表者",breakdown:"代わりを務める人全般。ambassador は国を代表する"},
     {synonym:true,word:"envoy",meaning:"使節",breakdown:"特別に送られる使い。ambassador は外国にとどまる"}]},

  {id:1514,word:"diplomat",partOfSpeech:"名詞",meaning:"外交官",
   meanings:["名|外交官","名|（人づきあいの）駆け引きの上手な人"],
   pronunciation:"/ˈdɪpləmæt/",part:152,
   example:"The diplomat worked hard to prevent a war.",
   exampleJa:"その外交官は戦争を防ぐために懸命に働いた。",
   example2:"Mina is a real diplomat when her friends argue.",
   exampleJa2:"ミナは友だちがけんかすると、本当にうまく間を取り持つ。",
   etymologyProcess:"dipl（二つに折る）→ 二つに折った公文書を持って外国へ行く人は…？",
   etymologyConclusion:"dipl（二つに折る）→ 二つに折った公文書を扱い、外国と交渉する人＝外交官",
   why:"【なぜ】ギリシャ語 diplōma は「二つに折った紙」。昔の通行証や公文書は二つに折って封をしました。その公文書を扱う仕事が diplomacy（外交）、それにたずさわる人が diplomat（外交官）になりました。\n【つながり】diploma（卒業証書）も同じ「折った公文書」から。今も「駆け引きが上手な人」の意味で使います。",
   relatedWords:[
     {word:"diploma",meaning:"卒業証書",breakdown:"dipl（二つに折る）＋ ma（もの）→ 二つに折った正式な書類"},
     {word:"diplomacy",meaning:"外交",breakdown:"dipl（二つに折る）＋ acy（名詞）→ 公文書で国どうしをつなぐ仕事"},
     {word:"diplomatic",meaning:"外交の；如才ない",breakdown:"dipl（二つに折る）＋ ic（形容詞）→ 外交に関する"},
     {synonym:true,word:"ambassador",meaning:"大使",breakdown:"外交官の中で最高位の人。diplomat は外交官全般"}]},

  {id:1515,word:"refugee",partOfSpeech:"名詞",meaning:"難民，避難者",
   meanings:["名|難民，避難者"],
   pronunciation:"/ˌrefjuˈdʒiː/",part:152,
   example:"Thousands of refugees crossed the border to escape the war.",
   exampleJa:"何千人もの難民が、戦争から逃れるために国境を越えた。",
   example2:"Our school collected warm clothes for refugee children this winter.",
   exampleJa2:"この冬、うちの学校は難民の子どもたちのために暖かい服を集めた。",
   etymologyProcess:"re（後ろへ）＋ fug（逃げる）＋ ee（人）→ 危険から後ろへ逃げてきた人は…？",
   etymologyConclusion:"re（後ろへ）＋ fug（逃げる）＋ ee（人）→ 戦争や迫害から逃げて、安全な所へ来た人＝難民",
   relatedWords:[
     {word:"refuge",meaning:"避難所",breakdown:"re（後ろへ）＋ fug（逃げる）→ 逃げこむ場所"},
     {word:"fugitive",meaning:"逃亡者",breakdown:"fug（逃げる）＋ itive（形容詞）→ 追っ手から逃げている人"},
     {synonym:true,word:"immigrant",meaning:"移民",breakdown:"自分の意思で移り住んだ人。refugee は逃げざるをえなかった人"},
     {synonym:true,word:"evacuee",meaning:"避難者",breakdown:"災害などで一時的に避難した人。refugee は国を追われた人"}]},

  {id:1516,word:"ally",partOfSpeech:"名詞",meaning:"同盟国，味方",
   meanings:["名|同盟国，味方","他|（be allied with で）～と同盟している"],
   pronunciation:"/ˈælaɪ/",part:152,
   example:"Britain was an important ally of France during the war.",
   exampleJa:"戦争中、イギリスはフランスの重要な同盟国だった。",
   example2:"In our class debate, Ken became my strongest ally.",
   exampleJa2:"クラスの討論で、ケンはいちばん頼りになる味方になった。",
   etymologyProcess:"ad（～へ）＋ lig（結ぶ）→ 相手のほうへ自分を結びつけると…？",
   etymologyConclusion:"ad（～へ）＋ lig（結ぶ）→ 相手のほうへ固く結びついて助け合う相手＝同盟国",
   relatedWords:[
     {word:"alliance",meaning:"同盟",breakdown:"ad（～へ）＋ lig（結ぶ）＋ ance（名詞）→ 国どうしが結びつくこと"},
     {word:"oblige",meaning:"義務づける",breakdown:"ob（～に向かって）＋ lig（結ぶ）→ 相手に縛りつけてやらせる"},
     {word:"rely",meaning:"頼る",breakdown:"re（強く）＋ lig（結ぶ）→ 相手にしっかり結びついて身をまかせる"},
     {synonym:true,word:"partner",meaning:"仲間，相棒",breakdown:"一緒に何かをする相手。ally は共通の敵に対する味方"}]},

  {id:1517,word:"reign",partOfSpeech:"名詞",meaning:"（王の）治世，統治",
   meanings:["名|（王の）治世，統治","自|（王として）君臨する"],
   pronunciation:"/reɪn/",part:152,
   example:"The castle was built during the reign of Queen Elizabeth.",
   exampleJa:"その城はエリザベス女王の治世に建てられた。",
   example2:"The champion reigned for five years without losing once.",
   exampleJa2:"そのチャンピオンは一度も負けずに5年間君臨した。",
   etymologyProcess:"reg（治める）→ 王として国を治めている期間は…？",
   etymologyConclusion:"reg（治める）→ 王が国を治めること、またその期間＝（王の）治世",
   relatedWords:[
     {word:"region",meaning:"地域",breakdown:"reg（治める）＋ ion（名詞）→ 一人の王が治める範囲"},
     {word:"regime",meaning:"政権",breakdown:"reg（治める）→ 国を上から治める仕組み"},
     {word:"royal",meaning:"王の",breakdown:"roy（治める）＋ al（形容詞）→ 国を治める王に関する"},
     {synonym:true,word:"rule",meaning:"支配",breakdown:"治めること全般。reign は王や女王の治世に使う"}]},

  {id:1518,word:"federal",partOfSpeech:"形容詞",meaning:"連邦の，連邦政府の",
   meanings:["形|連邦の，連邦政府の"],
   pronunciation:"/ˈfedərəl/",part:152,
   example:"The federal government decides the country's defense budget.",
   exampleJa:"連邦政府が国の防衛予算を決める。",
   example2:"Germany and Brazil are both federal republics with many states.",
   exampleJa2:"ドイツとブラジルは、どちらも多くの州からなる連邦共和国だ。",
   etymologyProcess:"fed（盟約）＋ al（形容詞）→ いくつもの州が約束を結んでまとまると…？",
   etymologyConclusion:"fed（盟約）＋ al（形容詞）→ いくつもの州が約束を結び、一つにまとまった＝連邦の",
   relatedWords:[
     {word:"federation",meaning:"連邦；連盟",breakdown:"fed（盟約）＋ ation（名詞）→ 約束で結ばれたまとまり"},
     {word:"confederate",meaning:"同盟の",breakdown:"con（共に）＋ fed（盟約）＋ ate（形容詞）→ 共に盟約を結んだ"},
     {synonym:true,word:"national",meaning:"国の",breakdown:"国全体の。federal は州の集まりである国の中央に使う"},
     {synonym:true,word:"union",meaning:"連合",breakdown:"一つにまとまったもの全般。federal は州が集まった連邦に使う"}]},

  {id:1519,word:"communist",partOfSpeech:"形容詞",meaning:"共産主義の",
   meanings:["形|共産主義の","名|共産主義者"],
   pronunciation:"/ˈkɑːmjənɪst/",part:152,
   example:"The country was ruled by a communist party for decades.",
   exampleJa:"その国は何十年もの間、共産主義の政党に支配されていた。",
   example2:"My grandfather was a communist when he was young.",
   exampleJa2:"祖父は若いころ、共産主義者だった。",
   etymologyProcess:"com（共に）＋ mun（分け合う）＋ ist（人）→ 財産をみんなで分け合う考えは…？",
   etymologyConclusion:"com（共に）＋ mun（分け合う）＋ ist（人）→ 財産をみんなで共に持とうとする考えの＝共産主義の",
   relatedWords:[
     {word:"common",meaning:"共通の",breakdown:"com（共に）＋ mun（分け合う）→ みんなで分け合って持つ"},
     {word:"community",meaning:"地域社会",breakdown:"com（共に）＋ mun（分け合う）＋ ity（名詞）→ 暮らしを分け合う人々"},
     {word:"communicate",meaning:"伝え合う",breakdown:"com（共に）＋ mun（分け合う）＋ ate（動詞）→ 考えを分け合う"},
     {word:"communal",meaning:"共同の",breakdown:"com（共に）＋ mun（分け合う）＋ al（形容詞）→ みんなで分け合って使う"}]},

  {id:1520,word:"municipal",partOfSpeech:"形容詞",meaning:"市の，市営の",
   meanings:["形|市の，市営の，地方自治体の"],
   pronunciation:"/mjuːˈnɪsɪpl/",part:152,
   example:"We swim at the municipal pool every summer.",
   exampleJa:"私たちは毎年夏、市のプールで泳ぐ。",
   example2:"Municipal elections will be held in our city next month.",
   exampleJa2:"来月、私たちの市で市の選挙が行われる。",
   etymologyProcess:"mun（務め）＋ cip（取る）＋ al（形容詞）→ 町の務めを自分たちで引き受けると…？",
   etymologyConclusion:"mun（務め）＋ cip（取る）＋ al（形容詞）→ 町の務めを住民が引き受けて治める＝市の",
   why:"【なぜ】ラテン語 municipium は munia（公の務め）＋ capere（取る）で、「ローマ市民としての務めを引き受けた町」。自分たちで町を運営しながらローマに従う町を指したことから、「市の・地方自治体の」になりました。\n【つながり】community や common の mun も、務めや持ち物を分け合う仲間。municipal office は「市役所」です。",
   relatedWords:[
     {word:"community",meaning:"地域社会",breakdown:"com（共に）＋ mun（分け合う）＋ ity（名詞）→ 暮らしを分け合う人々"},
     {word:"participate",meaning:"参加する",breakdown:"part（分ける）＋ cip（取る）＋ ate（動詞）→ 分けた一部を受け持つ"},
     {synonym:true,word:"local",meaning:"地元の",breakdown:"その土地の。municipal は市や町の役所が行う"},
     {synonym:true,word:"public",meaning:"公共の",breakdown:"みんなのための。municipal は市が運営する公共のもの"}]},

  {id:1521,word:"estate",partOfSpeech:"名詞",meaning:"（広い）地所，屋敷；（遺された）財産",
   meanings:["名|（広い）地所，屋敷","名|（死後に遺された）財産","名|（real estate で）不動産"],
   pronunciation:"/ɪˈsteɪt/",part:153,
   example:"The rich family lives on a large estate by the lake.",
   exampleJa:"その裕福な一家は、湖のそばの広い地所に住んでいる。",
   example2:"Her father's estate was divided among his three children.",
   exampleJa2:"彼女の父の遺した財産は、3人の子どもで分けられた。",
   etymologyProcess:"sta（立つ）→ その人の身分が立つもとになる土地や持ち物は…？",
   etymologyConclusion:"sta（立つ）→ 身分を支えて立たせる、その人の土地や持ち物＝（広い）地所，屋敷",
   why:"【なぜ】ラテン語 status（立っている状態）が古いフランス語で estat になりました。もとは「身分・地位」の意味で、中世では身分は持っている土地で決まったため、「身分を支える土地や財産」＝地所を指すようになりました。\n【つながり】state（状態・国家）、status（地位）はまったく同じ語から出た兄弟です。",
   relatedWords:[
     {word:"state",meaning:"状態；国家",breakdown:"sta（立つ）→ 立っているありさま"},
     {word:"status",meaning:"地位",breakdown:"sta（立つ）→ 社会の中で立っている位置"},
     {word:"stable",meaning:"安定した",breakdown:"sta（立つ）＋ able（できる）→ ぐらつかずに立っていられる"},
     {synonym:true,word:"property",meaning:"財産，所有地",breakdown:"持っている物全般。estate は広い土地や屋敷"}]},

  {id:1522,word:"asset",partOfSpeech:"名詞",meaning:"資産；強み",
   meanings:["名|（通例 assets で）資産","名|（役に立つ）強み，貴重な人"],
   pronunciation:"/ˈæset/",part:153,
   example:"The company sold some of its assets to pay its debts.",
   exampleJa:"その会社は借金を返すために資産の一部を売った。",
   example2:"Her kindness is a great asset to our team.",
   exampleJa2:"彼女の優しさは、うちのチームにとって大きな強みだ。",
   etymologyProcess:"ad（～へ）＋ sat（十分な）→ 借りを返すのに十分なほどあるものは…？",
   etymologyConclusion:"ad（～へ）＋ sat（十分な）→ 借りを返すのに十分なだけ持っている財産＝資産",
   why:"【なぜ】古いフランス語 asez（十分に）から。ラテン語 ad satis（十分なほどまで）がもとです。法律では「亡くなった人の借金を払うのに十分な財産」を assets と呼びました。そこから「持っている財産」＝資産、さらに「役に立つもの」＝強みになりました。\n【つながり】satisfy（十分に満たす）の sat と同じ家族です。",
   relatedWords:[
     {word:"satisfy",meaning:"満足させる",breakdown:"sat（十分な）＋ fy（する）→ 十分なところまで満たす"},
     {word:"satisfaction",meaning:"満足",breakdown:"sat（十分な）＋ fic（作る）＋ ion（名詞）→ 十分に満たされた気持ち"},
     {synonym:true,word:"property",meaning:"財産",breakdown:"持ち物全般。asset はお金に換えられる価値あるもの"},
     {synonym:true,word:"advantage",meaning:"有利な点",breakdown:"ほかより有利なところ。asset は役に立つ人や能力にも使う"}]},

  {id:1523,word:"revenue",partOfSpeech:"名詞",meaning:"（国や企業の）歳入，総収入",
   meanings:["名|（国の）歳入","名|（企業の）総収入，売上"],
   pronunciation:"/ˈrevənuː/",part:153,
   example:"Tax revenue fell sharply during the economic crisis.",
   exampleJa:"経済危機の間、税の歳入が大きく落ちこんだ。",
   example2:"The game company's revenue doubled after the new release.",
   exampleJa2:"そのゲーム会社の総収入は、新作の発売後に倍になった。",
   etymologyProcess:"re（元へ）＋ ven（来る）→ 出したお金が手元へ戻って来ると…？",
   etymologyConclusion:"re（元へ）＋ ven（来る）→ 国や会社の手元へ戻って入って来るお金＝（国や企業の）歳入",
   relatedWords:[
     {word:"event",meaning:"出来事",breakdown:"e（外へ）＋ vent（来る）→ 外に現れ出てきたこと"},
     {word:"convenient",meaning:"便利な",breakdown:"con（共に）＋ ven（来る）→ 必要なものが一緒に来ていて都合がよい"},
     {word:"avenue",meaning:"大通り",breakdown:"ad（～へ）＋ ven（来る）→ 町へ入って来るための道"},
     {synonym:true,word:"income",meaning:"収入",breakdown:"個人の稼ぎ。revenue は国や企業に入るお金"}]},

  {id:1524,word:"deficit",partOfSpeech:"名詞",meaning:"赤字，不足額",
   meanings:["名|赤字，不足額","名|（能力などの）不足"],
   pronunciation:"/ˈdefɪsɪt/",part:153,
   example:"The government is trying to reduce its huge budget deficit.",
   exampleJa:"政府は巨額の財政赤字を減らそうとしている。",
   example2:"Our club had a deficit after buying new uniforms.",
   exampleJa2:"新しいユニフォームを買ったあと、部は赤字になった。",
   etymologyProcess:"de（離して）＋ fic（作る）→ 必要な分を作れずに足りないと…？",
   etymologyConclusion:"de（離して）＋ fic（作る）→ 必要な額から離れて作りきれず足りない分＝赤字",
   why:"【なぜ】ラテン語 deficit は「足りない」という動詞そのもので、de（離れて）＋ facere（作る・する）の deficere（欠ける）から来ています。昔の会計帳簿で「〇〇が足りない」と書きこむ語だったので、名詞として「不足額」＝赤字になりました。\n【つながり】deficient（不足した）、defect（欠点）が同じ家族。日本語の「赤字」は赤いインクで書いたことから。",
   relatedWords:[
     {word:"defect",meaning:"欠点，欠陥",breakdown:"de（離して）＋ fect（作る）→ 作りそこなって欠けたところ"},
     {word:"efficient",meaning:"効率のよい",breakdown:"ef（外へ）＋ fic（作る）→ むだなく成果を外へ作り出す"},
     {word:"deficient",meaning:"不足した",breakdown:"de（離して）＋ fic（作る）＋ ent（～している）→ 足りないままの"},
     {synonym:true,word:"shortage",meaning:"不足",breakdown:"物が足りないこと。deficit はお金の足りない額"}]},

  {id:1525,word:"commerce",partOfSpeech:"名詞",meaning:"商業，通商",
   meanings:["名|商業，通商"],
   pronunciation:"/ˈkɑːmɜːrs/",part:153,
   example:"The port city became a center of international commerce.",
   exampleJa:"その港町は国際的な商業の中心地になった。",
   example2:"Online commerce has grown quickly in recent years.",
   exampleJa2:"ネットでの商業は、ここ数年で急速に広がった。",
   etymologyProcess:"com（共に）＋ merc（商品）→ 商品を持ち寄ってやりとりすると…？",
   etymologyConclusion:"com（共に）＋ merc（商品）→ 人々が商品を持ち寄って売り買いすること＝商業",
   relatedWords:[
     {word:"merchant",meaning:"商人",breakdown:"merc（商品）＋ ant（人）→ 商品を売り買いする人"},
     {word:"market",meaning:"市場",breakdown:"merc（商品）→ 商品を持ち寄って売り買いする場"},
     {word:"commercial",meaning:"商業の；コマーシャル",breakdown:"com（共に）＋ merc（商品）＋ ial（形容詞）→ 売り買いに関する"},
     {synonym:true,word:"trade",meaning:"貿易，取引",breakdown:"品物のやりとり。commerce は商業活動全体"}]},

  {id:1526,word:"output",partOfSpeech:"名詞",meaning:"生産高；出力",
   meanings:["名|生産高","名|（機械やコンピュータの）出力"],
   pronunciation:"/ˈaʊtpʊt/",part:153,
   example:"The factory's output rose by ten percent this year.",
   exampleJa:"その工場の生産高は今年10パーセント増えた。",
   example2:"This speaker has a much higher output than mine.",
   exampleJa2:"このスピーカーは、私のものよりずっと出力が大きい。",
   etymologyProcess:"out（外へ）＋ put（置く）→ 工場から外へ出して置いた量は…？",
   etymologyConclusion:"out（外へ）＋ put（置く）→ 工場や機械が外へ出して置いた量＝生産高",
   relatedWords:[
     {word:"input",meaning:"入力",breakdown:"in（中へ）＋ put（置く）→ 中へ入れて置くこと"},
     {word:"outcome",meaning:"結果",breakdown:"out（外へ）＋ come（来る）→ 最後に外へ出てきたもの"},
     {word:"outline",meaning:"輪郭，概要",breakdown:"out（外へ）＋ line（線）→ いちばん外側の線"},
     {synonym:true,word:"production",meaning:"生産",breakdown:"作り出すこと。output は作り出された量"}]},

  {id:1527,word:"subsidy",partOfSpeech:"名詞",meaning:"（政府の）補助金",
   meanings:["名|（政府の）補助金，助成金"],
   pronunciation:"/ˈsʌbsədi/",part:153,
   example:"Farmers receive a government subsidy for growing rice.",
   exampleJa:"農家は米作りに対して政府から補助金を受け取っている。",
   example2:"The city gives subsidies to families with small children.",
   exampleJa2:"市は小さな子どものいる家庭に補助金を出している。",
   etymologyProcess:"sub（下で）＋ sid（座る）→ 下に控えていて、いざというとき支えるものは…？",
   etymologyConclusion:"sub（下で）＋ sid（座る）→ 下に控えていて、足りない所を支えるお金＝（政府の）補助金",
   why:"【なぜ】ラテン語 subsidium は sub（後ろに）＋ sedere（座る）で、もとは「後ろの列に控えている予備の兵」。前の兵が苦しくなると助けに出たことから「助け・援助」になり、英語では政府が出す援助のお金＝補助金になりました。\n【つながり】president（先頭に座る人）、reside（住む）も sid の仲間です。",
   relatedWords:[
     {word:"president",meaning:"大統領，社長",breakdown:"pre（先に）＋ sid（座る）→ いちばん先の席に座る人"},
     {word:"reside",meaning:"住む",breakdown:"re（後ろへ）＋ sid（座る）→ 後ろに残って腰を落ち着ける"},
     {word:"subside",meaning:"おさまる",breakdown:"sub（下で）＋ sid（座る）→ 下へ座りこんで静まる"},
     {synonym:true,word:"grant",meaning:"助成金",breakdown:"研究や事業に与えるお金。subsidy は政府が産業や家計を支えるお金"}]},

  {id:1528,word:"transaction",partOfSpeech:"名詞",meaning:"（お金の）取り引き，売買",
   meanings:["名|（お金の）取り引き，売買"],
   pronunciation:"/trænˈzækʃn/",part:153,
   example:"Every transaction at this bank is recorded carefully.",
   exampleJa:"この銀行でのすべての取り引きは、注意深く記録される。",
   example2:"Many transactions can now be made with a smartphone.",
   exampleJa2:"今では多くの取り引きをスマホで済ませられる。",
   etymologyProcess:"trans（越えて）＋ act（追い立てる）＋ ion（名詞）→ 物事を相手の側へ押し進めると…？",
   etymologyConclusion:"trans（越えて）＋ act（追い立てる）＋ ion（名詞）→ 品物とお金を相手側へやりとりして進めること＝（お金の）取り引き",
   relatedWords:[
     {word:"action",meaning:"行動",breakdown:"act（追い立てる）＋ ion（名詞）→ 物事を前へ動かすこと"},
     {word:"react",meaning:"反応する",breakdown:"re（後ろへ）＋ act（追い立てる）→ 押されて押し返す"},
     {word:"activity",meaning:"活動",breakdown:"act（追い立てる）＋ ive（形容詞）＋ ity（名詞）→ 物事を動かしていること"},
     {synonym:true,word:"deal",meaning:"取引",breakdown:"くだけた言い方。transaction は記録に残る正式なもの"}]},

  {id:1529,word:"bankrupt",partOfSpeech:"形容詞",meaning:"倒産した，破産した",
   meanings:["形|倒産した，破産した","他|～を破産させる"],
   pronunciation:"/ˈbæŋkrʌpt/",part:153,
   example:"The old bookstore went bankrupt after thirty years.",
   exampleJa:"その古い本屋は、30年続いたあとに倒産した。",
   example2:"Bad investments could make even a big company bankrupt.",
   exampleJa2:"下手な投資をすれば、大企業でさえ破産しかねない。",
   etymologyProcess:"bank（両替台）＋ rupt（破る）→ 商売の台をこわされると…？",
   etymologyConclusion:"bank（両替台）＋ rupt（破る）→ 払えなくなって商売の台をこわされた＝倒産した",
   why:"【なぜ】イタリア語 banca rotta（こわれた台）から。中世イタリアの両替商は広場に台（banca）を出して商売しましたが、借金を払えなくなると、その台をこわされたといわれます。\n【つながり】bank（銀行）はこの「両替台」から。rupt（破る）は interrupt、erupt と同じ家族です。",
   relatedWords:[
     {word:"bank",meaning:"銀行",breakdown:"bank（両替台）→ 両替商がお金を並べた台"},
     {word:"interrupt",meaning:"じゃまをする",breakdown:"inter（間の）＋ rupt（破る）→ 話の間に割りこんで破る"},
     {word:"erupt",meaning:"噴火する",breakdown:"e（外へ）＋ rupt（破る）→ 山が内から破れて外へ噴き出す"},
     {synonym:true,word:"broke",meaning:"一文なしの",breakdown:"くだけた言い方で個人に使う。bankrupt は会社や法的な破産"}]},

  {id:1530,word:"monetary",partOfSpeech:"形容詞",meaning:"金融の，貨幣の",
   meanings:["形|金融の，貨幣の"],
   pronunciation:"/ˈmɑːnəteri/",part:153,
   example:"The central bank changed its monetary policy last month.",
   exampleJa:"中央銀行は先月、金融政策を変えた。",
   example2:"The old coins have little monetary value today.",
   exampleJa2:"その古い硬貨には、今ではほとんど貨幣としての価値がない。",
   etymologyProcess:"monet（お金）＋ ary（形容詞）→ お金そのものに関することなら…？",
   etymologyConclusion:"monet（お金）＋ ary（形容詞）→ 国が出すお金の量や価値に関する＝金融の",
   why:"【なぜ】ローマの女神ユノ・モネタの神殿で硬貨が造られていたので、moneta が「造幣所・お金」を指すようになりました。モネタは monere（注意させる）から来た呼び名とされます。\n【つながり】money（お金）も moneta から。monitor（注意して見張る）は monere の仲間で、遠い親せきにあたります。",
   relatedWords:[
     {word:"money",meaning:"お金",breakdown:"monet（お金）→ 神殿で造られた硬貨"},
     {word:"monitor",meaning:"監視する",breakdown:"mon（思い出させる）＋ or（もの）→ 注意をうながして見張るもの"},
     {synonym:true,word:"financial",meaning:"財政の，金融の",breakdown:"お金のやりくり全般。monetary は国の通貨に関して"},
     {word:"monetize",meaning:"収益化する",breakdown:"monet（お金）＋ ize（動詞）→ お金に変える"}]},

  {id:1531,word:"corporation",partOfSpeech:"名詞",meaning:"（大）企業，法人",
   meanings:["名|（大）企業，法人"],
   pronunciation:"/ˌkɔːrpəˈreɪʃn/",part:154,
   example:"He works for a large corporation with offices worldwide.",
   exampleJa:"彼は世界中に事務所を持つ大企業で働いている。",
   example2:"Many corporations were criticized for polluting the river.",
   exampleJa2:"多くの企業が川を汚したことで批判された。",
   etymologyProcess:"corpor（体）＋ ation（名詞）→ 大勢の人が一つの体のようにまとまると…？",
   etymologyConclusion:"corpor（体）＋ ation（名詞）→ 大勢の人が一つの体のようにまとまった組織＝（大）企業",
   why:"【なぜ】ラテン語 corporare は「一つの体にまとめる」。中世では、町や職人の組合を法律上「一人の体（人）」として扱い、corporation と呼びました。そこから、法律上の人として認められた会社＝法人・企業の意味になりました。\n【つながり】corpse（死体）、corps（部隊）も corpor の家族。日本語の「法人」も「法律上の人」という考え方です。",
   relatedWords:[
     {word:"corporate",meaning:"企業の",breakdown:"corpor（体）＋ ate（形容詞）→ 一つの体にまとまった組織の"},
     {word:"incorporate",meaning:"取り入れる",breakdown:"in（中へ）＋ corpor（体）＋ ate（動詞）→ 体の中へ組みこむ"},
     {word:"corps",meaning:"部隊，団",breakdown:"corpor（体）→ 一つの体のように動く人の集まり"},
     {synonym:true,word:"company",meaning:"会社",breakdown:"会社全般。corporation は大きな会社や法人"}]},

  {id:1532,word:"enterprise",partOfSpeech:"名詞",meaning:"（大胆な）事業，企て；企業",
   meanings:["名|（大胆な）事業，企て","名|企業","名|進取の気性"],
   pronunciation:"/ˈentərpraɪz/",part:154,
   example:"Building a bridge across the bay was a huge enterprise.",
   exampleJa:"湾に橋をかけるのは巨大な事業だった。",
   example2:"Small enterprises employ most of the workers in this town.",
   exampleJa2:"この町では、小さな企業が働く人の大半を雇っている。",
   etymologyProcess:"entre（間の）＋ pris（つかむ）→ 両手の間にしっかりつかんで取りかかると…？",
   etymologyConclusion:"entre（間の）＋ pris（つかむ）→ 両手でしっかりつかんで取りかかる大仕事＝（大胆な）事業",
   relatedWords:[
     {word:"entrepreneur",meaning:"起業家",breakdown:"entre（間の）＋ pren（つかむ）→ 事業を手につかんで始める人"},
     {word:"surprise",meaning:"驚かせる",breakdown:"sur（上から）＋ pris（つかむ）→ 上からいきなりつかみかかる"},
     {word:"prison",meaning:"刑務所",breakdown:"pris（つかむ）→ つかまえた人を入れておく所"},
     {synonym:true,word:"project",meaning:"事業，計画",breakdown:"計画された仕事。enterprise は危険を承知の大仕事"}]},

  {id:1533,word:"venture",partOfSpeech:"名詞",meaning:"（危険を伴う）新事業，冒険的な企て",
   meanings:["名|（危険を伴う）新事業，冒険的な企て","自|（危険を冒して）思い切って進む"],
   pronunciation:"/ˈventʃər/",part:154,
   example:"Their new venture failed within a year of opening.",
   exampleJa:"彼らの新事業は、始めて1年もたたずに失敗した。",
   example2:"We ventured into the dark cave with only one flashlight.",
   exampleJa2:"私たちは懐中電灯1本だけで、暗いほら穴へ思い切って入った。",
   etymologyProcess:"vent（来る）→ 何がやって来るか分からない先へ踏み出すと…？",
   etymologyConclusion:"vent（来る）→ 何がやって来るか分からない先へ踏み出す企て＝（危険を伴う）新事業",
   why:"【なぜ】venture は adventure（冒険）の頭を落として縮めた語。adventure はラテン語 advenire（～へやって来る）から出て、もとは「身にふりかかって来ること・運」でした。そこから「運にまかせて挑む企て」になり、今の「危険を伴う新事業」になりました。\n【つながり】「ベンチャー企業」はこの語。event（外に現れ来ること）も vent の家族です。",
   relatedWords:[
     {word:"adventure",meaning:"冒険",breakdown:"ad（～へ）＋ vent（来る）→ 身にふりかかって来る出来事"},
     {word:"event",meaning:"出来事",breakdown:"e（外へ）＋ vent（来る）→ 外に現れ出てきたこと"},
     {word:"prevent",meaning:"防ぐ",breakdown:"pre（先に）＋ vent（来る）→ 先回りして来て立ちふさがる"},
     {synonym:true,word:"undertaking",meaning:"事業，仕事",breakdown:"引き受けた仕事。venture は失敗の危険が大きいもの"}]},

  {id:1534,word:"headquarters",partOfSpeech:"名詞",meaning:"本社，本部",
   meanings:["名|本社，本部","名|（軍の）司令部"],
   pronunciation:"/ˈhedkwɔːrtərz/",part:154,
   example:"The company's headquarters is located in central Tokyo.",
   exampleJa:"その会社の本社は東京の中心部にある。",
   example2:"The police moved their headquarters to a new building.",
   exampleJa2:"警察は本部を新しい建物へ移した。",
   etymologyProcess:"head（頭）＋ quarter（区域）→ 全体の頭にあたる区域は…？",
   etymologyConclusion:"head（頭）＋ quarter（区域）→ 組織全体の頭として指図する区域＝本社",
   relatedWords:[
     {word:"quarter",meaning:"4分の1；地区",breakdown:"quarter（区域）→ 町を4つに分けた一区画"},
     {word:"headline",meaning:"見出し",breakdown:"head（頭）＋ line（線）→ 記事のいちばん上の行"},
     {word:"forehead",meaning:"額（ひたい）",breakdown:"fore（前に）＋ head（頭）→ 頭のいちばん前の面"},
     {synonym:true,word:"head office",meaning:"本社",breakdown:"ほぼ同じ意味。headquarters は軍や警察にも使う"}]},

  {id:1535,word:"personnel",partOfSpeech:"名詞",meaning:"（組織の）人員，全職員；人事部",
   meanings:["名|（組織の）人員，全職員","名|人事部"],
   pronunciation:"/ˌpɜːrsəˈnel/",part:154,
   example:"Only trained medical personnel may enter this room at night.",
   exampleJa:"夜間この部屋に入れるのは、訓練を受けた医療関係の人員だけだ。",
   example2:"Please send your application to the personnel office.",
   exampleJa2:"応募書類は人事部へ送ってください。",
   etymologyProcess:"person（人）→ 組織に関わる人たちをまとめて呼ぶと…？",
   etymologyConclusion:"person（人）→ 組織に関わる人たち全体＝（組織の）人員",
   relatedWords:[
     {word:"person",meaning:"人",breakdown:"person（人）→ 一人ひとりの人"},
     {word:"personal",meaning:"個人の",breakdown:"person（人）＋ al（形容詞）→ その人だけの"},
     {word:"personality",meaning:"性格，個性",breakdown:"person（人）＋ al（形容詞）＋ ity（名詞）→ その人らしさ"},
     {synonym:true,word:"staff",meaning:"職員",breakdown:"働いている人たち。personnel はかたい言い方"}]},

  {id:1536,word:"entrepreneur",partOfSpeech:"名詞",meaning:"起業家",
   meanings:["名|起業家"],
   pronunciation:"/ˌɑːntrəprəˈnɜːr/",part:154,
   example:"The young entrepreneur started her company in a garage.",
   exampleJa:"その若い起業家は、ガレージで会社を始めた。",
   example2:"Many students at our school dream of becoming successful entrepreneurs.",
   exampleJa2:"うちの学校の多くの生徒が、成功した起業家になることを夢見ている。",
   etymologyProcess:"entre（間の）＋ pren（つかむ）→ 事業を両手でつかんで始める人は…？",
   etymologyConclusion:"entre（間の）＋ pren（つかむ）→ 新しい事業を自分の手につかんで始める人＝起業家",
   relatedWords:[
     {word:"enterprise",meaning:"事業",breakdown:"entre（間の）＋ pris（つかむ）→ 両手でつかんで取りかかる大仕事"},
     {word:"surprise",meaning:"驚かせる",breakdown:"sur（上から）＋ pris（つかむ）→ 上からいきなりつかみかかる"},
     {word:"comprehend",meaning:"理解する",breakdown:"com（共に）＋ prehend（つかむ）→ 意味をまるごとつかむ"},
     {synonym:true,word:"founder",meaning:"創業者",breakdown:"会社を作った人。entrepreneur は危険を負って挑む人"}]},

  {id:1537,word:"predecessor",partOfSpeech:"名詞",meaning:"前任者；前のもの",
   meanings:["名|前任者","名|（機械などの）前のもの，前作"],
   pronunciation:"/ˈpredəsesər/",part:154,
   example:"The new principal is stricter than her predecessor.",
   exampleJa:"新しい校長は前任者よりも厳しい。",
   example2:"This phone is much lighter than its predecessor.",
   exampleJa2:"このスマホは前の機種よりずっと軽い。",
   etymologyProcess:"pre（先に）＋ de（離して）＋ cess（行く）＋ or（人）→ 先に去って行った人は…？",
   etymologyConclusion:"pre（先に）＋ de（離して）＋ cess（行く）＋ or（人）→ 先にその座を離れて去った人＝前任者",
   relatedWords:[
     {word:"process",meaning:"過程",breakdown:"pro（前へ）＋ cess（行く）→ 前へ進んでいく道のり"},
     {word:"success",meaning:"成功",breakdown:"sub（下で）＋ cess（行く）→ あとに続いて、うまく行くこと"},
     {word:"precede",meaning:"先に起こる",breakdown:"pre（先に）＋ ced（行く）→ 先に行く"},
     {word:"ancestor",meaning:"先祖",breakdown:"ante（前に）＋ cest（行く）→ 自分より前を行った人たち"}]},

  {id:1538,word:"toil",partOfSpeech:"自動詞",meaning:"骨折って働く，苦労する",
   meanings:["自|骨折って働く，苦労する","名|骨の折れる仕事，苦労"],
   pronunciation:"/tɔɪl/",part:154,
   example:"Farmers toil in the fields from morning till night.",
   exampleJa:"農家は朝から晩まで畑で骨折って働く。",
   example2:"After years of toil, she finally opened her own shop.",
   exampleJa2:"何年もの苦労のすえ、彼女はついに自分の店を開いた。",
   etymologyProcess:"toil（もみくちゃにする）→ もみくちゃになりながら働くと…？",
   etymologyConclusion:"toil（もみくちゃにする）→ 体がもみくちゃになるほどつらい仕事を続ける＝骨折って働く",
   hook:"古いフランス語 toillier（かき回す・もみくちゃにする）から。hard work より文学的。",
   relatedWords:[
     {synonym:true,word:"labor",meaning:"労働；骨折る",breakdown:"体を使う仕事。toil は長くつらい苦労"},
     {synonym:true,word:"work hard",meaning:"一生懸命働く",breakdown:"ふつうの言い方。toil は疲れ果てる感じが強い"},
     {synonym:true,word:"slave away",meaning:"あくせく働く",breakdown:"休みなく働き続ける。toil とほぼ同じで、くだけた言い方"},
     {synonym:true,word:"drudgery",meaning:"骨折り仕事",breakdown:"退屈でつらい仕事。toil も同じ感じで使う"}]},

  {id:1539,word:"undertake",partOfSpeech:"他動詞",meaning:"（仕事や責任を）引き受ける，始める",
   meanings:["他|（仕事や責任）を引き受ける，始める","他|（to do することを）約束する"],
   pronunciation:"/ˌʌndərˈteɪk/",part:154,
   example:"Our class will undertake a big recycling project this year.",
   exampleJa:"今年、うちのクラスは大きなリサイクル計画を引き受ける。",
   example2:"The team undertook the difficult job without complaint.",
   exampleJa2:"チームはその難しい仕事を不平も言わずに引き受けた。",
   etymologyProcess:"under（下に）＋ take（取る）→ 仕事の下にもぐりこんで取りかかると…？",
   etymologyConclusion:"under（下に）＋ take（取る）→ 仕事の下へ入って自分の肩で担ぎ取る＝（仕事や責任を）引き受ける",
   relatedWords:[
     {word:"undergo",meaning:"経験する",breakdown:"under（下に）＋ go（行く）→ つらいことの下をくぐり抜ける"},
     {word:"take",meaning:"取る",breakdown:"take（取る）→ 手に取る"},
     {word:"overtake",meaning:"追い越す",breakdown:"over（越えて）＋ take（取る）→ 追いついて前を取る"},
     {synonym:true,word:"accept",meaning:"受け入れる",breakdown:"差し出されたものを受ける。undertake は仕事を自分で担う"}]},

  {id:1540,word:"merge",partOfSpeech:"他動詞・自動詞",meaning:"合併する，一つにまとまる",
   meanings:["自|（with ～と）合併する，一つにまとまる","他|～を合併させる"],
   pronunciation:"/mɜːrdʒ/",part:154,
   example:"The two small banks decided to merge next spring.",
   exampleJa:"その2つの小さな銀行は、来春合併することを決めた。",
   example2:"Two lanes merged into one near the tunnel.",
   exampleJa2:"トンネルの近くで、2車線が1車線にまとまった。",
   etymologyProcess:"merg（沈める）→ 二つのものを同じ水に沈めて溶けこませると…？",
   etymologyConclusion:"merg（沈める）→ 別々のものが同じ水の中へ沈み、溶けあって一つになる＝合併する",
   why:"【なぜ】ラテン語 mergere は「水に沈める・浸す」。英語でもはじめは「沈める」の意味でしたが、17世紀ごろから「沈んで見分けがつかなくなる」＝一つに溶けこむ意味で使われ、やがて会社や道が「合併する・合流する」になりました。\n【つながり】emerge（水の外へ出る→現れる）、emergency（急に現れる事態）も同じ家族です。",
   relatedWords:[
     {word:"emerge",meaning:"現れる",breakdown:"e（外へ）＋ merg（沈める）→ 沈んでいた所から外へ出る"},
     {word:"emergency",meaning:"緊急事態",breakdown:"e（外へ）＋ merg（沈める）＋ ency（名詞）→ 急に浮かび出てくる事態"},
     {word:"submerge",meaning:"水中に沈める",breakdown:"sub（下で）＋ merg（沈める）→ 水面の下へ沈める"},
     {synonym:true,word:"combine",meaning:"結びつける",breakdown:"二つを組み合わせること。merge は区別がなくなるまで一つになる"}]},

  {id:1541,word:"comprise",partOfSpeech:"他動詞",meaning:"～から成る；～を構成する",
   meanings:["他|～から成る，～を含む","他|～を構成する"],
   pronunciation:"/kəmˈpraɪz/",part:155,
   example:"The committee will comprise ten teachers and five students.",
   exampleJa:"その委員会は、先生10人と生徒5人から成る予定だ。",
   example2:"Women comprised more than half of the audience.",
   exampleJa2:"観客の半数以上を女性が構成していた。",
   etymologyProcess:"com（共に）＋ pris（つかむ）→ いくつもの部分をひとまとめにつかむと…？",
   etymologyConclusion:"com（共に）＋ pris（つかむ）→ いくつもの部分をひとまとめにつかんで持つ＝～から成る",
   relatedWords:[
     {word:"enterprise",meaning:"事業",breakdown:"entre（間の）＋ pris（つかむ）→ 両手でつかんで取りかかる大仕事"},
     {word:"surprise",meaning:"驚かせる",breakdown:"sur（上から）＋ pris（つかむ）→ 上からいきなりつかみかかる"},
     {word:"comprehend",meaning:"理解する",breakdown:"com（共に）＋ prehend（つかむ）→ 意味をまるごとつかむ"},
     {synonym:true,word:"consist of",meaning:"～から成る",breakdown:"ほぼ同じ意味の言い方。comprise のほうがかたい"}]},

  {id:1542,word:"component",partOfSpeech:"名詞",meaning:"構成要素，部品",
   meanings:["名|構成要素，部品"],
   pronunciation:"/kəmˈpoʊnənt/",part:155,
   example:"Trust is an important component of any friendship.",
   exampleJa:"信頼は、どんな友情にも欠かせない構成要素だ。",
   example2:"This factory in our town makes small components for smartphones.",
   exampleJa2:"町のこの工場は、スマートフォン用の小さな部品を作っている。",
   etymologyProcess:"com（共に）＋ pon（置く）＋ ent（もの）→ 一緒に置かれて全体を作るものは…？",
   etymologyConclusion:"com（共に）＋ pon（置く）＋ ent（もの）→ ほかと一緒に置かれて全体を作る一つ＝構成要素",
   relatedWords:[
     {word:"compose",meaning:"構成する",breakdown:"com（共に）＋ pos（置く）→ いくつもを一緒に置いて組み立てる"},
     {word:"opponent",meaning:"相手，敵",breakdown:"op（向かい合って）＋ pon（置く）＋ ent（人）→ 向かいに置かれた人"},
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ion（名詞）→ 置かれている場所"},
     {synonym:true,word:"part",meaning:"部分，部品",breakdown:"一部分全般。component は全体を組み立てる一要素"}]},

  {id:1543,word:"framework",partOfSpeech:"名詞",meaning:"（考えや制度の）枠組み；骨組み",
   meanings:["名|（考えや制度の）枠組み","名|（建物の）骨組み"],
   pronunciation:"/ˈfreɪmwɜːrk/",part:155,
   example:"The new law provides a framework for protecting children online.",
   exampleJa:"新しい法律は、ネット上で子どもを守るための枠組みを定めている。",
   example2:"Only the steel framework of the building was left after the fire.",
   exampleJa2:"火事のあと、建物の鉄の骨組みだけが残った。",
   etymologyProcess:"frame（枠）＋ work（仕事）→ 全体を形づくる枠の作りは…？",
   etymologyConclusion:"frame（枠）＋ work（仕事）→ 中身を支えて形を決める枠の作り＝（考えや制度の）枠組み",
   relatedWords:[
     {word:"frame",meaning:"枠，額縁",breakdown:"frame（枠）→ まわりを囲んで形を保つもの"},
     {word:"homework",meaning:"宿題",breakdown:"home（家）＋ work（仕事）→ 家でやる勉強の仕事"},
     {word:"network",meaning:"網状組織，ネットワーク",breakdown:"net（網）＋ work（仕事）→ 網の目のように作り上げたもの"},
     {synonym:true,word:"structure",meaning:"構造",breakdown:"組み立て全体。framework は土台となる枠の部分"}]},

  {id:1544,word:"prototype",partOfSpeech:"名詞",meaning:"試作品；原型",
   meanings:["名|試作品","名|原型，典型"],
   pronunciation:"/ˈproʊtətaɪp/",part:155,
   example:"The engineers tested a prototype of the new electric car.",
   exampleJa:"技術者たちは新しい電気自動車の試作品を試した。",
   example2:"Our robot club built three prototypes before the contest.",
   exampleJa2:"うちのロボット部は、大会の前に試作品を3つ作った。",
   etymologyProcess:"proto（最初の）＋ typ（打った跡）→ 最初に打ち出された型は…？",
   etymologyConclusion:"proto（最初の）＋ typ（打った跡）→ 最初に打ち出した、もとになる型＝試作品",
   relatedWords:[
     {word:"type",meaning:"型，種類",breakdown:"typ（打った跡）→ 打ちつけてできた決まった形"},
     {word:"typical",meaning:"典型的な",breakdown:"typ（打った跡）＋ ical（形容詞）→ 型どおりの"},
     {synonym:true,word:"sample",meaning:"見本",breakdown:"一部を取り出した見本。prototype は最初に作った試しの品"},
     {synonym:true,word:"model",meaning:"模型，見本",breakdown:"見本全般。prototype は量産前の最初の試作"}]},

  {id:1545,word:"dimension",partOfSpeech:"名詞",meaning:"次元；（問題の）側面，規模",
   meanings:["名|次元","名|（問題の）側面","名|（dimensions で）寸法，規模"],
   pronunciation:"/daɪˈmenʃn/",part:155,
   example:"A cube has three dimensions: length, width, and height.",
   exampleJa:"立方体には縦・横・高さの3つの次元がある。",
   example2:"The problem has a political dimension as well.",
   exampleJa2:"その問題には政治的な側面もある。",
   etymologyProcess:"di（離れて）＋ mensi（測る）→ 端から端まで離して測った長さは…？",
   etymologyConclusion:"di（離れて）＋ mensi（測る）→ 端から端まで測り分けた、広がりの向き＝次元",
   why:"【なぜ】ラテン語 dimetiri は「すみずみまで測る」。そこから「測った大きさ・寸法」になり、縦・横・高さのような「測る向き」＝次元を指すようになりました。さらに「物事をどの向きから測るか」ということから、問題の「側面」の意味も生まれました。\n【つながり】measure（測る）と同じ家族。「3D」の D は dimension の頭文字です。",
   relatedWords:[
     {word:"measure",meaning:"測る",breakdown:"meas（測る）＋ ure（名詞）→ 長さや量を測ること"},
     {word:"immense",meaning:"巨大な",breakdown:"in（否定）＋ mensi（測る）→ 測りきれないほど大きい"},
     {synonym:true,word:"aspect",meaning:"側面",breakdown:"物事の見え方の一面。dimension は広がりや奥行きも含む"},
     {synonym:true,word:"size",meaning:"大きさ",breakdown:"大きさ全般。dimensions は縦・横・高さの寸法"}]},

  {id:1546,word:"margin",partOfSpeech:"名詞",meaning:"余白；（時間などの）余裕，差",
   meanings:["名|（ページの）余白","名|（時間などの）余裕","名|（得票などの）差"],
   pronunciation:"/ˈmɑːrdʒɪn/",part:155,
   example:"Please write your notes in the margin of the page.",
   exampleJa:"メモはページの余白に書いてください。",
   example2:"Our team won the match by a narrow margin.",
   exampleJa2:"うちのチームはわずかな差で試合に勝った。",
   etymologyProcess:"marg（ふち）→ ページのふちに残された部分は…？",
   etymologyConclusion:"marg（ふち）→ ページのふちに残された、何も書いていない部分＝余白",
   relatedWords:[
     {word:"marginal",meaning:"わずかな；周辺の",breakdown:"marg（ふち）＋ al（形容詞）→ ふちのほうにある、ほんの少しの"},
     {synonym:true,word:"edge",meaning:"ふち，端",breakdown:"物の端。margin は端に残された空き"},
     {synonym:true,word:"space",meaning:"空き，スペース",breakdown:"空いている所全般。margin はふちの空き"},
     {synonym:true,word:"room",meaning:"余地",breakdown:"入りこめる余地。margin は端や前後に取っておいた余裕"}]},

  {id:1547,word:"excel",partOfSpeech:"自動詞",meaning:"（in ～で）優れている，秀でる",
   meanings:["自|（in / at ～で）優れている，秀でる","他|～にまさる"],
   pronunciation:"/ɪkˈsel/",part:155,
   example:"Students who excel at sports can get special scholarships.",
   exampleJa:"スポーツで優れている生徒は、特別な奨学金をもらえる。",
   example2:"She has always excelled in math and science.",
   exampleJa2:"彼女は昔から数学と理科に秀でている。",
   etymologyProcess:"ex（外へ）＋ cel（高くそびえる）→ ほかより外へ高く抜きん出ると…？",
   etymologyConclusion:"ex（外へ）＋ cel（高くそびえる）→ まわりから外へ高く抜きん出ている＝（in ～で）優れている",
   relatedWords:[
     {word:"excellent",meaning:"すばらしい",breakdown:"ex（外へ）＋ cel（高くそびえる）＋ ent（～している）→ 高く抜きん出ている"},
     {word:"excellence",meaning:"優秀さ",breakdown:"ex（外へ）＋ cel（高くそびえる）＋ ence（名詞）→ 抜きん出ていること"},
     {synonym:true,word:"outdo",meaning:"～にまさる",breakdown:"相手より上をいくこと。excel は分野で抜きん出る"},
     {synonym:true,word:"shine",meaning:"光る；秀でる",breakdown:"目立って光ること。excel はかたい言い方"}]},

  {id:1548,word:"contradict",partOfSpeech:"他動詞",meaning:"～と矛盾する；～に反論する",
   meanings:["他|～と矛盾する","他|～に反論する，～を否定する"],
   pronunciation:"/ˌkɑːntrəˈdɪkt/",part:155,
   example:"His actions contradict everything he said in the speech.",
   exampleJa:"彼の行動は、演説で言ったことすべてと矛盾する。",
   example2:"Nobody on the team dared to contradict the strict coach.",
   exampleJa2:"チームのだれ一人、厳しいコーチに反論しようとはしなかった。",
   etymologyProcess:"contra（逆に）＋ dict（言う）→ 逆のことを言うと…？",
   etymologyConclusion:"contra（逆に）＋ dict（言う）→ 言ったことと逆のことを示す＝～と矛盾する",
   relatedWords:[
     {word:"predict",meaning:"予言する",breakdown:"pre（先に）＋ dict（言う）→ 起こる前に言う"},
     {word:"dictionary",meaning:"辞書",breakdown:"dict（言う）＋ ion（名詞）＋ ary（もの）→ 言葉を集めた本"},
     {word:"contrary",meaning:"反対の",breakdown:"contra（逆に）＋ ary（形容詞）→ 逆向きの"},
     {synonym:true,word:"deny",meaning:"否定する",breakdown:"違うと言うこと。contradict は相手の言葉に逆らう"}]},

  {id:1549,word:"consensus",partOfSpeech:"名詞",meaning:"（全員の）意見の一致，合意",
   meanings:["名|（全員の）意見の一致，合意"],
   pronunciation:"/kənˈsensəs/",part:155,
   example:"After a long discussion, the class reached a consensus.",
   exampleJa:"長い話し合いのあと、クラスはようやく意見の一致にたどり着いた。",
   example2:"There is a growing consensus that the rule should change.",
   exampleJa2:"その規則は変えるべきだという合意が広がっている。",
   etymologyProcess:"con（共に）＋ sens（感じる）→ 全員が同じように感じていると…？",
   etymologyConclusion:"con（共に）＋ sens（感じる）→ 全員が同じように感じ考えている状態＝（全員の）意見の一致",
   relatedWords:[
     {word:"consent",meaning:"同意",breakdown:"con（共に）＋ sens（感じる）→ 相手と同じ気持ちだと示して認める"},
     {word:"sense",meaning:"感覚；意味",breakdown:"sens（感じる）→ 体や心で受け取るはたらき"},
     {word:"sensible",meaning:"分別のある",breakdown:"sens（感じる）＋ ible（できる）→ よく感じ取って判断できる"},
     {synonym:true,word:"agreement",meaning:"合意，協定",breakdown:"話がまとまること全般。consensus は全員の一致"}]},

  {id:1550,word:"converse",partOfSpeech:"名詞",meaning:"（the converse で）正反対，逆",
   meanings:["名|（the converse で）正反対，逆","形|逆の","自|（with ～と）会話する（発音は /kənˈvɜːrs/）"],
   pronunciation:"/ˈkɑːnvɜːrs/",part:155,
   example:"Some think money brings happiness, but the converse is often true.",
   exampleJa:"お金が幸せを運ぶと考える人もいるが、実際はその正反対であることも多い。",
   example2:"In math class, we learned that the converse is not always true.",
   exampleJa2:"数学の授業で、ある命題の逆は必ずしも正しくないと習った。",
   etymologyProcess:"con（すっかり）＋ vers（回る）→ すっかり向きを回してひっくり返すと…？",
   etymologyConclusion:"con（すっかり）＋ vers（回る）→ すっかり向きを回してひっくり返したもの＝（the converse で）正反対",
   why:"【なぜ】ラテン語 convertere（すっかり向きを変える）の形 conversus から。向きを逆にすることから名詞の「正反対」になりました。一方、同じ語から出た conversari は「くり返し向き合う・一緒に過ごす」で、こちらが動詞の「会話する」になりました。\n【つながり】convert（転換する）、conversation（会話）、reverse（逆にする）も vers の家族です。",
   relatedWords:[
     {word:"conversation",meaning:"会話",breakdown:"con（共に）＋ vers（回る）＋ ation（名詞）→ 顔を向け合ってやりとりすること"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ 後ろ向きに回す"},
     {word:"convert",meaning:"転換する",breakdown:"con（すっかり）＋ vert（回る）→ すっかり向きを変える"},
     {synonym:true,word:"opposite",meaning:"反対",breakdown:"向かい合う反対。converse は順序や関係を逆にしたもの"}]},
