  {id:851,word:"current",partOfSpeech:"形容詞",meaning:"現在の；最新の",
   meanings:["形|現在の，今の","形|最新の"],
   pronunciation:"/ˈkɜːrənt/",part:86,
   example:"Please write your current address on this application form.",
   exampleJa:"この申込用紙に現在の住所を書いてください。",
   example2:"The current version of the app fixes that annoying bug.",
   exampleJa2:"そのアプリの最新の版は、あのやっかいな不具合を直している。",
   etymologyProcess:"curr（走る）＋ ent（〜している）→ 今まさに流れているのは…？",
   etymologyConclusion:"curr（走る）＋ ent（〜している）→ 今まさに流れて進んでいる最中の＝現在の",
   relatedWords:[
     {word:"occur",meaning:"起こる",breakdown:"oc（〜に向かって）＋ curr（走る）→ 出来事がこちらへ走って来る"},
     {word:"course",meaning:"進路；課程",breakdown:"cours（走る）→ 走って進んでいく一本の道すじ"},
     {word:"currency",meaning:"通貨",breakdown:"curr（走る）＋ cy（名詞）→ 世の中を走り回るお金"},
     {word:"recur",meaning:"再び起こる",breakdown:"re（再び）＋ curr（走る）→ 同じ事がもう一度走って来る"}]},

  {id:852,word:"temporary",partOfSpeech:"形容詞",meaning:"一時的な",
   meanings:["形|一時的な，仮の"],
   pronunciation:"/ˈtempəreri/",part:86,
   example:"They built a temporary stage in the school gym.",
   exampleJa:"彼らは学校の体育館に一時的な舞台を作った。",
   example2:"This road closure is temporary and will end next month.",
   exampleJa2:"この通行止めは一時的なもので、来月には終わる。",
   etymologyProcess:"tempor（時）＋ ary（形容詞）→ ある時の間だけ続くなら…？",
   etymologyConclusion:"tempor（時）＋ ary（形容詞）→ 区切られたある時の間だけ続く＝一時的な",
   relatedWords:[
     {word:"tempo",meaning:"テンポ，速さ",breakdown:"tempor（時）→ 音楽が時を刻んでいく速さ"},
     {word:"contemporary",meaning:"同時代の",breakdown:"com（共に）＋ tempor（時）→ 同じ時を共に生きている"},
     {word:"temporal",meaning:"時間の",breakdown:"tempor（時）＋ al（形容詞）→ 時の流れに関わる"},
     {synonym:true,word:"brief",meaning:"短時間の",breakdown:"時間が短いこと。temporary は「今だけで後で変わる」点を言う"}]},

  {id:853,word:"permanent",partOfSpeech:"形容詞",meaning:"永久的な",
   meanings:["形|永久的な，ずっと変わらない"],
   pronunciation:"/ˈpɜːrmənənt/",part:86,
   example:"The accident left a permanent scar on his left arm.",
   exampleJa:"その事故は彼の左腕に永久的な傷あとを残した。",
   example2:"Is this change permanent, or will it be canceled later?",
   exampleJa2:"この変更は永久的なものですか、それとも後で取り消されますか。",
   etymologyProcess:"per（すっかり）＋ mane（とどまる）→ 最後まで居続けるとしたら…？",
   etymologyConclusion:"per（すっかり）＋ mane（とどまる）＋ ent（〜している）→ 最後までそのまま居続ける＝永久的な",
   relatedWords:[
     {word:"remain",meaning:"とどまる，残る",breakdown:"re（後ろへ）＋ main（とどまる）→ 他が去った後もそこに残る"},
     {word:"remainder",meaning:"残り，余り",breakdown:"re（後ろへ）＋ main（とどまる）＋ der（名詞）→ 後に残っている分"},
     {word:"mansion",meaning:"大邸宅",breakdown:"mane（とどまる）＋ ion（名詞）→ 人が長く住みとどまる建物"},
     {synonym:true,word:"lasting",meaning:"長続きする",breakdown:"長く続くこと。permanent は「ずっと変わらない」と言い切る強さがある"}]},

  {id:854,word:"previous",partOfSpeech:"形容詞",meaning:"前の，一つ前の",
   meanings:["形|前の，一つ前の"],
   pronunciation:"/ˈpriːviəs/",part:86,
   example:"Please read the previous page before you answer this question.",
   exampleJa:"この問いに答える前に、一つ前のページを読んでください。",
   example2:"Her previous job was at a small bookstore near the station.",
   exampleJa2:"彼女の前の仕事は、駅の近くの小さな書店でのものだった。",
   etymologyProcess:"pre（先に）＋ vi（道）→ 同じ道をひと足先に行っていたのは…？",
   etymologyConclusion:"pre（先に）＋ vi（道）＋ ous（形容詞）→ 同じ道をひと足先に通っていた＝前の",
   relatedWords:[
     {word:"via",meaning:"～を経由して",breakdown:"via（道）→ その道を通って向こうへ行く"},
     {word:"obvious",meaning:"明らかな",breakdown:"ob（〜に向かって）＋ vi（道）→ 道の真ん中に立ちふさがって見える"},
     {word:"voyage",meaning:"航海",breakdown:"vi（道）＋ age（名詞）→ 遠い道のりを行くこと"},
     {synonym:true,word:"former",meaning:"前者の",breakdown:"二つのうち先に挙げたほう。previous は時間の上で一つ前を指す"}]},

  {id:855,word:"former",partOfSpeech:"形容詞",meaning:"前者の；かつての",
   meanings:["形|前者の","形|かつての，以前の"],
   pronunciation:"/ˈfɔːrmər/",part:86,
   example:"We visited two museums, and the former was much larger.",
   exampleJa:"私たちは博物館を2つ訪れたが、前者のほうがずっと大きかった。",
   example2:"Our former English teacher came back to visit the school.",
   exampleJa2:"私たちのかつての英語の先生が、学校を訪ねて戻ってきた。",
   etymologyProcess:"fore（前に）＋ er（より）→ 二つのうち前に置かれたほうは…？",
   etymologyConclusion:"fore（前に）＋ er（より）→ 二つ並べたうち、より前に置かれたほう＝前者の",
   relatedWords:[
     {word:"before",meaning:"～の前に",breakdown:"fore（前に）→ 時間や場所の上で前に来るところ"},
     {word:"forecast",meaning:"予報",breakdown:"fore（前に）＋ cast（投げる）→ 先へ考えを投げて言い当てる"},
     {word:"forehead",meaning:"額（ひたい）",breakdown:"fore（前に）＋ head（頭）→ 頭のいちばん前の面"},
     {word:"foremost",meaning:"最も重要な",breakdown:"fore（前に）＋ most（最も）→ いちばん前に立っている"}]},

  {id:856,word:"contemporary",partOfSpeech:"形容詞",meaning:"同時代の；現代の",
   meanings:["形|同時代の","形|現代の"],
   pronunciation:"/kənˈtempəreri/",part:86,
   example:"Shakespeare and Cervantes were contemporary writers in different countries.",
   exampleJa:"シェイクスピアとセルバンテスは、別の国の同時代の作家だった。",
   example2:"Our club performs contemporary dance at the school festival every year.",
   exampleJa2:"私たちの部活は毎年、文化祭で現代のダンスを踊る。",
   etymologyProcess:"com（共に）＋ tempor（時）→ 同じ時を分け合っているなら…？",
   etymologyConclusion:"com（共に）＋ tempor（時）＋ ary（形容詞）→ 同じ時代を共に生きている＝同時代の",
   relatedWords:[
     {word:"temporary",meaning:"一時的な",breakdown:"tempor（時）＋ ary（形容詞）→ 区切られた時の間だけ続く"},
     {word:"tempo",meaning:"テンポ，速さ",breakdown:"tempor（時）→ 音楽が時を刻んでいく速さ"},
     {synonym:true,word:"current",meaning:"現在の",breakdown:"今まさに進行中の。contemporary は「同じ時代を生きる」ことを言う"},
     {synonym:true,word:"modern",meaning:"現代の",breakdown:"今の時代の。contemporary は「同じ時を生きる」点に重さがある"}]},

  {id:857,word:"lately",partOfSpeech:"副詞",meaning:"（現在完了とともに）最近，このごろ",
   meanings:["副|（現在完了とともに）最近，このごろ"],
   pronunciation:"/ˈleɪtli/",part:86,
   example:"I have been getting up early lately to study English.",
   exampleJa:"最近、英語を勉強するために早起きしている。",
   example2:"Lately the weather has been much colder than usual here.",
   exampleJa2:"最近、ここの天気はいつもよりずっと寒い。",
   etymologyProcess:"late（遅い）＋ ly（副詞）→ 時の流れの遅い側を指すと…？",
   etymologyConclusion:"late（遅い）＋ ly（副詞）→ 時の流れの遅い側、つまりつい先ごろ＝最近",
   why:"【なぜ】late はもともと「遅い」。時間を一本の帯と見ると、「遅い側」は今にいちばん近いところです。そこから「ついこのあいだ」＝最近になりました。\n【つながり】latest（いちばん遅い＝最新の）、latter（後ろのほう＝後者）も同じ見方です。なお late 単独の副詞は「遅れて」で、lately とは意味が別なので注意。",
   relatedWords:[
     {word:"late",meaning:"遅い",breakdown:"late（遅い）→ 決めた時刻より後ろにずれている"},
     {word:"later",meaning:"後で",breakdown:"late（遅い）＋ er（より）→ より遅い時点で"},
     {word:"latest",meaning:"最新の",breakdown:"late（遅い）＋ est（最も）→ いちばん遅い、つまりいちばん新しい"},
     {word:"latter",meaning:"後者の",breakdown:"late（遅い）＋ er（より）→ 二つのうち後ろに置かれたほう"}]},

  {id:858,word:"immediately",partOfSpeech:"副詞",meaning:"すぐに，ただちに",
   meanings:["副|すぐに，ただちに"],
   pronunciation:"/ɪˈmiːdiətli/",part:86,
   example:"Call an ambulance immediately if someone falls down over there.",
   exampleJa:"向こうで誰かが倒れたら、すぐに救急車を呼びなさい。",
   example2:"She answered my message immediately after the class ended.",
   exampleJa2:"彼女は授業が終わった後、すぐに私のメッセージに返事をした。",
   etymologyProcess:"im（否定）＋ medi（中間）→ 間に何も挟まないとしたら…？",
   etymologyConclusion:"im（否定）＋ medi（中間）＋ ly（副詞）→ 間に何も挟まず、じかに次が来る＝すぐに",
   relatedWords:[
     {word:"medium",meaning:"中くらいの；媒体",breakdown:"medi（中間）→ 両端のちょうど真ん中にあるもの"},
     {word:"middle",meaning:"真ん中",breakdown:"middle（中間）→ 両端から等しく離れたところ"},
     {word:"immediate",meaning:"即座の",breakdown:"im（否定）＋ medi（中間）→ 間に何も入り込まない"},
     {synonym:true,word:"instantly",meaning:"即座に",breakdown:"一瞬のうちに。immediately は「間に何も挟まず次に」という含み"}]},

  {id:859,word:"deadline",partOfSpeech:"名詞",meaning:"締め切り",
   meanings:["名|締め切り，期限"],
   pronunciation:"/ˈdedlaɪn/",part:86,
   example:"The deadline for this report is next Friday at noon.",
   exampleJa:"このレポートの締め切りは来週の金曜の正午だ。",
   example2:"We missed the deadline because our printer suddenly broke down.",
   exampleJa2:"プリンターが急に壊れたので、私たちは締め切りに間に合わなかった。",
   etymologyProcess:"dead（動かない）＋ line（線）→ 越えたらもう動けない線は…？",
   etymologyConclusion:"dead（動かない）＋ line（線）→ 越えたらもう動けなくなる境目の線＝締め切り",
   why:"【なぜ】19世紀アメリカの捕虜収容所で、地面に引かれた線を越えた者は撃たれました。その「越えたら終わりの線」が dead line です。のちに新聞社が、これを過ぎたら原稿を載せられない時刻の呼び名に使いました。\n【つながり】日本語の「デッドライン」も同じ語です。line は outline（外をなぞった線＝輪郭）にも出てきます。",
   relatedWords:[
     {word:"dead",meaning:"死んでいる",breakdown:"dead（動かない）→ 息も動きもすっかり止まってしまっている"},
     {word:"deadly",meaning:"命にかかわる",breakdown:"dead（動かない）＋ ly（〜のような）→ 命を止めてしまうような"},
     {word:"line",meaning:"線；列",breakdown:"line（線）→ まっすぐに引かれた一本のすじ"},
     {word:"outline",meaning:"輪郭；要点",breakdown:"out（外へ）＋ line（線）→ 外側をぐるりとなぞった線"}]},

  {id:860,word:"decade",partOfSpeech:"名詞",meaning:"10年間",
   meanings:["名|10年間"],
   pronunciation:"/ˈdekeɪd/",part:86,
   example:"My grandparents have lived in this town for a decade.",
   exampleJa:"祖父母はこの町に10年間住んでいる。",
   example2:"Smartphones changed our daily life in a single decade.",
   exampleJa2:"スマートフォンはたった10年間で私たちの日常を変えた。",
   etymologyProcess:"dec（10）→ 年を10ずつまとめて数えると…？",
   etymologyConclusion:"dec（10）→ 年を10ずつのひとまとまりにして数えた区切り＝10年間",
   relatedWords:[
     {word:"December",meaning:"12月",breakdown:"dec（10）→ 昔の暦で10番目の月だった名残"},
     {word:"decimal",meaning:"小数の",breakdown:"dec（10）→ 10ごとに位が上がる数え方"},
     {word:"dime",meaning:"10セント硬貨",breakdown:"dec（10）→ 1ドルの10分の1にあたる硬貨"},
     {synonym:true,word:"century",meaning:"世紀，100年",breakdown:"100年のまとまり。decade はその10分の1の長さ"}]},

  {id:861,word:"supply",partOfSpeech:"他動詞",meaning:"補って与える，供給する",
   meanings:["他|補って与える，供給する","名|供給"],
   pronunciation:"/səˈplaɪ/",part:87,
   example:"The city will supply clean water to every home here.",
   exampleJa:"市はここのすべての家庭にきれいな水を供給する。",
   example2:"New notebooks were supplied to all the first-year students.",
   exampleJa2:"新しいノートが1年生全員に供給された。",
   etymologyProcess:"sup（下から）＋ ple（満たす）→ 足りないところを下から満たすと…？",
   etymologyConclusion:"sup（下から）＋ ple（満たす）→ 足りないところを下から補って満たす＝供給する",
   relatedWords:[
     {word:"complete",meaning:"完全な",breakdown:"com（すっかり）＋ ple（満たす）→ すみずみまで満たされている"},
     {word:"plenty",meaning:"たくさん",breakdown:"ple（満たす）＋ ty（名詞）→ 満ち足りているほどの量"},
     {word:"supplement",meaning:"補うもの，サプリ",breakdown:"sup（下から）＋ ple（満たす）→ 足りない分を下から補うもの"},
     {word:"accomplish",meaning:"成し遂げる",breakdown:"ac（〜へ）＋ com（すっかり）＋ ple（満たす）→ 最後まで満たしきる"}]},

  {id:862,word:"replace",partOfSpeech:"他動詞",meaning:"取って代わる；取り替える",
   meanings:["他|取って代わる","他|取り替える"],
   pronunciation:"/rɪˈpleɪs/",part:87,
   example:"Robots will replace some jobs in the near future.",
   exampleJa:"ロボットは近い将来、いくつかの仕事に取って代わるだろう。",
   example2:"I replaced the broken light bulb in my own room.",
   exampleJa2:"私は自分の部屋の切れた電球を取り替えた。",
   etymologyProcess:"re（戻す）＋ place（広場）→ 元の場所へ別のものを置くと…？",
   etymologyConclusion:"re（戻す）＋ place（広場）→ 元の場所へ別のものを戻して置く＝取って代わる",
   relatedWords:[
     {word:"place",meaning:"場所",breakdown:"place（広場）→ 人が集まる、広く開けたところ"},
     {word:"plaza",meaning:"広場",breakdown:"place（広場）→ 町の真ん中の開けた広場"},
     {word:"placement",meaning:"配置",breakdown:"place（広場）＋ ment（名詞）→ 物をどこに置くかの決め方"},
     {synonym:true,word:"substitute",meaning:"代わりに用いる",breakdown:"代役を立てること。replace は元のものを退けて場所を奪う"}]},

  {id:863,word:"exchange",partOfSpeech:"他動詞",meaning:"交換する",
   meanings:["他|交換する","名|交換"],
   pronunciation:"/ɪksˈtʃeɪndʒ/",part:87,
   example:"We exchanged email addresses after the summer camp ended.",
   exampleJa:"合宿が終わった後、私たちはメールアドレスを交換した。",
   example2:"You can exchange this shirt for a larger size.",
   exampleJa2:"このシャツはもっと大きいサイズと交換できます。",
   etymologyProcess:"ex（外へ）＋ chang（取りかえる）→ 互いに外へ出して渡し合うと…？",
   etymologyConclusion:"ex（外へ）＋ chang（取りかえる）→ 自分のものを外へ出して別のものと取りかえる＝交換する",
   relatedWords:[
     {word:"change",meaning:"変える；おつり",breakdown:"chang（取りかえる）→ 今のものを別のものに取りかえる"},
     {word:"changeable",meaning:"変わりやすい",breakdown:"chang（取りかえる）＋ able（できる）→ すぐに取りかわりうる"},
     {word:"interchange",meaning:"交換；立体交差",breakdown:"inter（間の）＋ chang（取りかえる）→ 互いの間で取りかえ合う"},
     {synonym:true,word:"trade",meaning:"取引する",breakdown:"品物とお金をやりとりする。exchange は物と物を直接取りかえる"}]},

  {id:864,word:"substitute",partOfSpeech:"他動詞",meaning:"代わりに用いる",
   meanings:["他|代わりに用いる","名|代わりの人，代用品"],
   pronunciation:"/ˈsʌbstɪtuːt/",part:87,
   example:"You can substitute honey for sugar in this recipe.",
   exampleJa:"このレシピでは砂糖の代わりに蜂蜜を用いることができる。",
   example2:"Our coach substituted a first-year student for the injured captain.",
   exampleJa2:"監督はけがをした主将の代わりに1年生を用いた。",
   etymologyProcess:"sub（下で）＋ stitut（立てる）→ 元のものの下に別のを立てると…？",
   etymologyConclusion:"sub（下で）＋ stitut（立てる）→ 元のものの下に別のものを立てて代わりにする＝代わりに用いる",
   relatedWords:[
     {word:"statue",meaning:"像",breakdown:"stitut（立てる）＋ ue（もの）→ 人の姿を立てたまま固めたもの"},
     {word:"institute",meaning:"設立する；協会",breakdown:"in（中に）＋ stitut（立てる）→ 中に柱を立てて組織を作る"},
     {word:"constitute",meaning:"構成する",breakdown:"con（共に）＋ stitut（立てる）→ 部品を共に立てて全体を作る"},
     {synonym:true,word:"replace",meaning:"取って代わる",breakdown:"元のものを退けて場所を奪う。substitute は代役を立てる"}]},

  {id:865,word:"submit",partOfSpeech:"他動詞",meaning:"提出する",
   meanings:["他|提出する","自|（to ～）（～に）従う"],
   pronunciation:"/səbˈmɪt/",part:87,
   example:"You must submit your report before Friday afternoon.",
   exampleJa:"金曜の午後までにレポートを提出しなければならない。",
   example2:"She submitted her application to the university last week.",
   exampleJa2:"彼女は先週、大学に願書を提出した。",
   etymologyProcess:"sub（下で）＋ mit（送る）→ 相手の下へ差し出すように送ると…？",
   etymologyConclusion:"sub（下で）＋ mit（送る）→ 目上の人の下へ差し出すように送る＝提出する",
   relatedWords:[
     {word:"admit",meaning:"認める",breakdown:"ad（〜へ）＋ mit（送る）→ 中へ送り入れてやる"},
     {word:"permit",meaning:"許可する",breakdown:"per（通して）＋ mit（送る）→ 通り抜けて行かせてやる"},
     {word:"transmit",meaning:"送り伝える",breakdown:"trans（越えて）＋ mit（送る）→ 境を越えて向こうへ送る"},
     {word:"commit",meaning:"ゆだねる；（罪を）犯す",breakdown:"com（共に）＋ mit（送る）→ 相手のもとへ身をすっかり送り込む"}]},

  {id:866,word:"alternative",partOfSpeech:"名詞",meaning:"代わりのもの，代案",
   meanings:["名|代わりのもの，代案","形|代わりの"],
   pronunciation:"/ɔːlˈtɜːrnətɪv/",part:87,
   example:"Is there an alternative to this very expensive plan?",
   exampleJa:"このとても高い計画の代わりのものはありますか。",
   example2:"Cycling to school is a healthy alternative to the bus.",
   exampleJa2:"自転車で学校へ行くのは、バスの代わりになるもので、健康的だ。",
   etymologyProcess:"alter（別の）→ 今のとは別に、もう一方に道があるなら…？",
   etymologyConclusion:"alter（別の）→ 今のとは別に、もう一方に用意された道＝代わりのもの",
   relatedWords:[
     {word:"alter",meaning:"変える",breakdown:"alter（別の）→ 今のものを別のものにしてしまう"},
     {word:"alien",meaning:"異星人；外国の",breakdown:"ali（別の）→ alter と同じ「別の」の仲間。よそから来たもの"},
     {word:"alternate",meaning:"交互にする",breakdown:"alter（別の）＋ ate（動詞）→ 別のほうと入れかわり続ける"},
     {synonym:true,word:"option",meaning:"選択肢",breakdown:"選んで取れるもの。alternative は「今のとは別の道」を指す"}]},

  {id:867,word:"deliver",partOfSpeech:"他動詞",meaning:"配達する，届ける",
   meanings:["他|配達する，届ける","他|（演説など）を述べる"],
   pronunciation:"/dɪˈlɪvər/",part:87,
   example:"They deliver fresh bread to our school every single morning.",
   exampleJa:"彼らは毎朝、私たちの学校に焼きたてのパンを配達する。",
   example2:"The package was delivered while I was at club practice.",
   exampleJa2:"その荷物は、私が部活の練習中に配達された。",
   etymologyProcess:"de（離して）＋ liber（自由な）→ 手元から解き放って渡すと…？",
   etymologyConclusion:"de（離して）＋ liber（自由な）→ 手元から解き放って相手の手に渡す＝配達する",
   relatedWords:[
     {word:"liberty",meaning:"自由",breakdown:"liber（自由な）＋ ty（名詞）→ 何にも縛られていない状態"},
     {word:"liberal",meaning:"自由な，寛大な",breakdown:"liber（自由な）＋ al（形容詞）→ 縛りをゆるめて認める"},
     {word:"delivery",meaning:"配達",breakdown:"de（離して）＋ liber（自由な）＋ ry（もの）→ 手元から放して届けること"},
     {synonym:true,word:"distribute",meaning:"分配する",breakdown:"割り当てて配ること。deliver は届け先の手に渡すことを言う"}]},

  {id:868,word:"enclose",partOfSpeech:"他動詞",meaning:"同封する；囲む",
   meanings:["他|同封する","他|囲む"],
   pronunciation:"/ɪnˈkloʊz/",part:87,
   example:"Please enclose a recent photo with your application form.",
   exampleJa:"申込用紙に最近の写真を同封してください。",
   example2:"A high green fence encloses the whole school playground.",
   exampleJa2:"高い緑のフェンスが学校の運動場全体を囲んでいる。",
   etymologyProcess:"en（中に）＋ clos（閉じる）→ 中に入れて閉じてしまうと…？",
   etymologyConclusion:"en（中に）＋ clos（閉じる）→ 中に入れて閉じ、外に出さない＝同封する",
   relatedWords:[
     {word:"close",meaning:"閉じる",breakdown:"clos（閉じる）→ 開いていたものをぴたりと閉じる"},
     {word:"include",meaning:"含む",breakdown:"in（中へ）＋ clude（閉じる）→ 中に閉じ込めて仲間に入れる"},
     {word:"closet",meaning:"物入れ，クローゼット",breakdown:"clos（閉じる）＋ et（小さい）→ 閉じてしまっておく小部屋"},
     {word:"disclose",meaning:"明らかにする",breakdown:"dis（否定）＋ clos（閉じる）→ 閉じていたものを開いて見せる"}]},

  {id:869,word:"envelope",partOfSpeech:"名詞",meaning:"封筒",
   meanings:["名|封筒"],
   pronunciation:"/ˈenvəloʊp/",part:87,
   example:"She wrote the address on the white envelope very carefully.",
   exampleJa:"彼女は白い封筒に住所をとてもていねいに書いた。",
   example2:"Put the letter into this envelope and seal it well.",
   exampleJa2:"手紙をこの封筒に入れて、しっかり封をしなさい。",
   etymologyProcess:"en（中に）＋ velop（包む）→ 手紙を中に入れて包むものは…？",
   etymologyConclusion:"en（中に）＋ velop（包む）→ 手紙を中に入れてすっぽり包む紙の袋＝封筒",
   relatedWords:[
     {word:"develop",meaning:"発達させる",breakdown:"de（逆に）＋ velop（包む）→ 包みを開いて中身を伸ばす"},
     {word:"envelop",meaning:"包み込む",breakdown:"en（中に）＋ velop（包む）→ すっぽりと包んでしまう"},
     {word:"development",meaning:"発達",breakdown:"de（逆に）＋ velop（包む）＋ ment（名詞）→ 包みが開いて広がること"},
     {synonym:true,word:"wrap",meaning:"包む",breakdown:"紙や布でくるむこと。envelope は手紙を入れる紙の袋そのもの"}]},

  {id:870,word:"trick",partOfSpeech:"名詞",meaning:"いたずら；手品",
   meanings:["名|いたずら，たくらみ","名|手品，芸"],
   pronunciation:"/trɪk/",part:87,
   example:"The children played a trick on their homeroom teacher today.",
   exampleJa:"子どもたちは今日、担任の先生にいたずらをした。",
   example2:"He showed us an amazing card trick at the party.",
   exampleJa2:"彼はパーティーで見事なトランプの手品を見せてくれた。",
   etymologyProcess:"trick（だます）→ 相手の目をあざむく小さな細工は…？",
   etymologyConclusion:"trick（だます）→ 相手の目をあざむいて仕掛ける小さな細工＝いたずら",
   hook:"ハロウィンの trick or treat と同じ語。「だます仕掛け」が芯にある。",
   relatedWords:[
     {synonym:true,word:"trap",meaning:"わな",breakdown:"かかると抜け出せない仕掛け。trick は相手の思い込みを利用する"},
     {synonym:true,word:"cheat",meaning:"ごまかす",breakdown:"ずるをして得をする。trick は必ずしも悪意があるとは限らない"},
     {synonym:true,word:"prank",meaning:"悪ふざけ",breakdown:"笑わせるための軽いいたずら。trick はだます仕掛け全般を指す"},
     {word:"tricky",meaning:"扱いにくい，ずるい",breakdown:"trick（だます）＋ y（形容詞）→ 一筋縄ではいかない"}]},

  {id:871,word:"load",partOfSpeech:"名詞",meaning:"積み荷，荷物",
   meanings:["名|積み荷，荷物","他|積み込む"],
   pronunciation:"/loʊd/",part:88,
   example:"The truck carried a heavy load of building materials.",
   exampleJa:"そのトラックは建築材料の重い積み荷を運んでいた。",
   example2:"Please help me load these heavy boxes into the car.",
   exampleJa2:"これらの重い箱を車に積み込むのを手伝ってください。",
   etymologyProcess:"load（積んで運ぶ）→ 車や船に積み込む重いものは…？",
   etymologyConclusion:"load（積んで運ぶ）→ 車や船に積んで運ぶ、ひとまとまりの重いもの＝積み荷",
   hook:"日本語の「ロード（積む・読み込む）」がそのまま使える。中身を入れる話。",
   relatedWords:[
     {word:"unload",meaning:"荷を下ろす",breakdown:"un（取り去る）＋ load（積んで運ぶ）→ 積んだ荷を下ろす"},
     {word:"overload",meaning:"積みすぎる",breakdown:"over（越えて）＋ load（積んで運ぶ）→ 限度を越えて積む"},
     {word:"loading",meaning:"読み込み中",breakdown:"load（積んで運ぶ）＋ ing（〜している）→ データを積み込んでいる最中"},
     {synonym:true,word:"burden",meaning:"重荷",breakdown:"背負わされる重さ。load は車や船に積まれた荷そのもの"}]},

  {id:872,word:"content",partOfSpeech:"名詞",meaning:"中身，内容",
   meanings:["名|中身，内容","名|（contents で）目次"],
   pronunciation:"/ˈkɑːntent/",part:88,
   example:"The contents of this old wooden box are very fragile.",
   exampleJa:"この古い木箱の中身はとても壊れやすい。",
   example2:"She checked the content of the email before sending it.",
   exampleJa2:"彼女は送信する前にメールの内容を確認した。",
   etymologyProcess:"con（すっかり）＋ ten（保つ）→ 入れ物の中に保たれているものは…？",
   etymologyConclusion:"con（すっかり）＋ ten（保つ）→ 入れ物の中にすっかり保たれているもの＝中身",
   relatedWords:[
     {word:"contain",meaning:"含む",breakdown:"con（すっかり）＋ tain（保つ）→ 中にすっかり保っている"},
     {word:"container",meaning:"容器",breakdown:"con（すっかり）＋ tain（保つ）＋ er（もの）→ 中身を保っておく入れ物"},
     {word:"continue",meaning:"続ける",breakdown:"con（共に）＋ tin（保つ）→ 切らさずに保ったままつなげる"},
     {word:"obtain",meaning:"手に入れる",breakdown:"ob（〜に向かって）＋ tain（保つ）→ 手を伸ばして自分の手に保つ"}]},

  {id:873,word:"household",partOfSpeech:"名詞",meaning:"所帯，一家",
   meanings:["名|所帯，一家","形|家庭の"],
   pronunciation:"/ˈhaʊshoʊld/",part:88,
   example:"Every household in this town received a free emergency kit.",
   exampleJa:"この町のすべての所帯が無料の防災袋を受け取った。",
   example2:"In my family the household chores are shared equally.",
   exampleJa2:"うちでは家庭の雑用は平等に分けられている。",
   etymologyProcess:"house（家）＋ hold（持ち続ける）→ 一つの家をまとめて守るのは…？",
   etymologyConclusion:"house（家）＋ hold（持ち続ける）→ 一つの家をまとめて切り盛りする人の集まり＝所帯",
   relatedWords:[
     {word:"house",meaning:"家",breakdown:"house（家）→ 人が身を寄せて住む建物"},
     {word:"hold",meaning:"持つ，保つ",breakdown:"hold（持ち続ける）→ 手を離さずそのままつかんでいる"},
     {word:"housework",meaning:"家事",breakdown:"house（家）＋ work（仕事）→ 家の中でする仕事"},
     {word:"housing",meaning:"住宅",breakdown:"house（家）＋ ing（名詞）→ 人が住むための建物"}]},

  {id:874,word:"good",partOfSpeech:"名詞",meaning:"（goods で）商品，品物",
   meanings:["名|（goods で）商品，品物","形|よい"],
   pronunciation:"/ɡʊd/",part:88,
   example:"The store moved its goods to a new warehouse.",
   exampleJa:"その店は商品を新しい倉庫へ移した。",
   example2:"Leather goods are popular souvenirs in this small country.",
   exampleJa2:"革の商品は、この小さな国で人気の土産だ。",
   etymologyProcess:"good（ふさわしい）→ 役に立つと認められた品物は…？",
   etymologyConclusion:"good（ふさわしい）→ 人の役に立つとみんなが認めた品物＝商品",
   why:"【なぜ】good はもともと「ぴったり合う・ふさわしい」。そこから「よい」になり、さらに「人にとって good なもの」＝役に立つ品物、という使い方が生まれました。品物は数えられるので、この意味では必ず複数形 goods になります。\n【つながり】日本語の「グッズ」も同じ語です。goodness（善良さ）や goodwill（好意）は「よい」のほうから育った語。",
   relatedWords:[
     {word:"goodness",meaning:"善良さ",breakdown:"good（ふさわしい）＋ ness（名詞）→ 人として望ましい性質"},
     {word:"goodwill",meaning:"好意，善意",breakdown:"good（ふさわしい）＋ will（望む）→ 相手によかれと望む気持ち"},
     {synonym:true,word:"product",meaning:"製品",breakdown:"作り出されたもの。goods は店で売られる品物そのものを指す"},
     {synonym:true,word:"merchandise",meaning:"商品",breakdown:"売り買いされる品物ぜんたい。goods は数えられる品々を指す"}]},

  {id:875,word:"luxury",partOfSpeech:"名詞",meaning:"ぜいたく；高級品",
   meanings:["名|ぜいたく","名|高級品","形|高級な"],
   pronunciation:"/ˈlʌkʃəri/",part:88,
   example:"For my family a trip abroad is a luxury.",
   exampleJa:"私の家族にとって、海外旅行はぜいたくだ。",
   example2:"This hotel offers luxury rooms with a wide sea view.",
   exampleJa2:"このホテルは海が広く見える高級な部屋を用意している。",
   etymologyProcess:"lux（あり余る）＋ ry（もの）→ 必要をはるかに越えたものは…？",
   etymologyConclusion:"lux（あり余る）＋ ry（もの）→ 必要をはるかに越えてあり余る豊かさ＝ぜいたく",
   relatedWords:[
     {word:"luxurious",meaning:"ぜいたくな",breakdown:"lux（あり余る）＋ ous（形容詞）→ あり余るほど豊かな"},
     {word:"deluxe",meaning:"豪華な",breakdown:"lux（あり余る）→ 仏語 de luxe「ぜいたくの」から。豪華さをまとった"},
     {synonym:true,word:"comfort",meaning:"快適さ",breakdown:"体や心の心地よさ。luxury は必要を越えた豊かさを指す"},
     {synonym:true,word:"treasure",meaning:"宝物",breakdown:"しまっておく値打ちのあるもの。luxury は使って楽しむ豊かさ"}]},

  {id:876,word:"credit",partOfSpeech:"名詞",meaning:"クレジット，後払い；信用",
   meanings:["名|クレジット，後払い","名|信用","名|（credits で）制作者名の表示"],
   pronunciation:"/ˈkredɪt/",part:88,
   example:"Many high school students do not have a credit card.",
   exampleJa:"多くの高校生はクレジットカードを持っていない。",
   example2:"The bank gave the small company more credit this year.",
   exampleJa2:"銀行は今年、その小さな会社にもっと信用を与えた。",
   etymologyProcess:"cred（信じる）＋ it（〜された）→ 後で払うと信じてもらえたら…？",
   etymologyConclusion:"cred（信じる）＋ it（〜された）→ 後で必ず払うと信じてもらえること＝クレジット",
   relatedWords:[
     {word:"incredible",meaning:"信じられない",breakdown:"in（否定）＋ cred（信じる）→ とても信じることができない"},
     {word:"credible",meaning:"信じられる",breakdown:"cred（信じる）＋ ible（できる）→ 信じることができる"},
     {word:"creed",meaning:"信条",breakdown:"cred（信じる）→ 信じて守ると決めた教え"},
     {synonym:true,word:"trust",meaning:"信頼",breakdown:"相手を信じて任せる気持ち。credit は後払いを許す社会的な信用"}]},

  {id:877,word:"questionnaire",partOfSpeech:"名詞",meaning:"アンケート",
   meanings:["名|アンケート，質問用紙"],
   pronunciation:"/ˌkwestʃəˈner/",part:88,
   example:"Please fill in this questionnaire before you leave today.",
   exampleJa:"今日帰る前に、このアンケートに記入してください。",
   example2:"The questionnaire asked about our reading habits at home.",
   exampleJa2:"そのアンケートは、家での読書の習慣について尋ねていた。",
   etymologyProcess:"quest（求める）＋ ion（名詞）→ 問いを並べて配る紙は…？",
   etymologyConclusion:"quest（求める）＋ ion（名詞）→ 答えを求める問いを並べて配る紙＝アンケート",
   relatedWords:[
     {word:"question",meaning:"質問",breakdown:"quest（求める）＋ ion（名詞）→ 答えを求めること"},
     {word:"request",meaning:"依頼する",breakdown:"re（何度も）＋ quest（求める）→ くり返し求める"},
     {word:"require",meaning:"必要とする",breakdown:"re（強く）＋ quire（求める）→ 強く求めて欠かせないとする"},
     {word:"inquiry",meaning:"調査，問い合わせ",breakdown:"in（中へ）＋ quire（求める）→ 中へ分け入って答えを求める"}]},

  {id:878,word:"reservation",partOfSpeech:"名詞",meaning:"予約",
   meanings:["名|予約","名|（言いにくい）ためらい，留保"],
   pronunciation:"/ˌrezərˈveɪʃn/",part:88,
   example:"I made a reservation for four people at seven.",
   exampleJa:"私は7時に4人の予約をした。",
   example2:"Your reservation was canceled because you arrived too late.",
   exampleJa2:"到着が遅すぎたので、あなたの予約は取り消された。",
   etymologyProcess:"re（後ろへ）＋ serv（守る）→ 自分のために取り置いてもらうと…？",
   etymologyConclusion:"re（後ろへ）＋ serv（守る）＋ ation（名詞）→ 自分のために取り置いて守ってもらうこと＝予約",
   relatedWords:[
     {word:"reserve",meaning:"取っておく",breakdown:"re（後ろへ）＋ serv（守る）→ 後のために取り置いて守る"},
     {word:"preserve",meaning:"保存する",breakdown:"pre（先に）＋ serv（守る）→ 先回りして傷まないように守る"},
     {word:"observe",meaning:"観察する",breakdown:"ob（〜に向かって）＋ serv（守る）→ 目を離さずじっと見守る"},
     {word:"conserve",meaning:"保存する",breakdown:"con（すっかり）＋ serv（守る）→ 減らさないようにすっかり守る"}]},

  {id:879,word:"fuss",partOfSpeech:"名詞",meaning:"大騒ぎ",
   meanings:["名|大騒ぎ，から騒ぎ"],
   pronunciation:"/fʌs/",part:88,
   example:"Do not make a fuss about such a small mistake.",
   exampleJa:"そんな小さな間違いで大騒ぎしないでください。",
   example2:"There was a big fuss over the new school rule.",
   exampleJa2:"新しい校則をめぐって大騒ぎがあった。",
   etymologyProcess:"fuss（騒ぎ立てる）→ 小さなことでざわめき立てると…？",
   etymologyConclusion:"fuss（騒ぎ立てる）→ 小さなことでざわざわと騒ぎ立てること＝大騒ぎ",
   hook:"語源ははっきりしないが、息を荒げる「フーッ」という音と結びつけると覚えやすい。",
   relatedWords:[
     {synonym:true,word:"noise",meaning:"騒音",breakdown:"耳ざわりな音そのもの。fuss は人が騒ぎ立てる様子を指す"},
     {synonym:true,word:"panic",meaning:"うろたえ",breakdown:"突然の恐れで取り乱すこと。fuss はささいな事での騒ぎ"},
     {synonym:true,word:"bother",meaning:"わずらわせる",breakdown:"手間をかけさせる。fuss は必要以上に気をもんで騒ぐこと"},
     {synonym:true,word:"quarrel",meaning:"口げんか",breakdown:"言い争いそのもの。fuss はそれを含む騒ぎ全体を指す"}]},

  {id:880,word:"reward",partOfSpeech:"名詞",meaning:"報酬，ほうび",
   meanings:["名|報酬，ほうび","他|報いる"],
   pronunciation:"/rɪˈwɔːrd/",part:88,
   example:"The police offered a reward for any useful information.",
   exampleJa:"警察は役に立つ情報に報酬を出した。",
   example2:"Hard daily practice will reward you with much better results.",
   exampleJa2:"毎日の厳しい練習は、ずっとよい結果であなたに報いてくれる。",
   etymologyProcess:"re（戻す）＋ ward（見張る）→ よい働きを見て返すものは…？",
   etymologyConclusion:"re（戻す）＋ ward（見張る）→ よい働きをしっかり見て、その分を返すもの＝報酬",
   relatedWords:[
     {word:"award",meaning:"賞；授与する",breakdown:"ex（外へ）＋ ward（見張る）→ よく見て判断し、外へ言い渡す"},
     {word:"regard",meaning:"みなす；敬意",breakdown:"re（じっと）＋ gard（見張る）→ じっと見つめて心にとめる"},
     {word:"guard",meaning:"守る",breakdown:"gard（見張る）→ 目を配って危険から守る"},
     {word:"aware",meaning:"気づいている",breakdown:"ware（見張る）→ 用心して見ていて、それに気づいている"}]},

  {id:881,word:"farewell",partOfSpeech:"名詞",meaning:"別れ，別れのあいさつ",
   meanings:["名|別れ，別れのあいさつ"],
   pronunciation:"/ˌferˈwel/",part:89,
   example:"We held a farewell party for our English teacher yesterday.",
   exampleJa:"私たちは昨日、英語の先生のために別れの会を開いた。",
   example2:"His farewell to the team was short but very moving.",
   exampleJa2:"チームへの彼の別れのあいさつは短かったが、とても感動的だった。",
   etymologyProcess:"fare（旅をする）＋ well（うまく）→ 旅立つ人にかける言葉は…？",
   etymologyConclusion:"fare（旅をする）＋ well（うまく）→ 旅立つ人に「無事で行け」と送る言葉＝別れのあいさつ",
   relatedWords:[
     {word:"fare",meaning:"運賃",breakdown:"fare（旅をする）→ 旅をするために払うお金"},
     {word:"welcome",meaning:"歓迎する",breakdown:"wil（望む）＋ come（来る）→ 来てほしかった人が来た"},
     {word:"welfare",meaning:"福祉",breakdown:"well（うまく）＋ fare（やっていく）→ うまくやっていけている状態"},
     {synonym:true,word:"goodbye",meaning:"さようなら",breakdown:"ふだんの別れの挨拶。farewell は改まった、長い別れに使う"}]},

  {id:882,word:"reception",partOfSpeech:"名詞",meaning:"もてなし，迎え方；受付",
   meanings:["名|もてなし，迎え方","名|受付","名|（電波の）受信"],
   pronunciation:"/rɪˈsepʃn/",part:89,
   example:"The hotel gave us a warm reception on our arrival.",
   exampleJa:"そのホテルは到着したとき、温かいもてなしをしてくれた。",
   example2:"Please leave your key at the reception before going out.",
   exampleJa2:"出かける前に受付に鍵を預けてください。",
   etymologyProcess:"re（戻す）＋ cept（取る）→ 訪れた人を受け取って迎えると…？",
   etymologyConclusion:"re（戻す）＋ cept（取る）＋ ion（名詞）→ 訪れた人を受け取って迎え入れること＝もてなし",
   relatedWords:[
     {word:"accept",meaning:"受け入れる",breakdown:"ac（〜へ）＋ cept（取る）→ 差し出されたほうへ手を出して取る"},
     {word:"except",meaning:"～を除いて",breakdown:"ex（外へ）＋ cept（取る）→ 外へ取り出して別あつかいにする"},
     {word:"concept",meaning:"概念",breakdown:"con（すっかり）＋ cept（取る）→ 頭の中にすっかり取り込んだ像"},
     {synonym:true,word:"welcome",meaning:"歓迎",breakdown:"よく来たと迎えること。reception は迎える場や催しも指す"}]},

  {id:883,word:"portion",partOfSpeech:"名詞",meaning:"1盛り；（全体の）部分",
   meanings:["名|1盛り，1人分","名|（全体の）部分"],
   pronunciation:"/ˈpɔːrʃn/",part:89,
   example:"This restaurant serves a very large portion of pasta.",
   exampleJa:"このレストランはとても大きな1盛りのパスタを出す。",
   example2:"A large portion of our class joined the city marathon.",
   exampleJa2:"私たちのクラスのかなりの部分が市のマラソンに参加した。",
   etymologyProcess:"porti（分ける）＋ ion（名詞）→ 全体から切り分けた1人分は…？",
   etymologyConclusion:"porti（分ける）＋ ion（名詞）→ 全体から切り分けられた1人分の取り分＝1盛り",
   relatedWords:[
     {word:"part",meaning:"部分",breakdown:"part（分ける）→ 全体から分けられた一つ"},
     {word:"partner",meaning:"相棒",breakdown:"part（分ける）＋ er（人）→ 分け前を共にする相手"},
     {word:"proportion",meaning:"割合",breakdown:"pro（前へ）＋ porti（分ける）→ 全体に対する分け前の大きさ"},
     {word:"particle",meaning:"粒子",breakdown:"part（分ける）＋ icle（小さいもの）→ 分けに分けた小さなかけら"}]},

  {id:884,word:"laundry",partOfSpeech:"名詞",meaning:"洗濯物；洗濯",
   meanings:["名|洗濯物","名|洗濯"],
   pronunciation:"/ˈlɔːndri/",part:89,
   example:"I hang the laundry on the balcony every sunny morning.",
   exampleJa:"私は晴れた朝はいつも、バルコニーに洗濯物を干す。",
   example2:"My brother forgot to bring the laundry inside last night.",
   exampleJa2:"兄は昨夜、洗濯物を中に取り込むのを忘れた。",
   etymologyProcess:"laund（洗う）＋ ry（もの）→ 洗うためにまとめた衣類は…？",
   etymologyConclusion:"laund（洗う）＋ ry（もの）→ これから洗う、また洗い終えた衣類のひとまとまり＝洗濯物",
   relatedWords:[
     {word:"launder",meaning:"洗濯する",breakdown:"laund（洗う）＋ er（人）→ 衣類を洗う人。そこから動詞になった"},
     {synonym:true,word:"wash",meaning:"洗う",breakdown:"水で汚れを落とすこと。laundry は洗う衣類のまとまりを指す"},
     {synonym:true,word:"clean",meaning:"きれいにする",breakdown:"汚れを取り除くこと。laundry は衣類を洗うことに限る"},
     {synonym:true,word:"rinse",meaning:"すすぐ",breakdown:"水で洗い流すこと。laundry は洗濯という仕事ぜんたいを指す"}]},

  {id:885,word:"nap",partOfSpeech:"名詞",meaning:"昼寝，うたた寝",
   meanings:["名|昼寝，うたた寝"],
   pronunciation:"/næp/",part:89,
   example:"My grandfather takes a short nap after lunch every day.",
   exampleJa:"祖父は毎日、昼食の後に短い昼寝をする。",
   example2:"A twenty-minute nap can help you study much better.",
   exampleJa2:"20分の昼寝は、ずっとよく勉強する助けになる。",
   etymologyProcess:"nap（うとうとする）→ 昼間に少しだけ眠ると…？",
   etymologyConclusion:"nap（うとうとする）→ 昼間に少しだけうとうとと眠ること＝昼寝",
   hook:"「パワーナップ（短い昼寝）」でそのまま通じる。短く軽い眠りが芯。",
   relatedWords:[
     {synonym:true,word:"sleep",meaning:"眠る",breakdown:"本格的に眠ること。nap は短く軽い、昼間のうたた寝"},
     {synonym:true,word:"doze",meaning:"うとうとする",breakdown:"眠りかけている状態。nap はそれを一区切りの行いとして数える"},
     {synonym:true,word:"rest",meaning:"休む",breakdown:"体を休めること。nap は必ず少し眠りに落ちる点が違う"},
     {synonym:true,word:"snooze",meaning:"居眠りする",breakdown:"短くうとうとすること。nap はそれを一区切りの行いとして数える"}]},

  {id:886,word:"wake",partOfSpeech:"自動詞",meaning:"目が覚める",
   meanings:["自|目が覚める","他|～を起こす"],
   pronunciation:"/weɪk/",part:89,
   example:"I usually wake at six thirty on school days.",
   exampleJa:"私はふだん、学校のある日は6時半に目が覚める。",
   example2:"The loud thunder woke the whole family last night.",
   exampleJa2:"大きな雷の音が昨夜、家族全員を起こした。",
   etymologyProcess:"wake（目覚める）→ 眠りから抜け出して頭がはっきりすると…？",
   etymologyConclusion:"wake（目覚める）→ 眠りから抜け出して意識がはっきりする＝目が覚める",
   relatedWords:[
     {word:"awake",meaning:"目が覚めて",breakdown:"wake（目覚める）→ すっかり眠りから覚めた状態にある"},
     {word:"awaken",meaning:"目覚めさせる",breakdown:"wake（目覚める）＋ en（〜にする）→ 眠りから覚めさせる"},
     {word:"wakeful",meaning:"眠れないでいる",breakdown:"wake（目覚める）＋ ful（満ちた）→ 目が冴えたままでいる"},
     {synonym:true,word:"rise",meaning:"起き上がる",breakdown:"床から体を起こすこと。wake は意識が戻ることを言う"}]},

  {id:887,word:"vending machine",partOfSpeech:"名詞",meaning:"自動販売機",
   meanings:["名|自動販売機"],
   pronunciation:"/ˈvendɪŋ məˌʃiːn/",part:89,
   example:"There is a vending machine right next to the school gate.",
   exampleJa:"校門のすぐ隣に自動販売機がある。",
   example2:"The vending machine did not give back my change.",
   exampleJa2:"その自動販売機はおつりを返してくれなかった。",
   etymologyProcess:"vend（売る）＋ ing（〜している）→ 人がいなくても売り続ける機械は…？",
   etymologyConclusion:"vend（売る）＋ ing（〜している）→ 人がいなくても売り続けてくれる機械＝自動販売機",
   relatedWords:[
     {word:"vendor",meaning:"売り手，販売業者",breakdown:"vend（売る）＋ or（人）→ 物を売るほうの人"},
     {word:"vend",meaning:"売る",breakdown:"vend（売る）→ 売り物として人前に差し出す"},
     {synonym:true,word:"stall",meaning:"売店，屋台",breakdown:"小さな売り場。vending machine は人のいない売り場そのもの"},
     {synonym:true,word:"sell",meaning:"売る",breakdown:"お金と引きかえに渡すこと。vend は機械や露店で売る堅い語"}]},

  {id:888,word:"grocery",partOfSpeech:"名詞",meaning:"食料雑貨店；（groceries で）食料品",
   meanings:["名|食料雑貨店","名|（groceries で）食料品"],
   pronunciation:"/ˈɡroʊsəri/",part:89,
   example:"My mother buys eggs at the grocery store near the station.",
   exampleJa:"母は駅の近くの食料雑貨店で卵を買う。",
   example2:"We carried the heavy grocery bags up the long stairs.",
   exampleJa2:"私たちは食料品の重い袋を、長い階段の上まで運んだ。",
   etymologyProcess:"gross（大量の）＋ ry（もの）→ まとめて仕入れて売る店は…？",
   etymologyConclusion:"gross（大量の）＋ ry（もの）→ 食べ物や日用品をまとめ買いして並べる店＝食料雑貨店",
   relatedWords:[
     {word:"grocer",meaning:"食料雑貨商",breakdown:"gross（大量の）＋ er（人）→ まとめ買いして売る人"},
     {word:"gross",meaning:"総計の；ひどい",breakdown:"gross（大量の）→ 差し引く前の、かたまりのままの量"},
     {synonym:true,word:"store",meaning:"店",breakdown:"品物を蓄えて売る場所。grocery は食料雑貨に限った店"},
     {synonym:true,word:"supermarket",meaning:"スーパー",breakdown:"自分で取って回る大きな店。grocery は昔ながらの小さな店も指す"}]},

  {id:889,word:"appointment",partOfSpeech:"名詞",meaning:"（面会の）約束，予約",
   meanings:["名|（面会の）約束，予約","名|任命"],
   pronunciation:"/əˈpɔɪntmənt/",part:89,
   example:"I have a dental appointment at four this afternoon.",
   exampleJa:"今日の午後4時に歯医者の予約がある。",
   example2:"She made an appointment to talk with her homeroom teacher.",
   exampleJa2:"彼女は担任の先生と話すための約束を取りつけた。",
   etymologyProcess:"ap（〜へ）＋ point（地点）→ 会う日時を一点に決めておくと…？",
   etymologyConclusion:"ap（〜へ）＋ point（地点）＋ ment（名詞）→ 会う日時を一点に決めておくこと＝面会の約束",
   relatedWords:[
     {word:"point",meaning:"点；要点",breakdown:"point（地点）→ とがった先が指し示す一つの点"},
     {word:"appoint",meaning:"任命する",breakdown:"ap（〜へ）＋ point（地点）→ 役目や日時を一点に決める"},
     {word:"disappoint",meaning:"失望させる",breakdown:"dis（否定）＋ ap（〜へ）＋ point（地点）→ 決めた約束を外して裏切る"},
     {word:"punctual",meaning:"時間を守る",breakdown:"punct（点）＋ al（形容詞）→ 決めた時刻の一点にぴたり合わせる"}]},

  {id:890,word:"consult",partOfSpeech:"他動詞",meaning:"相談する，意見を聞く",
   meanings:["他|相談する，意見を聞く","他|（辞書など）を調べる"],
   pronunciation:"/kənˈsʌlt/",part:89,
   example:"You should consult a doctor about that bad cough.",
   exampleJa:"そのひどい咳について医者に相談したほうがよい。",
   example2:"She consulted her teacher before choosing her future course.",
   exampleJa2:"彼女は進路を選ぶ前に先生に相談した。",
   etymologyProcess:"consult（相談する）→ 詳しい人に意見を聞きに行くと…？",
   etymologyConclusion:"consult（相談する）→ 詳しい人のところへ行って意見を聞く＝相談する",
   relatedWords:[
     {word:"consultant",meaning:"コンサルタント，相談役",breakdown:"consult（相談する）＋ ant（人）→ 相談に乗るのが仕事の人"},
     {word:"consultation",meaning:"相談，診察",breakdown:"consult（相談する）＋ ation（名詞）→ 意見を聞きに行くこと"},
     {synonym:true,word:"advise",meaning:"忠告する",breakdown:"こうしなさいと伝える側。consult は聞きに行く側の動き"},
     {synonym:true,word:"counsel",meaning:"助言する",breakdown:"consult と同じラテン語の家族。相手の身になって助言すること"}]},

  {id:891,word:"register",partOfSpeech:"他動詞",meaning:"登録する",
   meanings:["他|登録する，記録する","名|登録簿","名|レジ"],
   pronunciation:"/ˈredʒɪstər/",part:90,
   example:"You must register for the speech contest before next Monday.",
   exampleJa:"来週の月曜までにスピーチコンテストに登録しなければならない。",
   example2:"She registered her new bicycle at the city office.",
   exampleJa2:"彼女は市役所で新しい自転車を登録した。",
   etymologyProcess:"re（戻す）＋ gest（運ぶ）→ 後で見返せるよう帳簿へ運び戻すと…？",
   etymologyConclusion:"re（戻す）＋ gest（運ぶ）→ 後で見返せるよう帳簿へ運び戻して書き留める＝登録する",
   relatedWords:[
     {word:"suggest",meaning:"提案する",breakdown:"sug（下から）＋ gest（運ぶ）→ 下からそっと考えを差し出す"},
     {word:"gesture",meaning:"身ぶり",breakdown:"gest（運ぶ）＋ ure（名詞）→ 気持ちを体で運んで見せる動き"},
     {word:"digest",meaning:"消化する",breakdown:"di（離れて）＋ gest（運ぶ）→ 食べ物をばらばらに運び分ける"},
     {word:"registration",meaning:"登録",breakdown:"re（戻す）＋ gest（運ぶ）＋ ation（名詞）→ 帳簿に書き留めること"}]},

  {id:892,word:"dye",partOfSpeech:"他動詞",meaning:"染める",
   meanings:["他|染める","名|染料"],
   pronunciation:"/daɪ/",part:90,
   example:"She wants to dye her hair dark brown tomorrow.",
   exampleJa:"彼女は明日、髪を濃い茶色に染めたがっている。",
   example2:"This cloth was dyed with natural colors from plants.",
   exampleJa2:"この布は植物から取った天然の色で染められた。",
   etymologyProcess:"dye（色をしみ込ませる）→ 布や髪に色をしみ込ませると…？",
   etymologyConclusion:"dye（色をしみ込ませる）→ 布や髪に色をすっかりしみ込ませる＝染める",
   hook:"die（死ぬ）と同じ発音。ing 形は dyeing と e を残して区別する。",
   relatedWords:[
     {synonym:true,word:"color",meaning:"色をつける",breakdown:"表面に色をのせること。dye は繊維の芯まで色を入れる"},
     {synonym:true,word:"paint",meaning:"塗る",breakdown:"上から塗り重ねること。dye は液にひたしてしみ込ませる"},
     {synonym:true,word:"stain",meaning:"しみをつける",breakdown:"意図せず色がつくこと。dye は狙って色を入れる"},
     {synonym:true,word:"tint",meaning:"薄く色をつける",breakdown:"表面にうっすら色をのせる。dye は繊維の芯まで色を入れる"}]},

  {id:893,word:"subscribe",partOfSpeech:"自動詞",meaning:"定期購読する",
   meanings:["自|（to ～）（～を）定期購読する","自|（to ～）（～に）登録する"],
   pronunciation:"/səbˈskraɪb/",part:90,
   example:"Many students subscribe to that science magazine every year.",
   exampleJa:"多くの生徒が毎年その科学雑誌を定期購読している。",
   example2:"I subscribed to her channel after watching one short video.",
   exampleJa2:"短い動画を1本見た後、私は彼女のチャンネルを登録した。",
   etymologyProcess:"sub（下で）＋ scrib（書く）→ 申込書の下に名前を書くと…？",
   etymologyConclusion:"sub（下で）＋ scrib（書く）→ 申込書の下に名前を書いて約束する＝定期購読する",
   relatedWords:[
     {word:"describe",meaning:"描写する",breakdown:"de（下へ）＋ scrib（書く）→ 見たままを下へ書き写す"},
     {word:"prescribe",meaning:"処方する",breakdown:"pre（先に）＋ scrib（書く）→ 先に薬を書いて指示する"},
     {word:"subscription",meaning:"定期購読，サブスク",breakdown:"sub（下で）＋ script（書く）＋ ion（名詞）→ 名前を書いて続ける約束"},
     {word:"scribble",meaning:"走り書きする",breakdown:"scrib（書く）→ 勢いにまかせて何度も書きなぐる"}]},

  {id:894,word:"guarantee",partOfSpeech:"他動詞",meaning:"保証する",
   meanings:["他|保証する，請け合う","名|保証"],
   pronunciation:"/ˌɡærənˈtiː/",part:90,
   example:"We guarantee this school bag for two whole years.",
   exampleJa:"私たちはこの通学かばんを丸2年保証する。",
   example2:"Hard work alone does not always guarantee good results.",
   exampleJa2:"努力だけが必ずしもよい結果を保証するわけではない。",
   etymologyProcess:"garant（請け合う）→ 間違いないと請け合って引き受けると…？",
   etymologyConclusion:"garant（請け合う）→ 間違いないと請け合って責任まで引き受ける＝保証する",
   relatedWords:[
     {word:"warranty",meaning:"保証書",breakdown:"garant（請け合う）＋ ty（名詞）→ 請け合った内容を書いた紙"},
     {word:"warrant",meaning:"令状；保証する",breakdown:"garant（請け合う）→ 請け合った証しとして出す書き付け"},
     {synonym:true,word:"promise",meaning:"約束する",breakdown:"こうすると言うこと。guarantee は責任まで引き受ける強い約束"},
     {synonym:true,word:"ensure",meaning:"確実にする",breakdown:"そうなるように手を打つ。guarantee は相手に請け合って見せる"}]},

  {id:895,word:"wipe",partOfSpeech:"他動詞",meaning:"拭く",
   meanings:["他|拭く，拭き取る"],
   pronunciation:"/waɪp/",part:90,
   example:"Please wipe the desk before you start the experiment.",
   exampleJa:"実験を始める前に机を拭いてください。",
   example2:"He wiped his glasses with a soft clean cloth.",
   exampleJa2:"彼は柔らかいきれいな布で眼鏡を拭いた。",
   etymologyProcess:"wipe（さっとこする）→ 布でさっとこすって汚れを取ると…？",
   etymologyConclusion:"wipe（さっとこする）→ 布や手でさっとこすって汚れや水を取る＝拭く",
   hook:"語源は別だが、スマホの「スワイプ」と同じく面をさっとなでる動き。",
   relatedWords:[
     {synonym:true,word:"rub",meaning:"こする",breakdown:"押しつけてこすること。wipe は汚れや水を取るためにこする"},
     {synonym:true,word:"sweep",meaning:"掃く",breakdown:"ほうきでごみを払う。wipe は布で面をこすって取る"},
     {synonym:true,word:"erase",meaning:"消す",breakdown:"書いたものを消す。wipe は表面の汚れを拭き取る"},
     {synonym:true,word:"polish",meaning:"磨く",breakdown:"こすってつやを出す。wipe は汚れを取るところで止まる"}]},

  {id:896,word:"sweep",partOfSpeech:"他動詞",meaning:"掃く",
   meanings:["他|掃く，掃き清める","他|さっと押し流す"],
   pronunciation:"/swiːp/",part:90,
   example:"We sweep the classroom floor after lunch every day.",
   exampleJa:"私たちは毎日、昼食の後に教室の床を掃く。",
   example2:"A strong wind swept the dry leaves off the road.",
   exampleJa2:"強い風が乾いた葉を道から払いのけた。",
   etymologyProcess:"sweep（ひと振りで払う）→ ほうきをひと振りしてごみを払うと…？",
   etymologyConclusion:"sweep（ひと振りで払う）→ ほうきをひと振りしてごみを払い集める＝掃く",
   hook:"スポーツの「スイープ（総なめ）」も同じ。ひと振りで全部さらう動き。",
   relatedWords:[
     {synonym:true,word:"brush",meaning:"ブラシをかける",breakdown:"毛先ではらうこと。sweep はほうきで広い面をひと息に払う"},
     {synonym:true,word:"wipe",meaning:"拭く",breakdown:"布でこすって取ること。sweep はほうきでごみを払い集める"},
     {synonym:true,word:"dust",meaning:"ほこりを払う",breakdown:"ほこりを払い落とすこと。sweep はほうきで床のごみを集める"},
     {synonym:true,word:"clean",meaning:"きれいにする",breakdown:"汚れを取ること全般。sweep は床のごみを払う動きに限る"}]},

  {id:897,word:"transfer",partOfSpeech:"自動詞",meaning:"乗り換える；移す",
   meanings:["自|乗り換える","他|移す，移動させる"],
   pronunciation:"/trænsˈfɜːr/",part:90,
   example:"You must transfer to the local train at Kyoto Station.",
   exampleJa:"京都駅で普通列車に乗り換えなければならない。",
   example2:"The teacher transferred all the data to a new computer.",
   exampleJa2:"先生はすべてのデータを新しいコンピューターに移した。",
   etymologyProcess:"trans（越えて）＋ fer（運ぶ）→ 境を越えて別のほうへ移ると…？",
   etymologyConclusion:"trans（越えて）＋ fer（運ぶ）→ 今いる線を越えて別の乗り物へ身を運ぶ＝乗り換える",
   relatedWords:[
     {word:"ferry",meaning:"フェリー，渡し船",breakdown:"fer（運ぶ）＋ ry（もの）→ 人や車を向こう岸へ運ぶ船"},
     {word:"offer",meaning:"申し出る",breakdown:"of（相手のほうへ）＋ fer（運ぶ）→ 相手のほうへ差し出す"},
     {word:"prefer",meaning:"より好む",breakdown:"pre（先に）＋ fer（運ぶ）→ 心が先にそちらへ運ばれる"},
     {word:"refer",meaning:"言及する；参照する",breakdown:"re（戻す）＋ fer（運ぶ）→ 話を元のところへ運び戻す"}]},

  {id:898,word:"divorce",partOfSpeech:"自動詞",meaning:"離婚する",
   meanings:["自|離婚する","名|離婚"],
   pronunciation:"/dɪˈvɔːrs/",part:90,
   example:"They decided to divorce after twenty years of marriage.",
   exampleJa:"彼らは結婚20年の後、離婚することに決めた。",
   example2:"Her parents divorced when she was still a small child.",
   exampleJa2:"彼女の両親は、彼女がまだ小さな子どものころに離婚した。",
   etymologyProcess:"di（離れて）＋ vorc（回る）→ 二人が別々の方へ向きを変えると…？",
   etymologyConclusion:"di（離れて）＋ vorc（回る）→ 二人が別々の方へ向きを変えて離れていく＝離婚する",
   relatedWords:[
     {word:"diverse",meaning:"多様な",breakdown:"di（離れて）＋ vers（回る）→ それぞれ別の方を向いている"},
     {word:"divert",meaning:"そらす",breakdown:"di（離れて）＋ vert（回る）→ 向きを変えて別の方へやる"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ 向きを後ろへぐるりと回す"},
     {word:"version",meaning:"版；解釈",breakdown:"vers（回る）＋ ion（名詞）→ 向きを変えて言い直したもの"}]},

  {id:899,word:"fate",partOfSpeech:"名詞",meaning:"運命，行く末",
   meanings:["名|運命，行く末"],
   pronunciation:"/feɪt/",part:90,
   example:"Nobody knows the fate of the ship that sank yesterday.",
   exampleJa:"昨日沈んだ船の運命は、誰も知らない。",
   example2:"She believed that fate brought the two of them together.",
   exampleJa2:"彼女は、二人を引き合わせたのは運命だと信じていた。",
   etymologyProcess:"fat（語られる）→ 神が語ったとおりに定まっているなら…？",
   etymologyConclusion:"fat（語られる）→ 神々が語ったとおりに定まっている行く末＝運命",
   relatedWords:[
     {word:"fame",meaning:"名声",breakdown:"fam（語られる）→ 多くの人の口に語られること"},
     {word:"famous",meaning:"有名な",breakdown:"fam（語られる）＋ ous（形容詞）→ みんなに語られている"},
     {word:"fatal",meaning:"命にかかわる",breakdown:"fat（語られる）＋ al（形容詞）→ 定められた終わりを招く"},
     {synonym:true,word:"luck",meaning:"運",breakdown:"たまたまの巡り合わせ。fate は初めから定まっている行く末"}]},

  {id:900,word:"destiny",partOfSpeech:"名詞",meaning:"（進むべき）運命，宿命",
   meanings:["名|（進むべき）運命，宿命"],
   pronunciation:"/ˈdestəni/",part:90,
   example:"He believed it was his destiny to become a doctor.",
   exampleJa:"医者になることが自分の運命だと彼は信じていた。",
   example2:"Many people think that destiny decides who we meet.",
   exampleJa2:"多くの人は、誰と出会うかは運命が決めると思っている。",
   etymologyProcess:"de（すっかり）＋ stin（決める）→ 行き着く先が決められているなら…？",
   etymologyConclusion:"de（すっかり）＋ stin（決める）→ 行き着く先があらかじめ決められていること＝運命",
   relatedWords:[
     {word:"destination",meaning:"目的地",breakdown:"de（すっかり）＋ stin（決める）＋ ation（名詞）→ 行き着くと決められた場所"},
     {word:"destine",meaning:"運命づける",breakdown:"de（すっかり）＋ stin（決める）→ 行く先をあらかじめ決めておく"},
     {word:"obstinate",meaning:"がんこな",breakdown:"ob（向かい合って）＋ stin（決める）→ 向き合ったまま決めを変えない"},
     {synonym:true,word:"fate",meaning:"運命，行く末",breakdown:"定められた行く末。destiny は進むべき道という前向きな含みがある"}]},

  {id:901,word:"flavor",partOfSpeech:"名詞",meaning:"風味，味わい",
   meanings:["名|風味，味わい"],
   pronunciation:"/ˈfleɪvər/",part:91,
   example:"This ice cream has a strong lemon flavor today.",
   exampleJa:"このアイスクリームは今日、強いレモンの風味がする。",
   example2:"Fresh herbs add a nice flavor to the tomato soup.",
   exampleJa2:"新鮮なハーブがトマトスープによい風味を加える。",
   etymologyProcess:"flav（吹いてくる）→ 鼻へ吹いてきて舌と合わさるのは…？",
   etymologyConclusion:"flav（吹いてくる）→ 鼻へ吹いてきて舌の感じと重なる味わい＝風味",
   hook:"「フレーバー」がそのまま使える。味と香りが重なったものが風味。",
   relatedWords:[
     {synonym:true,word:"taste",meaning:"味",breakdown:"舌で感じるもの。flavor は香りも合わさった味わい全体"},
     {synonym:true,word:"smell",meaning:"におい",breakdown:"鼻で感じるもの。flavor は口の中で香りと味が重なったもの"},
     {synonym:true,word:"season",meaning:"味つけする",breakdown:"塩やこしょうで整えること。flavor はその結果生まれる味わい"},
     {synonym:true,word:"spice",meaning:"香辛料",breakdown:"風味を足すための材料。flavor は感じ取られる風味そのもの"}]},

  {id:902,word:"perfume",partOfSpeech:"名詞",meaning:"香水；よい香り",
   meanings:["名|香水","名|よい香り"],
   pronunciation:"/ˈpɜːrfjuːm/",part:91,
   example:"She wears a light perfume made from wild flowers.",
   exampleJa:"彼女は野の花から作られた軽い香水をつけている。",
   example2:"The perfume of the roses filled the whole small room.",
   exampleJa2:"バラのよい香りが小さな部屋全体に満ちた。",
   etymologyProcess:"per（通して）＋ fum（煙）→ 煙のように立ちのぼって広がるのは…？",
   etymologyConclusion:"per（通して）＋ fum（煙）→ 煙のように立ちのぼり部屋中を通っていく香り＝香水",
   relatedWords:[
     {word:"fume",meaning:"煙，ガス",breakdown:"fum（煙）→ 立ちのぼるけむりやガス"},
     {synonym:true,word:"aroma",meaning:"芳香，よい香り",breakdown:"コーヒーや花のよい香り。perfume はつけるための香水も指す"},
     {synonym:true,word:"scent",meaning:"香り",breakdown:"かすかなよいにおい。perfume はつけるための香水も指す"},
     {synonym:true,word:"fragrance",meaning:"芳香",breakdown:"よい香りの堅い言い方。perfume は商品としての香水も指す"}]},

  {id:903,word:"ingredient",partOfSpeech:"名詞",meaning:"（料理の）材料，具材",
   meanings:["名|（料理の）材料，具材","名|（成功などの）要素"],
   pronunciation:"/ɪnˈɡriːdiənt/",part:91,
   example:"Please buy all the ingredients for tonight's curry today.",
   exampleJa:"今日、今夜のカレーの材料を全部買ってきてください。",
   example2:"Patience is an important ingredient in any real success.",
   exampleJa2:"忍耐は、本当の成功に欠かせない要素だ。",
   etymologyProcess:"in（中へ）＋ gred（歩む）→ 料理の中へ歩み入っていくものは…？",
   etymologyConclusion:"in（中へ）＋ gred（歩む）→ 料理の中へ歩み入って一つになるもの＝料理の材料",
   relatedWords:[
     {word:"progress",meaning:"進歩",breakdown:"pro（前へ）＋ gress（歩む）→ 前へ歩み進んでいくこと"},
     {word:"congress",meaning:"議会",breakdown:"con（共に）＋ gress（歩む）→ 共に集まって歩み寄る場"},
     {word:"aggressive",meaning:"攻撃的な",breakdown:"ad（〜へ）＋ gress（歩む）→ 相手のほうへ踏み込んでいく"},
     {word:"gradual",meaning:"少しずつの",breakdown:"grad（歩み・段）＋ al（形容詞）→ 一段ずつ進んでいく"}]},

  {id:904,word:"bitter",partOfSpeech:"形容詞",meaning:"苦い",
   meanings:["形|苦い","形|つらい，苦々しい"],
   pronunciation:"/ˈbɪtər/",part:91,
   example:"This green tea tastes very bitter without any sugar.",
   exampleJa:"この緑茶は砂糖を入れないととても苦い。",
   example2:"He still remembers the bitter taste of that defeat.",
   exampleJa2:"彼はいまだに、あの敗北の苦い味を覚えている。",
   etymologyProcess:"bit（かむ）→ 舌をかみつくように刺す味は…？",
   etymologyConclusion:"bit（かむ）→ 舌をかみつくようにぴりっと刺してくる味＝苦い",
   relatedWords:[
     {word:"bite",meaning:"かむ",breakdown:"bit（かむ）→ 歯を立ててぐっと食い込ませる"},
     {word:"bit",meaning:"少し；かけら",breakdown:"bit（かむ）→ ひと口かじり取ったくらいの小さな分"},
     {word:"beetle",meaning:"甲虫，カブトムシ",breakdown:"bit（かむ）→ かみつくあごを持った虫"},
     {synonym:true,word:"sour",meaning:"酸っぱい",breakdown:"舌が縮むような酸味。bitter はコーヒーのような苦みを指す"}]},

  {id:905,word:"aisle",partOfSpeech:"名詞",meaning:"通路",
   meanings:["名|（座席や棚の間の）通路"],
   pronunciation:"/aɪl/",part:91,
   example:"Please do not leave your bag in the aisle.",
   exampleJa:"通路にかばんを置いたままにしないでください。",
   example2:"The flight attendant walked slowly down the narrow aisle.",
   exampleJa2:"客室乗務員は狭い通路をゆっくり歩いていった。",
   etymologyProcess:"ala（翼）→ 建物の横に翼のようにのびた道は…？",
   etymologyConclusion:"ala（翼）→ 建物の翼のように本体の横へのびた細い通り道＝通路",
   hook:"発音は /aɪl/ で s を読まない。island と同じく後から s が入った綴り。",
   relatedWords:[
     {synonym:true,word:"corridor",meaning:"廊下",breakdown:"建物の中の細長い通り道。aisle は座席や棚の間の通路"},
     {synonym:true,word:"path",meaning:"小道",breakdown:"外にある細い道。aisle は建物や乗り物の中の通路"},
     {synonym:true,word:"lane",meaning:"車線，小道",breakdown:"区切られた細長い道。aisle は歩いて通る屋内の道"},
     {synonym:true,word:"passage",meaning:"通路，通り道",breakdown:"通り抜けるための道。aisle は座席や棚の間の細い通路"}]},

  {id:906,word:"track",partOfSpeech:"名詞",meaning:"足跡；通り道",
   meanings:["名|足跡，通った跡","名|小道，通り道","名|（陸上の）トラック"],
   pronunciation:"/træk/",part:91,
   example:"We followed the tracks of a deer in the snow.",
   exampleJa:"私たちは雪の中でシカの足跡をたどった。",
   example2:"A narrow track leads from the village to the lake.",
   exampleJa2:"細い通り道が村から湖まで続いている。",
   etymologyProcess:"track（踏まれた跡）→ 通った者が地面に残していくものは…？",
   etymologyConclusion:"track（踏まれた跡）→ 通った者が地面に残していく跡やそのすじ＝足跡",
   hook:"陸上の「トラック」も音楽の「トラック（曲）」も同じ。通った跡のすじ。",
   relatedWords:[
     {synonym:true,word:"trail",meaning:"山道；跡",breakdown:"引きずった跡からできた道。track は踏まれてできた跡"},
     {synonym:true,word:"trace",meaning:"跡；たどる",breakdown:"かすかに残る印。track は続いて並んだ足跡のすじ"},
     {synonym:true,word:"path",meaning:"小道",breakdown:"人が歩いてできた道。track は動物や車の残した跡も指す"},
     {synonym:true,word:"route",meaning:"道すじ",breakdown:"決められた通り道。track は実際に踏まれてできた跡"}]},

  {id:907,word:"district",partOfSpeech:"名詞",meaning:"地区，区域",
   meanings:["名|地区，区域"],
   pronunciation:"/ˈdɪstrɪkt/",part:91,
   example:"This district has many small shops and very old houses.",
   exampleJa:"この地区には小さな店ととても古い家が多い。",
   example2:"Police patrol this district more often after the recent incident.",
   exampleJa2:"最近の事件の後、警察はこの地区をより頻繁に巡回している。",
   etymologyProcess:"dis（バラバラに）＋ strict（締めつける）→ 土地を区切って締めくくると…？",
   etymologyConclusion:"dis（バラバラに）＋ strict（締めつける）→ 土地を区切って締めくくった一まとまり＝地区",
   relatedWords:[
     {word:"strict",meaning:"厳しい",breakdown:"strict（締めつける）→ ゆるみなくきつく締めつける"},
     {word:"restrict",meaning:"制限する",breakdown:"re（後ろへ）＋ strict（締めつける）→ 締めて引き戻し、外へ出さない"},
     {word:"stress",meaning:"圧力，強調",breakdown:"stress（締めつける）→ ぎゅっと締めつけてくる力"},
     {word:"strain",meaning:"負担",breakdown:"strain（締めつける）→ ぴんと引き締められて生じる力"}]},

  {id:908,word:"facility",partOfSpeech:"名詞",meaning:"施設，設備",
   meanings:["名|施設，設備"],
   pronunciation:"/fəˈsɪləti/",part:91,
   example:"Our town built a new sports facility near the river.",
   exampleJa:"私たちの町は川の近くに新しいスポーツ施設を建てた。",
   example2:"Students can use all the facilities in this library for free.",
   exampleJa2:"生徒はこの図書館のすべての施設を無料で使える。",
   etymologyProcess:"facil（しやすい）＋ ity（名詞）→ 物事をしやすくしてくれるものは…？",
   etymologyConclusion:"facil（しやすい）＋ ity（名詞）→ 物事をしやすくするために備えられた建物や設備＝施設",
   why:"【なぜ】ラテン語 facere（作る）から facilis「作りやすい＝たやすい」ができ、その名詞 facilitas は「たやすさ」でした。そこから「物事をたやすくしてくれるもの」＝設備・施設へ意味が移りました。\n【つながり】difficult（＝たやすくない）や facilitate（たやすくする）も同じ家族。facility には今も「容易さ・才能」の意味が残っています。",
   relatedWords:[
     {word:"facilitate",meaning:"容易にする",breakdown:"facil（しやすい）＋ ate（動詞）→ 物事をしやすくしてやる"},
     {word:"difficult",meaning:"難しい",breakdown:"dis（否定）＋ facil（しやすい）→ たやすくはない"},
     {word:"fact",meaning:"事実",breakdown:"fact（作る）→ 実際に作り出されて起きたこと。facil と同じ facere の家族"},
     {synonym:true,word:"equipment",meaning:"設備，備品",breakdown:"そろえた道具のひとそろい。facility は建物ごとの設備を指す"}]},

  {id:909,word:"height",partOfSpeech:"名詞",meaning:"高さ",
   meanings:["名|高さ，身長"],
   pronunciation:"/haɪt/",part:91,
   example:"What is the height of that tall old clock tower?",
   exampleJa:"あの高い古い時計塔の高さはどれくらいですか。",
   example2:"The plane slowly reached a height of ten thousand meters.",
   exampleJa2:"その飛行機はゆっくり1万メートルの高さに達した。",
   etymologyProcess:"high（高い）＋ th（名詞）→ どれだけ高いかを表すと…？",
   etymologyConclusion:"high（高い）＋ th（名詞）→ どれだけ高いかを数で表したもの＝高さ",
   relatedWords:[
     {word:"high",meaning:"高い",breakdown:"high（高い）→ 地面から上へ大きく離れている"},
     {word:"highly",meaning:"大いに",breakdown:"high（高い）＋ ly（副詞）→ 程度の高いところまで"},
     {word:"heighten",meaning:"高める",breakdown:"high（高い）＋ en（〜にする）→ 高さや程度を上げる"},
     {synonym:true,word:"altitude",meaning:"高度",breakdown:"海面から測った高さ。height は物そのものの高さも指す"}]},

  {id:910,word:"distant",partOfSpeech:"形容詞",meaning:"遠い，遠く離れた",
   meanings:["形|遠い，遠く離れた","形|よそよそしい"],
   pronunciation:"/ˈdɪstənt/",part:91,
   example:"We could see a distant mountain through the clear air.",
   exampleJa:"澄んだ空気を通して、遠い山が見えた。",
   example2:"He keeps a distant attitude toward his new classmates.",
   exampleJa2:"彼は新しいクラスメートに対してよそよそしい態度を保っている。",
   etymologyProcess:"dis（離れて）＋ stant（立っている）→ 離れたところに立っていると…？",
   etymologyConclusion:"dis（離れて）＋ stant（立っている）→ 離れたところに立っていて間が空いている＝遠い",
   relatedWords:[
     {word:"distance",meaning:"距離",breakdown:"dis（離れて）＋ stant（立っている）→ 離れて立つ二点の間の長さ"},
     {word:"instant",meaning:"即座の",breakdown:"in（上に）＋ stant（立っている）→ すぐそばに立っている一瞬"},
     {word:"constant",meaning:"絶え間ない",breakdown:"con（共に）＋ stant（立っている）→ ずっと同じ所に立ち続ける"},
     {word:"stand",meaning:"立つ",breakdown:"sta（立つ）→ 足を地につけてまっすぐ立つ"}]},

  {id:911,word:"locate",partOfSpeech:"他動詞",meaning:"位置を突き止める",
   meanings:["他|位置を突き止める","他|（be located で）位置している"],
   pronunciation:"/ˈloʊkeɪt/",part:92,
   example:"The rescue team could not locate the missing hiker.",
   exampleJa:"救助隊は、行方不明の登山者の位置を突き止められなかった。",
   example2:"Our school is located near a quiet old shrine.",
   exampleJa2:"私たちの学校は静かな古い神社の近くに位置している。",
   etymologyProcess:"loc（場所）＋ ate（動詞）→ どの場所にあるかをはっきりさせると…？",
   etymologyConclusion:"loc（場所）＋ ate（動詞）→ どの場所にあるのかをはっきりさせる＝位置を突き止める",
   relatedWords:[
     {word:"local",meaning:"地元の",breakdown:"loc（場所）＋ al（形容詞）→ その場所に限られた"},
     {word:"location",meaning:"場所，位置",breakdown:"loc（場所）＋ ation（名詞）→ どこにあるかという場所"},
     {word:"allocate",meaning:"割り当てる",breakdown:"ad（〜へ）＋ loc（場所）→ それぞれの場所へ振り分ける"},
     {word:"relocate",meaning:"移転する",breakdown:"re（再び）＋ loc（場所）→ 別の場所へ置き直す"}]},

  {id:912,word:"occupy",partOfSpeech:"他動詞",meaning:"占める，ふさぐ",
   meanings:["他|（場所・時間）を占める，ふさぐ","他|占領する"],
   pronunciation:"/ˈɑːkjupaɪ/",part:92,
   example:"Large machines occupy most of the old factory floor.",
   exampleJa:"大きな機械が、古い工場の床の大部分を占めている。",
   example2:"Studying for exams occupied all of her free time.",
   exampleJa2:"試験勉強が彼女の自由な時間をすべて占めた。",
   etymologyProcess:"oc（〜に向かって）＋ cupa（取る）→ 場所をつかみ取ってふさぐと…？",
   etymologyConclusion:"oc（〜に向かって）＋ cupa（取る）→ 場所や時間をつかみ取ってふさいでしまう＝占める",
   relatedWords:[
     {word:"occupation",meaning:"職業；占領",breakdown:"oc（〜に向かって）＋ cupa（取る）＋ ion（名詞）→ 時間を取って打ち込むこと"},
     {word:"accept",meaning:"受け入れる",breakdown:"ac（〜へ）＋ cept（取る）→ 差し出されたほうへ手を出して取る"},
     {synonym:true,word:"fill",meaning:"満たす",breakdown:"中をいっぱいにすること。occupy は取ったまま他を入れないこと"},
     {synonym:true,word:"take",meaning:"取る",breakdown:"手に入れること。occupy は取って場所をふさいだ状態を指す"}]},

  {id:913,word:"surround",partOfSpeech:"他動詞",meaning:"取り囲む",
   meanings:["他|取り囲む"],
   pronunciation:"/səˈraʊnd/",part:92,
   example:"Tall trees surround the small park near my house.",
   exampleJa:"高い木々が、私の家の近くの小さな公園を取り囲んでいる。",
   example2:"The old castle was surrounded by a deep wide moat.",
   exampleJa2:"その古い城は、深く広い堀に取り囲まれていた。",
   etymologyProcess:"sur（上を越えて）＋ und（波打つ）→ 波があふれて周りを満たすと…？",
   etymologyConclusion:"sur（上を越えて）＋ und（波打つ）→ 水があふれて周りをぐるりと満たす＝取り囲む",
   why:"【なぜ】もとのラテン語 superundare は「あふれ出る」。水があふれて土地のまわりを満たす様子から、「まわりをぐるりと取り巻く」意味になりました。英語では綴りが round（丸い）に似ているため、「丸く囲む」と結びつけて使われるようになっています。\n【つながり】abundant（あふれるほど多い）、undulate（波打つ）も同じ und の家族です。",
   relatedWords:[
     {word:"abundant",meaning:"豊富な",breakdown:"ab（あふれて）＋ und（波打つ）→ 波のようにあふれるほど多い"},
     {word:"abound",meaning:"あり余るほどある",breakdown:"ab（あふれて）＋ und（波打つ）→ 波のようにあふれ出るほどある"},
     {word:"undulate",meaning:"波打つ",breakdown:"und（波打つ）＋ ate（動詞）→ ゆるやかに波のように動く"},
     {synonym:true,word:"enclose",meaning:"囲む",breakdown:"囲って閉じること。surround はぐるりと周りを取り巻くこと"}]},

  {id:914,word:"classical",partOfSpeech:"形容詞",meaning:"古典の，古典的な",
   meanings:["形|古典の，古典的な","形|（音楽が）クラシックの"],
   pronunciation:"/ˈklæsɪkl/",part:92,
   example:"He studies classical Greek plays at the university now.",
   exampleJa:"彼は今、大学で古典のギリシャ劇を学んでいる。",
   example2:"She enjoys classical music more than modern pop songs.",
   exampleJa2:"彼女は現代のポップスよりクラシック音楽を楽しむ。",
   etymologyProcess:"classic（一流の）＋ al（形容詞）→ 昔から手本とされてきたなら…？",
   etymologyConclusion:"classic（一流の）＋ al（形容詞）→ 昔から一流と認められ手本にされてきた＝古典の",
   why:"【なぜ】ラテン語 classis は、ローマ市民を財産で分けた「等級」のことでした。その最上級の市民を classicus と呼び、やがて「第一級の作家」を指すようになります。そこから「時代を越えて手本とされる＝古典の」になりました。\n【つながり】class（学級・等級）、classify（分類する）も同じ家族。音楽の「クラシック」も「一流と認められた曲」という意味です。",
   relatedWords:[
     {word:"class",meaning:"学級；等級",breakdown:"class（学級）→ 同じ段階に分けられたひとまとまり"},
     {word:"classic",meaning:"名作；一流の",breakdown:"classic（一流の）→ 時代を越えて一流と認められたもの"},
     {word:"classify",meaning:"分類する",breakdown:"class（学級）＋ fy（する）→ 段階やなかまごとに分ける"},
     {synonym:true,word:"traditional",meaning:"伝統的な",breakdown:"昔から受け継がれた。classical は手本とされる古典を指す"}]},

  {id:915,word:"civilization",partOfSpeech:"名詞",meaning:"文明",
   meanings:["名|文明"],
   pronunciation:"/ˌsɪvələˈzeɪʃn/",part:92,
   example:"Ancient civilization began near large rivers in warm areas.",
   exampleJa:"古代の文明は、暖かい地域の大きな川の近くで始まった。",
   example2:"Writing changed human civilization more than any other invention.",
   exampleJa2:"文字は、他のどんな発明よりも人類の文明を変えた。",
   etymologyProcess:"civ（市民）＋ ize（動詞）＋ ation（名詞）→ 市民らしく暮らし始めると…？",
   etymologyConclusion:"civ（市民）＋ ize（動詞）＋ ation（名詞）→ 人が町に集まり市民らしく暮らすようになること＝文明",
   relatedWords:[
     {word:"civil",meaning:"市民の；礼儀正しい",breakdown:"civ（市民）＋ il（〜の）→ 町に住む市民らしい"},
     {word:"citizen",meaning:"市民",breakdown:"civ（市民）→ 町に住む権利を持っている人"},
     {word:"city",meaning:"都市",breakdown:"civ（市民）＋ ty（名詞）→ 市民が集まって住むところ"},
     {word:"civilize",meaning:"文明化する",breakdown:"civ（市民）＋ ize（動詞）→ 市民らしい暮らしに変える"}]},

  {id:916,word:"heritage",partOfSpeech:"名詞",meaning:"遺産",
   meanings:["名|（受け継がれた）遺産"],
   pronunciation:"/ˈherɪtɪdʒ/",part:92,
   example:"This old temple is part of our national heritage.",
   exampleJa:"この古い寺は、私たちの国の遺産の一部だ。",
   example2:"The town works hard to protect its cultural heritage.",
   exampleJa2:"その町は、自分たちの文化の遺産を守るために懸命に取り組んでいる。",
   etymologyProcess:"herit（受け継ぐ）＋ age（名詞）→ 先の世代から受け継ぐものは…？",
   etymologyConclusion:"herit（受け継ぐ）＋ age（名詞）→ 先の世代から受け継ぎ次へ渡していくもの＝遺産",
   relatedWords:[
     {word:"inherit",meaning:"受け継ぐ",breakdown:"in（中へ）＋ herit（受け継ぐ）→ 自分の中へ受け取って継ぐ"},
     {word:"heir",meaning:"相続人",breakdown:"herit（受け継ぐ）→ 財産を受け継ぐことになっている人"},
     {word:"inheritance",meaning:"相続財産",breakdown:"in（中へ）＋ herit（受け継ぐ）＋ ance（名詞）→ 受け継がれる財産"},
     {synonym:true,word:"tradition",meaning:"伝統",breakdown:"受け継がれるならわし。heritage は建物や文化など受け継ぐもの全体"}]},

  {id:917,word:"script",partOfSpeech:"名詞",meaning:"台本，脚本",
   meanings:["名|台本，脚本","名|文字，書体"],
   pronunciation:"/skrɪpt/",part:92,
   example:"The actors read the script together before the rehearsal.",
   exampleJa:"俳優たちはリハーサルの前に、一緒に台本を読んだ。",
   example2:"She wrote the script for our class drama contest.",
   exampleJa2:"彼女は私たちのクラスの演劇コンテストの台本を書いた。",
   etymologyProcess:"script（書く）→ 役者の話す言葉を書き並べたものは…？",
   etymologyConclusion:"script（書く）→ 役者が話す言葉を順に書き並べたもの＝台本",
   relatedWords:[
     {word:"describe",meaning:"描写する",breakdown:"de（下へ）＋ scrib（書く）→ 見たままを下へ書き写す"},
     {word:"subscribe",meaning:"定期購読する",breakdown:"sub（下で）＋ scrib（書く）→ 申込書の下に名前を書く"},
     {word:"manuscript",meaning:"原稿",breakdown:"manu（手）＋ script（書く）→ 手で書かれたもの"},
     {word:"prescription",meaning:"処方せん",breakdown:"pre（先に）＋ script（書く）＋ ion（名詞）→ 先に書いて渡す指示"}]},

  {id:918,word:"tale",partOfSpeech:"名詞",meaning:"（語り継がれる）物語",
   meanings:["名|（語り継がれる）物語，話"],
   pronunciation:"/teɪl/",part:92,
   example:"My grandmother told us a strange old tale last night.",
   exampleJa:"祖母は昨夜、私たちに不思議な古い物語を話してくれた。",
   example2:"This folk tale has been passed down for many centuries.",
   exampleJa2:"この民話は何世紀にもわたって語り継がれてきた。",
   etymologyProcess:"tale（語る）→ 語り伝えられてきたひとまとまりは…？",
   etymologyConclusion:"tale（語る）→ 順を追って語り伝えられてきたひとまとまりの話＝物語",
   hook:"tale は語り継がれた昔話。story より、作り話・言い伝えの色が濃い。",
   relatedWords:[
     {word:"tell",meaning:"話す，伝える",breakdown:"tale（語る）→ 順を追って言葉で伝える"},
     {word:"talk",meaning:"話す，しゃべる",breakdown:"tale（語る）→ 言葉をやりとりして話す"},
     {synonym:true,word:"story",meaning:"話，物語",breakdown:"できごとの筋のこと。tale は語り継がれた昔話の色が濃い"},
     {synonym:true,word:"legend",meaning:"伝説",breakdown:"本当にあったと信じられる言い伝え。tale は物語一般を指す"}]},

  {id:919,word:"literature",partOfSpeech:"名詞",meaning:"文学",
   meanings:["名|文学","名|（ある分野の）文献"],
   pronunciation:"/ˈlɪtrətʃər/",part:92,
   example:"She studies English literature at a university in London.",
   exampleJa:"彼女はロンドンの大学で英文学を学んでいる。",
   example2:"Japanese literature includes many famous works by women writers.",
   exampleJa2:"日本の文学には、女性作家による有名な作品が多く含まれる。",
   etymologyProcess:"liter（文字）＋ ature（名詞）→ 文字で書き残された作品は…？",
   etymologyConclusion:"liter（文字）＋ ature（名詞）→ 文字で書き残された作品のひとまとまり＝文学",
   relatedWords:[
     {word:"letter",meaning:"文字；手紙",breakdown:"liter（文字）→ 一つ一つの文字。並べて送れば手紙になる"},
     {word:"literal",meaning:"文字どおりの",breakdown:"liter（文字）＋ al（形容詞）→ 書かれた文字そのままの"},
     {word:"literally",meaning:"文字どおりに",breakdown:"liter（文字）＋ ly（副詞）→ 文字に書いてあるとおりに"},
     {word:"literacy",meaning:"読み書きの力",breakdown:"liter（文字）＋ cy（名詞）→ 文字を読み書きできる力"}]},

  {id:920,word:"tragedy",partOfSpeech:"名詞",meaning:"悲劇",
   meanings:["名|悲劇","名|（実際の）悲惨なできごと"],
   pronunciation:"/ˈtrædʒədi/",part:92,
   example:"The play ends as a tragedy for the young hero.",
   exampleJa:"その劇は、若い主人公にとっての悲劇として終わる。",
   example2:"That traffic accident was a terrible tragedy for the town.",
   exampleJa2:"その交通事故は、町にとってひどい悲劇だった。",
   etymologyProcess:"trag（やぎ）＋ ody（歌）→ 儀式の歌から生まれた劇は…？",
   etymologyConclusion:"trag（やぎ）＋ ody（歌）→ やぎをささげる儀式の歌から生まれた、悲しい結末の劇＝悲劇",
   why:"【なぜ】ギリシャ語の tragos（やぎ）＋ ōidē（歌）。古代ギリシャの祭りで、やぎをいけにえにささげるときに歌われた合唱から劇が生まれた、という説が有力です。その劇が主人公の破滅を描いたので「悲劇」になりました。\n【つながり】comedy（喜劇）の -edy も同じ「歌」。melody（旋律）、parody（替え歌）も同じ家族です。",
   relatedWords:[
     {synonym:true,word:"comedy",meaning:"喜劇",breakdown:"tragedy と対になる劇。-edy はやはりギリシャ語の「歌」から"},
     {synonym:true,word:"melody",meaning:"旋律，メロディー",breakdown:"-ody は同じ「歌」。tragedy と同じ ōidē から来ている"},
     {word:"parody",meaning:"パロディー",breakdown:"para（そばで）＋ ody（歌）→ そばで真似して歌い替えたもの"},
     {synonym:true,word:"disaster",meaning:"災害，惨事",breakdown:"大きな不幸なできごと。tragedy は悲しい結末の劇も指す"}]},

  {id:921,word:"poetry",partOfSpeech:"名詞",meaning:"詩（作品全体）",
   meanings:["名|詩，詩というジャンル"],
   pronunciation:"/ˈpoʊətri/",part:93,
   example:"He started writing poetry when he was only fifteen.",
   exampleJa:"彼はまだ15歳のときに詩を書き始めた。",
   example2:"Japanese poetry often uses the four seasons as a theme.",
   exampleJa2:"日本の詩は、しばしば四季を題材にする。",
   etymologyProcess:"poe（作る）＋ ry（もの）→ 言葉を選んで作り上げたものは…？",
   etymologyConclusion:"poe（作る）＋ ry（もの）→ 言葉を選び抜いて作り上げた作品のひとまとまり＝詩",
   relatedWords:[
     {word:"poem",meaning:"詩（1編）",breakdown:"poe（作る）→ 言葉を選んで作り上げた作品1つ"},
     {word:"poet",meaning:"詩人",breakdown:"poe（作る）→ 言葉で作品を作る人"},
     {word:"poetic",meaning:"詩的な",breakdown:"poe（作る）＋ ic（形容詞）→ 詩のように作り上げられた"},
     {synonym:true,word:"verse",meaning:"韻文，詩節",breakdown:"行に区切った詩の形。poetry は詩というジャンル全体を指す"}]},

  {id:922,word:"biography",partOfSpeech:"名詞",meaning:"伝記",
   meanings:["名|伝記"],
   pronunciation:"/baɪˈɑːɡrəfi/",part:93,
   example:"I read a biography of a famous Japanese scientist.",
   exampleJa:"私は有名な日本の科学者の伝記を読んだ。",
   example2:"Her biography describes her childhood in a small fishing village.",
   exampleJa2:"彼女の伝記は、小さな漁村での子ども時代を描いている。",
   etymologyProcess:"bio（生命）＋ graph（書く）→ 人が生きた道のりを書き記すと…？",
   etymologyConclusion:"bio（生命）＋ graph（書く）→ その人が生きた道のりを書き記したもの＝伝記",
   relatedWords:[
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）→ 生き物について調べる学問"},
     {word:"graph",meaning:"グラフ",breakdown:"graph（書く）→ 数の動きを線で書き表したもの"},
     {word:"photograph",meaning:"写真",breakdown:"photo（光）＋ graph（書く）→ 光で描き取ったもの"},
     {word:"autograph",meaning:"サイン，自筆",breakdown:"auto（自分）＋ graph（書く）→ 自分の手で書いた名前"}]},

  {id:923,word:"term",partOfSpeech:"名詞",meaning:"用語，専門語",
   meanings:["名|用語，専門語","名|学期，期間","名|（terms で）条件"],
   pronunciation:"/tɜːrm/",part:93,
   example:"Please explain that difficult medical term in simple words.",
   exampleJa:"その難しい医学の用語を、やさしい言葉で説明してください。",
   example2:"The school term ends just before the summer holidays.",
   exampleJa2:"学期は夏休みの直前に終わる。",
   etymologyProcess:"term（境界）→ 意味のはしをきっちり区切った言葉は…？",
   etymologyConclusion:"term（境界）→ 意味の範囲をきっちり区切って決めた言葉＝用語",
   why:"【なぜ】ラテン語 terminus は「境の石」。意味のはしをきっちり区切った言葉が「用語」です。区切られた時間のまとまりが「学期・任期」、決めごとのはしが「条件（terms）」になりました。\n【つながり】terminal（終点）、determine（決める）も同じ家族。「ターミナル駅」は路線の境目のことです。",
   relatedWords:[
     {word:"terminal",meaning:"終点，ターミナル",breakdown:"term（境界）＋ al（形容詞）→ 路線の境目にあたる場所"},
     {word:"determine",meaning:"決める",breakdown:"de（すっかり）＋ term（境界）→ 境をすっかり引いて決める"},
     {word:"terminate",meaning:"終わらせる",breakdown:"term（境界）＋ ate（動詞）→ 境を引いてそこで終わりにする"},
     {synonym:true,word:"word",meaning:"語，言葉",breakdown:"ふつうの言葉。term は分野ごとに意味を決めた言葉を指す"}]},

  {id:924,word:"proverb",partOfSpeech:"名詞",meaning:"ことわざ",
   meanings:["名|ことわざ"],
   pronunciation:"/ˈprɑːvɜːrb/",part:93,
   example:"This old proverb teaches us the value of patience.",
   exampleJa:"この古いことわざは、忍耐の価値を教えてくれる。",
   example2:"My grandfather often uses a proverb about hard work.",
   exampleJa2:"祖父はよく、勤勉についてのことわざを使う。",
   etymologyProcess:"pro（人前で）＋ verb（言葉）→ 昔から言い習わされてきた短い句は…？",
   etymologyConclusion:"pro（人前で）＋ verb（言葉）→ 昔から人前で言い習わされてきた短い言葉＝ことわざ",
   relatedWords:[
     {word:"verb",meaning:"動詞",breakdown:"verb（言葉）→ 文の中心になる「言葉そのもの」"},
     {word:"verbal",meaning:"言葉による",breakdown:"verb（言葉）＋ al（形容詞）→ 言葉を使った"},
     {word:"adverb",meaning:"副詞",breakdown:"ad（〜へ）＋ verb（言葉）→ 動詞にそえて意味を足す言葉"},
     {synonym:true,word:"saying",meaning:"言い習わし",breakdown:"昔から言われる言葉。proverb は教えを含んだ短い決まり文句"}]},

  {id:925,word:"dialect",partOfSpeech:"名詞",meaning:"方言",
   meanings:["名|方言"],
   pronunciation:"/ˈdaɪəlekt/",part:93,
   example:"My grandmother still speaks the local dialect at home.",
   exampleJa:"祖母は家で、いまだに地元の方言を話す。",
   example2:"This dialect uses some words that surprise other Japanese people.",
   exampleJa2:"この方言には、他の地方の日本人を驚かせる言葉がいくつかある。",
   etymologyProcess:"dia（間で）＋ lect（拾う）→ その土地の人どうしだけで通じる言葉は…？",
   etymologyConclusion:"dia（間で）＋ lect（拾う）→ その土地の人どうしの間で拾い交わされる言葉＝方言",
   why:"【なぜ】ギリシャ語 dialektos は dia（間で）＋ legein（話す）。legein はもともと「拾い集める」で、言葉を選び拾って並べることが「話す」になりました。ラテン語 legere（拾う・読む）＝ collect や select の lect は、同じ根から枝分かれした親戚です。\n【つながり】dialogue（間で交わす言葉）、lecture（拾い上げて読み聞かせる）も同じ家族です。",
   relatedWords:[
     {word:"collect",meaning:"集める",breakdown:"col（共に）＋ lect（拾う）→ 一か所へ拾い集める"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離して）＋ lect（拾う）→ より分けて拾い上げる"},
     {word:"dialogue",meaning:"会話",breakdown:"dia（間で）＋ log（言葉）→ 二人の間で交わされる言葉"},
     {word:"lecture",meaning:"講義",breakdown:"lect（拾う）＋ ure（名詞）→ 言葉を拾い上げて読み聞かせること"}]},

  {id:926,word:"fluent",partOfSpeech:"形容詞",meaning:"流暢な，すらすら話す",
   meanings:["形|流暢な，すらすら話す"],
   pronunciation:"/ˈfluːənt/",part:93,
   example:"She is fluent in three languages including Spanish.",
   exampleJa:"彼女はスペイン語を含む3か国語が流暢だ。",
   example2:"After a year abroad his English became quite fluent.",
   exampleJa2:"1年の海外生活の後、彼の英語はかなり流暢になった。",
   etymologyProcess:"flu（流れる）＋ ent（〜している）→ 言葉がつかえず流れ出ていると…？",
   etymologyConclusion:"flu（流れる）＋ ent（〜している）→ 言葉がつかえずすらすら流れ出ている＝流暢な",
   relatedWords:[
     {synonym:true,word:"flow",meaning:"流れる",breakdown:"英語もとからの語。ラテン語の flu とは別系だが、流れるイメージは同じ"},
     {word:"influence",meaning:"影響",breakdown:"in（中へ）＋ flu（流れる）→ 中へ流れ込んで働きかける力"},
     {word:"fluid",meaning:"流体；なめらかな",breakdown:"flu（流れる）＋ id（〜な状態の）→ 流れる状態のもの"},
     {word:"flu",meaning:"インフルエンザ",breakdown:"flu（流れる）→ 星の力が流れ込んで起こると考えられた病"}]},

  {id:927,word:"translate",partOfSpeech:"他動詞",meaning:"翻訳する",
   meanings:["他|翻訳する，訳す"],
   pronunciation:"/trænsˈleɪt/",part:93,
   example:"Can you translate this short letter into English?",
   exampleJa:"この短い手紙を英語に翻訳してくれますか。",
   example2:"Her novel was translated into more than ten languages.",
   exampleJa2:"彼女の小説は10以上の言語に翻訳された。",
   etymologyProcess:"trans（越えて）＋ lat（運ぶ）→ 意味を言語の境を越えて運ぶと…？",
   etymologyConclusion:"trans（越えて）＋ lat（運ぶ）→ 意味を言語の境を越えて向こうへ運び移す＝翻訳する",
   relatedWords:[
     {word:"relate",meaning:"関係づける",breakdown:"re（後ろへ）＋ lat（運ぶ）→ 元へ運び戻して結びつける"},
     {word:"relative",meaning:"親類；相対的な",breakdown:"re（後ろへ）＋ lat（運ぶ）＋ ive（形容詞）→ 互いに結びついている"},
     {word:"translation",meaning:"翻訳",breakdown:"trans（越えて）＋ lat（運ぶ）＋ ion（名詞）→ 境を越えて運び移すこと"},
     {word:"transfer",meaning:"移す；乗り換える",breakdown:"trans（越えて）＋ fer（運ぶ）→ 境を越えて向こうへ運ぶ"}]},

  {id:928,word:"define",partOfSpeech:"他動詞",meaning:"定義する",
   meanings:["他|定義する，意味をはっきり決める"],
   pronunciation:"/dɪˈfaɪn/",part:93,
   example:"Please define this word in your own simple words.",
   exampleJa:"この語を、自分のやさしい言葉で定義してください。",
   example2:"The rules clearly define what students may bring inside.",
   exampleJa2:"その規則は、生徒が何を持ち込んでよいかをはっきり定義している。",
   etymologyProcess:"de（すっかり）＋ fin（終わり）→ 意味のはしをすっかり区切ると…？",
   etymologyConclusion:"de（すっかり）＋ fin（終わり）→ 意味のはしをすっかり区切ってはっきりさせる＝定義する",
   relatedWords:[
     {word:"final",meaning:"最後の",breakdown:"fin（終わり）＋ al（形容詞）→ 終わりにあたる"},
     {word:"finish",meaning:"終える",breakdown:"fin（終わり）＋ ish（〜にする）→ 終わりの状態にする"},
     {word:"definite",meaning:"明確な",breakdown:"de（すっかり）＋ fin（終わり）＋ ite（〜された）→ はしまで区切られた"},
     {word:"infinite",meaning:"無限の",breakdown:"in（否定）＋ fin（終わり）→ 終わりというものが来ない"}]},

  {id:929,word:"interpret",partOfSpeech:"他動詞",meaning:"解釈する；通訳する",
   meanings:["他|解釈する","他|通訳する"],
   pronunciation:"/ɪnˈtɜːrprət/",part:93,
   example:"Different people interpret this old poem in different ways.",
   exampleJa:"人によって、この古い詩をさまざまに解釈する。",
   example2:"She interpreted for the visitors from France last week.",
   exampleJa2:"彼女は先週、フランスからの訪問者のために通訳した。",
   etymologyProcess:"inter（間の）＋ pret（取り次ぐ）→ 二者の間に立って意味を伝えると…？",
   etymologyConclusion:"inter（間の）＋ pret（取り次ぐ）→ 二者の間に立って意味を取り次いで伝える＝解釈する",
   why:"【なぜ】ラテン語 interpres は「二者の間に立つ人＝仲立ち」。inter は「間の」ですが、後半 -pres の由来ははっきりしていません。そこから「間に立って意味を渡す」＝通訳する・解釈する になりました。\n【つながり】interpreter（通訳者）、interpretation（解釈）が同じ家族です。",
   relatedWords:[
     {word:"interpreter",meaning:"通訳者",breakdown:"inter（間の）＋ pret（取り次ぐ）＋ er（人）→ 間に立って言葉を渡す人"},
     {word:"interpretation",meaning:"解釈",breakdown:"inter（間の）＋ pret（取り次ぐ）＋ ation（名詞）→ 意味を取り次ぐこと"},
     {synonym:true,word:"translate",meaning:"翻訳する",breakdown:"文章を別の言語に移す。interpret は話し言葉をその場で渡す"},
     {synonym:true,word:"explain",meaning:"説明する",breakdown:"分かるように解き明かす。interpret は意味をどう取るかを示す"}]},

  {id:930,word:"quote",partOfSpeech:"他動詞",meaning:"引用する",
   meanings:["他|引用する","名|引用（文）"],
   pronunciation:"/kwoʊt/",part:93,
   example:"He often quotes his favorite writer in his essays.",
   exampleJa:"彼はよく、小論文で好きな作家を引用する。",
   example2:"She quoted one line from that poem in her speech.",
   exampleJa2:"彼女はスピーチで、その詩から一行を引用した。",
   etymologyProcess:"quot（いくつ）→ 何番目かの箇所に印をつけて抜き出すと…？",
   etymologyConclusion:"quot（いくつ）→ 何番目かの箇所に印をつけ、そこを抜き出して示す＝引用する",
   why:"【なぜ】ラテン語 quot は「いくつ」。中世の写本では、章や節に番号をふって印をつける作業を quotare と言いました。印をつけた箇所を抜き出して見せることから「引用する」になりました。\n【つながり】quota（割り当て数）、quotient（割り算の商）も同じ「いくつ」の家族です。",
   relatedWords:[
     {word:"quota",meaning:"割り当て",breakdown:"quot（いくつ）→ いくつ分と決められた取り分"},
     {word:"quotation",meaning:"引用（文）",breakdown:"quot（いくつ）＋ ation（名詞）→ 印をつけて抜き出した言葉"},
     {synonym:true,word:"cite",meaning:"引用する",breakdown:"根拠として挙げる堅い語。quote は言葉をそのまま写して示す"},
     {synonym:true,word:"mention",meaning:"言及する",breakdown:"話に出すこと。quote は原文をそのまま持ってくる"}]},

  {id:931,word:"literally",partOfSpeech:"副詞",meaning:"文字どおりに",
   meanings:["副|文字どおりに","副|（強調して）まったく"],
   pronunciation:"/ˈlɪtərəli/",part:94,
   example:"Do not translate this English idiom literally into Japanese.",
   exampleJa:"この英語の慣用句を、文字どおりに日本語へ訳してはいけない。",
   example2:"She was literally shaking with cold after the long swim.",
   exampleJa2:"長く泳いだ後、彼女はまったく寒さで震えていた。",
   etymologyProcess:"liter（文字）＋ ly（副詞）→ たとえではなく書かれたとおりなら…？",
   etymologyConclusion:"liter（文字）＋ ly（副詞）→ たとえではなく、書かれた文字のとおりに＝文字どおりに",
   relatedWords:[
     {word:"letter",meaning:"文字；手紙",breakdown:"liter（文字）→ 一つ一つの文字。並べて送れば手紙になる"},
     {word:"literal",meaning:"文字どおりの",breakdown:"liter（文字）＋ al（形容詞）→ 書かれた文字そのままの"},
     {word:"literature",meaning:"文学",breakdown:"liter（文字）＋ ature（名詞）→ 文字で書き残された作品"},
     {word:"literacy",meaning:"読み書きの力",breakdown:"liter（文字）＋ cy（名詞）→ 文字を読み書きできる力"}]},

  {id:932,word:"indicate",partOfSpeech:"他動詞",meaning:"示す，指し示す",
   meanings:["他|示す，指し示す","他|（that SV）～だと示す"],
   pronunciation:"/ˈɪndɪkeɪt/",part:94,
   example:"These numbers indicate a steady rise in world temperature.",
   exampleJa:"これらの数字は、世界の気温の着実な上昇を示している。",
   example2:"The survey indicated that most students want longer breaks.",
   exampleJa2:"その調査は、ほとんどの生徒がより長い休みを望んでいることを示した。",
   etymologyProcess:"in（〜に）＋ dic（言う）→ これだと指さして言い当てると…？",
   etymologyConclusion:"in（〜に）＋ dic（言う）→ これだと指さして言い当てて見せる＝示す",
   relatedWords:[
     {word:"dictionary",meaning:"辞書",breakdown:"dict（言う）＋ ary（集まり）→ 言葉の言い方を集めたもの"},
     {word:"predict",meaning:"予言する",breakdown:"pre（先に）＋ dict（言う）→ 起こる前に先に言う"},
     {word:"dedicate",meaning:"捧げる",breakdown:"de（すっかり）＋ dic（言う）→ これはあなたにと言い切る"},
     {word:"indication",meaning:"しるし，兆候",breakdown:"in（〜に）＋ dic（言う）＋ ation（名詞）→ 指し示しているしるし"}]},

  {id:933,word:"reveal",partOfSpeech:"他動詞",meaning:"明らかにする，見せる",
   meanings:["他|（隠れていたもの）を明らかにする，見せる"],
   pronunciation:"/rɪˈviːl/",part:94,
   example:"The company will reveal its new product next month.",
   exampleJa:"その会社は来月、新製品を明らかにする。",
   example2:"Her tired face revealed how hard she had worked.",
   exampleJa2:"彼女の疲れた顔が、どれほど懸命に働いたかを明らかにしていた。",
   etymologyProcess:"re（元へ）＋ veal（覆い）→ かぶせた覆いを取り去ると…？",
   etymologyConclusion:"re（元へ）＋ veal（覆い）→ かぶせてあった覆いを取り去って中を見せる＝明らかにする",
   relatedWords:[
     {word:"veil",meaning:"ベール，覆い",breakdown:"veal（覆い）→ 顔や物にかぶせて隠す薄い布"},
     {word:"revelation",meaning:"暴露；啓示",breakdown:"re（元へ）＋ veal（覆い）＋ ation（名詞）→ 覆いを取って見せること"},
     {synonym:true,word:"uncover",meaning:"明らかにする",breakdown:"ふたを取ること。reveal は隠していた事実そのものを見せる"},
     {synonym:true,word:"expose",meaning:"さらす",breakdown:"外にさらけ出すこと。reveal は覆いを取って中身を見せる"}]},

  {id:934,word:"announce",partOfSpeech:"他動詞",meaning:"発表する",
   meanings:["他|発表する，告知する"],
   pronunciation:"/əˈnaʊns/",part:94,
   example:"The school will announce the results on Friday morning.",
   exampleJa:"学校は金曜の朝に結果を発表する。",
   example2:"They announced their wedding date at the family dinner.",
   exampleJa2:"彼らは家族の夕食の席で、結婚の日取りを発表した。",
   etymologyProcess:"ad（〜へ）＋ nounce（告げる）→ 多くの人へ正式に告げ知らせると…？",
   etymologyConclusion:"ad（〜へ）＋ nounce（告げる）→ 多くの人へ向けて正式に告げ知らせる＝発表する",
   relatedWords:[
     {word:"pronounce",meaning:"発音する；宣言する",breakdown:"pro（人前で）＋ nounce（告げる）→ 人前ではっきり口に出す"},
     {word:"announcement",meaning:"発表，お知らせ",breakdown:"ad（〜へ）＋ nounce（告げる）＋ ment（名詞）→ 告げ知らせる中身"},
     {word:"denounce",meaning:"公然と非難する",breakdown:"de（下へ）＋ nounce（告げる）→ 相手を下に見て言い立てる"},
     {synonym:true,word:"declare",meaning:"宣言する",breakdown:"はっきり言い切ること。announce は知らせとして広く伝える"}]},

  {id:935,word:"broadcast",partOfSpeech:"他動詞",meaning:"放送する",
   meanings:["他|放送する","名|放送"],
   pronunciation:"/ˈbrɔːdkæst/",part:94,
   example:"They broadcast the baseball game live every single summer.",
   exampleJa:"彼らは毎年夏、その野球の試合を生で放送する。",
   example2:"The news was broadcast to the whole country immediately.",
   exampleJa2:"そのニュースはすぐに国全体に放送された。",
   etymologyProcess:"broad（広い）＋ cast（投げる）→ 種をまくように広くばらまくと…？",
   etymologyConclusion:"broad（広い）＋ cast（投げる）→ 種をまくように広くばらまいて届ける＝放送する",
   why:"【なぜ】もとは農業の言葉で、「種を広くばらまく」ことでした。20世紀に無線が生まれ、電波を四方へまき散らす様子がこれに似ているとされて「放送する」に使われるようになりました。\n【つながり】cast は「投げる」。forecast（先へ投げる＝予報）、podcast（ネット配信）も同じ家族です。",
   relatedWords:[
     {word:"broad",meaning:"広い",breakdown:"broad（広い）→ 端から端までの幅が大きい"},
     {word:"cast",meaning:"投げる；配役",breakdown:"cast（投げる）→ 勢いをつけて放り投げる"},
     {word:"forecast",meaning:"予報",breakdown:"fore（前に）＋ cast（投げる）→ 先へ考えを投げて言い当てる"},
     {word:"abroad",meaning:"海外へ",breakdown:"broad（広い）→ 広い世界のほうへ出ていく"}]},

  {id:936,word:"prove",partOfSpeech:"他動詞",meaning:"証明する",
   meanings:["他|証明する","自|（to be ～で）～だと分かる"],
   pronunciation:"/pruːv/",part:94,
   example:"You must prove your answer with a clear example.",
   exampleJa:"はっきりした例で、自分の答えを証明しなければならない。",
   example2:"New evidence proved that he was not the thief.",
   exampleJa2:"新しい証拠が、彼が泥棒ではないことを証明した。",
   etymologyProcess:"prove（試す）→ 実際に試して正しいと認めさせると…？",
   etymologyConclusion:"prove（試す）→ 実際に試してみせて、正しいと認めさせる＝証明する",
   relatedWords:[
     {word:"proof",meaning:"証拠",breakdown:"proof（試す）→ 試して確かめられた証し"},
     {word:"approve",meaning:"承認する",breakdown:"ad（〜へ）＋ prove（試す）→ 試してみてよしと認める"},
     {word:"probable",meaning:"ありそうな",breakdown:"prob（試す）＋ able（できる）→ 試せば本当だと出そうな"},
     {word:"probe",meaning:"探る；探査機",breakdown:"prob（試す）→ 突いて中を試し探るもの"}]},

  {id:937,word:"advertise",partOfSpeech:"他動詞",meaning:"宣伝する",
   meanings:["他|宣伝する，広告する"],
   pronunciation:"/ˈædvərtaɪz/",part:94,
   example:"They advertise the new game on many popular websites.",
   exampleJa:"彼らは多くの人気サイトで、その新しいゲームを宣伝する。",
   example2:"Our club advertised the concert with bright colorful posters.",
   exampleJa2:"私たちの部活は、明るく色鮮やかなポスターでコンサートを宣伝した。",
   etymologyProcess:"ad（〜へ）＋ vert（回る）→ 人の心をこちらへ振り向かせると…？",
   etymologyConclusion:"ad（〜へ）＋ vert（回る）→ 人の心をこちらへぐるりと振り向かせる＝宣伝する",
   relatedWords:[
     {word:"advertisement",meaning:"広告",breakdown:"ad（〜へ）＋ vert（回る）＋ ment（名詞）→ 心を振り向かせる知らせ"},
     {word:"convert",meaning:"変える",breakdown:"con（すっかり）＋ vert（回る）→ すっかり向きを変えてしまう"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ 向きを後ろへぐるりと回す"},
     {word:"version",meaning:"版；解釈",breakdown:"vers（回る）＋ ion（名詞）→ 向きを変えて言い直したもの"}]},

  {id:938,word:"clarify",partOfSpeech:"他動詞",meaning:"はっきりさせる",
   meanings:["他|はっきりさせる，明確にする"],
   pronunciation:"/ˈklærəfaɪ/",part:94,
   example:"Could you clarify the rules for the club tournament?",
   exampleJa:"部の大会の規則をはっきりさせてもらえますか。",
   example2:"The teacher clarified what the homework really required.",
   exampleJa2:"先生は、宿題が本当に何を求めているのかをはっきりさせた。",
   etymologyProcess:"clar（澄んだ）＋ fy（する）→ にごっていた話を澄ませると…？",
   etymologyConclusion:"clar（澄んだ）＋ fy（する）→ にごっていた話を澄ませて見通せるようにする＝はっきりさせる",
   relatedWords:[
     {word:"clear",meaning:"はっきりした，澄んだ",breakdown:"clar（澄んだ）→ にごりがなく向こうまで見通せる"},
     {word:"clarity",meaning:"明快さ",breakdown:"clar（澄んだ）＋ ity（名詞）→ 澄んでいてよく分かること"},
     {word:"declare",meaning:"宣言する",breakdown:"de（すっかり）＋ clar（澄んだ）→ すっかり澄ませてはっきり言う"},
     {synonym:true,word:"explain",meaning:"説明する",breakdown:"分かるように解き明かす。clarify はあいまいな点をはっきりさせる"}]},

  {id:939,word:"seek",partOfSpeech:"他動詞",meaning:"探し求める",
   meanings:["他|探し求める","他|（助言など）を求める"],
   pronunciation:"/siːk/",part:94,
   example:"Many young people seek advice about their future careers.",
   exampleJa:"多くの若者が、将来の仕事について助言を探し求める。",
   example2:"She sought help from her teacher before the difficult exam.",
   exampleJa2:"彼女はその難しい試験の前に、先生に助けを求めた。",
   etymologyProcess:"seek（探す）→ 手に入れようと心を向けて探し回ると…？",
   etymologyConclusion:"seek（探す）→ 手に入れようと心を向けて、あちこち探し回る＝探し求める",
   hook:"seek advice / seek help の形で覚える。過去形は sought（不規則）。",
   relatedWords:[
     {synonym:true,word:"search",meaning:"探す",breakdown:"すみずみまで調べて回ること。seek は手に入れたくて求めに行く"},
     {word:"seeker",meaning:"探し求める人",breakdown:"seek（探す）＋ er（人）→ 何かを探し求めている人"},
     {synonym:true,word:"pursue",meaning:"追い求める",breakdown:"後を追いかけること。seek は手に入れようと探し回ること"},
     {synonym:true,word:"request",meaning:"依頼する",breakdown:"人に頼むこと。seek は自分から探して求めに行くこと"}]},

  {id:940,word:"entertain",partOfSpeech:"他動詞",meaning:"楽しませる，もてなす",
   meanings:["他|楽しませる，もてなす"],
   pronunciation:"/ˌentərˈteɪn/",part:94,
   example:"The clown entertained the children for a whole hour.",
   exampleJa:"道化師は子どもたちを1時間まるまる楽しませた。",
   example2:"Good music can entertain people of every age.",
   exampleJa2:"よい音楽は、あらゆる年齢の人を楽しませることができる。",
   etymologyProcess:"inter（間の）＋ tain（保つ）→ 相手をそばに引き止めておくと…？",
   etymologyConclusion:"inter（間の）＋ tain（保つ）→ 相手を自分のそばに引き止めて飽きさせない＝楽しませる",
   why:"【なぜ】フランス語 entretenir は「間に保つ＝そばに引き止めておく」。客を引き止めてもてなすことから「もてなす」、さらに「楽しませる」へ広がりました。\n【つながり】contain（中に保つ）、obtain（手に保つ）も tain の家族。エンターテインメントは「人を引き止めておく力」のことです。",
   relatedWords:[
     {word:"entertainment",meaning:"娯楽",breakdown:"inter（間の）＋ tain（保つ）＋ ment（名詞）→ 人を引き止めておく楽しみ"},
     {word:"contain",meaning:"含む",breakdown:"con（すっかり）＋ tain（保つ）→ 中にすっかり保っている"},
     {word:"obtain",meaning:"手に入れる",breakdown:"ob（〜に向かって）＋ tain（保つ）→ 手を伸ばして自分の手に保つ"},
     {synonym:true,word:"amuse",meaning:"楽しませる",breakdown:"笑わせて面白がらせる。entertain は場をもたせてもてなすこと"}]},

  {id:941,word:"amuse",partOfSpeech:"他動詞",meaning:"（笑わせて）楽しませる",
   meanings:["他|（笑わせて）楽しませる，面白がらせる"],
   pronunciation:"/əˈmjuːz/",part:95,
   example:"His funny story amused everyone in the small classroom.",
   exampleJa:"彼のおかしな話は、小さな教室のみんなを楽しませた。",
   example2:"The children were amused by the little dog's clever tricks.",
   exampleJa2:"子どもたちは、その小犬の賢い芸を面白がった。",
   etymologyProcess:"muse（ぼんやり見とれる）→ 相手を見とれさせて時を忘れさせると…？",
   etymologyConclusion:"muse（ぼんやり見とれる）→ 相手をぽかんと見とれさせて時を忘れさせる＝楽しませる",
   relatedWords:[
     {word:"amusement",meaning:"娯楽，おかしさ",breakdown:"muse（ぼんやり見とれる）＋ ment（名詞）→ 時を忘れる楽しみ"},
     {word:"muse",meaning:"物思いにふける",breakdown:"muse（ぼんやり見とれる）→ ぼんやりと考えにふける"},
     {synonym:true,word:"entertain",meaning:"楽しませる",breakdown:"場をもたせてもてなすこと。amuse は笑わせて面白がらせる"},
     {synonym:true,word:"funny",meaning:"おかしい",breakdown:"笑いを誘うようす。amuse はその笑いを引き起こすほうを言う"}]},

  {id:942,word:"attract",partOfSpeech:"他動詞",meaning:"引きつける",
   meanings:["他|引きつける，引き寄せる"],
   pronunciation:"/əˈtrækt/",part:95,
   example:"Bright flowers attract many bees in early summer.",
   exampleJa:"明るい色の花は、初夏に多くのハチを引きつける。",
   example2:"The new museum attracted thousands of visitors last month.",
   exampleJa2:"新しい博物館は先月、何千人もの訪問者を引きつけた。",
   etymologyProcess:"ad（〜へ）＋ tract（引く）→ 自分のほうへぐっと引き寄せると…？",
   etymologyConclusion:"ad（〜へ）＋ tract（引く）→ 自分のほうへぐっと引き寄せてしまう＝引きつける",
   relatedWords:[
     {word:"tractor",meaning:"トラクター",breakdown:"tract（引く）＋ or（もの）→ 重い機械を引っぱる車"},
     {word:"attractive",meaning:"魅力的な",breakdown:"ad（〜へ）＋ tract（引く）＋ ive（形容詞）→ 人の心を引き寄せる"},
     {word:"extract",meaning:"取り出す",breakdown:"ex（外へ）＋ tract（引く）→ 外へ引っぱり出す"},
     {word:"contract",meaning:"契約；縮む",breakdown:"con（共に）＋ tract（引く）→ 互いを引き寄せて結ぶ"}]},

  {id:943,word:"fascinate",partOfSpeech:"他動詞",meaning:"魅了する",
   meanings:["他|魅了する，心を奪う"],
   pronunciation:"/ˈfæsɪneɪt/",part:95,
   example:"Space travel fascinates many junior high school students.",
   exampleJa:"宇宙旅行は、多くの中学生を魅了する。",
   example2:"The audience was fascinated by her beautiful violin playing.",
   exampleJa2:"聴衆は彼女の美しいバイオリンの演奏に魅了された。",
   etymologyProcess:"fascin（まじない）＋ ate（動詞）→ まじないのように心を釘づけにすると…？",
   etymologyConclusion:"fascin（まじない）＋ ate（動詞）→ まじないをかけたように心を釘づけにする＝魅了する",
   relatedWords:[
     {word:"fascinating",meaning:"とても面白い",breakdown:"fascin（まじない）＋ ing（〜している）→ 心を引きつけてやまない"},
     {word:"fascination",meaning:"魅力，心酔",breakdown:"fascin（まじない）＋ ation（名詞）→ 心を釘づけにする力"},
     {synonym:true,word:"attract",meaning:"引きつける",breakdown:"引き寄せること。fascinate は動けなくなるほど強く心を奪う"},
     {synonym:true,word:"charm",meaning:"魅了する",breakdown:"もとは呪文。fascinate と同じく、まじないの力から生まれた語"}]},

  {id:944,word:"absorb",partOfSpeech:"他動詞",meaning:"吸収する",
   meanings:["他|吸収する","他|（be absorbed in で）没頭する"],
   pronunciation:"/əbˈzɔːrb/",part:95,
   example:"Dry towels absorb water much faster than wet ones.",
   exampleJa:"乾いたタオルは、濡れたものよりずっと速く水を吸収する。",
   example2:"He was completely absorbed in the long mystery novel.",
   exampleJa2:"彼はその長い推理小説に完全に没頭していた。",
   etymologyProcess:"ab（離れて）＋ sorb（吸う）→ 吸い取って自分の中へ取り込むと…？",
   etymologyConclusion:"ab（離れて）＋ sorb（吸う）→ 相手から吸い取って自分の中へ取り込む＝吸収する",
   relatedWords:[
     {word:"absorption",meaning:"吸収",breakdown:"ab（離れて）＋ sorb（吸う）＋ ion（名詞）→ 吸い取って取り込むこと"},
     {word:"absorbent",meaning:"吸収性の",breakdown:"ab（離れて）＋ sorb（吸う）＋ ent（〜している）→ よく吸い取る性質の"},
     {synonym:true,word:"soak",meaning:"ひたす",breakdown:"液にひたすこと。absorb は中へ吸い込んで取り込むこと"},
     {synonym:true,word:"suck",meaning:"吸う",breakdown:"口で吸い込むこと。absorb はしみ込ませて取り込むこと"}]},

  {id:945,word:"fond",partOfSpeech:"形容詞",meaning:"（of ～で）～が好きで",
   meanings:["形|（of ～で）～が好きで，～を好んで"],
   pronunciation:"/fɑːnd/",part:95,
   example:"My little sister is very fond of small animals.",
   exampleJa:"妹は小さな動物がとても好きだ。",
   example2:"He grew fond of this quiet town over the years.",
   exampleJa2:"彼は年月がたつうちに、この静かな町が好きになった。",
   etymologyProcess:"fon（愚か）＋ ed（〜された）→ ばかみたいに我を忘れて心を寄せると…？",
   etymologyConclusion:"fon（愚か）＋ ed（〜された）→ ばかみたいに我を忘れて心を寄せている＝～が好きで",
   why:"【なぜ】もとは fonned「ばかげた」。中英語の fon は「愚か者」で、「愚かなほど夢中になっている」が出発点でした。そこから悪い意味が薄れ、「〜が大好きだ」というあたたかい語になりました。\n【つながり】fond hope（はかない望み）には、今も「甘い・はかない」という昔の色が残っています。be fond of ～ の形で使うのが決まりです。",
   relatedWords:[
     {synonym:true,word:"like",meaning:"好む",breakdown:"ふつうに好きなこと。fond は of を伴い、情のこもった好きを表す"},
     {word:"fondness",meaning:"愛着，好み",breakdown:"fon（愚か）＋ ness（名詞）→ 我を忘れるほど好きだという気持ち"},
     {synonym:true,word:"keen",meaning:"熱心な",breakdown:"強い興味があること。fond は長く続くあたたかい好意を表す"},
     {synonym:true,word:"affection",meaning:"愛情",breakdown:"あたたかい好意。fond はその気持ちを持っている状態を表す"}]},

  {id:946,word:"scare",partOfSpeech:"他動詞",meaning:"おびえさせる",
   meanings:["他|おびえさせる，怖がらせる"],
   pronunciation:"/sker/",part:95,
   example:"Loud fireworks scare my dog every summer night.",
   exampleJa:"大きな花火は、毎年夏の夜にうちの犬をおびえさせる。",
   example2:"The sudden noise scared the birds away from the tree.",
   exampleJa2:"突然の物音が鳥たちをおびえさせ、木から追い払った。",
   etymologyProcess:"scare（びくっとさせる）→ 突然びくっとさせて怖がらせると…？",
   etymologyConclusion:"scare（びくっとさせる）→ 突然びくっとさせて身をすくませる＝おびえさせる",
   hook:"「スケアリー（scary＝こわい）」でおなじみ。突然びくっとさせる怖さ。",
   relatedWords:[
     {word:"scary",meaning:"こわい",breakdown:"scare（びくっとさせる）＋ y（形容詞）→ びくっとさせるような"},
     {word:"scared",meaning:"おびえた",breakdown:"scare（びくっとさせる）＋ ed（〜された）→ びくっとさせられた状態"},
     {synonym:true,word:"frighten",meaning:"こわがらせる",breakdown:"恐れを起こさせること。scare は突然びくっとさせる感じが強い"},
     {synonym:true,word:"terrify",meaning:"ぞっとさせる",breakdown:"terr（恐れさせる）の家族。scare よりずっと強い恐怖を与える"}]},

  {id:947,word:"alarm",partOfSpeech:"他動詞",meaning:"ぎょっとさせる；警報",
   meanings:["他|ぎょっとさせる，不安にさせる","名|警報，目覚まし"],
   pronunciation:"/əˈlɑːrm/",part:95,
   example:"The sudden news alarmed everyone in the small village.",
   exampleJa:"その突然の知らせは、小さな村のみんなをぎょっとさせた。",
   example2:"A fire alarm rang loudly during the math class.",
   exampleJa2:"数学の授業中に、火災警報が大きく鳴った。",
   etymologyProcess:"arm（武器）→ 「武器を取れ」と危険を告げると…？",
   etymologyConclusion:"arm（武器）→ 「武器を取れ」の叫びで危険を告げ、身構えさせる＝ぎょっとさせる",
   why:"【なぜ】イタリア語の all'arme!「武器を取れ！」という叫びが、そのまま一語の名詞になりました。敵が来たと知らせる声だったので「警報」、さらに「人をぎょっとさせる」という動詞になりました。\n【つながり】目覚まし時計の「アラーム」も火災報知器の「警報」も同じ語。army（軍隊）、armor（よろい）も arm の家族です。",
   relatedWords:[
     {word:"army",meaning:"軍隊",breakdown:"arm（武器）＋ y（集まり）→ 武器を持つ人の集まり"},
     {word:"armor",meaning:"よろい",breakdown:"arm（武器）＋ or（もの）→ 身を守るために着る装備"},
     {word:"alarming",meaning:"驚くべき，不安な",breakdown:"arm（武器）＋ ing（〜している）→ 思わず身構えさせるような"},
     {synonym:true,word:"warn",meaning:"警告する",breakdown:"前もって知らせること。alarm は知らせて身構えさせるところまで言う"}]},

  {id:948,word:"amaze",partOfSpeech:"他動詞",meaning:"びっくりさせる",
   meanings:["他|びっくりさせる，感嘆させる"],
   pronunciation:"/əˈmeɪz/",part:95,
   example:"Her quick answer amazed the whole science class.",
   exampleJa:"彼女の素早い答えは、理科のクラス全体をびっくりさせた。",
   example2:"We were amazed by the size of the old tree.",
   exampleJa2:"私たちはその古い木の大きさにびっくりさせられた。",
   etymologyProcess:"maze（迷わせる）→ 頭が迷路に入ったようにさせると…？",
   etymologyConclusion:"maze（迷わせる）→ 頭が迷路に入ったようにぽかんとさせる＝びっくりさせる",
   relatedWords:[
     {word:"maze",meaning:"迷路",breakdown:"maze（迷わせる）→ 入ると進む道が分からなくなる造り"},
     {word:"amazing",meaning:"驚くべき，すばらしい",breakdown:"maze（迷わせる）＋ ing（〜している）→ 頭がぽかんとなるほどの"},
     {word:"amazement",meaning:"驚き",breakdown:"maze（迷わせる）＋ ment（名詞）→ 頭がぽかんとなる気持ち"},
     {synonym:true,word:"astonish",meaning:"ひどく驚かせる",breakdown:"雷に打たれたように驚かせる。amaze は感心を伴う驚き"}]},

  {id:949,word:"irritate",partOfSpeech:"他動詞",meaning:"（くり返し）いらだたせる",
   meanings:["他|（くり返す刺激で）いらだたせる","他|（皮膚・のど）を刺激する"],
   pronunciation:"/ˈɪrɪteɪt/",part:95,
   example:"The constant noise irritated everyone in the quiet library.",
   exampleJa:"絶え間ない物音が、静かな図書館のみんなをいらいらさせた。",
   example2:"Very dry air can irritate your throat in winter.",
   exampleJa2:"とても乾いた空気は、冬にのどを刺激することがある。",
   etymologyProcess:"irrit（いらだたせる）＋ ate（動詞）→ 小さな刺激をくり返すと…？",
   etymologyConclusion:"irrit（いらだたせる）＋ ate（動詞）→ 小さな刺激をくり返して気持ちをささくれ立たせる＝いらだたせる",
   relatedWords:[
     {word:"irritating",meaning:"いらいらさせる",breakdown:"irrit（いらだたせる）＋ ing（〜している）→ 神経を逆なでしてくる"},
     {word:"irritation",meaning:"いらだち；炎症",breakdown:"irrit（いらだたせる）＋ ation（名詞）→ ささくれ立った状態"},
     {synonym:true,word:"annoy",meaning:"いらだたせる",breakdown:"うるさがらせること。irritate は続く刺激で神経を逆なでする"},
     {synonym:true,word:"disturb",meaning:"かき乱す",breakdown:"静けさを乱すこと。irritate は小さな怒りをためさせる"}]},

  {id:950,word:"upset",partOfSpeech:"他動詞",meaning:"動揺させる",
   meanings:["他|動揺させる，うろたえさせる","形|動揺して","他|ひっくり返す"],
   pronunciation:"/ʌpˈset/",part:95,
   example:"The sad news upset her for several long days.",
   exampleJa:"その悲しい知らせは、何日もの間ずっと彼女を動揺させた。",
   example2:"Do not upset your little brother before the school trip.",
   exampleJa2:"修学旅行の前に、弟を動揺させないでください。",
   etymologyProcess:"up（上へ）＋ set（置く）→ 上下をひっくり返してしまうと…？",
   etymologyConclusion:"up（上へ）＋ set（置く）→ 上下をひっくり返して置き、落ち着きを失わせる＝動揺させる",
   why:"【なぜ】もとは「set up＝立てる」の意味でした。14〜15世紀に「持ち上げて逆さにする＝ひっくり返す」へ移り、さらに「心をひっくり返す＝動揺させる」になりました。\n【つながり】スポーツで番狂わせを an upset と言うのも「順位をひっくり返す」から。sunset（太陽が下りて据わる）も set の家族です。",
   relatedWords:[
     {word:"set",meaning:"置く，据える",breakdown:"set（置く）→ 物をしかるべきところに据える"},
     {word:"sunset",meaning:"日の入り",breakdown:"sun（太陽）＋ set（置く）→ 太陽が地平線に下りて据わる"},
     {word:"settle",meaning:"落ち着かせる；解決する",breakdown:"set（置く）→ しかるべき所に据えて落ち着かせる"},
     {synonym:true,word:"disturb",meaning:"かき乱す",breakdown:"静けさを乱すこと。upset は心をひっくり返して動揺させる"}]},
