  {id:2251,word:"sober",partOfSpeech:"形容詞",meaning:"しらふの，酒に酔っていない；まじめな，冷静な",
   meanings:["形|しらふの，酒に酔っていない","形|まじめな，冷静な","形|（色・服装が）地味な"],
   pronunciation:"/ˈsoʊbər/",part:226,
   example:"He had been drinking, so he was not sober enough to drive.",
   exampleJa:"彼は酒を飲んでいたので、運転できるほどしらふではなかった。",
   example2:"After the loss, the coach gave us a sober talk about our weaknesses.",
   exampleJa2:"敗戦のあと、監督は私たちの弱点について冷静な話をした。",
   etymologyProcess:"sobri（酒の気がない）→ お酒が入っていない頭の状態は…？",
   etymologyConclusion:"sobri（酒の気がない）→ お酒が入らず、頭がはっきりしている＝しらふの",
   etymologyMore:["酔わずに頭がさえている→まじめな，冷静な"],
   hook:"sober up で「酔いがさめる」。飲んでいない＝浮かれていない、と覚える。",
   relatedWords:[
     {word:"sobriety",meaning:"しらふ；節度",breakdown:"sobri（酒の気がない）＋ ety（名詞）→ 酒にのまれず節度を保つ状態"},
     {synonym:true,word:"calm",meaning:"落ち着いた",breakdown:"気持ちが静かなこと全般。sober は浮かれずにまじめ"},
     {synonym:true,word:"serious",meaning:"まじめな；深刻な",breakdown:"ふざけていないこと。sober は冷静さも含む"},
     {synonym:true,word:"sensible",meaning:"分別のある",breakdown:"判断が理にかなっていること。sober は落ち着いた態度"}]},

  {id:2252,word:"obstinate",partOfSpeech:"形容詞",meaning:"（説得に応じず）強情な，頑固な；（病気・汚れが）しつこい",
   meanings:["形|（説得に応じず）強情な，頑固な","形|（病気・汚れが）しつこい，治りにくい"],
   pronunciation:"/ˈɑːbstɪnət/",part:226,
   example:"My obstinate brother refused to admit that he was wrong.",
   exampleJa:"強情な兄は、自分が間違っていることを認めようとしなかった。",
   example2:"The captain was obstinate about keeping the old training plan.",
   exampleJa2:"キャプテンは古い練習計画を守ることについて強情だった。",
   etymologyProcess:"ob（向かい合って）＋ stin（決める）→ 相手に向かって心を固めると…？",
   etymologyConclusion:"ob（向かい合って）＋ stin（決める）→ 何を言われても決めたことを曲げず向き合う＝（説得に応じず）強情な",
   etymologyMore:["居すわって動かない→（病気・汚れが）しつこい，治りにくい"],
   relatedWords:[
     {word:"destination",meaning:"目的地",breakdown:"de（すっかり）＋ stin（決める）＋ ation（名詞）→ 行き先と決めた場所"},
     {word:"destiny",meaning:"運命",breakdown:"de（すっかり）＋ stin（決める）→ 前もって固く決められた行く末"},
     {synonym:true,word:"stubborn",meaning:"頑固な",breakdown:"日常的な「頑固な」。obstinate は理屈を聞かない硬さが強い"},
     {synonym:true,word:"persistent",meaning:"粘り強い；しつこい",breakdown:"よい意味にも使う。obstinate はほぼ悪い意味"}]},

  {id:2253,word:"solitary",partOfSpeech:"形容詞",meaning:"ひとりきりの，孤独な；人里離れた",
   meanings:["形|ひとりきりの，孤独な","形|（場所が）人里離れた","形|たった1つの"],
   pronunciation:"/ˈsɑːləteri/",part:226,
   example:"The old man lived a solitary life in the mountains.",
   exampleJa:"その老人は山の中でひとりきりの生活を送っていた。",
   example2:"Unlike lions, tigers are solitary animals that usually hunt alone.",
   exampleJa2:"ライオンと違って、トラはふつう単独で狩りをするひとりきりの動物だ。",
   etymologyProcess:"solus（ただひとり）＋ ary（形容詞）→ 仲間から離れて過ごすさまは…？",
   etymologyConclusion:"solus（ただひとり）＋ ary（形容詞）→ 仲間と離れて、ただひとりで過ごす＝ひとりきりの",
   spelling:"solus→solit（ラテン語 solitarius を通った形）",
   etymologyMore:["ひとりだけ離れている→（場所が）人里離れた"],
   relatedWords:[
     {word:"solo",meaning:"独唱，ソロ",breakdown:"solus（ただひとり）→ ひとりで演じる歌や演奏"},
     {word:"sole",meaning:"唯一の",breakdown:"solus（ただひとり）→ ほかにない、ただ1つだけの"},
     {word:"solitude",meaning:"ひとりでいること",breakdown:"solus（ただひとり）＋ tude（名詞）→ ひとりで静かにいる時間"},
     {synonym:true,word:"lonely",meaning:"孤独な",breakdown:"さびしい気持ちが中心。solitary はひとりでいる事実"}]},

  {id:2254,word:"vulgar",partOfSpeech:"形容詞",meaning:"下品な，低俗な；一般大衆の",
   meanings:["形|下品な，低俗な","形|（言葉が）卑わいな","形|一般大衆の，通俗の"],
   pronunciation:"/ˈvʌlɡər/",part:226,
   example:"Please stop telling vulgar jokes in front of the children.",
   exampleJa:"子どもたちの前で下品な冗談を言うのはやめてください。",
   example2:"Some people think that flashy gold cars look vulgar.",
   exampleJa2:"派手な金色の車は下品に見えると思う人もいる。",
   etymologyProcess:"vulg（民衆）＋ ar（形容詞）→ 上品ぶる人から見た庶民風は…？",
   etymologyConclusion:"vulg（民衆）＋ ar（形容詞）→ 洗練されていない庶民風だと見下された＝下品な",
   why:"【なぜ】ラテン語 vulgus は「民衆、ふつうの人々」。vulgaris はもともと「ありふれた、一般の人々の」という意味で、悪い意味はありませんでした。身分の高い人々が「庶民的なもの＝洗練されていない」と見下したことで、しだいに「下品な、低俗な」という意味に変わりました。\n【つながり】今でも「通俗の、一般大衆の」という古い意味が残っています。",
   relatedWords:[
     {word:"divulge",meaning:"（秘密を）漏らす",breakdown:"di（離れて）＋ vulg（民衆）→ 秘密を民衆の中へ広めてしまう"},
     {synonym:true,word:"rude",meaning:"無礼な",breakdown:"相手への礼儀がないこと。vulgar は品のなさ"},
     {synonym:true,word:"offensive",meaning:"不快な，失礼な",breakdown:"人をいやな気持ちにさせること全般"},
     {synonym:true,word:"coarse",meaning:"粗野な；きめの粗い",breakdown:"がさつで荒っぽいこと。vulgar は下品さ"}]},

  {id:2255,word:"skeptical",partOfSpeech:"形容詞",meaning:"懐疑的な，疑い深い",
   meanings:["形|（about/of ～に）懐疑的な，疑い深い"],
   pronunciation:"/ˈskeptɪkəl/",part:226,
   usage:["be skeptical about［of］事（～を疑う）"],
   example:"Many scientists remain skeptical about the new diet's health benefits.",
   exampleJa:"多くの科学者は、その新しい食事法の健康効果に懐疑的なままだ。",
   example2:"I was skeptical of his story, so I checked the facts myself.",
   exampleJa2:"私は彼の話に懐疑的だったので、自分で事実を確かめた。",
   etymologyProcess:"scop（見る）＋ ical（～の）→ すぐに信じず、よく見ようとするのは…？",
   etymologyConclusion:"scop（見る）＋ ical（～の）→ すぐに信じず、自分の目でよく見て確かめる＝懐疑的な",
   spelling:"scop→skep（ギリシャ語の同じ動詞の別の形）",
   relatedWords:[
     {word:"scope",meaning:"範囲",breakdown:"scop（見る）→ ひと目で見渡せる広さ"},
     {word:"telescope",meaning:"望遠鏡",breakdown:"tele（遠く）＋ scop（見る）→ 遠くを見るための筒"},
     {word:"microscope",meaning:"顕微鏡",breakdown:"micro（小さい）＋ scop（見る）→ 小さいものを見る道具"},
     {synonym:true,word:"doubtful",meaning:"疑わしい；疑っている",breakdown:"迷って確信がない。skeptical は根拠を求めて疑う"}]},

  {id:2256,word:"accustomed",partOfSpeech:"形容詞",meaning:"（習慣になって）慣れている；いつもの",
   meanings:["形|（習慣になって）慣れている","形|いつもの，習慣的な"],
   pronunciation:"/əˈkʌstəmd/",part:226,
   usage:["be accustomed to 名詞／doing（～に慣れている）","get accustomed to 名詞（～に慣れる）"],
   example:"My eyes soon became accustomed to the darkness of the room.",
   exampleJa:"私の目はすぐに部屋の暗さに慣れた。",
   example2:"Are you accustomed to getting up early for morning practice yet?",
   exampleJa2:"朝練のために早起きすることには、もう慣れていますか。",
   etymologyProcess:"ad（～へ）＋ custom（慣れ親しむ）＋ ed（～された）→ 何度もくり返すと…？",
   etymologyConclusion:"ad（～へ）＋ custom（慣れ親しむ）＋ ed（～された）→ くり返してなじんだ状態にされた＝（習慣になって）慣れている",
   spelling:"ad→ac（c の前で d が c に変わった）",
   etymologyMore:["いつも慣れ親しんでいる→いつもの，習慣的な"],
   relatedWords:[
     {word:"custom",meaning:"習慣",breakdown:"custom（慣れ親しむ）→ 人々が慣れ親しんだやり方"},
     {word:"customer",meaning:"客",breakdown:"custom（慣れ親しむ）＋ er（人）→ いつも来てくれるなじみの人"},
     {word:"costume",meaning:"衣装",breakdown:"costume（慣れ親しむ）→ その土地でなじんだ服装"},
     {synonym:true,word:"used",meaning:"（to ～に）慣れている",breakdown:"be used to の形で日常的。accustomed は少し硬い"}]},

  {id:2257,word:"obsessed",partOfSpeech:"形容詞",meaning:"（with ～に）取りつかれた，頭から離れない",
   meanings:["形|（with ～に）取りつかれた，頭から離れない"],
   pronunciation:"/əbˈsest/",part:226,
   usage:["be obsessed with 物・事（～に取りつかれている）"],
   example:"My little brother is obsessed with dinosaurs and talks about them constantly.",
   exampleJa:"弟は恐竜に取りつかれていて、いつも恐竜の話ばかりしている。",
   example2:"Don't get too obsessed with your test scores; enjoy learning too.",
   exampleJa2:"テストの点数に取りつかれすぎないで、学ぶことも楽しもう。",
   etymologyProcess:"ob（向かい合って）＋ sess（座る）→ 目の前に何かが座りこむと…？",
   etymologyConclusion:"ob（向かい合って）＋ sess（座る）→ ある考えが目の前に座りこんで居すわる＝（with ～に）取りつかれた",
   why:"【なぜ】ラテン語 obsidere は「～の前に座りこむ」、つまり敵の城を取り囲む（包囲する）という意味でした。のちに悪霊が人を取り囲んで離れない様子にも使われ、そこから「ある考えが頭を占領して離れない」という今の意味になりました。\n【つながり】名詞は obsession（執着）。session（会期）も sess（座る）の仲間です。",
   relatedWords:[
     {word:"obsession",meaning:"執着，強い思い込み",breakdown:"ob（向かい合って）＋ sess（座る）＋ ion（名詞）→ 頭の前に居すわる考え"},
     {word:"session",meaning:"会期；（活動の）時間",breakdown:"sess（座る）＋ ion（名詞）→ 皆が座って集まる会"},
     {synonym:true,word:"sit",meaning:"座る",breakdown:"英語本来の語で sess と遠い親戚。考えがどっかり座りこむ"},
     {synonym:true,word:"addicted",meaning:"（to ～に）中毒の",breakdown:"やめられない状態。obsessed は頭から離れない状態"}]},

  {id:2258,word:"preoccupied",partOfSpeech:"形容詞",meaning:"（with ～で）頭がいっぱいの，気を取られた",
   meanings:["形|（with ～で）頭がいっぱいの，気を取られた"],
   pronunciation:"/priˈɑːkjəpaɪd/",part:226,
   usage:["be preoccupied with 事（～で頭がいっぱいだ）"],
   example:"She was so preoccupied with her phone that she missed her stop.",
   exampleJa:"彼女はスマホのことで頭がいっぱいで、降りる駅を乗り過ごした。",
   example2:"Most of us are preoccupied with entrance exams this year.",
   exampleJa2:"今年、私たちの大半は入試のことで頭がいっぱいだ。",
   etymologyProcess:"pre（先に）＋ oc（～に向かって）＋ cupa（取る）→ 心の場所を先に取られると…？",
   etymologyConclusion:"pre（先に）＋ oc（～に向かって）＋ cupa（取る）→ 心の場所を先に別のことに取られている＝（with ～で）頭がいっぱいの",
   spelling:"cupa→cup（occupy と同じ部分）",
   relatedWords:[
     {word:"occupy",meaning:"占める",breakdown:"oc（～に向かって）＋ cupa（取る）→ 場所に手をのばして取る"},
     {word:"occupation",meaning:"職業",breakdown:"oc（～に向かって）＋ cupa（取る）＋ ation（名詞）→ 日々の時間を占める仕事"},
     {word:"accept",meaning:"受け入れる",breakdown:"ad（～へ）＋ cept（取る）→ 差し出された物を受け取る"},
     {word:"except",meaning:"～を除いて",breakdown:"ex（外へ）＋ cept（取る）→ 取り出して外に置く"}]},

  {id:2259,word:"prone",partOfSpeech:"形容詞",meaning:"（to ～）しがちな，（病気などに）かかりやすい；うつぶせの",
   meanings:["形|（to ～）しがちな，（病気などに）かかりやすい","形|うつぶせの"],
   pronunciation:"/proʊn/",part:226,
   usage:["be prone to 名詞（～にかかりやすい）","be prone to do（～しがちだ）"],
   example:"Young children are prone to catching colds in winter.",
   exampleJa:"幼い子どもは冬にかぜをひきがちだ。",
   example2:"Lie prone on the mat and slowly lift both legs.",
   exampleJa2:"マットの上にうつぶせの姿勢になり、ゆっくり両脚を上げなさい。",
   etymologyProcess:"pro（前へ）→ 体が前に傾いていると、そちらへ…？",
   etymologyConclusion:"pro（前へ）→ 体が前に傾いていて、そちらへ倒れこみやすい＝（to ～）しがちな",
   etymologyMore:["前に傾いて倒れた姿→うつぶせの"],
   hook:"accident-prone（事故を起こしがちな）のように、名詞の後ろに付けても使う。",
   relatedWords:[
     {word:"propose",meaning:"提案する",breakdown:"pro（前へ）＋ pos（置く）→ 案を人の前に置く"},
     {word:"produce",meaning:"生産する",breakdown:"pro（前へ）＋ duc（導く）→ 前へ引き出して生み出す"},
     {synonym:true,word:"likely",meaning:"～しそうな",breakdown:"起こる見込みが高いこと。prone は悪い傾向が多い"},
     {synonym:true,word:"apt",meaning:"～しがちな",breakdown:"性質としてそうなりやすい。prone のほうが悪い意味が強い"}]},

  {id:2260,word:"apt",partOfSpeech:"形容詞",meaning:"（表現などが）ぴったりの，的を射た；（to do）しがちな",
   meanings:["形|（表現などが）ぴったりの，的を射た","形|（to do）しがちな"],
   pronunciation:"/æpt/",part:226,
   usage:["be apt to do（～しがちだ）"],
   example:"That was an apt comment that fit the situation perfectly.",
   exampleJa:"それはその場面に合った、ぴったりの一言だった。",
   example2:"Students are apt to forget new words unless they review them.",
   exampleJa2:"生徒は復習しないと、新しい単語を忘れがちだ。",
   etymologyProcess:"apt（ぴったり合う）→ その場面にぴたりと合うと…？",
   etymologyConclusion:"apt（ぴったり合う）→ その場面にすき間なくぴたりと合っている＝（表現などが）ぴったりの",
   etymologyMore:["ある方向へぴったりはまりやすい→（to do）しがちな"],
   relatedWords:[
     {word:"adapt",meaning:"適応させる",breakdown:"ad（～へ）＋ apt（ぴったり合う）→ 環境に合うように変える"},
     {word:"aptitude",meaning:"適性",breakdown:"apt（ぴったり合う）＋ tude（名詞）→ 仕事にぴったり合う素質"},
     {word:"attitude",meaning:"態度",breakdown:"apt（ぴったり合う）＋ tude（名詞）→ 場に合わせて整えた構え"},
     {synonym:true,word:"suitable",meaning:"適した",breakdown:"目的にかなうこと。apt は言葉や表現によく使う"}]},

  {id:2261,word:"empirical",partOfSpeech:"形容詞",meaning:"実験［経験］に基づく，実証的な",
   meanings:["形|実験［経験］に基づく，実証的な"],
   pronunciation:"/ɪmˈpɪrɪkəl/",part:227,
   example:"The theory needs empirical evidence before scientists will accept it.",
   exampleJa:"科学者に受け入れられるには、その理論には実験に基づく証拠が必要だ。",
   example2:"Our science club collected empirical data on the river's water quality.",
   exampleJa2:"科学部は、川の水質について実際の調査に基づくデータを集めた。",
   etymologyProcess:"em（中へ）＋ peri（試す）＋ ical（～の）→ 実際に中へ入って試してみると…？",
   etymologyConclusion:"em（中へ）＋ peri（試す）＋ ical（～の）→ 頭の中だけでなく、実際に試してみた結果による＝実験［経験］に基づく",
   spelling:"peri→pir（ギリシャ語 peira「試み」の形）",
   relatedWords:[
     {word:"experience",meaning:"経験",breakdown:"ex（外へ）＋ peri（試す）＋ ence（名詞）→ 試してみて身につけたこと"},
     {word:"experiment",meaning:"実験",breakdown:"ex（外へ）＋ peri（試す）＋ ment（名詞）→ 本当かどうか試す作業"},
     {word:"expert",meaning:"専門家",breakdown:"ex（外へ）＋ peri（試す）→ 何度も試して腕をみがいた人"},
     {synonym:true,word:"practical",meaning:"実際的な",breakdown:"実際の役に立つこと。empirical は観察や実験で確かめること"}]},

  {id:2262,word:"susceptible",partOfSpeech:"形容詞",meaning:"（to ～の）影響を受けやすい，（病気に）かかりやすい",
   meanings:["形|（to ～の）影響を受けやすい，（病気に）かかりやすい","形|（of ～が）可能な"],
   pronunciation:"/səˈseptəbəl/",part:227,
   usage:["be susceptible to 名詞（～の影響を受けやすい）"],
   example:"Older people are more susceptible to the flu than young people.",
   exampleJa:"高齢者は若者よりもインフルエンザの影響を受けやすい。",
   example2:"Teenagers can be susceptible to pressure from their friends.",
   exampleJa2:"10代は友人からの圧力の影響を受けやすいことがある。",
   etymologyProcess:"sub（下で）＋ cept（取る）＋ ible（できる）→ 下で受け止めてしまうと…？",
   etymologyConclusion:"sub（下で）＋ cept（取る）＋ ible（できる）→ 外から来るものを下で受け止めてしまいやすい＝（to ～の）影響を受けやすい",
   spelling:"sub→sus（c の前で変化した）",
   relatedWords:[
     {word:"accept",meaning:"受け入れる",breakdown:"ad（～へ）＋ cept（取る）→ 差し出された物を受け取る"},
     {word:"receive",meaning:"受け取る",breakdown:"re（後ろへ）＋ ceive（取る）→ 届いた物を手元へ取りこむ"},
     {word:"concept",meaning:"概念",breakdown:"con（共に）＋ cept（取る）→ まとめて取りこんだ考え"},
     {synonym:true,word:"vulnerable",meaning:"傷つきやすい",breakdown:"攻撃や害に弱いこと。susceptible は影響や病気を受けやすい"}]},

  {id:2263,word:"pivotal",partOfSpeech:"形容詞",meaning:"（物事の）要となる，極めて重要な",
   meanings:["形|（物事の）要となる，極めて重要な"],
   pronunciation:"/ˈpɪvətəl/",part:227,
   example:"Her goal in the final minute played a pivotal role in our victory.",
   exampleJa:"最後の1分の彼女のゴールが、私たちの勝利で要となる役割を果たした。",
   example2:"The year 1945 was a pivotal year in Japanese history.",
   exampleJa2:"1945年は日本の歴史で要となる年だった。",
   etymologyProcess:"pivot（回転の軸）＋ al（～の）→ 全体がその一点を中心に回ると…？",
   etymologyConclusion:"pivot（回転の軸）＋ al（～の）→ 全体がその一点を軸にしてぐるりと回る＝（物事の）要となる",
   relatedWords:[
     {word:"pivot",meaning:"回転軸；軸足",breakdown:"pivot（回転の軸）→ 扉の軸や、バスケットボールの軸足"},
     {synonym:true,word:"key",meaning:"かぎとなる，重要な",breakdown:"扉を開けるかぎのように大事なこと"},
     {synonym:true,word:"central",meaning:"中心的な",breakdown:"まん中にあること。pivotal はそこを軸に全体が動く"},
     {synonym:true,word:"crucial",meaning:"決定的に重要な",breakdown:"結果を左右するほど大事。pivotal は転換の軸"}]},

  {id:2264,word:"fabulous",partOfSpeech:"形容詞",meaning:"とてもすてきな，すばらしい；信じられないほどの",
   meanings:["形|とてもすてきな，すばらしい","形|（話が）信じられないほどの，途方もない"],
   pronunciation:"/ˈfæbjələs/",part:227,
   example:"We had a fabulous time at the beach last weekend.",
   exampleJa:"先週末、私たちは海辺でとてもすてきな時間を過ごした。",
   example2:"The singer wore a fabulous dress covered in gold sequins.",
   exampleJa2:"その歌手は、金のスパンコールで覆われたとてもすてきなドレスを着ていた。",
   etymologyProcess:"fa（話す）＋ ous（～に満ちた）→ おとぎ話に出てきそうなほどだと…？",
   etymologyConclusion:"fa（話す）＋ ous（～に満ちた）→ おとぎ話に出てくるほど夢のようだ＝とてもすてきな",
   why:"【なぜ】fabulous はラテン語 fabula（語られた話、おとぎ話）から来ていて、もとは「伝説上の、作り話のような」という意味でした。現実とは思えないほど並外れている、から「信じられないほどすごい」へ、さらに会話で使うほめ言葉「とてもすてきな」へと、意味が軽くなりながら広がりました。\n【つながり】fable（寓話）も同じ仲間。会話では fab と略すこともあります。",
   etymologyMore:["作り話のようにありえない→（話が）信じられないほどの，途方もない"],
   relatedWords:[
     {word:"fable",meaning:"寓話",breakdown:"fa（話す）＋ ble（もの）→ 語り伝えられた教訓の話"},
     {word:"famous",meaning:"有名な",breakdown:"fam（語られる）＋ ous（～に満ちた）→ 人々に語られる"},
     {word:"infant",meaning:"幼児",breakdown:"in（否定）＋ fa（話す）＋ ant（人）→ まだ話せない幼い子"},
     {synonym:true,word:"wonderful",meaning:"すばらしい",breakdown:"ふつうのほめ言葉。fabulous はもっと華やか"}]},

  {id:2265,word:"splendid",partOfSpeech:"形容詞",meaning:"（輝くように）見事な，壮麗な；すばらしい",
   meanings:["形|（輝くように）見事な，壮麗な","形|すばらしい，申し分ない"],
   pronunciation:"/ˈsplendɪd/",part:227,
   example:"From the top of the tower, we enjoyed a splendid view of the city.",
   exampleJa:"塔の上から、私たちは街の見事な眺めを楽しんだ。",
   example2:"That's a splendid idea! Let's try it at the school festival.",
   exampleJa2:"それは見事な考えだね！文化祭で試してみよう。",
   etymologyProcess:"splend（輝く）＋ id（～な状態の）→ まぶしく光り輝いていると…？",
   etymologyConclusion:"splend（輝く）＋ id（～な状態の）→ まぶしく光り輝いているように立派だ＝（輝くように）見事な",
   relatedWords:[
     {word:"splendor",meaning:"壮麗さ，輝き",breakdown:"splend（輝く）＋ or（もの）→ 光り輝く立派なようす"},
     {synonym:true,word:"wonderful",meaning:"すばらしい",breakdown:"ふつうのほめ言葉。splendid は見た目の立派さが強い"},
     {synonym:true,word:"brilliant",meaning:"見事な；輝かしい",breakdown:"きらきら光ることから。頭のよさにも使う"},
     {synonym:true,word:"magnificent",meaning:"壮大な",breakdown:"大きくて堂々としていること"}]},

  {id:2266,word:"intriguing",partOfSpeech:"形容詞",meaning:"（好奇心をそそって）興味をかき立てる，おもしろい",
   meanings:["形|（好奇心をそそって）興味をかき立てる，おもしろい"],
   pronunciation:"/ɪnˈtriːɡɪŋ/",part:227,
   example:"The detective found an intriguing clue under the window.",
   exampleJa:"探偵は窓の下で、興味をかき立てる手がかりを見つけた。",
   example2:"Our club leader asked an intriguing question that made everyone think.",
   exampleJa2:"部長は、皆が考えこむような興味をかき立てる問いを出した。",
   etymologyProcess:"in（中へ）＋ tric（もつれ）＋ ing（～している）→ もつれた謎に心が入りこむと…？",
   etymologyConclusion:"in（中へ）＋ tric（もつれ）＋ ing（～している）→ もつれた謎の中へ心を引きこんでいく＝（好奇心をそそって）興味をかき立てる",
   spelling:"tric→trig（フランス語を通って変化）",
   relatedWords:[
     {word:"intrigue",meaning:"陰謀；興味をそそる",breakdown:"in（中へ）＋ tric（もつれ）→ 人をもつれた企みに巻きこむ"},
     {word:"intricate",meaning:"入り組んだ",breakdown:"in（中へ）＋ tric（もつれ）＋ ate（形容詞）→ 中がもつれて複雑"},
     {synonym:true,word:"interesting",meaning:"おもしろい",breakdown:"ふつうの「おもしろい」。intriguing は謎めいて気になる"},
     {synonym:true,word:"curious",meaning:"好奇心の強い；奇妙な",breakdown:"知りたがる気持ち。intriguing はそれを起こさせる側"}]},

  {id:2267,word:"ingenious",partOfSpeech:"形容詞",meaning:"（考えが）独創的な，巧妙な",
   meanings:["形|（考えや仕掛けが）独創的な，巧妙な","形|（人が）発明の才のある"],
   pronunciation:"/ɪnˈdʒiːniəs/",part:227,
   example:"He came up with an ingenious way to save water at home.",
   exampleJa:"彼は家で水を節約する独創的な方法を思いついた。",
   example2:"The robot our team built was simple but ingenious.",
   exampleJa2:"私たちのチームが作ったロボットは、単純だが独創的だった。",
   etymologyProcess:"in（中へ）＋ gen（生み出す）＋ ous（～に満ちた）→ 生まれ持った才から工夫が…？",
   etymologyConclusion:"in（中へ）＋ gen（生み出す）＋ ous（～に満ちた）→ 生まれ持った才で新しい工夫を生み出す＝（考えが）独創的な",
   relatedWords:[
     {word:"engine",meaning:"エンジン",breakdown:"in（中へ）＋ gen（生み出す）→ 工夫の才が生んだ仕掛け"},
     {word:"engineer",meaning:"技術者",breakdown:"in（中へ）＋ gen（生み出す）＋ eer（人）→ 仕掛けを工夫して作る人"},
     {word:"genius",meaning:"天才",breakdown:"gen（生み出す）→ 生まれつき宿っている才能"},
     {synonym:true,word:"creative",meaning:"創造的な",breakdown:"新しいものを生み出す力。ingenious は仕掛けのうまさ"}]},

  {id:2268,word:"affluent",partOfSpeech:"形容詞",meaning:"裕福な，豊かな",
   meanings:["形|裕福な，豊かな"],
   pronunciation:"/ˈæfluənt/",part:227,
   example:"They live in an affluent neighborhood with large houses and gardens.",
   exampleJa:"彼らは大きな家と庭のある、裕福な地域に住んでいる。",
   example2:"Japan became much more affluent in the 1960s and 1970s.",
   exampleJa2:"日本は1960年代から70年代にかけて、ずっと裕福になった。",
   etymologyProcess:"ad（～へ）＋ flu（流れる）＋ ent（～している）→ お金がどんどん流れこむと…？",
   etymologyConclusion:"ad（～へ）＋ flu（流れる）＋ ent（～している）→ お金や物が次々と流れこんでくる＝裕福な",
   spelling:"ad→af（f の前で d が f に変わった）",
   relatedWords:[
     {word:"influence",meaning:"影響",breakdown:"in（中へ）＋ flu（流れる）＋ ence（名詞）→ 中へ流れこんで働く力"},
     {word:"fluent",meaning:"流ちょうな",breakdown:"flu（流れる）＋ ent（～している）→ 言葉がすらすら流れる"},
     {word:"fluid",meaning:"液体，流動体",breakdown:"flu（流れる）＋ id（～な状態の）→ 流れる状態のもの"},
     {synonym:true,word:"rich",meaning:"金持ちの",breakdown:"ふつうの「金持ち」。affluent は社会や地域の豊かさにも使う"}]},

  {id:2269,word:"renowned",partOfSpeech:"形容詞",meaning:"（for ～で）名高い",
   meanings:["形|（for ～で）名高い，有名な"],
   pronunciation:"/rɪˈnaʊnd/",part:227,
   usage:["be renowned for 事（～で名高い）"],
   example:"Kyoto is renowned for its beautiful temples and gardens.",
   exampleJa:"京都は美しい寺院と庭園で名高い。",
   example2:"A renowned scientist will give a lecture at our school next month.",
   exampleJa2:"来月、名高い科学者が私たちの学校で講演をする。",
   etymologyProcess:"re（再び）＋ noun（名前）→ 名前が何度も呼ばれると…？",
   etymologyConclusion:"re（再び）＋ noun（名前）→ 名前がくり返し人々に呼ばれる＝（for ～で）名高い",
   spelling:"noun→nown（フランス語を通って変化）",
   relatedWords:[
     {word:"noun",meaning:"名詞",breakdown:"noun（名前）→ ものの名前を表す語"},
     {word:"pronoun",meaning:"代名詞",breakdown:"pro（代わりに）＋ noun（名前）→ 名前の代わりに使う語"},
     {word:"nominate",meaning:"指名する",breakdown:"nomin（名前）＋ ate（動詞）→ 候補として名前を挙げる"},
     {synonym:true,word:"famous",meaning:"有名な",breakdown:"ふつうの「有名な」。renowned は実力でたたえられる"}]},

  {id:2270,word:"eminent",partOfSpeech:"形容詞",meaning:"（学問などで）著名な，すぐれた",
   meanings:["形|（学問などで）著名な，すぐれた"],
   pronunciation:"/ˈemɪnənt/",part:227,
   example:"An eminent professor of economics was invited to the conference.",
   exampleJa:"著名な経済学の教授が、その会議に招かれた。",
   example2:"Her grandfather was an eminent doctor in this town.",
   exampleJa2:"彼女の祖父は、この町の著名な医師だった。",
   etymologyProcess:"e（外へ）＋ mine（突き出る）＋ ent（～している）→ 周りより外へ突き出ると…？",
   etymologyConclusion:"e（外へ）＋ mine（突き出る）＋ ent（～している）→ 周りから頭ひとつ外へ突き出ている＝（学問などで）著名な",
   spelling:"mine→min（ラテン語 minere「突き出る」）",
   relatedWords:[
     {word:"prominent",meaning:"目立った",breakdown:"pro（前へ）＋ mine（突き出る）＋ ent（～している）→ 前へ突き出て目立つ"},
     {synonym:true,word:"famous",meaning:"有名な",breakdown:"広く知られていること。eminent は専門の世界での高い評価"},
     {synonym:true,word:"outstanding",meaning:"際立ってすぐれた",breakdown:"out（外へ）＋ stand（立つ）。人より外に立って目立つ"},
     {synonym:true,word:"distinguished",meaning:"名声のある",breakdown:"他と区別されるほどすぐれていること"}]},

  {id:2271,word:"conspicuous",partOfSpeech:"形容詞",meaning:"（すぐ目につくほど）目立つ，人目を引く",
   meanings:["形|（すぐ目につくほど）目立つ，人目を引く"],
   pronunciation:"/kənˈspɪkjuəs/",part:228,
   example:"Wear a conspicuous color so we can find you in the crowd.",
   exampleJa:"人ごみでも見つけられるように、目立つ色の服を着てきて。",
   example2:"His absence from the team photo was quite conspicuous.",
   exampleJa2:"チーム写真に彼がいないことは、かなり目立っていた。",
   etymologyProcess:"con（すっかり）＋ spect（見る）＋ ous（～に満ちた）→ だれからもよく見えると…？",
   etymologyConclusion:"con（すっかり）＋ spect（見る）＋ ous（～に満ちた）→ だれの目にもはっきり見えてしまう＝（すぐ目につくほど）目立つ",
   spelling:"spect→spic（ラテン語 specere の変化形）",
   relatedWords:[
     {word:"inspect",meaning:"検査する",breakdown:"in（中へ）＋ spect（見る）→ 中までよく見て調べる"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ or（人）→ 試合や劇を見る人"},
     {word:"respect",meaning:"尊敬する",breakdown:"re（再び）＋ spect（見る）→ 何度もふり返って見る"},
     {synonym:true,word:"noticeable",meaning:"目につく",breakdown:"気づかれやすいこと。conspicuous はもっと強く目立つ"}]},

  {id:2272,word:"adept",partOfSpeech:"形容詞",meaning:"（at ～に）熟練した，腕のいい",
   meanings:["形|（at ～に）熟練した，腕のいい","名|達人，名人"],
   pronunciation:"/əˈdept/",part:228,
   usage:["be adept at［in］doing（～するのが上手だ）"],
   example:"My grandmother is adept at making traditional Japanese sweets.",
   exampleJa:"祖母は伝統的な和菓子作りに熟練している。",
   example2:"She quickly became adept at using the new video software.",
   exampleJa2:"彼女はすぐに新しい動画ソフトの扱いに熟練した。",
   etymologyProcess:"ad（～へ）＋ apisc（届く）→ 目標の技に手が届くと…？",
   etymologyConclusion:"ad（～へ）＋ apisc（届く）→ めざした技にしっかり手が届いた＝（at ～に）熟練した",
   spelling:"apisc→ept（過去分詞 adeptus の形）",
   why:"【なぜ】adept はラテン語 adipisci（到達する、手に入れる）の過去分詞 adeptus「到達した」から来ています。中世の錬金術師のうち、秘術をきわめた人を adeptus と呼んだため、「技をきわめた、熟練した」という意味で英語に入りました。\n【つながり】「到達した人」が「達人」になった、と考えると覚えやすい語です。",
   relatedWords:[
     {synonym:true,word:"skilled",meaning:"熟練した",breakdown:"技術を身につけていること。adept は手際のよさが目立つ"},
     {synonym:true,word:"expert",meaning:"専門家",breakdown:"深い知識と腕をもつ人。adept も名詞で達人"},
     {word:"apt",meaning:"ぴったりの",breakdown:"apt（ぴったり合う）→ adept と同じ大もと「結びつける」から"},
     {synonym:true,word:"proficient",meaning:"堪能な",breakdown:"練習で身につけた力。語学によく使う"}]},

  {id:2273,word:"proficient",partOfSpeech:"形容詞",meaning:"（語学・技能に）堪能な，熟達した",
   meanings:["形|（語学・技能に）堪能な，熟達した"],
   pronunciation:"/prəˈfɪʃənt/",part:228,
   usage:["be proficient in［at］事（～に堪能だ）"],
   example:"She is proficient in three languages, including Chinese.",
   exampleJa:"彼女は中国語を含む3つの言語に堪能だ。",
   example2:"You need to practice every day to become proficient at the piano.",
   exampleJa2:"ピアノに熟達するには、毎日練習する必要がある。",
   etymologyProcess:"pro（前へ）＋ fic（作る）＋ ent（～している）→ 練習で前へ前へ進むと…？",
   etymologyConclusion:"pro（前へ）＋ fic（作る）＋ ent（～している）→ 練習を重ねて前へ前へと進んできた＝（語学・技能に）堪能な",
   relatedWords:[
     {word:"efficient",meaning:"効率のよい",breakdown:"ex（外へ）＋ fic（作る）＋ ent（～している）→ 結果をしっかり作り出す"},
     {word:"profit",meaning:"利益",breakdown:"pro（前へ）＋ fic（作る）→ 前へ進んで生まれるもうけ"},
     {word:"difficult",meaning:"難しい",breakdown:"dis（否定）＋ fic（作る）→ 簡単には作れない"},
     {synonym:true,word:"skilled",meaning:"熟練した",breakdown:"技術を身につけていること。proficient は訓練で上達した"}]},

  {id:2274,word:"immense",partOfSpeech:"形容詞",meaning:"計り知れないほど大きな，とてつもない",
   meanings:["形|計り知れないほど大きな，とてつもない"],
   pronunciation:"/ɪˈmens/",part:228,
   example:"The new stadium cost an immense amount of money to build.",
   exampleJa:"新しい競技場の建設には、計り知れないほど大きな金額がかかった。",
   example2:"Winning the national tournament gave us immense joy.",
   exampleJa2:"全国大会での優勝は、私たちに計り知れないほど大きな喜びをもたらした。",
   etymologyProcess:"in（否定）＋ meas（測る）→ 大きすぎて測れないと…？",
   etymologyConclusion:"in（否定）＋ meas（測る）→ 大きすぎて、ものさしで測ることができない＝計り知れないほど大きな",
   spelling:"in→im（m の前で変化）、meas→mens（ラテン語 mensus）",
   relatedWords:[
     {word:"measure",meaning:"測る",breakdown:"meas（測る）＋ ure（名詞）→ 長さや量をはかる"},
     {word:"measurement",meaning:"測定；寸法",breakdown:"meas（測る）＋ ure（名詞）＋ ment（名詞）→ はかった結果の数字"},
     {synonym:true,word:"huge",meaning:"巨大な",breakdown:"ふつうの「とても大きい」。immense は測れないほど"},
     {synonym:true,word:"enormous",meaning:"莫大な",breakdown:"e（外へ）＋ norm（基準）。基準を外れるほど大きい"}]},

  {id:2275,word:"unanimous",partOfSpeech:"形容詞",meaning:"満場一致の，全員が賛成の",
   meanings:["形|満場一致の，全員が賛成の"],
   pronunciation:"/juˈnænɪməs/",part:228,
   example:"The committee made a unanimous decision to cancel the event.",
   exampleJa:"委員会はそのイベントを中止するという満場一致の決定をした。",
   example2:"Our class was unanimous in choosing a café for the school festival.",
   exampleJa2:"文化祭でカフェをやることに、クラスは満場一致だった。",
   etymologyProcess:"uni（1つ）＋ anim（命・息）＋ ous（～に満ちた）→ 全員の心がひとつだと…？",
   etymologyConclusion:"uni（1つ）＋ anim（命・息）＋ ous（～に満ちた）→ 全員の心と息がひとつにそろう＝満場一致の",
   spelling:"uni→un（anim とつながって i が消えた）",
   relatedWords:[
     {word:"animal",meaning:"動物",breakdown:"anim（命・息）＋ al（～の）→ 息をして生きているもの"},
     {word:"animation",meaning:"アニメーション",breakdown:"anim（命・息）＋ ation（名詞）→ 絵に命を吹きこむこと"},
     {word:"unite",meaning:"団結させる",breakdown:"uni（1つ）→ ばらばらのものを1つにまとめる"},
     {word:"uniform",meaning:"制服",breakdown:"uni（1つ）＋ form（形）→ 全員が同じ1つの形の服"}]},

  {id:2276,word:"reckless",partOfSpeech:"形容詞",meaning:"（危険を顧みず）無謀な，向こう見ずな",
   meanings:["形|（危険を顧みず）無謀な，向こう見ずな"],
   pronunciation:"/ˈrekləs/",part:228,
   example:"The driver was arrested for reckless driving on the highway.",
   exampleJa:"その運転手は、高速道路での無謀な運転で逮捕された。",
   example2:"It was reckless of you to climb the mountain alone in the snow.",
   exampleJa2:"雪の中、ひとりで山に登るなんて、君は無謀だったよ。",
   etymologyProcess:"reck（気にかける）＋ less（ない）→ 危険をまるで気にかけないと…？",
   etymologyConclusion:"reck（気にかける）＋ less（ない）→ 危険を少しも気にかけずに突っ走る＝（危険を顧みず）無謀な",
   relatedWords:[
     {word:"careless",meaning:"不注意な",breakdown:"care（心配ごと）＋ less（ない）→ 気にかける心配がない"},
     {word:"countless",meaning:"数えきれない",breakdown:"count（数える）＋ less（ない）→ 多すぎて数えられない"},
     {word:"homeless",meaning:"家のない",breakdown:"home（家）＋ less（ない）→ 住む家がない"},
     {synonym:true,word:"rash",meaning:"軽率な",breakdown:"よく考えずに急いで決めること。reckless は危険を無視する"}]},

  {id:2277,word:"futile",partOfSpeech:"形容詞",meaning:"（努力が）無駄な，むなしい",
   meanings:["形|（努力が）無駄な，むなしい"],
   pronunciation:"/ˈfjuːtəl/",part:228,
   example:"All our efforts to save the old theater were futile.",
   exampleJa:"古い劇場を救おうとした私たちの努力は、すべて無駄だった。",
   example2:"It's futile to argue with him when he is angry.",
   exampleJa2:"怒っているときの彼と言い争っても無駄だ。",
   etymologyProcess:"fuse（注ぐ）＋ ile（できる）→ 注いでもすぐこぼれる器だと…？",
   etymologyConclusion:"fuse（注ぐ）＋ ile（できる）→ いくら注いでも中身がこぼれ出てたまらない＝（努力が）無駄な",
   spelling:"fuse→fut（ラテン語 futilis の形）",
   why:"【なぜ】ラテン語 futilis は、おそらく fundere（注ぐ）と関係する語で、もとは「中身がすぐにこぼれ出る」という器の性質を表す語でした。水を注いでも漏れてしまう器は、いくら注いでも満たせません。そこから「力をつぎこんでも何も残らない」、つまり努力が無駄な、むなしいという意味になりました。\n【つながり】「底の抜けたバケツに水をくむ」ような空しさ、と覚えましょう。",
   relatedWords:[
     {word:"refuse",meaning:"断る",breakdown:"re（後ろへ）＋ fuse（注ぐ）→ 注がれたものを押し戻す"},
     {word:"confuse",meaning:"混乱させる",breakdown:"con（共に）＋ fuse（注ぐ）→ いっしょに注いでごちゃまぜ"},
     {synonym:true,word:"useless",meaning:"役に立たない",breakdown:"use（使う）＋ less（ない）。futile は努力が実らない"},
     {synonym:true,word:"pointless",meaning:"無意味な",breakdown:"やる意味がないこと。futile は結果が出ない"}]},

  {id:2278,word:"brutal",partOfSpeech:"形容詞",meaning:"残忍な，むごい；過酷な",
   meanings:["形|残忍な，むごい","形|（試練・天候などが）過酷な，厳しい"],
   pronunciation:"/ˈbruːtəl/",part:228,
   example:"The brutal attack on the village shocked the whole world.",
   exampleJa:"その村への残忍な攻撃は、全世界に衝撃を与えた。",
   example2:"Summer training camp was brutal, but we all got stronger.",
   exampleJa2:"夏合宿は過酷だったが、私たちは皆強くなった。",
   etymologyProcess:"brut（鈍い）＋ al（～の）→ 理性の鈍いけもののようだと…？",
   etymologyConclusion:"brut（鈍い）＋ al（～の）→ 理性の鈍いけもののように情けがない＝残忍な",
   why:"【なぜ】ラテン語 brutus は「重くて鈍い、愚かな」。ここから英語の brute が「理性をもたない獣」を指すようになり、brutal は「獣のように情け容赦のない」、つまり残忍な、という意味になりました。\n【つながり】カエサルを刺したブルートゥス（Brutus）の名も、もとは同じ「鈍い」という語です。",
   etymologyMore:["手加減のない荒々しさ→（試練・天候などが）過酷な，厳しい"],
   relatedWords:[
     {word:"brute",meaning:"けもの；乱暴者",breakdown:"brut（鈍い）→ 理性の鈍いけもの、乱暴な人"},
     {synonym:true,word:"cruel",meaning:"残酷な",breakdown:"人を苦しめて平気なこと。brutal は荒々しさが強い"},
     {synonym:true,word:"violent",meaning:"暴力的な",breakdown:"力ずくで乱暴なこと"},
     {synonym:true,word:"harsh",meaning:"厳しい，きつい",breakdown:"容赦なく厳しいこと。天候や言葉にも使う"}]},

  {id:2279,word:"ominous",partOfSpeech:"形容詞",meaning:"不吉な，（悪いことの）前兆となる",
   meanings:["形|不吉な，（悪いことの）前兆となる"],
   pronunciation:"/ˈɑːmɪnəs/",part:228,
   example:"Ominous dark clouds were gathering over the mountains.",
   exampleJa:"不吉な黒い雲が、山の上に集まりつつあった。",
   example2:"There was an ominous silence after the teacher saw my test.",
   exampleJa2:"先生が私のテストを見たあと、不吉な沈黙が流れた。",
   etymologyProcess:"omin（前兆）＋ ous（～に満ちた）→ 前ぶれの気配でいっぱいだと…？",
   etymologyConclusion:"omin（前兆）＋ ous（～に満ちた）→ 悪いことが起こる前ぶれに満ちている＝不吉な",
   relatedWords:[
     {word:"omen",meaning:"前兆",breakdown:"omin（前兆）→ 良くも悪くも、何かが起こる前ぶれ"},
     {synonym:true,word:"dark",meaning:"暗い；陰気な",breakdown:"光がないこと。ominous はこの先の悪い予感"},
     {synonym:true,word:"threatening",meaning:"脅すような，険悪な",breakdown:"危険がせまっている感じ。空模様にも使う"},
     {synonym:true,word:"sinister",meaning:"悪意のありそうな",breakdown:"邪悪なものを感じさせること"}]},

  {id:2280,word:"detrimental",partOfSpeech:"形容詞",meaning:"（to ～に）有害な，損害を与える",
   meanings:["形|（to ～に）有害な，損害を与える"],
   pronunciation:"/ˌdetrɪˈmentəl/",part:228,
   usage:["be detrimental to 名詞（～に有害だ）"],
   example:"Too much screen time can be detrimental to your eyesight.",
   exampleJa:"画面を長時間見すぎると、視力に有害なことがある。",
   example2:"Skipping breakfast is detrimental to students' concentration in class.",
   exampleJa2:"朝食を抜くことは、授業中の生徒の集中力に有害だ。",
   etymologyProcess:"de（離れて）＋ trit（すり減らす）＋ ment（名詞）＋ al（～の）→ 少しずつすり減らすと…？",
   etymologyConclusion:"de（離れて）＋ trit（すり減らす）＋ ment（名詞）＋ al（～の）→ 少しずつすり減らして損なっていく＝（to ～に）有害な",
   spelling:"trit→tri（ラテン語 terere の変化形）",
   relatedWords:[
     {word:"trite",meaning:"ありふれた，陳腐な",breakdown:"trit（すり減らす）→ 使われすぎてすり減った言葉"},
     {word:"detriment",meaning:"損害",breakdown:"de（離れて）＋ trit（すり減らす）＋ ment（名詞）→ すり減って失うこと"},
     {synonym:true,word:"harmful",meaning:"害のある",breakdown:"harm（害）＋ ful（満ちた）。日常的な「有害な」"},
     {synonym:true,word:"damage",meaning:"損害；傷つける",breakdown:"物や体を傷めること"}]},

  {id:2281,word:"wicked",partOfSpeech:"形容詞",meaning:"（心が）邪悪な，意地の悪い；いたずらな",
   meanings:["形|（心が）邪悪な，意地の悪い","形|いたずらな，茶目っ気のある"],
   pronunciation:"/ˈwɪkɪd/",part:229,
   example:"In the story, the wicked queen tries to poison the princess.",
   exampleJa:"その物語では、邪悪な女王が王女に毒を盛ろうとする。",
   example2:"My little sister gave me a wicked grin before hiding my shoes.",
   exampleJa2:"妹はいたずらな笑みを浮かべてから、私の靴を隠した。",
   etymologyProcess:"wicca（魔法使い）→ 魔法で悪さをたくらむ人のようだと…？",
   etymologyConclusion:"wicca（魔法使い）→ 魔法で人に悪さをたくらむ者のようだ＝（心が）邪悪な",
   spelling:"wicca→wick（古英語から短くなった）",
   hook:"語源ははっきりしないが、古英語 wicca から来たとされる。女性形 wicce が witch。",
   relatedWords:[
     {word:"witch",meaning:"魔女",breakdown:"wicce（魔法を使う女）→ wicca の女性形から"},
     {synonym:true,word:"evil",meaning:"邪悪な，悪い",breakdown:"悪そのもの。wicked は物語の悪役によく使う"},
     {synonym:true,word:"bad",meaning:"悪い",breakdown:"いちばんふつうの「悪い」"},
     {synonym:true,word:"naughty",meaning:"いたずらな",breakdown:"子どもの行儀の悪さ。wicked は茶目っ気にも使う"}]},

  {id:2282,word:"cynical",partOfSpeech:"形容詞",meaning:"冷笑的な，（人の善意を）信じない",
   meanings:["形|冷笑的な，（人の善意を）信じない","形|（自分の得だけを考えて）ずるい"],
   pronunciation:"/ˈsɪnɪkəl/",part:229,
   usage:["be cynical about 事（～を冷ややかに見る）"],
   example:"Many young people have become cynical about politics.",
   exampleJa:"多くの若者が、政治に対して冷笑的になっている。",
   example2:"Don't be so cynical; some people really do want to help.",
   exampleJa2:"そんなに冷笑的にならないで。本当に助けたいと思っている人もいるよ。",
   etymologyProcess:"cyn（犬）＋ ical（～の）→ 犬のように暮らした哲学者の目つきは…？",
   etymologyConclusion:"cyn（犬）＋ ical（～の）→ 犬のように暮らし、世間の常識を鼻で笑った学派のような＝冷笑的な",
   why:"【なぜ】古代ギリシャに、財産や礼儀を捨てて犬のように暮らした「キュニコス派（犬儒派）」という哲学者たちがいました。ディオゲネスが有名です。彼らは世間の決まりや人の善意を皮肉な目で見て笑い飛ばしました。そこから cynical は「人の誠実さを信じず、冷ややかに笑う」という意味になりました。\n【つながり】cynic は「皮肉屋」という名詞です。",
   relatedWords:[
     {word:"cynic",meaning:"皮肉屋",breakdown:"cyn（犬）→ 犬儒派のように、何でも皮肉に見る人"},
     {synonym:true,word:"sarcastic",meaning:"いやみな，皮肉な",breakdown:"言葉でちくりと刺すこと。cynical は物の見方"},
     {synonym:true,word:"negative",meaning:"否定的な",breakdown:"悪いほうに考えること全般"},
     {synonym:true,word:"doubtful",meaning:"疑っている",breakdown:"確信がないこと。cynical は善意を最初から信じない"}]},

  {id:2283,word:"savage",partOfSpeech:"形容詞",meaning:"（攻撃・批判が）容赦ない，激しい；どう猛な",
   meanings:["形|（攻撃・批判が）容赦ない，激しい","形|どう猛な，荒々しい"],
   pronunciation:"/ˈsævɪdʒ/",part:229,
   example:"The movie received savage criticism from the newspapers.",
   exampleJa:"その映画は、新聞各紙から容赦ない批判を受けた。",
   example2:"The farmer's sheep were killed in a savage attack by wolves.",
   exampleJa2:"その農家の羊たちは、オオカミのどう猛な襲撃で殺された。",
   etymologyProcess:"silv（森）→ 森にすむ獣のように荒々しいと…？",
   etymologyConclusion:"silv（森）→ 森の獣のように荒々しく、手加減しない＝（攻撃・批判が）容赦ない",
   spelling:"silv→sav（フランス語を通って変化）",
   why:"【なぜ】ラテン語 silvaticus は「森の、森に生えた」。人の手が入っていない森のものは「野生の、飼いならされていない」と考えられ、フランス語 sauvage を通って「荒々しい、どう猛な」の意味で英語に入りました。そこから今は、批判や攻撃が「手加減なしで激しい」ときにもよく使います。\n【つながり】Pennsylvania（ペンシルベニア）は「ペン家の森の土地」という意味です。",
   etymologyMore:["人に慣れない森の獣→どう猛な，荒々しい"],
   relatedWords:[
     {word:"Pennsylvania",meaning:"ペンシルベニア（州）",breakdown:"silv（森）→ ペン家の森の土地という州名"},
     {synonym:true,word:"fierce",meaning:"どう猛な；激しい",breakdown:"勢いが激しく恐ろしいこと"},
     {synonym:true,word:"wild",meaning:"野生の；乱暴な",breakdown:"人の手が入っていないこと。savage のもとの意味に近い"},
     {synonym:true,word:"cruel",meaning:"残酷な",breakdown:"わざと苦しめること。savage は荒々しさ"}]},

  {id:2284,word:"arbitrary",partOfSpeech:"形容詞",meaning:"独断的な，勝手な；でたらめな",
   meanings:["形|独断的な，勝手な","形|（選び方が）でたらめな，任意の"],
   pronunciation:"/ˈɑːrbɪtreri/",part:229,
   example:"The teacher's arbitrary rules made the students angry.",
   exampleJa:"先生の独断的な決まりに、生徒たちは腹を立てた。",
   example2:"The numbers in this list were chosen in an arbitrary way.",
   exampleJa2:"このリストの数字は、でたらめなやり方で選ばれた。",
   etymologyProcess:"arbitr（裁く人）＋ ary（形容詞）→ ひとりの判断だけで決めると…？",
   etymologyConclusion:"arbitr（裁く人）＋ ary（形容詞）→ 規則ではなく、裁く人ひとりの考えで決める＝独断的な",
   why:"【なぜ】ラテン語 arbiter は「争いを裁く人（仲裁人）」。arbitrarius は「仲裁人の判断にまかされた」という意味でした。決まった規則ではなく一人の考えしだい、という点が強調されて、「根拠なく勝手に決めた」「でたらめな」という意味に変わりました。\n【つながり】arbitration は今も「仲裁」の意味で使われます。",
   etymologyMore:["その人の考えしだいで決まる→（選び方が）でたらめな，任意の"],
   relatedWords:[
     {word:"arbitration",meaning:"仲裁",breakdown:"arbitr（裁く人）＋ ation（名詞）→ 第三者が間に入って裁く"},
     {synonym:true,word:"random",meaning:"でたらめな，無作為の",breakdown:"決まった順や理由がないこと"},
     {synonym:true,word:"unfair",meaning:"不公平な",breakdown:"un（否定）＋ fair（公平な）。arbitrary な決定はしばしば不公平"},
     {synonym:true,word:"selfish",meaning:"身勝手な",breakdown:"自分のことしか考えないこと"}]},

  {id:2285,word:"monotonous",partOfSpeech:"形容詞",meaning:"単調な，変化のない",
   meanings:["形|単調な，変化のない"],
   pronunciation:"/məˈnɑːtənəs/",part:229,
   example:"Working on the assembly line all day was monotonous and tiring.",
   exampleJa:"一日じゅう組み立てラインで働くのは、単調で疲れた。",
   example2:"The principal spoke in a monotonous voice for thirty minutes.",
   exampleJa2:"校長は30分間、単調な声で話した。",
   etymologyProcess:"mono（1つ）＋ ton（音の調子）＋ ous（～に満ちた）→ ずっと同じ調子だと…？",
   etymologyConclusion:"mono（1つ）＋ ton（音の調子）＋ ous（～に満ちた）→ ずっと1つの音の調子のまま変わらない＝単調な",
   relatedWords:[
     {word:"tone",meaning:"調子，口調",breakdown:"ton（音の調子）→ 声や音の上がり下がり"},
     {word:"intonation",meaning:"抑揚",breakdown:"in（中へ）＋ ton（音の調子）＋ ation（名詞）→ 声に調子をつけること"},
     {word:"monologue",meaning:"独白，ひとり語り",breakdown:"mono（1つ）＋ log（言葉）→ ひとりで語るせりふ"},
     {synonym:true,word:"boring",meaning:"退屈な",breakdown:"ふつうの「つまらない」。monotonous は変化がないから退屈"}]},

  {id:2286,word:"crude",partOfSpeech:"形容詞",meaning:"（作りが）粗末な，雑な；天然のままの",
   meanings:["形|（作りが）粗末な，雑な","形|天然のままの，未加工の","形|（言葉などが）下品な"],
   pronunciation:"/kruːd/",part:229,
   example:"The boys built a crude hut out of branches and leaves.",
   exampleJa:"少年たちは、枝と葉っぱで粗末な小屋を建てた。",
   example2:"The price of crude oil rose sharply last month.",
   exampleJa2:"先月、原油の価格が急激に上がった。",
   etymologyProcess:"cru（生の血）→ 生肉のように手が加わっていないと…？",
   etymologyConclusion:"cru（生の血）→ 生肉のように手が加わっておらず、仕上げがない＝（作りが）粗末な",
   etymologyMore:["手を加えていない生のまま→天然のままの，未加工の","磨かれず洗練されていない→（言葉などが）下品な"],
   hook:"crude oil（原油）は、精製する前の「生の」油。",
   relatedWords:[
     {word:"cruel",meaning:"残酷な",breakdown:"cru（生の血）→ 血を流しても平気なむごさ"},
     {word:"cruelty",meaning:"残酷さ",breakdown:"cru（生の血）＋ ty（名詞）→ 血を見ても平気な心"},
     {synonym:true,word:"rough",meaning:"粗い；大ざっぱな",breakdown:"表面や作りがざらざら。crude は仕上げが足りない"},
     {synonym:true,word:"raw",meaning:"生の",breakdown:"火を通していないこと。crude のもとの意味に近い"}]},

  {id:2287,word:"extravagant",partOfSpeech:"形容詞",meaning:"（お金の使い方が）ぜいたくな，浪費する；法外な",
   meanings:["形|（お金の使い方が）ぜいたくな，浪費する","形|（値段・要求が）法外な，度を越した"],
   pronunciation:"/ɪkˈstrævəɡənt/",part:229,
   example:"It was extravagant of him to buy a new car every year.",
   exampleJa:"毎年新車を買うなんて、彼はぜいたくだった。",
   example2:"The restaurant charges extravagant prices for a simple lunch.",
   exampleJa2:"その店は、簡単な昼食に法外な値段をとる。",
   etymologyProcess:"extra（範囲の外へ）＋ vag（さまよう）＋ ant（～な）→ 範囲の外へさまよい出ると…？",
   etymologyConclusion:"extra（範囲の外へ）＋ vag（さまよう）＋ ant（～な）→ ふつうの範囲の外までお金がさまよい出る＝（お金の使い方が）ぜいたくな",
   etymologyMore:["ふつうの範囲を外れる→（値段・要求が）法外な，度を越した"],
   relatedWords:[
     {word:"vague",meaning:"曖昧な",breakdown:"vag（さまよう）→ 考えがさまよってぼんやり"},
     {word:"extra",meaning:"余分の",breakdown:"extra（範囲の外へ）→ 決まった分の外の追加"},
     {word:"extraordinary",meaning:"並外れた",breakdown:"extra（範囲の外へ）＋ ord（順序）→ ふつうの順序の外にある"},
     {synonym:true,word:"wasteful",meaning:"むだの多い",breakdown:"waste（浪費する）＋ ful（満ちた）。むだづかいが多い"}]},

  {id:2288,word:"obsolete",partOfSpeech:"形容詞",meaning:"廃れた，時代遅れの",
   meanings:["形|廃れた，時代遅れの"],
   pronunciation:"/ˌɑːbsəˈliːt/",part:229,
   example:"Fax machines have become almost obsolete in many offices.",
   exampleJa:"多くの職場で、ファクスはほとんど廃れた機械になった。",
   example2:"This textbook is obsolete, so the school will replace it.",
   exampleJa2:"この教科書は時代遅れなので、学校は差しかえる予定だ。",
   etymologyProcess:"obsolesc（使われなくなる）→ だれにも使われなくなると…？",
   etymologyConclusion:"obsolesc（使われなくなる）→ 使われなくなって、時代から取り残された＝廃れた",
   spelling:"obsolesc→obsolet（過去分詞の形）",
   hook:"ラテン語 obsolescere（使われなくなる）から。solere（慣れている）に ob が付いた形。",
   relatedWords:[
     {word:"obsolescence",meaning:"廃れること，旧式化",breakdown:"obsolesc（使われなくなる）＋ ence（名詞）→ 古くなって使われなくなること"},
     {synonym:true,word:"outdated",meaning:"時代遅れの",breakdown:"out（外へ）＋ date（日付）。日付が過ぎて古い"},
     {synonym:true,word:"old-fashioned",meaning:"古風な，流行遅れの",breakdown:"昔のはやりのまま。obsolete はもう使われない"},
     {synonym:true,word:"ancient",meaning:"古代の",breakdown:"大昔のこと。obsolete は使われなくなったこと"}]},

  {id:2289,word:"devoid",partOfSpeech:"形容詞",meaning:"（of ～を）欠いている，～がまったくない",
   meanings:["形|（of ～を）欠いている，～がまったくない"],
   pronunciation:"/dɪˈvɔɪd/",part:229,
   usage:["be devoid of 名詞（～がまったくない）"],
   example:"The desert area is almost devoid of plants and animals.",
   exampleJa:"その砂漠地帯は、動植物をほとんど欠いている。",
   example2:"His speech was long but devoid of any real ideas.",
   exampleJa2:"彼の演説は長かったが、中身のある考えを欠いていた。",
   etymologyProcess:"de（すっかり）＋ void（空の）→ 中身がすっかり空になると…？",
   etymologyConclusion:"de（すっかり）＋ void（空の）→ 中身がすっかり空っぽになっている＝（of ～を）欠いている",
   relatedWords:[
     {word:"avoid",meaning:"避ける",breakdown:"ex（外へ）＋ void（空の）→ そこを空けて離れる"},
     {word:"void",meaning:"空の；無効の",breakdown:"void（空の）→ 中身がない、効き目がない"},
     {word:"vacant",meaning:"空いている",breakdown:"vac（空の）＋ ant（～な）→ だれも使っていない"},
     {word:"vacation",meaning:"休暇",breakdown:"vac（空の）＋ ation（名詞）→ 仕事を空ける休み"}]},

  {id:2290,word:"scarce",partOfSpeech:"形容詞",meaning:"（必要な量に比べて）乏しい，少ない",
   meanings:["形|（必要な量に比べて）乏しい，少ない","形|まれな，めったにない"],
   pronunciation:"/skers/",part:229,
   example:"Clean water is scarce in many parts of the world.",
   exampleJa:"世界の多くの地域で、きれいな水は乏しい。",
   example2:"Food became scarce during the war, so people grew their own vegetables.",
   exampleJa2:"戦争中は食料が乏しくなったので、人々は自分で野菜を育てた。",
   etymologyProcess:"ex（外へ）＋ carp（摘む）→ 実を摘み取られたあとの木は…？",
   etymologyConclusion:"ex（外へ）＋ carp（摘む）→ 摘み取られて、あとにはほとんど残っていない＝（必要な量に比べて）乏しい",
   spelling:"ex→s（フランス語を通って縮んだ）、carp→car",
   why:"【なぜ】scarce は古いフランス語 escars（けちな、乏しい）から来ていて、さらにラテン語 excarpere「摘み取る」にさかのぼると考えられています（はっきりしない部分もあります）。よい実を摘み取られたあとの木には少ししか残っていない、というイメージで「乏しい」とつながります。\n【つながり】副詞 scarcely は「ほとんど～ない」。",
   relatedWords:[
     {word:"excerpt",meaning:"抜粋",breakdown:"ex（外へ）＋ carp（摘む）→ 文章から摘み取った一部"},
     {word:"scarcity",meaning:"不足，欠乏",breakdown:"ex（外へ）＋ carp（摘む）＋ ity（名詞）→ 摘まれて少ない状態"},
     {synonym:true,word:"rare",meaning:"まれな",breakdown:"めったに見られないこと。scarce は必要な量に足りない"},
     {synonym:true,word:"short",meaning:"不足して",breakdown:"be short of で「～が足りない」"}]},

  {id:2291,word:"solemn",partOfSpeech:"形容詞",meaning:"厳粛な，おごそかな；まじめな",
   meanings:["形|厳粛な，おごそかな","形|（約束・表情が）真剣な，まじめな"],
   pronunciation:"/ˈsɑːləm/",part:230,
   example:"The graduation ceremony began in a solemn atmosphere.",
   exampleJa:"卒業式は厳粛な雰囲気の中で始まった。",
   example2:"He made a solemn promise never to lie to his parents again.",
   exampleJa2:"彼は二度と親にうそをつかないと、真剣な約束をした。",
   etymologyProcess:"sollemn（儀式の）→ 神にささげる儀式の場の空気は…？",
   etymologyConclusion:"sollemn（儀式の）→ 神にささげる儀式のように、ぴんと張りつめた＝厳粛な",
   spelling:"sollemn→solemn（l が1つに減った）",
   hook:"語源ははっきりしないが、もとは「毎年決まって行う宗教の儀式の」という意味。",
   etymologyMore:["儀式にのぞむような態度→（約束・表情が）真剣な，まじめな"],
   relatedWords:[
     {word:"solemnity",meaning:"厳粛さ",breakdown:"sollemn（儀式の）＋ ity（名詞）→ 儀式のようなおごそかさ"},
     {synonym:true,word:"serious",meaning:"まじめな；深刻な",breakdown:"ふざけていないこと。solemn は場の空気までおごそか"},
     {synonym:true,word:"formal",meaning:"正式な，堅苦しい",breakdown:"決まった形式にそっていること"},
     {synonym:true,word:"grave",meaning:"重大な；重々しい",breakdown:"重みがあって深刻なこと"}]},

  {id:2292,word:"rigid",partOfSpeech:"形容詞",meaning:"（物が）硬くて曲がらない；（規則が）厳格な",
   meanings:["形|（物が）硬くて曲がらない","形|（規則・考えが）厳格な，融通のきかない"],
   pronunciation:"/ˈrɪdʒɪd/",part:230,
   example:"The box is made of rigid plastic that does not bend easily.",
   exampleJa:"その箱は、簡単にはたわまない、硬くて曲がらないプラスチックでできている。",
   example2:"Our school has rigid rules about hair color and uniforms.",
   exampleJa2:"私たちの学校には、髪の色や制服について厳格な規則がある。",
   etymologyProcess:"rigor（こわばり）＋ id（～な状態の）→ ぴんとこわばっていると…？",
   etymologyConclusion:"rigor（こわばり）＋ id（～な状態の）→ こわばって、ぴんと固まっている＝（物が）硬くて曲がらない",
   spelling:"rigor→rig（rigor と同じ動詞 rigere の語幹）",
   etymologyMore:["こわばって曲げられない→（規則・考えが）厳格な，融通のきかない"],
   relatedWords:[
     {word:"rigorous",meaning:"厳密な，厳しい",breakdown:"rigor（こわばり）＋ ous（～に満ちた）→ 少しのゆるみも許さない"},
     {synonym:true,word:"stiff",meaning:"硬い，こわばった",breakdown:"曲げにくいこと。肩こりにも stiff を使う"},
     {synonym:true,word:"strict",meaning:"厳しい",breakdown:"規則を厳しく守らせること。rigid は融通がきかない"},
     {synonym:true,word:"hard",meaning:"硬い；難しい",breakdown:"いちばんふつうの「硬い」"}]},

  {id:2293,word:"robust",partOfSpeech:"形容詞",meaning:"（体・物が）頑丈な，たくましい；（経済などが）力強い",
   meanings:["形|（体・物が）頑丈な，たくましい","形|（経済・制度などが）力強い，しっかりした"],
   pronunciation:"/roʊˈbʌst/",part:230,
   example:"This robust laptop can survive being dropped on the floor.",
   exampleJa:"この頑丈なノートパソコンは、床に落としても壊れない。",
   example2:"The country's economy remained robust despite the crisis.",
   exampleJa2:"その国の経済は、危機にもかかわらず力強いままだった。",
   etymologyProcess:"robur（樫の木）→ 堅い樫の木のようだと…？",
   etymologyConclusion:"robur（樫の木）→ 堅い樫の木のようにがっしりして強い＝（体・物が）頑丈な",
   spelling:"robur→robus（ラテン語 robustus の形）",
   etymologyMore:["堅い木のようにびくともしない→（経済・制度などが）力強い，しっかりした"],
   relatedWords:[
     {word:"corroborate",meaning:"裏づける",breakdown:"com（すっかり）＋ robur（樫の木）→ 樫のように強くして支える"},
     {synonym:true,word:"strong",meaning:"強い",breakdown:"いちばんふつうの「強い」"},
     {synonym:true,word:"sturdy",meaning:"がっしりした",breakdown:"作りがしっかりして壊れにくいこと"},
     {synonym:true,word:"healthy",meaning:"健康な",breakdown:"体が元気なこと。robust は力強さまで含む"}]},

  {id:2294,word:"tangible",partOfSpeech:"形容詞",meaning:"（実際に）触れることのできる；目に見える，具体的な",
   meanings:["形|（実際に）触れることのできる","形|（成果などが）目に見える，具体的な"],
   pronunciation:"/ˈtændʒəbəl/",part:230,
   example:"Books and furniture are tangible objects, but ideas are not.",
   exampleJa:"本や家具は実際に触れることのできる物だが、考えはそうではない。",
   example2:"After months of practice, we finally saw tangible results in our matches.",
   exampleJa2:"何か月もの練習のあと、ついに試合で目に見える成果が出た。",
   etymologyProcess:"tang（触れる）＋ ible（できる）→ 手で実際にさわれると…？",
   etymologyConclusion:"tang（触れる）＋ ible（できる）→ 手で実際にさわって確かめられる＝（実際に）触れることのできる",
   etymologyMore:["手でつかめるほど確かな→（成果などが）目に見える，具体的な"],
   relatedWords:[
     {word:"contact",meaning:"接触；連絡",breakdown:"con（共に）＋ tact（触れる）→ 互いに触れ合う"},
     {word:"intact",meaning:"無傷の",breakdown:"in（否定）＋ tact（触れる）→ だれにも触れられず元のまま"},
     {word:"attain",meaning:"達成する",breakdown:"ad（～へ）＋ tang（触れる）→ 目標に手が触れる"},
     {synonym:true,word:"concrete",meaning:"具体的な",breakdown:"はっきりした形をもつこと。tangible は手でさわれるほど"}]},

  {id:2295,word:"superficial",partOfSpeech:"形容詞",meaning:"表面的な，うわべだけの；（傷が）浅い",
   meanings:["形|表面的な，うわべだけの","形|（傷が）表面の，浅い"],
   pronunciation:"/ˌsuːpərˈfɪʃəl/",part:230,
   example:"He only has a superficial knowledge of history.",
   exampleJa:"彼は歴史について表面的な知識しか持っていない。",
   example2:"Luckily, the cut on my knee was only superficial.",
   exampleJa2:"幸い、ひざの切り傷は表面の浅いものだった。",
   etymologyProcess:"super（上から）＋ faci（顔）＋ al（～の）→ いちばん上の面だけだと…？",
   etymologyConclusion:"super（上から）＋ faci（顔）＋ al（～の）→ いちばん上の面だけで、奥まで届かない＝表面的な",
   spelling:"faci→fici（ラテン語 superficies の形）",
   relatedWords:[
     {word:"surface",meaning:"表面",breakdown:"sur（上から）＋ face（顔）→ いちばん上に見える面"},
     {word:"face",meaning:"顔；表の面",breakdown:"face（顔）→ 人の顔、物の表側"},
     {word:"facial",meaning:"顔の",breakdown:"faci（顔）＋ al（～の）→ 顔にかかわる"},
     {synonym:true,word:"shallow",meaning:"浅い",breakdown:"深さがないこと。考えの浅さにも使う"}]},

  {id:2296,word:"spatial",partOfSpeech:"形容詞",meaning:"空間の，空間的な",
   meanings:["形|空間の，空間的な"],
   pronunciation:"/ˈspeɪʃəl/",part:230,
   example:"Playing with blocks helps children develop their spatial sense.",
   exampleJa:"積み木遊びは、子どもの空間の感覚を育てる助けになる。",
   example2:"Some students find it hard to imagine spatial figures in math class.",
   exampleJa2:"数学の授業で、空間の図形を思い描くのが苦手な生徒もいる。",
   etymologyProcess:"spati（空間）＋ al（～の）→ 広がりや位置にかかわると…？",
   etymologyConclusion:"spati（空間）＋ al（～の）→ 物の広がりや位置の関係にかかわる＝空間の",
   relatedWords:[
     {word:"space",meaning:"空間；宇宙",breakdown:"spati（空間）→ 何もない広がり、宇宙"},
     {word:"spacious",meaning:"広々とした",breakdown:"spati（空間）＋ ous（～に満ちた）→ 空間がたっぷりある"},
     {synonym:true,word:"area",meaning:"地域；面積",breakdown:"平面の広がり。spatial は立体の広がりも含む"},
     {synonym:true,word:"dimension",meaning:"寸法；次元",breakdown:"縦・横・高さなどの広がりの向き"}]},

  {id:2297,word:"hollow",partOfSpeech:"形容詞",meaning:"中が空洞の，うつろな；（言葉が）むなしい",
   meanings:["形|中が空洞の，うつろな","形|（言葉・約束が）むなしい，うわべだけの","名|くぼみ，穴"],
   pronunciation:"/ˈhɑːloʊ/",part:230,
   example:"The squirrel hid its nuts inside a hollow tree.",
   exampleJa:"リスは、中が空洞の木の中に木の実を隠した。",
   example2:"Without real action, his promises sounded hollow to the voters.",
   exampleJa2:"実際の行動がないので、彼の約束は有権者にむなしく聞こえた。",
   etymologyProcess:"hole（穴）→ 中がくりぬかれていると…？",
   etymologyConclusion:"hole（穴）→ 中がくりぬかれて、ぽっかり穴になっている＝中が空洞の",
   etymologyMore:["中身がからっぽ→（言葉・約束が）むなしい，うわべだけの"],
   hook:"hole（穴）と同じ古英語の家族。木の幹のうろも a hollow と言う。",
   relatedWords:[
     {word:"hole",meaning:"穴",breakdown:"hole（穴）→ ぽっかりあいたすき間"},
     {synonym:true,word:"empty",meaning:"空の",breakdown:"中身がないこと全般。hollow は形の中が空洞"},
     {synonym:true,word:"cave",meaning:"洞窟",breakdown:"中が空洞になった岩の穴"},
     {synonym:true,word:"vacant",meaning:"空いている",breakdown:"部屋や席がだれにも使われていないこと"}]},

  {id:2298,word:"homogeneous",partOfSpeech:"形容詞",meaning:"均質の，同じ種類からなる",
   meanings:["形|均質の，同じ種類からなる"],
   pronunciation:"/ˌhoʊməˈdʒiːniəs/",part:230,
   example:"Mix the flour and water until the mixture is homogeneous.",
   exampleJa:"混ぜたものが均質になるまで、小麦粉と水を混ぜなさい。",
   example2:"Our town used to be a homogeneous community, but now it is diverse.",
   exampleJa2:"私たちの町はかつて均質な社会だったが、今では多様だ。",
   etymologyProcess:"homo（同じ）＋ gen（生み出す）＋ ous（～に満ちた）→ 同じもとから生まれたものばかりだと…？",
   etymologyConclusion:"homo（同じ）＋ gen（生み出す）＋ ous（～に満ちた）→ 同じもとから生まれたものばかりでできている＝均質の",
   relatedWords:[
     {word:"gene",meaning:"遺伝子",breakdown:"gen（生み出す）→ 生き物を形づくるもと"},
     {word:"generation",meaning:"世代",breakdown:"gener（生み出す）＋ ation（名詞）→ 同じころに生まれた人々"},
     {synonym:true,word:"similar",meaning:"似ている",breakdown:"よく似ていること。homogeneous は全体が同じ性質"},
     {synonym:true,word:"uniform",meaning:"一様な；制服",breakdown:"どこも同じ形であること"}]},

  {id:2299,word:"feasible",partOfSpeech:"形容詞",meaning:"（計画などが）実現可能な，実行できる",
   meanings:["形|（計画などが）実現可能な，実行できる"],
   pronunciation:"/ˈfiːzəbəl/",part:230,
   example:"Is it feasible to finish the project by next Friday?",
   exampleJa:"来週の金曜日までにその計画を終えるのは、実現可能ですか。",
   example2:"The class decided that a trip abroad was not financially feasible.",
   exampleJa2:"クラスは、海外旅行はお金の面で実現可能ではないと判断した。",
   etymologyProcess:"fac（作る）＋ ible（できる）→ 実際にやって形にできると…？",
   etymologyConclusion:"fac（作る）＋ ible（できる）→ 実際にやって形にすることができる＝（計画などが）実現可能な",
   spelling:"fac→feas（フランス語 faire を通って変化）",
   relatedWords:[
     {word:"factory",meaning:"工場",breakdown:"fac（作る）＋ ory（場所）→ 物を作る場所"},
     {word:"feature",meaning:"特徴",breakdown:"feat（作る）＋ ure（名詞）→ 作られた形、目立つところ"},
     {word:"affair",meaning:"出来事；事柄",breakdown:"ad（～へ）＋ fac（作る）→ するべきこと、起きたこと"},
     {synonym:true,word:"possible",meaning:"可能な",breakdown:"ふつうの「できる」。feasible は計画が現実にやれる"}]},

  {id:2300,word:"viable",partOfSpeech:"形容詞",meaning:"（計画・事業が）成り立つ，実行可能な；生存できる",
   meanings:["形|（計画・事業が）成り立つ，実行可能な","形|（生物が）生存できる"],
   pronunciation:"/ˈvaɪəbəl/",part:230,
   example:"We need a viable plan to reduce waste at our school.",
   exampleJa:"学校のごみを減らすための、ちゃんと成り立つ計画が必要だ。",
   example2:"Without more customers, the small shop is no longer viable.",
   exampleJa2:"客が増えなければ、その小さな店はもう成り立たない。",
   etymologyProcess:"viv（生きる）＋ able（できる）→ 計画が生き続けられると…？",
   etymologyConclusion:"viv（生きる）＋ able（できる）→ 計画が命をもったように生き続けられる＝（計画・事業が）成り立つ",
   spelling:"viv→vi（フランス語 vie「命」を通って変化）",
   why:"【なぜ】viable はフランス語 vie（命）から来た語で、もとは「生まれた子や種が生きていける」という意味でした。そこから、計画や事業が途中で倒れずに「生き残っていける」、つまり現実に成り立つ、実行可能だという意味に広がりました。\n【つながり】経済のニュースでは a viable business（成り立つ商売）のように使います。",
   etymologyMore:["もとは生き物が生きていけること→（生物が）生存できる"],
   relatedWords:[
     {word:"survive",meaning:"生き残る",breakdown:"sur（上を越えて）＋ viv（生きる）→ 危機を越えて生き続ける"},
     {word:"revive",meaning:"生き返らせる",breakdown:"re（再び）＋ viv（生きる）→ もう一度生かす"},
     {word:"vivid",meaning:"鮮やかな",breakdown:"viv（生きる）＋ id（～な状態の）→ 生き生きとした"},
     {synonym:true,word:"feasible",meaning:"実現可能な",breakdown:"計画が実際にやれること。viable は続けて成り立つこと"}]},
