  {id:1751,word:"contaminate",partOfSpeech:"他動詞",meaning:"（有害物質で）汚染する；（心を）けがす",
   meanings:["他|（有害物質などで）汚染する","他|（考え・心を）けがす，悪影響を与える"],
   pronunciation:"/kənˈtæmɪneɪt/",part:176,
   example:"Chemicals from the factory contaminated the river for many years.",
   exampleJa:"工場から出た化学物質が、長年にわたって川を汚染した。",
   example2:"The water in this old well may be contaminated with bacteria.",
   exampleJa2:"この古い井戸の水は、細菌で汚染されているかもしれない。",
   etymologyProcess:"con（共に）＋ tang（触れる）→ 汚れたものと触れ合わせると…？",
   etymologyConclusion:"con（共に）＋ tang（触れる）＋ ate（動詞）→ 汚いものに触れさせて中まで汚す＝（有害物質で）汚染する",
   why:"【なぜ】ラテン語 contaminare は「触れ合わせる」がもとの意味。清いものが汚れたものに触れると、その汚れが移ってしまう、という考えから「けがす・汚す」の意味になりました。\n【つながり】contact（接触）や tangible（触れられる）も「触れる」の仲間。病気の「接触感染」を思い出すと、触れる→汚れが移る、の流れがつかめます。",
   spelling:"tang→tamin（ラテン語 contamen の形から）",
   etymologyMore:["汚れが心にまで移ってしまう→（考え・心を）けがす，悪影響を与える"],
   relatedWords:[
     {word:"contact",meaning:"接触；連絡を取る",breakdown:"con（共に）＋ tact（触れる）→ お互いに触れ合う"},
     {word:"tangible",meaning:"触れられる；明白な",breakdown:"tang（触れる）＋ ible（できる）→ 手で触れて確かめられる"},
     {word:"intact",meaning:"無傷の，そのままの",breakdown:"in（否定）＋ tact（触れる）→ だれにも触れられていない"},
     {synonym:true,word:"pollute",meaning:"汚染する",breakdown:"空気・水・土地を広く汚す。contaminate は有害物が混じる"}]},

  {id:1752,word:"erupt",partOfSpeech:"自動詞",meaning:"（火山が）噴火する；（争いが）急に起こる",
   meanings:["自|（火山が）噴火する","自|（争い・感情が）急に起こる，爆発する"],
   pronunciation:"/ɪˈrʌpt/",part:176,
   example:"The volcano erupted suddenly, and nearby towns were covered with ash.",
   exampleJa:"その火山は突然噴火し、近くの町は灰に覆われた。",
   example2:"Fighting could erupt again if the peace talks fail.",
   exampleJa2:"和平交渉が失敗すれば、再び戦闘が起こるかもしれない。",
   etymologyProcess:"e（外へ）＋ rupt（破る）→ 地面を破って外へ吹き出すと…？",
   etymologyConclusion:"e（外へ）＋ rupt（破る）→ 山が地面を破り、溶岩を外へ吹き出す＝（火山が）噴火する",
   etymologyMore:["閉じこめた力が破れて外へ出る→（争い・感情が）急に起こる，爆発する"],
   relatedWords:[
     {word:"interrupt",meaning:"じゃまをする，さえぎる",breakdown:"inter（間の）＋ rupt（破る）→ 話の間に割りこんで破る"},
     {word:"route",meaning:"道筋，ルート",breakdown:"rupt（破る）→ 森を切り開いて通した道"},
     {word:"bankrupt",meaning:"破産した",breakdown:"bank（両替台）＋ rupt（破る）→ 商売の台が壊された"},
     {word:"corrupt",meaning:"堕落した，不正な",breakdown:"cor（共に）＋ rupt（破る）→ まるごと壊れて中から腐った"}]},

  {id:1753,word:"roar",partOfSpeech:"自動詞",meaning:"（猛獣が）ほえる；とどろく",
   meanings:["自|（ライオンなどが）ほえる，うなる","自|（エンジン・群衆が）とどろく，大声を上げる","名|ほえ声；とどろき"],
   pronunciation:"/rɔːr/",part:176,
   example:"We heard a lion roar loudly from the other side of the zoo.",
   exampleJa:"動物園の反対側から、ライオンが大きくほえるのが聞こえた。",
   example2:"The crowd roared with excitement when the band came on stage.",
   exampleJa2:"バンドがステージに現れると、観衆は興奮して大声を上げた。",
   etymologyProcess:"roar（うなる声）→ 猛獣が低く大きな声を出すと…？",
   etymologyConclusion:"roar（うなる声）→ ライオンのように低く大きな声でうなる＝（猛獣が）ほえる",
   hook:"古英語の擬音語で「ガオー」の声そのもの。roar with laughter は「大笑いする」。",
   etymologyMore:["うなり声のように大きく響く→（エンジン・群衆が）とどろく，大声を上げる"],
   relatedWords:[
     {synonym:true,word:"bark",meaning:"（犬が）ほえる",breakdown:"犬のワンワン。roar はライオンなどの低く太い声"},
     {synonym:true,word:"scream",meaning:"悲鳴を上げる",breakdown:"高く鋭い叫び声。roar は低くとどろく声"},
     {synonym:true,word:"howl",meaning:"遠ぼえする",breakdown:"オオカミが長く尾を引いて鳴く。roar は短く力強い"},
     {synonym:true,word:"growl",meaning:"うなる",breakdown:"低い声でうなって威嚇する。roar はもっと大きい"}]},

  {id:1754,word:"inhabit",partOfSpeech:"他動詞",meaning:"（場所に）住む，生息する",
   meanings:["他|（場所に）住む，生息する"],
   pronunciation:"/ɪnˈhæbɪt/",part:176,
   example:"Many rare birds inhabit the forests on this small island.",
   exampleJa:"この小さな島の森には、多くの珍しい鳥が住んでいる。",
   example2:"The cave was inhabited by people thousands of years ago.",
   exampleJa2:"その洞窟には、何千年も前に人が住んでいた。",
   usage:["inhabit 場所（場所に住む。in は付けない）"],
   etymologyProcess:"in（～に）＋ habit（持ち続ける）→ ある場所に居続けると…？",
   etymologyConclusion:"in（～に）＋ habit（持ち続ける）→ ある場所に身を置き続けて暮らす＝（場所に）住む，生息する",
   relatedWords:[
     {word:"habitat",meaning:"生息地",breakdown:"habit（持ち続ける）→ 生き物がいつも居続ける場所"},
     {word:"habit",meaning:"習慣，くせ",breakdown:"habit（持ち続ける）→ ずっと持ち続けているふるまい"},
     {word:"inhabitant",meaning:"住民",breakdown:"in（～に）＋ habit（持ち続ける）＋ ant（人）→ そこに住む人"},
     {synonym:true,word:"live",meaning:"住む",breakdown:"ふつうの「住む」。inhabit は動物にも使うかたい語"}]},

  {id:1755,word:"nurture",partOfSpeech:"他動詞",meaning:"（大切に）育てる；（才能を）はぐくむ",
   meanings:["他|（子ども・植物を）大切に育てる","他|（才能・関係を）はぐくむ，養う","名|養育，しつけ"],
   pronunciation:"/ˈnɜːrtʃər/",part:176,
   example:"Parents nurture their children with love and patience.",
   exampleJa:"親は愛情と忍耐をもって、子どもを大切に育てる。",
   example2:"Our coach nurtured a strong team spirit in the club.",
   exampleJa2:"コーチは部の中に強い団結心をはぐくんだ。",
   etymologyProcess:"nutri（養い育てる）→ 栄養を与え続けて手をかけると…？",
   etymologyConclusion:"nutri（養い育てる）＋ ure（名詞）→ 栄養を与えて手をかけて育てる＝（大切に）育てる",
   spelling:"nutri→nurt（フランス語を通って縮まった）",
   etymologyMore:["心や力に栄養を与える→（才能・関係を）はぐくむ，養う"],
   relatedWords:[
     {word:"nurse",meaning:"看護師",breakdown:"nurs（養い育てる）→ 病人の世話をして元気にする人"},
     {word:"nutrition",meaning:"栄養",breakdown:"nutri（養い育てる）＋ tion（名詞）→ 体を養うもの"},
     {word:"nursery",meaning:"保育園",breakdown:"nurs（養い育てる）＋ ery（場所）→ 幼い子を育てる場所"},
     {word:"nourish",meaning:"栄養を与える",breakdown:"nour（養い育てる）→ 食べ物で体を養う"}]},

  {id:1756,word:"owl",partOfSpeech:"名詞",meaning:"フクロウ",
   meanings:["名|フクロウ"],
   pronunciation:"/aʊl/",part:176,
   example:"We heard an owl hooting in the dark forest last night.",
   exampleJa:"昨夜、暗い森でフクロウがホーホーと鳴くのが聞こえた。",
   example2:"My brother is a night owl who often studies until three.",
   exampleJa2:"兄は夜型の人で、よく3時まで勉強している。",
   etymologyProcess:"owl（ホーと鳴く鳥）→ 夜の森でホーと鳴く鳥は…？",
   etymologyConclusion:"owl（ホーと鳴く鳥）→ 夜に大きな目で獲物を探し、ホーと鳴く鳥＝フクロウ",
   hook:"鳴き声をまねて生まれた古英語。夜に起きているので night owl は「夜型の人」。",
   relatedWords:[
     {synonym:true,word:"bird",meaning:"鳥",breakdown:"鳥全般。owl は夜に狩りをする鳥"},
     {synonym:true,word:"eagle",meaning:"ワシ",breakdown:"昼に空高く飛ぶ大きな猛禽。owl は夜の猛禽"},
     {synonym:true,word:"hawk",meaning:"タカ",breakdown:"昼に狩りをする猛禽。owl と同じく肉食の鳥"},
     {synonym:true,word:"bat",meaning:"コウモリ",breakdown:"夜に飛ぶ哺乳動物。owl と同じ夜の生き物"}]},

  {id:1757,word:"instinct",partOfSpeech:"名詞",meaning:"本能；（とっさの）勘",
   meanings:["名|本能","名|（とっさの）勘，直感","名|（for ～の）天性の才能"],
   pronunciation:"/ˈɪnstɪŋkt/",part:176,
   example:"Birds build nests by instinct, without being taught by anyone.",
   exampleJa:"鳥はだれにも教わらずに、本能で巣を作る。",
   example2:"Trust your instincts when you choose an answer on the test.",
   exampleJa2:"テストで答えを選ぶときは、自分の勘を信じなさい。",
   etymologyProcess:"in（中へ）＋ stingu（突き刺す）→ 内側からつついて動かす力は…？",
   etymologyConclusion:"in（中へ）＋ stingu（突き刺す）→ 内側からつついて体を動かす生まれつきの力＝本能",
   spelling:"stingu→stinct（ラテン語の過去分詞の形）",
   etymologyMore:["考える前に内側からつつかれる→（とっさの）勘，直感"],
   relatedWords:[
     {word:"distinguish",meaning:"区別する",breakdown:"dis（離れて）＋ stingu（突き刺す）→ 印を刺して分け離す"},
     {word:"distinct",meaning:"はっきり異なる",breakdown:"dis（離れて）＋ stingu（突き刺す）→ 刺して分けた後の、別々の"},
     {word:"instinctive",meaning:"本能的な",breakdown:"in（中へ）＋ stingu（突き刺す）＋ ive（形容詞）→ 内から動かされる"},
     {synonym:true,word:"sense",meaning:"感覚",breakdown:"体や心で感じとる力。instinct は生まれつきの力"}]},

  {id:1758,word:"prey",partOfSpeech:"名詞",meaning:"（捕食される）獲物，餌食",
   meanings:["名|（捕食される）獲物，餌食","名|（悪人などの）犠牲者，食い物","自|（on ～を）捕食する"],
   pronunciation:"/preɪ/",part:176,
   example:"The hawk dived down and caught its prey in the field.",
   exampleJa:"タカは急降下して、野原で獲物を捕らえた。",
   example2:"Lions prey on zebras and other large animals.",
   exampleJa2:"ライオンはシマウマなどの大型動物を捕食する。",
   usage:["prey on 動物（動物を捕食する）","fall prey to A（A の餌食になる）"],
   etymologyProcess:"pred（奪ったもの）→ 狩りで奪い取られる動物は…？",
   etymologyConclusion:"pred（奪ったもの）→ 狩る側に奪い取られて食べられる動物＝（捕食される）獲物",
   spelling:"pred→prey（フランス語を通って変化）",
   etymologyMore:["強い者に奪われる弱い者→（悪人などの）犠牲者，食い物"],
   relatedWords:[
     {word:"predator",meaning:"捕食動物",breakdown:"pred（奪ったもの）＋ ator（人）→ 獲物を奪って食べるもの"},
     {word:"predatory",meaning:"捕食性の；食い物にする",breakdown:"pred（奪ったもの）＋ ory（形容詞）→ 奪って食べる性質の"},
     {synonym:true,word:"victim",meaning:"犠牲者",breakdown:"被害を受けた人。prey は狙われ食べられる側"},
     {synonym:true,word:"hunt",meaning:"狩りをする",breakdown:"獲物を追いかけてつかまえる。その相手が prey"}]},

  {id:1759,word:"anatomy",partOfSpeech:"名詞",meaning:"解剖学；（生物の）体の構造",
   meanings:["名|解剖学","名|（生物の）体の構造","名|（物事の）詳しい分析"],
   pronunciation:"/əˈnætəmi/",part:176,
   example:"Medical students study anatomy to learn how the body works.",
   exampleJa:"医学生は体の仕組みを知るために解剖学を学ぶ。",
   example2:"We learned about the anatomy of a frog in biology class.",
   exampleJa2:"生物の授業で、カエルの体の構造について学んだ。",
   etymologyProcess:"ana（すっかり）＋ tom（切る）→ 体をすっかり切り開く学問は…？",
   etymologyConclusion:"ana（すっかり）＋ tom（切る）＋ y（名詞）→ 体を切り開いて中の仕組みを調べる学問＝解剖学",
   etymologyMore:["切り開いて見える中の組み立て→（生物の）体の構造"],
   relatedWords:[
     {synonym:true,word:"dissect",meaning:"解剖する",breakdown:"dis（バラバラに）＋ sect（切る）。anatomy と同じ「切る」発想"},
     {word:"anatomical",meaning:"解剖学の",breakdown:"ana（すっかり）＋ tom（切る）＋ ical（～の）→ 切り開く学問の"},
     {word:"analysis",meaning:"分析",breakdown:"ana（すっかり）＋ lys（ほどく）→ すっかりほどいて調べる"},
     {synonym:true,word:"biology",meaning:"生物学",breakdown:"生き物全体を調べる学問。anatomy は体のつくりを見る"}]},

  {id:1760,word:"mammal",partOfSpeech:"名詞",meaning:"哺乳動物",
   meanings:["名|哺乳動物"],
   pronunciation:"/ˈmæməl/",part:176,
   example:"Whales are mammals, so they breathe air just like we do.",
   exampleJa:"クジラは哺乳動物なので、私たちと同じように空気を吸う。",
   example2:"The bat is the only mammal that can really fly.",
   exampleJa2:"コウモリは本当に空を飛べる唯一の哺乳動物だ。",
   etymologyProcess:"mamm（乳房）→ 母親の乳で子を育てる動物は…？",
   etymologyConclusion:"mamm（乳房）＋ al（～の）→ 母親が乳を飲ませて子を育てる動物＝哺乳動物",
   relatedWords:[
     {word:"mammary",meaning:"乳房の",breakdown:"mamm（乳房）＋ ary（形容詞）→ 乳を出すところの"},
     {synonym:true,word:"animal",meaning:"動物",breakdown:"動物全般。mammal は乳で子を育てる仲間"},
     {synonym:true,word:"reptile",meaning:"爬虫類",breakdown:"ヘビやトカゲの仲間（多くは卵から）。mammal と並ぶ分類"},
     {synonym:true,word:"creature",meaning:"生き物",breakdown:"生きているもの全般。mammal はその中の一群"}]},

  {id:1761,word:"predator",partOfSpeech:"名詞",meaning:"捕食動物；（弱い者を）食い物にする人",
   meanings:["名|捕食動物","名|（弱い者を）食い物にする人"],
   pronunciation:"/ˈpredətər/",part:177,
   example:"Lions are top predators, so few animals ever hunt them.",
   exampleJa:"ライオンは頂点に立つ捕食動物なので、ライオンを狩る動物はほとんどいない。",
   example2:"Be careful of online predators who pretend to be your friends.",
   exampleJa2:"友達のふりをしてネットで人を食い物にする者に気をつけなさい。",
   etymologyProcess:"pred（奪ったもの）＋ ator（人）→ 獲物を奪い取るものは…？",
   etymologyConclusion:"pred（奪ったもの）＋ ator（人）→ ほかの動物を奪い取って食べる動物＝捕食動物",
   etymologyMore:["弱い相手から奪い取る者→（弱い者を）食い物にする人"],
   relatedWords:[
     {word:"prey",meaning:"獲物，餌食",breakdown:"pred（奪ったもの）→ 狩る側に奪われて食べられる動物"},
     {word:"predatory",meaning:"捕食性の",breakdown:"pred（奪ったもの）＋ ory（形容詞）→ 奪って食べる性質の"},
     {synonym:true,word:"hunter",meaning:"狩りをする人",breakdown:"獲物を追う人や動物。predator は食べるために襲う動物"},
     {synonym:true,word:"enemy",meaning:"敵",breakdown:"争う相手。natural enemy（天敵）は predator に近い"}]},

  {id:1762,word:"hybrid",partOfSpeech:"名詞",meaning:"（動植物の）交配種；混成のもの",
   meanings:["名|（動植物の）交配種，雑種","名|（異なるものの）混成，ハイブリッド","形|混成の"],
   pronunciation:"/ˈhaɪbrɪd/",part:177,
   example:"This rose is a hybrid of two different wild species.",
   exampleJa:"このバラは、2つの異なる野生種の交配種だ。",
   example2:"My father drives a hybrid car that uses less gasoline.",
   exampleJa2:"父はガソリンをあまり使わないハイブリッド車に乗っている。",
   etymologyProcess:"hybrid（混ざった子）→ 種類の違う親から生まれた子は…？",
   etymologyConclusion:"hybrid（混ざった子）→ 種類の違う親をかけ合わせて生まれた子＝（動植物の）交配種",
   hook:"ラテン語で「飼い豚とイノシシの子」。そこから先の語源ははっきりしない。車の「ハイブリッド」も同じ語。",
   etymologyMore:["違う種類を1つに混ぜ合わせる→（異なるものの）混成，ハイブリッド"],
   relatedWords:[
     {synonym:true,word:"mix",meaning:"混ぜる；混合",breakdown:"ものを混ぜること全般。hybrid は混ざってできた新しい種"},
     {synonym:true,word:"blend",meaning:"混ぜ合わせる",breakdown:"なめらかに混ぜる。コーヒーの「ブレンド」"},
     {synonym:true,word:"mixture",meaning:"混合物",breakdown:"混ぜてできたもの。hybrid は生き物や仕組みに使う"},
     {synonym:true,word:"cross",meaning:"交配する；交配種",breakdown:"2つの種をかけ合わせる。その結果が hybrid"}]},

  {id:1763,word:"skull",partOfSpeech:"名詞",meaning:"頭蓋骨",
   meanings:["名|頭蓋骨","名|（くだけて）頭，頭脳"],
   pronunciation:"/skʌl/",part:177,
   example:"The doctor showed us an X-ray of the patient's skull.",
   exampleJa:"医者は私たちに患者の頭蓋骨のレントゲン写真を見せた。",
   example2:"A helmet protects your skull if you fall off your bike.",
   exampleJa2:"自転車から落ちても、ヘルメットが頭蓋骨を守ってくれる。",
   etymologyProcess:"skull（頭の骨）→ 脳を包みこむ固い骨は…？",
   etymologyConclusion:"skull（頭の骨）→ 脳を守るように包んでいる頭の骨＝頭蓋骨",
   hook:"北欧の言葉から来た語。海賊旗のドクロマークは英語で skull and crossbones。",
   relatedWords:[
     {synonym:true,word:"bone",meaning:"骨",breakdown:"骨全般。skull は頭の骨"},
     {synonym:true,word:"brain",meaning:"脳",breakdown:"skull の中に守られている器官"},
     {synonym:true,word:"head",meaning:"頭",breakdown:"首から上の部分。skull はその骨組み"},
     {synonym:true,word:"skeleton",meaning:"骸骨，骨格",breakdown:"体全体の骨組み。skull はそのいちばん上"}]},

  {id:1764,word:"timber",partOfSpeech:"名詞",meaning:"（建築用の）材木",
   meanings:["名|（建築用の）材木，木材","名|（材木用の）立ち木，森林"],
   pronunciation:"/ˈtɪmbər/",part:177,
   example:"The old house was built with timber from local forests.",
   exampleJa:"その古い家は、地元の森で取れた材木で建てられた。",
   example2:"Too much timber has been cut from the rainforest.",
   exampleJa2:"熱帯雨林からあまりにも多くの材木が切り出されてきた。",
   etymologyProcess:"timber（建てる材料）→ 家を建てるための木は…？",
   etymologyConclusion:"timber（建てる材料）→ 家や船を建てるために切り出した木＝（建築用の）材木",
   hook:"古英語で「建物，建てる材料」。ドイツ語の Zimmer（部屋）と同じ家族の語。",
   relatedWords:[
     {synonym:true,word:"wood",meaning:"木材；森",breakdown:"木という材料全般。timber は建築に使う木"},
     {synonym:true,word:"lumber",meaning:"（米）材木",breakdown:"板や角材に切った木。アメリカでよく使う"},
     {synonym:true,word:"log",meaning:"丸太",breakdown:"切り倒したままの幹。これを切ると timber になる"},
     {synonym:true,word:"board",meaning:"板",breakdown:"薄く平らに切った木。timber から作る"}]},

  {id:1765,word:"textile",partOfSpeech:"名詞",meaning:"織物；（textiles で）繊維産業",
   meanings:["名|織物","名|（textiles で）繊維産業"],
   pronunciation:"/ˈtekstaɪl/",part:177,
   example:"This town was once famous for producing cotton textiles.",
   exampleJa:"この町はかつて、綿の織物を作ることで有名だった。",
   example2:"Many people in the city used to work in textiles.",
   exampleJa2:"その都市では、かつて多くの人が繊維産業で働いていた。",
   etymologyProcess:"tex（織る）＋ ile（できる）→ 糸を織ってできるものは…？",
   etymologyConclusion:"tex（織る）＋ ile（できる）→ 糸を縦横に織って作った布＝織物",
   etymologyMore:["織物を作る仕事全体→（textiles で）繊維産業"],
   relatedWords:[
     {word:"text",meaning:"文章，本文",breakdown:"tex（織る）→ 言葉を織り合わせて作った文章"},
     {word:"texture",meaning:"手ざわり，質感",breakdown:"tex（織る）＋ ure（名詞）→ 織り目から感じる手ざわり"},
     {word:"context",meaning:"文脈，状況",breakdown:"con（共に）＋ tex（織る）→ 前後が織り合わさった流れ"},
     {synonym:true,word:"cloth",meaning:"布",breakdown:"ふつうの「布」。textile は織って作った布全般のかたい語"}]},

  {id:1766,word:"fabric",partOfSpeech:"名詞",meaning:"布地，生地；（社会の）構造",
   meanings:["名|布地，生地","名|（社会などの）構造，骨組み"],
   pronunciation:"/ˈfæbrɪk/",part:177,
   example:"She chose a soft cotton fabric for her new dress.",
   exampleJa:"彼女は新しいドレスに、柔らかい綿の布地を選んだ。",
   example2:"Crime can slowly damage the fabric of our society.",
   exampleJa2:"犯罪は私たちの社会の構造を少しずつ傷つけることがある。",
   etymologyProcess:"fabr（職人）＋ ic（名詞）→ 職人の手で組み立てられた物は…？",
   etymologyConclusion:"fabr（職人）＋ ic（名詞）→ 職人の手で組み立てられた物から、織った布へ＝布地，生地",
   why:"【なぜ】ラテン語 fabrica は「職人の仕事場」や「組み立てて作った物」。英語でも初めは建物のような組み立てられた物を指しましたが、やがて糸を織って作る物＝布地に意味がしぼられました。\n【つながり】the fabric of society（社会の骨組み）には、今も「組み立て・構造」の意味が残っています。",
   relatedWords:[
     {word:"fabricate",meaning:"でっち上げる；製造する",breakdown:"fabr（職人）＋ ate（動詞）→ 職人のように手を加えて作り上げる"},
     {word:"forge",meaning:"（鉄を）鍛える；偽造する",breakdown:"fabr（職人）→ 鍛冶職人の仕事場で鉄を打つ"},
     {synonym:true,word:"cloth",meaning:"布",breakdown:"ふつうの「布」。fabric は服を作る生地を言うことが多い"},
     {synonym:true,word:"material",meaning:"生地；材料",breakdown:"服の材料としての布。fabric とほぼ同じ意味で使う"}]},

  {id:1767,word:"mill",partOfSpeech:"名詞",meaning:"（紙・布などの）製造工場；製粉所",
   meanings:["名|（紙・布・鉄などの）製造工場","名|製粉所，水車小屋","名|（コーヒーなどの）ひき器"],
   pronunciation:"/mɪl/",part:177,
   example:"My grandfather worked at a paper mill for forty years.",
   exampleJa:"祖父は40年間、製紙工場で働いた。",
   example2:"The old mill by the river once made flour from wheat.",
   exampleJa2:"川沿いの古い製粉所は、かつて小麦から小麦粉を作っていた。",
   etymologyProcess:"mill（粉をひく）→ 穀物をひく小屋が機械の場所になると…？",
   etymologyConclusion:"mill（粉をひく）→ 穀物をひく水車小屋から、機械で物を作る場所へ＝（紙・布などの）製造工場",
   hook:"コーヒーミル・ペッパーミルの「ミル」。粉をひく道具から、ひく場所、そして工場へ広がった。",
   etymologyMore:["もとの穀物をひく場所→製粉所，水車小屋"],
   relatedWords:[
     {synonym:true,word:"factory",meaning:"工場",breakdown:"ふつうの「工場」。mill は紙・布・鉄などの素材の工場"},
     {synonym:true,word:"plant",meaning:"（大規模な）工場",breakdown:"発電所や化学工場などの大きな設備"},
     {synonym:true,word:"grind",meaning:"（粉に）ひく",breakdown:"mill で行う作業。穀物やコーヒー豆を粉にする"},
     {synonym:true,word:"flour",meaning:"小麦粉",breakdown:"mill で小麦をひいて作る粉"}]},

  {id:1768,word:"weave",partOfSpeech:"他動詞",meaning:"（布を）織る；（話を）組み立てる",
   meanings:["他|（布・かごを）織る，編む","他|（話・計画を）組み立てる","自|（車・人の間を）縫うように進む"],
   pronunciation:"/wiːv/",part:177,
   example:"My grandmother still weaves cloth on an old wooden loom.",
   exampleJa:"祖母は今でも、古い木の機織り機で布を織っている。",
   example2:"The runner was weaving through the crowd toward the finish line.",
   exampleJa2:"そのランナーは、ゴールに向かって人ごみを縫うように進んでいた。",
   etymologyProcess:"weave（織る）→ 縦糸に横糸を交互にくぐらせると…？",
   etymologyConclusion:"weave（織る）→ 縦糸に横糸を交互にくぐらせて布を作る＝（布を）織る",
   hook:"web（クモの巣，ネット）と同じ家族の古英語。過去形は wove，過去分詞は woven。",
   etymologyMore:["いくつもの筋を織り合わせる→（話・計画を）組み立てる","糸のように交互にくぐり抜ける→（車・人の間を）縫うように進む"],
   relatedWords:[
     {word:"weaver",meaning:"織る人，織工",breakdown:"weave（織る）＋ er（人）→ 機を使って布を織る人"},
     {word:"web",meaning:"クモの巣；網",breakdown:"web（網）→ クモが糸を織るように張った巣"},
     {synonym:true,word:"knit",meaning:"編む",breakdown:"毛糸を針で編む。weave は機で縦横に織る"},
     {synonym:true,word:"sew",meaning:"縫う",breakdown:"針と糸で布をつなぐ。weave は布そのものを作る"}]},

  {id:1769,word:"competent",partOfSpeech:"形容詞",meaning:"（仕事をこなす）能力のある，有能な",
   meanings:["形|（仕事をこなす）能力のある，有能な","形|（出来が）十分な，満足のいく"],
   pronunciation:"/ˈkɑːmpɪtənt/",part:177,
   example:"She is a competent nurse who stays calm in emergencies.",
   exampleJa:"彼女は緊急時にも落ち着いていられる、有能な看護師だ。",
   example2:"You need to be competent in English to study abroad.",
   exampleJa2:"留学するには、英語をこなす能力がなければならない。",
   usage:["be competent in 事（事をこなす力がある）","be competent to do（～する能力がある）"],
   etymologyProcess:"com（共に）＋ pet（求める）→ 求められる条件にかなうと…？",
   etymologyConclusion:"com（共に）＋ pet（求める）＋ ent（形容詞）→ 求められる条件にぴったり合う＝（仕事をこなす）能力のある",
   why:"【なぜ】ラテン語 competere は「一緒に向かう」から「ぴったり合う，ふさわしい」という意味になりました。役目にふさわしい＝その仕事をこなせる、という流れで「有能な」になります。\n【つながり】compete（競争する）も同じ語から。こちらは「同じものを一緒に求める」で争う意味になりました。",
   etymologyMore:["求めにかなうだけの出来→（出来が）十分な，満足のいく"],
   relatedWords:[
     {word:"compete",meaning:"競争する",breakdown:"com（共に）＋ pet（求める）→ 同じものを一緒に求めて争う"},
     {word:"competition",meaning:"競争；大会",breakdown:"com（共に）＋ pet（求める）＋ tion（名詞）→ 求めて争うこと"},
     {word:"appetite",meaning:"食欲",breakdown:"ad（～へ）＋ pet（求める）→ 食べ物へ向かって求める気持ち"},
     {word:"repeat",meaning:"くり返す",breakdown:"re（再び）＋ pet（求める）→ もう一度求めてやり直す"}]},

  {id:1770,word:"optimistic",partOfSpeech:"形容詞",meaning:"楽観的な",
   meanings:["形|（about ～について）楽観的な"],
   pronunciation:"/ˌɑːptɪˈmɪstɪk/",part:177,
   example:"Our coach is optimistic about the team's chances this year.",
   exampleJa:"コーチは今年のチームの見込みについて楽観的だ。",
   example2:"Try to stay optimistic even when things go wrong.",
   exampleJa2:"うまくいかないときでも、楽観的でいるようにしなさい。",
   usage:["be optimistic about 事（事について楽観的だ）"],
   etymologyProcess:"optim（最もよい）＋ ist（人）→ いつも最もよい結果を思い描くと…？",
   etymologyConclusion:"optim（最もよい）＋ ist（人）＋ ic（形容詞）→ 物事がいちばんよくなると考える＝楽観的な",
   relatedWords:[
     {word:"optimism",meaning:"楽観主義",breakdown:"optim（最もよい）＋ ism（主義）→ 最もよいほうを信じる考え方"},
     {word:"optimist",meaning:"楽観的な人",breakdown:"optim（最もよい）＋ ist（人）→ いつもよい結果を思う人"},
     {synonym:true,word:"positive",meaning:"前向きな",breakdown:"よい面を見る態度。optimistic は先の見通しが明るい"},
     {synonym:true,word:"hopeful",meaning:"希望をもった",breakdown:"hope（希望）＋ ful（満ちた）。うまくいくと期待する"}]},

  {id:1771,word:"patriotic",partOfSpeech:"形容詞",meaning:"愛国的な，愛国心の強い",
   meanings:["形|愛国的な，愛国心の強い"],
   pronunciation:"/ˌpeɪtriˈɑːtɪk/",part:178,
   example:"Many patriotic songs were sung at the national ceremony.",
   exampleJa:"国の式典では、多くの愛国的な歌が歌われた。",
   example2:"He felt very patriotic when his country won the gold medal.",
   exampleJa2:"自分の国が金メダルを取ったとき、彼はとても愛国的な気持ちになった。",
   etymologyProcess:"patr（父）＋ ic（形容詞）→ 父祖から受けついだ国を思うと…？",
   etymologyConclusion:"patr（父）＋ ic（形容詞）→ 父祖から受けついだ国を愛し大切に思う＝愛国的な",
   why:"【なぜ】ギリシャ語 patris は「父祖の地」、つまりご先祖から受けついだ国のこと。patriot はもと「同じ祖国の仲間」で、やがて「祖国を愛する人」になり、patriotic は「愛国的な」という意味になりました。\n【つながり】patron（後援者）は「父のように守る人」、pattern（型）はその patron が示す「手本」から生まれた語です。",
   relatedWords:[
     {word:"patriot",meaning:"愛国者",breakdown:"patr（父）→ 父祖の国を愛する人"},
     {word:"patron",meaning:"後援者，常連客",breakdown:"patr（父）→ 父のように後ろから支えてくれる人"},
     {word:"pattern",meaning:"模様；型",breakdown:"patr（父）→ 父のような patron が示す手本から「型」"},
     {synonym:true,word:"loyal",meaning:"忠実な",breakdown:"相手を裏切らない。patriotic は国に対する気持ち"}]},

  {id:1772,word:"noble",partOfSpeech:"形容詞",meaning:"（心・行いが）高潔な；貴族の",
   meanings:["形|（心・行いが）高潔な，気高い","形|貴族の，高貴な","名|貴族"],
   pronunciation:"/ˈnoʊbəl/",part:178,
   example:"Helping strangers in need is a noble thing to do.",
   exampleJa:"困っている見知らぬ人を助けるのは、高潔な行いだ。",
   example2:"She was born into a noble family in the 18th century.",
   exampleJa2:"彼女は18世紀に、貴族の家に生まれた。",
   etymologyProcess:"gn（知る）＋ ble（～できる）→ だれもが名を知る立派な人は…？",
   etymologyConclusion:"gn（知る）＋ ble（～できる）→ 名が知られるほど立派な心と行いの＝（心・行いが）高潔な",
   why:"【なぜ】ラテン語 nobilis は「知ることができる」＝名の知られた、という意味。名門の家は広く知られていたので「貴族の」になり、さらに貴族にふさわしい立派な心を表す「高潔な」へ広がりました。\n【つながり】recognize（見分ける）や ignore（無視する）も同じ「知る」の仲間です。",
   spelling:"gn→n（g が落ちた）",
   etymologyMore:["名が広く知られた家柄→貴族の，高貴な"],
   relatedWords:[
     {word:"recognize",meaning:"見分ける，認める",breakdown:"re（再び）＋ gn（知る）→ 前に知ったものだと気づく"},
     {word:"ignore",meaning:"無視する",breakdown:"in（否定）＋ gn（知る）→ 知らないふりをする"},
     {word:"nobility",meaning:"高潔さ；貴族",breakdown:"gn（知る）＋ ity（名詞）→ 名が知られるほどの立派さ"},
     {synonym:true,word:"honest",meaning:"正直な",breakdown:"うそをつかない。noble はさらに気高く立派なこと"}]},

  {id:1773,word:"naughty",partOfSpeech:"形容詞",meaning:"（子どもが）いたずらな，言うことを聞かない",
   meanings:["形|（子どもが）いたずらな，言うことを聞かない"],
   pronunciation:"/ˈnɔːti/",part:178,
   example:"The naughty boy hid his sister's shoes again.",
   exampleJa:"そのいたずらな男の子は、また妹の靴を隠した。",
   example2:"Our puppy was naughty and chewed up my homework.",
   exampleJa2:"うちの子犬は言うことを聞かず、私の宿題をかじってしまった。",
   etymologyProcess:"naught（何もない）＋ y（形容詞）→ 何の値打ちもないことばかりすると…？",
   etymologyConclusion:"naught（何もない）＋ y（形容詞）→ 値打ちのない悪さばかりする＝（子どもが）いたずらな",
   why:"【なぜ】naught は古英語で「何もない」という語。そこから「値打ちのない，悪い」を表す naughty ができました。昔は大人の悪事にも使う強い語でしたが、だんだん軽くなり、今では子どもの「いたずら」に使います。\n【つながり】否定の not も naught が縮まってできた語。数字の 0 を nought と言うこともあります。",
   relatedWords:[
     {word:"not",meaning:"～でない",breakdown:"naught（何もない）→ 縮まって否定の not になった"},
     {word:"naught",meaning:"無，ゼロ",breakdown:"naught（何もない）→ 何も無いこと"},
     {synonym:true,word:"bad",meaning:"悪い",breakdown:"悪いこと全般。naughty は子どもの軽い悪さ"},
     {synonym:true,word:"mischievous",meaning:"いたずら好きな",breakdown:"人を困らせて面白がる。naughty とほぼ同じ"}]},

  {id:1774,word:"arrogant",partOfSpeech:"形容詞",meaning:"傲慢な，横柄な",
   meanings:["形|傲慢な，横柄な"],
   pronunciation:"/ˈærəɡənt/",part:178,
   example:"The arrogant player never listened to his coach's advice.",
   exampleJa:"その傲慢な選手は、コーチの助言に決して耳を貸さなかった。",
   example2:"It is arrogant to think you are always right.",
   exampleJa2:"自分がいつも正しいと思うのは傲慢だ。",
   etymologyProcess:"ad（～へ）＋ rog（求める）→ 自分へ何でも求めてばかりいると…？",
   etymologyConclusion:"ad（～へ）＋ rog（求める）＋ ant（形容詞）→ 自分に当然の権利だと要求する＝傲慢な",
   spelling:"ad→ar（r の前で同化）",
   relatedWords:[
     {word:"interrogate",meaning:"尋問する",breakdown:"inter（間の）＋ rog（求める）→ 間に入りこんで答えを求める"},
     {word:"arrogance",meaning:"傲慢さ",breakdown:"ad（～へ）＋ rog（求める）＋ ance（名詞）→ 自分に求めすぎる態度"},
     {synonym:true,word:"proud",meaning:"誇りに思う；うぬぼれた",breakdown:"よい意味でも使う。arrogant は悪い意味だけ"},
     {synonym:true,word:"rude",meaning:"失礼な",breakdown:"礼儀を欠く。arrogant は相手を見下している"}]},

  {id:1775,word:"vigorous",partOfSpeech:"形容詞",meaning:"精力的な，力強い",
   meanings:["形|精力的な，力強い","形|（運動が）激しい，活発な"],
   pronunciation:"/ˈvɪɡərəs/",part:178,
   example:"My grandfather is still vigorous and walks ten kilometers a day.",
   exampleJa:"祖父は今でも精力的で、1日に10キロ歩いている。",
   example2:"Doctors advise us to do vigorous exercise three times a week.",
   exampleJa2:"医者は週に3回、激しい運動をするよう勧めている。",
   etymologyProcess:"vig（元気な）＋ ous（～に満ちた）→ 元気があふれていると…？",
   etymologyConclusion:"vig（元気な）＋ ous（～に満ちた）→ 生き生きとした力があふれている＝精力的な",
   etymologyMore:["あふれる力で体を動かす→（運動が）激しい，活発な"],
   relatedWords:[
     {word:"vigor",meaning:"活力，元気",breakdown:"vig（元気な）＋ or（もの）→ 体にみなぎる元気"},
     {word:"vegetable",meaning:"野菜",breakdown:"veg（元気な）＋ able（できる）→ 元気に育つ植物"},
     {word:"vigilant",meaning:"用心深い",breakdown:"vig（元気な）＋ ant（～な）→ 目がさえて見張っている"},
     {synonym:true,word:"energetic",meaning:"活発な",breakdown:"エネルギーにあふれた。vigorous は力強さが強い"}]},

  {id:1776,word:"humble",partOfSpeech:"形容詞",meaning:"（態度が）控えめな；（身分が）低い",
   meanings:["形|（態度が）控えめな，謙虚な","形|（身分・家柄が）低い，質素な","他|謙虚な気持ちにさせる"],
   pronunciation:"/ˈhʌmbəl/",part:178,
   example:"Despite his fame, the actor remained humble and kind.",
   exampleJa:"有名になっても、その俳優は控えめで親切なままだった。",
   example2:"She rose from humble beginnings to become a famous scientist.",
   exampleJa2:"彼女は貧しい生まれから、有名な科学者にまでなった。",
   etymologyProcess:"humil（低い）→ 自分を低いところに置くと…？",
   etymologyConclusion:"humil（低い）→ 自分を高く見せず、低いところに置く＝（態度が）控えめな",
   spelling:"humil→humbl（フランス語を通って変化）",
   etymologyMore:["地面に近い低い立場→（身分・家柄が）低い，質素な"],
   relatedWords:[
     {word:"humility",meaning:"謙虚さ",breakdown:"humil（低い）＋ ity（名詞）→ 自分を低く置く心"},
     {word:"humiliate",meaning:"恥をかかせる",breakdown:"humil（低い）＋ ate（～にする）→ 人を低くおとしめる"},
     {synonym:true,word:"modest",meaning:"謙虚な",breakdown:"自分の手柄を大きく言わない。humble とほぼ同じ"},
     {synonym:true,word:"simple",meaning:"質素な；簡単な",breakdown:"飾りがない。humble は身分が低い感じも含む"}]},

  {id:1777,word:"eligible",partOfSpeech:"形容詞",meaning:"（…の）資格のある，適格な",
   meanings:["形|（for ～の／to do する）資格のある，適格な","形|（結婚相手として）望ましい"],
   pronunciation:"/ˈelɪdʒəbəl/",part:178,
   example:"Students over sixteen are eligible for this scholarship.",
   exampleJa:"16歳を超える生徒は、この奨学金の資格がある。",
   example2:"You will be eligible to vote when you turn eighteen.",
   exampleJa2:"18歳になれば、投票する資格が得られる。",
   usage:["be eligible for 事（事の資格がある）","be eligible to do（～する資格がある）"],
   etymologyProcess:"e（外へ）＋ lect（拾う）→ 多くの中から選び出せると…？",
   etymologyConclusion:"e（外へ）＋ lect（拾う）＋ ible（できる）→ 多くの中から選び出されることができる＝（…の）資格のある",
   spelling:"lect→lig（ラテン語 eligere の形）",
   etymologyMore:["結婚相手に選び出したくなる→（結婚相手として）望ましい"],
   relatedWords:[
     {word:"elect",meaning:"選挙で選ぶ",breakdown:"e（外へ）＋ lect（拾う）→ 候補の中から拾い出す"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離れて）＋ lect（拾う）→ 分けて拾い上げる"},
     {word:"collect",meaning:"集める",breakdown:"con（共に）＋ lect（拾う）→ 一か所に拾い集める"},
     {synonym:true,word:"qualified",meaning:"資格をもった",breakdown:"試験などで資格を取った。eligible は条件を満たしている"}]},

  {id:1778,word:"courtesy",partOfSpeech:"名詞",meaning:"礼儀正しさ，丁寧さ",
   meanings:["名|礼儀正しさ，丁寧さ","名|（courtesy of ～で）～の好意により"],
   pronunciation:"/ˈkɜːrtəsi/",part:178,
   example:"Courtesy costs nothing, so always thank people who help you.",
   exampleJa:"礼儀正しさにお金はかからないのだから、助けてくれた人には必ずお礼を言いなさい。",
   example2:"The photos in this article appear courtesy of the museum.",
   exampleJa2:"この記事の写真は、博物館の好意により掲載されている。",
   etymologyProcess:"court（宮廷）＋ y（名詞）→ 宮廷の人々のようなふるまいは…？",
   etymologyConclusion:"court（宮廷）＋ y（名詞）→ 宮廷に仕える人々の上品で丁寧なふるまい＝礼儀正しさ",
   why:"【なぜ】中世の宮廷（court）では、王に仕える人に丁寧で上品なふるまいが求められました。そこから「宮廷風のふるまい」が、人を思いやる礼儀正しさを表すようになりました。\n【つながり】courteous（礼儀正しい）も同じ仲間。テニスの court も、もとは「囲まれた場所」を表す同じ語です。",
   etymologyMore:["礼儀として相手に示す厚意→（courtesy of ～で）～の好意により"],
   relatedWords:[
     {word:"court",meaning:"宮廷；コート；法廷",breakdown:"court（宮廷）→ 囲まれた場所。王の宮廷や球技のコート"},
     {word:"courteous",meaning:"礼儀正しい",breakdown:"court（宮廷）＋ ous（～に満ちた）→ 宮廷風の上品さにあふれた"},
     {synonym:true,word:"manners",meaning:"行儀，作法",breakdown:"ふるまいの決まり。courtesy は相手を思う丁寧さ"},
     {synonym:true,word:"respect",meaning:"尊敬；敬意",breakdown:"相手を大切に思う気持ち。courtesy はそれを態度で示す"}]},

  {id:1779,word:"resilient",partOfSpeech:"形容詞",meaning:"（困難から）立ち直りの早い；弾力のある",
   meanings:["形|（困難から）立ち直りの早い，へこたれない","形|（物が）弾力のある"],
   pronunciation:"/rɪˈzɪliənt/",part:178,
   example:"Children are often more resilient than adults think.",
   exampleJa:"子どもは大人が思うよりも、立ち直りが早いことが多い。",
   example2:"Our team stayed resilient and came back to win the final.",
   exampleJa2:"私たちのチームはへこたれず、逆転して決勝に勝った。",
   etymologyProcess:"re（後ろへ）＋ sult（跳ぶ）→ 押されてもぽんと跳ね返ると…？",
   etymologyConclusion:"re（後ろへ）＋ sult（跳ぶ）＋ ient（～な）→ 押されてもぽんと跳ね返って元に戻る＝（困難から）立ち直りの早い",
   spelling:"sult→sil（ラテン語 resilire の形）",
   etymologyMore:["押されても形が跳ね戻る→（物が）弾力のある"],
   relatedWords:[
     {word:"result",meaning:"結果",breakdown:"re（後ろへ）＋ sult（跳ぶ）→ 行いから跳ね返ってきたもの"},
     {word:"insult",meaning:"侮辱する",breakdown:"in（上に）＋ sult（跳ぶ）→ 相手に跳びかかって傷つける"},
     {word:"resilience",meaning:"回復力，立ち直る力",breakdown:"re（後ろへ）＋ sult（跳ぶ）＋ ence（名詞）→ 跳ね返る力"},
     {synonym:true,word:"tough",meaning:"たくましい",breakdown:"強くて負けない。resilient は倒れても元に戻る"}]},

  {id:1780,word:"inclined",partOfSpeech:"形容詞",meaning:"（～する）傾向がある；～したい気がする",
   meanings:["形|（to do）～する傾向がある","形|（to do）～したい気がする","形|傾いた"],
   pronunciation:"/ɪnˈklaɪnd/",part:178,
   example:"I'm inclined to forget things when I'm very tired.",
   exampleJa:"私はとても疲れていると、物事を忘れる傾向がある。",
   example2:"After the long test, I felt inclined to stay home and rest.",
   exampleJa2:"長いテストのあとで、家で休みたい気がした。",
   usage:["be inclined to do（～する傾向がある）","feel inclined to do（～したい気がする）"],
   etymologyProcess:"in（中へ）＋ clin（傾き）→ 心がある方向へ傾いていると…？",
   etymologyConclusion:"in（中へ）＋ clin（傾き）＋ ed（～された）→ 心がある方向へ傾いている＝（～する）傾向がある",
   etymologyMore:["気持ちがそちらへ傾く→（to do）～したい気がする"],
   relatedWords:[
     {word:"decline",meaning:"断る；減少する",breakdown:"de（下へ）＋ clin（傾き）→ 下へ傾いて落ちていく"},
     {word:"recline",meaning:"もたれる",breakdown:"re（後ろへ）＋ clin（傾き）→ 背もたれを後ろへ傾ける"},
     {word:"climate",meaning:"気候",breakdown:"clim（傾き）＋ ate（名詞）→ 太陽の傾きで決まる土地の天気"},
     {synonym:true,word:"likely",meaning:"～しそうな",breakdown:"起こる見込みが高い。inclined は人の傾向や気持ち"}]},

  {id:1781,word:"haunt",partOfSpeech:"他動詞",meaning:"（幽霊が）出る；（記憶が）つきまとう",
   meanings:["他|（幽霊が）出る，とりつく","他|（記憶・不安が）つきまとう，悩ませる","他|（場所に）よく行く"],
   pronunciation:"/hɔːnt/",part:179,
   example:"People say a ghost haunts the old school building at night.",
   exampleJa:"夜になると古い校舎に幽霊が出ると言われている。",
   example2:"The memory of that mistake haunted him for many years.",
   exampleJa2:"その失敗の記憶は、何年も彼につきまとった。",
   etymologyProcess:"haunt（よく通う）→ 死者の霊が同じ場所に何度も来ると…？",
   etymologyConclusion:"haunt（よく通う）→ 死者の霊が同じ場所にくり返し現れる＝（幽霊が）出る",
   hook:"もとは「よく通う」。古フランス語から来たが、その先ははっきりしない。幽霊屋敷は haunted house。",
   etymologyMore:["いやな記憶が何度もやって来る→（記憶・不安が）つきまとう，悩ませる","もとの「よく通う」→（場所に）よく行く"],
   relatedWords:[
     {word:"haunted",meaning:"幽霊の出る",breakdown:"haunt（よく通う）＋ ed（～された）→ 霊にくり返し訪れられる"},
     {synonym:true,word:"ghost",meaning:"幽霊",breakdown:"haunt するもの。a ghost haunts the house の形でよく使う"},
     {synonym:true,word:"bother",meaning:"悩ませる",breakdown:"人をわずらわせる。haunt は何度も頭に浮かんで離れない"},
     {synonym:true,word:"visit",meaning:"訪れる",breakdown:"ふつうに訪ねる。haunt はくり返し現れる"}]},

  {id:1782,word:"intent",partOfSpeech:"形容詞",meaning:"（…に）没頭した；決意した",
   meanings:["形|（on ～に）没頭した，熱中した","形|（on doing）～しようと決意した","名|意図，目的"],
   pronunciation:"/ɪnˈtent/",part:179,
   example:"She was so intent on her book that she didn't hear me.",
   exampleJa:"彼女は本に没頭していて、私の声が聞こえなかった。",
   example2:"He is intent on winning the speech contest this year.",
   exampleJa2:"彼は今年こそスピーチコンテストで優勝しようと決意している。",
   usage:["be intent on 事（事に没頭している）","be intent on doing（～しようと決意している）"],
   etymologyProcess:"in（～に）＋ tend（伸ばす）→ 心をひとつに張り伸ばすと…？",
   etymologyConclusion:"in（～に）＋ tend（伸ばす）→ 心をひとつのことへぴんと張り伸ばす＝（…に）没頭した",
   spelling:"tend→tent（ラテン語の過去分詞の形）",
   etymologyMore:["心を目標へまっすぐ伸ばす→（on doing）～しようと決意した","心が伸びていく向かう先→意図，目的"],
   relatedWords:[
     {word:"intend",meaning:"～するつもりである",breakdown:"in（～に）＋ tend（伸ばす）→ 心をある方向へ伸ばす"},
     {word:"attend",meaning:"出席する；注意を払う",breakdown:"ad（～へ）＋ tend（伸ばす）→ 心や足をそちらへ伸ばす"},
     {word:"extend",meaning:"延ばす，広げる",breakdown:"ex（外へ）＋ tend（伸ばす）→ 外へ向かって長く伸ばす"},
     {word:"intention",meaning:"意図",breakdown:"in（～に）＋ tend（伸ばす）＋ ion（名詞）→ 心が向かう先"}]},

  {id:1783,word:"indulge",partOfSpeech:"他動詞・自動詞",meaning:"（in ～に）ふける；甘やかす",
   meanings:["自|（in ～に）ふける，思う存分楽しむ","他|（子どもなどを）甘やかす","他|（欲望を）満たす"],
   pronunciation:"/ɪnˈdʌldʒ/",part:179,
   example:"On weekends, I indulge in reading comics all day long.",
   exampleJa:"週末には、一日じゅう漫画を読みふける。",
   example2:"Don't indulge your little brother every time he cries.",
   exampleJa2:"弟が泣くたびに甘やかしてはいけない。",
   usage:["indulge in 事（事にふける，思う存分楽しむ）","indulge oneself（好きなだけ楽しむ）"],
   etymologyProcess:"indulg（甘くする）→ 自分に甘くして好きなことに浸ると…？",
   etymologyConclusion:"indulg（甘くする）→ 自分に甘くして好きなことに身を任せる＝（in ～に）ふける",
   hook:"ラテン語 indulgere（大目に見る）から。その先の語源ははっきりしない。indulge in の形で覚える。",
   etymologyMore:["人に対して甘くする→（子どもなどを）甘やかす"],
   relatedWords:[
     {word:"indulgence",meaning:"ふけること；ぜいたく",breakdown:"indulg（甘くする）＋ ence（名詞）→ 自分に甘くすること"},
     {synonym:true,word:"enjoy",meaning:"楽しむ",breakdown:"ふつうに楽しむ。indulge は度を越して楽しむ感じ"},
     {synonym:true,word:"spoil",meaning:"甘やかす；台無しにする",breakdown:"甘やかしてだめにする。indulge より悪い結果が強い"},
     {synonym:true,word:"relax",meaning:"くつろぐ",breakdown:"気を楽にする。indulge は好きなことに浸りきる"}]},

  {id:1784,word:"flaw",partOfSpeech:"名詞",meaning:"（物の）小さな傷；（計画などの）欠点",
   meanings:["名|（物の）小さな傷，ひび","名|（計画・性格の）欠点，不備"],
   pronunciation:"/flɔː/",part:179,
   example:"There is a tiny flaw in this diamond near the edge.",
   exampleJa:"このダイヤモンドには、ふちの近くに小さな傷がある。",
   example2:"Our teacher found a serious flaw in my argument.",
   exampleJa2:"先生は私の主張に重大な欠点を見つけた。",
   etymologyProcess:"flaw（はがれたかけら）→ 表面が欠けてできたものは…？",
   etymologyConclusion:"flaw（はがれたかけら）→ 表面が欠けてできた小さなきず＝（物の）小さな傷",
   hook:"北欧語の「薄いかけら」から来たとされるが、はっきりしない。flawless は「完璧な」。",
   etymologyMore:["表面のひびのような弱いところ→（計画・性格の）欠点，不備"],
   relatedWords:[
     {word:"flawless",meaning:"完璧な，傷のない",breakdown:"flaw（はがれたかけら）＋ less（ない）→ 傷ひとつない"},
     {synonym:true,word:"fault",meaning:"欠点；責任",breakdown:"性格や機械の欠点。flaw は小さな傷のような欠点"},
     {synonym:true,word:"crack",meaning:"ひび，割れ目",breakdown:"割れてできた線。flaw は傷全般"},
     {synonym:true,word:"weakness",meaning:"弱点",breakdown:"弱いところ。flaw は本来あってはならない欠け"}]},

  {id:1785,word:"defect",partOfSpeech:"名詞",meaning:"（機械・体の）欠陥，不具合",
   meanings:["名|（機械・体の）欠陥，不具合","自|（国・党から）離反する，亡命する"],
   pronunciation:"/ˈdiːfekt/",part:179,
   example:"The company recalled the cars because of a brake defect.",
   exampleJa:"その会社は、ブレーキの欠陥のために車を回収した。",
   example2:"The doctor found a small defect in the baby's heart.",
   exampleJa2:"医者は赤ちゃんの心臓に小さな欠陥を見つけた。",
   etymologyProcess:"de（離れて）＋ fect（作る）→ あるべき形から離れて欠けると…？",
   etymologyConclusion:"de（離れて）＋ fect（作る）→ あるべき作りから離れて足りない部分＝（機械・体の）欠陥",
   why:"【なぜ】ラテン語 deficere は「離れる」＋「する」で、「やめる，足りなくなる」という意味。必要な部分が欠けている状態が defect＝欠陥です。\n【つながり】「離れる」の意味は動詞の defect（味方から離れる＝亡命する）に残っています。deficit（赤字）も「足りない」の仲間です。",
   relatedWords:[
     {word:"perfect",meaning:"完璧な",breakdown:"per（すっかり）＋ fect（作る）→ すっかり作り上げた"},
     {word:"effect",meaning:"効果，結果",breakdown:"ex（外へ）＋ fect（作る）→ 外に作り出されたもの"},
     {word:"defective",meaning:"欠陥のある",breakdown:"de（離れて）＋ fect（作る）＋ ive（形容詞）→ 作りが欠けた"},
     {synonym:true,word:"fault",meaning:"欠点；故障",breakdown:"欠点全般。defect は製品などの作りの欠陥"}]},

  {id:1786,word:"trait",partOfSpeech:"名詞",meaning:"（性格・体の）特色，特性",
   meanings:["名|（性格・体の）特色，特性"],
   pronunciation:"/treɪt/",part:179,
   example:"Honesty is one of her best personality traits.",
   exampleJa:"正直さは、彼女の性格のいちばんよい特色の一つだ。",
   example2:"Eye color is a trait that is passed down from parents.",
   exampleJa2:"目の色は、親から受けつがれる特色だ。",
   etymologyProcess:"tract（引く）→ 筆でさっと引いた線がその人らしさになると…？",
   etymologyConclusion:"tract（引く）→ 筆でさっと引いた線のように、その人らしさが出る点＝（性格・体の）特色",
   why:"【なぜ】ラテン語 tractus は「引くこと，引いた線」。フランス語で「筆の一筆，顔の輪郭」を表すようになり、その人らしさを形づくる線＝「特色，特性」に広がりました。\n【つながり】attract（引きつける）や tractor（引っぱる車）も「引く」の仲間。traitor（裏切り者）はつづりが似ていますが別の語です。",
   spelling:"tract→trait（フランス語を通って変化）",
   relatedWords:[
     {word:"attract",meaning:"引きつける",breakdown:"ad（～へ）＋ tract（引く）→ 自分のほうへ引き寄せる"},
     {word:"tractor",meaning:"トラクター",breakdown:"tract（引く）＋ or（もの）→ 重い農機具を引っぱる車"},
     {word:"portrait",meaning:"肖像画",breakdown:"pro（前へ）＋ tract（引く）→ 顔の線を前へ引き出して描いた絵"},
     {synonym:true,word:"feature",meaning:"特徴",breakdown:"目立つ点全般。trait は性格や遺伝で受けつぐ特色"}]},

  {id:1787,word:"analogy",partOfSpeech:"名詞",meaning:"（二つの物事の）類似点；類推",
   meanings:["名|（二つの物事の）類似点","名|類推，たとえ"],
   pronunciation:"/əˈnælədʒi/",part:179,
   example:"The teacher explained the heart using an analogy with a pump.",
   exampleJa:"先生はポンプとの類似点を挙げて、心臓のしくみを説明した。",
   example2:"By analogy, we can guess how the new system will work.",
   exampleJa2:"類推によって、新しい仕組みがどう動くか推測できる。",
   usage:["an analogy with A（A との類似点，A へのたとえ）","by analogy（類推によって）"],
   etymologyProcess:"analog（比率が同じ）→ 2つのものが同じ関係にあると…？",
   etymologyConclusion:"analog（比率が同じ）＋ y（名詞）→ 2つの物事の関係が同じように見える点＝（二つの物事の）類似点",
   etymologyMore:["似た点をたどって考えを進める→類推，たとえ"],
   relatedWords:[
     {word:"analog",meaning:"アナログの",breakdown:"analog（比率が同じ）→ 実物の変化にそっくり合わせて表す"},
     {word:"analogous",meaning:"類似した",breakdown:"analog（比率が同じ）＋ ous（形容詞）→ 同じような関係の"},
     {synonym:true,word:"similarity",meaning:"似ていること",breakdown:"似ている点全般。analogy は違うものの間の似た関係"},
     {synonym:true,word:"comparison",meaning:"比較；たとえ",breakdown:"並べて比べること。analogy は似た点を使って説明する"}]},

  {id:1788,word:"parallel",partOfSpeech:"形容詞",meaning:"（…と）平行の；（…との）類似点",
   meanings:["形|（to ～と）平行の","名|（with ～との）類似点，匹敵するもの"],
   pronunciation:"/ˈpærəlel/",part:179,
   example:"Draw two parallel lines on the paper with your ruler.",
   exampleJa:"定規を使って、紙に2本の平行の線を引きなさい。",
   example2:"This event has no parallel in the history of our school.",
   exampleJa2:"この出来事は、わが校の歴史で匹敵するものがない。",
   usage:["parallel to A（A と平行の）","have no parallel（匹敵するものがない）"],
   etymologyProcess:"para（そばで）＋ allel（互いに）→ 互いのそばを並んで進むと…？",
   etymologyConclusion:"para（そばで）＋ allel（互いに）→ 互いにそばに並び、どこまでも交わらない＝（…と）平行の",
   etymologyMore:["同じ向きに並んで比べられる→（with ～との）類似点，匹敵するもの"],
   relatedWords:[
     {word:"paragraph",meaning:"段落",breakdown:"para（そばで）＋ graph（書く）→ 区切りのそばに印を書いた"},
     {word:"parody",meaning:"パロディー",breakdown:"para（そばで）＋ ody（歌）→ 元の歌のそばに並べた替え歌"},
     {synonym:true,word:"similar",meaning:"似ている",breakdown:"似ていること全般。parallel は並べて比べられるほど"},
     {synonym:true,word:"equal",meaning:"等しい；匹敵するもの",breakdown:"同じくらいの。have no parallel ≒ have no equal"}]},

  {id:1789,word:"indispensable",partOfSpeech:"形容詞",meaning:"（…に）なくてはならない",
   meanings:["形|（to/for ～に）なくてはならない，欠かせない"],
   pronunciation:"/ˌɪndɪˈspensəbəl/",part:179,
   example:"A smartphone has become indispensable for many students.",
   exampleJa:"多くの学生にとって、スマートフォンはなくてはならないものになった。",
   example2:"Clean water is indispensable to all living things.",
   exampleJa2:"きれいな水は、すべての生き物になくてはならない。",
   usage:["be indispensable to/for A（A に不可欠だ）"],
   etymologyProcess:"in（否定）＋ dis（離れて）＋ pens（重さを量る）→ 手放せないものは…？",
   etymologyConclusion:"in（否定）＋ dis（離れて）＋ pens（重さを量る）＋ able（できる）→ 量り分けて手放すことができない＝（…に）なくてはならない",
   why:"【なぜ】dispense は「量って分け与える」。そこから dispense with ～「～を手放す，なしで済ます」の意味が生まれました。それを in（否定）と able（できる）で打ち消して、「なしでは済ませられない」＝なくてはならない、になりました。\n【つながり】液体を量って出す dispenser（ディスペンサー）や expense（出費）も同じ仲間です。",
   relatedWords:[
     {word:"spend",meaning:"（お金を）使う",breakdown:"pend（重さを量る）→ 量って払い出す"},
     {word:"expense",meaning:"出費，費用",breakdown:"ex（外へ）＋ pens（重さを量る）→ 量って外へ払い出すお金"},
     {word:"dispenser",meaning:"ディスペンサー",breakdown:"dis（離れて）＋ pens（重さを量る）＋ er（もの）→ 量って分け出す器具"},
     {synonym:true,word:"necessary",meaning:"必要な",breakdown:"欠かせない。indispensable はそれより強い"}]},

  {id:1790,word:"crucial",partOfSpeech:"形容詞",meaning:"（成否を分ける）決定的な，きわめて重要な",
   meanings:["形|（to/for ～にとって）決定的な，きわめて重要な"],
   pronunciation:"/ˈkruːʃəl/",part:179,
   example:"The next match is crucial for our team's future.",
   exampleJa:"次の試合は、私たちのチームの今後にとって決定的だ。",
   example2:"It is crucial that you get enough sleep before the exam.",
   exampleJa2:"試験の前に十分な睡眠をとることは、きわめて重要だ。",
   usage:["be crucial to/for A（A にとって決定的に重要だ）","It is crucial that SV（～が重要だ）"],
   etymologyProcess:"cruc（十字）＋ ial（形容詞）→ 道が十字に分かれる所に立つと…？",
   etymologyConclusion:"cruc（十字）＋ ial（形容詞）→ 道が十字に分かれ、進む先で成否が決まる＝（成否を分ける）決定的な",
   why:"【なぜ】ラテン語 crux は「十字」。17世紀の学者が「どちらの説が正しいかを決める実験」を、道しるべの十字にたとえて「十字の実験」と呼びました。そこから「成否を分ける分かれ道の」＝決定的な、という意味が広まりました。\n【つながり】cross（十字；横切る）や cruise（クルーズ）も同じ仲間です。",
   relatedWords:[
     {word:"cross",meaning:"十字；横切る",breakdown:"cruc（十字）→ 十字の形。十字に道を横切る"},
     {word:"cruise",meaning:"船旅，クルーズ",breakdown:"cruc（十字）→ 海を十字に行き来して回る"},
     {word:"crusade",meaning:"十字軍；改革運動",breakdown:"cruc（十字）＋ ade（行動）→ 十字を掲げた戦い"},
     {synonym:true,word:"important",meaning:"重要な",breakdown:"大事なこと全般。crucial は結果を決めるほど重要"}]},

  {id:1791,word:"grave",partOfSpeech:"形容詞",meaning:"（事態が）ゆゆしい，重大な",
   meanings:["形|（事態が）ゆゆしい，重大な","形|（表情が）重々しい，深刻な"],
   pronunciation:"/ɡreɪv/",part:180,
   example:"Ocean pollution is a grave problem for everyone on Earth.",
   exampleJa:"海の汚染は、地球上のすべての人にとってゆゆしい問題だ。",
   example2:"He looked grave when he heard the news from the hospital.",
   exampleJa2:"病院からの知らせを聞いて、彼は重々しい表情になった。",
   etymologyProcess:"grav（重い）→ ずしりと重くのしかかる事態は…？",
   etymologyConclusion:"grav（重い）→ ずしりと重くのしかかって軽く扱えない＝（事態が）ゆゆしい，重大な",
   etymologyMore:["心が重く沈んだ顔つき→（表情が）重々しい，深刻な"],
   relatedWords:[
     {word:"gravity",meaning:"重力；重大さ",breakdown:"grav（重い）＋ ity（名詞）→ 物を重く下へ引く力"},
     {word:"grief",meaning:"深い悲しみ",breakdown:"grav（重い）→ 心に重くのしかかる悲しみ"},
     {word:"aggravate",meaning:"悪化させる",breakdown:"ad（～へ）＋ grav（重い）＋ ate（動詞）→ さらに重くする"},
     {synonym:true,word:"serious",meaning:"深刻な，重大な",breakdown:"ふつうの「深刻な」。grave はより重く改まった語"}]},

  {id:1792,word:"primary",partOfSpeech:"形容詞",meaning:"（いちばん）主な，第一の；初等の",
   meanings:["形|（いちばん）主な，第一の","形|初等（教育）の，最初の"],
   pronunciation:"/ˈpraɪmeri/",part:180,
   example:"Our primary goal this season is to reach the finals.",
   exampleJa:"今シーズンの私たちの主な目標は、決勝に進むことだ。",
   example2:"My little sister goes to a primary school near our house.",
   exampleJa2:"妹は家の近くの小学校（初等学校）に通っている。",
   etymologyProcess:"prim（第一の）＋ ary（形容詞）→ 順位がいちばん上のものは…？",
   etymologyConclusion:"prim（第一の）＋ ary（形容詞）→ 大事さの順番がいちばん上にくる＝（いちばん）主な，第一の",
   etymologyMore:["時間の順番がいちばん最初→初等（教育）の，最初の"],
   relatedWords:[
     {word:"prime",meaning:"最も重要な；最盛期",breakdown:"prim（第一の）→ 順位も時期もいちばん上"},
     {word:"prince",meaning:"王子",breakdown:"prim（第一の）＋ cap（つかむ）→ 第一の座をつかむ人"},
     {word:"primitive",meaning:"原始的な",breakdown:"prim（第一の）＋ ive（形容詞）→ いちばん最初の段階の"},
     {synonym:true,word:"main",meaning:"主な",breakdown:"ふつうの「主な」。primary は順位が一番のかたい語"}]},

  {id:1793,word:"vital",partOfSpeech:"形容詞",meaning:"（成功・生存に）欠かせない，きわめて重要な",
   meanings:["形|（to/for ～に）欠かせない，きわめて重要な","形|生命の，生命維持に必要な","形|活気のある"],
   pronunciation:"/ˈvaɪtəl/",part:180,
   example:"Regular exercise is vital for staying healthy and happy.",
   exampleJa:"定期的な運動は、健康で幸せでいるために欠かせない。",
   example2:"The nurse checked the patient's vital signs every hour.",
   exampleJa2:"看護師は1時間ごとに、患者の生命の兆候（バイタルサイン）を確かめた。",
   usage:["be vital to/for A（A に欠かせない）","It is vital that SV（～がきわめて重要だ）"],
   etymologyProcess:"viv（生きる）＋ al（～の）→ 命を保つのに必要なものは…？",
   etymologyConclusion:"viv（生きる）＋ al（～の）→ 命を保つのに必要なほど大事な＝（成功・生存に）欠かせない",
   spelling:"viv→vit（ラテン語 vita（命）の形）",
   etymologyMore:["命そのものにかかわる→生命の，生命維持に必要な","命があふれている→活気のある"],
   relatedWords:[
     {word:"survive",meaning:"生き残る",breakdown:"sur（上を越えて）＋ viv（生きる）→ 危険を越えて生き続ける"},
     {word:"revive",meaning:"生き返らせる",breakdown:"re（再び）＋ viv（生きる）→ もう一度生かす"},
     {word:"vivid",meaning:"生き生きとした",breakdown:"viv（生きる）＋ id（～な状態の）→ 命があふれて鮮やかな"},
     {synonym:true,word:"essential",meaning:"不可欠な",breakdown:"本質的に必要な。vital は命にかかわるほど大事"}]},

  {id:1794,word:"integral",partOfSpeech:"形容詞",meaning:"（全体に）欠かせない一部の",
   meanings:["形|（全体に）欠かせない一部の，不可欠な"],
   pronunciation:"/ˈɪntɪɡrəl/",part:180,
   example:"Music is an integral part of our school festival.",
   exampleJa:"音楽は、わが校の文化祭に欠かせない一部だ。",
   example2:"Teamwork is integral to success in any sport.",
   exampleJa2:"チームワークは、どんなスポーツでも成功に不可欠だ。",
   usage:["an integral part of A（A に欠かせない一部）","be integral to A（A に不可欠だ）"],
   etymologyProcess:"in（否定）＋ teg（触れる）→ だれも手をつけていないまるごとの全体は…？",
   etymologyConclusion:"in（否定）＋ teg（触れる）＋ al（～の）→ 手つかずの全体をつくる一部の＝（全体に）欠かせない一部の",
   why:"【なぜ】ラテン語 integer は「触れられていない」＝欠けたところのない、まるごとの、という意味。integral はその「まるごとの全体」をつくっている部分のことで、欠けたら全体でなくなるので「欠かせない」になりました。\n【つながり】integrate（まとめる）や entire（全体の）も同じ仲間。数学の「整数」は英語で integer です。",
   spelling:"teg→tegr（ラテン語 integer の形）",
   relatedWords:[
     {word:"entire",meaning:"全体の",breakdown:"in（否定）＋ teg（触れる）→ 手つかずでまるごとの"},
     {word:"integrate",meaning:"まとめる，統合する",breakdown:"in（否定）＋ teg（触れる）＋ ate（動詞）→ まるごとの全体にする"},
     {word:"intact",meaning:"無傷の",breakdown:"in（否定）＋ tact（触れる）→ だれにも触れられていない"},
     {synonym:true,word:"essential",meaning:"不可欠な",breakdown:"なくてはならない。integral は全体の一部として欠かせない"}]},

  {id:1795,word:"profound",partOfSpeech:"形容詞",meaning:"（影響が）深い，重大な；深遠な",
   meanings:["形|（影響・変化が）深い，重大な","形|（考え・知識が）深い，深遠な"],
   pronunciation:"/prəˈfaʊnd/",part:180,
   example:"The war had a profound effect on her whole life.",
   exampleJa:"その戦争は、彼女の人生全体に深い影響を与えた。",
   example2:"The old monk's words were short but very profound.",
   exampleJa2:"年老いた僧の言葉は短かったが、とても深遠だった。",
   etymologyProcess:"pro（前へ）＋ found（底）→ ずっと底のほうまで届くと…？",
   etymologyConclusion:"pro（前へ）＋ found（底）→ ずっと底のほうまで届いている＝（影響が）深い，重大な",
   etymologyMore:["考えが心の奥底まで届く→（考え・知識が）深い，深遠な"],
   relatedWords:[
     {word:"foundation",meaning:"土台；設立",breakdown:"found（底）＋ ation（名詞）→ 建物のいちばん底の部分"},
     {word:"fundamental",meaning:"基本的な",breakdown:"fund（底）＋ al（～の）→ 底にある土台の"},
     {word:"fund",meaning:"資金",breakdown:"fund（底）→ 事業の底を支えるお金"},
     {synonym:true,word:"deep",meaning:"深い",breakdown:"ふつうの「深い」。profound は影響や考えに使うかたい語"}]},

  {id:1796,word:"grim",partOfSpeech:"形容詞",meaning:"（見通しが）暗い，厳しい；（表情が）険しい",
   meanings:["形|（見通しが）暗い，厳しい","形|（表情が）険しい，こわばった"],
   pronunciation:"/ɡrɪm/",part:180,
   example:"The future looked grim after the factory closed down.",
   exampleJa:"工場が閉鎖されたあと、先行きは暗く厳しく見えた。",
   example2:"His face was grim when he read the test results.",
   exampleJa2:"テストの結果を読んだとき、彼の表情は険しかった。",
   etymologyProcess:"grim（荒々しい）→ 恐ろしげで明るさのない様子は…？",
   etymologyConclusion:"grim（荒々しい）→ 恐ろしげで明るさがまったくない＝（見通しが）暗い，厳しい",
   hook:"古英語で「荒々しい，恐ろしい」。grim reality（厳しい現実）の形でよく使う。",
   etymologyMore:["恐ろしげにこわばった顔→（表情が）険しい，こわばった"],
   relatedWords:[
     {synonym:true,word:"dark",meaning:"暗い",breakdown:"光がない。grim は先行きや気分が暗い"},
     {synonym:true,word:"serious",meaning:"深刻な；まじめな",breakdown:"軽くない様子。grim は恐ろしさや暗さが強い"},
     {synonym:true,word:"gloomy",meaning:"陰気な，憂うつな",breakdown:"どんよりと暗い。grim は厳しくて冷たい"},
     {synonym:true,word:"severe",meaning:"厳しい，深刻な",breakdown:"程度が激しい。grim は見通しの暗さ"}]},

  {id:1797,word:"fierce",partOfSpeech:"形容詞",meaning:"（争い・風雨が）激しい，猛烈な",
   meanings:["形|（争い・風雨が）激しい，猛烈な","形|（動物が）どう猛な"],
   pronunciation:"/fɪrs/",part:180,
   example:"There was fierce competition for the last concert ticket.",
   exampleJa:"最後のコンサートのチケットをめぐって、激しい争いがあった。",
   example2:"Keep away from that dog because it can be fierce.",
   exampleJa2:"あの犬はどう猛になることがあるので、近づかないように。",
   etymologyProcess:"fier（野生の）→ 野生の獣のように荒々しいと…？",
   etymologyConclusion:"fier（野生の）→ 野生の獣のように荒々しく猛烈な＝（争い・風雨が）激しい，猛烈な",
   hook:"ラテン語 ferus（野生の）からフランス語を通って来た語。fierce competition（激しい競争）で覚える。",
   etymologyMore:["もとの「野生の獣のような」→（動物が）どう猛な"],
   relatedWords:[
     {synonym:true,word:"wild",meaning:"野生の；荒れた",breakdown:"自然のままの。fierce は荒々しく襲いかかる感じ"},
     {synonym:true,word:"violent",meaning:"暴力的な；激しい",breakdown:"力で傷つける。fierce は勢いの激しさ"},
     {synonym:true,word:"strong",meaning:"強い",breakdown:"ふつうの「強い」。fierce は荒々しいほど強い"},
     {synonym:true,word:"intense",meaning:"強烈な",breakdown:"程度が非常に強い。fierce は争いや風雨に多い"}]},

  {id:1798,word:"harsh",partOfSpeech:"形容詞",meaning:"（環境・罰が）過酷な；（言葉が）きつい",
   meanings:["形|（環境・罰が）過酷な，厳しすぎる","形|（言葉・態度が）きつい，とげとげしい","形|（光・音が）どぎつい，耳ざわりな"],
   pronunciation:"/hɑːrʃ/",part:180,
   example:"Few plants can survive in the harsh desert climate.",
   exampleJa:"過酷な砂漠の気候で生き残れる植物はほとんどない。",
   example2:"I regret saying such harsh words to my best friend.",
   exampleJa2:"親友にあんなきつい言葉を言ったことを後悔している。",
   etymologyProcess:"harsh（ざらざらした）→ 肌に痛いほどざらつく環境は…？",
   etymologyConclusion:"harsh（ざらざらした）→ 肌に痛いほどざらついて耐えがたい＝（環境・罰が）過酷な",
   hook:"北欧系の「ざらざらした」から来たとされる。harsh words（きつい言葉）で覚える。",
   etymologyMore:["聞くと心がざらつく→（言葉・態度が）きつい，とげとげしい","目や耳にざらつく→（光・音が）どぎつい，耳ざわりな"],
   relatedWords:[
     {synonym:true,word:"strict",meaning:"厳しい",breakdown:"規則にうるさい。harsh は思いやりがなく過酷"},
     {synonym:true,word:"rough",meaning:"ざらざらした；乱暴な",breakdown:"表面が粗い。harsh のもとの感じに近い"},
     {synonym:true,word:"severe",meaning:"厳しい，深刻な",breakdown:"程度が激しい。harsh は受ける側につらい"},
     {synonym:true,word:"cruel",meaning:"残酷な",breakdown:"わざと苦しめる。harsh は結果として厳しすぎる"}]},

  {id:1799,word:"acute",partOfSpeech:"形容詞",meaning:"（問題が）差し迫って深刻な；（痛みが）鋭い",
   meanings:["形|（問題・不足が）差し迫って深刻な","形|（痛み・病気が）鋭い，急性の","形|（感覚が）鋭い"],
   pronunciation:"/əˈkjuːt/",part:180,
   example:"There is an acute shortage of doctors in rural areas.",
   exampleJa:"地方では、差し迫って深刻な医師不足が起きている。",
   example2:"She suddenly felt an acute pain in her stomach.",
   exampleJa2:"彼女は突然、胃に鋭い痛みを感じた。",
   etymologyProcess:"acu（鋭い）→ 針先のように鋭く突き刺さる問題は…？",
   etymologyConclusion:"acu（鋭い）→ 針先のように鋭く突き刺さり、放っておけない＝（問題が）差し迫って深刻な",
   etymologyMore:["もとの「針先のように鋭い」→（痛み・病気が）鋭い，急性の","感じ取る力がとがっている→（感覚が）鋭い"],
   relatedWords:[
     {word:"acupuncture",meaning:"鍼治療",breakdown:"acu（鋭い）＋ punct（点）→ 鋭い針で体の点を刺す"},
     {word:"acid",meaning:"酸；すっぱい",breakdown:"acid（鋭い）→ 舌を鋭く刺すようなすっぱさ"},
     {synonym:true,word:"sharp",meaning:"鋭い",breakdown:"ふつうの「鋭い」。acute は痛みや問題に使うかたい語"},
     {synonym:true,word:"serious",meaning:"深刻な",breakdown:"軽くない。acute は今すぐ手を打つべき深刻さ"}]},

  {id:1800,word:"ambiguous",partOfSpeech:"形容詞",meaning:"（意味が）2通りに取れる，曖昧な",
   meanings:["形|（意味が）2通りに取れる，曖昧な","形|（態度が）どっちつかずの"],
   pronunciation:"/æmˈbɪɡjuəs/",part:180,
   example:"The question on the test was ambiguous, so many students got confused.",
   exampleJa:"テストのその問題は2通りに取れたので、多くの生徒が混乱した。",
   example2:"Her reply was so ambiguous that I didn't know what she meant.",
   exampleJa2:"彼女の返事はとても曖昧だったので、何を言いたいのか分からなかった。",
   etymologyProcess:"ambi（まわりを）＋ ag（行う）→ 意味があちこちへうろうろすると…？",
   etymologyConclusion:"ambi（まわりを）＋ ag（行う）＋ ous（形容詞）→ 意味があちこち行き来して一つに定まらない＝（意味が）2通りに取れる，曖昧な",
   why:"【なぜ】ラテン語 ambigere は「まわりを動き回る」から「どちらとも決めかねる」という意味になりました。意味が2つの方向をうろうろして一つに定まらない様子から「2通りに取れる，曖昧な」が生まれました。\n【つながり】ambition（野心）も「票を求めて歩き回る」から。vague はぼやけた曖昧さ、ambiguous は2通りに取れる曖昧さです。",
   spelling:"ag→ig（ラテン語 ambiguus の形）",
   etymologyMore:["どちらへ動くか決まらない→（態度が）どっちつかずの"],
   relatedWords:[
     {word:"ambition",meaning:"野心，大望",breakdown:"ambi（まわりを）＋ it（行く）→ 票を求めて歩き回る"},
     {word:"agent",meaning:"代理人",breakdown:"ag（行う）＋ ent（人）→ 人に代わって行う人"},
     {word:"ambiguity",meaning:"曖昧さ",breakdown:"ambi（まわりを）＋ ag（行う）＋ ity（名詞）→ 意味が定まらないこと"},
     {synonym:true,word:"vague",meaning:"曖昧な，ぼんやりした",breakdown:"輪郭がぼやけた。ambiguous は2通りに取れる"}]},
