  {id:1251,word:"prime",partOfSpeech:"形容詞",meaning:"最重要な，第一の",
   meanings:["形|最重要な，第一の","形|（品質が）最上の"],
   pronunciation:"/praɪm/",part:126,
   example:"Safety is our prime concern on this school trip.",
   exampleJa:"安全は、この修学旅行での最重要の関心事だ。",
   example2:"Speed was not the prime cause of that accident.",
   exampleJa2:"速度は、あの事故の第一の原因ではなかった。",
   etymologyProcess:"prim（第一の）→ すべての中で第一に置かれると…？",
   etymologyConclusion:"prim（第一の）→ すべての中で、まっさきに第一に置かれる＝最重要な",
   relatedWords:[
     {word:"primary",meaning:"第一の，主要な",breakdown:"prim（第一の）＋ ary（形容詞）→ いちばん初めに来る"},
     {word:"primitive",meaning:"原始的な",breakdown:"prim（第一の）＋ ive（形容詞）→ いちばん初めの姿のままの"},
     {word:"prince",meaning:"王子",breakdown:"prim（第一の）＋ cept（取る）→ 国で第一の地位を取る者"},
     {synonym:true,word:"chief",meaning:"主要な",breakdown:"頭に立つもの。prime は順位の第一に置かれることを言う"}]},

  {id:1252,word:"definite",partOfSpeech:"形容詞",meaning:"明確な，はっきりした",
   meanings:["形|明確な，はっきりした"],
   pronunciation:"/ˈdefɪnət/",part:126,
   example:"We need a definite answer before next Monday morning.",
   exampleJa:"来週の月曜の朝までに、明確な答えが必要だ。",
   example2:"There is no definite proof for his strange story.",
   exampleJa2:"彼の奇妙な話には、明確な証拠がない。",
   etymologyProcess:"de（すっかり）＋ fin（終わり）→ はしまですっかり区切られていると…？",
   etymologyConclusion:"de（すっかり）＋ fin（終わり）＋ ite（〜された）→ はしまですっかり区切られている＝明確な",
   relatedWords:[
     {word:"define",meaning:"定義する",breakdown:"de（すっかり）＋ fin（終わり）→ 意味のはしをすっかり区切る"},
     {word:"final",meaning:"最後の",breakdown:"fin（終わり）＋ al（形容詞）→ 終わりにあたる"},
     {word:"finish",meaning:"終える",breakdown:"fin（終わり）＋ ish（〜にする）→ 終わりの状態にする"},
     {word:"infinite",meaning:"無限の",breakdown:"in（否定）＋ fin（終わり）→ 終わりというものが来ない"}]},

  {id:1253,word:"evident",partOfSpeech:"形容詞",meaning:"明白な，見てすぐ分かる",
   meanings:["形|明白な，見てすぐ分かる"],
   pronunciation:"/ˈevɪdənt/",part:126,
   example:"It was evident that he had not slept well.",
   exampleJa:"彼がよく眠っていなかったのは明白だった。",
   example2:"Her musical talent became evident at a very young age.",
   exampleJa2:"彼女の音楽の才能は、とても幼いころに明白になった。",
   etymologyProcess:"ex（外へ）＋ vid（見る）→ 外から見てすぐそれと分かると…？",
   etymologyConclusion:"ex（外へ）＋ vid（見る）→ 外から見ただけですぐそれと分かる＝明白な",
   relatedWords:[
     {word:"evidence",meaning:"証拠",breakdown:"ex（外へ）＋ vid（見る）＋ ence（名詞）→ 外から見て分かる証し"},
     {word:"video",meaning:"動画，ビデオ",breakdown:"vid（見る）→ 目で見るためのもの"},
     {word:"provide",meaning:"供給する",breakdown:"pro（前もって）＋ vid（見る）→ 先を見越して用意しておく"},
     {word:"envy",meaning:"うらやましく思う",breakdown:"in（〜に）＋ vid（見る）→ 相手の持ち物をじっと見てほしくなる"}]},

  {id:1254,word:"prominent",partOfSpeech:"形容詞",meaning:"目立った；著名な",
   meanings:["形|目立った，際立った","形|著名な"],
   pronunciation:"/ˈprɑːmɪnənt/",part:126,
   example:"The tall tower is a prominent feature of this city.",
   exampleJa:"その高い塔は、この都市の目立った特徴だ。",
   example2:"She became a prominent scientist in her early forties.",
   exampleJa2:"彼女は40代の初めに、著名な科学者になった。",
   etymologyProcess:"pro（前へ）＋ mine（突き出る）→ 前へ突き出ていて人目を引くと…？",
   etymologyConclusion:"pro（前へ）＋ mine（突き出る）→ 前へぐっと突き出ていて人目を引く＝目立った",
   relatedWords:[
     {word:"eminent",meaning:"著名な",breakdown:"e（外へ）＋ mine（突き出る）→ ほかより外へ抜きん出ている"},
     {word:"imminent",meaning:"差し迫った",breakdown:"in（上に）＋ mine（突き出る）→ すぐ上に迫り出してきている"},
     {synonym:true,word:"noticeable",meaning:"目につく",breakdown:"気づかれやすいこと。prominent は前へ突き出て目立つこと"},
     {synonym:true,word:"famous",meaning:"有名な",breakdown:"広く知られること。prominent は際立って目立つことを言う"}]},

  {id:1255,word:"marked",partOfSpeech:"形容詞",meaning:"際立った，目立つ",
   meanings:["形|（違いが）際立った，目立つ"],
   pronunciation:"/mɑːrkt/",part:126,
   example:"There was a marked change in his whole attitude.",
   exampleJa:"彼の態度全体に、際立った変化があった。",
   example2:"The team showed marked improvement during this whole season.",
   exampleJa2:"そのチームは今季を通して、際立った進歩を見せた。",
   etymologyProcess:"mark（しるし）＋ ed（〜された）→ しるしを付けたようにはっきり違うと…？",
   etymologyConclusion:"mark（しるし）＋ ed（〜された）→ しるしを付けたようにはっきり違いが分かる＝際立った",
   relatedWords:[
     {word:"mark",meaning:"しるし；印をつける",breakdown:"mark（しるし）→ 見て分かるようにつけた印"},
     {word:"remark",meaning:"述べる；意見",breakdown:"re（強く）＋ mark（しるし）→ 心にしるしを付けて口に出す"},
     {word:"remarkable",meaning:"注目すべき",breakdown:"re（強く）＋ mark（しるし）＋ able（できる）→ 印をつけたくなるほどの"},
     {word:"landmark",meaning:"目印，名所",breakdown:"land（土地）＋ mark（しるし）→ 土地の目印になるもの"}]},

  {id:1256,word:"grace",partOfSpeech:"名詞",meaning:"優美さ，上品さ",
   meanings:["名|優美さ，上品さ","名|（神の）恵み"],
   pronunciation:"/ɡreɪs/",part:126,
   example:"She moved across the wide stage with great grace.",
   exampleJa:"彼女はこのうえない優美さで、広い舞台を横切った。",
   example2:"The young dancer's grace surprised the whole audience.",
   exampleJa2:"その若いダンサーの優美さは、観客全体を驚かせた。",
   etymologyProcess:"grat（心地よい）→ 見る人を心地よくさせる美しさなら…？",
   etymologyConclusion:"grat（心地よい）→ 見る人を心地よくさせる、しなやかな美しさ＝優美さ",
   relatedWords:[
     {word:"grateful",meaning:"感謝している",breakdown:"grat（心地よい）＋ ful（満ちた）→ ありがたい気持ちで満ちている"},
     {word:"congratulate",meaning:"祝う",breakdown:"con（共に）＋ grat（心地よい）→ 共に心地よさを分かち合う"},
     {word:"agree",meaning:"賛成する",breakdown:"ad（〜へ）＋ grat（心地よい）→ 心地よいほうへ心が寄る"},
     {word:"gratitude",meaning:"感謝",breakdown:"grat（心地よい）＋ tude（名詞）→ ありがたいと思う気持ち"}]},

  {id:1257,word:"charm",partOfSpeech:"名詞",meaning:"魅力",
   meanings:["名|魅力，人を引きつける力","他|魅了する"],
   pronunciation:"/tʃɑːrm/",part:126,
   example:"The small town has a quiet old-fashioned charm.",
   exampleJa:"その小さな町には、静かで昔ふうの魅力がある。",
   example2:"Her warm smile charmed everyone at the birthday party.",
   exampleJa2:"彼女の温かい笑顔は、誕生日会のみんなを魅了した。",
   etymologyProcess:"carm（呪文）→ 呪文をかけたように人の心を引きつけると…？",
   etymologyConclusion:"carm（呪文）→ 呪文をかけたように、人の心を引きつける力＝魅力",
   why:"【なぜ】ラテン語 carmen は「歌・呪文」。呪文で人の心を操るという考えから、「人の心を引きつける力」＝魅力になりました。お守りの「チャーム」には、呪文の意味が今も残っています。\n【つながり】fascinate（まじないをかけたように魅了する）も、同じ発想から生まれた語です。",
   relatedWords:[
     {synonym:true,word:"fascinate",meaning:"魅了する",breakdown:"まじないのように心を奪うこと。charm は引きつける力そのもの"},
     {synonym:true,word:"attraction",meaning:"魅力，呼び物",breakdown:"引きつけるもの。charm は人をうっとりさせる魅力を指す"},
     {word:"charming",meaning:"魅力的な",breakdown:"carm（呪文）＋ ing（〜している）→ 呪文のように人を引きつけている"},
     {synonym:true,word:"appeal",meaning:"心に響くこと",breakdown:"心に働きかける力。charm はうっとりさせる魅力を指す"}]},

  {id:1258,word:"fancy",partOfSpeech:"形容詞",meaning:"高級な，凝った",
   meanings:["形|高級な，凝った，しゃれた","他|～したい気がする"],
   pronunciation:"/ˈfænsi/",part:126,
   example:"They ate dinner at a very fancy French restaurant.",
   exampleJa:"彼らは、とても高級なフランス料理店で夕食をとった。",
   example2:"I do not need fancy clothes for this short trip.",
   exampleJa2:"この短い旅行に、高級な服は必要ない。",
   etymologyProcess:"phan（見せる）→ 想像で思い描いたように飾り立てると…？",
   etymologyConclusion:"phan（見せる）→ 想像で思い描いたように、凝って飾り立てた＝高級な",
   why:"【なぜ】fancy は fantasy（空想）が短くなった語。「思い描いたとおりの、手のこんだもの」という使い方から、「装飾的な・しゃれた・高級な」になりました。\n【つながり】fantasy（空想）、phantom（幻）も同じ「見せる」の家族。動詞の fancy は「〜したい気がする」です。",
   relatedWords:[
     {word:"fantasy",meaning:"空想",breakdown:"phan（見せる）＋ y（名詞）→ 心に思い描いて見せるもの"},
     {word:"phantom",meaning:"幻，幽霊",breakdown:"phan（見せる）→ 実体がないのに見えてしまうもの"},
     {word:"emphasize",meaning:"強調する",breakdown:"em（中へ）＋ phas（見せる）→ 中から押し出して見せつける"},
     {synonym:true,word:"luxurious",meaning:"ぜいたくな",breakdown:"あり余るほど豪華なこと。fancy は凝った飾りのある感じ"}]},

  {id:1259,word:"rational",partOfSpeech:"形容詞",meaning:"理性的な，筋の通った",
   meanings:["形|理性的な，筋の通った"],
   pronunciation:"/ˈræʃnəl/",part:126,
   example:"He always gives a rational answer to every question.",
   exampleJa:"彼はどんな問いにも、いつも理性的な答えを出す。",
   example2:"He tried to stay rational during the long argument.",
   exampleJa2:"彼は長い議論の間、理性的でいようとした。",
   etymologyProcess:"rat（計算する）＋ al（形容詞）→ きちんと筋道を計算して考えると…？",
   etymologyConclusion:"rat（計算する）＋ al（形容詞）→ きちんと筋道を計算して考える＝理性的な",
   relatedWords:[
     {word:"rate",meaning:"割合；評価する",breakdown:"rat（計算する）→ 計算して出したときの割合"},
     {word:"ratio",meaning:"比率",breakdown:"rat（計算する）→ 計算して出した、二つのものの割合"},
     {word:"reason",meaning:"理由；理性",breakdown:"rat（計算する）→ 筋道を計算して出した根拠"},
     {synonym:true,word:"logical",meaning:"論理的な",breakdown:"筋道が通ること。rational は感情に流されず考えることを言う"}]},

  {id:1260,word:"magnificent",partOfSpeech:"形容詞",meaning:"壮大な，見事な",
   meanings:["形|壮大な，見事な"],
   pronunciation:"/mæɡˈnɪfɪsnt/",part:126,
   example:"We saw a magnificent view from the high mountain top.",
   exampleJa:"私たちは、高い山頂から壮大な眺めを見た。",
   example2:"The old stone cathedral is truly magnificent inside.",
   exampleJa2:"その古い石の大聖堂は、内部が本当に壮大だ。",
   etymologyProcess:"magn（大きい）＋ fic（作る）→ 大きく作り上げられて見る者を圧倒すると…？",
   etymologyConclusion:"magn（大きい）＋ fic（作る）→ 大きく作り上げられ、見る者を圧倒する＝壮大な",
   relatedWords:[
     {word:"magnify",meaning:"拡大する",breakdown:"magn（大きい）＋ fy（する）→ 大きく見えるようにする"},
     {word:"magnitude",meaning:"大きさ，規模",breakdown:"magn（大きい）＋ tude（名詞）→ どれだけ大きいかという度合い"},
     {word:"major",meaning:"主要な，大きいほうの",breakdown:"maj（大きい）＋ or（より〜な）→ 二つのうち大きいほう"},
     {synonym:true,word:"splendid",meaning:"見事な",breakdown:"輝くほど見事なこと。magnificent は大きさで圧倒する壮大さ"}]},

  {id:1261,word:"superior",partOfSpeech:"形容詞",meaning:"より優れている",
   meanings:["形|（to ～）（～より）優れている","形|上位の"],
   pronunciation:"/suːˈpɪriər/",part:127,
   example:"This new model is superior to the old one.",
   exampleJa:"この新しい型は、古いものより優れている。",
   example2:"Their team showed superior skill in the final match.",
   exampleJa2:"彼らのチームは、決勝戦でより優れた技を見せた。",
   etymologyProcess:"super（上から）＋ ior（より〜な）→ 他より一段上に立っていると…？",
   etymologyConclusion:"super（上から）＋ ior（より〜な）→ 他より一段上に立っている＝より優れている",
   relatedWords:[
     {word:"supervise",meaning:"監督する",breakdown:"super（上から）＋ vis（見る）→ 上から全体を見張る"},
     {word:"superb",meaning:"すばらしい",breakdown:"super（上から）→ 群を抜いて上にある"},
     {word:"supermarket",meaning:"スーパー",breakdown:"super（上から）＋ market（市場）→ ふつうの市場を上回る大きな店"},
     {word:"surface",meaning:"表面",breakdown:"sur（上の）＋ face（顔）→ いちばん上に現れている面"}]},

  {id:1262,word:"loyal",partOfSpeech:"形容詞",meaning:"忠実な",
   meanings:["形|（to ～）（～に）忠実な"],
   pronunciation:"/ˈlɔɪəl/",part:127,
   example:"A loyal friend never leaves you in real trouble.",
   exampleJa:"忠実な友は、本当に困ったときに決してあなたを見捨てない。",
   example2:"The old dog stayed loyal to its kind owner.",
   exampleJa2:"その老犬は、優しい飼い主に忠実であり続けた。",
   etymologyProcess:"leg（法）＋ al（形容詞）→ 決まりにかなって相手を裏切らないと…？",
   etymologyConclusion:"leg（法）＋ al（形容詞）→ 決まりにかなって相手を裏切らない＝忠実な",
   why:"【なぜ】ラテン語 legalis は「法にかなった」。約束や決まりを守って裏切らないことから「忠実な」になりました。同じ語がまっすぐ英語に入ったのが legal（法律の）です。\n【つながり】legal（法律の）、privilege（その人だけに認められた決まり）も同じ leg の家族です。",
   relatedWords:[
     {word:"legal",meaning:"法律の，合法の",breakdown:"leg（法）＋ al（形容詞）→ 法にかなっている"},
     {word:"privilege",meaning:"特権",breakdown:"privi（個人の）＋ leg（法）→ その人だけに認められた決まり"},
     {word:"legislation",meaning:"立法，法律",breakdown:"leg（法）＋ lat（運ぶ）→ 法を作って世に運び出すこと"},
     {synonym:true,word:"faithful",meaning:"忠実な，誠実な",breakdown:"信頼を裏切らないこと。loyal は味方であり続けることを言う"}]},

  {id:1263,word:"horrible",partOfSpeech:"形容詞",meaning:"とてもひどい，ぞっとする",
   meanings:["形|とてもひどい，ぞっとする"],
   pronunciation:"/ˈhɔːrəbl/",part:127,
   example:"The weather was horrible during our whole school trip.",
   exampleJa:"修学旅行の間ずっと、天気はとてもひどかった。",
   example2:"He told us a horrible story about the train accident.",
   exampleJa2:"彼はその列車事故についての、ぞっとする話を聞かせた。",
   etymologyProcess:"horr（ぞっとする）＋ ible（できる）→ 身の毛がよだつほどぞっとさせると…？",
   etymologyConclusion:"horr（ぞっとする）＋ ible（できる）→ 身の毛がよだつほどぞっとさせる＝とてもひどい",
   relatedWords:[
     {word:"horror",meaning:"恐怖",breakdown:"horr（ぞっとする）＋ or（もの）→ 身の毛がよだつ思い"},
     {word:"horrify",meaning:"ぞっとさせる",breakdown:"horr（ぞっとする）＋ fy（する）→ 身の毛がよだつ思いをさせる"},
     {synonym:true,word:"terrible",meaning:"ひどい",breakdown:"terr（恐れさせる）から出た語。horrible はぞっとする感じが強い"},
     {synonym:true,word:"awful",meaning:"ひどい",breakdown:"awe（畏れ）から出た語。horrible はぞっとする不快さを言う"}]},

  {id:1264,word:"miserable",partOfSpeech:"形容詞",meaning:"悲惨な，みじめな",
   meanings:["形|悲惨な，みじめな","形|（気分が）ひどく沈んだ"],
   pronunciation:"/ˈmɪzrəbl/",part:127,
   example:"They lived in miserable conditions after the long war.",
   exampleJa:"彼らは長い戦争の後、悲惨な状況で暮らした。",
   example2:"I felt miserable with a bad cold all weekend.",
   exampleJa2:"私は週末ずっと、ひどいかぜでみじめな気分だった。",
   etymologyProcess:"miser（みじめな）＋ able（できる）→ 見ていてかわいそうになるほどつらいと…？",
   etymologyConclusion:"miser（みじめな）＋ able（できる）→ 見ていてかわいそうになるほどつらい＝悲惨な",
   relatedWords:[
     {word:"misery",meaning:"みじめさ，悲惨",breakdown:"miser（みじめな）＋ y（名詞）→ つらくみじめな状態そのもの"},
     {synonym:true,word:"unhappy",meaning:"不幸な",breakdown:"幸せでないこと。miserable は見ていてつらいほど悲惨なこと"},
     {synonym:true,word:"wretched",meaning:"みじめな",breakdown:"ひどくみじめなこと。miserable は気分の落ち込みにも使う"},
     {synonym:true,word:"poor",meaning:"かわいそうな；貧しい",breakdown:"気の毒なこと。miserable はその状態のひどさを言う"}]},

  {id:1265,word:"dull",partOfSpeech:"形容詞",meaning:"退屈な；（刃が）鈍い",
   meanings:["形|退屈な，さえない","形|（刃が）鈍い"],
   pronunciation:"/dʌl/",part:127,
   example:"The long meeting was dull from start to finish.",
   exampleJa:"その長い会議は、初めから終わりまで退屈だった。",
   example2:"This old knife is too dull to cut meat.",
   exampleJa2:"この古いナイフは鈍すぎて、肉が切れない。",
   etymologyProcess:"dull（愚かでにぶい）→ 切れ味も面白みもなく心を動かさないと…？",
   etymologyConclusion:"dull（にぶい）→ 切れ味も面白みもなく、心を動かさない＝退屈な",
   hook:"刃が「にぶい」も話が「退屈」も同じ dull。切れ味がない感じ。",
   relatedWords:[
     {synonym:true,word:"boring",meaning:"退屈な",breakdown:"飽きさせること。dull は刺激がなく鈍い感じを言う"},
     {synonym:true,word:"tedious",meaning:"長くて退屈な",breakdown:"だらだら続くこと。dull は面白みがないことを言う"},
     {synonym:true,word:"blunt",meaning:"（刃が）鈍い",breakdown:"切れ味が悪いこと。dull は刃にも話にも使える"},
     {synonym:true,word:"dim",meaning:"ぼんやりした",breakdown:"薄暗くはっきりしないこと。dull は面白みのなさにも使う"}]},

  {id:1266,word:"nasty",partOfSpeech:"形容詞",meaning:"不快な，いやな",
   meanings:["形|不快な，いやな","形|意地の悪い"],
   pronunciation:"/ˈnæsti/",part:127,
   example:"There was a nasty smell in the old kitchen.",
   exampleJa:"その古い台所には、不快なにおいがあった。",
   example2:"He said something nasty about his own close friend.",
   exampleJa2:"彼は、自分の親しい友人について意地の悪いことを言った。",
   etymologyProcess:"nasty（汚らしい）→ 思わず顔をしかめるほど汚らしいと…？",
   etymologyConclusion:"nasty（汚らしい）→ 思わず顔をしかめるほど汚らしくていやな＝不快な",
   hook:"語源ははっきりしない。汚い・意地悪い・ひどい、と幅広く使える。",
   relatedWords:[
     {synonym:true,word:"unpleasant",meaning:"不愉快な",breakdown:"感じがよくないこと。nasty はもっとくだけて強い言い方"},
     {synonym:true,word:"dirty",meaning:"汚い",breakdown:"汚れていること。nasty は汚らしくて不快なことを言う"},
     {synonym:true,word:"mean",meaning:"意地の悪い",breakdown:"人に冷たいこと。nasty はその言い方がひどいことを言う"},
     {synonym:true,word:"awful",meaning:"ひどい",breakdown:"程度がひどいこと。nasty は不快さ・汚さのほうを指す"}]},

  {id:1267,word:"insane",partOfSpeech:"形容詞",meaning:"正気でない",
   meanings:["形|正気でない，非常識な"],
   pronunciation:"/ɪnˈseɪn/",part:127,
   example:"Driving at that high speed is completely insane.",
   exampleJa:"あんな高い速度で運転するのは、まったく正気でない。",
   example2:"The idea sounded insane at first to almost everyone.",
   exampleJa2:"その考えは最初、ほとんどの人には正気でなく聞こえた。",
   etymologyProcess:"in（否定）＋ san（健全な）→ 心が健全でなくなっていると…？",
   etymologyConclusion:"in（否定）＋ san（健全な）→ 心が健全に働かなくなっている＝正気でない",
   relatedWords:[
     {word:"sane",meaning:"正気の",breakdown:"san（健全な）→ 心が健全に働いている"},
     {word:"sanitation",meaning:"衛生（設備）",breakdown:"san（健全な）＋ ation（名詞）→ 体を健全に保つための仕組み"},
     {word:"sanitary",meaning:"衛生的な",breakdown:"san（健全な）＋ ary（形容詞）→ 健康を保てるほど清潔な"},
     {synonym:true,word:"crazy",meaning:"気が狂った",breakdown:"くだけた語。insane は医学や法律の場でも使う硬い語"}]},

  {id:1268,word:"ridiculous",partOfSpeech:"形容詞",meaning:"ばかげた",
   meanings:["形|ばかげた，笑ってしまうほどおかしい"],
   pronunciation:"/rɪˈdɪkjələs/",part:127,
   example:"That excuse sounds completely ridiculous to everyone in class.",
   exampleJa:"その言い訳は、クラスのみんなにまったくばかげて聞こえる。",
   example2:"He wore a ridiculous hat to the school party.",
   exampleJa2:"彼は学校のパーティーに、ばかげた帽子をかぶってきた。",
   etymologyProcess:"ridi（笑う）＋ cul（小さい）→ 思わず笑ってしまうほど筋が通らないと…？",
   etymologyConclusion:"ridi（笑う）＋ cul（小さい）＋ ous（形容詞）→ 思わず笑うほど筋が通らない＝ばかげた",
   relatedWords:[
     {word:"ridicule",meaning:"あざ笑う",breakdown:"ridi（笑う）＋ cul（小さい）→ 小ばかにして笑う"},
     {synonym:true,word:"absurd",meaning:"不合理な",breakdown:"筋が通らないこと。ridiculous は笑ってしまうほどばかげたこと"},
     {synonym:true,word:"silly",meaning:"ばかげた",breakdown:"子どもっぽくばかげたこと。ridiculous はあきれるほどひどい"},
     {word:"deride",meaning:"あざ笑う",breakdown:"de（下へ）＋ ridi（笑う）→ 相手を見下して笑う"}]},

  {id:1269,word:"rotten",partOfSpeech:"形容詞",meaning:"腐った",
   meanings:["形|腐った","形|ひどい，最低の"],
   pronunciation:"/ˈrɑːtn/",part:127,
   example:"The rotten apples smelled very bad in the box.",
   exampleJa:"腐ったリンゴが、箱の中でとてもひどいにおいを放っていた。",
   example2:"These eggs are rotten, so please do not use them.",
   exampleJa2:"これらの卵は腐っているので、使わないでください。",
   etymologyProcess:"rot（腐る）＋ en（〜された）→ すっかり腐ってくずれてしまうと…？",
   etymologyConclusion:"rot（腐る）＋ en（〜された）→ すっかり腐って、くずれてしまった＝腐った",
   relatedWords:[
     {word:"rot",meaning:"腐る",breakdown:"rot（腐る）→ 中からくずれていたんでいく"},
     {synonym:true,word:"decay",meaning:"腐敗する，衰える",breakdown:"ゆっくり崩れること。rotten はすでに腐った状態を表す"},
     {synonym:true,word:"spoil",meaning:"だめにする，腐らせる",breakdown:"食べ物がだめになること。rotten はその結果の状態を指す"},
     {synonym:true,word:"stale",meaning:"古くなった",breakdown:"新鮮でないこと。rotten はもっと進んで腐った状態を指す"}]},

  {id:1270,word:"notorious",partOfSpeech:"形容詞",meaning:"悪名高い",
   meanings:["形|（for ～で）（～で）悪名高い"],
   pronunciation:"/noʊˈtɔːriəs/",part:127,
   example:"That street is notorious for its heavy traffic jams.",
   exampleJa:"その通りは、ひどい渋滞で悪名高い。",
   example2:"He was a notorious pirate in those old days.",
   exampleJa2:"彼はその昔の時代、悪名高い海賊だった。",
   etymologyProcess:"not（知る）＋ ous（形容詞）→ 悪いことで広く知られてしまうと…？",
   etymologyConclusion:"not（知る）＋ ous（形容詞）→ 悪いことのほうで広く知られてしまっている＝悪名高い",
   why:"【なぜ】ラテン語 notorius は「よく知られた」で、もとは良し悪しを問いませんでした。英語では悪い評判で知られる場合に使われるようになり、「悪名高い」に固まりました。\n【つながり】notice（気づく）、notion（考え）も同じ not（知る）の家族です。",
   relatedWords:[
     {word:"notice",meaning:"気づく；掲示",breakdown:"not（知る）→ それと知って気づくこと"},
     {word:"notion",meaning:"考え",breakdown:"not（知る）＋ ion（名詞）→ 頭の中に知られた形として浮かぶもの"},
     {synonym:true,word:"infamous",meaning:"悪名高い",breakdown:"ほぼ同じ意味。notorious は「〜で知られる」の形でよく使う"},
     {synonym:true,word:"famous",meaning:"有名な",breakdown:"よい意味でも使える。notorious は悪い評判に限って使う"}]},

  {id:1271,word:"evil",partOfSpeech:"形容詞",meaning:"邪悪な，悪い",
   meanings:["形|邪悪な，悪い","名|悪，害悪"],
   pronunciation:"/ˈiːvl/",part:128,
   example:"The old story tells of a cruel and evil king.",
   exampleJa:"その古い物語は、残酷で邪悪な王について語っている。",
   example2:"Greed can turn a good person truly evil.",
   exampleJa2:"欲は、善良な人を本当に邪悪に変えてしまうことがある。",
   etymologyProcess:"evil（度を越した）→ 度を越して人を傷つけようとすると…？",
   etymologyConclusion:"evil（度を越した）→ 度を越して、人を傷つけようとする＝邪悪な",
   hook:"live（生きる）を逆から読むと evil。覚え方として有名な語呂合わせ。",
   relatedWords:[
     {synonym:true,word:"wicked",meaning:"邪悪な",breakdown:"ほぼ同じ意味。evil はもっと強く、根本から悪いことを言う"},
     {synonym:true,word:"bad",meaning:"悪い",breakdown:"よくないこと全般。evil は道徳の上で深く悪いことを指す"},
     {synonym:true,word:"cruel",meaning:"残酷な",breakdown:"むごい仕打ちをすること。evil は心そのものが悪いこと"},
     {synonym:true,word:"sin",meaning:"罪",breakdown:"宗教の上での罪。evil はその根にある悪そのものを指す"}]},

  {id:1272,word:"mess",partOfSpeech:"名詞",meaning:"乱雑，散らかり",
   meanings:["名|乱雑，散らかり","名|困った状態"],
   pronunciation:"/mes/",part:128,
   example:"Please clean up this terrible mess before dinner time.",
   exampleJa:"夕食の時間の前に、このひどい散らかりを片づけてください。",
   example2:"His small room was always in a complete mess.",
   exampleJa2:"彼の小さな部屋は、いつも完全に散らかっていた。",
   etymologyProcess:"mis（送る）→ 食卓へ送られた料理が寄せ集まって乱れると…？",
   etymologyConclusion:"mis（送る）→ 食卓へ送られた料理の寄せ集め。そこから散らかった状態＝乱雑",
   why:"【なぜ】もとは「食卓へ運ばれる一皿の料理」。兵士が大皿から取り分けて食べる食事（mess）の乱れた様子から、「ごちゃごちゃ・散らかり」の意味になりました。\n【つながり】mission（送り出される任務）、submit（下へ差し出す）も同じ「送る」の家族です。",
   relatedWords:[
     {word:"mission",meaning:"任務",breakdown:"mis（送る）＋ ion（名詞）→ 送り出されて果たす役目"},
     {word:"submit",meaning:"提出する",breakdown:"sub（下で）＋ mit（送る）→ 目上の人の下へ差し出す"},
     {word:"permit",meaning:"許可する",breakdown:"per（通して）＋ mit（送る）→ 通り抜けて行かせてやる"},
     {word:"dismiss",meaning:"退ける",breakdown:"dis（離れて）＋ mis（送る）→ 向こうへ送り出して取り合わない"}]},

  {id:1273,word:"vast",partOfSpeech:"形容詞",meaning:"広大な，膨大な",
   meanings:["形|広大な，膨大な"],
   pronunciation:"/væst/",part:128,
   example:"A vast desert stretches beyond those low brown hills.",
   exampleJa:"広大な砂漠が、あの低い茶色の丘の向こうに広がっている。",
   example2:"The library holds a vast amount of old information.",
   exampleJa2:"その図書館は、膨大な量の古い情報を収めている。",
   etymologyProcess:"vast（荒れ果てた）→ 果てしなく広がってがらんとしていると…？",
   etymologyConclusion:"vast（荒れ果てた）→ 果てしなく広がって、がらんとしている＝広大な",
   relatedWords:[
     {word:"waste",meaning:"むだにする；荒れ地",breakdown:"wast（荒れ果てた）→ 使わないまま荒れさせてしまう"},
     {word:"devastate",meaning:"壊滅させる",breakdown:"de（すっかり）＋ vast（荒れ果てた）→ すっかり荒れ果てた姿に変える"},
     {synonym:true,word:"huge",meaning:"巨大な",breakdown:"とても大きいこと。vast は広がりの果てしなさを言う"},
     {synonym:true,word:"immense",meaning:"計り知れない",breakdown:"測れないほど大きいこと。vast は見わたす限りの広がり"}]},

  {id:1274,word:"huge",partOfSpeech:"形容詞",meaning:"巨大な",
   meanings:["形|巨大な，ばく大な"],
   pronunciation:"/hjuːdʒ/",part:128,
   example:"A huge wave suddenly hit the small fishing boat.",
   exampleJa:"巨大な波が突然、その小さな漁船を襲った。",
   example2:"They built a huge new stadium near the river.",
   exampleJa2:"彼らは川の近くに、巨大な新しい競技場を建てた。",
   etymologyProcess:"huge（とてつもない）→ 見上げるほどとてつもなく大きいと…？",
   etymologyConclusion:"huge（とてつもない）→ 見上げるほど、とてつもなく大きい＝巨大な",
   hook:"語源ははっきりしない。very big をひと言で言う、いちばん身近な語。",
   relatedWords:[
     {synonym:true,word:"enormous",meaning:"巨大な",breakdown:"並外れて大きいこと。huge はもっとくだけた言い方"},
     {synonym:true,word:"giant",meaning:"巨大な；巨人",breakdown:"巨人のように大きいこと。huge は大きさ一般に使える"},
     {synonym:true,word:"vast",meaning:"広大な",breakdown:"果てしない広がり。huge はかさや量の大きさを言う"},
     {synonym:true,word:"massive",meaning:"どっしり大きい",breakdown:"重くて大きいこと。huge は単に大きいことを言う"}]},

  {id:1275,word:"tiny",partOfSpeech:"形容詞",meaning:"とても小さな",
   meanings:["形|とても小さな，ごく小さな"],
   pronunciation:"/ˈtaɪni/",part:128,
   example:"A tiny insect crawled across the clean white paper.",
   exampleJa:"とても小さな虫が、きれいな白い紙の上をはっていった。",
   example2:"She keeps a tiny vegetable garden behind her house.",
   exampleJa2:"彼女は家の裏に、とても小さな野菜畑を持っている。",
   etymologyProcess:"tiny（ごく小さい）→ 目をこらさないと見えないほど小さいと…？",
   etymologyConclusion:"tiny（ごく小さい）→ 目をこらさないと見えないほど小さい＝とても小さな",
   hook:"語源ははっきりしない。small よりさらに小さいときに使う。",
   relatedWords:[
     {synonym:true,word:"small",meaning:"小さい",breakdown:"ふつうに小さいこと。tiny はそれよりずっと小さいことを言う"},
     {synonym:true,word:"little",meaning:"小さい",breakdown:"かわいらしく小さいこと。tiny は大きさの小ささを強く言う"},
     {synonym:true,word:"minute",meaning:"ごく小さい",breakdown:"細かくて小さいこと。tiny はくだけた日常語として使う"},
     {synonym:true,word:"slight",meaning:"わずかな",breakdown:"ごくわずかなこと。tiny は大きさがとても小さいことを言う"}]},

  {id:1276,word:"sphere",partOfSpeech:"名詞",meaning:"球体",
   meanings:["名|球体","名|（活動の）領域"],
   pronunciation:"/sfɪr/",part:128,
   example:"The earth is not a perfect sphere, but slightly flat.",
   exampleJa:"地球は完全な球体ではなく、少し平たい。",
   example2:"A glass sphere hung above the long wooden table.",
   exampleJa2:"ガラスの球体が、長い木のテーブルの上に下がっていた。",
   etymologyProcess:"sphere（球）→ どこから見ても丸い完全な丸いかたまりは…？",
   etymologyConclusion:"sphere（球）→ どこから見ても丸い、完全な丸いかたまり＝球体",
   relatedWords:[
     {word:"atmosphere",meaning:"大気；雰囲気",breakdown:"atmo（蒸気）＋ sphere（球）→ 地球を包んでいる蒸気の球"},
     {word:"hemisphere",meaning:"半球",breakdown:"hemi（半分）＋ sphere（球）→ 球をちょうど半分にしたもの"},
     {synonym:true,word:"ball",meaning:"ボール，球",breakdown:"丸いもの。sphere は数学や科学で言う完全な球を指す"},
     {synonym:true,word:"globe",meaning:"地球儀；球",breakdown:"丸い球。sphere は形としての球そのものを指す"}]},

  {id:1277,word:"strip",partOfSpeech:"名詞",meaning:"細長い一片",
   meanings:["名|細長い一片，細長い区域","他|はぎ取る"],
   pronunciation:"/strɪp/",part:128,
   example:"She cut the colored paper into thin long strips.",
   exampleJa:"彼女は色紙を、細く長い一片に切った。",
   example2:"A narrow strip of land divides the two lakes.",
   exampleJa2:"細長い一片の土地が、その2つの湖を分けている。",
   etymologyProcess:"strip（細長い帯）→ 布や紙を細長く切り取ったものは…？",
   etymologyConclusion:"strip（細長い帯）→ 布や紙などを細長く切り取った一片＝細長い一片",
   hook:"stripe（しま模様）と同じ「細長い」の仲間。細長いひと切れが芯。",
   relatedWords:[
     {synonym:true,word:"stripe",meaning:"しま模様",breakdown:"細長い線の模様。strip は切り取った細長い一片を指す"},
     {synonym:true,word:"band",meaning:"帯",breakdown:"巻きつける細長いもの。strip は切り取った細長い片"},
     {synonym:true,word:"ribbon",meaning:"リボン",breakdown:"飾り用の細長い布。strip はもっと広く細長い片を指す"},
     {synonym:true,word:"piece",meaning:"かけら，一片",breakdown:"一部分。strip は特に細長い形の一片を指す"}]},

  {id:1278,word:"vessel",partOfSpeech:"名詞",meaning:"（体の）管；船",
   meanings:["名|（血管などの）管","名|（大きな）船","名|容器"],
   pronunciation:"/ˈvesl/",part:128,
   example:"Blood vessels carry oxygen to every part of the body.",
   exampleJa:"血管は、体のすみずみへ酸素を運んでいる。",
   example2:"A large fishing vessel entered the quiet small harbor.",
   exampleJa2:"大きな漁船が、静かな小さな港に入ってきた。",
   etymologyProcess:"vas（器）＋ el（小さい）→ 中に液を入れて運ぶ小さな器なら…？",
   etymologyConclusion:"vas（器）＋ el（小さい）→ 中に液を入れて運ぶ小さな器や管＝体の管",
   relatedWords:[
     {word:"vase",meaning:"花びん",breakdown:"vas（器）→ 花を生けるための器"},
     {synonym:true,word:"container",meaning:"容器",breakdown:"中身を入れる物。vessel は液を運ぶ器や血管を指す"},
     {synonym:true,word:"ship",meaning:"船",breakdown:"海を行く乗り物。vessel は改まった言い方の「船」"},
     {synonym:true,word:"tube",meaning:"管",breakdown:"細長い筒。vessel は体の中の血管を指すことが多い"}]},

  {id:1279,word:"internal",partOfSpeech:"形容詞",meaning:"内部の",
   meanings:["形|内部の，内側の","形|（国の）国内の"],
   pronunciation:"/ɪnˈtɜːrnl/",part:128,
   example:"The company started an internal investigation last week.",
   exampleJa:"その会社は先週、内部の調査を始めた。",
   example2:"Doctors checked his internal organs very carefully yesterday.",
   exampleJa2:"医師たちは昨日、彼の体の内部の臓器をとても注意深く調べた。",
   etymologyProcess:"intern（内側の）＋ al（形容詞）→ 外から見えない内側にあると…？",
   etymologyConclusion:"intern（内側の）＋ al（形容詞）→ 外からは見えない内側にある＝内部の",
   relatedWords:[
     {word:"interior",meaning:"内部（の）",breakdown:"intern（内側の）＋ ior（より〜な）→ より内側にある部分"},
     {word:"intern",meaning:"実習生",breakdown:"intern（内側の）→ 組織の内側に入って学ぶ人"},
     {synonym:true,word:"inner",meaning:"内側の",breakdown:"内にあること。internal は組織や体の内部を指す硬い語"},
     {synonym:true,word:"domestic",meaning:"国内の",breakdown:"国の中のこと。internal は組織や国の内部の問題を指す"}]},

  {id:1280,word:"mobile",partOfSpeech:"形容詞",meaning:"動きやすい，流動的な",
   meanings:["形|動きやすい，流動的な","形|携帯式の"],
   pronunciation:"/ˈmoʊbl/",part:128,
   example:"Young workers today are very mobile between big cities.",
   exampleJa:"今日の若い働き手は、大きな都市の間をとても移動しやすい。",
   example2:"She uses a mobile phone for all her daily work.",
   exampleJa2:"彼女は日々の仕事すべてに、携帯電話を使っている。",
   etymologyProcess:"mob（動かす）＋ ile（できる）→ 自由に動かすことができると…？",
   etymologyConclusion:"mob（動かす）＋ ile（できる）→ 自由に動かすことができる＝動きやすい",
   relatedWords:[
     {word:"mobility",meaning:"動きやすさ，移動性",breakdown:"mob（動かす）＋ ity（名詞）→ どれだけ動けるかという度合い"},
     {word:"automobile",meaning:"自動車",breakdown:"auto（自分）＋ mob（動かす）→ 自分の力で動く車"},
     {word:"motion",meaning:"動き",breakdown:"mot（動かす）＋ ion（名詞）→ 動いているということ"},
     {word:"emotion",meaning:"感情",breakdown:"e（外へ）＋ mot（動かす）→ 心が外へ動き出して表に現れるもの"}]},

  {id:1281,word:"steep",partOfSpeech:"形容詞",meaning:"険しい，急な",
   meanings:["形|（坂などが）険しい，急な"],
   pronunciation:"/stiːp/",part:129,
   example:"The narrow path to the temple is very steep.",
   exampleJa:"寺へ行く細い道は、とても険しい。",
   example2:"We climbed a steep hill behind the old school.",
   exampleJa2:"私たちは、古い学校の裏の険しい丘を登った。",
   etymologyProcess:"steep（そそり立つ）→ 壁のようにそそり立って登りにくいと…？",
   etymologyConclusion:"steep（そそり立つ）→ 壁のようにそそり立っていて登りにくい＝険しい",
   hook:"もとの意味は「高くそそり立つ」。坂や値段の急さにも使う。",
   relatedWords:[
     {synonym:true,word:"sharp",meaning:"急な，鋭い",breakdown:"角度が鋭いこと。steep は登れないほどの急な傾きを言う"},
     {synonym:true,word:"sheer",meaning:"切り立った",breakdown:"まっすぐ切り立つこと。steep は傾きの急さを広く言う"},
     {word:"steeple",meaning:"尖塔",breakdown:"steep（そそり立つ）→ 空へそそり立つ教会の細い塔"},
     {synonym:true,word:"abrupt",meaning:"急な",breakdown:"だしぬけに変わること。steep は坂の傾きの急さを言う"}]},

  {id:1282,word:"intense",partOfSpeech:"形容詞",meaning:"強烈な，激しい",
   meanings:["形|強烈な，激しい"],
   pronunciation:"/ɪnˈtens/",part:129,
   example:"The intense heat made everyone stay inside all day.",
   exampleJa:"その強烈な暑さが、一日中みんなを室内にとどめた。",
   example2:"She felt intense pressure before the final piano contest.",
   exampleJa2:"彼女はピアノの決勝大会の前に、強烈な重圧を感じた。",
   etymologyProcess:"in（中へ）＋ tend（伸ばす）→ 中でぴんと張りつめて力がこもると…？",
   etymologyConclusion:"in（中へ）＋ tend（伸ばす）→ 中でぴんと張りつめて力がこもっている＝強烈な",
   relatedWords:[
     {word:"tend",meaning:"傾向がある",breakdown:"tend（伸ばす）→ 心がそちらへ伸びていく"},
     {word:"extend",meaning:"伸ばす，広げる",breakdown:"ex（外へ）＋ tend（伸ばす）→ 外へ向けて伸ばしていく"},
     {word:"attend",meaning:"出席する",breakdown:"ad（〜へ）＋ tend（伸ばす）→ 心をそちらへ伸ばして出向く"},
     {word:"extent",meaning:"程度，広がり",breakdown:"ex（外へ）＋ tend（伸ばす）→ どこまで伸び広がっているかの幅"}]},

  {id:1283,word:"inevitable",partOfSpeech:"形容詞",meaning:"避けられない",
   meanings:["形|避けられない，必然の"],
   pronunciation:"/ɪnˈevɪtəbl/",part:129,
   example:"Change is inevitable in every growing young company.",
   exampleJa:"変化は、成長するどの若い会社でも避けられない。",
   example2:"The delay was inevitable, so everyone arrived very late.",
   exampleJa2:"その遅れは避けられなかったので、みんなとても遅く到着した。",
   etymologyProcess:"in（否定）＋ evit（避ける）＋ able（できる）→ どうやっても避けられないと…？",
   etymologyConclusion:"in（否定）＋ evit（避ける）＋ able（できる）→ どうやっても避けることができない＝避けられない",
   relatedWords:[
     {word:"inevitably",meaning:"必然的に",breakdown:"in（否定）＋ evit（避ける）＋ ly（副詞）→ 避けようがなく必ず"},
     {synonym:true,word:"unavoidable",meaning:"避けられない",breakdown:"ほぼ同じ意味。inevitable は「必ずそうなる」含みが強い"},
     {synonym:true,word:"certain",meaning:"確実な",breakdown:"間違いないこと。inevitable は避けようがなく必ず起こること"},
     {synonym:true,word:"necessary",meaning:"必然の，必要な",breakdown:"欠かせないこと。inevitable は起こるのを止められないことを言う"}]},

  {id:1284,word:"neutral",partOfSpeech:"形容詞",meaning:"中立の",
   meanings:["形|中立の，どちらにもつかない"],
   pronunciation:"/ˈnuːtrəl/",part:129,
   example:"Switzerland stayed neutral during both of the world wars.",
   exampleJa:"スイスは、両方の世界大戦の間ずっと中立のままだった。",
   example2:"A judge must stay neutral in every single case.",
   exampleJa2:"裁判官は、どの事件でも中立でいなければならない。",
   etymologyProcess:"ne（否定）＋ uter（二つのうちどちらか）→ どちら側にもつかないと…？",
   etymologyConclusion:"ne（否定）＋ uter（二つのうちどちらか）→ 二つのどちら側にもつかない＝中立の",
   relatedWords:[
     {word:"neutralize",meaning:"中和する，無効にする",breakdown:"ne（否定）＋ uter（二つのうちどちらか）→ どちらでもない状態にする"},
     {word:"neutron",meaning:"中性子",breakdown:"ne（否定）＋ uter（二つのうちどちらか）→ プラスにもマイナスにも寄らない粒"},
     {synonym:true,word:"impartial",meaning:"公平な",breakdown:"かたよらないこと。neutral はどちらにも味方しないことを言う"},
     {synonym:true,word:"fair",meaning:"公平な",breakdown:"えこひいきしないこと。neutral は立場を取らないことを言う"}]},

  {id:1285,word:"brief",partOfSpeech:"形容詞",meaning:"手短な，短時間の",
   meanings:["形|手短な，短時間の"],
   pronunciation:"/briːf/",part:129,
   example:"He gave a brief speech at the school opening ceremony.",
   exampleJa:"彼は学校の開会式で、手短なスピーチをした。",
   example2:"Please write a brief summary of this long article.",
   exampleJa2:"この長い記事の手短な要約を書いてください。",
   etymologyProcess:"brev（短い）→ 時間や言葉が短く切り詰められていると…？",
   etymologyConclusion:"brev（短い）→ 時間や言葉が短く切り詰められている＝手短な",
   relatedWords:[
     {word:"briefly",meaning:"手短に",breakdown:"brev（短い）＋ ly（副詞）→ 短く切り詰めて"},
     {word:"abbreviate",meaning:"省略する",breakdown:"ad（〜へ）＋ brev（短い）→ 短くなるほうへ縮める"},
     {word:"briefcase",meaning:"書類かばん",breakdown:"brev（短い）＋ case（箱）→ 要点を書いた書類を入れる箱"},
     {synonym:true,word:"short",meaning:"短い",breakdown:"長さが短いこと。brief は時間や話が短いことを言う"}]},

  {id:1286,word:"bare",partOfSpeech:"形容詞",meaning:"むき出しの，何もつけていない",
   meanings:["形|むき出しの，何もつけていない"],
   pronunciation:"/ber/",part:129,
   example:"He walked on the cold floor with bare feet.",
   exampleJa:"彼はむき出しの足で、冷たい床を歩いた。",
   example2:"The winter trees stood bare against the gray sky.",
   exampleJa2:"冬の木々は、灰色の空を背にむき出しで立っていた。",
   etymologyProcess:"bare（おおいのない）→ 何も着せず、覆いもないままだと…？",
   etymologyConclusion:"bare（おおいのない）→ 何も着せず、覆いもかけていない＝むき出しの",
   relatedWords:[
     {word:"barely",meaning:"かろうじて",breakdown:"bare（おおいのない）＋ ly（副詞）→ 余分をそぎ落としてぎりぎり"},
     {synonym:true,word:"naked",meaning:"裸の",breakdown:"服を着ていないこと。bare は覆いがない状態全般に使う"},
     {synonym:true,word:"empty",meaning:"空の",breakdown:"中に何もないこと。bare は表面に覆いがないことを言う"},
     {synonym:true,word:"plain",meaning:"飾りのない",breakdown:"飾りがないこと。bare は覆いがまったくないことを言う"}]},

  {id:1287,word:"mutual",partOfSpeech:"形容詞",meaning:"相互の，互いの",
   meanings:["形|相互の，互いの"],
   pronunciation:"/ˈmjuːtʃuəl/",part:129,
   example:"The two countries signed a mutual trade agreement yesterday.",
   exampleJa:"両国は昨日、相互の貿易協定に署名した。",
   example2:"Their long friendship is based on deep mutual respect.",
   exampleJa2:"彼らの長い友情は、深い互いの敬意に基づいている。",
   etymologyProcess:"mut（変える）＋ al（形容詞）→ 互いに入れかわるようにやりとりすると…？",
   etymologyConclusion:"mut（変える）＋ al（形容詞）→ 互いに入れかわるようにやりとりし合う＝相互の",
   relatedWords:[
     {word:"mutation",meaning:"突然変異",breakdown:"mut（変える）＋ ation（名詞）→ 姿が急に変わってしまうこと"},
     {word:"commute",meaning:"通勤する",breakdown:"com（すっかり）＋ mut（変える）→ 場所を入れかえて行き来する"},
     {synonym:true,word:"shared",meaning:"共通の",breakdown:"分け合うこと。mutual は互いに向け合っていることを言う"},
     {synonym:true,word:"common",meaning:"共通の",breakdown:"みんなに当てはまること。mutual は二者の間のやりとりを指す"}]},

  {id:1288,word:"potential",partOfSpeech:"形容詞",meaning:"潜在的な，可能性のある",
   meanings:["形|潜在的な，可能性のある","名|可能性，潜在力"],
   pronunciation:"/pəˈtenʃl/",part:129,
   example:"He is a potential leader of this very young team.",
   exampleJa:"彼は、このとても若いチームの潜在的な指導者だ。",
   example2:"Teachers try to find each student's hidden potential.",
   exampleJa2:"先生たちは、それぞれの生徒の隠れた可能性を見つけようとする。",
   etymologyProcess:"pot（力がある）＋ al（形容詞）→ 表には出ていないが力を秘めていると…？",
   etymologyConclusion:"pot（力がある）＋ al（形容詞）→ 表には出ていないが、内に力を秘めている＝潜在的な",
   relatedWords:[
     {word:"potent",meaning:"強力な",breakdown:"pot（力がある）＋ ent（〜している）→ 大きな力を持っている"},
     {word:"power",meaning:"力",breakdown:"pot（力がある）→ 物事を動かすことのできる力"},
     {word:"possible",meaning:"可能な",breakdown:"poss（できる）＋ ible（できる）→ 実現する見込みがある"},
     {synonym:true,word:"hidden",meaning:"隠れた",breakdown:"見えていないこと。potential は力が中に秘められていること"}]},

  {id:1289,word:"tough",partOfSpeech:"形容詞",meaning:"たくましい；困難な",
   meanings:["形|たくましい，ねばり強い","形|困難な，手ごわい"],
   pronunciation:"/tʌf/",part:129,
   example:"She is tough enough to run every single morning.",
   exampleJa:"彼女は毎朝走れるほど、たくましい。",
   example2:"This is a tough question for young students.",
   exampleJa2:"これは、若い生徒には困難な問題だ。",
   etymologyProcess:"tough（強くてしなやか）→ 引っぱっても切れないほど強くねばると…？",
   etymologyConclusion:"tough（強くてしなやか）→ 引っぱっても切れないほど強くねばる＝たくましい",
   hook:"「タフな人」でそのまま通じる。強くてねばり強いのが芯。",
   relatedWords:[
     {synonym:true,word:"strong",meaning:"強い",breakdown:"力が強いこと。tough はねばって折れない強さを言う"},
     {synonym:true,word:"hard",meaning:"固い；難しい",breakdown:"固いこと。tough は固くてもしなやかに耐える強さ"},
     {synonym:true,word:"durable",meaning:"長持ちする",breakdown:"長く持つこと。tough は簡単には壊れない丈夫さを言う"},
     {synonym:true,word:"firm",meaning:"しっかりした",breakdown:"ぐらつかないこと。tough はねばり強く耐えることを言う"}]},

  {id:1290,word:"conventional",partOfSpeech:"形容詞",meaning:"従来の，型どおりの",
   meanings:["形|従来の，型どおりの"],
   pronunciation:"/kənˈvenʃənl/",part:129,
   example:"Many farmers still use conventional growing methods here.",
   exampleJa:"ここでは、多くの農家が今も従来の栽培方法を使っている。",
   example2:"This bold design is far from conventional office furniture.",
   exampleJa2:"この大胆なデザインは、従来の事務家具とはかけ離れている。",
   etymologyProcess:"con（共に）＋ vent（来る）→ みんなが共に集まって決めてきたとおりだと…？",
   etymologyConclusion:"con（共に）＋ vent（来る）→ みんなが共に集まって決めてきたとおりの＝従来の",
   relatedWords:[
     {word:"convention",meaning:"慣習；大会",breakdown:"con（共に）＋ vent（来る）＋ ion（名詞）→ 共に集まって決めたならわし"},
     {word:"event",meaning:"できごと，行事",breakdown:"e（外へ）＋ vent（来る）→ 外に現れ出てきたできごと"},
     {word:"invent",meaning:"発明する",breakdown:"in（上に）＋ vent（来る）→ 探していたものに行き当たって見つけ出す"},
     {word:"prevent",meaning:"防ぐ",breakdown:"pre（先に）＋ vent（来る）→ 先回りして来させないようにする"}]},

  {id:1291,word:"supreme",partOfSpeech:"形容詞",meaning:"最高の，至高の",
   meanings:["形|最高の，至高の"],
   pronunciation:"/suːˈpriːm/",part:130,
   example:"Her skill is supreme among all the players here.",
   exampleJa:"彼女の技術は、ここの全選手の中で最高だ。",
   example2:"Safety is of supreme importance in this large factory.",
   exampleJa2:"安全は、この大きな工場では最高に重要だ。",
   etymologyProcess:"suprem（いちばん上）→ それ以上のものがないいちばん上だと…？",
   etymologyConclusion:"suprem（いちばん上）→ それ以上のものがない、いちばん上の＝最高の",
   relatedWords:[
     {word:"summit",meaning:"頂上；首脳会談",breakdown:"summ（いちばん上）→ 山のいちばん上のところ"},
     {word:"sum",meaning:"合計",breakdown:"sum（いちばん上）→ 足し算の答えを上に書いたことから"},
     {word:"super",meaning:"超～，すごい",breakdown:"super（上から）→ ふつうより上にあること"},
     {synonym:true,word:"highest",meaning:"最高の",breakdown:"いちばん高いこと。supreme は位や重要さの最高を言う"}]},

  {id:1292,word:"resemble",partOfSpeech:"他動詞",meaning:"似ている",
   meanings:["他|～に似ている"],
   pronunciation:"/rɪˈzembl/",part:130,
   example:"She resembles her mother in many small ways.",
   exampleJa:"彼女は多くの細かい点で、母親に似ている。",
   example2:"This town resembles the one where I grew up.",
   exampleJa2:"この町は、私が育った町に似ている。",
   etymologyProcess:"re（再び）＋ simil（似ている）→ もう一人の自分を見るようだと…？",
   etymologyConclusion:"re（再び）＋ simil（似ている）→ もう一人の自分を見るようによく似ている＝似ている",
   relatedWords:[
     {word:"similar",meaning:"似ている",breakdown:"simil（似ている）＋ ar（形容詞）→ 形やようすが近い"},
     {word:"simulate",meaning:"まねる，模擬する",breakdown:"simil（似ている）＋ ate（動詞）→ 似せて作ってみせる"},
     {word:"assemble",meaning:"組み立てる；集まる",breakdown:"ad（〜へ）＋ simul（一緒に）→ ばらばらの物を一か所へ寄せ集める"},
     {synonym:true,word:"look like",meaning:"～に見える",breakdown:"見た目が似ていること。resemble は前置詞なしで目的語を取る"}]},

  {id:1293,word:"contrary",partOfSpeech:"形容詞",meaning:"反対の，逆の",
   meanings:["形|（to ～）（～と）反対の，逆の","名|（on the contrary で）それどころか"],
   pronunciation:"/ˈkɑːntreri/",part:130,
   example:"His opinion is contrary to the strict school rules.",
   exampleJa:"彼の意見は、その厳しい校則とは反対だ。",
   example2:"On the contrary, the new plan worked very well.",
   exampleJa2:"それどころか、その新しい計画はとてもうまくいった。",
   etymologyProcess:"contra（逆に）＋ ary（形容詞）→ 向かい合って正反対を向いていると…？",
   etymologyConclusion:"contra（逆に）＋ ary（形容詞）→ 向かい合って正反対を向いている＝反対の",
   relatedWords:[
     {word:"contrast",meaning:"対比，対照",breakdown:"contra（逆に）＋ st（立つ）→ 逆を向いて並び立つこと"},
     {word:"counter",meaning:"逆らう；カウンター",breakdown:"counter（向かい合う）→ 向かい合って受け止める"},
     {word:"encounter",meaning:"偶然出会う",breakdown:"en（中に）＋ counter（向かい合う）→ 思いがけず正面から向かい合う"},
     {synonym:true,word:"opposite",meaning:"反対の",breakdown:"向かい側にあること。contrary は考えや性質が正反対なこと"}]},

  {id:1294,word:"category",partOfSpeech:"名詞",meaning:"部類，範疇",
   meanings:["名|部類，範疇，分類"],
   pronunciation:"/ˈkætəɡɔːri/",part:130,
   example:"This book belongs to the science fiction category.",
   exampleJa:"この本は、空想科学の部類に属する。",
   example2:"We put each item into a different category yesterday.",
   exampleJa2:"私たちは昨日、それぞれの品目を別々の部類に入れた。",
   etymologyProcess:"cata（下へ）＋ agor（広場）→ 広場で公に言い分けたひとまとまりは…？",
   etymologyConclusion:"cata（下へ）＋ agor（広場）→ 広場で公に言い分けたひとまとまり＝部類",
   why:"【なぜ】ギリシャ語 katēgoria は、もともと「広場で公に言い立てること（告発）」。アリストテレスがこの語を「物事を言い分ける枠組み」の意味で使ったことから、「範疇・部類」になりました。\n【つながり】cata（下へ）は catalog（下へ書き連ねた一覧）にも出てきます。",
   relatedWords:[
     {word:"catalog",meaning:"カタログ，目録",breakdown:"cata（下へ）＋ log（言葉）→ 下へ書き連ねた一覧"},
     {word:"categorize",meaning:"分類する",breakdown:"cata（下へ）＋ agor（広場）＋ ize（動詞）→ 部類ごとに分ける"},
     {synonym:true,word:"type",meaning:"型，種類",breakdown:"似たもののまとまり。category は分け方として決めた部類"},
     {synonym:true,word:"class",meaning:"分類，等級",breakdown:"段階で分けたまとまり。category は性質で分けた部類"}]},

  {id:1295,word:"scope",partOfSpeech:"名詞",meaning:"範囲，及ぶ範囲",
   meanings:["名|範囲，及ぶ範囲","名|（活動の）余地"],
   pronunciation:"/skoʊp/",part:130,
   example:"This question is outside the scope of our study.",
   exampleJa:"この問いは、私たちの研究の範囲の外にある。",
   example2:"The new job offers a wide scope for creativity.",
   exampleJa2:"その新しい仕事は、創造性を発揮する広い範囲を与えてくれる。",
   etymologyProcess:"scop（見る）→ 目で見わたせる広がり、手の届く先なら…？",
   etymologyConclusion:"scop（見る）→ 目で見わたせる広がり。そこから力の及ぶ広さ＝範囲",
   why:"【なぜ】ギリシャ語 skopos はもともと「目で狙う的」。望遠鏡（telescope）のように「どこまで見えるか」が、そのまま「どこまで力が及ぶか＝範囲」になりました。\n【つながり】-scope の付く語は、どれも「見るための道具」です。",
   relatedWords:[
     {word:"telescope",meaning:"望遠鏡",breakdown:"tele（遠く）＋ scop（見る）→ 遠くを見るための道具"},
     {word:"microscope",meaning:"顕微鏡",breakdown:"micro（小さい）＋ scop（見る）→ 小さなものを見るための道具"},
     {synonym:true,word:"range",meaning:"範囲，幅",breakdown:"広がりの幅。scope は目や力の及ぶ範囲を言う"},
     {synonym:true,word:"extent",meaning:"程度，広がり",breakdown:"どこまで及ぶか。scope は扱える範囲のほうを指す"}]},

  {id:1296,word:"given",partOfSpeech:"形容詞",meaning:"定められた，特定の",
   meanings:["形|定められた，特定の","前|～を考えると"],
   pronunciation:"/ˈɡɪvn/",part:130,
   example:"You must finish the work in a given time.",
   exampleJa:"定められた時間の中で、その仕事を終えなければならない。",
   example2:"Any given student may borrow up to five books.",
   exampleJa2:"どの特定の生徒も、5冊まで本を借りることができる。",
   etymologyProcess:"give（与える）＋ en（〜された）→ あらかじめ与えられて決まっていると…？",
   etymologyConclusion:"give（与える）＋ en（〜された）→ あらかじめ与えられて決まっている＝定められた",
   relatedWords:[
     {word:"give",meaning:"与える",breakdown:"give（与える）→ 自分の手から相手のほうへ渡す"},
     {word:"forgive",meaning:"許す",breakdown:"give（与える）→ 罰を求める気持ちを、すっかり手放して与えないでおく"},
     {word:"gift",meaning:"贈り物；才能",breakdown:"give（与える）→ 与えられたもの。生まれつきの才能も指す"},
     {synonym:true,word:"specific",meaning:"特定の",breakdown:"はっきり決まったもの。given は前もって定められていること"}]},

  {id:1297,word:"peculiar",partOfSpeech:"形容詞",meaning:"固有の；奇妙な",
   meanings:["形|（to ～）（～に）固有の","形|奇妙な，風変わりな"],
   pronunciation:"/pɪˈkjuːliər/",part:130,
   example:"This custom is peculiar to our small island.",
   exampleJa:"この習慣は、私たちの小さな島に固有のものだ。",
   example2:"There was a peculiar smell in the empty old room.",
   exampleJa2:"その空っぽの古い部屋には、奇妙なにおいがあった。",
   etymologyProcess:"pecu（家畜）＋ ar（形容詞）→ 自分の財産のようにその人だけに属すと…？",
   etymologyConclusion:"pecu（家畜）＋ ar（形容詞）→ 自分の財産のように、その人だけに属する＝固有の",
   why:"【なぜ】ラテン語 pecu は「家畜」。昔は家畜が個人の財産だったので、peculium は「自分だけの持ち物」でした。そこから「その人・その土地だけの＝固有の」、さらに「他と違う＝奇妙な」へ広がりました。\n【つながり】pecuniary（金銭の）も同じ「家畜＝財産」の家族です。",
   relatedWords:[
     {word:"peculiarity",meaning:"特有の性質",breakdown:"pecu（家畜）＋ ar（形容詞）＋ ity（名詞）→ その人だけに属する性質"},
     {word:"peculiarly",meaning:"独特に；妙に",breakdown:"pecu（家畜）＋ ar（形容詞）＋ ly（副詞）→ その人だけのやり方で"},
     {synonym:true,word:"unique",meaning:"唯一の，独特の",breakdown:"ただ一つのもの。peculiar はその人や土地だけに属すること"},
     {synonym:true,word:"strange",meaning:"奇妙な",breakdown:"見慣れないこと。peculiar は他と違う独特さのほうを言う"}]},

  {id:1298,word:"sufficient",partOfSpeech:"形容詞",meaning:"十分な",
   meanings:["形|十分な，足りている"],
   pronunciation:"/səˈfɪʃnt/",part:130,
   example:"We do not have sufficient time for this big task.",
   exampleJa:"私たちには、この大きな仕事のための十分な時間がない。",
   example2:"Sufficient sleep is necessary for every growing child.",
   exampleJa2:"十分な睡眠は、育ちざかりのどの子どもにも必要だ。",
   etymologyProcess:"suf（下で）＋ fic（作る）→ 下から支えるだけのものが作られていると…？",
   etymologyConclusion:"suf（下で）＋ fic（作る）→ 下から支えるだけのものが作り出されている＝十分な",
   relatedWords:[
     {word:"sufficiently",meaning:"十分に",breakdown:"suf（下で）＋ fic（作る）＋ ly（副詞）→ 足りるだけそろって"},
     {word:"efficient",meaning:"効率のよい",breakdown:"ef（外へ）＋ fic（作る）→ むだなく成果を外へ作り出す"},
     {word:"difficult",meaning:"難しい",breakdown:"dis（否定）＋ facil（しやすい）→ たやすくはない"},
     {synonym:true,word:"enough",meaning:"十分な",breakdown:"足りること。sufficient は少し硬く、書き言葉で使う"}]},

  {id:1299,word:"numerous",partOfSpeech:"形容詞",meaning:"（数が）多くの",
   meanings:["形|（数が）多くの，たくさんの"],
   pronunciation:"/ˈnuːmərəs/",part:130,
   example:"Numerous new students joined the club this spring.",
   exampleJa:"多くの新入生が、この春その部に入った。",
   example2:"He has made numerous trips to that far country.",
   exampleJa2:"彼はその遠い国へ、多くの旅をしてきた。",
   etymologyProcess:"numer（数）＋ ous（形容詞）→ 数えきれないほど数が多いと…？",
   etymologyConclusion:"numer（数）＋ ous（形容詞）→ 数えきれないほど数が多い＝多くの",
   relatedWords:[
     {word:"number",meaning:"数",breakdown:"numer（数）→ 数えて表したもの"},
     {word:"numerical",meaning:"数の，数字の",breakdown:"numer（数）＋ ical（〜の）→ 数に関わっている"},
     {word:"innumerable",meaning:"数えきれない",breakdown:"in（否定）＋ numer（数）＋ able（できる）→ 数えることができない"},
     {synonym:true,word:"many",meaning:"多くの",breakdown:"数が多いこと。numerous は硬く、書き言葉でよく使う"}]},

  {id:1300,word:"substantial",partOfSpeech:"形容詞",meaning:"かなりの；中身のある",
   meanings:["形|かなりの，相当な","形|中身のある，しっかりした"],
   pronunciation:"/səbˈstænʃl/",part:130,
   example:"The team made substantial progress during this whole year.",
   exampleJa:"チームは今年一年で、かなりの進歩を遂げた。",
   example2:"She received a substantial sum of prize money.",
   exampleJa2:"彼女はかなりの額の賞金を受け取った。",
   etymologyProcess:"sub（下で）＋ sta（立つ）→ 下でしっかり支えるほど中身があると…？",
   etymologyConclusion:"sub（下で）＋ sta（立つ）→ 下でしっかり支えるほど中身がある＝かなりの",
   relatedWords:[
     {word:"substance",meaning:"物質；中身",breakdown:"sub（下で）＋ sta（立つ）→ 見た目の下で全体を支える中身"},
     {word:"stand",meaning:"立つ",breakdown:"sta（立つ）→ 足を地につけてまっすぐ立つ"},
     {word:"circumstance",meaning:"状況",breakdown:"circ（輪を描く）＋ sta（立つ）→ まわりを取り巻いて立っていること"},
     {word:"constant",meaning:"絶え間ない",breakdown:"con（共に）＋ sta（立つ）＋ ant（形容詞）→ ずっと同じ所に立ち続ける"}]},

  {id:1301,word:"unit",partOfSpeech:"名詞",meaning:"単位",
   meanings:["名|単位","名|（組織の）一部隊，一団"],
   pronunciation:"/ˈjuːnɪt/",part:131,
   example:"The meter is a basic unit of length worldwide.",
   exampleJa:"メートルは、世界共通の長さの基本的な単位だ。",
   example2:"Our small team works as one strong unit.",
   exampleJa2:"私たちの小さなチームは、一つの強い一団として働いている。",
   etymologyProcess:"uni（1つの）→ 数えるときの1つ分としたまとまりは…？",
   etymologyConclusion:"uni（1つの）→ 数えるときに1つ分としてひとくくりにしたもの＝単位",
   why:"【なぜ】unit はラテン語からそのまま来た語ではなく、16世紀の数学者ジョン・ディーが unity（ひとつであること）を digit（けた）に似せて短くして作った語です。\n【つながり】unity（まとまり）、union（結合）、unique（唯一の）と同じ uni（1つの）の家族です。",
   relatedWords:[
     {word:"union",meaning:"労働組合；結合",breakdown:"uni（1つの）＋ ion（名詞）→ 一つに結びついた集まり"},
     {word:"unite",meaning:"団結する",breakdown:"uni（1つの）＋ ite（〜された）→ 一つにまとめられる"},
     {word:"unique",meaning:"唯一の",breakdown:"uni（1つの）＋ ique（形容詞）→ たった一つしかない"},
     {word:"uniform",meaning:"制服；均一の",breakdown:"uni（1つの）＋ form（形）→ みんな同じ一つの形"}]},

  {id:1302,word:"diameter",partOfSpeech:"名詞",meaning:"直径",
   meanings:["名|直径"],
   pronunciation:"/daɪˈæmɪtər/",part:131,
   example:"This circle has a diameter of ten centimeters.",
   exampleJa:"この円は、10センチの直径を持っている。",
   example2:"Scientists measured the diameter of the huge old tree.",
   exampleJa2:"科学者たちは、その巨大な古い木の直径を測った。",
   etymologyProcess:"dia（間で）＋ metr（測る）→ 円を突き抜けて端から端まで測ると…？",
   etymologyConclusion:"dia（間で）＋ metr（測る）→ 円を突き抜けて端から端まで測った長さ＝直径",
   relatedWords:[
     {word:"geometry",meaning:"幾何学",breakdown:"geo（大地）＋ metr（測る）→ 土地を測ることから生まれた学問"},
     {word:"thermometer",meaning:"温度計",breakdown:"thermo（熱）＋ metr（測る）→ 熱の高さを測るための道具"},
     {word:"dialogue",meaning:"会話",breakdown:"dia（間で）＋ log（言葉）→ 二人の間で交わされる言葉"},
     {word:"dialect",meaning:"方言",breakdown:"dia（間で）＋ lect（拾う）→ その土地の人どうしで拾い交わす言葉"}]},

  {id:1303,word:"arithmetic",partOfSpeech:"名詞",meaning:"算数，計算",
   meanings:["名|算数，計算"],
   pronunciation:"/əˈrɪθmətɪk/",part:131,
   example:"Young children learn simple arithmetic at elementary school.",
   exampleJa:"幼い子どもたちは、小学校で簡単な算数を学ぶ。",
   example2:"He checked his arithmetic twice before answering the question.",
   exampleJa2:"彼はその問いに答える前に、自分の計算を2回確かめた。",
   etymologyProcess:"arithm（数）＋ ic（名詞）→ 数を足し引きして計算する技なら…？",
   etymologyConclusion:"arithm（数）＋ ic（名詞）→ 数を足し引きして計算していく技＝算数",
   why:"【なぜ】ギリシャ語 arithmos は「数」。それを扱う技という意味の arithmētikē technē（数の技）が短くなって arithmetic になりました。\n【つながり】mathematics（数学）が形や量まで広く扱うのに対し、arithmetic は足し算・引き算などの計算そのものを指します。",
   relatedWords:[
     {synonym:true,word:"mathematics",meaning:"数学",breakdown:"数と形を広く扱う学問。arithmetic はその中の計算の部分"},
     {synonym:true,word:"calculate",meaning:"計算する",breakdown:"計算すること。arithmetic はその計算の技ぜんたいを指す"},
     {synonym:true,word:"number",meaning:"数",breakdown:"数そのもの。arithmetic はそれを足し引きする技を指す"},
     {word:"logarithm",meaning:"対数",breakdown:"log（言葉）＋ arithm（数）→ かけ算を足し算に直すための数"}]},

  {id:1304,word:"quantity",partOfSpeech:"名詞",meaning:"量，分量",
   meanings:["名|量，分量"],
   pronunciation:"/ˈkwɑːntəti/",part:131,
   example:"We need a large quantity of paper for today.",
   exampleJa:"私たちは今日のために、大きな量の紙を必要としている。",
   example2:"Quality is far more important than quantity here.",
   exampleJa2:"ここでは、質のほうが量よりずっと重要だ。",
   etymologyProcess:"quant（どれだけ）＋ ity（名詞）→ どれだけあるかを表す大きさは…？",
   etymologyConclusion:"quant（どれだけ）＋ ity（名詞）→ どれだけあるかを表す大きさ＝量",
   relatedWords:[
     {word:"quality",meaning:"質",breakdown:"qual（どんな）＋ ity（名詞）→ どんなものかという中身"},
     {word:"quantify",meaning:"数値で表す",breakdown:"quant（どれだけ）＋ fy（する）→ どれだけかを数にして示す"},
     {synonym:true,word:"amount",meaning:"量，額",breakdown:"合計の量。quantity は数えられる量にも使える"},
     {synonym:true,word:"volume",meaning:"量，かさ",breakdown:"かさばりの大きさ。quantity は数や量の多さを指す"}]},

  {id:1305,word:"deficiency",partOfSpeech:"名詞",meaning:"欠乏，不足",
   meanings:["名|欠乏，不足","名|欠陥"],
   pronunciation:"/dɪˈfɪʃnsi/",part:131,
   example:"A deficiency of vitamin C causes a serious illness.",
   exampleJa:"ビタミンCの欠乏は、重い病気を引き起こす。",
   example2:"The report showed a deficiency in basic safety training.",
   exampleJa2:"その報告書は、基本的な安全訓練の不足を示していた。",
   etymologyProcess:"de（離して）＋ fic（作る）→ 作るべき分が足りずに欠けていると…？",
   etymologyConclusion:"de（離して）＋ fic（作る）→ 作るべき分が足りずに欠けている状態＝欠乏",
   relatedWords:[
     {word:"deficit",meaning:"赤字，不足額",breakdown:"de（離して）＋ fic（作る）→ 足りずに欠けてしまっている分"},
     {word:"efficient",meaning:"効率のよい",breakdown:"ef（外へ）＋ fic（作る）→ むだなく成果を外へ作り出す"},
     {word:"sufficient",meaning:"十分な",breakdown:"suf（下で）＋ fic（作る）→ 下から支えるだけのものがある"},
     {synonym:true,word:"lack",meaning:"欠乏，不足",breakdown:"足りないこと。deficiency は必要な分が欠けた状態を指す"}]},

  {id:1306,word:"maximum",partOfSpeech:"名詞",meaning:"最大限，最大量",
   meanings:["名|最大限，最大量","形|最大の"],
   pronunciation:"/ˈmæksɪməm/",part:131,
   example:"This elevator can carry a maximum of ten people.",
   exampleJa:"このエレベーターは、最大限10人を運ぶことができる。",
   example2:"Try to get the maximum benefit from each lesson.",
   exampleJa2:"それぞれの授業から、最大限の利益を得るようにしなさい。",
   etymologyProcess:"max（いちばん大きい）→ それ以上は上げられない量なら…？",
   etymologyConclusion:"max（いちばん大きい）→ それ以上は上げられない、いちばん大きい量＝最大限",
   relatedWords:[
     {word:"maximize",meaning:"最大にする",breakdown:"max（いちばん大きい）＋ ize（動詞）→ できる限り大きくする"},
     {word:"major",meaning:"主要な，大きいほうの",breakdown:"maj（大きい）＋ or（より〜な）→ 二つのうち大きいほう"},
     {word:"magnify",meaning:"拡大する",breakdown:"magn（大きい）＋ fy（する）→ 大きく見えるようにする"},
     {synonym:true,word:"limit",meaning:"限界",breakdown:"越えられない境。maximum は上げられる限界の量を指す"}]},

  {id:1307,word:"bunch",partOfSpeech:"名詞",meaning:"束，房",
   meanings:["名|束，房","名|（a bunch of で）たくさんの"],
   pronunciation:"/bʌntʃ/",part:131,
   example:"He gave his mother a big bunch of flowers.",
   exampleJa:"彼は母親に、大きな花の束を贈った。",
   example2:"She bought a bunch of ripe yellow bananas today.",
   exampleJa2:"彼女は今日、熟した黄色いバナナを1房買った。",
   etymologyProcess:"bunch（ひとかたまり）→ 同じものをまとめてひとかたまりにすると…？",
   etymologyConclusion:"bunch（ひとかたまり）→ 同じものをまとめてひとかたまりにしたもの＝束",
   hook:"語源ははっきりしない。a bunch of ～（たくさんの～）の形でよく使う。",
   relatedWords:[
     {synonym:true,word:"bundle",meaning:"束",breakdown:"縛ってまとめたもの。bunch は自然にまとまった房も指す"},
     {synonym:true,word:"group",meaning:"集団",breakdown:"まとまりぜんたい。bunch は手に持てるほどのひとかたまり"},
     {synonym:true,word:"cluster",meaning:"かたまり，房",breakdown:"寄り集まったかたまり。bunch は花や果物の房によく使う"},
     {synonym:true,word:"pile",meaning:"積み重ね",breakdown:"積み上げたもの。bunch は横に寄り集まったひとかたまり"}]},

  {id:1308,word:"lessen",partOfSpeech:"他動詞",meaning:"減らす，やわらげる",
   meanings:["他|減らす，やわらげる","自|減る"],
   pronunciation:"/ˈlesn/",part:131,
   example:"Warm milk may lessen the pain a little tonight.",
   exampleJa:"温かい牛乳は、今夜その痛みを少しやわらげるかもしれない。",
   example2:"Good planning lessens the risk of big mistakes.",
   exampleJa2:"よい計画は、大きな失敗の危険を減らす。",
   etymologyProcess:"les（より少ない）＋ en（〜にする）→ 今より少ない状態にすると…？",
   etymologyConclusion:"les（より少ない）＋ en（〜にする）→ 今よりも少ない状態にする＝減らす",
   why:"【なぜ】less（より少ない）に en（〜にする）が付いた形で、「より少なくする」。lighten（軽くする）、widen（広くする）と同じ作り方です。\n【つながり】発音の同じ lesson（授業）はラテン語 lectio（読むこと）から出た、まったく別の語です。",
   relatedWords:[
     {word:"less",meaning:"より少ない",breakdown:"les（より少ない）→ 量や程度が下のほうにある"},
     {word:"least",meaning:"最も少ない",breakdown:"les（より少ない）＋ est（最も）→ いちばん少ない"},
     {synonym:true,word:"reduce",meaning:"減らす",breakdown:"量を減らすこと。lessen は程度を少なくすることを言う"},
     {synonym:true,word:"decrease",meaning:"減る",breakdown:"だんだん減ること。lessen は減らす側の動きを言う"}]},

  {id:1309,word:"era",partOfSpeech:"名詞",meaning:"時代",
   meanings:["名|（ひとまとまりの）時代"],
   pronunciation:"/ˈɪrə/",part:131,
   example:"We now live in the era of the internet.",
   exampleJa:"私たちは今、インターネットの時代に生きている。",
   example2:"That long era ended with the death of the king.",
   exampleJa2:"その長い時代は、王の死とともに終わった。",
   etymologyProcess:"era（数え始めの年）→ ある年から数え始めた年月のまとまりは…？",
   etymologyConclusion:"era（数え始めの年）→ ある年から数え始めた、ひとまとまりの年月＝時代",
   hook:"「〜の時代」とまとめて呼ぶときの語。数え始めの起点があるのが芯。",
   why:"【なぜ】ラテン語 aera はもともと「計算に使う駒の数」。そこから「数え始めの年」、さらに「そこから続くひとまとまりの年月＝時代」になりました。\n【つながり】A.D. のように「起点を決めて数える」という発想が、もとにあります。",
   relatedWords:[
     {synonym:true,word:"age",meaning:"時代；年齢",breakdown:"長い時代。era は特徴で区切られたひとまとまりの時代"},
     {synonym:true,word:"period",meaning:"期間，時期",breakdown:"区切られた長さ。era は性格のはっきりした時代を指す"},
     {synonym:true,word:"epoch",meaning:"新時代",breakdown:"新しい時代の始まり。era はその続く時代ぜんたいを指す"},
     {synonym:true,word:"century",meaning:"世紀",breakdown:"100年の区切り。era は長さではなく性格で区切る"}]},

  {id:1310,word:"session",partOfSpeech:"名詞",meaning:"会期；ひと続きの時間",
   meanings:["名|（議会などの）会期","名|（練習・授業の）ひと続きの時間"],
   pronunciation:"/ˈseʃn/",part:131,
   example:"The summer session of parliament ended last Friday.",
   exampleJa:"議会の夏の会期は、先週の金曜に終わった。",
   example2:"Each practice session lasts about ninety long minutes.",
   exampleJa2:"それぞれの練習の時間は、約90分の長さ続く。",
   etymologyProcess:"sess（座る）＋ ion（名詞）→ 人が座って事を行うひと区切りなら…？",
   etymologyConclusion:"sess（座る）＋ ion（名詞）→ 人が座って事を行う、ひと区切りの時間＝会期",
   relatedWords:[
     {word:"possess",meaning:"所有している",breakdown:"poss（できる）＋ sess（座る）→ 力の及ぶ場所にどっしり座っている"},
     {word:"resident",meaning:"住人",breakdown:"re（後ろへ）＋ sid（座る）→ その土地に腰を落ち着けている人"},
     {word:"president",meaning:"大統領，社長",breakdown:"pre（先に）＋ sid（座る）→ いちばん先の席に座る人"},
     {word:"reside",meaning:"住む",breakdown:"re（後ろへ）＋ sid（座る）→ その土地に腰を落ち着ける"}]},

  {id:1311,word:"pause",partOfSpeech:"名詞",meaning:"休止，ひと呼吸の間",
   meanings:["名|休止，ひと呼吸の間","自|一時止まる"],
   pronunciation:"/pɔːz/",part:132,
   example:"There was a long pause before her final answer.",
   exampleJa:"彼女の最終的な答えの前に、長い休止があった。",
   example2:"He paused for a moment and quietly looked around.",
   exampleJa2:"彼は少し言葉を切って、静かにあたりを見回した。",
   etymologyProcess:"paus（やめる）→ 続いていた動きを少しの間やめると…？",
   etymologyConclusion:"paus（やめる）→ 続いていた動きを、少しの間だけやめること＝休止",
   hook:"音楽や動画の「ポーズ（一時停止）」と同じ。短く止めるのが芯。",
   relatedWords:[
     {synonym:true,word:"break",meaning:"休憩",breakdown:"一時的に止めること。pause はもっと短いひと区切りの間"},
     {synonym:true,word:"stop",meaning:"止まる",breakdown:"完全に止めること。pause は少しの間だけ止めること"},
     {synonym:true,word:"rest",meaning:"休む",breakdown:"体を休めること。pause は動きや話を短く止めること"},
     {synonym:true,word:"silence",meaning:"沈黙",breakdown:"音がないこと。pause は話の途中の短い間を指す"}]},

  {id:1312,word:"annual",partOfSpeech:"形容詞",meaning:"年に1度の，毎年の",
   meanings:["形|年に1度の，毎年の"],
   pronunciation:"/ˈænjuəl/",part:132,
   example:"Our school holds an annual sports festival every autumn.",
   exampleJa:"私たちの学校は毎秋、年に1度の体育祭を開く。",
   example2:"The company's annual report comes out each March.",
   exampleJa2:"その会社の年に1度の報告書は、毎年3月に出る。",
   etymologyProcess:"ann（年）＋ al（形容詞）→ 1年に1度めぐってくるなら…？",
   etymologyConclusion:"ann（年）＋ al（形容詞）→ 1年に1度めぐってくる＝年に1度の",
   relatedWords:[
     {word:"anniversary",meaning:"記念日",breakdown:"ann（年）＋ vers（回る）→ 年がひとめぐりして戻ってくる日"},
     {word:"annually",meaning:"毎年",breakdown:"ann（年）＋ ly（副詞）→ 1年ごとに"},
     {synonym:true,word:"yearly",meaning:"毎年の",breakdown:"1年ごとの。annual は改まった場でよく使う言い方"},
     {synonym:true,word:"regular",meaning:"定期的な",breakdown:"決まった間をおくこと。annual は1年ごとであることを言う"}]},

  {id:1313,word:"eternal",partOfSpeech:"形容詞",meaning:"永遠の",
   meanings:["形|永遠の，終わりのない"],
   pronunciation:"/ɪˈtɜːrnl/",part:132,
   example:"Many people dream of eternal youth and good health.",
   exampleJa:"多くの人が、永遠の若さと健康を夢見る。",
   example2:"Their friendship felt eternal at that young age.",
   exampleJa2:"彼らの友情は、その若い年ごろには永遠に感じられた。",
   etymologyProcess:"etern（限りない年月）→ 終わりが来ず限りなく続くと…？",
   etymologyConclusion:"etern（限りない年月）→ 終わりが来ず、限りない年月続いていく＝永遠の",
   relatedWords:[
     {word:"eternity",meaning:"永遠",breakdown:"etern（限りない年月）＋ ity（名詞）→ 終わりのない時の長さ"},
     {synonym:true,word:"permanent",meaning:"永久的な",breakdown:"ずっと変わらないこと。eternal は終わりが来ないことを言う"},
     {synonym:true,word:"endless",meaning:"果てしない",breakdown:"終わりがないこと。eternal は時間の上で永遠であることを言う"},
     {synonym:true,word:"forever",meaning:"永久に",breakdown:"いつまでも。eternal はその状態を表す形容詞"}]},

  {id:1314,word:"initial",partOfSpeech:"形容詞",meaning:"最初の，出だしの",
   meanings:["形|最初の，出だしの","名|頭文字"],
   pronunciation:"/ɪˈnɪʃl/",part:132,
   example:"My initial reaction to the news was pure surprise.",
   exampleJa:"その知らせへの私の最初の反応は、純粋な驚きだった。",
   example2:"Please write your initial answer in this small box.",
   exampleJa2:"最初の答えを、この小さな枠に書いてください。",
   etymologyProcess:"in（中へ）＋ it（行く）→ 中へ足を踏み入れたいちばん初めなら…？",
   etymologyConclusion:"in（中へ）＋ it（行く）→ 中へ足を踏み入れた、いちばん初めの＝最初の",
   relatedWords:[
     {word:"initiate",meaning:"始める",breakdown:"in（中へ）＋ it（行く）＋ ate（動詞）→ 中へ足を踏み入れて始める"},
     {word:"exit",meaning:"出口",breakdown:"ex（外へ）＋ it（行く）→ 外へ出て行くところ"},
     {word:"transit",meaning:"通過，輸送",breakdown:"trans（越えて）＋ it（行く）→ 境を越えて行くこと"},
     {synonym:true,word:"first",meaning:"最初の",breakdown:"いちばん初めの。initial は「出だしの」という含みが強い"}]},

  {id:1315,word:"prior",partOfSpeech:"形容詞",meaning:"（～より）前の，事前の",
   meanings:["形|（to ～）（～より）前の，事前の"],
   pronunciation:"/ˈpraɪər/",part:132,
   example:"The meeting was held prior to the final exam.",
   exampleJa:"その会議は、期末試験より前に開かれた。",
   example2:"He had no prior experience in this kind of job.",
   exampleJa2:"彼はこの種の仕事では、以前の経験がまったくなかった。",
   etymologyProcess:"pri（前の）＋ or（より〜な）→ 順序や時間がそれより前にあると…？",
   etymologyConclusion:"pri（前の）＋ or（より〜な）→ 順序や時間が、それより前にある＝～より前の",
   relatedWords:[
     {word:"priority",meaning:"優先（順位）",breakdown:"pri（前の）＋ ity（名詞）→ ほかより前に置かれること"},
     {word:"prime",meaning:"最重要な",breakdown:"prim（第一の）→ すべての中で第一に置かれる"},
     {word:"previous",meaning:"前の",breakdown:"pre（先に）＋ vi（道）→ 同じ道をひと足先に通っていた"},
     {synonym:true,word:"earlier",meaning:"より早い",breakdown:"時間が前のこと。prior は順序が先であることも表す"}]},

  {id:1316,word:"subsequent",partOfSpeech:"形容詞",meaning:"続いて起こる，その後の",
   meanings:["形|続いて起こる，その後の"],
   pronunciation:"/ˈsʌbsɪkwənt/",part:132,
   example:"Subsequent events soon proved that he was right.",
   exampleJa:"続いて起こったできごとが、まもなく彼が正しいと証明した。",
   example2:"The first test failed, but subsequent tests all succeeded.",
   exampleJa2:"最初の試験は失敗したが、続いて行われた試験はすべて成功した。",
   etymologyProcess:"sub（下で）＋ sequ（ついて行く）→ すぐ後ろについて続いてくると…？",
   etymologyConclusion:"sub（下で）＋ sequ（ついて行く）→ すぐ後ろについて続いてくる＝続いて起こる",
   relatedWords:[
     {word:"sequence",meaning:"順序，連続",breakdown:"sequ（ついて行く）＋ ence（名詞）→ 次々についていく並び"},
     {word:"consequence",meaning:"結果",breakdown:"con（共に）＋ sequ（ついて行く）＋ ence（名詞）→ 後についてくるもの"},
     {word:"pursue",meaning:"追い求める",breakdown:"pur（前へ）＋ sequ（ついて行く）→ 前へ前へと追いかけていく"},
     {synonym:true,word:"following",meaning:"次の",breakdown:"次に来ること。subsequent はその後に続いて起こることを言う"}]},

  {id:1317,word:"meanwhile",partOfSpeech:"副詞",meaning:"その間に",
   meanings:["副|その間に，一方では"],
   pronunciation:"/ˈmiːnwaɪl/",part:132,
   example:"You set the table; meanwhile I will cook dinner.",
   exampleJa:"テーブルの用意をして。その間に、私が夕食を作るから。",
   example2:"Meanwhile, the heavy rain had stopped outside the window.",
   exampleJa2:"その間に、窓の外では激しい雨がやんでいた。",
   etymologyProcess:"while（ひと続きの時間）→ ちょうどそのひと続きの時間のあいだなら…？",
   etymologyConclusion:"while（ひと続きの時間）→ ちょうどそのひと続きの時間のあいだに＝その間に",
   hook:"mean（中ほどの）＋ while（時間）。「そのあいだに」と覚える。",
   relatedWords:[
     {word:"while",meaning:"～の間；しばらく",breakdown:"while（ひと続きの時間）→ ある長さの時間のあいだ"},
     {word:"worthwhile",meaning:"やりがいのある",breakdown:"worth（値打ち）＋ while（時間）→ 時間をかける値打ちがある"},
     {synonym:true,word:"meantime",meaning:"その間",breakdown:"in the meantime の形で使う。meanwhile とほぼ同じ意味"},
     {synonym:true,word:"during",meaning:"～の間",breakdown:"前置詞。meanwhile は単独で「その間に」と言える副詞"}]},

  {id:1318,word:"routine",partOfSpeech:"名詞",meaning:"決まりきった仕事，日課",
   meanings:["名|決まりきった仕事，日課","形|型どおりの"],
   pronunciation:"/ruːˈtiːn/",part:132,
   example:"My morning routine starts with a cold quick shower.",
   exampleJa:"私の朝の日課は、冷たく手早いシャワーから始まる。",
   example2:"A daily routine can make life feel very safe.",
   exampleJa2:"毎日の決まった日課があると、生活はとても安心できるものになる。",
   etymologyProcess:"rupt（破る）＋ ine（もの）→ 通り慣れて踏み固められた道のようなら…？",
   etymologyConclusion:"rupt（破る）＋ ine（もの）→ 踏み破られた道のように決まりきった手順＝決まりきった仕事",
   why:"【なぜ】route（道）から出た語で、もとは「踏み破られてできた道」。毎日同じ道を通るように、いつも同じ手順でする仕事を routine と呼ぶようになりました。\n【つながり】route（道）、interrupt（間に割って入る）も同じ rupt（破る）の家族です。",
   relatedWords:[
     {word:"route",meaning:"道すじ",breakdown:"rupt（破る）→ 踏み破られてできた通り道"},
     {word:"interrupt",meaning:"さえぎる，中断する",breakdown:"inter（間の）＋ rupt（破る）→ 間に割って入って断ち切る"},
     {word:"erupt",meaning:"噴火する",breakdown:"e（外へ）＋ rupt（破る）→ 外へ破って噴き出す"},
     {synonym:true,word:"habit",meaning:"習慣",breakdown:"身についたふるまい。routine は決まった手順の流れを指す"}]},

  {id:1319,word:"souvenir",partOfSpeech:"名詞",meaning:"土産，記念の品",
   meanings:["名|土産，記念の品"],
   pronunciation:"/ˌsuːvəˈnɪr/",part:132,
   example:"She bought a small souvenir at the airport shop.",
   exampleJa:"彼女は空港の店で、小さな土産を買った。",
   example2:"This old shell is a souvenir from that summer.",
   exampleJa2:"この古い貝殻は、あの夏からの記念の品だ。",
   etymologyProcess:"sub（下で）＋ ven（来る）→ 心の底から思い出がよみがえる品なら…？",
   etymologyConclusion:"sub（下で）＋ ven（来る）→ 心の底から思い出がよみがえってくる品＝土産",
   why:"【なぜ】フランス語の souvenir は「思い出す」という動詞。見るたびに旅の記憶がよみがえる品ということで、「記念の品・土産」になりました。\n【つながり】convenient（都合よく来る）、event（外へ出てくる）も同じ ven（来る）の家族です。",
   relatedWords:[
     {word:"convenient",meaning:"便利な",breakdown:"con（共に）＋ ven（来る）→ 都合よく共に来てくれる"},
     {word:"event",meaning:"できごと，行事",breakdown:"e（外へ）＋ vent（来る）→ 外に現れ出てきたできごと"},
     {word:"prevent",meaning:"防ぐ",breakdown:"pre（先に）＋ vent（来る）→ 先回りして来させないようにする"},
     {synonym:true,word:"memento",meaning:"記念の品",breakdown:"思い出のよすが。souvenir は旅先で買う土産にもよく使う"}]},

  {id:1320,word:"brick",partOfSpeech:"名詞",meaning:"れんが",
   meanings:["名|れんが"],
   pronunciation:"/brɪk/",part:132,
   example:"That old house is made of dark red brick.",
   exampleJa:"あの古い家は、濃い赤のれんがでできている。",
   example2:"Workers carried heavy bricks up the narrow back stairs.",
   exampleJa2:"作業員たちは、重いれんがを狭い裏階段へ運び上げた。",
   etymologyProcess:"brick（焼き固めた塊）→ 粘土を焼いて固めた積み上げ用の塊は…？",
   etymologyConclusion:"brick（焼き固めた塊）→ 粘土を焼き固めた、積み上げるための塊＝れんが",
   hook:"語源ははっきりしないが、break（割る）の仲間とも言われる。",
   relatedWords:[
     {synonym:true,word:"stone",meaning:"石",breakdown:"自然の石。brick は粘土を焼いて人が作った塊"},
     {synonym:true,word:"block",meaning:"かたまり",breakdown:"四角いかたまり。brick は壁を積むための焼いた塊"},
     {synonym:true,word:"tile",meaning:"タイル，かわら",breakdown:"薄く平らな焼き物。brick は厚みのある積む塊"},
     {synonym:true,word:"clay",meaning:"粘土",breakdown:"brick の原料。brick はそれを焼き固めた四角い塊を指す"}]},

  {id:1321,word:"pole",partOfSpeech:"名詞",meaning:"棒，さお；（地球の）極",
   meanings:["名|棒，さお","名|（地球の）極"],
   pronunciation:"/poʊl/",part:133,
   example:"A long wooden pole held up the old tent.",
   exampleJa:"長い木の棒が、その古いテントを支えていた。",
   example2:"Penguins live near the South Pole all year round.",
   exampleJa2:"ペンギンは一年中、南極の近くに住んでいる。",
   etymologyProcess:"pal（杭）→ 地面に打ち込む長い杭のようなものは…？",
   etymologyConclusion:"pal（杭）→ 地面に打ち込む、長い杭のようなもの＝棒",
   hook:"「棒」と「極」は別語源の同音語。North Pole の pole は「軸の先」。",
   relatedWords:[
     {synonym:true,word:"stick",meaning:"棒，枝",breakdown:"細い棒。pole はもっと長くて太い棒を指す"},
     {synonym:true,word:"bar",meaning:"棒，かんぬき",breakdown:"横に渡す棒。pole は縦に立てる長い棒を指す"},
     {synonym:true,word:"rod",meaning:"さお，細い棒",breakdown:"細長い棒。pole は旗やテントを支える太い棒"},
     {synonym:true,word:"post",meaning:"柱，支柱",breakdown:"地面に立てる柱。pole は丸くて長い棒を指す"}]},

  {id:1322,word:"mischief",partOfSpeech:"名詞",meaning:"いたずら，やんちゃ",
   meanings:["名|いたずら，やんちゃ","名|害，損害"],
   pronunciation:"/ˈmɪstʃɪf/",part:133,
   example:"The boys got into mischief during the long lunch break.",
   exampleJa:"男の子たちは長い昼休みの間、いたずらをした。",
   example2:"Her bright eyes were full of mischief that morning.",
   exampleJa2:"その朝、彼女の明るい目はいたずらに満ちていた。",
   etymologyProcess:"mis（誤って）＋ chief（頭）→ 事の結末を悪いほうへ向けてしまうと…？",
   etymologyConclusion:"mis（誤って）＋ chief（頭）→ 事の結末を悪いほうへ向けて起こす悪さ＝いたずら",
   why:"【なぜ】古フランス語 meschief は mes（悪く）＋ chief（頭・結末）で、「悪い結末に至ること」＝災難でした。英語では軽い害のほうへ意味が移り、「いたずら」になりました。\n【つながり】chief（頭・長）、achieve（結末まで行き着く）も同じ chief の家族です。",
   relatedWords:[
     {word:"chief",meaning:"長；主要な",breakdown:"chief（頭）→ 集団のいちばん上に立つ者"},
     {word:"achieve",meaning:"達成する",breakdown:"ad（〜へ）＋ chief（頭）→ 事の結末まで行き着く"},
     {word:"mischievous",meaning:"いたずら好きな",breakdown:"mis（誤って）＋ chief（頭）＋ ous（形容詞）→ 悪さをしたがる"},
     {synonym:true,word:"trick",meaning:"いたずら",breakdown:"だます仕掛け。mischief はやんちゃな悪さぜんたいを指す"}]},

  {id:1323,word:"superstition",partOfSpeech:"名詞",meaning:"迷信",
   meanings:["名|迷信"],
   pronunciation:"/ˌsuːpərˈstɪʃn/",part:133,
   example:"Many old superstitions still survive in this small village.",
   exampleJa:"多くの古い迷信が、この小さな村には今も生き残っている。",
   example2:"It is just an old superstition about black cats.",
   exampleJa2:"それは、黒猫についての古い迷信にすぎない。",
   etymologyProcess:"super（上から）＋ sta（立つ）→ 理屈の上に居座り続ける信じ込みなら…？",
   etymologyConclusion:"super（上から）＋ sta（立つ）→ 理屈の上に居座り続ける、根拠のない信じ込み＝迷信",
   why:"【なぜ】ラテン語 superstitio は super（上に）＋ stare（立つ）ですが、そこから「迷信」へどう移ったかは諸説あり、はっきりしていません。「理屈を越えて居座り続ける思い込み」と結びつけると覚えやすくなります。\n【つながり】superior（上に立つ）、substance（下で支える中身）も同じ sta の家族です。",
   relatedWords:[
     {word:"stand",meaning:"立つ",breakdown:"sta（立つ）→ 足を地につけてまっすぐ立つ"},
     {word:"superior",meaning:"より優れている",breakdown:"super（上から）＋ ior（より〜な）→ 他より一段上に立っている"},
     {word:"substance",meaning:"物質；中身",breakdown:"sub（下で）＋ sta（立つ）→ 見た目の下で全体を支える中身"},
     {synonym:true,word:"myth",meaning:"神話；作り話",breakdown:"語り伝えられた話。superstition は根拠なく信じられた考え"}]},

  {id:1324,word:"storage",partOfSpeech:"名詞",meaning:"貯蔵，保管",
   meanings:["名|貯蔵，保管","名|保管場所"],
   pronunciation:"/ˈstɔːrɪdʒ/",part:133,
   example:"We need more storage for all the winter vegetables.",
   exampleJa:"冬の野菜すべてのために、もっと貯蔵の場所が必要だ。",
   example2:"All the school data is kept in cloud storage.",
   exampleJa2:"学校のデータはすべて、クラウドの保管場所に置かれている。",
   etymologyProcess:"staur（立てる）＋ age（名詞）→ 後のために積み立ててしまっておくと…？",
   etymologyConclusion:"staur（立てる）＋ age（名詞）→ 後のために積み立ててしまっておくこと＝貯蔵",
   relatedWords:[
     {word:"store",meaning:"蓄える；店",breakdown:"staur（立てる）→ 蓄えを積み立てておくところ"},
     {word:"restore",meaning:"修復する",breakdown:"re（元へ）＋ staur（立てる）→ 崩れたものを元どおりに立て直す"},
     {word:"restaurant",meaning:"レストラン",breakdown:"re（元へ）＋ staur（立てる）→ 食べて元気を立て直すための店"},
     {synonym:true,word:"warehouse",meaning:"倉庫",breakdown:"物をしまう建物。storage はしまっておくこと自体も指す"}]},

  {id:1325,word:"shelter",partOfSpeech:"名詞",meaning:"避難所，雨風をしのぐ場所",
   meanings:["名|避難所，雨風をしのぐ場所","他|保護する"],
   pronunciation:"/ˈʃeltər/",part:133,
   example:"They found shelter under a large old oak tree.",
   exampleJa:"彼らは大きな古いカシの木の下に、避難所を見つけた。",
   example2:"The city built a shelter for homeless older people.",
   exampleJa2:"市は、家のない高齢の人々のための避難所を建てた。",
   etymologyProcess:"shelter（おおい）→ 雨や危険から身をおおって守るところは…？",
   etymologyConclusion:"shelter（おおい）→ 雨や危険から身をおおって守ってくれる場所＝避難所",
   hook:"語源ははっきりしない。「身をおおって守る場所」が芯にある。",
   relatedWords:[
     {synonym:true,word:"refuge",meaning:"避難，逃げ場",breakdown:"逃げ込む先。shelter は雨風や危険をしのぐ場所を指す"},
     {synonym:true,word:"protection",meaning:"保護",breakdown:"守ること。shelter は守ってくれる場所そのものを指す"},
     {synonym:true,word:"cover",meaning:"覆い，隠れ場所",breakdown:"覆うもの。shelter は人が入って身を守れる場所"},
     {synonym:true,word:"roof",meaning:"屋根",breakdown:"雨を防ぐもの。shelter は屋根も壁も含めた避難の場所"}]},

  {id:1326,word:"garment",partOfSpeech:"名詞",meaning:"衣類（の一点）",
   meanings:["名|衣類（の一点），衣服"],
   pronunciation:"/ˈɡɑːrmənt/",part:133,
   example:"Every garment in this small shop is completely handmade.",
   exampleJa:"この小さな店のすべての衣類は、完全に手作りだ。",
   example2:"She folded each garment and put it away carefully.",
   exampleJa2:"彼女はそれぞれの衣類をたたんで、注意深くしまった。",
   etymologyProcess:"garn（備える）＋ ment（名詞）→ 身に備えつけて着るものなら…？",
   etymologyConclusion:"garn（備える）＋ ment（名詞）→ 身に備えつけて着るもの＝衣類",
   relatedWords:[
     {word:"garnish",meaning:"飾りをそえる",breakdown:"garn（備える）＋ ish（〜にする）→ 料理に飾りを備えつける"},
     {synonym:true,word:"outfit",meaning:"ひとそろいの服",breakdown:"上下そろいの服装。garment は一点一点の衣類を指す"},
     {synonym:true,word:"costume",meaning:"衣装",breakdown:"劇や行事で着る服。garment は衣類の一点一点を指す"},
     {synonym:true,word:"clothing",meaning:"衣服",breakdown:"着る物ぜんたい。garment は一点一点の衣類を指す"}]},

  {id:1327,word:"canal",partOfSpeech:"名詞",meaning:"運河",
   meanings:["名|運河，人工の水路"],
   pronunciation:"/kəˈnæl/",part:133,
   example:"Boats move slowly along the narrow old stone canal.",
   exampleJa:"船が、狭い古い石の運河に沿ってゆっくり進む。",
   example2:"The Suez Canal connects two completely different seas.",
   exampleJa2:"スエズ運河は、まったく異なる2つの海をつないでいる。",
   etymologyProcess:"can（管）＋ al（名詞）→ 水を流すために人が掘った管のような道は…？",
   etymologyConclusion:"can（管）＋ al（名詞）→ 水を流すために人が掘った、管のような水路＝運河",
   relatedWords:[
     {word:"channel",meaning:"海峡；チャンネル",breakdown:"can（管）→ 水や電波が通っていく道"},
     {word:"cane",meaning:"つえ；茎",breakdown:"can（管）→ 中が空になっている細い茎"},
     {synonym:true,word:"waterway",meaning:"水路",breakdown:"水の通り道。canal は人が掘って作った水路を指す"},
     {synonym:true,word:"river",meaning:"川",breakdown:"自然にできた流れ。canal は人の手で掘られた水路"}]},

  {id:1328,word:"cabinet",partOfSpeech:"名詞",meaning:"戸棚；内閣",
   meanings:["名|戸棚，収納棚","名|（政府の）内閣"],
   pronunciation:"/ˈkæbɪnət/",part:133,
   example:"Please put these cups in the kitchen cabinet.",
   exampleJa:"これらのカップを、台所の戸棚に入れてください。",
   example2:"The prime minister chose a completely new cabinet yesterday.",
   exampleJa2:"首相は昨日、まったく新しい内閣を選んだ。",
   etymologyProcess:"cabin（小部屋）＋ et（小さい）→ 物をしまう小さな部屋のような箱は…？",
   etymologyConclusion:"cabin（小部屋）＋ et（小さい）→ 物をしまう、小さな部屋のような箱＝戸棚",
   why:"【なぜ】cabinet はもともと「小部屋」だったと考えられています。王が少数の側近だけを集めて相談した小部屋を cabinet と呼び、そこに集まる人たち＝「内閣」の意味が生まれました。\n【つながり】cabin（小屋・客室）も同じ家族。今も「戸棚」と「内閣」の両方の意味で使われます。",
   relatedWords:[
     {word:"cabin",meaning:"小屋；客室",breakdown:"cabin（小部屋）→ 小さく仕切られた部屋"},
     {synonym:true,word:"cupboard",meaning:"食器棚",breakdown:"食器をしまう棚。cabinet はもっと広く物入れを指す"},
     {synonym:true,word:"shelf",meaning:"棚",breakdown:"物を置く板。cabinet は扉のついた戸棚を指す"},
     {synonym:true,word:"government",meaning:"政府",breakdown:"国を治める組織。cabinet はその中心の大臣たちの集まり"}]},

  {id:1329,word:"incident",partOfSpeech:"名詞",meaning:"出来事，事件",
   meanings:["名|（思いがけない）出来事，事件"],
   pronunciation:"/ˈɪnsɪdənt/",part:133,
   example:"A strange incident happened near the school gate today.",
   exampleJa:"奇妙な出来事が、今日校門の近くで起こった。",
   example2:"Nobody talked about the incident for many long years.",
   exampleJa2:"誰も何年もの長い間、その出来事について話さなかった。",
   etymologyProcess:"in（上に）＋ cid（落ちる）→ 思いがけず身の上に落ちてくると…？",
   etymologyConclusion:"in（上に）＋ cid（落ちる）→ 思いがけず身の上に落ちてきたこと＝出来事",
   relatedWords:[
     {word:"accident",meaning:"事故",breakdown:"ac（〜へ）＋ cid（落ちる）→ 思いがけず身に落ちかかってくること"},
     {word:"coincide",meaning:"同時に起こる",breakdown:"co（共に）＋ cid（落ちる）→ 同じ時に重なって落ちてくる"},
     {word:"occasion",meaning:"機会，場合",breakdown:"oc（〜に向かって）＋ cas（落ちる）→ ちょうどそこへ落ちてきた折"},
     {synonym:true,word:"event",meaning:"できごと",breakdown:"起こった事ぜんたい。incident は思いがけない小さな出来事"}]},

  {id:1330,word:"circumstance",partOfSpeech:"名詞",meaning:"状況，事情",
   meanings:["名|（複数で）状況，事情"],
   pronunciation:"/ˈsɜːrkəmstæns/",part:133,
   example:"In these circumstances we cannot start the game today.",
   exampleJa:"この状況では、私たちは今日試合を始められない。",
   example2:"He explained the circumstances of the small traffic accident.",
   exampleJa2:"彼はその小さな交通事故の状況を説明した。",
   etymologyProcess:"circ（輪を描く）＋ sta（立つ）→ まわりを取り巻いて立っているものなら…？",
   etymologyConclusion:"circ（輪を描く）＋ sta（立つ）→ まわりを取り巻いて立っているものごと＝状況",
   relatedWords:[
     {word:"circle",meaning:"円，輪",breakdown:"circ（輪を描く）→ ぐるりと一周して閉じた線"},
     {word:"circulate",meaning:"循環する",breakdown:"circ（輪を描く）＋ ate（動詞）→ ぐるぐると回り続ける"},
     {word:"instance",meaning:"例，場合",breakdown:"in（上に）＋ sta（立つ）→ 目の前に立って示される一つの例"},
     {word:"stable",meaning:"安定した",breakdown:"sta（立つ）＋ able（できる）→ ぐらつかずに立っていられる"}]},

  {id:1331,word:"fetch",partOfSpeech:"他動詞",meaning:"取って来る",
   meanings:["他|（行って）取って来る，連れて来る"],
   pronunciation:"/fetʃ/",part:134,
   example:"Please fetch a glass of cold water for me.",
   exampleJa:"私に冷たい水を一杯、取って来てください。",
   example2:"The clever dog fetches the ball every single time.",
   exampleJa2:"その賢い犬は、毎回ボールを取って来る。",
   etymologyProcess:"fetch（取りに行って戻る）→ そこまで行って取り、持って戻ると…？",
   etymologyConclusion:"fetch（取りに行って戻る）→ そこまで行って取り、持って戻ってくる＝取って来る",
   hook:"bring は「持ってくる」だけ。fetch は「行って→取って→戻る」の往復。",
   relatedWords:[
     {synonym:true,word:"bring",meaning:"持ってくる",breakdown:"こちらへ持ってくること。fetch は取りに行って戻る往復を含む"},
     {synonym:true,word:"get",meaning:"取ってくる，手に入れる",breakdown:"手に入れること。fetch は取りに行って持ち帰ることを言う"},
     {synonym:true,word:"carry",meaning:"運ぶ",breakdown:"持ち運ぶこと。fetch は取りに行って戻ってくることを指す"},
     {synonym:true,word:"retrieve",meaning:"回収する",breakdown:"取り戻すこと。fetch は犬がボールを取って来る動きにも使う"}]},

  {id:1332,word:"distribute",partOfSpeech:"他動詞",meaning:"分配する，配る",
   meanings:["他|分配する，配る"],
   pronunciation:"/dɪˈstrɪbjuːt/",part:134,
   example:"Teachers distribute the new textbooks every April here.",
   exampleJa:"ここでは、先生たちが毎年4月に新しい教科書を配る。",
   example2:"Volunteers distributed warm food to the flooded village.",
   exampleJa2:"ボランティアが、水害にあった村に温かい食べ物を分配した。",
   etymologyProcess:"dis（バラバラに）＋ tribut（割り当てる）→ ばらばらに分けて割り当てると…？",
   etymologyConclusion:"dis（バラバラに）＋ tribut（割り当てる）→ ばらばらに分けて、それぞれへ割り当てる＝分配する",
   relatedWords:[
     {word:"contribute",meaning:"貢献する，寄付する",breakdown:"con（共に）＋ tribut（割り当てる）→ 自分の分を共に出し合う"},
     {word:"tribute",meaning:"貢ぎ物；賛辞",breakdown:"tribut（割り当てる）→ 割り当てられて差し出すもの"},
     {word:"attribute",meaning:"～のせいにする；特質",breakdown:"ad（〜へ）＋ tribut（割り当てる）→ 原因をそちらへ割り当てる"},
     {synonym:true,word:"hand out",meaning:"配る",breakdown:"手渡して配ること。distribute は割り当てて広く配ることを言う"}]},

  {id:1333,word:"purchase",partOfSpeech:"他動詞",meaning:"購入する",
   meanings:["他|購入する","名|購入（品）"],
   pronunciation:"/ˈpɜːrtʃəs/",part:134,
   example:"They purchase new computers every three or four years.",
   exampleJa:"彼らは3、4年ごとに新しいコンピューターを購入する。",
   example2:"She purchased the concert tickets online last night.",
   exampleJa2:"彼女は昨夜、オンラインでそのコンサートの切符を購入した。",
   etymologyProcess:"pur（前へ）＋ chas（つかむ）→ 前へ出て追い求め、手に入れると…？",
   etymologyConclusion:"pur（前へ）＋ chas（つかむ）→ 前へ出て追い求め、ついに手に入れる＝購入する",
   why:"【なぜ】古フランス語 porchacier は「追い求めて手に入れる」。chase（追いかける）と同じ家族で、狩りのように追って得る意味でした。そこから「お金を払って手に入れる」＝購入する、に落ち着きました。\n【つながり】chase（追いかける）、catch（つかまえる）も同じ「つかむ」の家族です。",
   relatedWords:[
     {word:"chase",meaning:"追いかける",breakdown:"chas（つかむ）→ つかまえようとして後を走って追う"},
     {word:"catch",meaning:"捕まえる",breakdown:"chas（つかむ）→ 追いついて手でつかまえる"},
     {word:"capture",meaning:"捕らえる",breakdown:"cap（つかむ）＋ ure（名詞）→ つかまえて自分のものにする"},
     {synonym:true,word:"buy",meaning:"買う",breakdown:"お金を出して手に入れること。purchase は硬い言い方"}]},

  {id:1334,word:"statue",partOfSpeech:"名詞",meaning:"像，彫像",
   meanings:["名|像，彫像"],
   pronunciation:"/ˈstætʃuː/",part:134,
   example:"A tall statue stands in the middle of the park.",
   exampleJa:"高い像が、その公園の真ん中に立っている。",
   example2:"They built the statue over a hundred years ago.",
   exampleJa2:"彼らは100年以上前に、その像を建てた。",
   etymologyProcess:"sta（立つ）→ 人の姿を立てたまま固めて残すと…？",
   etymologyConclusion:"sta（立つ）→ 人の姿を立てたまま固めて残したもの＝像",
   relatedWords:[
     {word:"stand",meaning:"立つ",breakdown:"sta（立つ）→ 足を地につけてまっすぐ立つ"},
     {word:"substance",meaning:"物質；中身",breakdown:"sub（下で）＋ sta（立つ）→ 見た目の下で全体を支える中身"},
     {word:"constant",meaning:"絶え間ない",breakdown:"con（共に）＋ sta（立つ）＋ ant（形容詞）→ ずっと同じ所に立ち続ける"},
     {word:"circumstance",meaning:"状況",breakdown:"circ（輪を描く）＋ sta（立つ）→ まわりを取り巻いて立っていること"}]},

  {id:1335,word:"sculpture",partOfSpeech:"名詞",meaning:"彫刻",
   meanings:["名|彫刻（作品）"],
   pronunciation:"/ˈskʌlptʃər/",part:134,
   example:"This sculpture took the artist three whole years.",
   exampleJa:"この彫刻は、その芸術家に3年まるまるかかった。",
   example2:"The museum displays modern sculpture from many different countries.",
   exampleJa2:"その博物館は、さまざまな国の現代彫刻を展示している。",
   etymologyProcess:"sculpt（彫る）＋ ure（名詞）→ 石や木を彫って形を出した作品は…？",
   etymologyConclusion:"sculpt（彫る）＋ ure（名詞）→ 石や木を彫って形を出した作品＝彫刻",
   relatedWords:[
     {word:"sculptor",meaning:"彫刻家",breakdown:"sculpt（彫る）＋ or（人）→ 石や木を彫って形を作る人"},
     {synonym:true,word:"statue",meaning:"像",breakdown:"人の姿の像。sculpture は彫って作った作品ぜんたいを指す"},
     {synonym:true,word:"carve",meaning:"彫る",breakdown:"刃物で削ること。sculpture はそうして作られた作品を指す"},
     {word:"sculpt",meaning:"彫る，彫刻する",breakdown:"sculpt（彫る）→ 石や木を削って形を出していく"}]},

  {id:1336,word:"myth",partOfSpeech:"名詞",meaning:"神話；作り話",
   meanings:["名|神話","名|作り話，根拠のない俗説"],
   pronunciation:"/mɪθ/",part:134,
   example:"Greek myth explains how the four seasons first began.",
   exampleJa:"ギリシャ神話は、四季がどのように始まったかを説明する。",
   example2:"It is a myth that carrots improve your night vision.",
   exampleJa2:"ニンジンが夜の視力をよくするというのは、作り話だ。",
   etymologyProcess:"myth（語り伝え）→ 神々や英雄について語り伝えられた話は…？",
   etymologyConclusion:"myth（語り伝え）→ 神々や英雄について語り伝えられてきた話＝神話",
   relatedWords:[
     {word:"mythology",meaning:"神話（学）",breakdown:"myth（語り伝え）＋ log（言葉）→ 神話を言葉で語り集めたもの"},
     {synonym:true,word:"legend",meaning:"伝説",breakdown:"人の世の言い伝え。myth は神々の物語を指す"},
     {synonym:true,word:"tale",meaning:"物語",breakdown:"語り継がれた話。myth は神々や世界の始まりの物語を指す"},
     {synonym:true,word:"belief",meaning:"信じられていること",breakdown:"信じている考え。myth は根拠のない俗説も指す"}]},

  {id:1337,word:"craft",partOfSpeech:"名詞",meaning:"工芸；（手の）技能",
   meanings:["名|工芸，手仕事","名|（熟練した）技能"],
   pronunciation:"/kræft/",part:134,
   example:"Traditional craft is still taught in this small village.",
   exampleJa:"伝統的な工芸が、この小さな村では今も教えられている。",
   example2:"Writing well is a craft that takes many years.",
   exampleJa2:"うまく書くことは、何年もかかる技能だ。",
   etymologyProcess:"craft（手の技）→ 手を動かして作り上げる技とその作品は…？",
   etymologyConclusion:"craft（手の技）→ 手を動かして作り上げる技と、その作品＝工芸",
   relatedWords:[
     {word:"aircraft",meaning:"航空機",breakdown:"air（空気）＋ craft（手の技）→ 空を行くために作られたもの"},
     {word:"crafty",meaning:"ずる賢い",breakdown:"craft（手の技）＋ y（形容詞）→ 技が回りすぎてずる賢い"},
     {synonym:true,word:"skill",meaning:"技能",breakdown:"身につけた腕前。craft は手仕事の技とその作品を指す"},
     {synonym:true,word:"handicraft",meaning:"手工芸",breakdown:"手で作る工芸。craft はその技ぜんたいを指す"}]},

  {id:1338,word:"journal",partOfSpeech:"名詞",meaning:"（専門の）雑誌；日誌",
   meanings:["名|（専門・学術の）雑誌","名|日誌，日記"],
   pronunciation:"/ˈdʒɜːrnl/",part:134,
   example:"She published her research in a well-known science journal.",
   exampleJa:"彼女は自分の研究を、よく知られた科学の雑誌に発表した。",
   example2:"He keeps a journal of his daily running training.",
   exampleJa2:"彼は毎日のランニング練習の日誌をつけている。",
   etymologyProcess:"journ（日）＋ al（名詞）→ 日ごとに書きためて定期的に出すものは…？",
   etymologyConclusion:"journ（日）＋ al（名詞）→ 日ごとに書きため、定期的に出す刊行物＝専門の雑誌",
   why:"【なぜ】ラテン語 diurnalis は「日ごとの」。日ごとに書きつける帳面が journal（日誌・日記）になり、そこから定期的に出る刊行物＝学術雑誌も journal と呼ばれるようになりました。\n【つながり】journey（もとは1日で行ける道のり）、diary（日ごとの記録）も同じ「日」の家族です。",
   relatedWords:[
     {word:"journey",meaning:"旅",breakdown:"journ（日）＋ y（名詞）→ もとは1日で行ける道のり"},
     {word:"journalist",meaning:"記者",breakdown:"journ（日）＋ ist（人）→ 日ごとの出来事を書く人"},
     {synonym:true,word:"magazine",meaning:"雑誌",breakdown:"一般向けの雑誌。journal は専門や学術の雑誌を指す"},
     {synonym:true,word:"diary",meaning:"日記",breakdown:"日々の記録。journal は日誌にも学術雑誌にも使う"}]},

  {id:1339,word:"encyclopedia",partOfSpeech:"名詞",meaning:"百科事典",
   meanings:["名|百科事典"],
   pronunciation:"/ɪnˌsaɪkləˈpiːdiə/",part:134,
   example:"He looked up the word in an old encyclopedia.",
   exampleJa:"彼はその語を、古い百科事典で調べた。",
   example2:"The online encyclopedia grows larger every single day.",
   exampleJa2:"そのオンラインの百科事典は、毎日大きくなっていく。",
   etymologyProcess:"cycle（回す）＋ ped（子を教える）→ 学ぶことをひと回りぜんぶ収めると…？",
   etymologyConclusion:"cycle（回す）＋ ped（子を教える）→ 学ぶべきことをひと回りぜんぶ収めた本＝百科事典",
   why:"【なぜ】ギリシャ語の enkyklios paideia は「輪をなす教育」＝一般教養のこと。学ぶべきことがひと回りぜんぶそろっている、という意味でした。その一続きを一冊にまとめた本が encyclopedia です。\n【つながり】cycle（ひと回り）、pediatrician（子どもの医者）も同じ家族です。",
   relatedWords:[
     {word:"cycle",meaning:"周期；自転車",breakdown:"cycle（回す）→ ぐるりと一回りして元へ戻ること"},
     {word:"recycle",meaning:"再利用する",breakdown:"re（再び）＋ cycle（回す）→ もう一度ぐるりと回して使う"},
     {synonym:true,word:"dictionary",meaning:"辞書",breakdown:"語の意味を調べる本。encyclopedia は物事の説明を集めた本"},
     {word:"pediatrician",meaning:"小児科医",breakdown:"ped（子を教える）→ 子どもを診る医者。ped は「子ども」の家族"}]},

  {id:1340,word:"heaven",partOfSpeech:"名詞",meaning:"天国",
   meanings:["名|天国","名|（複数で）空，天"],
   pronunciation:"/ˈhevn/",part:134,
   example:"Many people believe in heaven after this earthly life.",
   exampleJa:"多くの人が、この地上の生の後の天国を信じている。",
   example2:"The quiet green garden felt like heaven that afternoon.",
   exampleJa2:"その静かな緑の庭は、その午後、天国のように感じられた。",
   etymologyProcess:"heaven（空）→ 空の上にあると信じられた神々の場所は…？",
   etymologyConclusion:"heaven（空）→ 空の上にあると信じられた、神々のいる場所＝天国",
   hook:"もとの意味は「空」。空の上にある神の国、というのが芯。",
   relatedWords:[
     {synonym:true,word:"sky",meaning:"空",breakdown:"heaven のもとの意味がこれ。heaven は空の上の神の国を指す"},
     {synonym:true,word:"paradise",meaning:"楽園",breakdown:"美しい理想の地。heaven は死後に行くと信じられた場所"},
     {word:"heavenly",meaning:"天の；すばらしい",breakdown:"heaven（空）＋ ly（〜のような）→ 天のように美しい"},
     {synonym:true,word:"bliss",meaning:"至福",breakdown:"このうえない幸せ。heaven はそれを味わえる場所を指す"}]},

  {id:1341,word:"funeral",partOfSpeech:"名詞",meaning:"葬式",
   meanings:["名|葬式，葬儀"],
   pronunciation:"/ˈfjuːnərəl/",part:135,
   example:"Many old friends came to the quiet small funeral.",
   exampleJa:"多くの旧友が、その静かな小さな葬式に来た。",
   example2:"The funeral was held at a small country church.",
   exampleJa2:"その葬式は、小さな田舎の教会で行われた。",
   etymologyProcess:"funer（葬送）＋ al（名詞）→ 亡くなった人を送り出す儀式なら…？",
   etymologyConclusion:"funer（葬送）＋ al（名詞）→ 亡くなった人を送り出すための儀式＝葬式",
   relatedWords:[
     {word:"funerary",meaning:"葬儀の",breakdown:"funer（葬送）＋ ary（形容詞）→ 葬式に関わっている"},
     {synonym:true,word:"burial",meaning:"埋葬",breakdown:"土に埋めること。funeral はその前後の儀式ぜんたいを指す"},
     {synonym:true,word:"grave",meaning:"墓",breakdown:"遺体を納める場所。funeral は送り出す儀式のほうを指す"},
     {synonym:true,word:"ceremony",meaning:"儀式",breakdown:"改まった式。funeral は亡くなった人を送る式を指す"}]},

  {id:1342,word:"soul",partOfSpeech:"名詞",meaning:"魂",
   meanings:["名|魂，霊魂","名|（音楽の）ソウル；心のこもった感じ"],
   pronunciation:"/soʊl/",part:135,
   example:"He believes the soul lives on after a person dies.",
   exampleJa:"彼は、人が死んだ後も魂は生き続けると信じている。",
   example2:"Her singing has real soul and very deep feeling.",
   exampleJa2:"彼女の歌には、本当の魂と、とても深い感情がある。",
   etymologyProcess:"soul（人の芯にあるもの）→ 体の中に宿って人を生かしているものは…？",
   etymologyConclusion:"soul（命の息）→ 体の中に宿って人を生かしていると考えられたもの＝魂",
   hook:"語源ははっきりしない。音楽の「ソウル」も同じ語で、心の奥が芯。",
   relatedWords:[
     {synonym:true,word:"spirit",meaning:"精神，霊",breakdown:"心や霊。soul は人ひとりに宿る魂そのものを指す"},
     {synonym:true,word:"mind",meaning:"心，頭",breakdown:"考える働き。soul は生命や人格の芯にあるものを指す"},
     {synonym:true,word:"heart",meaning:"心臓；心",breakdown:"感情のある場所。soul はもっと深い、命の芯を指す"},
     {synonym:true,word:"ghost",meaning:"幽霊",breakdown:"死者の姿。soul は生きている人にも宿っているもの"}]},

  {id:1343,word:"priest",partOfSpeech:"名詞",meaning:"神父，司祭",
   meanings:["名|神父，司祭"],
   pronunciation:"/priːst/",part:135,
   example:"The village priest visits sick people every single week.",
   exampleJa:"その村の神父は、毎週病気の人を訪ねる。",
   example2:"A young priest led the quiet early morning service.",
   exampleJa2:"若い神父が、静かな早朝の礼拝を導いた。",
   etymologyProcess:"presb（年長の）→ 年長者として人々を導く役目の人は…？",
   etymologyConclusion:"presb（年長の）→ 年長者として人々を導く役目を持つ人＝神父",
   hook:"長老派教会（Presbyterian）の presb と同じ語。もとは「年長者」。",
   why:"【なぜ】ギリシャ語 presbyteros は「より年長の者」。初期の教会では年長者が信者を導いたため、その役目を指す語がなまって priest になりました。\n【つながり】長老派教会（Presbyterian）の presbyter も、同じ「年長者」の語です。",
   relatedWords:[
     {synonym:true,word:"minister",meaning:"牧師",breakdown:"プロテスタントの聖職者。priest はカトリックなどの司祭を指す"},
     {synonym:true,word:"church",meaning:"教会",breakdown:"信者の集まる場所。priest はそこで人々を導く役目の人"},
     {synonym:true,word:"monk",meaning:"修道士",breakdown:"修道院で暮らす人。priest は信者を導く役目を持つ人"},
     {synonym:true,word:"elder",meaning:"年長者",breakdown:"priest のもとの意味がこれ。年長者として人々を導く人"}]},

  {id:1344,word:"faith",partOfSpeech:"名詞",meaning:"信仰；信頼",
   meanings:["名|信仰","名|（in ～への）信頼"],
   pronunciation:"/feɪθ/",part:135,
   example:"Her faith gave her strength during those hard years.",
   exampleJa:"彼女の信仰は、そのつらい年月の間、彼女に力を与えた。",
   example2:"I have complete faith in my oldest friend.",
   exampleJa2:"私はいちばん古い友人に、完全な信頼を置いている。",
   etymologyProcess:"fid（信じる）→ 疑わずにまっすぐ心を寄せていくと…？",
   etymologyConclusion:"fid（信じる）→ 疑うことなく、まっすぐ寄せていく心＝信仰",
   relatedWords:[
     {word:"confidence",meaning:"自信；信頼",breakdown:"con（すっかり）＋ fid（信じる）→ すっかり信じきっている気持ち"},
     {word:"confident",meaning:"自信のある",breakdown:"con（すっかり）＋ fid（信じる）＋ ent（〜している）→ 信じきっている"},
     {word:"fidelity",meaning:"忠実さ",breakdown:"fid（信じる）＋ ity（名詞）→ 信じられて裏切らないこと"},
     {word:"faithful",meaning:"忠実な",breakdown:"fid（信じる）＋ ful（満ちた）→ 信頼にこたえる心で満ちた"}]},

  {id:1345,word:"sacred",partOfSpeech:"形容詞",meaning:"神聖な",
   meanings:["形|神聖な，聖なる"],
   pronunciation:"/ˈseɪkrɪd/",part:135,
   example:"This old mountain is sacred to the local people.",
   exampleJa:"この古い山は、地元の人々にとって神聖なものだ。",
   example2:"They keep the sacred book inside a wooden box.",
   exampleJa2:"彼らはその神聖な本を、木の箱の中に納めている。",
   etymologyProcess:"sacr（神にささげる）＋ ed（〜された）→ 神にささげられておかしがたいと…？",
   etymologyConclusion:"sacr（神にささげる）＋ ed（〜された）→ 神にささげられて、おかしがたい＝神聖な",
   relatedWords:[
     {word:"sacrifice",meaning:"犠牲にする",breakdown:"sacr（神にささげる）＋ fic（作る）→ 神にささげるものにする"},
     {word:"sacrament",meaning:"（教会の）秘跡",breakdown:"sacr（神にささげる）＋ ment（名詞）→ 神にささげる聖なる儀式"},
     {synonym:true,word:"holy",meaning:"神聖な",breakdown:"ほぼ同じ意味。sacred は「神にささげられた」という含みが強い"},
     {synonym:true,word:"divine",meaning:"神の",breakdown:"神に属すること。sacred は人が神にささげたものを指す"}]},

  {id:1346,word:"divine",partOfSpeech:"形容詞",meaning:"神の，神から出た",
   meanings:["形|神の，神から出た"],
   pronunciation:"/dɪˈvaɪn/",part:135,
   example:"Ancient people saw divine power in the rising sun.",
   exampleJa:"古代の人々は、のぼる太陽に神の力を見た。",
   example2:"The music felt almost divine in that old hall.",
   exampleJa2:"その音楽は、あの古いホールではほとんど神のもののように感じられた。",
   etymologyProcess:"div（神）＋ ine（〜の）→ 神に属し、神から出ていると…？",
   etymologyConclusion:"div（神）＋ ine（〜の）→ 神に属していて、神から出ている＝神の",
   relatedWords:[
     {word:"divinity",meaning:"神性；神学",breakdown:"div（神）＋ ity（名詞）→ 神であるということ"},
     {word:"deity",meaning:"神",breakdown:"dei（神）＋ ty（名詞）→ 神とされている存在"},
     {synonym:true,word:"holy",meaning:"神聖な",breakdown:"神に関わること。divine は神そのものから出ていることを言う"},
     {synonym:true,word:"sacred",meaning:"神聖な",breakdown:"神にささげられたもの。divine は神に属することを言う"}]},

  {id:1347,word:"Muslim",partOfSpeech:"名詞",meaning:"イスラム教徒",
   meanings:["名|イスラム教徒","形|イスラム教の"],
   pronunciation:"/ˈmʌzlɪm/",part:135,
   example:"Many Muslims fast during the holy month of Ramadan.",
   exampleJa:"多くのイスラム教徒は、聖なるラマダンの月に断食する。",
   example2:"My Muslim classmate prays five times each single day.",
   exampleJa2:"私のイスラム教徒の同級生は、毎日5回祈る。",
   etymologyProcess:"slm（身をゆだねる）→ 神に身をすっかりゆだねる人は…？",
   etymologyConclusion:"islam（身をゆだねる）→ 神に身をすっかりゆだねている人＝イスラム教徒",
   relatedWords:[
     {word:"Islam",meaning:"イスラム教",breakdown:"islam（身をゆだねる）→ 神に身をゆだねるという教え"},
     {synonym:true,word:"Christian",meaning:"キリスト教徒",breakdown:"別の宗教の信者。Muslim はイスラム教を信じる人を指す"},
     {synonym:true,word:"mosque",meaning:"モスク",breakdown:"イスラム教の礼拝所。Muslim はそこで祈る人を指す"},
     {synonym:true,word:"believer",meaning:"信者",breakdown:"信じる人ぜんたい。Muslim はイスラム教の信者を指す"}]},

  {id:1348,word:"context",partOfSpeech:"名詞",meaning:"文脈，前後関係",
   meanings:["名|文脈，前後関係","名|（物事の）背景"],
   pronunciation:"/ˈkɑːntekst/",part:135,
   example:"You must read the word in its whole context.",
   exampleJa:"その語は、文脈全体の中で読まなければならない。",
   example2:"Without context, the photo can easily mislead people.",
   exampleJa2:"文脈がないと、その写真は簡単に人を誤解させてしまう。",
   etymologyProcess:"con（共に）＋ tex（織る）→ 前後の言葉と共に織り合わされていると…？",
   etymologyConclusion:"con（共に）＋ tex（織る）→ 前後の言葉と共に織り合わされたつながり＝文脈",
   relatedWords:[
     {word:"text",meaning:"本文，文章",breakdown:"tex（織る）→ 言葉を織り合わせて作ったもの"},
     {word:"textile",meaning:"織物",breakdown:"tex（織る）＋ ile（できる）→ 織って作ることのできる布"},
     {word:"texture",meaning:"手ざわり，きめ",breakdown:"tex（織る）＋ ure（名詞）→ 織り目から生まれる手ざわり"},
     {synonym:true,word:"background",meaning:"背景",breakdown:"後ろにある事情。context は前後のつながりのほうを指す"}]},

  {id:1349,word:"singular",partOfSpeech:"形容詞",meaning:"単数の；並外れた",
   meanings:["形|（文法の）単数の","形|並外れた，まれに見る"],
   pronunciation:"/ˈsɪŋɡjələr/",part:135,
   example:"The singular form of this old noun is irregular.",
   exampleJa:"この古い名詞の単数の形は、不規則だ。",
   example2:"She showed singular courage during the long dangerous fire.",
   exampleJa2:"彼女はその長く危険な火事の間、並外れた勇気を示した。",
   etymologyProcess:"sing（1つの）＋ ar（形容詞）→ たった1つだけを指し示すと…？",
   etymologyConclusion:"sing（1つの）＋ ar（形容詞）→ たった1つだけを指し示している＝単数の",
   relatedWords:[
     {word:"single",meaning:"ただ一つの",breakdown:"sing（1つの）→ ほかに並ぶもののない、ただ一つ"},
     {word:"singly",meaning:"一つずつ",breakdown:"sing（1つの）＋ ly（副詞）→ 一つずつ別々に"},
     {synonym:true,word:"unique",meaning:"唯一の",breakdown:"ただ一つのもの。singular は文法の「単数」にも使う"},
     {synonym:true,word:"remarkable",meaning:"注目すべき",breakdown:"目立つこと。singular は「並外れた」の意味でも使う"}]},

  {id:1350,word:"command",partOfSpeech:"名詞",meaning:"（言語を）操る力；命令",
   meanings:["名|（言語などを）操る力","名|命令，指揮"],
   pronunciation:"/kəˈmænd/",part:135,
   example:"She has a good command of three foreign languages.",
   exampleJa:"彼女は3つの外国語を自在に操る力を持っている。",
   example2:"The captain gave a clear command to everyone aboard.",
   exampleJa2:"艦長は、乗っているみんなにはっきりした命令を出した。",
   etymologyProcess:"com（すっかり）＋ mand（委ねる）→ すっかり自分の手に委ねて動かすと…？",
   etymologyConclusion:"com（すっかり）＋ mand（委ねる）→ すっかり自分の手に委ねて意のままに動かす力＝操る力",
   relatedWords:[
     {word:"demand",meaning:"要求する",breakdown:"de（すっかり）＋ mand（委ねる）→ 自分に委ねるよう強く求める"},
     {word:"recommend",meaning:"推薦する",breakdown:"re（強く）＋ mand（委ねる）→ 安心して委ねられると勧める"},
     {word:"mandatory",meaning:"義務的な",breakdown:"mand（委ねる）＋ ory（形容詞）→ 命じられて必ずしなければならない"},
     {synonym:true,word:"order",meaning:"命令",breakdown:"言いつけること。command は指揮する立場からの命令を指す"}]},
