  {id:1851,word:"texture",partOfSpeech:"名詞",meaning:"手ざわり，質感；（食べ物の）食感",
   meanings:["名|手ざわり，質感","名|（食べ物の）食感，歯ざわり","名|（音楽・文章の）味わい，構成"],
   pronunciation:"/ˈtekstʃər/",part:186,
   example:"This sweater has a soft texture, so it feels nice on the skin.",
   exampleJa:"このセーターは手ざわりがやわらかいので、肌に心地よい。",
   example2:"I love the crunchy texture of freshly fried chicken.",
   exampleJa2:"私は揚げたてのチキンのサクサクした食感が大好きだ。",
   etymologyProcess:"tex（織る）＋ ure（名詞）→ 布の織り目にさわると…？",
   etymologyConclusion:"tex（織る）＋ ure（名詞）→ 布の織り目が指先に伝える感じ＝手ざわり，質感",
   etymologyMore:["口の中で感じる織り目の細かさ→（食べ物の）食感，歯ざわり"],
   relatedWords:[
     {word:"text",meaning:"本文，文章",breakdown:"tex（織る）→ 言葉を織り上げてできた文章"},
     {word:"tissue",meaning:"ティッシュ；（生物の）組織",breakdown:"tis（織る）→ 薄く織った布。細胞が織り合わさった組織"},
     {word:"textile",meaning:"織物",breakdown:"tex（織る）＋ ile（できる）→ 糸を織って仕上げた布"},
     {word:"context",meaning:"文脈",breakdown:"con（共に）＋ tex（織る）→ 前後の言葉が織り合わさった流れ"}]},

  {id:1852,word:"preliminary",partOfSpeech:"形容詞",meaning:"予備的な，準備の",
   meanings:["形|予備的な，準備の","名|（―ies）予選；準備"],
   pronunciation:"/prɪˈlɪmɪneri/",part:186,
   example:"The preliminary results of the survey will be announced next week.",
   exampleJa:"その調査の予備的な結果は、来週発表される予定だ。",
   example2:"Our team easily passed the preliminary round of the tournament.",
   exampleJa2:"私たちのチームは、大会の予選ラウンドを楽々と通過した。",
   etymologyProcess:"pre（先に）＋ limin（敷居）→ 敷居をまたぐ前に済ませるのは…？",
   etymologyConclusion:"pre（先に）＋ limin（敷居）＋ ary（形容詞）→ 本番の敷居をまたぐ前の段階の＝予備的な",
   relatedWords:[
     {word:"eliminate",meaning:"取り除く",breakdown:"ex（外へ）＋ limin（敷居）→ 敷居の外へ追い出す"},
     {word:"prepare",meaning:"準備する",breakdown:"pre（先に）＋ par（整える）→ 本番より先に整えておく"},
     {word:"preview",meaning:"下見；試写",breakdown:"pre（先に）＋ vis（見る）→ 公開より先に見ておく"},
     {synonym:true,word:"introductory",meaning:"導入の，入門の",breakdown:"本題へ導き入れる。preliminary は本番前の下準備"}]},

  {id:1853,word:"mandatory",partOfSpeech:"形容詞",meaning:"（法や命令で）強制的な，必須の",
   meanings:["形|（法や命令で）強制的な，必須の"],
   pronunciation:"/ˈmændətɔːri/",part:186,
   example:"Wearing a helmet is mandatory for everyone on this construction site.",
   exampleJa:"この工事現場では、全員のヘルメット着用が強制的に決められている。",
   example2:"Is it mandatory to attend the meeting after school today?",
   exampleJa2:"今日の放課後の集まりには、必ず出席しなければなりませんか。",
   etymologyProcess:"mand（委ねる）＋ ory（形容詞）→ 命令として手渡されたことは…？",
   etymologyConclusion:"mand（委ねる）＋ ory（形容詞）→ 上から命令として委ねられ、断れない＝（法や命令で）強制的な",
   relatedWords:[
     {word:"command",meaning:"命令する",breakdown:"com（すっかり）＋ mand（委ねる）→ すっかり言い渡して任せる"},
     {word:"demand",meaning:"要求する",breakdown:"de（すっかり）＋ mand（委ねる）→ すっかり自分に渡せと迫る"},
     {word:"mandate",meaning:"（公的な）命令，権限",breakdown:"mand（委ねる）＋ ate（名詞）→ 上から委ねられた務め"},
     {synonym:true,word:"compulsory",meaning:"義務的な，必修の",breakdown:"規則で押しつけられる。必修科目によく使う"}]},

  {id:1854,word:"indigenous",partOfSpeech:"形容詞",meaning:"（その土地に）もともと住む，土着の",
   meanings:["形|（その土地に）もともと住む，土着の","形|（動植物が）その土地原産の"],
   pronunciation:"/ɪnˈdɪdʒənəs/",part:186,
   example:"Indigenous people have lived on this island for thousands of years.",
   exampleJa:"この島には、何千年も前からもともと住む人々が暮らしてきた。",
   example2:"Koalas are indigenous to Australia and live in eucalyptus forests.",
   exampleJa2:"コアラはオーストラリア原産で、ユーカリの森にすむ。",
   etymologyProcess:"indi（中で）＋ gen（生み出す）→ その土地の中で生まれたのは…？",
   etymologyConclusion:"indi（中で）＋ gen（生み出す）＋ ous（形容詞）→ その土地の中で生まれ育った＝（その土地に）もともと住む",
   relatedWords:[
     {word:"generation",meaning:"世代",breakdown:"gen（生み出す）＋ ation（名詞）→ 同じころに生み出された人々"},
     {word:"gene",meaning:"遺伝子",breakdown:"gen（生み出す）→ 親から子を生み出すもと"},
     {word:"generous",meaning:"気前のよい",breakdown:"gen（生み出す）＋ ous（形容詞）→ 良い生まれらしく心が広い"},
     {synonym:true,word:"native",meaning:"その土地に生まれた",breakdown:"生まれた場所を表すふつうの語。indigenous は硬い言い方"}]},

  {id:1855,word:"respective",partOfSpeech:"形容詞",meaning:"それぞれの，各自の",
   meanings:["形|それぞれの，各自の"],
   pronunciation:"/rɪˈspektɪv/",part:186,
   example:"After the ceremony, the students went back to their respective classrooms.",
   exampleJa:"式のあと、生徒たちはそれぞれの教室へ戻った。",
   example2:"My brother and I are good at our respective subjects.",
   exampleJa2:"兄と私は、それぞれ別の得意科目がある。",
   etymologyProcess:"re（後ろへ）＋ spect（見る）→ 一人ひとりを振り返って見ると…？",
   etymologyConclusion:"re（後ろへ）＋ spect（見る）＋ ive（形容詞）→ 一人ひとりを振り返って見た、その人ごとの＝それぞれの",
   why:"【なぜ】ラテン語 respicere は「振り返って見る」。そこから respect に「～に目を向けること、関係」という意味が生まれ、「その人に関係した分の」→「それぞれの」となりました。\n【つながり】respectively（それぞれ）は文の最後に置いて「前に挙げた順に」を表します。尊敬の respect も同じ語から別の方向に育った形です。",
   relatedWords:[
     {word:"respect",meaning:"尊敬する",breakdown:"re（後ろへ）＋ spect（見る）→ 振り返ってもう一度見るほど重んじる"},
     {word:"expect",meaning:"期待する",breakdown:"ex（外へ）＋ spect（見る）→ 外を見て来るのを待つ"},
     {word:"inspect",meaning:"検査する",breakdown:"in（中へ）＋ spect（見る）→ 中までよく見る"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ ator（人）→ 試合を見る人"}]},

  {id:1856,word:"multiply",partOfSpeech:"他動詞・自動詞",meaning:"（数を）掛ける；増やす，増える",
   meanings:["他|（数を）掛ける，掛け算する","他|（大幅に）増やす","自|増える，繁殖する"],
   pronunciation:"/ˈmʌltɪplaɪ/",part:186,
   example:"If you multiply three by four, you get twelve.",
   exampleJa:"3に4を掛けると、12になる。",
   example2:"Bacteria multiply very quickly in warm and wet places.",
   exampleJa2:"細菌は暖かく湿った場所でとても速く増える。",
   usage:["multiply A by B（A に B を掛ける）"],
   etymologyProcess:"multi（多く）＋ plic（折る）→ 何回も折り重ねると…？",
   etymologyConclusion:"multi（多く）＋ plic（折る）→ 何重にも折り重ねて数を何倍にもする＝（数を）掛ける",
   spelling:"plic→ply（フランス語を通って縮まった）",
   etymologyMore:["折り重ねるたびに量がふくらむ→（大幅に）増やす","生き物が折り重なるように数を増す→増える，繁殖する"],
   relatedWords:[
     {word:"multiple",meaning:"多数の，複数の",breakdown:"multi（多く）＋ plic（折る）→ 何重にも折り重なった"},
     {word:"multimedia",meaning:"マルチメディア",breakdown:"multi（多く）＋ medi（中間）→ 間を取りもつ媒体を多く使う"},
     {word:"complicated",meaning:"複雑な",breakdown:"com（共に）＋ plic（折る）→ いくつも折り重なってこみ入った"},
     {word:"explicit",meaning:"明白な",breakdown:"ex（外へ）＋ plic（折る）→ 折り目を外へ広げてはっきり見せた"}]},

  {id:1857,word:"soar",partOfSpeech:"自動詞",meaning:"（空高く）舞い上がる；急上昇する",
   meanings:["自|（空高く）舞い上がる","自|（物価・数量が）急上昇する"],
   pronunciation:"/sɔːr/",part:186,
   example:"We watched an eagle soar high above the mountains.",
   exampleJa:"私たちは、ワシが山々の上空高く舞い上がるのを見た。",
   example2:"Vegetable prices have soared because of the bad weather this summer.",
   exampleJa2:"この夏の悪天候のせいで、野菜の値段が急上昇した。",
   etymologyProcess:"ex（外へ）＋ aur（空気）→ 地面を離れて空気の中へ出ると…？",
   etymologyConclusion:"ex（外へ）＋ aur（空気）→ 地面を離れ、空気の中へ高く出ていく＝（空高く）舞い上がる",
   spelling:"ex→s、aur→oar（どちらもフランス語を通って縮まった）",
   etymologyMore:["数字が鳥のように高く上がる→（物価・数量が）急上昇する"],
   relatedWords:[
     {word:"aura",meaning:"オーラ，雰囲気",breakdown:"aur（空気）→ 人のまわりにただよう空気"},
     {word:"exit",meaning:"出口",breakdown:"ex（外へ）＋ it（行く）→ 外へ出て行くところ"},
     {word:"export",meaning:"輸出する",breakdown:"ex（外へ）＋ port（運ぶ）→ 国の外へ運び出す"},
     {synonym:true,word:"rise",meaning:"上がる",breakdown:"上がること全般。soar は勢いよく高く上がる"}]},

  {id:1858,word:"diminish",partOfSpeech:"他動詞・自動詞",meaning:"（次第に）減少する，小さくなる",
   meanings:["自|（次第に）減少する，小さくなる","他|（価値・力を）減らす，弱める"],
   pronunciation:"/dɪˈmɪnɪʃ/",part:186,
   example:"The pain in my knee began to diminish after a few days.",
   exampleJa:"ひざの痛みは、数日後に次第に減少し始めた。",
   example2:"The accident did not diminish his love for soccer at all.",
   exampleJa2:"その事故も、彼のサッカーへの愛をまったく弱めなかった。",
   etymologyProcess:"de（すっかり）＋ min（小さい）→ すっかり小さくなっていくと…？",
   etymologyConclusion:"de（すっかり）＋ min（小さい）＋ ish（動詞をつくる）→ だんだん小さくなっていく＝（次第に）減少する",
   spelling:"de→di（のちに綴りが変わった）",
   relatedWords:[
     {word:"mini",meaning:"小型の",breakdown:"min（小さい）→ 小さいサイズのもの"},
     {word:"minute",meaning:"分；ごく小さい",breakdown:"min（小さい）→ 時間を小さく区切った単位"},
     {word:"minimum",meaning:"最小限",breakdown:"min（小さい）→ これ以上ないほど小さい量"},
     {word:"minor",meaning:"小さいほうの",breakdown:"min（小さい）＋ or（より～な）→ より小さく重要でない"}]},

  {id:1859,word:"accumulate",partOfSpeech:"他動詞・自動詞",meaning:"（少しずつ）蓄積する，ためる",
   meanings:["他|（少しずつ）蓄積する，ためる","自|たまる，積もる"],
   pronunciation:"/əˈkjuːmjəleɪt/",part:186,
   example:"She accumulated a lot of knowledge by reading every day.",
   exampleJa:"彼女は毎日の読書で、多くの知識を蓄積した。",
   example2:"Dust accumulates quickly on the shelves if you don't clean them.",
   exampleJa2:"掃除をしないと、棚にはすぐにほこりがたまる。",
   etymologyProcess:"ad（～へ）＋ cumul（積み重ね）→ 山の上へ次々に重ねると…？",
   etymologyConclusion:"ad（～へ）＋ cumul（積み重ね）＋ ate（動詞）→ 山の上へ少しずつ積み重ねていく＝（少しずつ）蓄積する",
   spelling:"ad→ac（c の前で同化）",
   relatedWords:[
     {word:"cumulative",meaning:"累積的な",breakdown:"cumul（積み重ね）＋ ative（形容詞）→ 積み重なって増えていく"},
     {word:"accept",meaning:"受け入れる",breakdown:"ad（～へ）＋ cept（取る）→ 自分のほうへ取り入れる"},
     {word:"attract",meaning:"引きつける",breakdown:"ad（～へ）＋ tract（引く）→ 自分のほうへ引き寄せる"},
     {synonym:true,word:"collect",meaning:"集める",breakdown:"あちこちから寄せ集める。accumulate は少しずつたまっていく"}]},

  {id:1860,word:"exceed",partOfSpeech:"他動詞",meaning:"（限度・数量を）超える，上回る",
   meanings:["他|（限度・数量を）超える，上回る"],
   pronunciation:"/ɪkˈsiːd/",part:186,
   example:"The cost of the trip must not exceed 50,000 yen.",
   exampleJa:"旅行の費用は5万円を超えてはならない。",
   example2:"The number of visitors exceeded our expectations this year.",
   exampleJa2:"今年の来場者数は、私たちの予想を上回った。",
   etymologyProcess:"ex（外へ）＋ ced（行く）→ 決められた線の外へ行くと…？",
   etymologyConclusion:"ex（外へ）＋ ced（行く）→ 決められた線の外まで行ってしまう＝（限度・数量を）超える",
   spelling:"ced→ceed（綴りが変わった）",
   relatedWords:[
     {word:"excess",meaning:"超過，行き過ぎ",breakdown:"ex（外へ）＋ cess（行く）→ 線の外まで行ってしまった分"},
     {word:"success",meaning:"成功",breakdown:"sub（下で）＋ cess（行く）→ 下から続いて行き、うまく至る"},
     {word:"process",meaning:"過程",breakdown:"pro（前へ）＋ cess（行く）→ 前へ進んでいく道すじ"},
     {word:"access",meaning:"接近，利用",breakdown:"ad（～へ）＋ cess（行く）→ 目的の場所へ行くこと"}]},

  {id:1861,word:"abundant",partOfSpeech:"形容詞",meaning:"（あり余るほど）豊富な",
   meanings:["形|（あり余るほど）豊富な，たくさんある"],
   pronunciation:"/əˈbʌndənt/",part:187,
   example:"This region has abundant rain, so rice grows well here.",
   exampleJa:"この地方は雨が豊富なので、ここでは米がよく育つ。",
   example2:"Fish are abundant in the clean river near our school.",
   exampleJa2:"学校の近くのきれいな川には、魚が豊富にいる。",
   etymologyProcess:"ab（離れて）＋ und（波打つ）→ 波がふちからあふれ出すほどだと…？",
   etymologyConclusion:"ab（離れて）＋ und（波打つ）＋ ant（～な）→ 波がふちからあふれ出すほど多い＝（あり余るほど）豊富な",
   relatedWords:[
     {word:"surround",meaning:"取り囲む",breakdown:"sur（上を越えて）＋ und（波打つ）→ 波があふれてまわりを包む"},
     {word:"abound",meaning:"たくさんある",breakdown:"ab（離れて）＋ und（波打つ）→ 波があふれるほど満ちている"},
     {word:"absent",meaning:"欠席の",breakdown:"ab（離れて）＋ sent（いる）→ その場から離れている"},
     {synonym:true,word:"plenty",meaning:"たくさん",breakdown:"十分以上にあること。a lot と同じくらいよく使う"}]},

  {id:1862,word:"ample",partOfSpeech:"形容詞",meaning:"（十分すぎるほど）たっぷりの，広い",
   meanings:["形|（十分すぎるほど）たっぷりの","形|（場所が）広い，ゆったりした"],
   pronunciation:"/ˈæmpəl/",part:187,
   example:"There is ample space for all our bikes behind the gym.",
   exampleJa:"体育館の裏には、全員の自転車を置けるたっぷりの空間がある。",
   example2:"You will have ample time to finish the test, so don't rush.",
   exampleJa2:"テストを終える時間はたっぷりあるので、あわてないで。",
   etymologyProcess:"ampl（大きい）→ 必要な量より大きくゆとりがあると…？",
   etymologyConclusion:"ampl（大きい）→ 必要な量より大きく、ゆとりがある＝（十分すぎるほど）たっぷりの",
   hook:"ギターの「アンプ」は amplifier の略。小さな音を ample（たっぷり）に大きくする機械。",
   relatedWords:[
     {word:"amplify",meaning:"（音などを）増幅する",breakdown:"ampl（大きい）＋ ify（する）→ 小さな音を大きくする"},
     {word:"amplifier",meaning:"アンプ，増幅器",breakdown:"ampl（大きい）＋ ify（する）＋ er（道具・人）→ 音を大きくする機械"},
     {synonym:true,word:"enough",meaning:"十分な",breakdown:"必要なだけあること。ample は必要以上にたっぷり"},
     {synonym:true,word:"plenty",meaning:"たくさん",breakdown:"量が多いこと全般。ample は硬い書き言葉で使う"}]},

  {id:1863,word:"gross",partOfSpeech:"形容詞",meaning:"（差し引く前の）総計の；ひどい",
   meanings:["形|（差し引く前の）総計の，全体の","形|（間違い・不正が）ひどい，はなはだしい","形|（口語で）気持ち悪い"],
   pronunciation:"/ɡroʊs/",part:187,
   example:"The company's gross income this year was over ten billion yen.",
   exampleJa:"その会社の今年の収入は、総計で100億円を超えた。",
   example2:"Forgetting your passport before a school trip is a gross mistake.",
   exampleJa2:"修学旅行の前にパスポートを忘れるのは、ひどい間違いだ。",
   etymologyProcess:"gross（大量の）→ 細かく分けずに大きな丸ごとで見ると…？",
   etymologyConclusion:"gross（大量の）→ 何も差し引かず、大きな丸ごとの量で数える＝（差し引く前の）総計の",
   hook:"GDP の G は gross（総計の）。手取りの net に対して、引かれる前の丸ごとの額。",
   etymologyMore:["大きすぎて目立つほど→（間違い・不正が）ひどい，はなはだしい"],
   relatedWords:[
     {word:"grocery",meaning:"食料雑貨店",breakdown:"gross（大量の）＋ ery（場所）→ 大量に仕入れて売る店"},
     {word:"grocer",meaning:"食料雑貨商",breakdown:"gross（大量の）＋ er（人）→ 品物を大量に仕入れる商人"},
     {synonym:true,word:"total",meaning:"合計の",breakdown:"全部を足した。gross は差し引く前であることを強調する"},
     {synonym:true,word:"whole",meaning:"全体の",breakdown:"欠けずにまるごとの。gross は主にお金や量に使う"}]},

  {id:1864,word:"infinite",partOfSpeech:"形容詞",meaning:"無限の，限りない",
   meanings:["形|無限の，限りない","形|（数えきれないほど）莫大な"],
   pronunciation:"/ˈɪnfɪnət/",part:187,
   example:"The universe seems infinite when you look up at the night sky.",
   exampleJa:"夜空を見上げると、宇宙は無限のように思える。",
   example2:"Our teacher seems to have infinite patience with us.",
   exampleJa2:"先生は私たちに対して、限りない忍耐力を持っているようだ。",
   etymologyProcess:"in（否定）＋ fin（終わり）→ 終わりが決められていないと…？",
   etymologyConclusion:"in（否定）＋ fin（終わり）＋ ite（～された）→ 終わりが定められていない＝無限の",
   relatedWords:[
     {word:"finish",meaning:"終える",breakdown:"fin（終わり）＋ ish（～にする）→ 終わりまでたどり着かせる"},
     {word:"final",meaning:"最後の",breakdown:"fin（終わり）＋ al（形容詞）→ いちばん終わりの"},
     {word:"define",meaning:"定義する",breakdown:"de（すっかり）＋ fin（終わり）→ 意味の境目をはっきり決める"},
     {word:"finite",meaning:"限りのある",breakdown:"fin（終わり）＋ ite（～された）→ 終わりが決められた"}]},

  {id:1865,word:"sole",partOfSpeech:"形容詞",meaning:"ただ一つの，唯一の",
   meanings:["形|ただ一つの，唯一の","形|（権利などが）独占的な"],
   pronunciation:"/soʊl/",part:187,
   example:"Ken was the sole student who got a perfect score on the test.",
   exampleJa:"ケンは、そのテストで満点を取ったただ一人の生徒だった。",
   example2:"My sole purpose in joining the club was to make friends.",
   exampleJa2:"部に入った私のただ一つの目的は、友達を作ることだった。",
   etymologyProcess:"sole（ただ一つの）→ ほかに並ぶものがいないのは…？",
   etymologyConclusion:"sole（ただ一つの）→ ほかに並ぶものがなく、それだけ＝ただ一つの",
   hook:"solo（ソロ）と同じラテン語 solus から。足の裏や魚の sole は別の語。",
   relatedWords:[
     {word:"solo",meaning:"ソロ，独奏",breakdown:"sole（ただ一つの）→ ただ一人で歌う・演奏する"},
     {word:"solitary",meaning:"ひとりぼっちの",breakdown:"sole（ただ一つの）＋ ary（形容詞）→ ただ一人でいる"},
     {synonym:true,word:"only",meaning:"唯一の",breakdown:"ふつうの「ただ一つの」。sole は硬い言い方"},
     {synonym:true,word:"single",meaning:"たった一つの",breakdown:"一つだけであること。sole はほかにいないことを強調"}]},

  {id:1866,word:"heap",partOfSpeech:"名詞",meaning:"（どさっと積もった）山，かたまり",
   meanings:["名|（どさっと積もった）山，かたまり","名|（a heap of / heaps of）たくさん","他|積み上げる"],
   pronunciation:"/hiːp/",part:187,
   example:"There was a heap of dirty clothes on his bedroom floor.",
   exampleJa:"彼の寝室の床には、汚れた服の山があった。",
   example2:"We have heaps of homework to do this weekend.",
   exampleJa2:"今週末は、やるべき宿題がたくさんある。",
   etymologyProcess:"heap（積み重なり）→ 物がどさっと積もってできるのは…？",
   etymologyConclusion:"heap（積み重なり）→ 物がどさっと積もってできた山＝（どさっと積もった）山",
   hook:"a heap of ～ / heaps of ～ で「山ほどの～」。pile より乱雑に積もった感じ。",
   relatedWords:[
     {synonym:true,word:"pile",meaning:"積み重なった山",breakdown:"きちんと重ねた山にも使う。heap は乱雑"},
     {synonym:true,word:"stack",meaning:"（整然と積んだ）山",breakdown:"本や皿をきれいに重ねた山"},
     {synonym:true,word:"lot",meaning:"たくさん",breakdown:"a lot of の lot。heaps of はくだけた言い方"},
     {synonym:true,word:"mountain",meaning:"山",breakdown:"本物の山。a mountain of ～ も「山ほどの～」"}]},

  {id:1867,word:"fraction",partOfSpeech:"名詞",meaning:"ほんの一部，わずか；分数",
   meanings:["名|ほんの一部，わずか","名|分数"],
   pronunciation:"/ˈfrækʃən/",part:187,
   example:"Only a fraction of the students passed the difficult exam.",
   exampleJa:"その難しい試験に合格したのは、生徒のほんの一部だけだった。",
   example2:"We learned how to add fractions in math class today.",
   exampleJa2:"今日の数学の授業で、分数の足し算を習った。",
   etymologyProcess:"frag（砕く）＋ ion（名詞）→ 全体を砕いてできたかけらは…？",
   etymologyConclusion:"frag（砕く）＋ ion（名詞）→ 全体を砕いてできた小さなかけら＝ほんの一部",
   spelling:"frag→fract（「砕かれた」の形 fractus から）",
   etymologyMore:["全体を割った一かけらを数で表す→分数"],
   relatedWords:[
     {word:"fragile",meaning:"壊れやすい",breakdown:"frag（砕く）＋ ile（できる）→ すぐに砕けてしまう"},
     {word:"fragment",meaning:"破片，かけら",breakdown:"frag（砕く）＋ ment（名詞）→ 砕けて残った小片"},
     {word:"fracture",meaning:"骨折",breakdown:"frag（砕く）＋ ure（名詞）→ 骨が砕けて折れること"},
     {synonym:true,word:"part",meaning:"部分",breakdown:"全体の一部分。fraction はごくわずかな部分"}]},

  {id:1868,word:"simultaneous",partOfSpeech:"形容詞",meaning:"同時の，同時に起こる",
   meanings:["形|同時の，同時に起こる"],
   pronunciation:"/ˌsaɪməlˈteɪniəs/",part:187,
   example:"There were simultaneous power outages in several towns last night.",
   exampleJa:"昨夜、いくつかの町で同時に停電が起きた。",
   example2:"The concert will be shown simultaneously on TV and online.",
   exampleJa2:"そのコンサートはテレビとネットで同時に放送される。",
   etymologyProcess:"simul（一緒に）＋ ous（形容詞）→ 時間の上で一緒に並ぶと…？",
   etymologyConclusion:"simul（一緒に）＋ ous（形容詞）→ 同じ時間に一緒に起こる＝同時の",
   relatedWords:[
     {word:"assemble",meaning:"集める，組み立てる",breakdown:"ad（～へ）＋ simul（一緒に）→ 一か所へ一緒に寄せる"},
     {word:"assembly",meaning:"集会",breakdown:"ad（～へ）＋ simul（一緒に）→ 一か所に一緒に集まること"},
     {synonym:true,word:"same",meaning:"同じ",breakdown:"simul と遠い親戚の英語本来の語"},
     {synonym:true,word:"together",meaning:"一緒に",breakdown:"場所も時もそろって。simultaneous は時がそろう"}]},

  {id:1869,word:"medieval",partOfSpeech:"形容詞",meaning:"中世の",
   meanings:["形|中世の","形|（口語で）古くさい"],
   pronunciation:"/ˌmediˈiːvəl/",part:187,
   example:"We visited a medieval castle during our trip to Germany.",
   exampleJa:"ドイツ旅行の間に、私たちは中世の城を訪れた。",
   example2:"Most medieval people rarely traveled far from their villages.",
   exampleJa2:"中世の人々の多くは、村から遠くへ出かけることはめったになかった。",
   etymologyProcess:"medi（中間）＋ ev（時代）→ 古代と近代の間にある時代は…？",
   etymologyConclusion:"medi（中間）＋ ev（時代）＋ al（形容詞）→ 古代と近代の間にはさまれた時代の＝中世の",
   relatedWords:[
     {word:"medium",meaning:"中くらいの",breakdown:"medi（中間）→ 大と小の間の大きさ"},
     {word:"media",meaning:"メディア",breakdown:"medi（中間）→ 出来事と人の間を取りもつもの"},
     {word:"immediately",meaning:"すぐに",breakdown:"im（否定）＋ medi（中間）→ 間に何もはさまずに"},
     {word:"age",meaning:"時代；年齢",breakdown:"ev（時代）→ 生きてきた時の長さ、ひと区切りの時代"}]},

  {id:1870,word:"dawn",partOfSpeech:"名詞",meaning:"夜明け；（物事の）始まり",
   meanings:["名|夜明け","名|（物事の）始まり，幕開け","自|夜が明ける"],
   pronunciation:"/dɔːn/",part:187,
   example:"We left home at dawn to see the sunrise from the mountain.",
   exampleJa:"山から日の出を見るため、私たちは夜明けに家を出た。",
   example2:"The invention of the internet marked the dawn of a new age.",
   exampleJa2:"インターネットの発明は、新しい時代の始まりとなった。",
   etymologyProcess:"day（日）→ 新しい日の光がさしはじめる時は…？",
   etymologyConclusion:"day（日）→ 新しい日の光がさしはじめる時＝夜明け",
   spelling:"day→daw（古英語 dagian「夜が明ける」から変化）",
   hook:"day と同じ古英語の家族。from dawn till dusk で「夜明けから夕暮れまで」。",
   etymologyMore:["一日が明けるように時代が明ける→（物事の）始まり，幕開け"],
   relatedWords:[
     {word:"today",meaning:"今日",breakdown:"to（～へ）＋ day（日）→ この日に"},
     {word:"daily",meaning:"毎日の",breakdown:"day（日）＋ ly（～のような）→ 一日ごとの"},
     {word:"Sunday",meaning:"日曜日",breakdown:"sun（太陽）＋ day（日）→ 太陽の日"},
     {word:"someday",meaning:"いつか",breakdown:"som（何らかの）＋ day（日）→ いつかのある日"}]},

  {id:1871,word:"span",partOfSpeech:"名詞",meaning:"（時間の）長さ，期間；（橋などの）全長",
   meanings:["名|（時間の）長さ，期間","名|（橋などの）全長，端から端まで","他|（期間・空間に）またがる"],
   pronunciation:"/spæn/",part:188,
   example:"He read more than 300 books over a span of three years.",
   exampleJa:"彼は3年の期間に、300冊以上の本を読んだ。",
   example2:"The new bridge has a span of nearly one kilometer.",
   exampleJa2:"新しい橋は、全長が1キロ近くある。",
   etymologyProcess:"span（手を広げた幅）→ 端から端までの広がりは…？",
   etymologyConclusion:"span（手を広げた幅）→ 端から端までの広がりを時間に当てはめた＝（時間の）長さ，期間",
   hook:"もとは親指から小指まで手を広げた長さ。life span（寿命）、attention span（集中が続く時間）。",
   etymologyMore:["手を広げて端から端まで届く→（橋などの）全長，端から端まで"],
   relatedWords:[
     {synonym:true,word:"period",meaning:"期間",breakdown:"区切られた時間。span は始めから終わりまでの長さ"},
     {synonym:true,word:"length",meaning:"長さ",breakdown:"物や時間の長さ全般"},
     {synonym:true,word:"term",meaning:"学期；期間",breakdown:"決められた期間。school term（学期）"},
     {synonym:true,word:"lifetime",meaning:"一生",breakdown:"生きている間。life span は寿命の長さ"}]},

  {id:1872,word:"adolescent",partOfSpeech:"名詞",meaning:"思春期の若者；思春期の",
   meanings:["名|思春期の若者","形|思春期の，青年期の"],
   pronunciation:"/ˌædəˈlesənt/",part:188,
   example:"Many adolescents worry about how they look to others.",
   exampleJa:"多くの思春期の若者は、他人からどう見えるかを気にする。",
   example2:"Adolescent children need plenty of sleep to grow well.",
   exampleJa2:"思春期の子どもがよく育つには、十分な睡眠が必要だ。",
   etymologyProcess:"ad（～へ）＋ ol（育つ）→ 子どもから大人へ移る途中の時期は…？",
   etymologyConclusion:"ad（～へ）＋ ol（育つ）＋ ent（人）→ 大人へ向かって育っている途中の人＝思春期の若者",
   relatedWords:[
     {word:"adult",meaning:"大人",breakdown:"ad（～へ）＋ ol（育つ）→ すっかり育ち終えた人"},
     {word:"adolescence",meaning:"思春期，青年期",breakdown:"ad（～へ）＋ ol（育つ）＋ ence（名詞）→ 大人へ育っていく時期"},
     {synonym:true,word:"teenager",meaning:"10代の若者",breakdown:"13～19歳（-teen が付く年齢）の人"},
     {synonym:true,word:"youth",meaning:"若者；青春時代",breakdown:"若い人や若い時期全般。adolescent は子どもから大人への途中"}]},

  {id:1873,word:"millennium",partOfSpeech:"名詞",meaning:"千年，千年間；千年紀",
   meanings:["名|千年，千年間","名|千年紀（西暦を千年ごとに区切った期間）"],
   pronunciation:"/mɪˈleniəm/",part:188,
   example:"This old temple has stood here for more than a millennium.",
   exampleJa:"この古いお寺は、千年以上ここに建っている。",
   example2:"People around the world celebrated the new millennium in 2000.",
   exampleJa2:"2000年、世界中の人々が新しい千年紀を祝った。",
   etymologyProcess:"mil（千）＋ ann（年）→ 千の年が集まると…？",
   etymologyConclusion:"mil（千）＋ ann（年）→ 年が千回めぐるほどの長い時間＝千年，千年間",
   spelling:"ann→enn（語の中に入って母音が変わった）",
   relatedWords:[
     {word:"million",meaning:"100万",breakdown:"mil（千）→ 千をさらに大きくふくらませた数"},
     {word:"annual",meaning:"毎年の，年1回の",breakdown:"ann（年）＋ al（形容詞）→ 1年ごとにめぐってくる"},
     {word:"anniversary",meaning:"記念日",breakdown:"ann（年）＋ vers（回る）→ 1年回ってまた来る日"},
     {synonym:true,word:"century",meaning:"100年，世紀",breakdown:"cent（100）の年。millennium はその10倍"}]},

  {id:1874,word:"expire",partOfSpeech:"自動詞",meaning:"（期限が）切れる，満了する",
   meanings:["自|（期限が）切れる，満了する","自|（文語で）息を引き取る"],
   pronunciation:"/ɪkˈspaɪər/",part:188,
   example:"My passport expires next month, so I need a new one.",
   exampleJa:"私のパスポートは来月期限が切れるので、新しいものが必要だ。",
   example2:"Check the date before you use this coupon, because it may have expired.",
   exampleJa2:"このクーポンは期限が切れているかもしれないので、使う前に日付を確かめて。",
   etymologyProcess:"ex（外へ）＋ spir（息をする）→ 最後の息を外へ吐き出すと…？",
   etymologyConclusion:"ex（外へ）＋ spir（息をする）→ 最後の息を吐き出すように、有効な時間が終わる＝（期限が）切れる",
   why:"【なぜ】ex（外へ）＋ spir（息をする）で、もとは「最後の息を外へ吐き出す」＝息を引き取ることでした。命が終わるイメージが、契約や免許、クーポンなどの「有効な命」が終わることにも使われ、「期限が切れる」の意味になりました。\n【つながり】spirit（精神）や inspire（ひらめきを吹きこむ）も「息」の仲間。expiration date は「有効期限」です。",
   spelling:"spir→pir（x の中に s の音が吸収された）",
   relatedWords:[
     {word:"spirit",meaning:"精神，心",breakdown:"spir（息をする）→ 体に吹きこまれた命の息"},
     {word:"inspire",meaning:"ひらめきを与える",breakdown:"in（中へ）＋ spir（息をする）→ 心の中へ息を吹きこむ"},
     {word:"expiration",meaning:"満了，期限切れ",breakdown:"ex（外へ）＋ spir（息をする）＋ ation（名詞）→ 息が尽きること"},
     {synonym:true,word:"end",meaning:"終わる",breakdown:"終わること全般。expire は決められた期限が終わる"}]},

  {id:1875,word:"postpone",partOfSpeech:"他動詞",meaning:"（予定を）延期する，後回しにする",
   meanings:["他|（予定を）延期する，後回しにする"],
   pronunciation:"/poʊstˈpoʊn/",part:188,
   example:"The baseball game was postponed because of heavy rain.",
   exampleJa:"その野球の試合は、大雨のため延期された。",
   example2:"Let's postpone the meeting until everyone can come to school.",
   exampleJa2:"全員が学校に来られるまで、話し合いを延期しよう。",
   usage:["postpone doing（～するのを延期する）"],
   etymologyProcess:"post（後に）＋ pon（置く）→ 予定を後ろへ置き直すと…？",
   etymologyConclusion:"post（後に）＋ pon（置く）→ 予定を今より後ろの日に置き直す＝（予定を）延期する",
   relatedWords:[
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ion（名詞）→ 物が置かれている場所"},
     {word:"opponent",meaning:"相手，敵",breakdown:"op（向かい合って）＋ pon（置く）→ 向かい側に置かれた人"},
     {word:"postwar",meaning:"戦後の",breakdown:"post（後に）＋ war（戦い）→ 戦争が終わった後の"},
     {synonym:true,word:"delay",meaning:"遅らせる",breakdown:"予定より遅れさせる。postpone は日時を決め直す"}]},

  {id:1876,word:"periodically",partOfSpeech:"副詞",meaning:"定期的に，周期的に",
   meanings:["副|定期的に，周期的に"],
   pronunciation:"/ˌpɪriˈɑːdɪkli/",part:188,
   example:"The nurse checked the patient's temperature periodically during the night.",
   exampleJa:"看護師は夜の間、患者の体温を定期的に測った。",
   example2:"Halley's Comet appears periodically, about once every 76 years.",
   exampleJa2:"ハレー彗星は、およそ76年に一度、周期的に現れる。",
   etymologyProcess:"period（一回り）＋ ic（形容詞）→ 一回りしてはまた来るように…？",
   etymologyConclusion:"period（一回り）＋ ic（形容詞）＋ ly（副詞）→ 一回りしてはまた同じことが来るように＝定期的に",
   why:"【なぜ】period はギリシャ語で「周りを（peri）めぐる道（hodos）」。ぐるりと一周してもとに戻る道のりから、同じことがくり返される「周期」、区切られた「期間」、文の終わりを示す「ピリオド」へと意味が広がりました。\n【つながり】periodic（周期的な）は元素の周期表 periodic table の periodic。-ly が付いて「一回りするたびに」＝定期的に、です。",
   relatedWords:[
     {word:"period",meaning:"期間；ピリオド",breakdown:"period（一回り）→ ひとめぐりする区切りの時間"},
     {word:"periodic",meaning:"周期的な",breakdown:"period（一回り）＋ ic（形容詞）→ 一回りごとにくり返す"},
     {synonym:true,word:"regularly",meaning:"規則正しく",breakdown:"決まった間隔で。periodically とほぼ同じ"},
     {synonym:true,word:"often",meaning:"よく，しばしば",breakdown:"回数が多いこと。間隔が決まっているとは限らない"}]},

  {id:1877,word:"array",partOfSpeech:"名詞",meaning:"勢ぞろい，ずらりと並んだもの",
   meanings:["名|勢ぞろい，ずらりと並んだもの","名|（整然とした）配列，並び","他|（整然と）並べる"],
   pronunciation:"/əˈreɪ/",part:188,
   example:"The store sells a wide array of snacks from around the world.",
   exampleJa:"その店では、世界中のお菓子が勢ぞろいしている。",
   example2:"An array of solar panels covers the roof of our school.",
   exampleJa2:"ずらりと並んだ太陽光パネルが、学校の屋根を覆っている。",
   etymologyProcess:"ad（～へ）＋ rai（整える）→ きちんと整えて並べると…？",
   etymologyConclusion:"ad（～へ）＋ rai（整える）→ きちんと整えて横一列に並べたもの＝勢ぞろい",
   spelling:"ad→ar（r の前で同化）、rai→ray（フランス語を通って変化）",
   relatedWords:[
     {word:"ready",meaning:"用意ができた",breakdown:"rai（整える）→ 整って、いつでも始められる"},
     {word:"accept",meaning:"受け入れる",breakdown:"ad（～へ）＋ cept（取る）→ 自分のほうへ取り入れる"},
     {word:"attract",meaning:"引きつける",breakdown:"ad（～へ）＋ tract（引く）→ 自分のほうへ引き寄せる"},
     {synonym:true,word:"range",meaning:"（品物の）そろい，幅",breakdown:"a wide range of も「幅広い～」。array は見た目に並ぶ感じ"}]},

  {id:1878,word:"realm",partOfSpeech:"名詞",meaning:"（活動・関心の）世界，分野；王国",
   meanings:["名|（活動・関心の）世界，分野","名|王国，領土"],
   pronunciation:"/relm/",part:188,
   example:"Her new book takes readers into the realm of fantasy.",
   exampleJa:"彼女の新しい本は、読者をファンタジーの世界へ連れていく。",
   example2:"Space travel for ordinary people is now within the realm of possibility.",
   exampleJa2:"一般の人の宇宙旅行は、今や十分ありえる世界の話になっている。",
   etymologyProcess:"reg（治める）→ 王が治める土地のような広がりは…？",
   etymologyConclusion:"reg（治める）→ 王が治める土地のように、一つの物事が支配する広がり＝（活動・関心の）世界，分野",
   spelling:"reg→re（フランス語を通って g が消えた）",
   etymologyMore:["もとの意味の、王が治める土地→王国，領土"],
   relatedWords:[
     {word:"region",meaning:"地域",breakdown:"reg（治める）＋ ion（名詞）→ 一つの支配が及ぶ土地"},
     {word:"regular",meaning:"規則正しい",breakdown:"reg（治める）＋ ar（～の）→ 決まりで治められた"},
     {word:"royal",meaning:"王の",breakdown:"roy（治める）＋ al（形容詞）→ 国を治める王の"},
     {synonym:true,word:"field",meaning:"分野",breakdown:"学問や仕事の分野。realm は想像や考えの世界にも使う"}]},

  {id:1879,word:"domain",partOfSpeech:"名詞",meaning:"（支配・権限の及ぶ）領域，範囲",
   meanings:["名|（支配・権限の及ぶ）領域，範囲","名|（ネットの）ドメイン"],
   pronunciation:"/doʊˈmeɪn/",part:188,
   example:"This question is outside my domain, so ask the science teacher.",
   exampleJa:"この質問は私の領域の外なので、理科の先生に聞いて。",
   example2:"Our school website uses its own domain name.",
   exampleJa2:"私たちの学校のウェブサイトは、独自のドメイン名を使っている。",
   etymologyProcess:"dom（家）→ 家の主人にしかできないことは…？",
   etymologyConclusion:"dom（家）→ 家の主人が取りしきるように、支配や権限が届く範囲＝（支配・権限の及ぶ）領域",
   etymologyMore:["ネット上で持ち主が管理する区画→（ネットの）ドメイン"],
   relatedWords:[
     {word:"domestic",meaning:"家庭の；国内の",breakdown:"dom（家）＋ ic（形容詞）→ 家の中の、国の内側の"},
     {word:"dome",meaning:"ドーム，丸屋根",breakdown:"dom（家）→ 大聖堂の丸い屋根"},
     {word:"dominate",meaning:"支配する",breakdown:"dom（家）＋ ate（～にする）→ 家の主人として取りしきる"},
     {synonym:true,word:"area",meaning:"地域；分野",breakdown:"広がり全般。domain は支配や担当が及ぶ範囲"}]},

  {id:1880,word:"boundary",partOfSpeech:"名詞",meaning:"境界（線），境目",
   meanings:["名|境界（線），境目","名|（―ies）限界，範囲"],
   pronunciation:"/ˈbaʊndəri/",part:188,
   example:"The river forms the boundary between the two countries.",
   exampleJa:"その川が、2つの国の境界になっている。",
   example2:"Even good friends should respect each other's personal boundaries.",
   exampleJa2:"仲の良い友達でも、互いの個人的な境目は尊重すべきだ。",
   etymologyProcess:"bound（境界）＋ ary（もの）→ 土地の境を示すものは…？",
   etymologyConclusion:"bound（境界）＋ ary（もの）→ 土地と土地の境を示す線＝境界（線）",
   relatedWords:[
     {word:"bound",meaning:"（―s）境界，限界",breakdown:"bound（境界）→ 越えてはいけない線。out of bounds"},
     {synonym:true,word:"border",meaning:"国境，へり",breakdown:"国と国の境によく使う"},
     {synonym:true,word:"limit",meaning:"限度",breakdown:"これ以上は越えられない線"},
     {synonym:true,word:"edge",meaning:"ふち，端",breakdown:"物の外側のはし"}]},

  {id:1881,word:"spectrum",partOfSpeech:"名詞",meaning:"（連続した）範囲，幅；スペクトル",
   meanings:["名|（連続した）範囲，幅","名|（光の）スペクトル"],
   pronunciation:"/ˈspektrəm/",part:189,
   example:"The survey collected a broad spectrum of opinions from students.",
   exampleJa:"その調査は、生徒から幅広い範囲の意見を集めた。",
   example2:"A rainbow shows us the colors of the light spectrum.",
   exampleJa2:"虹は、光のスペクトルの色を私たちに見せてくれる。",
   etymologyProcess:"spect（見る）→ 目に見える色の像が帯のように並ぶと…？",
   etymologyConclusion:"spect（見る）→ 目に見える像が端から端まで帯のように並んだ広がり＝（連続した）範囲，幅",
   hook:"虹の色が赤から紫まで切れ目なく並ぶ帯。a wide spectrum of ～ で「幅広い～」。",
   etymologyMore:["光を分けると色が帯になって見える→（光の）スペクトル"],
   relatedWords:[
     {word:"expect",meaning:"期待する",breakdown:"ex（外へ）＋ spect（見る）→ 外を見て来るのを待つ"},
     {word:"respect",meaning:"尊敬する",breakdown:"re（後ろへ）＋ spect（見る）→ 振り返って見直すほど重んじる"},
     {word:"spectacular",meaning:"目を見張るような",breakdown:"spect（見る）＋ ar（～の）→ 見る者を驚かせる"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ ator（人）→ 試合を見る人"}]},

  {id:1882,word:"equip",partOfSpeech:"他動詞",meaning:"（必要な物を）備えつける，装備させる",
   meanings:["他|（必要な物を）備えつける，装備させる","他|（知識・能力を）身につけさせる"],
   pronunciation:"/ɪˈkwɪp/",part:189,
   example:"The school plans to equip every classroom with a large screen.",
   exampleJa:"学校は、全教室に大型スクリーンを備えつける予定だ。",
   example2:"Good teachers equip students with the skills they need for life.",
   exampleJa2:"よい教師は、生徒に人生で必要な力を身につけさせる。",
   usage:["equip A with B（A に B を備えつける）","be equipped with ～（～を備えている）"],
   etymologyProcess:"equip（船を整える）→ 船出の前に必要な物を積みこむと…？",
   etymologyConclusion:"equip（船を整える）→ 船出に必要な物をすべて積みこむ＝（必要な物を）備えつける",
   hook:"古ノルド語の「船の支度をする」から来たとされる。名詞は equipment（装備）。",
   etymologyMore:["道具の代わりに力を積みこむ→（知識・能力を）身につけさせる"],
   relatedWords:[
     {word:"equipment",meaning:"装備，機器",breakdown:"equip（船を整える）＋ ment（名詞）→ 備えつけた道具一式"},
     {synonym:true,word:"provide",meaning:"与える，供給する",breakdown:"必要な物を渡す。equip は使えるように備えつける"},
     {synonym:true,word:"supply",meaning:"供給する",breakdown:"足りない分を補って渡す"},
     {synonym:true,word:"prepare",meaning:"準備する",breakdown:"前もって整えること全般"}]},

  {id:1883,word:"transmit",partOfSpeech:"他動詞",meaning:"（信号・病気などを）送る，伝える",
   meanings:["他|（信号・情報を）送る，送信する","他|（病気・性質などを）伝える，うつす"],
   pronunciation:"/trænzˈmɪt/",part:189,
   example:"Satellites transmit TV signals to homes all over the world.",
   exampleJa:"人工衛星は、世界中の家庭にテレビの信号を送っている。",
   example2:"Some mosquitoes can transmit serious diseases to humans.",
   exampleJa2:"蚊の中には、人間に重い病気をうつすものがいる。",
   etymologyProcess:"trans（越えて）＋ mit（送る）→ 離れた場所まで越えて届けると…？",
   etymologyConclusion:"trans（越えて）＋ mit（送る）→ 離れた場所まで越えて送り届ける＝（信号・病気などを）送る",
   etymologyMore:["人から人へ越えて送られる→（病気・性質などを）伝える，うつす"],
   relatedWords:[
     {word:"admit",meaning:"認める；入れる",breakdown:"ad（～へ）＋ mit（送る）→ 中へ送り入れるのを許す"},
     {word:"permit",meaning:"許可する",breakdown:"per（すっかり）＋ mit（送る）→ 通り抜けて送るのを許す"},
     {word:"mission",meaning:"任務",breakdown:"mit（送る）＋ ion（名詞）→ 送り出されてする仕事"},
     {word:"transport",meaning:"輸送する",breakdown:"trans（越えて）＋ port（運ぶ）→ 向こう側へ運ぶ"}]},

  {id:1884,word:"endow",partOfSpeech:"他動詞",meaning:"（才能・資質を）授ける；寄付する",
   meanings:["他|（才能・資質を）授ける","他|（学校などに）基金を寄付する"],
   pronunciation:"/ɪnˈdaʊ/",part:189,
   example:"Parents cannot endow their children with talent, but they can give love.",
   exampleJa:"親は子どもに才能を授けることはできないが、愛を与えることはできる。",
   example2:"She is endowed with a beautiful singing voice.",
   exampleJa2:"彼女は、美しい歌声を授けられている。",
   usage:["endow A with B（A に B を授ける）","be endowed with ～（～に恵まれている）"],
   etymologyProcess:"en（中へ）＋ dos（与える）→ 相手の中へ贈り物を与えると…？",
   etymologyConclusion:"en（中へ）＋ dos（与える）→ 相手の中へ贈り物として与え入れる＝（才能・資質を）授ける",
   spelling:"dos→dow（フランス語を通って変化）",
   etymologyMore:["財産を贈り物として与える→（学校などに）基金を寄付する"],
   relatedWords:[
     {synonym:true,word:"bestow",meaning:"授ける，贈る",breakdown:"目上の人が贈り物や名誉を与える。endow は才能や資金を授ける"},
     {word:"donate",meaning:"寄付する",breakdown:"don（与える）＋ ate（～する）→ お金や物を与えて贈る"},
     {word:"encourage",meaning:"励ます",breakdown:"en（中へ）＋ cour（心）→ 心の中へ勇気を入れる"},
     {synonym:true,word:"give",meaning:"与える",breakdown:"与えること全般。endow は才能やお金を授ける"}]},

  {id:1885,word:"inherit",partOfSpeech:"他動詞",meaning:"（財産・性質を）受け継ぐ，相続する",
   meanings:["他|（財産・性質を）受け継ぐ，相続する","他|（前任者から）引き継ぐ"],
   pronunciation:"/ɪnˈherɪt/",part:189,
   example:"She inherited her father's talent for music and art.",
   exampleJa:"彼女は、父親の音楽と美術の才能を受け継いだ。",
   example2:"My uncle will inherit the family farm next year.",
   exampleJa2:"おじが来年、家族の農場を相続する予定だ。",
   usage:["inherit A from B（B から A を受け継ぐ）"],
   etymologyProcess:"in（中へ）＋ herit（受け継ぐ）→ 跡継ぎとして中へ受け入れると…？",
   etymologyConclusion:"in（中へ）＋ herit（受け継ぐ）→ 跡継ぎとして親の持ち物を自分の中へ受け取る＝（財産・性質を）受け継ぐ",
   relatedWords:[
     {word:"heritage",meaning:"遺産",breakdown:"herit（受け継ぐ）＋ age（名詞）→ 先祖から受け継いだもの"},
     {word:"heir",meaning:"相続人",breakdown:"heir（受け継ぐ人）→ 財産や地位を受け継ぐ人"},
     {word:"inheritance",meaning:"相続財産",breakdown:"in（中へ）＋ herit（受け継ぐ）＋ ance（名詞）→ 受け継いだ財産"},
     {synonym:true,word:"receive",meaning:"受け取る",breakdown:"受け取ること全般。inherit は親や前の人から受け継ぐ"}]},

  {id:1886,word:"retrieve",partOfSpeech:"他動詞",meaning:"（元の場所から）取り戻す，回収する",
   meanings:["他|（元の場所から）取り戻す，回収する","他|（データを）呼び出す，復元する"],
   pronunciation:"/rɪˈtriːv/",part:189,
   example:"Our dog loves to retrieve balls from the pond.",
   exampleJa:"うちの犬は、池からボールを取り戻してくるのが大好きだ。",
   example2:"I finally retrieved the file that I had deleted by mistake.",
   exampleJa2:"間違えて消したファイルを、ようやく復元できた。",
   etymologyProcess:"re（再び）＋ triev（見つける）→ なくした物を再び見つけると…？",
   etymologyConclusion:"re（再び）＋ triev（見つける）→ なくした物を再び見つけて手元に戻す＝（元の場所から）取り戻す",
   why:"【なぜ】古いフランス語 retrover（もう一度見つける）から。狩りで撃ち落とした鳥を犬が探し出して持ち帰ることにも使われ、「見つけて持ってくる」＝取り戻す、回収する、となりました。trover（見つける）自体の語源ははっきりしていません。\n【つながり】犬のゴールデン・レトリーバー（retriever）は、獲物を回収する犬。データを「呼び出す」のも、しまった情報を見つけて持ってくることです。",
   etymologyMore:["しまった情報を見つけて持ってくる→（データを）呼び出す，復元する"],
   relatedWords:[
     {word:"retriever",meaning:"レトリーバー（犬）",breakdown:"re（再び）＋ triev（見つける）＋ er（道具・人）→ 獲物を探して持ち帰る犬"},
     {word:"return",meaning:"戻る，返す",breakdown:"re（後ろへ）＋ turn（回る）→ くるりと回って戻る"},
     {synonym:true,word:"recover",meaning:"取り戻す；回復する",breakdown:"失ったものや健康を取り戻す。cover（覆う）とは別の語"},
     {synonym:true,word:"regain",meaning:"取り戻す",breakdown:"失ったものを再び得る。retrieve は探して持ってくる"}]},

  {id:1887,word:"displace",partOfSpeech:"他動詞",meaning:"（本来の場所から）追い出す，立ち退かせる",
   meanings:["他|（本来の場所から）追い出す，立ち退かせる","他|（…に）取って代わる"],
   pronunciation:"/dɪsˈpleɪs/",part:189,
   example:"The war displaced thousands of families from their homes.",
   exampleJa:"その戦争は、何千もの家族を家から追い出した。",
   example2:"For many people, smartphones have displaced digital cameras.",
   exampleJa2:"多くの人にとって、スマートフォンがデジタルカメラに取って代わった。",
   etymologyProcess:"dis（離れて）＋ place（広場）→ いた場所から離してしまうと…？",
   etymologyConclusion:"dis（離れて）＋ place（広場）→ もといた場所から引き離して外へ出す＝（本来の場所から）追い出す",
   etymologyMore:["前のものを追い出して居座る→（…に）取って代わる"],
   relatedWords:[
     {word:"place",meaning:"場所",breakdown:"place（広場）→ 人が集まる広い所から、場所一般へ"},
     {word:"replace",meaning:"取って代わる",breakdown:"re（再び）＋ place（広場）→ 同じ場所に別のものを置き直す"},
     {word:"plaza",meaning:"広場",breakdown:"place（広場）→ 町の中の開けた場所"},
     {synonym:true,word:"remove",meaning:"取り除く",breakdown:"その場からどける。displace は住む場所を失わせる"}]},

  {id:1888,word:"bond",partOfSpeech:"名詞",meaning:"（人と人の）きずな，結びつき",
   meanings:["名|（人と人の）きずな，結びつき","名|債券","自|（with ～と）きずなを深める"],
   pronunciation:"/bɑːnd/",part:189,
   example:"The long trip created a strong bond between the two brothers.",
   exampleJa:"長い旅で、2人の兄弟の間に強いきずなが生まれた。",
   example2:"Many people buy government bonds as a safe way to save money.",
   exampleJa2:"多くの人が、安全な貯金の方法として国の債券を買う。",
   etymologyProcess:"bind（縛る）→ 人と人を結びつけて縛るものは…？",
   etymologyConclusion:"bind（縛る）→ 人と人を見えないひもで結びつけるもの＝（人と人の）きずな",
   spelling:"bind→bond（同じ語から母音が変わった）",
   hook:"band（ひも，バンド）も同じ家族。債券も「返すと約束で縛る証文」。",
   etymologyMore:["お金を返す約束で相手を縛る証文→債券"],
   relatedWords:[
     {word:"bind",meaning:"縛る，結びつける",breakdown:"bind（縛る）→ ひもでしっかりくくる"},
     {word:"bound",meaning:"縛られた；～する義務がある",breakdown:"bind（縛る）→ 縛られて離れられない"},
     {word:"band",meaning:"ひも，帯",breakdown:"bind（縛る）→ 物を縛りまとめるひも"},
     {word:"bundle",meaning:"束",breakdown:"bind（縛る）→ 縛ってひとまとめにした包み"}]},

  {id:1889,word:"hospitality",partOfSpeech:"名詞",meaning:"手厚いもてなし，歓待",
   meanings:["名|手厚いもてなし，歓待","名|（ホテル・飲食などの）接客業"],
   pronunciation:"/ˌhɑːspɪˈtæləti/",part:189,
   example:"Thank you for your warm hospitality during our stay in Kyoto.",
   exampleJa:"京都に滞在している間の、温かく手厚いもてなしに感謝します。",
   example2:"My sister wants to work in the hospitality industry after college.",
   exampleJa2:"姉は大学を出たら、接客業の仕事に就きたいと思っている。",
   etymologyProcess:"hosp（客をもてなす）＋ ity（名詞）→ 客を心をこめて迎えることは…？",
   etymologyConclusion:"hosp（客をもてなす）＋ al（～の）＋ ity（名詞）→ 客を心をこめて迎え入れること＝手厚いもてなし",
   etymologyMore:["人をもてなすことを仕事にする→（ホテル・飲食などの）接客業"],
   relatedWords:[
     {word:"hospital",meaning:"病院",breakdown:"hosp（客をもてなす）＋ al（～の）→ 旅人を泊めた宿から、病人を世話する所へ"},
     {word:"host",meaning:"主催者，もてなす人",breakdown:"host（客をもてなす）→ 客を迎える側の人"},
     {word:"hotel",meaning:"ホテル",breakdown:"host（客をもてなす）→ 客を泊めてもてなす建物"},
     {synonym:true,word:"welcome",meaning:"歓迎",breakdown:"来た人を喜んで迎えること"}]},

  {id:1890,word:"certificate",partOfSpeech:"名詞",meaning:"証明書，免許状",
   meanings:["名|証明書，免許状","名|（課程の）修了証"],
   pronunciation:"/sərˈtɪfɪkət/",part:189,
   example:"You will receive a certificate after finishing the English course.",
   exampleJa:"英語講座を終えると、証明書がもらえる。",
   example2:"Please bring your birth certificate to the city office.",
   exampleJa2:"出生証明書を市役所に持ってきてください。",
   etymologyProcess:"cert（ふるい分ける）＋ fic（作る）→ 確かだと見分けて作った紙は…？",
   etymologyConclusion:"cert（ふるい分ける）＋ fic（作る）＋ ate（名詞）→ 確かだと見分けて作った書類＝証明書",
   relatedWords:[
     {word:"certain",meaning:"確かな",breakdown:"cert（ふるい分ける）→ ふるいにかけて確かだと決まった"},
     {word:"certainly",meaning:"確かに",breakdown:"cert（ふるい分ける）＋ ly（～に）→ ふるい分けたように間違いなく"},
     {word:"certify",meaning:"証明する",breakdown:"cert（ふるい分ける）＋ ify（する）→ 確かだと認める"},
     {word:"factory",meaning:"工場",breakdown:"fic（作る）＋ ory（場所）→ 物を作る場所"}]},

  {id:1891,word:"brochure",partOfSpeech:"名詞",meaning:"（案内用の）パンフレット，小冊子",
   meanings:["名|（案内用の）パンフレット，小冊子"],
   pronunciation:"/broʊˈʃʊr/",part:190,
   example:"I picked up a travel brochure about Okinawa at the station.",
   exampleJa:"駅で、沖縄の旅行パンフレットをもらった。",
   example2:"The university will send a brochure to every student who asks.",
   exampleJa2:"その大学は、希望する生徒全員に案内の小冊子を送ってくれる。",
   etymologyProcess:"broch（針で縫う）→ 数枚の紙を針でさっと縫いとめると…？",
   etymologyConclusion:"broch（針で縫う）→ 数枚の紙を針でさっと縫いとめた薄い冊子＝（案内用の）パンフレット",
   hook:"フランス語の「針で縫いとじる」から。胸に留めるブローチ（brooch）も同じ「針」の仲間。",
   relatedWords:[
     {word:"brooch",meaning:"ブローチ",breakdown:"broch（針で縫う）→ 針で服に留める飾り"},
     {synonym:true,word:"pamphlet",meaning:"パンフレット",breakdown:"とじた薄い冊子。brochure は宣伝や案内用が多い"},
     {synonym:true,word:"leaflet",meaning:"ちらし",breakdown:"1枚か折りたたんだだけの紙"},
     {synonym:true,word:"catalog",meaning:"カタログ",breakdown:"商品を一覧にした冊子"}]},

  {id:1892,word:"outlet",partOfSpeech:"名詞",meaning:"（電気の）コンセント；はけ口；直販店",
   meanings:["名|（電気の）コンセント","名|（感情などの）はけ口","名|直販店，アウトレット"],
   pronunciation:"/ˈaʊtlet/",part:190,
   example:"Is there an outlet near the desk where I can charge my phone?",
   exampleJa:"机の近くに、スマホを充電できるコンセントはありますか。",
   example2:"Sports can be a good outlet for stress.",
   exampleJa2:"スポーツはストレスのよいはけ口になりうる。",
   etymologyProcess:"out（外へ）＋ let（出させる）→ 中のものを外へ出させる口は…？",
   etymologyConclusion:"out（外へ）＋ let（出させる）→ 壁の中の電気を外へ取り出す口＝（電気の）コンセント",
   etymologyMore:["たまった気持ちを外へ出させる口→（感情などの）はけ口","工場の品を直接外へ出して売る→直販店，アウトレット"],
   relatedWords:[
     {word:"outside",meaning:"外側",breakdown:"out（外へ）＋ side（横）→ 外の側"},
     {word:"output",meaning:"出力，生産高",breakdown:"out（外へ）＋ put（置く）→ 外へ出したもの"},
     {word:"outcome",meaning:"結果",breakdown:"out（外へ）＋ come（来る）→ 外に出てきたもの"},
     {word:"let",meaning:"～させる",breakdown:"let（出させる）→ 行かせる、させてやる"}]},

  {id:1893,word:"accommodation",partOfSpeech:"名詞",meaning:"宿泊施設，泊まる所",
   meanings:["名|宿泊施設，泊まる所","名|（意見などの）調整，歩み寄り"],
   pronunciation:"/əˌkɑːməˈdeɪʃən/",part:190,
   example:"The price of the tour includes meals and accommodation.",
   exampleJa:"そのツアーの料金には、食事と宿泊施設が含まれている。",
   example2:"We need to find accommodation for thirty club members.",
   exampleJa2:"部員30人分の泊まる所を見つける必要がある。",
   etymologyProcess:"ad（～へ）＋ com（共に）＋ modus（ほどよさ）→ 相手にほどよく合わせると…？",
   etymologyConclusion:"ad（～へ）＋ com（共に）＋ modus（ほどよさ）＋ ation（名詞）→ 旅人に合わせて整えた部屋＝宿泊施設",
   why:"【なぜ】accommodate は ad（～へ）＋ com（共に）＋ modus（ほどよさ）で「相手にぴったり合うようにする」。旅人の必要に合わせて部屋や食事を整えることから「泊める」となり、名詞の accommodation が「宿泊施設」を指すようになりました。\n【つながり】modest（控えめな）、moderate（ほどよい）も modus の仲間です。",
   spelling:"ad→ac（c の前で同化）、modus→mod（語尾が落ちた）",
   relatedWords:[
     {word:"accommodate",meaning:"収容する，泊める",breakdown:"ad（～へ）＋ com（共に）＋ modus（ほどよさ）→ 相手に合わせて受け入れる"},
     {word:"modest",meaning:"控えめな",breakdown:"modus（ほどよさ）→ ほどよさを守り、出しゃばらない"},
     {word:"model",meaning:"模型，手本",breakdown:"modul（小さなます）→ 形を小さく写した型"},
     {synonym:true,word:"hotel",meaning:"ホテル",breakdown:"泊まる建物の代表。accommodation は宿全般"}]},

  {id:1894,word:"haven",partOfSpeech:"名詞",meaning:"（安全な）隠れ場所，安息の地",
   meanings:["名|（安全な）隠れ場所，安息の地","名|（文語で）港"],
   pronunciation:"/ˈheɪvən/",part:190,
   example:"The library was a quiet haven for students during the exams.",
   exampleJa:"試験の間、図書館は生徒にとって静かな安息の地だった。",
   example2:"This small island is a safe haven for many rare birds.",
   exampleJa2:"この小さな島は、多くの珍しい鳥にとって安全な隠れ場所だ。",
   etymologyProcess:"haven（港）→ 嵐を避けて船が逃げこむ場所は…？",
   etymologyConclusion:"haven（港）→ 嵐を避けて船が逃げこむ港のように、危険から守られる場所＝（安全な）隠れ場所",
   hook:"もとは古英語で「港」。heaven（天国）とは別の語。tax haven は税金の「逃げ場」。",
   relatedWords:[
     {synonym:true,word:"harbor",meaning:"港",breakdown:"船が安全に停まる港。haven はたとえで使うことが多い"},
     {synonym:true,word:"shelter",meaning:"避難所",breakdown:"雨風や危険をしのぐ場所"},
     {synonym:true,word:"refuge",meaning:"避難，逃げ場",breakdown:"re（後ろへ）＋ fug（逃げる）。追われて逃げこむ所"},
     {synonym:true,word:"port",meaning:"港",breakdown:"船が出入りする港町。haven より一般的"}]},

  {id:1895,word:"venue",partOfSpeech:"名詞",meaning:"（催しの）会場，開催地",
   meanings:["名|（催しの）会場，開催地"],
   pronunciation:"/ˈvenjuː/",part:190,
   example:"The venue for the concert was changed because of the storm.",
   exampleJa:"嵐のため、コンサートの会場が変更された。",
   example2:"Our school gym will be the venue for the speech contest.",
   exampleJa2:"学校の体育館が、スピーチコンテストの会場になる。",
   etymologyProcess:"ven（来る）＋ ue（もの）→ 人々がやって来る場所は…？",
   etymologyConclusion:"ven（来る）＋ ue（もの）→ 催しのために人々がやって来る場所＝（催しの）会場",
   relatedWords:[
     {word:"event",meaning:"出来事，行事",breakdown:"ex（外へ）＋ vent（来る）→ 外に出てきたこと"},
     {word:"adventure",meaning:"冒険",breakdown:"ad（～へ）＋ vent（来る）＋ ure（もの）→ 身にふりかかってくること"},
     {word:"convenient",meaning:"便利な",breakdown:"con（共に）＋ ven（来る）→ 必要なときにうまくやって来る"},
     {word:"souvenir",meaning:"おみやげ",breakdown:"sub（下で）＋ ven（来る）→ 心の下から思い出がやって来るもの"}]},

  {id:1896,word:"intersection",partOfSpeech:"名詞",meaning:"交差点",
   meanings:["名|交差点","名|（線の）交わり，交点"],
   pronunciation:"/ˌɪntərˈsekʃən/",part:190,
   example:"Turn left at the next intersection and you'll see the station.",
   exampleJa:"次の交差点を左に曲がると、駅が見えます。",
   example2:"There is always heavy traffic at this busy intersection.",
   exampleJa2:"このにぎやかな交差点は、いつも交通量が多い。",
   etymologyProcess:"inter（間の）＋ sect（切る）→ 道と道が互いを切り合う所は…？",
   etymologyConclusion:"inter（間の）＋ sect（切る）＋ ion（名詞）→ 道と道が互いを横切って交わる所＝交差点",
   relatedWords:[
     {word:"section",meaning:"部分，区域",breakdown:"sect（切る）＋ ion（名詞）→ 切り分けた一部"},
     {word:"insect",meaning:"昆虫",breakdown:"in（中へ）＋ sect（切る）→ 体に切れこみがある生き物"},
     {word:"international",meaning:"国際的な",breakdown:"inter（間の）＋ nat（生まれる）→ 国と国の間の"},
     {synonym:true,word:"crossroads",meaning:"十字路",breakdown:"2本の道が十字に交わる所"}]},

  {id:1897,word:"pavement",partOfSpeech:"名詞",meaning:"（英）歩道；舗装した道",
   meanings:["名|（英）歩道","名|（米）舗装道路，舗装面"],
   pronunciation:"/ˈpeɪvmənt/",part:190,
   example:"Please walk on the pavement, not in the road.",
   exampleJa:"車道ではなく、歩道を歩いてください。",
   example2:"The hot summer sun made the pavement too hot to touch.",
   exampleJa2:"夏の強い日ざしで、舗装道路は触れないほど熱くなった。",
   etymologyProcess:"pav（たたき固める）＋ ment（名詞）→ 地面をたたき固めた道は…？",
   etymologyConclusion:"pav（たたき固める）＋ ment（名詞）→ 地面をたたき固めて歩きやすくした道＝（英）歩道",
   etymologyMore:["たたき固めた道の表面全体→（米）舗装道路，舗装面"],
   relatedWords:[
     {word:"pave",meaning:"舗装する",breakdown:"pav（たたき固める）→ 道をたたき固めて平らにする"},
     {synonym:true,word:"sidewalk",meaning:"（米）歩道",breakdown:"道のわき（side）の歩く所。アメリカ英語"},
     {synonym:true,word:"road",meaning:"道路",breakdown:"車も人も通る道全般"},
     {synonym:true,word:"path",meaning:"小道",breakdown:"人が歩いてできた細い道"}]},

  {id:1898,word:"pedestrian",partOfSpeech:"名詞",meaning:"歩行者",
   meanings:["名|歩行者","形|歩行者用の"],
   pronunciation:"/pəˈdestriən/",part:190,
   example:"This street is only for pedestrians on Sundays.",
   exampleJa:"この通りは、日曜日は歩行者専用だ。",
   example2:"Drivers must stop for pedestrians at a crosswalk.",
   exampleJa2:"運転手は横断歩道で歩行者のために止まらなければならない。",
   etymologyProcess:"pedi（足）＋ ian（人）→ 乗り物に乗らず足で行く人は…？",
   etymologyConclusion:"pedi（足）＋ ian（人）→ 乗り物に乗らず、自分の足で進む人＝歩行者",
   spelling:"pedi→ped（ラテン語 pes の語幹）",
   relatedWords:[
     {word:"pedal",meaning:"ペダル",breakdown:"pedi（足）＋ al（～の）→ 足でふむ部分"},
     {word:"expedition",meaning:"遠征，探検",breakdown:"ex（外へ）＋ pedi（足）→ 足を外へ踏み出す長い旅"},
     {synonym:true,word:"walker",meaning:"歩く人",breakdown:"walk（歩く）する人。pedestrian は交通の場面の硬い語"},
     {synonym:true,word:"passer-by",meaning:"通行人",breakdown:"たまたま通る人。pedestrian は車でなく歩く人"}]},

  {id:1899,word:"excursion",partOfSpeech:"名詞",meaning:"（団体の）小旅行，遠足",
   meanings:["名|（団体の）小旅行，遠足"],
   pronunciation:"/ɪkˈskɜːrʒən/",part:190,
   example:"Our class went on an excursion to the science museum.",
   exampleJa:"私たちのクラスは、科学館への小旅行に出かけた。",
   example2:"Boat excursions to the island are popular with tourists in summer.",
   exampleJa2:"島への船の小旅行は、夏に観光客に人気がある。",
   etymologyProcess:"ex（外へ）＋ curr（走る）→ いつもの場所から外へ走り出ると…？",
   etymologyConclusion:"ex（外へ）＋ curr（走る）＋ ion（名詞）→ いつもの場所から外へ短く出かけること＝（団体の）小旅行",
   spelling:"curr→curs（「走った」の形 cursus から）",
   relatedWords:[
     {word:"current",meaning:"今の；流れ",breakdown:"curr（走る）＋ ent（～している）→ 今まさに走っている"},
     {word:"course",meaning:"進路，講座",breakdown:"cours（走る）→ 走っていく道すじ"},
     {word:"occur",meaning:"起こる",breakdown:"op（向かい合って）＋ curr（走る）→ 向こうから走ってくる"},
     {synonym:true,word:"trip",meaning:"旅行",breakdown:"短い旅行全般。excursion は団体で出かけることが多い"}]},

  {id:1900,word:"shipping",partOfSpeech:"名詞",meaning:"（荷物の）発送，配送；海運",
   meanings:["名|（荷物の）発送，配送","名|送料","名|海運（業）"],
   pronunciation:"/ˈʃɪpɪŋ/",part:190,
   example:"Shipping is free if you spend more than 3,000 yen.",
   exampleJa:"3,000円より多く買えば、発送は無料になる。",
   example2:"A lot of shipping between Asia and Europe passes through the Suez Canal.",
   exampleJa2:"アジアとヨーロッパの間の海運の多くは、スエズ運河を通る。",
   etymologyProcess:"scip（船）＋ ing（名詞）→ 荷物を船に積んで送り出すことは…？",
   etymologyConclusion:"scip（船）＋ ing（名詞）→ 荷物を船に積んで送り出すこと＝（荷物の）発送",
   why:"【なぜ】ship は名詞なら「船」ですが、動詞では「船で送る」。昔の遠い国への荷物はほとんど船で運ばれたため、やがてトラックや飛行機で送る場合も ship と言うようになり、shipping が「発送，配送」全般を指すようになりました。\n【つながり】ネット通販の free shipping は「送料無料」。船を使う本来の意味は「海運（業）」に残っています。",
   spelling:"scip→ship（古英語の綴りから変化）",
   relatedWords:[
     {word:"ship",meaning:"船；発送する",breakdown:"scip（船）→ 船、そして船で荷を送る"},
     {word:"shipment",meaning:"発送；積み荷",breakdown:"scip（船）＋ ment（名詞）→ 送り出された荷物"},
     {synonym:true,word:"delivery",meaning:"配達",breakdown:"届け先まで持っていくこと"},
     {synonym:true,word:"transport",meaning:"輸送",breakdown:"trans（越えて）＋ port（運ぶ）。物を運ぶこと全般"}]},
