  {id:2051,word:"dictate",partOfSpeech:"他動詞",meaning:"口述して書き取らせる；（条件などを）指図する",
   meanings:["他|口述して書き取らせる","他|（条件などを）指図する，命令する","他|（物事を）左右する，決定づける"],
   pronunciation:"/ˈdɪkteɪt/",part:206,
   example:"The teacher dictated ten English sentences to the class slowly.",
   exampleJa:"先生はクラスに英文を10個、ゆっくり口述して書き取らせた。",
   example2:"Nobody should dictate what you wear on weekends.",
   exampleJa2:"週末に何を着るかを、誰かに指図されるいわれはない。",
   usage:["dictate to 人（人に口述する；人に指図する）"],
   etymologyProcess:"dict（言う）＋ ate（動詞）→ 言った言葉を相手に書かせると…？",
   etymologyConclusion:"dict（言う）＋ ate（動詞）→ 言った言葉をそのまま相手に書き取らせる＝口述して書き取らせる",
   etymologyMore:["言ったとおりに相手を従わせる→（条件などを）指図する，命令する"],
   relatedWords:[
     {word:"dictionary",meaning:"辞書",breakdown:"dict（言う）＋ ary（場所）→ 言葉を集めて並べた本"},
     {word:"predict",meaning:"予言する",breakdown:"pre（先に）＋ dict（言う）→ 起こる前に言っておく"},
     {word:"contradict",meaning:"矛盾する；反論する",breakdown:"contra（逆に）＋ dict（言う）→ 逆のことを言う"},
     {word:"dictator",meaning:"独裁者",breakdown:"dict（言う）＋ ator（人）→ 言ったことを皆に従わせる人"}]},

  {id:2052,word:"provoke",partOfSpeech:"他動詞",meaning:"（怒り・反応を）引き起こす；挑発する",
   meanings:["他|（怒り・反応を）引き起こす","他|（人を）怒らせる，挑発する"],
   pronunciation:"/prəˈvoʊk/",part:206,
   example:"His rude comment provoked anger among the other students.",
   exampleJa:"彼の失礼な発言は、ほかの生徒たちの怒りを引き起こした。",
   example2:"Don't let him provoke you into a fight at practice.",
   exampleJa2:"練習中に彼に挑発されて、けんかをしてはいけない。",
   usage:["provoke 人 into doing（人を挑発して～させる）"],
   etymologyProcess:"pro（前へ）＋ voc（呼ぶ）→ 相手の気持ちを表へ呼び出すと…？",
   etymologyConclusion:"pro（前へ）＋ voc（呼ぶ）→ 心の中の怒りや反応を表へ呼び出す＝（怒り・反応を）引き起こす",
   spelling:"voc→vok（c が k の綴りに変わった）",
   etymologyMore:["相手を呼び出して挑む→（人を）怒らせる，挑発する"],
   relatedWords:[
     {word:"voice",meaning:"声",breakdown:"voc（呼ぶ）→ 人を呼ぶときに出すもの"},
     {word:"vocabulary",meaning:"語彙",breakdown:"voc（呼ぶ）＋ ary（集まり）→ ものを呼ぶ名前の集まり"},
     {word:"vocal",meaning:"声の；ボーカル",breakdown:"voc（呼ぶ）＋ al（形容詞）→ 声を出して歌う"},
     {word:"evoke",meaning:"呼び起こす",breakdown:"e（外へ）＋ voc（呼ぶ）→ 心の奥から外へ呼び出す"}]},

  {id:2053,word:"refine",partOfSpeech:"他動詞",meaning:"（技術・考えを）洗練させる，磨きをかける；精製する",
   meanings:["他|（技術・考えを）洗練させる，磨きをかける","他|（石油・砂糖などを）精製する"],
   pronunciation:"/rɪˈfaɪn/",part:206,
   example:"She spent months refining her speech for the contest.",
   exampleJa:"彼女はコンテストに向けて、何か月もかけてスピーチを洗練させた。",
   example2:"Crude oil is refined into gasoline at this plant.",
   exampleJa2:"この工場で、原油はガソリンに精製される。",
   etymologyProcess:"re（再び）＋ fin（終わり）→ 最後の仕上げをくり返すと…？",
   etymologyConclusion:"re（再び）＋ fin（終わり）→ 仕上げを何度もやり直して粗い部分をなくす＝（技術・考えを）洗練させる",
   why:"【なぜ】fin（終わり）から生まれた fine は、もとは「最後まで仕上げた」＝混じりけのない、という意味でした。refine は「もう一度仕上げ直して純粋にする」ことで、金属や砂糖の精製がもとの使い方です。そこから、技術や文章の粗い部分を取り除いて磨き上げる意味に広がりました。\n【つながり】精製所は refinery。fine（見事な・細かい）も同じ「仕上がった」イメージです。",
   relatedWords:[
     {word:"finish",meaning:"終える",breakdown:"fin（終わり）＋ ish（動詞）→ 終わりまでやり切る"},
     {word:"final",meaning:"最後の",breakdown:"fin（終わり）＋ al（形容詞）→ いちばん終わりの"},
     {word:"fine",meaning:"見事な；細かい",breakdown:"fin（終わり）→ 最後まで仕上げて混じりけがない"},
     {word:"define",meaning:"定義する",breakdown:"de（すっかり）＋ fin（終わり）→ 意味の境目をはっきり決める"}]},

  {id:2054,word:"enlighten",partOfSpeech:"他動詞",meaning:"（人を）啓発する，教え導く",
   meanings:["他|（人を）啓発する，教え導く","他|（about ～について）（人に）はっきり教える"],
   pronunciation:"/ɪnˈlaɪtn/",part:206,
   example:"The museum tour enlightened us about daily life in ancient Egypt.",
   exampleJa:"博物館の見学で、私たちは古代エジプトの日々の暮らしについて啓発された。",
   example2:"Reading good books can enlighten young people in many ways.",
   exampleJa2:"良い本を読むことは、さまざまな面で若者を啓発しうる。",
   etymologyProcess:"en（～にする）＋ lighten（照らす）→ 心の中を照らすと…？",
   etymologyConclusion:"en（～にする）＋ lighten（照らす）→ 心を照らして物事が見えるようにする＝（人を）啓発する",
   relatedWords:[
     {word:"lighten",meaning:"明るくする",breakdown:"lighten（照らす）→ 暗い所に光を当てて明るくする"},
     {word:"lightning",meaning:"稲妻",breakdown:"lighten（照らす）＋ ing（名詞）→ 空を一瞬で照らすもの"},
     {synonym:true,word:"light",meaning:"光；明かり",breakdown:"lighten のもとになった語。「軽い」の light とは別の語"},
     {word:"enlightenment",meaning:"啓発；悟り",breakdown:"en（～にする）＋ lighten（照らす）＋ ment（名詞）→ 心が照らされること"}]},

  {id:2055,word:"unleash",partOfSpeech:"他動詞",meaning:"（抑えていた力・感情を）解き放つ，爆発させる",
   meanings:["他|（抑えていた力・感情を）解き放つ，爆発させる","他|（犬を）引きひもから放す"],
   pronunciation:"/ʌnˈliːʃ/",part:206,
   example:"The storm unleashed its full power on the small island.",
   exampleJa:"嵐は小さな島の上で、ためこんだ力をすべて解き放った。",
   example2:"A wave of energy was unleashed in our team by the coach's speech.",
   exampleJa2:"コーチの話によって、チームのやる気が一気に解き放たれた。",
   etymologyProcess:"un（取り去る）＋ leash（引きひも）→ 犬のひもを外すと…？",
   etymologyConclusion:"un（取り去る）＋ leash（引きひも）→ ひもを外した犬のように、抑えていた力を一気に放つ＝（抑えていた力・感情を）解き放つ",
   relatedWords:[
     {word:"leash",meaning:"（犬の）引きひも",breakdown:"leash（引きひも）→ 犬が走り出さないようにつなぐひも"},
     {word:"unlock",meaning:"鍵を開ける",breakdown:"un（取り去る）＋ lock（鍵）→ かかっている鍵を外す"},
     {word:"unfold",meaning:"広げる",breakdown:"un（取り去る）＋ fold（重ねる）→ 重ねた折り目を取り去って開く"},
     {synonym:true,word:"release",meaning:"解放する",breakdown:"leash と同じくラテン語 laxus（ゆるい）の家族。つかんだ手をゆるめて放す"}]},

  {id:2056,word:"prolong",partOfSpeech:"他動詞",meaning:"（期間を）延ばす，長引かせる",
   meanings:["他|（期間を）延ばす，長引かせる"],
   pronunciation:"/prəˈlɔːŋ/",part:206,
   example:"They decided to prolong their stay in Kyoto by two days.",
   exampleJa:"彼らは京都での滞在を2日延ばすことにした。",
   example2:"The meeting was prolonged by a long argument about the budget.",
   exampleJa2:"予算をめぐる長い議論のせいで、会議が長引いた。",
   etymologyProcess:"pro（前へ）＋ long（沿って続く）→ 先のほうへ長くすると…？",
   etymologyConclusion:"pro（前へ）＋ long（沿って続く）→ 終わりの時点を先のほうへ長く伸ばす＝（期間を）延ばす",
   relatedWords:[
     {word:"long",meaning:"長い",breakdown:"long（沿って続く）→ 端から端までずっと続いている"},
     {word:"length",meaning:"長さ",breakdown:"long（沿って続く）＋ th（名詞）→ どこまで続くかの量"},
     {word:"belong",meaning:"属する",breakdown:"be（すっかり）＋ long（沿って続く）→ ある所にずっと沿っている"},
     {synonym:true,word:"extend",meaning:"延長する",breakdown:"ex（外へ）＋ tend（伸ばす）。長さ・範囲にも使う。prolong は時間が中心"}]},

  {id:2057,word:"mitigate",partOfSpeech:"他動詞",meaning:"（被害・影響を）緩和する，軽くする",
   meanings:["他|（被害・影響を）緩和する，軽くする"],
   pronunciation:"/ˈmɪtɪɡeɪt/",part:206,
   example:"Planting trees can help mitigate the effects of floods.",
   exampleJa:"木を植えることは、洪水の影響を緩和するのに役立ちうる。",
   example2:"The new rules were introduced to mitigate stress among students.",
   exampleJa2:"生徒たちのストレスを軽くするため、新しい規則が導入された。",
   etymologyProcess:"miti（やわらかい）＋ ig（行う）→ 固く激しいものをやわらかくすると…？",
   etymologyConclusion:"miti（やわらかい）＋ ig（行う）＋ ate（動詞）→ 激しいものをやわらかくして害を小さくする＝（被害・影響を）緩和する",
   spelling:"ag→ig（語の中で母音が弱まった）",
   relatedWords:[
     {word:"navigate",meaning:"航行する；道案内する",breakdown:"navi（船）＋ ig（行う）＋ ate（動詞）→ 船を動かして進める"},
     {word:"agent",meaning:"代理人",breakdown:"ag（行う）＋ ent（人）→ 人に代わって物事を行う"},
     {word:"act",meaning:"行動する",breakdown:"act（行う）→ 実際に何かをする"},
     {synonym:true,word:"relieve",meaning:"和らげる",breakdown:"苦痛や不安を軽くする。mitigate は被害や悪影響を小さくする"}]},

  {id:2058,word:"grind",partOfSpeech:"他動詞",meaning:"（穀物・豆を）挽く，すりつぶす",
   meanings:["他|（穀物・豆を）挽く，すりつぶす","他|（刃物を）研ぐ","他|（歯を）きしらせる"],
   pronunciation:"/ɡraɪnd/",part:206,
   example:"My father grinds fresh coffee beans every morning before work.",
   exampleJa:"父は毎朝仕事の前に、新鮮なコーヒー豆を挽く。",
   example2:"Some people grind their teeth while they are asleep.",
   exampleJa2:"眠っている間に歯をきしらせる人もいる。",
   etymologyProcess:"grind（すりつぶす）→ 石臼をゴリゴリ回すと…？",
   etymologyConclusion:"grind（すりつぶす）→ 石臼で穀物を粉になるまで細かくする＝（穀物・豆を）挽く",
   hook:"コーヒーの「グラインダー」は豆を挽く道具。過去形・過去分詞は ground になる。",
   etymologyMore:["刃を砥石にこすりつける→（刃物を）研ぐ","上下の歯をすり合わせる→（歯を）きしらせる"],
   relatedWords:[
     {word:"grinder",meaning:"粉砕機，グラインダー",breakdown:"grind（すりつぶす）＋ er（道具）→ 豆や肉を細かくする道具"},
     {synonym:true,word:"crush",meaning:"押しつぶす",breakdown:"強い力で一気につぶす。grind はこすって細かくする"},
     {synonym:true,word:"mill",meaning:"（ひき臼で）ひく",breakdown:"水車や臼で粉にする。grind は手でこすってすりつぶす場合も"},
     {synonym:true,word:"sharpen",meaning:"鋭くする，研ぐ",breakdown:"刃やえんぴつをとがらせる。grind は砥石でこする研ぎ方"}]},

  {id:2059,word:"withstand",partOfSpeech:"他動詞",meaning:"（外からの力に）屈せず耐える，持ちこたえる",
   meanings:["他|（外からの力に）屈せず耐える，持ちこたえる"],
   pronunciation:"/wɪðˈstænd/",part:206,
   example:"This building is designed to withstand very strong earthquakes.",
   exampleJa:"この建物は、非常に強い地震に屈せず耐えるよう設計されている。",
   example2:"Our team withstood the pressure and won in the final minute.",
   exampleJa2:"私たちのチームは重圧に持ちこたえ、最後の1分で勝った。",
   etymologyProcess:"with（逆らって）＋ stand（立つ）→ 押してくる力に逆らって立つと…？",
   etymologyConclusion:"with（逆らって）＋ stand（立つ）→ 押し寄せる力に逆らって倒れずに立ち続ける＝（外からの力に）屈せず耐える",
   relatedWords:[
     {word:"stand",meaning:"立つ；我慢する",breakdown:"stand（立つ）→ その場に足をつけて立っている"},
     {word:"understand",meaning:"理解する",breakdown:"under（下に）＋ stand（立つ）→ 物事の下に立って根っこまで見る"},
     {word:"outstanding",meaning:"目立った，傑出した",breakdown:"out（外へ）＋ stand（立つ）＋ ing（形容詞）→ 周りより外に立ち出ている"},
     {word:"withdraw",meaning:"引き出す；撤退する",breakdown:"with（後ろへ）＋ draw（引っぱる）→ 後ろへ引っぱり戻す"}]},

  {id:2060,word:"exert",partOfSpeech:"他動詞",meaning:"（力・影響力を）及ぼす，働かせる",
   meanings:["他|（力・影響力を）及ぼす，働かせる","他|（exert oneself）懸命に努力する，無理をする"],
   pronunciation:"/ɪɡˈzɜːrt/",part:206,
   example:"Parents exert a strong influence on their children's values.",
   exampleJa:"親は子どもの価値観に強い影響力を及ぼす。",
   example2:"You should not exert yourself too much right after an injury.",
   exampleJa2:"けがをした直後は、あまり無理をしないほうがいい。",
   usage:["exert influence on 人（人に影響を及ぼす）","exert oneself（懸命に努力する）"],
   etymologyProcess:"ex（外へ）＋ ser（つなぐ）→ 内につないでいたものを外へ出すと…？",
   etymologyConclusion:"ex（外へ）＋ ser（つなぐ）→ 内にためた力を外へ押し出して相手に届かせる＝（力・影響力を）及ぼす",
   spelling:"ser→ert（x のあとで s が消えた）",
   why:"【なぜ】ラテン語 exserere は、もとは「つながれていたものを外へ出す」、つまり腕などを突き出すことでした。体の内にある力を外へ押し出すイメージから、力や影響力を「働かせる・及ぼす」意味になりました。自分の力を出し切ることから exert oneself（懸命に努力する）も生まれました。\n【つながり】series（つながり）や insert（差しこむ）が同じ「つなぐ」の仲間です。",
   relatedWords:[
     {word:"series",meaning:"連続，シリーズ",breakdown:"ser（つなぐ）＋ ies（名詞）→ 次々につながって並ぶもの"},
     {word:"insert",meaning:"差しこむ",breakdown:"in（中へ）＋ ser（つなぐ）→ 中へ入れてつなぎ合わせる"},
     {word:"desert",meaning:"見捨てる",breakdown:"de（離れて）＋ ser（つなぐ）→ つながりを切って離れる"},
     {synonym:true,word:"apply",meaning:"（力などを）加える",breakdown:"物に当てて力を加える。exert は内の力を外へ出して及ぼす"}]},

  {id:2061,word:"summon",partOfSpeech:"他動詞",meaning:"（人を）呼び出す，召喚する",
   meanings:["他|（人を）呼び出す，召喚する","他|（summon up）（勇気・力を）奮い起こす"],
   pronunciation:"/ˈsʌmən/",part:207,
   example:"The principal summoned the three students to his office.",
   exampleJa:"校長はその3人の生徒を校長室に呼び出した。",
   example2:"She summoned up the courage to speak in front of everyone.",
   exampleJa2:"彼女は勇気を奮い起こして、みんなの前で話した。",
   usage:["summon 人 to 場所（人を場所に呼び出す）","summon up 勇気（勇気を奮い起こす）"],
   etymologyProcess:"sub（下で）＋ mon（思い出させる）→ そっと注意をうながして来させると…？",
   etymologyConclusion:"sub（下で）＋ mon（思い出させる）→ そっと知らせて、その人を自分のもとへ来させる＝（人を）呼び出す",
   spelling:"sub→sum（b が m に変わった）",
   why:"【なぜ】ラテン語 summonere は sub（下で）＋ monere（思い出させる・注意する）で、「そっと注意をうながす」という意味でした。中世には、裁判所が人に「出頭せよ」と知らせることを指すようになり、そこから人を呼び出す・召喚する意味が中心になりました。\n【つながり】monitor（注意して見張る）や monument（思い出させる記念碑）が同じ仲間です。",
   etymologyMore:["心の奥から力を呼び出す→（勇気・力を）奮い起こす"],
   relatedWords:[
     {word:"monitor",meaning:"監視する；モニター",breakdown:"mon（思い出させる）＋ or（もの）→ 注意をうながし見張る装置"},
     {word:"monument",meaning:"記念碑",breakdown:"mon（思い出させる）＋ ment（名詞）→ 出来事を思い出させる石碑"},
     {synonym:true,word:"call",meaning:"呼ぶ",breakdown:"ふつうの「呼ぶ」。summon は立場が上の人が正式に呼びつける"},
     {synonym:true,word:"invite",meaning:"招待する",breakdown:"来てほしいと誘う。summon は来ることを求める"}]},

  {id:2062,word:"thrust",partOfSpeech:"他動詞",meaning:"（ぐいと）強く押しつける，突っこむ",
   meanings:["他|（ぐいと）強く押しつける，突っこむ","名|（the ～）要点，核心","名|推進力"],
   pronunciation:"/θrʌst/",part:207,
   example:"He thrust the letter into my hand and ran away.",
   exampleJa:"彼はその手紙を私の手にぐいと押しつけて走り去った。",
   example2:"The main thrust of his speech was about climate change.",
   exampleJa2:"彼のスピーチの要点は、気候変動についてだった。",
   etymologyProcess:"thrust（ぐいと押す）→ 力をこめて相手のほうへ押し出すと…？",
   etymologyConclusion:"thrust（ぐいと押す）→ 力をこめて物を相手や中へぐいと押し出す＝（ぐいと）強く押しつける",
   hook:"ロケットの「推力（スラスト）」も thrust。過去形・過去分詞も thrust のまま。",
   etymologyMore:["話をぐいと前へ押し出す中心→要点，核心","機体を前へ押し出す力→推進力"],
   relatedWords:[
     {synonym:true,word:"push",meaning:"押す",breakdown:"ふつうの「押す」。thrust は急に強く突き出す"},
     {synonym:true,word:"press",meaning:"押しつける",breakdown:"じわっと力をかけ続ける。thrust は一気に突く"},
     {synonym:true,word:"shove",meaning:"乱暴に押す",breakdown:"人や物を押しのける。thrust は前へ突き出す"},
     {synonym:true,word:"poke",meaning:"つつく",breakdown:"指や棒で軽く突く。thrust は力いっぱい"}]},

  {id:2063,word:"pierce",partOfSpeech:"他動詞",meaning:"突き刺す，突き通す",
   meanings:["他|突き刺す，突き通す","他|（光・音が）貫く"],
   pronunciation:"/pɪrs/",part:207,
   example:"A sharp nail pierced the back tire of my bicycle.",
   exampleJa:"鋭い釘が、私の自転車の後ろのタイヤに突き刺さった。",
   example2:"A loud scream pierced the silence of the night.",
   exampleJa2:"大きな悲鳴が、夜の静けさを貫いた。",
   etymologyProcess:"pierce（突き通す）→ とがった先で表面を破ると…？",
   etymologyConclusion:"pierce（突き通す）→ とがった先で表面を破り、向こう側まで通す＝突き刺す",
   hook:"耳たぶに穴を通す「ピアス」はこの語から。光や音が闇や静けさを貫くときにも使う。",
   etymologyMore:["闇や静けさを突き抜けて届く→（光・音が）貫く"],
   relatedWords:[
     {synonym:true,word:"hole",meaning:"穴",breakdown:"pierce したあとにあく穴"},
     {synonym:true,word:"needle",meaning:"針",breakdown:"布を pierce して糸を通す道具"},
     {synonym:true,word:"stab",meaning:"（刃物で）刺す",breakdown:"ナイフなどで刺す。pierce は向こうまで突き通す"},
     {synonym:true,word:"penetrate",meaning:"貫通する，入りこむ",breakdown:"奥まで入りこむ。pierce は先で穴をあける"}]},

  {id:2064,word:"harness",partOfSpeech:"他動詞",meaning:"（自然の力などを）役立つように利用する",
   meanings:["他|（自然の力などを）役立つように利用する","名|（馬の）引き具，ハーネス"],
   pronunciation:"/ˈhɑːrnɪs/",part:207,
   example:"This village harnesses wind power to produce its own electricity.",
   exampleJa:"この村は風の力を役立つように利用して、自分たちの電気を作っている。",
   example2:"The farmer put a harness on the horse before plowing.",
   exampleJa2:"農夫は畑を耕す前に、馬に引き具をつけた。",
   etymologyProcess:"harness（馬具）→ 馬に引き具をつけて働かせると…？",
   etymologyConclusion:"harness（馬具）→ 馬に引き具をつけて力を仕事に回すように、力を活かす＝（自然の力などを）役立つように利用する",
   hook:"登山の安全ベルトや犬の胴輪も「ハーネス」。つないで力を操るイメージ。",
   relatedWords:[
     {synonym:true,word:"use",meaning:"使う",breakdown:"ふつうの「使う」。harness は大きな力を手なずけて使う"},
     {synonym:true,word:"control",meaning:"制御する",breakdown:"思いどおりに動かす。harness は制御して役立てる"},
     {synonym:true,word:"utilize",meaning:"利用する，活用する",breakdown:"目的のために役立てる。harness は自然の力によく使う"},
     {synonym:true,word:"exploit",meaning:"（資源を）開発する",breakdown:"資源を最大限に使う。悪用の意味もある"}]},

  {id:2065,word:"excavate",partOfSpeech:"他動詞",meaning:"（遺跡などを）発掘する；（地面を）掘る",
   meanings:["他|（遺跡などを）発掘する","他|（地面・穴を）掘る"],
   pronunciation:"/ˈekskəveɪt/",part:207,
   example:"Archaeologists excavated an ancient village near the river last year.",
   exampleJa:"昨年、考古学者たちが川の近くで古代の村を発掘した。",
   example2:"Workers are excavating the ground for a new subway station.",
   exampleJa2:"作業員たちが、新しい地下鉄の駅のために地面を掘っている。",
   etymologyProcess:"ex（外へ）＋ cav（くぼみ）→ 土をかき出してくぼみを作ると…？",
   etymologyConclusion:"ex（外へ）＋ cav（くぼみ）＋ ate（動詞）→ 土をかき出して埋もれた物を掘り出す＝（遺跡などを）発掘する",
   relatedWords:[
     {word:"cave",meaning:"洞窟",breakdown:"cav（くぼみ）→ 岩の中にできた大きなくぼみ"},
     {word:"cavity",meaning:"空洞；虫歯の穴",breakdown:"cav（くぼみ）＋ ity（名詞）→ 中が空っぽになった所"},
     {word:"excavator",meaning:"掘削機，ショベルカー",breakdown:"ex（外へ）＋ cav（くぼみ）＋ ator（もの）→ 土をかき出す機械"},
     {synonym:true,word:"dig",meaning:"掘る",breakdown:"ふつうの「掘る」。excavate は大がかりに掘り出す"}]},

  {id:2066,word:"evade",partOfSpeech:"他動詞",meaning:"（義務・質問を）うまく逃れる，かわす",
   meanings:["他|（義務・質問を）うまく逃れる，かわす","他|（追っ手を）かわして逃げる"],
   pronunciation:"/ɪˈveɪd/",part:207,
   example:"The politician evaded every question about the missing money.",
   exampleJa:"その政治家は、消えたお金についての質問をすべてうまく逃れた。",
   example2:"The thief managed to evade the police for three weeks.",
   exampleJa2:"その泥棒は3週間、警察の手をかわして逃げ続けた。",
   etymologyProcess:"e（外へ）＋ vad（進む）→ 囲みの外へするりと進むと…？",
   etymologyConclusion:"e（外へ）＋ vad（進む）→ 迫ってくるものの外へするりと抜け出す＝（義務・質問を）うまく逃れる",
   relatedWords:[
     {word:"invade",meaning:"侵略する",breakdown:"in（中へ）＋ vad（進む）→ 他人の土地の中へ攻めて進む"},
     {word:"evasion",meaning:"回避，逃れること",breakdown:"e（外へ）＋ vad（進む）＋ ion（名詞）→ 外へすり抜けること"},
     {synonym:true,word:"avoid",meaning:"避ける",breakdown:"近づかないようにする。evade はずるく、うまくかわす"},
     {synonym:true,word:"escape",meaning:"逃げる",breakdown:"つかまった所から逃げ出す。evade はつかまる前にかわす"}]},

  {id:2067,word:"embody",partOfSpeech:"他動詞",meaning:"（考えなどを）具体化する，体現する",
   meanings:["他|（考えなどを）具体化する，体現する","他|（全体の一部として）含む"],
   pronunciation:"/ɪmˈbɑːdi/",part:207,
   example:"The new school building should embody the ideas of its students.",
   exampleJa:"新しい校舎は、生徒たちのアイデアを具体化するものであるべきだ。",
   example2:"For many fans, the captain embodied the spirit of the team.",
   exampleJa2:"多くのファンにとって、キャプテンはチームの精神を体現していた。",
   etymologyProcess:"em（中へ）＋ body（体）→ 目に見えない考えに体を与えると…？",
   etymologyConclusion:"em（中へ）＋ body（体）→ 形のない考えを目に見える体の中へ入れる＝（考えなどを）具体化する",
   relatedWords:[
     {word:"body",meaning:"体",breakdown:"body（体）→ 形があって目に見える入れもの"},
     {word:"nobody",meaning:"誰も～ない",breakdown:"no（ない）＋ body（体）→ 体が一つもない"},
     {word:"embodiment",meaning:"具体化；化身",breakdown:"em（中へ）＋ body（体）＋ ment（名詞）→ 考えが体になったもの"},
     {synonym:true,word:"represent",meaning:"表す，象徴する",breakdown:"何かの代わりに示す。embody はそのものになりきって示す"}]},

  {id:2068,word:"assimilate",partOfSpeech:"他動詞・自動詞",meaning:"（知識・情報を）吸収して身につける；同化する",
   meanings:["他|（知識・情報を）吸収して身につける","自|（into ～に）同化する，溶けこむ"],
   pronunciation:"/əˈsɪməleɪt/",part:207,
   example:"Young children can assimilate new words very quickly.",
   exampleJa:"幼い子どもは、新しい言葉をとても速く吸収して身につけることができる。",
   example2:"Many immigrants assimilated into American society within one generation.",
   exampleJa2:"多くの移民は、一世代のうちにアメリカ社会に同化した。",
   usage:["assimilate into 社会（社会に溶けこむ）"],
   etymologyProcess:"ad（～へ）＋ simil（似ている）→ 取り入れたものを自分に似せると…？",
   etymologyConclusion:"ad（～へ）＋ simil（似ている）＋ ate（動詞）→ 取り入れたものを自分と似た一部に変える＝（知識・情報を）吸収して身につける",
   spelling:"ad→as（後ろの s に合わせて変化）",
   etymologyMore:["自分のほうが周りと似た存在になる→同化する，溶けこむ"],
   relatedWords:[
     {word:"similar",meaning:"似ている",breakdown:"simil（似ている）＋ ar（形容詞）→ 形や性質が近い"},
     {word:"similarity",meaning:"類似点",breakdown:"simil（似ている）＋ ity（名詞）→ 似ているところ"},
     {word:"similarly",meaning:"同じように",breakdown:"simil（似ている）＋ ly（副詞）→ 似たやり方で"},
     {synonym:true,word:"absorb",meaning:"吸収する",breakdown:"水や知識を吸いこむ。assimilate は自分の一部にまでする"}]},

  {id:2069,word:"discern",partOfSpeech:"他動詞",meaning:"（違いを）はっきり見分ける，識別する",
   meanings:["他|（違いを）はっきり見分ける，識別する","他|（ぼんやりしたものを）かろうじて認める"],
   pronunciation:"/dɪˈsɜːrn/",part:207,
   example:"It is hard to discern the difference between the two paintings.",
   exampleJa:"その2枚の絵の違いをはっきり見分けるのは難しい。",
   example2:"I could barely discern the path in the thick fog.",
   exampleJa2:"濃い霧の中で、私は道をかろうじて認めることができた。",
   etymologyProcess:"dis（バラバラに）＋ cern（ふるい分ける）→ 混ざったものをふるいにかけると…？",
   etymologyConclusion:"dis（バラバラに）＋ cern（ふるい分ける）→ 混ざったものをふるいで分けるように区別する＝（違いを）はっきり見分ける",
   relatedWords:[
     {word:"secret",meaning:"秘密",breakdown:"se（離れて）＋ cret（ふるい分ける）→ 分けて別にしまっておくもの"},
     {word:"certain",meaning:"確かな",breakdown:"cert（ふるい分ける）＋ ain（～の）→ ふるい分けてはっきりした"},
     {word:"concern",meaning:"関係する；心配",breakdown:"con（共に）＋ cern（ふるい分ける）→ 一緒にふるいにかかわる"},
     {word:"discriminate",meaning:"区別する；差別する",breakdown:"dis（バラバラに）＋ crimin（ふるい分ける）→ 分けて扱いを変える"}]},

  {id:2070,word:"scrutinize",partOfSpeech:"他動詞",meaning:"（細部まで）精査する，綿密に調べる",
   meanings:["他|（細部まで）精査する，綿密に調べる"],
   pronunciation:"/ˈskruːtənaɪz/",part:207,
   example:"The teacher scrutinized every answer on my test paper.",
   exampleJa:"先生は私の答案のすべての答えを精査した。",
   example2:"Every detail of the contract will be scrutinized by lawyers.",
   exampleJa2:"契約書のすべての細部が、弁護士たちによって綿密に調べられるだろう。",
   etymologyProcess:"scrut（がらくた）＋ ize（動詞）→ がらくたの山を一つずつ探ると…？",
   etymologyConclusion:"scrut（がらくた）＋ ize（動詞）→ がらくたの山を一つずつひっくり返して調べる＝（細部まで）精査する",
   why:"【なぜ】ラテン語 scruta は「がらくた・古着のくず」。scrutari は、くずの山を一つずつひっくり返して探すことでした。役に立つものが紛れていないか細かく調べる様子から、「綿密に調べる」意味の scrutiny が生まれ、動詞 scrutinize になりました。\n【つながり】名詞 scrutiny は「精査」。under scrutiny で「厳しく調べられている」です。",
   relatedWords:[
     {word:"scrutiny",meaning:"精査，綿密な調査",breakdown:"scrut（がらくた）＋ iny（名詞）→ くずの山まで調べること"},
     {synonym:true,word:"check",meaning:"確認する",breakdown:"合っているか確かめる。scrutinize は細部まで厳しく見る"},
     {synonym:true,word:"examine",meaning:"詳しく調べる",breakdown:"よく見て調べる。scrutinize はさらに念入り"},
     {synonym:true,word:"inspect",meaning:"点検する",breakdown:"in（中を）＋ spect（見る）。不備がないか見て回る"}]},

  {id:2071,word:"streamline",partOfSpeech:"他動詞",meaning:"（仕事・組織を）合理化する，効率化する",
   meanings:["他|（仕事・組織を）合理化する，効率化する","他|流線形にする"],
   pronunciation:"/ˈstriːmlaɪn/",part:208,
   example:"The company streamlined its system for handling online orders.",
   exampleJa:"その会社は、オンライン注文を処理する仕組みを合理化した。",
   example2:"Engineers streamline the shape of trains to reduce wind resistance.",
   exampleJa2:"技術者たちは空気抵抗を減らすため、列車の形を流線形にする。",
   etymologyProcess:"stream（流れる）＋ line（線）→ 流れをさえぎる出っぱりを削ると…？",
   etymologyConclusion:"stream（流れる）＋ line（線）→ 流れをさえぎる出っぱりを削り、すいすい進むようにする＝（仕事・組織を）合理化する",
   why:"【なぜ】streamline は、もとは水や空気がなめらかに流れる線、つまり「流線形」のことでした。流線形の乗り物は抵抗が少なく、速く進みます。そこから、仕事の手順からむだな出っぱりを削り、すいすい進むようにすることも streamline と言うようになりました。\n【つながり】stream（小川）、headline（見出し）、outline（輪郭）が同じ語根の仲間です。",
   relatedWords:[
     {word:"stream",meaning:"小川；流れ",breakdown:"stream（流れる）→ 途切れずに流れていく水"},
     {word:"line",meaning:"線；列",breakdown:"line（線）→ まっすぐ引かれたすじ"},
     {word:"headline",meaning:"見出し",breakdown:"head（頭）＋ line（線）→ 記事のいちばん上の行"},
     {word:"outline",meaning:"輪郭；概要",breakdown:"out（外へ）＋ line（線）→ 外側をなぞる線"}]},

  {id:2072,word:"mentor",partOfSpeech:"他動詞",meaning:"（若手を）親身に指導する，助言する",
   meanings:["他|（若手を）親身に指導する，助言する","名|（信頼できる）助言者，師"],
   pronunciation:"/ˈmentɔːr/",part:208,
   example:"Senior engineers mentor new employees during their first year.",
   exampleJa:"先輩の技術者たちは、新入社員を最初の1年間親身に指導する。",
   example2:"Our coach has been my mentor since junior high school.",
   exampleJa2:"コーチは中学時代からずっと、私の信頼できる助言者だ。",
   etymologyProcess:"mentor（賢人の名）→ 英雄の息子を導いた人のようにすると…？",
   etymologyConclusion:"mentor（賢人の名）→ 若い王子を導いた賢人のように、若い人を見守り導く＝（若手を）親身に指導する",
   hook:"『オデュッセイア』で王子を導いた老人メントルの名から。実は女神アテナが化けていた。",
   relatedWords:[
     {synonym:true,word:"teacher",meaning:"先生",breakdown:"教える人。mentor は仕事や人生まで長く見守る"},
     {synonym:true,word:"coach",meaning:"コーチ；指導する",breakdown:"技術を鍛える人。mentor は相談相手の面が強い"},
     {synonym:true,word:"guide",meaning:"案内する",breakdown:"道を示して連れていく。mentor は成長を導く"},
     {synonym:true,word:"advise",meaning:"助言する",breakdown:"ad（～へ）＋ vis（見る）。mentor はそれを長く続ける人"}]},

  {id:2073,word:"contemplate",partOfSpeech:"他動詞",meaning:"（じっくり）熟考する；（～しようかと）考える",
   meanings:["他|（じっくり）熟考する","他|（doing）～しようかと考える","他|じっと見つめる"],
   pronunciation:"/ˈkɑːntəmpleɪt/",part:208,
   example:"He sat by the window, contemplating his future after graduation.",
   exampleJa:"彼は窓辺に座り、卒業後の将来をじっくり熟考していた。",
   example2:"She is seriously contemplating quitting the brass band this year.",
   exampleJa2:"彼女は今年、吹奏楽部をやめようかと本気で考えている。",
   usage:["contemplate doing（～しようかと考える）"],
   etymologyProcess:"con（すっかり）＋ templ（神殿）→ 神聖な区画をじっと見つめると…？",
   etymologyConclusion:"con（すっかり）＋ templ（神殿）＋ ate（動詞）→ 神聖な区画をじっと見つめて意味を読み取る＝（じっくり）熟考する",
   why:"【なぜ】ラテン語 templum は、占い師が鳥の飛び方を観察するために空や地面に区切った神聖な区画のことでした。contemplari は、その区画をじっと見つめて神の意思を読み取ること。そこから「じっと見つめる」、さらに「じっくり考える」の意味になりました。\n【つながり】temple（寺院・神殿）も同じ templum から来ています。",
   etymologyMore:["この先の行動をじっと見つめて考える→（doing）～しようかと考える"],
   relatedWords:[
     {word:"temple",meaning:"寺院，神殿",breakdown:"templ（神殿）→ 神をまつるために区切った神聖な場所"},
     {word:"contemplation",meaning:"熟考；瞑想",breakdown:"con（すっかり）＋ templ（神殿）＋ ation（名詞）→ じっと見つめて考えること"},
     {synonym:true,word:"consider",meaning:"よく考える",breakdown:"ふつうの「よく考える」。contemplate はさらに長く深く"},
     {synonym:true,word:"think",meaning:"考える",breakdown:"考える全般。contemplate は静かにじっくり"}]},

  {id:2074,word:"conjecture",partOfSpeech:"他動詞・自動詞",meaning:"（不十分な根拠で）推測する；推測",
   meanings:["他|（不十分な根拠で）推測する","名|推測，憶測"],
   pronunciation:"/kənˈdʒektʃər/",part:208,
   example:"Scientists can only conjecture about what the planet's surface is like.",
   exampleJa:"科学者たちは、その惑星の表面がどうなっているかを推測するしかない。",
   example2:"His story about the accident is pure conjecture.",
   exampleJa2:"事故についての彼の話は、まったくの憶測だ。",
   etymologyProcess:"con（共に）＋ ject（投げる）→ 手がかりを一か所に投げ集めると…？",
   etymologyConclusion:"con（共に）＋ ject（投げる）＋ ure（名詞）→ 手がかりを寄せ集めて答えを組み立てる＝（不十分な根拠で）推測する",
   why:"【なぜ】ラテン語 conicere は「一か所に投げ集める」こと。集めた断片をつなぎ合わせて答えを組み立てる様子から、夢や占いを解く、つまり「推測する」ことを指すようになりました。確かな証拠ではなく、寄せ集めから出した答えという響きが今も残っています。\n【つながり】project（前に投げる＝計画）や subject、object も ject（投げる）の仲間です。",
   relatedWords:[
     {word:"project",meaning:"計画",breakdown:"pro（前へ）＋ ject（投げる）→ 考えを先へ投げ出したもの"},
     {word:"subject",meaning:"教科；主題",breakdown:"sub（下で）＋ ject（投げる）→ 下に置かれて扱われるもの"},
     {word:"reject",meaning:"拒絶する",breakdown:"re（後ろへ）＋ ject（投げる）→ 受け取らずに投げ返す"},
     {synonym:true,word:"guess",meaning:"推測する",breakdown:"ふつうの「当てずっぽうに言う」。conjecture は硬い語"}]},

  {id:2075,word:"presume",partOfSpeech:"他動詞",meaning:"（確証なしに）～だと推定する；厚かましくも～する",
   meanings:["他|（確証なしに）～だと推定する","他|（presume to do）厚かましくも～する"],
   pronunciation:"/prɪˈzuːm/",part:208,
   example:"I presume that the train will be late because of the snow.",
   exampleJa:"雪のため、電車は遅れるだろうと私は推定している。",
   example2:"I wouldn't presume to tell you how to run your club.",
   exampleJa2:"あなたの部の運営に、厚かましくも口を出すつもりはありません。",
   usage:["presume that SV（SV だと推定する）","presume to do（厚かましくも～する）"],
   etymologyProcess:"pre（先に）＋ sume（取る）→ 確かめる前に先に受け取ると…？",
   etymologyConclusion:"pre（先に）＋ sume（取る）→ 確かめる前に、そうだと先に受け取っておく＝（確証なしに）～だと推定する",
   etymologyMore:["許しを得る前に自分から先に取る→（presume to do）厚かましくも～する"],
   relatedWords:[
     {word:"assume",meaning:"思いこむ，仮定する",breakdown:"ad（～へ）＋ sume（取る）→ 考えを手もとに取りこむ"},
     {word:"consume",meaning:"消費する",breakdown:"con（すっかり）＋ sume（取る）→ すっかり取り尽くす"},
     {word:"resume",meaning:"再開する",breakdown:"re（再び）＋ sume（取る）→ 手放したものを再び取る"},
     {word:"presumably",meaning:"おそらく",breakdown:"pre（先に）＋ sume（取る）＋ ably（副詞）→ 先にそう受け取れば"}]},

  {id:2076,word:"gauge",partOfSpeech:"他動詞",meaning:"（状況・気持ちを）見きわめる，判断する",
   meanings:["他|（状況・気持ちを）見きわめる，判断する","他|（計器で）測る","名|計器，ゲージ"],
   pronunciation:"/ɡeɪdʒ/",part:208,
   example:"It is hard to gauge how people feel from short messages.",
   exampleJa:"短いメッセージから人の気持ちを見きわめるのは難しい。",
   example2:"Check the fuel gauge before you start a long drive.",
   exampleJa2:"長距離を運転する前に、燃料計を確認しなさい。",
   etymologyProcess:"gauge（ものさし）→ ものさしを当てて程度をはかると…？",
   etymologyConclusion:"gauge（ものさし）→ ものさしを当てるように、状況の大きさや程度を見はかる＝（状況・気持ちを）見きわめる",
   hook:"「ゲージ」は計器のこと。語源ははっきりしないが、目盛りを読む動きから判断の意味に。",
   etymologyMore:["目盛りを当てて量を読む→（計器で）測る"],
   relatedWords:[
     {synonym:true,word:"measure",meaning:"測る",breakdown:"長さや量を測る。gauge は目盛りで見当をつける"},
     {synonym:true,word:"judge",meaning:"判断する",breakdown:"よしあしを決める。gauge は程度を見はかる"},
     {synonym:true,word:"estimate",meaning:"見積もる",breakdown:"数や量をおおよそ計算する"},
     {synonym:true,word:"meter",meaning:"計量器，メーター",breakdown:"量を示す器具。gauge とほぼ同じ場面で使う"}]},

  {id:2077,word:"verify",partOfSpeech:"他動詞",meaning:"（正しいかどうか）確かめる，検証する",
   meanings:["他|（正しいかどうか）確かめる，検証する"],
   pronunciation:"/ˈverɪfaɪ/",part:208,
   example:"Please verify your email address before you log in.",
   exampleJa:"ログインする前に、メールアドレスが正しいかどうか確かめてください。",
   example2:"The results were verified by two other research teams.",
   exampleJa2:"その結果は、ほかの2つの研究チームによって検証された。",
   etymologyProcess:"ver（真実の）＋ fy（する）→ 本当かどうかをはっきりさせると…？",
   etymologyConclusion:"ver（真実の）＋ fy（する）→ 本当に正しいことをはっきりさせる＝（正しいかどうか）確かめる",
   relatedWords:[
     {word:"very",meaning:"とても；まさにその",breakdown:"ver（真実の）＋ y（形容詞）→ 本当に。もとは「真の」"},
     {word:"verdict",meaning:"評決，判断",breakdown:"ver（真実の）＋ dict（言う）→ 真実だと言い渡すこと"},
     {word:"verification",meaning:"確認，検証",breakdown:"ver（真実の）＋ fic（作る）＋ ation（名詞）→ 真実だとはっきりさせること"},
     {synonym:true,word:"confirm",meaning:"確認する",breakdown:"con（強く）＋ firm（固い）。確かなものに固める"}]},

  {id:2078,word:"pledge",partOfSpeech:"他動詞",meaning:"（公に）固く誓う，誓約する",
   meanings:["他|（公に）固く誓う，誓約する","他|（寄付などを）約束する","名|誓約，公約"],
   pronunciation:"/pledʒ/",part:208,
   example:"The students pledged to keep their school clean all year.",
   exampleJa:"生徒たちは、1年中学校をきれいに保つと固く誓った。",
   example2:"Many companies made a pledge to cut their carbon emissions.",
   exampleJa2:"多くの企業が、二酸化炭素の排出を減らすという誓約をした。",
   usage:["pledge to do（～すると誓う）","pledge 物 to 人（人に物を約束する）"],
   etymologyProcess:"pledge（保証）→ 自分を保証に差し出して約束すると…？",
   etymologyConclusion:"pledge（保証）→ 自分を保証として差し出し、必ず守ると約束する＝（公に）固く誓う",
   hook:"語源ははっきりしない。promise より公式で重い約束。選挙の「公約」も pledge。",
   relatedWords:[
     {synonym:true,word:"promise",meaning:"約束する",breakdown:"ふつうの「約束する」。pledge はより公式で重い"},
     {synonym:true,word:"swear",meaning:"誓う",breakdown:"神などにかけて誓う"},
     {synonym:true,word:"vow",meaning:"誓い；誓う",breakdown:"心に固く決めた誓い"},
     {synonym:true,word:"oath",meaning:"宣誓",breakdown:"法廷などで正式に述べる誓い"}]},

  {id:2079,word:"dismay",partOfSpeech:"他動詞",meaning:"（人を）ろうばいさせる，がっかりさせる",
   meanings:["他|（人を）ろうばいさせる，がっかりさせる","名|ろうばい，落胆"],
   pronunciation:"/dɪsˈmeɪ/",part:208,
   example:"The sudden news of the game's cancellation dismayed all the players.",
   exampleJa:"試合中止という突然の知らせは、選手全員をろうばいさせた。",
   example2:"To our dismay, it started raining just before the festival.",
   exampleJa2:"がっかりしたことに、祭りの直前に雨が降り出した。",
   usage:["to 人's dismay（人ががっかりしたことに）"],
   etymologyProcess:"dis（否定）＋ may（力がある）→ 人から力を奪うと…？",
   etymologyConclusion:"dis（否定）＋ may（力がある）→ 人から力を奪い、気持ちをくじいてしまう＝（人を）ろうばいさせる",
   relatedWords:[
     {word:"may",meaning:"～してよい；～かもしれない",breakdown:"may（力がある）→ もとは「～する力がある」"},
     {word:"might",meaning:"力；～かもしれない",breakdown:"may（力がある）＋ t（名詞）→ 持っている力"},
     {synonym:true,word:"disappoint",meaning:"がっかりさせる",breakdown:"期待を裏切る。dismay は驚きとショックが加わる"},
     {synonym:true,word:"upset",meaning:"動揺させる",breakdown:"up（上へ）＋ set（置く）。ひっくり返して心を乱す"}]},

  {id:2080,word:"lament",partOfSpeech:"他動詞",meaning:"（死・不運を）深く悲しむ，嘆く",
   meanings:["他|（死・不運を）深く悲しむ，嘆く","名|嘆き，悲嘆"],
   pronunciation:"/ləˈment/",part:208,
   example:"The whole town lamented the death of the old doctor.",
   exampleJa:"町中が、年老いた医師の死を深く悲しんだ。",
   example2:"Many older people lament the loss of traditional festivals.",
   exampleJa2:"多くの高齢者は、伝統的な祭りがなくなったことを嘆いている。",
   etymologyProcess:"lament（泣き叫ぶ）→ 声をあげて泣くほどつらいと…？",
   etymologyConclusion:"lament（泣き叫ぶ）→ 声をあげて泣くほど、失ったものを思って悲しむ＝（死・不運を）深く悲しむ",
   hook:"心の中だけでなく、言葉や声に出して悲しむ感じ。詩や歌の「哀歌」も a lament。",
   relatedWords:[
     {synonym:true,word:"cry",meaning:"泣く；叫ぶ",breakdown:"声をあげて泣く。lament はそれを深い悲しみとして表す"},
     {synonym:true,word:"regret",meaning:"後悔する；残念に思う",breakdown:"してしまったことを悔やむ"},
     {synonym:true,word:"mourn",meaning:"嘆く，悼む",breakdown:"人の死を悼む。lament は失ったもの全般を嘆く"},
     {synonym:true,word:"grieve",meaning:"深く悲しむ",breakdown:"大切なものを失って苦しむ"}]},

  {id:2081,word:"perplex",partOfSpeech:"他動詞",meaning:"（人を）困惑させる，途方に暮れさせる",
   meanings:["他|（人を）困惑させる，途方に暮れさせる"],
   pronunciation:"/pərˈpleks/",part:209,
   example:"The difficult question perplexed even the smartest students in class.",
   exampleJa:"その難問は、クラスで一番頭のいい生徒たちさえ困惑させた。",
   example2:"I was perplexed by her sudden change of mind.",
   exampleJa2:"私は彼女の突然の心変わりに途方に暮れた。",
   etymologyProcess:"per（すっかり）＋ plex（編み合わせる）→ 頭の中がすっかり絡み合うと…？",
   etymologyConclusion:"per（すっかり）＋ plex（編み合わせる）→ 糸がすっかり絡み合うように、頭をこんがらがらせる＝（人を）困惑させる",
   relatedWords:[
     {word:"complex",meaning:"複雑な",breakdown:"com（共に）＋ plex（編み合わせる）→ いくつも編み合わさった"},
     {word:"complexity",meaning:"複雑さ",breakdown:"com（共に）＋ plex（編み合わせる）＋ ity（名詞）→ 絡み合っている度合い"},
     {word:"perplexity",meaning:"困惑，当惑",breakdown:"per（すっかり）＋ plex（編み合わせる）＋ ity（名詞）→ 頭が絡まった状態"},
     {synonym:true,word:"confuse",meaning:"混乱させる",breakdown:"con（共に）＋ fuse（注ぐ）。ごちゃまぜにする。perplex は答えが出ず悩ませる"}]},

  {id:2082,word:"disgust",partOfSpeech:"他動詞",meaning:"（人に）嫌悪を抱かせる，むかつかせる",
   meanings:["他|（人に）嫌悪を抱かせる，むかつかせる","名|嫌悪，むかつき"],
   pronunciation:"/dɪsˈɡʌst/",part:209,
   example:"The smell of the rotten fish disgusted everyone in the room.",
   exampleJa:"腐った魚のにおいは、部屋にいた全員に嫌悪を抱かせた。",
   example2:"She left the room in disgust after hearing his rude joke.",
   exampleJa2:"彼の失礼な冗談を聞いて、彼女はむかつきながら部屋を出た。",
   usage:["be disgusted with 人・物（人・物にうんざりする）","in disgust（うんざりして）"],
   etymologyProcess:"dis（否定）＋ gust（味わう）→ とても味わえないと感じると…？",
   etymologyConclusion:"dis（否定）＋ gust（味わう）→ 口に合わず、とても味わえないと感じさせる＝（人に）嫌悪を抱かせる",
   relatedWords:[
     {word:"disgusting",meaning:"むかつくような，ひどい",breakdown:"dis（否定）＋ gust（味わう）＋ ing（形容詞）→ 味わいたくもない"},
     {word:"gusto",meaning:"楽しみ，熱意",breakdown:"gust（味わう）→ 心から味わって楽しむこと"},
     {synonym:true,word:"hate",meaning:"ひどく嫌う",breakdown:"強く嫌う気持ち。disgust は吐き気がするほどの嫌悪"},
     {synonym:true,word:"dislike",meaning:"嫌う",breakdown:"dis（否定）＋ like（好む）。disgust よりずっと軽い"}]},

  {id:2083,word:"evoke",partOfSpeech:"他動詞",meaning:"（記憶・感情を）呼び起こす",
   meanings:["他|（記憶・感情を）呼び起こす","他|（反応を）引き出す"],
   pronunciation:"/ɪˈvoʊk/",part:209,
   example:"This old song evokes memories of my summers in Okinawa.",
   exampleJa:"この古い歌は、沖縄で過ごした夏の記憶を呼び起こす。",
   example2:"The film evoked strong reactions from the audience.",
   exampleJa2:"その映画は、観客から強い反応を引き出した。",
   etymologyProcess:"e（外へ）＋ voc（呼ぶ）→ 心の奥にあるものを外へ呼ぶと…？",
   etymologyConclusion:"e（外へ）＋ voc（呼ぶ）→ 心の奥にしまわれたものを外へ呼び出す＝（記憶・感情を）呼び起こす",
   spelling:"voc→vok（c が k の綴りに変わった）",
   relatedWords:[
     {word:"voice",meaning:"声",breakdown:"voc（呼ぶ）→ 人を呼ぶときに出すもの"},
     {word:"vocal",meaning:"声の；ボーカル",breakdown:"voc（呼ぶ）＋ al（形容詞）→ 声を出して歌う"},
     {word:"provoke",meaning:"引き起こす；挑発する",breakdown:"pro（前へ）＋ voc（呼ぶ）→ 怒りを表へ呼び出す"},
     {synonym:true,word:"remind",meaning:"思い出させる",breakdown:"re（再び）＋ mind（心）。evoke は気分ごと呼び出す"}]},

  {id:2084,word:"harbor",partOfSpeech:"他動詞",meaning:"（悪い感情・疑いを）心に抱く",
   meanings:["他|（悪い感情・疑いを）心に抱く","他|（犯人などを）かくまう","名|港"],
   pronunciation:"/ˈhɑːrbər/",part:209,
   example:"He still harbors a grudge against his old teammate.",
   exampleJa:"彼は昔のチームメイトに対して、今も恨みを心に抱いている。",
   example2:"Our ship stayed in the harbor until the storm passed.",
   exampleJa2:"嵐が過ぎるまで、私たちの船は港にとどまった。",
   etymologyProcess:"harbor（避難所）→ 港に船をかくまうように、思いを胸に…？",
   etymologyConclusion:"harbor（避難所）→ 港に船をかくまうように、思いを胸の中にしまっておく＝（悪い感情・疑いを）心に抱く",
   hook:"もとは古英語で「軍の宿営地」。今は名詞の「港」がいちばん身近な意味。",
   etymologyMore:["避難所に入れて守る→（犯人などを）かくまう"],
   relatedWords:[
     {synonym:true,word:"port",meaning:"港",breakdown:"港そのもの。harbor は船が風や波から守られる所"},
     {synonym:true,word:"hide",meaning:"隠す",breakdown:"見えない所にしまう。harbor は人を守ってかくまう"},
     {synonym:true,word:"keep",meaning:"持ち続ける",breakdown:"手もとに置いておく。harbor は悪い思いを胸に持ち続ける"},
     {synonym:true,word:"bear",meaning:"（感情を）抱く",breakdown:"bear a grudge（恨みを抱く）の形でも使う"}]},

  {id:2085,word:"friction",partOfSpeech:"名詞",meaning:"摩擦；（人・国の間の）あつれき",
   meanings:["名|摩擦","名|（人・国の間の）あつれき，不和"],
   pronunciation:"/ˈfrɪkʃən/",part:209,
   example:"Friction between the tires and the road helps a car stop.",
   exampleJa:"タイヤと道路の間の摩擦は、車が止まるのを助ける。",
   example2:"There was some friction between the two captains before the game.",
   exampleJa2:"試合前、2人のキャプテンの間には多少のあつれきがあった。",
   etymologyProcess:"fric（こする）＋ tion（名詞）→ 物と物がこすれ合うと…？",
   etymologyConclusion:"fric（こする）＋ tion（名詞）→ 物と物がこすれ合って動きをじゃまする力＝摩擦",
   etymologyMore:["意見どうしがこすれ合う→（人・国の間の）あつれき，不和"],
   relatedWords:[
     {word:"frictionless",meaning:"摩擦のない",breakdown:"fric（こする）＋ tion（名詞）＋ less（ない）→ こすれ合いのない"},
     {synonym:true,word:"rub",meaning:"こする",breakdown:"表面をこする動き。friction はそのときに生まれる力"},
     {synonym:true,word:"conflict",meaning:"対立",breakdown:"con（共に）＋ flict（打つ）。friction より激しいぶつかり合い"},
     {synonym:true,word:"tension",meaning:"緊張",breakdown:"張りつめた関係。friction はこすれ合う不和"}]},

  {id:2086,word:"mutation",partOfSpeech:"名詞",meaning:"（遺伝子の）突然変異；変化",
   meanings:["名|（遺伝子の）突然変異","名|変化，変形"],
   pronunciation:"/mjuːˈteɪʃən/",part:209,
   example:"A mutation in one gene can change the color of a flower.",
   exampleJa:"1つの遺伝子の突然変異が、花の色を変えることがある。",
   example2:"Scientists are studying how mutations of the virus spread worldwide.",
   exampleJa2:"科学者たちは、ウイルスの突然変異が世界中にどう広がるかを研究している。",
   etymologyProcess:"mut（変える）＋ ation（名詞）→ 生き物の設計図が変わると…？",
   etymologyConclusion:"mut（変える）＋ ation（名詞）→ 生き物の設計図である遺伝子が変わること＝（遺伝子の）突然変異",
   relatedWords:[
     {word:"mutual",meaning:"お互いの",breakdown:"mut（変える）＋ ual（形容詞）→ 取り替えっこする"},
     {word:"commute",meaning:"通勤する",breakdown:"com（すっかり）＋ mut（変える）→ 券に替えて毎日行き来する"},
     {word:"mutant",meaning:"突然変異体",breakdown:"mut（変える）＋ ant（もの）→ 変化して生まれたもの"},
     {synonym:true,word:"change",meaning:"変化",breakdown:"変わること全般。mutation は生物の遺伝子の変化"}]},

  {id:2087,word:"heredity",partOfSpeech:"名詞",meaning:"遺伝；遺伝的特質",
   meanings:["名|遺伝","名|遺伝的特質"],
   pronunciation:"/həˈredəti/",part:209,
   example:"Heredity plays a role in how tall a person grows.",
   exampleJa:"遺伝は、人の身長がどれくらい伸びるかに関わっている。",
   example2:"Some diseases are passed on through heredity, not lifestyle.",
   exampleJa2:"病気の中には、生活習慣ではなく遺伝によって伝わるものもある。",
   etymologyProcess:"hered（受け継ぐ）＋ ity（名詞）→ 親から子へ受け継がれると…？",
   etymologyConclusion:"hered（受け継ぐ）＋ ity（名詞）→ 体の特徴が親から子へ受け継がれること＝遺伝",
   relatedWords:[
     {word:"inherit",meaning:"受け継ぐ",breakdown:"in（中へ）＋ herit（受け継ぐ）→ 財産や性質を自分の中へ受ける"},
     {word:"heritage",meaning:"遺産",breakdown:"herit（受け継ぐ）＋ age（名詞）→ 先祖から受け継いだもの"},
     {word:"heir",meaning:"相続人",breakdown:"heir（受け継ぐ人）→ 財産を受け継ぐ人"},
     {word:"hereditary",meaning:"遺伝性の",breakdown:"hered（受け継ぐ）＋ ary（形容詞）→ 親から伝わる"}]},

  {id:2088,word:"synthesis",partOfSpeech:"名詞",meaning:"（化学的な）合成；統合",
   meanings:["名|（化学的な）合成","名|（考えなどの）統合"],
   pronunciation:"/ˈsɪnθəsɪs/",part:209,
   example:"Plants use sunlight for the synthesis of sugar in their leaves.",
   exampleJa:"植物は、葉の中での糖の合成に日光を使う。",
   example2:"Her essay is a clever synthesis of two different ideas.",
   exampleJa2:"彼女の小論文は、2つの異なる考えを見事に統合したものだ。",
   etymologyProcess:"syn（共に）＋ thes（置く）→ いくつもの材料を一緒に置くと…？",
   etymologyConclusion:"syn（共に）＋ thes（置く）＋ is（名詞）→ 材料を一緒に置いて新しい物を作ること＝（化学的な）合成",
   etymologyMore:["別々の考えを一緒に置いてまとめる→（考えなどの）統合"],
   relatedWords:[
     {word:"photosynthesis",meaning:"光合成",breakdown:"photo（光）＋ syn（共に）＋ thes（置く）→ 光の力で養分を作る"},
     {word:"hypothesis",meaning:"仮説",breakdown:"hypo（下に）＋ thes（置く）→ 議論の土台に置く考え"},
     {word:"synthetic",meaning:"合成の，人工の",breakdown:"syn（共に）＋ thes（置く）＋ ic（形容詞）→ 組み合わせて作った"},
     {synonym:true,word:"combine",meaning:"組み合わせる",breakdown:"com（共に）＋ bi（2つ）。2つ以上をまとめる"}]},

  {id:2089,word:"veterinarian",partOfSpeech:"名詞",meaning:"獣医",
   meanings:["名|獣医"],
   pronunciation:"/ˌvetərəˈneriən/",part:209,
   example:"My cousin wants to become a veterinarian and help sick animals.",
   exampleJa:"いとこは獣医になって、病気の動物を助けたいと思っている。",
   example2:"We took our dog to the veterinarian for a checkup.",
   exampleJa2:"私たちは健康診断のため、犬を獣医に連れていった。",
   etymologyProcess:"veterin（荷を運ぶ家畜）＋ ian（人）→ 家畜の世話をする人は…？",
   etymologyConclusion:"veterin（荷を運ぶ家畜）＋ ian（人）→ 荷を運ぶ牛や馬の病気を治す人＝獣医",
   relatedWords:[
     {word:"vet",meaning:"獣医",breakdown:"veterin（荷を運ぶ家畜）→ veterinarian を短くした語"},
     {synonym:true,word:"doctor",meaning:"医者",breakdown:"人を診る医者。veterinarian は動物の医者"},
     {synonym:true,word:"animal",meaning:"動物",breakdown:"veterinarian が診る相手"},
     {synonym:true,word:"pet",meaning:"ペット",breakdown:"今の獣医がいちばんよく診る動物"}]},

  {id:2090,word:"epidemic",partOfSpeech:"名詞",meaning:"（伝染病の）大流行；流行性の",
   meanings:["名|（伝染病の）大流行","形|流行性の","名|（悪いことの）急速な広がり"],
   pronunciation:"/ˌepɪˈdemɪk/",part:209,
   example:"A flu epidemic closed many schools in the city last winter.",
   exampleJa:"昨冬、インフルエンザの大流行で市内の多くの学校が閉鎖された。",
   example2:"Some experts say obesity among children has become an epidemic.",
   exampleJa2:"子どもの肥満が急速な広がりを見せていると言う専門家もいる。",
   etymologyProcess:"epi（間に）＋ demo（民衆）→ 病気が民衆の間に広がると…？",
   etymologyConclusion:"epi（間に）＋ demo（民衆）＋ ic（形容詞）→ 病気が民衆の間に一気に広がる＝（伝染病の）大流行",
   spelling:"demo→dem（語尾の o が落ちた）",
   etymologyMore:["病気のように人々の間に一気に広がる→（悪いことの）急速な広がり"],
   relatedWords:[
     {word:"democracy",meaning:"民主主義",breakdown:"demo（民衆）＋ cracy（支配）→ 民衆が国を治めるしくみ"},
     {word:"demographic",meaning:"人口統計の",breakdown:"demo（民衆）＋ graph（書く）＋ ic（形容詞）→ 人々の数を書き記す"},
     {synonym:true,word:"pandemic",meaning:"世界的大流行",breakdown:"pan（すべての）＋ dem（民衆）。epidemic が世界中に広がったもの"},
     {synonym:true,word:"disease",meaning:"病気",breakdown:"dis（否定）＋ ease（楽）。epidemic で広がるもの"}]},

  {id:2091,word:"obesity",partOfSpeech:"名詞",meaning:"肥満",
   meanings:["名|肥満"],
   pronunciation:"/oʊˈbiːsəti/",part:210,
   example:"Lack of exercise is one cause of obesity in children.",
   exampleJa:"運動不足は、子どもの肥満の原因の一つだ。",
   example2:"The government started a campaign to fight obesity.",
   exampleJa2:"政府は肥満と闘うキャンペーンを始めた。",
   etymologyProcess:"obes（食べて太った）＋ ity（名詞）→ 食べすぎて太った状態は…？",
   etymologyConclusion:"obes（食べて太った）＋ ity（名詞）→ 食べすぎて体に脂肪がつきすぎた状態＝肥満",
   relatedWords:[
     {word:"obese",meaning:"肥満の",breakdown:"obes（食べて太った）→ 食べすぎて太りすぎた"},
     {synonym:true,word:"fat",meaning:"脂肪；太った",breakdown:"ふつうの「太った」。obesity は健康に害があるほどの状態"},
     {synonym:true,word:"overweight",meaning:"太りすぎの",breakdown:"over（超えて）＋ weight（重さ）。obesity より軽い言い方"},
     {synonym:true,word:"diet",meaning:"食事；ダイエット",breakdown:"毎日の食事。obesity を防ぐ手段の一つ"}]},

  {id:2092,word:"neuron",partOfSpeech:"名詞",meaning:"ニューロン，神経細胞",
   meanings:["名|ニューロン，神経細胞"],
   pronunciation:"/ˈnʊrɑːn/",part:210,
   example:"Each neuron in the brain sends signals to many other cells.",
   exampleJa:"脳の中の一つ一つのニューロンは、ほかの多くの細胞に信号を送る。",
   example2:"Neurons carry messages between the brain and the body.",
   exampleJa2:"神経細胞は、脳と体の間で情報を運ぶ。",
   etymologyProcess:"neur（神経）→ 体中に信号を伝える細胞は…？",
   etymologyConclusion:"neur（神経）→ 体中に信号を伝える神経の、一つ一つの細胞＝ニューロン",
   hook:"もとはギリシャ語で「筋，腱」。人の脳には約860億個あるといわれる。",
   relatedWords:[
     {word:"neural",meaning:"神経の",breakdown:"neur（神経）＋ al（形容詞）→ 神経にかかわる"},
     {word:"neurology",meaning:"神経学",breakdown:"neur（神経）＋ log（学問）→ 神経を研究する学問"},
     {synonym:true,word:"nerve",meaning:"神経",breakdown:"neuron と遠い親戚のラテン語系。神経の束を指す"},
     {synonym:true,word:"brain",meaning:"脳",breakdown:"neuron が大量に集まってできている"}]},

  {id:2093,word:"dementia",partOfSpeech:"名詞",meaning:"認知症",
   meanings:["名|認知症"],
   pronunciation:"/dɪˈmenʃə/",part:210,
   example:"My grandmother has dementia and sometimes forgets my name.",
   exampleJa:"祖母は認知症で、ときどき私の名前を忘れる。",
   example2:"Regular exercise may lower the risk of dementia in old age.",
   exampleJa2:"定期的な運動は、老後の認知症のリスクを下げるかもしれない。",
   etymologyProcess:"de（離れて）＋ mens（心）→ 心がもとの場所から離れると…？",
   etymologyConclusion:"de（離れて）＋ mens（心）＋ ia（状態）→ 記憶や判断の力が心から離れていく状態＝認知症",
   spelling:"mens→ment（ラテン語の変化形 ment- から）",
   relatedWords:[
     {word:"mental",meaning:"心の，精神の",breakdown:"mens（心）＋ al（形容詞）→ 心にかかわる"},
     {word:"mention",meaning:"話に出す",breakdown:"mens（心）＋ ion（名詞）→ 心に浮かんだことを口にする"},
     {word:"comment",meaning:"論評，コメント",breakdown:"com（すっかり）＋ mens（心）→ 心で考えたことを述べる"},
     {synonym:true,word:"forget",meaning:"忘れる",breakdown:"ふつうの「忘れる」。dementia では病気として忘れていく"}]},

  {id:2094,word:"diabetes",partOfSpeech:"名詞",meaning:"糖尿病",
   meanings:["名|糖尿病"],
   pronunciation:"/ˌdaɪəˈbiːtiːz/",part:210,
   example:"Eating too much sugar can raise the risk of diabetes.",
   exampleJa:"砂糖をとりすぎると、糖尿病のリスクが高まることがある。",
   example2:"My uncle checks his blood sugar every day because of his diabetes.",
   exampleJa2:"おじは糖尿病のため、毎日血糖値を測っている。",
   etymologyProcess:"diabet（通り抜ける）→ 飲んだ水がすぐ体を通り抜ける病気は…？",
   etymologyConclusion:"diabet（通り抜ける）→ 飲んだ水が体を通り抜けて、すぐ尿に出てしまう病気＝糖尿病",
   hook:"ギリシャ語で「サイフォン（管）」。のどが渇き、尿がたくさん出る症状から。",
   relatedWords:[
     {synonym:true,word:"sugar",meaning:"砂糖；糖",breakdown:"diabetes では血液中の糖が多くなりすぎる"},
     {synonym:true,word:"blood",meaning:"血液",breakdown:"diabetes の検査では血液中の糖の量を測る"},
     {synonym:true,word:"insulin",meaning:"インスリン",breakdown:"血糖を下げるホルモン。diabetes の治療に使う"},
     {synonym:true,word:"disease",meaning:"病気",breakdown:"dis（否定）＋ ease（楽）。diabetes も長く付き合う病気"}]},

  {id:2095,word:"placebo",partOfSpeech:"名詞",meaning:"偽薬，プラセボ",
   meanings:["名|偽薬，プラセボ"],
   pronunciation:"/pləˈsiːboʊ/",part:210,
   example:"Half of the patients were given a placebo instead of the new drug.",
   exampleJa:"患者の半数には、新薬の代わりに偽薬が与えられた。",
   example2:"Some people feel better just because of the placebo effect.",
   exampleJa2:"プラセボ効果だけで気分がよくなる人もいる。",
   etymologyProcess:"plac（喜ばせる）→ 成分ではなく、安心させて喜ばせる薬は…？",
   etymologyConclusion:"plac（喜ばせる）→ 効く成分はなく、患者を安心させて喜ばせるだけの薬＝偽薬",
   why:"【なぜ】placebo はラテン語で「私は喜ばせましょう」という意味の動詞の形です。中世には、お世辞で人の機嫌をとる人を指すこともありました。やがて、効き目はないが患者を安心させ、喜ばせるために出す薬を指すようになり、今の「偽薬」になりました。\n【つながり】please（喜ばせる）、pleasant（楽しい）、pleasure（喜び）が同じ仲間です。",
   relatedWords:[
     {word:"please",meaning:"喜ばせる",breakdown:"pleas（喜ばせる）→ 相手の気持ちを満たす"},
     {word:"pleasant",meaning:"楽しい，心地よい",breakdown:"pleas（喜ばせる）＋ ant（～な）→ 人を喜ばせるような"},
     {word:"pleasure",meaning:"喜び，楽しみ",breakdown:"pleas（喜ばせる）＋ ure（名詞）→ 喜ばされた気持ち"},
     {synonym:true,word:"medicine",meaning:"薬",breakdown:"病気を治す薬。placebo は薬の形をしているだけ"}]},

  {id:2096,word:"malnutrition",partOfSpeech:"名詞",meaning:"栄養失調",
   meanings:["名|栄養失調"],
   pronunciation:"/ˌmælnuːˈtrɪʃən/",part:210,
   example:"Many children in the region suffer from malnutrition.",
   exampleJa:"その地域の多くの子どもが、栄養失調に苦しんでいる。",
   example2:"Skipping meals every day can lead to malnutrition.",
   exampleJa2:"毎日食事を抜くと、栄養失調になりかねない。",
   etymologyProcess:"mal（悪く）＋ nutri（養い育てる）→ 体の養い方が悪いと…？",
   etymologyConclusion:"mal（悪く）＋ nutri（養い育てる）＋ tion（名詞）→ 体を養う食べ物が足りず、うまく育たない状態＝栄養失調",
   relatedWords:[
     {word:"nutrition",meaning:"栄養",breakdown:"nutri（養い育てる）＋ tion（名詞）→ 体を養い育てるもの"},
     {word:"nurse",meaning:"看護師",breakdown:"nurs（養い育てる）→ 病人や子どもの世話をする人"},
     {word:"nourish",meaning:"栄養を与える",breakdown:"nour（養い育てる）＋ ish（動詞）→ 食べ物で体を養う"},
     {word:"malfunction",meaning:"故障",breakdown:"mal（悪く）＋ function（働き）→ 働きが悪くなること"}]},

  {id:2097,word:"dehydration",partOfSpeech:"名詞",meaning:"脱水（症状）",
   meanings:["名|脱水（症状）"],
   pronunciation:"/ˌdiːhaɪˈdreɪʃən/",part:210,
   example:"Drink plenty of water to avoid dehydration during summer practice.",
   exampleJa:"夏の練習中は脱水症状を防ぐため、水をたくさん飲みなさい。",
   example2:"The old man was taken to the hospital with severe dehydration.",
   exampleJa2:"その老人は、重い脱水症状で病院に運ばれた。",
   etymologyProcess:"de（離れて）＋ hydr（水）→ 体から水が離れていくと…？",
   etymologyConclusion:"de（離れて）＋ hydr（水）＋ ation（名詞）→ 体から水分が抜けていってしまう状態＝脱水（症状）",
   relatedWords:[
     {word:"hydrogen",meaning:"水素",breakdown:"hydr（水）＋ gen（生み出す）→ 燃やすと水を生み出す元素"},
     {word:"hydrate",meaning:"水分を補給する",breakdown:"hydr（水）＋ ate（動詞）→ 体に水を与える"},
     {synonym:true,word:"thirst",meaning:"のどの渇き",breakdown:"水がほしい感覚。dehydration の最初のサイン"},
     {synonym:true,word:"dry",meaning:"乾いた",breakdown:"水気がない状態。dehydration は体の中が乾くこと"}]},

  {id:2098,word:"abortion",partOfSpeech:"名詞",meaning:"妊娠中絶",
   meanings:["名|妊娠中絶"],
   pronunciation:"/əˈbɔːrʃən/",part:210,
   example:"The law on abortion is different in each country.",
   exampleJa:"妊娠中絶に関する法律は、国ごとに異なる。",
   example2:"The debate over abortion divides many voters in America.",
   exampleJa2:"妊娠中絶をめぐる議論は、アメリカの多くの有権者を二分している。",
   etymologyProcess:"ab（離れて）＋ ort（のぼり始める）→ 生まれ出ることから離れると…？",
   etymologyConclusion:"ab（離れて）＋ ort（のぼり始める）＋ ion（名詞）→ 生まれ出ようとする命を途中で止めること＝妊娠中絶",
   relatedWords:[
     {word:"origin",meaning:"起源",breakdown:"ori（のぼり始める）＋ gin（名詞）→ 物事がのぼり始めた所"},
     {word:"original",meaning:"最初の；独創的な",breakdown:"ori（のぼり始める）＋ al（形容詞）→ 始まりのままの"},
     {word:"abort",meaning:"（計画を）中止する",breakdown:"ab（離れて）＋ ort（のぼり始める）→ 始まったことを途中でやめる"},
     {synonym:true,word:"pregnancy",meaning:"妊娠",breakdown:"pre（前に）＋ gn（生まれる）。abortion はこれを途中で終えること"}]},

  {id:2099,word:"antibiotic",partOfSpeech:"名詞",meaning:"抗生物質",
   meanings:["名|抗生物質","形|抗生物質の"],
   pronunciation:"/ˌæntibaɪˈɑːtɪk/",part:210,
   example:"The doctor gave me antibiotics for my throat infection.",
   exampleJa:"医者は私ののどの感染症に抗生物質を出した。",
   example2:"Antibiotics do not work on colds because colds are caused by viruses.",
   exampleJa2:"かぜはウイルスが原因なので、抗生物質は効かない。",
   etymologyProcess:"anti（逆に）＋ bio（生命）→ 細菌の命に逆らう薬は…？",
   etymologyConclusion:"anti（逆に）＋ bio（生命）＋ tic（形容詞）→ 体に入った細菌の命に逆らって殺す薬＝抗生物質",
   relatedWords:[
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）→ 命あるものを研究する学問"},
     {word:"biography",meaning:"伝記",breakdown:"bio（生命）＋ graph（書く）→ 人の一生を書いたもの"},
     {word:"antibody",meaning:"抗体",breakdown:"anti（逆に）＋ body（体）→ 体に入った敵に逆らう物質"},
     {synonym:true,word:"medicine",meaning:"薬",breakdown:"薬全般。antibiotic は細菌に効く薬"}]},

  {id:2100,word:"psychiatry",partOfSpeech:"名詞",meaning:"精神医学",
   meanings:["名|精神医学"],
   pronunciation:"/saɪˈkaɪətri/",part:210,
   example:"She decided to study psychiatry to help people with mental illness.",
   exampleJa:"彼女は心の病を持つ人を助けるため、精神医学を学ぶことにした。",
   example2:"Psychiatry has changed greatly over the past fifty years.",
   exampleJa2:"精神医学は、この50年で大きく変わった。",
   etymologyProcess:"psych（心）＋ iatr（治す）→ 心を治すための学問は…？",
   etymologyConclusion:"psych（心）＋ iatr（治す）＋ y（名詞）→ 心の病気を治すための医学＝精神医学",
   relatedWords:[
     {word:"psychology",meaning:"心理学",breakdown:"psych（心）＋ log（学問）→ 心のはたらきを研究する学問"},
     {word:"psychiatrist",meaning:"精神科医",breakdown:"psych（心）＋ iatr（治す）＋ ist（人）→ 心の病を治す医者"},
     {word:"pediatrician",meaning:"小児科医",breakdown:"ped（子ども）＋ iatr（治す）＋ ian（人）→ 子どもの病気を治す医者"},
     {word:"psychological",meaning:"心理的な",breakdown:"psych（心）＋ log（学問）＋ ical（形容詞）→ 心にかかわる"}]},

