  {id:251,word:"terrible",partOfSpeech:"形容詞",meaning:"ひどい；とても苦手な",
   meanings:["形|ひどい", "形|とても苦手な"],
   pronunciation:"/ˈterəbl/",part:26,
   example:"The terrible storm destroyed several houses near the river.",
   exampleJa:"ひどい嵐で、川の近くの家が数軒壊れた。",
   example2:"I am terrible at drawing faces, but I enjoy art.",
   exampleJa2:"私は顔を描くのがとても苦手だが、美術は楽しい。",
   etymologyProcess:"terr（恐れさせる）＋ ible（できる）→ 思わず恐れを感じるほど…？",
   etymologyConclusion:"terr（恐れさせる）＋ ible（できる）→ 恐れを感じさせるほど悪い＝ひどい",
   relatedWords:[
     {word:"terror",meaning:"恐怖",breakdown:"terr（恐れさせる）→ 心が凍るような恐れ"},
     {word:"terrify",meaning:"ひどく怖がらせる",breakdown:"terr（恐れさせる）＋ ify（する）→ 恐れで震えさせる"},
     {word:"terribly",meaning:"ひどく",breakdown:"terr（恐れさせる）＋ ibly（副詞）→ 恐れるほど強く"},
     {synonym:true,word:"bad",meaning:"悪い",breakdown:"広く使える「悪い」。terrible は程度がとても強い"}]},

  {id:252,word:"awful",partOfSpeech:"形容詞",meaning:"ひどく不快な；非常に悪い",
   meanings:["形|ひどく不快な", "形|非常に悪い"],
   pronunciation:"/ˈɔːfl/",part:26,
   example:"An awful smell came from the old kitchen sink.",
   exampleJa:"古い台所の流しからひどく不快なにおいがした。",
   example2:"The school lunch tasted awful, so I left some.",
   exampleJa2:"給食はひどく不快な味だったので、私は少し残した。",
   etymologyProcess:"awe（畏れ）＋ ful（満ちた）→ 畏れでいっぱいになると…？",
   etymologyConclusion:"awe（畏れ）＋ ful（満ちた）→ 畏れを起こすほどひどいものから＝ひどく不快な",
   relatedWords:[
     {word:"awe",meaning:"畏敬の念",breakdown:"awe（畏れ）→ 大きな存在を前に息をのむ"},
     {word:"awesome",meaning:"すばらしい",breakdown:"awe（畏れ）＋ some（〜を生む）→ 感動で息をのませる"},
     {word:"awfully",meaning:"ひどく",breakdown:"awe（畏れ）＋ ful（満ちた）＋ ly（副詞）→ 息をのむほど強く"},
     {synonym:true,word:"horrible",meaning:"ぞっとするほど嫌な",breakdown:"不快さや怖さを強く示す。awful と近い"}]},

  {id:253,word:"thin",partOfSpeech:"形容詞",meaning:"薄い；やせた",
   meanings:["形|薄い", "形|やせた"],
   pronunciation:"/θɪn/",part:26,
   example:"The thin ice cracked when the dog stepped on it.",
   exampleJa:"薄い氷は、犬が上に乗ると割れた。",
   example2:"This paper is too thin for our art project.",
   exampleJa2:"この紙は薄すぎて、私たちの美術の作品には使えない。",
   etymologyProcess:"thin（薄い）→ 厚みがほとんどなかったら…？",
   etymologyConclusion:"thin（薄い）→ 古くから、厚みがわずかな状態を表す＝薄い",
   hook:"紙の薄さも、人の細さも、薄いイメージ。",
   relatedWords:[
     {word:"thinly",meaning:"薄く",breakdown:"thin（薄い）＋ ly（副詞）→ 薄い層になるように"},
     {word:"thinness",meaning:"薄さ",breakdown:"thin（薄い）＋ ness（名詞）→ 厚みの少なさ"},
     {synonym:true,word:"slim",meaning:"ほっそりした",breakdown:"人の細さを好意的にいう。thin はやせすぎにも使う"},
     {synonym:true,word:"narrow",meaning:"幅が狭い",breakdown:"横幅が小さいこと。thin は厚みが小さいこと"}]},

  {id:254,word:"tight",partOfSpeech:"形容詞",meaning:"きつい；余裕のない",
   meanings:["形|きつい", "形|余裕のない"],
   pronunciation:"/taɪt/",part:26,
   example:"The tight lid kept the soup from leaking out.",
   exampleJa:"きついふたが、スープの漏れを防いだ。",
   example2:"These shoes feel tight after a long day at school.",
   exampleJa2:"学校で長い一日を過ごした後、この靴はきつく感じる。",
   etymologyProcess:"tight（しっかりした）→ すき間なくしっかり締まると…？",
   etymologyConclusion:"tight（しっかりした）→ 古い「しっかりした」の意味から＝きつい",
   hook:"服・ふた・日程に余裕がない状態を表す。",
   relatedWords:[
     {word:"tightly",meaning:"きつく",breakdown:"tight（しっかりした）＋ ly（副詞）→ すき間なく締めて"},
     {word:"tighten",meaning:"締める",breakdown:"tight（しっかりした）＋ en（〜にする）→ 締まりを強める"},
     {word:"airtight",meaning:"気密の",breakdown:"air（空気）＋ tight（しっかりした）→ 空気も通さない"},
     {synonym:true,word:"firm",meaning:"しっかりした",breakdown:"ぐらつかないこと。tight は締まりの強さに注目"}]},

  {id:255,word:"loose",partOfSpeech:"形容詞",meaning:"ゆるい；固定されていない",
   meanings:["形|ゆるい", "形|固定されていない"],
   pronunciation:"/luːs/",part:26,
   example:"A loose screw made the wooden chair feel unsafe.",
   exampleJa:"ゆるいねじのせいで、その木の椅子は危なっかしかった。",
   example2:"Wear loose clothes when you practice dancing after school.",
   exampleJa2:"放課後にダンスを練習するときは、ゆるい服を着よう。",
   etymologyProcess:"loose（縛られていない）→ 縛りが外れて自由になると…？",
   etymologyConclusion:"loose（縛られていない）→ 古い「自由な」の意味から、締まりがない状態へ＝ゆるい",
   hook:"lose（失う）と区別。loose は s を /s/ と読む。",
   relatedWords:[
     {word:"loosely",meaning:"ゆるく",breakdown:"loose（縛られていない）＋ ly（副詞）→ 縛りを弱くして"},
     {word:"loosen",meaning:"ゆるめる",breakdown:"loose（縛られていない）＋ en（〜にする）→ 縛りを弱める"},
     {word:"looseness",meaning:"ゆるさ",breakdown:"loose（縛られていない）＋ ness（名詞）→ 締まりの弱さ"},
     {synonym:true,word:"free",meaning:"自由な",breakdown:"制限を受けないこと。loose は固定の弱さも表す"}]},

  {id:256,word:"raw",partOfSpeech:"形容詞",meaning:"調理していない；未加工の",
   meanings:["形|調理していない", "形|未加工の"],
   pronunciation:"/rɔː/",part:26,
   example:"Keep raw meat away from food that is already cooked.",
   exampleJa:"調理していない肉は、すでに調理済みの食べ物から離しておこう。",
   example2:"We compared raw vegetables with cooked ones in class.",
   exampleJa2:"授業で、調理していない野菜と調理した野菜を比べた。",
   etymologyProcess:"raw（手を加えていない）→ 火も加工も加えていなければ…？",
   etymologyConclusion:"raw（手を加えていない）→ 古くからの「生の」という意味が芯＝調理していない",
   hook:"生肉・原料・未整理のデータに共通する「手つかず」。",
   relatedWords:[
     {word:"rawness",meaning:"生の状態",breakdown:"raw（手を加えていない）＋ ness（名詞）→ 手つかずの状態"},
     {synonym:true,word:"uncooked",meaning:"加熱していない",breakdown:"料理の火入れをしていない点をはっきり示す"},
     {synonym:true,word:"natural",meaning:"自然のままの",breakdown:"人の加工が少ないこと。raw は未処理に注目"},
     {synonym:true,word:"fresh",meaning:"新鮮な",breakdown:"時間がたっていないこと。生かどうかとは別"}]},

  {id:257,word:"empty",partOfSpeech:"形容詞",meaning:"空っぽの；人がいない",
   meanings:["形|空っぽの", "形|人がいない"],
   pronunciation:"/ˈempti/",part:26,
   example:"The empty bottle rolled across the floor of the bus.",
   exampleJa:"空っぽの瓶が、バスの床を転がった。",
   example2:"The classroom was empty when I returned after club practice.",
   exampleJa2:"部活の練習後に戻ると、教室は空っぽだった。",
   etymologyProcess:"empty（空っぽの）→ 中に何も残っていなければ…？",
   etymologyConclusion:"empty（空っぽの）→ 古英語の「暇な」から、何もない状態へ＝空っぽの",
   hook:"容器にも部屋にも使える。「空っぽ」が共通のイメージ。",
   relatedWords:[
     {word:"emptiness",meaning:"空虚さ",breakdown:"empty（空っぽの）＋ ness（名詞）→ 中が満たされない状態"},
     {synonym:true,word:"vacant",meaning:"空いている",breakdown:"席や部屋が使われていないことを表す"},
     {synonym:true,word:"blank",meaning:"何も書かれていない",breakdown:"紙や画面に内容がないこと。empty は中身全般"},
     {synonym:true,word:"bare",meaning:"むき出しの",breakdown:"覆いや飾りがないこと。中身の有無とは区別する"}]},

  {id:258,word:"smooth",partOfSpeech:"形容詞",meaning:"なめらかな；滞りのない",
   meanings:["形|なめらかな", "形|滞りのない"],
   pronunciation:"/smuːð/",part:26,
   example:"The smooth stone felt cool in the palm of my hand.",
   exampleJa:"なめらかな石は、手のひらでひんやりと感じられた。",
   example2:"With enough practice, your speech will sound smooth and natural.",
   exampleJa2:"十分に練習すれば、君のスピーチはなめらかで自然に聞こえるだろう。",
   etymologyProcess:"smooth（でこぼこがない）→ 引っかかるでこぼこがなければ…？",
   etymologyConclusion:"smooth（でこぼこがない）→ 古くから、手が引っかからない状態を表す＝なめらかな",
   hook:"表面のでこぼこがないことから、進行に問題がないことへ。",
   relatedWords:[
     {word:"smoothly",meaning:"順調に",breakdown:"smooth（でこぼこがない）＋ ly（副詞）→ 引っかからず進んで"},
     {word:"smoothness",meaning:"なめらかさ",breakdown:"smooth（でこぼこがない）＋ ness（名詞）→ 凹凸のなさ"},
     {synonym:true,word:"even",meaning:"平らな",breakdown:"高さや量にむらがない。smooth は手触りにも使う"},
     {synonym:true,word:"flat",meaning:"平たい",breakdown:"面の曲がりや起伏がない。手触りとは別の観点"}]},

  {id:259,word:"direct",partOfSpeech:"形容詞",meaning:"直接の；まっすぐな",
   meanings:["形|直接の", "形|まっすぐな"],
   pronunciation:"/dəˈrekt/",part:26,
   example:"We have direct contact with the local rescue team.",
   exampleJa:"私たちは地元の救助隊と直接の連絡を取っている。",
   example2:"Our school has a direct link to the university library.",
   exampleJa2:"私たちの学校には大学図書館への直接のつながりがある。",
   etymologyProcess:"di（離れて）＋ rect（まっすぐ）→ 寄り道をせずまっすぐなら…？",
   etymologyConclusion:"di（離れて）＋ rect（まっすぐ）→ 曲がりを離して、まっすぐ進むイメージ＝直接の",
   relatedWords:[
     {word:"direction",meaning:"方向",breakdown:"di（離れて）＋ rect（まっすぐ）＋ ion（名詞）→ 向かう先"},
     {word:"directly",meaning:"直接に",breakdown:"di（離れて）＋ rect（まっすぐ）＋ ly（副詞）→ 間を挟まずに"},
     {word:"correct",meaning:"正しい",breakdown:"com（すっかり）＋ rect（まっすぐ）→ 曲がりを正した"},
     {word:"rectangle",meaning:"長方形",breakdown:"rect（まっすぐ）＋ angle（角）→ 直角が四つの形"}]},

  {id:260,word:"familiar",partOfSpeech:"形容詞",meaning:"なじみのある；よく知っている",
   meanings:["形|なじみのある", "形|よく知っている"],
   pronunciation:"/fəˈmɪliər/",part:26,
   example:"A familiar voice called my name from across the street.",
   exampleJa:"なじみのある声が、通りの向こうから私の名前を呼んだ。",
   example2:"Seeing a familiar face helped me relax before the exam.",
   exampleJa2:"なじみのある顔を見て、試験前の緊張がほぐれた。",
   etymologyProcess:"famil（家族）＋ iar（形容詞）→ 家族のように近い存在なら…？",
   etymologyConclusion:"famil（家族）＋ iar（形容詞）→ 同じ家の一員のように、よく知った＝なじみのある",
   relatedWords:[
     {word:"family",meaning:"家族",breakdown:"famil（家族）→ 同じ家の中で暮らす人たち"},
     {word:"unfamiliar",meaning:"なじみのない",breakdown:"un（否定）＋ famil（家族）＋ iar（形容詞）→ 家の外の知らない存在"},
     {word:"familiarity",meaning:"よく知っていること",breakdown:"famil（家族）＋ iar（形容詞）＋ ity（名詞）→ 身内のような近さ"},
     {synonym:true,word:"known",meaning:"知られている",breakdown:"知識として知られていること。familiar は親しみも含む"}]},

  {id:261,word:"similar",partOfSpeech:"形容詞",meaning:"よく似た",
   meanings:["形|よく似た"],
   pronunciation:"/ˈsɪmələr/",part:27,
   example:"The two houses have similar windows and red roofs.",
   exampleJa:"その2軒の家には、よく似た窓と赤い屋根がある。",
   example2:"Your answer is similar to mine, but the examples differ.",
   exampleJa2:"君の答えは私のものによく似ているが、例は違う。",
   etymologyProcess:"simil（似ている）＋ ar（形容詞）→ 互いの姿が重なって見えたら…？",
   etymologyConclusion:"simil（似ている）＋ ar（形容詞）→ 同じような姿や性質を持つ＝よく似た",
   relatedWords:[
     {word:"similarly",meaning:"同様に",breakdown:"simil（似ている）＋ ar（形容詞）＋ ly（副詞）→ 似たやり方で"},
     {word:"similarity",meaning:"類似点",breakdown:"simil（似ている）＋ ar（形容詞）＋ ity（名詞）→ 姿が重なる点"},
     {word:"resemble",meaning:"似ている",breakdown:"re（強く）＋ simil（似ている）→ 姿がよく重なる"},
     {synonym:true,word:"alike",meaning:"似ている",breakdown:"似た状態を表す。similar は名詞の前にも置ける"}]},

  {id:262,word:"differ",partOfSpeech:"自動詞",meaning:"異なる",
   meanings:["自|異なる"],
   pronunciation:"/ˈdɪfər/",part:27,
   example:"The two reports differ in their explanations of the accident.",
   exampleJa:"その2つの報告書は、事故の説明が異なる。",
   example2:"Even close friends may differ on important school rules.",
   exampleJa2:"親しい友人同士でも、大事な校則について意見が異なることがある。",
   etymologyProcess:"dis（離れて）＋ fer（運ぶ）→ 別々の方向へ運ばれたら…？",
   etymologyConclusion:"dis（離れて）＋ fer（運ぶ）→ 別の方向へ運ばれ、同じでなくなる＝異なる",
   relatedWords:[
     {word:"different",meaning:"異なった",breakdown:"dis（離れて）＋ fer（運ぶ）→ 別の方向へ離れた"},
     {word:"difference",meaning:"違い",breakdown:"dis（離れて）＋ fer（運ぶ）→ 二つが離れている点"},
     {word:"offer",meaning:"申し出る",breakdown:"of（相手のほうへ）＋ fer（運ぶ）→ 相手の前へ持っていく"},
     {word:"transfer",meaning:"移す",breakdown:"trans（越えて）＋ fer（運ぶ）→ 境界を越えて運ぶ"}]},

  {id:263,word:"vary",partOfSpeech:"自動詞",meaning:"さまざまに変わる",
   meanings:["自|さまざまに変わる"],
   pronunciation:"/ˈveri/",part:27,
   example:"Ticket prices vary according to the day of the week.",
   exampleJa:"切符の値段は曜日に応じてさまざまに変わる。",
   example2:"Our practice times may vary during the summer holidays.",
   exampleJa2:"夏休み中は、私たちの練習時間がさまざまに変わるかもしれない。",
   etymologyProcess:"vari（変わる）→ 一つの形にとどまらなければ…？",
   etymologyConclusion:"vari（変わる）→ ラテン語の「変える」から、一定でなくなる＝さまざまに変わる",
   hook:"形が変わる仲間は various（さまざまな）や variety（多様さ）。",
   relatedWords:[
     {word:"various",meaning:"さまざまな",breakdown:"vari（変わる）＋ ous（形容詞）→ 一つの形に収まらない"},
     {word:"variety",meaning:"多様さ",breakdown:"vari（変わる）＋ ety（名詞）→ 違う形が並ぶこと"},
     {word:"variable",meaning:"変わりやすい",breakdown:"vari（変わる）＋ able（できる）→ 形を変えられる"},
     {word:"variation",meaning:"変化",breakdown:"vari（変わる）＋ ation（名詞）→ 元の形からの変わり方"}]},

  {id:264,word:"specific",partOfSpeech:"形容詞",meaning:"特定の；具体的な",
   meanings:["形|特定の", "形|具体的な"],
   pronunciation:"/spəˈsɪfɪk/",part:27,
   example:"The medicine is designed to treat one specific illness.",
   exampleJa:"その薬は、ある特定の病気を治すために作られている。",
   example2:"Is there a specific topic you want to discuss in class?",
   exampleJa2:"授業で話し合いたい特定の話題はありますか。",
   etymologyProcess:"speci（種類）＋ fic（作る）→ ほかと区別できる種類を作ると…？",
   etymologyConclusion:"speci（種類）＋ fic（作る）→ 一つの種類をはっきり区別する＝特定の",
   relatedWords:[
     {word:"species",meaning:"種",breakdown:"speci（種類）→ 同じ特徴を持つ生き物のまとまり"},
     {word:"special",meaning:"特別な",breakdown:"speci（種類）＋ al（形容詞）→ ほかとは区別される"},
     {word:"specialist",meaning:"専門家",breakdown:"speci（種類）＋ alist（人）→ 一つの分野を深く扱う"},
     {word:"specify",meaning:"明確に示す",breakdown:"speci（種類）＋ fy（する）→ 対象を絞って示す"}]},

  {id:265,word:"common",partOfSpeech:"形容詞",meaning:"よく見られる；共通の",
   meanings:["形|よく見られる", "形|共通の"],
   pronunciation:"/ˈkɑːmən/",part:27,
   example:"This bird is common in gardens throughout the country.",
   exampleJa:"この鳥は、国中の庭でよく見られる。",
   example2:"Spelling mistakes are common when students learn new English words.",
   exampleJa2:"生徒が新しい英単語を学ぶとき、つづりの間違いはよく見られる。",
   etymologyProcess:"com（共に）＋ mun（分け合う）→ みんなで分け持つものなら…？",
   etymologyConclusion:"com（共に）＋ mun（分け合う）→ みんなが分け持つことから、広く行き渡った＝よく見られる",
   relatedWords:[
     {word:"community",meaning:"地域社会",breakdown:"com（共に）＋ mun（分け合う）→ 暮らしを分け合う集まり"},
     {word:"communicate",meaning:"伝える",breakdown:"com（共に）＋ mun（分け合う）→ 情報を分け合う"},
     {word:"commonly",meaning:"一般に",breakdown:"com（共に）＋ mun（分け合う）→ 広く分かち持たれて"},
     {word:"uncommon",meaning:"めったにない",breakdown:"un（否定）＋ com（共に）＋ mun（分け合う）→ 広くは見られない"}]},

  {id:266,word:"unusual",partOfSpeech:"形容詞",meaning:"いつもと違う；珍しい",
   meanings:["形|いつもと違う", "形|珍しい"],
   pronunciation:"/ʌnˈjuːʒuəl/",part:27,
   example:"An unusual noise from the engine made the driver stop.",
   exampleJa:"エンジンからのいつもと違う音で、運転手は車を止めた。",
   example2:"It is unusual for our teacher to arrive late.",
   exampleJa2:"私たちの先生が遅れて来るのは、いつもと違うことだ。",
   etymologyProcess:"un（否定）＋ use（使う）＋ ual（形容詞）→ いつものやり方ではなかったら…？",
   etymologyConclusion:"un（否定）＋ use（使う）＋ ual（形容詞）→ 日ごろ使い慣れた状態ではない＝いつもと違う",
   relatedWords:[
     {word:"usual",meaning:"いつもの",breakdown:"use（使う）＋ ual（形容詞）→ 普段から使い慣れた"},
     {word:"usually",meaning:"たいてい",breakdown:"use（使う）＋ ual（形容詞）＋ ly（副詞）→ いつもどおりに"},
     {word:"use",meaning:"使う",breakdown:"use（使う）→ 道具を日々役立てる"},
     {word:"useful",meaning:"役に立つ",breakdown:"use（使う）＋ ful（満ちた）→ 使い道がたくさんある"}]},

  {id:267,word:"add",partOfSpeech:"他動詞",meaning:"付け加える",
   meanings:["他|付け加える"],
   pronunciation:"/æd/",part:27,
   example:"Add a little salt to the soup before serving it.",
   exampleJa:"出す前に、スープに塩を少し付け加えよう。",
   example2:"I added two examples to my essay during lunch.",
   exampleJa2:"昼休みに、自分の作文に例を2つ付け加えた。",
   etymologyProcess:"ad（〜へ）＋ dat（与える）→ 今あるものへさらに与えると…？",
   etymologyConclusion:"ad（〜へ）＋ dat（与える）→ 「与える」が形を変え、もとへさらに加える＝付け加える",
   relatedWords:[
     {word:"addition",meaning:"追加",breakdown:"ad（〜へ）＋ dat（与える）→ 今あるものへ足すこと"},
     {word:"additional",meaning:"追加の",breakdown:"ad（〜へ）＋ dat（与える）→ さらに足して与える"},
     {word:"donate",meaning:"寄付する",breakdown:"don（与える）＋ ate（動詞）→ 必要な人の手へ差し出す"},
     {word:"data",meaning:"データ",breakdown:"dat（与える）→ 判断の材料として与えられたもの"}]},

  {id:268,word:"increase",partOfSpeech:"自動詞",meaning:"増える",
   meanings:["自|増える"],
   pronunciation:"/ɪnˈkriːs/",part:27,
   example:"The number of visitors increases every year in this town.",
   exampleJa:"この町では訪問者の数が毎年増える。",
   example2:"The number of books I read increases during summer vacation.",
   exampleJa2:"夏休みには私が読む本の数が増える。",
   etymologyProcess:"in（中へ）＋ creas（育つ）→ 内側から大きく育っていくと…？",
   etymologyConclusion:"in（中へ）＋ creas（育つ）→ 中で育って、量や数が大きくなる＝増える",
   relatedWords:[
     {word:"decrease",meaning:"減る",breakdown:"de（下へ）＋ creas（育つ）→ 育ちが下向きになる"},
     {word:"increasingly",meaning:"ますます",breakdown:"in（中へ）＋ creas（育つ）→ 量が育ち続けて"},
     {synonym:true,word:"growth",meaning:"成長",breakdown:"大きく育つこと。increase は数や量が増えること"},
     {synonym:true,word:"grow",meaning:"育つ",breakdown:"生き物の成長にも使う。increase は数や量の増加"}]},

  {id:269,word:"reduce",partOfSpeech:"他動詞",meaning:"減らす",
   meanings:["他|減らす"],
   pronunciation:"/rɪˈduːs/",part:27,
   example:"The new buses will reduce air pollution in our city.",
   exampleJa:"新しいバスは、私たちの市の大気汚染を減らすだろう。",
   example2:"We reduced food waste by taking smaller portions at lunch.",
   exampleJa2:"昼食で取る量を少なくして、食べ物の無駄を減らした。",
   etymologyProcess:"re（戻す）＋ duc（導く）→ 小さい状態へ連れ戻すと…？",
   etymologyConclusion:"re（戻す）＋ duc（導く）→ 量を少ないところへ導き戻す＝減らす",
   relatedWords:[
     {word:"reduction",meaning:"削減",breakdown:"re（戻す）＋ duc（導く）→ 少ない状態へ戻すこと"},
     {word:"introduce",meaning:"紹介する",breakdown:"intro（内へ）＋ duc（導く）→ 仲間の中へ案内する"},
     {word:"produce",meaning:"生み出す",breakdown:"pro（前へ）＋ duc（導く）→ 形にして前へ出す"},
     {word:"educate",meaning:"教育する",breakdown:"e（外へ）＋ duc（導く）→ 子どもを導いて育てる"}]},

  {id:270,word:"divide",partOfSpeech:"他動詞",meaning:"分割する；割り算する",
   meanings:["他|分割する", "他|割り算する"],
   pronunciation:"/dɪˈvaɪd/",part:27,
   example:"Divide the cake into eight pieces before the guests arrive.",
   exampleJa:"客が到着する前に、ケーキを8つに分割しよう。",
   example2:"Our class was divided into four groups for the project.",
   exampleJa2:"その課題のため、私たちのクラスは4つの班に分割された。",
   etymologyProcess:"divid（分ける）→ 一つだったものを離していくと…？",
   etymologyConclusion:"divid（分ける）→ まとまりを別々に分ける＝分割する",
   hook:"divide A into B で「AをBに分ける」。into が分けた先。",
   relatedWords:[
     {word:"division",meaning:"分割",breakdown:"divid（分ける）→ 一つを別々にすること"},
     {word:"individual",meaning:"個人",breakdown:"in（否定）＋ divid（分ける）→ これ以上分けない一人"},
     {word:"undivided",meaning:"分割されていない",breakdown:"un（否定）＋ divid（分ける）→ まとまったままの"},
     {synonym:true,word:"separate",meaning:"分ける",breakdown:"別々に離すこと。divide は全体を区切ることに注目"}]},

  {id:271,word:"count",partOfSpeech:"他動詞",meaning:"数える",
   meanings:["他|数える"],
   pronunciation:"/kaʊnt/",part:28,
   example:"Please count the chairs before the guests enter the hall.",
   exampleJa:"客がホールに入る前に、椅子を数えてください。",
   example2:"We counted twenty kinds of birds on our school trip.",
   exampleJa2:"校外学習で、私たちは20種類の鳥を数えた。",
   etymologyProcess:"comput（計算する）→ 一つずつまとめて計算すると…？",
   etymologyConclusion:"comput（計算する）→ 一つずつ計算して全体の数を出す＝数える",
   hook:"count は数を順に数えること。computer と同じラテン語から。",
   relatedWords:[
     {word:"computer",meaning:"コンピューター",breakdown:"comput（計算する）→ 計算をまとめて行う道具"},
     {word:"discount",meaning:"割引",breakdown:"dis（離れて）＋ count（数える）→ 合計から数を引く"},
     {word:"account",meaning:"説明・口座",breakdown:"ad（〜へ）＋ count（数える）→ 数をまとめて報告する"},
     {word:"countless",meaning:"数え切れない",breakdown:"count（数える）＋ less（ない）→ 数え終わりがない"}]},

  {id:272,word:"weigh",partOfSpeech:"他動詞",meaning:"重さを量る；慎重に検討する",
   meanings:["他|重さを量る", "他|慎重に検討する"],
   pronunciation:"/weɪ/",part:28,
   example:"The clerk weighed the package before printing the shipping label.",
   exampleJa:"店員は発送用のラベルを印刷する前に、荷物の重さを量った。",
   example2:"We will weigh our vegetables after harvesting them at school.",
   exampleJa2:"学校で野菜を収穫した後、重さを量る予定だ。",
   etymologyProcess:"weigh（重さを量る）→ 持ち上げて重さを確かめると…？",
   etymologyConclusion:"weigh（重さを量る）→ 古い「持ち上げる」から、はかりで確かめる動きへ＝重さを量る",
   hook:"weigh は動詞、weight は重さという名詞。",
   relatedWords:[
     {word:"weight",meaning:"重さ",breakdown:"weigh（重さを量る）＋ t（名詞）→ はかりにかかる重み"},
     {word:"overweight",meaning:"体重が重すぎる",breakdown:"over（越えて）＋ weight（重さ）→ 適量を越えた重さ"},
     {word:"lightweight",meaning:"軽量の",breakdown:"light（軽い）＋ weight（重さ）→ 重みがわずか"},
     {synonym:true,word:"measure",meaning:"測定する",breakdown:"長さや量を広く測る。weigh は重さを測る"}]},

  {id:273,word:"quarter",partOfSpeech:"名詞",meaning:"4分の1；15分",
   meanings:["名|4分の1", "名|15分"],
   pronunciation:"/ˈkwɔːrtər/",part:28,
   example:"A quarter of the land is covered by forest.",
   exampleJa:"その土地の4分の1は森林に覆われている。",
   example2:"We finished a quarter of our homework before dinner.",
   exampleJa2:"夕食前に、私たちは宿題の4分の1を終えた。",
   etymologyProcess:"quart（4番目）＋ er（もの）→ 四つに等しく分けた一つなら…？",
   etymologyConclusion:"quart（4番目）＋ er（もの）→ 全体を四つに分けたうちの一つ＝4分の1",
   relatedWords:[
     {word:"quarterly",meaning:"年4回の",breakdown:"quart（4番目）＋ er（もの）＋ ly（形容詞）→ 年を四つに分けた"},
     {word:"quartet",meaning:"四重奏団",breakdown:"quart（4番目）＋ et（小さい）→ 四人で作る音の組"},
     {synonym:true,word:"four",meaning:"4",breakdown:"数そのもの。quarter は四つに分けた一つ"},
     {synonym:true,word:"fourth",meaning:"4番目・4分の1",breakdown:"順序にも使う。a fourth は a quarter と同じ量"}]},

  {id:274,word:"lot",partOfSpeech:"名詞",meaning:"たくさん；割り当てられた土地",
   meanings:["名|たくさん", "名|割り当てられた土地"],
   pronunciation:"/lɑːt/",part:28,
   example:"A lot of people gathered outside the new museum.",
   exampleJa:"新しい博物館の外に、たくさんの人が集まった。",
   example2:"I learned a lot from my classmates during the project.",
   exampleJa2:"その課題を通じて、クラスメートからたくさんのことを学んだ。",
   etymologyProcess:"lot（くじで決めた取り分）→ 取り分をひとまとめにすると…？",
   etymologyConclusion:"lot（くじで決めた取り分）→ くじで決めた取り分から、まとまった量へ＝たくさん",
   hook:"a lot of＋名詞で「たくさんの」。a lot だけでも量を表す。",
   relatedWords:[
     {word:"allot",meaning:"割り当てる",breakdown:"ad（〜へ）＋ lot（くじで決めた取り分）→ 一人ずつ取り分を渡す"},
     {word:"lottery",meaning:"宝くじ",breakdown:"lot（くじで決めた取り分）→ くじで当たりを分ける仕組み"},
     {synonym:true,word:"many",meaning:"多くの",breakdown:"数えられる名詞に使う。a lot of は数えない名詞にも使う"},
     {synonym:true,word:"plenty",meaning:"十分な量",breakdown:"必要を満たす多さ。a lot は量の大きさを示す"}]},

  {id:275,word:"pile",partOfSpeech:"名詞",meaning:"積み重なった山；大量",
   meanings:["名|積み重なった山", "名|大量"],
   pronunciation:"/paɪl/",part:28,
   example:"A pile of old newspapers stood beside the door.",
   exampleJa:"古新聞の積み重なった山が、ドアのそばにあった。",
   example2:"The pile of homework on my desk looks much smaller now.",
   exampleJa2:"机の上の宿題の積み重なった山は、今ではずっと小さく見える。",
   etymologyProcess:"pile（積み重なったもの）→ 物が次々と積み上がると…？",
   etymologyConclusion:"pile（積み重なったもの）→ ラテン語の「柱」から、積み上げたかたまりへ＝積み重なった山",
   hook:"a pile of books で本の山。動詞では「積み重ねる」。",
   relatedWords:[
     {word:"pillar",meaning:"柱",breakdown:"pile（積み重なったもの）→ 高く積み上げて支える柱"},
     {synonym:true,word:"mountain",meaning:"山・大量",breakdown:"巨大な量の比喩にも使う。pile は実際の積み重ねにも使う"},
     {synonym:true,word:"stack",meaning:"整然とした積み重ね",breakdown:"本や箱などが、きちんと重なったもの"},
     {synonym:true,word:"lot",meaning:"たくさん",breakdown:"量の多さを表す。pile は積み重なった形にも注目"}]},

  {id:276,word:"rate",partOfSpeech:"名詞",meaning:"割合；一定の料金",
   meanings:["名|割合", "名|一定の料金"],
   pronunciation:"/reɪt/",part:28,
   example:"The unemployment rate fell after the new factory opened.",
   exampleJa:"新しい工場が開いた後、失業の割合が下がった。",
   example2:"Our class had the highest attendance rate in the school.",
   exampleJa2:"私たちのクラスは、学校で出席の割合が最も高かった。",
   etymologyProcess:"rat（計算する）→ 計算して基準と比べると…？",
   etymologyConclusion:"rat（計算する）→ ラテン語の「計算された」から、比べて示す数へ＝割合",
   hook:"rate は基準あたりの量。金額なら料金、進み方なら速度。",
   relatedWords:[
     {word:"ratio",meaning:"比率",breakdown:"rat（計算する）→ 二つの量を計算して比べる"},
     {word:"reason",meaning:"理由",breakdown:"rat（計算する）→ 計算をたどるように考えた根拠"},
     {word:"reasonable",meaning:"理にかなった",breakdown:"rat（計算する）＋ able（できる）→ 理由を筋道立てて考えられる"},
     {synonym:true,word:"speed",meaning:"速さ",breakdown:"移動する速さ。rate は変化や発生の割合にも使う"}]},

  {id:277,word:"figure",partOfSpeech:"名詞",meaning:"数値；人物；図",
   meanings:["名|数値", "名|人物", "名|図"],
   pronunciation:"/ˈfɪɡjər/",part:28,
   example:"The latest figure shows a sharp rise in sales.",
   exampleJa:"最新の数値は、売り上げの急な増加を示している。",
   example2:"Check every figure in your report before handing it in.",
   exampleJa2:"提出前に、レポートの数値を一つずつ確認しよう。",
   etymologyProcess:"fig（形作る）＋ ure（名詞）→ 形にして表したものなら…？",
   etymologyConclusion:"fig（形作る）＋ ure（名詞）→ 形作られた姿から、数を表す記号へ＝数値",
   relatedWords:[
     {word:"figurative",meaning:"比喩的な",breakdown:"fig（形作る）＋ ure（名詞）＋ ative（形容詞）→ 言葉で別の姿を描く"},
     {word:"figurine",meaning:"小さな像",breakdown:"fig（形作る）＋ ure（名詞）＋ ine（小さい）→ 小さく形作った像"},
     {synonym:true,word:"number",meaning:"数",breakdown:"数を広く指す。figure は資料に示された数値にも使う"},
     {synonym:true,word:"shape",meaning:"形",breakdown:"外側の形。figure は人の姿や図も表す"}]},

  {id:278,word:"lack",partOfSpeech:"名詞",meaning:"不足",
   meanings:["名|不足"],
   pronunciation:"/læk/",part:28,
   example:"A lack of clean water caused problems in the village.",
   exampleJa:"きれいな水の不足が、その村で問題を引き起こした。",
   example2:"My lack of sleep made it hard to concentrate in class.",
   exampleJa2:"睡眠不足のせいで、私は授業に集中しにくかった。",
   etymologyProcess:"lack（足りない）→ 必要なものが欠けていたら…？",
   etymologyConclusion:"lack（足りない）→ 古い「欠けている」の意味が芯＝不足",
   hook:"a lack of＋名詞で「〜の不足」。動詞なら of は不要。",
   relatedWords:[
     {word:"lacking",meaning:"欠けている",breakdown:"lack（足りない）＋ ing（形容詞）→ 必要な部分が抜けた"},
     {synonym:true,word:"shortage",meaning:"不足分",breakdown:"必要量に届かないこと。lack は全くない場合も表す"},
     {synonym:true,word:"absence",meaning:"不在",breakdown:"そこにないこと。lack は必要なのに足りない点に注目"},
     {synonym:true,word:"need",meaning:"必要",breakdown:"必要としていること。lack は不足という状態"}]},

  {id:279,word:"extra",partOfSpeech:"形容詞",meaning:"追加の；余分な",
   meanings:["形|追加の", "形|余分な"],
   pronunciation:"/ˈekstrə/",part:28,
   example:"The hotel charges an extra fee for late arrivals.",
   exampleJa:"そのホテルは、遅い到着に追加の料金を請求する。",
   example2:"Our teacher gave us extra time to finish the test.",
   exampleJa2:"先生は、テストを終えるための追加の時間をくれた。",
   etymologyProcess:"extra（範囲の外へ）→ 決まった範囲の外に足すなら…？",
   etymologyConclusion:"extra（範囲の外へ）→ 通常の範囲から外に出て加わる＝追加の",
   hook:"ラテン語で「外に」。決まった量の外に足すイメージ。",
   relatedWords:[
     {word:"extraordinary",meaning:"並外れた",breakdown:"extra（範囲の外へ）＋ ordinary（ふつうの）→ 普通の外に出た"},
     {word:"extracurricular",meaning:"課外の",breakdown:"extra（範囲の外へ）＋ curricul（課程）→ 授業の範囲の外の"},
     {synonym:true,word:"additional",meaning:"付け加えた",breakdown:"今ある量に加えたこと。extra に近い"},
     {synonym:true,word:"spare",meaning:"予備の",breakdown:"必要なときのために残してあること"}]},

  {id:280,word:"ready",partOfSpeech:"形容詞",meaning:"準備ができた；進んで取り組む",
   meanings:["形|準備ができた", "形|進んで取り組む"],
   pronunciation:"/ˈredi/",part:28,
   example:"The rescue team was ready to leave before sunrise.",
   exampleJa:"救助隊は、日の出前に出発の準備ができていた。",
   example2:"Are you ready for the science test tomorrow morning?",
   exampleJa2:"明日の朝の理科のテストの準備はできていますか。",
   etymologyProcess:"ready（整った）→ すぐ動けるように整うと…？",
   etymologyConclusion:"ready（整った）→ 古い「整った」の意味から、すぐ使える状態へ＝準備ができた",
   hook:"be ready to do で「〜する準備ができている」。",
   relatedWords:[
     {word:"already",meaning:"すでに",breakdown:"all（すっかり）＋ ready（整った）→ もう整っている"},
     {word:"readily",meaning:"快く・容易に",breakdown:"ready（整った）＋ ly（副詞）→ すぐ動ける態勢で"},
     {word:"readiness",meaning:"準備ができた状態",breakdown:"ready（整った）＋ ness（名詞）→ すぐ動ける状態"},
     {synonym:true,word:"prepared",meaning:"用意ができた",breakdown:"前もって準備したこと。ready は今すぐ動けること"}]},

  {id:281,word:"prepare",partOfSpeech:"他動詞",meaning:"準備する",
   meanings:["他|準備する"],
   pronunciation:"/prɪˈper/",part:29,
   example:"The chef prepared a simple meal for the tired travelers.",
   exampleJa:"料理人は、疲れた旅行者のために簡単な食事を準備した。",
   example2:"We will prepare our presentation together after school tomorrow.",
   exampleJa2:"明日の放課後、私たちは一緒に発表を準備する予定だ。",
   etymologyProcess:"pre（先に）＋ pair（整える）→ 必要になる前に整えると…？",
   etymologyConclusion:"pre（先に）＋ pair（整える）→ 使うときより先に、整った状態にする＝準備する",
   relatedWords:[
     {word:"preparation",meaning:"準備",breakdown:"pre（先に）＋ pair（整える）→ 前もって整えること"},
     {word:"repair",meaning:"修理する",breakdown:"re（再び）＋ pair（整える）→ もう一度使えるように整える"},
     {word:"prepared",meaning:"準備のできた",breakdown:"pre（先に）＋ pair（整える）→ 前もって整えてある"},
     {synonym:true,word:"ready",meaning:"準備ができた",breakdown:"今すぐ使える状態。prepare はその状態にする動作"}]},

  {id:282,word:"adjust",partOfSpeech:"自動詞",meaning:"慣れる",
   meanings:["自|慣れる"],
   pronunciation:"/əˈdʒʌst/",part:29,
   example:"New workers need time to adjust to the busy office.",
   exampleJa:"新しい従業員には、その忙しい職場に慣れる時間が必要だ。",
   example2:"I gradually adjusted to life at my new school.",
   exampleJa2:"私は、新しい学校での生活に少しずつ慣れた。",
   etymologyProcess:"ad（〜へ）＋ juxta（すぐそばに）→ 相手にぴったり寄せていくと…？",
   etymologyConclusion:"ad（〜へ）＋ juxta（すぐそばに）→ 状況のすぐそばへ自分を合わせる＝慣れる",
   relatedWords:[
     {word:"adjustment",meaning:"調整",breakdown:"ad（〜へ）＋ juxta（すぐそばに）→ ぴったり合うように寄せる"},
     {word:"adjustable",meaning:"調整できる",breakdown:"ad（〜へ）＋ juxta（すぐそばに）→ 合う位置へ動かせる"},
     {synonym:true,word:"change",meaning:"変える",breakdown:"広く変化を表す。adjust は条件に合うように変える"},
     {synonym:true,word:"fit",meaning:"合う",breakdown:"大きさや条件が合うこと。adjust は合うように変える"}]},

  {id:283,word:"apply",partOfSpeech:"自動詞",meaning:"当てはまる；申し込む",
   meanings:["自|当てはまる", "自|申し込む"],
   pronunciation:"/əˈplaɪ/",part:29,
   example:"The same safety rules apply to every worker here.",
   exampleJa:"ここでは、同じ安全規則がすべての従業員に当てはまる。",
   example2:"This advice may apply to your plans for university.",
   exampleJa2:"この助言は、君の大学進学の計画にも当てはまるかもしれない。",
   etymologyProcess:"ad（〜へ）＋ pli（折る）→ 相手のほうへ折り合わせると…？",
   etymologyConclusion:"ad（〜へ）＋ pli（折る）→ 対象のほうへ折り合わせ、ぴったり合う＝当てはまる",
   relatedWords:[
     {word:"application",meaning:"申請・応用",breakdown:"ad（〜へ）＋ pli（折る）→ 相手や目的へ合わせること"},
     {word:"applicant",meaning:"応募者",breakdown:"ad（〜へ）＋ pli（折る）→ 求める先へ申し出る人"},
     {word:"reply",meaning:"返答する",breakdown:"re（戻す）＋ pli（折る）→ 言葉を相手へ折り返す"},
     {word:"multiply",meaning:"掛ける",breakdown:"multi（多く）＋ pli（折る）→ 何重にも折り重ねる"}]},

  {id:284,word:"suit",partOfSpeech:"他動詞",meaning:"人の都合に合う；似合う",
   meanings:["他|人の都合に合う", "他|似合う"],
   pronunciation:"/suːt/",part:29,
   example:"An afternoon meeting would suit everyone on the team.",
   exampleJa:"午後の会議なら、チームの全員の都合に合うだろう。",
   example2:"Does this study schedule suit you during the exam period?",
   exampleJa2:"試験期間中、この勉強の予定は君の都合に合いますか。",
   etymologyProcess:"suit（付き従う）→ 相手にぴったり付き従うと…？",
   etymologyConclusion:"suit（付き従う）→ ラテン語の「従う」から、相手に合うことへ＝人の都合に合う",
   hook:"服が人に似合うことも、予定が人に合うことも表せる。",
   relatedWords:[
     {word:"suitable",meaning:"適した",breakdown:"suit（付き従う）＋ able（できる）→ 相手にぴったり合わせられる"},
     {word:"suitcase",meaning:"スーツケース",breakdown:"suit（付き従う）＋ case（箱）→ 一そろいの服を入れる箱"},
     {word:"suite",meaning:"一続きの部屋",breakdown:"suit（付き従う）→ 一つの部屋に次が付き従う"},
     {synonym:true,word:"fit",meaning:"大きさが合う",breakdown:"サイズが合うこと。suit は好みや事情に合うこと"}]},

  {id:285,word:"case",partOfSpeech:"名詞",meaning:"場合；事例",
   meanings:["名|場合", "名|事例"],
   pronunciation:"/keɪs/",part:29,
   example:"In that case, we should ask a local guide.",
   exampleJa:"その場合は、地元の案内人に頼むべきだ。",
   example2:"Keep a spare pen in case your first one breaks.",
   exampleJa2:"最初のペンが壊れる場合に備えて、予備のペンを持っておこう。",
   etymologyProcess:"cad（落ちる）→ 出来事が降りかかってきたら…？",
   etymologyConclusion:"cad（落ちる）→ ラテン語の「起こったこと」から、一つの状況へ＝場合",
   hook:"箱の case は別の由来。こちらは起こった出来事を表す。",
   relatedWords:[
     {word:"casual",meaning:"何気ない",breakdown:"cad（落ちる）＋ ual（形容詞）→ 偶然その場に落ちたような"},
     {word:"occasion",meaning:"機会・時",breakdown:"oc（〜に向かって）＋ cad（落ちる）→ 巡り合わせが訪れる時"},
     {word:"chance",meaning:"機会",breakdown:"cad（落ちる）→ 偶然目の前に落ちてきた巡り合わせ"},
     {synonym:true,word:"situation",meaning:"状況",breakdown:"周りの事情全体。case は一つの事例や場合を指す"}]},

  {id:286,word:"scene",partOfSpeech:"名詞",meaning:"場面；現場",
   meanings:["名|場面", "名|現場"],
   pronunciation:"/siːn/",part:29,
   example:"The final scene of the film made everyone cry.",
   exampleJa:"その映画の最後の場面で、誰もが泣いた。",
   example2:"We practiced the opening scene again after school today.",
   exampleJa2:"今日の放課後、私たちは冒頭の場面をもう一度練習した。",
   etymologyProcess:"scene（舞台の背景）→ 舞台に広がる光景を切り取ると…？",
   etymologyConclusion:"scene（舞台の背景）→ ギリシャ語の「幕屋」から、劇の舞台や一場面へ＝場面",
   hook:"映画や劇の一場面。事故の現場にも使われる。",
   relatedWords:[
     {word:"scenery",meaning:"景色",breakdown:"scene（舞台の背景）＋ ry（もの）→ 目の前に広がる背景"},
     {word:"scenic",meaning:"景色のよい",breakdown:"scene（舞台の背景）＋ ic（形容詞）→ 背景が美しく見える"},
     {synonym:true,word:"stage",meaning:"舞台",breakdown:"演技をする場所。scene はそこで展開される一場面"},
     {synonym:true,word:"setting",meaning:"舞台設定",breakdown:"物語が起きる場所や時代。scene は一つの場面"}]},

  {id:287,word:"chance",partOfSpeech:"名詞",meaning:"機会；見込み",
   meanings:["名|機会", "名|見込み"],
   pronunciation:"/tʃæns/",part:29,
   example:"The trip gave me a chance to speak English.",
   exampleJa:"その旅行は、私に英語を話す機会を与えてくれた。",
   example2:"You will have another chance to take the test.",
   exampleJa2:"君には、その試験を受ける機会がもう一度ある。",
   etymologyProcess:"cad（落ちる）→ 思いがけず目の前に落ちてきたら…？",
   etymologyConclusion:"cad（落ちる）→ さいころの落ち方のような巡り合わせから＝機会",
   hook:"by chance は「偶然に」。巡ってきた機会というイメージ。",
   relatedWords:[
     {word:"accident",meaning:"事故",breakdown:"ad（〜へ）＋ cad（落ちる）→ 思いがけず降りかかる出来事"},
     {word:"occasion",meaning:"機会・時",breakdown:"oc（〜に向かって）＋ cad（落ちる）→ 巡り合わせが来る時"},
     {word:"case",meaning:"場合",breakdown:"cad（落ちる）→ 降りかかってきた一つの出来事"},
     {synonym:true,word:"opportunity",meaning:"好機",breakdown:"何かをするのによい機会。chance は偶然にも注目"}]},

  {id:288,word:"opportunity",partOfSpeech:"名詞",meaning:"好機",
   meanings:["名|好機"],
   pronunciation:"/ˌɑːpərˈtuːnəti/",part:29,
   example:"The new bridge offers an opportunity to develop local trade.",
   exampleJa:"新しい橋は、地元の商業を発展させる好機をもたらす。",
   example2:"Joining the club was an opportunity to make new friends.",
   exampleJa2:"入部は、新しい友達を作る好機だった。",
   etymologyProcess:"op（〜に向かって）＋ portus（港）→ 港へ向かう風が吹いたら…？",
   etymologyConclusion:"op（〜に向かって）＋ portus（港）→ 港へ進むのに都合のよい状態から＝好機",
   relatedWords:[
     {word:"opportune",meaning:"時宜にかなった",breakdown:"op（〜に向かって）＋ portus（港）→ 港へ向かうのに都合がよい"},
     {word:"port",meaning:"港",breakdown:"portus（港）→ 船が出入りする入口"},
     {word:"airport",meaning:"空港",breakdown:"air（空気）＋ portus（港）→ 空の乗り物が出入りする港"},
     {synonym:true,word:"chance",meaning:"機会",breakdown:"偶然巡ってきた機会にも使う。opportunity は好条件に注目"}]},

  {id:289,word:"experience",partOfSpeech:"名詞",meaning:"経験；体験",
   meanings:["名|経験", "名|体験"],
   pronunciation:"/ɪkˈspɪriəns/",part:29,
   example:"Her experience as a nurse helped during the emergency.",
   exampleJa:"看護師としての彼女の経験が、その緊急時に役立った。",
   example2:"I gained useful experience by helping at our school festival.",
   exampleJa2:"文化祭の手伝いをして、役立つ経験を積んだ。",
   etymologyProcess:"ex（外へ）＋ peri（試す）＋ ence（名詞）→ 実際に試して確かめたことなら…？",
   etymologyConclusion:"ex（外へ）＋ peri（試す）＋ ence（名詞）→ 試して結果を取り出すイメージから、実地で得たもの＝経験",
   relatedWords:[
     {word:"experiment",meaning:"実験",breakdown:"ex（外へ）＋ peri（試す）→ 実際に試して確かめること"},
     {word:"expert",meaning:"専門家",breakdown:"ex（外へ）＋ peri（試す）→ 多く試して詳しくなった人"},
     {word:"experienced",meaning:"経験豊富な",breakdown:"ex（外へ）＋ peri（試す）→ 実際に試したことが多い"},
     {synonym:true,word:"practice",meaning:"練習",breakdown:"上達のために繰り返すこと。experience は体験の蓄積"}]},

  {id:290,word:"time",partOfSpeech:"名詞",meaning:"時間；回数",
   meanings:["名|時間", "名|回数"],
   pronunciation:"/taɪm/",part:29,
   example:"We need more time to finish repairing the bridge.",
   exampleJa:"その橋の修理を終えるには、もっと時間が必要だ。",
   example2:"How much time do you spend studying after dinner?",
   exampleJa2:"夕食後、どれくらいの時間を勉強に使っていますか。",
   etymologyProcess:"time（時間の区切り）→ 流れの中の一部分を区切ると…？",
   etymologyConclusion:"time（時間の区切り）→ 古くから、続く流れの一区切りを表す＝時間",
   hook:"some time はある程度の時間、three times なら3回。",
   relatedWords:[
     {word:"timely",meaning:"時宜にかなった",breakdown:"time（時間の区切り）＋ ly（形容詞）→ ちょうどよい時の"},
     {word:"timetable",meaning:"時間割",breakdown:"time（時間の区切り）＋ table（板）→ 時を並べた表"},
     {word:"lifetime",meaning:"生涯",breakdown:"life（命）＋ time（時間の区切り）→ 命が続く間"},
     {word:"bedtime",meaning:"就寝時刻",breakdown:"bed（ベッド）＋ time（時間の区切り）→ ベッドに入る時"}]},

  {id:291,word:"spring",partOfSpeech:"名詞",meaning:"春；泉",
   meanings:["名|春", "名|泉"],
   pronunciation:"/sprɪŋ/",part:30,
   example:"Wild flowers cover the hillside every spring after the snow melts.",
   exampleJa:"毎年春に雪が解けると、野の花が丘の斜面を覆う。",
   example2:"Our school will hold a sports festival next spring.",
   exampleJa2:"私たちの学校は、来年の春に体育祭を開く予定だ。",
   etymologyProcess:"spring（跳び出す）→ 芽が地面から跳び出すころは…？",
   etymologyConclusion:"spring（跳び出す）→ 芽が勢いよく出てくる季節から＝春",
   hook:"芽が出る春、水が出る泉、跳ねるばねは同じ芯。",
   relatedWords:[
     {word:"springtime",meaning:"春の季節",breakdown:"spring（跳び出す）＋ time（時間の区切り）→ 芽が出る時季"},
     {word:"offspring",meaning:"子孫",breakdown:"off（離れて）＋ spring（跳び出す）→ 親から生まれ出た命"},
     {word:"springboard",meaning:"踏み切り板",breakdown:"spring（跳び出す）＋ board（板）→ 跳び出すための板"},
     {synonym:true,word:"season",meaning:"季節",breakdown:"一年の中の季節全般。spring はそのうちの春"}]},

  {id:292,word:"minute",partOfSpeech:"名詞",meaning:"分；ほんの短い間",
   meanings:["名|分", "名|ほんの短い間"],
   pronunciation:"/ˈmɪnɪt/",part:30,
   example:"The train leaves in one minute, so please hurry.",
   exampleJa:"電車はあと1分で出発するので、急いでください。",
   example2:"We had only ten minutes to finish the quiz.",
   exampleJa2:"私たちには、その小テストを終えるのに10分しかなかった。",
   etymologyProcess:"min（小さい）→ 一時間を小さく区切ったら…？",
   etymologyConclusion:"min（小さい）→ 時間を小さい部分に分けたもの＝分",
   hook:"時間の「分」は /ˈmɪnɪt/。「微小な」の minute は発音が違う。",
   relatedWords:[
     {word:"diminish",meaning:"小さくする",breakdown:"de（すっかり）＋ min（小さい）→ 大きさを少し削る"},
     {word:"minimum",meaning:"最小限",breakdown:"min（小さい）→ これ以上小さくできない量"},
     {word:"minus",meaning:"引く・マイナス",breakdown:"min（小さい）→ 元の数より小さくする"},
     {synonym:true,word:"moment",meaning:"瞬間",breakdown:"短いひととき。minute は正確には60秒"}]},

  {id:293,word:"age",partOfSpeech:"名詞",meaning:"年齢；時代",
   meanings:["名|年齢", "名|時代"],
   pronunciation:"/eɪdʒ/",part:30,
   example:"Children under the age of six can enter free.",
   exampleJa:"年齢が6歳未満の子どもは、無料で入場できる。",
   example2:"At my age, my father was already working abroad.",
   exampleJa2:"私の年齢のころ、父はすでに海外で働いていた。",
   etymologyProcess:"age（生きてきた時間）→ 生まれてからの時間を数えると…？",
   etymologyConclusion:"age（生きてきた時間）→ ラテン語の「生きた期間」から＝年齢",
   hook:"年齢も時代も、ある長さを持つ時間のまとまり。",
   relatedWords:[
     {word:"teenage",meaning:"10代の",breakdown:"teen（13〜19）＋ age（生きてきた時間）→ 10代の年齢の"},
     {word:"aged",meaning:"〜歳の・高齢の",breakdown:"age（生きてきた時間）＋ ed（〜された）→ 年月を重ねた"},
     {word:"middle-aged",meaning:"中年の",breakdown:"middle（中間）＋ age（生きてきた時間）→ 人生の中ごろの"},
     {synonym:true,word:"year",meaning:"年",breakdown:"時間を数える単位。age は生まれてからの年数"}]},

  {id:294,word:"generation",partOfSpeech:"名詞",meaning:"世代；生成",
   meanings:["名|世代", "名|生成"],
   pronunciation:"/ˌdʒenəˈreɪʃn/",part:30,
   example:"Each generation passes its stories on to the next.",
   exampleJa:"それぞれの世代が、自分たちの物語を次へ伝える。",
   example2:"Our generation can use technology to solve new problems.",
   exampleJa2:"私たちの世代は、新しい問題の解決に技術を使える。",
   etymologyProcess:"gener（生み出す）＋ ation（名詞）→ 同じころに生まれた人たちなら…？",
   etymologyConclusion:"gener（生み出す）＋ ation（名詞）→ 同じ時期に生み出された人々のまとまり＝世代",
   relatedWords:[
     {word:"generate",meaning:"生み出す",breakdown:"gener（生み出す）＋ ate（動詞）→ 新しいものを生む"},
     {word:"generator",meaning:"発電機",breakdown:"gener（生み出す）＋ ator（もの）→ 電気を生み出す機械"},
     {word:"general",meaning:"一般的な",breakdown:"gener（生み出す）＋ al（形容詞）→ 生まれを同じくする種類全体に関わる"},
     {synonym:true,word:"age group",meaning:"年齢層",breakdown:"近い年齢の集まり。generation は同時代を生きる世代"}]},

  {id:295,word:"anniversary",partOfSpeech:"名詞",meaning:"記念日",
   meanings:["名|記念日"],
   pronunciation:"/ˌænɪˈvɜːrsəri/",part:30,
   example:"They planted a tree on their tenth wedding anniversary.",
   exampleJa:"彼らは結婚10周年の記念日に木を植えた。",
   example2:"We will celebrate the fiftieth anniversary of our school next week.",
   exampleJa2:"来週、私たちは学校の創立50周年の記念日を祝う。",
   etymologyProcess:"ann（年）＋ vers（回る）＋ ary（形容詞）→ 一年が回って同じ日に戻ると…？",
   etymologyConclusion:"ann（年）＋ vers（回る）＋ ary（形容詞）→ 年がひと巡りして戻ってくる日＝記念日",
   relatedWords:[
     {word:"annual",meaning:"毎年の",breakdown:"ann（年）＋ ual（形容詞）→ 一年ごとに巡る"},
     {word:"universe",meaning:"宇宙",breakdown:"uni（1つの）＋ vers（回る）→ 一つにまとまった全世界"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（戻す）＋ vers（回る）→ 向きを反対へ回す"},
     {synonym:true,word:"birthday",meaning:"誕生日",breakdown:"生まれた日の記念日。anniversary は結婚や創立にも使う"}]},

  {id:296,word:"recently",partOfSpeech:"副詞",meaning:"最近",
   meanings:["副|最近"],
   pronunciation:"/ˈriːsntli/",part:30,
   example:"A small bakery recently opened next to the station.",
   exampleJa:"最近、駅の隣に小さなパン屋が開店した。",
   example2:"Have you read any interesting books for class recently?",
   exampleJa2:"最近、授業のために何か面白い本を読みましたか。",
   etymologyProcess:"recent（新しい）＋ ly（副詞）→ まだ新しさが残るころなら…？",
   etymologyConclusion:"recent（新しい）＋ ly（副詞）→ 出来事がまだ新しく感じられる時期に＝最近",
   relatedWords:[
     {word:"recent",meaning:"最近の",breakdown:"recent（新しい）→ まだ時があまりたっていない"},
     {word:"recency",meaning:"新しさ",breakdown:"recent（新しい）＋ cy（名詞）→ どれだけ最近かという度合い"},
     {synonym:true,word:"lately",meaning:"近ごろ",breakdown:"このところ続く状況に使いやすい。recently は一度の出来事にも使う"},
     {synonym:true,word:"newly",meaning:"新たに",breakdown:"何かが新しく起きた直後を表す"}]},

  {id:297,word:"used",partOfSpeech:"形容詞",meaning:"慣れている",
   meanings:["形|慣れている"],
   pronunciation:"/juːst/",part:30,
   example:"The workers are used to the noise from the machines.",
   exampleJa:"その従業員たちは、機械の騒音に慣れている。",
   example2:"I am used to getting up early for club practice.",
   exampleJa2:"私は、部活の練習のために早起きすることに慣れている。",
   etymologyProcess:"use（使う）＋ ed（〜された）→ 何度も使ってなじんでいたら…？",
   etymologyConclusion:"use（使う）＋ ed（〜された）→ 繰り返し触れて、使い慣れた状態になる＝慣れている",
   relatedWords:[
     {word:"use",meaning:"使う",breakdown:"use（使う）→ 道具を日々役立てる"},
     {word:"user",meaning:"使用者",breakdown:"use（使う）＋ er（人）→ 道具を手に取る人"},
     {word:"reuse",meaning:"再利用する",breakdown:"re（再び）＋ use（使う）→ もう一度役立てる"},
     {word:"useful",meaning:"役に立つ",breakdown:"use（使う）＋ ful（満ちた）→ 使い道がたくさんある"}]},

  {id:298,word:"early",partOfSpeech:"副詞",meaning:"早く；初期に",
   meanings:["副|早く", "副|初期に"],
   pronunciation:"/ˈɜːrli/",part:30,
   example:"The doctor arrived early to check on the patients.",
   exampleJa:"医師は、患者の様子を見るために早く到着した。",
   example2:"If we finish early, we can play basketball after class.",
   exampleJa2:"早く終われば、授業後にバスケットボールができる。",
   etymologyProcess:"ere（前に）＋ ly（副詞）→ いつもの時より前だったら…？",
   etymologyConclusion:"ere（前に）＋ ly（副詞）→ 予定した時より前、または始まりに近い時に＝早く",
   relatedWords:[
     {word:"earlier",meaning:"より早く",breakdown:"ere（前に）＋ ly（副詞）＋ er（より）→ さらに前の時に"},
     {word:"earliest",meaning:"最も早い",breakdown:"ere（前に）＋ ly（副詞）＋ est（最も）→ 一番前の時の"},
     {synonym:true,word:"soon",meaning:"間もなく",breakdown:"今から少し後。early は予定や基準より前"},
     {synonym:true,word:"ahead",meaning:"前方に・先に",breakdown:"位置や進み具合が先にあることを表す"}]},

  {id:299,word:"first",partOfSpeech:"形容詞",meaning:"最初の；第1の",
   meanings:["形|最初の", "形|第1の"],
   pronunciation:"/fɜːrst/",part:30,
   example:"The first train leaves this station before six every morning.",
   exampleJa:"最初の電車は、毎朝6時前にこの駅を出発する。",
   example2:"My first speech in English was about our school garden.",
   exampleJa2:"私の最初の英語のスピーチは、学校の庭についてだった。",
   etymologyProcess:"fore（前に）＋ est（最も）→ いちばん前にあるものなら…？",
   etymologyConclusion:"fore（前に）＋ est（最も）→ 前である度合いが最も大きい＝最初の",
   relatedWords:[
     {word:"foremost",meaning:"最も重要な",breakdown:"fore（前に）＋ most（最も）→ 一番前に出る"},
     {word:"forehead",meaning:"額",breakdown:"fore（前に）＋ head（頭）→ 頭の前側"},
     {word:"foresee",meaning:"予見する",breakdown:"fore（前に）＋ see（見る）→ 起こる前に見る"},
     {word:"firstly",meaning:"第一に",breakdown:"fore（前に）＋ est（最も）＋ ly（副詞）→ 一番先に述べると"}]},

  {id:300,word:"latest",partOfSpeech:"形容詞",meaning:"最新の",
   meanings:["形|最新の"],
   pronunciation:"/ˈleɪtɪst/",part:30,
   example:"The latest report includes data from all major cities.",
   exampleJa:"最新の報告書には、すべての主要都市のデータが含まれている。",
   example2:"Have you seen the latest issue of our school newspaper?",
   exampleJa2:"学校新聞の最新の号を見ましたか。",
   etymologyProcess:"late（遅い）＋ est（最も）→ 時間の流れで一番後ろなら…？",
   etymologyConclusion:"late（遅い）＋ est（最も）→ 最も遅い時点に現れた、いちばん新しい＝最新の",
   relatedWords:[
     {word:"late",meaning:"遅い",breakdown:"late（遅い）→ 決まった時より後ろにずれる"},
     {word:"later",meaning:"後で",breakdown:"late（遅い）＋ er（より）→ 今より後ろの時点で"},
     {word:"lately",meaning:"近ごろ",breakdown:"late（遅い）＋ ly（副詞）→ 最近の時間のあたりで"},
     {synonym:true,word:"newest",meaning:"最も新しい",breakdown:"古くない度合いが最大。latest は発表の順序にも使う"}]},

  {id:301,word:"modern",partOfSpeech:"形容詞",meaning:"現代の；近代的な",
   meanings:["形|現代の", "形|近代的な"],
   pronunciation:"/ˈmɑːdərn/",part:31,
   example:"Modern hospitals use computers to keep records of their patients.",
   exampleJa:"現代の病院は、患者の記録を保存するためにコンピューターを使う。",
   example2:"We compared modern art with older paintings in class.",
   exampleJa2:"授業で、現代の美術と昔の絵画を比べた。",
   etymologyProcess:"mod（今）＋ ern（形容詞）→ 今の時代に属するものなら…？",
   etymologyConclusion:"mod（今）＋ ern（形容詞）→ ラテン語の「今」を表す言葉から＝現代の",
   relatedWords:[
     {word:"modernize",meaning:"近代化する",breakdown:"mod（今）＋ ern（形容詞）＋ ize（する）→ 今の時代に合わせる"},
     {word:"modernization",meaning:"近代化",breakdown:"mod（今）＋ ern（形容詞）→ 今の仕組みへ変えること"},
     {synonym:true,word:"current",meaning:"現在の",breakdown:"今進行中のこと。modern は現代的な様式にも使う"},
     {synonym:true,word:"new",meaning:"新しい",breakdown:"古くないこと。modern は時代の特徴に注目"}]},

  {id:302,word:"ancient",partOfSpeech:"形容詞",meaning:"古代の；大昔の",
   meanings:["形|古代の", "形|大昔の"],
   pronunciation:"/ˈeɪnʃənt/",part:31,
   example:"The museum displays tools used by people in ancient Egypt.",
   exampleJa:"その博物館は、古代のエジプトの人々が使った道具を展示している。",
   example2:"Our history class will study ancient cities next month.",
   exampleJa2:"来月、私たちの歴史の授業で古代の都市を学ぶ予定だ。",
   etymologyProcess:"ante（前に）→ 今よりはるか前の時代なら…？",
   etymologyConclusion:"ante（前に）→ ラテン語の「前に」から、ずっと昔のことへ＝古代の",
   hook:"ただ古い old より、はるか昔の時代を強く感じさせる。",
   relatedWords:[
     {word:"ancestor",meaning:"祖先",breakdown:"ante（前に）＋ ced（行く）→ 自分より前を歩んだ人"},
     {word:"advance",meaning:"前進する",breakdown:"ante（前に）→ 前のほうへ進み出る"},
     {synonym:true,word:"old",meaning:"古い",breakdown:"年代が前であること。ancient は大昔という響き"},
     {word:"antique",meaning:"骨董の",breakdown:"ante（前に）→ 昔から残る価値ある品の"}]},

  {id:303,word:"spend",partOfSpeech:"他動詞",meaning:"時間を費やす；お金を使う",
   meanings:["他|時間を費やす", "他|お金を使う"],
   pronunciation:"/spend/",part:31,
   example:"Volunteers spend their weekends helping families in the village.",
   exampleJa:"ボランティアは、村の家族を手伝うことに週末の時間を費やす。",
   example2:"I spent two hours practicing the piano after school.",
   exampleJa2:"私は放課後、ピアノの練習に2時間を費やした。",
   etymologyProcess:"pend（重さを量る）→ はかりで量って支払うと…？",
   etymologyConclusion:"pend（重さを量る）→ お金を量って払うことから、持ち時間を使うことへ＝時間を費やす",
   hook:"spend＋時間＋doing で「〜するのに時間を費やす」。",
   relatedWords:[
     {word:"expense",meaning:"費用",breakdown:"ex（外へ）＋ pens（重さを量る）→ 量って外へ支払った分"},
     {word:"expensive",meaning:"高価な",breakdown:"ex（外へ）＋ pens（重さを量る）→ 支払う分が多い"},
     {word:"spending",meaning:"支出",breakdown:"pend（重さを量る）＋ ing（名詞）→ 外へ払い出すお金"},
     {synonym:true,word:"use",meaning:"使う",breakdown:"資源を広く使う。spend は時間やお金を消費すること"}]},

  {id:304,word:"delay",partOfSpeech:"他動詞",meaning:"遅らせる",
   meanings:["他|遅らせる"],
   pronunciation:"/dɪˈleɪ/",part:31,
   example:"Heavy snow delayed the delivery of food to the village.",
   exampleJa:"大雪が、その村への食料の配達を遅らせた。",
   example2:"We may delay our match if the rain continues.",
   exampleJa2:"雨が続けば、試合を遅らせるかもしれない。",
   etymologyProcess:"delay（先へ延ばす）→ 予定をもっと先へ延ばすと…？",
   etymologyConclusion:"delay（先へ延ばす）→ 古フランス語の「先送りする」から＝遅らせる",
   hook:"delay＋名詞、または delay doing で行動を先へ延ばす。",
   relatedWords:[
     {word:"delayed",meaning:"遅れた",breakdown:"delay（先へ延ばす）＋ ed（〜された）→ 予定より後ろにずれた"},
     {synonym:true,word:"postpone",meaning:"延期する",breakdown:"日時を後に決め直す。delay は進行の遅れにも使う"},
     {synonym:true,word:"wait",meaning:"待つ",breakdown:"人が動かず待つこと。delay は物事を遅くすること"},
     {synonym:true,word:"slow",meaning:"遅くする",breakdown:"速度を落とす。delay は開始や到着を遅くする"}]},

  {id:305,word:"borrow",partOfSpeech:"他動詞",meaning:"借りる",
   meanings:["他|借りる"],
   pronunciation:"/ˈbɑːroʊ/",part:31,
   example:"May I borrow your ladder to fix the roof?",
   exampleJa:"屋根を直すために、はしごを借りてもよいですか。",
   example2:"She borrowed three books from the school library yesterday.",
   exampleJa2:"彼女は昨日、学校の図書館から本を3冊借りた。",
   etymologyProcess:"borrow（借り受ける）→ 返す約束で受け取るなら…？",
   etymologyConclusion:"borrow（借り受ける）→ 古い「担保を置く」という関係から、借り受けることへ＝借りる",
   hook:"borrow は受け取る側、lend は貸す側の動詞。",
   relatedWords:[
     {word:"borrower",meaning:"借り手",breakdown:"borrow（借り受ける）＋ er（人）→ 返す約束で受け取る人"},
     {word:"borrowing",meaning:"借り入れ",breakdown:"borrow（借り受ける）＋ ing（名詞）→ 一時的に受け取ること"},
     {synonym:true,word:"rent",meaning:"有料で借りる",breakdown:"有料で借りる。borrow は通常無料で借りる"},
     {synonym:true,word:"take",meaning:"持っていく",breakdown:"受け取る・持ち出すこと。borrow には返す約束がある"}]},

  {id:306,word:"lend",partOfSpeech:"他動詞",meaning:"貸す",
   meanings:["他|貸す"],
   pronunciation:"/lend/",part:31,
   example:"The farmer will lend us a truck to carry the boxes.",
   exampleJa:"その農家の人は、箱を運ぶためにトラックを私たちに貸す予定だ。",
   example2:"Could you lend me your notes before tomorrow's science test?",
   exampleJa2:"明日の理科のテストの前に、ノートを貸してくれますか。",
   etymologyProcess:"lend（貸す）→ あとで返してもらう約束なら…？",
   etymologyConclusion:"lend（貸す）→ 古英語で、貸し物を一時的に渡すこと＝貸す",
   hook:"lend 人 物、または lend 物 to 人。lend の過去形は lent。",
   relatedWords:[
     {word:"loan",meaning:"貸付金",breakdown:"lend（貸す）→ 返してもらう約束で渡すお金"},
     {word:"lender",meaning:"貸し手",breakdown:"lend（貸す）＋ er（人）→ 一時的に渡す側の人"},
     {synonym:true,word:"give",meaning:"与える",breakdown:"相手のものにする。lend は返してもらう前提"},
     {synonym:true,word:"let",meaning:"貸し出す",breakdown:"家などを料金と引き換えに貸すときに使う"}]},

  {id:307,word:"rent",partOfSpeech:"他動詞",meaning:"有料で借りる；賃貸する",
   meanings:["他|有料で借りる", "他|賃貸する"],
   pronunciation:"/rent/",part:31,
   example:"We rented a small car to explore the island.",
   exampleJa:"私たちは島を見て回るため、小さな車を有料で借りた。",
   example2:"Our club will rent a hall for the winter concert.",
   exampleJa2:"私たちの部は、冬の演奏会のためにホールを有料で借りる。",
   etymologyProcess:"rent（定期的な支払い）→ 使う代わりに料金を渡すなら…？",
   etymologyConclusion:"rent（定期的な支払い）→ フランス語の「収入・支払い」から、使用料を払うことへ＝有料で借りる",
   hook:"rent は借りる側にも貸す側にも使える。借り賃という名詞にもなる。",
   relatedWords:[
     {word:"rental",meaning:"賃貸",breakdown:"rent（定期的な支払い）＋ al（名詞）→ 使用料を払う仕組み"},
     {word:"renter",meaning:"借り手",breakdown:"rent（定期的な支払い）＋ er（人）→ 使用料を払う人"},
     {synonym:true,word:"hire",meaning:"借りる・雇う",breakdown:"人や道具の利用に料金を払う。家には普通 rent を使う"},
     {synonym:true,word:"borrow",meaning:"借りる",breakdown:"通常は無料で借りる。rent は料金が伴う"}]},

  {id:308,word:"provide",partOfSpeech:"他動詞",meaning:"供給する；用意して与える",
   meanings:["他|供給する", "他|用意して与える"],
   pronunciation:"/prəˈvaɪd/",part:31,
   example:"The shelter provides warm meals for people without homes.",
   exampleJa:"その宿泊支援施設は、住む家のない人々に温かい食事を供給する。",
   example2:"Our school will provide computers for the new science course.",
   exampleJa2:"学校は、新しい理科の授業のためにコンピューターを供給する予定だ。",
   etymologyProcess:"pro（前へ）＋ vis（見る）→ 先に見て必要をそろえると…？",
   etymologyConclusion:"pro（前へ）＋ vis（見る）→ 先を見越して、必要なものをそろえて渡す＝供給する",
   relatedWords:[
     {word:"provision",meaning:"供給・備え",breakdown:"pro（前へ）＋ vis（見る）→ 先を見て用意するもの"},
     {word:"provider",meaning:"提供者",breakdown:"pro（前へ）＋ vis（見る）→ 必要を見越して渡す人"},
     {word:"video",meaning:"動画",breakdown:"vis（見る）→ 動きを目で見られる記録"},
     {word:"revise",meaning:"改訂する",breakdown:"re（再び）＋ vis（見る）→ もう一度見て直す"}]},

  {id:309,word:"board",partOfSpeech:"名詞",meaning:"板；委員会",
   meanings:["名|板", "名|委員会"],
   pronunciation:"/bɔːrd/",part:31,
   example:"A wooden board covered the broken window during the storm.",
   exampleJa:"嵐の間、木の板が壊れた窓を覆っていた。",
   example2:"We painted a board to make a sign for our classroom.",
   exampleJa2:"私たちは教室の看板を作るために板に色を塗った。",
   etymologyProcess:"board（板）→ 薄く平たい木の一枚なら…？",
   etymologyConclusion:"board（板）→ 古くから、平らに切り出した木を表す＝板",
   hook:"会議用の板の机から委員会、船の板から乗船の意味にも広がる。",
   relatedWords:[
     {word:"blackboard",meaning:"黒板",breakdown:"black（黒い）＋ board（板）→ 白い文字を書く黒い板"},
     {word:"keyboard",meaning:"鍵盤",breakdown:"key（鍵）＋ board（板）→ キーが並んだ板"},
     {word:"cupboard",meaning:"食器棚",breakdown:"cup（カップ）＋ board（板）→ カップを置く板から棚へ"},
     {word:"skateboard",meaning:"スケートボード",breakdown:"skate（滑る）＋ board（板）→ 車輪で滑る板"}]},

  {id:310,word:"garbage",partOfSpeech:"名詞",meaning:"ごみ",
   meanings:["名|ごみ"],
   pronunciation:"/ˈɡɑːrbɪdʒ/",part:31,
   example:"The city collects garbage twice a week in this area.",
   exampleJa:"市は、この地区のごみを週に2回回収する。",
   example2:"We put our lunch garbage in separate bins at school.",
   exampleJa2:"学校では、昼食のごみを分別用の箱に入れた。",
   etymologyProcess:"garbage（捨てる残り物）→ 食べ物の残りを捨てるなら…？",
   etymologyConclusion:"garbage（捨てる残り物）→ 古くは料理で取り除く部分を指し、廃棄物全般へ＝ごみ",
   hook:"数えない名詞。a garbage ではなく a bag of garbage。",
   relatedWords:[
     {synonym:true,word:"waste",meaning:"廃棄物",breakdown:"不要になった物全般。garbage は家庭のごみにも使う"},
     {synonym:true,word:"trash",meaning:"ごみ",breakdown:"主に米語で使うごみの総称。garbage と意味が重なる"},
     {synonym:true,word:"rubbish",meaning:"ごみ",breakdown:"主に英語圏のイギリスで使う、ごみの総称"},
     {synonym:true,word:"litter",meaning:"散らかったごみ",breakdown:"道路などに捨てられた紙くずや容器を指す"}]},

  {id:311,word:"item",partOfSpeech:"名詞",meaning:"品物；項目",
   meanings:["名|品物", "名|項目"],
   pronunciation:"/ˈaɪtəm/",part:32,
   example:"Every item in this shop is made by hand.",
   exampleJa:"この店の品物は、どれも手作りだ。",
   example2:"Choose one item from your bag and describe it in English.",
   exampleJa2:"かばんから品物を1つ選んで、英語で説明しよう。",
   etymologyProcess:"item（同様に・さらに）→ 一覧にさらに一つと書き足すと…？",
   etymologyConclusion:"item（同様に・さらに）→ ラテン語で一覧を続ける語から、数える一つ一つへ＝品物",
   hook:"a useful item で役立つ品物。一覧の一項目という意味もある。",
   relatedWords:[
     {word:"itemize",meaning:"項目別にする",breakdown:"item（同様に・さらに）＋ ize（する）→ 一つずつ書き並べる"},
     {synonym:true,word:"thing",meaning:"物",breakdown:"物事を広く指す。item は数え上げる一つに注目"},
     {synonym:true,word:"object",meaning:"物体",breakdown:"具体的な形のある物。item は品物や項目を数える語"},
     {synonym:true,word:"article",meaning:"品物",breakdown:"集合の中の一つの品物。item と近い意味で使える"}]},

  {id:312,word:"wheel",partOfSpeech:"名詞",meaning:"車輪；ハンドル",
   meanings:["名|車輪", "名|ハンドル"],
   pronunciation:"/wiːl/",part:32,
   example:"The front wheel of my bicycle needs a new tire.",
   exampleJa:"私の自転車の前の車輪には、新しいタイヤが必要だ。",
   example2:"We attached four wheels to our robot before the competition.",
   exampleJa2:"大会の前に、私たちはロボットに4つの車輪を取り付けた。",
   etymologyProcess:"wheel（回る輪）→ 地面の上で輪が回ると…？",
   etymologyConclusion:"wheel（回る輪）→ 古くから、回って物を運ぶ輪を表す＝車輪",
   hook:"車の steering wheel は運転方向を変えるハンドル。",
   relatedWords:[
     {word:"wheelchair",meaning:"車椅子",breakdown:"wheel（回る輪）＋ chair（椅子）→ 輪で動く椅子"},
     {word:"wheelbarrow",meaning:"手押し一輪車",breakdown:"wheel（回る輪）＋ barrow（運ぶ台）→ 輪のついた運搬台"},
     {word:"steering wheel",meaning:"ハンドル",breakdown:"steer（舵を取る）＋ wheel（回る輪）→ 進む向きを変える輪"},
     {synonym:true,word:"tire",meaning:"タイヤ",breakdown:"車輪の外側につけるゴムの部分。wheel は車輪全体"}]},

  {id:313,word:"note",partOfSpeech:"名詞",meaning:"メモ；短い手紙",
   meanings:["名|メモ", "名|短い手紙"],
   pronunciation:"/noʊt/",part:32,
   example:"She left a note on the door for the delivery driver.",
   exampleJa:"彼女は配達員に向けて、ドアにメモを残した。",
   example2:"Take notes while the teacher explains the new grammar rule.",
   exampleJa2:"先生が新しい文法の規則を説明する間、メモを取ろう。",
   etymologyProcess:"nota（しるし）→ 忘れないようしるしを残すと…？",
   etymologyConclusion:"nota（しるし）→ ラテン語の「しるし」から、短く書き留めたものへ＝メモ",
   hook:"否定の not とは別の由来。こちらは nota（しるし）から。",
   relatedWords:[
     {word:"notepad",meaning:"メモ帳",breakdown:"nota（しるし）＋ pad（紙の束）→ 書き留めるための紙の束"},
     {word:"notebook",meaning:"ノート",breakdown:"nota（しるし）＋ book（本）→ 書き留めたしるしを集める本"},
     {word:"notable",meaning:"注目すべき",breakdown:"nota（しるし）＋ able（できる）→ しるしを付けたくなる"},
     {word:"footnote",meaning:"脚注",breakdown:"foot（足）＋ nota（しるし）→ ページの足元に添える注"}]},

  {id:314,word:"present",partOfSpeech:"名詞",meaning:"贈り物；現在",
   meanings:["名|贈り物", "名|現在"],
   pronunciation:"/ˈpreznt/",part:32,
   example:"The children brought a present for their grandmother's birthday.",
   exampleJa:"子どもたちは、おばあさんの誕生日の贈り物を持ってきた。",
   example2:"I made a small present for my friend after school.",
   exampleJa2:"私は放課後、友達のために小さな贈り物を作った。",
   etymologyProcess:"pre（前へ）＋ sent（いる）→ 相手の目の前に差し出すと…？",
   etymologyConclusion:"pre（前へ）＋ sent（いる）→ 相手の前に置いて差し出すもの＝贈り物",
   relatedWords:[
     {word:"represent",meaning:"代表する",breakdown:"re（再び）＋ pre（前へ）＋ sent（いる）→ 代わって前に立つ"},
     {word:"presentation",meaning:"発表",breakdown:"pre（前へ）＋ sent（いる）→ 人の前に出して見せること"},
     {word:"presence",meaning:"存在",breakdown:"pre（前へ）＋ sent（いる）→ 目の前にいる状態"},
     {synonym:true,word:"gift",meaning:"贈り物",breakdown:"贈る品物。present は誕生日などの身近な贈り物によく使う"}]},

  {id:315,word:"bargain",partOfSpeech:"名詞",meaning:"お買い得品",
   meanings:["名|お買い得品"],
   pronunciation:"/ˈbɑːrɡən/",part:32,
   example:"This warm coat was a bargain at half price.",
   exampleJa:"この暖かいコートは、半額で買えたお買い得品だった。",
   example2:"We found some great bargains at the school charity sale.",
   exampleJa2:"学校のチャリティー販売で、すてきなお買い得品を見つけた。",
   etymologyProcess:"bargain（取引する）→ 交渉してよい値段で手に入ると…？",
   etymologyConclusion:"bargain（取引する）→ 古フランス語の「値段を交渉する」から＝お買い得品",
   hook:"値段の割によい物が a bargain。動詞では値段交渉をすること。",
   relatedWords:[
     {word:"bargaining",meaning:"交渉",breakdown:"bargain（取引する）＋ ing（名詞）→ 値段をすり合わせること"},
     {synonym:true,word:"deal",meaning:"取引・買い得",breakdown:"a good deal ならよい条件の取引や買い物"},
     {synonym:true,word:"buy",meaning:"買った物",breakdown:"a good buy なら値段の割によい買い物"},
     {synonym:true,word:"discount",meaning:"割引",breakdown:"元の値段から引くこと。bargain は買い得な品物"}]},

  {id:316,word:"stuff",partOfSpeech:"名詞",meaning:"もの；持ち物",
   meanings:["名|もの", "名|持ち物"],
   pronunciation:"/stʌf/",part:32,
   example:"Please move your stuff away from the emergency exit.",
   exampleJa:"非常口から自分のものをどけてください。",
   example2:"I keep my sports stuff in a separate locker at school.",
   exampleJa2:"学校では、運動用のものを別のロッカーに入れている。",
   etymologyProcess:"stuff（詰める材料）→ 中に詰めるものをまとめると…？",
   etymologyConclusion:"stuff（詰める材料）→ 古フランス語の「材料・備品」から、もの全般へ＝もの",
   hook:"数えない名詞。いろいろなものをまとめて指すくだけた言い方。",
   relatedWords:[
     {word:"stuffing",meaning:"詰め物",breakdown:"stuff（詰める材料）＋ ing（名詞）→ 中を満たす材料"},
     {word:"stuffed",meaning:"詰めた",breakdown:"stuff（詰める材料）＋ ed（〜された）→ 中をいっぱいにした"},
     {synonym:true,word:"things",meaning:"もの",breakdown:"数えられる複数のもの。stuff はまとめて扱う"},
     {synonym:true,word:"belongings",meaning:"持ち物",breakdown:"誰かが所有するもの。stuff は材料などにも使う"}]},

  {id:317,word:"string",partOfSpeech:"名詞",meaning:"ひも；弦",
   meanings:["名|ひも", "名|弦"],
   pronunciation:"/strɪŋ/",part:32,
   example:"Tie the box with string before sending it by post.",
   exampleJa:"郵便で送る前に、箱をひもで結ぼう。",
   example2:"We used a piece of string to hang our classroom decorations.",
   exampleJa2:"私たちは教室の飾りをつるすのに、ひもを1本使った。",
   etymologyProcess:"string（張ったひも）→ 細いものをぴんと張ると…？",
   etymologyConclusion:"string（張ったひも）→ 古くから、引っ張って張る細いひもを表す＝ひも",
   hook:"物を結ぶひもから、楽器に張る弦へもつながる。",
   relatedWords:[
     {word:"shoestring",meaning:"靴ひも",breakdown:"string（張ったひも）→ 靴を結んで留めるひも"},
     {word:"stringed",meaning:"弦のある",breakdown:"string（張ったひも）＋ ed（〜された）→ 楽器に弦を張った"},
     {synonym:true,word:"rope",meaning:"縄",breakdown:"太く丈夫なもの。string は細いひもに使う"},
     {synonym:true,word:"thread",meaning:"糸",breakdown:"縫い物などの細い糸。string はそれより太めのひも"}]},

  {id:318,word:"leisure",partOfSpeech:"名詞",meaning:"自由時間",
   meanings:["名|自由時間"],
   pronunciation:"/ˈliːʒər/",part:32,
   example:"People need leisure as well as time for work.",
   exampleJa:"人には仕事の時間だけでなく、自由時間も必要だ。",
   example2:"I spend my leisure time reading comics after finishing homework.",
   exampleJa2:"宿題を終えた後の自由時間に、漫画を読んで過ごす。",
   etymologyProcess:"lic（許される）→ 自由にしてよいと許された時間なら…？",
   etymologyConclusion:"lic（許される）→ ラテン語の「許される」から、自分で使える時間へ＝自由時間",
   hook:"仕事や義務から離れて、自分の好きに使える時間。",
   relatedWords:[
     {word:"license",meaning:"許可証",breakdown:"lic（許される）＋ ense（名詞）→ してよいと示す証明"},
     {synonym:true,word:"holiday",meaning:"休日",breakdown:"仕事や学校がない日。leisure は自由に使える時間"},
     {synonym:true,word:"break",meaning:"休憩",breakdown:"活動を一時止めること。leisure は自由に使える時間"},
     {synonym:true,word:"rest",meaning:"休息",breakdown:"疲れを取ること。leisure には趣味や遊びも含む"}]},

  {id:319,word:"diet",partOfSpeech:"名詞",meaning:"日々の食事；食事制限",
   meanings:["名|日々の食事", "名|食事制限"],
   pronunciation:"/ˈdaɪət/",part:32,
   example:"A healthy diet includes vegetables, fruit, and enough protein.",
   exampleJa:"健康的な日々の食事には、野菜、果物、十分なたんぱく質が含まれる。",
   example2:"We learned how a balanced diet helps athletes stay healthy.",
   exampleJa2:"私たちは、バランスのよい日々の食事が選手の健康にどう役立つか学んだ。",
   etymologyProcess:"diet（暮らし方）→ 日々の暮らしで口にするものなら…？",
   etymologyConclusion:"diet（暮らし方）→ ギリシャ語の「生活の仕方」から、食生活へ＝日々の食事",
   hook:"日本語のダイエットより広く、毎日の食事全体を指す。",
   relatedWords:[
     {word:"dietary",meaning:"食事の",breakdown:"diet（暮らし方）＋ ary（形容詞）→ 日々食べる物に関わる"},
     {word:"dieting",meaning:"食事制限",breakdown:"diet（暮らし方）＋ ing（名詞）→ 食べ方を調整すること"},
     {synonym:true,word:"food",meaning:"食べ物",breakdown:"口にする物そのもの。diet は食べ方や組み合わせ"},
     {synonym:true,word:"meal",meaning:"一回の食事",breakdown:"朝食など一回分。diet は日常の食事全体"}]},

  {id:320,word:"furniture",partOfSpeech:"名詞",meaning:"家具",
   meanings:["名|家具"],
   pronunciation:"/ˈfɜːrnɪtʃər/",part:32,
   example:"The room looks larger after we moved the furniture.",
   exampleJa:"家具を動かした後、部屋は広く見える。",
   example2:"Our class made small pieces of furniture in woodwork lessons.",
   exampleJa2:"私たちのクラスは、木工の授業で小さな家具を作った。",
   etymologyProcess:"furn（備える）＋ iture（名詞）→ 部屋に必要なものを備えると…？",
   etymologyConclusion:"furn（備える）＋ iture（名詞）→ 暮らしに必要な物を部屋にそろえたもの＝家具",
   relatedWords:[
     {word:"furnish",meaning:"備え付ける",breakdown:"furn（備える）＋ ish（〜にする）→ 必要な物をそろえる"},
     {word:"furnished",meaning:"家具付きの",breakdown:"furn（備える）→ 家具をすでにそろえた"},
     {synonym:true,word:"table",meaning:"テーブル",breakdown:"家具の一種類。furniture は家具をまとめて指す"},
     {synonym:true,word:"chair",meaning:"椅子",breakdown:"座るための家具。furniture は数えない名詞"}]},

  {id:321,word:"refrigerator",partOfSpeech:"名詞",meaning:"冷蔵庫",
   meanings:["名|冷蔵庫"],
   pronunciation:"/rɪˈfrɪdʒəreɪtər/",part:33,
   example:"Put the milk in the refrigerator as soon as you arrive.",
   exampleJa:"着いたらすぐ、牛乳を冷蔵庫に入れてください。",
   example2:"Our club keeps drinks in a small refrigerator during summer.",
   exampleJa2:"夏の間、私たちの部は小さな冷蔵庫に飲み物を入れている。",
   etymologyProcess:"re（再び）＋ friger（冷やす）＋ ator（装置）→ 何度も冷たくする装置なら…？",
   etymologyConclusion:"re（再び）＋ friger（冷やす）＋ ator（装置）→ 食品を繰り返し冷やして保つ装置＝冷蔵庫",
   relatedWords:[
     {word:"fridge",meaning:"冷蔵庫",breakdown:"friger（冷やす）→ 冷やす装置の名前を短くした"},
     {word:"refrigerate",meaning:"冷蔵する",breakdown:"re（再び）＋ friger（冷やす）＋ ate（動詞）→ 冷たい状態に保つ"},
     {synonym:true,word:"cooler",meaning:"保冷容器",breakdown:"中身を冷たく保つ容器。refrigerator は冷却装置を持つ"},
     {synonym:true,word:"freezer",meaning:"冷凍庫",breakdown:"凍らせて保存する。refrigerator は主に冷やす"}]},

  {id:322,word:"traffic",partOfSpeech:"名詞",meaning:"交通量；往来",
   meanings:["名|交通量", "名|往来"],
   pronunciation:"/ˈtræfɪk/",part:33,
   example:"Heavy traffic made the trip to the airport much longer.",
   exampleJa:"交通量が多かったせいで、空港への移動にずっと時間がかかった。",
   example2:"There is less traffic near our school on Sundays.",
   exampleJa2:"日曜日は、学校の近くの交通量が少ない。",
   etymologyProcess:"traffic（商いの往来）→ 商売のため人や物が行き交うと…？",
   etymologyConclusion:"traffic（商いの往来）→ 古い「商取引」から、人や車の往来へ＝交通量",
   hook:"数えない名詞。heavy traffic は交通量が多いこと。",
   relatedWords:[
     {synonym:true,word:"transport",meaning:"輸送",breakdown:"人や物を運ぶこと。traffic は実際の往来やその量"},
     {synonym:true,word:"movement",meaning:"動き",breakdown:"動くこと全般。traffic は道路などの行き来"},
     {synonym:true,word:"flow",meaning:"流れ",breakdown:"途切れず進む様子。traffic flow は車の流れ"},
     {synonym:true,word:"travel",meaning:"移動・旅行",breakdown:"場所から場所へ行くこと。traffic は往来全体"}]},

  {id:323,word:"sell",partOfSpeech:"他動詞",meaning:"売る",
   meanings:["他|売る"],
   pronunciation:"/sel/",part:33,
   example:"The local farmers sell fresh vegetables at the weekend market.",
   exampleJa:"地元の農家の人たちは、週末の市場で新鮮な野菜を売る。",
   example2:"Our class sold handmade cards to raise money for charity.",
   exampleJa2:"私たちのクラスは、寄付金を集めるために手作りのカードを売った。",
   etymologyProcess:"sell（渡す）→ 代金と引き換えに相手へ渡すと…？",
   etymologyConclusion:"sell（渡す）→ 古英語の「渡す」が、代金を受け取る意味へ＝売る",
   hook:"sell の過去形は sold。sell A to B でAをBに売る。",
   relatedWords:[
     {word:"seller",meaning:"売り手",breakdown:"sell（渡す）＋ er（人）→ 代金と引き換えに渡す人"},
     {word:"bestseller",meaning:"ベストセラー",breakdown:"best（最もよい）＋ sell（渡す）→ とてもよく売れる品"},
     {word:"resell",meaning:"転売する",breakdown:"re（再び）＋ sell（渡す）→ 手に入れた物をまた売る"},
     {synonym:true,word:"trade",meaning:"取引する",breakdown:"物を交換・売買する。sell は代金を受け取って渡す側"}]},

  {id:324,word:"pay",partOfSpeech:"他動詞",meaning:"支払う",
   meanings:["他|支払う"],
   pronunciation:"/peɪ/",part:33,
   example:"You can pay the entrance fee at the front desk.",
   exampleJa:"受付で入場料を支払うことができる。",
   example2:"I paid the fee for our school trip yesterday.",
   exampleJa2:"昨日、私は校外学習の費用を支払った。",
   etymologyProcess:"pac（穏やかにする）→ 代金を渡して相手を満足させると…？",
   etymologyConclusion:"pac（穏やかにする）→ ラテン語の「なだめる」から、債務を清算する動きへ＝支払う",
   hook:"pay for＋買うもの。pay＋金額で支払う額を示す。",
   relatedWords:[
     {word:"payment",meaning:"支払い",breakdown:"pac（穏やかにする）＋ ment（名詞）→ お金を渡して清算すること"},
     {word:"peace",meaning:"平和",breakdown:"pac（穏やかにする）→ 争いがおさまった状態"},
     {word:"repay",meaning:"返済する",breakdown:"re（再び）＋ pac（穏やかにする）→ 借りたお金を戻して清算する"},
     {word:"peaceful",meaning:"平和な",breakdown:"pac（穏やかにする）＋ ful（満ちた）→ 穏やかさに満ちた"}]},

  {id:325,word:"wear",partOfSpeech:"他動詞",meaning:"身につけている；すり減らす",
   meanings:["他|身につけている", "他|すり減らす"],
   pronunciation:"/wer/",part:33,
   example:"The workers wear helmets when they enter the building site.",
   exampleJa:"作業員は、建築現場に入るときヘルメットを身につけている。",
   example2:"I wore my new jacket to the school concert yesterday.",
   exampleJa2:"私は昨日、学校の演奏会に新しい上着を身につけて行った。",
   etymologyProcess:"wear（身につける）→ 服を体につけた状態なら…？",
   etymologyConclusion:"wear（身につける）→ 古くから、服を体にまとっていることを表す＝身につけている",
   hook:"put on は着る動作、wear は着ている状態。",
   relatedWords:[
     {word:"sportswear",meaning:"運動着",breakdown:"sport（運動）＋ wear（身につける）→ 運動のときに着る物"},
     {word:"underwear",meaning:"下着",breakdown:"under（下に）＋ wear（身につける）→ 服の下に着る物"},
     {word:"footwear",meaning:"履物",breakdown:"foot（足）＋ wear（身につける）→ 足につける物"},
     {synonym:true,word:"dress",meaning:"服を着る",breakdown:"服装を整える動作や状態。wear は何を着ているかを示す"}]},

  {id:326,word:"clothes",partOfSpeech:"名詞",meaning:"衣服",
   meanings:["名|衣服"],
   pronunciation:"/kloʊðz/",part:33,
   example:"Wet clothes were hanging from a line behind the house.",
   exampleJa:"ぬれた衣服が、家の裏のひもにつるされていた。",
   example2:"Bring warm clothes for our school trip to the mountains.",
   exampleJa2:"山への校外学習には、暖かい衣服を持ってきてください。",
   etymologyProcess:"cloth（布）＋ es（複数）→ 体を覆う布を集めると…？",
   etymologyConclusion:"cloth（布）＋ es（複数）→ 古くから、体を覆う布のまとまりを表す＝衣服",
   relatedWords:[
     {word:"cloth",meaning:"布",breakdown:"cloth（布）→ 体や物を覆う織物"},
     {word:"clothing",meaning:"衣類",breakdown:"cloth（布）＋ ing（名詞）→ 身につける布の品全体"},
     {word:"tablecloth",meaning:"テーブルクロス",breakdown:"table（板）＋ cloth（布）→ テーブルを覆う布"},
     {synonym:true,word:"dress",meaning:"服・ドレス",breakdown:"服装全般やワンピース。clothes は衣服の複数を指す"}]},

  {id:327,word:"marry",partOfSpeech:"他動詞",meaning:"結婚する",
   meanings:["他|結婚する"],
   pronunciation:"/ˈmæri/",part:33,
   example:"She plans to marry her partner in a small ceremony.",
   exampleJa:"彼女は、ささやかな式でパートナーと結婚する予定だ。",
   example2:"My sister married a teacher from our old school.",
   exampleJa2:"姉は、私たちが以前通った学校の先生と結婚した。",
   etymologyProcess:"marit（結婚した）→ 夫婦として結ばれた状態なら…？",
   etymologyConclusion:"marit（結婚した）→ ラテン語の「結婚させる」につながる語から＝結婚する",
   hook:"marry＋人で「人と結婚する」。marry with 人とはしない。",
   relatedWords:[
     {word:"marriage",meaning:"結婚",breakdown:"marit（結婚した）＋ age（名詞）→ 夫婦として結ばれること"},
     {word:"married",meaning:"既婚の",breakdown:"marit（結婚した）＋ ed（〜された）→ 夫婦になっている"},
     {word:"remarry",meaning:"再婚する",breakdown:"re（再び）＋ marit（結婚した）→ 再び結婚する"},
     {synonym:true,word:"wedding",meaning:"結婚式",breakdown:"結婚を祝う儀式。marry は結婚するという動詞"}]},

  {id:328,word:"greet",partOfSpeech:"他動詞",meaning:"挨拶する",
   meanings:["他|挨拶する"],
   pronunciation:"/ɡriːt/",part:33,
   example:"The owner came outside to greet the arriving guests.",
   exampleJa:"主人は、到着した客に挨拶するため、外に出てきた。",
   example2:"We greeted the exchange students with smiles after assembly.",
   exampleJa2:"集会の後、私たちは笑顔で交換留学生に挨拶した。",
   etymologyProcess:"greet（声をかける）→ 出会った人に声をかけると…？",
   etymologyConclusion:"greet（声をかける）→ 古くから、相手に話しかけることを表す＝挨拶する",
   hook:"greet＋人で「人に挨拶する」。あいだに to は置かない。",
   relatedWords:[
     {word:"greeting",meaning:"挨拶",breakdown:"greet（声をかける）＋ ing（名詞）→ 出会いに添える声"},
     {word:"greeter",meaning:"出迎える人",breakdown:"greet（声をかける）＋ er（人）→ 声をかけて迎える人"},
     {synonym:true,word:"welcome",meaning:"歓迎する",breakdown:"来てくれたことを喜ぶ。greet は出会いの挨拶"},
     {synonym:true,word:"hello",meaning:"こんにちは",breakdown:"挨拶の言葉そのもの。greet は挨拶する動作"}]},

  {id:329,word:"order",partOfSpeech:"他動詞",meaning:"注文する；命令する",
   meanings:["他|注文する", "他|命令する"],
   pronunciation:"/ˈɔːrdər/",part:33,
   example:"We ordered hot soup because the evening was cold.",
   exampleJa:"夕方は寒かったので、私たちは温かいスープを注文した。",
   example2:"Our club will order new uniforms before the tournament.",
   exampleJa2:"私たちの部は、大会の前に新しいユニフォームを注文する予定だ。",
   etymologyProcess:"ord（順序）→ することを順に指示すると…？",
   etymologyConclusion:"ord（順序）→ 順序を整えて指示することから、品物を求める動きへ＝注文する",
   hook:"物事の順序、社会の秩序、注文は「整った並び」からつながる。",
   relatedWords:[
     {word:"ordinary",meaning:"普通の",breakdown:"ord（順序）＋ inary（形容詞）→ いつもの並びどおりの"},
     {word:"disorder",meaning:"混乱",breakdown:"dis（否定）＋ ord（順序）→ 並びが整っていない"},
     {word:"reorder",meaning:"再注文する",breakdown:"re（再び）＋ ord（順序）→ 必要な品をもう一度頼む"},
     {synonym:true,word:"request",meaning:"頼む",breakdown:"相手に求めること。order は商品を指定するときにも使う"}]},

  {id:330,word:"room",partOfSpeech:"名詞",meaning:"部屋；余地",
   meanings:["名|部屋", "名|余地"],
   pronunciation:"/ruːm/",part:33,
   example:"The hotel room has a window facing the sea.",
   exampleJa:"そのホテルの部屋には、海に面した窓がある。",
   example2:"We decorated our club room with photos from last year's trip.",
   exampleJa2:"私たちは、去年の旅行の写真で部活の部屋を飾った。",
   etymologyProcess:"room（部屋）→ 人が過ごせる空間を区切ると…？",
   etymologyConclusion:"room（部屋）→ 古い「広さ・空間」から、建物内の区切られた場所へ＝部屋",
   hook:"部屋なら数えられる。余地の意味の room は数えない。",
   relatedWords:[
     {word:"classroom",meaning:"教室",breakdown:"class（学級）＋ room（部屋）→ 学級が集まる部屋"},
     {word:"bedroom",meaning:"寝室",breakdown:"bed（ベッド）＋ room（部屋）→ 寝るための部屋"},
     {word:"roomy",meaning:"広々とした",breakdown:"room（部屋）＋ y（形容詞）→ 使える空間がたっぷりある"},
     {word:"bathroom",meaning:"浴室",breakdown:"bath（入浴）＋ room（部屋）→ 入浴するための部屋"}]},

  {id:331,word:"story",partOfSpeech:"名詞",meaning:"階",
   meanings:["名|階"],
   pronunciation:"/ˈstɔːri/",part:34,
   example:"The top story of the new library has large windows.",
   exampleJa:"新しい図書館の最上階には、大きな窓がある。",
   example2:"Our club room is on the second story of this building.",
   exampleJa2:"部室は、この建物の2階にある。",
   etymologyProcess:"story（階層）→ 建物を上下に区切って数えると…？",
   etymologyConclusion:"story（階層）→ 語源の詳しいつながりは不確かだが、建物の上下の区切りを表す＝階",
   hook:"物語の story と区別。建物の階はイギリス英語では storey とも書く。",
   relatedWords:[
     {word:"multistory",meaning:"多階建ての",breakdown:"multi（多く）＋ story（階層）→ いくつもの階が重なる"},
     {word:"two-story",meaning:"2階建ての",breakdown:"two（二つ）＋ story（階層）→ 二つの階を重ねた"},
     {synonym:true,word:"floor",meaning:"階・床",breakdown:"建物の階や床。story は建物の高さを階数で数える"},
     {synonym:true,word:"level",meaning:"階層",breakdown:"高さの段階。story は建物の一階層を指す"}]},

  {id:332,word:"site",partOfSpeech:"名詞",meaning:"用地；現場；跡地",
   meanings:["名|用地", "名|現場", "名|跡地"],
   pronunciation:"/saɪt/",part:34,
   example:"The city chose a site near the river for the museum.",
   exampleJa:"市は、博物館のために川の近くの用地を選んだ。",
   example2:"We visited the site of our new school last week.",
   exampleJa2:"先週、私たちは新しい学校の用地を訪れた。",
   etymologyProcess:"sit（置く）→ 建物などを置く場所なら…？",
   etymologyConclusion:"sit（置く）→ ラテン語の「置かれた場所」から、目的を持つ土地へ＝用地",
   hook:"座る sit と形が似るが、ここはラテン語 situs の系統。",
   relatedWords:[
     {word:"situation",meaning:"状況",breakdown:"sit（置く）＋ uation（名詞）→ 置かれている状態"},
     {word:"situated",meaning:"位置する",breakdown:"sit（置く）＋ uate（動詞）＋ ed（〜された）→ ある場所に置かれた"},
     {word:"website",meaning:"ウェブサイト",breakdown:"web（網）＋ sit（置く）→ 網の中に置かれた情報の場所"},
     {word:"campsite",meaning:"キャンプ場",breakdown:"camp（野営）＋ sit（置く）→ テントを置く場所"}]},

  {id:333,word:"yard",partOfSpeech:"名詞",meaning:"庭；囲まれた敷地",
   meanings:["名|庭", "名|囲まれた敷地"],
   pronunciation:"/jɑːrd/",part:34,
   example:"The children played in the yard behind their house.",
   exampleJa:"子どもたちは、家の裏の庭で遊んだ。",
   example2:"We planted flowers in the school yard on Friday.",
   exampleJa2:"金曜日に、私たちは学校の庭に花を植えた。",
   etymologyProcess:"yard（囲まれた場所）→ 囲いで区切った場所なら…？",
   etymologyConclusion:"yard（囲まれた場所）→ 古くから、囲いの中にある土地を表す＝庭",
   hook:"長さの単位の yard は別の由来。ここでは家の周りの場所。",
   relatedWords:[
     {word:"backyard",meaning:"裏庭",breakdown:"back（後ろ）＋ yard（囲まれた場所）→ 家の後ろの囲い地"},
     {word:"schoolyard",meaning:"校庭",breakdown:"school（学校）＋ yard（囲まれた場所）→ 学校の中の広場"},
     {word:"garden",meaning:"庭",breakdown:"yard（囲まれた場所）→ 囲いの中で草木を育てる場所"},
     {synonym:true,word:"grounds",meaning:"敷地",breakdown:"建物に付属する土地全体。yard は囲いや家の周りを意識する"}]},

  {id:334,word:"bottom",partOfSpeech:"名詞",meaning:"底；最下部",
   meanings:["名|底", "名|最下部"],
   pronunciation:"/ˈbɑːtəm/",part:34,
   example:"There is a small hole in the bottom of the bucket.",
   exampleJa:"そのバケツの底には、小さな穴がある。",
   example2:"I found my missing pen at the bottom of my bag.",
   exampleJa2:"かばんの底で、なくしたペンを見つけた。",
   etymologyProcess:"bottom（いちばん下）→ これ以上下に行けないところなら…？",
   etymologyConclusion:"bottom（いちばん下）→ 古くから、物のいちばん下の部分を表す＝底",
   hook:"at the bottom of で「〜の底に」。順位なら最下位も表す。",
   relatedWords:[
     {word:"bottomless",meaning:"底なしの",breakdown:"bottom（いちばん下）＋ less（ない）→ 底が見つからない"},
     {synonym:true,word:"base",meaning:"土台",breakdown:"下で支える部分。bottom は支えるかに関係なく最下部"},
     {synonym:true,word:"floor",meaning:"床・底面",breakdown:"下の平らな面。bottom は物の最下部全般"},
     {synonym:true,word:"foot",meaning:"ふもと",breakdown:"山などの一番下。bottom は容器の底にも使う"}]},

  {id:335,word:"line",partOfSpeech:"名詞",meaning:"列；線；行",
   meanings:["名|列", "名|線", "名|行"],
   pronunciation:"/laɪn/",part:34,
   example:"A long line of visitors waited outside the museum.",
   exampleJa:"来館者の長い列が、博物館の外で待っていた。",
   example2:"We stood in line to buy tickets for the school concert.",
   exampleJa2:"学校の演奏会の切符を買うために、私たちは列に並んだ。",
   etymologyProcess:"line（線）→ 一本の糸のようにつながると…？",
   etymologyConclusion:"line（線）→ ラテン語の「麻の糸」から、一筋に並んだものへ＝列",
   hook:"人の列、紙の線、文章の行は、どれも一筋の並び。",
   relatedWords:[
     {word:"outline",meaning:"輪郭",breakdown:"out（外へ）＋ line（線）→ 外側をなぞる線"},
     {word:"underline",meaning:"下線を引く",breakdown:"under（下に）＋ line（線）→ 文字の下に線を引く"},
     {word:"deadline",meaning:"締め切り",breakdown:"dead（動かない）＋ line（線）→ これを越えると終わりになる線"},
     {synonym:true,word:"queue",meaning:"待ち行列",breakdown:"順番を待つ人の列。line は線や文章の行にも使う"}]},

  {id:336,word:"row",partOfSpeech:"名詞",meaning:"横一列；並び",
   meanings:["名|横一列", "名|並び"],
   pronunciation:"/roʊ/",part:34,
   example:"A row of chairs was placed near the entrance.",
   exampleJa:"入口の近くに椅子が横一列に置かれていた。",
   example2:"We planted a row of sunflowers along the school fence.",
   exampleJa2:"学校の柵に沿って、ひまわりを横一列に植えた。",
   etymologyProcess:"row（ひと続きの並び）→ 横に一つずつ並べると…？",
   etymologyConclusion:"row（ひと続きの並び）→ 古くから、一続きに並んだものを表す＝横一列",
   hook:"座席の横の列が row。待ち行列には line がよく使われる。",
   relatedWords:[
     {word:"front-row",meaning:"最前列の",breakdown:"front（前）＋ row（ひと続きの並び）→ 一番前の並びの"},
     {synonym:true,word:"line",meaning:"列",breakdown:"一筋の並び。row は座席や植木の横並びによく使う"},
     {synonym:true,word:"rank",meaning:"整列した列",breakdown:"兵士などが横に並ぶ列。順位という意味もある"},
     {synonym:true,word:"series",meaning:"連続",breakdown:"順に続くもの。row は実際に並んだ配置にも使う"}]},

  {id:337,word:"background",partOfSpeech:"名詞",meaning:"背景；経歴",
   meanings:["名|背景", "名|経歴"],
   pronunciation:"/ˈbækɡraʊnd/",part:34,
   example:"The mountains in the background make this photo beautiful.",
   exampleJa:"背景の山々が、この写真を美しくしている。",
   example2:"We painted a blue background for the school play.",
   exampleJa2:"私たちは、学校の劇のために青い背景を描いた。",
   etymologyProcess:"back（後ろ）＋ ground（底・地面）→ 主役の後ろに広がる場所なら…？",
   etymologyConclusion:"back（後ろ）＋ ground（底・地面）→ 手前のものの後ろに広がる部分＝背景",
   relatedWords:[
     {word:"backdrop",meaning:"背景幕",breakdown:"back（後ろ）＋ drop（垂らす）→ 舞台の後ろに垂らす幕"},
     {word:"ground",meaning:"地面",breakdown:"ground（底・地面）→ 足元で物を支える面"},
     {word:"underground",meaning:"地下の",breakdown:"under（下に）＋ ground（底・地面）→ 地面の下にある"},
     {word:"backpack",meaning:"リュック",breakdown:"back（後ろ）＋ pack（包み）→ 背中に載せる荷物"}]},

  {id:338,word:"direction",partOfSpeech:"名詞",meaning:"方向；道順；指示",
   meanings:["名|方向", "名|道順", "名|指示"],
   pronunciation:"/dəˈrekʃn/",part:34,
   example:"The wind suddenly changed direction as the storm approached.",
   exampleJa:"嵐が近づくと、風は突然方向を変えた。",
   example2:"Which direction should we go to reach the school gym?",
   exampleJa2:"学校の体育館に着くには、どちらの方向へ行けばよいですか。",
   etymologyProcess:"di（離れて）＋ rect（まっすぐ）＋ ion（名詞）→ まっすぐ向けた先はどちらか…？",
   etymologyConclusion:"di（離れて）＋ rect（まっすぐ）＋ ion（名詞）→ よそへそれず、まっすぐ向けた先＝方向",
   relatedWords:[
     {word:"direct",meaning:"直接の",breakdown:"di（離れて）＋ rect（まっすぐ）→ 寄り道せずまっすぐな"},
     {word:"redirect",meaning:"向け直す",breakdown:"re（再び）＋ di（離れて）＋ rect（まっすぐ）→ 別の先へ向ける"},
     {word:"correct",meaning:"正しい",breakdown:"com（すっかり）＋ rect（まっすぐ）→ 曲がりを正した"},
     {word:"rectangle",meaning:"長方形",breakdown:"rect（まっすぐ）＋ angle（角）→ 直角が四つの形"}]},

  {id:339,word:"culture",partOfSpeech:"名詞",meaning:"文化；培養",
   meanings:["名|文化", "名|培養"],
   pronunciation:"/ˈkʌltʃər/",part:34,
   example:"Food is an important part of every country's culture.",
   exampleJa:"食べ物は、どの国の文化にとっても大切な一部だ。",
   example2:"We learned about local culture by visiting a traditional festival.",
   exampleJa2:"伝統的な祭りを訪れて、私たちは地元の文化について学んだ。",
   etymologyProcess:"cult（耕す）＋ ure（名詞）→ 土地のように心も育てると…？",
   etymologyConclusion:"cult（耕す）＋ ure（名詞）→ 土地を耕すことから、人の知恵や暮らしを育てることへ＝文化",
   relatedWords:[
     {word:"cultural",meaning:"文化の",breakdown:"cult（耕す）＋ ure（名詞）＋ al（形容詞）→ 育まれた暮らしの"},
     {word:"agriculture",meaning:"農業",breakdown:"agri（畑）＋ cult（耕す）→ 畑を耕して作物を育てる"},
     {word:"cultivate",meaning:"耕す",breakdown:"cult（耕す）＋ ivate（動詞）→ 土地に手をかけて育てる"},
     {synonym:true,word:"custom",meaning:"慣習",breakdown:"繰り返される社会の習わし。culture は知恵や表現も含む"}]},

  {id:340,word:"art",partOfSpeech:"名詞",meaning:"芸術；技術",
   meanings:["名|芸術", "名|技術"],
   pronunciation:"/ɑːrt/",part:34,
   example:"The gallery displays art from many different parts of Asia.",
   exampleJa:"その美術館は、アジアのさまざまな地域の芸術を展示している。",
   example2:"Our art teacher encouraged us to try painting with unusual materials.",
   exampleJa2:"美術の先生は、珍しい材料で絵を描いてみるよう私たちを励ました。",
   etymologyProcess:"art（技）→ 身につけた技で美しさを作ると…？",
   etymologyConclusion:"art（技）→ ラテン語の「技・技術」から、美を表現する営みへ＝芸術",
   hook:"絵や彫刻だけでなく、人が身につけた技術も表せる。",
   relatedWords:[
     {word:"artist",meaning:"芸術家",breakdown:"art（技）＋ ist（人）→ 技を使って作品を作る人"},
     {word:"artistic",meaning:"芸術的な",breakdown:"art（技）＋ istic（形容詞）→ 表現する技を感じさせる"},
     {word:"artificial",meaning:"人工の",breakdown:"art（技）＋ fic（作る）→ 人の技で作られた"},
     {word:"artwork",meaning:"美術作品",breakdown:"art（技）＋ work（仕事）→ 表現する技で生まれた作品"}]},

  {id:341,word:"cartoon",partOfSpeech:"名詞",meaning:"漫画；アニメ",
   meanings:["名|漫画", "名|アニメ"],
   pronunciation:"/kɑːrˈtuːn/",part:35,
   example:"The newspaper printed a cartoon about the city's traffic problems.",
   exampleJa:"新聞は、その市の交通問題についての漫画を載せた。",
   example2:"We drew a cartoon to explain our school recycling rules.",
   exampleJa2:"私たちは、学校のリサイクルの規則を説明する漫画を描いた。",
   etymologyProcess:"cart（紙）＋ oon（大きい）→ 大きな紙に下絵を描くと…？",
   etymologyConclusion:"cart（紙）＋ oon（大きい）→ イタリア語の「大きな紙」から、絵で示す作品へ＝漫画",
   relatedWords:[
     {word:"carton",meaning:"紙箱",breakdown:"cart（紙）→ 厚い紙で作った箱"},
     {word:"card",meaning:"カード",breakdown:"cart（紙）→ 文字や絵を書いた厚い紙"},
     {word:"chart",meaning:"図表",breakdown:"cart（紙）→ 紙の上にまとめて示したもの"},
     {word:"cartoonist",meaning:"漫画家",breakdown:"cart（紙）＋ oon（大きい）＋ ist（人）→ 漫画を描く人"}]},

  {id:342,word:"novel",partOfSpeech:"名詞",meaning:"小説",
   meanings:["名|小説"],
   pronunciation:"/ˈnɑːvl/",part:35,
   example:"Her first novel tells the story of a young musician.",
   exampleJa:"彼女の最初の小説は、若い音楽家の物語を描いている。",
   example2:"I borrowed a mystery novel from our school library yesterday.",
   exampleJa2:"私は昨日、学校の図書館から推理小説を借りた。",
   etymologyProcess:"nov（新しい）＋ el（小さい）→ 新しい話を一つ届けると…？",
   etymologyConclusion:"nov（新しい）＋ el（小さい）→ イタリア語の「新しい話」から、創作された長い物語へ＝小説",
   relatedWords:[
     {word:"novelist",meaning:"小説家",breakdown:"nov（新しい）＋ el（小さい）＋ ist（人）→ 新しい物語を書く人"},
     {word:"novelty",meaning:"目新しさ",breakdown:"nov（新しい）＋ el（小さい）＋ ty（名詞）→ 新しく感じること"},
     {word:"news",meaning:"ニュース",breakdown:"new（新しい）→ 新しく伝わってきた知らせ"},
     {synonym:true,word:"fiction",meaning:"創作文学",breakdown:"事実ではなく作った物語全般。novel は長編の小説"}]},

  {id:343,word:"instrument",partOfSpeech:"名詞",meaning:"楽器；器具",
   meanings:["名|楽器", "名|器具"],
   pronunciation:"/ˈɪnstrəmənt/",part:35,
   example:"The musician carefully packed her instrument before leaving the hall.",
   exampleJa:"その音楽家は、ホールを出る前に楽器を丁寧にしまった。",
   example2:"Which instrument would you like to play in our school band?",
   exampleJa2:"学校のバンドでは、どの楽器を演奏したいですか。",
   etymologyProcess:"in（中へ）＋ struct（積み上げる）＋ ment（名詞）→ 使うための装備を整えると…？",
   etymologyConclusion:"in（中へ）＋ struct（積み上げる）＋ ment（名詞）→ 中に必要なものを備えることから、演奏などに使う道具へ＝楽器",
   relatedWords:[
     {word:"instruct",meaning:"教える",breakdown:"in（中へ）＋ struct（積み上げる）→ 頭に知識を組み立てる"},
     {word:"instruction",meaning:"指示",breakdown:"in（中へ）＋ struct（積み上げる）→ 手順を組み立てて示すこと"},
     {word:"construct",meaning:"建設する",breakdown:"con（共に）＋ struct（積み上げる）→ 材料を一緒に積み上げる"},
     {synonym:true,word:"tool",meaning:"道具",breakdown:"仕事に使う物全般。instrument は楽器や精密な器具にも使う"}]},

  {id:344,word:"tune",partOfSpeech:"名詞",meaning:"曲；旋律",
   meanings:["名|曲", "名|旋律"],
   pronunciation:"/tuːn/",part:35,
   example:"A familiar tune was playing softly on the radio.",
   exampleJa:"ラジオから、なじみのある曲が静かに流れていた。",
   example2:"I practiced the same tune until I could play it smoothly.",
   exampleJa2:"なめらかに弾けるようになるまで、同じ曲を練習した。",
   etymologyProcess:"ton（音の調子）→ 張った弦が音を出すと…？",
   etymologyConclusion:"ton（音の調子）→ ギリシャ語の「張り」から、音の高さやそのつながりへ＝曲",
   hook:"鼻歌でなぞれる旋律。in tune は音程が合っていること。",
   relatedWords:[
     {word:"tone",meaning:"音色・調子",breakdown:"ton（音の調子）→ 張った弦が出す音の性質"},
     {synonym:true,word:"song",meaning:"歌",breakdown:"歌詞のある曲。tune は口ずさめる旋律に注目する"},
     {word:"intonation",meaning:"抑揚",breakdown:"in（中へ）＋ ton（音の調子）→ 話す声につく音の高低"},
     {synonym:true,word:"music",meaning:"音楽",breakdown:"音楽全般を指す。tune はその中の一つの旋律"}]},

  {id:345,word:"sentence",partOfSpeech:"名詞",meaning:"文；判決",
   meanings:["名|文", "名|判決"],
   pronunciation:"/ˈsentəns/",part:35,
   example:"The first sentence of the letter explained the problem clearly.",
   exampleJa:"その手紙の最初の文は、問題をはっきり説明していた。",
   example2:"Write a sentence using each new word from today's lesson.",
   exampleJa2:"今日の授業の新しい単語をそれぞれ使って、文を書こう。",
   etymologyProcess:"sens（感じる）＋ ence（名詞）→ 感じた考えを言葉にまとめると…？",
   etymologyConclusion:"sens（感じる）＋ ence（名詞）→ ラテン語の「意見・判断」から、意味のまとまった言葉へ＝文",
   relatedWords:[
     {word:"sense",meaning:"感覚・意味",breakdown:"sens（感じる）→ 感じ取ってわかること"},
     {word:"sensitive",meaning:"敏感な",breakdown:"sens（感じる）＋ itive（形容詞）→ わずかなことも感じ取る"},
     {word:"consent",meaning:"同意する",breakdown:"con（共に）＋ sens（感じる）→ 相手と同じように感じる"},
     {word:"sensible",meaning:"分別のある",breakdown:"sens（感じる）＋ ible（できる）→ 状況を感じ取って判断できる"}]},

  {id:346,word:"article",partOfSpeech:"名詞",meaning:"記事；品物；冠詞",
   meanings:["名|記事", "名|品物", "名|冠詞"],
   pronunciation:"/ˈɑːrtɪkl/",part:35,
   example:"The article explains how the new train system works.",
   exampleJa:"その記事は、新しい鉄道システムの仕組みを説明している。",
   example2:"I wrote an article about our club for the school newspaper.",
   exampleJa2:"学校新聞に、私たちの部についての記事を書いた。",
   etymologyProcess:"articul（小さな関節）→ 全体をつなぐ小さな区切りなら…？",
   etymologyConclusion:"articul（小さな関節）→ ラテン語の「小さな関節」から、文章の一つのまとまりへ＝記事",
   hook:"新聞の記事も、契約の条項も、全体の中の一区切り。",
   relatedWords:[
     {word:"articulate",meaning:"明確に述べる",breakdown:"articul（小さな関節）→ 言葉の区切りをはっきりつなぐ"},
     {word:"articulation",meaning:"発音・連結",breakdown:"articul（小さな関節）＋ ation（名詞）→ 区切りをつなぐこと"},
     {synonym:true,word:"report",meaning:"報告",breakdown:"調べた事実を伝える文章。article は新聞などの記事"},
     {synonym:true,word:"story",meaning:"記事・話",breakdown:"出来事を伝える記事にも使う。article は論説にも使う"}]},

  {id:347,word:"passage",partOfSpeech:"名詞",meaning:"一節；通路；通過",
   meanings:["名|一節", "名|通路", "名|通過"],
   pronunciation:"/ˈpæsɪdʒ/",part:35,
   example:"She read a short passage from the book aloud.",
   exampleJa:"彼女は、その本の短い一節を声に出して読んだ。",
   example2:"This passage is difficult, so read it again before answering.",
   exampleJa2:"この一節は難しいので、答える前にもう一度読もう。",
   etymologyProcess:"pass（通り抜ける）＋ age（名詞）→ 読み進める途中の一区切りなら…？",
   etymologyConclusion:"pass（通り抜ける）＋ age（名詞）→ 通り抜ける場所から、文章を進む途中の一部分へ＝一節",
   relatedWords:[
     {word:"pass",meaning:"通過する",breakdown:"pass（通り抜ける）→ ある場所を通って向こうへ行く"},
     {word:"passenger",meaning:"乗客",breakdown:"pass（通り抜ける）→ 乗り物で道を通っていく人"},
     {word:"passport",meaning:"旅券",breakdown:"pass（通り抜ける）＋ portus（港）→ 出入口を通るための証明"},
     {word:"passing",meaning:"通過",breakdown:"pass（通り抜ける）＋ ing（名詞）→ 向こうへ通っていくこと"}]},

  // 既存 No.42 の vocabulary を原書の番号にも再掲（内容は再生成しない）。
  {id:348,word:"vocabulary",partOfSpeech:"名詞",meaning:"語彙",
   meanings:["名|語彙"],
   pronunciation:"/vəˈkæbjəleri/",part:35,
   example:"Let's review today's new vocabulary before the short test.",
   exampleJa:"小テストの前に、今日の新しい語彙を復習しましょう。",
   example2:"He has a large vocabulary for a first-year student.",
   exampleJa2:"1年生にしては彼は語彙が豊富だ。",
   etymologyProcess:"voc（呼ぶ）＋ ary（もの）→ 呼び名として持っている言葉の…？",
   etymologyConclusion:"voc（呼ぶ）＋ ary（もの）→ 呼び名として手元に持っている言葉の全体＝語彙",
   hook:"基本は不可算。語1つを指すときは a vocabulary ではなく a word。",
   relatedWords:[
     {word:"voice",meaning:"声",breakdown:"voc（呼ぶ）→ 呼ぶために出す音そのもの"},
     {word:"vocal",meaning:"声の；ボーカル",breakdown:"voc（呼ぶ）＋ al（形容詞）→ 声を使って出すもの"},
     {word:"vocation",meaning:"天職",breakdown:"voc（呼ぶ）＋ ation（名詞）→ 天から呼ばれて就く仕事"},
     {word:"advocate",meaning:"支持を訴える",breakdown:"ad（〜へ）＋ voc（呼ぶ）→ 味方するほうへ声を上げる"}]},

  {id:349,word:"rumor",partOfSpeech:"名詞",meaning:"うわさ",
   meanings:["名|うわさ"],
   pronunciation:"/ˈruːmər/",part:35,
   example:"A rumor about the factory closing spread through the town.",
   exampleJa:"工場が閉鎖されるといううわさが、町に広まった。",
   example2:"Do not believe every rumor you hear at school.",
   exampleJa2:"学校で耳にするうわさを、何でも信じてはいけない。",
   etymologyProcess:"rumor（人々のざわめき）→ 人々の話し声が広がっていくと…？",
   etymologyConclusion:"rumor（人々のざわめき）→ ラテン語の「ざわめき・世間の話」から＝うわさ",
   hook:"確かめられていない話。イギリス英語では rumour と書く。",
   relatedWords:[
     {word:"rumored",meaning:"うわさされる",breakdown:"rumor（人々のざわめき）＋ ed（〜された）→ 人々の間で話される"},
     {synonym:true,word:"gossip",meaning:"うわさ話",breakdown:"人の私生活についての話が中心。rumor は出来事にも使う"},
     {synonym:true,word:"story",meaning:"話",breakdown:"事実か創作かを問わない話。rumor は未確認の話"},
     {synonym:true,word:"talk",meaning:"話・風説",breakdown:"人々の間の話という意味がある。rumor と近い場合もある"}]},

  {id:350,word:"spell",partOfSpeech:"他動詞",meaning:"つづる",
   meanings:["他|つづる"],
   pronunciation:"/spel/",part:35,
   example:"Could you spell your family name for the hotel clerk?",
   exampleJa:"ホテルの受付係に、名字をつづって伝えてくれますか。",
   example2:"I spelled every word correctly on the English test today.",
   exampleJa2:"今日の英語のテストでは、すべての単語を正しくつづった。",
   etymologyProcess:"spell（語る）→ 言葉を文字で一つずつ伝えると…？",
   etymologyConclusion:"spell（語る）→ 古い「語る」から、文字を順に示す動きへ＝つづる",
   hook:"spell の過去形は spelled または spelt。文字を順に伝えること。",
   relatedWords:[
     {word:"spelling",meaning:"つづり",breakdown:"spell（語る）＋ ing（名詞）→ 言葉を文字で表した並び"},
     {word:"misspell",meaning:"つづりを間違える",breakdown:"mis（誤って）＋ spell（語る）→ 文字の並べ方を誤る"},
     {word:"spellcheck",meaning:"つづり検査",breakdown:"spell（語る）→ 文字の並びを確かめる"},
     {synonym:true,word:"write",meaning:"書く",breakdown:"文字を記すこと全般。spell は文字の正しい順番に注目"}]},
