  {id:451,word:"stomachache",partOfSpeech:"名詞",meaning:"腹痛",
   meanings:["名|腹痛，胃の痛み"],
   pronunciation:"/ˈstʌmək.eɪk/",part:46,
   example:"He got a bad stomachache after eating too much cake.",
   exampleJa:"彼はケーキを食べすぎたあと、ひどい腹痛になった。",
   example2:"A sudden stomachache kept her from joining the morning practice.",
   exampleJa2:"急な腹痛のせいで、彼女は朝練に参加できなかった。",
   etymologyProcess:"stomach（胃）＋ ache（痛み）→ 胃のあたりに出る痛みは…？",
   etymologyConclusion:"stomach（胃）＋ ache（痛み）→ 食べ物をためる袋のあたりがずきずきする＝腹痛",
   relatedWords:[
     {word:"headache",meaning:"頭痛",breakdown:"head（頭）＋ ache（痛み）→ 頭の中がずきずきと痛むこと"},
     {word:"toothache",meaning:"歯痛",breakdown:"tooth（歯）＋ ache（痛み）→ 歯の一本がずきずきと痛むこと"},
     {word:"ache",meaning:"うずく；痛み",breakdown:"ache（痛み）→ 鋭くはないが、長く続いて体にこもる痛み"},
     {word:"stomach",meaning:"胃，腹",breakdown:"stomach（胃）→ 食べた物をいったんためておく体の袋"}]},

  {id:452,word:"symptom",partOfSpeech:"名詞",meaning:"症状",
   meanings:["名|症状","名|（悪いことの）兆し"],
   pronunciation:"/ˈsɪmptəm/",part:46,
   example:"A high fever is the most common symptom of this illness.",
   exampleJa:"高熱が、この病気のいちばんよく見られる症状だ。",
   example2:"The doctor asked me to write down all my symptoms carefully.",
   exampleJa2:"医者は私に、自分の症状をすべて丁寧に書き出すよう言った。",
   etymologyProcess:"sym（共に）＋ ptom（落ちる）→ 病気と一緒に降りかかってくるものは…？",
   etymologyConclusion:"sym（共に）＋ ptom（落ちる）→ 病気と一緒に体に降りかかってくる目印＝症状",
   relatedWords:[
     {word:"sympathy",meaning:"同情",breakdown:"sym（共に）＋ path（感じる）→ 相手と同じ痛みを一緒に感じる心"},
     {word:"symbol",meaning:"象徴",breakdown:"sym（共に）＋ bol（投げる）→ 二つを重ね投げて合わせた目印"},
     {word:"system",meaning:"制度，体系",breakdown:"sym（共に）＋ stem（立てる）→ ばらばらの物を共に立てて組んだ全体"},
     {synonym:true,word:"sign",meaning:"兆候，しるし",breakdown:"何かを知らせる目印全般。symptom は体に出る病気の目印"}]},

  {id:453,word:"cancer",partOfSpeech:"名詞",meaning:"がん",
   meanings:["名|がん，悪性腫瘍"],
   pronunciation:"/ˈkænsər/",part:46,
   example:"Doctors say early tests can help them find cancer sooner.",
   exampleJa:"医師たちは、早い検査ががんの早期発見に役立つと言う。",
   example2:"Her grandmother fought cancer for years and finally got well again.",
   exampleJa2:"彼女の祖母は何年もがんと闘い、ついにまた元気になった。",
   hook:"ラテン語の「カニ」が語源。腫瘍が周りへ脚を伸ばす形をカニに見立てた。",
   etymologyProcess:"cancer（カニ）→ 脚を広げるように周りへ食い込む病は…？",
   etymologyConclusion:"cancer（カニ）→ カニの脚のように周りの組織へ広がっていく病気＝がん",
   relatedWords:[
     {synonym:true,word:"tumor",meaning:"腫瘍",breakdown:"体の中でふくらんだかたまり。cancer はそのうち悪性のもの"},
     {synonym:true,word:"disease",meaning:"病気",breakdown:"体の調子が崩れた状態全般。cancer はその中の一つの病名"},
     {synonym:true,word:"cure",meaning:"～を治す",breakdown:"病気を治すこと。cancer は治療が長く続く代表的な病気"},
     {synonym:true,word:"patient",meaning:"患者",breakdown:"治療を受ける人。cancer の患者は定期的な検査を受ける"}]},

  {id:454,word:"ambulance",partOfSpeech:"名詞",meaning:"救急車",
   meanings:["名|救急車"],
   pronunciation:"/ˈæmbjələns/",part:46,
   example:"Someone called an ambulance as soon as the old man fell.",
   exampleJa:"その老人が倒れるとすぐに、誰かが救急車を呼んだ。",
   example2:"Two ambulances arrived at the school gate within five minutes.",
   exampleJa2:"5分以内に、2台の救急車が校門に到着した。",
   etymologyProcess:"ambul（歩く）＋ ance（名詞）→ 戦場を歩いて回った移動病院は…？",
   etymologyConclusion:"ambul（歩く）＋ ance（名詞）→ 患者のところまで歩いて出向く動く病院＝救急車",
   relatedWords:[
     {word:"amble",meaning:"ぶらぶら歩く",breakdown:"ambul（歩く）→ 急がずにゆっくりと歩いて進む"},
     {synonym:true,word:"emergency",meaning:"緊急事態",breakdown:"すぐ手当てが必要な場面。ambulance はそこへ向かう車"},
     {synonym:true,word:"hospital",meaning:"病院",breakdown:"治療する建物。ambulance は患者をそこまで運ぶ役"},
     {word:"preamble",meaning:"前置き，序文",breakdown:"pre（先に）＋ ambul（歩く）→ 本題の前を軽く歩いて通る導入"}]},

  {id:455,word:"recover",partOfSpeech:"他動詞・自動詞",meaning:"回復する",
   meanings:["自|回復する","他|～を取り戻す"],
   pronunciation:"/rɪˈkʌvər/",part:46,
   example:"It took him a month to recover from the bad flu.",
   exampleJa:"ひどいインフルエンザから回復するのに、彼は1か月かかった。",
   example2:"She recovered quickly and was back at club practice on Monday.",
   exampleJa2:"彼女は早く回復し、月曜には部活の練習に戻っていた。",
   etymologyProcess:"re（再び）＋ cuper（つかむ）→ 手からこぼれたものをもう一度…？",
   etymologyConclusion:"re（再び）＋ cuper（つかむ）→ 失った体調や物をもう一度自分の手につかみ直す＝回復する",
   relatedWords:[
     {word:"recovery",meaning:"回復",breakdown:"re（再び）＋ cuper（つかむ）→ 元の状態を取り戻していくこと"},
     {synonym:true,word:"heal",meaning:"治る",breakdown:"傷がふさがって元に戻る。recover は体力や損失まで取り戻す"},
     {synonym:true,word:"cure",meaning:"～を治す",breakdown:"医者が病気を治す側。recover は本人が治っていく側"},
     {synonym:true,word:"restore",meaning:"～を元に戻す",breakdown:"崩れたものを元の状態に立て直す。recover は自分が戻る"}]},

  {id:456,word:"sore",partOfSpeech:"形容詞",meaning:"（触ると）ひりひり痛い",
   meanings:["形|（触ると）ひりひり痛い","名|ただれ，傷口"],
   pronunciation:"/sɔːr/",part:46,
   example:"My throat is so sore that I can hardly speak today.",
   exampleJa:"のどがとてもひりひり痛くて、今日はほとんど話せない。",
   example2:"After the long run my legs felt sore for two days.",
   exampleJa2:"長距離走のあと、私の脚は2日間ひりひり痛んだ。",
   hook:"sore throat（のどが痛い）の形で覚える。表面がしみる痛みに使う。",
   etymologyProcess:"sore（痛む）→ 触れるだけでしみるような感じは…？",
   etymologyConclusion:"sore（痛む）→ 触れたりこすれたりするだけでしみる感じ＝ひりひり痛い",
   relatedWords:[
     {word:"sorry",meaning:"すまなく思う",breakdown:"sore（痛む）→ 相手を思って心のほうが痛んでいる状態"},
     {synonym:true,word:"ache",meaning:"うずく",breakdown:"奥で鈍く続く痛み。sore は表面がしみる痛み"},
     {synonym:true,word:"hurt",meaning:"痛む",breakdown:"痛み全般を表す一番ふつうの語。sore は状態を表す形容詞"},
     {synonym:true,word:"painful",meaning:"痛みを伴う",breakdown:"痛みが強いことを客観的に言う。sore は本人の感覚"}]},

  {id:457,word:"swell",partOfSpeech:"自動詞",meaning:"腫れる",
   meanings:["自|腫れる，ふくらむ","自|（数量が）増大する"],
   pronunciation:"/swel/",part:46,
   example:"His ankle began to swell right after he twisted it.",
   exampleJa:"彼の足首は、ひねった直後から腫れ始めた。",
   example2:"My finger swelled up badly when a bee stung me yesterday.",
   exampleJa2:"昨日ハチに刺されたとき、私の指はひどく腫れ上がった。",
   hook:"「腫れる」と「数が増える」は同じ絵。中身が増えて外へふくらむ動き。",
   etymologyProcess:"swell（ふくらむ）→ 中身が増えて外へ盛り上がると…？",
   etymologyConclusion:"swell（ふくらむ）→ 中身が増えて外側へ丸く盛り上がってくる＝腫れる",
   relatedWords:[
     {word:"swelling",meaning:"腫れ",breakdown:"swell（ふくらむ）＋ ing（名詞）→ ふくらんで盛り上がった部分"},
     {word:"swollen",meaning:"腫れ上がった",breakdown:"swell（ふくらむ）→ ふくらみきってしまった状態"},
     {synonym:true,word:"expand",meaning:"広がる",breakdown:"面や範囲が広がる。swell は中身が増えて盛り上がる"},
     {synonym:true,word:"increase",meaning:"増える",breakdown:"数や量が増える。swell は目に見えてふくらむ感じが強い"}]},

  {id:458,word:"cough",partOfSpeech:"自動詞",meaning:"咳をする",
   meanings:["自|咳をする","名|咳"],
   pronunciation:"/kɔːf/",part:46,
   example:"He began to cough loudly in the middle of the concert.",
   exampleJa:"彼はコンサートの途中で大きく咳をし始めた。",
   example2:"She coughed all night and decided to stay home from school.",
   exampleJa2:"彼女は一晩中咳をして、学校を休むことに決めた。",
   hook:"ゴホッという音をそのまま写した語。発音は「コフ」で gh は f の音。",
   etymologyProcess:"cough（ゴホッという音）→ のどを鳴らして息を押し出すと…？",
   etymologyConclusion:"cough（ゴホッという音）→ のどを鳴らして息を勢いよく押し出す＝咳をする",
   relatedWords:[
     {synonym:true,word:"sneeze",meaning:"くしゃみをする",breakdown:"鼻から息を吹き出す。cough はのどから押し出す"},
     {synonym:true,word:"breathe",meaning:"呼吸する",breakdown:"静かに息を出し入れする。cough は激しく吐き出す"},
     {synonym:true,word:"throat",meaning:"のど",breakdown:"咳が出る場所。sore throat で「のどが痛い」"},
     {synonym:true,word:"fever",meaning:"熱",breakdown:"かぜのもう一つの症状。cough と一緒に出ることが多い"}]},

  {id:459,word:"bleed",partOfSpeech:"自動詞",meaning:"出血する",
   meanings:["自|出血する","他|～から血を抜く"],
   pronunciation:"/bliːd/",part:46,
   example:"He started to bleed from the nose during the basketball game.",
   exampleJa:"バスケの試合中、彼は鼻から出血し始めた。",
   example2:"Press the cut with a clean cloth until it stops bleeding.",
   exampleJa2:"出血が止まるまで、切り傷を清潔な布で押さえなさい。",
   etymologyProcess:"blood（血）→ 体の中の赤い液が外へ出てくると…？",
   etymologyConclusion:"blood（血）→ 体の中をめぐる赤い液が傷口から外へ流れ出る＝出血する",
   relatedWords:[
     {word:"blood",meaning:"血",breakdown:"blood（血）→ 体じゅうをめぐって酸素を運ぶ赤い液"},
     {word:"bloody",meaning:"血まみれの",breakdown:"blood（血）＋ y（〜な状態の）→ 血がべったりついている"},
     {synonym:true,word:"wound",meaning:"傷",breakdown:"刃物などでできた傷。bleed はそこから血が出る動き"},
     {synonym:true,word:"injure",meaning:"～を傷つける",breakdown:"けがをさせる。bleed はその結果として起こること"}]},

  {id:460,word:"faint",partOfSpeech:"形容詞",meaning:"かすかな",
   meanings:["形|かすかな，ぼんやりした","自|気を失う"],
   pronunciation:"/feɪnt/",part:46,
   example:"We heard a faint sound of music from the next room.",
   exampleJa:"私たちは隣の部屋からかすかな音楽の音を聞いた。",
   example2:"There was only a faint hope that the team would win.",
   exampleJa2:"そのチームが勝つという、かすかな望みしかなかった。",
   hook:"「かすかな」と「気を失う」は同じ絵。力が抜けて存在が薄くなること。",
   etymologyProcess:"feint（力を抜く）→ 力が抜けて気配が薄くなると…？",
   etymologyConclusion:"feint（力を抜く）→ 力が抜けて、あるかないか分からないほど薄い＝かすかな",
   relatedWords:[
     {word:"faintly",meaning:"かすかに",breakdown:"feint（力を抜く）＋ ly（副詞）→ 力なくぼんやりと"},
     {word:"feign",meaning:"～のふりをする",breakdown:"feint（力を抜く）→ 本気を出さず、そういうふりだけをする"},
     {synonym:true,word:"dim",meaning:"薄暗い",breakdown:"光が弱い。faint は光にも音にも望みにも使える"},
     {synonym:true,word:"weak",meaning:"弱い",breakdown:"力が足りない。faint は感じ取りにくいほど弱い"}]},

  {id:461,word:"exhaust",partOfSpeech:"他動詞",meaning:"～を疲れ果てさせる",
   meanings:["他|～を疲れ果てさせる","他|（資源など）を使い尽くす"],
   pronunciation:"/ɪɡˈzɔːst/",part:47,
   example:"The long trip through the mountains exhausted every member of the group.",
   exampleJa:"山を越える長い旅は、その一行の全員を疲れ果てさせた。",
   example2:"I was completely exhausted after three hours of practice in the heat.",
   exampleJa2:"暑さの中での3時間の練習のあと、私は完全に疲れ果てていた。",
   etymologyProcess:"ex（外へ）＋ haust（汲み出す）→ 中身を最後まで汲み出すと…？",
   etymologyConclusion:"ex（外へ）＋ haust（汲み出す）→ 体力を一滴残らず外へ汲み出してしまう＝疲れ果てさせる",
   relatedWords:[
     {word:"exhausted",meaning:"疲れ果てた",breakdown:"ex（外へ）＋ haust（汲み出す）＋ ed（〜された）→ 力を汲み出された"},
     {word:"exhausting",meaning:"へとへとにさせる",breakdown:"ex（外へ）＋ haust（汲み出す）＋ ing（〜している）→ 力を奪う側"},
     {word:"exhaustion",meaning:"極度の疲労",breakdown:"ex（外へ）＋ haust（汲み出す）＋ ion（名詞）→ 汲み尽くされた状態"},
     {synonym:true,word:"tired",meaning:"疲れた",breakdown:"ふつうの疲れ。exhausted は動けないほどの疲れ"}]},

  {id:462,word:"cure",partOfSpeech:"他動詞",meaning:"～を治す",
   meanings:["他|～を治す，治療する","名|治療法"],
   pronunciation:"/kjʊr/",part:47,
   example:"This new medicine can cure the illness in about two weeks.",
   exampleJa:"この新しい薬は、その病気を2週間ほどで治すことができる。",
   example2:"The doctor cured my sister's skin trouble with a simple cream.",
   exampleJa2:"医者は簡単なクリームで妹の肌の不調を治した。",
   etymologyProcess:"cur（気にかける）→ 相手の体を気にかけて手を尽くすと…？",
   etymologyConclusion:"cur（気にかける）→ 相手の体を気にかけて手を尽くし、悪い所を取り除く＝治す",
   relatedWords:[
     {word:"curious",meaning:"好奇心の強い",breakdown:"cur（気にかける）＋ ous（形容詞）→ 何でも気にかけて知りたがる"},
     {word:"accurate",meaning:"正確な",breakdown:"ad（〜へ）＋ cur（気にかける）→ 細かい所まで気を配ってずれがない"},
     {word:"secure",meaning:"安全な",breakdown:"se（離れて）＋ cur（気にかける）→ 心配ごとから離れていて安心できる"},
     {synonym:true,word:"heal",meaning:"治る",breakdown:"傷がふさがって元に戻る。cure は医者や薬が治す側"}]},

  {id:463,word:"disabled",partOfSpeech:"形容詞",meaning:"障がいのある",
   meanings:["形|障がいのある","形|（機能が）使えなくされた"],
   pronunciation:"/dɪsˈeɪbld/",part:47,
   example:"This hotel has ten rooms designed for disabled guests and families.",
   exampleJa:"このホテルには、障がいのある客と家族のための部屋が10室ある。",
   example2:"Our school built a new ramp so disabled students can enter easily.",
   exampleJa2:"私たちの学校は、障がいのある生徒が楽に入れるよう新しい坂道を作った。",
   etymologyProcess:"dis（否定）＋ able（できる）→ できる力をさまたげられた状態は…？",
   etymologyConclusion:"dis（否定）＋ able（できる）＋ ed（〜された）→ ある動作をする力をさまたげられた＝障がいのある",
   relatedWords:[
     {word:"able",meaning:"～できる",breakdown:"able（できる）→ その動作をする力を持っている"},
     {word:"ability",meaning:"能力",breakdown:"abil（できる）＋ ity（名詞）→ 何かをやりとげられる力そのもの"},
     {word:"disability",meaning:"障がい",breakdown:"dis（否定）＋ abil（できる）＋ ity（名詞）→ 力がさまたげられている状態"},
     {word:"enable",meaning:"～を可能にする",breakdown:"en（〜にする）＋ able（できる）→ できる状態へ押し上げてやる"}]},

  {id:464,word:"stiff",partOfSpeech:"形容詞",meaning:"凝った，こわばった",
   meanings:["形|凝った，こわばった","形|（態度が）堅苦しい"],
   pronunciation:"/stɪf/",part:47,
   example:"My shoulders feel stiff because I studied at my desk all day.",
   exampleJa:"一日中机で勉強したので、私の肩は凝っている。",
   example2:"His legs were stiff the morning after the long tennis match.",
   exampleJa2:"長いテニスの試合の翌朝、彼の脚はこわばっていた。",
   hook:"「体が凝る」と「態度が堅苦しい」は同じ絵。曲がらず固まっていること。",
   etymologyProcess:"stiff（こわばった）→ 曲がらず固まってしまった感じは…？",
   etymologyConclusion:"stiff（こわばった）→ やわらかく曲がらず、固まって動かしにくい＝凝った，こわばった",
   relatedWords:[
     {word:"stiffen",meaning:"こわばる",breakdown:"stiff（こわばった）＋ en（〜にする）→ 固まって動きにくくなる"},
     {synonym:true,word:"tight",meaning:"きつい",breakdown:"ゆとりがなく締まっている。stiff は曲がらないほうに寄る"},
     {synonym:true,word:"hard",meaning:"かたい",breakdown:"押しても形が変わらない。stiff は曲げようとして曲がらない"},
     {synonym:true,word:"sore",meaning:"ひりひり痛い",breakdown:"こすれてしみる痛み。stiff は固まって動かしにくい状態"}]},

  {id:465,word:"muscle",partOfSpeech:"名詞",meaning:"筋肉",
   meanings:["名|筋肉","名|腕力"],
   pronunciation:"/ˈmʌsl/",part:47,
   example:"Swimming every morning helped him build strong muscles in his arms.",
   exampleJa:"毎朝泳いだことで、彼は腕に強い筋肉をつけることができた。",
   example2:"I pulled a muscle in my leg during yesterday's soccer game.",
   exampleJa2:"昨日のサッカーの試合中、私は脚の筋肉を痛めた。",
   etymologyProcess:"mus（ねずみ）＋ cle（もの）→ 皮の下で動く小さなねずみは…？",
   etymologyConclusion:"mus（ねずみ）＋ cle（もの）→ 力こぶが皮の下を走る小ねずみに見えた＝筋肉",
   relatedWords:[
     {word:"muscular",meaning:"筋肉のたくましい",breakdown:"mus（ねずみ）＋ cle（もの）＋ ar（形容詞）→ 筋肉が盛り上がった"},
     {word:"mussel",meaning:"ムール貝",breakdown:"mus（ねずみ）＋ cle（もの）→ 小さなねずみに似た形の黒い貝"},
     {synonym:true,word:"bone",meaning:"骨",breakdown:"体を支えるかたい部分。muscle はそれを動かす部分"},
     {synonym:true,word:"strength",meaning:"体力",breakdown:"力そのもの。muscle は力を生み出す体の部品"}]},

  {id:466,word:"tongue",partOfSpeech:"名詞",meaning:"舌",
   meanings:["名|舌","名|（母語としての）言語"],
   pronunciation:"/tʌŋ/",part:47,
   example:"I burned my tongue on the hot soup at dinner last night.",
   exampleJa:"私は昨夜の夕食で、熱いスープで舌をやけどした。",
   example2:"The doctor asked the boy to stick out his tongue slowly.",
   exampleJa2:"医者はその少年に、ゆっくり舌を出すように言った。",
   hook:"mother tongue（母語）のように「言語」の意味もある。話す道具が舌だから。",
   etymologyProcess:"tongue（舌）→ 味を感じ、言葉を作るこの器官は…？",
   etymologyConclusion:"tongue（舌）→ 味を感じ取り、動いて言葉の音を作り出す器官＝舌",
   relatedWords:[
     {synonym:true,word:"taste",meaning:"～の味がする",breakdown:"舌がする仕事。tongue はその働きをする器官そのもの"},
     {synonym:true,word:"language",meaning:"言語",breakdown:"話す中身。tongue は母語を指すときに使う古い言い方"},
     {synonym:true,word:"lip",meaning:"くちびる",breakdown:"口の外側。tongue は口の中で動くほう"},
     {synonym:true,word:"throat",meaning:"のど",breakdown:"舌の奥へ続く通り道。声はここから出る"}]},

  {id:467,word:"sense",partOfSpeech:"名詞",meaning:"感覚",
   meanings:["名|感覚","名|分別，判断力","他|～を感じ取る"],
   pronunciation:"/sens/",part:47,
   example:"Dogs have a much better sense of smell than humans do.",
   exampleJa:"犬は人間よりもずっと優れたにおいの感覚を持っている。",
   example2:"After the accident he lost all sense of touch in one hand.",
   exampleJa2:"事故のあと、彼は片手の触れる感覚をすべて失った。",
   etymologyProcess:"sens（感じる）→ 外の世界を体で受け取る力は…？",
   etymologyConclusion:"sens（感じる）→ 外の世界のようすを体で直接受け取る力＝感覚",
   relatedWords:[
     {word:"sensitive",meaning:"敏感な",breakdown:"sens（感じる）＋ itive（形容詞）→ わずかな変化もすぐ感じ取る"},
     {word:"sensible",meaning:"分別のある",breakdown:"sens（感じる）＋ ible（できる）→ 物事を感じ取って正しく判断できる"},
     {word:"nonsense",meaning:"ばかげたこと",breakdown:"non（否定）＋ sens（感じる）→ 意味がまるで感じ取れない話"},
     {word:"sensation",meaning:"感じ，大騒ぎ",breakdown:"sens（感じる）＋ ation（名詞）→ 体や世間が受けた強い感じ"}]},

  {id:468,word:"sweat",partOfSpeech:"名詞",meaning:"汗",
   meanings:["名|汗","自|汗をかく"],
   pronunciation:"/swet/",part:47,
   example:"Sweat ran down his face as he finished the last lap.",
   exampleJa:"最後の1周を走り終えるとき、汗が彼の顔を流れ落ちた。",
   example2:"She wiped the sweat from her forehead after the long practice.",
   exampleJa2:"長い練習のあと、彼女は額から汗をぬぐった。",
   hook:"no sweat は「お安いご用」。汗をかくほどの苦労ではない、という意味。",
   etymologyProcess:"sweat（汗）→ 体を冷やすために皮膚からにじむ水は…？",
   etymologyConclusion:"sweat（汗）→ 体を冷やすために皮膚からにじみ出てくる塩気のある水＝汗",
   relatedWords:[
     {word:"sweaty",meaning:"汗ばんだ",breakdown:"sweat（汗）＋ y（〜な状態の）→ 汗でじっとりしている"},
     {synonym:true,word:"tear",meaning:"涙",breakdown:"目から出るしずく。sweat は皮膚全体から出るしずく"},
     {word:"sweatshirt",meaning:"トレーナー",breakdown:"sweat（汗）＋ shirt（シャツ）→ 汗をかく運動のために着る上着"},
     {synonym:true,word:"effort",meaning:"努力",breakdown:"sweat は汗をかくほどの苦労そのものを指すこともある"}]},

  {id:469,word:"gender",partOfSpeech:"名詞",meaning:"性，性別",
   meanings:["名|性，性別","名|（文法の）性"],
   pronunciation:"/ˈdʒendər/",part:47,
   example:"The company hires people without asking about their age or gender.",
   exampleJa:"その会社は、年齢や性別を尋ねずに人を採用する。",
   example2:"Our class discussed gender roles in Japanese homes for one hour.",
   exampleJa2:"私たちのクラスは、日本の家庭での性別の役割について1時間話し合った。",
   etymologyProcess:"gener（生み出す）→ 生まれつきで分けられる種類は…？",
   etymologyConclusion:"gener（生み出す）→ 生まれによって分けられる人の種類＝性，性別",
   relatedWords:[
     {word:"generation",meaning:"世代",breakdown:"gener（生み出す）＋ ation（名詞）→ 同じころに生み出された人々"},
     {word:"general",meaning:"全体の，一般の",breakdown:"gener（生み出す）＋ al（〜の）→ 同じ種から出た全体に当てはまる"},
     {word:"gene",meaning:"遺伝子",breakdown:"gener（生み出す）→ 生まれつきの特徴を作り出すもと"},
     {synonym:true,word:"sex",meaning:"（生物学上の）性",breakdown:"体のつくりで分ける性。gender は社会的な役割も含む"}]},

  {id:470,word:"nationality",partOfSpeech:"名詞",meaning:"国籍",
   meanings:["名|国籍","名|国民性"],
   pronunciation:"/ˌnæʃəˈnæləti/",part:47,
   example:"Please write your name and nationality clearly on this entry form.",
   exampleJa:"この入国用紙に、名前と国籍をはっきり書いてください。",
   example2:"Students of five different nationalities joined our school festival this year.",
   exampleJa2:"今年、5つの異なる国籍の生徒が私たちの学園祭に参加した。",
   etymologyProcess:"nat（生まれる）＋ ion（名詞）→ 生まれた国に属していることは…？",
   etymologyConclusion:"nat（生まれる）＋ ion（名詞）＋ al（〜の）＋ ity（名詞）→ 生まれた国に属する資格＝国籍",
   relatedWords:[
     {word:"nation",meaning:"国家",breakdown:"nat（生まれる）＋ ion（名詞）→ 同じ土地に生まれた人々のまとまり"},
     {word:"national",meaning:"国の，全国的な",breakdown:"nat（生まれる）＋ ion（名詞）＋ al（〜の）→ 国全体にかかわる"},
     {word:"native",meaning:"母国の",breakdown:"nat（生まれる）＋ ive（〜な性質の）→ 生まれたときからそこのもの"},
     {word:"nature",meaning:"自然",breakdown:"nat（生まれる）＋ ure（もの）→ 生まれたままの、手を加えない姿"}]},

  {id:471,word:"citizen",partOfSpeech:"名詞",meaning:"市民",
   meanings:["名|市民","名|国民"],
   pronunciation:"/ˈsɪtəzn/",part:48,
   example:"Every citizen of this town can use the library for free.",
   exampleJa:"この町のすべての市民は、図書館を無料で使うことができる。",
   example2:"She became a Japanese citizen after living here for ten years.",
   exampleJa2:"彼女はここに10年住んだあと、日本の市民になった。",
   etymologyProcess:"civ（市民）＋ izen（人）→ 都市に暮らし権利を持つ人は…？",
   etymologyConclusion:"civ（市民）＋ izen（人）→ 都市に暮らし、その一員としての権利を持つ人＝市民",
   relatedWords:[
     {word:"city",meaning:"都市",breakdown:"civ（市民）→ 市民たちが集まって暮らす大きなまち"},
     {word:"civil",meaning:"市民の",breakdown:"civ（市民）＋ il（〜の）→ 軍や国ではなく市民の側にかかわる"},
     {word:"civilization",meaning:"文明",breakdown:"civ（市民）＋ ation（名詞）→ 市民の暮らしが育ててきた仕組み"},
     {word:"civilian",meaning:"民間人",breakdown:"civ（市民）＋ ian（人）→ 軍人ではない、ふつうの暮らしの人"}]},

  {id:472,word:"civil",partOfSpeech:"形容詞",meaning:"市民の",
   meanings:["形|市民の，民間の","形|礼儀正しい"],
   pronunciation:"/ˈsɪvl/",part:48,
   example:"The civil rights of every worker are protected by this law.",
   exampleJa:"すべての労働者の市民としての権利は、この法律で守られている。",
   example2:"A long civil war divided that country for almost four years.",
   exampleJa2:"長い内戦が、その国を4年近く分断した。",
   etymologyProcess:"civ（市民）＋ il（〜の）→ 軍でも国でもなく市民の側のことは…？",
   etymologyConclusion:"civ（市民）＋ il（〜の）→ 軍や王ではなく、市民の側にかかわっている＝市民の",
   relatedWords:[
     {word:"citizen",meaning:"市民",breakdown:"civ（市民）＋ izen（人）→ 都市の一員として権利を持つ人"},
     {word:"city",meaning:"都市",breakdown:"civ（市民）→ 市民たちが集まって暮らす大きなまち"},
     {word:"civilization",meaning:"文明",breakdown:"civ（市民）＋ ation（名詞）→ 市民の暮らしが育ててきた仕組み"},
     {synonym:true,word:"public",meaning:"公共の",breakdown:"みんなのためのもの。civil は国や軍に対する市民の側"}]},

  {id:473,word:"racial",partOfSpeech:"形容詞",meaning:"人種の",
   meanings:["形|人種の，人種間の"],
   pronunciation:"/ˈreɪʃl/",part:48,
   example:"The new law was written to stop racial discrimination at work.",
   exampleJa:"その新しい法律は、職場での人種の差別をなくすために作られた。",
   example2:"Our teacher showed a film about racial problems in American schools.",
   exampleJa2:"先生はアメリカの学校での人種の問題についての映画を見せた。",
   etymologyProcess:"race（人種）＋ al（〜の）→ 生まれの系統による分け方は…？",
   etymologyConclusion:"race（人種）＋ al（〜の）→ 生まれの系統で人を分けた区分にかかわる＝人種の",
   relatedWords:[
     {word:"race",meaning:"人種",breakdown:"race（人種）→ 同じ系統に生まれたと見なされる人々のまとまり"},
     {word:"racism",meaning:"人種差別",breakdown:"race（人種）＋ ism（主義）→ 人種で人を上下に分ける考え方"},
     {word:"racist",meaning:"人種差別主義者",breakdown:"race（人種）＋ ist（人）→ 人種で人を上下に分ける人"},
     {synonym:true,word:"ethnic",meaning:"民族の",breakdown:"言葉や文化で分ける区分。racial は体の特徴による区分"}]},

  {id:474,word:"rural",partOfSpeech:"形容詞",meaning:"田舎の",
   meanings:["形|田舎の，農村の"],
   pronunciation:"/ˈrʊrəl/",part:48,
   example:"Many young people are leaving rural areas to work in cities.",
   exampleJa:"多くの若者が、都市で働くために田舎の地域を離れている。",
   example2:"My grandparents live in a quiet rural village near the mountains.",
   exampleJa2:"私の祖父母は、山の近くの静かな田舎の村に住んでいる。",
   etymologyProcess:"rur（田畑）＋ al（〜の）→ 畑と野原が広がる土地のことは…？",
   etymologyConclusion:"rur（田畑）＋ al（〜の）→ 建物より畑と野原が広がる土地にかかわる＝田舎の",
   relatedWords:[
     {word:"rustic",meaning:"田舎風の",breakdown:"rur（田畑）→ 同じ田畑の語根。畑のくらしのような素朴な感じ"},
     {synonym:true,word:"urban",meaning:"都市の",breakdown:"建物が密集した都市の。rural はその正反対の語"},
     {synonym:true,word:"countryside",meaning:"田園地帯",breakdown:"田舎の風景そのもの。rural はそれを表す形容詞"},
     {synonym:true,word:"farm",meaning:"農場",breakdown:"田舎の暮らしの中心。rural な地域に広がっている"}]},

  {id:475,word:"domestic",partOfSpeech:"形容詞",meaning:"国内の",
   meanings:["形|国内の","形|家庭の"],
   pronunciation:"/dəˈmestɪk/",part:48,
   example:"Domestic flights from this airport are cheaper than international ones.",
   exampleJa:"この空港からの国内線は、国際線より安い。",
   example2:"The company sells most of its bread in the domestic market.",
   exampleJa2:"その会社はパンの大半を国内の市場で売っている。",
   etymologyProcess:"dom（家）＋ ic（形容詞）→ 自分の家の内側にあたる範囲は…？",
   etymologyConclusion:"dom（家）＋ ic（形容詞）→ 外ではなく自分の家の内側にあたる範囲＝国内の",
   relatedWords:[
     {word:"dome",meaning:"丸屋根，ドーム",breakdown:"dom（家）→ 家の上にかぶせた丸い屋根"},
     {word:"dominate",meaning:"～を支配する",breakdown:"dom（家）＋ ate（動詞）→ 家の主として上から取りしきる"},
     {word:"dominant",meaning:"支配的な",breakdown:"dom（家）＋ ant（〜な）→ 家の主のように一番上に立っている"},
     {synonym:true,word:"international",meaning:"国際的な",breakdown:"国と国をまたぐ。domestic はその正反対の語"}]},

  {id:476,word:"global",partOfSpeech:"形容詞",meaning:"世界的な",
   meanings:["形|世界的な，地球規模の"],
   pronunciation:"/ˈɡloʊbl/",part:48,
   example:"Climate change has become a global problem for every country.",
   exampleJa:"気候変動は、すべての国にとって世界的な問題になった。",
   example2:"Our class joined a global project with students from six countries.",
   exampleJa2:"私たちのクラスは、6か国の生徒と世界的な企画に参加した。",
   etymologyProcess:"globe（球）＋ al（〜の）→ 丸い地球ぜんたいに広がることは…？",
   etymologyConclusion:"globe（球）＋ al（〜の）→ 丸い地球ぜんたいに広がっている＝世界的な",
   relatedWords:[
     {word:"globe",meaning:"地球，球体",breakdown:"globe（球）→ まるい玉。とくに丸い地球そのもの"},
     {word:"globalization",meaning:"グローバル化",breakdown:"globe（球）＋ ation（名詞）→ 世界が一つにつながっていくこと"},
     {word:"globally",meaning:"世界的に",breakdown:"globe（球）＋ ly（副詞）→ 地球ぜんたいの規模で"},
     {synonym:true,word:"worldwide",meaning:"世界中の",breakdown:"世界のすみずみまで。global は地球を一つと見る言い方"}]},

  {id:477,word:"suburb",partOfSpeech:"名詞",meaning:"郊外",
   meanings:["名|郊外，近郊の住宅地"],
   pronunciation:"/ˈsʌbɜːrb/",part:48,
   example:"They moved to a quiet suburb about an hour from Tokyo.",
   exampleJa:"彼らは東京から1時間ほどの静かな郊外に引っ越した。",
   example2:"Many families in the suburbs drive their children to school daily.",
   exampleJa2:"郊外の多くの家庭は、毎日子どもを車で学校へ送っている。",
   etymologyProcess:"sub（下で）＋ urb（都市）→ 都市のすそに広がる住宅地は…？",
   etymologyConclusion:"sub（下で）＋ urb（都市）→ 都市の足元のすそに広がって並ぶ住宅地＝郊外",
   relatedWords:[
     {word:"urban",meaning:"都市の",breakdown:"urb（都市）＋ an（〜の）→ 建物が密に並ぶ都市にかかわる"},
     {word:"suburban",meaning:"郊外の",breakdown:"sub（下で）＋ urb（都市）＋ an（〜の）→ 都市のすそに広がる"},
     {synonym:true,word:"downtown",meaning:"中心街",breakdown:"まちの真ん中。suburb はその外側に広がる住宅地"},
     {synonym:true,word:"neighborhood",meaning:"近所",breakdown:"住まいの周り。suburb は都市の外側という位置を示す"}]},

  {id:478,word:"border",partOfSpeech:"名詞",meaning:"国境",
   meanings:["名|国境，境界","他|～と接している"],
   pronunciation:"/ˈbɔːrdər/",part:48,
   example:"The train crossed the border between France and Spain at midnight.",
   exampleJa:"その列車は真夜中にフランスとスペインの国境を越えた。",
   example2:"Every car waiting at the border is checked by two officers.",
   exampleJa2:"国境で待つすべての車は、2人の係官によって調べられる。",
   etymologyProcess:"bord（へり）＋ er（もの）→ 土地のいちばん外のへりは…？",
   etymologyConclusion:"bord（へり）＋ er（もの）→ 国の土地がそこで終わるいちばん外のへり＝国境",
   relatedWords:[
     {word:"borderline",meaning:"境界線",breakdown:"bord（へり）＋ line（線）→ へりに沿って引かれた一本の線"},
     {word:"board",meaning:"板",breakdown:"bord（へり）→ もとは船のへり。そこから平たい板を指す"},
     {synonym:true,word:"boundary",meaning:"境界",breakdown:"区切りの線全般。border は国と国の区切りによく使う"},
     {synonym:true,word:"edge",meaning:"端",breakdown:"物のふち。border は土地や国のふちに限って使う"}]},

  {id:479,word:"burden",partOfSpeech:"名詞",meaning:"重荷，負担",
   meanings:["名|重荷，負担","他|～に負担をかける"],
   pronunciation:"/ˈbɜːrdn/",part:48,
   example:"The cost of the trip became a heavy burden for his family.",
   exampleJa:"その旅行の費用は、彼の家族にとって重い負担になった。",
   example2:"She carried the burden of the whole team on her shoulders.",
   exampleJa2:"彼女はチーム全体の重荷を自分の肩に背負っていた。",
   etymologyProcess:"bear（運ぶ）＋ den（名詞）→ 背負って運ばされるものは…？",
   etymologyConclusion:"bear（運ぶ）＋ den（名詞）→ 背負って運ばなければならない重いもの＝重荷",
   relatedWords:[
     {word:"bear",meaning:"～に耐える",breakdown:"bear（運ぶ）→ 重いものを背負って持ちこたえる"},
     {word:"birth",meaning:"誕生",breakdown:"bear（運ぶ）＋ th（名詞）→ 母が体に運んだ子が世に出ること"},
     {word:"bearer",meaning:"運ぶ人",breakdown:"bear（運ぶ）＋ er（人）→ 荷物や知らせを運んでいく人"},
     {synonym:true,word:"load",meaning:"積み荷",breakdown:"実際に積んだ荷。burden は心の重さにも使える"}]},

  {id:480,word:"impact",partOfSpeech:"名詞",meaning:"大きな影響，衝撃",
   meanings:["名|大きな影響，衝撃","名|衝突の力"],
   pronunciation:"/ˈɪmpækt/",part:48,
   example:"The new rule had a big impact on our club activities.",
   exampleJa:"その新しい規則は、私たちの部活動に大きな影響を与えた。",
   example2:"Everyone in the hall felt the impact of her honest speech.",
   exampleJa2:"会場の全員が、彼女の正直な演説の衝撃を感じた。",
   etymologyProcess:"im（中へ）＋ pact（打ち込む）→ 相手にぶつかって食い込む力は…？",
   etymologyConclusion:"im（中へ）＋ pact（打ち込む）→ 相手の中へ強く打ち込まれてあとに残る力＝大きな影響，衝撃",
   relatedWords:[
     {word:"compact",meaning:"ぎっしり詰まった",breakdown:"com（共に）＋ pact（打ち込む）→ 隙間なく打ち固めて小さくまとめた"},
     {word:"pact",meaning:"協定",breakdown:"pact（打ち込む）→ 両者で打って固めた、動かせない約束"},
     {synonym:true,word:"influence",meaning:"影響（力）",breakdown:"じわじわ効く影響。impact は一撃で残る強い影響"},
     {synonym:true,word:"effect",meaning:"効果",breakdown:"結果として出る変化。impact はその強さを強調する語"}]},

  {id:481,word:"status",partOfSpeech:"名詞",meaning:"地位",
   meanings:["名|地位，身分","名|（進行中の）状況"],
   pronunciation:"/ˈsteɪtəs/",part:49,
   example:"In that village, owning land raised a family's social status.",
   exampleJa:"その村では、土地を持つことが一家の社会的な地位を上げた。",
   example2:"Money alone does not decide a person's status in this school.",
   exampleJa2:"この学校では、お金だけが人の地位を決めるわけではない。",
   etymologyProcess:"sta（立つ）→ 社会の中でその人が立っている場所は…？",
   etymologyConclusion:"sta（立つ）→ 社会という舞台の中でその人が立っている場所＝地位",
   relatedWords:[
     {word:"statue",meaning:"像",breakdown:"sta（立つ）＋ ue（もの）→ 立たせて置いてある人の形"},
     {word:"stable",meaning:"安定した",breakdown:"sta（立つ）＋ able（できる）→ ぐらつかずに立っていられる"},
     {word:"station",meaning:"駅，持ち場",breakdown:"sta（立つ）＋ ion（名詞）→ 動かずに立って待つ決まった場所"},
     {word:"establish",meaning:"～を確立する",breakdown:"e（外へ）＋ sta（立つ）→ 外から見える形にしっかり立てる"}]},

  {id:482,word:"equal",partOfSpeech:"形容詞",meaning:"等しい",
   meanings:["形|等しい","形|平等な","他|～に等しい"],
   pronunciation:"/ˈiːkwəl/",part:49,
   example:"Cut the cake into six equal pieces for all the guests.",
   exampleJa:"すべての客のために、ケーキを6つの等しい大きさに切りなさい。",
   example2:"Every member was given an equal chance to join the team.",
   exampleJa2:"すべての部員に、チームに入る等しい機会が与えられた。",
   etymologyProcess:"equ（等しい）＋ al（〜の）→ どちらにも差がない状態は…？",
   etymologyConclusion:"equ（等しい）＋ al（〜の）→ 二つを並べてもどちらにも差がない＝等しい",
   relatedWords:[
     {word:"equally",meaning:"等しく",breakdown:"equ（等しい）＋ al（〜の）＋ ly（副詞）→ どちらにも差をつけずに"},
     {word:"equality",meaning:"平等",breakdown:"equ（等しい）＋ ity（名詞）→ 扱いに差がないという状態"},
     {word:"equator",meaning:"赤道",breakdown:"equ（等しい）＋ ator（もの）→ 地球を上下に等しく分ける線"},
     {word:"adequate",meaning:"十分な",breakdown:"ad（〜へ）＋ equ（等しい）→ 必要な量にちょうど釣り合っている"}]},

  {id:483,word:"relationship",partOfSpeech:"名詞",meaning:"（人と人の）関係",
   meanings:["名|（人と人の）関係","名|（物事の）関連"],
   pronunciation:"/rɪˈleɪʃnʃɪp/",part:49,
   example:"She has a good relationship with everyone in her host family.",
   exampleJa:"彼女はホストファミリーの全員と良い関係を築いている。",
   example2:"Their relationship as teammates grew stronger after the summer camp.",
   exampleJa2:"チームメイトとしての彼らの関係は、夏合宿のあと強くなった。",
   etymologyProcess:"re（戻す）＋ lat（運ぶ）→ 互いのあいだで行き来するものは…？",
   etymologyConclusion:"re（戻す）＋ lat（運ぶ）＋ ship（名詞）→ 互いに気持ちを運び合っているつながり＝関係",
   relatedWords:[
     {word:"relate",meaning:"～を関連づける",breakdown:"re（戻す）＋ lat（運ぶ）→ 二つのあいだに話を運んで結びつける"},
     {word:"relative",meaning:"親類",breakdown:"re（戻す）＋ lat（運ぶ）＋ ive（〜な性質の）→ 血のつながりで結ばれた人"},
     {word:"translate",meaning:"～を翻訳する",breakdown:"trans（越えて）＋ lat（運ぶ）→ 意味を別の言語へ運び越す"},
     {word:"relation",meaning:"関連",breakdown:"re（戻す）＋ lat（運ぶ）＋ ion（名詞）→ 行き来してできたつながり"}]},

  {id:484,word:"reputation",partOfSpeech:"名詞",meaning:"評判",
   meanings:["名|評判，名声"],
   pronunciation:"/ˌrepjuˈteɪʃn/",part:49,
   example:"That restaurant has a good reputation for its fresh fish.",
   exampleJa:"あのレストランは新鮮な魚で良い評判を得ている。",
   example2:"One careless post can destroy a school's reputation in a day.",
   exampleJa2:"軽はずみな投稿一つが、学校の評判を一日で壊すことがある。",
   etymologyProcess:"re（何度も）＋ puta（考える）→ 世間が繰り返し値ぶみした結果は…？",
   etymologyConclusion:"re（何度も）＋ puta（考える）＋ ation（名詞）→ 世間が何度も値ぶみして固まった見方＝評判",
   relatedWords:[
     {word:"dispute",meaning:"～について論争する",breakdown:"dis（バラバラに）＋ puta（考える）→ 考えが割れて言い合いになる"},
     {word:"compute",meaning:"～を計算する",breakdown:"com（共に）＋ puta（考える）→ 数を合わせて考え、答えを出す"},
     {word:"deputy",meaning:"代理人",breakdown:"de（離して）＋ puta（考える）→ 仕事を切り分けて任された者"},
     {synonym:true,word:"fame",meaning:"名声",breakdown:"広く名が知られること。reputation は良し悪しの評価を含む"}]},

  {id:485,word:"trend",partOfSpeech:"名詞",meaning:"風潮，傾向",
   meanings:["名|風潮，傾向","自|（ある方向へ）向かう"],
   pronunciation:"/trend/",part:49,
   example:"There is a clear trend toward shorter working hours in Japan.",
   exampleJa:"日本では労働時間が短くなるという明らかな風潮がある。",
   example2:"The trend of reading on phones has changed how students study.",
   exampleJa2:"スマホで読むという風潮は、生徒の勉強の仕方を変えた。",
   hook:"a trend toward A（Aへの風潮）の形でよく出る。動詞なら「～へ向かう」。",
   etymologyProcess:"trend（回って向かう）→ 世の中の向きが変わっていくと…？",
   etymologyConclusion:"trend（回って向かう）→ 世の中ぜんたいがある向きへ回って動いていく流れ＝風潮，傾向",
   relatedWords:[
     {word:"trendy",meaning:"流行の",breakdown:"trend（回って向かう）＋ y（〜な状態の）→ 今の向きに乗っている"},
     {synonym:true,word:"fashion",meaning:"流行",breakdown:"服など見た目の流行。trend は世の中全体の動く向き"},
     {synonym:true,word:"tendency",meaning:"傾向",breakdown:"そうなりやすい性質。trend は社会全体の流れを指す"},
     {synonym:true,word:"movement",meaning:"運動，動き",breakdown:"人が起こす動き。trend は自然に生まれる流れ"}]},

  {id:486,word:"service",partOfSpeech:"名詞",meaning:"（公共の）事業，サービス",
   meanings:["名|（公共の）事業，サービス","名|奉仕，勤務"],
   pronunciation:"/ˈsɜːrvɪs/",part:49,
   example:"The bus service in this town stops at nine every night.",
   exampleJa:"この町のバスのサービスは、毎晩9時で終わる。",
   example2:"A new health service for elderly people started here last spring.",
   exampleJa2:"高齢者のための新しい保健事業が、昨春ここで始まった。",
   etymologyProcess:"serv（仕える）＋ ice（名詞）→ 人のために働いて尽くすことは…？",
   etymologyConclusion:"serv（仕える）＋ ice（名詞）→ 人のために働いて役に立つ仕事のしくみ＝事業，サービス",
   relatedWords:[
     {word:"serve",meaning:"（飲食物）を出す",breakdown:"serv（仕える）→ 相手の求めに応じて差し出す"},
     {word:"servant",meaning:"召使い",breakdown:"serv（仕える）＋ ant（人）→ 主人に仕えて働く人"},
     {word:"deserve",meaning:"～に値する",breakdown:"de（すっかり）＋ serv（仕える）→ 尽くした分だけ受け取る資格がある"},
     {word:"server",meaning:"給仕する人；サーバー",breakdown:"serv（仕える）＋ er（人）→ 求めに応じて差し出す側"}]},

  {id:487,word:"religion",partOfSpeech:"名詞",meaning:"宗教",
   meanings:["名|宗教","名|信仰"],
   pronunciation:"/rɪˈlɪdʒən/",part:49,
   example:"People of many religions live together peacefully in that old city.",
   exampleJa:"その古い都市では、多くの宗教の人々が平和に共に暮らしている。",
   example2:"Our textbook explains how religion shaped art in the Middle Ages.",
   exampleJa2:"私たちの教科書は、宗教が中世の芸術をどう形づくったかを説明している。",
   etymologyProcess:"re（強く）＋ lig（結ぶ）→ 人と神を強く結び直すものは…？",
   etymologyConclusion:"re（強く）＋ lig（結ぶ）＋ ion（名詞）→ 人と神とを強く結び直すきまりと教え＝宗教",
   relatedWords:[
     {word:"religious",meaning:"宗教の",breakdown:"re（強く）＋ lig（結ぶ）＋ ous（形容詞）→ 神と強く結ばれている"},
     {word:"rely",meaning:"頼る",breakdown:"re（強く）＋ lig（結ぶ）→ 相手にしっかり結びついて身を預ける"},
     {word:"league",meaning:"連盟",breakdown:"lig（結ぶ）→ 同じ目的のもとに結び合った集まり"},
     {word:"oblige",meaning:"～に義務を負わせる",breakdown:"ob（〜に向かって）＋ lig（結ぶ）→ 約束で相手を縛りつける"}]},

  {id:488,word:"moral",partOfSpeech:"形容詞",meaning:"道徳的な",
   meanings:["形|道徳的な，道徳上の","名|教訓"],
   pronunciation:"/ˈmɔːrəl/",part:49,
   example:"Helping a stranger in trouble is a moral act, not a duty.",
   exampleJa:"困っている見知らぬ人を助けるのは、義務ではなく道徳的な行いだ。",
   example2:"Our teacher raised a difficult moral question about lying to friends.",
   exampleJa2:"先生は、友人にうそをつくことについて難しい道徳的な問いを出した。",
   etymologyProcess:"mor（習わし）＋ al（〜の）→ その社会で正しいとされる習わしは…？",
   etymologyConclusion:"mor（習わし）＋ al（〜の）→ その社会が正しいとしてきた習わしに沿う＝道徳的な",
   relatedWords:[
     {word:"morality",meaning:"道徳",breakdown:"mor（習わし）＋ al（〜の）＋ ity（名詞）→ 正しさについての決まりごと"},
     {word:"morally",meaning:"道徳的に",breakdown:"mor（習わし）＋ al（〜の）＋ ly（副詞）→ 正しさの面から見て"},
     {word:"morale",meaning:"士気",breakdown:"mor（習わし）→ 集団の気持ちの持ち方。やる気の高さ"},
     {synonym:true,word:"ethical",meaning:"倫理的な",breakdown:"学問として筋の通った正しさ。moral は社会の習わし寄り"}]},

  {id:489,word:"standard",partOfSpeech:"名詞",meaning:"基準",
   meanings:["名|基準，水準","形|標準の"],
   pronunciation:"/ˈstændərd/",part:49,
   example:"This factory keeps a very high standard for all its products.",
   exampleJa:"この工場は、すべての製品に非常に高い基準を保っている。",
   example2:"Her essay easily met the standard set by the contest judges.",
   exampleJa2:"彼女の作文は、コンクールの審査員が定めた基準を楽に満たした。",
   etymologyProcess:"sta（立つ）＋ ard（しっかり）→ 戦場にしっかり立てて味方を集めた旗は…？",
   etymologyConclusion:"sta（立つ）＋ ard（しっかり）→ 戦場にしっかり立てた旗のように皆がそろえる目印＝基準",
   relatedWords:[
     {word:"stand",meaning:"立つ",breakdown:"sta（立つ）→ 足で地面にまっすぐ立っている"},
     {word:"instant",meaning:"即座の",breakdown:"in（中に）＋ sta（立つ）→ すぐそこに立っている、その一瞬の"},
     {word:"constant",meaning:"一定の",breakdown:"con（共に）＋ sta（立つ）→ ずっと同じ所に立ち続けている"},
     {synonym:true,word:"level",meaning:"水準",breakdown:"高さの位置。standard は満たすべき目安という意味が強い"}]},

  {id:490,word:"prosperity",partOfSpeech:"名詞",meaning:"繁栄",
   meanings:["名|繁栄，好況"],
   pronunciation:"/prɑːˈsperəti/",part:49,
   example:"The port brought great prosperity to this small town long ago.",
   exampleJa:"その港は、昔この小さな町に大きな繁栄をもたらした。",
   example2:"Peace and prosperity continued in that country for over fifty years.",
   exampleJa2:"その国では、平和と繁栄が50年以上続いた。",
   etymologyProcess:"pro（前へ）＋ sper（希望）→ 望みどおりに事が運び続けると…？",
   etymologyConclusion:"pro（前へ）＋ sper（希望）＋ ity（名詞）→ 望みどおりに前へ進み、豊かに満ちること＝繁栄",
   relatedWords:[
     {word:"prosper",meaning:"繁栄する",breakdown:"pro（前へ）＋ sper（希望）→ 望みどおりに前へ進んで豊かになる"},
     {word:"prosperous",meaning:"繁栄している",breakdown:"pro（前へ）＋ sper（希望）＋ ous（形容詞）→ 望みが満ちている"},
     {word:"desperate",meaning:"絶望的な",breakdown:"de（離して）＋ sper（希望）→ 希望から切り離されて追い詰められた"},
     {word:"despair",meaning:"絶望",breakdown:"de（離して）＋ sper（希望）→ 希望を手放してしまうこと"}]},

  {id:491,word:"crisis",partOfSpeech:"名詞",meaning:"危機",
   meanings:["名|危機，重大な分かれ目"],
   pronunciation:"/ˈkraɪsɪs/",part:50,
   example:"The country faced a serious food crisis after the long drought.",
   exampleJa:"その国は長い干ばつのあと、深刻な食料の危機に直面した。",
   example2:"Our club survived a financial crisis thanks to the parents' help.",
   exampleJa2:"私たちの部は、保護者の助けのおかげでお金の危機を乗り越えた。",
   etymologyProcess:"cris（ふるい分ける）＋ is（名詞）→ 良くなるか悪くなるか決まる場面は…？",
   etymologyConclusion:"cris（ふるい分ける）＋ is（名詞）→ 良い方か悪い方かがふるい分けられる場面＝危機",
   relatedWords:[
     {word:"critical",meaning:"重大な；批判的な",breakdown:"crit（ふるい分ける）＋ al（〜の）→ 分かれ目を見分けるほど大事な"},
     {word:"criticize",meaning:"～を批判する",breakdown:"crit（ふるい分ける）＋ ize（動詞）→ 良し悪しを分けて悪い点を言う"},
     {word:"critic",meaning:"批評家",breakdown:"crit（ふるい分ける）＋ ic（名詞）→ 作品の良し悪しを分けて語る人"},
     {synonym:true,word:"emergency",meaning:"緊急事態",breakdown:"すぐ動くべき場面。crisis は先行きが決まる分かれ目"}]},

  {id:492,word:"prejudice",partOfSpeech:"名詞",meaning:"偏見",
   meanings:["名|偏見，先入観"],
   pronunciation:"/ˈpredʒudɪs/",part:50,
   example:"He judged the new student without prejudice and became her friend.",
   exampleJa:"彼は偏見なしに新入生を見て、彼女の友人になった。",
   example2:"Prejudice against foreign workers still remains in some small towns.",
   exampleJa2:"外国人労働者に対する偏見が、いくつかの小さな町にはまだ残っている。",
   etymologyProcess:"pre（先に）＋ jud（さばく）→ 知る前に決めつけてしまう心は…？",
   etymologyConclusion:"pre（先に）＋ jud（さばく）→ よく知る前にさばいて決めつけてしまう見方＝偏見",
   relatedWords:[
     {word:"judge",meaning:"～を判断する",breakdown:"jud（さばく）→ 正しいかどうかを見きわめて決める"},
     {word:"judgment",meaning:"判断",breakdown:"jud（さばく）＋ ment（名詞）→ 見きわめて決めた中身"},
     {word:"justice",meaning:"正義，司法",breakdown:"jus（正しい）＋ ice（名詞）→ 正しさに沿ってさばくこと"},
     {synonym:true,word:"bias",meaning:"かたより",breakdown:"見方のかたより全般。prejudice は人への決めつけに使う"}]},

  {id:493,word:"discrimination",partOfSpeech:"名詞",meaning:"差別",
   meanings:["名|差別","名|見分ける力"],
   pronunciation:"/dɪˌskrɪmɪˈneɪʃn/",part:50,
   example:"The company was punished for discrimination against its female workers.",
   exampleJa:"その会社は女性労働者への差別で罰を受けた。",
   example2:"Our school teaches that discrimination by skin color is never acceptable.",
   exampleJa2:"私たちの学校は、肌の色による差別は決して許されないと教えている。",
   etymologyProcess:"dis（バラバラに）＋ crimin（ふるい分ける）→ 人を分け隔てすると…？",
   etymologyConclusion:"dis（バラバラに）＋ crimin（ふるい分ける）→ 人をふるいにかけて分け隔てすること＝差別",
   relatedWords:[
     {word:"discriminate",meaning:"差別する",breakdown:"dis（バラバラに）＋ crimin（ふるい分ける）＋ ate（動詞）→ 分け隔てる"},
     {word:"certain",meaning:"確かな",breakdown:"cert（ふるい分ける）→ ふるいにかけて残った、はっきりしたもの"},
     {word:"secret",meaning:"秘密",breakdown:"se（離して）＋ cret（ふるい分ける）→ より分けて隠しておくこと"},
     {synonym:true,word:"prejudice",meaning:"偏見",breakdown:"心の中の決めつけ。discrimination は実際の行いに出る"}]},

  {id:494,word:"charity",partOfSpeech:"名詞",meaning:"慈善",
   meanings:["名|慈善，慈善団体","名|思いやり"],
   pronunciation:"/ˈtʃærəti/",part:50,
   example:"They gave all the money from the concert to a children's charity.",
   exampleJa:"彼らはコンサートの収益をすべて子どもの慈善団体に寄付した。",
   example2:"Our class sold cookies for charity at the school festival.",
   exampleJa2:"私たちのクラスは学園祭で慈善のためにクッキーを売った。",
   etymologyProcess:"car（いとしい）＋ ity（名詞）→ 人をいとしく思う心が形になると…？",
   etymologyConclusion:"car（いとしい）＋ ity（名詞）→ 人をいとしく思う心が施しの形になったもの＝慈善",
   relatedWords:[
     {word:"charitable",meaning:"慈善の",breakdown:"car（いとしい）＋ able（できる）→ 人をいとしく思って手を差し出す"},
     {word:"cherish",meaning:"～を大切にする",breakdown:"car（いとしい）＋ ish（〜にする）→ いとしいものとして抱え守る"},
     {synonym:true,word:"donate",meaning:"寄付する",breakdown:"お金や物を差し出す行い。charity はその心と仕組み"},
     {synonym:true,word:"kindness",meaning:"親切",breakdown:"人にやさしくすること。charity は困った人への施しを指す"}]},

  {id:495,word:"benefit",partOfSpeech:"名詞",meaning:"恩恵",
   meanings:["名|恩恵，利益","他|～の利益になる"],
   pronunciation:"/ˈbenɪfɪt/",part:50,
   example:"Students get the benefit of free books at this city library.",
   exampleJa:"生徒はこの市立図書館で、本が無料という恩恵を受ける。",
   example2:"The new bus line brought real benefits to people in the village.",
   exampleJa2:"新しいバス路線は、村の人々に本当の恩恵をもたらした。",
   etymologyProcess:"bene（良い）＋ fic（作る）→ 相手に良いものを作って渡すと…？",
   etymologyConclusion:"bene（良い）＋ fic（作る）→ 相手のために良いことを作り出して渡すもの＝恩恵",
   relatedWords:[
     {word:"beneficial",meaning:"有益な",breakdown:"bene（良い）＋ fic（作る）＋ ial（形容詞）→ 良い結果を作り出す"},
     {word:"perfect",meaning:"完全な",breakdown:"per（すっかり）＋ fic（作る）→ すっかり作り終えて欠けがない"},
     {word:"effect",meaning:"効果",breakdown:"ef（外へ）＋ fic（作る）→ 作り出されて外へ現れた結果"},
     {synonym:true,word:"advantage",meaning:"利点",breakdown:"他より有利な点。benefit は受け取る側の得を指す"}]},

  {id:496,word:"welfare",partOfSpeech:"名詞",meaning:"福祉",
   meanings:["名|福祉，福利","名|（人の）幸福"],
   pronunciation:"/ˈwelfer/",part:50,
   example:"The city spends much of its budget on welfare for elderly people.",
   exampleJa:"その市は予算の多くを高齢者の福祉に使っている。",
   example2:"Animal welfare was the topic of our English speech contest.",
   exampleJa2:"動物の福祉が、私たちの英語スピーチ大会の題目だった。",
   etymologyProcess:"well（うまく）＋ fare（やっていく）→ 皆がうまくやっていける仕組みは…？",
   etymologyConclusion:"well（うまく）＋ fare（やっていく）→ 皆がうまくやっていけるよう支える仕組み＝福祉",
   relatedWords:[
     {word:"farewell",meaning:"別れのあいさつ",breakdown:"fare（やっていく）＋ well（うまく）→ うまくやっていってね、の言葉"},
     {word:"warfare",meaning:"戦争行為",breakdown:"war（戦い）＋ fare（やっていく）→ 戦いをどう進めていくかという営み"},
     {word:"fare",meaning:"運賃",breakdown:"fare（やっていく）→ 目的地まで進んでいくために払うお金"},
     {synonym:true,word:"charity",meaning:"慈善",breakdown:"個人の善意による施し。welfare は国や市が作る仕組み"}]},

  {id:497,word:"community",partOfSpeech:"名詞",meaning:"地域社会",
   meanings:["名|地域社会，共同体","名|（同じ趣味などの）仲間"],
   pronunciation:"/kəˈmjuːnəti/",part:50,
   example:"The whole community worked together to clean the river last Sunday.",
   exampleJa:"先週の日曜、地域社会全体が力を合わせて川を掃除した。",
   example2:"Our school garden is open to the local community every weekend.",
   exampleJa2:"私たちの学校の畑は、毎週末に地元の地域社会へ開放されている。",
   etymologyProcess:"com（共に）＋ mun（分け合う）→ 暮らしを分け合う人の集まりは…？",
   etymologyConclusion:"com（共に）＋ mun（分け合う）＋ ity（名詞）→ 暮らしを共に分け合う人々の集まり＝地域社会",
   relatedWords:[
     {word:"common",meaning:"よく見られる",breakdown:"com（共に）＋ mun（分け合う）→ みんなで分け合って持っている"},
     {word:"communicate",meaning:"意思の疎通をはかる",breakdown:"com（共に）＋ mun（分け合う）＋ ate（動詞）→ 思いを分け合う"},
     {word:"immune",meaning:"免疫のある",breakdown:"im（否定）＋ mun（分け合う）→ みんなが負う務めを分け持たずにすむ"},
     {synonym:true,word:"society",meaning:"社会",breakdown:"人の集まり全体。community は顔の見える範囲を指す"}]},

  {id:498,word:"individual",partOfSpeech:"名詞",meaning:"個人",
   meanings:["名|個人","形|個々の，個人の"],
   pronunciation:"/ˌɪndɪˈvɪdʒuəl/",part:50,
   example:"Each individual in this class has a different way of learning.",
   exampleJa:"このクラスの個人は一人ひとり、違う学び方を持っている。",
   example2:"The rights of the individual are protected by this old law.",
   exampleJa2:"個人の権利は、この古い法律によって守られている。",
   etymologyProcess:"in（〜でない）＋ divid（分ける）→ これ以上は分けられない一人は…？",
   etymologyConclusion:"in（〜でない）＋ divid（分ける）＋ ual（〜の）→ これ以上は分けられない一人＝個人",
   relatedWords:[
     {word:"divide",meaning:"～を分割する",breakdown:"divid（分ける）→ ひとかたまりを切って複数に分ける"},
     {word:"division",meaning:"分割，部門",breakdown:"divid（分ける）＋ ion（名詞）→ 分けてできた一つひとつ"},
     {word:"dividend",meaning:"配当金",breakdown:"divid（分ける）→ もうけを分けて株主へ配るお金"},
     {synonym:true,word:"person",meaning:"人",breakdown:"人を数える一般語。individual は集団に対する一人を強調"}]},

  {id:499,word:"official",partOfSpeech:"名詞",meaning:"役人",
   meanings:["名|役人，職員","形|公式の"],
   pronunciation:"/əˈfɪʃl/",part:50,
   example:"A city official came to our school to explain the new rule.",
   exampleJa:"市の役人が、新しい規則を説明しに私たちの学校へ来た。",
   example2:"Officials from three countries met to talk about the river.",
   exampleJa2:"3か国の役人が、その川について話し合うために集まった。",
   etymologyProcess:"offic（務め）→ 公の務めを正式に任された立場の人は…？",
   etymologyConclusion:"offic（務め）→ 公の務めを正式に任されて働いている立場の人＝役人",
   relatedWords:[
     {word:"office",meaning:"事務所，役所",breakdown:"offic（務め）→ 務めを果たすために人が集まる部屋"},
     {word:"officer",meaning:"将校，役員",breakdown:"offic（務め）＋ er（人）→ 公の務めを受け持つ人"},
     {word:"operate",meaning:"～を操作する",breakdown:"oper（仕事）＋ ate（動詞）→ 仕事として機械を動かす"},
     {synonym:true,word:"staff",meaning:"職員",breakdown:"働く人全体をまとめて言う語。official は公の立場の人"}]},

  {id:500,word:"immigrant",partOfSpeech:"名詞",meaning:"移民",
   meanings:["名|（入ってくる）移民"],
   pronunciation:"/ˈɪmɪɡrənt/",part:50,
   example:"Many immigrants from Asia have settled in this port town.",
   exampleJa:"アジアからの多くの移民が、この港町に住みついている。",
   example2:"The museum tells the story of immigrants who built the railroad.",
   exampleJa2:"その博物館は、鉄道を造った移民たちの物語を伝えている。",
   etymologyProcess:"im（中へ）＋ migr（移る）→ 別の国の中へ移り住んだ人は…？",
   etymologyConclusion:"im（中へ）＋ migr（移る）＋ ant（人）→ 別の国の中へ移り住んできた人＝移民",
   relatedWords:[
     {word:"migrate",meaning:"移動する",breakdown:"migr（移る）＋ ate（動詞）→ 住む場所を別の土地へ移す"},
     {word:"emigrant",meaning:"（出ていく）移民",breakdown:"e（外へ）＋ migr（移る）＋ ant（人）→ 国の外へ移り出る人"},
     {word:"migration",meaning:"移住，渡り",breakdown:"migr（移る）＋ ation（名詞）→ 群れで住む場所を移していくこと"},
     {synonym:true,word:"refugee",meaning:"難民",breakdown:"戦争などで逃れてきた人。immigrant は移り住む人全般"}]},

  {id:501,word:"volunteer",partOfSpeech:"名詞",meaning:"志願者，ボランティア",
   meanings:["名|志願者，ボランティア","自|進んで引き受ける"],
   pronunciation:"/ˌvɑːlənˈtɪr/",part:51,
   example:"About thirty volunteers cleaned the beach early on Sunday morning.",
   exampleJa:"約30人のボランティアが、日曜の朝早くに浜辺を掃除した。",
   example2:"Our school needs volunteers to guide visitors during the open day.",
   exampleJa2:"私たちの学校は、公開日に来客を案内するボランティアを必要としている。",
   etymologyProcess:"vol（望む）＋ eer（人）→ 頼まれる前に自分から望んで動く人は…？",
   etymologyConclusion:"vol（望む）＋ eer（人）→ 命じられる前に自分から望んで引き受ける人＝志願者",
   relatedWords:[
     {word:"voluntary",meaning:"自発的な",breakdown:"vol（望む）＋ ary（形容詞）→ 自分から望んでする"},
     {word:"voluntarily",meaning:"自発的に",breakdown:"vol（望む）＋ ary（形容詞）＋ ly（副詞）→ 自分から進んで"},
     {word:"benevolent",meaning:"慈悲深い",breakdown:"bene（良い）＋ vol（望む）＋ ent（〜している）→ 人の幸せを望む"},
     {synonym:true,word:"helper",meaning:"手伝う人",breakdown:"手を貸す人全般。volunteer は無償で自ら進んで動く人"}]},

  {id:502,word:"interact",partOfSpeech:"自動詞",meaning:"交流する",
   meanings:["自|交流する，やり取りする","自|互いに作用し合う"],
   pronunciation:"/ˌɪntərˈækt/",part:51,
   example:"Students from both schools interact freely during the summer camp.",
   exampleJa:"両校の生徒は、夏合宿の間に自由に交流する。",
   example2:"He interacted with many local people while studying in Canada.",
   exampleJa2:"カナダで学ぶ間、彼は多くの地元の人と交流した。",
   etymologyProcess:"inter（間の）＋ act（追い立てる）→ 互いの間で働きかけ合うと…？",
   etymologyConclusion:"inter（間の）＋ act（追い立てる）→ 互いの間で行き来しながら働きかけ合う＝交流する",
   relatedWords:[
     {word:"interaction",meaning:"交流，相互作用",breakdown:"inter（間の）＋ act（追い立てる）＋ ion（名詞）→ 行き来する働きかけ"},
     {word:"active",meaning:"活動的な",breakdown:"act（追い立てる）＋ ive（〜な性質の）→ 自分からどんどん動く"},
     {word:"react",meaning:"反応する",breakdown:"re（戻す）＋ act（追い立てる）→ 受けた動きを相手へ返す"},
     {word:"activity",meaning:"活動",breakdown:"act（追い立てる）＋ ity（名詞）→ 体や心を動かして行うこと"}]},

  {id:503,word:"contribute",partOfSpeech:"他動詞・自動詞",meaning:"貢献する",
   meanings:["自|貢献する","他|～を寄付する"],
   pronunciation:"/kənˈtrɪbjuːt/",part:51,
   example:"Her careful notes contributed a lot to our group presentation.",
   exampleJa:"彼女の丁寧なメモは、私たちの班の発表に大きく貢献した。",
   example2:"Every player must contribute something to win a close game.",
   exampleJa2:"接戦に勝つには、すべての選手が何かで貢献しなければならない。",
   etymologyProcess:"con（共に）＋ tribut（割り当てる）→ 自分の分を出し合うと…？",
   etymologyConclusion:"con（共に）＋ tribut（割り当てる）→ 皆で自分の分を出し合って全体を支える＝貢献する",
   relatedWords:[
     {word:"contribution",meaning:"貢献，寄付",breakdown:"con（共に）＋ tribut（割り当てる）＋ ion（名詞）→ 出し合った分"},
     {word:"distribute",meaning:"～を配る",breakdown:"dis（あちこちに）＋ tribut（割り当てる）→ 一人ずつに割り当てて配る"},
     {word:"tribute",meaning:"賛辞，みつぎ物",breakdown:"tribut（割り当てる）→ 相手に割り当てて差し出す敬いの品"},
     {word:"attribute",meaning:"～のせいだとする",breakdown:"ad（〜へ）＋ tribut（割り当てる）→ 原因をその相手に割り当てる"}]},

  {id:504,word:"abolish",partOfSpeech:"他動詞",meaning:"～を廃止する",
   meanings:["他|（制度など）を廃止する"],
   pronunciation:"/əˈbɑːlɪʃ/",part:51,
   example:"That country abolished the old tax system about twenty years ago.",
   exampleJa:"その国は、約20年前に古い税の制度を廃止した。",
   example2:"Many students want the school to abolish the rule about hair.",
   exampleJa2:"多くの生徒は、学校が髪についての規則を廃止することを望んでいる。",
   etymologyProcess:"ab（離れて）＋ ol（育つ）→ 育ってきた古い仕組みを取り去ると…？",
   etymologyConclusion:"ab（離れて）＋ ol（育つ）＋ ish（〜にする）→ 長年育ってきた仕組みを取り去る＝廃止する",
   relatedWords:[
     {word:"adult",meaning:"大人",breakdown:"ad（〜へ）＋ ol（育つ）→ すっかり育ちきった人"},
     {word:"adolescent",meaning:"青年",breakdown:"ad（〜へ）＋ ol（育つ）＋ ent（人）→ 大人へ育っていく途中の人"},
     {synonym:true,word:"cancel",meaning:"～を取り消す",breakdown:"予定や約束を取り消す。abolish は制度そのものをなくす"},
     {synonym:true,word:"ban",meaning:"～を禁止する",breakdown:"してはいけないと決める。abolish は仕組み自体を消す"}]},

  {id:505,word:"impose",partOfSpeech:"他動詞",meaning:"～を課す",
   meanings:["他|（税・罰など）を課す","他|（考え）を押しつける"],
   pronunciation:"/ɪmˈpoʊz/",part:51,
   example:"The city imposed a new tax on plastic bags last April.",
   exampleJa:"市は昨年4月、レジ袋に新しい税を課した。",
   example2:"Teachers should not impose their own opinions on young students.",
   exampleJa2:"教師は自分の意見を若い生徒に押しつけるべきではない。",
   etymologyProcess:"im（中へ）＋ pos（置く）→ 相手の上に重みを置くと…？",
   etymologyConclusion:"im（中へ）＋ pos（置く）→ 相手の肩の上に重みをどんと置いて負わせる＝課す",
   relatedWords:[
     {word:"oppose",meaning:"～に反対する",breakdown:"op（向かい合って）＋ pos（置く）→ 相手の正面に立ちはだかる"},
     {word:"propose",meaning:"～を提案する",breakdown:"pro（前へ）＋ pos（置く）→ 考えを相手の前に差し出す"},
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ion（名詞）→ 置かれている場所"},
     {word:"compose",meaning:"～を構成する",breakdown:"com（共に）＋ pos（置く）→ 部品を並べ置いて一つにまとめる"}]},

  {id:506,word:"access",partOfSpeech:"名詞",meaning:"利用する権利，接近",
   meanings:["名|利用する権利，接近","他|～を利用する"],
   pronunciation:"/ˈækses/",part:51,
   example:"Students have free access to the school library after four o'clock.",
   exampleJa:"生徒は4時以降、学校の図書館を無料で利用する権利がある。",
   example2:"Villagers were given access to clean water for the first time.",
   exampleJa2:"村人たちは初めて、きれいな水を利用する権利を与えられた。",
   etymologyProcess:"ac（〜へ）＋ cess（行く）→ そこまで行って中に入れることは…？",
   etymologyConclusion:"ac（〜へ）＋ cess（行く）→ そこまで近づいて中へ入ってよいという許し＝利用する権利",
   relatedWords:[
     {word:"process",meaning:"過程",breakdown:"pro（前へ）＋ cess（行く）→ 前へ進んでいく道のり"},
     {word:"success",meaning:"成功",breakdown:"suc（すぐ後に）＋ cess（行く）→ 望んだ結果がすぐ後について来ること"},
     {word:"exceed",meaning:"～を超える",breakdown:"ex（外へ）＋ cess（行く）→ 決められた線の外まで行ってしまう"},
     {word:"necessary",meaning:"必要な",breakdown:"ne（否定）＋ cess（行く）→ それなしには先へ行けない"}]},

  {id:507,word:"duty",partOfSpeech:"名詞",meaning:"義務",
   meanings:["名|義務，務め","名|関税"],
   pronunciation:"/ˈduːti/",part:51,
   example:"It is the duty of every driver to obey traffic signals.",
   exampleJa:"信号に従うことは、すべての運転手の義務だ。",
   example2:"Cleaning the classroom is a daily duty for our whole class.",
   exampleJa2:"教室の掃除は、私たちのクラス全体の毎日の義務だ。",
   etymologyProcess:"deb（負う）＋ ty（名詞）→ 当然返さねばならないものは…？",
   etymologyConclusion:"deb（負う）＋ ty（名詞）→ 当然果たして返さなければならない借りのようなもの＝義務",
   relatedWords:[
     {word:"due",meaning:"支払われるべき",breakdown:"deb（負う）→ 当然返さなければならない状態にある"},
     {word:"dutiful",meaning:"忠実な",breakdown:"deb（負う）＋ ful（満ちた）→ 務めをきちんと果たす気持ちに満ちた"},
     {synonym:true,word:"obligation",meaning:"義務，責務",breakdown:"約束で縛られた義務。duty は立場から生まれる務め"},
     {synonym:true,word:"responsibility",meaning:"責任",breakdown:"結果を引き受ける責任。duty はやるべき務めそのもの"}]},

  {id:508,word:"responsible",partOfSpeech:"形容詞",meaning:"責任がある",
   meanings:["形|責任がある","形|信頼できる"],
   pronunciation:"/rɪˈspɑːnsəbl/",part:51,
   example:"The teacher is responsible for the safety of all her students.",
   exampleJa:"その教師は、生徒全員の安全に責任がある。",
   example2:"Who was responsible for locking the gym door last night?",
   exampleJa2:"昨夜、体育館の扉を施錠することに責任があったのは誰ですか。",
   etymologyProcess:"re（戻す）＋ spond（誓う）→ 問われたら答えを返すと約束すると…？",
   etymologyConclusion:"re（戻す）＋ spond（誓う）＋ ible（できる）→ 問われたら答えを返すと誓える＝責任がある",
   relatedWords:[
     {word:"respond",meaning:"返答する",breakdown:"re（戻す）＋ spond（誓う）→ 相手の問いかけに言葉を返す"},
     {word:"response",meaning:"返答",breakdown:"re（戻す）＋ spond（誓う）→ 問いかけに対して返された言葉"},
     {word:"responsibility",meaning:"責任",breakdown:"re（戻す）＋ spond（誓う）＋ ity（名詞）→ 答えを返す立場そのもの"},
     {word:"correspond",meaning:"一致する；文通する",breakdown:"cor（共に）＋ spond（誓う）→ 互いに答え合って合う"}]},

  {id:509,word:"policy",partOfSpeech:"名詞",meaning:"政策，方針",
   meanings:["名|政策，方針","名|保険証券"],
   pronunciation:"/ˈpɑːləsi/",part:51,
   example:"The government changed its policy on foreign students last year.",
   exampleJa:"政府は昨年、外国人留学生についての政策を変えた。",
   example2:"Our school has a clear policy about the use of smartphones.",
   exampleJa2:"私たちの学校には、スマホの使用についての明確な方針がある。",
   etymologyProcess:"polit（都市）＋ y（名詞）→ 都市をどう治めるか決めた筋道は…？",
   etymologyConclusion:"polit（都市）＋ y（名詞）→ 都市をどう治めるかを決めておく筋道＝政策，方針",
   relatedWords:[
     {word:"politics",meaning:"政治",breakdown:"polit（都市）＋ ics（学問・活動）→ 都市をどう治めるかを決める営み"},
     {word:"police",meaning:"警察",breakdown:"polit（都市）→ 都市の秩序を保つために置かれた組織"},
     {word:"political",meaning:"政治的な",breakdown:"polit（都市）＋ ic（形容詞）＋ al（〜の）→ 都市を治めることにかかわる"},
     {word:"politician",meaning:"政治家",breakdown:"polit（都市）＋ ian（人）→ 都市を治める仕事をする人"}]},

  {id:510,word:"elect",partOfSpeech:"他動詞",meaning:"（投票で）～を選出する",
   meanings:["他|（投票で）～を選出する"],
   pronunciation:"/ɪˈlekt/",part:51,
   example:"The students elected her as the new leader of the council.",
   exampleJa:"生徒たちは彼女を生徒会の新しいリーダーに選出した。",
   example2:"A new mayor will be elected in this city next month.",
   exampleJa2:"来月、この市で新しい市長が選出される。",
   etymologyProcess:"e（外へ）＋ lect（拾う）→ 大勢の中から一人を拾い上げると…？",
   etymologyConclusion:"e（外へ）＋ lect（拾う）→ 大勢の中から票で一人を拾い上げて外へ出す＝選出する",
   relatedWords:[
     {word:"select",meaning:"～を選ぶ",breakdown:"se（離して）＋ lect（拾う）→ ほかと切り離してより分けて拾う"},
     {word:"election",meaning:"選挙",breakdown:"e（外へ）＋ lect（拾う）＋ ion（名詞）→ 票で人を拾い上げる仕組み"},
     {word:"collect",meaning:"～を集める",breakdown:"col（共に）＋ lect（拾う）→ あちこちから拾って一つに集める"},
     {word:"lecture",meaning:"講義",breakdown:"lect（拾う）＋ ure（名詞）→ 書かれた言葉を拾い読んで聞かせること"}]},

  {id:511,word:"industry",partOfSpeech:"名詞",meaning:"工業，産業",
   meanings:["名|工業，産業","名|勤勉"],
   pronunciation:"/ˈɪndəstri/",part:52,
   example:"The car industry is the biggest employer in this northern city.",
   exampleJa:"自動車工業は、この北の都市で最大の雇い主だ。",
   example2:"Our class visited a factory to study the local paper industry.",
   exampleJa2:"私たちのクラスは、地元の製紙工業を学ぶため工場を見学した。",
   etymologyProcess:"indu（中で）＋ stru（積み上げる）→ 内側でこつこつ積み上げる働きは…？",
   etymologyConclusion:"indu（中で）＋ stru（積み上げる）→ 休まず内側で物を積み上げ続ける働き＝工業，産業",
   relatedWords:[
     {word:"structure",meaning:"構造",breakdown:"stru（積み上げる）＋ ure（名詞）→ 積み上げてできた組み立て"},
     {word:"construct",meaning:"～を建設する",breakdown:"con（共に）＋ stru（積み上げる）→ 材料を組み合わせて積み上げる"},
     {word:"instrument",meaning:"楽器，道具",breakdown:"in（中へ）＋ stru（積み上げる）＋ ment（名詞）→ 中に組んだ仕掛け"},
     {word:"destroy",meaning:"～を破壊する",breakdown:"de（逆に）＋ stru（積み上げる）→ 積み上げたものを逆に崩す"}]},

  {id:512,word:"income",partOfSpeech:"名詞",meaning:"収入",
   meanings:["名|収入，所得"],
   pronunciation:"/ˈɪnkʌm/",part:52,
   example:"His monthly income is not enough to support a large family.",
   exampleJa:"彼の毎月の収入は、大家族を養うには十分でない。",
   example2:"Part-time work gave her a small income during the summer holidays.",
   exampleJa2:"アルバイトは、夏休みの間に彼女へ少しの収入をもたらした。",
   etymologyProcess:"in（中へ）＋ come（来る）→ 自分のふところへ入ってくるお金は…？",
   etymologyConclusion:"in（中へ）＋ come（来る）→ 働いた結果として自分のふところへ入ってくるお金＝収入",
   relatedWords:[
     {word:"outcome",meaning:"結果",breakdown:"out（外へ）＋ come（来る）→ ものごとの末に外へ出てきたもの"},
     {word:"become",meaning:"～になる",breakdown:"be（すっかり）＋ come（来る）→ すっかりその状態までやって来る"},
     {word:"overcome",meaning:"～を克服する",breakdown:"over（越えて）＋ come（来る）→ 困難を越えて向こう側まで来る"},
     {word:"welcome",meaning:"～を歓迎する",breakdown:"wil（望む）＋ come（来る）→ 来てほしいと望んでいた人を迎える"}]},

  {id:513,word:"profit",partOfSpeech:"名詞",meaning:"利益",
   meanings:["名|（商売の）利益","自|利益を得る"],
   pronunciation:"/ˈprɑːfɪt/",part:52,
   example:"The shop made a small profit in its very first year.",
   exampleJa:"その店は、ごく最初の年に少しの利益を出した。",
   example2:"All profits from our school shop go to the sports clubs.",
   exampleJa2:"私たちの学校の売店の利益はすべて、運動部へ回される。",
   etymologyProcess:"pro（前へ）＋ fic（作る）→ かけた元手より前へ作り出せた分は…？",
   etymologyConclusion:"pro（前へ）＋ fic（作る）→ かけた元手より前へ多く作り出せた余りの分＝利益",
   relatedWords:[
     {word:"profitable",meaning:"もうかる",breakdown:"pro（前へ）＋ fic（作る）＋ able（できる）→ 元手より多く作り出せる"},
     {word:"perfect",meaning:"完全な",breakdown:"per（すっかり）＋ fic（作る）→ すっかり作り終えて欠けがない"},
     {word:"factory",meaning:"工場",breakdown:"fic（作る）＋ ory（場所）→ 物を作り出すための建物"},
     {synonym:true,word:"benefit",meaning:"恩恵",breakdown:"受け取る側の得。profit は商売で残るお金の得を指す"}]},

  {id:514,word:"tax",partOfSpeech:"名詞",meaning:"税金",
   meanings:["名|税金","他|～に課税する"],
   pronunciation:"/tæks/",part:52,
   example:"The government raised the tax on cigarettes again this spring.",
   exampleJa:"政府はこの春、たばこの税金を再び引き上げた。",
   example2:"Books for children are sold without any tax in that country.",
   exampleJa2:"その国では、子ども向けの本は税金なしで売られている。",
   etymologyProcess:"tax（値ぶみする）→ 財産を値ぶみして割り当てられるものは…？",
   etymologyConclusion:"tax（値ぶみする）→ 国が財産を値ぶみして国民に割り当てるお金＝税金",
   relatedWords:[
     {word:"task",meaning:"仕事，課題",breakdown:"tax（値ぶみする）→ 値ぶみして割り当てられた、片づける一仕事"},
     {word:"taxi",meaning:"タクシー",breakdown:"tax（値ぶみする）→ 走った分を計って料金を決める車"},
     {word:"taste",meaning:"～の味がする",breakdown:"tax（値ぶみする）→ 舌で値ぶみするように中身を確かめる"},
     {synonym:true,word:"duty",meaning:"関税",breakdown:"輸入品にかかる税。tax は税金全体を指す広い語"}]},

  {id:515,word:"expense",partOfSpeech:"名詞",meaning:"（かかる）費用，経費",
   meanings:["名|（かかる）費用，経費","名|犠牲"],
   pronunciation:"/ɪkˈspens/",part:52,
   example:"The expense of running this old bus is rising every year.",
   exampleJa:"この古いバスを走らせる費用は、毎年上がっている。",
   example2:"Our club covered the expenses of the trip with its own money.",
   exampleJa2:"私たちの部は、自分たちのお金で遠征の費用をまかなった。",
   etymologyProcess:"ex（外へ）＋ pens（重さを量る）→ 量って外へ払い出す分は…？",
   etymologyConclusion:"ex（外へ）＋ pens（重さを量る）→ 銀を量って外へ払い出していく分＝費用，経費",
   relatedWords:[
     {word:"expensive",meaning:"高価な",breakdown:"ex（外へ）＋ pens（重さを量る）→ 量って払う額が大きい"},
     {word:"spend",meaning:"（時間）を費やす",breakdown:"pens（重さを量る）→ 量って外へ払い出してしまう"},
     {word:"depend",meaning:"次第である",breakdown:"de（下へ）＋ pens（重さを量る）→ 下にぶら下がって相手に左右される"},
     {word:"pension",meaning:"年金",breakdown:"pens（重さを量る）＋ ion（名詞）→ 量って定期的に支払われるお金"}]},

  {id:516,word:"debt",partOfSpeech:"名詞",meaning:"借金",
   meanings:["名|借金，負債","名|恩義"],
   pronunciation:"/det/",part:52,
   example:"He worked two jobs to pay off his large debt.",
   exampleJa:"彼は多額の借金を返すために、二つの仕事をした。",
   example2:"The company's debts grew larger after the factory closed last year.",
   exampleJa2:"昨年工場が閉鎖されたあと、その会社の借金はさらに膨らんだ。",
   etymologyProcess:"deb（負う）＋ t（名詞）→ 返さなければならないものを負うと…？",
   etymologyConclusion:"deb（負う）＋ t（名詞）→ いつか返さなければならないものを負っている状態＝借金",
   relatedWords:[
     {word:"debtor",meaning:"債務者",breakdown:"deb（負う）＋ or（人）→ 借りを負っている側の人"},
     {word:"due",meaning:"支払われるべき",breakdown:"deb（負う）→ 当然返さなければならない状態にある"},
     {word:"duty",meaning:"義務",breakdown:"deb（負う）＋ ty（名詞）→ 当然果たすべきものを負っている状態"},
     {synonym:true,word:"loan",meaning:"貸付金",breakdown:"貸す側から見たお金。debt は借りた側から見た同じお金"}]},

  {id:517,word:"deposit",partOfSpeech:"名詞",meaning:"預金，手付金",
   meanings:["名|預金，手付金","他|～を預ける"],
   pronunciation:"/dɪˈpɑːzɪt/",part:52,
   example:"She put a large deposit in the bank before leaving Japan.",
   exampleJa:"彼女は日本を離れる前に、銀行へ多額の預金を入れた。",
   example2:"A deposit of ten thousand yen is needed to book this room.",
   exampleJa2:"この部屋を予約するには、1万円の手付金が必要だ。",
   etymologyProcess:"de（下へ）＋ pos（置く）→ 安全な所へ下ろして置いておくお金は…？",
   etymologyConclusion:"de（下へ）＋ pos（置く）→ 安全な所へ下ろして預け置いておくお金＝預金，手付金",
   relatedWords:[
     {word:"purpose",meaning:"目的",breakdown:"pur（前へ）＋ pos（置く）→ 自分の前に置いて目指すもの"},
     {word:"opposite",meaning:"反対の",breakdown:"op（向かい合って）＋ pos（置く）→ 向かい合わせに置かれている"},
     {word:"expose",meaning:"～をさらす",breakdown:"ex（外へ）＋ pos（置く）→ 外に置いて見えるようにする"},
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ion（名詞）→ 置かれている場所"}]},

  {id:518,word:"charge",partOfSpeech:"名詞",meaning:"（サービスの）料金，請求額",
   meanings:["名|（サービスの）料金，請求額","他|～を請求する","他|～を充電する"],
   pronunciation:"/tʃɑːrdʒ/",part:52,
   example:"There is no charge for using the hotel's swimming pool.",
   exampleJa:"ホテルのプールの使用に料金はかからない。",
   example2:"The repair shop added a small charge for the new battery.",
   exampleJa2:"修理店は、新しい電池のぶんの少額の料金を加えた。",
   etymologyProcess:"carr（荷車）→ 荷車に重い荷を積み込むように負わせると…？",
   etymologyConclusion:"carr（荷車）→ 荷車に荷を積むように相手へ負わせる支払い＝料金",
   relatedWords:[
     {word:"carry",meaning:"～を運ぶ",breakdown:"carr（荷車）→ 荷車に載せるようにして物を運んでいく"},
     {word:"cargo",meaning:"積み荷",breakdown:"carr（荷車）→ 船や車に積み込まれた荷物"},
     {word:"car",meaning:"車",breakdown:"carr（荷車）→ 人や物を載せて走る乗り物"},
     {word:"charger",meaning:"充電器",breakdown:"carr（荷車）＋ er（もの）→ 電気を積み込んでやる道具"}]},

  {id:519,word:"wage",partOfSpeech:"名詞",meaning:"賃金",
   meanings:["名|（時間・日ごとの）賃金"],
   pronunciation:"/weɪdʒ/",part:52,
   example:"The daily wage for this farm work is fifteen thousand yen.",
   exampleJa:"この農作業の1日の賃金は1万5千円だ。",
   example2:"Workers asked the company to raise their wages this spring.",
   exampleJa2:"労働者たちは今春、会社に賃金を上げるよう求めた。",
   etymologyProcess:"wag（約束の担保）→ 働いた分は必ず払うと約束したお金は…？",
   etymologyConclusion:"wag（約束の担保）→ 働いた時間の分は必ず払うと約束して渡すお金＝賃金",
   relatedWords:[
     {word:"wager",meaning:"賭け",breakdown:"wag（約束の担保）＋ er（もの）→ 約束の印として差し出すかけ金"},
     {synonym:true,word:"salary",meaning:"給料",breakdown:"月ごとに決まった額。wage は時間や日で数えて払う額"},
     {synonym:true,word:"pay",meaning:"～を支払う",breakdown:"お金を渡す動き。wage は受け取る側のお金そのもの"},
     {synonym:true,word:"income",meaning:"収入",breakdown:"入ってくるお金全体。wage はそのうち労働への支払い"}]},

  {id:520,word:"recession",partOfSpeech:"名詞",meaning:"不況",
   meanings:["名|（景気の）不況，後退"],
   pronunciation:"/rɪˈseʃn/",part:52,
   example:"Many small shops closed during the long recession of those years.",
   exampleJa:"その時代の長い不況の間に、多くの小さな店が閉店した。",
   example2:"Economists warn that another recession may begin within two years.",
   exampleJa2:"経済学者は、2年以内に別の不況が始まるかもしれないと警告する。",
   etymologyProcess:"re（後ろへ）＋ cess（行く）→ 景気が後ろへ下がっていくと…？",
   etymologyConclusion:"re（後ろへ）＋ cess（行く）＋ ion（名詞）→ 景気が前へ進まず後ろへ下がること＝不況",
   relatedWords:[
     {word:"recede",meaning:"後退する",breakdown:"re（後ろへ）＋ cess（行く）→ もとの位置より後ろへ引いていく"},
     {word:"process",meaning:"過程",breakdown:"pro（前へ）＋ cess（行く）→ 前へ進んでいく道のり"},
     {word:"success",meaning:"成功",breakdown:"suc（すぐ後に）＋ cess（行く）→ 望んだ結果がすぐ後について来ること"},
     {word:"exceed",meaning:"～を超える",breakdown:"ex（外へ）＋ cess（行く）→ 決められた線の外まで行ってしまう"}]},

  {id:521,word:"consume",partOfSpeech:"他動詞",meaning:"～を消費する",
   meanings:["他|～を消費する","他|～を食べ尽くす"],
   pronunciation:"/kənˈsuːm/",part:53,
   example:"This old air conditioner consumes a lot of electricity every summer.",
   exampleJa:"この古いエアコンは、毎年夏に多くの電気を消費する。",
   example2:"Most of the paper consumed at school could be recycled easily.",
   exampleJa2:"学校で消費される紙の大半は、簡単に再生できるだろう。",
   etymologyProcess:"con（すっかり）＋ sume（取る）→ 残らず取り込んで使い切ると…？",
   etymologyConclusion:"con（すっかり）＋ sume（取る）→ 残らず取り込んで使い切ってしまう＝消費する",
   relatedWords:[
     {word:"consumer",meaning:"消費者",breakdown:"con（すっかり）＋ sume（取る）＋ er（人）→ 買って使い切る側の人"},
     {word:"assume",meaning:"～と思い込む",breakdown:"ad（〜へ）＋ sume（取る）→ そうだと自分の中へ取り込んで決める"},
     {word:"resume",meaning:"～を再開する",breakdown:"re（再び）＋ sume（取る）→ いったん置いたものを再び手に取る"},
     {word:"consumption",meaning:"消費",breakdown:"con（すっかり）＋ sume（取る）＋ ion（名詞）→ 使い切ってしまうこと"}]},

  {id:522,word:"waste",partOfSpeech:"他動詞",meaning:"～を浪費する",
   meanings:["他|～を浪費する","名|廃棄物"],
   pronunciation:"/weɪst/",part:53,
   example:"Do not waste your money on games you will never play.",
   exampleJa:"決して遊ばないゲームにお金を浪費してはいけない。",
   example2:"He wasted three hours looking for a book in the wrong room.",
   exampleJa2:"彼は違う部屋で本を探して3時間を浪費した。",
   etymologyProcess:"wast（荒れ果てた）→ 使えるものを荒れ地のようにしてしまうと…？",
   etymologyConclusion:"wast（荒れ果てた）→ 使えるものを荒れ地のように何も残らなくする＝浪費する",
   relatedWords:[
     {word:"wasteful",meaning:"むだの多い",breakdown:"wast（荒れ果てた）＋ ful（満ちた）→ むだばかりで実りがない"},
     {word:"vast",meaning:"広大な",breakdown:"vast（荒れ果てた）→ 人の手が届かないほど果てしなく広い"},
     {word:"devastate",meaning:"～を荒廃させる",breakdown:"de（すっかり）＋ vast（荒れ果てた）→ すっかり荒れ地にしてしまう"},
     {synonym:true,word:"spend",meaning:"（時間）を費やす",breakdown:"ふつうに使うこと。waste はむだに使ってしまうこと"}]},

  {id:523,word:"invest",partOfSpeech:"他動詞・自動詞",meaning:"投資する",
   meanings:["自|投資する","他|（時間・労力）をつぎ込む"],
   pronunciation:"/ɪnˈvest/",part:53,
   example:"Her father invested in a small company near the station.",
   exampleJa:"彼女の父は、駅の近くの小さな会社に投資した。",
   example2:"Wise people invest their money in their own education first.",
   exampleJa2:"賢い人はまず、自分の教育にお金を投資する。",
   etymologyProcess:"in（中へ）＋ vest（衣を着せる）→ お金に新しい役目を着せると…？",
   etymologyConclusion:"in（中へ）＋ vest（衣を着せる）→ 眠っているお金に事業という衣を着せて働かせる＝投資する",
   relatedWords:[
     {word:"vest",meaning:"チョッキ",breakdown:"vest（衣を着せる）→ 上半身に着せる、そでのない衣"},
     {word:"investment",meaning:"投資",breakdown:"in（中へ）＋ vest（衣を着せる）＋ ment（名詞）→ お金を働かせること"},
     {word:"investor",meaning:"投資家",breakdown:"in（中へ）＋ vest（衣を着せる）＋ or（人）→ お金を働かせる人"},
     {synonym:true,word:"fund",meaning:"資金",breakdown:"元手となるお金。invest はそれを働かせる動き"}]},

  {id:524,word:"import",partOfSpeech:"他動詞",meaning:"～を輸入する",
   meanings:["他|～を輸入する","名|輸入品"],
   pronunciation:"/ɪmˈpɔːrt/",part:53,
   example:"Japan imports most of its wheat from other countries every year.",
   exampleJa:"日本は毎年、小麦の大半を他国から輸入している。",
   example2:"These oranges were imported from Australia just three days ago.",
   exampleJa2:"これらのオレンジは、ほんの3日前にオーストラリアから輸入された。",
   etymologyProcess:"im（中へ）＋ port（運ぶ）→ 品物を国の中へ運び入れると…？",
   etymologyConclusion:"im（中へ）＋ port（運ぶ）→ 港から品物を自分の国の中へ運び入れる＝輸入する",
   relatedWords:[
     {word:"export",meaning:"～を輸出する",breakdown:"ex（外へ）＋ port（運ぶ）→ 品物を国の外へ運び出す"},
     {word:"transport",meaning:"～を輸送する",breakdown:"trans（越えて）＋ port（運ぶ）→ 遠くまで越えて物を運ぶ"},
     {word:"portable",meaning:"持ち運べる",breakdown:"port（運ぶ）＋ able（できる）→ 手に持って運べる軽さの"},
     {word:"report",meaning:"～を報告する",breakdown:"re（戻す）＋ port（運ぶ）→ 見てきたことを持ち帰って伝える"}]},

  {id:525,word:"financial",partOfSpeech:"形容詞",meaning:"財政的な",
   meanings:["形|財政的な，金銭上の"],
   pronunciation:"/faɪˈnænʃl/",part:53,
   example:"The city is in serious financial trouble after the big earthquake.",
   exampleJa:"その市は大地震のあと、深刻な財政的な困難にある。",
   example2:"Our club received financial help from the parents' association last year.",
   exampleJa2:"私たちの部は昨年、保護者会から財政的な援助を受けた。",
   etymologyProcess:"fin（終わり）＋ ance（名詞）＋ al（〜の）→ 支払いを終わらせる仕事は…？",
   etymologyConclusion:"fin（終わり）＋ ance（名詞）＋ al（〜の）→ 支払いを終わらせるお金の動きにかかわる＝財政的な",
   relatedWords:[
     {word:"finance",meaning:"財政，資金",breakdown:"fin（終わり）＋ ance（名詞）→ 支払いを終わらせるためのお金の動き"},
     {word:"finish",meaning:"～を終える",breakdown:"fin（終わり）＋ ish（〜にする）→ 最後まで行って終わりにする"},
     {word:"final",meaning:"最後の",breakdown:"fin（終わり）＋ al（〜の）→ いちばん終わりに来る"},
     {word:"define",meaning:"～を定義する",breakdown:"de（すっかり）＋ fin（終わり）→ 意味の境目をはっきり区切る"}]},

  {id:526,word:"hire",partOfSpeech:"他動詞",meaning:"（賃金を払って）～を雇う",
   meanings:["他|（賃金を払って）～を雇う","他|（英）～を借りる"],
   pronunciation:"/ˈhaɪər/",part:53,
   example:"The restaurant hired five new cooks before the busy summer season.",
   exampleJa:"そのレストランは、忙しい夏の時期の前に5人の新しい調理人を雇った。",
   example2:"Our school hires a coach to train the volleyball team.",
   exampleJa2:"私たちの学校は、バレー部を指導するコーチを雇っている。",
   hook:"employ より口語的で短期の雇用に使う。英国では「物を借りる」の意味も。",
   etymologyProcess:"hire（賃金）→ 決めた賃金を払って人に働いてもらうと…？",
   etymologyConclusion:"hire（賃金）→ 決めた賃金を払う約束で人に働いてもらう＝雇う",
   relatedWords:[
     {synonym:true,word:"employ",meaning:"～を雇用する",breakdown:"長く正式に雇う。hire は短期や口語で使うことが多い"},
     {synonym:true,word:"fire",meaning:"～を解雇する",breakdown:"雇うのをやめる。hire のちょうど反対の動き"},
     {synonym:true,word:"rent",meaning:"～を有料で借りる",breakdown:"物を借りる。英国では hire も同じ意味で使う"},
     {synonym:true,word:"wage",meaning:"賃金",breakdown:"hire した人に払うお金。語の中心にあるもの"}]},

  {id:527,word:"employ",partOfSpeech:"他動詞",meaning:"～を雇用する",
   meanings:["他|～を雇用する","他|（手段）を用いる"],
   pronunciation:"/ɪmˈplɔɪ/",part:53,
   example:"That factory employs about two hundred people from this small town.",
   exampleJa:"あの工場は、この小さな町から約200人を雇用している。",
   example2:"She was employed as an English teacher right after graduating.",
   exampleJa2:"彼女は卒業した直後に、英語教師として雇用された。",
   etymologyProcess:"em（中へ）＋ ploy（折る）→ 人を仕事の中へ折り込むと…？",
   etymologyConclusion:"em（中へ）＋ ploy（折る）→ 人を仕事の中へ折り込んで役目を持たせる＝雇用する",
   relatedWords:[
     {word:"employer",meaning:"雇い主",breakdown:"em（中へ）＋ ploy（折る）＋ er（人）→ 人を仕事に組み入れる側"},
     {word:"imply",meaning:"～をほのめかす",breakdown:"im（中へ）＋ pli（折る）→ 意味を内側に折り込んで含ませる"},
     {word:"apply",meaning:"当てはまる",breakdown:"ad（〜へ）＋ pli（折る）→ 相手にぴたりと折り重ねる"},
     {word:"employment",meaning:"雇用",breakdown:"em（中へ）＋ ploy（折る）＋ ment（名詞）→ 人が仕事に組み入れられた状態"}]},

  {id:528,word:"resign",partOfSpeech:"自動詞",meaning:"辞職する",
   meanings:["自|辞職する","他|～を辞任する"],
   pronunciation:"/rɪˈzaɪn/",part:53,
   example:"The manager resigned after the team lost ten games straight.",
   exampleJa:"チームが10連敗したあと、その監督は辞職した。",
   example2:"He may resign from the committee before the new year starts.",
   exampleJa2:"彼は新年が始まる前に、委員会を辞職するかもしれない。",
   etymologyProcess:"re（戻す）＋ sign（しるし）→ 引き受けたしるしを返すと…？",
   etymologyConclusion:"re（戻す）＋ sign（しるし）→ 引き受けたしるしに取り消しの印をつけて返す＝辞職する",
   relatedWords:[
     {word:"sign",meaning:"兆候，しるし",breakdown:"sign（しるし）→ 何かを知らせるために置かれた目印"},
     {word:"signal",meaning:"合図",breakdown:"sign（しるし）＋ al（名詞）→ 相手に向けて送るしるし"},
     {word:"signature",meaning:"署名",breakdown:"sign（しるし）＋ ature（名詞）→ 自分のしるしとして書く名前"},
     {word:"design",meaning:"～を設計する",breakdown:"de（下へ）＋ sign（しるし）→ 作る前に形をしるしで書き記す"}]},

  {id:529,word:"qualify",partOfSpeech:"自動詞",meaning:"資格を得る",
   meanings:["自|資格を得る","他|～に資格を与える"],
   pronunciation:"/ˈkwɑːlɪfaɪ/",part:53,
   example:"Our team must qualify for the national tournament by winning tomorrow.",
   exampleJa:"私たちのチームは明日勝って全国大会の資格を得なければならない。",
   example2:"She studied hard and qualified as a nurse at twenty-two.",
   exampleJa2:"彼女は懸命に勉強し、22歳で看護師の資格を得た。",
   etymologyProcess:"qual（どんな）＋ fy（する）→ どんな中身かをはっきりさせると…？",
   etymologyConclusion:"qual（どんな）＋ fy（する）→ どんな力を持つ者かをはっきりさせて認めさせる＝資格を得る",
   relatedWords:[
     {word:"quality",meaning:"質",breakdown:"qual（どんな）＋ ity（名詞）→ どんな中身かという、そのものの良し悪し"},
     {word:"qualification",meaning:"資格",breakdown:"qual（どんな）＋ fy（する）＋ ation（名詞）→ 中身を認められた証"},
     {word:"quantity",meaning:"量",breakdown:"quant（どれだけ）＋ ity（名詞）→ どれだけあるかという多さ"},
     {word:"qualified",meaning:"資格のある",breakdown:"qual（どんな）＋ fy（する）＋ ed（〜された）→ 中身を認められた"}]},

  {id:530,word:"assign",partOfSpeech:"他動詞",meaning:"～を割り当てる",
   meanings:["他|～を割り当てる","他|（人）を任命する"],
   pronunciation:"/əˈsaɪn/",part:53,
   example:"The teacher assigned a different topic to each small group.",
   exampleJa:"先生は、それぞれの小さな班に違う題目を割り当てた。",
   example2:"Two students are assigned to clean the science room every Friday.",
   exampleJa2:"毎週金曜、2人の生徒が理科室の掃除に割り当てられる。",
   etymologyProcess:"ad（〜へ）＋ sign（しるし）→ 相手ごとにしるしをつけて分けると…？",
   etymologyConclusion:"ad（〜へ）＋ sign（しるし）→ 相手ごとにしるしをつけて取り分を決める＝割り当てる",
   relatedWords:[
     {word:"assignment",meaning:"課題，宿題",breakdown:"ad（〜へ）＋ sign（しるし）＋ ment（名詞）→ 割り当てられた仕事"},
     {word:"significant",meaning:"重要な",breakdown:"sign（しるし）＋ fic（作る）→ はっきりしるしを作るほど目立つ"},
     {word:"sign",meaning:"兆候，しるし",breakdown:"sign（しるし）→ 何かを知らせるために置かれた目印"},
     {word:"design",meaning:"～を設計する",breakdown:"de（下へ）＋ sign（しるし）→ 作る前に形をしるしで書き記す"}]},

  {id:531,word:"occupation",partOfSpeech:"名詞",meaning:"（日々従事する）職業",
   meanings:["名|（日々従事する）職業","名|占領"],
   pronunciation:"/ˌɑːkjuˈpeɪʃn/",part:54,
   example:"Please write your age and occupation in the boxes below.",
   exampleJa:"下の欄にあなたの年齢と職業を書いてください。",
   example2:"Farming was the main occupation of people in this valley.",
   exampleJa2:"農業は、この谷の人々の主な職業だった。",
   etymologyProcess:"oc（〜に向かって）＋ cupa（取る）→ 一日の時間を取ってふさぐものは…？",
   etymologyConclusion:"oc（〜に向かって）＋ cupa（取る）→ 一日の時間を取ってふさいでいる仕事＝職業",
   relatedWords:[
     {word:"occupy",meaning:"～を占める",breakdown:"oc（〜に向かって）＋ cupa（取る）→ 場所や時間を取ってふさぐ"},
     {word:"accept",meaning:"～を受け入れる",breakdown:"ad（〜へ）＋ cept（取る）→ 差し出されたものを手に取る"},
     {word:"except",meaning:"～を除いて",breakdown:"ex（外へ）＋ cept（取る）→ 一つだけ外へ取り出しておく"},
     {word:"concept",meaning:"概念",breakdown:"con（共に）＋ cept（取る）→ 頭の中でまとめて取り込んだ考え"}]},

  {id:532,word:"career",partOfSpeech:"名詞",meaning:"（生涯の）経歴，職業",
   meanings:["名|（生涯の）経歴，職業","名|出世コース"],
   pronunciation:"/kəˈrɪr/",part:54,
   example:"She began her career as a nurse in a small hospital.",
   exampleJa:"彼女は小さな病院で看護師としての経歴を始めた。",
   example2:"A good teacher can change the career of a young student.",
   exampleJa2:"よい教師は、若い生徒の経歴を変えることができる。",
   etymologyProcess:"carr（荷車）→ 荷車が通ってできた一本の道は…？",
   etymologyConclusion:"carr（荷車）→ 荷車が通ってできた道のように、歩んできた一本の道＝経歴",
   relatedWords:[
     {word:"carriage",meaning:"馬車，客車",breakdown:"carr（荷車）＋ age（名詞）→ 人を載せて運ぶための車"},
     {word:"carry",meaning:"～を運ぶ",breakdown:"carr（荷車）→ 荷車に載せるようにして物を運んでいく"},
     {word:"cargo",meaning:"積み荷",breakdown:"carr（荷車）→ 船や車に積み込まれた荷物"},
     {word:"charge",meaning:"請求額",breakdown:"carr（荷車）→ 荷を積むように相手へ負わせる支払い"}]},

  {id:533,word:"profession",partOfSpeech:"名詞",meaning:"専門職",
   meanings:["名|（訓練を要する）専門職","名|公言"],
   pronunciation:"/prəˈfeʃn/",part:54,
   example:"Teaching is a profession that requires both knowledge and patience.",
   exampleJa:"教えることは、知識と忍耐の両方を必要とする専門職だ。",
   example2:"Law and medicine have long been respected professions in this country.",
   exampleJa2:"法律と医学は、この国で長く尊敬される専門職であった。",
   etymologyProcess:"pro（人前で）＋ fess（告げる）＋ ion（名詞）→ 人前で腕前を告げて就く仕事は…？",
   etymologyConclusion:"pro（人前で）＋ fess（告げる）＋ ion（名詞）→ 人前で腕前を宣言して就く仕事＝専門職",
   relatedWords:[
     {word:"professional",meaning:"専門職の，プロの",breakdown:"pro（人前で）＋ fess（告げる）＋ al（〜の）→ 腕前を公言できる"},
     {word:"professor",meaning:"教授",breakdown:"pro（人前で）＋ fess（告げる）＋ or（人）→ 人前で学問を説く人"},
     {word:"confess",meaning:"～を告白する",breakdown:"con（すっかり）＋ fess（告げる）→ 隠さずすっかり告げてしまう"},
     {synonym:true,word:"occupation",meaning:"職業",breakdown:"日々従事する仕事全般。profession は訓練のいる専門職"}]},

  {id:534,word:"unemployment",partOfSpeech:"名詞",meaning:"失業",
   meanings:["名|失業，失業率"],
   pronunciation:"/ˌʌnɪmˈplɔɪmənt/",part:54,
   example:"Unemployment rose quickly in that city after the factory closed.",
   exampleJa:"工場が閉鎖されたあと、その市では失業が急速に増えた。",
   example2:"The government is trying to reduce unemployment among young people.",
   exampleJa2:"政府は若者の間の失業を減らそうとしている。",
   etymologyProcess:"un（否定）＋ ploy（折る）→ 仕事に組み入れてもらえない状態は…？",
   etymologyConclusion:"un（否定）＋ em（中へ）＋ ploy（折る）＋ ment（名詞）→ 仕事の中へ折り込まれていない＝失業",
   relatedWords:[
     {word:"unemployed",meaning:"失業している",breakdown:"un（否定）＋ ploy（折る）＋ ed（〜された）→ 仕事に組み入れられていない"},
     {word:"employment",meaning:"雇用",breakdown:"em（中へ）＋ ploy（折る）＋ ment（名詞）→ 人が仕事に組み入れられた状態"},
     {word:"complicated",meaning:"複雑な",breakdown:"com（共に）＋ pli（折る）→ 何重にも折り重なってほどきにくい"},
     {word:"imply",meaning:"～をほのめかす",breakdown:"im（中へ）＋ pli（折る）→ 意味を内側に折り込んで含ませる"}]},

  {id:535,word:"document",partOfSpeech:"名詞",meaning:"書類",
   meanings:["名|書類，文書","他|～を記録する"],
   pronunciation:"/ˈdɑːkjumənt/",part:54,
   example:"Please bring every document you need to open a bank account.",
   exampleJa:"銀行口座を開くのに必要なすべての書類を持ってきてください。",
   example2:"These old documents were found in the school library last month.",
   exampleJa2:"これらの古い書類は、先月学校の図書館で見つかった。",
   etymologyProcess:"doc（教える）＋ ment（名詞）→ 中身を書いて人に教えるものは…？",
   etymologyConclusion:"doc（教える）＋ ment（名詞）→ 何があったかを書き記して人に教えるもの＝書類",
   relatedWords:[
     {word:"doctor",meaning:"医者，博士",breakdown:"doc（教える）＋ or（人）→ もとは学問を教える資格を持つ人"},
     {word:"doctrine",meaning:"教義",breakdown:"doc（教える）＋ ine（もの）→ 教えとしてまとめられた中身"},
     {word:"documentary",meaning:"記録映画",breakdown:"doc（教える）＋ ment（名詞）＋ ary（もの）→ 事実を記録して見せる作品"},
     {synonym:true,word:"record",meaning:"記録",breakdown:"残しておく記録全般。document は紙に書かれた書類"}]},

  {id:536,word:"department",partOfSpeech:"名詞",meaning:"部門",
   meanings:["名|（組織の）部門，学科","名|（役所の）省"],
   pronunciation:"/dɪˈpɑːrtmənt/",part:54,
   example:"She works in the sales department on the fourth floor.",
   exampleJa:"彼女は4階の販売部門で働いている。",
   example2:"Our school's music department will hold a concert next Saturday.",
   exampleJa2:"私たちの学校の音楽部門は、来週の土曜に演奏会を開く。",
   etymologyProcess:"de（離して）＋ part（分ける）→ 全体を切り分けてできた一つは…？",
   etymologyConclusion:"de（離して）＋ part（分ける）＋ ment（名詞）→ 組織を切り分けてできた一つの区切り＝部門",
   relatedWords:[
     {word:"part",meaning:"部分",breakdown:"part（分ける）→ 全体を分けてできた一つひとつ"},
     {word:"depart",meaning:"出発する",breakdown:"de（離して）＋ part（分ける）→ その場から身を切り離して出ていく"},
     {word:"particular",meaning:"特定の",breakdown:"part（分ける）＋ cul（小さい）→ 細かく分けた中の、その一つ"},
     {word:"partner",meaning:"仲間，相棒",breakdown:"part（分ける）＋ er（人）→ 仕事や取り分を分け合う相手"}]},

  {id:537,word:"branch",partOfSpeech:"名詞",meaning:"支店",
   meanings:["名|支店，支部","名|（木の）枝"],
   pronunciation:"/bræntʃ/",part:54,
   example:"The bank opened a new branch near our high school.",
   exampleJa:"その銀行は、私たちの高校の近くに新しい支店を開いた。",
   example2:"Every branch of this company closes at seven in the evening.",
   exampleJa2:"この会社のすべての支店は、夕方7時に閉まる。",
   hook:"もとの意味は「木の枝」。本店から枝分かれした店なので「支店」。",
   etymologyProcess:"branch（枝）→ 幹から分かれて伸びた先にあるものは…？",
   etymologyConclusion:"branch（枝）→ 幹から分かれて伸びた枝の先にある店＝支店",
   relatedWords:[
     {synonym:true,word:"headquarters",meaning:"本社",breakdown:"組織の中心。branch はそこから枝分かれした先"},
     {synonym:true,word:"division",meaning:"部門",breakdown:"組織を分けた区切り。branch は場所として分かれた店"},
     {synonym:true,word:"office",meaning:"事務所",breakdown:"働く場所全般。branch は本店に対する出先の店"},
     {synonym:true,word:"root",meaning:"根",breakdown:"木の下の部分。branch はそこから伸びた上の部分"}]},

  {id:538,word:"retail",partOfSpeech:"名詞",meaning:"小売り",
   meanings:["名|小売り","形|小売りの"],
   pronunciation:"/ˈriːteɪl/",part:54,
   example:"The store moved from wholesale to retail about ten years ago.",
   exampleJa:"その店は10年ほど前に、卸売りから小売りへ移った。",
   example2:"Many students find their first job in retail or restaurants.",
   exampleJa2:"多くの学生は、小売りか飲食店で最初の仕事を見つける。",
   etymologyProcess:"re（再び）＋ tail（切る）→ まとめ買いした品を切り分けて売ると…？",
   etymologyConclusion:"re（再び）＋ tail（切る）→ まとめ買いした品を小さく切り分けて客に売ること＝小売り",
   relatedWords:[
     {word:"tailor",meaning:"仕立て屋",breakdown:"tail（切る）＋ or（人）→ 布を切って服を仕立てる人"},
     {word:"detail",meaning:"詳細",breakdown:"de（すっかり）＋ tail（切る）→ 細かく切り分けた一つひとつ"},
     {synonym:true,word:"wholesale",meaning:"卸売り",breakdown:"まとめて業者に売ること。retail は客に少しずつ売る"},
     {synonym:true,word:"customer",meaning:"客",breakdown:"retail の相手になる人。小分けにして買っていく側"}]},

  {id:539,word:"colleague",partOfSpeech:"名詞",meaning:"同僚",
   meanings:["名|（仕事上の）同僚"],
   pronunciation:"/ˈkɑːliːɡ/",part:54,
   example:"He asked a colleague to check the report before the meeting.",
   exampleJa:"彼は会議の前に、報告書を確認するよう同僚に頼んだ。",
   example2:"Her colleagues gave her flowers on her last day at work.",
   exampleJa2:"彼女の同僚たちは、職場での最後の日に花を贈った。",
   etymologyProcess:"col（共に）＋ leg（任じる）→ 同じ役目を任された相手は…？",
   etymologyConclusion:"col（共に）＋ leg（任じる）＋ ue（もの）→ 同じ役目を共に任されている相手＝同僚",
   relatedWords:[
     {word:"college",meaning:"大学",breakdown:"col（共に）＋ leg（任じる）→ 同じ学びを共に任された仲間の集まる場"},
     {word:"delegate",meaning:"代表者",breakdown:"de（離して）＋ leg（任じる）＋ ate（動詞）→ 役目を託して送り出す人"},
     {word:"legacy",meaning:"遺産",breakdown:"leg（任じる）＋ cy（名詞）→ 後の人に託して残していくもの"},
     {synonym:true,word:"coworker",meaning:"同僚",breakdown:"同じ職場で働く人。colleague は専門職どうしで使うことが多い"}]},

  {id:540,word:"system",partOfSpeech:"名詞",meaning:"制度，体系",
   meanings:["名|制度，体系","名|（機械の）装置一式"],
   pronunciation:"/ˈsɪstəm/",part:54,
   example:"The school changed its grading system at the start of April.",
   exampleJa:"その学校は4月の初めに評価の制度を変えた。",
   example2:"A new bus system was introduced to connect the two towns.",
   exampleJa2:"二つの町を結ぶため、新しいバスの制度が導入された。",
   etymologyProcess:"sym（共に）＋ stem（立てる）→ ばらばらの物を共に組み立てると…？",
   etymologyConclusion:"sym（共に）＋ stem（立てる）→ ばらばらの物を共に組み立てて作った全体＝制度，体系",
   relatedWords:[
     {word:"symptom",meaning:"症状",breakdown:"sym（共に）＋ ptom（落ちる）→ 病気と一緒に体へ降りかかる目印"},
     {word:"symbol",meaning:"象徴",breakdown:"sym（共に）＋ bol（投げる）→ 二つを重ね投げて合わせた目印"},
     {word:"sympathy",meaning:"同情",breakdown:"sym（共に）＋ path（感じる）→ 相手と同じ痛みを一緒に感じる心"},
     {word:"systematic",meaning:"体系的な",breakdown:"sym（共に）＋ stem（立てる）＋ ic（形容詞）→ きちんと組み立てられた"}]},

  {id:541,word:"structure",partOfSpeech:"名詞",meaning:"構造",
   meanings:["名|構造，組み立て","名|建造物"],
   pronunciation:"/ˈstrʌktʃər/",part:55,
   example:"The structure of this bridge has not changed for eighty years.",
   exampleJa:"この橋の構造は、80年間変わっていない。",
   example2:"Our teacher drew the structure of a flower on the blackboard.",
   exampleJa2:"先生は黒板に花の構造を描いた。",
   etymologyProcess:"stru（積み上げる）＋ ure（名詞）→ 積み上げてできた組み立ては…？",
   etymologyConclusion:"stru（積み上げる）＋ ure（名詞）→ 部品を積み上げてできあがった組み立て方＝構造",
   relatedWords:[
     {word:"construct",meaning:"～を建設する",breakdown:"con（共に）＋ stru（積み上げる）→ 材料を組み合わせて積み上げる"},
     {word:"instruct",meaning:"～に指示する",breakdown:"in（中へ）＋ stru（積み上げる）→ 相手の中に知識を積み上げてやる"},
     {word:"destroy",meaning:"～を破壊する",breakdown:"de（逆に）＋ stru（積み上げる）→ 積み上げたものを逆に崩す"},
     {word:"instrument",meaning:"楽器，道具",breakdown:"in（中へ）＋ stru（積み上げる）＋ ment（名詞）→ 中に組んだ仕掛け"}]},

  {id:542,word:"architecture",partOfSpeech:"名詞",meaning:"建築",
   meanings:["名|建築，建築様式","名|（全体の）設計"],
   pronunciation:"/ˈɑːrkɪtektʃər/",part:55,
   example:"He went to Italy to study the architecture of old churches.",
   exampleJa:"彼は古い教会の建築を学ぶためにイタリアへ行った。",
   example2:"Japanese architecture uses wood and paper in a very clever way.",
   exampleJa2:"日本の建築は、木と紙をとても巧みに使っている。",
   etymologyProcess:"arch（主な）＋ tect（建てる）→ 建てる仕事を束ねる技は…？",
   etymologyConclusion:"arch（主な）＋ tect（建てる）＋ ure（名詞）→ 建てる仕事を束ねる頭の技＝建築",
   relatedWords:[
     {word:"architect",meaning:"建築家",breakdown:"arch（主な）＋ tect（建てる）→ 建てる仕事の頭に立って設計する人"},
     {word:"monarch",meaning:"君主",breakdown:"mono（1つ）＋ arch（主な）→ ただ一人で頭に立って治める人"},
     {synonym:true,word:"building",meaning:"建物",breakdown:"建てられた物そのもの。architecture は建て方の技と様式"},
     {synonym:true,word:"design",meaning:"～を設計する",breakdown:"形を決める行い。architecture は建物の設計全体を指す"}]},

  {id:543,word:"construction",partOfSpeech:"名詞",meaning:"建設",
   meanings:["名|建設，工事","名|（文の）構文"],
   pronunciation:"/kənˈstrʌkʃn/",part:55,
   example:"The construction of the new station will finish next March.",
   exampleJa:"新しい駅の建設は、来年の3月に終わる予定だ。",
   example2:"Noise from the construction site kept us awake all night.",
   exampleJa2:"建設現場からの騒音で、私たちは一晩中眠れなかった。",
   etymologyProcess:"con（共に）＋ stru（積み上げる）→ 材料を組み合わせて積み上げると…？",
   etymologyConclusion:"con（共に）＋ stru（積み上げる）＋ ion（名詞）→ 材料を組み合わせて積み上げること＝建設",
   relatedWords:[
     {word:"construct",meaning:"～を建設する",breakdown:"con（共に）＋ stru（積み上げる）→ 材料を組み合わせて積み上げる"},
     {word:"structure",meaning:"構造",breakdown:"stru（積み上げる）＋ ure（名詞）→ 積み上げてできあがった組み立て"},
     {word:"instruct",meaning:"～に指示する",breakdown:"in（中へ）＋ stru（積み上げる）→ 相手の中に知識を積み上げてやる"},
     {word:"industry",meaning:"工業，産業",breakdown:"indu（中で）＋ stru（積み上げる）→ 休まず内側で物を積み上げる働き"}]},

  {id:544,word:"function",partOfSpeech:"名詞",meaning:"機能",
   meanings:["名|機能，働き","自|機能する"],
   pronunciation:"/ˈfʌŋkʃn/",part:55,
   example:"The main function of the heart is to send blood around.",
   exampleJa:"心臓の主な機能は、血液を全身に送ることだ。",
   example2:"This watch has a useful function for measuring running speed.",
   exampleJa2:"この時計には、走る速さを測る便利な機能がある。",
   etymologyProcess:"funct（果たす）＋ ion（名詞）→ 受け持った役目を果たす働きは…？",
   etymologyConclusion:"funct（果たす）＋ ion（名詞）→ そのものが受け持って果たしている役目＝機能",
   relatedWords:[
     {word:"functional",meaning:"機能的な",breakdown:"funct（果たす）＋ ion（名詞）＋ al（〜の）→ 役目をきちんと果たす"},
     {word:"malfunction",meaning:"故障",breakdown:"mal（悪く）＋ funct（果たす）＋ ion（名詞）→ 役目を正しく果たせないこと"},
     {synonym:true,word:"role",meaning:"役割",breakdown:"人が受け持つ役。function は物や器官の働きに使う"},
     {synonym:true,word:"purpose",meaning:"目的",breakdown:"何のためかという狙い。function は実際にする働き"}]},

  {id:545,word:"surface",partOfSpeech:"名詞",meaning:"表面",
   meanings:["名|表面","名|うわべ"],
   pronunciation:"/ˈsɜːrfɪs/",part:55,
   example:"The surface of the lake was completely still that cold morning.",
   exampleJa:"その寒い朝、湖の表面は完全に静かだった。",
   example2:"Dust had covered the surface of the old piano in the hall.",
   exampleJa2:"ほこりが、ホールの古いピアノの表面を覆っていた。",
   etymologyProcess:"sur（上から）＋ face（顔）→ 物の上側に出ている顔は…？",
   etymologyConclusion:"sur（上から）＋ face（顔）→ 物の上側に出て見えている顔の部分＝表面",
   relatedWords:[
     {word:"face",meaning:"顔",breakdown:"face（顔）→ 体の前面にあって表情が出る部分"},
     {word:"superficial",meaning:"表面的な",breakdown:"super（上から）＋ face（顔）→ 表の顔だけを見て中身を見ない"},
     {word:"surname",meaning:"名字",breakdown:"sur（上から）＋ name（名前）→ 個人の名の上に置く家の名"},
     {word:"facial",meaning:"顔の",breakdown:"face（顔）＋ ial（形容詞）→ 顔にかかわる"}]},

  {id:546,word:"aspect",partOfSpeech:"名詞",meaning:"側面",
   meanings:["名|（物事の）側面","名|外観"],
   pronunciation:"/ˈæspekt/",part:55,
   example:"We must think about every aspect of this difficult problem.",
   exampleJa:"私たちはこの難しい問題のあらゆる側面について考えねばならない。",
   example2:"The funny aspect of school life was missing from his speech.",
   exampleJa2:"学校生活の楽しい側面が、彼の演説には欠けていた。",
   etymologyProcess:"ad（〜へ）＋ spect（見る）→ ある向きから見たときの姿は…？",
   etymologyConclusion:"ad（〜へ）＋ spect（見る）→ ある向きへ目を向けたときに見えてくる姿＝側面",
   relatedWords:[
     {word:"respect",meaning:"～を尊敬する",breakdown:"re（何度も）＋ spect（見る）→ 何度も振り返って見るほど敬う"},
     {word:"inspect",meaning:"～を検査する",breakdown:"in（中へ）＋ spect（見る）→ 中まで入り込んでじっくり見る"},
     {word:"expect",meaning:"～を予期する",breakdown:"ex（外へ）＋ spect（見る）→ 外をじっと見て来るのを待つ"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ ator（人）→ 試合や劇を見に来ている人"}]},

  {id:547,word:"edge",partOfSpeech:"名詞",meaning:"端",
   meanings:["名|端，へり","名|（刃物の）刃"],
   pronunciation:"/edʒ/",part:55,
   example:"He sat quietly on the edge of the wooden bench.",
   exampleJa:"彼は木のベンチの端に静かに座った。",
   example2:"Do not put your glass near the edge of the table.",
   exampleJa2:"グラスをテーブルの端の近くに置いてはいけない。",
   hook:"もとの意味は刃物の「刃」。そこから「ふちの線」の意味が生まれた。",
   etymologyProcess:"edge（刃）→ 刃のように細く切れているところは…？",
   etymologyConclusion:"edge（刃）→ 刃のように細く、そこで物が終わっている線＝端",
   relatedWords:[
     {synonym:true,word:"border",meaning:"国境，境界",breakdown:"土地の区切り。edge は物そのもののふち"},
     {synonym:true,word:"corner",meaning:"角",breakdown:"二つのふちが出あう点。edge はふちの線そのもの"},
     {synonym:true,word:"side",meaning:"横，側面",breakdown:"物の横の面。edge はその面が終わる細い線"},
     {synonym:true,word:"sharp",meaning:"鋭い",breakdown:"よく切れる。edge のもとの意味である刃を表す語"}]},

  {id:548,word:"makeup",partOfSpeech:"名詞",meaning:"構成，成り立ち",
   meanings:["名|構成，成り立ち","名|化粧"],
   pronunciation:"/ˈmeɪkʌp/",part:55,
   example:"The makeup of our class changed a lot after the spring break.",
   exampleJa:"春休みのあと、私たちのクラスの構成は大きく変わった。",
   example2:"Scientists studied the makeup of the rock brought from the moon.",
   exampleJa2:"科学者たちは、月から持ち帰られた岩の構成を調べた。",
   etymologyProcess:"make（作る）＋ up（上へ）→ 部品を組み上げてできた中身は…？",
   etymologyConclusion:"make（作る）＋ up（上へ）→ 部品を組み上げてできあがった中身の並び＝構成",
   relatedWords:[
     {word:"make",meaning:"～を作る",breakdown:"make（作る）→ 材料に手を加えて形のあるものにする"},
     {word:"makeover",meaning:"作り直し，改装",breakdown:"make（作る）＋ over（越えて）→ もう一度はじめから作り変えること"},
     {synonym:true,word:"structure",meaning:"構造",breakdown:"部品の組み立て方。makeup は何でできているかの中身"},
     {synonym:true,word:"composition",meaning:"構成，組み立て",breakdown:"かたい語。makeup は日常語として同じ中身を指す"}]},

  {id:549,word:"consist",partOfSpeech:"自動詞",meaning:"（部分）から成り立っている",
   meanings:["自|（部分）から成り立っている","自|（本質が）～にある"],
   pronunciation:"/kənˈsɪst/",part:55,
   example:"Our club consists of thirty members from three different grades.",
   exampleJa:"私たちの部は、3つの異なる学年の30人の部員から成り立っている。",
   example2:"The test consisted of forty questions and one short essay.",
   exampleJa2:"そのテストは40問と短い作文1題から成り立っていた。",
   etymologyProcess:"con（共に）＋ sist（立つ）→ いくつかの部分が共に立っていると…？",
   etymologyConclusion:"con（共に）＋ sist（立つ）→ いくつかの部分が共に立って全体を支えている＝成り立っている",
   relatedWords:[
     {word:"insist",meaning:"～を言い張る",breakdown:"in（上に）＋ sist（立つ）→ 自分の考えの上に立ち続けて譲らない"},
     {word:"assist",meaning:"～を手伝う",breakdown:"ad（〜へ）＋ sist（立つ）→ 相手のそばに立って力を貸す"},
     {word:"resist",meaning:"～に抵抗する",breakdown:"re（後ろへ）＋ sist（立つ）→ 押されても立ち止まって押し返す"},
     {word:"exist",meaning:"存在する",breakdown:"e（外へ）＋ sist（立つ）→ 世の中に姿を現して立っている"}]},

  {id:550,word:"compose",partOfSpeech:"他動詞",meaning:"～を構成する",
   meanings:["他|～を構成する","他|（曲）を作る"],
   pronunciation:"/kəmˈpoʊz/",part:55,
   example:"Twelve small islands compose this famous national park in the south.",
   exampleJa:"12の小さな島々が、南部のこの有名な国立公園を構成している。",
   example2:"This dictionary is composed of two large volumes and one index.",
   exampleJa2:"この辞書は、2冊の大きな本と1冊の索引から構成されている。",
   etymologyProcess:"com（共に）＋ pos（置く）→ 部品を並べ置いて一つにまとめると…？",
   etymologyConclusion:"com（共に）＋ pos（置く）→ 部品を共に並べ置いて一つの全体にまとめる＝構成する",
   relatedWords:[
     {word:"composition",meaning:"構成，作文",breakdown:"com（共に）＋ pos（置く）＋ ion（名詞）→ 並べ置いてまとめたもの"},
     {word:"composer",meaning:"作曲家",breakdown:"com（共に）＋ pos（置く）＋ er（人）→ 音を並べ置いて曲を組む人"},
     {word:"propose",meaning:"～を提案する",breakdown:"pro（前へ）＋ pos（置く）→ 考えを相手の前に差し出す"},
     {word:"expose",meaning:"～をさらす",breakdown:"ex（外へ）＋ pos（置く）→ 外に置いて見えるようにする"}]},
