  {id:1651,word:"discharge",partOfSpeech:"他動詞",meaning:"（液体・ガスなどを）排出する；退院させる",
   meanings:["他|（液体・ガスなどを）排出する","他|（病院などから）退院させる，解放する","名|排出；退院"],
   pronunciation:"/dɪsˈtʃɑːrdʒ/",part:166,
   example:"The factory was fined for discharging dirty water into the river.",
   exampleJa:"その工場は、川に汚れた水を排出したことで罰金を科された。",
   example2:"My grandfather will be discharged from the hospital next week.",
   exampleJa2:"祖父は来週、退院する予定だ。",
   etymologyProcess:"dis（離れて）＋ carr（荷車）→ 積んだ荷を下ろすと…？",
   etymologyConclusion:"dis（離れて）＋ carr（荷車）→ 積み荷を下ろすように中身を外へ出す＝（液体・ガスなどを）排出する",
   relatedWords:[
     {word:"charge",meaning:"請求額",breakdown:"carr（荷車）→ 荷を積むように相手へ負わせる支払い"},
     {word:"cargo",meaning:"積み荷",breakdown:"carr（荷車）→ 船や車に積み込まれた荷物"},
     {word:"carry",meaning:"運ぶ",breakdown:"carr（荷車）→ 荷車に載せて運んでいく"},
     {synonym:true,word:"release",meaning:"解放する；放出する",breakdown:"閉じこめていたものを放つ。discharge は中身を外へ出す"}]},

  {id:1652,word:"drain",partOfSpeech:"他動詞",meaning:"（水を）抜く，排水する；消耗させる",
   meanings:["他|（水などを）抜く，排水する","他|（体力・資源を）消耗させる","名|排水管，排水口"],
   pronunciation:"/dreɪn/",part:166,
   example:"Please drain the pasta well before you add the sauce.",
   exampleJa:"ソースをかける前に、パスタの水をよく抜いてください。",
   example2:"The long practice after school completely drained all my energy.",
   exampleJa2:"放課後の長い練習で、私の体力はすっかり消耗した。",
   etymologyProcess:"drain（水気を抜く）→ たまった水を流し出すと…？",
   etymologyConclusion:"drain（水気を抜く）→ たまった水を流し出して乾かす＝（水を）抜く",
   hook:"台所の「排水口」も drain。brain drain（頭脳流出）のように力や人が抜けることにも使う。",
   relatedWords:[
     {word:"drainage",meaning:"排水，水はけ",breakdown:"drain（水気を抜く）＋ age（名詞）→ 水を流し出すしくみ"},
     {synonym:true,word:"dry",meaning:"乾いた；乾かす",breakdown:"drain と同じ古英語の家族。水を抜いた先が乾いた状態"},
     {synonym:true,word:"empty",meaning:"空にする；空の",breakdown:"中身をなくすこと全般。drain は液体を流し出す"},
     {synonym:true,word:"exhaust",meaning:"疲れ果てさせる",breakdown:"力を使い切らせる。drain は少しずつ吸い取るように減らす"}]},

  {id:1653,word:"soak",partOfSpeech:"他動詞",meaning:"（液体に）浸す，ずぶぬれにする",
   meanings:["他|（液体に）浸す，つけておく","他|ずぶぬれにする","自|（液体が）しみこむ"],
   pronunciation:"/soʊk/",part:166,
   example:"Soak the beans in water overnight before you cook them.",
   exampleJa:"料理する前に、豆を一晩水に浸しておきなさい。",
   example2:"We got completely soaked on our way home from the stadium.",
   exampleJa2:"競技場からの帰り道に、私たちはすっかりずぶぬれになった。",
   etymologyProcess:"soak（しみこむ）→ 水の中にじっくり置いておくと…？",
   etymologyConclusion:"soak（しみこむ）→ 中まで水がしみこむまで液体につけておく＝（液体に）浸す",
   hook:"suck（吸う）と同じ家族。スポンジが水を吸うように、中までじっくりしみこませる。",
   relatedWords:[
     {word:"soaking",meaning:"ずぶぬれの",breakdown:"soak（しみこむ）＋ ing（～している）→ 水が中までしみこんでいる"},
     {synonym:true,word:"absorb",meaning:"吸収する",breakdown:"ab（離れて）＋ sorb（吸う）。soak は液体の側から包みこむ"},
     {synonym:true,word:"wet",meaning:"ぬれた；ぬらす",breakdown:"表面がぬれること。soak は中までぐっしょり"},
     {synonym:true,word:"dip",meaning:"さっとつける",breakdown:"一瞬だけ液体に入れる。soak は長い時間つけておく"}]},

  {id:1654,word:"dip",partOfSpeech:"他動詞",meaning:"（さっと）つける，ちょっと浸す",
   meanings:["他|（液体に）さっとつける，ちょっと浸す","自|（一時的に）下がる","名|ひと泳ぎ；（値の）下落"],
   pronunciation:"/dɪp/",part:166,
   example:"Dip the strawberries in melted chocolate and let them cool.",
   exampleJa:"いちごを溶かしたチョコレートにさっとつけて、冷ましなさい。",
   example2:"Temperatures here often dip below zero in January.",
   exampleJa2:"ここでは1月になると、気温がよく0度を下回る。",
   etymologyProcess:"dip（ちょっと沈める）→ 液体に一瞬だけ入れると…？",
   etymologyConclusion:"dip（ちょっと沈める）→ 液体に一瞬だけくぐらせてすぐ上げる＝（さっと）つける",
   hook:"北斗七星は Big Dipper（大きなひしゃく）。水にちょっとくぐらせてすくう動き。",
   relatedWords:[
     {word:"dipper",meaning:"ひしゃく",breakdown:"dip（ちょっと沈める）＋ er（道具・人）→ 水にくぐらせてすくう道具"},
     {synonym:true,word:"deep",meaning:"深い",breakdown:"dip と同じ古英語の家族。沈めていった先が深いところ"},
     {synonym:true,word:"soak",meaning:"浸す",breakdown:"長い時間つけておく。dip は一瞬だけ"},
     {synonym:true,word:"plunge",meaning:"突っこむ，飛びこむ",breakdown:"勢いよく深く入れる。dip は軽く浅く"}]},

  {id:1655,word:"suspend",partOfSpeech:"他動詞",meaning:"つるす；（一時的に）停止する",
   meanings:["他|つるす，ぶら下げる","他|（一時的に）停止する，延期する","他|停学［停職］にする"],
   pronunciation:"/səˈspend/",part:166,
   example:"A huge lamp was suspended from the ceiling of the hall.",
   exampleJa:"ホールの天井から、巨大なランプがつるされていた。",
   example2:"The school suspended him for a week for cheating on the test.",
   exampleJa2:"学校はテストでのカンニングを理由に、彼を1週間の停学にした。",
   etymologyProcess:"sub（下で）＋ pend（ぶら下がる）→ 下にぶら下げておくと…？",
   etymologyConclusion:"sub（下で）＋ pend（ぶら下がる）→ 上からつって下にぶら下げる＝つるす",
   why:"【なぜ】ラテン語 suspendere は「下からつり上げる」。つるされた物は地面に着かず宙ぶらりんです。そこから、物事を決着させずに「宙に浮かせておく」という意味が生まれ、運行の一時停止や停学にも使われるようになりました。\n【つながり】suspense（サスペンス）は結末が宙づりのままハラハラする状態。pendant（ペンダント）もぶら下がる飾りです。",
   relatedWords:[
     {word:"pendant",meaning:"ペンダント",breakdown:"pend（ぶら下がる）＋ ant（もの）→ 首から下げる飾り"},
     {word:"depend",meaning:"頼る",breakdown:"de（下へ）＋ pend（ぶら下がる）→ 下にぶら下がって支えてもらう"},
     {word:"pending",meaning:"未決定の",breakdown:"pend（ぶら下がる）＋ ing（～している）→ 決まらずにぶら下がったまま"},
     {synonym:true,word:"hang",meaning:"掛ける，つるす",breakdown:"ふつうの「つるす」。suspend は宙に浮かせる感じが強い"}]},

  {id:1656,word:"extract",partOfSpeech:"他動詞",meaning:"（…から）取り出す，抽出する",
   meanings:["他|（from ～から）取り出す，抽出する","他|（歯などを）抜く","名|抽出物，エキス；抜粋"],
   pronunciation:"/ɪkˈstrækt/",part:166,
   example:"Scientists extract oil from the seeds of this plant.",
   exampleJa:"科学者たちは、この植物の種から油を取り出している。",
   example2:"The dentist had to extract two of my back teeth.",
   exampleJa2:"歯医者は私の奥歯を2本抜かなければならなかった。",
   etymologyProcess:"ex（外へ）＋ tract（引く）→ 中から外へ引っぱると…？",
   etymologyConclusion:"ex（外へ）＋ tract（引く）→ 中にあるものを外へ引っぱり出す＝（…から）取り出す",
   relatedWords:[
     {word:"attract",meaning:"引きつける",breakdown:"ad（～へ）＋ tract（引く）→ 自分のほうへ引き寄せる"},
     {word:"tractor",meaning:"トラクター",breakdown:"tract（引く）＋ or（もの）→ 重い農機具を引っぱる車"},
     {word:"subtract",meaning:"引き算する",breakdown:"sub（下で）＋ tract（引く）→ 下から引き抜いて減らす"},
     {synonym:true,word:"remove",meaning:"取り除く",breakdown:"その場からどける。extract は中から引っぱり出す"}]},

  {id:1657,word:"slap",partOfSpeech:"他動詞",meaning:"平手で打つ，ピシャリとたたく",
   meanings:["他|平手で打つ，ピシャリとたたく","他|（物を）ピシャッと置く","名|平手打ち"],
   pronunciation:"/slæp/",part:166,
   example:"Please don't slap the table when you get angry.",
   exampleJa:"怒ったときに、机を平手でたたかないでください。",
   example2:"He slapped his friend on the back to cheer him up.",
   exampleJa2:"彼は友達を励まそうと、背中をピシャリとたたいた。",
   etymologyProcess:"slap（ピシャッという音）→ その音が出るたたき方は…？",
   etymologyConclusion:"slap（ピシャッという音）→ 開いた手のひらでピシャッとたたく＝平手で打つ",
   hook:"音から生まれた語。clap（パチパチ）と同じく「ピシャッ」という音そのものを表す。",
   relatedWords:[
     {synonym:true,word:"clap",meaning:"手をたたく",breakdown:"これも音から生まれた語。両手を打ち合わせる"},
     {synonym:true,word:"pat",meaning:"軽くたたく",breakdown:"やさしくポンポン。slap は強くピシャリ"},
     {synonym:true,word:"hit",meaning:"打つ，たたく",breakdown:"たたく全般。slap は平手に限る"},
     {synonym:true,word:"punch",meaning:"げんこつでなぐる",breakdown:"握りこぶしで打つ。slap は手のひら"}]},

  {id:1658,word:"embrace",partOfSpeech:"他動詞",meaning:"抱擁する；（考えを）喜んで受け入れる",
   meanings:["他|抱擁する，抱きしめる","他|（考え・変化を）喜んで受け入れる","名|抱擁"],
   pronunciation:"/ɪmˈbreɪs/",part:166,
   example:"The mother embraced her son warmly at the airport gate.",
   exampleJa:"母親は空港のゲートで、息子を温かく抱擁した。",
   example2:"Our school should embrace new ideas from its students.",
   exampleJa2:"私たちの学校は、生徒からの新しい考えを喜んで受け入れるべきだ。",
   etymologyProcess:"em（中へ）＋ brac（腕）→ 腕の中へ入れると…？",
   etymologyConclusion:"em（中へ）＋ brac（腕）→ 相手を両腕の中へ包みこむ＝抱擁する",
   relatedWords:[
     {word:"bracelet",meaning:"ブレスレット",breakdown:"brac（腕）→ 腕にはめる小さな輪の飾り"},
     {word:"brace",meaning:"支え；歯列矯正器",breakdown:"brac（腕）→ 両腕のように両側からがっちり支える器具"},
     {synonym:true,word:"hug",meaning:"抱きしめる",breakdown:"ぎゅっと抱く日常語。embrace は少しあらたまった言い方"},
     {synonym:true,word:"accept",meaning:"受け入れる",breakdown:"受け取ること全般。embrace は喜んで進んで受け入れる"}]},

  {id:1659,word:"embark",partOfSpeech:"自動詞",meaning:"（on ～に）乗り出す，着手する；乗船する",
   meanings:["自|（on ～に）乗り出す，着手する","自|（船・飛行機に）乗りこむ"],
   pronunciation:"/ɪmˈbɑːrk/",part:166,
   example:"She embarked on a new career as a nurse last spring.",
   exampleJa:"彼女は去年の春、看護師として新しい仕事に乗り出した。",
   example2:"The passengers will embark at the port early tomorrow morning.",
   exampleJa2:"乗客たちは明日の早朝、港で乗船する予定だ。",
   etymologyProcess:"em（中へ）＋ bark（小舟）→ 舟の中へ乗りこむと…？",
   etymologyConclusion:"em（中へ）＋ bark（小舟）→ 舟に乗りこんで新しい旅へこぎ出す＝（on ～に）乗り出す",
   why:"【なぜ】もとはフランス語 embarquer「舟（barque）に乗せる」で、文字どおり乗船することでした。港を離れた舟はもう引き返せず、長い旅が始まります。そこから、大きな仕事や計画に「乗り出す・着手する」という意味に広がりました。\n【つながり】disembark は舟から降りること。荷物運びの平底船バージ（barge）も同じ家族です。",
   relatedWords:[
     {word:"disembark",meaning:"（船などから）降りる",breakdown:"dis（離れて）＋ em（中へ）＋ bark（小舟）→ 乗っていた舟から離れる"},
     {word:"barge",meaning:"平底の荷船，バージ",breakdown:"bark（小舟）→ 川で荷を運ぶ平たい舟"},
     {synonym:true,word:"launch",meaning:"打ち上げる；始める",breakdown:"勢いよく送り出す。embark は自分が乗りこんで始める"},
     {synonym:true,word:"undertake",meaning:"引き受ける",breakdown:"仕事を自分の責任で引き受ける。embark は船出のイメージ"}]},

  {id:1660,word:"intervene",partOfSpeech:"自動詞",meaning:"（in ～に）介入する，仲裁に入る",
   meanings:["自|（in ～に）介入する，仲裁に入る","自|（出来事が）間に起こる"],
   pronunciation:"/ˌɪntərˈviːn/",part:166,
   example:"The teacher intervened before the argument turned into a fight.",
   exampleJa:"口論がけんかになる前に、先生が介入した。",
   example2:"The government may intervene to stop prices from rising further.",
   exampleJa2:"政府は、物価がこれ以上上がるのを止めるために介入するかもしれない。",
   etymologyProcess:"inter（間の）＋ ven（来る）→ 二者の間にやって来ると…？",
   etymologyConclusion:"inter（間の）＋ ven（来る）→ 争う二者の間に割って入って来る＝（in ～に）介入する",
   relatedWords:[
     {word:"intervention",meaning:"介入",breakdown:"inter（間の）＋ ven（来る）＋ tion（名詞）→ 間に割って入ること"},
     {word:"prevent",meaning:"妨げる",breakdown:"pre（先に）＋ vent（来る）→ 先回りして来て止める"},
     {word:"adventure",meaning:"冒険",breakdown:"ad（～へ）＋ vent（来る）＋ ure（名詞）→ 向こうからやって来る出来事"},
     {synonym:true,word:"interfere",meaning:"邪魔する",breakdown:"よけいな口出しで邪魔をする。intervene は問題を収めるために間に入る"}]},

  {id:1661,word:"penetrate",partOfSpeech:"他動詞",meaning:"（中へ）入り込む，貫通する；見抜く",
   meanings:["他|（中へ）入り込む，貫通する","他|（市場などに）進出する","他|（本質を）見抜く"],
   pronunciation:"/ˈpenətreɪt/",part:167,
   example:"The sunlight could not penetrate the thick forest at all.",
   exampleJa:"日の光は、その深い森の中までまったく入り込めなかった。",
   example2:"Japanese companies are trying hard to penetrate the Indian market.",
   exampleJa2:"日本の企業は、インド市場に進出しようと力を注いでいる。",
   etymologyProcess:"penetr（奥まで入る）→ ものの内側の奥へ進むと…？",
   etymologyConclusion:"penetr（奥まで入る）→ ものの内側の奥深くまで入っていく＝（中へ）入り込む",
   hook:"レントゲンのＸ線は体を penetrate（貫通）して写す。見えない奥まで届くイメージ。",
   relatedWords:[
     {word:"penetration",meaning:"貫通；浸透",breakdown:"penetr（奥まで入る）＋ ation（名詞）→ 奥まで入り込むこと"},
     {synonym:true,word:"pierce",meaning:"突き刺す，貫く",breakdown:"とがった物で穴を開ける。penetrate は奥まで届く"},
     {synonym:true,word:"enter",meaning:"入る",breakdown:"中に入ること全般。penetrate は壁などを通りぬけて入る"},
     {synonym:true,word:"invade",meaning:"侵略する",breakdown:"力ずくで攻め入る。penetrate は攻撃でなくても使う"}]},

  {id:1662,word:"intrude",partOfSpeech:"自動詞",meaning:"（許可なく）立ち入る，押し入る；邪魔をする",
   meanings:["自|（into ～に）許可なく立ち入る，押し入る","自|（on ～の）邪魔をする"],
   pronunciation:"/ɪnˈtruːd/",part:167,
   example:"Someone intruded into our garden while we were asleep last night.",
   exampleJa:"昨夜、私たちが寝ている間に、誰かが庭に立ち入った。",
   example2:"I'm sorry to intrude, but can I ask you something?",
   exampleJa2:"お邪魔してすみませんが、ひとつ聞いてもいいですか。",
   etymologyProcess:"in（中へ）＋ trud（押す）→ 中へぐいぐい押していくと…？",
   etymologyConclusion:"in（中へ）＋ trud（押す）→ 招かれていないのに中へ押し入る＝（許可なく）立ち入る",
   relatedWords:[
     {word:"intruder",meaning:"侵入者",breakdown:"in（中へ）＋ trud（押す）＋ er（人）→ 勝手に押し入ってくる人"},
     {word:"protrude",meaning:"突き出る",breakdown:"pro（前へ）＋ trud（押す）→ 前へ押し出されて飛び出す"},
     {synonym:true,word:"invade",meaning:"侵略する",breakdown:"軍などが攻め入る。intrude は個人が勝手に入りこむ"},
     {synonym:true,word:"interrupt",meaning:"話をさえぎる",breakdown:"話や作業を途中で止める。intrude は場に割りこむ"}]},

  {id:1663,word:"utilize",partOfSpeech:"他動詞",meaning:"（目的のために）利用する，活用する",
   meanings:["他|（目的のために）利用する，活用する"],
   pronunciation:"/ˈjuːtəlaɪz/",part:167,
   example:"We should utilize solar energy more in our daily lives.",
   exampleJa:"私たちは日常生活で、太陽エネルギーをもっと利用するべきだ。",
   example2:"The old factory is now utilized as an art museum.",
   exampleJa2:"その古い工場は、今は美術館として活用されている。",
   etymologyProcess:"util（役に立つ）＋ ize（動詞）→ 役に立つように扱うと…？",
   etymologyConclusion:"util（役に立つ）＋ ize（動詞）→ 目的に役立つように使いこなす＝（目的のために）利用する",
   relatedWords:[
     {word:"utility",meaning:"役に立つこと；（電気・水道などの）公共設備",breakdown:"util（役に立つ）＋ ity（名詞）→ 暮らしに役立つもの"},
     {synonym:true,word:"use",meaning:"使う",breakdown:"utilize と同じラテン語 uti（使う）から。ふだん使いの語"},
     {synonym:true,word:"employ",meaning:"（手段を）用いる；雇う",breakdown:"手段として用いる。utilize は役立つよう活用する"},
     {synonym:true,word:"apply",meaning:"応用する",breakdown:"知識や技術を当てはめる。utilize は資源などを活用する"}]},

  {id:1664,word:"embed",partOfSpeech:"他動詞",meaning:"埋め込む，はめこむ；（心に）深く刻みこむ",
   meanings:["他|（in ～に）埋め込む，はめこむ","他|（記憶・社会などに）深く根づかせる"],
   pronunciation:"/ɪmˈbed/",part:167,
   example:"Engineers embed tiny chips in the soles of these running shoes.",
   exampleJa:"技術者たちは、このランニングシューズの靴底に小さなチップを埋め込んでいる。",
   example2:"The memory of that summer is deeply embedded in my mind.",
   exampleJa2:"あの夏の記憶は、私の心に深く刻みこまれている。",
   etymologyProcess:"em（中へ）＋ bed（ベッド）→ 寝床の中へくるむと…？",
   etymologyConclusion:"em（中へ）＋ bed（ベッド）→ 寝床にくるむように中へしっかり収める＝埋め込む",
   relatedWords:[
     {word:"bedroom",meaning:"寝室",breakdown:"bed（ベッド）＋ room（部屋）→ 寝るための部屋"},
     {word:"bedtime",meaning:"就寝時刻",breakdown:"bed（ベッド）＋ time（時間の区切り）→ ベッドに入る時"},
     {synonym:true,word:"insert",meaning:"差しこむ",breakdown:"すき間に入れる。embed は周りにしっかり固めて入れる"},
     {synonym:true,word:"bury",meaning:"埋める",breakdown:"土などの下に隠す。embed は中に組みこんで一体にする"}]},

  {id:1665,word:"allocate",partOfSpeech:"他動詞",meaning:"（予算・時間などを）配分する，割り当てる",
   meanings:["他|（to ～に）配分する，割り当てる"],
   pronunciation:"/ˈæləkeɪt/",part:167,
   example:"The city allocated more money to public libraries this year.",
   exampleJa:"市は今年、公立図書館により多くのお金を配分した。",
   example2:"Each club is allocated one hour in the gym per week.",
   exampleJa2:"各部には、週に1時間ずつ体育館が割り当てられている。",
   etymologyProcess:"ad（～へ）＋ loc（場所）＋ ate（動詞）→ それぞれの場所へ置くと…？",
   etymologyConclusion:"ad（～へ）＋ loc（場所）＋ ate（動詞）→ お金や時間をそれぞれの持ち場へ置く＝（予算・時間などを）配分する",
   relatedWords:[
     {word:"local",meaning:"地元の",breakdown:"loc（場所）＋ al（～の）→ その場所の"},
     {word:"location",meaning:"場所，位置",breakdown:"loc（場所）＋ ation（名詞）→ 物が置かれている場所"},
     {word:"locate",meaning:"（場所を）突き止める",breakdown:"loc（場所）＋ ate（動詞）→ ある物の場所を見つける"},
     {synonym:true,word:"assign",meaning:"割り当てる",breakdown:"仕事や役目を人に当てる。allocate は予算や時間を配る"}]},

  {id:1666,word:"coordinate",partOfSpeech:"他動詞",meaning:"（全体がうまくいくように）調整する，まとめる",
   meanings:["他|（全体がうまくいくように）調整する，まとめる","他|（体の動きを）連動させる","名|座標"],
   pronunciation:"/koʊˈɔːrdɪneɪt/",part:167,
   example:"A good captain coordinates the efforts of every team member.",
   exampleJa:"よいキャプテンは、チーム全員の力をうまく調整してまとめる。",
   example2:"Babies cannot yet coordinate the movements of their arms and legs.",
   exampleJa2:"赤ちゃんはまだ、手足の動きをうまく連動させることができない。",
   etymologyProcess:"co（共に）＋ ord（順序）＋ ate（動詞）→ みんなを同じ順序に並べると…？",
   etymologyConclusion:"co（共に）＋ ord（順序）＋ ate（動詞）→ ばらばらな動きを共に順序よくそろえる＝（全体がうまくいくように）調整する",
   relatedWords:[
     {word:"order",meaning:"順序；命令",breakdown:"ord（順序）→ きちんと並んだ順番"},
     {word:"ordinary",meaning:"ふつうの",breakdown:"ord（順序）＋ ary（形容詞）→ いつもの順序どおりの"},
     {word:"disorder",meaning:"混乱",breakdown:"dis（否定）＋ ord（順序）→ 並びが整っていない"},
     {synonym:true,word:"organize",meaning:"計画して準備する",breakdown:"行事などを組み立てる。coordinate は関わる人や動きをそろえる"}]},

  {id:1667,word:"blink",partOfSpeech:"自動詞",meaning:"まばたきする；（光が）点滅する",
   meanings:["自|まばたきする","自|（光が）点滅する","名|まばたき"],
   pronunciation:"/blɪŋk/",part:167,
   example:"Try not to blink when the photographer takes the picture.",
   exampleJa:"カメラマンが写真を撮るとき、まばたきしないようにしてね。",
   example2:"The red light on the machine kept blinking all night.",
   exampleJa2:"機械の赤いランプが、一晩中点滅し続けていた。",
   etymologyProcess:"blink（ちらっと光る）→ 目や光がちらちらすると…？",
   etymologyConclusion:"blink（ちらっと光る）→ 目を一瞬閉じてはまた開く＝まばたきする",
   hook:"車の点滅する方向指示器は「ブリンカー」。in the blink of an eye は「一瞬で」。",
   relatedWords:[
     {synonym:true,word:"wink",meaning:"ウインクする",breakdown:"片目だけを閉じて合図する。blink は両目"},
     {synonym:true,word:"flash",meaning:"ぴかっと光る",breakdown:"一瞬強く光る。blink は明るさがちかちか変わる"},
     {synonym:true,word:"glance",meaning:"ちらっと見る",breakdown:"一瞬だけ目を向ける。blink は目を閉じて開く"},
     {synonym:true,word:"twinkle",meaning:"（星が）きらきら光る",breakdown:"星のように小さくきらきら光る。blink は明るさがちかちか変わる"}]},

  {id:1668,word:"spin",partOfSpeech:"自動詞",meaning:"ぐるぐる回る；（糸を）つむぐ",
   meanings:["自|ぐるぐる回る，回転する","他|回転させる","自|（頭が）くらくらする","他|（糸を）つむぐ"],
   pronunciation:"/spɪn/",part:167,
   example:"The dancer began to spin faster and faster on the stage.",
   exampleJa:"ダンサーは舞台の上で、どんどん速くぐるぐる回り始めた。",
   example2:"My head was spinning after the long math test.",
   exampleJa2:"長い数学のテストのあと、頭がくらくらしていた。",
   etymologyProcess:"spin（糸をつむぐ）→ 糸車を回し続けると…？",
   etymologyConclusion:"spin（糸をつむぐ）→ 糸をつむぐ糸車のようにぐるぐる回る＝ぐるぐる回る",
   hook:"糸車をぐるぐる回して糸をつむぐのが spin。spider（クモ）も「糸をつむぐもの」。",
   relatedWords:[
     {word:"spinner",meaning:"くるくる回るもの，スピナー",breakdown:"spin（糸をつむぐ）＋ er（道具・人）→ 指先でくるくる回るおもちゃ"},
     {synonym:true,word:"rotate",meaning:"回転する",breakdown:"軸を中心に回る。spin は速くくるくる回る"},
     {synonym:true,word:"turn",meaning:"回る，曲がる",breakdown:"向きを変えること全般。spin は何回も回り続ける"},
     {synonym:true,word:"whirl",meaning:"ぐるぐる回る",breakdown:"うずを巻くように回る。spin とほぼ同じ"}]},

  {id:1669,word:"rotate",partOfSpeech:"自動詞",meaning:"（軸を中心に）回転する；交替する",
   meanings:["自|（軸を中心に）回転する","他|回転させる","他|（役割・位置などを）交替する，順番に受け持つ"],
   pronunciation:"/ˈroʊteɪt/",part:167,
   example:"The earth rotates on its axis once every twenty-four hours.",
   exampleJa:"地球は、24時間に1回、軸を中心に回転する。",
   example2:"The members of our team rotate positions every game.",
   exampleJa2:"私たちのチームのメンバーは、試合ごとにポジションを交替する。",
   etymologyProcess:"rota（車輪）＋ ate（動詞）→ 車輪のように動くと…？",
   etymologyConclusion:"rota（車輪）＋ ate（動詞）→ 車輪のように軸のまわりを回る＝（軸を中心に）回転する",
   relatedWords:[
     {word:"rotation",meaning:"回転；交替",breakdown:"rota（車輪）＋ tion（名詞）→ 車輪のように回ること"},
     {word:"rotary",meaning:"回転する",breakdown:"rota（車輪）＋ ary（形容詞）→ 車輪のようにぐるぐる回る"},
     {synonym:true,word:"spin",meaning:"ぐるぐる回る",breakdown:"速くくるくる回る。rotate は軸を中心に規則正しく回る"},
     {synonym:true,word:"revolve",meaning:"（周りを）回る",breakdown:"ほかの物の周りを回る。地球は太陽の周りを revolve する"}]},

  {id:1670,word:"scramble",partOfSpeech:"自動詞",meaning:"（あわてて）よじ登る；奪い合う",
   meanings:["自|（あわてて）よじ登る，はうように急ぐ","自|（for ～を）奪い合う","他|（卵を）かき混ぜて焼く；ごちゃまぜにする"],
   pronunciation:"/ˈskræmbl/",part:167,
   example:"The children scrambled up the hill to see the fireworks.",
   exampleJa:"子どもたちは花火を見ようと、あわてて丘をよじ登った。",
   example2:"I had scrambled eggs and toast for breakfast this morning.",
   exampleJa2:"今朝は、朝食にスクランブルエッグとトーストを食べた。",
   etymologyProcess:"scramble（手足でもがく）→ 手足をばたつかせて進むと…？",
   etymologyConclusion:"scramble（手足でもがく）→ 手足をばたつかせて急いで上へ進む＝（あわてて）よじ登る",
   hook:"語源ははっきりしないが、スクランブルエッグ＝卵をあわただしくかき混ぜる料理と覚える。",
   relatedWords:[
     {synonym:true,word:"climb",meaning:"登る",breakdown:"上へ登ること全般。scramble は手も使って必死に"},
     {synonym:true,word:"rush",meaning:"急いで行く",breakdown:"大急ぎで動く。scramble はあわてて取り乱した感じ"},
     {synonym:true,word:"compete",meaning:"競争する",breakdown:"勝とうと争う。scramble は我先にと奪い合う"},
     {synonym:true,word:"mix",meaning:"混ぜる",breakdown:"混ぜ合わせる全般。scramble はごちゃごちゃにかき混ぜる"}]},

  {id:1671,word:"vanish",partOfSpeech:"自動詞",meaning:"（ふっと）消えうせる，見えなくなる",
   meanings:["自|（急に）消えうせる，見えなくなる","自|（存在が）なくなる，消滅する"],
   pronunciation:"/ˈvænɪʃ/",part:168,
   example:"The cat vanished into the dark forest without a sound.",
   exampleJa:"猫は音もなく、暗い森の中へ消えうせた。",
   example2:"Many small shops have vanished from this town in recent years.",
   exampleJa2:"ここ数年で、この町から小さな店がたくさんなくなった。",
   etymologyProcess:"vani（空っぽの）＋ ish（動詞をつくる）→ そこが空っぽになると…？",
   etymologyConclusion:"vani（空っぽの）＋ ish（動詞をつくる）→ そこにあったものが空っぽになる＝（ふっと）消えうせる",
   relatedWords:[
     {word:"vanity",meaning:"うぬぼれ；むなしさ",breakdown:"vani（空っぽの）＋ ty（名詞）→ 中身のない自慢"},
     {word:"vain",meaning:"むだな",breakdown:"vani（空っぽの）→ 中身がなく実を結ばない。in vain で「むだに」"},
     {synonym:true,word:"disappear",meaning:"見えなくなる",breakdown:"dis（否定）＋ appear（現れる）。vanish は急に跡形もなく"},
     {synonym:true,word:"fade",meaning:"だんだん薄れる",breakdown:"少しずつ消えていく。vanish はふっと一気に消える"}]},

  {id:1672,word:"snap",partOfSpeech:"自動詞",meaning:"ポキンと折れる；パチンと鳴らす",
   meanings:["自|ポキンと折れる","他|（指などを）パチンと鳴らす","自|（at ～に）きつい口調で言う","名|スナップ写真"],
   pronunciation:"/snæp/",part:168,
   example:"Dry branches snap easily when you step on them.",
   exampleJa:"乾いた枝は、踏むと簡単にポキンと折れる。",
   example2:"She snapped her fingers to get the dog's attention.",
   exampleJa2:"彼女は犬の注意を引こうと、指をパチンと鳴らした。",
   etymologyProcess:"snap（パチンという音）→ その音を立てて枝が…？",
   etymologyConclusion:"snap（パチンという音）→ 枝などが短い音を立てて急に割れる＝ポキンと折れる",
   hook:"「スナップ写真」は一瞬でパチッと撮る写真。服のスナップボタンもパチンと留まる。",
   relatedWords:[
     {synonym:true,word:"break",meaning:"壊す，折る",breakdown:"壊れること全般。snap は音を立てて一気に"},
     {synonym:true,word:"crack",meaning:"ひびが入る",breakdown:"割れ目ができる。snap は完全に折れる"},
     {synonym:true,word:"click",meaning:"カチッと鳴る",breakdown:"これも音から生まれた語。小さく硬い音"},
     {synonym:true,word:"bite",meaning:"かみつく",breakdown:"歯でかむ。snap at は「かみつくように言う」"}]},

  {id:1673,word:"rattle",partOfSpeech:"自動詞",meaning:"ガタガタ鳴る；ガラガラ（おもちゃ）",
   meanings:["自|ガタガタ鳴る","他|ガタガタ鳴らす；動揺させる","名|（赤ちゃんの）ガラガラ"],
   pronunciation:"/ˈrætl/",part:168,
   example:"The windows rattle every time a big truck goes by.",
   exampleJa:"大きなトラックが通るたびに、窓がガタガタ鳴る。",
   example2:"The baby was happily shaking her new rattle in bed.",
   exampleJa2:"赤ちゃんはベッドで、新しいガラガラを楽しそうに振っていた。",
   etymologyProcess:"rattle（ガタガタいう音）→ その音を立てると…？",
   etymologyConclusion:"rattle（ガタガタいう音）→ ゆれて固い物がぶつかり合う音がする＝ガタガタ鳴る",
   hook:"音から生まれた語。しっぽを鳴らすガラガラヘビは rattlesnake。",
   relatedWords:[
     {synonym:true,word:"shake",meaning:"ゆらす，ふる",breakdown:"ゆり動かすこと。rattle はその結果ガタガタ音がする"},
     {synonym:true,word:"clatter",meaning:"ガチャガチャ鳴る",breakdown:"固い物がぶつかる音。rattle とよく似た音の語"},
     {synonym:true,word:"knock",meaning:"ノックする",breakdown:"こぶしでたたく音。rattle は細かく続く音"},
     {synonym:true,word:"vibrate",meaning:"振動する",breakdown:"細かくふるえる。rattle は音が出るのが中心"}]},

  {id:1674,word:"cease",partOfSpeech:"自動詞",meaning:"（続いていたことが）やむ，終わる",
   meanings:["自|（続いていたことが）やむ，終わる","他|（～することを）やめる"],
   pronunciation:"/siːs/",part:168,
   example:"The loud noise from the party finally ceased around midnight.",
   exampleJa:"パーティーの大きな騒音は、真夜中ごろにようやくやんだ。",
   example2:"The company will cease production of this model next year.",
   exampleJa2:"その会社は来年、この型の生産をやめる。",
   etymologyProcess:"cess（行く）→ その場から去っていくと…？",
   etymologyConclusion:"cess（行く）→ 立ち去って動きがなくなる＝（続いていたことが）やむ",
   why:"【なぜ】ラテン語 cedere は「行く・引き下がる」。そこから「引き下がったまま動かない」という cessare（やめる・休む）が生まれ、フランス語を通って cease になりました。前へ進む cess が、ここでは「身を引いて止まる」ほうへ向かったのです。\n【つながり】process（前へ進む）とは逆向き。ceasefire（停戦）は「撃つのをやめる」です。",
   relatedWords:[
     {word:"process",meaning:"過程",breakdown:"pro（前へ）＋ cess（行く）→ 前へ進んでいく道のり"},
     {word:"access",meaning:"接近；利用する権利",breakdown:"ad（～へ）＋ cess（行く）→ 目的のところへ行くこと"},
     {word:"success",meaning:"成功",breakdown:"sub（下で）＋ cess（行く）→ うまく次へ進めたこと"},
     {synonym:true,word:"stop",meaning:"止まる，やめる",breakdown:"ふつうの「止まる」。cease は長く続いたものが終わる"}]},

  {id:1675,word:"haste",partOfSpeech:"名詞",meaning:"急ぐこと，あわてること",
   meanings:["名|急ぐこと，あわてること"],
   pronunciation:"/heɪst/",part:168,
   example:"In her haste, she forgot to lock the front door.",
   exampleJa:"急ぐあまり、彼女は玄関の鍵をかけ忘れた。",
   example2:"Remember that haste makes waste, so check your answers twice.",
   exampleJa2:"「急いては事を仕損じる」と言うから、答えは2回見直しなさい。",
   etymologyProcess:"haste（急ぎ）→ 時間に追われると…？",
   etymologyConclusion:"haste（急ぎ）→ 時間に追われてばたばたと急ぐこと＝急ぐこと",
   hook:"Haste makes waste.（急いては事を仕損じる）ということわざで覚える。",
   relatedWords:[
     {word:"hasty",meaning:"急ぎすぎた，軽率な",breakdown:"haste（急ぎ）＋ y（～な状態の）→ あわてて考えが足りない"},
     {word:"hasten",meaning:"急がせる，早める",breakdown:"haste（急ぎ）＋ en（～にする）→ 急ぎの状態にする"},
     {synonym:true,word:"hurry",meaning:"急ぐこと；急ぐ",breakdown:"ふつうの「急ぐ」。haste は少しかたい言い方"},
     {synonym:true,word:"rush",meaning:"大急ぎ",breakdown:"勢いよく急ぐ。haste はあわてる気持ちが中心"}]},

  {id:1676,word:"conceal",partOfSpeech:"他動詞",meaning:"（意図的に）隠す，秘密にする",
   meanings:["他|（意図的に）隠す，秘密にする"],
   pronunciation:"/kənˈsiːl/",part:168,
   example:"He tried to conceal his feelings from his classmates.",
   exampleJa:"彼はクラスメートに、自分の気持ちを隠そうとした。",
   example2:"A small camera was concealed behind a picture on the wall.",
   exampleJa2:"小さなカメラが、壁の絵の裏に隠されていた。",
   etymologyProcess:"con（すっかり）＋ ceal（隠す）→ すっかり覆って隠すと…？",
   etymologyConclusion:"con（すっかり）＋ ceal（隠す）→ 見つからないようにすっかり覆い隠す＝（意図的に）隠す",
   relatedWords:[
     {word:"concealment",meaning:"隠すこと，隠ぺい",breakdown:"con（すっかり）＋ ceal（隠す）＋ ment（名詞）→ 覆い隠すこと"},
     {synonym:true,word:"hide",meaning:"隠す",breakdown:"ふつうの「隠す」。conceal はわざと秘密にするかたい語"},
     {synonym:true,word:"cover",meaning:"覆う",breakdown:"上からかぶせる。conceal は見せないことが目的"},
     {synonym:true,word:"disguise",meaning:"変装させる；ごまかす",breakdown:"見た目を変えてごまかす。conceal は見えなくする"}]},

  {id:1677,word:"disguise",partOfSpeech:"他動詞",meaning:"変装させる；（本心を）ごまかす",
   meanings:["他|変装させる（oneself で「変装する」）","他|（本心・事実を）ごまかす，隠す","名|変装"],
   pronunciation:"/dɪsˈɡaɪz/",part:168,
   example:"The spy disguised himself as a delivery worker.",
   exampleJa:"そのスパイは、配達員に変装した。",
   example2:"She couldn't disguise her disappointment after losing the final.",
   exampleJa2:"決勝で負けたあと、彼女はがっかりした気持ちを隠せなかった。",
   etymologyProcess:"dis（離れて）＋ guise（姿）→ ふだんの姿から離れると…？",
   etymologyConclusion:"dis（離れて）＋ guise（姿）→ ふだんの姿から離れた身なりにする＝変装させる",
   relatedWords:[
     {word:"guise",meaning:"見せかけ，外見",breakdown:"guise（姿）→ 外から見た姿。under the guise of で「～を装って」"},
     {synonym:true,word:"pretend",meaning:"ふりをする",breakdown:"そうであるように見せる。disguise は見た目を変える"},
     {synonym:true,word:"mask",meaning:"仮面；覆い隠す",breakdown:"顔を覆って隠す。disguise は全体の姿を変える"},
     {synonym:true,word:"hide",meaning:"隠す",breakdown:"見えない所へやる。disguise は別物に見せかける"}]},

  {id:1678,word:"deceive",partOfSpeech:"他動詞",meaning:"（うそで）あざむく，だます",
   meanings:["他|（うそで）あざむく，だます","他|（oneself で）思いこむ"],
   pronunciation:"/dɪˈsiːv/",part:168,
   example:"The salesman deceived many elderly people with false promises.",
   exampleJa:"そのセールスマンは、うその約束で多くのお年寄りをあざむいた。",
   example2:"Don't be deceived by his friendly smile and kind words.",
   exampleJa2:"彼の人なつこい笑顔と優しい言葉にだまされてはいけない。",
   etymologyProcess:"de（離して）＋ ceive（取る）→ 相手をわなで捕らえると…？",
   etymologyConclusion:"de（離して）＋ ceive（取る）→ 相手をわなにかけてまるめこむ＝（うそで）あざむく",
   relatedWords:[
     {word:"receive",meaning:"受け取る",breakdown:"re（後ろへ）＋ ceive（取る）→ 差し出されたものを手に取る"},
     {word:"perceive",meaning:"気づく，感じ取る",breakdown:"per（すっかり）＋ ceive（取る）→ すっかりつかみ取る"},
     {word:"deception",meaning:"だますこと，ごまかし",breakdown:"de（離して）＋ cept（取る）＋ ion（名詞）→ わなで捕らえること"},
     {synonym:true,word:"cheat",meaning:"だます；ずるをする",breakdown:"ずるをして得をする。deceive はうそで信じこませる"}]},

  {id:1679,word:"neglect",partOfSpeech:"他動詞",meaning:"（すべきことを）怠る；放っておく",
   meanings:["他|（すべきことを）怠る","他|（世話をせず）放っておく","名|怠慢；放置"],
   pronunciation:"/nɪˈɡlekt/",part:168,
   example:"Don't neglect your health just to study for the exams.",
   exampleJa:"試験勉強のためだけに、健康管理を怠ってはいけない。",
   example2:"The old house had been neglected for many years.",
   exampleJa2:"その古い家は何年も放っておかれていた。",
   etymologyProcess:"nec（否定）＋ lect（拾う）→ 拾わずに放っておくと…？",
   etymologyConclusion:"nec（否定）＋ lect（拾う）→ 拾い上げるべきものを拾わない＝（すべきことを）怠る",
   relatedWords:[
     {word:"collect",meaning:"集める",breakdown:"con（共に）＋ lect（拾う）→ ばらばらの物を一か所へ拾い寄せる"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離して）＋ lect（拾う）→ 分けて拾い出す"},
     {word:"elect",meaning:"（選挙で）選ぶ",breakdown:"e（外へ）＋ lect（拾う）→ 多くの中から拾い出す"},
     {synonym:true,word:"ignore",meaning:"無視する",breakdown:"わざと知らんぷりする。neglect はすべきことをしない"}]},

  {id:1680,word:"evacuate",partOfSpeech:"他動詞",meaning:"避難させる；（建物などから）退避する",
   meanings:["他|（危険な場所から）避難させる","他|（建物などから）退避する"],
   pronunciation:"/ɪˈvækjueɪt/",part:168,
   example:"The police evacuated everyone from the building before the fire spread.",
   exampleJa:"警察は、火が広がる前に建物から全員を避難させた。",
   example2:"We had to evacuate the school during the earthquake drill.",
   exampleJa2:"地震の避難訓練で、私たちは校舎から退避しなければならなかった。",
   etymologyProcess:"e（外へ）＋ vac（空の）＋ ate（動詞）→ 中を空にして外へ出すと…？",
   etymologyConclusion:"e（外へ）＋ vac（空の）＋ ate（動詞）→ 人を外へ出して建物を空にする＝避難させる",
   relatedWords:[
     {word:"vacation",meaning:"休暇",breakdown:"vac（空の）＋ ation（名詞）→ 仕事を空にしている期間"},
     {word:"vacant",meaning:"空いている",breakdown:"vac（空の）＋ ant（～な）→ 誰も使っていない"},
     {word:"vacuum",meaning:"真空；掃除機",breakdown:"vac（空の）→ 中身が何もない空間"},
     {synonym:true,word:"escape",meaning:"逃げる",breakdown:"危険から自分で逃げ出す。evacuate は計画的に人を外へ出す"}]},

  {id:1681,word:"coincide",partOfSpeech:"自動詞",meaning:"（with ～と）同時に起こる；一致する",
   meanings:["自|（with ～と）同時に起こる，重なる","自|（意見などが）一致する"],
   pronunciation:"/ˌkoʊɪnˈsaɪd/",part:169,
   example:"My birthday coincides with the school festival this year.",
   exampleJa:"今年は、私の誕生日が文化祭と同時に来る。",
   example2:"Our opinions did not coincide on this point at all.",
   exampleJa2:"この点について、私たちの意見はまったく一致しなかった。",
   etymologyProcess:"co（共に）＋ in（上に）＋ cid（落ちる）→ 同じところへ一緒に落ちてくると…？",
   etymologyConclusion:"co（共に）＋ in（上に）＋ cid（落ちる）→ 二つの出来事が同じ時に一緒に降りかかる＝（with ～と）同時に起こる",
   relatedWords:[
     {word:"coincidence",meaning:"偶然の一致",breakdown:"co（共に）＋ in（上に）＋ cid（落ちる）＋ ence（名詞）→ 偶然重なること"},
     {word:"incident",meaning:"出来事，事件",breakdown:"in（上に）＋ cid（落ちる）＋ ent（もの）→ 身の上に降りかかったこと"},
     {word:"accident",meaning:"事故",breakdown:"ad（～へ）＋ cid（落ちる）＋ ent（もの）→ 思いがけず降りかかる出来事"},
     {synonym:true,word:"overlap",meaning:"重なる",breakdown:"一部が重なり合う。coincide はぴったり同時・一致"}]},

  {id:1682,word:"prevail",partOfSpeech:"自動詞",meaning:"広く行き渡っている，普及している；打ち勝つ",
   meanings:["自|広く行き渡っている，普及している","自|（over / against ～に）打ち勝つ"],
   pronunciation:"/prɪˈveɪl/",part:169,
   example:"This custom still prevails in many parts of Asia.",
   exampleJa:"この習慣は、今でもアジアの多くの地域に広く行き渡っている。",
   example2:"In the end, justice prevailed over evil in the movie.",
   exampleJa2:"その映画では、最後に正義が悪に打ち勝った。",
   etymologyProcess:"pre（先に）＋ vail（役に立つ）→ ほかより先に力をふるうと…？",
   etymologyConclusion:"pre（先に）＋ vail（役に立つ）→ ほかより強い力をふるって広がる＝広く行き渡っている",
   why:"【なぜ】ラテン語 praevalere は「ほかより強い」。vail のもとの valere は「力がある」です。力くらべで上回ると「打ち勝つ」になり、ある考えや習慣がほかに勝ってあちこちで優勢になると「広く行き渡っている」になりました。\n【つながり】prevalent（広く行き渡った）は同じ家族。available（利用できる）の vail も「役に立つ力」です。",
   relatedWords:[
     {word:"available",meaning:"利用できる",breakdown:"ad（～へ）＋ vail（役に立つ）＋ able（～できる）→ 役に立てることができる"},
     {word:"prevalent",meaning:"広く行き渡った",breakdown:"pre（先に）＋ val（力がある）＋ ent（～している）→ ほかより強く広がっている"},
     {word:"valid",meaning:"有効な",breakdown:"val（力がある）＋ id（～な状態の）→ ちゃんと力を持っている"},
     {synonym:true,word:"win",meaning:"勝つ",breakdown:"試合や争いに勝つ。prevail は苦しい争いの末に勝ち残る"}]},

  {id:1683,word:"sustain",partOfSpeech:"他動詞",meaning:"（長く）維持する，持続させる；（損害を）受ける",
   meanings:["他|（長く）維持する，持続させる","他|（重さを下から）支える","他|（損害・けがを）受ける"],
   pronunciation:"/səˈsteɪn/",part:169,
   example:"It is hard to sustain your motivation during a long vacation.",
   exampleJa:"長い休みの間、やる気を維持するのは難しい。",
   example2:"The player sustained a serious knee injury in the match.",
   exampleJa2:"その選手は試合で、ひざに大けがを負った。",
   etymologyProcess:"sub（下で）＋ tain（保つ）→ 下から支えて保つと…？",
   etymologyConclusion:"sub（下で）＋ tain（保つ）→ 下から支えて倒れないように保ち続ける＝（長く）維持する",
   relatedWords:[
     {word:"sustainable",meaning:"持続可能な，サステナブルな",breakdown:"sub（下で）＋ tain（保つ）＋ able（～できる）→ 支え続けられる"},
     {word:"contain",meaning:"含む",breakdown:"con（共に）＋ tain（保つ）→ 中にまとめて保っている"},
     {word:"retain",meaning:"保ち続ける",breakdown:"re（後ろへ）＋ tain（保つ）→ 手放さずに引きとめておく"},
     {synonym:true,word:"keep",meaning:"保つ",breakdown:"ふつうの「保つ」。sustain は力を注いで長く続けさせる"}]},

  {id:1684,word:"linger",partOfSpeech:"自動詞",meaning:"（なかなか去らずに）残る，長居する",
   meanings:["自|（なかなか去らずに）残る，長居する","自|（においなどが）いつまでも残る"],
   pronunciation:"/ˈlɪŋɡər/",part:169,
   example:"The smell of curry lingered in the kitchen all day.",
   exampleJa:"カレーのにおいが、一日中台所に残っていた。",
   example2:"Please don't linger in the hallway after the bell rings.",
   exampleJa2:"チャイムが鳴ったら、廊下に残ってぐずぐずしないでください。",
   etymologyProcess:"linger（ぐずぐず長引く）→ 去らずにいつまでもいると…？",
   etymologyConclusion:"linger（ぐずぐず長引く）→ 去らずに長くその場にとどまる＝（なかなか去らずに）残る",
   hook:"long（長い）と同じ家族。名残惜しくて、いつまでもぐずぐずとどまるイメージ。",
   relatedWords:[
     {synonym:true,word:"long",meaning:"長い",breakdown:"linger と同じ古英語の家族。いる時間が長くなる"},
     {synonym:true,word:"remain",meaning:"残る，とどまる",breakdown:"そのまま残る。linger は去りがたくてぐずぐず残る"},
     {synonym:true,word:"stay",meaning:"とどまる，滞在する",breakdown:"ある場所にいること全般"},
     {synonym:true,word:"delay",meaning:"遅らせる",breakdown:"予定より遅くする。linger は立ち去るのが遅れる"}]},

  {id:1685,word:"revive",partOfSpeech:"自動詞",meaning:"生き返る，よみがえる；復活させる",
   meanings:["自|生き返る，元気を取り戻す","他|生き返らせる；（伝統などを）復活させる"],
   pronunciation:"/rɪˈvaɪv/",part:169,
   example:"The flowers revived after I gave them some water.",
   exampleJa:"少し水をやると、花は生き返った。",
   example2:"The town is trying to revive its old summer festival.",
   exampleJa2:"その町は、昔の夏祭りを復活させようとしている。",
   etymologyProcess:"re（再び）＋ viv（生きる）→ もう一度生きると…？",
   etymologyConclusion:"re（再び）＋ viv（生きる）→ 弱ったものがもう一度生き生きとする＝生き返る",
   relatedWords:[
     {word:"survive",meaning:"生き残る",breakdown:"sur（上を越えて）＋ viv（生きる）→ 危機を越えて生き続ける"},
     {word:"vivid",meaning:"鮮やかな",breakdown:"viv（生きる）＋ id（～な状態の）→ 生きているように生き生きしている"},
     {word:"revival",meaning:"復活，リバイバル",breakdown:"re（再び）＋ viv（生きる）＋ al（名詞）→ もう一度よみがえること"},
     {synonym:true,word:"recover",meaning:"回復する",breakdown:"元の状態に戻る。revive は弱ったものが息を吹き返す"}]},

  {id:1686,word:"resume",partOfSpeech:"他動詞",meaning:"（中断したことを）再開する",
   meanings:["他|（中断したことを）再開する","自|再び始まる"],
   pronunciation:"/rɪˈzuːm/",part:169,
   example:"We will resume the meeting after a short break.",
   exampleJa:"短い休憩のあと、会議を再開します。",
   example2:"Classes will resume on Monday after the typhoon passes.",
   exampleJa2:"台風が過ぎたら、月曜日に授業が再開される。",
   etymologyProcess:"re（再び）＋ sume（取る）→ 置いたものをもう一度手に取ると…？",
   etymologyConclusion:"re（再び）＋ sume（取る）→ 途中で置いたものをもう一度手に取る＝（中断したことを）再開する",
   relatedWords:[
     {word:"consume",meaning:"消費する",breakdown:"con（すっかり）＋ sume（取る）→ すっかり取り尽くして使い切る"},
     {word:"assume",meaning:"～と思い込む",breakdown:"ad（～へ）＋ sume（取る）→ そうだと自分の中へ取り込んで決める"},
     {word:"presume",meaning:"推定する",breakdown:"pre（先に）＋ sume（取る）→ 確かめる前に先に受け取る"},
     {synonym:true,word:"restart",meaning:"再開する",breakdown:"もう一度始める日常語。resume は途中から続ける"}]},

  {id:1687,word:"outbreak",partOfSpeech:"名詞",meaning:"（戦争・病気などの）発生，勃発",
   meanings:["名|（戦争・病気などの）発生，勃発"],
   pronunciation:"/ˈaʊtbreɪk/",part:169,
   example:"There was an outbreak of flu at our school last month.",
   exampleJa:"先月、私たちの学校でインフルエンザが集団発生した。",
   example2:"Many families left the country after the outbreak of war.",
   exampleJa2:"戦争が勃発したあと、多くの家族がその国を離れた。",
   etymologyProcess:"out（外へ）＋ break（破る）→ 中から破って外へ出ると…？",
   etymologyConclusion:"out（外へ）＋ break（破る）→ 押さえていたものが破れて一気に外へ出る＝（戦争・病気などの）発生",
   relatedWords:[
     {word:"break",meaning:"壊す，破る",breakdown:"break（破る）→ 力をかけて割ったり壊したりする"},
     {word:"breakdown",meaning:"故障；内訳",breakdown:"break（破る）＋ down（下へ）→ 壊れて動かなくなること"},
     {word:"outcome",meaning:"結果",breakdown:"out（外へ）＋ come（来る）→ 最後に外へ出てきたもの"},
     {synonym:true,word:"epidemic",meaning:"（病気の）流行",breakdown:"病気が広く広がること。outbreak は起こり始め"}]},

  {id:1688,word:"inspect",partOfSpeech:"他動詞",meaning:"（詳しく）検査する，点検する",
   meanings:["他|（詳しく）検査する，点検する","他|視察する"],
   pronunciation:"/ɪnˈspekt/",part:169,
   example:"Workers inspect the roller coaster every morning before the park opens.",
   exampleJa:"遊園地が開く前に、作業員が毎朝ジェットコースターを点検する。",
   example2:"The officer carefully inspected my passport at the airport.",
   exampleJa2:"空港で、係官が私のパスポートを念入りに検査した。",
   etymologyProcess:"in（中へ）＋ spect（見る）→ 中までのぞきこむと…？",
   etymologyConclusion:"in（中へ）＋ spect（見る）→ 中までのぞきこんで細かく調べる＝（詳しく）検査する",
   relatedWords:[
     {word:"inspector",meaning:"検査官",breakdown:"in（中へ）＋ spect（見る）＋ or（人）→ 中まで見て調べる人"},
     {word:"expect",meaning:"予期する",breakdown:"ex（外へ）＋ spect（見る）→ 外をじっと見て来るのを待つ"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ ator（人）→ じっと見ている人"},
     {synonym:true,word:"examine",meaning:"調べる，診察する",breakdown:"よく調べる。inspect は決まりどおりか点検する"}]},

  {id:1689,word:"expedition",partOfSpeech:"名詞",meaning:"探検（隊），遠征",
   meanings:["名|探検（隊），遠征","名|（目的のある）小旅行"],
   pronunciation:"/ˌekspəˈdɪʃn/",part:169,
   example:"They joined an expedition to the South Pole last year.",
   exampleJa:"彼らは去年、南極への探検に参加した。",
   example2:"Our club went on a fishing expedition to the lake.",
   exampleJa2:"私たちの部は、湖へ釣りの遠征に出かけた。",
   etymologyProcess:"ex（外へ）＋ pedi（足）＋ tion（名詞）→ 足を自由にして外へ出ると…？",
   etymologyConclusion:"ex（外へ）＋ pedi（足）＋ tion（名詞）→ 足を自由にして遠くへ出かけること＝探検",
   why:"【なぜ】ラテン語 expedire は「足かせを外す」。足が自由になると動けるので「準備を整える・送り出す」という意味になり、そこから準備を整えて送り出す軍の遠征、さらに目的を持った長い旅＝探検を指すようになりました。\n【つながり】pedal（ペダル）や pedestrian（歩行者）も「足」の家族です。",
   relatedWords:[
     {word:"pedal",meaning:"ペダル",breakdown:"pedi（足）＋ al（～の）→ 足でふむ部品"},
     {word:"pedestrian",meaning:"歩行者",breakdown:"pedi（足）＋ an（～の）→ 足で歩いて行く人"},
     {synonym:true,word:"exploration",meaning:"探検",breakdown:"未知の場所を調べて回ること。expedition は隊を組んだ旅"},
     {synonym:true,word:"journey",meaning:"旅",breakdown:"長い旅全般。expedition は目的を持った遠征"}]},

  {id:1690,word:"enroll",partOfSpeech:"自動詞",meaning:"（学校・講座に）入学する，登録する",
   meanings:["自|（in / at ～に）入学する，登録する","他|入学させる，登録させる"],
   pronunciation:"/ɪnˈroʊl/",part:169,
   example:"My sister plans to enroll in a cooking school next year.",
   exampleJa:"姉は来年、料理学校に入学するつもりだ。",
   example2:"More than five hundred students are enrolled at this college.",
   exampleJa2:"この大学には、500人以上の学生が在籍している。",
   etymologyProcess:"en（中に）＋ roll（名簿）→ 名簿の中に名前を入れると…？",
   etymologyConclusion:"en（中に）＋ roll（名簿）→ 学校の名簿の中に名前を書き入れる＝（学校・講座に）入学する",
   relatedWords:[
     {word:"roll",meaning:"転がる；巻いたもの；名簿",breakdown:"roll（名簿）→ くるくる巻いた紙。出席を取る名簿にも"},
     {word:"enrollment",meaning:"入学，登録",breakdown:"en（中に）＋ roll（名簿）＋ ment（名詞）→ 名簿に名前を入れること"},
     {synonym:true,word:"register",meaning:"登録する",breakdown:"公式の記録に書きこむ。enroll は学校や講座に入る"},
     {synonym:true,word:"enter",meaning:"入る；入学する",breakdown:"入ること全般。enroll は名簿に名前が載る"}]},

  {id:1691,word:"discipline",partOfSpeech:"名詞",meaning:"規律，しつけ；しつける",
   meanings:["名|規律，しつけ","他|しつける；罰する","名|（学問の）分野"],
   pronunciation:"/ˈdɪsəplɪn/",part:170,
   example:"Team sports teach young people discipline and patience.",
   exampleJa:"チームスポーツは、若者に規律と忍耐を教えてくれる。",
   example2:"Parents should discipline their children without shouting at them.",
   exampleJa2:"親は、どならずに子どもをしつけるべきだ。",
   etymologyProcess:"discipl（弟子）→ 弟子が守るべきものは…？",
   etymologyConclusion:"discipl（弟子）→ 弟子が師から教えこまれて守る決まり＝規律",
   why:"【なぜ】ラテン語 discipulus は「学ぶ者＝弟子」、disciplina は弟子への「教え」でした。教えには決まりを守らせる訓練がつきもので、そこから「規律・しつけ」、決まりを破ったときの「罰する」、さらに教えの範囲である「学問の分野」へと広がりました。\n【つながり】disciple（弟子）は同じ家族。self-discipline は「自分で自分をしつける」＝自制心です。",
   relatedWords:[
     {word:"disciple",meaning:"弟子，信奉者",breakdown:"discipl（弟子）→ 師のそばで教えを学ぶ人"},
     {synonym:true,word:"rule",meaning:"規則",breakdown:"守るべき決まり。discipline は決まりを守る力や訓練"},
     {synonym:true,word:"training",meaning:"訓練",breakdown:"くり返して身につけること。discipline は心がまえも含む"},
     {synonym:true,word:"punish",meaning:"罰する",breakdown:"悪いことに罰を与える。discipline は正すためにしつける"}]},

  {id:1692,word:"tuition",partOfSpeech:"名詞",meaning:"授業料；（個人）指導",
   meanings:["名|授業料","名|（個人・少人数の）指導"],
   pronunciation:"/tuˈɪʃn/",part:170,
   example:"University tuition in this country has risen sharply.",
   exampleJa:"この国では、大学の授業料が急に上がった。",
   example2:"She receives private tuition in math twice a week.",
   exampleJa2:"彼女は週に2回、数学の個人指導を受けている。",
   etymologyProcess:"tuit（見守る）＋ ion（名詞）→ 見守って教えてもらうと…？",
   etymologyConclusion:"tuit（見守る）＋ ion（名詞）→ 先生に見守られて教わるための費用＝授業料",
   why:"【なぜ】ラテン語 tueri は「見守る・世話をする」。tuition はもともと「保護・後見」の意味でした。子どもを見守ることは教え導くことでもあるので「指導」の意味になり、さらに指導を受けるために払うお金＝授業料を指すようになりました。\n【つながり】tutor（チューター、家庭教師）は「見守る人」。intuition（直感）も「じっと見つめる」から来ています。",
   relatedWords:[
     {word:"tutor",meaning:"家庭教師，チューター",breakdown:"tut（見守る）＋ or（人）→ 生徒を見守って教える人"},
     {word:"intuition",meaning:"直感",breakdown:"in（～に）＋ tuit（見守る）＋ ion（名詞）→ じっと見つめてぱっと分かること"},
     {synonym:true,word:"fee",meaning:"料金，謝礼",breakdown:"サービスへの支払い全般。tuition は教育の費用"},
     {synonym:true,word:"lesson",meaning:"授業，レッスン",breakdown:"一回ごとの授業。tuition は指導そのもの"}]},

  {id:1693,word:"ethic",partOfSpeech:"名詞",meaning:"倫理，道徳観",
   meanings:["名|倫理，道徳観","名|（ethics で）倫理学；行動の規範"],
   pronunciation:"/ˈeθɪk/",part:170,
   example:"Hard work is an important part of the Japanese work ethic.",
   exampleJa:"勤勉さは、日本人の労働倫理の大切な一部だ。",
   example2:"Doctors must follow strict ethics when they treat patients.",
   exampleJa2:"医師は、患者を治療するときに厳しい倫理規範に従わなければならない。",
   etymologyProcess:"eth（習慣）＋ ic（名詞）→ 人々の習慣から生まれた決まりは…？",
   etymologyConclusion:"eth（習慣）＋ ic（名詞）→ 人々の習慣から生まれた正しいふるまいの決まり＝倫理",
   relatedWords:[
     {word:"ethical",meaning:"倫理的な",breakdown:"eth（習慣）＋ ical（～の）→ 正しいふるまいの決まりに合った"},
     {word:"unethical",meaning:"倫理に反する",breakdown:"un（否定）＋ eth（習慣）＋ ical（～の）→ 正しいふるまいに反した"},
     {synonym:true,word:"moral",meaning:"道徳；道徳的な",breakdown:"ラテン語 mos（習慣）から。ethic とほぼ同じ意味"},
     {synonym:true,word:"principle",meaning:"原理，原則",breakdown:"行動のもとになる考え。ethic は善悪の基準"}]},

  {id:1694,word:"psychology",partOfSpeech:"名詞",meaning:"心理学；心理",
   meanings:["名|心理学","名|（人・集団の）心理"],
   pronunciation:"/saɪˈkɑːlədʒi/",part:170,
   example:"My older brother is studying psychology at a university in Tokyo.",
   exampleJa:"兄は東京の大学で心理学を勉強している。",
   example2:"Good coaches understand the psychology of young players.",
   exampleJa2:"よいコーチは、若い選手の心理を理解している。",
   etymologyProcess:"psych（心）＋ log（学問）→ 心について学ぶと…？",
   etymologyConclusion:"psych（心）＋ log（学問）→ 人の心のはたらきを調べる学問＝心理学",
   relatedWords:[
     {word:"psychologist",meaning:"心理学者",breakdown:"psych（心）＋ log（学問）＋ ist（人）→ 心を研究する人"},
     {word:"psychological",meaning:"心理的な",breakdown:"psych（心）＋ log（学問）＋ ical（～の）→ 心の働きに関する"},
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）→ 生命について語る学問"},
     {synonym:true,word:"mind",meaning:"心，精神",breakdown:"考えたり感じたりする心。psychology はそれを調べる学問"}]},

  {id:1695,word:"astronomy",partOfSpeech:"名詞",meaning:"天文学",
   meanings:["名|天文学"],
   pronunciation:"/əˈstrɑːnəmi/",part:170,
   example:"I became interested in astronomy after visiting a planetarium.",
   exampleJa:"プラネタリウムに行ってから、私は天文学に興味を持った。",
   example2:"Ancient people used astronomy to make accurate calendars for farming.",
   exampleJa2:"昔の人々は、農業のための正確な暦を作るのに天文学を使った。",
   etymologyProcess:"astro（星）＋ nom（決まり）→ 星の動きの決まりを調べると…？",
   etymologyConclusion:"astro（星）＋ nom（決まり）→ 星の動きの決まりを調べる学問＝天文学",
   relatedWords:[
     {word:"astronaut",meaning:"宇宙飛行士",breakdown:"astro（星）＋ naut（船乗り）→ 星の世界へ向かう船乗り"},
     {word:"astronomer",meaning:"天文学者",breakdown:"astro（星）＋ nom（決まり）＋ er（人）→ 星の決まりを調べる人"},
     {word:"economy",meaning:"経済",breakdown:"eco（家）＋ nom（切り盛りする）→ 家の切り盛りの仕方"},
     {synonym:true,word:"astrology",meaning:"星占い",breakdown:"星で運勢を占うこと。astronomy は科学"}]},

  {id:1696,word:"archaeologist",partOfSpeech:"名詞",meaning:"考古学者",
   meanings:["名|考古学者"],
   pronunciation:"/ˌɑːrkiˈɑːlədʒɪst/",part:170,
   example:"The archaeologist found ancient coins near the old temple.",
   exampleJa:"その考古学者は、古い寺の近くで古代の硬貨を見つけた。",
   example2:"I want to become an archaeologist and study ancient Egypt.",
   exampleJa2:"私は考古学者になって、古代エジプトを研究したい。",
   etymologyProcess:"archae（古い）＋ log（学問）＋ ist（人）→ 古い時代を研究する人は…？",
   etymologyConclusion:"archae（古い）＋ log（学問）＋ ist（人）→ 大昔の人の暮らしを調べる人＝考古学者",
   relatedWords:[
     {word:"archaeology",meaning:"考古学",breakdown:"archae（古い）＋ log（学問）→ 大昔の遺物を調べる学問"},
     {word:"archaic",meaning:"古風な，古代の",breakdown:"archae（古い）＋ ic（形容詞）→ 大昔の時代の"},
     {word:"psychologist",meaning:"心理学者",breakdown:"psych（心）＋ log（学問）＋ ist（人）→ 心を研究する人"},
     {synonym:true,word:"historian",meaning:"歴史家",breakdown:"記録から歴史を調べる人。archaeologist は遺物から調べる"}]},

  {id:1697,word:"thesis",partOfSpeech:"名詞",meaning:"（卒業・学位）論文；主張",
   meanings:["名|（卒業・学位）論文","名|主張，命題"],
   pronunciation:"/ˈθiːsɪs/",part:170,
   example:"She wrote her graduation thesis on climate change.",
   exampleJa:"彼女は、気候変動について卒業論文を書いた。",
   example2:"The main thesis of his speech was very simple.",
   exampleJa2:"彼のスピーチの中心となる主張は、とても単純だった。",
   etymologyProcess:"thes（置く）→ 自分の考えを目の前に置くと…？",
   etymologyConclusion:"thes（置く）→ 自分の考えを置いて示し、証明していく文章＝（卒業・学位）論文",
   why:"【なぜ】ギリシャ語 thesis は「置くこと」。議論の場に「これが正しい」と置かれた考えのことを指し、そこから「主張・命題」の意味になりました。やがて、その主張を証明するために書く長い文章、つまり大学の論文も thesis と呼ぶようになりました。\n【つながり】hypothesis（仮説）は「下に置いた考え」、synthesis（統合）は「共に置くこと」です。",
   relatedWords:[
     {word:"hypothesis",meaning:"仮説",breakdown:"hypo（下に）＋ thes（置く）→ 議論の土台として下に置いた考え"},
     {word:"synthesis",meaning:"合成，統合",breakdown:"syn（共に）＋ thes（置く）→ いくつかを合わせて一つに置くこと"},
     {synonym:true,word:"essay",meaning:"作文，小論文",breakdown:"考えをまとめた短い文章。thesis は研究の論文"},
     {synonym:true,word:"argument",meaning:"主張，論拠",breakdown:"理由を挙げて示す考え。thesis は中心となる主張"}]},

  {id:1698,word:"dormitory",partOfSpeech:"名詞",meaning:"寮，寄宿舎",
   meanings:["名|寮，寄宿舎"],
   pronunciation:"/ˈdɔːrmətɔːri/",part:170,
   example:"Most first-year students live in the college dormitory.",
   exampleJa:"1年生のほとんどは、大学の寮に住んでいる。",
   example2:"Our dormitory has a big dining hall and a laundry room.",
   exampleJa2:"私たちの寮には、大きな食堂と洗濯室がある。",
   etymologyProcess:"dorm（眠る）＋ ory（場所）→ 眠るための場所は…？",
   etymologyConclusion:"dorm（眠る）＋ ory（場所）→ 大勢が眠るための建物＝寮",
   relatedWords:[
     {word:"dorm",meaning:"寮（口語）",breakdown:"dorm（眠る）→ dormitory を短くした言い方"},
     {word:"dormant",meaning:"休止中の，眠っている",breakdown:"dorm（眠る）＋ ant（～な）→ 眠ったように動かない"},
     {synonym:true,word:"hostel",meaning:"安い宿泊所",breakdown:"旅行者が泊まる安い宿。dormitory は学生が住む"},
     {synonym:true,word:"lodging",meaning:"下宿，宿泊場所",breakdown:"泊まる場所全般。dormitory は学生などが大勢で住む建物"}]},

  {id:1699,word:"grasp",partOfSpeech:"他動詞",meaning:"しっかりつかむ；（意味を）把握する",
   meanings:["他|しっかりつかむ，握る","他|（意味を）理解する，把握する","名|把握；理解"],
   pronunciation:"/ɡræsp/",part:170,
   example:"She grasped the rope with both hands and climbed up.",
   exampleJa:"彼女は両手でロープをしっかりつかんで、登っていった。",
   example2:"It took me a long time to grasp the main idea of the essay.",
   exampleJa2:"その評論の要点を把握するのに、長い時間がかかった。",
   etymologyProcess:"grasp（手でつかむ）→ 手でぎゅっとつかむと…？",
   etymologyConclusion:"grasp（手でつかむ）→ 手のひらでぎゅっと握って離さない＝しっかりつかむ",
   hook:"grope（手探りする）の仲間。手でしっかりつかむ→頭で内容をつかむ＝理解する、と広がった。",
   relatedWords:[
     {synonym:true,word:"grab",meaning:"（さっと）つかむ",breakdown:"素早くつかみ取る。grasp はしっかり握る"},
     {synonym:true,word:"hold",meaning:"持つ，握る",breakdown:"手に持ち続ける全般。grasp は力を入れて握る"},
     {synonym:true,word:"understand",meaning:"理解する",breakdown:"意味が分かる全般。grasp は難しい内容をつかむ"},
     {synonym:true,word:"seize",meaning:"つかむ，奪う",breakdown:"力ずくでつかみ取る。grasp は離さないように握る"}]},

  {id:1700,word:"anticipate",partOfSpeech:"他動詞",meaning:"（前もって）予想して備える；心待ちにする",
   meanings:["他|（前もって）予想する，予期して備える","他|心待ちにする"],
   pronunciation:"/ænˈtɪsɪpeɪt/",part:170,
   example:"We anticipated heavy traffic, so we left home early.",
   exampleJa:"渋滞を見越して、私たちは早めに家を出た。",
   example2:"The new game is eagerly anticipated by fans all over the world.",
   exampleJa2:"その新作ゲームは、世界中のファンに心待ちにされている。",
   etymologyProcess:"ante（前に）＋ cip（取る）＋ ate（動詞）→ 起こる前に取りにいくと…？",
   etymologyConclusion:"ante（前に）＋ cip（取る）＋ ate（動詞）→ 起こる前に先回りしてつかんでおく＝（前もって）予想して備える",
   relatedWords:[
     {word:"participate",meaning:"参加する",breakdown:"part（分ける）＋ cip（取る）＋ ate（動詞）→ 分けた一部を受け持つ"},
     {word:"anticipation",meaning:"予想；期待",breakdown:"ante（前に）＋ cip（取る）＋ ation（名詞）→ 前もってつかむこと"},
     {word:"ancestor",meaning:"祖先",breakdown:"ante（前に）＋ ced（行く）→ 自分より前を歩んだ人"},
     {synonym:true,word:"expect",meaning:"予期する",breakdown:"来ると思って待つ。anticipate は先回りして備える"}]},

  {id:1701,word:"foresee",partOfSpeech:"他動詞",meaning:"予見する，前もって見通す",
   meanings:["他|予見する，前もって見通す"],
   pronunciation:"/fɔːrˈsiː/",part:171,
   example:"Nobody could foresee how popular the small café would become.",
   exampleJa:"その小さなカフェがどれほど人気になるか、誰も予見できなかった。",
   example2:"Experts had foreseen the problem years before it happened.",
   exampleJa2:"専門家たちは、その問題が起こる何年も前に見通していた。",
   etymologyProcess:"fore（前に）＋ see（見る）→ 起こる前に見ると…？",
   etymologyConclusion:"fore（前に）＋ see（見る）→ 起こるより前に先を見ておく＝予見する",
   relatedWords:[
     {word:"forecast",meaning:"予報",breakdown:"fore（前に）＋ cast（投げる）→ 先の空模様を前もって投げかける"},
     {word:"forehead",meaning:"額（ひたい）",breakdown:"fore（前に）＋ head（頭）→ 頭のいちばん前の部分"},
     {word:"sightseeing",meaning:"観光",breakdown:"sight（光景）＋ see（見る）＋ ing（名詞）→ 名所を見て回ること"},
     {synonym:true,word:"predict",meaning:"予測する",breakdown:"前もって言う。foresee は先の様子が見えている"}]},

  {id:1702,word:"infer",partOfSpeech:"他動詞",meaning:"（根拠から）推論する，推し量る",
   meanings:["他|（from ～から）推論する，推し量る"],
   pronunciation:"/ɪnˈfɜːr/",part:171,
   example:"We can infer the writer's feelings from the last paragraph.",
   exampleJa:"最後の段落から、筆者の気持ちを推し量ることができる。",
   example2:"What can you infer from these test results?",
   exampleJa2:"このテストの結果から、どんなことが推し量れますか。",
   etymologyProcess:"in（中へ）＋ fer（運ぶ）→ 根拠を頭の中へ運びこむと…？",
   etymologyConclusion:"in（中へ）＋ fer（運ぶ）→ 手がかりを運びこんで答えを導く＝（根拠から）推論する",
   why:"【なぜ】ラテン語 inferre は「中へ運びこむ」。議論の場に手がかりを運びこみ、そこから答えを「持ち出す」ことを指すようになり、英語では「根拠から結論を引き出す＝推論する」の意味になりました。\n【つながり】inference（推論）は同じ家族。refer（参照する）や transfer（移す）の fer も「運ぶ」です。",
   relatedWords:[
     {word:"inference",meaning:"推論",breakdown:"in（中へ）＋ fer（運ぶ）＋ ence（名詞）→ 手がかりから導いた考え"},
     {word:"refer",meaning:"参照する；言及する",breakdown:"re（元へ）＋ fer（運ぶ）→ 話を元の資料へ運び戻す"},
     {word:"transfer",meaning:"移す；乗り換える",breakdown:"trans（越えて）＋ fer（運ぶ）→ 境を越えて別の場所へ運ぶ"},
     {synonym:true,word:"guess",meaning:"推測する",breakdown:"あてずっぽうも含む。infer は根拠から筋道立てて考える"}]},

  {id:1703,word:"deduce",partOfSpeech:"他動詞",meaning:"（論理的に）推定する，導き出す",
   meanings:["他|（from ～から）推定する，導き出す"],
   pronunciation:"/dɪˈduːs/",part:171,
   example:"The detective deduced the truth from a single footprint.",
   exampleJa:"探偵は、たった一つの足跡から真相を推定した。",
   example2:"From her accent, I could deduce that she was from Osaka.",
   exampleJa2:"なまりから、彼女が大阪出身だと推定できた。",
   etymologyProcess:"de（下へ）＋ duc（導く）→ 筋道をたどって下へ導くと…？",
   etymologyConclusion:"de（下へ）＋ duc（導く）→ 分かっている事実から答えを引き出す＝（論理的に）推定する",
   relatedWords:[
     {word:"introduce",meaning:"紹介する",breakdown:"intro（中へ）＋ duc（導く）→ 輪の中へ導き入れる"},
     {word:"produce",meaning:"生産する",breakdown:"pro（前へ）＋ duc（導く）→ 前へ導き出して形にする"},
     {word:"reduce",meaning:"減らす",breakdown:"re（後ろへ）＋ duc（導く）→ 後ろへ引いて小さくする"},
     {synonym:true,word:"conclude",meaning:"結論を下す",breakdown:"考えを締めくくる。deduce は筋道をたどって導く"}]},

  {id:1704,word:"deem",partOfSpeech:"他動詞",meaning:"（～だと）みなす，判断する",
   meanings:["他|（～だと）みなす，判断する"],
   pronunciation:"/diːm/",part:171,
   example:"The school deemed the old gym too dangerous to use.",
   exampleJa:"学校は、古い体育館を使うには危険すぎるとみなした。",
   example2:"You may leave early if it is deemed necessary.",
   exampleJa2:"必要だと判断されれば、早退してもかまいません。",
   etymologyProcess:"deem（裁く）→ 裁くように判断を下すと…？",
   etymologyConclusion:"deem（裁く）→ 裁きを下すように「これは～だ」と判断する＝（～だと）みなす",
   hook:"doom（運命・破滅）と同じ家族。もとは「裁きを下す」。かたい文で使う。",
   relatedWords:[
     {synonym:true,word:"doom",meaning:"破滅，悪い運命",breakdown:"deem と同じ古英語の家族。下された裁き"},
     {synonym:true,word:"consider",meaning:"よく考える；みなす",breakdown:"consider A B で「A を B とみなす」。deem よりふつう"},
     {synonym:true,word:"regard",meaning:"みなす",breakdown:"regard A as B の形で使う"},
     {synonym:true,word:"judge",meaning:"判断する",breakdown:"よしあしを決める。deem は正式に判断を下す"}]},

  {id:1705,word:"ponder",partOfSpeech:"他動詞",meaning:"じっくり考える，熟考する",
   meanings:["他|じっくり考える，熟考する","自|（on / over ～について）考えこむ"],
   pronunciation:"/ˈpɑːndər/",part:171,
   example:"She pondered the question for a long time before answering.",
   exampleJa:"彼女は答える前に、その質問を長い間じっくり考えた。",
   example2:"I often ponder over my future when I can't sleep.",
   exampleJa2:"眠れないとき、私はよく将来について考えこむ。",
   etymologyProcess:"pond（重さを量る）→ 頭の中で重さを量ると…？",
   etymologyConclusion:"pond（重さを量る）→ 考えを天びんにかけて重さを量る＝じっくり考える",
   relatedWords:[
     {word:"pound",meaning:"ポンド（重さ・お金の単位）",breakdown:"pond（重さを量る）→ 量った重さの単位"},
     {word:"spend",meaning:"（お金・時間を）使う",breakdown:"ex（外へ）＋ pend（重さを量る）→ 量ったお金を外へ払い出す"},
     {word:"expensive",meaning:"高価な",breakdown:"ex（外へ）＋ pens（重さを量る）＋ ive（形容詞）→ 量って多く払い出す"},
     {synonym:true,word:"consider",meaning:"よく考える",breakdown:"よく考えること全般。ponder は時間をかけて深く"}]},

  {id:1706,word:"assure",partOfSpeech:"他動詞",meaning:"（不安な人に）請け合う，保証する",
   meanings:["他|（人に）請け合う，保証する","他|確実にする"],
   pronunciation:"/əˈʃʊr/",part:171,
   example:"The doctor assured me that the surgery would be safe.",
   exampleJa:"医者は、その手術は安全だと私に請け合った。",
   example2:"I can assure you that your bag will arrive tomorrow.",
   exampleJa2:"お荷物は明日必ず届くと、私が保証いたします。",
   etymologyProcess:"ad（～へ）＋ sure（確かな）→ 相手に確かさを届けると…？",
   etymologyConclusion:"ad（～へ）＋ sure（確かな）→ 不安な相手に「確かだ」と言って安心させる＝（不安な人に）請け合う",
   relatedWords:[
     {word:"sure",meaning:"確かな",breakdown:"sure（確かな）→ 疑う余地なくはっきりしている"},
     {word:"ensure",meaning:"確実にする",breakdown:"en（～にする）＋ sure（確かな）→ 確かな状態にしておく"},
     {word:"insure",meaning:"保険をかける",breakdown:"in（～に）＋ sure（確かな）→ 万一に備えて確かにしておく"},
     {synonym:true,word:"guarantee",meaning:"保証する",breakdown:"責任を持って約束する。assure は言葉で安心させる"}]},

  {id:1707,word:"assess",partOfSpeech:"他動詞",meaning:"（状況・能力を）見極める，査定する",
   meanings:["他|（状況・能力を）見極める，評価する","他|（金額を）査定する"],
   pronunciation:"/əˈses/",part:171,
   example:"Teachers assess each student's progress at the end of the term.",
   exampleJa:"先生たちは学期末に、生徒一人一人の成長を見極める。",
   example2:"The damage from the storm was assessed at ten million yen.",
   exampleJa2:"嵐による被害は、1000万円と査定された。",
   etymologyProcess:"ad（～へ）＋ sess（座る）→ 裁判官のそばに座ると…？",
   etymologyConclusion:"ad（～へ）＋ sess（座る）→ 裁判官のそばに座って値打ちを決める＝（状況・能力を）見極める",
   why:"【なぜ】ラテン語 assidere は「そばに座る」。昔の裁判では、裁判官のそばに座る補佐役が罰金や税の額を決めていました。そこから「額を査定する」、さらに広く「状況や能力を見極めて評価する」という意味になりました。\n【つながり】session（会議の時間）、possess（所有している）も「座る」の sess の家族です。",
   relatedWords:[
     {word:"assessment",meaning:"評価，査定",breakdown:"ad（～へ）＋ sess（座る）＋ ment（名詞）→ そばに座って値打ちを決めること"},
     {word:"session",meaning:"会期，集まり",breakdown:"sess（座る）＋ ion（名詞）→ 席に座って話し合う時間"},
     {word:"possess",meaning:"所有している",breakdown:"poss（できる）＋ sess（座る）→ 力の及ぶ場所にどっしり座っている"},
     {synonym:true,word:"evaluate",meaning:"評価する",breakdown:"値打ちを判断する。assess とほぼ同じで使い分けは少ない"}]},

  {id:1708,word:"concede",partOfSpeech:"他動詞",meaning:"（しぶしぶ）認める；譲る",
   meanings:["他|（しぶしぶ）認める","他|（権利・勝利を）譲る","他|（試合で点を）許す"],
   pronunciation:"/kənˈsiːd/",part:171,
   example:"He finally conceded that his plan had some problems.",
   exampleJa:"彼は、自分の計画にいくつか問題があるとようやく認めた。",
   example2:"Our team conceded two goals in the first half.",
   exampleJa2:"私たちのチームは、前半に2点を許した。",
   etymologyProcess:"con（すっかり）＋ ced（行く）→ すっかり身を引くと…？",
   etymologyConclusion:"con（すっかり）＋ ced（行く）→ 言い争いからすっかり身を引いて相手に譲る＝（しぶしぶ）認める",
   relatedWords:[
     {word:"ancestor",meaning:"祖先",breakdown:"ante（前に）＋ ced（行く）→ 自分より前を歩んだ人"},
     {word:"proceed",meaning:"進む",breakdown:"pro（前へ）＋ ceed（行く）→ 前へ進んでいく"},
     {word:"concession",meaning:"譲歩",breakdown:"con（すっかり）＋ cess（行く）＋ ion（名詞）→ 身を引いて譲ること"},
     {synonym:true,word:"admit",meaning:"認める",breakdown:"事実だと認める。concede は負けや誤りをしぶしぶ認める"}]},

  {id:1709,word:"compromise",partOfSpeech:"自動詞",meaning:"妥協する；妥協",
   meanings:["自|（with ～と）妥協する","名|妥協，歩み寄り","他|（信用などを）危うくする"],
   pronunciation:"/ˈkɑːmprəmaɪz/",part:171,
   example:"After a long talk, both sides agreed to compromise on the price.",
   exampleJa:"長い話し合いのあと、両者は値段について妥協することに同意した。",
   example2:"We reached a compromise about where to go on the class trip.",
   exampleJa2:"クラス旅行の行き先について、私たちは妥協案にまとまった。",
   etymologyProcess:"com（共に）＋ pro（前へ）＋ mis（送る）→ 互いに約束を前へ差し出すと…？",
   etymologyConclusion:"com（共に）＋ pro（前へ）＋ mis（送る）→ 両方が約束を差し出して歩み寄る＝妥協する",
   why:"【なぜ】ラテン語 compromittere は「共に約束する」。もめている両者が「仲裁人の決定に従います」と互いに約束することでした。その結果、どちらも少しずつ譲ることになるので、「歩み寄る・妥協する」の意味になりました。\n【つながり】promise（約束）がそのまま入っています。mission（任務）の mis も「送る」です。",
   relatedWords:[
     {word:"promise",meaning:"約束",breakdown:"pro（前へ）＋ mis（送る）→ 言葉を前へ送り出して誓う"},
     {word:"mission",meaning:"任務，使命",breakdown:"mis（送る）＋ ion（名詞）→ 送り出されて果たすべき仕事"},
     {word:"dismiss",meaning:"解散させる；退ける",breakdown:"dis（バラバラに）＋ mis（送る）→ ばらばらに送り出して帰す"},
     {synonym:true,word:"agreement",meaning:"合意",breakdown:"意見が一致すること。compromise は互いに譲って決める"}]},

  {id:1710,word:"comprehend",partOfSpeech:"他動詞",meaning:"（十分に）理解する，のみこむ",
   meanings:["他|（十分に）理解する，のみこむ"],
   pronunciation:"/ˌkɑːmprɪˈhend/",part:171,
   example:"Small children cannot comprehend the value of money.",
   exampleJa:"小さな子どもは、お金の価値を十分に理解することができない。",
   example2:"I read the sentence three times but still couldn't comprehend it.",
   exampleJa2:"その文を3回読んだが、それでものみこめなかった。",
   etymologyProcess:"com（すっかり）＋ prehend（つかむ）→ すっかりつかみ取ると…？",
   etymologyConclusion:"com（すっかり）＋ prehend（つかむ）→ 内容を丸ごとすっかりつかみ取る＝（十分に）理解する",
   relatedWords:[
     {word:"comprehension",meaning:"理解（力）",breakdown:"com（すっかり）＋ prehend（つかむ）＋ ion（名詞）→ 丸ごとつかむ力"},
     {word:"comprehensive",meaning:"包括的な",breakdown:"com（すっかり）＋ prehend（つかむ）＋ ive（形容詞）→ 全部つかんだ"},
     {word:"enterprise",meaning:"事業",breakdown:"entre（間の）＋ pris（つかむ）→ 両手でつかんで取りかかる大仕事"},
     {synonym:true,word:"understand",meaning:"理解する",breakdown:"ふつうの「分かる」。comprehend は難しい内容を全部つかむ"}]},

  {id:1711,word:"reconcile",partOfSpeech:"他動詞",meaning:"仲直りさせる；（考えなどを）両立させる",
   meanings:["他|仲直りさせる，和解させる","他|（考えなどを）調和させる，両立させる"],
   pronunciation:"/ˈrekənsaɪl/",part:172,
   example:"The teacher tried to reconcile the two friends after their fight.",
   exampleJa:"先生は、けんかした二人の友達を仲直りさせようとした。",
   example2:"It is hard to reconcile club activities with studying for exams.",
   exampleJa2:"部活動と受験勉強を両立させるのは難しい。",
   etymologyProcess:"re（再び）＋ con（共に）＋ cil（呼ぶ）→ もう一度一緒に呼び集めると…？",
   etymologyConclusion:"re（再び）＋ con（共に）＋ cil（呼ぶ）→ 離れた二人をもう一度同じ場へ呼び寄せる＝仲直りさせる",
   relatedWords:[
     {word:"council",meaning:"評議会，会議",breakdown:"con（共に）＋ cil（呼ぶ）→ 人々を一か所に呼び集めた会"},
     {word:"reconciliation",meaning:"和解",breakdown:"re（再び）＋ con（共に）＋ cil（呼ぶ）＋ ation（名詞）→ 仲直り"},
     {synonym:true,word:"harmonize",meaning:"調和させる",breakdown:"音や色をうまく合わせる。reconcile は対立を解いて合わせる"},
     {synonym:true,word:"settle",meaning:"（争いを）解決する",breakdown:"もめごとに決着をつける。reconcile は仲を元に戻す"}]},

  {id:1712,word:"instill",partOfSpeech:"他動詞",meaning:"（考え・気持ちを）じわじわ植え付ける，教えこむ",
   meanings:["他|（in / into ～に）植え付ける，教えこむ"],
   pronunciation:"/ɪnˈstɪl/",part:172,
   example:"Good coaches instill confidence in their young players.",
   exampleJa:"よいコーチは、若い選手に少しずつ自信を植え付けていく。",
   example2:"My parents instilled a love of reading in me.",
   exampleJa2:"両親は、私に読書の楽しさを教えこんでくれた。",
   etymologyProcess:"in（中へ）＋ still（しずく）→ しずくを一滴ずつたらしこむと…？",
   etymologyConclusion:"in（中へ）＋ still（しずく）→ 一滴ずつたらしこむように心の中へ入れる＝（考え・気持ちを）じわじわ植え付ける",
   why:"【なぜ】ラテン語 instillare は「しずくを一滴ずつたらしこむ」。目薬をさすような動作です。一度に注ぎこむのではなく、少しずつ時間をかけて入れていくことから、考えや習慣を「じわじわ植え付ける・教えこむ」という意味になりました。\n【つながり】distill（蒸留する）は「しずくにして分ける」。静かなという意味の still とは別の語です。",
   relatedWords:[
     {word:"distill",meaning:"蒸留する",breakdown:"de（下へ）＋ still（しずく）→ しずくにして下へたらし分け取る"},
     {synonym:true,word:"teach",meaning:"教える",breakdown:"教えること全般。instill は時間をかけて身につけさせる"},
     {synonym:true,word:"plant",meaning:"植える",breakdown:"種を植える。instill は心に考えを植える"},
     {synonym:true,word:"inspire",meaning:"奮い立たせる",breakdown:"気持ちを吹きこむ。instill は少しずつしみこませる"}]},

  {id:1713,word:"alert",partOfSpeech:"形容詞",meaning:"油断のない，注意を怠らない；警報",
   meanings:["形|油断のない，注意を怠らない","名|警報","他|（危険を）知らせる，警告する"],
   pronunciation:"/əˈlɜːrt/",part:172,
   example:"Drivers must stay alert, especially when driving late at night.",
   exampleJa:"運転手は、特に夜遅くに運転するときは、注意を怠ってはいけない。",
   example2:"This app will alert you when your train is delayed.",
   exampleJa2:"電車が遅れると、このアプリが知らせてくれる。",
   etymologyProcess:"alert（見張り台の上で）→ 見張り台に立っていると…？",
   etymologyConclusion:"alert（見張り台の上で）→ 見張り台で目を光らせて待ちかまえる＝油断のない",
   hook:"イタリア語 all'erta（見張り台の上で）から。スマホの「アラート」は注意をうながす通知。",
   relatedWords:[
     {synonym:true,word:"aware",meaning:"気づいている",breakdown:"分かっている状態。alert はすぐ動けるよう身がまえている"},
     {synonym:true,word:"careful",meaning:"注意深い",breakdown:"ミスしないよう気をつける。alert は危険にすばやく気づく"},
     {synonym:true,word:"warn",meaning:"警告する",breakdown:"危険を前もって知らせる。alert は急ぎの知らせ"},
     {synonym:true,word:"attentive",meaning:"よく注意を払う",breakdown:"話や相手にしっかり気を配る"}]},

  {id:1714,word:"cognitive",partOfSpeech:"形容詞",meaning:"認知の，認識に関する",
   meanings:["形|認知の，認識に関する"],
   pronunciation:"/ˈkɑːɡnətɪv/",part:172,
   example:"Playing chess may improve young children's cognitive skills, such as memory.",
   exampleJa:"チェスをすると、記憶力のような幼い子どもの認知能力が高まるかもしれない。",
   example2:"Sleep plays an important role in the cognitive development of babies.",
   exampleJa2:"睡眠は、赤ちゃんの認知の発達に大切な役割を果たす。",
   etymologyProcess:"co（共に）＋ gn（知る）＋ ive（形容詞）→ 物事を知る働きに関わると…？",
   etymologyConclusion:"co（共に）＋ gn（知る）＋ ive（形容詞）→ 見たり覚えたりして物事を知る働きの＝認知の",
   relatedWords:[
     {word:"recognize",meaning:"見分ける",breakdown:"re（再び）＋ gn（知る）＋ ize（動詞）→ 前に知った姿をもう一度知る"},
     {word:"ignore",meaning:"無視する",breakdown:"in（否定）＋ gn（知る）→ 知らないことにして相手にしない"},
     {word:"diagnose",meaning:"診断する",breakdown:"dia（間で）＋ gn（知る）→ 症状からどの病気かを見分ける"},
     {synonym:true,word:"mental",meaning:"心の，精神の",breakdown:"心に関わること全般。cognitive は考える・覚える働き"}]},

  {id:1715,word:"intuition",partOfSpeech:"名詞",meaning:"直感，勘",
   meanings:["名|直感，勘"],
   pronunciation:"/ˌɪntuˈɪʃn/",part:172,
   example:"My intuition told me that something was wrong.",
   exampleJa:"何かがおかしいと、私の直感が告げていた。",
   example2:"She made the decision based on intuition, not on data.",
   exampleJa2:"彼女は、データではなく勘に基づいてその決断をした。",
   etymologyProcess:"in（～に）＋ tuit（見守る）＋ ion（名詞）→ じっと見つめていると…？",
   etymologyConclusion:"in（～に）＋ tuit（見守る）＋ ion（名詞）→ じっと見つめて理屈ぬきにぱっと分かること＝直感",
   relatedWords:[
     {word:"intuitive",meaning:"直感的な",breakdown:"in（～に）＋ tuit（見守る）＋ ive（形容詞）→ ぱっと見て分かる"},
     {word:"tuition",meaning:"授業料；指導",breakdown:"tuit（見守る）＋ ion（名詞）→ 見守って教えること"},
     {word:"tutor",meaning:"家庭教師，チューター",breakdown:"tut（見守る）＋ or（人）→ 生徒を見守って教える人"},
     {synonym:true,word:"instinct",meaning:"本能",breakdown:"生まれつき持つ力。intuition は理由なくぱっと分かる感覚"}]},

  {id:1716,word:"vow",partOfSpeech:"名詞",meaning:"誓い；誓う",
   meanings:["名|誓い","他|誓う"],
   pronunciation:"/vaʊ/",part:172,
   example:"They made a vow to meet again in ten years.",
   exampleJa:"彼らは、10年後にまた会うという誓いを立てた。",
   example2:"He vowed never to be late for practice again.",
   exampleJa2:"彼は、二度と練習に遅れないと誓った。",
   etymologyProcess:"vow（誓う）→ 神の前で固く約束すると…？",
   etymologyConclusion:"vow（誓う）→ 神の前で固く約束したこと＝誓い",
   relatedWords:[
     {word:"vote",meaning:"投票する",breakdown:"vot（誓う）→ 誓いを立てて自分の意思を示す"},
     {word:"devote",meaning:"捧げる",breakdown:"de（すっかり）＋ vot（誓う）→ 誓って自分をすっかり差し出す"},
     {synonym:true,word:"promise",meaning:"約束",breakdown:"ふつうの約束。vow はおごそかに誓う"},
     {synonym:true,word:"oath",meaning:"宣誓",breakdown:"法廷などで正式に誓うこと"}]},

  {id:1717,word:"nightmare",partOfSpeech:"名詞",meaning:"悪夢；悪夢のような出来事",
   meanings:["名|悪夢","名|悪夢のような出来事"],
   pronunciation:"/ˈnaɪtmer/",part:172,
   example:"I had a terrible nightmare about missing the entrance exam.",
   exampleJa:"入試を受けそこなうという、ひどい悪夢を見た。",
   example2:"The trip turned into a nightmare when we lost our passports.",
   exampleJa2:"パスポートをなくして、その旅行は悪夢のような出来事になった。",
   etymologyProcess:"night（夜）＋ mare（夢魔）→ 夜に夢魔が来ると…？",
   etymologyConclusion:"night（夜）＋ mare（夢魔）→ 夜に夢魔が胸に乗って見せる怖い夢＝悪夢",
   why:"【なぜ】mare は「雌馬」ではなく、古英語で「眠っている人の胸に乗って息苦しくさせる魔物」のことです。昔の人は、寝苦しくて怖い夢を見るのはこの魔物のしわざだと考えました。そこから、怖い夢そのもの、さらに悪夢のようにひどい出来事を指すようになりました。\n【つながり】「ナイトメア」はゲームや映画の題名でもおなじみです。",
   relatedWords:[
     {word:"midnight",meaning:"真夜中",breakdown:"mid（真ん中の）＋ night（夜）→ 夜のちょうど真ん中"},
     {word:"overnight",meaning:"一晩中；一夜で",breakdown:"over（越えて）＋ night（夜）→ 夜を越えて朝まで"},
     {synonym:true,word:"dream",meaning:"夢",breakdown:"眠っている間に見るもの全般。nightmare は怖い夢"},
     {synonym:true,word:"disaster",meaning:"大惨事",breakdown:"ひどい災い。nightmare は悪夢のようなつらい体験"}]},

  {id:1718,word:"stereotype",partOfSpeech:"名詞",meaning:"固定観念，決まりきった型",
   meanings:["名|固定観念，決まりきった型","他|型にはめて見る"],
   pronunciation:"/ˈsteriətaɪp/",part:172,
   example:"It is a stereotype that all Japanese people are shy.",
   exampleJa:"日本人はみんな内気だというのは、固定観念だ。",
   example2:"The movie stereotypes older people as weak and lonely.",
   exampleJa2:"その映画は、お年寄りを弱くて孤独な人だと型にはめて描いている。",
   etymologyProcess:"stereo（固い）＋ typ（打った跡）→ 固い金属の版で打つと…？",
   etymologyConclusion:"stereo（固い）＋ typ（打った跡）→ 固い版で何度も同じ形を刷る決まりきった型＝固定観念",
   why:"【なぜ】stereotype はもともと印刷の言葉で、活字を固めて作った「鉛の版」のことでした。この版を使うと、何度刷ってもまったく同じ形が出てきます。そこから、人や物を一つの決まった形でしか見ない考え方＝固定観念を指すようになりました。\n【つながり】stereo（ステレオ）は「固い→立体の」、type（タイプ）は「打った跡→型」です。",
   relatedWords:[
     {word:"stereo",meaning:"ステレオ",breakdown:"stereo（固い）→ 固く形のある立体の音"},
     {word:"type",meaning:"型",breakdown:"typ（打った跡）→ 同じ型から打ち出された仲間"},
     {word:"prototype",meaning:"試作品",breakdown:"pro（前へ）＋ typ（打った跡）→ いちばん先に打ち出したひな型"},
     {synonym:true,word:"prejudice",meaning:"偏見",breakdown:"よく知らずに持つ悪い見方。stereotype は型にはめた見方"}]},

  {id:1719,word:"illusion",partOfSpeech:"名詞",meaning:"錯覚，幻想",
   meanings:["名|錯覚","名|（誤った）幻想，思いこみ"],
   pronunciation:"/ɪˈluːʒn/",part:172,
   example:"The mirror creates the illusion that the room is bigger.",
   exampleJa:"鏡によって、部屋が実際より広く見える錯覚が生まれる。",
   example2:"She has no illusions about how hard the job will be.",
   exampleJa2:"彼女は、その仕事がどれほど大変かについて何の幻想も抱いていない。",
   etymologyProcess:"in（～に）＋ lus（遊ぶ）＋ ion（名詞）→ 目をからかって遊ぶと…？",
   etymologyConclusion:"in（～に）＋ lus（遊ぶ）＋ ion（名詞）→ 目や心がからかわれて本物と思いこむこと＝錯覚",
   relatedWords:[
     {word:"prelude",meaning:"前奏曲；前ぶれ",breakdown:"pre（先に）＋ lud（遊ぶ）→ 本番の前に軽く奏でる"},
     {word:"interlude",meaning:"合間の出来事；間奏",breakdown:"inter（間の）＋ lud（遊ぶ）→ 間にはさむ演奏"},
     {synonym:true,word:"fantasy",meaning:"空想",breakdown:"自由に思いえがく世界。illusion は本物と思いこむ"},
     {synonym:true,word:"misconception",meaning:"思いちがい",breakdown:"まちがった理解。illusion は本物だと思いこむ見え方や考え"}]},

  {id:1720,word:"criterion",partOfSpeech:"名詞",meaning:"（判断・評価の）基準",
   meanings:["名|（判断・評価の）基準（複数形 criteria）"],
   pronunciation:"/kraɪˈtɪriən/",part:172,
   example:"Price is not the only criterion for choosing a smartphone.",
   exampleJa:"値段は、スマホを選ぶときの唯一の基準ではない。",
   example2:"Students who meet all the criteria can apply for the scholarship.",
   exampleJa2:"すべての基準を満たす生徒は、その奨学金に申しこめる。",
   etymologyProcess:"crit（ふるい分ける）→ ふるい分けるときに使うものは…？",
   etymologyConclusion:"crit（ふるい分ける）→ 良い悪いをふるい分けるときの物差し＝（判断・評価の）基準",
   relatedWords:[
     {word:"critic",meaning:"批評家",breakdown:"crit（ふるい分ける）→ 良し悪しを見分けて述べる人"},
     {word:"criticize",meaning:"批判する",breakdown:"crit（ふるい分ける）＋ ize（動詞）→ 良し悪しを分けて悪い点を言う"},
     {word:"critical",meaning:"批判的な；重大な",breakdown:"crit（ふるい分ける）＋ ical（～の）→ 分かれ目に関わる"},
     {synonym:true,word:"standard",meaning:"基準，標準",breakdown:"決まった目安。criterion は判断するときの物差し"}]},

  {id:1721,word:"ideology",partOfSpeech:"名詞",meaning:"イデオロギー，（政治的な）考え方の体系",
   meanings:["名|イデオロギー，（政治的・社会的な）考え方の体系"],
   pronunciation:"/ˌaɪdiˈɑːlədʒi/",part:173,
   example:"That ideology shaped the way the country was ruled for decades.",
   exampleJa:"そのイデオロギーが、何十年もその国の治め方を形作った。",
   example2:"The two parties have very different political ideologies.",
   exampleJa2:"その二つの政党は、政治的な考え方の体系がまったく違う。",
   etymologyProcess:"ide（見える姿）＋ log（学問）→ 頭に浮かぶ考えを学ぶと…？",
   etymologyConclusion:"ide（見える姿）＋ log（学問）→ 頭に浮かぶ考えをまとめて一つの筋にしたもの＝イデオロギー",
   why:"【なぜ】ideology は18世紀末にフランスで「観念（idea）の学問」として作られた言葉です。ところが、のちに「現実を見ない理屈」とからかう意味で使われ、やがて政治や社会についての決まった考え方のまとまりを指すようになりました。\n【つながり】idea（アイデア）と、biology の -logy がそのまま入っています。",
   relatedWords:[
     {word:"idea",meaning:"考え，思いつき",breakdown:"ide（見える姿）→ 頭の中に浮かんだ姿"},
     {word:"ideal",meaning:"理想；理想的な",breakdown:"ide（見える姿）＋ al（形容詞）→ 頭の中に描いた最高の姿"},
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）→ 生命について語る学問"},
     {synonym:true,word:"belief",meaning:"信念",breakdown:"正しいと信じる考え。ideology は社会全体の考え方のまとまり"}]},

  {id:1722,word:"tolerate",partOfSpeech:"他動詞",meaning:"（いやなことを）大目に見る，がまんする",
   meanings:["他|（いやなことを）大目に見る，がまんする","他|（厳しい条件に）耐えられる"],
   pronunciation:"/ˈtɑːləreɪt/",part:173,
   example:"Our coach won't tolerate any lateness at practice.",
   exampleJa:"私たちのコーチは、練習での遅刻を少しも大目に見ない。",
   example2:"Some plants can tolerate the very cold weather in the mountains.",
   exampleJa2:"山のとても寒い気候に耐えられる植物もある。",
   etymologyProcess:"toler（耐える）＋ ate（動詞）→ いやなことに耐えると…？",
   etymologyConclusion:"toler（耐える）＋ ate（動詞）→ いやなことにも耐えて受け流す＝（いやなことを）大目に見る",
   relatedWords:[
     {word:"tolerance",meaning:"寛容；耐性",breakdown:"toler（耐える）＋ ance（名詞）→ 違いやいやなことに耐える力"},
     {word:"tolerant",meaning:"寛容な",breakdown:"toler（耐える）＋ ant（～な）→ 他人の違いに耐えられる"},
     {synonym:true,word:"bear",meaning:"耐える",breakdown:"重いものやつらさに耐える。tolerate は許して受け入れる"},
     {synonym:true,word:"endure",meaning:"耐え忍ぶ",breakdown:"長いつらさに持ちこたえる"}]},

  {id:1723,word:"overlook",partOfSpeech:"他動詞",meaning:"見落とす；大目に見る；見下ろす",
   meanings:["他|見落とす","他|（欠点を）大目に見る","他|（高い所から）見下ろす"],
   pronunciation:"/ˌoʊvərˈlʊk/",part:173,
   example:"I overlooked a small mistake on the last page of my report.",
   exampleJa:"レポートの最後のページにある小さなミスを見落とした。",
   example2:"Our hotel room overlooked the beautiful harbor of the city.",
   exampleJa2:"私たちのホテルの部屋からは、街の美しい港が見下ろせた。",
   etymologyProcess:"over（越えて）＋ look（見る）→ 上を越えて向こうを見ると…？",
   etymologyConclusion:"over（越えて）＋ look（見る）→ 上を越えて遠くを見て、手前を見逃す＝見落とす",
   relatedWords:[
     {word:"outlook",meaning:"見通し；考え方",breakdown:"out（外へ）＋ look（見る）→ 外の先のほうを見わたすこと"},
     {word:"overtake",meaning:"追い越す",breakdown:"over（越えて）＋ take（取る）→ 前の人を越えて前に出る"},
     {synonym:true,word:"miss",meaning:"見逃す，取りのがす",breakdown:"気づかずにのがす全般"},
     {synonym:true,word:"neglect",meaning:"怠る",breakdown:"すべきことをしない。overlook はうっかり気づかない"}]},

  {id:1724,word:"conceive",partOfSpeech:"他動詞",meaning:"（考えを）思いつく，心に描く；妊娠する",
   meanings:["他|（考え・計画を）思いつく，心に描く","自|（of ～を）想像する","他・自|妊娠する"],
   pronunciation:"/kənˈsiːv/",part:173,
   example:"He conceived the idea for the game while riding the train.",
   exampleJa:"彼は電車に乗っている間に、そのゲームのアイデアを思いついた。",
   example2:"I can't conceive of life without my smartphone.",
   exampleJa2:"スマホのない生活なんて想像できない。",
   etymologyProcess:"con（すっかり）＋ ceive（取る）→ 心の中にすっかり取りこむと…？",
   etymologyConclusion:"con（すっかり）＋ ceive（取る）→ 考えを心の中にすっかり取りこんで形にする＝（考えを）思いつく",
   why:"【なぜ】ラテン語 concipere は「すっかり取りこむ」。体の中に新しい命を取りこむと「妊娠する」、心の中に新しい考えを取りこむと「思いつく・心に描く」になりました。どちらも「中に宿して育て始める」という同じ出発点です。\n【つながり】concept（コンセプト、概念）は「心に取りこんだ考え」。receive（受け取る）の ceive も同じ家族です。",
   relatedWords:[
     {word:"concept",meaning:"概念，考え",breakdown:"con（すっかり）＋ cept（取る）→ 頭の中にすっかり取りこんだ考え"},
     {word:"receive",meaning:"受け取る",breakdown:"re（後ろへ）＋ ceive（取る）→ 差し出されたものを手に取る"},
     {word:"perceive",meaning:"気づく，感じ取る",breakdown:"per（すっかり）＋ ceive（取る）→ すっかりつかみ取る"},
     {synonym:true,word:"imagine",meaning:"想像する",breakdown:"頭に思い浮かべる。conceive は新しく考え出す"}]},

  {id:1725,word:"misunderstand",partOfSpeech:"他動詞",meaning:"誤解する，思いちがいをする",
   meanings:["他|誤解する，思いちがいをする"],
   pronunciation:"/ˌmɪsʌndərˈstænd/",part:173,
   example:"I think you misunderstand what I was trying to say.",
   exampleJa:"私が言おうとしたことを、あなたは誤解していると思う。",
   example2:"His joke was misunderstood by many people online.",
   exampleJa2:"彼の冗談は、ネット上の多くの人に誤解された。",
   etymologyProcess:"mis（誤って）＋ understand（理解する）→ 理解のしかたをまちがえると…？",
   etymologyConclusion:"mis（誤って）＋ understand（理解する）→ まちがったほうへ受け取って分かったつもりになる＝誤解する",
   relatedWords:[
     {word:"understand",meaning:"理解する",breakdown:"understand（理解する）→ 物事のただ中に立って見きわめる"},
     {word:"mistake",meaning:"まちがい",breakdown:"mis（誤って）＋ take（取る）→ 誤って取りちがえること"},
     {word:"misuse",meaning:"誤用；誤用する",breakdown:"mis（誤って）＋ use（使う）→ まちがった使い方をする"},
     {synonym:true,word:"confuse",meaning:"混同する",breakdown:"二つを取りちがえる。misunderstand は意味を取りちがえる"}]},

  {id:1726,word:"keen",partOfSpeech:"形容詞",meaning:"（感覚が）鋭い；（on ～に）熱中している",
   meanings:["形|（感覚・知性が）鋭い","形|（on ～に）熱中している，～したがっている","形|（競争が）激しい"],
   pronunciation:"/kiːn/",part:173,
   example:"Dogs have a keen sense of smell and can find lost people.",
   exampleJa:"犬は鋭い嗅覚を持っていて、行方不明の人を見つけられる。",
   example2:"My little brother is very keen on soccer these days.",
   exampleJa2:"弟は最近、サッカーにとても熱中している。",
   etymologyProcess:"keen（勇ましい）→ 勇ましく鋭いと…？",
   etymologyConclusion:"keen（勇ましい）→ 勇ましく刃のように研ぎすまされた＝（感覚が）鋭い",
   hook:"もとは古英語で「勇敢な」。勇ましく鋭い→感覚が鋭い、気持ちが熱い、と広がった。",
   relatedWords:[
     {synonym:true,word:"sharp",meaning:"鋭い",breakdown:"刃物や痛みが鋭い。keen は感覚や頭の働き"},
     {synonym:true,word:"eager",meaning:"熱心な",breakdown:"したくてたまらない。keen on もほぼ同じ"},
     {synonym:true,word:"enthusiastic",meaning:"熱狂的な",breakdown:"強く夢中になっている"},
     {synonym:true,word:"intense",meaning:"激しい",breakdown:"程度が強い。keen competition で「激しい競争」"}]},

  {id:1727,word:"subjective",partOfSpeech:"形容詞",meaning:"主観的な，個人の感じ方による",
   meanings:["形|主観的な，個人の感じ方による"],
   pronunciation:"/səbˈdʒektɪv/",part:173,
   example:"Taste in music is very subjective, so don't judge others.",
   exampleJa:"音楽の好みはとても主観的なものだから、他人を決めつけてはいけない。",
   example2:"Try to write a report that is not based on subjective opinions.",
   exampleJa2:"主観的な意見に頼らない報告書を書くようにしなさい。",
   etymologyProcess:"sub（下で）＋ ject（投げる）＋ ive（形容詞）→ 物事の下に置かれた「私」から見ると…？",
   etymologyConclusion:"sub（下で）＋ ject（投げる）＋ ive（形容詞）→ 感じる側の「私」を土台にした＝主観的な",
   why:"【なぜ】subject はラテン語で「下に投げ置かれたもの」。哲学では、見たり感じたりするときの土台になる「私（主体）」を指すようになりました。そこから subjective は「感じる私の側から見た＝主観的な」となりました。反対に、見られる側の「物」が object で、objective は「客観的な」です。\n【つながり】subject（主題・科目）も同じ語です。",
   relatedWords:[
     {word:"subject",meaning:"主題；科目",breakdown:"sub（下で）＋ ject（投げる）→ 下に置かれて取り上げられるもの"},
     {word:"object",meaning:"物；反対する",breakdown:"ob（～に向かって）＋ ject（投げる）→ 目の前に投げ出された物"},
     {word:"reject",meaning:"拒絶する",breakdown:"re（戻す）＋ ject（投げる）→ 投げ返して受け取らない"},
     {synonym:true,word:"personal",meaning:"個人的な",breakdown:"その人自身の。subjective は感じ方がその人しだい"}]},

  {id:1728,word:"compulsory",partOfSpeech:"形容詞",meaning:"（規則で）義務的な，必修の",
   meanings:["形|（規則で）義務的な，強制の","形|（科目が）必修の"],
   pronunciation:"/kəmˈpʌlsəri/",part:173,
   example:"Wearing a helmet is compulsory for all cyclists in this city.",
   exampleJa:"この市では、自転車に乗る人は全員、ヘルメットの着用が義務だ。",
   example2:"English is a compulsory subject in most Japanese high schools.",
   exampleJa2:"日本のほとんどの高校では、英語は必修科目だ。",
   etymologyProcess:"com（すっかり）＋ puls（押しやる）＋ ory（形容詞）→ 力で押しやられると…？",
   etymologyConclusion:"com（すっかり）＋ puls（押しやる）＋ ory（形容詞）→ 力ずくで押しやってでもさせる＝（規則で）義務的な",
   relatedWords:[
     {word:"compel",meaning:"強制する",breakdown:"com（すっかり）＋ pel（押しやる）→ すっかり押して動かしてしまう"},
     {word:"expel",meaning:"追い出す",breakdown:"ex（外へ）＋ pel（押しやる）→ 外へ押し出してしまう"},
     {word:"pulse",meaning:"脈拍",breakdown:"puls（押しやる）→ 血を押し出すように打つ動き"},
     {synonym:true,word:"required",meaning:"必須の",breakdown:"必要とされている。compulsory は規則で強制される"}]},

  {id:1729,word:"relieve",partOfSpeech:"他動詞",meaning:"（苦痛・不安を）和らげる，取り除く",
   meanings:["他|（苦痛・不安を）和らげる，取り除く","他|安心させる（be relieved で「ほっとする」）","他|（任務を）交代する"],
   pronunciation:"/rɪˈliːv/",part:173,
   example:"This medicine will relieve your headache in about thirty minutes.",
   exampleJa:"この薬を飲めば、30分ほどで頭痛が和らぐ。",
   example2:"I was relieved to hear that everyone was safe.",
   exampleJa2:"みんなが無事だと聞いて、ほっとした。",
   etymologyProcess:"re（再び）＋ lev（持ち上げる）→ 重荷を持ち上げると…？",
   etymologyConclusion:"re（再び）＋ lev（持ち上げる）→ のしかかる重荷を持ち上げて軽くする＝（苦痛・不安を）和らげる",
   relatedWords:[
     {word:"relief",meaning:"安心；救済",breakdown:"re（再び）＋ lev（持ち上げる）→ 重荷を持ち上げて軽くすること"},
     {word:"elevator",meaning:"エレベーター",breakdown:"e（外へ）＋ lev（持ち上げる）＋ or（もの）→ 人を持ち上げる装置"},
     {word:"lever",meaning:"てこ，レバー",breakdown:"lev（持ち上げる）→ 重い物を持ち上げるための棒"},
     {synonym:true,word:"ease",meaning:"和らげる",breakdown:"楽にする。relieve は重荷を取り除いて楽にする"}]},

  {id:1730,word:"trim",partOfSpeech:"他動詞",meaning:"刈り込む，切りそろえる；削減する",
   meanings:["他|刈り込む，切りそろえる","他|（予算などを）削減する","名|手入れ，刈り込み"],
   pronunciation:"/trɪm/",part:173,
   example:"My father trims the bushes in our garden every spring.",
   exampleJa:"父は毎年春に、庭の植えこみを刈り込む。",
   example2:"I asked the hairdresser to trim my bangs a little.",
   exampleJa2:"美容師さんに、前髪を少し切りそろえてもらった。",
   etymologyProcess:"trim（整える）→ 余分な所を切って整えると…？",
   etymologyConclusion:"trim（整える）→ はみ出た所を少し切って形を整える＝刈り込む",
   hook:"ペットの「トリミング」は毛を切りそろえること。余分な所を少し切って整える。",
   relatedWords:[
     {synonym:true,word:"cut",meaning:"切る",breakdown:"切ること全般。trim は形を整えるために少し切る"},
     {synonym:true,word:"shave",meaning:"そる",breakdown:"ひげなどを根元からそり落とす。trim は長さを少しそろえるだけ"},
     {synonym:true,word:"reduce",meaning:"減らす",breakdown:"量を減らす全般。trim は余分をけずる"},
     {synonym:true,word:"clip",meaning:"（はさみで）切る，刈る",breakdown:"はさみでパチンと切る。trim は形を整えるために少し切る"}]},

  {id:1731,word:"disposal",partOfSpeech:"名詞",meaning:"（ごみなどの）処分，廃棄",
   meanings:["名|（ごみなどの）処分，廃棄","名|（at one's disposal で）自由に使えること"],
   pronunciation:"/dɪˈspoʊzl/",part:174,
   example:"The city is changing its rules for garbage disposal next year.",
   exampleJa:"市は来年、ごみの処分のルールを変える予定だ。",
   example2:"The car is at your disposal while you stay here.",
   exampleJa2:"ここに滞在している間、その車は自由に使ってかまいません。",
   etymologyProcess:"dis（離れて）＋ pos（置く）＋ al（名詞）→ 離れた所へ置くと…？",
   etymologyConclusion:"dis（離れて）＋ pos（置く）＋ al（名詞）→ いらない物を手元から離れた所へ置くこと＝（ごみなどの）処分",
   relatedWords:[
     {word:"dispose",meaning:"（of ～を）処分する",breakdown:"dis（離れて）＋ pos（置く）→ 手元から離して置く"},
     {word:"propose",meaning:"提案する",breakdown:"pro（前へ）＋ pos（置く）→ 案を相手の前に差し出して置く"},
     {word:"position",meaning:"位置；立場",breakdown:"pos（置く）＋ ion（名詞）→ 置かれている場所"},
     {synonym:true,word:"removal",meaning:"除去",breakdown:"取り去ること。disposal は捨てて片づけること"}]},

  {id:1732,word:"scent",partOfSpeech:"名詞",meaning:"（よい）香り；（動物の）においの跡",
   meanings:["名|（よい）香り","名|（動物・人が残す）においの跡"],
   pronunciation:"/sent/",part:174,
   example:"The scent of roses filled the whole garden.",
   exampleJa:"バラの香りが、庭じゅうに広がっていた。",
   example2:"The police dog followed the thief's scent through the woods.",
   exampleJa2:"警察犬は、森を抜けて泥棒のにおいの跡を追った。",
   etymologyProcess:"scent（感じる）→ 鼻で感じ取るものは…？",
   etymologyConclusion:"scent（感じる）→ 鼻でふっと感じ取る心地よいにおい＝（よい）香り",
   why:"【なぜ】もとはラテン語 sentire「感じる」で、英語では最初 sent と書き、「においで感じ取る」という意味でした。17世紀ごろ、ascent（上昇）や descent（下降）などの綴りにつられて c が入り、今の scent の形になりました。においを感じ取ることから、香りそのものや、動物がたどるにおいの跡も指すようになりました。\n【つながり】sense（センス、感覚）や sensitive（敏感な）と同じ家族です。",
   relatedWords:[
     {word:"sense",meaning:"感覚；意味",breakdown:"sens（感じる）→ 感じ取ってわかること"},
     {word:"sensitive",meaning:"敏感な",breakdown:"sens（感じる）＋ itive（形容詞）→ わずかなことも感じ取る"},
     {synonym:true,word:"smell",meaning:"におい",breakdown:"においの全般。scent はよい香りやかすかなにおい"},
     {synonym:true,word:"fragrance",meaning:"芳香",breakdown:"花や香水の甘い香り。scent より上品な語"}]},

  {id:1733,word:"grain",partOfSpeech:"名詞",meaning:"穀物；（砂などの）粒",
   meanings:["名|穀物","名|（砂・塩などの）粒","名|（a grain of で）ほんの少し"],
   pronunciation:"/ɡreɪn/",part:174,
   example:"Rice is the main grain grown in this region.",
   exampleJa:"米は、この地域で育てられている主な穀物だ。",
   example2:"There is not a grain of truth in that rumor.",
   exampleJa2:"そのうわさには、ほんの少しの真実もない。",
   etymologyProcess:"gran（粒）→ 小さな粒がたくさん実ると…？",
   etymologyConclusion:"gran（粒）→ 小さな粒の実をたくさんつける作物＝穀物",
   relatedWords:[
     {word:"granite",meaning:"花こう岩",breakdown:"gran（粒）＋ ite（もの）→ 粒々が見える石"},
     {word:"granola",meaning:"グラノーラ",breakdown:"gran（粒）→ 穀物の粒を焼いて固めた食べ物"},
     {synonym:true,word:"cereal",meaning:"穀物；シリアル",breakdown:"食べる穀物全般。grain は一粒一粒にも使う"},
     {synonym:true,word:"particle",meaning:"微粒子",breakdown:"とても小さなかけら。grain は砂や塩の粒"}]},

  {id:1734,word:"wheat",partOfSpeech:"名詞",meaning:"小麦",
   meanings:["名|小麦"],
   pronunciation:"/wiːt/",part:174,
   example:"Bread and pasta are both made from wheat.",
   exampleJa:"パンもパスタも、小麦から作られる。",
   example2:"Farmers in this area grow wheat and potatoes.",
   exampleJa2:"この地域の農家は、小麦とじゃがいもを育てている。",
   etymologyProcess:"wheat（白いもの）→ ひくと白い粉になる穀物は…？",
   etymologyConclusion:"wheat（白いもの）→ ひくと白い粉になる穀物＝小麦",
   hook:"white（白い）と同じ家族。白い粉になる穀物＝小麦。パンやうどんのもと。",
   relatedWords:[
     {synonym:true,word:"white",meaning:"白い",breakdown:"wheat と同じ古英語の家族。小麦粉の色"},
     {synonym:true,word:"flour",meaning:"小麦粉",breakdown:"小麦をひいた粉。flower（花）と同じ発音"},
     {synonym:true,word:"barley",meaning:"大麦",breakdown:"ビールや麦茶の原料になる麦"},
     {synonym:true,word:"rice",meaning:"米",breakdown:"アジアの主食になる穀物"}]},

  {id:1735,word:"deforestation",partOfSpeech:"名詞",meaning:"森林伐採，森林破壊",
   meanings:["名|森林伐採，森林破壊"],
   pronunciation:"/diːˌfɔːrɪˈsteɪʃn/",part:174,
   example:"Deforestation is destroying the homes of many wild animals.",
   exampleJa:"森林伐採が、多くの野生動物のすみかを壊している。",
   example2:"We must stop the deforestation of the Amazon rain forest.",
   exampleJa2:"私たちはアマゾンの熱帯雨林の森林破壊を止めなければならない。",
   etymologyProcess:"de（離して）＋ forest（森）＋ ation（名詞）→ 土地から森を離すと…？",
   etymologyConclusion:"de（離して）＋ forest（森）＋ ation（名詞）→ 土地から森を切り離してなくすこと＝森林伐採",
   relatedWords:[
     {word:"forest",meaning:"森",breakdown:"forest（森）→ 木がたくさん生えている広い土地"},
     {word:"reforestation",meaning:"森林の再生，植林",breakdown:"re（再び）＋ forest（森）＋ ation（名詞）→ もう一度森にすること"},
     {word:"forestry",meaning:"林業",breakdown:"forest（森）＋ ry（～の仕事）→ 森を育てて木を切り出す仕事"},
     {synonym:true,word:"logging",meaning:"木材の切り出し",breakdown:"材木にするため木を切ること"}]},

  {id:1736,word:"drought",partOfSpeech:"名詞",meaning:"干ばつ，日照り",
   meanings:["名|干ばつ，日照り"],
   pronunciation:"/draʊt/",part:174,
   example:"The long drought killed most of the crops this summer.",
   exampleJa:"長い干ばつで、この夏は作物のほとんどが枯れた。",
   example2:"Many farmers lost their income because of the severe drought.",
   exampleJa2:"ひどい日照りのために、多くの農家が収入を失った。",
   etymologyProcess:"drought（乾き）→ 雨が降らず乾ききると…？",
   etymologyConclusion:"drought（乾き）→ 長く雨が降らず土地が乾ききること＝干ばつ",
   hook:"dry（乾いた）と同じ家族。発音は「ドラウト」で、gh は読まない。",
   relatedWords:[
     {synonym:true,word:"dry",meaning:"乾いた",breakdown:"drought と同じ古英語の家族。水気がない"},
     {synonym:true,word:"famine",meaning:"飢きん",breakdown:"食べ物が足りなくなること。干ばつが原因になることも多い"},
     {synonym:true,word:"shortage",meaning:"不足",breakdown:"足りないこと全般。drought は雨の不足"},
     {synonym:true,word:"heat wave",meaning:"熱波",breakdown:"何日も続く猛暑"}]},

  {id:1737,word:"irrigation",partOfSpeech:"名詞",meaning:"灌漑（田畑に水を引くこと）",
   meanings:["名|灌漑（かんがい），田畑に水を引くこと"],
   pronunciation:"/ˌɪrɪˈɡeɪʃn/",part:174,
   example:"Irrigation allows farmers to grow rice even in dry areas.",
   exampleJa:"灌漑のおかげで、乾いた地域でも農家は米を作れる。",
   example2:"The villagers built a new irrigation system to bring river water to their fields.",
   exampleJa2:"村人たちは、川の水を畑に引く新しい灌漑設備を作った。",
   etymologyProcess:"in（中へ）＋ rig（水をやる）＋ ation（名詞）→ 田畑の中へ水をやると…？",
   etymologyConclusion:"in（中へ）＋ rig（水をやる）＋ ation（名詞）→ 田畑の中へ水路で水を引き入れること＝灌漑",
   relatedWords:[
     {word:"irrigate",meaning:"（田畑に）水を引く",breakdown:"in（中へ）＋ rig（水をやる）＋ ate（動詞）→ 田畑に水を流しこむ"},
     {synonym:true,word:"water",meaning:"水をやる",breakdown:"植物に水をかけること全般"},
     {synonym:true,word:"canal",meaning:"運河，水路",breakdown:"人が掘った水の通り道。irrigation に使われる"},
     {synonym:true,word:"agriculture",meaning:"農業",breakdown:"作物を育てる仕事。irrigation はその大切な技術"}]},

  {id:1738,word:"spectacle",partOfSpeech:"名詞",meaning:"（壮大な）光景，見もの；めがね",
   meanings:["名|（壮大な）光景，見もの","名|（spectacles で）めがね"],
   pronunciation:"/ˈspektəkl/",part:174,
   example:"The fireworks over the lake were a wonderful spectacle.",
   exampleJa:"湖の上の花火は、すばらしい光景だった。",
   example2:"My grandfather needs his spectacles to read the newspaper.",
   exampleJa2:"祖父は、新聞を読むのにめがねが必要だ。",
   etymologyProcess:"spect（見る）＋ cle（もの）→ 見るためのものは…？",
   etymologyConclusion:"spect（見る）＋ cle（もの）→ 思わず目をみはって見るもの＝（壮大な）光景",
   relatedWords:[
     {word:"spectacular",meaning:"壮観な",breakdown:"spect（見る）＋ cle（もの）＋ ar（形容詞）→ 見ものになるほどすごい"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ ator（人）→ じっと見ている人"},
     {word:"inspect",meaning:"検査する",breakdown:"in（中へ）＋ spect（見る）→ 中までのぞきこんで調べる"},
     {synonym:true,word:"scene",meaning:"場面，光景",breakdown:"目の前の景色。spectacle は人目を引く見もの"}]},

  {id:1739,word:"altitude",partOfSpeech:"名詞",meaning:"高度，標高",
   meanings:["名|高度，標高","名|（altitudes で）高地"],
   pronunciation:"/ˈæltɪtuːd/",part:174,
   example:"The plane is now flying at an altitude of ten thousand meters.",
   exampleJa:"その飛行機は今、高度1万メートルを飛んでいる。",
   example2:"It is hard to breathe at high altitudes.",
   exampleJa2:"標高の高い所では、息をするのが苦しい。",
   etymologyProcess:"alt（高い）＋ tude（名詞）→ どれだけ高いかは…？",
   etymologyConclusion:"alt（高い）＋ tude（名詞）→ 海面からどれだけ高いかということ＝高度",
   relatedWords:[
     {word:"exalt",meaning:"高める，たたえる",breakdown:"ex（外へ）＋ alt（高い）→ 高く持ち上げてほめたたえる"},
     {word:"alto",meaning:"アルト",breakdown:"alt（高い）→ 男声より高い声部。今は女声の低いほう"},
     {synonym:true,word:"height",meaning:"高さ",breakdown:"物の高さ全般。altitude は海面からの高さ"},
     {synonym:true,word:"elevation",meaning:"標高",breakdown:"e（外へ）＋ lev（持ち上げる）。土地の高さ"}]},

  {id:1740,word:"catastrophe",partOfSpeech:"名詞",meaning:"大災害；大失敗",
   meanings:["名|大災害，大惨事","名|大失敗，ひどい出来事"],
   pronunciation:"/kəˈtæstrəfi/",part:174,
   example:"The earthquake was the worst catastrophe in the country's history.",
   exampleJa:"その地震は、国の歴史で最悪の大災害だった。",
   example2:"Forgetting my passport at the airport would be a total catastrophe.",
   exampleJa2:"空港でパスポートを忘れたら、とんでもない大失敗だ。",
   etymologyProcess:"cata（下へ）＋ strophe（向き）→ 向きが下へひっくり返ると…？",
   etymologyConclusion:"cata（下へ）＋ strophe（向き）→ 物事が下へひっくり返るほどの出来事＝大災害",
   why:"【なぜ】ギリシャ語 katastrophē は「ひっくり返ること」。古代ギリシャの劇では、物語が一気にひっくり返って終わる場面を指し、悲劇では主人公の破滅でした。そこから、すべてがひっくり返るような大きな不幸＝大災害を意味するようになりました。\n【つながり】apostrophe（アポストロフィ）も strophe（向き）の家族です。",
   relatedWords:[
     {word:"apostrophe",meaning:"アポストロフィ（'）",breakdown:"apo（離れて）＋ strophe（向き）→ 文字をわきへ向けて省いたしるし"},
     {word:"catastrophic",meaning:"壊滅的な",breakdown:"cata（下へ）＋ strophe（向き）＋ ic（形容詞）→ すべてがひっくり返るような"},
     {synonym:true,word:"disaster",meaning:"災害，大惨事",breakdown:"不幸な大事件。catastrophe はさらに大きく取り返しがつかない"},
     {synonym:true,word:"tragedy",meaning:"悲劇",breakdown:"悲しい出来事や劇。catastrophe は被害の大きさに重点"}]},

  {id:1741,word:"wilderness",partOfSpeech:"名詞",meaning:"荒野，原野",
   meanings:["名|荒野，原野（人が住まない自然のままの土地）"],
   pronunciation:"/ˈwɪldərnəs/",part:175,
   example:"They spent a week camping in the Canadian wilderness.",
   exampleJa:"彼らは、カナダの荒野で1週間キャンプをして過ごした。",
   example2:"Bears still live freely in the wilderness of Hokkaido.",
   exampleJa2:"北海道の原野では、今もクマが自由に暮らしている。",
   etymologyProcess:"wilder（野の獣）＋ ness（名詞）→ 野の獣だけがいる所は…？",
   etymologyConclusion:"wilder（野の獣）＋ ness（名詞）→ 人が住まず野の獣だけがいる土地＝荒野",
   why:"【なぜ】wilderness の wilder は、古英語 wilddeor「野生の獣」が縮まった形です。deor は今の deer（シカ）のもとで、昔は獣全般を指しました。つまり wilderness は「野の獣たちのすむ場所」で、人の手が入っていない荒れた土地を表すようになりました。\n【つながり】wild（野生の）、wildlife（野生生物）と同じ家族です。",
   relatedWords:[
     {word:"wild",meaning:"野生の；荒々しい",breakdown:"wild（野生の）→ 人の手がまったく入っていない"},
     {word:"wildlife",meaning:"野生生物",breakdown:"wild（野生の）＋ life（命）→ 自然のままに生きる動植物"},
     {synonym:true,word:"desert",meaning:"砂漠",breakdown:"雨が少なく乾いた土地。wilderness は森や山も含む"},
     {synonym:true,word:"nature",meaning:"自然",breakdown:"自然全般。wilderness は人の手が入っていない土地"}]},

  {id:1742,word:"decay",partOfSpeech:"自動詞",meaning:"（ゆっくり）朽ちる，腐敗する；衰える",
   meanings:["自|（ゆっくり）朽ちる，腐敗する","自|衰える","名|腐敗；虫歯；衰退"],
   pronunciation:"/dɪˈkeɪ/",part:175,
   example:"Fallen leaves slowly decay and become part of the soil.",
   exampleJa:"落ち葉はゆっくり朽ちて、土の一部になる。",
   example2:"Eating too much sugar can cause tooth decay.",
   exampleJa2:"砂糖をとりすぎると、虫歯になることがある。",
   etymologyProcess:"de（下へ）＋ cay（落ちる）→ 下へ落ちていくと…？",
   etymologyConclusion:"de（下へ）＋ cay（落ちる）→ 元の形から少しずつ下へ崩れ落ちる＝（ゆっくり）朽ちる",
   relatedWords:[
     {word:"accident",meaning:"事故",breakdown:"ad（～へ）＋ cid（落ちる）＋ ent（もの）→ 思いがけず降りかかる出来事"},
     {word:"occasion",meaning:"機会，時",breakdown:"oc（～に向かって）＋ cad（落ちる）→ 巡り合わせが訪れる時"},
     {word:"incident",meaning:"出来事，事件",breakdown:"in（上に）＋ cid（落ちる）＋ ent（もの）→ 身の上に降りかかったこと"},
     {synonym:true,word:"rot",meaning:"腐る",breakdown:"ぐずぐずに腐る。decay は時間をかけて崩れていく"}]},

  {id:1743,word:"erosion",partOfSpeech:"名詞",meaning:"浸食；（信頼などの）低下",
   meanings:["名|（水・風による）浸食","名|（信頼・権利などの）低下，衰え"],
   pronunciation:"/ɪˈroʊʒn/",part:175,
   example:"Trees and grass help protect the hillside from soil erosion.",
   exampleJa:"木や草は、丘の斜面を土の浸食から守るのに役立つ。",
   example2:"The scandal led to an erosion of trust in the government.",
   exampleJa2:"その不祥事で、政府への信頼が低下した。",
   etymologyProcess:"e（外へ）＋ ros（かじる）＋ ion（名詞）→ 少しずつかじり取ると…？",
   etymologyConclusion:"e（外へ）＋ ros（かじる）＋ ion（名詞）→ 水や風が土地を少しずつかじり取ること＝浸食",
   relatedWords:[
     {word:"erode",meaning:"浸食する",breakdown:"e（外へ）＋ rod（かじる）→ 少しずつかじって削り取る"},
     {word:"rodent",meaning:"げっ歯類（ネズミなど）",breakdown:"rod（かじる）＋ ent（もの）→ 物をかじる動物"},
     {synonym:true,word:"wear",meaning:"すり減る",breakdown:"使って少しずつ減る。erosion は自然の力で削られる"},
     {synonym:true,word:"decline",meaning:"低下",breakdown:"だんだん下がること。erosion は少しずつ削られるように"}]},

  {id:1744,word:"flame",partOfSpeech:"名詞",meaning:"炎",
   meanings:["名|炎","名|（in flames で）燃えて"],
   pronunciation:"/fleɪm/",part:175,
   example:"The flame of the candle moved gently in the wind.",
   exampleJa:"ろうそくの炎が、風にゆらゆらと揺れた。",
   example2:"The old wooden house was soon in flames after the lightning.",
   exampleJa2:"雷が落ちたあと、その古い木造の家はすぐに炎に包まれた。",
   etymologyProcess:"flam（炎）→ ゆらゆら燃え上がるものは…？",
   etymologyConclusion:"flam（炎）→ ゆらゆらと燃え上がる火の先＝炎",
   relatedWords:[
     {word:"flamingo",meaning:"フラミンゴ",breakdown:"flam（炎）→ 炎のように赤い羽を持つ鳥"},
     {word:"flammable",meaning:"燃えやすい",breakdown:"flam（炎）＋ able（できる）→ すぐに炎が上がる"},
     {synonym:true,word:"fire",meaning:"火，火事",breakdown:"火全般。flame は燃えている炎の部分"},
     {synonym:true,word:"blaze",meaning:"燃え立つ炎",breakdown:"勢いよく燃え上がる大きな炎"}]},

  {id:1745,word:"galaxy",partOfSpeech:"名詞",meaning:"銀河",
   meanings:["名|銀河","名|（the Galaxy で）天の川銀河"],
   pronunciation:"/ˈɡæləksi/",part:175,
   example:"Scientists say our galaxy contains hundreds of billions of stars.",
   exampleJa:"科学者によると、私たちの銀河には何千億もの星がある。",
   example2:"The telescope took a clear picture of a distant galaxy.",
   exampleJa2:"その望遠鏡は、遠くの銀河の鮮明な写真を撮った。",
   etymologyProcess:"galax（ミルク）→ 夜空に流れるミルクのような帯は…？",
   etymologyConclusion:"galax（ミルク）→ 夜空にミルクをこぼしたように見える星の集まり＝銀河",
   hook:"天の川は英語で Milky Way。galaxy も「ミルク」から。",
   why:"【なぜ】ギリシャ語 galaxias は「乳のような」という意味で、もとは夜空に白く流れる帯、つまり天の川だけを指す名前でした。のちに望遠鏡で、その白い帯が無数の星の集まりだと分かり、宇宙にある同じような星の大集団もすべて galaxy と呼ぶようになりました。\n【つながり】スマホの「ギャラクシー」もこの語です。",
   relatedWords:[
     {synonym:true,word:"universe",meaning:"宇宙",breakdown:"すべてをふくむ宇宙全体。galaxy はその中の星の集団"},
     {synonym:true,word:"star",meaning:"星",breakdown:"一つ一つの星。galaxy は何千億もの星の集まり"},
     {synonym:true,word:"planet",meaning:"惑星",breakdown:"恒星の周りを回る星。地球も planet"},
     {synonym:true,word:"space",meaning:"宇宙空間",breakdown:"地球の外に広がる空間"}]},

  {id:1746,word:"chill",partOfSpeech:"名詞",meaning:"（ひんやりした）冷え，寒気；冷やす",
   meanings:["名|（ひんやりした）冷え，寒気","名|（恐怖で）ぞっとする感じ","他|冷やす"],
   pronunciation:"/tʃɪl/",part:175,
   example:"There was a chill in the air early this morning.",
   exampleJa:"今朝は早い時間、空気がひんやりしていた。",
   example2:"Please chill the drinks before the party starts.",
   exampleJa2:"パーティーが始まる前に、飲み物を冷やしておいてね。",
   etymologyProcess:"chill（冷たい）→ ひんやりした空気を感じると…？",
   etymologyConclusion:"chill（冷たい）→ 肌にひんやり感じる冷たさ＝（ひんやりした）冷え",
   hook:"cold・cool と同じ家族。「チルする」は熱を冷ましてのんびりすること。",
   relatedWords:[
     {synonym:true,word:"cold",meaning:"寒い，冷たい",breakdown:"chill と同じ古英語の家族。寒さ全般"},
     {synonym:true,word:"cool",meaning:"涼しい；冷ます",breakdown:"chill と同じ家族。心地よい涼しさ"},
     {synonym:true,word:"freeze",meaning:"凍る",breakdown:"水が氷になるほど冷える"},
     {synonym:true,word:"shiver",meaning:"震える",breakdown:"寒さや恐怖でぶるぶる震える"}]},

  {id:1747,word:"thermal",partOfSpeech:"形容詞",meaning:"熱の，熱による；保温性の",
   meanings:["形|熱の，熱による","形|（衣類が）保温性の"],
   pronunciation:"/ˈθɜːrml/",part:175,
   example:"Iceland makes good use of thermal energy from under the ground.",
   exampleJa:"アイスランドは、地下からの熱エネルギーをうまく利用している。",
   example2:"I wore thermal underwear to stay warm during the ski trip.",
   exampleJa2:"スキー旅行の間、暖かく過ごすために保温性の下着を着た。",
   etymologyProcess:"thermo（熱）＋ al（形容詞）→ 熱に関わると…？",
   etymologyConclusion:"thermo（熱）＋ al（形容詞）→ 熱に関わる、熱を生む＝熱の",
   relatedWords:[
     {word:"thermometer",meaning:"温度計",breakdown:"thermo（熱）＋ metr（測る）→ 熱の高さを測るための道具"},
     {word:"thermos",meaning:"魔法びん",breakdown:"thermo（熱）→ 中の熱を逃がさない入れ物"},
     {synonym:true,word:"hot",meaning:"熱い",breakdown:"温度が高いこと。thermal は熱に関する"},
     {synonym:true,word:"warm",meaning:"暖かい",breakdown:"ほどよく温かい。thermal wear は暖かさを保つ服"}]},

  {id:1748,word:"fertile",partOfSpeech:"形容詞",meaning:"（土地が）肥えた，肥沃な；豊かな",
   meanings:["形|（土地が）肥えた，肥沃な","形|（想像力などが）豊かな","形|繁殖力のある"],
   pronunciation:"/ˈfɜːrtl/",part:175,
   example:"The land near the river is very fertile.",
   exampleJa:"川の近くの土地は、とても肥えている。",
   example2:"She has a fertile imagination and writes great stories.",
   exampleJa2:"彼女は想像力が豊かで、すばらしい物語を書く。",
   etymologyProcess:"fer（運ぶ）＋ ile（できる）→ 実りをたくさん運べると…？",
   etymologyConclusion:"fer（運ぶ）＋ ile（できる）→ 実りをどんどん運んでくれる＝（土地が）肥えた",
   relatedWords:[
     {word:"fertilizer",meaning:"肥料",breakdown:"fer（運ぶ）＋ ile（できる）＋ izer（もの）→ 土地を実り多くするもの"},
     {word:"offer",meaning:"申し出る",breakdown:"of（相手のほうへ）＋ fer（運ぶ）→ 相手の前へ持っていく"},
     {word:"transfer",meaning:"移す；乗り換える",breakdown:"trans（越えて）＋ fer（運ぶ）→ 境を越えて別の場所へ運ぶ"},
     {synonym:true,word:"rich",meaning:"豊かな；（土が）肥えた",breakdown:"栄養がたっぷりある。fertile は作物がよく育つ"}]},

  {id:1749,word:"fossil",partOfSpeech:"名詞",meaning:"化石；化石の",
   meanings:["名|化石","形|化石の，化石化した"],
   pronunciation:"/ˈfɑːsl/",part:175,
   example:"We found a fossil of a small fish in the rock.",
   exampleJa:"私たちは、岩の中に小さな魚の化石を見つけた。",
   example2:"Most of our electricity still comes from fossil fuels like coal.",
   exampleJa2:"私たちの電気の多くは、今も石炭のような化石燃料から作られている。",
   etymologyProcess:"foss（掘る）＋ il（～の）→ 地面から掘り出されたものは…？",
   etymologyConclusion:"foss（掘る）＋ il（～の）→ 地面から掘り出された大昔の生き物の跡＝化石",
   relatedWords:[
     {word:"fossilize",meaning:"化石になる",breakdown:"foss（掘る）＋ il（～の）＋ ize（動詞）→ 化石になる"},
     {synonym:true,word:"bone",meaning:"骨",breakdown:"体を支える骨。fossil は骨などが石になったもの"},
     {synonym:true,word:"remains",meaning:"遺骸，遺跡",breakdown:"残されたもの。fossil は石になって残ったもの"},
     {synonym:true,word:"dinosaur",meaning:"恐竜",breakdown:"大昔の巨大なは虫類。化石から姿が分かる"}]},

  {id:1750,word:"exploit",partOfSpeech:"他動詞",meaning:"（資源を）開発する，最大限に活用する；搾取する",
   meanings:["他|（資源などを）開発する，最大限に活用する","他|（人を）不当に利用する，搾取する"],
   pronunciation:"/ɪkˈsplɔɪt/",part:175,
   example:"The company wants to exploit the oil under the sea.",
   exampleJa:"その会社は、海底の石油を開発したいと考えている。",
   example2:"Some factories exploit workers by paying them very little.",
   exampleJa2:"賃金をほとんど払わずに、労働者を搾取している工場もある。",
   etymologyProcess:"ex（外へ）＋ ploit（折る）→ たたんだものを外へ広げると…？",
   etymologyConclusion:"ex（外へ）＋ ploit（折る）→ 眠っている力を外へ広げて使い切る＝（資源を）開発する",
   why:"【なぜ】ラテン語 explicare は「折りたたみを広げる」。古いフランス語では「やりとげる」、そこから「手柄・偉業」という意味になりました。英語では、あるものの力を広げて最大限に役立てる＝開発する・活用するになり、さらに人の弱みまで利用する「搾取する」という悪い意味も生まれました。\n【つながり】explicit（明確な）、display（展示する）も「折る」の家族です。",
   relatedWords:[
     {word:"explicit",meaning:"明確な",breakdown:"ex（外へ）＋ plic（折る）→ 折りたたみを開いてはっきりさせた"},
     {word:"display",meaning:"展示する",breakdown:"dis（バラバラに）＋ pli（折る）→ たたんだ布を広げて見せる"},
     {word:"employ",meaning:"雇う；用いる",breakdown:"em（中へ）＋ ploy（折る）→ 中に包みこんで使う"},
     {synonym:true,word:"utilize",meaning:"利用する",breakdown:"役立つように使う。exploit は最大限に引き出す"}]},
