  {id:2201,word:"artifact",partOfSpeech:"名詞",meaning:"（昔の人が作った）遺物，工芸品",
   meanings:["名|（昔の人が作った）遺物，工芸品","名|（ある文化・時代の）産物"],
   pronunciation:"/ˈɑːrtɪfækt/",part:221,
   example:"The museum displays artifacts found in an ancient Egyptian tomb.",
   exampleJa:"その博物館は、古代エジプトの墓で見つかった遺物を展示している。",
   example2:"Old school textbooks are artifacts that show how people once lived.",
   exampleJa2:"古い学校の教科書は、人々がかつてどう暮らしていたかを示す産物だ。",
   etymologyProcess:"art（技）＋ fact（作る）→ 技を使って人の手で作ると…？",
   etymologyConclusion:"art（技）＋ fact（作る）→ 人が技を使って作り、後の時代まで残ったもの＝（昔の人が作った）遺物，工芸品",
   etymologyMore:["人の手で作ったものは時代を映す→（ある文化・時代の）産物"],
   relatedWords:[
     {word:"artificial",meaning:"人工的な",breakdown:"art（技）＋ fic（作る）＋ ial（形容詞）→ 自然でなく技で作った"},
     {word:"artist",meaning:"芸術家",breakdown:"art（技）＋ ist（人）→ 技を身につけて作品を生み出す人"},
     {word:"factory",meaning:"工場",breakdown:"fact（作る）＋ ory（場所）→ ものを作る場所"},
     {word:"manufacture",meaning:"製造する",breakdown:"manu（手）＋ fact（作る）＋ ure（名詞）→ 手で作る"}]},

  {id:2202,word:"token",partOfSpeech:"名詞",meaning:"（気持ちなどの）しるし，証",
   meanings:["名|（気持ちなどの）しるし，証","名|（ゲーム・機械用の）代用硬貨，引換券","形|形だけの，名ばかりの"],
   pronunciation:"/ˈtoʊkən/",part:221,
   example:"Please accept this small gift as a token of our thanks.",
   exampleJa:"感謝のしるしとして、このささやかな贈り物を受け取ってください。",
   example2:"We bought some tokens to play the games at the arcade.",
   exampleJa2:"私たちはゲームセンターで遊ぶために代用硬貨を何枚か買った。",
   etymologyProcess:"token（しるし）→ 目に見える形で示すと…？",
   etymologyConclusion:"token（しるし）→ 目に見えない気持ちを、形あるもので示す＝（気持ちなどの）しるし，証",
   etymologyMore:["お金のしるしとして使う札→（ゲーム・機械用の）代用硬貨，引換券","しるしだけで中身がない→形だけの，名ばかりの"],
   hook:"teach（教える）と同じ古英語の家族で「指し示すもの」。a token of ～（～のしるし）の形で覚える。",
   relatedWords:[
     {synonym:true,word:"teach",meaning:"教える",breakdown:"token と同じ古英語の家族。指し示して分からせる"},
     {synonym:true,word:"sign",meaning:"しるし；兆候",breakdown:"何かを示すもの全般。token は気持ちを形にしたもの"},
     {synonym:true,word:"symbol",meaning:"象徴",breakdown:"考えを代わりに表す形。token は小さな証の品"},
     {synonym:true,word:"gift",meaning:"贈り物",breakdown:"贈るもの全般。token は気持ちを伝える小さな品"}]},

  {id:2203,word:"cue",partOfSpeech:"名詞",meaning:"（行動を始める）合図，きっかけ",
   meanings:["名|（行動を始める）合図，きっかけ","名|手がかり","他|合図を出す"],
   pronunciation:"/kjuː/",part:221,
   example:"The actor waited for his cue before walking onto the stage.",
   exampleJa:"その俳優は、舞台に出ていく前に合図を待った。",
   example2:"When the teacher nodded, that was our cue to start singing.",
   exampleJa2:"先生がうなずいたら、それが私たちが歌い始める合図だった。",
   etymologyProcess:"cue（役者への合図）→ 舞台で出番を知らせると…？",
   etymologyConclusion:"cue（役者への合図）→ 舞台で「次はあなたの番」と知らせるもの＝（行動を始める）合図，きっかけ",
   etymologyMore:["次にどうするかを知らせる→手がかり"],
   hook:"語源ははっきりしないが、台本の q（ラテン語 quando＝いつ）の略という説がある。テレビの「キュー」。",
   relatedWords:[
     {synonym:true,word:"signal",meaning:"信号，合図",breakdown:"光や音などで知らせるもの。cue は動き出すタイミングの合図"},
     {synonym:true,word:"sign",meaning:"しるし；兆候",breakdown:"何かを示すもの全般。cue は「今だ」と知らせる"},
     {synonym:true,word:"hint",meaning:"ヒント",breakdown:"答えに近づくための手がかり。cue は行動のきっかけ"},
     {synonym:true,word:"clue",meaning:"（謎を解く）手がかり",breakdown:"つづりが似ているが別の語。糸玉から「解く手がかり」"}]},

  {id:2204,word:"quest",partOfSpeech:"名詞",meaning:"（長く困難な）探求，追求",
   meanings:["名|（長く困難な）探求，追求","自|探し求める"],
   pronunciation:"/kwest/",part:221,
   example:"The knights set out on a quest to find the lost treasure.",
   exampleJa:"騎士たちは、失われた宝を見つける探求の旅に出た。",
   example2:"Our club's quest for the national title continues this year.",
   exampleJa2:"全国優勝を目指す私たちの部の追求は、今年も続く。",
   etymologyProcess:"quest（求める）→ 大切なものを求めて旅を続けると…？",
   etymologyConclusion:"quest（求める）→ 大切なものを求めて長い旅を続ける＝（長く困難な）探求，追求",
   relatedWords:[
     {word:"question",meaning:"質問",breakdown:"quest（求める）＋ ion（名詞）→ 答えを求めて投げかける言葉"},
     {word:"request",meaning:"頼む；依頼",breakdown:"re（再び）＋ quest（求める）→ くり返し求めてお願いする"},
     {word:"conquer",meaning:"征服する",breakdown:"con（すっかり）＋ quer（求める）→ 求めたものをすっかり手に入れる"},
     {word:"inquire",meaning:"たずねる",breakdown:"in（中へ）＋ quire（求める）→ 中の事情を求めて問う"}]},

  {id:2205,word:"melancholy",partOfSpeech:"名詞",meaning:"（もの悲しい）憂うつ，ふさぎこみ",
   meanings:["名|（もの悲しい）憂うつ，ふさぎこみ","形|もの悲しい，憂うつな"],
   pronunciation:"/ˈmelənkɑːli/",part:221,
   example:"A deep melancholy came over him as autumn turned to winter.",
   exampleJa:"秋が冬へと変わるにつれて、深い憂うつが彼をおそった。",
   example2:"The band played a melancholy song at the end of the school festival.",
   exampleJa2:"文化祭の最後に、バンドはもの悲しい曲を演奏した。",
   etymologyProcess:"melan（黒い）＋ chol（胆汁）→ 体に黒い液がたまると…？",
   etymologyConclusion:"melan（黒い）＋ chol（胆汁）→ 黒い胆汁が増えると心が沈むと考えられた＝（もの悲しい）憂うつ，ふさぎこみ",
   why:"【なぜ】古代ギリシャの医学では、体には4種類の液が流れていて、そのつり合いで気分や性格が決まると考えられていました。黒い胆汁が多すぎると気分が暗く沈むとされたため、「黒い胆汁」という病気の名前が、そのまま「憂うつ」を表す語になりました。\n【つながり】melanin（メラニン）は肌を黒くする色素、cholesterol（コレステロール）は胆石から見つかった物質です。",
   relatedWords:[
     {word:"melanin",meaning:"メラニン（色素）",breakdown:"melan（黒い）→ 肌や髪を黒っぽくする色素"},
     {word:"cholesterol",meaning:"コレステロール",breakdown:"chol（胆汁）→ 胆石の中から最初に見つかった物質"},
     {synonym:true,word:"sad",meaning:"悲しい",breakdown:"悲しい気持ち全般。melancholy は理由なく長く沈む感じ"},
     {synonym:true,word:"blue",meaning:"気分が沈んだ",breakdown:"会話でよく使う「ブルーな」。melancholy はより深く文学的"}]},

  {id:2206,word:"self-esteem",partOfSpeech:"名詞",meaning:"自尊心，自己肯定感",
   meanings:["名|自尊心，自己肯定感"],
   pronunciation:"/ˌself ɪˈstiːm/",part:221,
   example:"Kind words from her coach helped build up her self-esteem.",
   exampleJa:"コーチからの優しい言葉が、彼女の自尊心を高めるのに役立った。",
   example2:"People with low self-esteem often find it hard to accept praise.",
   exampleJa2:"自己肯定感が低い人は、ほめ言葉を素直に受け取るのが難しいことが多い。",
   etymologyProcess:"self（自分）＋ estim（値ぶみする）→ 自分の値打ちを見積もると…？",
   etymologyConclusion:"self（自分）＋ estim（値ぶみする）→ 自分自身を価値あるものと値ぶみする気持ち＝自尊心，自己肯定感",
   spelling:"estim→esteem（フランス語を通って変化）",
   relatedWords:[
     {word:"estimate",meaning:"見積もる",breakdown:"estim（値ぶみする）＋ ate（動詞）→ だいたいの値打ちや量を見積もる"},
     {word:"aim",meaning:"狙う；目標",breakdown:"aim（値ぶみする）→ 距離を見積もって狙いを定める"},
     {word:"selfless",meaning:"私心のない",breakdown:"self（自分）＋ less（ない）→ 自分のことを勘定に入れない"},
     {synonym:true,word:"confidence",meaning:"自信",breakdown:"できると信じる気持ち。self-esteem は自分の価値を認める気持ち"}]},

  {id:2207,word:"empathy",partOfSpeech:"名詞",meaning:"（相手の立場に立った）共感，感情移入",
   meanings:["名|（相手の立場に立った）共感，感情移入"],
   pronunciation:"/ˈempəθi/",part:221,
   example:"Good nurses show empathy for patients who are in pain.",
   exampleJa:"よい看護師は、痛みに苦しむ患者に共感を示す。",
   example2:"Reading novels can help young people develop empathy for others.",
   exampleJa2:"小説を読むことは、若者が他人への共感を育てる助けになりうる。",
   etymologyProcess:"em（中へ）＋ path（感じる）→ 相手の心の中に入って感じると…？",
   etymologyConclusion:"em（中へ）＋ path（感じる）→ 相手の心の中に入り、その気持ちを自分も感じる＝（相手の立場に立った）共感，感情移入",
   relatedWords:[
     {word:"sympathy",meaning:"同情",breakdown:"sym（共に）＋ path（感じる）→ 相手と同じ気持ちを共に感じる"},
     {word:"telepathy",meaning:"テレパシー",breakdown:"tele（遠く）＋ path（感じる）→ 離れた相手の心を感じ取る"},
     {word:"pathetic",meaning:"哀れな",breakdown:"path（感じる）＋ etic（～の）→ 見る人に悲しみを感じさせる"},
     {synonym:true,word:"understanding",meaning:"理解，思いやり",breakdown:"相手の事情を分かること。empathy は気持ちまで感じ取る"}]},

  {id:2208,word:"precaution",partOfSpeech:"名詞",meaning:"（万一に備えた）予防策，用心",
   meanings:["名|（万一に備えた）予防策，用心"],
   pronunciation:"/prɪˈkɔːʃn/",part:221,
   example:"Wash your hands often as a precaution against catching a cold.",
   exampleJa:"かぜの予防策として、こまめに手を洗いなさい。",
   example2:"The school took extra precautions before the typhoon arrived.",
   exampleJa2:"台風が来る前に、学校は追加の予防策を講じた。",
   usage:["as a precaution against 事（事への予防策として）","take precautions（予防策を講じる）"],
   etymologyProcess:"pre（先に）＋ caut（用心する）→ 何か起きる前に用心すると…？",
   etymologyConclusion:"pre（先に）＋ caut（用心する）＋ ion（名詞）→ 何か起きる前に先に用心しておくこと＝（万一に備えた）予防策，用心",
   relatedWords:[
     {word:"caution",meaning:"用心，注意",breakdown:"caut（用心する）＋ ion（名詞）→ 危険に気をつけること"},
     {word:"cautious",meaning:"用心深い",breakdown:"caut（用心する）＋ ous（～に満ちた）→ 用心する気持ちでいっぱい"},
     {word:"prevent",meaning:"防ぐ",breakdown:"pre（先に）＋ vent（来る）→ 先回りして来るものをさえぎる"},
     {word:"prepare",meaning:"準備する",breakdown:"pre（先に）＋ pare（整える）→ 前もって整えておく"}]},

  {id:2209,word:"distress",partOfSpeech:"名詞",meaning:"（心身の）苦痛，苦悩",
   meanings:["名|（心身の）苦痛，苦悩","名|（船などの）遭難，危難","他|苦しめる，悩ませる"],
   pronunciation:"/dɪˈstres/",part:221,
   example:"The loud fireworks caused great distress to the animals at the zoo.",
   exampleJa:"大きな花火の音は、動物園の動物たちに大きな苦痛を与えた。",
   example2:"The coast guard rescued a fishing boat in distress last night.",
   exampleJa2:"昨夜、沿岸警備隊が遭難した漁船を救助した。",
   etymologyProcess:"di（離れて）＋ stress（締めつける）→ 強く締めつけられると…？",
   etymologyConclusion:"di（離れて）＋ stress（締めつける）→ 引き裂かれるように強く締めつけられて苦しい＝（心身の）苦痛，苦悩",
   etymologyMore:["締めつけられて身動きがとれない→（船などの）遭難，危難"],
   relatedWords:[
     {word:"stress",meaning:"ストレス；強調する",breakdown:"stress（締めつける）→ 心や体をぎゅっと締めつける力"},
     {word:"strict",meaning:"厳しい",breakdown:"strict（締めつける）→ 規則でぎゅっと締めつける"},
     {word:"district",meaning:"地区",breakdown:"di（離れて）＋ strict（締めつける）→ 区切って支配した地域"},
     {word:"restrict",meaning:"制限する",breakdown:"re（後ろへ）＋ strict（締めつける）→ 締めつけて引き戻す"}]},

  {id:2210,word:"apprehension",partOfSpeech:"名詞",meaning:"（先のことへの）不安，気がかり",
   meanings:["名|（先のことへの）不安，気がかり","名|理解（力）","名|逮捕"],
   pronunciation:"/ˌæprɪˈhenʃn/",part:221,
   example:"She felt some apprehension about her first job interview.",
   exampleJa:"彼女は初めての就職面接に、いくらか不安を感じていた。",
   example2:"There is growing apprehension among students about the new exam system.",
   exampleJa2:"新しい入試制度について、生徒の間で不安が高まっている。",
   etymologyProcess:"ap（～へ）＋ prehend（つかむ）→ 先のことを心でつかむと…？",
   etymologyConclusion:"ap（～へ）＋ prehend（つかむ）＋ ion（名詞）→ まだ来ない先のことを心でつかんで気にする＝（先のことへの）不安，気がかり",
   spelling:"prehend→prehens（ラテン語の過去分詞の形）",
   why:"【なぜ】ラテン語 apprehendere は「つかまえる」。そこから、犯人をつかまえる「逮捕」と、頭で物事をつかむ「理解」の意味が生まれました。さらに、これから起こりそうな悪いことを先回りして心でつかみ、あれこれ思い浮かべてしまう気持ち＝「不安」の意味が広がりました。\n【つながり】comprehend（理解する）、prison（刑務所）も「つかむ」の家族です。",
   etymologyMore:["犯人をつかまえる→逮捕","頭でしっかりつかむ→理解（力）"],
   relatedWords:[
     {word:"comprehend",meaning:"理解する",breakdown:"com（すっかり）＋ prehend（つかむ）→ 内容をすっかりつかむ"},
     {word:"prison",meaning:"刑務所",breakdown:"pris（つかむ）→ つかまえた人を入れておく場所"},
     {word:"surprise",meaning:"驚かせる",breakdown:"sur（上から）＋ pris（つかむ）→ 上から不意につかみかかる"},
     {synonym:true,word:"anxiety",meaning:"不安，心配",breakdown:"心配な気持ち全般。apprehension は先の出来事への不安"}]},

  {id:2211,word:"scorn",partOfSpeech:"名詞",meaning:"（見下した）軽蔑，あざけり",
   meanings:["名|（見下した）軽蔑，あざけり","他|軽蔑する，はねつける"],
   pronunciation:"/skɔːrn/",part:222,
   example:"She looked at the cheaters with scorn and walked away.",
   exampleJa:"彼女はずるをした人たちを軽蔑して見て、立ち去った。",
   example2:"He scorned our advice and made the same mistake again.",
   exampleJa2:"彼は私たちの忠告をはねつけ、また同じ失敗をした。",
   etymologyProcess:"scorn（あざける）→ 相手を笑いものにすると…？",
   etymologyConclusion:"scorn（あざける）→ 相手を下に見て笑いものにする気持ち＝（見下した）軽蔑，あざけり",
   hook:"ゲルマン語の「あざける」がフランス語を通って入った語。pour scorn on ～（～をあざける）。",
   relatedWords:[
     {synonym:true,word:"laugh",meaning:"笑う",breakdown:"laugh at ～で「～をあざ笑う」。scorn は見下す気持ちが強い"},
     {synonym:true,word:"insult",meaning:"侮辱する",breakdown:"言葉や態度で傷つける。scorn は心の中の見下し"},
     {synonym:true,word:"contempt",meaning:"軽蔑",breakdown:"価値がないと見下すこと。scorn はあざけりが加わる"},
     {synonym:true,word:"mock",meaning:"からかう，ばかにする",breakdown:"まねをして笑いものにする。scorn は冷たく見下す"}]},

  {id:2212,word:"menace",partOfSpeech:"名詞",meaning:"（社会・人への）脅威，危険な存在",
   meanings:["名|（社会・人への）脅威，危険な存在","名|厄介者","他|おびやかす"],
   pronunciation:"/ˈmenəs/",part:222,
   example:"Drunk drivers are a menace to everyone on the road.",
   exampleJa:"飲酒運転をする人は、道路にいるすべての人にとって脅威だ。",
   example2:"Rising sea levels menace many small islands in the Pacific.",
   exampleJa2:"海面の上昇は、太平洋の多くの小さな島々をおびやかしている。",
   etymologyProcess:"menac（突き出る）→ 頭上に岩が突き出ていると…？",
   etymologyConclusion:"menac（突き出る）→ 頭上に突き出た岩のように身に迫る危険＝（社会・人への）脅威，危険な存在",
   etymologyMore:["まわりを困らせる危ない存在→厄介者"],
   why:"【なぜ】ラテン語 minae はもともと「突き出たもの」、特に頭上に張り出した岩や城壁の先を指し、そこから「脅し」の意味でも使われました。いつ落ちてくるか分からない岩のように、身に迫って人をおびやかすもの＝脅威・危険な存在を表すようになりました。\n【つながり】prominent（目立つ）、eminent（すぐれた）も「突き出る」の家族です。",
   hook:"a menace to ～（～にとっての脅威）の形でよく使う。人を指すと「困り者」の意味にも。",
   relatedWords:[
     {synonym:true,word:"threat",meaning:"脅し，脅威",breakdown:"危険を知らせる脅し全般。menace は存在そのものが危ない"},
     {synonym:true,word:"danger",meaning:"危険",breakdown:"危ない状態全般。menace は人や物が危険のもとになる"},
     {synonym:true,word:"risk",meaning:"危険性",breakdown:"悪いことが起こる可能性。menace は目の前の脅威"},
     {synonym:true,word:"threaten",meaning:"脅かす，脅す",breakdown:"脅威を与える動詞。menace も動詞でおびやかす"}]},

  {id:2213,word:"sentiment",partOfSpeech:"名詞",meaning:"（感情のこもった）考え，心情；感傷",
   meanings:["名|（感情のこもった）考え，心情","名|感傷，情にもろいこと"],
   pronunciation:"/ˈsentɪmənt/",part:222,
   example:"Public sentiment turned against the plan after the accident.",
   exampleJa:"その事故のあと、世間の心情はその計画に反対する方へ傾いた。",
   example2:"There is no room for sentiment when the coach chooses the team.",
   exampleJa2:"監督がチームを選ぶとき、感傷が入りこむ余地はない。",
   etymologyProcess:"sens（感じる）＋ ment（名詞）→ 心で感じ取ったものは…？",
   etymologyConclusion:"sens（感じる）＋ ment（名詞）→ 心で感じ取って抱いた思い＝（感情のこもった）考え，心情",
   spelling:"sens→sent（もとの動詞 sentire の形）",
   etymologyMore:["感じる気持ちに流される→感傷，情にもろいこと"],
   relatedWords:[
     {word:"sense",meaning:"感覚",breakdown:"sens（感じる）→ ものを感じ取るはたらき"},
     {word:"sensitive",meaning:"敏感な",breakdown:"sens（感じる）＋ ive（形容詞）→ 小さなことも感じ取る"},
     {word:"sentence",meaning:"文；判決",breakdown:"sens（感じる）→ 感じて考えたことを言葉にまとめたもの"},
     {word:"scent",meaning:"香り",breakdown:"scent（感じる）→ 鼻で感じ取るにおい"}]},

  {id:2214,word:"verge",partOfSpeech:"名詞",meaning:"瀬戸際，寸前；へり",
   meanings:["名|瀬戸際，寸前","名|（道路などの）へり，縁","自|（on ～に）近い，接する"],
   pronunciation:"/vɜːrdʒ/",part:222,
   example:"The small shop was on the verge of closing down.",
   exampleJa:"その小さな店は閉店の瀬戸際にあった。",
   example2:"His jokes in class sometimes verge on being rude.",
   exampleJa2:"授業中の彼の冗談は、ときどき失礼に近いものになる。",
   usage:["on the verge of doing（今にも～しそうで）","verge on 事（事に近い）"],
   etymologyProcess:"verge（棒）→ 棒で示した境目のぎりぎりは…？",
   etymologyConclusion:"verge（棒）→ 権威の棒が示す境目から、物事が起こるぎりぎりの縁＝瀬戸際，寸前",
   why:"【なぜ】ラテン語 virga は「細い棒」。中世のイギリスでは役人が持つ権威の棒を指し、その力が及ぶ範囲の境目も verge と呼ぶようになりました。境目から「縁・へり」へ、さらに「何かが起こる一歩手前の縁」＝瀬戸際へと意味が移りました。\n【つながり】イギリスでは道路わきの細い芝生の帯も verge と呼びます。「境目」というもとの意味が今も生きています。",
   etymologyMore:["縁そのものを指す→（道路などの）へり，縁"],
   hook:"on the verge of ～（今にも～しそうで）の形で使うことがほとんど。崖っぷちに立つイメージ。",
   relatedWords:[
     {synonym:true,word:"edge",meaning:"端，縁",breakdown:"ものの端全般。verge は何かが起こる寸前の縁"},
     {synonym:true,word:"border",meaning:"境界",breakdown:"区切りの線。verge はもともと棒が示す境目"},
     {synonym:true,word:"brink",meaning:"（崖などの）縁，瀬戸際",breakdown:"on the brink of ～も「今にも～しそう」。より危機的"},
     {synonym:true,word:"almost",meaning:"ほとんど",breakdown:"もう少しで。on the verge of は名詞で言う「寸前」"}]},

  {id:2215,word:"plausible",partOfSpeech:"形容詞",meaning:"（一見）もっともらしい，ありそうな",
   meanings:["形|（一見）もっともらしい，ありそうな"],
   pronunciation:"/ˈplɔːzəbl/",part:222,
   example:"His excuse for being late sounded plausible to the teacher.",
   exampleJa:"遅刻した彼の言い訳は、先生にはもっともらしく聞こえた。",
   example2:"Scientists offered a plausible explanation for the strange lights.",
   exampleJa2:"科学者たちは、その奇妙な光についてありそうな説明を示した。",
   etymologyProcess:"plaus（拍手する）＋ ible（できる）→ 拍手してもらえそうだと…？",
   etymologyConclusion:"plaus（拍手する）＋ ible（できる）→ 拍手をもらえるほどそれらしく聞こえる＝（一見）もっともらしい，ありそうな",
   why:"【なぜ】ラテン語 plausibilis は「拍手に値する，ほめられるべき」。英語に入ったころは「称賛に値する」の意味でしたが、やがて「聞く人がうなずいて拍手しそうな」＝いかにも本当らしく聞こえる、という意味に移りました。見かけだけという響きが残り、「一見もっともらしい」と訳すことが多い語です。\n【つながり】applause（拍手）、applaud（拍手する）が同じ家族です。",
   relatedWords:[
     {word:"applause",meaning:"拍手",breakdown:"ap（～へ）＋ plaus（拍手する）→ 相手へ向けて手をたたく"},
     {word:"applaud",meaning:"拍手する",breakdown:"ap（～へ）＋ plaus（拍手する）→ 舞台の人へ手をたたく"},
     {word:"explode",meaning:"爆発する",breakdown:"ex（外へ）＋ plod（拍手する）→ 手をたたいて役者を追い出す"},
     {synonym:true,word:"reasonable",meaning:"筋の通った",breakdown:"理屈に合っている。plausible は本当らしく聞こえる"}]},

  {id:2216,word:"holistic",partOfSpeech:"形容詞",meaning:"（部分でなく）全体的な，全体を見た",
   meanings:["形|（部分でなく）全体的な，全体を見た"],
   pronunciation:"/hoʊˈlɪstɪk/",part:222,
   example:"The school takes a holistic approach to student health.",
   exampleJa:"その学校は、生徒の健康に全体的な取り組み方をしている。",
   example2:"Doctors are learning to treat patients in a more holistic way.",
   exampleJa2:"医師たちは、より全体を見たやり方で患者を治療することを学んでいる。",
   etymologyProcess:"hol（全体）＋ istic（形容詞）→ 全体として見ると…？",
   etymologyConclusion:"hol（全体）＋ istic（形容詞）→ 部分に分けず、まるごと全体として見る＝（部分でなく）全体的な，全体を見た",
   relatedWords:[
     {word:"hologram",meaning:"ホログラム",breakdown:"hol（全体）→ 物の全体の姿をまるごと写した立体像"},
     {synonym:true,word:"whole",meaning:"全体の",breakdown:"ふつうの「全体の」。holistic は考え方や見方に使う"},
     {synonym:true,word:"overall",meaning:"全体的な",breakdown:"全部をまとめた。holistic は部分のつながりまで見る"},
     {synonym:true,word:"complete",meaning:"完全な",breakdown:"欠けたところがない。holistic は全体をとらえる見方"}]},

  {id:2217,word:"contagious",partOfSpeech:"形容詞",meaning:"（接触で）うつる，伝染性の",
   meanings:["形|（接触で）うつる，伝染性の","形|（笑い・気分が）人にうつりやすい"],
   pronunciation:"/kənˈteɪdʒəs/",part:222,
   example:"Measles is a highly contagious disease that spreads very quickly.",
   exampleJa:"はしかは非常にうつりやすい病気で、とても速く広がる。",
   example2:"Her laugh was so contagious that the whole class started laughing.",
   exampleJa2:"彼女の笑いはとても人にうつりやすく、クラス全員が笑い出した。",
   etymologyProcess:"con（共に）＋ tang（触れる）→ 人と触れ合うと…？",
   etymologyConclusion:"con（共に）＋ tang（触れる）＋ ious（形容詞）→ 触れ合うことで病気が人から人へ移る＝（接触で）うつる，伝染性の",
   spelling:"tang→tag（同じ動詞 tangere の n のない形）",
   etymologyMore:["触れ合うと広がる→（笑い・気分が）人にうつりやすい"],
   relatedWords:[
     {word:"contact",meaning:"接触；連絡する",breakdown:"con（共に）＋ tact（触れる）→ 互いに触れ合う"},
     {word:"tangible",meaning:"触れられる；明白な",breakdown:"tang（触れる）＋ ible（できる）→ 手で触れられる"},
     {word:"entire",meaning:"全体の",breakdown:"in（否定）＋ tact（触れる）→ 誰にも触れられず丸ごと"},
     {synonym:true,word:"infectious",meaning:"感染性の",breakdown:"病原体が入りこんでうつる。contagious は接触でうつる"}]},

  {id:2218,word:"vocal",partOfSpeech:"形容詞",meaning:"声の，発声の；遠慮なく意見を言う",
   meanings:["形|声の，発声の","形|（意見を）遠慮なく言う","名|（歌の）ボーカル"],
   pronunciation:"/ˈvoʊkl/",part:222,
   example:"Singers do special exercises to protect their vocal cords.",
   exampleJa:"歌手は声帯（声のひも）を守るために特別な練習をする。",
   example2:"Some parents were very vocal about the new school rules.",
   exampleJa2:"新しい校則について、遠慮なく意見を言う保護者もいた。",
   etymologyProcess:"voc（呼ぶ）＋ al（～に関する）→ 呼びかける声に関すると…？",
   etymologyConclusion:"voc（呼ぶ）＋ al（～に関する）→ 呼びかける声に関係する＝声の，発声の",
   etymologyMore:["声を上げて言う→（意見を）遠慮なく言う","声を担当する→（歌の）ボーカル"],
   relatedWords:[
     {word:"voice",meaning:"声",breakdown:"voc（呼ぶ）→ 呼びかけるときに出す声"},
     {word:"vocabulary",meaning:"語彙",breakdown:"voc（呼ぶ）→ ものを呼ぶための言葉の集まり"},
     {word:"advocate",meaning:"主張する；支持者",breakdown:"ad（～へ）＋ voc（呼ぶ）＋ ate（動詞）→ 味方として呼ばれる"},
     {word:"vowel",meaning:"母音",breakdown:"voc（呼ぶ）→ 声だけで出せる音"}]},

  {id:2219,word:"sensory",partOfSpeech:"形容詞",meaning:"感覚の，知覚の",
   meanings:["形|感覚の，知覚の"],
   pronunciation:"/ˈsensəri/",part:222,
   example:"Our eyes and ears are the most important sensory organs.",
   exampleJa:"目と耳は、最も重要な感覚の器官だ。",
   example2:"Loud and bright classrooms can cause sensory overload for some students.",
   exampleJa2:"うるさく明るすぎる教室は、一部の生徒に感覚の負担をかけすぎることがある。",
   etymologyProcess:"sens（感じる）＋ ory（形容詞）→ 感じ取るはたらきに関すると…？",
   etymologyConclusion:"sens（感じる）＋ ory（形容詞）→ 見る・聞くなど感じ取るはたらきに関わる＝感覚の，知覚の",
   relatedWords:[
     {word:"sense",meaning:"感覚",breakdown:"sens（感じる）→ ものを感じ取るはたらき"},
     {word:"sensitive",meaning:"敏感な",breakdown:"sens（感じる）＋ ive（形容詞）→ 小さなことも感じ取る"},
     {word:"sensor",meaning:"センサー",breakdown:"sens（感じる）＋ or（もの）→ 光や熱を感じ取る装置"},
     {word:"nonsense",meaning:"ばかげたこと",breakdown:"non（否定）＋ sens（感じる）→ 意味が感じ取れない"}]},

  {id:2220,word:"numb",partOfSpeech:"形容詞",meaning:"（寒さなどで）感覚がない，しびれた",
   meanings:["形|（寒さなどで）感覚がない，しびれた","形|（ショックで）ぼうぜんとした","他|感覚をなくさせる"],
   pronunciation:"/nʌm/",part:222,
   example:"My fingers were numb after the long walk in the snow.",
   exampleJa:"雪の中を長く歩いたあと、私の指は感覚がなかった。",
   example2:"The cold wind numbed our faces as we waited for the bus.",
   exampleJa2:"バスを待つ間、冷たい風で私たちの顔は感覚がなくなった。",
   etymologyProcess:"numb（取られた）→ 感覚を取られてしまうと…？",
   etymologyConclusion:"numb（取られた）→ 寒さなどに感覚を取られてしまった＝（寒さなどで）感覚がない，しびれた",
   etymologyMore:["心の感覚まで取られる→（ショックで）ぼうぜんとした"],
   hook:"古英語 niman（取る）の過去分詞から。感覚を「取られた」状態。最後の b は発音しない。",
   relatedWords:[
     {synonym:true,word:"cold",meaning:"冷たい",breakdown:"冷えた状態。numb は冷えすぎて感覚がない"},
     {synonym:true,word:"asleep",meaning:"眠って；（手足が）しびれて",breakdown:"my leg is asleep で「足がしびれた」。会話的"},
     {synonym:true,word:"frozen",meaning:"凍った",breakdown:"凍りついた。numb は感覚がなくなった状態"},
     {synonym:true,word:"paralyze",meaning:"まひさせる",breakdown:"まったく動かなくする。numb は感覚だけがない"}]},

  {id:2221,word:"physiological",partOfSpeech:"形容詞",meaning:"生理的な，生理学の",
   meanings:["形|生理的な，生理学の"],
   pronunciation:"/ˌfɪziəˈlɑːdʒɪkl/",part:223,
   example:"Sleep has important physiological effects on growing teenagers.",
   exampleJa:"睡眠は、成長期の10代に重要な生理的な影響を与える。",
   example2:"Stress before exams can cause physiological changes such as a fast heartbeat.",
   exampleJa2:"試験前のストレスは、速い心拍などの生理的な変化を引き起こすことがある。",
   etymologyProcess:"phys（自然）＋ log（学問）→ 自然のしくみを学ぶと…？",
   etymologyConclusion:"phys（自然）＋ log（学問）＋ ical（～の）→ 体に自然に備わったはたらきを学ぶ学問の＝生理的な，生理学の",
   why:"【なぜ】ギリシャ語 physiologia は「自然についての研究」。英語でも最初は自然全体を調べる学問を指していました。やがて研究の中心が生き物の体へ移り、呼吸・消化・睡眠など、体が自然に行っているはたらきを調べる「生理学」の意味になりました。\n【つながり】physics（物理学）も「自然」の学問。生き物の体に向けたのが physiology です。",
   relatedWords:[
     {word:"physics",meaning:"物理学",breakdown:"phys（自然）→ 自然界のしくみを調べる学問"},
     {word:"physical",meaning:"身体の；物質の",breakdown:"physic（自然）＋ al（～の）→ 自然に備わった体や物の"},
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）→ 生き物を調べる学問"},
     {word:"technology",meaning:"科学技術",breakdown:"techn（技）＋ log（学問）→ 技を体系立てた学問"}]},

  {id:2222,word:"bilateral",partOfSpeech:"形容詞",meaning:"二国間の，双方の",
   meanings:["形|二国間の，双方の","形|（体の）左右両側の"],
   pronunciation:"/ˌbaɪˈlætərəl/",part:223,
   example:"Japan and Australia signed a bilateral trade agreement last year.",
   exampleJa:"日本とオーストラリアは、昨年二国間の貿易協定に署名した。",
   example2:"The two schools held bilateral talks to plan a joint festival.",
   exampleJa2:"2つの学校は、合同の祭りを計画するために双方の話し合いを開いた。",
   etymologyProcess:"bi（2つ）＋ later（側）→ 2つの側がそろうと…？",
   etymologyConclusion:"bi（2つ）＋ later（側）＋ al（～の）→ 2つの側がどちらも関わる＝二国間の，双方の",
   etymologyMore:["体の2つの側→（体の）左右両側の"],
   relatedWords:[
     {word:"bicycle",meaning:"自転車",breakdown:"bi（2つ）＋ cycle（回す）→ 回る車輪が2つある乗り物"},
     {word:"unilateral",meaning:"一方的な",breakdown:"uni（1つ）＋ later（側）＋ al（～の）→ 片側だけで決める"},
     {word:"lateral",meaning:"横の，側面の",breakdown:"later（側）＋ al（～の）→ わきの側にある"},
     {synonym:true,word:"mutual",meaning:"相互の",breakdown:"互いに同じことをし合う。bilateral は2つの当事者の間の"}]},

  {id:2223,word:"feudal",partOfSpeech:"形容詞",meaning:"封建（制度）の",
   meanings:["形|封建（制度）の","形|（上下関係が）封建的な"],
   pronunciation:"/ˈfjuːdl/",part:223,
   example:"In the feudal system, farmers worked the land for their lord.",
   exampleJa:"封建制度の中では、農民は領主のために土地を耕した。",
   example2:"The strict rules between older and younger club members feel almost feudal.",
   exampleJa2:"部活の先輩と後輩の間の厳しい決まりは、ほとんど封建的に感じられる。",
   etymologyProcess:"fee（家畜＝財産）＋ al（～の）→ 財産として土地をもらうと…？",
   etymologyConclusion:"fee（家畜＝財産）＋ al（～の）→ 忠誠と引きかえに領地を財産として与える仕組みの＝封建（制度）の",
   spelling:"fee→feud（中世ラテン語 feudum の形）",
   why:"【なぜ】起源には諸説ありますが、ゲルマン語の「家畜」＝昔の財産にさかのぼるという説が有力です。中世ラテン語 feudum では、王や領主が家来に与える「領地」を指します。領地をもらう代わりに忠誠と兵役を誓う仕組みが、ここから feudal system（封建制度）と呼ばれるようになりました。\n【つながり】「封建」の「封」も、土地を分け与えて治めさせるという意味で、発想がよく似ています。",
   etymologyMore:["身分の上下がきっちり決まった仕組み→（上下関係が）封建的な"],
   relatedWords:[
     {word:"fee",meaning:"料金，謝礼",breakdown:"fee（家畜＝財産）→ 財産として払うもの"},
     {synonym:true,word:"lord",meaning:"領主，君主",breakdown:"領地を治める人。feudal な社会のいちばん上"},
     {synonym:true,word:"knight",meaning:"騎士",breakdown:"領地をもらって主君に仕えた戦士"},
     {synonym:true,word:"medieval",meaning:"中世の",breakdown:"ヨーロッパの封建制度は中世に栄えた"}]},

  {id:2224,word:"imperial",partOfSpeech:"形容詞",meaning:"帝国の，皇帝の",
   meanings:["形|帝国の，皇帝の","形|皇室の"],
   pronunciation:"/ɪmˈpɪriəl/",part:223,
   example:"The imperial army of ancient Rome conquered many lands.",
   exampleJa:"古代ローマの帝国の軍隊は、多くの土地を征服した。",
   example2:"Our class took photos in front of the Imperial Palace in Tokyo.",
   exampleJa2:"私たちのクラスは、東京の皇居の前で写真を撮った。",
   etymologyProcess:"imper（命じる）＋ ial（形容詞）→ 命令を下して国を治めると…？",
   etymologyConclusion:"imper（命じる）＋ ial（形容詞）→ 命令を下して広い国を治める皇帝の＝帝国の，皇帝の",
   etymologyMore:["日本では皇帝にあたる天皇の家→皇室の"],
   relatedWords:[
     {word:"empire",meaning:"帝国",breakdown:"imper（命じる）→ 皇帝が命令を下して治める国"},
     {word:"emperor",meaning:"皇帝",breakdown:"imper（命じる）＋ or（人）→ 国じゅうに命令を下す人"},
     {word:"imperative",meaning:"絶対必要な；命令的な",breakdown:"imper（命じる）＋ ative（形容詞）→ 命令のように欠かせない"},
     {synonym:true,word:"royal",meaning:"王の，王室の",breakdown:"王（king）の。imperial は皇帝（emperor）の"}]},

  {id:2225,word:"complementary",partOfSpeech:"形容詞",meaning:"（互いに）補い合う，補完的な",
   meanings:["形|（互いに）補い合う，補完的な"],
   pronunciation:"/ˌkɑːmplɪˈmentəri/",part:223,
   example:"Their skills are complementary, so they make a great team.",
   exampleJa:"2人の能力は互いに補い合うので、すばらしいチームになる。",
   example2:"In art class, we learned that red and green are complementary colors.",
   exampleJa2:"美術の授業で、赤と緑は互いに補い合う色（補色）だと学んだ。",
   etymologyProcess:"com（すっかり）＋ ple（満たす）→ 足りない所をすっかり満たすと…？",
   etymologyConclusion:"com（すっかり）＋ ple（満たす）＋ ment（名詞）＋ ary（形容詞）→ 互いの足りない所を満たし合う＝（互いに）補い合う，補完的な",
   relatedWords:[
     {word:"complete",meaning:"完全な",breakdown:"com（すっかり）＋ ple（満たす）→ すっかり満たして欠けがない"},
     {word:"plenty",meaning:"たくさん",breakdown:"ple（満たす）＋ ty（名詞）→ 満ちあふれるほどの量"},
     {word:"supplement",meaning:"補う；補足",breakdown:"sub（下で）＋ ple（満たす）＋ ment（名詞）→ 下から足して満たす"},
     {word:"compliment",meaning:"ほめ言葉",breakdown:"com（すっかり）＋ ple（満たす）→ 礼儀を満たす言葉"}]},

  {id:2226,word:"pertinent",partOfSpeech:"形容詞",meaning:"（当面の問題に）直接関係のある，適切な",
   meanings:["形|（当面の問題に）直接関係のある，適切な"],
   pronunciation:"/ˈpɜːrtnənt/",part:223,
   example:"Please ask only questions that are pertinent to today's topic.",
   exampleJa:"今日の話題に直接関係のある質問だけをしてください。",
   example2:"The detective found some pertinent information in the old files.",
   exampleJa2:"探偵は古い記録の中から、事件に直接関係のある情報を見つけた。",
   usage:["pertinent to 事（事に直接関係のある）"],
   etymologyProcess:"per（すっかり）＋ tin（保つ）→ 最後までしっかりつながりを保つと…？",
   etymologyConclusion:"per（すっかり）＋ tin（保つ）＋ ent（形容詞）→ 話題としっかりつながりを保っている＝（当面の問題に）直接関係のある，適切な",
   relatedWords:[
     {word:"continue",meaning:"続ける",breakdown:"con（共に）＋ tin（保つ）→ つながりを保ち続ける"},
     {word:"contain",meaning:"含む",breakdown:"con（共に）＋ tain（保つ）→ 中にまとめて保つ"},
     {word:"retain",meaning:"保持する",breakdown:"re（後ろへ）＋ tain（保つ）→ 後ろに引きとめて持ち続ける"},
     {synonym:true,word:"relevant",meaning:"関連のある，適切な",breakdown:"関係がある。pertinent は問題に直接かかわる"}]},

  {id:2227,word:"intrinsic",partOfSpeech:"形容詞",meaning:"本来備わっている，本質的な",
   meanings:["形|本来備わっている，本質的な"],
   pronunciation:"/ɪnˈtrɪnsɪk/",part:223,
   example:"Every person has intrinsic value, no matter what they achieve.",
   exampleJa:"何を成しとげるかに関係なく、どの人にも本来備わっている価値がある。",
   example2:"Students learn best when they have intrinsic motivation, not just test pressure.",
   exampleJa2:"生徒は、試験の重圧だけでなく、内から生まれるやる気があるときに最もよく学ぶ。",
   etymologyProcess:"intra（内側に）＋ sec（そばに）→ 内側にぴったりあると…？",
   etymologyConclusion:"intra（内側に）＋ sec（そばに）→ 外から付けたのでなく、もともと内側にある＝本来備わっている，本質的な",
   spelling:"intra→intr（a が消えた）、sec→sic（ラテン語 intrinsecus が変化）",
   relatedWords:[
     {word:"extrinsic",meaning:"外からの，付帯的な",breakdown:"extra（範囲の外へ）＋ sec（そばに）→ 外側から付いた"},
     {synonym:true,word:"natural",meaning:"生まれつきの，自然な",breakdown:"生まれつきそうである。intrinsic はそのものの中身に備わる"},
     {synonym:true,word:"basic",meaning:"基本的な",breakdown:"土台になる。intrinsic は本質として内にある"},
     {synonym:true,word:"essential",meaning:"本質的な；不可欠な",breakdown:"欠かせない本質の。intrinsic は内側から備わる"}]},

  {id:2228,word:"unprecedented",partOfSpeech:"形容詞",meaning:"前例のない，かつてない",
   meanings:["形|前例のない，かつてない"],
   pronunciation:"/ʌnˈpresɪdentɪd/",part:223,
   example:"The town faced an unprecedented heat wave last summer.",
   exampleJa:"その町は去年の夏、前例のない熱波に見舞われた。",
   example2:"Our soccer team won an unprecedented ten games in a row.",
   exampleJa2:"私たちのサッカー部は、かつてない10連勝をした。",
   etymologyProcess:"un（否定）＋ pre（先に）＋ ced（行く）→ 過去をさかのぼって探しても…？",
   etymologyConclusion:"un（否定）＋ pre（先に）＋ ced（行く）→ 先に起きた同じような例がない＝前例のない，かつてない",
   relatedWords:[
     {word:"precede",meaning:"先行する",breakdown:"pre（先に）＋ ced（行く）→ 先に立って行く"},
     {word:"precedent",meaning:"前例",breakdown:"pre（先に）＋ ced（行く）＋ ent（もの）→ 先に起きた例"},
     {word:"process",meaning:"過程",breakdown:"pro（前へ）＋ cess（行く）→ 前へ進んでいく流れ"},
     {word:"access",meaning:"接近；利用する権利",breakdown:"ac（～へ）＋ cess（行く）→ 目的の場所へ行く"}]},

  {id:2229,word:"tentative",partOfSpeech:"形容詞",meaning:"仮の，暫定的な；ためらいがちな",
   meanings:["形|仮の，暫定的な","形|ためらいがちな，自信のない"],
   pronunciation:"/ˈtentətɪv/",part:223,
   example:"We made a tentative plan to meet at the station on Saturday.",
   exampleJa:"私たちは、土曜日に駅で会うという仮の計画を立てた。",
   example2:"The new student gave me a shy and tentative smile.",
   exampleJa2:"転校生は、はにかんだ、ためらいがちなほほえみを私に向けた。",
   etymologyProcess:"tempt（試す）＋ ative（形容詞）→ まず試しにやってみる段階は…？",
   etymologyConclusion:"tempt（試す）＋ ative（形容詞）→ まだ試しにやってみている段階の＝仮の，暫定的な",
   spelling:"tempt→tent（ラテン語の別の形 tentare から）",
   etymologyMore:["おそるおそる試してみる→ためらいがちな，自信のない"],
   relatedWords:[
     {word:"attempt",meaning:"試みる",breakdown:"ad（～へ）＋ tempt（試す）→ 目標へ向かって試す"},
     {word:"tempt",meaning:"誘惑する",breakdown:"tempt（試す）→ 心を試すように誘いかける"},
     {word:"temptation",meaning:"誘惑",breakdown:"tempt（試す）＋ ation（名詞）→ 心を試される誘い"},
     {synonym:true,word:"temporary",meaning:"一時的な",breakdown:"しばらくの間だけ。tentative はまだ決まっていない"}]},

  {id:2230,word:"drastic",partOfSpeech:"形容詞",meaning:"（手段が）思い切った，抜本的な",
   meanings:["形|（手段が）思い切った，抜本的な","形|（変化が）急激な"],
   pronunciation:"/ˈdræstɪk/",part:223,
   example:"The government took drastic measures to stop the virus from spreading.",
   exampleJa:"政府はウイルスの広がりを止めるため、思い切った対策をとった。",
   example2:"Cutting out all sweets from your diet may be too drastic.",
   exampleJa2:"食事から甘い物を全部なくすのは、思い切りすぎかもしれない。",
   etymologyProcess:"dra（行う）＋ ic（形容詞）→ 強く働きかけて行うと…？",
   etymologyConclusion:"dra（行う）＋ ic（形容詞）→ 強く働きかけて一気にやってしまう＝（手段が）思い切った，抜本的な",
   spelling:"dra→drast（ギリシャ語 drastikos の形）",
   etymologyMore:["一気に大きく働く→（変化が）急激な"],
   relatedWords:[
     {word:"drama",meaning:"劇，ドラマ",breakdown:"dra（行う）→ 舞台の上で行ってみせる劇"},
     {word:"dramatic",meaning:"劇的な",breakdown:"dra（行う）＋ ic（形容詞）→ 劇のように激しく動く"},
     {synonym:true,word:"extreme",meaning:"極端な",breakdown:"いちばん端まで行った。drastic は手段が思い切った"},
     {synonym:true,word:"radical",meaning:"根本的な",breakdown:"根っこから変える。drastic は強く一気に変える"}]},

  {id:2231,word:"ubiquitous",partOfSpeech:"形容詞",meaning:"どこにでもある，至る所に存在する",
   meanings:["形|どこにでもある，至る所に存在する"],
   pronunciation:"/juːˈbɪkwɪtəs/",part:224,
   example:"Smartphones have become ubiquitous in almost every part of modern life.",
   exampleJa:"スマートフォンは、現代の生活のほぼあらゆる場面でどこにでもあるものになった。",
   example2:"Convenience stores seem ubiquitous in Japan, even in small towns.",
   exampleJa2:"日本では、小さな町でさえコンビニが至る所に存在するように思える。",
   etymologyProcess:"ubi（どこに）＋ que（～でも）→ どこを見ても…？",
   etymologyConclusion:"ubi（どこに）＋ que（～でも）＋ ous（形容詞）→ どこを見てもそこにある＝どこにでもある，至る所に存在する",
   spelling:"que→qui（名詞 ubiquity を通って変化）",
   relatedWords:[
     {synonym:true,word:"everywhere",meaning:"どこでも",breakdown:"「どこにでも」を表すふつうの副詞。ubiquitous はその形容詞版"},
     {synonym:true,word:"common",meaning:"よくある",breakdown:"ありふれている。ubiquitous はどこにでも見かける"},
     {synonym:true,word:"widespread",meaning:"広く行き渡った",breakdown:"広い範囲に広がった。ubiquitous は至る所にある"},
     {word:"ubiquity",meaning:"遍在，どこにでもあること",breakdown:"ubi（どこに）＋ que（～でも）＋ ity（名詞）→ どこにでもあること"}]},

  {id:2232,word:"pervasive",partOfSpeech:"形容詞",meaning:"（隅々まで）広がった，はびこる",
   meanings:["形|（隅々まで）広がった，はびこる"],
   pronunciation:"/pərˈveɪsɪv/",part:224,
   example:"The smell of smoke was pervasive throughout the whole building.",
   exampleJa:"煙のにおいが、建物全体の隅々まで広がっていた。",
   example2:"Social media has a pervasive influence on teenagers today.",
   exampleJa2:"ソーシャルメディアは、今の10代に隅々まで広がった影響を与えている。",
   etymologyProcess:"per（通して）＋ vad（進む）→ 端から端まで進んでいくと…？",
   etymologyConclusion:"per（通して）＋ vad（進む）＋ ive（形容詞）→ 端から端まで入りこんで進んでいく＝（隅々まで）広がった，はびこる",
   spelling:"vad→vas（ラテン語の過去分詞の形）",
   relatedWords:[
     {word:"invade",meaning:"侵略する",breakdown:"in（中へ）＋ vad（進む）→ よその土地の中へ進む"},
     {word:"invasion",meaning:"侵略",breakdown:"in（中へ）＋ vad（進む）＋ ion（名詞）→ 中へ攻め入ること"},
     {word:"evade",meaning:"避ける，逃れる",breakdown:"ex（外へ）＋ vad（進む）→ 外へ進んで逃げる"},
     {synonym:true,word:"widespread",meaning:"広く行き渡った",breakdown:"広い範囲に広がった。pervasive は隅々まで入りこむ"}]},

  {id:2233,word:"exponential",partOfSpeech:"形容詞",meaning:"（増え方が）指数関数的な，急激な",
   meanings:["形|（増え方が）指数関数的な，急激な"],
   pronunciation:"/ˌekspəˈnenʃl/",part:224,
   example:"The app saw exponential growth in users after its launch.",
   exampleJa:"そのアプリは公開後、利用者数が指数関数的に増えた。",
   example2:"The cost of the project has increased at an exponential rate.",
   exampleJa2:"その計画の費用は、急激な割合で増えてきた。",
   etymologyProcess:"ex（外へ）＋ pon（置く）→ 数の外に小さく置いた数は…？",
   etymologyConclusion:"ex（外へ）＋ pon（置く）＋ ent（もの）＋ ial（形容詞）→ 右上に置く指数のように増える＝（増え方が）指数関数的な，急激な",
   why:"【なぜ】ラテン語 exponere は「外に置く，示す」。数学では、2³ の 3 のように数の右上に置いて「何回かけるか」を示す数を exponent（指数）と呼びました。指数が1つ増えるごとに値が何倍にもふくらむので、exponential は「指数関数的な」、さらに日常でも「加速して増える」ことに使います。\n【つながり】expose（さらす）、opponent（相手）も「置く」の家族です。",
   relatedWords:[
     {word:"expose",meaning:"さらす",breakdown:"ex（外へ）＋ pos（置く）→ 外に置いて見えるようにする"},
     {word:"opponent",meaning:"相手，敵",breakdown:"op（向かい合って）＋ pon（置く）＋ ent（人）→ 向かいに置かれた人"},
     {word:"component",meaning:"部品，構成要素",breakdown:"com（共に）＋ pon（置く）＋ ent（もの）→ 一緒に置いて組み立てるもの"},
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ion（名詞）→ 置かれている場所"}]},

  {id:2234,word:"perpetual",partOfSpeech:"形容詞",meaning:"絶え間ない，永続する",
   meanings:["形|絶え間ない，永続する"],
   pronunciation:"/pərˈpetʃuəl/",part:224,
   example:"The old man lived in perpetual fear of losing his house.",
   exampleJa:"その老人は、家を失うのではという絶え間ない不安の中で暮らしていた。",
   example2:"I'm tired of my brother's perpetual complaints about his homework.",
   exampleJa2:"弟の宿題についての絶え間ない文句には、うんざりしている。",
   etymologyProcess:"per（通して）＋ pet（求める）→ 最後まで通して向かい続けると…？",
   etymologyConclusion:"per（通して）＋ pet（求める）＋ ual（～の）→ 途切れずに最後まで向かい続ける＝絶え間ない，永続する",
   why:"【なぜ】ラテン語 petere は「目指して向かう，求める」。per（通して）がつくと「最後まで通して向かっていく」となり、perpetuus は途中で途切れない「ずっと続く」という意味になりました。そこから英語でも、終わりなく続くこと＝絶え間ない・永続するを表します。\n【つながり】compete（競う）は共に同じ目標へ向かうこと。「ペペチュアルカレンダー（万年暦）」にも使われます。",
   relatedWords:[
     {word:"compete",meaning:"競争する",breakdown:"com（共に）＋ pet（求める）→ 同じものを一緒に求めて争う"},
     {word:"repeat",meaning:"くり返す",breakdown:"re（再び）＋ pet（求める）→ もう一度求めて同じことをする"},
     {word:"appetite",meaning:"食欲",breakdown:"ap（～へ）＋ pet（求める）→ 食べ物へ向かう欲求"},
     {synonym:true,word:"constant",meaning:"絶えず続く",breakdown:"変わらずに続く。perpetual は終わりが来ない感じ"}]},

  {id:2235,word:"future-oriented",partOfSpeech:"形容詞",meaning:"未来志向の，将来を見すえた",
   meanings:["形|未来志向の，将来を見すえた"],
   pronunciation:"/ˈfjuːtʃər ˈɔːrientɪd/",part:224,
   example:"Our principal wants the school to become more future-oriented.",
   exampleJa:"校長先生は、学校がもっと未来志向になることを望んでいる。",
   example2:"Future-oriented students often plan their study schedules carefully.",
   exampleJa2:"将来を見すえた生徒は、勉強の予定を注意深く立てることが多い。",
   etymologyProcess:"future（これから来る）＋ ori（のぼり始める）→ 日ののぼる方へ向きを合わせると…？",
   etymologyConclusion:"future（これから来る）＋ ori（のぼり始める）→ これから来る時へ向きを合わせる＝未来志向の，将来を見すえた",
   why:"【なぜ】ラテン語 oriri は「（太陽が）のぼる」。太陽がのぼる方角＝東を orient と呼び、昔は教会や地図を東に合わせて向きを決めました。そこから orient は「向きを合わせる」という動詞になり、-oriented は「～の方を向いた，～志向の」を表します。\n【つながり】origin（起源）も「のぼり始める」所。「オリエンテーション」は新しい場所で向きを合わせる説明会です。",
   relatedWords:[
     {word:"origin",meaning:"起源",breakdown:"ori（のぼり始める）→ 物事がのぼり始めた出発点"},
     {word:"original",meaning:"最初の；独創的な",breakdown:"ori（のぼり始める）＋ al（～の）→ 始まりの時点の"},
     {word:"orientation",meaning:"オリエンテーション，方向づけ",breakdown:"ori（のぼり始める）＋ ation（名詞）→ 日の出の方へ向きを合わせる"},
     {synonym:true,word:"forward-looking",meaning:"前向きな，先を見た",breakdown:"前を見ている。future-oriented は将来に目標を置く"}]},

  {id:2236,word:"intact",partOfSpeech:"形容詞",meaning:"（損なわれず）無傷の，そのままの",
   meanings:["形|（損なわれず）無傷の，そのままの"],
   pronunciation:"/ɪnˈtækt/",part:224,
   example:"Amazingly, the old vase was still intact after the earthquake.",
   exampleJa:"驚いたことに、その古い花びんは地震のあとも無傷のままだった。",
   example2:"Despite the storm, our tent stayed intact through the night.",
   exampleJa2:"嵐にもかかわらず、私たちのテントは一晩中そのままの形で持ちこたえた。",
   etymologyProcess:"in（否定）＋ tact（触れる）→ だれにも触れられていないと…？",
   etymologyConclusion:"in（否定）＋ tact（触れる）→ だれにも触れられず、傷ひとつついていない＝（損なわれず）無傷の，そのままの",
   relatedWords:[
     {word:"contact",meaning:"接触；連絡する",breakdown:"con（共に）＋ tact（触れる）→ 互いに触れ合う"},
     {word:"entire",meaning:"全体の",breakdown:"in（否定）＋ tact（触れる）→ 誰にも触れられず丸ごと"},
     {word:"tangible",meaning:"触れられる；明白な",breakdown:"tang（触れる）＋ ible（できる）→ 手で触れられる"},
     {synonym:true,word:"whole",meaning:"全体の，完全な",breakdown:"欠けずにそろった。intact は傷がついていない"}]},

  {id:2237,word:"maternal",partOfSpeech:"形容詞",meaning:"母の，母方の；母親らしい",
   meanings:["形|母の，母方の","形|母親らしい"],
   pronunciation:"/məˈtɜːrnl/",part:224,
   example:"She got her curly hair from her maternal grandmother.",
   exampleJa:"彼女の巻き毛は、母方の祖母から受け継いだものだ。",
   example2:"The older girl showed maternal care toward the little children.",
   exampleJa2:"年上の女の子は、小さな子どもたちに母親らしい世話をした。",
   etymologyProcess:"mater（母）＋ al（～の）→ 母に関係すると…？",
   etymologyConclusion:"mater（母）＋ al（～の）→ 母に関係する、母の側の＝母の，母方の",
   etymologyMore:["母のようにふるまう→母親らしい"],
   relatedWords:[
     {word:"maternity",meaning:"母であること；出産の",breakdown:"mater（母）＋ ity（名詞）→ 母であること"},
     {word:"material",meaning:"材料",breakdown:"mater（母）＋ ial（形容詞）→ 物を生み出す母＝もと、とされる"},
     {synonym:true,word:"mother",meaning:"母",breakdown:"ゲルマン語の「母」。mater と同じ大昔の語から"},
     {synonym:true,word:"motherly",meaning:"母親らしい",breakdown:"ふだん使う言い方。maternal はやや硬い"}]},

  {id:2238,word:"masculine",partOfSpeech:"形容詞",meaning:"男らしい，男性的な",
   meanings:["形|男らしい，男性的な","形|（文法で）男性の"],
   pronunciation:"/ˈmæskjəlɪn/",part:224,
   example:"He has a deep, masculine voice that everyone notices.",
   exampleJa:"彼は、だれもが気づく低く男らしい声をしている。",
   example2:"Some people think cooking isn't masculine, but that idea is outdated.",
   exampleJa2:"料理は男性的でないと考える人もいるが、その考えは古い。",
   etymologyProcess:"mascul（男）＋ ine（～の）→ 男に関すると…？",
   etymologyConclusion:"mascul（男）＋ ine（～の）→ 男の特徴をそなえた＝男らしい，男性的な",
   etymologyMore:["男の側に分類する→（文法で）男性の"],
   relatedWords:[
     {word:"male",meaning:"男性の，雄の",breakdown:"mascul（男）→ フランス語を通って短くなった「男性の」"},
     {word:"macho",meaning:"男っぽい，マッチョな",breakdown:"mascul（男）→ スペイン語で macho になった男らしさ"},
     {synonym:true,word:"manly",meaning:"男らしい",breakdown:"man（男）＋ ly（～らしい）。ふだん使う言い方"},
     {synonym:true,word:"tough",meaning:"たくましい，頑丈な",breakdown:"強くて打たれ強い。masculine は男性らしさ全般"}]},

  {id:2239,word:"juvenile",partOfSpeech:"形容詞",meaning:"少年少女の，青少年の；子どもっぽい",
   meanings:["形|少年少女の，青少年の","形|子どもっぽい","名|少年少女"],
   pronunciation:"/ˈdʒuːvənaɪl/",part:224,
   example:"The city opened a new center to prevent juvenile crime.",
   exampleJa:"市は青少年の犯罪を防ぐための新しいセンターを開いた。",
   example2:"His juvenile jokes annoyed everyone at the meeting.",
   exampleJa2:"彼の子どもっぽい冗談は、会議にいた全員をいらいらさせた。",
   etymologyProcess:"juven（若い）→ まだ若い年ごろだと…？",
   etymologyConclusion:"juven（若い）→ 大人になる前の、まだ若い年ごろの＝少年少女の，青少年の",
   etymologyMore:["若さが悪く出る→子どもっぽい"],
   relatedWords:[
     {word:"junior",meaning:"年下の，下級の",breakdown:"jun（若い）＋ ior（より～な）→ より若いほうの"},
     {word:"rejuvenate",meaning:"若返らせる",breakdown:"re（再び）＋ juven（若い）＋ ate（動詞）→ もう一度若くする"},
     {synonym:true,word:"young",meaning:"若い",breakdown:"ゲルマン語の「若い」。juven と同じ大昔の語から"},
     {synonym:true,word:"childish",meaning:"子どもっぽい",breakdown:"ふだん使う言い方。juvenile は法律や硬い場面でも"}]},

  {id:2240,word:"intelligible",partOfSpeech:"形容詞",meaning:"（はっきり）理解できる，わかりやすい",
   meanings:["形|（はっきり）理解できる，わかりやすい"],
   pronunciation:"/ɪnˈtelɪdʒəbl/",part:224,
   example:"His speech was barely intelligible because of the loud music.",
   exampleJa:"大音量の音楽のせいで、彼のスピーチはかろうじて理解できる程度だった。",
   example2:"Please write your report in plain and intelligible English.",
   exampleJa2:"報告書は、平易でわかりやすい英語で書いてください。",
   etymologyProcess:"inter（間の）＋ lect（拾う）→ 間から拾い分けられると…？",
   etymologyConclusion:"inter（間の）＋ lect（拾う）＋ ible（できる）→ 言葉の中から意味を拾い分けられる＝（はっきり）理解できる，わかりやすい",
   spelling:"inter→intel（l の前で r が l に）、lect→lig（e が i に変わった）",
   relatedWords:[
     {word:"intelligent",meaning:"頭のよい",breakdown:"inter（間の）＋ lect（拾う）＋ ent（～している）→ 間から選び拾える"},
     {word:"collect",meaning:"集める",breakdown:"col（共に）＋ lect（拾う）→ 拾って一か所に集める"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離れて）＋ lect（拾う）→ より分けて拾い出す"},
     {word:"lecture",meaning:"講義",breakdown:"lect（拾う・読む）＋ ure（名詞）→ 読み上げて聞かせる"}]},

  {id:2241,word:"dairy",partOfSpeech:"形容詞",meaning:"乳製品の，酪農の",
   meanings:["形|乳製品の，酪農の","名|乳製品；酪農場"],
   pronunciation:"/ˈderi/",part:225,
   example:"Milk, cheese, and yogurt are all dairy products.",
   exampleJa:"牛乳、チーズ、ヨーグルトはどれも乳製品だ。",
   example2:"My uncle runs a dairy farm with about fifty cows.",
   exampleJa2:"おじは、約50頭の牛がいる酪農場を営んでいる。",
   etymologyProcess:"dairy（乳しぼり小屋）→ 乳をしぼって加工する場所は…？",
   etymologyConclusion:"dairy（乳しぼり小屋）→ 牛の乳をしぼってバターやチーズにする所の＝乳製品の，酪農の",
   hook:"diary（日記）と混同注意。古英語で「パンをこねる女性」が、のちに乳しぼり係の意味に。",
   relatedWords:[
     {synonym:true,word:"dough",meaning:"パン生地",breakdown:"dairy と同じ「こねる」の家族。パンをこねる生地"},
     {synonym:true,word:"milk",meaning:"牛乳",breakdown:"dairy products の代表。牛からしぼる乳"},
     {synonym:true,word:"cheese",meaning:"チーズ",breakdown:"乳を固めて作る dairy product"},
     {synonym:true,word:"farm",meaning:"農場",breakdown:"作物や家畜を育てる所。dairy farm は乳牛の牧場"}]},

  {id:2242,word:"stray",partOfSpeech:"形容詞",meaning:"（動物が）迷子の，飼い主のいない",
   meanings:["形|（動物が）迷子の，飼い主のいない","自|（道・話から）それる，はぐれる","形|（弾などが）それた，はぐれた"],
   pronunciation:"/streɪ/",part:225,
   example:"We found a stray cat sleeping under our car this morning.",
   exampleJa:"今朝、私たちは車の下で寝ている飼い主のいない猫を見つけた。",
   example2:"Don't stray from the path when you hike in the mountains.",
   exampleJa2:"山でハイキングをするときは、道からそれてはいけない。",
   etymologyProcess:"extra（範囲の外へ）＋ vag（さまよう）→ 外へさまよい出ると…？",
   etymologyConclusion:"extra（範囲の外へ）＋ vag（さまよう）→ 家や群れの外へさまよい出てしまった＝（動物が）迷子の，飼い主のいない",
   spelling:"extra→s（es- を通って縮まった）、vag→tray（フランス語で変化）",
   why:"【なぜ】古いフランス語 estraier（さまよう）から来た語で、ラテン語 extra vagari（外をさまよう）が元です。家や群れの外へさまよい出た動物を表し、動詞では道や話題から「それる」の意味で使われます。\n【つながり】vague（ぼんやりした）も「さまよう」の家族です。",
   etymologyMore:["決まった道の外へさまよう→（道・話から）それる，はぐれる","ねらいからそれて飛ぶ→（弾などが）それた，はぐれた"],
   relatedWords:[
     {word:"vague",meaning:"ぼんやりした",breakdown:"vag（さまよう）→ 考えがさまよって定まらない"},
     {word:"extra",meaning:"余分の",breakdown:"extra（範囲の外へ）→ 決まった分の外にある"},
     {word:"extraordinary",meaning:"並外れた",breakdown:"extra（範囲の外へ）＋ ord（順序）→ ふつうの並びの外"},
     {synonym:true,word:"lost",meaning:"迷った",breakdown:"道や物を失った。stray は群れや家からはぐれた"}]},

  {id:2243,word:"dormant",partOfSpeech:"形容詞",meaning:"（活動を）休止している，眠っている",
   meanings:["形|（活動を）休止している，眠っている"],
   pronunciation:"/ˈdɔːrmənt/",part:225,
   example:"Many seeds stay dormant in the cold soil until spring comes.",
   exampleJa:"多くの種は、春が来るまで冷たい土の中で休止している。",
   example2:"My interest in the piano lay dormant until I heard her play.",
   exampleJa2:"彼女の演奏を聞くまで、ピアノへの私の興味は眠っていた。",
   etymologyProcess:"dorm（眠る）＋ ant（～な）→ 眠ったままでいると…？",
   etymologyConclusion:"dorm（眠る）＋ ant（～な）→ 眠っているように動きを止めている＝（活動を）休止している，眠っている",
   relatedWords:[
     {word:"dormitory",meaning:"寮",breakdown:"dorm（眠る）＋ ory（場所）→ 眠るための部屋が並ぶ建物"},
     {word:"dorm",meaning:"寮（話し言葉）",breakdown:"dorm（眠る）→ dormitory を短くした語"},
     {synonym:true,word:"asleep",meaning:"眠って",breakdown:"実際に寝ている。dormant は活動を止めている"},
     {synonym:true,word:"inactive",meaning:"活動していない",breakdown:"動いていない。dormant はまた動き出す力を残す"}]},

  {id:2244,word:"comprehensive",partOfSpeech:"形容詞",meaning:"包括的な，総合的な",
   meanings:["形|包括的な，総合的な"],
   pronunciation:"/ˌkɑːmprɪˈhensɪv/",part:225,
   example:"This book gives a comprehensive guide to Japanese history.",
   exampleJa:"この本は、日本史への包括的な手引きになっている。",
   example2:"The final exam will be comprehensive, so review everything we studied.",
   exampleJa2:"期末試験は総合的なものになるので、学んだことすべてを復習しなさい。",
   etymologyProcess:"com（すっかり）＋ prehend（つかむ）→ 全部をすっかりつかむと…？",
   etymologyConclusion:"com（すっかり）＋ prehend（つかむ）＋ ive（形容詞）→ 全部をすっかりつかんで取りこんでいる＝包括的な，総合的な",
   spelling:"prehend→prehens（ラテン語の過去分詞の形）",
   relatedWords:[
     {word:"comprehend",meaning:"理解する",breakdown:"com（すっかり）＋ prehend（つかむ）→ 内容をすっかりつかむ"},
     {word:"prison",meaning:"刑務所",breakdown:"pris（つかむ）→ つかまえた人を入れておく場所"},
     {word:"surprise",meaning:"驚かせる",breakdown:"sur（上から）＋ pris（つかむ）→ 上から不意につかみかかる"},
     {synonym:true,word:"thorough",meaning:"徹底的な",breakdown:"すみずみまで行き届いた。comprehensive は範囲が広い"}]},

  {id:2245,word:"edible",partOfSpeech:"形容詞",meaning:"食べられる，食用の",
   meanings:["形|食べられる，食用の"],
   pronunciation:"/ˈedəbl/",part:225,
   example:"Some wild mushrooms are edible, but many are poisonous.",
   exampleJa:"野生のキノコには食べられるものもあるが、多くは毒がある。",
   example2:"The cake was decorated with edible flowers from the garden.",
   exampleJa2:"そのケーキは、庭でとれた食用の花で飾られていた。",
   etymologyProcess:"edi（食べる）＋ ble（～できる）→ 口に入れても安全なものは…？",
   etymologyConclusion:"edi（食べる）＋ ble（～できる）→ 安全に食べることができる＝食べられる，食用の",
   relatedWords:[
     {word:"obese",meaning:"肥満の",breakdown:"ob（～に向かって）＋ edi（食べる）→ 食べ物に向かい続けて太った"},
     {synonym:true,word:"eat",meaning:"食べる",breakdown:"ゲルマン語の「食べる」。edi と同じ大昔の語から"},
     {synonym:true,word:"food",meaning:"食べ物",breakdown:"食べるもの全般。edible は食べても安全な"},
     {synonym:true,word:"delicious",meaning:"とてもおいしい",breakdown:"味がよい。edible は食べられるかどうか"}]},

  {id:2246,word:"perishable",partOfSpeech:"形容詞",meaning:"（食べ物が）腐りやすい，傷みやすい",
   meanings:["形|（食べ物が）腐りやすい，傷みやすい","名|（複数形で）生鮮食品"],
   pronunciation:"/ˈperɪʃəbl/",part:225,
   example:"Keep perishable foods like milk and fish in the fridge.",
   exampleJa:"牛乳や魚のような腐りやすい食品は、冷蔵庫に入れておきなさい。",
   example2:"The store sells perishables at half price after eight o'clock.",
   exampleJa2:"その店は8時を過ぎると生鮮食品を半額で売る。",
   etymologyProcess:"per（すっかり）＋ it（行く）→ すっかり行ってしまうと…？",
   etymologyConclusion:"per（すっかり）＋ it（行く）＋ able（できる）→ すぐにだめになって消えていきやすい＝（食べ物が）腐りやすい，傷みやすい",
   spelling:"it→i（もとの動詞 ire の形）",
   why:"【なぜ】ラテン語 perire は「すっかり行ってしまう」＝消え去る、滅びる、死ぬ。英語の perish（滅びる，死ぬ）はここから来ました。-able がついた perishable は「滅びやすい」、特に食べ物について「すぐにだめになる」＝腐りやすいという意味で使われます。\n【つながり】exit（出口）も「行く」の家族。外へ行く所です。",
   etymologyMore:["すぐにだめになる食品→（複数形で）生鮮食品"],
   relatedWords:[
     {word:"perish",meaning:"滅びる，死ぬ",breakdown:"per（すっかり）＋ it（行く）→ すっかり行ってしまい消える"},
     {word:"exit",meaning:"出口",breakdown:"ex（外へ）＋ it（行く）→ 外へ行く所"},
     {word:"issue",meaning:"問題；発行する",breakdown:"ex（外へ）＋ it（行く）→ 外へ出ていくもの"},
     {synonym:true,word:"fresh",meaning:"新鮮な",breakdown:"とれたての。perishable は新鮮さがすぐ失われる"}]},

  {id:2247,word:"naive",partOfSpeech:"形容詞",meaning:"世間知らずの，考えが甘い",
   meanings:["形|世間知らずの，考えが甘い","形|素朴な，飾り気のない"],
   pronunciation:"/naɪˈiːv/",part:225,
   example:"It was naive of me to believe his promise so easily.",
   exampleJa:"彼の約束をあんなに簡単に信じるなんて、私は世間知らずだった。",
   example2:"Many young users are too naive about the dangers of the internet.",
   exampleJa2:"多くの若い利用者は、インターネットの危険について考えが甘すぎる。",
   etymologyProcess:"nat（生まれる）＋ ive（形容詞）→ 生まれたままだと…？",
   etymologyConclusion:"nat（生まれる）＋ ive（形容詞）→ 生まれたままで世の中の裏を知らない＝世間知らずの，考えが甘い",
   spelling:"nat→na（フランス語 naïf を通って t が消えた）",
   why:"【なぜ】ラテン語 nativus は「生まれつきの，自然のままの」。フランス語 naïf（女性形 naïve）では「飾り気のない，素朴な」になり、さらに「生まれたままで世の中の裏を知らない」＝世間知らずの意味が強まりました。日本語の「ナイーブ（繊細な）」とは意味がずれているので注意しましょう。\n【つながり】native（生まれた土地の）と、もとは同じ語です。",
   etymologyMore:["生まれたままの飾らない姿→素朴な，飾り気のない"],
   relatedWords:[
     {word:"native",meaning:"母国の，生まれた土地の",breakdown:"nat（生まれる）＋ ive（形容詞）→ 生まれた場所の"},
     {word:"nature",meaning:"自然；性質",breakdown:"nat（生まれる）＋ ure（名詞）→ 生まれたままの姿"},
     {word:"nation",meaning:"国家，国民",breakdown:"nat（生まれる）＋ ion（名詞）→ 同じ土地に生まれた人々"},
     {synonym:true,word:"innocent",meaning:"無邪気な；無罪の",breakdown:"悪を知らない。naive は世間を知らなすぎる"}]},

  {id:2248,word:"zealous",partOfSpeech:"形容詞",meaning:"（信念・目的に）熱狂的な，熱心すぎる",
   meanings:["形|（信念・目的に）熱狂的な，熱心すぎる"],
   pronunciation:"/ˈzeləs/",part:225,
   example:"The zealous fans waited outside the hotel all night.",
   exampleJa:"熱狂的なファンたちは、ホテルの外で一晩じゅう待っていた。",
   example2:"Our coach is zealous about making us run every morning.",
   exampleJa2:"コーチは、私たちを毎朝走らせることに熱心すぎる。",
   etymologyProcess:"zeal（熱意）＋ ous（～に満ちた）→ 熱意であふれていると…？",
   etymologyConclusion:"zeal（熱意）＋ ous（～に満ちた）→ 熱い思いがあふれるほど満ちている＝（信念・目的に）熱狂的な，熱心すぎる",
   relatedWords:[
     {word:"zeal",meaning:"熱意",breakdown:"zeal（熱意）→ ギリシャ語で燃えるような熱い思い"},
     {word:"jealous",meaning:"嫉妬深い",breakdown:"zeal（熱意）＋ ous（～に満ちた）→ 熱すぎる思いがねたみに"},
     {word:"jealousy",meaning:"嫉妬",breakdown:"zeal（熱意）＋ y（名詞）→ 熱い思いが向かうねたみ"},
     {synonym:true,word:"eager",meaning:"熱心な",breakdown:"したくてたまらない。zealous は度が過ぎるほど"}]},

  {id:2249,word:"timid",partOfSpeech:"形容詞",meaning:"臆病な，おどおどした",
   meanings:["形|臆病な，おどおどした"],
   pronunciation:"/ˈtɪmɪd/",part:225,
   example:"The timid rabbit ran away as soon as we came near.",
   exampleJa:"その臆病なウサギは、私たちが近づくとすぐに逃げていった。",
   example2:"She was too timid to raise her hand in class.",
   exampleJa2:"彼女はおどおどしていて、授業で手を挙げられなかった。",
   etymologyProcess:"tim（恐れる）＋ id（～な状態の）→ いつも恐れていると…？",
   etymologyConclusion:"tim（恐れる）＋ id（～な状態の）→ いつもびくびく恐れている状態の＝臆病な，おどおどした",
   relatedWords:[
     {word:"intimidate",meaning:"おどす，おじけづかせる",breakdown:"in（中へ）＋ tim（恐れる）＋ ate（動詞）→ 心の中に恐れを入れる"},
     {word:"timidity",meaning:"臆病さ",breakdown:"tim（恐れる）＋ ity（名詞）→ 恐れやすい性質"},
     {synonym:true,word:"shy",meaning:"恥ずかしがりの",breakdown:"人前で照れる。timid は怖がって引っこむ"},
     {synonym:true,word:"afraid",meaning:"怖がって",breakdown:"何かを怖がっている。timid はもともと怖がりな性格"}]},

  {id:2250,word:"delinquent",partOfSpeech:"形容詞",meaning:"非行の，非行に走った；（支払いが）滞った",
   meanings:["形|非行の，非行に走った","形|（支払い・義務が）滞った","名|非行少年［少女］"],
   pronunciation:"/dɪˈlɪŋkwənt/",part:225,
   example:"The program helps delinquent teenagers go back to school.",
   exampleJa:"そのプログラムは、非行に走った10代が学校に戻るのを助けている。",
   example2:"He was delinquent in paying his phone bill for three months.",
   exampleJa2:"彼は3か月間、電話代の支払いが滞っていた。",
   etymologyProcess:"de（離れて）＋ linqu（残す）→ 務めを残して離れると…？",
   etymologyConclusion:"de（離れて）＋ linqu（残す）＋ ent（～している）→ 果たすべき務めを残して離れてしまう＝非行の，非行に走った",
   why:"【なぜ】ラテン語 delinquere は「務めを残して離れる」＝果たすべきことを怠る、過ちを犯す。そこから、社会のきまりを守らずに外れていく若者＝「非行の」の意味が生まれました。支払いなどの務めを怠る「滞った」という意味も、同じ「果たさずに放っておく」から来ています。\n【つながり】relinquish（手放す）も「残す」の家族です。",
   relatedWords:[
     {word:"relinquish",meaning:"手放す",breakdown:"re（後ろへ）＋ linqu（残す）→ 後ろに残して手放す"},
     {word:"delinquency",meaning:"非行",breakdown:"de（離れて）＋ linqu（残す）→ 務めを残して外れる行い"},
     {synonym:true,word:"bad",meaning:"悪い",breakdown:"悪いこと全般。delinquent はきまりを破る若者に"},
     {synonym:true,word:"criminal",meaning:"犯罪の；犯罪者",breakdown:"法を犯した。delinquent は主に未成年の非行"}]},
