  {id:2001,word:"roam",partOfSpeech:"自動詞",meaning:"（広い範囲を）うろつき回る，放浪する",
   meanings:["自|（広い範囲を）うろつき回る，放浪する","他|（場所を）歩き回る"],
   pronunciation:"/roʊm/",part:201,
   example:"Wild horses roam freely across the wide plains of Mongolia.",
   exampleJa:"野生の馬が、モンゴルの広い平原を自由にうろつき回っている。",
   example2:"We roamed around the old town all afternoon without a map.",
   exampleJa2:"私たちは地図を持たずに、午後ずっと旧市街を歩き回った。",
   etymologyProcess:"roam（さまよう）→ 行き先を決めずにあちこちへ…？",
   etymologyConclusion:"roam（さまよう）→ 行き先を決めずに広い範囲をあちこち動く＝（広い範囲を）うろつき回る",
   hook:"語源ははっきりしない。ローミングは、電話が契約エリアの外を渡り歩くこと。",
   relatedWords:[
     {word:"roaming",meaning:"（携帯電話の）ローミング",breakdown:"roam（さまよう）＋ ing（名詞）→ 自分のエリアの外を渡り歩く"},
     {synonym:true,word:"wander",meaning:"歩き回る",breakdown:"あてもなく歩くこと。roam は広い範囲を自由に動き回る"},
     {synonym:true,word:"walk",meaning:"歩く",breakdown:"歩くこと全般。roam は目的地を決めない"},
     {synonym:true,word:"travel",meaning:"旅行する",breakdown:"遠くへ出かけること。roam は行き先を決めずにさまよう"}]},

  {id:2002,word:"stroll",partOfSpeech:"自動詞",meaning:"ぶらぶら歩く，散策する",
   meanings:["自|ぶらぶら歩く，散策する","名|散歩，ぶらぶら歩き"],
   pronunciation:"/stroʊl/",part:201,
   example:"After dinner, we strolled along the beach under the stars.",
   exampleJa:"夕食後、私たちは星空の下で浜辺をぶらぶら歩いた。",
   example2:"Let's take a stroll in the park before class starts.",
   exampleJa2:"授業が始まる前に、公園を散歩しよう。",
   etymologyProcess:"stroll（放浪する）→ 急がず気ままに足を運ぶと…？",
   etymologyConclusion:"stroll（放浪する）→ 急ぐ用事もなく気ままにのんびり歩く＝ぶらぶら歩く",
   hook:"語源ははっきりしない。take a stroll（散歩する）の形でよく使う。",
   relatedWords:[
     {word:"stroller",meaning:"ベビーカー",breakdown:"stroll（放浪する）＋ er（道具・人）→ 散歩で押して歩く車"},
     {synonym:true,word:"walk",meaning:"歩く；散歩",breakdown:"歩くこと全般。stroll はのんびり楽しむ歩き方"},
     {synonym:true,word:"wander",meaning:"歩き回る",breakdown:"あてもなく歩く。stroll は近所を気楽に歩く"},
     {synonym:true,word:"roam",meaning:"うろつき回る",breakdown:"広い範囲を自由に動く。stroll は短くゆったり"}]},

  {id:2003,word:"circulate",partOfSpeech:"他動詞・自動詞",meaning:"循環する；（うわさ・情報が）広まる",
   meanings:["自|循環する，巡る","自|（うわさ・情報が）広まる","他|（書類などを）回す，配布する"],
   pronunciation:"/ˈsɜːrkjəleɪt/",part:201,
   example:"Blood circulates through the body, carrying oxygen to every cell.",
   exampleJa:"血液は体内を循環し、すべての細胞に酸素を運ぶ。",
   example2:"A strange rumor about our teacher circulated around the school.",
   exampleJa2:"担任の先生についての妙なうわさが、学校中に広まった。",
   etymologyProcess:"circ（輪を描く）＋ ate（動詞）→ 輪を描いてぐるぐる回ると…？",
   etymologyConclusion:"circ（輪を描く）＋ ate（動詞）→ 輪を描くように回って、またもとへ戻る＝循環する",
   etymologyMore:["人から人へ輪のように回る→（うわさ・情報が）広まる"],
   relatedWords:[
     {word:"circle",meaning:"円；仲間",breakdown:"circ（輪を描く）→ ぐるりと描いた小さな輪の形"},
     {word:"circus",meaning:"サーカス",breakdown:"circ（輪を描く）→ 円い舞台をぐるりと囲んで見る興行"},
     {word:"circulation",meaning:"循環；発行部数",breakdown:"circ（輪を描く）＋ ation（名詞）→ ぐるぐる回ること"},
     {word:"circular",meaning:"円形の",breakdown:"circ（輪を描く）＋ ar（形容詞）→ 輪のような形の"}]},

  {id:2004,word:"wane",partOfSpeech:"自動詞",meaning:"（力・人気などが）衰える，弱まる；（月が）欠ける",
   meanings:["自|（力・人気などが）衰える，弱まる","自|（月が）欠ける","名|衰退，（月の）欠け"],
   pronunciation:"/weɪn/",part:201,
   example:"Interest in the new game began to wane after a few weeks.",
   exampleJa:"数週間たつと、その新しいゲームへの関心は衰え始めた。",
   example2:"The moon is waning, so the nights are getting darker.",
   exampleJa2:"月が欠けてきているので、夜が暗くなってきている。",
   etymologyProcess:"wane（欠けていく）→ 満ちていたものが少しずつ…？",
   etymologyConclusion:"wane（欠けていく）→ 満ちていたものが少しずつ減って細っていく＝（力・人気などが）衰える",
   hook:"月の満ち欠けは wax and wane。細っていく月のように勢いがしぼむ。",
   relatedWords:[
     {synonym:true,word:"decline",meaning:"減少する；断る",breakdown:"下へ傾いていく。wane は満ちていたものが細る"},
     {synonym:true,word:"fade",meaning:"薄れる，消えていく",breakdown:"色や音が弱まる。wane は力や人気が衰える"},
     {synonym:true,word:"weaken",meaning:"弱まる，弱める",breakdown:"weak（弱い）＋ en（～にする）。wane は時とともに細る"},
     {synonym:true,word:"fall",meaning:"落ちる；下がる",breakdown:"下へ落ちること全般。wane はじわじわ細っていく"}]},

  {id:2005,word:"deteriorate",partOfSpeech:"自動詞",meaning:"（質や状態が）悪化する，劣化する",
   meanings:["自|（質や状態が）悪化する，劣化する","他|悪化させる"],
   pronunciation:"/dɪˈtɪriəreɪt/",part:201,
   example:"His health began to deteriorate after he stopped exercising.",
   exampleJa:"運動をやめてから、彼の健康は悪化し始めた。",
   example2:"Our team's performance deteriorated badly in the second half.",
   exampleJa2:"後半になって、私たちのチームのプレーはひどく悪化した。",
   etymologyProcess:"deterior（より悪い）＋ ate（動詞）→ 前よりもっと悪い方へ…？",
   etymologyConclusion:"deterior（より悪い）＋ ate（動詞）→ 前よりもっと悪い状態へ移っていく＝（質や状態が）悪化する",
   relatedWords:[
     {word:"deterioration",meaning:"悪化，劣化",breakdown:"deterior（より悪い）＋ ation（名詞）→ 前より悪くなっていくこと"},
     {synonym:true,word:"worse",meaning:"より悪い",breakdown:"英語本来の「より悪い」。get worse で deteriorate に近い"},
     {synonym:true,word:"damage",meaning:"損害；傷つける",breakdown:"外から傷つけて損なう。deteriorate は自然に悪くなる"},
     {synonym:true,word:"decline",meaning:"衰える；減少する",breakdown:"下へ傾いていく。deteriorate は質が落ちていく"}]},

  {id:2006,word:"plunge",partOfSpeech:"他動詞・自動詞",meaning:"（勢いよく）飛び込む，突っ込む；急落する",
   meanings:["自|（勢いよく）飛び込む，突っ込む","他|（急に）突っ込む，陥れる","自|（価格などが）急落する"],
   pronunciation:"/plʌndʒ/",part:201,
   example:"The boys plunged into the cold lake one after another.",
   exampleJa:"少年たちは次々に冷たい湖に飛び込んだ。",
   example2:"Stock prices plunged after the company's bad news was announced.",
   exampleJa2:"その会社の悪い知らせが発表されると、株価は急落した。",
   etymologyProcess:"plumb（鉛）→ 重い鉛のおもりが水に落ちると…？",
   etymologyConclusion:"plumb（鉛）→ 鉛のおもりのように勢いよく水の中へ沈む＝（勢いよく）飛び込む",
   why:"【なぜ】ラテン語 plumbum は「鉛」。船乗りは鉛のおもりをひもにつけて水に投げこみ、水の深さを測りました。ずしんと沈むその動きから、フランス語 plonger「水に沈める」が生まれ、英語の plunge になりました。\n【つながり】plumber（配管工）は、昔の水道管が鉛でできていたことから。元素記号 Pb も plumbum の頭文字です。",
   etymologyMore:["おもりが一気に沈むように→（価格などが）急落する"],
   spelling:"plumb→plun（フランス語を通って変化）",
   relatedWords:[
     {word:"plumber",meaning:"配管工",breakdown:"plumb（鉛）＋ er（人）→ 鉛の管を扱う職人"},
     {word:"plumbing",meaning:"配管（設備）",breakdown:"plumb（鉛）＋ ing（名詞）→ 鉛の管を張りめぐらせたしくみ"},
     {synonym:true,word:"dive",meaning:"飛び込む，潜る",breakdown:"頭から水に入る。plunge は勢いよく深く突っ込む"},
     {synonym:true,word:"jump",meaning:"跳ぶ",breakdown:"跳ぶこと全般。plunge は水や中へ勢いよく入る"}]},

  {id:2007,word:"backfire",partOfSpeech:"自動詞",meaning:"裏目に出る",
   meanings:["自|裏目に出る","自|（エンジンが）逆火を起こす"],
   pronunciation:"/ˌbækˈfaɪər/",part:201,
   example:"His plan to trick the teacher backfired and he got detention.",
   exampleJa:"先生をだまそうという彼の計画は裏目に出て、彼は居残りになった。",
   example2:"Cutting sleep to study longer can backfire on your test scores.",
   exampleJa2:"長く勉強するために睡眠を削ると、テストの点数で裏目に出ることがある。",
   etymologyProcess:"back（後ろ）＋ fire（火）→ 火が前でなく後ろへ吹き出すと…？",
   etymologyConclusion:"back（後ろ）＋ fire（火）→ 撃った火が後ろへ吹き返して自分に当たる＝裏目に出る",
   relatedWords:[
     {word:"background",meaning:"背景",breakdown:"back（後ろ）＋ ground（底・地面）→ 絵の後ろに広がる地面"},
     {word:"backyard",meaning:"裏庭",breakdown:"back（後ろ）＋ yard（囲まれた場所）→ 家の後ろの囲まれた庭"},
     {word:"fireworks",meaning:"花火",breakdown:"fire（火）＋ work（仕事）→ 火薬職人が夜空に火で描く仕事"},
     {word:"firefighter",meaning:"消防士",breakdown:"fire（火）＋ fight（戦う）＋ er（人）→ 火と戦う人"}]},

  {id:2008,word:"cram",partOfSpeech:"他動詞・自動詞",meaning:"詰め込み勉強をする；（無理に）詰め込む",
   meanings:["自|詰め込み勉強をする","他|（無理に）詰め込む，押し込む"],
   pronunciation:"/kræm/",part:201,
   example:"Many students cram for tests the night before instead of reviewing.",
   exampleJa:"多くの生徒は、復習するかわりにテストの前夜に詰め込み勉強をする。",
   example2:"She managed to cram all her clothes into one small suitcase.",
   exampleJa2:"彼女はなんとか服を全部、小さなスーツケース1つに詰め込んだ。",
   usage:["cram for 試験（試験に向けて詰め込み勉強をする）","cram A into B（A を B に詰め込む）"],
   etymologyProcess:"cram（押し込む）→ 試験の前に頭へぎゅうぎゅう…？",
   etymologyConclusion:"cram（押し込む）→ 短い時間で頭に知識をぎゅうぎゅう押し込む＝詰め込み勉強をする",
   hook:"cram school は「塾」。袋に物を押し込むように、短時間で頭に詰める。",
   relatedWords:[
     {synonym:true,word:"stuff",meaning:"詰める；物",breakdown:"中に物を詰めこむ。cram はすき間なく無理に詰める"},
     {synonym:true,word:"pack",meaning:"荷造りする，詰める",breakdown:"かばんなどに入れる。cram は入りきらないほど詰める"},
     {synonym:true,word:"study",meaning:"勉強する",breakdown:"学ぶこと全般。cram は試験前に一気に覚える"},
     {synonym:true,word:"squeeze",meaning:"しぼる；押し込む",breakdown:"ぎゅっと押しつける。cram は中へ詰めるほうに使う"}]},

  {id:2009,word:"speculate",partOfSpeech:"自動詞",meaning:"（根拠なしに）推測する；投機する",
   meanings:["自|（根拠なしに）推測する，あれこれ考える","自|投機する"],
   pronunciation:"/ˈspekjəleɪt/",part:201,
   example:"Fans speculated about who would be the band's new singer.",
   exampleJa:"ファンたちは、誰がバンドの新しい歌手になるのかを推測した。",
   example2:"It's too early to speculate on the result of the election.",
   exampleJa2:"選挙の結果を推測するのは、まだ早すぎる。",
   usage:["speculate about [on] 事（事について推測する）"],
   etymologyProcess:"spec（見る）＋ ate（動詞）→ 見張り台から遠くを眺めて…？",
   etymologyConclusion:"spec（見る）＋ ate（動詞）→ 見張り台から遠くを眺め、見えない先をあれこれ思う＝（根拠なしに）推測する",
   etymologyMore:["先の値動きを読んで賭ける→投機する"],
   relatedWords:[
     {word:"expect",meaning:"予想する，期待する",breakdown:"ex（外へ）＋ spect（見る）→ 外を見て来るのを待つ"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ or（人）→ 試合を見る人"},
     {word:"inspect",meaning:"点検する",breakdown:"in（中へ）＋ spect（見る）→ 中までよく見る"},
     {word:"speculation",meaning:"推測；投機",breakdown:"spec（見る）＋ ation（名詞）→ 遠くを眺めてあれこれ思うこと"}]},

  {id:2010,word:"evaporate",partOfSpeech:"自動詞",meaning:"蒸発する；（希望・感情などが）消えうせる",
   meanings:["自|蒸発する","自|（希望・感情などが）消えうせる"],
   pronunciation:"/ɪˈvæpəreɪt/",part:201,
   example:"Water in puddles evaporates quickly on hot, sunny days.",
   exampleJa:"水たまりの水は、暑く晴れた日にはすぐ蒸発する。",
   example2:"My confidence evaporated when I saw the difficult first question.",
   exampleJa2:"難しい最初の問題を見たとき、私の自信は消えうせた。",
   etymologyProcess:"e（外へ）＋ vapor（湯気）＋ ate（動詞）→ 水が湯気になって…？",
   etymologyConclusion:"e（外へ）＋ vapor（湯気）＋ ate（動詞）→ 水が湯気になって外へ出ていく＝蒸発する",
   etymologyMore:["湯気のように跡形もなく消える→（希望・感情などが）消えうせる"],
   relatedWords:[
     {word:"vapor",meaning:"蒸気，湯気",breakdown:"vapor（湯気）→ 水が細かい粒になって立ちのぼったもの"},
     {word:"evaporation",meaning:"蒸発",breakdown:"e（外へ）＋ vapor（湯気）＋ ation（名詞）→ 湯気になって出ていくこと"},
     {synonym:true,word:"steam",meaning:"湯気，蒸気",breakdown:"湯をわかすと出る湯気。evaporate は水が気体になること"},
     {synonym:true,word:"disappear",meaning:"消える",breakdown:"見えなくなること全般。evaporate は水のように消える"}]},

  {id:2011,word:"vomit",partOfSpeech:"他動詞・自動詞",meaning:"（食べた物を）吐く，もどす",
   meanings:["自|（食べた物を）吐く，もどす","他|（胃の中の物を）吐き出す","名|吐いた物"],
   pronunciation:"/ˈvɑːmɪt/",part:202,
   example:"The little boy vomited in the car on the winding mountain road.",
   exampleJa:"曲がりくねった山道で、その小さな男の子は車の中で吐いた。",
   example2:"If you feel like vomiting, go to the nurse's office right away.",
   exampleJa2:"吐きそうになったら、すぐに保健室へ行きなさい。",
   etymologyProcess:"vom（吐き出す）→ 胃の中の物を口から外へ…？",
   etymologyConclusion:"vom（吐き出す）→ 胃に入った物を口から外へ出してしまう＝（食べた物を）吐く",
   hook:"ラテン語 vomere「吐き出す」がほぼそのまま。くだけた言い方は throw up。",
   relatedWords:[
     {synonym:true,word:"sick",meaning:"気分が悪い；病気の",breakdown:"feel sick で「吐き気がする」。vomit は実際に吐く"},
     {synonym:true,word:"throw",meaning:"投げる",breakdown:"throw up で「吐く」。vomit より日常的な言い方"},
     {synonym:true,word:"stomach",meaning:"胃；おなか",breakdown:"食べた物が入るところ。vomit はそこから物がもどる"},
     {synonym:true,word:"spit",meaning:"（つばなどを）吐く",breakdown:"口の中の物を吐き出す。vomit は胃の物を出す"}]},

  {id:2012,word:"frown",partOfSpeech:"自動詞",meaning:"眉をひそめる，顔をしかめる",
   meanings:["自|眉をひそめる，顔をしかめる","自|（frown on で）いい顔をしない，難色を示す","名|しかめ面"],
   pronunciation:"/fraʊn/",part:202,
   example:"The teacher frowned when she saw my messy homework.",
   exampleJa:"私の雑な宿題を見て、先生は眉をひそめた。",
   example2:"My parents frown on using smartphones at the dinner table.",
   exampleJa2:"両親は、夕食の席でスマホを使うことにいい顔をしない。",
   usage:["frown at 人・物（～に顔をしかめる）","frown on 事（事にいい顔をしない）"],
   etymologyProcess:"frown（しかめ面をする）→ 眉間にしわを寄せると…？",
   etymologyConclusion:"frown（しかめ面をする）→ 不満や疑いで眉間にしわを寄せる＝眉をひそめる",
   hook:"語源ははっきりしない。眉間のしわは不満の合図。frown on で「認めない」。",
   relatedWords:[
     {synonym:true,word:"angry",meaning:"怒った",breakdown:"怒っている気持ち。frown はそれが眉に出た顔つき"},
     {synonym:true,word:"face",meaning:"顔；直面する",breakdown:"make a face で「顔をしかめる」。frown は眉を寄せる"},
     {synonym:true,word:"worry",meaning:"心配する",breakdown:"心配で顔が曇ることも。frown は眉間にしわを寄せる"},
     {synonym:true,word:"disapprove",meaning:"よくないと思う",breakdown:"dis（否定）＋ approve（認める）。frown on に近い"}]},

  {id:2013,word:"hatch",partOfSpeech:"他動詞・自動詞",meaning:"（卵・ひなが）かえる，孵化する；（計画を）たくらむ",
   meanings:["自|（卵・ひなが）かえる，孵化する","他|（卵を）かえす","他|（計画などを）ひそかにたくらむ"],
   pronunciation:"/hætʃ/",part:202,
   example:"Five chicks hatched from the eggs early this morning.",
   exampleJa:"今朝早く、卵から5羽のひながかえった。",
   example2:"The students hatched a secret plan for their teacher's birthday.",
   exampleJa2:"生徒たちは先生の誕生日に向けて、秘密の計画をたくらんだ。",
   etymologyProcess:"hatch（卵からかえる）→ 温めた卵の殻が割れると…？",
   etymologyConclusion:"hatch（卵からかえる）→ 温めていた卵の殻が割れてひなが出てくる＝（卵・ひなが）かえる",
   etymologyMore:["卵を温めてかえすように練る→（計画などを）ひそかにたくらむ"],
   hook:"語源ははっきりしない。船の「ハッチ」（出入り口のふた）は別の語。",
   relatedWords:[
     {synonym:true,word:"egg",meaning:"卵",breakdown:"ひなが育つ殻。hatch はそこからひなが出てくる"},
     {synonym:true,word:"chick",meaning:"ひよこ，ひな",breakdown:"卵からかえったばかりの鳥"},
     {synonym:true,word:"born",meaning:"生まれた",breakdown:"be born で「生まれる」。hatch は卵から生まれる"},
     {synonym:true,word:"breed",meaning:"繁殖させる，育てる",breakdown:"動物を増やし育てる。hatch は卵をかえす場面"}]},

  {id:2014,word:"cling",partOfSpeech:"自動詞",meaning:"しがみつく，くっつく；（考えなどに）固執する",
   meanings:["自|しがみつく，くっつく","自|（考えなどに）固執する"],
   pronunciation:"/klɪŋ/",part:202,
   example:"The little girl began to cling to her mother in the crowd.",
   exampleJa:"人混みの中で、その女の子は母親にしがみつき始めた。",
   example2:"Some people still cling to the old idea that boys shouldn't cry.",
   exampleJa2:"男の子は泣くべきではないという古い考えに、今も固執する人がいる。",
   usage:["cling to 人・物（～にしがみつく）","cling to 考え（考えに固執する）"],
   etymologyProcess:"cling（しがみつく）→ 手を放さずにぴたりと…？",
   etymologyConclusion:"cling（しがみつく）→ 手を放さずに、ぴたりと体を寄せてつかまる＝しがみつく",
   etymologyMore:["つかんだ手を放さない→（考えなどに）固執する"],
   hook:"英語本来の古い語。ラップフィルムは cling film（くっつく膜）。",
   relatedWords:[
     {synonym:true,word:"hold",meaning:"持つ，つかむ",breakdown:"手でつかむこと全般。cling は必死に放さない"},
     {synonym:true,word:"stick",meaning:"くっつく",breakdown:"のりのように貼りつく。cling は抱きつくように寄る"},
     {synonym:true,word:"hug",meaning:"抱きしめる",breakdown:"愛情をこめて抱く。cling は不安で放さない"},
     {synonym:true,word:"adhere",meaning:"くっつく；守る",breakdown:"ad（～へ）＋ her（くっつく）。cling は英語本来の語"}]},

  {id:2015,word:"adhere",partOfSpeech:"自動詞",meaning:"（規則・方針を）忠実に守る；くっつく",
   meanings:["自|（規則・方針を）忠実に守る，従う","自|（物に）くっつく，付着する"],
   pronunciation:"/ədˈhɪr/",part:202,
   example:"All players must adhere to the rules of the tournament.",
   exampleJa:"選手は全員、大会の規則を忠実に守らなければならない。",
   example2:"This tape doesn't adhere well to wet surfaces.",
   exampleJa2:"このテープは、ぬれた面にはよくくっつかない。",
   usage:["adhere to 規則・方針（規則・方針を守る）"],
   etymologyProcess:"ad（～へ）＋ her（くっつく）→ 決まりにぴたりとくっついて…？",
   etymologyConclusion:"ad（～へ）＋ her（くっつく）→ 決まりにぴたりとくっついて離れない＝（規則・方針を）忠実に守る",
   relatedWords:[
     {word:"adhesive",meaning:"接着剤；粘着性の",breakdown:"ad（～へ）＋ hes（くっつく）＋ ive（形容詞）→ ぴたりとくっつく性質の"},
     {word:"hesitate",meaning:"ためらう",breakdown:"hes（くっつく）＋ ate（動詞）→ その場にくっついて足が出ない"},
     {word:"coherent",meaning:"筋の通った",breakdown:"co（共に）＋ her（くっつく）→ 話の部分どうしがくっついている"},
     {synonym:true,word:"stick",meaning:"くっつく；（to で）やり通す",breakdown:"stick to the rules とも言う。adhere はより硬い語"}]},

  {id:2016,word:"collaborate",partOfSpeech:"自動詞",meaning:"共同して働く，協同する",
   meanings:["自|共同して働く，協同する","自|（敵に）協力する，内通する"],
   pronunciation:"/kəˈlæbəreɪt/",part:202,
   example:"Scientists from ten countries collaborated on the space project.",
   exampleJa:"10か国の科学者が、その宇宙計画で共同して働いた。",
   example2:"Our class will collaborate with a school in Australia this year.",
   exampleJa2:"今年、私たちのクラスはオーストラリアの学校と協同する予定だ。",
   usage:["collaborate with 人 on 事（人と事で共同して働く）"],
   etymologyProcess:"col（共に）＋ labor（働く）＋ ate（動詞）→ みんなで一緒に…？",
   etymologyConclusion:"col（共に）＋ labor（働く）＋ ate（動詞）→ 何人かが一緒に一つの仕事をする＝共同して働く",
   relatedWords:[
     {word:"labor",meaning:"労働",breakdown:"labor（働く）→ 体や頭を使って働くこと"},
     {word:"laboratory",meaning:"実験室，研究所",breakdown:"labor（働く）＋ ory（場所）→ 研究者が働く場所"},
     {word:"collaboration",meaning:"共同作業，コラボ",breakdown:"col（共に）＋ labor（働く）＋ ation（名詞）→ 一緒に働くこと"},
     {synonym:true,word:"cooperate",meaning:"協力する",breakdown:"co（共に）＋ oper（仕事）。collaborate は共に作り上げる"}]},

  {id:2017,word:"lag",partOfSpeech:"自動詞",meaning:"（～に）遅れをとる，後れる",
   meanings:["自|（～に）遅れをとる，後れる","名|（時間の）遅れ，ずれ"],
   pronunciation:"/læɡ/",part:202,
   example:"Our town still lags behind big cities in public transportation.",
   exampleJa:"私たちの町は、公共交通でいまだに大都市に遅れをとっている。",
   example2:"I had terrible jet lag after flying back from London.",
   exampleJa2:"ロンドンから飛行機で帰ったあと、ひどい時差ぼけになった。",
   usage:["lag behind 人・物（～に遅れをとる）"],
   etymologyProcess:"lag（遅れて進む）→ みんなより後ろをのろのろ…？",
   etymologyConclusion:"lag（遅れて進む）→ みんなより後ろをのろのろついて行く＝（～に）遅れをとる",
   hook:"語源ははっきりしない。時差ぼけは jet lag、ゲームの「ラグ」も反応の遅れ。",
   relatedWords:[
     {synonym:true,word:"late",meaning:"遅れた，遅い",breakdown:"決まった時刻より遅いこと。lag は他より後ろにいる"},
     {synonym:true,word:"delay",meaning:"遅らせる；遅れ",breakdown:"予定を後へずらす。lag は差がついて遅れる"},
     {synonym:true,word:"slow",meaning:"遅い",breakdown:"速さが足りない。lag はその結果、後ろに残る"},
     {synonym:true,word:"behind",meaning:"後ろに",breakdown:"lag behind の形でよく使う"}]},

  {id:2018,word:"cater",partOfSpeech:"自動詞",meaning:"（パーティーなどの）料理を提供する；（要求・好みに）応える",
   meanings:["自|（パーティーなどの）料理を提供する，仕出しをする","自|（要求・好みに）応える，合わせる"],
   pronunciation:"/ˈkeɪtər/",part:202,
   example:"A local restaurant will cater for the wedding party next month.",
   exampleJa:"来月の結婚披露宴は、地元のレストランが料理を提供する。",
   example2:"This shop caters to young people who love anime.",
   exampleJa2:"この店は、アニメが大好きな若者の好みに応えている。",
   usage:["cater for 行事（行事の料理を提供する）","cater to [for] 客・要望（客・要望に応える）"],
   etymologyProcess:"cap（つかむ）→ 食べ物を買い付けてそろえ…？",
   etymologyConclusion:"cap（つかむ）→ 食料を買い付けてそろえ、人々に食事を出す＝（パーティーなどの）料理を提供する",
   why:"【なぜ】もとはフランス語 acater「買う」で、さらにラテン語の「つかみ取る」にさかのぼります。英語では昔、屋敷の食料を買い付ける係を cater と呼びました。食べ物をそろえて出す仕事から「料理を提供する」が生まれ、さらに相手の求めに合わせて用意する意味に広がりました。\n【つながり】catering（ケータリング）は料理の出張サービス。catch（つかまえる）も同じ「つかむ」の仲間です。",
   spelling:"cap→cat（フランス語を通って変化）",
   relatedWords:[
     {word:"catch",meaning:"つかまえる",breakdown:"chas（つかむ）→ 飛んでくる物を手でつかみ取る"},
     {word:"chase",meaning:"追いかける",breakdown:"chas（つかむ）→ つかまえようとして後を追う"},
     {word:"purchase",meaning:"購入する",breakdown:"pur（前へ）＋ chas（つかむ）→ 追い求めてつかみ、自分の物にする"},
     {synonym:true,word:"serve",meaning:"（食事を）出す",breakdown:"料理を客の前に出す。cater は料理をまるごと請け負う"}]},

  {id:2019,word:"flush",partOfSpeech:"他動詞・自動詞",meaning:"（顔が）赤くなる，紅潮する；（水を）どっと流す",
   meanings:["自|（顔が）赤くなる，紅潮する","他|（トイレなどの水を）どっと流す","名|（顔の）紅潮"],
   pronunciation:"/flʌʃ/",part:202,
   example:"Her face flushed with embarrassment when everyone laughed.",
   exampleJa:"みんなが笑うと、彼女の顔は恥ずかしさで赤くなった。",
   example2:"Don't forget to flush the toilet after you use it.",
   exampleJa2:"使ったあとは、トイレの水を流すのを忘れないで。",
   etymologyProcess:"flush（さっと流れ出る）→ 血がさっと顔に上ると…？",
   etymologyConclusion:"flush（さっと流れ出る）→ 血がさっと顔に上って、ほおが染まる＝（顔が）赤くなる",
   etymologyMore:["水がさっと勢いよく流れる→（トイレなどの水を）どっと流す"],
   hook:"語源ははっきりしない。血がさっと上るのも、水がさっと流れるのも flush。",
   relatedWords:[
     {synonym:true,word:"blush",meaning:"（恥ずかしくて）赤面する",breakdown:"照れて赤くなる。flush は怒りや熱でも赤くなる"},
     {synonym:true,word:"red",meaning:"赤い",breakdown:"turn red で「赤くなる」。flush より日常的"},
     {synonym:true,word:"flow",meaning:"流れる",breakdown:"液体が流れること全般。flush はどっと一気に"},
     {synonym:true,word:"wash",meaning:"洗う，洗い流す",breakdown:"水でよごれを落とす。flush は水の勢いで流す"}]},

  {id:2020,word:"ascribe",partOfSpeech:"他動詞",meaning:"（原因を～に）あるとする，～のせいにする",
   meanings:["他|（原因を～に）あるとする，～のせいにする","他|（作品などを～の）作だとする"],
   pronunciation:"/əˈskraɪb/",part:202,
   example:"He ascribed his success to his coach's good advice.",
   exampleJa:"彼は、自分の成功の原因がコーチのよい助言にあるとした。",
   example2:"This old poem is often ascribed to a famous monk.",
   exampleJa2:"この古い詩は、有名な僧の作だとよく考えられている。",
   usage:["ascribe A to B（A の原因［作者］を B だとする）"],
   etymologyProcess:"ad（～へ）＋ scrib（書く）→ 出来事の横に誰かの名を書き添えると…？",
   etymologyConclusion:"ad（～へ）＋ scrib（書く）→ 出来事の横に、そのもととなる名を書き添える＝（原因を～に）あるとする",
   etymologyMore:["作品に作者の名を書き添える→（作品などを～の）作だとする"],
   spelling:"ad→a（d が消えた）",
   relatedWords:[
     {word:"describe",meaning:"描写する",breakdown:"de（下へ）＋ scrib（書く）→ 見たものを書き写す"},
     {word:"script",meaning:"台本",breakdown:"script（書く）→ せりふが書かれたもの"},
     {word:"subscribe",meaning:"定期購読する，登録する",breakdown:"sub（下で）＋ scrib（書く）→ 申込書の下に名前を書く"},
     {synonym:true,word:"blame",meaning:"（～のせいにして）責める",breakdown:"悪い結果の責任を負わせる。ascribe はよい結果にも使う"}]},

  {id:2021,word:"endorse",partOfSpeech:"他動詞",meaning:"（公に）支持する，是認する；（商品を）推奨する",
   meanings:["他|（公に）支持する，是認する","他|（有名人が商品を）推奨する，宣伝する","他|（小切手などに）裏書きする"],
   pronunciation:"/ɪnˈdɔːrs/",part:203,
   example:"The mayor publicly endorsed the plan to build a new library.",
   exampleJa:"市長は、新しい図書館を建てる計画を公に支持した。",
   example2:"Many famous athletes endorse sports drinks in TV commercials.",
   exampleJa2:"多くの有名選手が、テレビのCMでスポーツ飲料を推奨している。",
   etymologyProcess:"in（上に）＋ dors（背中）→ 書類の背中側に名前を書くと…？",
   etymologyConclusion:"in（上に）＋ dors（背中）→ 書類の裏に署名して「これでよい」と認める＝（公に）支持する",
   why:"【なぜ】ラテン語 dorsum は「背中」。書類の裏（背中）に署名して保証する「裏書き」が出発点です。保証する人が名前を出して後ろ盾になることから、人や案を公に「支持する」意味に。さらに有名人が名前を貸して商品の後ろ盾になる「推奨する」にも広がりました。\n【つながり】英語の back も「背中」から「支持する」になりました（back up ＝ 後ろから支える）。",
   spelling:"in→en（フランス語を通って変化）",
   relatedWords:[
     {word:"endorsement",meaning:"支持，推奨",breakdown:"in（上に）＋ dors（背中）＋ ment（名詞）→ 裏に署名して認めること"},
     {synonym:true,word:"support",meaning:"支持する，支える",breakdown:"下から支える。endorse は公の場で賛成を表明する"},
     {synonym:true,word:"back",meaning:"背中；支持する",breakdown:"背中から支えることで「支持する」。endorse と同じ発想"},
     {synonym:true,word:"sign",meaning:"署名する",breakdown:"名前を書くこと。endorse はもとは書類の裏への署名"}]},

  {id:2022,word:"disclose",partOfSpeech:"他動詞",meaning:"（隠していた情報を）公表する，打ち明ける",
   meanings:["他|（隠していた情報を）公表する，打ち明ける","他|（隠れていた物を）あらわにする"],
   pronunciation:"/dɪsˈkloʊz/",part:203,
   example:"The company refused to disclose the names of its customers.",
   exampleJa:"その会社は、顧客の名前を公表することを拒んだ。",
   example2:"She finally disclosed her secret to her best friend after school.",
   exampleJa2:"放課後、彼女はついに親友に秘密を打ち明けた。",
   etymologyProcess:"dis（否定）＋ clos（閉じる）→ 閉じていたふたを開けると…？",
   etymologyConclusion:"dis（否定）＋ clos（閉じる）→ 閉じていたふたを開けて中身を人に見せる＝（隠していた情報を）公表する",
   relatedWords:[
     {word:"close",meaning:"閉じる",breakdown:"clos（閉じる）→ 戸やふたを閉める"},
     {word:"closet",meaning:"クローゼット，物置",breakdown:"clos（閉じる）＋ et（小さい）→ 閉じられた小部屋"},
     {word:"enclose",meaning:"同封する，囲む",breakdown:"en（中へ）＋ clos（閉じる）→ 中に入れて閉じる"},
     {word:"disclosure",meaning:"公表，開示",breakdown:"dis（否定）＋ clos（閉じる）＋ ure（名詞）→ 閉じた物を開けて見せること"}]},

  {id:2023,word:"improvise",partOfSpeech:"他動詞・自動詞",meaning:"即興で作る［演じる］；間に合わせに作る",
   meanings:["他|即興で作る［演じる］","他|（ありあわせの物で）間に合わせに作る"],
   pronunciation:"/ˈɪmprəvaɪz/",part:203,
   example:"The singer forgot the words, so she improvised new ones.",
   exampleJa:"歌手は歌詞を忘れたので、新しい歌詞を即興で作った。",
   example2:"We had no tent, so we improvised a shelter with branches.",
   exampleJa2:"テントがなかったので、私たちは枝で雨よけを間に合わせに作った。",
   etymologyProcess:"im（否定）＋ pro（前もって）＋ vis（見る）→ 前もって準備せずに…？",
   etymologyConclusion:"im（否定）＋ pro（前もって）＋ vis（見る）→ 前もって見て準備せず、その場でこしらえる＝即興で作る",
   etymologyMore:["その場にある物でこしらえる→（ありあわせの物で）間に合わせに作る"],
   relatedWords:[
     {word:"provide",meaning:"供給する，用意する",breakdown:"pro（前もって）＋ vid（見る）→ 先を見て用意しておく"},
     {word:"visit",meaning:"訪れる",breakdown:"vis（見る）＋ it（行く）→ 見に行く"},
     {word:"supervise",meaning:"監督する",breakdown:"super（上から）＋ vis（見る）→ 上から見守る"},
     {word:"vision",meaning:"視力；見通し",breakdown:"vis（見る）＋ ion（名詞）→ 見る力、先を見通す力"}]},

  {id:2024,word:"transplant",partOfSpeech:"他動詞",meaning:"（臓器などを）移植する；（植物を）植えかえる",
   meanings:["他|（臓器などを）移植する","他|（植物を）植えかえる","名|移植（手術）"],
   pronunciation:"/trænsˈplænt/",part:203,
   example:"Doctors transplanted a new heart into the young patient.",
   exampleJa:"医師たちは、その若い患者に新しい心臓を移植した。",
   example2:"We transplanted the tomato seedlings into bigger pots last week.",
   exampleJa2:"先週、私たちはトマトの苗を大きな鉢に植えかえた。",
   etymologyProcess:"trans（越えて）＋ plant（足で踏み込む）→ 植えた物を別の場所へ…？",
   etymologyConclusion:"trans（越えて）＋ plant（足で踏み込む）→ 根づいた物を別の場所へ移して植え直す＝（臓器などを）移植する",
   relatedWords:[
     {word:"plant",meaning:"植物；植える",breakdown:"plant（足で踏み込む）→ 足で土を踏み固めて植える"},
     {word:"plantation",meaning:"大農園",breakdown:"plant（足で踏み込む）＋ ation（名詞）→ 一面に作物を植えた土地"},
     {word:"transport",meaning:"輸送する",breakdown:"trans（越えて）＋ port（運ぶ）→ 向こうへ運ぶ"},
     {word:"transfer",meaning:"移す；乗り換える",breakdown:"trans（越えて）＋ fer（運ぶ）→ 別の場所へ移す"}]},

  {id:2025,word:"encompass",partOfSpeech:"他動詞",meaning:"（広い範囲を）包含する，含む",
   meanings:["他|（広い範囲を）包含する，含む","他|取り囲む"],
   pronunciation:"/ɪnˈkʌmpəs/",part:203,
   example:"The national park encompasses mountains, lakes, and several small villages.",
   exampleJa:"その国立公園は、山や湖、いくつかの小さな村を包含している。",
   example2:"Our history class encompasses events from ancient times to today.",
   exampleJa2:"私たちの歴史の授業は、古代から現代までの出来事を含んでいる。",
   etymologyProcess:"en（中へ）＋ compass（歩いて回る）→ ぐるりと歩いて回った内側に…？",
   etymologyConclusion:"en（中へ）＋ compass（歩いて回る）→ ぐるりと歩いて回った内側にまとめて入れる＝（広い範囲を）包含する",
   relatedWords:[
     {word:"compass",meaning:"方位磁針；コンパス",breakdown:"compass（歩いて回る）→ ぐるりと回って円を描く道具"},
     {synonym:true,word:"include",meaning:"含む",breakdown:"一部として入れる。encompass は広い範囲を丸ごと包む"},
     {synonym:true,word:"cover",meaning:"覆う；（範囲に）及ぶ",breakdown:"上からかぶせる。encompass は外からぐるりと囲む"},
     {synonym:true,word:"surround",meaning:"取り囲む",breakdown:"周りを囲む。encompass は中に含むことに重点"}]},

  {id:2026,word:"forge",partOfSpeech:"他動詞",meaning:"（関係などを）築き上げる；偽造する",
   meanings:["他|（関係などを）築き上げる","他|（文書・署名などを）偽造する","他|（鉄を）鍛えて作る"],
   pronunciation:"/fɔːrdʒ/",part:203,
   example:"The two schools forged a strong friendship through sports exchanges.",
   exampleJa:"2つの学校は、スポーツ交流を通して強い友情を築き上げた。",
   example2:"He was arrested for forging his boss's signature on a check.",
   exampleJa2:"彼は小切手に上司の署名を偽造して逮捕された。",
   etymologyProcess:"fabr（職人が作る）→ 鍛冶屋が鉄を打って形にするように…？",
   etymologyConclusion:"fabr（職人が作る）→ 鉄を何度も打つように時間をかけて形にする＝（関係などを）築き上げる",
   why:"【なぜ】ラテン語 fabrica は「職人の仕事場」。フランス語を通るうちに、鉄を熱して打つ「鍛冶場」を指すようになりました。鉄を何度も打って形にするように、関係や計画を「築き上げる」意味が生まれました。一方、本物そっくりに作ることから「偽造する」の意味も出てきました。\n【つながり】fabric（布地）や fabricate（でっち上げる）も同じ家族です。",
   spelling:"fabr→forg（フランス語を通って変化）",
   relatedWords:[
     {word:"fabric",meaning:"布地，織物",breakdown:"fabr（職人が作る）＋ ic（名詞）→ 職人が織って作った物"},
     {word:"fabricate",meaning:"でっち上げる；製造する",breakdown:"fabr（職人が作る）＋ ate（動詞）→ 手を加えてこしらえる"},
     {synonym:true,word:"build",meaning:"建てる，築く",breakdown:"積み上げて作る。forge は鍛えるように固める"},
     {synonym:true,word:"make",meaning:"作る",breakdown:"作ること全般。forge は力をこめて形にする"}]},

  {id:2027,word:"entangle",partOfSpeech:"他動詞",meaning:"（網・糸などに）からませる；（面倒なことに）巻き込む",
   meanings:["他|（網・糸などに）からませる","他|（面倒なことに）巻き込む"],
   pronunciation:"/ɪnˈtæŋɡl/",part:203,
   example:"A sea turtle got entangled in an old fishing net.",
   exampleJa:"1匹のウミガメが、古い漁網にからまってしまった。",
   example2:"I don't want to get entangled in their argument.",
   exampleJa2:"私は彼らの口論に巻き込まれたくない。",
   etymologyProcess:"en（中へ）＋ tangle（もつれる）→ もつれた糸の中に入ると…？",
   etymologyConclusion:"en（中へ）＋ tangle（もつれる）→ もつれた糸や網の中に入りこんで動けなくする＝（網・糸などに）からませる",
   etymologyMore:["糸にからめ取られるように→（面倒なことに）巻き込む"],
   relatedWords:[
     {word:"tangle",meaning:"もつれ；もつれさせる",breakdown:"tangle（もつれる）→ 糸や髪がからみ合った状態"},
     {synonym:true,word:"knot",meaning:"結び目",breakdown:"ひもを結んだところ。entangle はほどけないほどからむ"},
     {synonym:true,word:"trap",meaning:"わな；閉じこめる",breakdown:"わなで捕まえる。entangle は網や糸にからめ取る"},
     {synonym:true,word:"twist",meaning:"ねじる",breakdown:"ひねって巻く。entangle はからまって抜けない"}]},

  {id:2028,word:"entail",partOfSpeech:"他動詞",meaning:"（必然的に）伴う，必要とする",
   meanings:["他|（必然的に）伴う，必要とする"],
   pronunciation:"/ɪnˈteɪl/",part:203,
   example:"Becoming a doctor entails many years of hard study.",
   exampleJa:"医者になることは、何年もの厳しい勉強を必然的に伴う。",
   example2:"Being the team captain entails a lot of extra responsibility.",
   exampleJa2:"チームのキャプテンになると、多くの余分な責任が伴う。",
   etymologyProcess:"en（中へ）＋ tail（切る）→ 受け継ぐ土地に決まりが切り分けられて…？",
   etymologyConclusion:"en（中へ）＋ tail（切る）→ ある物事に、切り離せない別の物事がついてくる＝（必然的に）伴う",
   why:"【なぜ】tail は古いフランス語 taillier「切る」から。中世の法律では、土地を「受け継げる人を限って（切り分けて）」相続させることを entail と言いました。そうした土地を受け継ぐと、決まりが必ずついてきます。そこから「あることに別のことが必ずついてくる」＝「伴う」の意味になりました。\n【つながり】tailor（仕立て屋）は布を切る人、detail は細かく切り分けた部分です。",
   relatedWords:[
     {word:"detail",meaning:"細部",breakdown:"de（すっかり）＋ tail（切る）→ 細かく切り分けた部分"},
     {word:"tailor",meaning:"仕立て屋",breakdown:"tail（切る）＋ or（人）→ 布を切って服を作る人"},
     {word:"retail",meaning:"小売り",breakdown:"re（再び）＋ tail（切る）→ 大きな荷を切り分けて売る"},
     {synonym:true,word:"involve",meaning:"巻き込む；含む",breakdown:"in（中へ）＋ volve（回す）。entail は必ずついてくる"}]},

  {id:2029,word:"herald",partOfSpeech:"他動詞",meaning:"（～の）到来を告げる，先触れとなる",
   meanings:["他|（～の）到来を告げる，先触れとなる","名|先触れ，前ぶれ","名|（昔の）伝令，使者"],
   pronunciation:"/ˈherəld/",part:203,
   example:"The first cherry blossoms herald the arrival of spring in Japan.",
   exampleJa:"日本では、最初の桜の花が春の到来を告げる。",
   example2:"The first smartphones heralded a new age of communication.",
   exampleJa2:"最初のスマートフォンは、通信の新しい時代の先触れとなった。",
   etymologyProcess:"herald（伝令）→ 王の使者が大声で知らせを…？",
   etymologyConclusion:"herald（伝令）→ 使者が先に来て、これから来るものを知らせる＝（～の）到来を告げる",
   hook:"中世の herald は王の知らせを告げる使者。新聞名の Herald もここから。",
   relatedWords:[
     {synonym:true,word:"announce",meaning:"発表する，告げる",breakdown:"人々に知らせる。herald はこれから来るものを告げる"},
     {synonym:true,word:"sign",meaning:"しるし，兆し",breakdown:"何かを示すもの。herald は到来を知らせる"},
     {synonym:true,word:"messenger",meaning:"使いの者",breakdown:"知らせを運ぶ人。herald はもとは王の使者"},
     {synonym:true,word:"signal",meaning:"合図；合図する",breakdown:"何かを知らせる合図。herald は始まりの合図"}]},

  {id:2030,word:"surpass",partOfSpeech:"他動詞",meaning:"（～を）上回る，しのぐ",
   meanings:["他|（～を）上回る，しのぐ"],
   pronunciation:"/sərˈpæs/",part:203,
   example:"The new movie's ticket sales surpassed everyone's expectations this summer.",
   exampleJa:"その新作映画の興行収入は、この夏みんなの予想を上回った。",
   example2:"She hopes to surpass her personal best in the next race.",
   exampleJa2:"彼女は次のレースで、自己ベストを上回りたいと思っている。",
   etymologyProcess:"sur（上を越えて）＋ pass（通り抜ける）→ 相手の上を越えて先へ…？",
   etymologyConclusion:"sur（上を越えて）＋ pass（通り抜ける）→ 相手の上を越えて先へ抜けていく＝（～を）上回る",
   relatedWords:[
     {word:"pass",meaning:"通り過ぎる；合格する",breakdown:"pass（通り抜ける）→ そばを抜けて先へ行く"},
     {word:"passenger",meaning:"乗客",breakdown:"pass（通り抜ける）＋ er（人）→ 乗り物で通っていく人"},
     {word:"passage",meaning:"通路；一節",breakdown:"pass（通り抜ける）＋ age（名詞）→ 通り抜ける道"},
     {word:"survive",meaning:"生き残る",breakdown:"sur（上を越えて）＋ viv（生きる）→ 困難を越えて生き続ける"}]},

  {id:2031,word:"transcend",partOfSpeech:"他動詞",meaning:"（限界・違いなどを）超える，超越する",
   meanings:["他|（限界・違いなどを）超える，超越する","他|（～より）まさる"],
   pronunciation:"/trænˈsend/",part:204,
   example:"Great music can transcend differences of language and culture.",
   exampleJa:"すぐれた音楽は、言語や文化の違いを超えることができる。",
   example2:"The beauty of the view transcended anything we had imagined.",
   exampleJa2:"その景色の美しさは、私たちが想像していたどんなものにもまさっていた。",
   etymologyProcess:"trans（越えて）＋ scend（登る）→ 高い壁をよじ登って向こうへ…？",
   etymologyConclusion:"trans（越えて）＋ scend（登る）→ 高い壁をよじ登って向こう側へ越えていく＝（限界・違いなどを）超える",
   relatedWords:[
     {word:"escalator",meaning:"エスカレーター",breakdown:"scal（はしご）＋ ator（もの）→ 動いて登っていく階段"},
     {word:"descend",meaning:"降りる",breakdown:"de（下へ）＋ scend（登る）→ 登るの逆で下へ行く"},
     {word:"ascend",meaning:"登る，上がる",breakdown:"ad（～へ）＋ scend（登る）→ 上へ向かって登る"},
     {word:"transport",meaning:"輸送する",breakdown:"trans（越えて）＋ port（運ぶ）→ 向こうへ運ぶ"}]},

  {id:2032,word:"flatter",partOfSpeech:"他動詞",meaning:"お世辞を言う，おだてる",
   meanings:["他|お世辞を言う，おだてる","他|（be flattered で）うれしく思う，光栄に思う","他|（写真などが）実物よりよく見せる"],
   pronunciation:"/ˈflætər/",part:204,
   example:"He always flatters the teacher to get better grades.",
   exampleJa:"彼はよい成績をとるために、いつも先生にお世辞を言う。",
   example2:"I'm flattered that you asked me to sing at your wedding.",
   exampleJa2:"結婚式で歌ってほしいと頼まれて、光栄に思います。",
   usage:["be flattered（うれしく思う，光栄に思う）"],
   etymologyProcess:"flatter（なでる）→ 相手の気持ちをなでるように…？",
   etymologyConclusion:"flatter（なでる）→ 相手の気持ちをなでるように、ほめ言葉を並べる＝お世辞を言う",
   hook:"語源ははっきりしない。I'm flattered.（光栄です）はほめられた側の決まり文句。",
   relatedWords:[
     {synonym:true,word:"praise",meaning:"ほめる",breakdown:"よい点を認めてほめる。flatter は本心以上にほめる"},
     {synonym:true,word:"compliment",meaning:"ほめ言葉；ほめる",breakdown:"素直なほめ言葉。flatter は下心のあるほめ方"},
     {synonym:true,word:"sweet",meaning:"甘い",breakdown:"sweet talk で「甘い言葉，おだて」"},
     {synonym:true,word:"honor",meaning:"名誉，光栄",breakdown:"It's an honor. も「光栄です」。be flattered に近い"}]},

  {id:2033,word:"enact",partOfSpeech:"他動詞",meaning:"（法律を）制定する；（劇などを）演じる",
   meanings:["他|（法律を）制定する","他|（劇・場面などを）演じる"],
   pronunciation:"/ɪˈnækt/",part:204,
   example:"The government enacted a new law to protect wild animals.",
   exampleJa:"政府は、野生動物を守るための新しい法律を制定した。",
   example2:"The students enacted a famous scene from Romeo and Juliet.",
   exampleJa2:"生徒たちは『ロミオとジュリエット』の有名な場面を演じた。",
   etymologyProcess:"en（～にする）＋ act（追い立てる）→ 案を押し進めて実際に動く決まりに…？",
   etymologyConclusion:"en（～にする）＋ act（追い立てる）→ 案を押し進めて、実際に動く法令にする＝（法律を）制定する",
   etymologyMore:["場面を実際に動かして見せる→（劇・場面などを）演じる"],
   relatedWords:[
     {word:"action",meaning:"行動",breakdown:"act（追い立てる）＋ ion（名詞）→ 体を動かしてすること"},
     {word:"actor",meaning:"俳優",breakdown:"act（追い立てる）＋ or（人）→ 舞台で動いて演じる人"},
     {word:"active",meaning:"活動的な",breakdown:"act（追い立てる）＋ ive（形容詞）→ いつも動いている"},
     {word:"exact",meaning:"正確な",breakdown:"ex（外へ）＋ act（追い立てる）→ 追い出してきっちり量った"}]},

  {id:2034,word:"amend",partOfSpeech:"他動詞",meaning:"（法律・文書などを）改正する，修正する",
   meanings:["他|（法律・文書などを）改正する，修正する"],
   pronunciation:"/əˈmend/",part:204,
   example:"The club voted to amend its rules about practice times.",
   exampleJa:"その部は、練習時間に関する規則を改正することを投票で決めた。",
   example2:"The constitution has been amended several times since then.",
   exampleJa2:"憲法はそれ以来、何度か改正されてきた。",
   etymologyProcess:"ex（外へ）＋ menda（欠点）→ 欠点を外へ取り除くと…？",
   etymologyConclusion:"ex（外へ）＋ menda（欠点）→ 文の欠点を外へ取り除いて、よりよく直す＝（法律・文書などを）改正する",
   spelling:"ex→a（フランス語を通って変化）",
   relatedWords:[
     {word:"mend",meaning:"直す，修理する",breakdown:"menda（欠点）→ 欠点を取り除いて直す"},
     {word:"amendment",meaning:"改正，修正案",breakdown:"ex（外へ）＋ menda（欠点）＋ ment（名詞）→ 欠点を取り除く直し"},
     {synonym:true,word:"fix",meaning:"直す；固定する",breakdown:"壊れた物を直す。amend は文や決まりを直す"},
     {synonym:true,word:"change",meaning:"変える",breakdown:"変えること全般。amend は正式に書き直す"}]},

  {id:2035,word:"kidnap",partOfSpeech:"他動詞",meaning:"（人を）誘拐する",
   meanings:["他|（人を）誘拐する"],
   pronunciation:"/ˈkɪdnæp/",part:204,
   example:"Police arrested the men who planned to kidnap a famous singer.",
   exampleJa:"警察は、有名な歌手を誘拐しようと計画した男たちを逮捕した。",
   example2:"The boy was kidnapped but returned home safely two days later.",
   exampleJa2:"少年は誘拐されたが、2日後に無事に家へ帰った。",
   etymologyProcess:"kid（子ども）＋ nab（ひったくる）→ 子どもをさっとひったくると…？",
   etymologyConclusion:"kid（子ども）＋ nab（ひったくる）→ 子どもなど人をさっとひったくって連れ去る＝（人を）誘拐する",
   spelling:"nab→nap（泥棒仲間の言葉で、どちらの綴りも使われた）",
   relatedWords:[
     {word:"kid",meaning:"子ども",breakdown:"kid（子ども）→ もとは子ヤギ。くだけた言い方で子ども"},
     {word:"nab",meaning:"（犯人などを）捕まえる",breakdown:"nab（ひったくる）→ さっとつかまえる"},
     {synonym:true,word:"steal",meaning:"盗む",breakdown:"物をこっそり取る。kidnap は人を連れ去る"},
     {synonym:true,word:"grab",meaning:"ひっつかむ",breakdown:"急につかみ取る。kidnap は人をつかんで連れ去る"}]},

  {id:2036,word:"smuggle",partOfSpeech:"他動詞",meaning:"密輸する，こっそり持ち込む",
   meanings:["他|密輸する，こっそり持ち込む［持ち出す］"],
   pronunciation:"/ˈsmʌɡl/",part:204,
   example:"The men tried to smuggle drugs into the country by boat.",
   exampleJa:"男たちは、船で国内に麻薬を密輸しようとした。",
   example2:"He smuggled some snacks into the movie theater in his bag.",
   exampleJa2:"彼はかばんに入れて、映画館にお菓子をこっそり持ち込んだ。",
   usage:["smuggle A into B（A を B にこっそり持ち込む）"],
   etymologyProcess:"smuggle（こっそり運ぶ）→ 見つからないように国境を越えて…？",
   etymologyConclusion:"smuggle（こっそり運ぶ）→ 役人に見つからないように品物を国へ運び入れる＝密輸する",
   hook:"北ドイツ・オランダの言葉（smuggeln）から。お菓子を映画館に持ち込むのも smuggle。",
   relatedWords:[
     {synonym:true,word:"import",meaning:"輸入する",breakdown:"im（中へ）＋ port（運ぶ）。smuggle は許可なくこっそり"},
     {synonym:true,word:"secret",meaning:"秘密の",breakdown:"人に知られていない。smuggle は秘密に運ぶ"},
     {synonym:true,word:"hide",meaning:"隠す",breakdown:"見えない所に置く。smuggle は隠して運ぶ"},
     {synonym:true,word:"sneak",meaning:"こっそり動く",breakdown:"人目を避けて動く。smuggle は物をこっそり運ぶ"}]},

  {id:2037,word:"convict",partOfSpeech:"他動詞",meaning:"（～に）有罪判決を下す",
   meanings:["他|（～に）有罪判決を下す","名|受刑者，囚人"],
   pronunciation:"/kənˈvɪkt/",part:204,
   example:"The jury convicted him of stealing a car from the station.",
   exampleJa:"陪審は、駅から車を盗んだ罪で彼に有罪判決を下した。",
   example2:"She was convicted of fraud and sent to prison for three years.",
   exampleJa2:"彼女は詐欺で有罪判決を受け、3年間刑務所に送られた。",
   usage:["convict 人 of 罪（人に罪で有罪判決を下す）"],
   etymologyProcess:"con（すっかり）＋ vict（打ち勝つ）→ 法廷で相手をすっかり負かすと…？",
   etymologyConclusion:"con（すっかり）＋ vict（打ち勝つ）→ 法廷で弁明をすっかり打ち負かし、罪を示す＝（～に）有罪判決を下す",
   relatedWords:[
     {word:"victory",meaning:"勝利",breakdown:"vict（打ち勝つ）＋ ory（名詞）→ 相手に打ち勝つこと"},
     {word:"convince",meaning:"納得させる",breakdown:"con（すっかり）＋ vinc（打ち勝つ）→ 反論をすっかり負かして信じさせる"},
     {word:"conviction",meaning:"有罪判決；確信",breakdown:"con（すっかり）＋ vict（打ち勝つ）＋ ion（名詞）→ すっかり負かして決まること"},
     {synonym:true,word:"guilty",meaning:"有罪の",breakdown:"罪を犯している。convict は裁判で有罪だと決める"}]},

  {id:2038,word:"hinder",partOfSpeech:"他動詞",meaning:"（進み具合を）妨げる，じゃまする",
   meanings:["他|（進み具合を）妨げる，じゃまする"],
   pronunciation:"/ˈhɪndər/",part:204,
   example:"Heavy snow hindered the rescue team's search for the climbers.",
   exampleJa:"大雪が、救助隊による登山者の捜索を妨げた。",
   example2:"Too much worry can hinder you from doing your best.",
   exampleJa2:"心配しすぎると、全力を出すのをじゃますることがある。",
   usage:["hinder 人 from doing（人が～するのを妨げる）"],
   etymologyProcess:"hind（後ろの）→ 前へ進もうとする人を後ろに…？",
   etymologyConclusion:"hind（後ろの）→ 前へ進もうとするものを後ろに引きとめる＝（進み具合を）妨げる",
   relatedWords:[
     {word:"behind",meaning:"～の後ろに",breakdown:"be（by ＝～のところで）＋ hind（後ろの）→ 後ろ側のところに"},
     {word:"hindsight",meaning:"あと知恵",breakdown:"hind（後ろの）＋ sight（見る）→ 済んだことを後ろから見る"},
     {synonym:true,word:"prevent",meaning:"妨げる，防ぐ",breakdown:"起こらないようにする。hinder は進みを遅らせる"},
     {synonym:true,word:"block",meaning:"ふさぐ",breakdown:"通れないようにする。hinder は進みにくくする"}]},

  {id:2039,word:"inflict",partOfSpeech:"他動詞",meaning:"（打撃・苦痛などを）与える，負わせる",
   meanings:["他|（打撃・苦痛などを）与える，負わせる","他|（嫌なことを）押しつける"],
   pronunciation:"/ɪnˈflɪkt/",part:204,
   example:"The typhoon inflicted serious damage on the small island.",
   exampleJa:"台風は、その小さな島に深刻な打撃を与えた。",
   example2:"Please don't inflict your bad mood on your little sister.",
   exampleJa2:"自分の不機嫌を、妹に押しつけないでちょうだい。",
   usage:["inflict A on B（B に A を与える，負わせる）"],
   etymologyProcess:"in（上に）＋ flict（打つ）→ 相手の上に打ちつけると…？",
   etymologyConclusion:"in（上に）＋ flict（打つ）→ 相手の上に打ちつけて痛みを負わせる＝（打撃・苦痛などを）与える",
   etymologyMore:["相手に打ちつけてかぶせる→（嫌なことを）押しつける"],
   relatedWords:[
     {word:"conflict",meaning:"対立，争い",breakdown:"con（共に）＋ flict（打つ）→ 互いに打ち合う"},
     {synonym:true,word:"cause",meaning:"引き起こす",breakdown:"原因となる。inflict は害を直接負わせる"},
     {synonym:true,word:"hurt",meaning:"傷つける",breakdown:"体や心を痛める。inflict は痛みを与える側から言う"},
     {synonym:true,word:"damage",meaning:"損害；傷つける",breakdown:"inflict damage on ～ の形でよく使う"}]},

  {id:2040,word:"alleviate",partOfSpeech:"他動詞",meaning:"（苦痛・問題などを）軽くする，軽減する",
   meanings:["他|（苦痛・問題などを）軽くする，軽減する"],
   pronunciation:"/əˈliːvieɪt/",part:204,
   example:"This medicine will alleviate the pain in your back.",
   exampleJa:"この薬は、腰の痛みを軽くしてくれるでしょう。",
   example2:"Talking with friends helped alleviate my stress before the exam.",
   exampleJa2:"友達と話すことで、試験前のストレスが軽減された。",
   etymologyProcess:"ad（～へ）＋ lev（持ち上げる）→ 重い荷を持ち上げてやると…？",
   etymologyConclusion:"ad（～へ）＋ lev（持ち上げる）→ のしかかる重荷を持ち上げて軽くしてやる＝（苦痛・問題などを）軽くする",
   spelling:"ad→al（l の前で同化）",
   relatedWords:[
     {word:"elevator",meaning:"エレベーター",breakdown:"e（外へ）＋ lev（持ち上げる）＋ ator（もの）→ 人を上へ持ち上げる"},
     {word:"relief",meaning:"安心；軽減",breakdown:"re（再び）＋ lev（持ち上げる）→ 重荷が持ち上がってほっとする"},
     {word:"relieve",meaning:"和らげる",breakdown:"re（再び）＋ lev（持ち上げる）→ 重荷を持ち上げて楽にする"},
     {word:"lever",meaning:"てこ，レバー",breakdown:"lev（持ち上げる）＋ er（道具・人）→ 重い物を持ち上げる道具"}]},

  {id:2041,word:"eradicate",partOfSpeech:"他動詞",meaning:"（病気・悪習などを）根絶する，根こそぎなくす",
   meanings:["他|（病気・悪習などを）根絶する，根こそぎなくす"],
   pronunciation:"/ɪˈrædɪkeɪt/",part:205,
   example:"Scientists hope to eradicate malaria within the next twenty years.",
   exampleJa:"科学者たちは、今後20年以内にマラリアを根絶したいと考えている。",
   example2:"Our school is working hard to eradicate bullying completely.",
   exampleJa2:"私たちの学校は、いじめを完全に根絶しようと懸命に取り組んでいる。",
   etymologyProcess:"e（外へ）＋ radic（根）＋ ate（動詞）→ 根っこごと外へ引き抜くと…？",
   etymologyConclusion:"e（外へ）＋ radic（根）＋ ate（動詞）→ 雑草を根っこごと外へ引き抜く＝（病気・悪習などを）根絶する",
   relatedWords:[
     {word:"radical",meaning:"根本的な；過激な",breakdown:"radic（根）＋ al（形容詞）→ 根っこにまで届く"},
     {word:"radish",meaning:"ハツカダイコン",breakdown:"radic（根）→ 根を食べる野菜"},
     {synonym:true,word:"root",meaning:"根",breakdown:"英語本来の「根」。root out で eradicate に近い"},
     {synonym:true,word:"remove",meaning:"取り除く",breakdown:"取り去ること全般。eradicate は根こそぎなくす"}]},

  {id:2042,word:"expel",partOfSpeech:"他動詞",meaning:"（学校・組織から）追い出す，退学させる",
   meanings:["他|（学校・組織から）追い出す，退学させる","他|（ガス・空気などを）排出する"],
   pronunciation:"/ɪkˈspel/",part:205,
   example:"The school may expel students who break this rule twice.",
   exampleJa:"この規則を2度破った生徒を、学校は退学させることがある。",
   example2:"The player was expelled from the team for fighting.",
   exampleJa2:"その選手は、けんかをしてチームから追い出された。",
   usage:["expel 人 from 学校・組織（人を～から追い出す）"],
   etymologyProcess:"ex（外へ）＋ pel（押しやる）→ 仲間の輪の外へ押しやると…？",
   etymologyConclusion:"ex（外へ）＋ pel（押しやる）→ 集団の外へ力ずくで押しやる＝（学校・組織から）追い出す",
   etymologyMore:["中の空気を外へ押し出す→（ガス・空気などを）排出する"],
   relatedWords:[
     {word:"appeal",meaning:"訴える；魅力",breakdown:"ad（～へ）＋ pel（押しやる）→ 相手へ気持ちを押しやる"},
     {word:"propeller",meaning:"プロペラ",breakdown:"pro（前へ）＋ pel（押しやる）＋ er（道具・人）→ 前へ押し進める道具"},
     {word:"propel",meaning:"推進する",breakdown:"pro（前へ）＋ pel（押しやる）→ 前へ押し出す"},
     {synonym:true,word:"kick",meaning:"ける",breakdown:"kick out で「追い出す」。expel は正式な処分"}]},

  {id:2043,word:"omit",partOfSpeech:"他動詞",meaning:"（必要でないものを）省く，抜かす",
   meanings:["他|（必要でないものを）省く，抜かす","他|（うっかり）入れ忘れる"],
   pronunciation:"/oʊˈmɪt/",part:205,
   example:"You can omit this step if you are short of time.",
   exampleJa:"時間が足りなければ、この手順は省いてもよい。",
   example2:"My name was omitted from the club list by mistake.",
   exampleJa2:"手違いで、部の名簿から私の名前が省かれていた。",
   etymologyProcess:"ob（～に向かって）＋ mit（送る）→ 手元から向こうへ送り出すと…？",
   etymologyConclusion:"ob（～に向かって）＋ mit（送る）→ 手元から向こうへ送り出して手放す＝（必要でないものを）省く",
   etymologyMore:["気づかず手放してしまう→（うっかり）入れ忘れる"],
   spelling:"ob→o（b が消えた）",
   relatedWords:[
     {word:"message",meaning:"伝言",breakdown:"mis（送る）＋ age（名詞）→ 相手へ送り届ける言葉"},
     {word:"admit",meaning:"認める",breakdown:"ad（～へ）＋ mit（送る）→ 中へ送り入れるのを許す"},
     {word:"omission",meaning:"省略，脱落",breakdown:"ob（～に向かって）＋ mis（送る）＋ ion（名詞）→ 送り出して抜けたもの"},
     {synonym:true,word:"skip",meaning:"飛ばす",breakdown:"順番の途中を飛ばす。omit は正式に省く"}]},

  {id:2044,word:"discard",partOfSpeech:"他動詞",meaning:"（不要な物を）捨てる，処分する",
   meanings:["他|（不要な物・考えを）捨てる，処分する"],
   pronunciation:"/dɪˈskɑːrd/",part:205,
   example:"Please discard empty bottles in the recycling box by the door.",
   exampleJa:"空きびんは、ドアのそばのリサイクル箱に捨ててください。",
   example2:"We discarded our first idea and started again from zero.",
   exampleJa2:"私たちは最初の案を捨てて、ゼロからやり直した。",
   etymologyProcess:"dis（離れて）＋ cart（紙）→ いらない札を手元から離すと…？",
   etymologyConclusion:"dis（離れて）＋ cart（紙）→ いらない札を手元から離して場に捨てる＝（不要な物を）捨てる",
   why:"【なぜ】もとはトランプの用語で、いらない札（card）を手元から離して（dis）捨てることでした。カードゲームで役に立たない札を場に出して手放す動きから、ふだんの生活で使わなくなった物や考えを「捨てる・処分する」意味に広がりました。\n【つながり】card の語源は「紙」。cartoon（漫画）や carton（紙の箱）も同じ家族です。",
   spelling:"cart→card（フランス語を通って変化）",
   relatedWords:[
     {word:"card",meaning:"カード，札",breakdown:"cart（紙）→ 厚い紙を切った札"},
     {word:"cartoon",meaning:"漫画",breakdown:"cart（紙）＋ oon（大きい）→ 大きな紙に描いた下絵"},
     {word:"carton",meaning:"紙の箱，（牛乳の）パック",breakdown:"cart（紙）→ 厚紙を折って作った箱"},
     {synonym:true,word:"throw",meaning:"投げる",breakdown:"throw away で「捨てる」。discard より日常的"}]},

  {id:2045,word:"curb",partOfSpeech:"他動詞",meaning:"（好ましくない動きを）食い止める，抑える",
   meanings:["他|（好ましくない動きを）食い止める，抑える","名|抑制；（米）歩道の縁石"],
   pronunciation:"/kɜːrb/",part:205,
   example:"The city introduced new rules to curb traffic noise at night.",
   exampleJa:"市は、夜の交通騒音を食い止めるために新しい規則を取り入れた。",
   example2:"Try to curb your spending on snacks this month.",
   exampleJa2:"今月はお菓子に使うお金を抑えるようにしなさい。",
   etymologyProcess:"curv（曲がった）→ 馬の口にかけた曲がった鎖で…？",
   etymologyConclusion:"curv（曲がった）→ 曲がったくつわ鎖で馬の勢いを引きとめる＝（好ましくない動きを）食い止める",
   why:"【なぜ】もとはフランス語 courbe「曲がった」で、ラテン語 curvus にさかのぼります。英語では馬のあごにかける曲がった鎖（くつわ鎖）を curb と呼びました。この鎖を引いて馬の勢いを抑えたことから、勢いづいたものを「食い止める・抑える」意味になりました。\n【つながり】curve（カーブ）も同じ「曲がった」の仲間です。歩道の縁石の意味は主にアメリカ英語です。",
   spelling:"curv→curb（フランス語を通って変化）",
   relatedWords:[
     {word:"curve",meaning:"曲線，カーブ",breakdown:"curv（曲がった）→ ゆるやかに曲がった線"},
     {synonym:true,word:"control",meaning:"制御する",breakdown:"思いどおりに動かす。curb は行きすぎを抑える"},
     {synonym:true,word:"limit",meaning:"制限する",breakdown:"上限を決める。curb は勢いを食い止める"},
     {synonym:true,word:"reduce",meaning:"減らす",breakdown:"量を少なくする。curb は増えるのを抑える"}]},

  {id:2046,word:"restrain",partOfSpeech:"他動詞",meaning:"（感情・行動を）抑えつける，こらえる",
   meanings:["他|（感情・行動を）抑えつける，こらえる","他|（人・動物を）取り押さえる"],
   pronunciation:"/rɪˈstreɪn/",part:205,
   example:"She tried hard to restrain her anger during the meeting.",
   exampleJa:"彼女は会議の間、怒りを抑えつけようと懸命に努めた。",
   example2:"I couldn't restrain myself from laughing at his joke in class.",
   exampleJa2:"授業中、彼の冗談に笑うのをこらえられなかった。",
   usage:["restrain 人 from doing（人が～しないよう抑える）"],
   etymologyProcess:"re（後ろへ）＋ strain（締めつける）→ 前へ出ようとするものを締めて…？",
   etymologyConclusion:"re（後ろへ）＋ strain（締めつける）→ 前へ出ようとする気持ちを後ろへ締めつける＝（感情・行動を）抑えつける",
   etymologyMore:["暴れる体を締めつけて止める→（人・動物を）取り押さえる"],
   relatedWords:[
     {word:"strict",meaning:"厳しい",breakdown:"strict（締めつける）→ 決まりできつく締めつける"},
     {word:"restrict",meaning:"制限する",breakdown:"re（後ろへ）＋ strict（締めつける）→ 締めつけて広がらせない"},
     {word:"strain",meaning:"緊張；負担",breakdown:"strain（締めつける）→ ぴんと張って締めつけられた状態"},
     {word:"restraint",meaning:"抑制，自制",breakdown:"re（後ろへ）＋ strain（締めつける）＋ t（名詞）→ 自分を締めて抑えること"}]},

  {id:2047,word:"inhibit",partOfSpeech:"他動詞",meaning:"（成長・働きなどを）抑制する，妨げる",
   meanings:["他|（成長・働きなどを）抑制する，妨げる","他|（人に）ためらわせる"],
   pronunciation:"/ɪnˈhɪbɪt/",part:205,
   example:"Cold weather can inhibit the growth of young plants.",
   exampleJa:"寒い天候は、若い植物の成長を抑制することがある。",
   example2:"Fear of mistakes inhibits many students from speaking English.",
   exampleJa2:"間違いへの恐れが、多くの生徒に英語を話すのをためらわせている。",
   usage:["inhibit 人 from doing（人に～するのをためらわせる）"],
   etymologyProcess:"in（中へ）＋ hibit（持つ）→ 出ようとするものを中に抱えて…？",
   etymologyConclusion:"in（中へ）＋ hibit（持つ）→ 外へ出ようとするものを中に抱えて押さえておく＝（成長・働きなどを）抑制する",
   etymologyMore:["心の中で気持ちを押さえこむ→（人に）ためらわせる"],
   relatedWords:[
     {word:"exhibit",meaning:"展示する",breakdown:"ex（外へ）＋ hibit（持つ）→ 外へ持ち出して見せる"},
     {word:"prohibit",meaning:"禁止する",breakdown:"pro（前に）＋ hibit（持つ）→ 前に手をかざして止める"},
     {word:"habit",meaning:"習慣",breakdown:"hab（持つ）＋ it（～された）→ 身について持ち続けるもの"},
     {word:"inhibition",meaning:"抑制；ためらい",breakdown:"in（中へ）＋ hibit（持つ）＋ ion（名詞）→ 中に抱えて押さえること"}]},

  {id:2048,word:"hamper",partOfSpeech:"他動詞",meaning:"（自由な動きを）じゃまする，足かせになる",
   meanings:["他|（自由な動きを）じゃまする，足かせになる"],
   pronunciation:"/ˈhæmpər/",part:205,
   example:"Bad weather hampered our efforts to finish the outdoor stage.",
   exampleJa:"悪天候が、屋外ステージを仕上げようとする私たちの作業をじゃました。",
   example2:"A knee injury is hampering his performance this season.",
   exampleJa2:"ひざのけがが、今シーズンの彼のプレーの足かせになっている。",
   etymologyProcess:"hamper（重しをつける）→ 動きに重りが加わると…？",
   etymologyConclusion:"hamper（重しをつける）→ 動きに重りをつけたように鈍くする＝（自由な動きを）じゃまする",
   hook:"語源ははっきりしない。ふた付きのかご hamper は別の語。",
   relatedWords:[
     {synonym:true,word:"hinder",meaning:"妨げる",breakdown:"hind（後ろの）から。hamper は動きそのものを重くする"},
     {synonym:true,word:"prevent",meaning:"防ぐ，妨げる",breakdown:"起こらないようにする。hamper は進めにくくする"},
     {synonym:true,word:"block",meaning:"ふさぐ",breakdown:"通れなくする。hamper は通れるが進みにくい"},
     {synonym:true,word:"slow",meaning:"遅くする",breakdown:"slow down で「遅らせる」。hamper はじゃまして遅らせる"}]},

  {id:2049,word:"lure",partOfSpeech:"他動詞",meaning:"（うまい話で）誘い込む，おびき寄せる",
   meanings:["他|（うまい話で）誘い込む，おびき寄せる","名|魅力；（釣りの）ルアー，おとり"],
   pronunciation:"/lʊr/",part:205,
   example:"The shop uses big discounts to lure customers inside.",
   exampleJa:"その店は、大幅な値引きで客を店内に誘い込んでいる。",
   example2:"Many young people are drawn by the lure of city life.",
   exampleJa2:"多くの若者が、都会の暮らしの魅力に引きつけられている。",
   etymologyProcess:"lure（おとり）→ えさを見せて相手を近くへ…？",
   etymologyConclusion:"lure（おとり）→ えさやおとりを見せて相手を手元へ引き寄せる＝（うまい話で）誘い込む",
   hook:"釣りの「ルアー」がこれ。もとは鷹狩りで鷹を呼び戻すおとりの道具。",
   relatedWords:[
     {synonym:true,word:"attract",meaning:"引きつける",breakdown:"ad（～へ）＋ tract（引く）。lure はわなにかけて誘う"},
     {synonym:true,word:"invite",meaning:"招待する",breakdown:"正直に誘う。lure はうまい話で誘い込む"},
     {synonym:true,word:"tempt",meaning:"誘惑する",breakdown:"したい気にさせる。lure は実際に引き寄せる"},
     {synonym:true,word:"bait",meaning:"えさ",breakdown:"釣り針につけるえさ。lure は作り物のおとり"}]},

  {id:2050,word:"reassure",partOfSpeech:"他動詞",meaning:"（不安な人を）安心させる，元気づける",
   meanings:["他|（不安な人を）安心させる，元気づける"],
   pronunciation:"/ˌriːəˈʃʊr/",part:205,
   example:"The doctor reassured me that the surgery was quite safe.",
   exampleJa:"医者は手術がかなり安全だと言って、私を安心させた。",
   example2:"Mom's calm voice always reassures me before big tests.",
   exampleJa2:"大事な試験の前、母の落ち着いた声はいつも私を安心させてくれる。",
   usage:["reassure 人 that SV（～だと言って人を安心させる）","reassure 人 about 事（事について人を安心させる）"],
   etymologyProcess:"re（再び）＋ as（～へ）＋ sure（確かな）→ 揺らいだ心をもう一度…？",
   etymologyConclusion:"re（再び）＋ as（～へ）＋ sure（確かな）→ 揺らいだ心をもう一度確かなものにする＝（不安な人を）安心させる",
   relatedWords:[
     {word:"sure",meaning:"確かな",breakdown:"sure（確かな）→ 心配がなく、はっきりしている"},
     {word:"insurance",meaning:"保険",breakdown:"in（中へ）＋ sure（確かな）＋ ance（名詞）→ 損を確かに埋めるしくみ"},
     {word:"ensure",meaning:"確実にする",breakdown:"en（～にする）＋ sure（確かな）→ 確かな状態にする"},
     {word:"assure",meaning:"保証する，請け合う",breakdown:"as（～へ）＋ sure（確かな）→ 相手に確かだと言う"}]},
