  {id:1051,word:"sensation",partOfSpeech:"名詞",meaning:"（体で受け取る）感覚",
   meanings:["名|（体で受け取る）感覚，感じ","名|大評判，センセーション"],
   pronunciation:"/senˈseɪʃn/",part:106,
   example:"He lost all sensation in his left hand yesterday.",
   exampleJa:"彼は昨日、左手の感覚をすべて失った。",
   example2:"The new singer caused a real sensation overseas.",
   exampleJa2:"その新人歌手は、海外で本当の大評判を巻き起こした。",
   etymologyProcess:"sens（感じる）＋ ation（名詞）→ 体が受け取って感じ取るものは…？",
   etymologyConclusion:"sens（感じる）＋ ation（名詞）→ 体が受け取って感じ取るもの＝体で受け取る感覚",
   relatedWords:[
     {word:"sense",meaning:"感覚；意味",breakdown:"sens（感じる）→ 体や心で感じ取る働き"},
     {word:"sensitive",meaning:"敏感な",breakdown:"sens（感じる）＋ ive（形容詞）→ 細かいことまでよく感じ取る"},
     {word:"sensible",meaning:"分別のある",breakdown:"sens（感じる）＋ ible（できる）→ 物事を感じ分けられる"},
     {word:"nonsense",meaning:"ばかげたこと",breakdown:"non（否定）＋ sens（感じる）→ 意味が感じ取れないこと"}]},

  {id:1052,word:"code",partOfSpeech:"名詞",meaning:"規定，きまり；暗号",
   meanings:["名|規定，きまり","名|暗号","名|（プログラムの）コード"],
   pronunciation:"/koʊd/",part:106,
   example:"Our school has a strict dress code for students.",
   exampleJa:"私たちの学校には、生徒に厳しい服装の規定がある。",
   example2:"They sent the important message in a secret code.",
   exampleJa2:"彼らはその大切な伝言を、秘密の暗号で送った。",
   etymologyProcess:"cod（書板）→ 板に書きつけて定めた決まりのまとまりは…？",
   etymologyConclusion:"cod（書板）→ 板に書きつけて定めた決まりのひとそろい＝規定",
   why:"【なぜ】ラテン語 caudex は「木の幹」。薄く割った木の板を重ねて書きつけたものが codex（冊子）で、そこに書かれた法律のまとまりが「法典・規定」になりました。\n【つながり】プログラムの「コード」も暗号の「コード」も、決まった書き方のひとそろいという点で同じ。dress code は服装の決まりです。",
   relatedWords:[
     {word:"decode",meaning:"解読する",breakdown:"de（逆に）＋ cod（書板）→ 暗号を元の言葉に戻す"},
     {synonym:true,word:"rule",meaning:"規則",breakdown:"一つ一つの決まり。code はそれをまとめた体系を指す"},
     {synonym:true,word:"law",meaning:"法律",breakdown:"国の定め。code はそれを整理してまとめた法典のこと"},
     {synonym:true,word:"cipher",meaning:"暗号",breakdown:"読めなくした文字。code は決まった置きかえの体系"}]},

  {id:1053,word:"agenda",partOfSpeech:"名詞",meaning:"議題，協議事項",
   meanings:["名|議題，協議事項"],
   pronunciation:"/əˈdʒendə/",part:106,
   example:"The first item on the agenda is the budget.",
   exampleJa:"議題の最初の項目は、予算だ。",
   example2:"We added one more topic to the agenda for today.",
   exampleJa2:"私たちは今日の議題に、もう1つ話題を加えた。",
   etymologyProcess:"ag（行う）→ これから行われるべきこととして並べると…？",
   etymologyConclusion:"ag（行う）→ これから行われるべきこととして並べたもの＝議題",
   relatedWords:[
     {word:"agent",meaning:"代理人",breakdown:"ag（行う）＋ ent（人）→ 代わりに事を行う人"},
     {word:"agency",meaning:"代理店，機関",breakdown:"ag（行う）＋ cy（名詞）→ 代わりに事を行うところ"},
     {word:"agile",meaning:"すばやい，機敏な",breakdown:"ag（行う）＋ ile（できる）→ すばやく動いて事を行える"},
     {synonym:true,word:"schedule",meaning:"予定表",breakdown:"時刻まで決めた予定。agenda は会議で話す項目の一覧"}]},

  {id:1054,word:"liberty",partOfSpeech:"名詞",meaning:"自由（権）",
   meanings:["名|自由（権）"],
   pronunciation:"/ˈlɪbərti/",part:106,
   example:"The famous statue stands as a symbol of liberty.",
   exampleJa:"その有名な像は、自由の象徴として立っている。",
   example2:"People fought very hard for liberty in that country.",
   exampleJa2:"その国で、人々は自由のためにとても懸命に戦った。",
   etymologyProcess:"liber（自由な）＋ ty（名詞）→ 縛りから解かれて自分で決められると…？",
   etymologyConclusion:"liber（自由な）＋ ty（名詞）→ 縛りから解かれ、自分で決められる状態＝自由",
   relatedWords:[
     {word:"liberal",meaning:"自由な，寛大な",breakdown:"liber（自由な）＋ al（形容詞）→ 縛りをゆるめて認める"},
     {word:"deliver",meaning:"配達する",breakdown:"de（離して）＋ liber（自由な）→ 手元から解き放って届ける"},
     {word:"liberate",meaning:"解放する",breakdown:"liber（自由な）＋ ate（動詞）→ 縛りを解いて自由にする"},
     {synonym:true,word:"freedom",meaning:"自由",breakdown:"英語もとからの語。liberty は「縛りを解かれた自由」を指す"}]},

  {id:1055,word:"committee",partOfSpeech:"名詞",meaning:"委員会",
   meanings:["名|委員会"],
   pronunciation:"/kəˈmɪti/",part:106,
   example:"The committee will meet again next Friday afternoon.",
   exampleJa:"委員会は来週の金曜の午後に、また集まる。",
   example2:"She was chosen for the school festival committee.",
   exampleJa2:"彼女は文化祭の委員会に選ばれた。",
   etymologyProcess:"com（共に）＋ mit（送る）→ 仕事を共にゆだねられた人たちは…？",
   etymologyConclusion:"com（共に）＋ mit（送る）→ 仕事をまとめて任された人たちの集まり＝委員会",
   relatedWords:[
     {word:"commit",meaning:"ゆだねる；（罪を）犯す",breakdown:"com（共に）＋ mit（送る）→ 相手のもとへ身をすっかり送り込む"},
     {word:"submit",meaning:"提出する",breakdown:"sub（下で）＋ mit（送る）→ 目上の人の下へ差し出す"},
     {word:"permit",meaning:"許可する",breakdown:"per（通して）＋ mit（送る）→ 通り抜けて行かせてやる"},
     {synonym:true,word:"council",meaning:"議会，評議会",breakdown:"話し合って決める会。committee は仕事を任された小さな集まり"}]},

  {id:1056,word:"humanity",partOfSpeech:"名詞",meaning:"人類；人間らしさ",
   meanings:["名|人類","名|人間らしさ，思いやり"],
   pronunciation:"/hjuːˈmænəti/",part:106,
   example:"Climate change is a serious problem for all humanity.",
   exampleJa:"気候変動は、人類すべてにとって深刻な問題だ。",
   example2:"She showed great humanity toward the lost young children.",
   exampleJa2:"彼女は迷子の幼い子どもたちに、大きな思いやりを示した。",
   etymologyProcess:"human（人）＋ ity（名詞）→ 人であること、人すべてのまとまりは…？",
   etymologyConclusion:"human（人）＋ ity（名詞）→ 人であること、また人すべてのまとまり＝人類",
   relatedWords:[
     {word:"human",meaning:"人間（の）",breakdown:"human（人）→ ほかの生き物と区別された「人」そのもの"},
     {word:"humane",meaning:"思いやりのある",breakdown:"human（人）→ 人らしい優しさを持っている"},
     {word:"humanism",meaning:"人間中心の考え方",breakdown:"human（人）＋ ism（主義）→ 人を中心に置く考え方"},
     {synonym:true,word:"mankind",meaning:"人類",breakdown:"人という種ぜんたい。humanity は人間らしさの意味でも使う"}]},

  {id:1057,word:"mankind",partOfSpeech:"名詞",meaning:"人類，人間という種",
   meanings:["名|人類，人間という種"],
   pronunciation:"/mænˈkaɪnd/",part:106,
   example:"Fire was one of the greatest discoveries of mankind.",
   exampleJa:"火は人類の最も偉大な発見の一つだった。",
   example2:"This invention changed mankind in many deep ways.",
   exampleJa2:"この発明は、多くの深い意味で人類を変えた。",
   etymologyProcess:"kind（種）→ 人という一つの種にまとまるすべては…？",
   etymologyConclusion:"kind（種）→ 人という一つの種としてまとめたすべての人＝人類",
   hook:"man（人）＋ kind（種）。kind はもともと「同じ生まれのなかま」。",
   relatedWords:[
     {word:"kind",meaning:"種類；親切な",breakdown:"kind（種）→ 同じ生まれを持つなかま。そこから「種類」"},
     {synonym:true,word:"humanity",meaning:"人類",breakdown:"人間ぜんたい。mankind は「人という種」という言い方"},
     {synonym:true,word:"human",meaning:"人間",breakdown:"一人一人の人。mankind はその全体をひとまとめにした語"},
     {word:"kin",meaning:"親族，身内",breakdown:"kind（種）→ 同じ生まれを分け合っているなかま"}]},

  {id:1058,word:"authority",partOfSpeech:"名詞",meaning:"権威，権限",
   meanings:["名|権威，権限","名|（複数で）当局"],
   pronunciation:"/əˈθɔːrəti/",part:106,
   example:"That teacher has real authority in this noisy classroom.",
   exampleJa:"あの先生は、この騒がしい教室で本当の権威を持っている。",
   example2:"Local authorities decided to close the old stone bridge.",
   exampleJa2:"地元の当局は、その古い石の橋を閉鎖することに決めた。",
   etymologyProcess:"auth（増やす）＋ ity（名詞）→ 物事を生み出し動かす力を持っていると…？",
   etymologyConclusion:"auth（増やす）＋ ity（名詞）→ 物事を生み出し動かす力を持っていること＝権威",
   why:"【なぜ】ラテン語 auctor は augere（増やす）から出た語で、「新しく生み出し、育てる人」＝創始者・作者のことでした。そういう人の言葉には重みがあるので、auctoritas は「重み・信用」、さらに「権威・権限」になりました。\n【つながり】author（著者）、augment（増やす）、auction（競り上げる＝オークション）も同じ家族です。",
   relatedWords:[
     {word:"author",meaning:"著者",breakdown:"auth（増やす）＋ or（人）→ 作品を生み出すほうの人"},
     {word:"authorize",meaning:"権限を与える",breakdown:"auth（増やす）＋ ize（動詞）→ 物事を動かす力を与える"},
     {word:"augment",meaning:"増やす",breakdown:"aug（増やす）＋ ment（名詞）→ さらに増し加えること"},
     {synonym:true,word:"power",meaning:"力，権力",breakdown:"動かす力ぜんたい。authority は認められた正しい権限"}]},

  {id:1059,word:"justice",partOfSpeech:"名詞",meaning:"正義，公正",
   meanings:["名|正義，公正","名|裁判"],
   pronunciation:"/ˈdʒʌstɪs/",part:106,
   example:"People marched in the street demanding social justice.",
   exampleJa:"人々は社会の正義を求めて、通りを行進した。",
   example2:"The court finally brought justice to the young victims.",
   exampleJa2:"裁判所はついに、若い被害者たちに正義をもたらした。",
   etymologyProcess:"just（正しい）＋ ice（名詞）→ 正しさがきちんと行き渡っていると…？",
   etymologyConclusion:"just（正しい）＋ ice（名詞）→ 正しさがすみずみまで行き渡っていること＝正義",
   relatedWords:[
     {word:"just",meaning:"公正な；ちょうど",breakdown:"just（正しい）→ ゆがみなくまっすぐで正しい"},
     {word:"justify",meaning:"正当化する",breakdown:"just（正しい）＋ fy（する）→ 正しいと示してみせる"},
     {word:"injustice",meaning:"不正",breakdown:"in（否定）＋ just（正しい）→ 正しさが行き渡っていないこと"},
     {word:"judge",meaning:"裁判官；判断する",breakdown:"jus（正しい）＋ dic（言う）→ 法を口に出して言い渡す人"}]},

  {id:1060,word:"insurance",partOfSpeech:"名詞",meaning:"保険",
   meanings:["名|保険"],
   pronunciation:"/ɪnˈʃʊrəns/",part:106,
   example:"My parents bought insurance for their brand-new car.",
   exampleJa:"両親は、新車の保険に入った。",
   example2:"Travel insurance covers accidents during your whole trip.",
   exampleJa2:"旅行保険は、旅の間ずっと事故を補償してくれる。",
   etymologyProcess:"in（〜に）＋ sure（確かな）→ 万一のときも確かだと言えるようにすると…？",
   etymologyConclusion:"in（〜に）＋ sure（確かな）→ 万一のときも確かだと言える状態にしておく仕組み＝保険",
   relatedWords:[
     {word:"sure",meaning:"確かな",breakdown:"sure（確かな）→ 疑う余地なくはっきりしている"},
     {word:"ensure",meaning:"確実にする",breakdown:"en（〜にする）＋ sure（確かな）→ 確かな状態にしておく"},
     {word:"insure",meaning:"保険をかける",breakdown:"in（〜に）＋ sure（確かな）→ 万一に備えて確かにしておく"},
     {word:"assure",meaning:"保証する，安心させる",breakdown:"ad（〜へ）＋ sure（確かな）→ 相手に確かだと言ってやる"}]},

  {id:1061,word:"hardship",partOfSpeech:"名詞",meaning:"苦難，耐えがたさ",
   meanings:["名|苦難，耐えがたさ"],
   pronunciation:"/ˈhɑːrdʃɪp/",part:107,
   example:"The family faced great hardship after the big earthquake.",
   exampleJa:"その家族は大地震の後、大きな苦難に直面した。",
   example2:"She overcame many hardships to become a good doctor.",
   exampleJa2:"彼女はよい医者になるために、多くの苦難を乗り越えた。",
   etymologyProcess:"hard（かたい）＋ ship（名詞）→ 暮らしが固く厳しいままだと…？",
   etymologyConclusion:"hard（かたい）＋ ship（名詞）→ 暮らしが固く厳しくて耐えがたい状態＝苦難",
   relatedWords:[
     {word:"hard",meaning:"固い；難しい",breakdown:"hard（かたい）→ 力を加えても変わらないほど固い"},
     {word:"hardly",meaning:"ほとんど～ない",breakdown:"hard（かたい）＋ ly（副詞）→ 難しくてほとんどできない"},
     {word:"harden",meaning:"固くする",breakdown:"hard（かたい）＋ en（〜にする）→ 固い状態にする"},
     {synonym:true,word:"difficulty",meaning:"困難",breakdown:"やりにくさ。hardship は暮らしの厳しさ・つらさを指す"}]},

  {id:1062,word:"poverty",partOfSpeech:"名詞",meaning:"貧困",
   meanings:["名|貧困，貧しさ"],
   pronunciation:"/ˈpɑːvərti/",part:107,
   example:"Many children still live in deep poverty today.",
   exampleJa:"今日でも、多くの子どもが深い貧困の中で暮らしている。",
   example2:"The new law aims to reduce child poverty by 2030.",
   exampleJa2:"その新しい法律は、2030年までに子どもの貧困を減らすことを目指している。",
   etymologyProcess:"pover（貧しい）＋ ty（名詞）→ 暮らしに必要なものが足りないと…？",
   etymologyConclusion:"pover（貧しい）＋ ty（名詞）→ 暮らしに必要なものが足りない状態＝貧困",
   relatedWords:[
     {word:"poor",meaning:"貧しい",breakdown:"pover（貧しい）→ 持っているものが少ない"},
     {word:"impoverish",meaning:"貧しくする",breakdown:"im（中へ）＋ pover（貧しい）→ 貧しい状態へ追い込む"},
     {synonym:true,word:"need",meaning:"困窮；必要",breakdown:"足りなくて困ること。poverty はその状態が続いていること"},
     {synonym:true,word:"hunger",meaning:"飢え",breakdown:"食べ物が足りないこと。poverty は暮らし全体の不足を指す"}]},

  {id:1063,word:"chaos",partOfSpeech:"名詞",meaning:"大混乱",
   meanings:["名|大混乱，無秩序"],
   pronunciation:"/ˈkeɪɑːs/",part:107,
   example:"The sudden storm caused chaos at the busy airport.",
   exampleJa:"突然の嵐が、混雑した空港に大混乱を引き起こした。",
   example2:"Complete chaos followed the sudden and unexpected power failure.",
   exampleJa2:"突然の思いがけない停電の後、まったくの大混乱が続いた。",
   etymologyProcess:"chaos（ぽっかり開いた裂け目）→ 何の形も秩序もない状態なら…？",
   etymologyConclusion:"chaos（ぽっかり開いた裂け目）→ 何の秩序もなく入り乱れた状態＝大混乱",
   hook:"「カオス」でそのまま通じる。手がつけられないほど乱れた状態。",
   why:"【なぜ】ギリシャ語 khaos は「ぽっかり開いた裂け目・空虚」。ギリシャ神話では、世界が生まれる前の何も形のない状態を指しました。そこから「秩序のない、めちゃくちゃな状態」＝大混乱になりました。\n【つながり】カオス理論の「カオス」も同じ語。yawn（大きく口を開ける）と遠い親戚だと考えられています。",
   relatedWords:[
     {synonym:true,word:"confusion",meaning:"混乱",breakdown:"物事がごちゃごちゃになること。chaos は手のつけられない大混乱"},
     {synonym:true,word:"disorder",meaning:"無秩序",breakdown:"順序の乱れ。chaos はそれが極まってめちゃくちゃな状態"},
     {synonym:true,word:"mess",meaning:"散らかり，めちゃくちゃ",breakdown:"くだけた語。chaos はもっと大きく深刻な混乱を指す"},
     {synonym:true,word:"panic",meaning:"うろたえ",breakdown:"人が取り乱すこと。chaos は場ぜんたいの混乱を指す"}]},

  {id:1064,word:"isolation",partOfSpeech:"名詞",meaning:"孤立，隔離",
   meanings:["名|孤立，隔離"],
   pronunciation:"/ˌaɪsəˈleɪʃn/",part:107,
   example:"Long isolation made the old man very lonely.",
   exampleJa:"長い孤立が、その老人をとても寂しくさせた。",
   example2:"The village lived in isolation for many long centuries.",
   exampleJa2:"その村は、長い何世紀もの間、孤立して暮らしていた。",
   etymologyProcess:"isol（島）＋ ation（名詞）→ まわりから切り離されて島のようになると…？",
   etymologyConclusion:"isol（島）＋ ation（名詞）→ まわりから切り離されて島のようになること＝孤立",
   relatedWords:[
     {word:"isolate",meaning:"孤立させる",breakdown:"isol（島）＋ ate（動詞）→ 島のようにまわりから切り離す"},
     {word:"isle",meaning:"小島",breakdown:"isol（島）→ 水に囲まれた小さな陸地"},
     {word:"peninsula",meaning:"半島",breakdown:"pen（ほとんど）＋ isol（島）→ ほとんど島のように突き出た陸地"},
     {synonym:true,word:"loneliness",meaning:"孤独",breakdown:"ひとりで寂しい気持ち。isolation は切り離されている状態"}]},

  {id:1065,word:"region",partOfSpeech:"名詞",meaning:"地域，地方",
   meanings:["名|地域，地方"],
   pronunciation:"/ˈriːdʒən/",part:107,
   example:"This region is famous for its very fresh seafood.",
   exampleJa:"この地域は、とても新鮮な海産物で有名だ。",
   example2:"Heavy snow fell across the northern region yesterday.",
   exampleJa2:"昨日、北の地域一帯に大雪が降った。",
   etymologyProcess:"reg（治める）＋ ion（名詞）→ ひとつの決まりで治められる土地は…？",
   etymologyConclusion:"reg（治める）＋ ion（名詞）→ ひとつの決まりで治められる、ひとまとまりの土地＝地域",
   relatedWords:[
     {word:"regular",meaning:"規則正しい",breakdown:"regul（まっすぐな棒）＋ ar（形容詞）→ 棒で測ったようにそろっている"},
     {word:"regional",meaning:"地域の",breakdown:"reg（治める）＋ ion（名詞）＋ al（形容詞）→ その地域に関わる"},
     {word:"reign",meaning:"治世；君臨する",breakdown:"reg（治める）→ 王として国を治めること"},
     {synonym:true,word:"area",meaning:"地域，区域",breakdown:"広さを持つ場所。region はまとまりを持った大きな地域"}]},

  {id:1066,word:"proof",partOfSpeech:"名詞",meaning:"（決め手となる）証拠",
   meanings:["名|（決め手となる）証拠","名|（本の）校正刷り"],
   pronunciation:"/pruːf/",part:107,
   example:"The police found clear proof of his complete innocence.",
   exampleJa:"警察は、彼の完全な無実のはっきりした証拠を見つけた。",
   example2:"You need real proof before you accuse another person.",
   exampleJa2:"他人を責める前には、本当の証拠が必要だ。",
   etymologyProcess:"proof（試す）→ 試して確かめられたものは…？",
   etymologyConclusion:"proof（試す）→ 試して確かめられた、そうだと言い切れるもの＝決め手となる証拠",
   relatedWords:[
     {word:"prove",meaning:"証明する",breakdown:"prove（試す）→ 実際に試してみせて正しいと認めさせる"},
     {word:"approve",meaning:"承認する",breakdown:"ad（〜へ）＋ prove（試す）→ 試してみてよしと認める"},
     {word:"probable",meaning:"ありそうな",breakdown:"prob（試す）＋ able（できる）→ 試せば本当だと出そうな"},
     {word:"probe",meaning:"探る；探査機",breakdown:"prob（試す）→ 突いて中を試し探るもの"}]},

  {id:1067,word:"warranty",partOfSpeech:"名詞",meaning:"保証書",
   meanings:["名|（品質の）保証書，保証"],
   pronunciation:"/ˈwɔːrənti/",part:107,
   example:"This new laptop comes with a two-year warranty.",
   exampleJa:"この新しいノートパソコンには、2年の保証書が付いている。",
   example2:"The warranty does not cover any damage from water.",
   exampleJa2:"その保証書は、水によるどんな損傷も補償しない。",
   etymologyProcess:"garant（請け合う）＋ ty（名詞）→ 不具合があれば直すと請け合う紙は…？",
   etymologyConclusion:"garant（請け合う）＋ ty（名詞）→ 不具合があれば直すと請け合った書きつけ＝保証書",
   relatedWords:[
     {word:"guarantee",meaning:"保証する",breakdown:"garant（請け合う）→ 間違いないと請け合って責任を引き受ける"},
     {word:"warrant",meaning:"令状；保証する",breakdown:"garant（請け合う）→ 請け合った証しとして出す書き付け"},
     {synonym:true,word:"promise",meaning:"約束",breakdown:"こうすると言うこと。warranty は文書にした売り手の保証"},
     {synonym:true,word:"receipt",meaning:"領収書",breakdown:"買った証しの紙。warranty は直すと請け合った紙"}]},

  {id:1068,word:"principle",partOfSpeech:"名詞",meaning:"原理，原則",
   meanings:["名|原理，原則","名|（行動の）信条"],
   pronunciation:"/ˈprɪnsəpl/",part:107,
   example:"This machine works on a very simple principle.",
   exampleJa:"この機械は、とても単純な原理で動いている。",
   example2:"She never breaks her own strong moral principles.",
   exampleJa2:"彼女は自分の強い道徳の原則を、決して破らない。",
   etymologyProcess:"princip（第一の）→ いちばん初めに置かれてもとになる考えは…？",
   etymologyConclusion:"princip（第一の）→ いちばん初めに置かれ、すべてのもとになる考え＝原理",
   hook:"principle＝原則、principal＝校長・主要な。-le なら「考えのもと」。",
   relatedWords:[
     {word:"principal",meaning:"主要な；校長",breakdown:"princip（第一の）＋ al（形容詞）→ いちばん初めに来る、いちばん大事な"},
     {word:"prince",meaning:"王子",breakdown:"prim（第一の）＋ cept（取る）→ 国で第一の地位を取る者"},
     {synonym:true,word:"rule",meaning:"規則",breakdown:"守るべき決まり。principle は物事のもとになる考え方"},
     {synonym:true,word:"theory",meaning:"理論",breakdown:"筋道立てた説明。principle はその土台になる原理"}]},

  {id:1069,word:"origin",partOfSpeech:"名詞",meaning:"起源，始まり",
   meanings:["名|起源，始まり","名|生まれ，出身"],
   pronunciation:"/ˈɔːrɪdʒɪn/",part:107,
   example:"Scientists study the origin of the whole universe.",
   exampleJa:"科学者たちは、宇宙全体の起源を研究している。",
   example2:"The origin of this old custom is still unknown.",
   exampleJa2:"この古い習慣の起源は、今もわかっていない。",
   etymologyProcess:"ori（のぼり始める）→ 物事が初めて立ちのぼってきたところは…？",
   etymologyConclusion:"ori（のぼり始める）→ 物事が初めて立ちのぼってきたところ＝起源",
   relatedWords:[
     {word:"original",meaning:"最初の；独創的な",breakdown:"ori（のぼり始める）＋ al（形容詞）→ いちばん初めにあった"},
     {word:"originate",meaning:"始まる",breakdown:"ori（のぼり始める）＋ ate（動詞）→ そこから起こり始める"},
     {word:"orient",meaning:"東洋；方向づける",breakdown:"ori（のぼり始める）＋ ent（〜している）→ 太陽がのぼる側"},
     {synonym:true,word:"source",meaning:"源",breakdown:"わき出るもと。origin は物事の始まりの一点を指す"}]},

  {id:1070,word:"setting",partOfSpeech:"名詞",meaning:"環境，周囲のようす",
   meanings:["名|環境，周囲のようす","名|（機械の）設定"],
   pronunciation:"/ˈsetɪŋ/",part:107,
   example:"The hotel stands in a beautiful quiet mountain setting.",
   exampleJa:"そのホテルは、美しく静かな山の環境の中に立っている。",
   example2:"Please check the settings on your new smartphone.",
   exampleJa2:"新しいスマートフォンの設定を確認してください。",
   etymologyProcess:"set（置く）＋ ing（名詞）→ 物事が置かれているまわりのようすは…？",
   etymologyConclusion:"set（置く）＋ ing（名詞）→ 物事が置かれている、そのまわりのようす＝環境",
   relatedWords:[
     {word:"set",meaning:"置く，据える",breakdown:"set（置く）→ 物をしかるべきところに据える"},
     {word:"sunset",meaning:"日の入り",breakdown:"sun（太陽）＋ set（置く）→ 太陽が地平線に下りて据わる"},
     {word:"settle",meaning:"落ち着かせる；解決する",breakdown:"set（置く）→ 座らせて、しかるべき所に落ち着かせる"},
     {synonym:true,word:"environment",meaning:"環境",breakdown:"まわりを取り巻くもの。setting は物事が置かれた場面や背景"}]},

  {id:1071,word:"mission",partOfSpeech:"名詞",meaning:"任務，使命",
   meanings:["名|任務，使命","名|派遣団"],
   pronunciation:"/ˈmɪʃn/",part:108,
   example:"Their mission was to rescue the lost young climbers.",
   exampleJa:"彼らの任務は、遭難した若い登山者を救うことだった。",
   example2:"The space mission lasted more than six long months.",
   exampleJa2:"その宇宙の任務は、6か月以上の長さにわたった。",
   etymologyProcess:"mis（送る）＋ ion（名詞）→ 送り出されて果たすよう与えられた役目は…？",
   etymologyConclusion:"mis（送る）＋ ion（名詞）→ 送り出されて果たすように与えられた役目＝任務",
   relatedWords:[
     {word:"submit",meaning:"提出する",breakdown:"sub（下で）＋ mit（送る）→ 目上の人の下へ差し出す"},
     {word:"permit",meaning:"許可する",breakdown:"per（通して）＋ mit（送る）→ 通り抜けて行かせてやる"},
     {word:"dismiss",meaning:"退ける",breakdown:"dis（離れて）＋ mis（送る）→ 向こうへ送り出して取り合わない"},
     {word:"transmit",meaning:"送り伝える",breakdown:"trans（越えて）＋ mit（送る）→ 境を越えて向こうへ送る"}]},

  {id:1072,word:"project",partOfSpeech:"名詞",meaning:"（大きな）計画，事業",
   meanings:["名|（大きな）計画，事業"],
   pronunciation:"/ˈprɑːdʒekt/",part:108,
   example:"Our class started a project about local town history.",
   exampleJa:"私たちのクラスは、地元の町の歴史についての計画を始めた。",
   example2:"The big city project will take three more years.",
   exampleJa2:"その大きな市の計画は、あと3年かかるだろう。",
   etymologyProcess:"pro（前へ）＋ ject（投げる）→ 考えを前へ投げ出して形にすると…？",
   etymologyConclusion:"pro（前へ）＋ ject（投げる）→ 考えを前方へ投げ出して形にしていくもの＝大きな計画",
   relatedWords:[
     {word:"reject",meaning:"拒む",breakdown:"re（後ろへ）＋ ject（投げる）→ 投げ返して受け取らない"},
     {word:"object",meaning:"物；反対する",breakdown:"ob（向かい合って）＋ ject（投げる）→ 目の前に投げ出されたもの"},
     {word:"subject",meaning:"科目；主題",breakdown:"sub（下で）＋ ject（投げる）→ 下に置かれて扱われるもの"},
     {word:"inject",meaning:"注射する",breakdown:"in（中へ）＋ ject（投げる）→ 中へ勢いよく押し込む"}]},

  {id:1073,word:"monument",partOfSpeech:"名詞",meaning:"記念碑",
   meanings:["名|記念碑，記念建造物"],
   pronunciation:"/ˈmɑːnjumənt/",part:108,
   example:"A tall stone monument stands in the center of town.",
   exampleJa:"高い石の記念碑が、町の中心に立っている。",
   example2:"They built a monument for the brave young soldiers.",
   exampleJa2:"彼らは勇敢な若い兵士たちのために、記念碑を建てた。",
   etymologyProcess:"mon（思い出させる）＋ ment（名詞）→ 後の世に思い出させるため建てるものは…？",
   etymologyConclusion:"mon（思い出させる）＋ ment（名詞）→ 後の世に思い出させるために建てたもの＝記念碑",
   relatedWords:[
     {word:"monitor",meaning:"監視する；モニター",breakdown:"mon（思い出させる）＋ or（もの）→ 注意を促して見張るもの"},
     {word:"summon",meaning:"呼び出す",breakdown:"sub（下で）＋ mon（思い出させる）→ 下から呼び立てて来させる"},
     {word:"monster",meaning:"怪物",breakdown:"mon（思い出させる）→ 神の警告を示すものと考えられた生き物"},
     {synonym:true,word:"memorial",meaning:"記念の，追悼の",breakdown:"心にとどめるためのもの。monument は建てられた碑そのもの"}]},

  {id:1074,word:"revolution",partOfSpeech:"名詞",meaning:"革命",
   meanings:["名|革命","名|回転，公転"],
   pronunciation:"/ˌrevəˈluːʃn/",part:108,
   example:"The French Revolution changed Europe in many deep ways.",
   exampleJa:"フランス革命は、多くの深い点でヨーロッパを変えた。",
   example2:"Smartphones brought a real revolution in our daily communication.",
   exampleJa2:"スマートフォンは、私たちの日常の連絡に本当の革命をもたらした。",
   etymologyProcess:"re（再び）＋ volve（回す）→ 世の中をぐるりと回してしまうと…？",
   etymologyConclusion:"re（再び）＋ volve（回す）→ 世の中をぐるりと回してひっくり返すこと＝革命",
   relatedWords:[
     {word:"revolve",meaning:"回転する",breakdown:"re（再び）＋ volve（回す）→ 同じところをぐるぐると回る"},
     {word:"involve",meaning:"巻き込む",breakdown:"in（中へ）＋ volve（回す）→ 中へ巻き込んでしまう"},
     {word:"evolve",meaning:"進化する",breakdown:"e（外へ）＋ volve（回す）→ 巻物を開くように少しずつ展開する"},
     {word:"volume",meaning:"量；巻",breakdown:"volve（回す）→ 巻いた巻物。そこから「巻」「かさ」へ"}]},

  {id:1075,word:"contract",partOfSpeech:"名詞",meaning:"契約",
   meanings:["名|契約，契約書"],
   pronunciation:"/ˈkɑːntrækt/",part:108,
   example:"They signed a two-year contract with the large company.",
   exampleJa:"彼らはその大きな会社と、2年の契約を結んだ。",
   example2:"We must read the contract carefully before signing it.",
   exampleJa2:"署名する前に、その契約を注意深く読まなければならない。",
   etymologyProcess:"con（共に）＋ tract（引く）→ 互いを引き寄せて結びつけると…？",
   etymologyConclusion:"con（共に）＋ tract（引く）→ 互いを引き寄せて固く結びつけた約束＝契約",
   relatedWords:[
     {word:"attract",meaning:"引きつける",breakdown:"ad（〜へ）＋ tract（引く）→ 自分のほうへぐっと引き寄せる"},
     {word:"extract",meaning:"取り出す",breakdown:"ex（外へ）＋ tract（引く）→ 外へ引っぱり出す"},
     {word:"tractor",meaning:"トラクター",breakdown:"tract（引く）＋ or（もの）→ 重い機械を引っぱる車"},
     {word:"subtract",meaning:"引き算する",breakdown:"sub（下で）＋ tract（引く）→ 下から差し引く"}]},

  {id:1076,word:"infrastructure",partOfSpeech:"名詞",meaning:"社会基盤，インフラ",
   meanings:["名|社会基盤，インフラ"],
   pronunciation:"/ˈɪnfrəstrʌktʃər/",part:108,
   example:"The country needs better infrastructure for clean water.",
   exampleJa:"その国は、きれいな水のためのよりよい社会基盤を必要としている。",
   example2:"Roads and bridges are part of our daily infrastructure.",
   exampleJa2:"道路と橋は、私たちの日々の社会基盤の一部だ。",
   etymologyProcess:"infra（下に）＋ struct（積み上げる）→ 社会の下で全体を支えるものは…？",
   etymologyConclusion:"infra（下に）＋ struct（積み上げる）→ 社会の下で全体を支えるように築かれたもの＝社会基盤",
   relatedWords:[
     {word:"structure",meaning:"構造，建造物",breakdown:"struct（積み上げる）＋ ure（名詞）→ 積み上げて組み立てられたもの"},
     {word:"construct",meaning:"建設する",breakdown:"con（共に）＋ struct（積み上げる）→ 材料を積み上げて造る"},
     {word:"instruct",meaning:"指示する，教える",breakdown:"in（中へ）＋ struct（積み上げる）→ 心の中に知識を積み上げる"},
     {word:"destroy",meaning:"破壊する",breakdown:"de（逆に）＋ stroy（積み上げる）→ 積み上げたものを逆に崩す"}]},

  {id:1077,word:"negotiate",partOfSpeech:"他動詞",meaning:"交渉する",
   meanings:["他|交渉する，取り決める"],
   pronunciation:"/nɪˈɡoʊʃieɪt/",part:108,
   example:"The two countries will negotiate a new trade deal.",
   exampleJa:"両国は、新しい貿易協定を交渉するだろう。",
   example2:"She negotiated a better price for the old bike.",
   exampleJa2:"彼女はその古い自転車の、よりよい値段を交渉した。",
   etymologyProcess:"neg（いいえと言う）＋ oti（ひま）→ ひまではないと言って商談に入ると…？",
   etymologyConclusion:"neg（いいえと言う）＋ oti（ひま）→ ひまではないと商談をまとめにかかる＝交渉する",
   why:"【なぜ】ラテン語 negotium は neg（〜でない）＋ otium（ひま）で、「ひまでないこと」＝仕事・商売のことでした。商売の話し合いをすることから「交渉する」になりました。\n【つながり】negative（否定の）、neglect（気にとめない）も neg の家族。イタリア語で店を negozio と言うのも同じ語です。",
   relatedWords:[
     {word:"negative",meaning:"否定の",breakdown:"neg（いいえと言う）＋ ive（形容詞）→ 打ち消す向きの"},
     {word:"neglect",meaning:"おろそかにする",breakdown:"neg（いいえと言う）＋ lect（拾う）→ 拾い上げずに放っておく"},
     {word:"deny",meaning:"否定する",breakdown:"de（すっかり）＋ ny（いいえと言う）→ きっぱりと否と言う"},
     {synonym:true,word:"bargain",meaning:"値切る，取引する",breakdown:"値段をやりとりすること。negotiate は条件全体を話し合う"}]},

  {id:1078,word:"cooperate",partOfSpeech:"自動詞",meaning:"協力する",
   meanings:["自|協力する"],
   pronunciation:"/koʊˈɑːpəreɪt/",part:108,
   example:"The two schools cooperate on a large recycling project.",
   exampleJa:"2つの学校が、大きなリサイクル計画で協力している。",
   example2:"Everyone cooperated to clean the park last Sunday morning.",
   exampleJa2:"先週の日曜の朝、みんなが公園を掃除するために協力した。",
   etymologyProcess:"co（共に）＋ oper（仕事）→ 同じ仕事に共に手を出すと…？",
   etymologyConclusion:"co（共に）＋ oper（仕事）→ 同じ仕事に共に手を出して進めていく＝協力する",
   relatedWords:[
     {word:"operate",meaning:"操作する；手術する",breakdown:"oper（仕事）＋ ate（動詞）→ 仕事として実際に動かす"},
     {word:"opera",meaning:"オペラ",breakdown:"opera（仕事）→ 手をかけて作り上げた大きな作品"},
     {word:"cooperation",meaning:"協力",breakdown:"co（共に）＋ oper（仕事）＋ ation（名詞）→ 共に手を出して進めること"},
     {synonym:true,word:"collaborate",meaning:"共同で取り組む",breakdown:"共に働くこと。cooperate は相手に合わせて助け合うこと"}]},

  {id:1079,word:"restore",partOfSpeech:"他動詞",meaning:"修復する；回復させる",
   meanings:["他|修復する，元に戻す","他|（健康・秩序）を回復させる"],
   pronunciation:"/rɪˈstɔːr/",part:108,
   example:"They will restore the old stone castle next year.",
   exampleJa:"彼らは来年、その古い石の城を修復する。",
   example2:"A good night's sleep restored his energy completely.",
   exampleJa2:"ぐっすり眠ったことが、彼の元気を完全に回復させた。",
   etymologyProcess:"re（元へ）＋ staur（立てる）→ 崩れたものを元どおり立て直すと…？",
   etymologyConclusion:"re（元へ）＋ staur（立てる）→ 崩れたものを元どおりに立て直す＝修復する",
   relatedWords:[
     {word:"restaurant",meaning:"レストラン",breakdown:"re（元へ）＋ staur（立てる）→ 食べて元気を立て直すための店"},
     {word:"restoration",meaning:"修復，復元",breakdown:"re（元へ）＋ staur（立てる）＋ ation（名詞）→ 元どおりに立て直すこと"},
     {word:"store",meaning:"蓄える；店",breakdown:"staur（立てる）→ 蓄えを積み立てておくところ"},
     {synonym:true,word:"recover",meaning:"回復する",breakdown:"元気や物を取り戻すこと。restore は人や物を元へ戻す"}]},

  {id:1080,word:"found",partOfSpeech:"他動詞",meaning:"創立する",
   meanings:["他|創立する，設立する"],
   pronunciation:"/faʊnd/",part:108,
   example:"They founded this school over a hundred years ago.",
   exampleJa:"彼らは100年以上前に、この学校を創立した。",
   example2:"The company was founded by two young engineers.",
   exampleJa2:"その会社は、2人の若い技術者によって創立された。",
   etymologyProcess:"found（底）→ 底に土台を据えて組織を起こすと…？",
   etymologyConclusion:"found（底）→ 底に土台を据えて、新しく組織を起こす＝創立する",
   hook:"find の過去形 found と同じつづりだが別の語。foundation（土台）の found。",
   relatedWords:[
     {word:"foundation",meaning:"土台，基礎；財団",breakdown:"found（底）＋ ation（名詞）→ 底に据えられた土台"},
     {word:"fundamental",meaning:"基本的な",breakdown:"fund（底）＋ ment（名詞）＋ al（形容詞）→ いちばん底を成している"},
     {word:"profound",meaning:"深い",breakdown:"pro（前へ）＋ found（底）→ 底のほうまで届いている"},
     {synonym:true,word:"establish",meaning:"設立する",breakdown:"しっかり打ち立てること。found は土台を据えて始めること"}]},

  {id:1081,word:"conservative",partOfSpeech:"形容詞",meaning:"保守的な",
   meanings:["形|保守的な","形|控えめな，堅実な"],
   pronunciation:"/kənˈsɜːrvətɪv/",part:109,
   example:"My grandfather has very conservative ideas about education.",
   exampleJa:"祖父は教育について、とても保守的な考えを持っている。",
   example2:"The small town remained conservative for a very long time.",
   exampleJa2:"その小さな町は、とても長い間ずっと保守的なままだった。",
   etymologyProcess:"con（すっかり）＋ serv（守る）→ 今あるやり方をすっかり守ろうとすると…？",
   etymologyConclusion:"con（すっかり）＋ serv（守る）→ 今あるやり方をすっかり守ろうとする＝保守的な",
   relatedWords:[
     {word:"preserve",meaning:"保存する",breakdown:"pre（先に）＋ serv（守る）→ 先回りして傷まないように守る"},
     {word:"reserve",meaning:"取っておく",breakdown:"re（後ろへ）＋ serv（守る）→ 後のために取り置いて守る"},
     {word:"observe",meaning:"観察する",breakdown:"ob（〜に向かって）＋ serv（守る）→ 目を離さずじっと見守る"},
     {word:"conserve",meaning:"保存する，節約する",breakdown:"con（すっかり）＋ serv（守る）→ 減らさないようにすっかり守る"}]},

  {id:1082,word:"affair",partOfSpeech:"名詞",meaning:"事柄，情勢",
   meanings:["名|事柄，出来事","名|（複数で）情勢，事情"],
   pronunciation:"/əˈfer/",part:109,
   example:"The teacher handled the whole affair very calmly.",
   exampleJa:"先生はその事柄全体を、とても冷静に扱った。",
   example2:"Current affairs are covered well in this weekly magazine.",
   exampleJa2:"時事の情勢は、この週刊誌でよく取り上げられている。",
   etymologyProcess:"ad（〜へ）＋ fac（作る）→ これからしなければならないことは…？",
   etymologyConclusion:"ad（〜へ）＋ fac（作る）→ これからしなければならない、ひとまとまりのこと＝事柄",
   relatedWords:[
     {word:"fact",meaning:"事実",breakdown:"fact（作る）→ 実際に作り出されて起きたこと"},
     {word:"factory",meaning:"工場",breakdown:"fact（作る）＋ ory（場所）→ 物を作るための場所"},
     {word:"facility",meaning:"施設，設備",breakdown:"facil（しやすい）＋ ity（名詞）→ 物事をしやすくする設備"},
     {synonym:true,word:"matter",meaning:"事柄，問題",breakdown:"扱うべきこと。affair は人が関わる出来事や情勢を指す"}]},

  {id:1083,word:"agency",partOfSpeech:"名詞",meaning:"代理店；（政府の）機関",
   meanings:["名|代理店","名|（政府の）機関，庁"],
   pronunciation:"/ˈeɪdʒənsi/",part:109,
   example:"A travel agency arranged the whole school trip.",
   exampleJa:"旅行の代理店が、修学旅行全体を手配した。",
   example2:"The government agency published a new safety report.",
   exampleJa2:"その政府機関は、新しい安全報告書を公表した。",
   etymologyProcess:"ag（行う）＋ cy（名詞）→ 人に代わって事を行うところは…？",
   etymologyConclusion:"ag（行う）＋ cy（名詞）→ 人に代わって事を行う役目を持つところ＝代理店",
   relatedWords:[
     {word:"agent",meaning:"代理人",breakdown:"ag（行う）＋ ent（人）→ 代わりに事を行う人"},
     {word:"agenda",meaning:"議題",breakdown:"ag（行う）→ これから行われるべきこととして並べたもの"},
     {word:"active",meaning:"活発な",breakdown:"act（追い立てる）＋ ive（形容詞）→ よく動いて事を進める"},
     {synonym:true,word:"office",meaning:"事務所，役所",breakdown:"仕事をする場所。agency は人の代わりに動く組織を指す"}]},

  {id:1084,word:"council",partOfSpeech:"名詞",meaning:"議会，評議会",
   meanings:["名|議会，評議会","名|（生徒会などの）委員会"],
   pronunciation:"/ˈkaʊnsl/",part:109,
   example:"The city council decided to build a new library.",
   exampleJa:"市議会は、新しい図書館を建てることに決めた。",
   example2:"Our student council meets every Monday after school.",
   exampleJa2:"私たちの生徒会は、毎週月曜の放課後に集まる。",
   etymologyProcess:"con（共に）＋ cil（呼ぶ）→ 人々を共に呼び集めて話し合うと…？",
   etymologyConclusion:"con（共に）＋ cil（呼ぶ）→ 人々を共に呼び集めて話し合う会＝議会",
   why:"【なぜ】ラテン語 concilium は con（共に）＋ calare（呼ぶ）で、「人々を呼び集めること」。そこから呼び集めて話し合う「会議・議会」になりました。\n【つながり】つづりの似た counsel（助言）は consulere（相談する）から出た別の語です。council は「呼び集めた会」、counsel は「助言」と覚えます。",
   relatedWords:[
     {synonym:true,word:"call",meaning:"呼ぶ",breakdown:"声を上げて招くこと。concilium の calare と同じ「呼ぶ」仲間"},
     {word:"reconcile",meaning:"和解させる",breakdown:"re（再び）＋ cil（呼ぶ）→ 再び呼び戻して仲直りさせる"},
     {synonym:true,word:"committee",meaning:"委員会",breakdown:"仕事を任された小さな集まり。council は話し合って決める会"},
     {synonym:true,word:"assembly",meaning:"集会，議会",breakdown:"集まること。council は決める権限を持った会を指す"}]},

  {id:1085,word:"kingdom",partOfSpeech:"名詞",meaning:"王国；（動植物の）界",
   meanings:["名|王国","名|（動植物の）界"],
   pronunciation:"/ˈkɪŋdəm/",part:109,
   example:"The small kingdom lasted for over three whole centuries.",
   exampleJa:"その小さな王国は、3世紀以上にわたって続いた。",
   example2:"Whales belong to the animal kingdom, not to fish.",
   exampleJa2:"クジラは魚ではなく、動物界に属している。",
   etymologyProcess:"king（王）→ 王が治めているひとまとまりの国は…？",
   etymologyConclusion:"king（王）→ 王が治めている国、またその一つのまとまり＝王国",
   hook:"-dom は「〜の状態・範囲」。freedom（自由の状態）と同じ語尾。",
   relatedWords:[
     {word:"king",meaning:"王",breakdown:"king（王）→ 一族を率いて国を治める者"},
     {synonym:true,word:"empire",meaning:"帝国",breakdown:"皇帝が治める広い国。kingdom は王が治める国を指す"},
     {synonym:true,word:"realm",meaning:"王国，領域",breakdown:"支配の及ぶ範囲。kingdom は王のいる国を指す"},
     {word:"kingly",meaning:"王らしい，堂々とした",breakdown:"king（王）＋ ly（〜のような）→ 王にふさわしいようす"}]},

  {id:1086,word:"republic",partOfSpeech:"名詞",meaning:"共和国",
   meanings:["名|共和国"],
   pronunciation:"/rɪˈpʌblɪk/",part:109,
   example:"France became a republic more than two centuries ago.",
   exampleJa:"フランスは、2世紀以上前に共和国になった。",
   example2:"The new republic held its first free election.",
   exampleJa2:"その新しい共和国は、最初の自由な選挙を行った。",
   etymologyProcess:"res（物事）＋ publ（人々）→ 国を人々みんなの物事として治めると…？",
   etymologyConclusion:"res（物事）＋ publ（人々）→ 国を人々みんなの物事として治める仕組みの国＝共和国",
   why:"【なぜ】ラテン語 res publica は「公のもの・みんなの物事」。国を王ひとりのものではなく、市民みんなのものとして治める仕組みを指しました。そこから「共和国」になりました。\n【つながり】public（公の）、publish（世に出す）も同じ家族。国名にある Republic はこの語です。",
   relatedWords:[
     {word:"public",meaning:"公の，公共の",breakdown:"publ（人々）→ 人々みんなに関わる"},
     {word:"publish",meaning:"出版する",breakdown:"publ（人々）→ 人々みんなが読める状態にして世に出す"},
     {word:"publication",meaning:"出版；出版物",breakdown:"publ（人々）＋ ation（名詞）→ 人々に広く出すこと"},
     {synonym:true,word:"democracy",meaning:"民主主義",breakdown:"人々が決める仕組み。republic は王を持たない国の形"}]},

  {id:1087,word:"empire",partOfSpeech:"名詞",meaning:"帝国",
   meanings:["名|帝国"],
   pronunciation:"/ˈempaɪər/",part:109,
   example:"The Roman Empire lasted for many hundreds of years.",
   exampleJa:"ローマ帝国は、何百年もの間続いた。",
   example2:"That old empire once ruled half of the world.",
   exampleJa2:"その古い帝国は、かつて世界の半分を支配した。",
   etymologyProcess:"imper（命じる）→ 一人が命じて広く治める大きな国は…？",
   etymologyConclusion:"imper（命じる）→ 一人の皇帝が命じて広く治める大きな国＝帝国",
   relatedWords:[
     {word:"emperor",meaning:"皇帝",breakdown:"imper（命じる）＋ or（人）→ 命じて国ぜんたいを治める人"},
     {word:"imperial",meaning:"帝国の",breakdown:"imper（命じる）＋ al（形容詞）→ 帝国に関わる"},
     {synonym:true,word:"kingdom",meaning:"王国",breakdown:"王が治める国。empire はいくつもの国を従えた大きな国"},
     {synonym:true,word:"rule",meaning:"支配する，統治する",breakdown:"治めること。empire は皇帝が広く支配する国のまとまり"}]},

  {id:1088,word:"aid",partOfSpeech:"名詞",meaning:"援助，救援",
   meanings:["名|援助，救援","他|援助する"],
   pronunciation:"/eɪd/",part:109,
   example:"The country sent food aid to the flooded area.",
   exampleJa:"その国は、水害にあった地域に食料の援助を送った。",
   example2:"Teachers gave first aid to the injured young student.",
   exampleJa2:"先生たちは、けがをした若い生徒に応急手当をした。",
   etymologyProcess:"aid（助ける）→ 困っている人に手を差し伸べて支えると…？",
   etymologyConclusion:"aid（助ける）→ 困っている人に手を差し伸べて支えること＝援助",
   hook:"first aid（応急手当）でおなじみ。困った人に差し伸べる手が芯。",
   relatedWords:[
     {synonym:true,word:"help",meaning:"助け",breakdown:"ふつうの「助け」。aid は組織的・公的な援助に使うことが多い"},
     {synonym:true,word:"support",meaning:"支援",breakdown:"支えること。aid は物やお金を送る援助を指すことが多い"},
     {synonym:true,word:"assist",meaning:"手伝う",breakdown:"そばで手を貸すこと。aid は困っている人を助けること"},
     {synonym:true,word:"relief",meaning:"救援",breakdown:"苦しみを取り除く救い。aid はそのために送る物やお金"}]},

  {id:1089,word:"reform",partOfSpeech:"他動詞",meaning:"改革する",
   meanings:["他|改革する，改める","名|改革"],
   pronunciation:"/rɪˈfɔːrm/",part:109,
   example:"The government plans to reform the whole tax system.",
   exampleJa:"政府は、税の仕組み全体を改革する計画だ。",
   example2:"Many people want to reform the old school rules.",
   exampleJa2:"多くの人が、古い校則を改革したいと思っている。",
   etymologyProcess:"re（再び）＋ form（形）→ 古くなった仕組みをよい形に作り直すと…？",
   etymologyConclusion:"re（再び）＋ form（形）→ 古くなった仕組みを、もう一度よい形に作り直す＝改革する",
   relatedWords:[
     {word:"form",meaning:"形；形づくる",breakdown:"form（形）→ 目に見えるまとまった形"},
     {word:"inform",meaning:"知らせる",breakdown:"in（中へ）＋ form（形）→ 相手の頭の中に形を作ってやる"},
     {word:"transform",meaning:"変える，変形させる",breakdown:"trans（越えて）＋ form（形）→ 境を越えて別の形に変える"},
     {word:"uniform",meaning:"制服；均一の",breakdown:"uni（1つの）＋ form（形）→ みんな同じ一つの形"}]},

  {id:1090,word:"minister",partOfSpeech:"名詞",meaning:"大臣",
   meanings:["名|大臣","名|（教会の）牧師"],
   pronunciation:"/ˈmɪnɪstər/",part:109,
   example:"The minister of education announced a big new plan.",
   exampleJa:"教育の大臣が、大きな新しい計画を発表した。",
   example2:"Each minister reported to the prime minister directly.",
   exampleJa2:"それぞれの大臣が、首相に直接報告した。",
   etymologyProcess:"min（小さい）→ 王より小さな者として国の仕事を預かると…？",
   etymologyConclusion:"min（小さい）→ 王より小さな者として仕え、国の仕事を預かる人＝大臣",
   why:"【なぜ】ラテン語 minister は「召使い・小さいほうの者」。主人に仕える者という意味でした。やがて国王に仕えて政治を預かる人を指すようになり、「大臣」になりました。\n【つながり】minimum（最小）、minor（小さいほうの）も同じ min の家族。教会の「牧師」も minister と言います。",
   relatedWords:[
     {word:"minimum",meaning:"最小限",breakdown:"min（小さい）→ これ以上小さくできない、いちばん小さい量"},
     {word:"minor",meaning:"小さいほうの",breakdown:"min（小さい）＋ or（より〜な）→ 二つのうち小さいほうの"},
     {word:"minute",meaning:"分；ごく小さい",breakdown:"min（小さい）→ 時間を細かく小さく分けた一つ"},
     {synonym:true,word:"secretary",meaning:"（米国の）長官；秘書",breakdown:"米国では大臣を Secretary と呼ぶ。minister は英国や日本で使う"}]},

  {id:1091,word:"parliament",partOfSpeech:"名詞",meaning:"議会（国会）",
   meanings:["名|議会（国会）"],
   pronunciation:"/ˈpɑːrləmənt/",part:110,
   example:"The British Parliament meets in a famous old building.",
   exampleJa:"英国の議会は、有名な古い建物で開かれる。",
   example2:"Parliament passed the new law last Thursday afternoon.",
   exampleJa2:"議会は先週木曜の午後、新しい法律を可決した。",
   etymologyProcess:"parl（話す）＋ ment（名詞）→ 集まって話し合い国の決まりを作る場は…？",
   etymologyConclusion:"parl（話す）＋ ment（名詞）→ 集まって話し合い、国の決まりを作る場＝議会",
   relatedWords:[
     {word:"parlor",meaning:"応接間",breakdown:"parl（話す）＋ or（もの）→ 客と話をするための部屋"},
     {synonym:true,word:"congress",meaning:"（米国の）議会",breakdown:"アメリカの議会。parliament は英国や日本などの議会"},
     {synonym:true,word:"assembly",meaning:"議会，集会",breakdown:"集まること。parliament は国の法律を作る議会を指す"},
     {synonym:true,word:"council",meaning:"評議会",breakdown:"話し合って決める会。parliament は国の立法を行う議会"}]},

  {id:1092,word:"territory",partOfSpeech:"名詞",meaning:"領土；縄張り",
   meanings:["名|領土，領域","名|（動物の）縄張り"],
   pronunciation:"/ˈterətɔːri/",part:110,
   example:"That small island is part of Japanese territory.",
   exampleJa:"その小さな島は、日本の領土の一部だ。",
   example2:"Wolves mark their territory with a very strong smell.",
   exampleJa2:"オオカミは、とても強いにおいで自分の縄張りに印をつける。",
   etymologyProcess:"terra（土地）＋ ory（場所）→ 自分のものとして持っている土地は…？",
   etymologyConclusion:"terra（土地）＋ ory（場所）→ ある国が自分のものとして持っている土地＝領土",
   relatedWords:[
     {word:"terrain",meaning:"地形",breakdown:"terra（土地）→ その土地の起伏やようす"},
     {word:"terrace",meaning:"テラス，段々畑",breakdown:"terra（土地）→ 土を盛って平らにならしたところ"},
     {word:"Mediterranean",meaning:"地中海の",breakdown:"medi（中間）＋ terra（土地）→ 陸地の真ん中にある海"},
     {synonym:true,word:"land",meaning:"土地，国土",breakdown:"陸地そのもの。territory は支配の及ぶ範囲を指す"}]},

  {id:1093,word:"poll",partOfSpeech:"名詞",meaning:"世論調査；投票",
   meanings:["名|世論調査","名|投票（数）"],
   pronunciation:"/poʊl/",part:110,
   example:"A new poll shows most people support the plan.",
   exampleJa:"新しい世論調査は、大半の人がその計画を支持していると示している。",
   example2:"The class poll decided the topic of our project.",
   exampleJa2:"クラスの投票が、私たちの計画の題材を決めた。",
   etymologyProcess:"poll（頭）→ 一人一人の頭を数えるように意見を集めると…？",
   etymologyConclusion:"poll（頭）→ 一人一人の頭を数えるように意見を集めること＝世論調査",
   hook:"「頭数を数える」が芯。go to the polls なら「投票に行く」。",
   why:"【なぜ】poll はもともと「頭」。選挙で賛成の人の頭を数えたことから「投票（数）」になり、さらに意見を数える「世論調査」になりました。\n【つながり】tadpole（オタマジャクシ）は「頭＋しっぽ」。poll tax（人頭税）も「頭ごとの税」です。",
   relatedWords:[
     {synonym:true,word:"survey",meaning:"調査",breakdown:"広く調べること。poll は意見を数えあげる調査を指す"},
     {synonym:true,word:"vote",meaning:"投票",breakdown:"一票を投じること。poll はその数を集めた結果も指す"},
     {synonym:true,word:"questionnaire",meaning:"アンケート",breakdown:"問いを並べた紙。poll は意見の分かれ方を出す調査"},
     {synonym:true,word:"election",meaning:"選挙",breakdown:"代表を選ぶこと。poll は投票そのものや世論調査を指す"}]},

  {id:1094,word:"fortune",partOfSpeech:"名詞",meaning:"財産；運",
   meanings:["名|（大きな）財産","名|運，幸運"],
   pronunciation:"/ˈfɔːrtʃən/",part:110,
   example:"He made a fortune in the computer software business.",
   exampleJa:"彼はコンピューターのソフト事業で、財産を築いた。",
   example2:"She had the good fortune to meet her own hero.",
   exampleJa2:"彼女は自分の憧れの人に会うという幸運に恵まれた。",
   etymologyProcess:"fortun（めぐり合わせ）→ めぐり合わせで手に入った大きな富は…？",
   etymologyConclusion:"fortun（めぐり合わせ）→ よいめぐり合わせで手に入った大きな富＝財産",
   relatedWords:[
     {word:"fortunate",meaning:"幸運な",breakdown:"fortun（めぐり合わせ）＋ ate（形容詞）→ よいめぐり合わせに当たった"},
     {word:"unfortunately",meaning:"残念ながら",breakdown:"un（否定）＋ fortun（めぐり合わせ）＋ ly（副詞）→ よい巡りではなく"},
     {synonym:true,word:"wealth",meaning:"富",breakdown:"多くの財。fortune は運よく築いた大きな財産を指す"},
     {synonym:true,word:"luck",meaning:"運",breakdown:"たまたまの巡り合わせ。fortune はもっと大きな運命の巡り"}]},

  {id:1095,word:"property",partOfSpeech:"名詞",meaning:"財産，所有地；性質",
   meanings:["名|財産，所有地","名|（物の）性質"],
   pronunciation:"/ˈprɑːpərti/",part:110,
   example:"This wide land is the property of the city.",
   exampleJa:"この広い土地は、市の財産だ。",
   example2:"Water has the property of dissolving many substances.",
   exampleJa2:"水は、多くの物質を溶かすという性質を持っている。",
   etymologyProcess:"propri（自分のもの）＋ ty（名詞）→ 自分のものとして持っているものは…？",
   etymologyConclusion:"propri（自分のもの）＋ ty（名詞）→ 自分のものとして持っている物＝財産",
   why:"【なぜ】ラテン語 proprius は「そのもの自身の」。人が自分のものとして持てば「財産」、物が自分自身として備えていれば「性質」。同じ「自分のもの」から二つの方向へ広がりました。\n【つながり】proper（固有の）、appropriate（その場に自分のものとしてぴたり合う）も同じ家族です。",
   relatedWords:[
     {word:"proper",meaning:"適切な；固有の",breakdown:"propri（自分のもの）→ そのものにふさわしい"},
     {word:"appropriate",meaning:"適切な",breakdown:"ad（〜へ）＋ propri（自分のもの）→ その場にぴたりと合う"},
     {word:"proprietor",meaning:"所有者",breakdown:"propri（自分のもの）＋ or（人）→ 自分のものとして持っている人"},
     {synonym:true,word:"possession",meaning:"所有物",breakdown:"持っているもの。property は土地や建物などの財産を指す"}]},

  {id:1096,word:"fund",partOfSpeech:"名詞",meaning:"資金，基金",
   meanings:["名|資金，基金","他|資金を出す"],
   pronunciation:"/fʌnd/",part:110,
   example:"The school raised funds for new sports equipment.",
   exampleJa:"学校は、新しい運動用具のための資金を集めた。",
   example2:"This special fund supports students from poor families.",
   exampleJa2:"この特別な資金は、貧しい家庭の生徒を支えている。",
   etymologyProcess:"fund（底）→ 事業の底を支えるためにためておくお金は…？",
   etymologyConclusion:"fund（底）→ 事業の底を支えるためにためておくお金＝資金",
   relatedWords:[
     {word:"found",meaning:"創立する",breakdown:"found（底）→ 底に土台を据えて、新しく組織を起こす"},
     {word:"foundation",meaning:"土台，基礎；財団",breakdown:"found（底）＋ ation（名詞）→ 底に据えられた土台"},
     {word:"fundamental",meaning:"基本的な",breakdown:"fund（底）＋ ment（名詞）＋ al（形容詞）→ いちばん底を成している"},
     {word:"profound",meaning:"深い",breakdown:"pro（前へ）＋ found（底）→ 底のほうまで届いている"}]},

  {id:1097,word:"stock",partOfSpeech:"名詞",meaning:"株；在庫",
   meanings:["名|株，株式","名|在庫，たくわえ"],
   pronunciation:"/stɑːk/",part:110,
   example:"He bought stock in a small technology company.",
   exampleJa:"彼は小さな技術の会社の株を買った。",
   example2:"That very popular book is out of stock right now.",
   exampleJa2:"あのとても人気の本は、今は在庫切れだ。",
   etymologyProcess:"stock（木の幹）→ 幹のように蓄えの元になるものは…？",
   etymologyConclusion:"stock（木の幹）→ 幹のように蓄えの元になるもの、また会社の持ち分＝株",
   hook:"日本語の「ストック（買い置き）」は在庫の意味。幹＝蓄えの元。",
   why:"【なぜ】stock はもともと「木の幹・切り株」。そこから「たくわえの元」＝在庫、さらに「会社の元手を分けた持ち分」＝株、へ広がりました。\n【つながり】stockings（靴下）も stock の「脚を覆うもの」から来たと言われます。日本語の「ストック（買い置き）」は在庫の意味です。",
   relatedWords:[
     {synonym:true,word:"share",meaning:"株，持ち分",breakdown:"分け前。英国では株を share、米国では stock と言う"},
     {synonym:true,word:"supply",meaning:"蓄え，供給",breakdown:"用意してある分。stock は店や倉庫にある在庫を指す"},
     {synonym:true,word:"inventory",meaning:"在庫（目録）",breakdown:"在庫の一覧。stock は在庫そのものを指す"},
     {synonym:true,word:"goods",meaning:"商品，品物",breakdown:"売る品物。stock は店や倉庫にある在庫の量を指す"}]},

  {id:1098,word:"labor",partOfSpeech:"名詞",meaning:"労働；労働力",
   meanings:["名|労働，骨の折れる仕事","名|労働力，働き手"],
   pronunciation:"/ˈleɪbər/",part:110,
   example:"Hard human labor built this long stone wall.",
   exampleJa:"人の厳しい労働が、この長い石の壁を築いた。",
   example2:"The factory needs more skilled labor this year.",
   exampleJa2:"その工場は今年、もっと熟練した労働力を必要としている。",
   etymologyProcess:"labor（働く）→ 体を使ってきつく働くこと自体を指すと…？",
   etymologyConclusion:"labor（働く）→ 体を使ってきつく働くこと、またその働き手＝労働",
   relatedWords:[
     {word:"laboratory",meaning:"研究室，実験室",breakdown:"labor（働く）＋ ory（場所）→ 手を動かして試しながら働く部屋"},
     {word:"laborious",meaning:"骨の折れる",breakdown:"labor（働く）＋ ous（形容詞）→ 働きづめになるほど手間がかかる"},
     {word:"collaborate",meaning:"協力する",breakdown:"col（共に）＋ labor（働く）→ 共に力を出し合って働く"},
     {word:"elaborate",meaning:"入念な；詳しく述べる",breakdown:"ex（外へ）＋ labor（働く）→ 手をかけて練り上げる"}]},

  {id:1099,word:"overwork",partOfSpeech:"自動詞",meaning:"働きすぎる",
   meanings:["自|働きすぎる","他|働かせすぎる","名|過労"],
   pronunciation:"/ˌoʊvərˈwɜːrk/",part:110,
   example:"Many adults overwork and slowly lose their good health.",
   exampleJa:"多くの大人が働きすぎて、ゆっくりと健康を失っていく。",
   example2:"Do not overwork before the important exam week starts.",
   exampleJa2:"大切な試験週間が始まる前に、働きすぎないでください。",
   etymologyProcess:"over（越えて）＋ work（仕事）→ ほどよい量を越えて働いてしまうと…？",
   etymologyConclusion:"over（越えて）＋ work（仕事）→ ほどよい量を越えて働いてしまう＝働きすぎる",
   relatedWords:[
     {word:"work",meaning:"働く；仕事",breakdown:"work（仕事）→ 体や頭を使って事をなすこと"},
     {word:"overcome",meaning:"打ち勝つ",breakdown:"over（越えて）＋ come（来る）→ 上を越えて乗りこえる"},
     {word:"overload",meaning:"積みすぎる",breakdown:"over（越えて）＋ load（積んで運ぶ）→ 限度を越えて積む"},
     {word:"overlook",meaning:"見落とす；見渡す",breakdown:"over（越えて）＋ look（見る）→ 上を越して見てしまう"}]},

  {id:1100,word:"firm",partOfSpeech:"名詞",meaning:"会社，事務所",
   meanings:["名|会社，事務所","形|しっかりした，固い"],
   pronunciation:"/fɜːrm/",part:110,
   example:"He joined a large trading firm last spring.",
   exampleJa:"彼は昨春、大きな貿易会社に入った。",
   example2:"The table has a firm and very steady base.",
   exampleJa2:"そのテーブルは、しっかりしてとても安定した台を持っている。",
   etymologyProcess:"firm（しっかりした）→ 署名で固く結ばれた商いの組織は…？",
   etymologyConclusion:"firm（しっかりした）→ 署名で固く結ばれた、しっかりした商いの組織＝会社",
   why:"【なぜ】ラテン語 firmus は「堅い」。イタリア語で「署名」を firma と言い、署名で固く結ばれた商売の組織が firm（会社）になりました。形容詞の firm（しっかりした）は、元の意味がそのまま残ったものです。\n【つながり】confirm（しっかり確かめる）、farm（もとは決まった地代を払う土地）も同じ家族です。",
   relatedWords:[
     {word:"confirm",meaning:"確認する",breakdown:"con（すっかり）＋ firm（しっかりした）→ すっかり固めて確かめる"},
     {word:"firmly",meaning:"しっかりと",breakdown:"firm（しっかりした）＋ ly（副詞）→ 固く、ぐらつかずに"},
     {word:"affirm",meaning:"断言する",breakdown:"ad（〜へ）＋ firm（しっかりした）→ そうだと固く言い切る"},
     {synonym:true,word:"company",meaning:"会社",breakdown:"ふつうの「会社」。firm は法律や会計などの事務所によく使う"}]},

  {id:1101,word:"union",partOfSpeech:"名詞",meaning:"労働組合；結合",
   meanings:["名|労働組合","名|結合，連合"],
   pronunciation:"/ˈjuːniən/",part:111,
   example:"The workers' union asked for much higher wages.",
   exampleJa:"労働組合は、もっと高い賃金を求めた。",
   example2:"The union of these two groups made them strong.",
   exampleJa2:"この2つの集団の結合が、彼らを強くした。",
   etymologyProcess:"uni（1つの）＋ ion（名詞）→ ばらばらのものが一つに結びつくと…？",
   etymologyConclusion:"uni（1つの）＋ ion（名詞）→ ばらばらの者が一つに結びついた集まり＝労働組合",
   relatedWords:[
     {word:"unite",meaning:"団結する，結びつける",breakdown:"uni（1つの）＋ ite（〜された）→ 一つにまとめられる"},
     {word:"unique",meaning:"唯一の",breakdown:"uni（1つの）＋ ique（形容詞）→ たった一つしかない"},
     {word:"uniform",meaning:"制服；均一の",breakdown:"uni（1つの）＋ form（形）→ みんな同じ一つの形"},
     {word:"unity",meaning:"まとまり，統一",breakdown:"uni（1つの）＋ ty（名詞）→ 一つにまとまっていること"}]},

  {id:1102,word:"administration",partOfSpeech:"名詞",meaning:"経営，運営",
   meanings:["名|経営，運営，行政","名|（米国の）政権"],
   pronunciation:"/ədˌmɪnɪˈstreɪʃn/",part:111,
   example:"Good administration keeps this large hospital running smoothly.",
   exampleJa:"よい経営が、この大きな病院を滞りなく動かしている。",
   example2:"She studies business administration at a famous private university.",
   exampleJa2:"彼女は有名な私立大学で、経営学を学んでいる。",
   etymologyProcess:"ad（〜へ）＋ min（小さい）→ 下の立場で仕えて組織の事をさばくと…？",
   etymologyConclusion:"ad（〜へ）＋ min（小さい）＋ ation（名詞）→ 仕える立場で組織の事をさばくこと＝経営",
   why:"【なぜ】ラテン語 minister は「より小さい者＝召使い」。その召使いが主人の家の用事をさばいたことから ministrare（仕える・管理する）、さらに administer（運営する）になりました。\n【つながり】minister（大臣＝国に仕える人）、minimum、minor も同じ min の家族です。",
   relatedWords:[
     {word:"minister",meaning:"大臣",breakdown:"min（小さい）→ 王より小さな者として仕え、国の仕事を預かる人"},
     {word:"minimum",meaning:"最小限",breakdown:"min（小さい）→ これ以上小さくできない、いちばん小さい量"},
     {word:"minor",meaning:"小さいほうの",breakdown:"min（小さい）＋ or（より〜な）→ 二つのうち小さいほうの"},
     {word:"administer",meaning:"管理する，運営する",breakdown:"ad（〜へ）＋ min（小さい）→ 仕える立場で組織を動かす"}]},

  {id:1103,word:"secretary",partOfSpeech:"名詞",meaning:"秘書",
   meanings:["名|秘書","名|（米国の）長官"],
   pronunciation:"/ˈsekrəteri/",part:111,
   example:"The secretary arranged all the meetings for him.",
   exampleJa:"秘書が、彼のためにすべての会議を手配した。",
   example2:"She worked as a secretary for almost ten years.",
   exampleJa2:"彼女はほぼ10年間、秘書として働いた。",
   etymologyProcess:"se（離して）＋ cret（ふるい分ける）→ 秘密を選り分けて預かる人は…？",
   etymologyConclusion:"se（離して）＋ cret（ふるい分ける）→ 秘密を選り分けて預かり、仕事を支える人＝秘書",
   why:"【なぜ】ラテン語 secretum は「よりわけて隠されたこと」＝秘密。その秘密を預かる人が secretarius で、そこから「秘書」になりました。\n【つながり】secret（秘密）、discreet（慎重な）も同じ cret の家族。アメリカでは大臣を Secretary と呼びます。",
   relatedWords:[
     {word:"secret",meaning:"秘密",breakdown:"se（離して）＋ cret（ふるい分ける）→ よりわけて隠しておくこと"},
     {word:"discern",meaning:"見分ける",breakdown:"dis（バラバラに）＋ cern（ふるい分ける）→ より分けて見分ける"},
     {word:"discreet",meaning:"慎重な，口の固い",breakdown:"dis（バラバラに）＋ cret（ふるい分ける）→ よく選り分けて口に出す"},
     {word:"certain",meaning:"確かな",breakdown:"cert（ふるい分ける）＋ ain（〜の）→ ふるい分けてはっきりした"}]},

  {id:1104,word:"editor",partOfSpeech:"名詞",meaning:"編集者",
   meanings:["名|編集者，編集長"],
   pronunciation:"/ˈedɪtər/",part:111,
   example:"The editor checked every single page of the magazine.",
   exampleJa:"編集者は、雑誌のすべてのページを一つ残らず確認した。",
   example2:"She became an editor at a small publishing company.",
   exampleJa2:"彼女は小さな出版社の編集者になった。",
   etymologyProcess:"e（外へ）＋ dit（渡す）→ 原稿を整えて世の中へ出し渡す人は…？",
   etymologyConclusion:"e（外へ）＋ dit（渡す）＋ or（人）→ 原稿を整えて世の中へ出し渡す人＝編集者",
   relatedWords:[
     {word:"edit",meaning:"編集する",breakdown:"e（外へ）＋ dit（渡す）→ 世に出せる形に整える"},
     {word:"edition",meaning:"版",breakdown:"e（外へ）＋ dit（渡す）＋ ion（名詞）→ 世に出された一つの形"},
     {word:"tradition",meaning:"伝統",breakdown:"tra（向こうへ）＋ dit（渡す）→ 次の世代へ渡していくもの"},
     {word:"add",meaning:"加える",breakdown:"ad（〜へ）＋ dit（渡す）→ そこへさらに渡して足す"}]},

  {id:1105,word:"client",partOfSpeech:"名詞",meaning:"依頼人，顧客",
   meanings:["名|依頼人，顧客"],
   pronunciation:"/ˈklaɪənt/",part:111,
   example:"The lawyer met his new client early this morning.",
   exampleJa:"弁護士は今朝早く、新しい依頼人に会った。",
   example2:"Our company has many clients in other Asian countries.",
   exampleJa2:"私たちの会社は、他のアジアの国々に多くの顧客を持っている。",
   etymologyProcess:"clin（傾き）＋ ent（人）→ 有力者に身を寄せて助けを頼む人は…？",
   etymologyConclusion:"clin（傾き）＋ ent（人）→ 有力者のほうへ身を寄せて助けを頼む人＝依頼人",
   relatedWords:[
     {word:"clinic",meaning:"診療所",breakdown:"clin（傾き）＋ ic（名詞）→ 病床のそばで患者を診る場所"},
     {word:"incline",meaning:"傾く，傾ける",breakdown:"in（中へ）＋ clin（傾き）→ 内側へ傾いていく"},
     {word:"decline",meaning:"断る；下がる",breakdown:"de（下へ）＋ clin（傾き）→ 下へ傾いて離れていく"},
     {word:"climate",meaning:"気候",breakdown:"clim（傾き）＋ ate（名詞）→ 太陽の傾き方で決まる土地の天気"}]},

  {id:1106,word:"recruit",partOfSpeech:"他動詞",meaning:"新規採用する",
   meanings:["他|新規採用する，新しく集める","名|新入社員，新人"],
   pronunciation:"/rɪˈkruːt/",part:111,
   example:"The company will recruit ten new workers this spring.",
   exampleJa:"その会社は今春、10人の新しい社員を新規採用する。",
   example2:"Our club recruits new members at the start of April.",
   exampleJa2:"私たちの部は、4月の初めに新入部員を新しく集める。",
   etymologyProcess:"re（再び）＋ cruit（育つ）→ 人を新しく集めて組織を育て直すと…？",
   etymologyConclusion:"re（再び）＋ cruit（育つ）→ 人を新しく集めて、組織をもう一度育て直す＝新規採用する",
   relatedWords:[
     {word:"increase",meaning:"増える",breakdown:"in（中へ）＋ creas（育つ）→ 中でどんどん育って増える"},
     {word:"crescent",meaning:"三日月",breakdown:"creas（育つ）＋ ent（〜している）→ これから満ちていく途中の月"},
     {word:"decrease",meaning:"減る",breakdown:"de（下へ）＋ creas（育つ）→ 育ちが下向きになって減っていく"},
     {synonym:true,word:"hire",meaning:"雇う",breakdown:"お金を払って働いてもらう。recruit は新しく人を集めること"}]},

  {id:1107,word:"basis",partOfSpeech:"名詞",meaning:"基礎，根拠",
   meanings:["名|基礎，根拠","名|（on a ～ basis で）方式"],
   pronunciation:"/ˈbeɪsɪs/",part:111,
   example:"Trust is the basis of every good lasting friendship.",
   exampleJa:"信頼は、長く続くよい友情すべての基礎だ。",
   example2:"His argument has no scientific basis at all.",
   exampleJa2:"彼の主張には、科学的な根拠がまったくない。",
   etymologyProcess:"bas（踏み台・土台）→ その上に物事を組み立てていく台は…？",
   etymologyConclusion:"bas（踏み台・土台）→ その上に物事を組み立てていく土台＝基礎",
   relatedWords:[
     {word:"base",meaning:"土台；基地",breakdown:"bas（踏み台・土台）→ 下で全体を支えているところ"},
     {word:"basic",meaning:"基本的な",breakdown:"bas（踏み台・土台）＋ ic（形容詞）→ 土台にあたる"},
     {word:"basement",meaning:"地下室",breakdown:"bas（踏み台・土台）＋ ment（名詞）→ 建物の土台の高さの部屋"},
     {synonym:true,word:"foundation",meaning:"土台，基礎",breakdown:"据えられた土台。basis は考えや議論のよりどころも指す"}]},

  {id:1108,word:"element",partOfSpeech:"名詞",meaning:"要素；元素",
   meanings:["名|要素，成分","名|（化学の）元素"],
   pronunciation:"/ˈelɪmənt/",part:111,
   example:"Trust is an important element of good teamwork.",
   exampleJa:"信頼は、よいチームワークの大切な要素だ。",
   example2:"Water is made of two simple chemical elements.",
   exampleJa2:"水は、2つの単純な化学元素からできている。",
   etymologyProcess:"element（要素）→ 全体を組み立てているひとかけらは…？",
   etymologyConclusion:"element（要素）→ それ以上分けられない、全体を組み立てるひとかけら＝要素",
   hook:"理科の「元素」と同じ語。これ以上分けられない一かけら、が芯。",
   relatedWords:[
     {word:"elementary",meaning:"初歩の；小学校の",breakdown:"element（要素）＋ ary（形容詞）→ いちばん基本の要素にあたる"},
     {synonym:true,word:"component",meaning:"構成要素",breakdown:"組み立てる部品。element はそれ以上分けられない基本の一つ"},
     {synonym:true,word:"factor",meaning:"要因",breakdown:"結果を左右するもの。element は全体を作っている成分"},
     {synonym:true,word:"ingredient",meaning:"材料",breakdown:"料理に入れるもの。element は物事を作る基本の成分"}]},

  {id:1109,word:"constitute",partOfSpeech:"他動詞",meaning:"構成する",
   meanings:["他|構成する，～を成す"],
   pronunciation:"/ˈkɑːnstətuːt/",part:111,
   example:"Women constitute half of the student population here.",
   exampleJa:"ここの学生の半数を、女性が構成している。",
   example2:"These five members constitute the whole planning team.",
   exampleJa2:"これら5人の部員が、企画班全体を構成している。",
   etymologyProcess:"con（共に）＋ stitut（立てる）→ 部品を共に立てて全体を作ると…？",
   etymologyConclusion:"con（共に）＋ stitut（立てる）→ 部品を共に立てて一つの全体を形づくる＝構成する",
   relatedWords:[
     {word:"institute",meaning:"設立する；協会",breakdown:"in（中に）＋ stitut（立てる）→ 中に柱を立てて組織を作る"},
     {word:"substitute",meaning:"代わりに用いる",breakdown:"sub（下で）＋ stitut（立てる）→ 元のものの下に別のものを立てる"},
     {word:"constitution",meaning:"憲法；構成",breakdown:"con（共に）＋ stitut（立てる）＋ ion（名詞）→ 国の形を共に立てた決まり"},
     {word:"state",meaning:"状態；国家",breakdown:"sta（立つ）→ そこに立っているありさま"}]},

  {id:1110,word:"unify",partOfSpeech:"他動詞",meaning:"統一する",
   meanings:["他|統一する，一つにまとめる"],
   pronunciation:"/ˈjuːnɪfaɪ/",part:111,
   example:"The new leader tried to unify the divided country.",
   exampleJa:"新しい指導者は、分裂した国を統一しようとした。",
   example2:"One clear goal can unify a whole school team.",
   exampleJa2:"一つの明確な目標が、学校のチーム全体を統一することがある。",
   etymologyProcess:"uni（1つの）＋ fy（する）→ ばらばらのものを一つにまとめると…？",
   etymologyConclusion:"uni（1つの）＋ fy（する）→ ばらばらのものを一つにまとめてしまう＝統一する",
   relatedWords:[
     {word:"unite",meaning:"団結する，結びつける",breakdown:"uni（1つの）＋ ite（〜された）→ 一つにまとめられる"},
     {word:"union",meaning:"労働組合；結合",breakdown:"uni（1つの）＋ ion（名詞）→ 一つに結びついた集まり"},
     {word:"unique",meaning:"唯一の",breakdown:"uni（1つの）＋ ique（形容詞）→ たった一つしかない"},
     {word:"uniform",meaning:"制服；均一の",breakdown:"uni（1つの）＋ form（形）→ みんな同じ一つの形"}]},

  {id:1111,word:"combine",partOfSpeech:"他動詞",meaning:"結びつける，組み合わせる",
   meanings:["他|結びつける，組み合わせる"],
   pronunciation:"/kəmˈbaɪn/",part:112,
   example:"You can combine these two colors to make purple.",
   exampleJa:"この2つの色を結びつけると、紫を作ることができる。",
   example2:"The recipe combines Japanese and Italian cooking styles.",
   exampleJa2:"そのレシピは、日本とイタリアの料理法を結びつけている。",
   etymologyProcess:"com（共に）＋ bin（2つずつ）→ 二つのものを共に合わせると…？",
   etymologyConclusion:"com（共に）＋ bin（2つずつ）→ 二つのものを共に合わせて一つにする＝結びつける",
   relatedWords:[
     {word:"binary",meaning:"2進法の；2つの",breakdown:"bin（2つずつ）＋ ary（形容詞）→ 2つ一組で数えていく"},
     {word:"combination",meaning:"組み合わせ",breakdown:"com（共に）＋ bin（2つずつ）＋ ation（名詞）→ 合わせて一つにすること"},
     {synonym:true,word:"mix",meaning:"混ぜる",breakdown:"混ぜ合わせること。combine は別々のものを結びつけて一つにする"},
     {synonym:true,word:"merge",meaning:"合併する",breakdown:"溶け合って一つになる。combine は二つを合わせて使うこと"}]},

  {id:1112,word:"unite",partOfSpeech:"自動詞",meaning:"（人が）団結する",
   meanings:["自|（人が）団結する","他|結びつける，一つにする"],
   pronunciation:"/juˈnaɪt/",part:112,
   example:"The members united to save their old school club.",
   exampleJa:"部員たちは、古い学校の部を守るために団結した。",
   example2:"A common enemy can unite very different groups.",
   exampleJa2:"共通の敵は、まるで違う集団を団結させることがある。",
   etymologyProcess:"uni（1つの）＋ ite（〜された）→ ばらばらの者が一つにまとまると…？",
   etymologyConclusion:"uni（1つの）＋ ite（〜された）→ ばらばらの者が一つにまとまる＝人が団結する",
   relatedWords:[
     {word:"union",meaning:"労働組合；結合",breakdown:"uni（1つの）＋ ion（名詞）→ 一つに結びついた集まり"},
     {word:"unify",meaning:"統一する",breakdown:"uni（1つの）＋ fy（する）→ ばらばらのものを一つにまとめる"},
     {word:"unique",meaning:"唯一の",breakdown:"uni（1つの）＋ ique（形容詞）→ たった一つしかない"},
     {word:"unity",meaning:"まとまり，統一",breakdown:"uni（1つの）＋ ty（名詞）→ 一つにまとまっていること"}]},

  {id:1113,word:"link",partOfSpeech:"名詞",meaning:"関連，つながり",
   meanings:["名|関連，つながり","名|（ネットの）リンク","他|つなぐ"],
   pronunciation:"/lɪŋk/",part:112,
   example:"Doctors found a clear link between sleep and health.",
   exampleJa:"医師たちは、睡眠と健康の間に明らかな関連を見つけた。",
   example2:"This link takes you to the new school website.",
   exampleJa2:"このリンクは、新しい学校のウェブサイトへつないでくれる。",
   etymologyProcess:"link（鎖の輪）→ 二つをつなぎ合わせている輪のようなものは…？",
   etymologyConclusion:"link（鎖の輪）→ 二つをつなぎ合わせている鎖の輪のようなもの＝関連",
   hook:"ネットの「リンク」と同じ。鎖の輪のように二つをつなぐものが芯。",
   relatedWords:[
     {synonym:true,word:"connection",meaning:"つながり",breakdown:"つながっていること。link はつなぐ一つ一つの輪を指す"},
     {synonym:true,word:"chain",meaning:"鎖",breakdown:"link がつながってできたもの。link はその一つの輪"},
     {synonym:true,word:"relation",meaning:"関係",breakdown:"物事の間柄。link はそれを結びつける具体的なつながり"},
     {synonym:true,word:"bond",meaning:"きずな，結びつき",breakdown:"固く結ぶもの。link は二つをつなぐ輪のイメージ"}]},

  {id:1114,word:"relevant",partOfSpeech:"形容詞",meaning:"関連のある，適切な",
   meanings:["形|（to ～）（～に）関連のある，適切な"],
   pronunciation:"/ˈreləvənt/",part:112,
   example:"Please give only information relevant to this main topic.",
   exampleJa:"この主な話題に関連のある情報だけを出してください。",
   example2:"Her question was not relevant to today's history lesson.",
   exampleJa2:"彼女の質問は、今日の歴史の授業には関連がなかった。",
   etymologyProcess:"re（再び）＋ lev（持ち上げる）→ その話題で改めて取り上げるに足ると…？",
   etymologyConclusion:"re（再び）＋ lev（持ち上げる）→ その話題のところで改めて持ち上がってくる＝関連のある",
   why:"【なぜ】ラテン語 relevare は「再び持ち上げる」。法律の場で「その事件に関わりがあって取り上げるに足る」という言い方から、「関連のある・適切な」になりました。\n【つながり】elevator（持ち上げる機械）、relief（重荷を持ち上げる＝安心）も同じ lev の家族です。",
   relatedWords:[
     {word:"elevator",meaning:"エレベーター",breakdown:"e（外へ）＋ lev（持ち上げる）＋ or（もの）→ 人を持ち上げる装置"},
     {word:"relief",meaning:"安心；救済",breakdown:"re（再び）＋ lev（持ち上げる）→ 重荷を持ち上げて軽くすること"},
     {word:"lever",meaning:"てこ，レバー",breakdown:"lev（持ち上げる）→ 重い物を持ち上げるための棒"},
     {synonym:true,word:"related",meaning:"関係のある",breakdown:"つながりがあること。relevant は「その場にふさわしい」含みが強い"}]},

  {id:1115,word:"murder",partOfSpeech:"名詞",meaning:"殺人",
   meanings:["名|殺人","他|殺害する"],
   pronunciation:"/ˈmɜːrdər/",part:112,
   example:"The police are investigating a murder in that quiet town.",
   exampleJa:"警察は、あの静かな町で起きた殺人を捜査している。",
   example2:"He was arrested for the murder of his own neighbor.",
   exampleJa2:"彼は隣人を殺した罪で逮捕された。",
   etymologyProcess:"murd（死）→ わざと人の命を奪うことは…？",
   etymologyConclusion:"murd（死）→ 人がわざと他人の命を奪うこと＝殺人",
   relatedWords:[
     {word:"murderer",meaning:"殺人者",breakdown:"murd（死）＋ er（人）→ 人の命を奪った人"},
     {synonym:true,word:"kill",meaning:"殺す",breakdown:"命を奪うこと全般。murder はわざと人を殺すことに限る"},
     {synonym:true,word:"crime",meaning:"犯罪",breakdown:"法を破る行い。murder はその中でも最も重い罪の一つ"},
     {synonym:true,word:"homicide",meaning:"殺人（法律用語）",breakdown:"法律で使う堅い語。murder はわざと人を殺すことを指す"}]},

  {id:1116,word:"arrest",partOfSpeech:"他動詞",meaning:"逮捕する",
   meanings:["他|逮捕する","名|逮捕"],
   pronunciation:"/əˈrest/",part:112,
   example:"The police arrested the man near the train station.",
   exampleJa:"警察は、駅の近くでその男を逮捕した。",
   example2:"He was arrested for driving without a proper license.",
   exampleJa2:"彼は正式な免許なしで運転して逮捕された。",
   etymologyProcess:"ad（〜へ）＋ rest（立ち止まる）→ 相手をその場に立ち止まらせると…？",
   etymologyConclusion:"ad（〜へ）＋ rest（立ち止まる）→ 相手をその場に立ち止まらせ、身柄を押さえる＝逮捕する",
   why:"【なぜ】ラテン語 arrestare は ad（〜へ）＋ restare（立ち止まる）で、「その場に立ち止まらせる」。動きを止めて身柄を押さえることから「逮捕する」になりました。\n【つながり】この rest は「立ち止まる」で、the rest（残り＝その場に残っているぶん）と同じ家族。「休む」の rest は同じつづりの別の語です。",
   relatedWords:[
     {word:"station",meaning:"駅；持ち場",breakdown:"sta（立つ）＋ ion（名詞）→ 人や車が立ち止まる場所"},
     {synonym:true,word:"catch",meaning:"捕まえる",breakdown:"つかまえること。arrest は警察が法にもとづいて身柄を押さえる"},
     {synonym:true,word:"detain",meaning:"拘束する",breakdown:"引き止めておくこと。arrest は逮捕の手続きそのものを指す"},
     {synonym:true,word:"capture",meaning:"捕らえる",breakdown:"つかまえて自分のものにする。arrest は法にもとづく逮捕"}]},

  {id:1117,word:"prison",partOfSpeech:"名詞",meaning:"刑務所",
   meanings:["名|刑務所，監獄"],
   pronunciation:"/ˈprɪzn/",part:112,
   example:"He spent five long years in that old prison.",
   exampleJa:"彼はその古い刑務所で、5年の長い年月を過ごした。",
   example2:"The old prison was finally closed down last year.",
   exampleJa2:"その古い刑務所は、昨年ついに閉鎖された。",
   etymologyProcess:"pris（つかむ）→ 捕らえた人を閉じ込めておく建物は…？",
   etymologyConclusion:"pris（つかむ）→ 捕らえた人を閉じ込めておくための建物＝刑務所",
   relatedWords:[
     {word:"prisoner",meaning:"囚人",breakdown:"pris（つかむ）＋ er（人）→ 捕らえられている人"},
     {word:"surprise",meaning:"驚かせる",breakdown:"sur（上から）＋ pris（つかむ）→ 上から不意につかみかかる"},
     {word:"comprise",meaning:"～から成る",breakdown:"com（すっかり）＋ pris（つかむ）→ すっかりつかんで中に含む"},
     {synonym:true,word:"jail",meaning:"留置場，刑務所",breakdown:"短い期間入れておく所。prison は刑が決まった人が入る所"}]},

  {id:1118,word:"vice",partOfSpeech:"名詞",meaning:"悪徳，悪い癖",
   meanings:["名|悪徳，悪い癖","名|（社会の）不道徳，売春など"],
   pronunciation:"/vaɪs/",part:112,
   example:"Gambling was his greatest vice as a young man.",
   exampleJa:"賭け事が、若いころの彼の最大の悪徳だった。",
   example2:"The city fought hard against crime and vice.",
   exampleJa2:"その市は、犯罪と悪徳に対して懸命に戦った。",
   etymologyProcess:"vit（欠点）→ 人の性格に付いた直しがたい欠点は…？",
   etymologyConclusion:"vit（欠点）→ 人の性格に付いてしまった、直しがたい欠点＝悪徳",
   hook:"vice president（副社長）の vice は「代わりに」で、まったく別の語。",
   relatedWords:[
     {word:"vicious",meaning:"悪意のある，ひどい",breakdown:"vit（欠点）＋ ous（形容詞）→ 欠点だらけでたちが悪い"},
     {synonym:true,word:"sin",meaning:"罪",breakdown:"宗教の上での罪。vice は身についた悪い癖や悪徳を指す"},
     {synonym:true,word:"crime",meaning:"犯罪",breakdown:"法を破る行い。vice は法よりも道徳の上での悪を指す"},
     {synonym:true,word:"fault",meaning:"欠点，落ち度",breakdown:"小さな欠点。vice はもっと重く、性格に根づいた悪"}]},

  {id:1119,word:"witness",partOfSpeech:"名詞",meaning:"目撃者，証人",
   meanings:["名|目撃者，証人","他|目撃する"],
   pronunciation:"/ˈwɪtnəs/",part:112,
   example:"Police asked every witness about the terrible car accident.",
   exampleJa:"警察はすべての目撃者に、そのひどい自動車事故について尋ねた。",
   example2:"She was the only witness to the whole event.",
   exampleJa2:"彼女は、その出来事全体の唯一の目撃者だった。",
   etymologyProcess:"wit（知っている）＋ ness（名詞）→ その場を見て知っている人は…？",
   etymologyConclusion:"wit（知っている）＋ ness（名詞）→ その場を実際に見て知っている人＝目撃者",
   relatedWords:[
     {word:"wit",meaning:"機知，頭の働き",breakdown:"wit（知っている）→ 素早く物事を知りとらえる力"},
     {word:"wise",meaning:"賢い",breakdown:"wit（知っている）→ 物事をよく知っている"},
     {synonym:true,word:"observer",meaning:"観察者",breakdown:"見ている人。witness は後で証言できる目撃者を指す"},
     {synonym:true,word:"evidence",meaning:"証拠",breakdown:"事実を示すもの。witness はそれを語れる人のほうを指す"}]},

  {id:1120,word:"bullet",partOfSpeech:"名詞",meaning:"弾丸",
   meanings:["名|弾丸"],
   pronunciation:"/ˈbʊlɪt/",part:112,
   example:"The bullet missed him by only a few centimeters.",
   exampleJa:"弾丸は、ほんの数センチのところで彼を外れた。",
   example2:"Police found one bullet near the broken glass window.",
   exampleJa2:"警察は、割れたガラス窓の近くで弾丸を1発見つけた。",
   etymologyProcess:"bull（丸いもの）＋ et（小さい）→ 銃から飛び出す小さな球は…？",
   etymologyConclusion:"bull（丸いもの）＋ et（小さい）→ 銃から勢いよく飛び出す小さな球＝弾丸",
   relatedWords:[
     {word:"bulletin",meaning:"掲示，短い知らせ",breakdown:"bull（丸いもの）＋ et（小さい）→ 丸い封印を押した公式の知らせ"},
     {synonym:true,word:"ball",meaning:"ボール，球",breakdown:"まるい形のもの。bullet は銃から飛び出す小さな球"},
     {synonym:true,word:"shot",meaning:"発砲；弾",breakdown:"撃つこと。bullet は撃ち出される弾そのものを指す"},
     {synonym:true,word:"gun",meaning:"銃",breakdown:"弾を撃つ道具。bullet はそこから飛び出す小さな球"}]},

  {id:1121,word:"sword",partOfSpeech:"名詞",meaning:"剣",
   meanings:["名|剣，刀"],
   pronunciation:"/sɔːrd/",part:113,
   example:"The old sword hung above the large stone fireplace.",
   exampleJa:"その古い剣は、大きな石の暖炉の上に掛かっていた。",
   example2:"He drew his sword and stepped bravely forward.",
   exampleJa2:"彼は剣を抜き、勇敢に前へ進み出た。",
   etymologyProcess:"sword（切る武器）→ 刃で切りつけるための長い武器は…？",
   etymologyConclusion:"sword（切る武器）→ 刃で相手を切りつけるための長い武器＝剣",
   hook:"w は読まず /sɔːrd/。answer や two と同じ、つづりだけ残った w。",
   relatedWords:[
     {synonym:true,word:"blade",meaning:"刃",breakdown:"切る部分そのもの。sword は柄まで含めた武器ぜんたい"},
     {synonym:true,word:"knife",meaning:"ナイフ，包丁",breakdown:"短い刃物。sword は両手で扱うほど長い刃物"},
     {synonym:true,word:"weapon",meaning:"武器",breakdown:"戦いの道具ぜんたい。sword はその中の長い刃物"},
     {synonym:true,word:"dagger",meaning:"短剣",breakdown:"短く鋭い刃物。sword は長く、振って切るための武器"}]},

  {id:1122,word:"wound",partOfSpeech:"名詞",meaning:"（刃物などの）傷",
   meanings:["名|（刃物・弾による）傷","他|傷つける"],
   pronunciation:"/wuːnd/",part:113,
   example:"The young soldier had a deep wound in his leg.",
   exampleJa:"その若い兵士は、脚に深い傷を負っていた。",
   example2:"Her kind words healed the wound in his heart.",
   exampleJa2:"彼女の優しい言葉が、彼の心の傷をいやした。",
   etymologyProcess:"wound（傷つける）→ 刃物や弾で体に負わされた深い傷は…？",
   etymologyConclusion:"wound（傷つける）→ 刃物や弾によって体に負わされた深い傷＝傷",
   hook:"wind（巻く）の過去形 wound /waʊnd/ と同じつづり。傷は /wuːnd/。",
   relatedWords:[
     {synonym:true,word:"injury",meaning:"けが",breakdown:"事故などによるけが。wound は刃物や弾で受けた傷を指す"},
     {synonym:true,word:"cut",meaning:"切り傷",breakdown:"浅く切れた傷。wound はもっと深く重い傷を指す"},
     {synonym:true,word:"scar",meaning:"傷あと",breakdown:"治った後に残る跡。wound はまだふさがっていない傷"},
     {synonym:true,word:"hurt",meaning:"傷つける",breakdown:"痛みを与えること。wound は名詞で使うのが中心"}]},

  {id:1123,word:"triumph",partOfSpeech:"名詞",meaning:"（誇らしい）勝利",
   meanings:["名|（誇らしい）勝利，大成功"],
   pronunciation:"/ˈtraɪəmf/",part:113,
   example:"The team celebrated their triumph in the final game.",
   exampleJa:"チームは決勝戦での勝利を祝った。",
   example2:"Her speech was a real triumph for the whole school.",
   exampleJa2:"彼女のスピーチは、学校全体にとって本当の大成功だった。",
   etymologyProcess:"triumph（凱旋）→ 敵を破って堂々と帰ってくることは…？",
   etymologyConclusion:"triumph（凱旋）→ 敵を破り、堂々と帰ってくるような大きな勝利＝誇らしい勝利",
   hook:"ローマの「凱旋式」がもと。ただ勝つだけでなく、誇らしく祝う勝利。",
   relatedWords:[
     {synonym:true,word:"victory",meaning:"勝利",breakdown:"ふつうの勝ち。triumph は誇らしく祝うような大きな勝利"},
     {synonym:true,word:"success",meaning:"成功",breakdown:"うまくいくこと。triumph は競って勝ち取った輝かしい成果"},
     {synonym:true,word:"win",meaning:"勝つ",breakdown:"勝つという動き。triumph はその結果の晴れやかな勝利"},
     {synonym:true,word:"achievement",meaning:"業績",breakdown:"成し遂げたこと。triumph は人に誇れる輝かしい勝利"}]},

  {id:1124,word:"military",partOfSpeech:"形容詞",meaning:"軍事的な，軍の",
   meanings:["形|軍事的な，軍の","名|（the ～で）軍隊"],
   pronunciation:"/ˈmɪləteri/",part:113,
   example:"The country increased its military budget again this year.",
   exampleJa:"その国は今年もまた、軍の予算を増やした。",
   example2:"Military training starts very early every single morning.",
   exampleJa2:"軍の訓練は、毎朝とても早くに始まる。",
   etymologyProcess:"milit（兵士）＋ ary（形容詞）→ 兵士や軍隊に関わっていると…？",
   etymologyConclusion:"milit（兵士）＋ ary（形容詞）→ 兵士や軍隊に関わっている＝軍事的な",
   relatedWords:[
     {word:"militant",meaning:"闘争的な",breakdown:"milit（兵士）＋ ant（〜な）→ 兵士のように戦う構えの"},
     {word:"militia",meaning:"民兵",breakdown:"milit（兵士）→ ふだんは市民で、必要なとき兵士になる人々"},
     {synonym:true,word:"army",meaning:"軍隊",breakdown:"兵士の集まり。military は軍に関わることぜんたいを指す"},
     {word:"militarism",meaning:"軍国主義",breakdown:"milit（兵士）＋ ism（主義）→ 軍を第一に置く考え方"}]},

  {id:1125,word:"strategy",partOfSpeech:"名詞",meaning:"戦略",
   meanings:["名|戦略，大きな方針"],
   pronunciation:"/ˈstrætədʒi/",part:113,
   example:"The coach explained his strategy before the big game.",
   exampleJa:"監督は大事な試合の前に、自分の戦略を説明した。",
   example2:"A good study strategy saves you a lot of time.",
   exampleJa2:"よい勉強の戦略は、あなたの時間を大きく節約してくれる。",
   etymologyProcess:"strat（軍隊）＋ ag（行う）→ 軍隊を動かして勝ちへ導く筋道は…？",
   etymologyConclusion:"strat（軍隊）＋ ag（行う）→ 軍隊を動かして勝ちに導く、大きな筋道＝戦略",
   relatedWords:[
     {word:"strategic",meaning:"戦略的な",breakdown:"strat（軍隊）＋ ag（行う）＋ ic（形容詞）→ 大きな筋道で動く"},
     {word:"agent",meaning:"代理人",breakdown:"ag（行う）＋ ent（人）→ 代わりに事を行う人"},
     {synonym:true,word:"tactics",meaning:"戦術",breakdown:"その場の具体的な手。strategy は全体を見通した大きな筋道"},
     {synonym:true,word:"plan",meaning:"計画",breakdown:"やることの段取り。strategy は勝つための大きな方針"}]},

  {id:1126,word:"conquer",partOfSpeech:"他動詞",meaning:"征服する；克服する",
   meanings:["他|征服する","他|（恐れなど）を克服する"],
   pronunciation:"/ˈkɑːŋkər/",part:113,
   example:"The army conquered the whole island in one week.",
   exampleJa:"その軍は、1週間で島全体を征服した。",
   example2:"She finally conquered her fear of speaking in public.",
   exampleJa2:"彼女はついに、人前で話す恐怖を克服した。",
   etymologyProcess:"con（すっかり）＋ quer（求める）→ すっかり求めて相手の土地を手に入れると…？",
   etymologyConclusion:"con（すっかり）＋ quer（求める）→ すっかり求めて相手の土地を手に入れる＝征服する",
   relatedWords:[
     {word:"question",meaning:"質問",breakdown:"quest（求める）＋ ion（名詞）→ 答えを求めること"},
     {word:"request",meaning:"依頼する",breakdown:"re（何度も）＋ quest（求める）→ くり返し求める"},
     {word:"require",meaning:"必要とする",breakdown:"re（強く）＋ quire（求める）→ 強く求めて欠かせないとする"},
     {word:"inquiry",meaning:"調査，問い合わせ",breakdown:"in（中へ）＋ quire（求める）→ 中へ分け入って答えを求める"}]},

  {id:1127,word:"defend",partOfSpeech:"他動詞",meaning:"守る，防御する",
   meanings:["他|守る，防御する","他|（意見）を弁護する"],
   pronunciation:"/dɪˈfend/",part:113,
   example:"Soldiers defended the small village for three long days.",
   exampleJa:"兵士たちは3日間、その小さな村を守り続けた。",
   example2:"You must defend your own opinion with clear reasons.",
   exampleJa2:"はっきりした理由で、自分の意見を守らなければならない。",
   etymologyProcess:"de（離して）＋ fend（打つ）→ 打ちかかる相手を打って遠ざけると…？",
   etymologyConclusion:"de（離して）＋ fend（打つ）→ 打ちかかってくる相手を打って遠ざける＝守る",
   relatedWords:[
     {word:"offend",meaning:"怒らせる",breakdown:"of（相手のほうへ）＋ fend（打つ）→ 相手のほうへ打ちつけて傷つける"},
     {word:"offense",meaning:"違反；気分を害すること",breakdown:"of（相手のほうへ）＋ fend（打つ）→ 相手を打って傷つけること"},
     {word:"defendant",meaning:"被告",breakdown:"de（離して）＋ fend（打つ）＋ ant（人）→ 訴えから身を守る側の人"},
     {synonym:true,word:"protect",meaning:"保護する",breakdown:"覆って守ること。defend は攻めてくる相手を退けて守る"}]},

  {id:1128,word:"dominate",partOfSpeech:"他動詞",meaning:"支配する",
   meanings:["他|支配する，圧倒する"],
   pronunciation:"/ˈdɑːmɪneɪt/",part:113,
   example:"One large company dominates the whole car market here.",
   exampleJa:"1つの大きな会社が、ここの自動車市場全体を支配している。",
   example2:"Tall trees dominate the view from my bedroom window.",
   exampleJa2:"高い木々が、私の寝室の窓からの眺めを支配している。",
   etymologyProcess:"dom（家）＋ ate（動詞）→ 家の主のようにふるまって全体を握ると…？",
   etymologyConclusion:"dom（家）＋ ate（動詞）→ 家の主のようにふるまい、全体を思いのままにする＝支配する",
   why:"【なぜ】ラテン語 dominus は「家の主」。家のすべてを取りしきる人のことでした。そこから「思いのままに治める」＝支配する、になりました。\n【つながり】domestic（家庭の）、dome（丸屋根）も同じ家族。ゲームの「ドミノ」もこの語から来たという説があります。",
   relatedWords:[
     {word:"domestic",meaning:"家庭の；国内の",breakdown:"dom（家）＋ ic（形容詞）→ 家の中に関わっている"},
     {word:"dominant",meaning:"支配的な",breakdown:"dom（家）＋ ant（〜な）→ 主のように上に立っている"},
     {word:"dome",meaning:"丸屋根，ドーム",breakdown:"dom（家）→ 家を覆う大きな丸い屋根"},
     {synonym:true,word:"control",meaning:"支配する，管理する",breakdown:"思いどおりに操ること。dominate は力で上に立って押さえる"}]},

  {id:1129,word:"rob",partOfSpeech:"他動詞",meaning:"（人・場所から）奪う，襲う",
   meanings:["他|（人・場所から）奪う，襲う"],
   pronunciation:"/rɑːb/",part:113,
   example:"Thieves sometimes rob small banks late at night.",
   exampleJa:"泥棒は時々、夜遅くに小さな銀行を襲う。",
   example2:"Someone robbed him of his wallet on the crowded train.",
   exampleJa2:"誰かが混んだ電車で、彼から財布を奪った。",
   etymologyProcess:"rob（奪い取る）→ 人から力ずくで持ち物を取り上げると…？",
   etymologyConclusion:"rob（奪い取る）→ 人や場所から、力ずくで持ち物を取り上げる＝奪う",
   hook:"rob A of B（AからBを奪う）。目的語は奪う物ではなく人や場所。",
   relatedWords:[
     {word:"robbery",meaning:"強盗（事件）",breakdown:"rob（奪い取る）＋ ry（もの）→ 力ずくで奪い取る犯罪"},
     {word:"robber",meaning:"強盗（犯）",breakdown:"rob（奪い取る）＋ er（人）→ 力ずくで奪い取る人"},
     {synonym:true,word:"steal",meaning:"盗む",breakdown:"こっそり取ること。rob は人や場所から力ずくで奪う"},
     {synonym:true,word:"thief",meaning:"泥棒",breakdown:"こっそり盗む人。rob は脅して奪う行いのほうを指す"}]},

  {id:1130,word:"deprive",partOfSpeech:"他動詞",meaning:"（権利など）を奪う",
   meanings:["他|（of ～）（人から～）を奪う，失わせる"],
   pronunciation:"/dɪˈpraɪv/",part:113,
   example:"The new law deprived them of their old rights.",
   exampleJa:"その新しい法律は、彼らから古い権利を奪った。",
   example2:"Noise can deprive you of a good night's sleep.",
   exampleJa2:"騒音は、あなたからよい夜の眠りを奪うことがある。",
   etymologyProcess:"de（離して）＋ privi（個人の）→ その人だけのものを引き離して取ると…？",
   etymologyConclusion:"de（離して）＋ privi（個人の）→ その人だけのものを引き離して取り上げる＝奪う",
   relatedWords:[
     {word:"private",meaning:"私的な，個人の",breakdown:"privi（個人の）＋ ate（形容詞）→ その人だけのものである"},
     {word:"privilege",meaning:"特権",breakdown:"privi（個人の）＋ leg（法）→ その人だけに認められた決まり"},
     {word:"privacy",meaning:"私生活，プライバシー",breakdown:"privi（個人の）＋ cy（名詞）→ 他人を入れない自分だけの領域"},
     {synonym:true,word:"remove",meaning:"取り除く",breakdown:"どけること。deprive は人から大切なものを取り上げること"}]},

  {id:1131,word:"devastate",partOfSpeech:"他動詞",meaning:"壊滅させる",
   meanings:["他|壊滅させる，荒廃させる"],
   pronunciation:"/ˈdevəsteɪt/",part:114,
   example:"The huge fire devastated the whole northern forest.",
   exampleJa:"その巨大な火事は、北の森全体を壊滅させた。",
   example2:"A very strong typhoon can devastate a small island.",
   exampleJa2:"とても強い台風は、小さな島を壊滅させることがある。",
   etymologyProcess:"de（すっかり）＋ vast（荒れ果てた）→ 一帯をすっかり荒れ果てた姿にすると…？",
   etymologyConclusion:"de（すっかり）＋ vast（荒れ果てた）→ 一帯をすっかり荒れ果てた姿に変える＝壊滅させる",
   relatedWords:[
     {word:"vast",meaning:"広大な",breakdown:"vast（荒れ果てた）→ 果てしなく広がって、がらんとしている"},
     {word:"waste",meaning:"むだにする；荒れ地",breakdown:"wast（荒れ果てた）→ 使わないまま荒れさせてしまう"},
     {synonym:true,word:"destroy",meaning:"破壊する",breakdown:"壊すこと。devastate は広い範囲を荒れ果てさせること"},
     {synonym:true,word:"ruin",meaning:"台なしにする",breakdown:"だめにすること。devastate は大きな被害で荒廃させること"}]},

  {id:1132,word:"crash",partOfSpeech:"自動詞",meaning:"激突する",
   meanings:["自|激突する，衝突する","自|（機械が）突然止まる","名|衝突事故"],
   pronunciation:"/kræʃ/",part:114,
   example:"The car crashed into a tree near the school gate.",
   exampleJa:"その車は、校門の近くの木に激突した。",
   example2:"My computer often crashes when I open big files.",
   exampleJa2:"大きなファイルを開くと、私のパソコンはよく突然止まる。",
   etymologyProcess:"crash（ガシャンという音）→ 大きな音を立てて激しくぶつかると…？",
   etymologyConclusion:"crash（ガシャンという音）→ 大きな音を立てて激しくぶつかる＝激突する",
   hook:"音をまねて生まれた語。「ガシャン」という音そのものが語になった。",
   relatedWords:[
     {synonym:true,word:"collide",meaning:"衝突する",breakdown:"ぶつかること。crash は大きな音と壊れ方を伴う"},
     {synonym:true,word:"smash",meaning:"打ち砕く",breakdown:"粉々にすること。crash はぶつかって壊れることを言う"},
     {synonym:true,word:"bang",meaning:"バタンと鳴る",breakdown:"同じく音をまねた語。crash はもっと壊れる感じが強い"},
     {synonym:true,word:"bump",meaning:"ドンとぶつかる",breakdown:"軽くぶつかること。crash は大きな音を立てて壊れるほどの衝突"}]},

  {id:1133,word:"hazard",partOfSpeech:"名詞",meaning:"危険（のもと）",
   meanings:["名|危険（のもと），危険な物事"],
   pronunciation:"/ˈhæzərd/",part:114,
   example:"Wet fallen leaves are a real hazard for cyclists.",
   exampleJa:"ぬれた落ち葉は、自転車に乗る人にとって本当の危険だ。",
   example2:"Smoking is a serious health hazard for everyone.",
   exampleJa2:"喫煙は、すべての人にとって深刻な健康上の危険だ。",
   etymologyProcess:"hazard（さいころ）→ 結果が読めないまま身に降りかかる危うさは…？",
   etymologyConclusion:"hazard（さいころ）→ さいころのように結果が読めず、身に降りかかる危うさ＝危険のもと",
   hook:"ゴルフの「ハザード」でおなじみ。事故につながる危険のもとが芯。",
   why:"【なぜ】もとはアラビア語の「さいころ」から来たとされ、中世には「さいころ賭博」を指しました。出目が読めない勝負から、「運まかせの危うさ」＝危険、へ移りました。\n【つながり】ゴルフの「ハザード（池や砂地）」、車の hazard lamp（非常点滅灯）も同じ語です。",
   relatedWords:[
     {synonym:true,word:"danger",meaning:"危険",breakdown:"危ないこと全般。hazard は事故につながる具体的な危険源"},
     {synonym:true,word:"risk",meaning:"危険性，リスク",breakdown:"起こりうる度合い。hazard は危険のもとそのものを指す"},
     {synonym:true,word:"threat",meaning:"脅威",breakdown:"害をもたらしそうなもの。hazard は事故を招く危険な状態"},
     {word:"hazardous",meaning:"危険な",breakdown:"hazard（さいころ）＋ ous（形容詞）→ 出目が読めないほど危うい"}]},

  {id:1134,word:"debris",partOfSpeech:"名詞",meaning:"破片，残骸",
   meanings:["名|破片，残骸，がれき"],
   pronunciation:"/dəˈbriː/",part:114,
   example:"Debris from the storm covered the whole narrow road.",
   exampleJa:"嵐による破片が、その狭い道全体を覆っていた。",
   example2:"Workers cleared the debris after the old building fell.",
   exampleJa2:"古い建物が倒れた後、作業員たちが残骸を片づけた。",
   etymologyProcess:"debris（砕けたかけら）→ すっかり砕けて散らばったものは…？",
   etymologyConclusion:"debris（砕けたかけら）→ すっかり砕けて散らばってしまったかけら＝破片",
   hook:"フランス語の de（すっかり）＋ briser（砕く）から。s は読まない。",
   relatedWords:[
     {synonym:true,word:"wreckage",meaning:"残骸",breakdown:"壊れた物の残り。debris は散らばったかけらを指す"},
     {synonym:true,word:"fragment",meaning:"断片",breakdown:"割れた一片。debris は散らばった破片ぜんたいを指す"},
     {synonym:true,word:"rubble",meaning:"がれき",breakdown:"崩れた石やれんが。debris はもっと広く破片全般を指す"},
     {synonym:true,word:"trash",meaning:"ごみ",breakdown:"捨てるもの。debris は壊れて散らばったかけらを指す"}]},

  {id:1135,word:"orphan",partOfSpeech:"名詞",meaning:"孤児",
   meanings:["名|孤児"],
   pronunciation:"/ˈɔːrfn/",part:114,
   example:"The war left many young orphans in that country.",
   exampleJa:"その戦争は、あの国に多くの幼い孤児を残した。",
   example2:"She grew up as an orphan in a small village.",
   exampleJa2:"彼女は小さな村で、孤児として育った。",
   etymologyProcess:"orph（親を失った）→ 親を亡くして一人になった子どもは…？",
   etymologyConclusion:"orph（親を失った）→ 親を亡くして一人になってしまった子ども＝孤児",
   relatedWords:[
     {word:"orphanage",meaning:"孤児院",breakdown:"orph（親を失った）＋ age（名詞）→ 親のない子を育てるところ"},
     {synonym:true,word:"child",meaning:"子ども",breakdown:"子どもぜんたい。orphan は親を亡くした子どもだけを指す"},
     {synonym:true,word:"foster",meaning:"里親として育てる",breakdown:"よその子を引き取って育てること。orphan はその対象になる子ども"},
     {synonym:true,word:"adopt",meaning:"養子にする",breakdown:"引き取って育てること。orphan はその対象になる子ども"}]},

  {id:1136,word:"slave",partOfSpeech:"名詞",meaning:"奴隷",
   meanings:["名|奴隷"],
   pronunciation:"/sleɪv/",part:114,
   example:"The museum shows how slaves lived long ago.",
   exampleJa:"その博物館は、奴隷が昔どのように暮らしたかを示している。",
   example2:"No one should ever be treated as a slave.",
   exampleJa2:"誰も決して、奴隷として扱われてはならない。",
   etymologyProcess:"slav（スラブ人）→ 自由を奪われ、人に所有されて働かされる人は…？",
   etymologyConclusion:"slav（スラブ人）→ 自由を奪われ、人に所有されて働かされる人＝奴隷",
   why:"【なぜ】中世のヨーロッパで、捕らえられて売られた人の多くがスラブ系の人々だったため、民族名 Slav がそのまま「奴隷」を表す語になりました。\n【つながり】slavery（奴隷制）も同じ語。国名のスロバキア、スロベニアも Slav から来ています。",
   relatedWords:[
     {word:"slavery",meaning:"奴隷制",breakdown:"slav（スラブ人）＋ ry（もの）→ 人を奴隷として使う仕組み"},
     {synonym:true,word:"servant",meaning:"召使い",breakdown:"仕える人。slave は自由を奪われて所有されている人"},
     {synonym:true,word:"labor",meaning:"労働",breakdown:"働くこと。slave はそれを強いられている人を指す"},
     {synonym:true,word:"captive",meaning:"捕虜，とらわれ人",breakdown:"捕らえられた人。slave は所有され働かされる人を指す"}]},

  {id:1137,word:"acquaintance",partOfSpeech:"名詞",meaning:"知人",
   meanings:["名|知人，知り合い","名|（ある分野の）知識"],
   pronunciation:"/əˈkweɪntəns/",part:114,
   example:"He is just an acquaintance, not a close friend.",
   exampleJa:"彼はただの知人で、親しい友達ではない。",
   example2:"I met an old acquaintance at the train station.",
   exampleJa2:"私は駅で、昔の知人に会った。",
   etymologyProcess:"ad（〜へ）＋ co（共に）＋ gn（知る）→ 顔と名前を知っている程度の相手は…？",
   etymologyConclusion:"ad（〜へ）＋ co（共に）＋ gn（知る）→ 顔と名前を知っている程度の相手＝知人",
   relatedWords:[
     {word:"acquaint",meaning:"知らせる，慣れさせる",breakdown:"ad（〜へ）＋ gn（知る）→ 知っている状態にしてやる"},
     {word:"recognize",meaning:"見分ける，認める",breakdown:"re（再び）＋ co（共に）＋ gn（知る）→ 前に知ったものだと分かる"},
     {word:"ignore",meaning:"無視する",breakdown:"in（否定）＋ gnor（知る）→ 知らないことにして取り合わない"},
     {synonym:true,word:"friend",meaning:"友達",breakdown:"心を許す相手。acquaintance は顔を知っている程度の間柄"}]},

  {id:1138,word:"merchant",partOfSpeech:"名詞",meaning:"商人",
   meanings:["名|商人，貿易商"],
   pronunciation:"/ˈmɜːrtʃənt/",part:114,
   example:"A rich merchant built this large old wooden house.",
   exampleJa:"裕福な商人が、この大きな古い木の家を建てた。",
   example2:"Merchants from many countries met at that busy port.",
   exampleJa2:"多くの国からの商人が、そのにぎやかな港で出会った。",
   etymologyProcess:"merc（商品）＋ ant（人）→ 商品を仕入れて売り買いする人は…？",
   etymologyConclusion:"merc（商品）＋ ant（人）→ 商品を仕入れて売り買いする人＝商人",
   relatedWords:[
     {word:"commerce",meaning:"商業",breakdown:"com（共に）＋ merc（商品）→ 互いに商品をやりとりすること"},
     {word:"merchandise",meaning:"商品",breakdown:"merc（商品）→ 売り買いされる品物ぜんたい"},
     {word:"market",meaning:"市場",breakdown:"merc（商品）→ 商品を持ち寄って売り買いする場"},
     {synonym:true,word:"trader",meaning:"貿易商，取引する人",breakdown:"取引する人。merchant は品物を仕入れて売る商人"}]},

  {id:1139,word:"resident",partOfSpeech:"名詞",meaning:"住人，居住者",
   meanings:["名|住人，居住者","形|住み込みの"],
   pronunciation:"/ˈrezɪdənt/",part:114,
   example:"Every resident of this town knows that old story.",
   exampleJa:"この町のすべての住人が、あの古い話を知っている。",
   example2:"New residents must register at the city office first.",
   exampleJa2:"新しい住人は、まず市役所で登録しなければならない。",
   etymologyProcess:"re（後ろへ）＋ sid（座る）→ その土地に腰を落ち着けている人は…？",
   etymologyConclusion:"re（後ろへ）＋ sid（座る）→ その土地に腰を落ち着けて座り続ける人＝住人",
   relatedWords:[
     {word:"reside",meaning:"住む",breakdown:"re（後ろへ）＋ sid（座る）→ その土地に腰を落ち着ける"},
     {word:"president",meaning:"大統領，社長",breakdown:"pre（先に）＋ sid（座る）→ いちばん先の席に座る人"},
     {word:"residence",meaning:"住まい",breakdown:"re（後ろへ）＋ sid（座る）＋ ence（名詞）→ 腰を落ち着けている所"},
     {synonym:true,word:"citizen",meaning:"市民",breakdown:"町に住む権利を持つ人。resident はそこに住んでいる人"}]},

  {id:1140,word:"crew",partOfSpeech:"名詞",meaning:"乗組員；班",
   meanings:["名|乗組員，乗務員","名|（仕事の）班，一団"],
   pronunciation:"/kruː/",part:114,
   example:"The whole crew worked hard during the long voyage.",
   exampleJa:"乗組員全体が、長い航海の間よく働いた。",
   example2:"Our film crew arrived at the island yesterday morning.",
   exampleJa2:"私たちの撮影班は、昨日の朝その島に到着した。",
   etymologyProcess:"cruit（育つ）→ 人数を増やして組まれた一団は…？",
   etymologyConclusion:"cruit（育つ）→ 人数を増やして組まれ、共に働く一団＝乗組員",
   why:"【なぜ】もとのフランス語 creue は「増えたもの・増援」。兵を増やした一団のことでした。そこから船や飛行機を動かす「ひとまとまりの人たち」＝乗組員になりました。\n【つながり】recruit（新しく人を集める）も同じ「育つ・増える」の家族です。",
   relatedWords:[
     {word:"recruit",meaning:"新規採用する",breakdown:"re（再び）＋ cruit（育つ）→ 人を新しく集めて組織を育て直す"},
     {word:"increase",meaning:"増える",breakdown:"in（中へ）＋ creas（育つ）→ 中でどんどん育って増える"},
     {synonym:true,word:"team",meaning:"チーム，班",breakdown:"目的を共にする集まり。crew は船や機を動かす一団"},
     {synonym:true,word:"staff",meaning:"職員，スタッフ",breakdown:"働く人たち。crew は乗り物や現場を動かす一団"}]},

  {id:1141,word:"chase",partOfSpeech:"他動詞",meaning:"追いかける",
   meanings:["他|追いかける，追跡する","名|追跡"],
   pronunciation:"/tʃeɪs/",part:115,
   example:"The dog chased a small cat across the wide yard.",
   exampleJa:"その犬は、広い庭の向こうへ小さな猫を追いかけた。",
   example2:"The police chased the stolen car through narrow streets.",
   exampleJa2:"警察は、狭い通りを通って盗まれた車を追いかけた。",
   etymologyProcess:"chas（つかむ）→ つかまえようとして後を走って追うと…？",
   etymologyConclusion:"chas（つかむ）→ つかまえようとして、相手の後を走って追う＝追いかける",
   relatedWords:[
     {word:"catch",meaning:"捕まえる",breakdown:"chas（つかむ）→ 追いついて手でつかまえる"},
     {word:"capture",meaning:"捕らえる",breakdown:"cap（つかむ）＋ ure（名詞）→ つかまえて自分のものにする"},
     {word:"capable",meaning:"能力がある",breakdown:"cap（つかむ）＋ able（できる）→ しっかりつかんでやり切れる"},
     {synonym:true,word:"pursue",meaning:"追い求める",breakdown:"後を追うこと。chase は走って追いかける動きが中心"}]},

  {id:1142,word:"proceed",partOfSpeech:"自動詞",meaning:"進む，進行する",
   meanings:["自|進む，進行する","自|（to ～）次に～へ移る"],
   pronunciation:"/proʊˈsiːd/",part:115,
   example:"Please proceed to the next question on the test.",
   exampleJa:"テストの次の問題へ進んでください。",
   example2:"The work proceeded smoothly despite the very heavy rain.",
   exampleJa2:"とても激しい雨にもかかわらず、作業は順調に進んだ。",
   etymologyProcess:"pro（前へ）＋ ceed（行く）→ 止まらずに前へ進んでいくと…？",
   etymologyConclusion:"pro（前へ）＋ ceed（行く）→ 止まらずに前へ進んでいく＝進む",
   relatedWords:[
     {word:"process",meaning:"過程",breakdown:"pro（前へ）＋ cess（行く）→ 前へ進んでいく道のり"},
     {word:"succeed",meaning:"成功する；後を継ぐ",breakdown:"suc（すぐ後に）＋ ceed（行く）→ すぐ後について行き着く"},
     {word:"exceed",meaning:"超える",breakdown:"ex（外へ）＋ ceed（行く）→ 決められた枠の外へ行ってしまう"},
     {word:"precede",meaning:"先に行く，先立つ",breakdown:"pre（先に）＋ ced（行く）→ ほかより先に行く"}]},

  {id:1143,word:"fade",partOfSpeech:"自動詞",meaning:"薄れる，色あせる",
   meanings:["自|薄れる，色あせる","自|（音・記憶が）次第に消える"],
   pronunciation:"/feɪd/",part:115,
   example:"The colors of the old curtain faded in strong sunlight.",
   exampleJa:"その古いカーテンの色は、強い日光で薄れた。",
   example2:"Memories of that day slowly fade a little every year.",
   exampleJa2:"あの日の記憶は、毎年少しずつゆっくりと薄れていく。",
   etymologyProcess:"fade（色あせる）→ 色や音が少しずつ弱まって消えていくと…？",
   etymologyConclusion:"fade（色あせる）→ 色や音が少しずつ弱まって消えていく＝薄れる",
   hook:"音楽の「フェードアウト」でおなじみ。だんだん弱まって消えること。",
   relatedWords:[
     {synonym:true,word:"disappear",meaning:"消える",breakdown:"見えなくなること。fade は少しずつ弱まって消えていく"},
     {synonym:true,word:"weaken",meaning:"弱まる",breakdown:"力が落ちること。fade は色や音がだんだん薄くなること"},
     {synonym:true,word:"pale",meaning:"青白い，薄い",breakdown:"色が薄いようす。fade はその状態へ変わっていく動き"},
     {synonym:true,word:"dim",meaning:"薄暗くなる",breakdown:"光が弱まること。fade は色・音・記憶にも使える"}]},

  {id:1144,word:"dissolve",partOfSpeech:"自動詞",meaning:"溶ける",
   meanings:["自|溶ける","他|溶かす；（組織）を解散させる"],
   pronunciation:"/dɪˈzɑːlv/",part:115,
   example:"Sugar dissolves quickly in a cup of hot tea.",
   exampleJa:"砂糖は、熱い紅茶のカップの中ですぐに溶ける。",
   example2:"The government dissolved the old committee last month.",
   exampleJa2:"政府は先月、その古い委員会を解散させた。",
   etymologyProcess:"dis（バラバラに）＋ solve（ほどく）→ 粒がばらばらにほどけて液に混ざると…？",
   etymologyConclusion:"dis（バラバラに）＋ solve（ほどく）→ 粒がばらばらにほどけて液に混ざる＝溶ける",
   relatedWords:[
     {word:"solve",meaning:"解く，解決する",breakdown:"solve（ほどく）→ もつれをほどいて答えを出す"},
     {word:"solution",meaning:"解決；溶液",breakdown:"solu（ほどく）＋ ion（名詞）→ ほどけて解けた状態"},
     {word:"resolve",meaning:"解決する；決意する",breakdown:"re（すっかり）＋ solve（ほどく）→ もつれをすっかりほどく"},
     {word:"absolute",meaning:"絶対的な",breakdown:"ab（離れて）＋ solu（ほどく）→ 何からも解き放たれている"}]},

  {id:1145,word:"float",partOfSpeech:"自動詞",meaning:"浮かぶ",
   meanings:["自|浮かぶ，漂う","名|浮き；フロート"],
   pronunciation:"/floʊt/",part:115,
   example:"Wooden boats float easily on the calm quiet lake.",
   exampleJa:"木の舟は、穏やかで静かな湖に軽々と浮かぶ。",
   example2:"White clouds floated slowly across the wide blue sky.",
   exampleJa2:"白い雲が、広い青空をゆっくり浮かんで流れていった。",
   etymologyProcess:"float（水に乗る）→ 沈まずに水や空気の上に乗っていると…？",
   etymologyConclusion:"float（水に乗る）→ 沈まずに、水や空気の上に乗っている＝浮かぶ",
   hook:"「フロート（浮き）」でおなじみ。沈まず表面に乗っていることが芯。",
   relatedWords:[
     {synonym:true,word:"drift",meaning:"漂う",breakdown:"流れに任せて動くこと。float は沈まずにいることが中心"},
     {synonym:true,word:"swim",meaning:"泳ぐ",breakdown:"自分の力で進むこと。float は力を抜いて浮いているだけ"},
     {word:"fleet",meaning:"艦隊",breakdown:"float（水に乗る）→ 浮かんで進む船のひとそろい"},
     {synonym:true,word:"flow",meaning:"流れる",breakdown:"水が進むこと。float はその上に乗っているほうを言う"}]},

  {id:1146,word:"sink",partOfSpeech:"自動詞",meaning:"沈む",
   meanings:["自|沈む","名|（台所の）流し"],
   pronunciation:"/sɪŋk/",part:115,
   example:"Heavy stones sink quickly to the bottom of the pond.",
   exampleJa:"重い石は、池の底へすぐに沈む。",
   example2:"The old ship sank during a terrible winter storm.",
   exampleJa2:"その古い船は、ひどい冬の嵐の間に沈んだ。",
   etymologyProcess:"sink（沈む）→ 水や砂の中へ下がって見えなくなると…？",
   etymologyConclusion:"sink（沈む）→ 水や砂の中へ下がっていって見えなくなる＝沈む",
   hook:"台所の「シンク」も同じ語。水が下へ落ちていく場所のこと。",
   relatedWords:[
     {synonym:true,word:"drown",meaning:"おぼれる",breakdown:"水に沈んで息ができなくなること。sink は物にも使う"},
     {synonym:true,word:"dive",meaning:"飛び込む，もぐる",breakdown:"自分から水に入ること。sink はひとりでに沈むこと"},
     {synonym:true,word:"fall",meaning:"落ちる",breakdown:"下へ落ちること。sink は水や柔らかい物の中へ沈むこと"},
     {synonym:true,word:"submerge",meaning:"水中に沈める",breakdown:"水の下に入れること。sink は自然に沈んでいくこと"}]},

  {id:1147,word:"bounce",partOfSpeech:"自動詞",meaning:"跳ねる，弾む",
   meanings:["自|跳ねる，弾む","他|弾ませる"],
   pronunciation:"/baʊns/",part:115,
   example:"The ball bounced twice before it hit the net.",
   exampleJa:"そのボールは、ネットに当たる前に2回跳ねた。",
   example2:"Children love to bounce on the big soft bed.",
   exampleJa2:"子どもたちは、大きな柔らかいベッドの上で跳ねるのが大好きだ。",
   etymologyProcess:"bounce（ドンと当たる）→ ぶつかった勢いで跳ね返ると…？",
   etymologyConclusion:"bounce（ドンと当たる）→ ぶつかった勢いでそのまま跳ね返る＝跳ねる",
   hook:"ボールが「バウンドする」動きそのまま。当たって跳ね返るのが芯。",
   relatedWords:[
     {synonym:true,word:"jump",meaning:"跳ぶ",breakdown:"自分の力で跳び上がること。bounce はぶつかって跳ね返ること"},
     {synonym:true,word:"rebound",meaning:"跳ね返る",breakdown:"別語だがはね返る動きは同じ。bounce はくり返し弾む感じを含む"},
     {synonym:true,word:"spring",meaning:"跳び出す，ばね",breakdown:"勢いよく跳ねること。bounce は当たって返る動きを指す"},
     {synonym:true,word:"bump",meaning:"ドンとぶつかる",breakdown:"ぶつかること。bounce はその後に跳ね返るところまで言う"}]},

  {id:1148,word:"transform",partOfSpeech:"他動詞",meaning:"（すっかり）変える",
   meanings:["他|（すっかり）変える，変形させる"],
   pronunciation:"/trænsˈfɔːrm/",part:115,
   example:"Computers transformed the way we study English today.",
   exampleJa:"コンピューターは、今の私たちの英語の学び方をすっかり変えた。",
   example2:"Strong heat can transform water into invisible steam.",
   exampleJa2:"強い熱は、水を目に見えない蒸気にすっかり変えることができる。",
   etymologyProcess:"trans（越えて）＋ form（形）→ 元の形の境を越えて別の形にすると…？",
   etymologyConclusion:"trans（越えて）＋ form（形）→ 元の形の境を越えて、別の形にしてしまう＝すっかり変える",
   relatedWords:[
     {word:"form",meaning:"形；形づくる",breakdown:"form（形）→ 目に見えるまとまった形"},
     {word:"reform",meaning:"改革する",breakdown:"re（再び）＋ form（形）→ もう一度よい形に作り直す"},
     {word:"inform",meaning:"知らせる",breakdown:"in（中へ）＋ form（形）→ 相手の頭の中に形を作ってやる"},
     {word:"uniform",meaning:"制服；均一の",breakdown:"uni（1つの）＋ form（形）→ みんな同じ一つの形"}]},

  {id:1149,word:"shift",partOfSpeech:"名詞",meaning:"転換，移り変わり",
   meanings:["名|転換，移り変わり","名|交代勤務","他|移す，ずらす"],
   pronunciation:"/ʃɪft/",part:115,
   example:"There was a big shift in public opinion last year.",
   exampleJa:"昨年、世論に大きな転換があった。",
   example2:"My father works the night shift at the car factory.",
   exampleJa2:"父は自動車工場で、夜の交代勤務をしている。",
   etymologyProcess:"shift（ずらす）→ 位置や考えをずらして別のほうへ移すと…？",
   etymologyConclusion:"shift（ずらす）→ 位置や考えをずらして、別のほうへ移していくこと＝転換",
   hook:"「シフトキー」も交代勤務の「シフト」も同じ。位置をずらすこと。",
   relatedWords:[
     {synonym:true,word:"change",meaning:"変化",breakdown:"変わること全般。shift は位置や向きがずれていく変化"},
     {synonym:true,word:"move",meaning:"動かす",breakdown:"動かすこと。shift は少しずらして別の位置へ移すこと"},
     {synonym:true,word:"switch",meaning:"切りかえる",breakdown:"ぱっと入れかえること。shift はゆるやかにずれていく感じ"},
     {synonym:true,word:"turn",meaning:"向きを変える",breakdown:"向きを変えること。shift は位置や考えの移り変わり"}]},

  {id:1150,word:"modify",partOfSpeech:"他動詞",meaning:"（一部を）変更する",
   meanings:["他|（一部を）変更する，手直しする"],
   pronunciation:"/ˈmɑːdɪfaɪ/",part:115,
   example:"You may modify this plan if you really need to.",
   exampleJa:"本当に必要なら、この計画を変更してもかまいません。",
   example2:"Engineers modified the design after the very first test.",
   exampleJa2:"技術者たちは、いちばん最初の試験の後で設計を変更した。",
   etymologyProcess:"modus（ほどよさ）＋ fy（する）→ ちょうどよい形に手を入れると…？",
   etymologyConclusion:"modus（ほどよさ）＋ fy（する）→ ちょうどよい形になるように手を入れる＝一部を変更する",
   relatedWords:[
     {word:"model",meaning:"模型；手本",breakdown:"modus（ほどよさ）＋ el（小さい）→ 寸法どおりに作った小さな形"},
     {word:"moderate",meaning:"適度な",breakdown:"modus（ほどよさ）＋ ate（形容詞）→ ほどよい量に収まっている"},
     {word:"modest",meaning:"控えめな",breakdown:"modus（ほどよさ）→ ほどよさを越えず控えめでいる"},
     {word:"mode",meaning:"方法，様式",breakdown:"modus（ほどよさ）→ ほどよく整えられたやり方"}]},
