  {id:1151,word:"revise",partOfSpeech:"他動詞",meaning:"改訂する，見直して書き直す",
   meanings:["他|改訂する，見直して書き直す"],
   pronunciation:"/rɪˈvaɪz/",part:116,
   example:"Please revise your essay before the final submission deadline.",
   exampleJa:"最終の提出期限の前に、小論文を見直して書き直してください。",
   example2:"The plan was revised after the students' many comments.",
   exampleJa2:"その計画は、生徒たちの多くの意見を受けて書き直された。",
   etymologyProcess:"re（再び）＋ vis（見る）→ もう一度見直して直すところを直すと…？",
   etymologyConclusion:"re（再び）＋ vis（見る）→ もう一度見直して、直すべきところを直す＝見直して書き直す",
   relatedWords:[
     {word:"vision",meaning:"視力；展望",breakdown:"vis（見る）＋ ion（名詞）→ 目で物を見てとらえる力"},
     {word:"visible",meaning:"目に見える",breakdown:"vis（見る）＋ ible（できる）→ 見ることができる"},
     {word:"advise",meaning:"忠告する",breakdown:"ad（〜へ）＋ vis（見る）→ そちらを見るように言ってやる"},
     {word:"supervise",meaning:"監督する",breakdown:"super（上から）＋ vis（見る）→ 上から全体を見張る"}]},

  {id:1152,word:"enhance",partOfSpeech:"他動詞",meaning:"（質を）高める",
   meanings:["他|（質・価値）を高める，向上させる"],
   pronunciation:"/ɪnˈhæns/",part:116,
   example:"Good sleep can enhance your memory and your mood.",
   exampleJa:"よい睡眠は、記憶力と気分を高めることがある。",
   example2:"New lights enhanced the beauty of the old stone bridge.",
   exampleJa2:"新しい照明が、その古い石橋の美しさを高めた。",
   etymologyProcess:"en（〜にする）＋ hanc（高い）→ 今より一段高い状態へ引き上げると…？",
   etymologyConclusion:"en（〜にする）＋ hanc（高い）→ 今より一段高い状態へ引き上げる＝質を高める",
   why:"【なぜ】もとはラテン語 altus（高い）。俗ラテン語 inaltiare（高くする）がフランス語を通るあいだに、h の入った enhaucier の形になり、英語へ入りました。だから alt と hanc は同じ「高い」です。\n【つながり】altitude（高度）、exalt（高くたたえる）も同じ家族です。",
   relatedWords:[
     {word:"altitude",meaning:"高度",breakdown:"alt（高い）＋ tude（名詞）→ どれだけ高いかという度合い"},
     {word:"exalt",meaning:"高める，たたえる",breakdown:"ex（外へ）＋ alt（高い）→ 高く持ち上げてほめたたえる"},
     {synonym:true,word:"improve",meaning:"改善する",breakdown:"よくすること。enhance はすでによいものをさらに高めること"},
     {synonym:true,word:"boost",meaning:"押し上げる",breakdown:"下から押し上げること。enhance は質や価値を高めること"}]},

  {id:1153,word:"lower",partOfSpeech:"他動詞",meaning:"下げる",
   meanings:["他|（高さ・値）を下げる","形|より低い"],
   pronunciation:"/ˈloʊər/",part:116,
   example:"Please lower your voice in this very quiet library.",
   exampleJa:"このとても静かな図書館では、声を下げてください。",
   example2:"The shop lowered the price of all winter coats.",
   exampleJa2:"その店は、すべての冬のコートの値段を下げた。",
   etymologyProcess:"low（低い）＋ er（より）→ 今より低い位置や値へ移すと…？",
   etymologyConclusion:"low（低い）＋ er（より）→ 今より低い位置や値のほうへ移す＝下げる",
   relatedWords:[
     {word:"low",meaning:"低い",breakdown:"low（低い）→ 高さや程度が下のほうにある"},
     {word:"below",meaning:"～の下に",breakdown:"low（低い）→ 低いほうに位置して"},
     {synonym:true,word:"reduce",meaning:"減らす",breakdown:"量を減らすこと。lower は高さや値を低いほうへ移すこと"},
     {synonym:true,word:"drop",meaning:"落とす",breakdown:"落とすこと。lower はゆっくり下のほうへ移すこと"}]},

  {id:1154,word:"voyage",partOfSpeech:"名詞",meaning:"航海，長い船旅",
   meanings:["名|航海，長い船旅","名|（宇宙の）旅"],
   pronunciation:"/ˈvɔɪɪdʒ/",part:116,
   example:"Their voyage across the wide ocean took three months.",
   exampleJa:"彼らの広い大洋を越える航海は、3か月かかった。",
   example2:"The old sailor described his very first long voyage.",
   exampleJa2:"その老いた船乗りは、いちばん最初の長い航海について語った。",
   etymologyProcess:"vi（道）＋ age（名詞）→ 海の上の長い道のりを行くことは…？",
   etymologyConclusion:"vi（道）＋ age（名詞）→ 海の上の長い道のりを行くこと＝航海",
   why:"【なぜ】ラテン語 viaticum は「旅のための路銀・旅支度」。via（道）から出た語で、フランス語を通るうちに「旅そのもの」を指すようになり、英語では特に海の長旅＝航海を表すようになりました。\n【つながり】via（〜を経由して）、obvious（道の真ん中に見えている）も同じ vi の家族です。",
   relatedWords:[
     {word:"via",meaning:"～を経由して",breakdown:"via（道）→ その道を通って向こうへ行く"},
     {word:"obvious",meaning:"明らかな",breakdown:"ob（〜に向かって）＋ vi（道）→ 道の真ん中に立ちふさがって見える"},
     {word:"previous",meaning:"前の",breakdown:"pre（先に）＋ vi（道）→ 同じ道をひと足先に通っていた"},
     {synonym:true,word:"journey",meaning:"旅",breakdown:"長い旅ぜんたい。voyage は海や宇宙を行く長い旅を指す"}]},

  {id:1155,word:"confirm",partOfSpeech:"他動詞",meaning:"確認する，裏づける",
   meanings:["他|確認する，裏づける"],
   pronunciation:"/kənˈfɜːrm/",part:116,
   example:"Please confirm your hotel reservation by email today.",
   exampleJa:"今日、メールでホテルの予約を確認してください。",
   example2:"The test results confirmed the doctor's first opinion.",
   exampleJa2:"検査の結果は、医師の最初の見立てを裏づけた。",
   etymologyProcess:"con（すっかり）＋ firm（しっかりした）→ ぐらつきをなくしてすっかり固めると…？",
   etymologyConclusion:"con（すっかり）＋ firm（しっかりした）→ ぐらつきをなくしてすっかり固める＝確認する",
   relatedWords:[
     {word:"firm",meaning:"しっかりした；会社",breakdown:"firm（しっかりした）→ ぐらつかず固い"},
     {word:"firmly",meaning:"しっかりと",breakdown:"firm（しっかりした）＋ ly（副詞）→ 固く、ぐらつかずに"},
     {word:"affirm",meaning:"断言する",breakdown:"ad（〜へ）＋ firm（しっかりした）→ そうだと固く言い切る"},
     {synonym:true,word:"check",meaning:"調べる，確かめる",breakdown:"調べること。confirm は「間違いない」と固めるところまで言う"}]},

  {id:1156,word:"ensure",partOfSpeech:"他動詞",meaning:"確実にする",
   meanings:["他|確実にする，保証する"],
   pronunciation:"/ɪnˈʃʊr/",part:116,
   example:"Please ensure that all the windows are firmly closed.",
   exampleJa:"すべての窓がしっかり閉まっていることを確実にしてください。",
   example2:"Careful daily practice ensures a good result on stage.",
   exampleJa2:"毎日の入念な練習が、舞台でのよい結果を確実にする。",
   etymologyProcess:"en（〜にする）＋ sure（確かな）→ そうなると確かな状態にしておくと…？",
   etymologyConclusion:"en（〜にする）＋ sure（確かな）→ そうなると確かな状態にしておく＝確実にする",
   relatedWords:[
     {word:"sure",meaning:"確かな",breakdown:"sure（確かな）→ 疑う余地なくはっきりしている"},
     {word:"insure",meaning:"保険をかける",breakdown:"in（〜に）＋ sure（確かな）→ 万一に備えて確かにしておく"},
     {word:"assure",meaning:"保証する，安心させる",breakdown:"ad（〜へ）＋ sure（確かな）→ 相手に確かだと言ってやる"},
     {word:"insurance",meaning:"保険",breakdown:"in（〜に）＋ sure（確かな）＋ ance（名詞）→ 万一に備える仕組み"}]},

  {id:1157,word:"address",partOfSpeech:"他動詞",meaning:"（問題に）取り組む",
   meanings:["他|（問題に）取り組む","他|（人に）演説する","名|住所"],
   pronunciation:"/əˈdres/",part:116,
   example:"We must address this problem before it grows bigger.",
   exampleJa:"もっと大きくなる前に、私たちはこの問題に取り組まなければならない。",
   example2:"The principal addressed the whole school early this morning.",
   exampleJa2:"校長は今朝早く、全校に向けて演説した。",
   etymologyProcess:"ad（〜へ）＋ rect（まっすぐ）→ 問題のほうへまっすぐ向き合うと…？",
   etymologyConclusion:"ad（〜へ）＋ rect（まっすぐ）→ 問題のほうへまっすぐ向き合って手をつける＝取り組む",
   why:"【なぜ】俗ラテン語 *directiare は「まっすぐにする」。相手のほうへまっすぐ向けることから、「宛先を書く（住所）」「まっすぐ語りかける（演説する）」「問題に正面から向き合う（取り組む）」へ広がりました。\n【つながり】direct（まっすぐ向ける）、correct（ゆがみをまっすぐ直す）も同じ rect の家族です。",
   relatedWords:[
     {word:"direct",meaning:"まっすぐな；指示する",breakdown:"di（離れて）＋ rect（まっすぐ）→ まっすぐそちらへ向ける"},
     {word:"correct",meaning:"正しい；訂正する",breakdown:"cor（共に）＋ rect（まっすぐ）→ ゆがみをまっすぐに直す"},
     {word:"rectangle",meaning:"長方形",breakdown:"rect（まっすぐ）＋ angle（角）→ 角がまっすぐに立った四角形"},
     {synonym:true,word:"tackle",meaning:"取り組む",breakdown:"問題に立ち向かうこと。address は正面から向き合って扱うこと"}]},

  {id:1158,word:"approach",partOfSpeech:"名詞",meaning:"取り組み方；接近",
   meanings:["名|取り組み方，やり方","名|接近","他|近づく"],
   pronunciation:"/əˈproʊtʃ/",part:116,
   example:"Her approach to learning English is very practical.",
   exampleJa:"彼女の英語学習への取り組み方は、とても実際的だ。",
   example2:"We quietly watched the slow approach of the storm.",
   exampleJa2:"私たちは、嵐のゆっくりした接近を静かに見守った。",
   etymologyProcess:"ap（〜へ）＋ proch（近い）→ 問題に近づいていくときの近づき方は…？",
   etymologyConclusion:"ap（〜へ）＋ proch（近い）→ 問題に近づいていくときの近づき方＝取り組み方",
   relatedWords:[
     {word:"reproach",meaning:"非難する",breakdown:"re（後ろへ）＋ proch（近い）→ 相手に詰め寄って責める"},
     {synonym:true,word:"method",meaning:"方法",breakdown:"順序立った手順。approach は問題への向き合い方・考え方"},
     {word:"approximate",meaning:"おおよその",breakdown:"ap（〜へ）＋ proxim（最も近い）→ 正確ではないが最も近い"},
     {synonym:true,word:"attitude",meaning:"態度",breakdown:"向き合う姿勢。approach はやり方まで含めた取り組み方"}]},

  {id:1159,word:"resolve",partOfSpeech:"他動詞",meaning:"（問題を）解決する",
   meanings:["他|（問題・対立）を解決する","他|（to do で）決意する"],
   pronunciation:"/rɪˈzɑːlv/",part:116,
   example:"The two sides finally resolved their long bitter argument.",
   exampleJa:"双方はついに、長く激しい議論を解決した。",
   example2:"She resolved to study abroad right after graduation.",
   exampleJa2:"彼女は卒業後すぐに留学しようと決意した。",
   etymologyProcess:"re（すっかり）＋ solve（ほどく）→ もつれた問題をすっかりほどくと…？",
   etymologyConclusion:"re（すっかり）＋ solve（ほどく）→ もつれた問題をすっかりほどいてしまう＝解決する",
   relatedWords:[
     {word:"solve",meaning:"解く，解決する",breakdown:"solve（ほどく）→ もつれをほどいて答えを出す"},
     {word:"solution",meaning:"解決；溶液",breakdown:"solu（ほどく）＋ ion（名詞）→ ほどけて解けた状態"},
     {word:"dissolve",meaning:"溶ける",breakdown:"dis（バラバラに）＋ solve（ほどく）→ ばらばらにほどけて液に混ざる"},
     {word:"absolute",meaning:"絶対的な",breakdown:"ab（離れて）＋ solu（ほどく）→ 何からも解き放たれている"}]},

  {id:1160,word:"settle",partOfSpeech:"他動詞",meaning:"（もめ事を）決着させる",
   meanings:["他|（もめ事）を決着させる","自|（場所に）落ち着く，定住する"],
   pronunciation:"/ˈsetl/",part:116,
   example:"They settled the argument with one quiet honest talk.",
   exampleJa:"彼らは、正直な話し合いひとつでその言い争いを決着させた。",
   example2:"My family settled in this small town twenty years ago.",
   exampleJa2:"私の家族は20年前に、この小さな町に落ち着いた。",
   etymologyProcess:"set（置く）→ 動いていたものを所定の位置に据えると…？",
   etymologyConclusion:"set（置く）→ 動いていたものを所定の位置に据えて落ち着かせる＝決着させる",
   why:"【なぜ】古英語 setl は「すわる席」。そこから setlan（腰を据えさせる）ができ、「住みつく」「落ち着く」、さらに「もめ事に決着をつける」へ広がりました。\n【つながり】sit（すわる）、set（据える）と同じ「すわる・据える」の大きな family にあたります。",
   relatedWords:[
     {word:"set",meaning:"置く，据える",breakdown:"set（置く）→ 物をしかるべきところに据える"},
     {word:"setting",meaning:"環境，周囲のようす",breakdown:"set（置く）＋ ing（名詞）→ 物事が置かれているまわりのようす"},
     {word:"sunset",meaning:"日の入り",breakdown:"sun（太陽）＋ set（置く）→ 太陽が地平線に下りて据わる"},
     {synonym:true,word:"resolve",meaning:"解決する",breakdown:"もつれをほどくこと。settle は争いに決着をつけて落ち着かせる"}]},

  {id:1161,word:"enrich",partOfSpeech:"他動詞",meaning:"豊かにする",
   meanings:["他|豊かにする，中身を充実させる"],
   pronunciation:"/ɪnˈrɪtʃ/",part:117,
   example:"Reading many good books can enrich your daily life.",
   exampleJa:"よい本をたくさん読むことは、日々の生活を豊かにすることがある。",
   example2:"Farmers enrich the soil with natural compost every spring.",
   exampleJa2:"農家は毎春、自然のたい肥で土を豊かにする。",
   etymologyProcess:"en（〜にする）＋ rich（豊かな）→ 中身を加えて豊かな状態にすると…？",
   etymologyConclusion:"en（〜にする）＋ rich（豊かな）→ 中身を加えて、より豊かな状態にする＝豊かにする",
   relatedWords:[
     {word:"rich",meaning:"豊かな，裕福な",breakdown:"rich（豊かな）→ 持っているものがたっぷりある"},
     {word:"richness",meaning:"豊かさ",breakdown:"rich（豊かな）＋ ness（名詞）→ 中身がたっぷりあること"},
     {word:"richly",meaning:"豊かに，たっぷりと",breakdown:"rich（豊かな）＋ ly（副詞）→ たっぷり満たされたようすで"},
     {synonym:true,word:"improve",meaning:"改善する",breakdown:"よくすること。enrich は中身を加えて豊かにすることを言う"}]},

  {id:1162,word:"warn",partOfSpeech:"他動詞",meaning:"警告する",
   meanings:["他|警告する，注意を与える"],
   pronunciation:"/wɔːrn/",part:117,
   example:"The teacher warned us about the slippery wet floor.",
   exampleJa:"先生は、滑りやすいぬれた床について私たちに警告した。",
   example2:"Road signs warn drivers to slow down near schools.",
   exampleJa2:"道路標識は運転手に、学校の近くで速度を落とすよう警告している。",
   etymologyProcess:"ware（見張る）→ 見張っていて危ないと先に知らせると…？",
   etymologyConclusion:"ware（見張る）→ 見張っていて、危ないと先に知らせてやる＝警告する",
   relatedWords:[
     {word:"aware",meaning:"気づいている",breakdown:"ware（見張る）→ 用心して見ていて、それに気づいている"},
     {word:"beware",meaning:"用心する",breakdown:"ware（見張る）→ 気をつけて見張っていろ、という呼びかけ"},
     {word:"ward",meaning:"病棟；守る",breakdown:"ward（見張る）→ 目を配って守っているところ"},
     {word:"guard",meaning:"守る",breakdown:"gard（見張る）→ 目を配って危険から守る"}]},

  {id:1163,word:"force",partOfSpeech:"他動詞",meaning:"強いる，無理にさせる",
   meanings:["他|強いる，無理にさせる","名|力，勢い"],
   pronunciation:"/fɔːrs/",part:117,
   example:"Bad weather forced them to cancel the school trip.",
   exampleJa:"悪天候が、彼らに修学旅行の中止を強いた。",
   example2:"Nobody can force you to change your own opinion.",
   exampleJa2:"誰も、あなたに自分の意見を変えるよう強いることはできない。",
   etymologyProcess:"fort（力）→ 力ずくで相手にやらせてしまうと…？",
   etymologyConclusion:"fort（力）→ 力ずくで、相手にそうせざるを得なくさせる＝強いる",
   relatedWords:[
     {word:"effort",meaning:"努力",breakdown:"ef（外へ）＋ fort（力）→ 力を外へ出しきること"},
     {word:"comfort",meaning:"快適さ；慰める",breakdown:"com（すっかり）＋ fort（力）→ すっかり力づけて安らがせる"},
     {word:"enforce",meaning:"施行する，強制する",breakdown:"en（〜にする）＋ fort（力）→ 力を持たせて守らせる"},
     {synonym:true,word:"compel",meaning:"強制する",breakdown:"やむを得ずさせること。force は力で押し切る感じが強い"}]},

  {id:1164,word:"appeal",partOfSpeech:"自動詞",meaning:"訴える，呼びかける",
   meanings:["自|（to ～）（～に）訴える，呼びかける","自|（to ～）（～の）心に響く"],
   pronunciation:"/əˈpiːl/",part:117,
   example:"The group appealed to the mayor for much more help.",
   exampleJa:"その団体は市長に、もっと多くの助けを求めて訴えた。",
   example2:"Her honest speech appealed to many young listeners.",
   exampleJa2:"彼女の正直なスピーチは、多くの若い聴衆の心に響いた。",
   etymologyProcess:"ap（〜へ）＋ pel（押しやる）→ 相手の心へ押しやるように呼びかけると…？",
   etymologyConclusion:"ap（〜へ）＋ pel（押しやる）→ 相手の心のほうへ押しやるように強く呼びかける＝訴える",
   relatedWords:[
     {word:"expel",meaning:"追い出す",breakdown:"ex（外へ）＋ pel（押しやる）→ 外へ押し出してしまう"},
     {word:"propel",meaning:"推進する",breakdown:"pro（前へ）＋ pel（押しやる）→ 前へぐいぐい押し進める"},
     {word:"compel",meaning:"強制する",breakdown:"com（すっかり）＋ pel（押しやる）→ すっかり押して動かしてしまう"},
     {synonym:true,word:"attract",meaning:"引きつける",breakdown:"引き寄せること。appeal は心に働きかけて訴えかけること"}]},

  {id:1165,word:"applause",partOfSpeech:"名詞",meaning:"拍手（かっさい）",
   meanings:["名|拍手（かっさい）"],
   pronunciation:"/əˈplɔːz/",part:117,
   example:"Loud applause filled the hall after her piano performance.",
   exampleJa:"彼女のピアノの演奏の後、大きな拍手がホールを満たした。",
   example2:"The long speech finally ended with warm loud applause.",
   exampleJa2:"その長いスピーチは、ついに温かく大きな拍手で終わった。",
   etymologyProcess:"ap（〜へ）＋ plaus（拍手する）→ 演じ手へ向けて手を打ち鳴らすと…？",
   etymologyConclusion:"ap（〜へ）＋ plaus（拍手する）→ 演じ手へ向けて手を打ち鳴らすこと＝拍手",
   relatedWords:[
     {word:"applaud",meaning:"拍手する",breakdown:"ap（〜へ）＋ plaud（拍手する）→ その人へ向けて手を打ち鳴らす"},
     {word:"plausible",meaning:"もっともらしい",breakdown:"plaus（拍手する）＋ ible（できる）→ 拍手したくなるほど筋が通って見える"},
     {synonym:true,word:"clap",meaning:"手をたたく",breakdown:"手を打つ動き。applause はその音や行いを指す名詞"},
     {synonym:true,word:"cheer",meaning:"声援",breakdown:"声で応援すること。applause は手をたたいてたたえること"}]},

  {id:1166,word:"leap",partOfSpeech:"自動詞",meaning:"跳ぶ，跳び上がる",
   meanings:["自|跳ぶ，跳び上がる","名|跳躍"],
   pronunciation:"/liːp/",part:117,
   example:"The cat leaps onto the high stone wall every morning.",
   exampleJa:"その猫は毎朝、高い石塀の上に跳び上がる。",
   example2:"He leaped over the wide stream without stopping once.",
   exampleJa2:"彼は一度も止まらずに、広い小川を跳び越えた。",
   etymologyProcess:"leap（勢いよく跳ぶ）→ 足で地を蹴って大きく跳び上がると…？",
   etymologyConclusion:"leap（勢いよく跳ぶ）→ 足で地を蹴って、大きく跳び上がる＝跳ぶ",
   hook:"うるう年 leap year は「1日跳び越える年」。大きく跳ぶのが芯。",
   relatedWords:[
     {synonym:true,word:"jump",meaning:"跳ぶ",breakdown:"跳ぶこと全般。leap はもっと大きく、勢いよく跳ぶこと"},
     {synonym:true,word:"hop",meaning:"ぴょんと跳ぶ",breakdown:"小さく跳ぶこと。leap は大きく遠くまで跳ぶこと"},
     {synonym:true,word:"bounce",meaning:"弾む",breakdown:"ぶつかって跳ね返ること。leap は自分の力で跳び上がること"},
     {synonym:true,word:"spring",meaning:"跳び出す",breakdown:"ばねのように跳ぶこと。leap は大きなひと跳びを表す"}]},

  {id:1167,word:"grab",partOfSpeech:"他動詞",meaning:"（さっと）つかむ",
   meanings:["他|（さっと乱暴に）つかむ，ひったくる"],
   pronunciation:"/ɡræb/",part:117,
   example:"She grabs her bag and runs to the train station.",
   exampleJa:"彼女はかばんをさっとつかんで、駅へ走る。",
   example2:"He grabbed my arm and quickly pulled me back.",
   exampleJa2:"彼は私の腕をつかんで、すばやく引き戻した。",
   etymologyProcess:"grab（ひっつかむ）→ 手を伸ばしてさっと乱暴につかみ取ると…？",
   etymologyConclusion:"grab（ひっつかむ）→ 手を伸ばして、さっと乱暴につかみ取る＝つかむ",
   hook:"かばんを「ガッとつかむ」感じ。素早く乱暴につかむ動きが芯。",
   relatedWords:[
     {synonym:true,word:"seize",meaning:"つかみ取る",breakdown:"ぐっと力強くつかむこと。grab はもっと乱暴で素早い"},
     {synonym:true,word:"catch",meaning:"捕まえる",breakdown:"飛んでくる物を受け止めること。grab は手を出してつかみ取る"},
     {word:"grasp",meaning:"しっかりつかむ",breakdown:"grab（ひっつかむ）→ 手でぎゅっと握りしめて離さない"},
     {synonym:true,word:"hold",meaning:"持つ，つかんでいる",breakdown:"手を離さずにいること。grab はつかむ瞬間の動き"}]},

  {id:1168,word:"seize",partOfSpeech:"他動詞",meaning:"（機会などを）つかみ取る",
   meanings:["他|（機会・物）をつかみ取る","他|押収する，差し押さえる"],
   pronunciation:"/siːz/",part:117,
   example:"You should seize every chance to speak real English.",
   exampleJa:"本物の英語を話すあらゆる機会を、つかみ取るべきだ。",
   example2:"Police seized the stolen bags at the airport yesterday.",
   exampleJa2:"警察は昨日、空港で盗まれたかばんを押収した。",
   etymologyProcess:"seize（さっと取る）→ 機会や物をぐっと力強くつかみ取ると…？",
   etymologyConclusion:"seize（さっと取る）→ 機会や物を、ぐっと力強くつかみ取る＝つかみ取る",
   hook:"語源ははっきりしない。seize the chance（好機をつかむ）で覚える。",
   relatedWords:[
     {synonym:true,word:"grab",meaning:"さっとつかむ",breakdown:"乱暴に素早くつかむこと。seize は力強く確実につかみ取る"},
     {synonym:true,word:"grasp",meaning:"しっかりつかむ",breakdown:"握りしめること。seize は機会や権力をつかむのにも使う"},
     {synonym:true,word:"capture",meaning:"捕らえる",breakdown:"つかまえること。seize は素早くつかみ取る動きを言う"},
     {synonym:true,word:"catch",meaning:"捕まえる",breakdown:"受け止めること。seize は自分から強くつかみに行く"}]},

  {id:1169,word:"cast",partOfSpeech:"他動詞",meaning:"投げる，投げかける",
   meanings:["他|投げる，投げかける","名|配役，キャスト"],
   pronunciation:"/kæst/",part:117,
   example:"The fisherman casts his wide net into the calm sea.",
   exampleJa:"その漁師は、穏やかな海に広い網を投げる。",
   example2:"The tall tower cast a long shadow at sunset.",
   exampleJa2:"その高い塔は、夕暮れに長い影を投げかけた。",
   etymologyProcess:"cast（投げる）→ 腕を振って勢いよく放り投げると…？",
   etymologyConclusion:"cast（投げる）→ 腕を振って、勢いよく遠くへ放り投げる＝投げる",
   relatedWords:[
     {word:"forecast",meaning:"予報",breakdown:"fore（前に）＋ cast（投げる）→ 先へ考えを投げて言い当てる"},
     {word:"broadcast",meaning:"放送する",breakdown:"broad（広い）＋ cast（投げる）→ 広くばらまくように届ける"},
     {word:"outcast",meaning:"のけ者",breakdown:"out（外へ）＋ cast（投げる）→ 仲間の外へ投げ出された人"},
     {synonym:true,word:"throw",meaning:"投げる",breakdown:"ふつうの「投げる」。cast は網や影を投げるなど硬い語"}]},

  {id:1170,word:"stun",partOfSpeech:"他動詞",meaning:"気絶させる；呆然とさせる",
   meanings:["他|気絶させる","他|呆然とさせる"],
   pronunciation:"/stʌn/",part:117,
   example:"A hard blow can stun a person for several seconds.",
   exampleJa:"強い一撃は、人を数秒間気絶させることがある。",
   example2:"The sudden news stunned everyone in the quiet classroom.",
   exampleJa2:"その突然の知らせは、静かな教室のみんなを呆然とさせた。",
   etymologyProcess:"ex（外へ）＋ tonar（雷が鳴る）→ 一瞬、何も分からなくさせてしまうと…？",
   etymologyConclusion:"ex（外へ）＋ tonar（雷が鳴る）→ 雷に打たれたように一瞬何も分からなくさせる＝気絶させる",
   why:"【なぜ】古フランス語 estoner は ex（外へ）＋ tonare（雷が鳴る）で、「雷のような衝撃を与える」こと。そこから「気絶させる」「呆然とさせる」になりました。\n【つながり】astonish（ひどく驚かせる）も同じ語から。tone（音の調子）、thunder（雷）も遠い親戚です。",
   relatedWords:[
     {word:"astonish",meaning:"ひどく驚かせる",breakdown:"ex（外へ）＋ tonar（雷が鳴る）→ 雷に打たれたように強く驚かせる"},
     {synonym:true,word:"shock",meaning:"衝撃を与える",breakdown:"強い衝撃を与えること。stun は一瞬動けなくさせる"},
     {synonym:true,word:"amaze",meaning:"びっくりさせる",breakdown:"頭がぽかんとなる驚き。stun はもっと打ちのめされる感じ"},
     {synonym:true,word:"daze",meaning:"ぼうっとさせる",breakdown:"頭をぼんやりさせること。stun は一撃で動けなくさせる"}]},

  {id:1171,word:"illuminate",partOfSpeech:"他動詞",meaning:"照らす，明るくする",
   meanings:["他|照らす，明るくする","他|（問題）を解き明かす"],
   pronunciation:"/ɪˈluːmɪneɪt/",part:118,
   example:"Candles illuminate the small room every winter evening.",
   exampleJa:"ろうそくが、毎冬の夕方その小さな部屋を照らす。",
   example2:"The stage was illuminated by hundreds of tiny lights.",
   exampleJa2:"舞台は、何百もの小さな明かりで照らされた。",
   etymologyProcess:"in（中へ）＋ lumin（光）→ 暗いところに光を入れて明るくすると…？",
   etymologyConclusion:"in（中へ）＋ lumin（光）→ 暗いところに光を入れて隅々まで明るくする＝照らす",
   relatedWords:[
     {word:"luminous",meaning:"光を放つ",breakdown:"lumin（光）＋ ous（形容詞）→ 光に満ちて輝いている"},
     {word:"illumination",meaning:"照明，イルミネーション",breakdown:"in（中へ）＋ lumin（光）＋ ation（名詞）→ 光を当てて明るくすること"},
     {synonym:true,word:"light",meaning:"照らす；光",breakdown:"明かりをつけること。illuminate は全体を照らし出す硬い語"},
     {synonym:true,word:"brighten",meaning:"明るくする",breakdown:"明るさを増すこと。illuminate は光を当てて照らすこと"}]},

  {id:1172,word:"uncover",partOfSpeech:"他動詞",meaning:"暴く，掘り起こす",
   meanings:["他|（隠れた事実）を暴く","他|掘り起こす，覆いを取る"],
   pronunciation:"/ʌnˈkʌvər/",part:118,
   example:"Reporters uncover the truth behind the big political scandal.",
   exampleJa:"記者たちは、その大きな政治の不祥事の裏にある真実を暴く。",
   example2:"Workers uncovered old coins under the school ground.",
   exampleJa2:"作業員たちが、校庭の下から古い硬貨を掘り起こした。",
   etymologyProcess:"un（取り去る）＋ cover（覆う）→ かぶせてあった覆いを取り去ると…？",
   etymologyConclusion:"un（取り去る）＋ cover（覆う）→ かぶせてあった覆いを取り去って見せる＝暴く",
   relatedWords:[
     {word:"cover",meaning:"覆う",breakdown:"cover（覆う）→ 上からかぶせて見えなくする"},
     {word:"discover",meaning:"発見する",breakdown:"dis（否定）＋ cover（覆う）→ 覆いを外して見つけ出す"},
     {synonym:true,word:"expose",meaning:"さらけ出す",breakdown:"外にさらすこと。uncover は覆いを取って隠れた事実を見せる"},
     {synonym:true,word:"reveal",meaning:"明らかにする",breakdown:"覆いを取って見せること。uncover は隠れた事実を掘り起こす"}]},

  {id:1173,word:"mend",partOfSpeech:"他動詞",meaning:"修繕する，繕う",
   meanings:["他|修繕する，繕う"],
   pronunciation:"/mend/",part:118,
   example:"My grandmother mends old socks every Sunday evening.",
   exampleJa:"祖母は毎週日曜の夕方、古い靴下を修繕する。",
   example2:"The carpenter mended the broken wooden gate very quickly.",
   exampleJa2:"大工は、その壊れた木の門をとてもすばやく修繕した。",
   etymologyProcess:"menda（欠点）→ 欠点や傷んだところを取り除いて直すと…？",
   etymologyConclusion:"menda（欠点）→ 欠点や傷んだところを取り除いて元どおりにする＝修繕する",
   hook:"amend（改める）の頭が落ちた形。悪いところを取り除くのが芯。",
   relatedWords:[
     {word:"amend",meaning:"改正する，改める",breakdown:"ex（外へ）＋ menda（欠点）→ 欠点を外へ取り除いて直す"},
     {synonym:true,word:"repair",meaning:"修理する",breakdown:"壊れた所を直すこと。mend は布や小物を繕うのによく使う"},
     {synonym:true,word:"fix",meaning:"直す",breakdown:"くだけた語。mend は縫って繕うような直し方を指す"},
     {synonym:true,word:"sew",meaning:"縫う",breakdown:"糸で縫うこと。mend は破れを縫って元どおりにすること"}]},

  {id:1174,word:"react",partOfSpeech:"自動詞",meaning:"反応する",
   meanings:["自|（to ～）（～に）反応する","自|（with ～）（～と）化学反応する"],
   pronunciation:"/riˈækt/",part:118,
   example:"How did your parents react to the good news?",
   exampleJa:"ご両親は、そのよい知らせにどう反応しましたか。",
   example2:"Some metals react strongly with water and air.",
   exampleJa2:"ある種の金属は、水や空気と強く反応する。",
   etymologyProcess:"re（後ろへ）＋ act（追い立てる）→ 受けた働きかけに動き返すと…？",
   etymologyConclusion:"re（後ろへ）＋ act（追い立てる）→ 受けた働きかけに対して動き返す＝反応する",
   relatedWords:[
     {word:"act",meaning:"行動する；演じる",breakdown:"act（追い立てる）→ 自分から動いて事をなす"},
     {word:"active",meaning:"活発な",breakdown:"act（追い立てる）＋ ive（形容詞）→ よく動いて事を進める"},
     {word:"actor",meaning:"俳優",breakdown:"act（追い立てる）＋ or（人）→ 舞台で動いて演じる人"},
     {word:"reaction",meaning:"反応",breakdown:"re（後ろへ）＋ act（追い立てる）＋ ion（名詞）→ 受けて動き返すこと"}]},

  {id:1175,word:"endure",partOfSpeech:"他動詞",meaning:"耐える，持ちこたえる",
   meanings:["他|耐える，持ちこたえる","自|長く続く"],
   pronunciation:"/ɪnˈdʊr/",part:118,
   example:"They endured the cold night without a warm fire.",
   exampleJa:"彼らは、暖かい火なしでその寒い夜に耐えた。",
   example2:"Few people can endure such hard daily training.",
   exampleJa2:"そんな厳しい毎日の訓練に耐えられる人は、ほとんどいない。",
   etymologyProcess:"en（〜にする）＋ dur（固い）→ 心を固くしてつらさに持ちこたえると…？",
   etymologyConclusion:"en（〜にする）＋ dur（固い）→ 心を固くして、つらさに持ちこたえる＝耐える",
   relatedWords:[
     {word:"durable",meaning:"長持ちする",breakdown:"dur（固い）＋ able（できる）→ 固くて長く持ちこたえられる"},
     {word:"during",meaning:"～の間",breakdown:"dur（固い）＋ ing（〜している）→ その状態が続いている間"},
     {word:"duration",meaning:"継続期間",breakdown:"dur（固い）＋ ation（名詞）→ 続いている長さ"},
     {synonym:true,word:"bear",meaning:"耐える",breakdown:"重さを支えること。endure は長くつらさに持ちこたえること"}]},

  {id:1176,word:"bind",partOfSpeech:"他動詞",meaning:"縛る，束ねる",
   meanings:["他|縛る，束ねる","他|（人を）結びつける"],
   pronunciation:"/baɪnd/",part:118,
   example:"Please bind these old newspapers with strong thick string.",
   exampleJa:"これらの古新聞を、丈夫で太いひもで縛ってください。",
   example2:"A shared goal binds the whole team together tightly.",
   exampleJa2:"共通の目標が、チーム全体を固く結びつけている。",
   etymologyProcess:"bind（縛る）→ ひもや約束でしっかり結びつけて離さないと…？",
   etymologyConclusion:"bind（縛る）→ ひもや約束でしっかり結びつけて離さない＝縛る",
   relatedWords:[
     {word:"bond",meaning:"きずな；債券",breakdown:"bind（縛る）→ 人と人を結びつけているもの"},
     {word:"bundle",meaning:"束",breakdown:"bind（縛る）＋ le（もの）→ 縛ってひとまとめにしたもの"},
     {word:"band",meaning:"帯；一団",breakdown:"bind（縛る）→ 縛るための帯。そこから結ばれた一団"},
     {synonym:true,word:"tie",meaning:"結ぶ",breakdown:"ひもで結ぶこと。bind はきつく縛って離さない感じが強い"}]},

  {id:1177,word:"encounter",partOfSpeech:"他動詞",meaning:"偶然出会う，出くわす",
   meanings:["他|偶然出会う，出くわす","名|遭遇"],
   pronunciation:"/ɪnˈkaʊntər/",part:118,
   example:"I encountered my old teacher at the busy airport.",
   exampleJa:"私は、にぎやかな空港で昔の先生に偶然出会った。",
   example2:"Climbers often encounter sudden changes in the mountain weather.",
   exampleJa2:"登山者はしばしば、山の天気の急な変化に出くわす。",
   etymologyProcess:"en（中に）＋ counter（向かい合う）→ 思いがけず正面から向かい合うと…？",
   etymologyConclusion:"en（中に）＋ counter（向かい合う）→ 思いがけず正面から向かい合う＝偶然出会う",
   relatedWords:[
     {word:"counter",meaning:"逆らう；カウンター",breakdown:"counter（向かい合う）→ 向かい合って受け止める"},
     {word:"contrary",meaning:"反対の",breakdown:"contra（逆に）＋ ary（形容詞）→ 向かい合って逆を向いている"},
     {word:"contrast",meaning:"対比，対照",breakdown:"contra（逆に）＋ st（立つ）→ 逆を向いて並び立つこと"},
     {synonym:true,word:"meet",meaning:"会う",breakdown:"会うこと全般。encounter は思いがけず出くわすことを言う"}]},

  {id:1178,word:"trace",partOfSpeech:"他動詞",meaning:"（跡を）たどって捜し出す",
   meanings:["他|（跡を）たどって捜し出す","名|跡，形跡"],
   pronunciation:"/treɪs/",part:118,
   example:"Police traced the missing girl through her mobile phone.",
   exampleJa:"警察は、携帯電話を通して行方不明の少女をたどって捜し出した。",
   example2:"Detectives can trace a car by its number plate.",
   exampleJa2:"刑事は、番号標によって車をたどって捜し出すことができる。",
   etymologyProcess:"tract（引く）→ 残された跡を引くようにたどっていくと…？",
   etymologyConclusion:"tract（引く）→ 残された跡を引くようにたどって見つけ出す＝たどって捜し出す",
   relatedWords:[
     {word:"attract",meaning:"引きつける",breakdown:"ad（〜へ）＋ tract（引く）→ 自分のほうへぐっと引き寄せる"},
     {word:"extract",meaning:"取り出す",breakdown:"ex（外へ）＋ tract（引く）→ 外へ引っぱり出す"},
     {word:"contract",meaning:"契約",breakdown:"con（共に）＋ tract（引く）→ 互いを引き寄せて結びつけた約束"},
     {word:"tractor",meaning:"トラクター",breakdown:"tract（引く）＋ or（もの）→ 重い機械を引っぱる車"}]},

  {id:1179,word:"undergo",partOfSpeech:"他動詞",meaning:"（つらいこと）を経験する",
   meanings:["他|（変化・苦難）を経験する","他|（手術・検査）を受ける"],
   pronunciation:"/ˌʌndərˈɡoʊ/",part:118,
   example:"The old building will undergo major repairs next year.",
   exampleJa:"その古い建物は来年、大きな修理を経験することになる。",
   example2:"She had to undergo a long and difficult operation.",
   exampleJa2:"彼女は、長く難しい手術を受けなければならなかった。",
   etymologyProcess:"under（下に）＋ go（行く）→ つらいことの下をくぐり抜けていくと…？",
   etymologyConclusion:"under（下に）＋ go（行く）→ つらいことの下をくぐり抜けていく＝経験する",
   relatedWords:[
     {word:"understand",meaning:"理解する",breakdown:"under（下に）＋ sta（立つ）→ 物事の下に立って支えるように分かる"},
     {word:"underline",meaning:"下線を引く；強調する",breakdown:"under（下に）＋ line（線）→ 下に線を引いて目立たせる"},
     {word:"undertake",meaning:"引き受ける",breakdown:"under（下に）＋ take（取る）→ 下に入って重さを引き受ける"},
     {synonym:true,word:"experience",meaning:"経験する",breakdown:"身をもって知ること。undergo はつらいことを受けて通り抜ける"}]},

  {id:1180,word:"seal",partOfSpeech:"他動詞",meaning:"密封する",
   meanings:["他|密封する，封をする","名|印章；シール"],
   pronunciation:"/siːl/",part:118,
   example:"Please seal the envelope carefully before you send it.",
   exampleJa:"送る前に、その封筒を注意深く密封してください。",
   example2:"The glass jar was sealed to keep the food fresh.",
   exampleJa2:"そのガラス瓶は、食べ物を新鮮に保つために密封された。",
   etymologyProcess:"sign（しるし）→ しるしの印を押して開けられなくすると…？",
   etymologyConclusion:"sign（しるし）→ しるしの印を押して、開けられないように閉じる＝密封する",
   relatedWords:[
     {word:"sign",meaning:"しるし；署名する",breakdown:"sign（しるし）→ 見て分かるように付けた印"},
     {word:"signal",meaning:"合図，信号",breakdown:"sign（しるし）＋ al（名詞）→ 知らせるためのしるし"},
     {word:"design",meaning:"設計する；デザイン",breakdown:"de（下へ）＋ sign（しるし）→ 紙に印をつけて形を決める"},
     {word:"signature",meaning:"署名",breakdown:"sign（しるし）＋ ature（名詞）→ 自分のしるしとして書く名前"}]},

  {id:1181,word:"incorporate",partOfSpeech:"他動詞",meaning:"取り入れる",
   meanings:["他|取り入れる，組み込む"],
   pronunciation:"/ɪnˈkɔːrpəreɪt/",part:119,
   example:"The new plan incorporates ideas from every single class.",
   exampleJa:"新しい計画は、すべてのクラスからの考えを取り入れている。",
   example2:"They incorporated local wood into the modern school building.",
   exampleJa2:"彼らは地元の木材を、現代的な校舎に取り入れた。",
   etymologyProcess:"in（中へ）＋ corpor（体）→ 別のものを自分の体の中に取り込むと…？",
   etymologyConclusion:"in（中へ）＋ corpor（体）→ 別のものを自分の体の中に取り込んで一つにする＝取り入れる",
   relatedWords:[
     {word:"corporation",meaning:"法人，大企業",breakdown:"corpor（体）＋ ation（名詞）→ 一つの体のようにまとまって動く組織"},
     {word:"corps",meaning:"部隊，団",breakdown:"corpor（体）→ ひとかたまりとして動く人の集まり"},
     {word:"corpse",meaning:"死体",breakdown:"corpor（体）→ 命のなくなった体そのもの"},
     {synonym:true,word:"include",meaning:"含む",breakdown:"中に入れること。incorporate は溶け込ませて一部にすること"}]},

  {id:1182,word:"emerge",partOfSpeech:"自動詞",meaning:"現れる，姿を見せる",
   meanings:["自|現れる，姿を見せる","自|（事実が）明るみに出る"],
   pronunciation:"/ɪˈmɜːrdʒ/",part:119,
   example:"The sun emerges slowly from behind the dark clouds.",
   exampleJa:"太陽が、暗い雲の後ろからゆっくりと現れる。",
   example2:"New facts emerged during the long police investigation.",
   exampleJa2:"長い警察の捜査の間に、新しい事実が明るみに出た。",
   etymologyProcess:"e（外へ）＋ merg（沈める）→ 沈んでいたものが水面の外へ出ると…？",
   etymologyConclusion:"e（外へ）＋ merg（沈める）→ 沈んでいたものが水面の外へ出てくる＝現れる",
   relatedWords:[
     {word:"merge",meaning:"合併する，溶け合う",breakdown:"merg（沈める）→ 沈めるように混ぜて一つにする"},
     {word:"submerge",meaning:"水中に沈める",breakdown:"sub（下で）＋ merg（沈める）→ 水面の下へ沈める"},
     {word:"emergency",meaning:"緊急事態",breakdown:"e（外へ）＋ merg（沈める）＋ cy（名詞）→ 突然表に出てきた出来事"},
     {synonym:true,word:"appear",meaning:"現れる",breakdown:"見えるようになること。emerge は隠れていた所から出てくる"}]},

  {id:1183,word:"unfold",partOfSpeech:"他動詞",meaning:"広げる；展開する",
   meanings:["他|（折ったもの）を広げる","自|（物語などが）展開する"],
   pronunciation:"/ʌnˈfoʊld/",part:119,
   example:"Please unfold the large map on the wide table.",
   exampleJa:"その広いテーブルの上で、大きな地図を広げてください。",
   example2:"The story unfolds slowly over the first three chapters.",
   exampleJa2:"その物語は、最初の3章をかけてゆっくり展開する。",
   etymologyProcess:"un（取り去る）＋ fold（重ねる）→ 折り重なっていたものを開くと…？",
   etymologyConclusion:"un（取り去る）＋ fold（重ねる）→ 折り重なっていたものを開いて平らにする＝広げる",
   relatedWords:[
     {word:"fold",meaning:"折りたたむ",breakdown:"fold（重ねる）→ 折って重ね合わせる"},
     {word:"twofold",meaning:"2倍の，2重の",breakdown:"two（2）＋ fold（重ねる）→ 2つ重ねた分の"},
     {word:"manifold",meaning:"多様な",breakdown:"mani（多い）＋ fold（重ねる）→ 幾重にも重なっていて種類が多い"},
     {synonym:true,word:"develop",meaning:"発達する；展開する",breakdown:"包みを開いて伸ばすこと。unfold は折り目を開いて広げること"}]},

  {id:1184,word:"derive",partOfSpeech:"自動詞",meaning:"由来する",
   meanings:["自|（from ～）（～に）由来する","他|（from ～から）引き出す"],
   pronunciation:"/dɪˈraɪv/",part:119,
   example:"Many English words derive from old Latin word roots.",
   exampleJa:"多くの英単語は、古いラテン語の語根に由来する。",
   example2:"Her real strength derives from years of quiet practice.",
   exampleJa2:"彼女の本当の強さは、長年の地道な練習に由来する。",
   etymologyProcess:"de（離して）＋ riv（川）→ 大きな流れから水を引くように出てくると…？",
   etymologyConclusion:"de（離して）＋ riv（川）→ 大きな川から水を引くように、もとから流れ出る＝由来する",
   why:"【なぜ】ラテン語 derivare は「川（rivus）から水を引く」こと。用水路を引くように、もとの流れから枝分かれして出てくる様子から、「〜に由来する」になりました。\n【つながり】rival（同じ川の水を使い合う者どうし＝競争相手）も同じ riv の家族です。",
   relatedWords:[
     {word:"derivative",meaning:"派生物；派生した",breakdown:"de（離して）＋ riv（川）＋ ive（形容詞）→ もとから枝分かれして出た"},
     {word:"rival",meaning:"競争相手",breakdown:"riv（川）→ 同じ川の水を使い合って争う者どうし"},
     {word:"derivation",meaning:"由来，派生",breakdown:"de（離して）＋ riv（川）＋ ation（名詞）→ もとから枝分かれして出ること"},
     {synonym:true,word:"originate",meaning:"始まる，起こる",breakdown:"そこから起こること。derive はもとから流れ出て来ることを言う"}]},

  {id:1185,word:"generate",partOfSpeech:"他動詞",meaning:"生み出す，発生させる",
   meanings:["他|生み出す，発生させる"],
   pronunciation:"/ˈdʒenəreɪt/",part:119,
   example:"Solar panels generate electricity even on cloudy days.",
   exampleJa:"太陽光パネルは、曇りの日でも電気を生み出す。",
   example2:"The new movie generated a lot of excitement online.",
   exampleJa2:"その新しい映画は、ネット上で多くの興奮を生み出した。",
   etymologyProcess:"gener（生み出す）＋ ate（動詞）→ 何もないところから新しく作り出すと…？",
   etymologyConclusion:"gener（生み出す）＋ ate（動詞）→ 何もないところから新しく作り出す＝生み出す",
   relatedWords:[
     {word:"gene",meaning:"遺伝子",breakdown:"gen（生み出す）→ 体の特徴を生み出すもとになるもの"},
     {word:"generation",meaning:"世代",breakdown:"gener（生み出す）＋ ation（名詞）→ 生み出されて続く一つの代"},
     {word:"genetic",meaning:"遺伝の",breakdown:"gen（生み出す）＋ etic（〜の）→ 生まれつき受け継ぐことに関わる"},
     {word:"generous",meaning:"気前のよい",breakdown:"gener（生み出す）＋ ous（形容詞）→ よい生まれの者らしく惜しみない"}]},

  {id:1186,word:"possess",partOfSpeech:"他動詞",meaning:"所有している",
   meanings:["他|所有している，持っている"],
   pronunciation:"/pəˈzes/",part:119,
   example:"The museum possesses several very rare old paintings.",
   exampleJa:"その博物館は、とても珍しい古い絵を何枚か所有している。",
   example2:"The young team was said to possess great potential.",
   exampleJa2:"その若いチームは、大きな可能性を持っていると言われていた。",
   etymologyProcess:"poss（できる）＋ sess（座る）→ 自分の力の及ぶ場所にどっしり座ると…？",
   etymologyConclusion:"poss（できる）＋ sess（座る）→ 自分の力の及ぶ場所にどっしり座っている＝所有している",
   relatedWords:[
     {word:"possession",meaning:"所有；所有物",breakdown:"poss（できる）＋ sess（座る）＋ ion（名詞）→ 自分のものとして持つこと"},
     {word:"possible",meaning:"可能な",breakdown:"poss（できる）＋ ible（できる）→ 実現する見込みがある"},
     {word:"resident",meaning:"住人",breakdown:"re（後ろへ）＋ sid（座る）→ その土地に腰を落ち着けている人"},
     {synonym:true,word:"own",meaning:"所有する",breakdown:"自分のものとして持つこと。possess は硬く、書き言葉で使う"}]},

  {id:1187,word:"retain",partOfSpeech:"他動詞",meaning:"保持する，保ち続ける",
   meanings:["他|保持する，保ち続ける"],
   pronunciation:"/rɪˈteɪn/",part:119,
   example:"This thick wall retains heat during the cold winter.",
   exampleJa:"この厚い壁は、寒い冬の間ずっと熱を保持する。",
   example2:"He retained his calm during the whole difficult meeting.",
   exampleJa2:"彼は難しい会議の間ずっと、落ち着きを保ち続けた。",
   etymologyProcess:"re（後ろへ）＋ tain（保つ）→ 手放さずに引き寄せて持ち続けると…？",
   etymologyConclusion:"re（後ろへ）＋ tain（保つ）→ 手放さずに後ろへ引き寄せて持ち続ける＝保持する",
   relatedWords:[
     {word:"contain",meaning:"含む",breakdown:"con（すっかり）＋ tain（保つ）→ 中にすっかり保っている"},
     {word:"obtain",meaning:"手に入れる",breakdown:"ob（〜に向かって）＋ tain（保つ）→ 手を伸ばして自分の手に保つ"},
     {word:"entertain",meaning:"楽しませる",breakdown:"inter（間の）＋ tain（保つ）→ 相手をそばに引き止めておく"},
     {synonym:true,word:"keep",meaning:"保つ",breakdown:"持ち続けること。retain は手放さず保ち続ける硬い語"}]},

  {id:1188,word:"secure",partOfSpeech:"他動詞",meaning:"確保する",
   meanings:["他|確保する，手に入れる","形|安全な，しっかりした"],
   pronunciation:"/sɪˈkjʊr/",part:119,
   example:"The team secured a place in the final round.",
   exampleJa:"そのチームは、決勝戦への出場を確保した。",
   example2:"Please keep your password secure at all times.",
   exampleJa2:"パスワードは、常に安全に保ってください。",
   etymologyProcess:"se（離れて）＋ cur（気にかける）→ 心配から離れた状態にして押さえると…？",
   etymologyConclusion:"se（離れて）＋ cur（気にかける）→ 心配から離れた状態にしてしっかり押さえる＝確保する",
   relatedWords:[
     {word:"security",meaning:"安全，警備",breakdown:"se（離れて）＋ cur（気にかける）＋ ity（名詞）→ 心配から離れている状態"},
     {word:"cure",meaning:"治療する",breakdown:"cur（気にかける）→ 気にかけて手当てし、よくする"},
     {word:"curious",meaning:"好奇心の強い",breakdown:"cur（気にかける）＋ ous（形容詞）→ あれこれ気にかけたがる"},
     {word:"accurate",meaning:"正確な",breakdown:"ac（〜へ）＋ cur（気にかける）→ 細かいところまで気を配った"}]},

  {id:1189,word:"capture",partOfSpeech:"他動詞",meaning:"捕らえる",
   meanings:["他|捕らえる，捕獲する","他|（映像・魅力）をとらえる"],
   pronunciation:"/ˈkæptʃər/",part:119,
   example:"The hunters captured a wild deer near the river.",
   exampleJa:"猟師たちは、川の近くで野生のシカを捕らえた。",
   example2:"This photo captures the beauty of the old town.",
   exampleJa2:"この写真は、その古い町の美しさをとらえている。",
   etymologyProcess:"cap（つかむ）＋ ure（名詞）→ 逃げるものをつかまえて自分のものにすると…？",
   etymologyConclusion:"cap（つかむ）＋ ure（名詞）→ 逃げるものをつかまえて手中に収めること＝捕らえる",
   relatedWords:[
     {word:"capacity",meaning:"収容力，容量",breakdown:"cap（つかむ）＋ ity（名詞）→ どれだけ抱えこめるかという大きさ"},
     {word:"capable",meaning:"能力がある",breakdown:"cap（つかむ）＋ able（できる）→ しっかりつかんでやり切れる"},
     {word:"captive",meaning:"捕虜；とらわれた",breakdown:"cap（つかむ）＋ ive（形容詞）→ つかまえられたままでいる"},
     {synonym:true,word:"catch",meaning:"捕まえる",breakdown:"つかまえること。capture は逃げるものを確保する硬い語"}]},

  {id:1190,word:"monitor",partOfSpeech:"他動詞",meaning:"監視する",
   meanings:["他|監視する，見守る","名|モニター，監視装置"],
   pronunciation:"/ˈmɑːnɪtər/",part:119,
   example:"Doctors monitor the patient's heart every single hour.",
   exampleJa:"医師は1時間ごとに、その患者の心臓を監視する。",
   example2:"Teachers monitored the students during the long final exam.",
   exampleJa2:"先生たちは、長い期末試験の間ずっと生徒を監視した。",
   etymologyProcess:"mon（思い出させる）＋ or（もの）→ 注意を促しながら見張り続けると…？",
   etymologyConclusion:"mon（思い出させる）＋ or（もの）→ 危ないと注意を促しながら見張り続ける＝監視する",
   why:"【なぜ】ラテン語 monere は「思い出させる・警告する」。monitor はもともと「注意を与える人」で、そこから「異常がないか見張る人・装置」になりました。\n【つながり】monument（後の世に思い出させるもの）、summon（呼び出す）も同じ家族です。",
   relatedWords:[
     {word:"monument",meaning:"記念碑",breakdown:"mon（思い出させる）＋ ment（名詞）→ 後の世に思い出させるために建てたもの"},
     {word:"summon",meaning:"呼び出す",breakdown:"sub（下で）＋ mon（思い出させる）→ 下から呼び立てて来させる"},
     {word:"monster",meaning:"怪物",breakdown:"mon（思い出させる）→ 神の警告を示すものと考えられた生き物"},
     {synonym:true,word:"watch",meaning:"見守る",breakdown:"じっと見ること。monitor は装置や記録を使って見張り続けること"}]},

  {id:1191,word:"investigate",partOfSpeech:"他動詞",meaning:"調査する",
   meanings:["他|（事件・原因）を調査する"],
   pronunciation:"/ɪnˈvestɪɡeɪt/",part:120,
   example:"The police are investigating the cause of the fire.",
   exampleJa:"警察は、その火事の原因を調査している。",
   example2:"Scientists investigated the strange lights in the night sky.",
   exampleJa2:"科学者たちは、夜空の奇妙な光を調査した。",
   etymologyProcess:"in（中へ）＋ vestig（足跡）→ 残された足跡を中まで追って調べると…？",
   etymologyConclusion:"in（中へ）＋ vestig（足跡）→ 残された足跡を奥まで追って調べる＝調査する",
   relatedWords:[
     {word:"investigation",meaning:"調査",breakdown:"in（中へ）＋ vestig（足跡）＋ ation（名詞）→ 足跡を追って調べること"},
     {word:"vestige",meaning:"痕跡，名残",breakdown:"vestig（足跡）→ 消えかけて残っている跡"},
     {synonym:true,word:"examine",meaning:"調べる",breakdown:"よく調べること。investigate は手がかりを追って調べ上げること"},
     {synonym:true,word:"research",meaning:"研究する",breakdown:"くり返し探ること。investigate は事件や原因を調べ上げること"}]},

  {id:1192,word:"detect",partOfSpeech:"他動詞",meaning:"探知する，見つけ出す",
   meanings:["他|探知する，見つけ出す"],
   pronunciation:"/dɪˈtekt/",part:120,
   example:"This machine can detect very small amounts of gas.",
   exampleJa:"この機械は、ごく少量のガスを探知することができる。",
   example2:"Doctors detected the illness at a very early stage.",
   exampleJa2:"医師たちは、ごく早い段階でその病気を見つけ出した。",
   etymologyProcess:"de（離して）＋ tect（覆う）→ かぶせてある覆いを外して見つけると…？",
   etymologyConclusion:"de（離して）＋ tect（覆う）→ かぶせてある覆いを外して見つけ出す＝探知する",
   relatedWords:[
     {word:"detective",meaning:"探偵，刑事",breakdown:"de（離して）＋ tect（覆う）→ 覆いを外して真相を見つけ出す人"},
     {word:"protect",meaning:"守る",breakdown:"pro（前へ）＋ tect（覆う）→ 前に覆いをかけて守る"},
     {word:"detector",meaning:"探知機",breakdown:"de（離して）＋ tect（覆う）＋ or（もの）→ 見つけ出すための装置"},
     {synonym:true,word:"discover",meaning:"発見する",breakdown:"見つけ出すこと。detect は機械や注意力でそれと気づくこと"}]},

  {id:1193,word:"inquiry",partOfSpeech:"名詞",meaning:"問い合わせ；調査",
   meanings:["名|問い合わせ","名|（公的な）調査"],
   pronunciation:"/ɪnˈkwaɪəri/",part:120,
   example:"Please send your inquiry to this email address.",
   exampleJa:"問い合わせは、このメールアドレスへ送ってください。",
   example2:"The government opened an inquiry into the train accident.",
   exampleJa2:"政府は、その列車事故についての調査を始めた。",
   etymologyProcess:"in（中へ）＋ quire（求める）→ 中へ分け入って答えを求めると…？",
   etymologyConclusion:"in（中へ）＋ quire（求める）→ 中へ分け入って答えを求めること＝問い合わせ",
   relatedWords:[
     {word:"question",meaning:"質問",breakdown:"quest（求める）＋ ion（名詞）→ 答えを求めること"},
     {word:"require",meaning:"必要とする",breakdown:"re（強く）＋ quire（求める）→ 強く求めて欠かせないとする"},
     {word:"request",meaning:"依頼する",breakdown:"re（何度も）＋ quest（求める）→ くり返し求める"},
     {word:"questionnaire",meaning:"アンケート",breakdown:"quest（求める）＋ ion（名詞）→ 答えを求める問いを並べた紙"}]},

  {id:1194,word:"specialize",partOfSpeech:"自動詞",meaning:"専攻する，専門にする",
   meanings:["自|（in ～）（～を）専攻する，専門にする"],
   pronunciation:"/ˈspeʃəlaɪz/",part:120,
   example:"She wants to specialize in modern Japanese history.",
   exampleJa:"彼女は、近代の日本史を専攻したいと思っている。",
   example2:"This small shop specializes in handmade leather bags.",
   exampleJa2:"この小さな店は、手作りの革かばんを専門にしている。",
   etymologyProcess:"speci（種類）＋ ize（動詞）→ ある一つの種類にしぼって取り組むと…？",
   etymologyConclusion:"speci（種類）＋ ize（動詞）→ ある一つの種類にしぼって深く取り組む＝専攻する",
   relatedWords:[
     {word:"special",meaning:"特別な",breakdown:"speci（種類）＋ al（形容詞）→ 他とは別の種類に属している"},
     {word:"species",meaning:"（生物の）種",breakdown:"speci（種類）→ 生き物を分けたひとつの種類"},
     {word:"specific",meaning:"具体的な，特定の",breakdown:"speci（種類）＋ fic（作る）→ 種類をはっきり区切った"},
     {word:"especially",meaning:"特に",breakdown:"ex（外へ）＋ speci（種類）＋ ly（副詞）→ 他の種類から取り出して"}]},

  {id:1195,word:"semester",partOfSpeech:"名詞",meaning:"学期（半年）",
   meanings:["名|学期（1年を2つに分けたもの）"],
   pronunciation:"/sɪˈmestər/",part:120,
   example:"The new semester starts right after the spring holidays.",
   exampleJa:"新しい学期は、春休みの直後に始まる。",
   example2:"He took five different classes during the first semester.",
   exampleJa2:"彼は最初の学期に、5つの違う授業を取った。",
   etymologyProcess:"sem（6）＋ mestr（月）→ 6か月をひと区切りにした学びの期間は…？",
   etymologyConclusion:"sem（6）＋ mestr（月）→ 6か月をひと区切りとする学びの期間＝学期",
   why:"【なぜ】ラテン語 semestris は sex（6）＋ mensis（月）で「6か月の」。大学の1年をちょうど半分に分けた期間を指し、そこから「学期」になりました。\n【つながり】mensis は month（月）と同じ家族。trimester（3か月ごとの期間）も同じ作り方の語です。",
   relatedWords:[
     {word:"trimester",meaning:"3か月の期間",breakdown:"tri（3）＋ mestr（月）→ 3か月をひと区切りとした期間"},
     {synonym:true,word:"term",meaning:"学期",breakdown:"英国などで言う学期。semester は1年を2つに分けた学期"},
     {synonym:true,word:"month",meaning:"月",breakdown:"mensis と同じ家族の語。semester はその6つ分の長さ"},
     {synonym:true,word:"quarter",meaning:"4半期",breakdown:"1年を4つに分けた期間。semester は2つに分けた期間"}]},

  {id:1196,word:"biology",partOfSpeech:"名詞",meaning:"生物学",
   meanings:["名|生物学"],
   pronunciation:"/baɪˈɑːlədʒi/",part:120,
   example:"She studies biology at a large university in Kyoto.",
   exampleJa:"彼女は、京都の大きな大学で生物学を学んでいる。",
   example2:"Our biology class visited the deep forest last Friday.",
   exampleJa2:"私たちの生物学の授業は、先週の金曜に深い森を訪れた。",
   etymologyProcess:"bio（生命）＋ log（学問）→ 生き物のしくみを調べる学問は…？",
   etymologyConclusion:"bio（生命）＋ log（学問）→ 生き物のしくみとはたらきを調べる学問＝生物学",
   relatedWords:[
     {word:"biography",meaning:"伝記",breakdown:"bio（生命）＋ graph（書く）→ その人が生きた道のりを書き記したもの"},
     {word:"ecology",meaning:"生態学",breakdown:"eco（家）＋ log（学問）→ 生き物とすみかの関わりを調べる学問"},
     {word:"dialogue",meaning:"会話",breakdown:"dia（間で）＋ log（言葉）→ 二人の間で交わされる言葉"},
     {word:"logic",meaning:"論理",breakdown:"log（言葉）＋ ic（名詞）→ 言葉の筋道の立て方"}]},

  {id:1197,word:"ecology",partOfSpeech:"名詞",meaning:"生態学；生態",
   meanings:["名|生態学","名|（ある地域の）生態"],
   pronunciation:"/iˈkɑːlədʒi/",part:120,
   example:"The class learned about the ecology of coral reefs.",
   exampleJa:"そのクラスは、サンゴ礁の生態について学んだ。",
   example2:"Ecology helps us understand how living things depend on each other.",
   exampleJa2:"生態学は、生き物どうしがどう支え合っているかを理解する助けになる。",
   etymologyProcess:"eco（家）＋ log（学問）→ 生き物とすみかの関わりを調べると…？",
   etymologyConclusion:"eco（家）＋ log（学問）→ 生き物とそのすみかとの関わりを調べる学問＝生態学",
   relatedWords:[
     {word:"economy",meaning:"経済",breakdown:"eco（家）＋ nom（切り盛りする）→ 家の切り盛りの仕方"},
     {word:"economic",meaning:"経済の",breakdown:"eco（家）＋ nom（切り盛りする）＋ ic（形容詞）→ 国の切り盛りに関わる"},
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）→ 生き物のしくみを調べる学問"},
     {synonym:true,word:"environment",meaning:"環境",breakdown:"まわりを取り巻くもの。ecology は生き物との関わりを学ぶ学問"}]},

  {id:1198,word:"philosophy",partOfSpeech:"名詞",meaning:"哲学",
   meanings:["名|哲学","名|（人生の）信条，考え方"],
   pronunciation:"/fɪˈlɑːsəfi/",part:120,
   example:"He reads Greek philosophy every night before going to bed.",
   exampleJa:"彼は毎晩、寝る前にギリシャ哲学を読む。",
   example2:"Her philosophy of life is simple and very clear.",
   exampleJa2:"彼女の人生の信条は、単純でとても明快だ。",
   etymologyProcess:"phil（愛する）＋ soph（知恵）→ 知恵を愛して求め続けると…？",
   etymologyConclusion:"phil（愛する）＋ soph（知恵）→ 知恵を愛し、求め続ける学問＝哲学",
   relatedWords:[
     {word:"philosopher",meaning:"哲学者",breakdown:"phil（愛する）＋ soph（知恵）＋ er（人）→ 知恵を愛し求める人"},
     {word:"sophisticated",meaning:"洗練された",breakdown:"soph（知恵）＋ ist（人）＋ ate（動詞）→ 知恵で手を加えて磨き上げた"},
     {synonym:true,word:"thought",meaning:"思想，考え",breakdown:"考えること。philosophy は筋道立てた深い考えの体系"},
     {synonym:true,word:"wisdom",meaning:"知恵",breakdown:"深い知恵。philosophy はそれを愛し求める営みを指す"}]},

  {id:1199,word:"geography",partOfSpeech:"名詞",meaning:"地理（学）",
   meanings:["名|地理学","名|（ある土地の）地理，地形"],
   pronunciation:"/dʒiˈɑːɡrəfi/",part:120,
   example:"We are studying the geography of Africa this month.",
   exampleJa:"私たちは今月、アフリカの地理を学んでいる。",
   example2:"The geography of this island makes farming quite difficult.",
   exampleJa2:"この島の地形は、農業をかなり難しくしている。",
   etymologyProcess:"geo（大地）＋ graph（書く）→ 大地のようすを書き表すと…？",
   etymologyConclusion:"geo（大地）＋ graph（書く）→ 大地のようすを書き表したもの＝地理学",
   relatedWords:[
     {word:"geology",meaning:"地質学",breakdown:"geo（大地）＋ log（学問）→ 大地の成り立ちを調べる学問"},
     {word:"geometry",meaning:"幾何学",breakdown:"geo（大地）＋ metr（測る）→ 土地を測ることから生まれた学問"},
     {word:"graph",meaning:"グラフ",breakdown:"graph（書く）→ 数の動きを線で書き表したもの"},
     {word:"photograph",meaning:"写真",breakdown:"photo（光）＋ graph（書く）→ 光で描き取ったもの"}]},

  {id:1200,word:"institution",partOfSpeech:"名詞",meaning:"機関；制度",
   meanings:["名|（公共の）機関，施設","名|（社会の）制度"],
   pronunciation:"/ˌɪnstɪˈtuːʃn/",part:120,
   example:"This medical institution was built about a century ago.",
   exampleJa:"この医療機関は、およそ1世紀前に建てられた。",
   example2:"Marriage is a very old institution in many cultures.",
   exampleJa2:"結婚は、多くの文化でとても古い制度だ。",
   etymologyProcess:"in（中に）＋ stitut（立てる）→ 社会の中に柱を立てて作ると…？",
   etymologyConclusion:"in（中に）＋ stitut（立てる）＋ ion（名詞）→ 社会の中に柱を立てて作られた組織＝機関",
   relatedWords:[
     {word:"institute",meaning:"設立する；協会",breakdown:"in（中に）＋ stitut（立てる）→ 中に柱を立てて組織を作る"},
     {word:"constitute",meaning:"構成する",breakdown:"con（共に）＋ stitut（立てる）→ 部品を共に立てて全体を作る"},
     {word:"substitute",meaning:"代わりに用いる",breakdown:"sub（下で）＋ stitut（立てる）→ 元のものの下に別のものを立てる"},
     {word:"constitution",meaning:"憲法；構成",breakdown:"con（共に）＋ stitut（立てる）＋ ion（名詞）→ 国の形を共に立てた決まり"}]},

  {id:1201,word:"faculty",partOfSpeech:"名詞",meaning:"（生まれつきの）能力；学部",
   meanings:["名|（生まれつきの）能力","名|（大学の）学部，教員団"],
   pronunciation:"/ˈfæklti/",part:121,
   example:"She has a great faculty for learning new languages.",
   exampleJa:"彼女は、新しい言語を学ぶ大きな能力を持っている。",
   example2:"The science faculty moved to a brand-new campus.",
   exampleJa2:"理学部は、新しいキャンパスへ移った。",
   etymologyProcess:"facil（しやすい）＋ ty（名詞）→ 物事をたやすくこなせる力なら…？",
   etymologyConclusion:"facil（しやすい）＋ ty（名詞）→ 物事をたやすくこなせる生まれつきの力＝能力",
   why:"【なぜ】もとは「たやすくこなせる力」。中世の大学で「教える力を持つ人の集まり」を faculty と呼んだことから、「学部・教員団」の意味が生まれました。\n【つながり】facility（物事をしやすくする設備）、facilitate（たやすくする）も同じ家族です。",
   relatedWords:[
     {word:"facility",meaning:"施設，設備",breakdown:"facil（しやすい）＋ ity（名詞）→ 物事をしやすくする設備"},
     {word:"facilitate",meaning:"容易にする",breakdown:"facil（しやすい）＋ ate（動詞）→ 物事をしやすくしてやる"},
     {word:"difficult",meaning:"難しい",breakdown:"dis（否定）＋ facil（しやすい）→ たやすくはない"},
     {word:"fact",meaning:"事実",breakdown:"fact（作る）→ 実際に作り出されて起きたこと"}]},

  {id:1202,word:"intermediate",partOfSpeech:"形容詞",meaning:"中級の，中間の",
   meanings:["形|中級の，中間の"],
   pronunciation:"/ˌɪntərˈmiːdiət/",part:121,
   example:"He joined the intermediate English class last April.",
   exampleJa:"彼は昨年の4月、中級の英語クラスに入った。",
   example2:"This book is written for intermediate level learners.",
   exampleJa2:"この本は、中級の水準の学習者向けに書かれている。",
   etymologyProcess:"inter（間の）＋ medi（中間）→ 初級と上級のちょうど間にあると…？",
   etymologyConclusion:"inter（間の）＋ medi（中間）→ 初級と上級のちょうど間にあたる＝中級の",
   relatedWords:[
     {word:"medium",meaning:"媒体；中くらいの",breakdown:"medi（中間）→ 送り手と受け手の中間に立って伝えるもの"},
     {word:"middle",meaning:"真ん中",breakdown:"middle（中間）→ 両端から等しく離れたところ"},
     {word:"immediately",meaning:"すぐに",breakdown:"im（否定）＋ medi（中間）→ 間に何も挟まずに"},
     {word:"media",meaning:"メディア，報道機関",breakdown:"medi（中間）→ 情報を伝える媒体の複数形"}]},

  {id:1203,word:"notion",partOfSpeech:"名詞",meaning:"（ばくぜんとした）考え",
   meanings:["名|（ばくぜんとした）考え，思いつき"],
   pronunciation:"/ˈnoʊʃn/",part:121,
   example:"He has a strange notion about how birds fly.",
   exampleJa:"彼は、鳥の飛び方について奇妙な考えを持っている。",
   example2:"The notion of fairness changes from age to age.",
   exampleJa2:"公正さという考えは、時代ごとに変わっていく。",
   etymologyProcess:"not（知る）＋ ion（名詞）→ 頭の中に知られた形として浮かぶものは…？",
   etymologyConclusion:"not（知る）＋ ion（名詞）→ 頭の中に知られた形として浮かんでくるもの＝考え",
   relatedWords:[
     {word:"notice",meaning:"気づく；掲示",breakdown:"not（知る）＋ ice（名詞）→ それと知ること"},
     {word:"recognize",meaning:"見分ける，認める",breakdown:"re（再び）＋ co（共に）＋ gn（知る）→ 前に知ったものだと分かる"},
     {word:"ignore",meaning:"無視する",breakdown:"in（否定）＋ gnor（知る）→ 知らないことにして取り合わない"},
     {synonym:true,word:"idea",meaning:"考え，着想",breakdown:"思いつき。notion はもっとぼんやりした考えを指す"}]},

  {id:1204,word:"concept",partOfSpeech:"名詞",meaning:"概念，とらえ方",
   meanings:["名|概念，とらえ方"],
   pronunciation:"/ˈkɑːnsept/",part:121,
   example:"The concept of time is very hard to explain.",
   exampleJa:"時間という概念は、説明するのがとても難しい。",
   example2:"This new design is based on one simple concept.",
   exampleJa2:"この新しいデザインは、一つの単純な概念に基づいている。",
   etymologyProcess:"con（すっかり）＋ cept（取る）→ 頭の中にすっかり取り込んでまとめると…？",
   etymologyConclusion:"con（すっかり）＋ cept（取る）→ 頭の中にすっかり取り込んでまとめた形＝概念",
   relatedWords:[
     {word:"accept",meaning:"受け入れる",breakdown:"ac（〜へ）＋ cept（取る）→ 差し出されたほうへ手を出して取る"},
     {word:"except",meaning:"～を除いて",breakdown:"ex（外へ）＋ cept（取る）→ 外へ取り出して別あつかいにする"},
     {word:"reception",meaning:"もてなし；受付",breakdown:"re（戻す）＋ cept（取る）＋ ion（名詞）→ 訪れた人を受け取ること"},
     {word:"capture",meaning:"捕らえる",breakdown:"cap（つかむ）＋ ure（名詞）→ つかまえて自分のものにする"}]},

  {id:1205,word:"meditation",partOfSpeech:"名詞",meaning:"瞑想",
   meanings:["名|瞑想","名|熟考"],
   pronunciation:"/ˌmedɪˈteɪʃn/",part:121,
   example:"Daily meditation helps him stay calm and focused.",
   exampleJa:"毎日の瞑想は、彼が落ち着いて集中していられるのを助けている。",
   example2:"She learned meditation at a quiet old mountain temple.",
   exampleJa2:"彼女は、静かな古い山寺で瞑想を学んだ。",
   etymologyProcess:"medit（じっくり考える）＋ ation（名詞）→ 心を静めて考え続けると…？",
   etymologyConclusion:"medit（じっくり考える）＋ ation（名詞）→ 心を静めて一つのことを考え続けること＝瞑想",
   relatedWords:[
     {word:"meditate",meaning:"瞑想する",breakdown:"medit（じっくり考える）＋ ate（動詞）→ 心を静めて考え続ける"},
     {synonym:true,word:"reflection",meaning:"熟考；反射",breakdown:"静かに考えること。meditation は心を静める修行の色が濃い"},
     {synonym:true,word:"concentration",meaning:"集中",breakdown:"一点に集めること。meditation は心を静めて考え続けること"},
     {synonym:true,word:"mindfulness",meaning:"マインドフルネス",breakdown:"今この時に心を向ける訓練。meditation はその代表的なやり方"}]},

  {id:1206,word:"insight",partOfSpeech:"名詞",meaning:"洞察（力）",
   meanings:["名|洞察（力），見抜く力"],
   pronunciation:"/ˈɪnsaɪt/",part:121,
   example:"Her book gives deep insight into human behavior.",
   exampleJa:"彼女の本は、人間の行動への深い洞察を与えてくれる。",
   example2:"The teacher showed real insight into the difficult problem.",
   exampleJa2:"先生は、その難しい問題への本物の洞察を示した。",
   etymologyProcess:"in（中へ）＋ sight（光景）→ 物事の内側まで見通す目の力なら…？",
   etymologyConclusion:"in（中へ）＋ sight（光景）→ 物事の内側まで見通してしまう目の力＝洞察力",
   relatedWords:[
     {word:"sight",meaning:"視力；光景",breakdown:"sight（光景）→ 目に映って見えるもの"},
     {word:"foresight",meaning:"先見の明",breakdown:"fore（前に）＋ sight（光景）→ 先のことまで見通しておく力"},
     {synonym:true,word:"understanding",meaning:"理解",breakdown:"分かること。insight は奥まで見通す鋭い見抜き方を指す"},
     {synonym:true,word:"wisdom",meaning:"知恵",breakdown:"深い知恵。insight は物事の内側を見抜く力を指す"}]},

  {id:1207,word:"caution",partOfSpeech:"名詞",meaning:"用心，注意",
   meanings:["名|用心，注意","他|警告する"],
   pronunciation:"/ˈkɔːʃn/",part:121,
   example:"Please cross the old wooden bridge with great caution.",
   exampleJa:"その古い木の橋は、十分な用心をもって渡ってください。",
   example2:"The road sign warns drivers to use extra caution.",
   exampleJa2:"その道路標識は、運転手にいっそうの用心を促している。",
   etymologyProcess:"caut（用心する）＋ ion（名詞）→ 危なくないか気をつけて構えると…？",
   etymologyConclusion:"caut（用心する）＋ ion（名詞）→ 危なくないかと気をつけて構えること＝用心",
   relatedWords:[
     {word:"cautious",meaning:"用心深い",breakdown:"caut（用心する）＋ ous（形容詞）→ 用心を欠かさないでいる"},
     {word:"precaution",meaning:"予防策",breakdown:"pre（先に）＋ caut（用心する）＋ ion（名詞）→ 先回りしての用心"},
     {synonym:true,word:"care",meaning:"注意，世話",breakdown:"気を配ること。caution は危険に備える用心を指す"},
     {synonym:true,word:"warning",meaning:"警告",breakdown:"危ないと知らせること。caution は自分が構える用心のほう"}]},

  {id:1208,word:"will",partOfSpeech:"名詞",meaning:"意志",
   meanings:["名|意志，意欲","名|遺言（書）"],
   pronunciation:"/wɪl/",part:121,
   example:"He has a strong will to become a good doctor.",
   exampleJa:"彼は、よい医者になろうという強い意志を持っている。",
   example2:"My grandfather left a will before he passed away.",
   exampleJa2:"祖父は亡くなる前に、遺言を残した。",
   etymologyProcess:"wil（望む）→ こうしたいと心に決めて動かないと…？",
   etymologyConclusion:"wil（望む）→ こうしたいと心に決めて動かない、強い思い＝意志",
   why:"【なぜ】will はもともと「こうしたいという望み」。死ぬ前に「自分はこうしてほしい」と書き残したものが、そのまま「遺言」と呼ばれるようになりました。\n【つながり】willing（進んで〜する）も「そうしたい」から。未来を表す助動詞の will も、もとは「〜するつもりだ」です。",
   relatedWords:[
     {word:"willing",meaning:"進んで～する",breakdown:"wil（望む）＋ ing（〜している）→ そうしたいと望んでいる"},
     {word:"goodwill",meaning:"好意，善意",breakdown:"good（ふさわしい）＋ wil（望む）→ 相手によかれと望む気持ち"},
     {word:"welcome",meaning:"歓迎する",breakdown:"wil（望む）＋ come（来る）→ 来てほしかった人が来た"},
     {synonym:true,word:"determination",meaning:"決意",breakdown:"固く決めること。will はその決意を支える心の力を指す"}]},

  {id:1209,word:"option",partOfSpeech:"名詞",meaning:"選択肢",
   meanings:["名|選択肢，選べる道"],
   pronunciation:"/ˈɑːpʃn/",part:121,
   example:"Students have three options for the coming school trip.",
   exampleJa:"生徒には、今度の修学旅行の選択肢が3つある。",
   example2:"Walking home was not a real option that night.",
   exampleJa2:"その夜、歩いて帰ることは現実的な選択肢ではなかった。",
   etymologyProcess:"opt（選ぶ）＋ ion（名詞）→ 選んで取ることのできる道の一つは…？",
   etymologyConclusion:"opt（選ぶ）＋ ion（名詞）→ 選んで取ることのできる道の一つ＝選択肢",
   relatedWords:[
     {word:"optional",meaning:"任意の，選択できる",breakdown:"opt（選ぶ）＋ al（形容詞）→ 選んでも選ばなくてもよい"},
     {word:"adopt",meaning:"採用する；養子にする",breakdown:"ad（〜へ）＋ opt（選ぶ）→ 選んで自分のほうへ取り入れる"},
     {word:"opt",meaning:"選ぶ",breakdown:"opt（選ぶ）→ いくつかの中から自分でこれと選び取る"},
     {synonym:true,word:"choice",meaning:"選択",breakdown:"選ぶこと。option は選べる道の一つ一つを指す"}]},

  {id:1210,word:"prospect",partOfSpeech:"名詞",meaning:"見通し，見込み",
   meanings:["名|見通し，見込み","名|（複数で）将来性"],
   pronunciation:"/ˈprɑːspekt/",part:121,
   example:"There is little prospect of rain later this week.",
   exampleJa:"今週の後半、雨の見通しはほとんどない。",
   example2:"The job offers good prospects for young hard workers.",
   exampleJa2:"その仕事は、よく働く若者によい将来性を与えてくれる。",
   etymologyProcess:"pro（前へ）＋ spect（見る）→ 前方を見わたして先のようすを思い描くと…？",
   etymologyConclusion:"pro（前へ）＋ spect（見る）→ 前方を見わたして思い描く、先のようす＝見通し",
   relatedWords:[
     {word:"expect",meaning:"期待する",breakdown:"ex（外へ）＋ spect（見る）→ 外を見ながら来るのを待つ"},
     {word:"respect",meaning:"尊敬する",breakdown:"re（再び）＋ spect（見る）→ 何度も見返すほど価値を認める"},
     {word:"inspect",meaning:"検査する",breakdown:"in（中へ）＋ spect（見る）→ 中までのぞき込んで調べる"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ ator（人）→ 見ているほうの人"}]},

  {id:1211,word:"cherish",partOfSpeech:"他動詞",meaning:"大切にする",
   meanings:["他|（思い出・人）を大切にする，いつくしむ"],
   pronunciation:"/ˈtʃerɪʃ/",part:122,
   example:"I cherish the memories of my childhood summer holidays.",
   exampleJa:"私は、子ども時代の夏休みの思い出を大切にしている。",
   example2:"She cherishes the old silver watch from her grandfather.",
   exampleJa2:"彼女は、祖父からもらった古い銀の時計を大切にしている。",
   etymologyProcess:"car（いとしい）＋ ish（〜にする）→ いとしいものとして胸に抱き続けると…？",
   etymologyConclusion:"car（いとしい）＋ ish（〜にする）→ いとしいものとして胸に抱き続ける＝大切にする",
   why:"【なぜ】ラテン語 carus は「いとしい」。古フランス語 chier（いとしい）を経て、-ish（〜にする）が付いて「いとしいものとして扱う」＝大切にする、になりました。\n【つながり】charity（人をいとしく思う心からの行い）も同じ家族。つづりの似た care（心配・世話）は別系統のゲルマン語なので注意してください。",
   relatedWords:[
     {word:"charity",meaning:"慈善",breakdown:"car（いとしい）＋ ty（名詞）→ 人をいとしく思う気持ちからの行い"},
     {word:"caress",meaning:"優しくなでる",breakdown:"car（いとしい）→ いとしさをこめて、そっとなでる"},
     {synonym:true,word:"treasure",meaning:"大切にする；宝物",breakdown:"宝のように扱うこと。cherish は心の中で大事に思い続けること"},
     {synonym:true,word:"value",meaning:"重んじる",breakdown:"価値を認めること。cherish は愛情をこめて大事にすること"}]},

  {id:1212,word:"intend",partOfSpeech:"他動詞",meaning:"～するつもりだ",
   meanings:["他|（to do）～するつもりだ，意図する"],
   pronunciation:"/ɪnˈtend/",part:122,
   example:"I intend to study abroad right after my graduation.",
   exampleJa:"私は卒業後すぐに留学するつもりだ。",
   example2:"They intended no harm at all with that joke.",
   exampleJa2:"彼らはその冗談で、害を与えるつもりはまったくなかった。",
   etymologyProcess:"in（中へ）＋ tend（伸ばす）→ 目指すほうへ心をぴんと伸ばすと…？",
   etymologyConclusion:"in（中へ）＋ tend（伸ばす）→ 目指すほうへ心をぴんと伸ばしている＝～するつもりだ",
   relatedWords:[
     {word:"tend",meaning:"傾向がある",breakdown:"tend（伸ばす）→ 心がそちらへ伸びていく"},
     {word:"extend",meaning:"伸ばす，広げる",breakdown:"ex（外へ）＋ tend（伸ばす）→ 外へ向けて伸ばしていく"},
     {word:"attend",meaning:"出席する",breakdown:"ad（〜へ）＋ tend（伸ばす）→ 心をそちらへ伸ばして出向く"},
     {word:"intention",meaning:"意図",breakdown:"in（中へ）＋ tend（伸ばす）＋ ion（名詞）→ 心を伸ばしている向き"}]},

  {id:1213,word:"suspect",partOfSpeech:"他動詞",meaning:"～ではないかと思う",
   meanings:["他|（that SV）～ではないかと思う","他|（人）を怪しいと思う"],
   pronunciation:"/səˈspekt/",part:122,
   example:"I suspect that he already knows the whole truth.",
   exampleJa:"彼はすでに真実をすべて知っているのではないかと思う。",
   example2:"Police suspected the man standing near the broken window.",
   exampleJa2:"警察は、壊れた窓の近くに立っていた男を怪しいと思った。",
   etymologyProcess:"sub（下で）＋ spect（見る）→ 下から探るように見て怪しむと…？",
   etymologyConclusion:"sub（下で）＋ spect（見る）→ 下から探るように見て、そうではないかと疑う＝～ではないかと思う",
   relatedWords:[
     {word:"respect",meaning:"尊敬する",breakdown:"re（再び）＋ spect（見る）→ 何度も見返すほど価値を認める"},
     {word:"inspect",meaning:"検査する",breakdown:"in（中へ）＋ spect（見る）→ 中までのぞき込んで調べる"},
     {word:"expect",meaning:"期待する",breakdown:"ex（外へ）＋ spect（見る）→ 外を見ながら来るのを待つ"},
     {word:"prospect",meaning:"見通し",breakdown:"pro（前へ）＋ spect（見る）→ 前方を見わたして思い描く先のようす"}]},

  {id:1214,word:"identify",partOfSpeech:"他動詞",meaning:"特定する，見分ける",
   meanings:["他|（正体・身元）を特定する，見分ける"],
   pronunciation:"/aɪˈdentɪfaɪ/",part:122,
   example:"Police often identify drivers from security camera images.",
   exampleJa:"警察はよく、防犯カメラの映像から運転手を特定する。",
   example2:"Scientists identified a completely new kind of tiny insect.",
   exampleJa2:"科学者たちは、まったく新しい種類の小さな昆虫を特定した。",
   etymologyProcess:"ident（同じ）＋ fy（する）→ これと同じものだと見極めて言い当てると…？",
   etymologyConclusion:"ident（同じ）＋ fy（する）→ これと同じものだと見極めて言い当てる＝特定する",
   relatedWords:[
     {word:"identity",meaning:"正体，身元",breakdown:"ident（同じ）＋ ty（名詞）→ ほかならぬその人であること"},
     {word:"identical",meaning:"まったく同じ",breakdown:"ident（同じ）＋ al（形容詞）→ 見分けがつかないほど同じ"},
     {synonym:true,word:"recognize",meaning:"見分ける",breakdown:"それと分かること。identify は誰・何かをはっきり突き止めること"},
     {synonym:true,word:"determine",meaning:"突き止める，決める",breakdown:"はっきりさせること。identify は正体を言い当てること"}]},

  {id:1215,word:"permit",partOfSpeech:"他動詞",meaning:"許可する",
   meanings:["他|許可する，認める","名|許可証"],
   pronunciation:"/pərˈmɪt/",part:122,
   example:"The school does not permit phones during class time.",
   exampleJa:"学校は、授業中の電話を許可していない。",
   example2:"Weather permitting, we will climb the mountain tomorrow morning.",
   exampleJa2:"天気が許せば、私たちは明日の朝その山に登る。",
   etymologyProcess:"per（通して）＋ mit（送る）→ 通り抜けて行かせてやると…？",
   etymologyConclusion:"per（通して）＋ mit（送る）→ 止めずに通り抜けて行かせてやる＝許可する",
   relatedWords:[
     {word:"submit",meaning:"提出する",breakdown:"sub（下で）＋ mit（送る）→ 目上の人の下へ差し出す"},
     {word:"transmit",meaning:"送り伝える",breakdown:"trans（越えて）＋ mit（送る）→ 境を越えて向こうへ送る"},
     {word:"commit",meaning:"ゆだねる；（罪を）犯す",breakdown:"com（共に）＋ mit（送る）→ 相手のもとへ身をすっかり送り込む"},
     {word:"mission",meaning:"任務",breakdown:"mis（送る）＋ ion（名詞）→ 送り出されて果たす役目"}]},

  {id:1216,word:"acknowledge",partOfSpeech:"他動詞",meaning:"（事実と）認める",
   meanings:["他|（事実と）認める","他|（受け取りを）知らせる"],
   pronunciation:"/əkˈnɑːlɪdʒ/",part:122,
   example:"He acknowledged his own mistake in front of everyone.",
   exampleJa:"彼はみんなの前で、自分の失敗を認めた。",
   example2:"The company acknowledges the problem and will fix it.",
   exampleJa2:"その会社は問題を認めており、それを直すつもりだ。",
   etymologyProcess:"ac（〜へ）＋ knowledge（知っている）→ 知っていると相手にはっきり示すと…？",
   etymologyConclusion:"ac（〜へ）＋ knowledge（知っている）→ 知っていると相手に向かってはっきり示す＝認める",
   why:"【なぜ】もとは古英語の on-（〜に向かって）＋「知る」で、「知っていると表に出す」こと。つづりの c は後から、ラテン語の ad- に似せて入り込んだものです。\n【つながり】ラテン語系ではなく、knowledge や know と同じゲルマン系の仲間です。",
   relatedWords:[
     {word:"knowledge",meaning:"知識",breakdown:"knowledge（知っている）→ 知っていることのひとまとまり"},
     {word:"know",meaning:"知る",breakdown:"know（知る）→ 頭の中にはっきり持っている"},
     {word:"recognize",meaning:"見分ける，認める",breakdown:"re（再び）＋ co（共に）＋ gn（知る）→ 前に知ったものだと分かる"},
     {synonym:true,word:"admit",meaning:"認める",breakdown:"しぶしぶ認めること。acknowledge は事実として公に認めること"}]},

  {id:1217,word:"perceive",partOfSpeech:"他動詞",meaning:"認識する，感じ取る",
   meanings:["他|認識する，感じ取る"],
   pronunciation:"/pərˈsiːv/",part:122,
   example:"Dogs perceive high sounds that humans cannot hear.",
   exampleJa:"犬は、人間には聞こえない高い音を感じ取る。",
   example2:"She perceived a small change in his quiet voice.",
   exampleJa2:"彼女は、彼の静かな声の小さな変化を感じ取った。",
   etymologyProcess:"per（すっかり）＋ cept（取る）→ 五感ですっかり取り込んで気づくと…？",
   etymologyConclusion:"per（すっかり）＋ cept（取る）→ 五感ですっかり取り込んで、それと気づく＝認識する",
   relatedWords:[
     {word:"accept",meaning:"受け入れる",breakdown:"ac（〜へ）＋ cept（取る）→ 差し出されたほうへ手を出して取る"},
     {word:"concept",meaning:"概念",breakdown:"con（すっかり）＋ cept（取る）→ 頭の中にすっかり取り込んだ形"},
     {word:"except",meaning:"～を除いて",breakdown:"ex（外へ）＋ cept（取る）→ 外へ取り出して別あつかいにする"},
     {word:"reception",meaning:"もてなし；受付",breakdown:"re（戻す）＋ cept（取る）＋ ion（名詞）→ 訪れた人を受け取ること"}]},

  {id:1218,word:"evaluate",partOfSpeech:"他動詞",meaning:"評価する",
   meanings:["他|評価する，値打ちを見定める"],
   pronunciation:"/ɪˈvæljueɪt/",part:122,
   example:"Teachers evaluate each student's work very carefully here.",
   exampleJa:"ここでは、先生たちが各生徒の作品をとても注意深く評価する。",
   example2:"We evaluated three plans before choosing the best one.",
   exampleJa2:"私たちは最良のものを選ぶ前に、3つの計画を評価した。",
   etymologyProcess:"e（外へ）＋ valu（価値）→ 価値をどれだけか引き出して見定めると…？",
   etymologyConclusion:"e（外へ）＋ valu（価値）→ 価値がどれだけあるかを引き出して見定める＝評価する",
   relatedWords:[
     {word:"value",meaning:"価値；重んじる",breakdown:"valu（価値）→ そのものにどれだけの値打ちがあるか"},
     {word:"valuable",meaning:"価値のある",breakdown:"valu（価値）＋ able（できる）→ 高い値打ちが認められる"},
     {word:"valid",meaning:"有効な，妥当な",breakdown:"val（力がある）＋ id（〜な状態の）→ 根拠がしっかりしていて通用する"},
     {synonym:true,word:"assess",meaning:"査定する",breakdown:"程度を見積もること。evaluate は価値や質を見定めること"}]},

  {id:1219,word:"cultivate",partOfSpeech:"他動詞",meaning:"耕す；（力を）育てる",
   meanings:["他|（土地）を耕す，栽培する","他|（能力・関係）を育てる"],
   pronunciation:"/ˈkʌltɪveɪt/",part:122,
   example:"Farmers cultivate these wide flat fields every single spring.",
   exampleJa:"農家は毎年春、これらの広く平らな畑を耕す。",
   example2:"Reading widely helps cultivate a rich strong imagination.",
   exampleJa2:"幅広く読むことは、豊かで強い想像力を育てる助けになる。",
   etymologyProcess:"cult（耕す）＋ ate（動詞）→ 土を耕して作物や力を育て上げると…？",
   etymologyConclusion:"cult（耕す）＋ ate（動詞）→ 土を耕して、作物や力を育て上げる＝耕す",
   relatedWords:[
     {word:"culture",meaning:"文化",breakdown:"cult（耕す）＋ ure（名詞）→ 人が心を耕して育ててきたもの"},
     {word:"agriculture",meaning:"農業",breakdown:"agri（畑）＋ cult（耕す）→ 畑を耕して作物を作ること"},
     {word:"colony",meaning:"植民地；集団",breakdown:"cult（耕す）→ 人が移り住んで土地を耕したところ"},
     {synonym:true,word:"grow",meaning:"育てる",breakdown:"育つ・育てること。cultivate は手をかけて育て上げること"}]},

  {id:1220,word:"shade",partOfSpeech:"名詞",meaning:"日陰",
   meanings:["名|日陰","名|（色の）濃淡"],
   pronunciation:"/ʃeɪd/",part:122,
   example:"We ate our lunch in the shade of a tree.",
   exampleJa:"私たちは、木の日陰で昼食を食べた。",
   example2:"This wide hat gives good shade on sunny days.",
   exampleJa2:"この広いつばの帽子は、晴れた日によい日陰を作ってくれる。",
   etymologyProcess:"shad（影）→ 日ざしがさえぎられてできる涼しい暗がりは…？",
   etymologyConclusion:"shad（影）→ 日ざしがさえぎられてできる、涼しい暗がり＝日陰",
   relatedWords:[
     {word:"shadow",meaning:"影",breakdown:"shad（影）→ 光をさえぎった物が地に落とす形"},
     {word:"shady",meaning:"日陰の；うさんくさい",breakdown:"shad（影）＋ y（形容詞）→ 日陰が多い。そこから「うさんくさい」"},
     {synonym:true,word:"shelter",meaning:"避難所",breakdown:"身を守る場所。shade は日ざしをさえぎった涼しい場所"},
     {synonym:true,word:"sunshade",meaning:"日よけ",breakdown:"日ざしをさえぎる道具。shade はそれでできる日陰そのもの"}]},

  {id:1221,word:"breeze",partOfSpeech:"名詞",meaning:"そよ風",
   meanings:["名|そよ風，微風"],
   pronunciation:"/briːz/",part:123,
   example:"A cool breeze blew through the open classroom window.",
   exampleJa:"涼しいそよ風が、開いた教室の窓から吹き抜けた。",
   example2:"The summer breeze carried the fresh smell of the sea.",
   exampleJa2:"夏のそよ風が、海の新鮮なにおいを運んできた。",
   etymologyProcess:"breeze（やわらかい風）→ 頬をなでるように吹く軽い風は…？",
   etymologyConclusion:"breeze（やわらかい風）→ 頬をなでるように吹く、軽くやわらかい風＝そよ風",
   hook:"もとは船乗りが使った「北東の風」。a breeze は「楽なこと」にも使う。",
   relatedWords:[
     {synonym:true,word:"wind",meaning:"風",breakdown:"風ぜんたい。breeze は心地よい弱い風だけを指す"},
     {synonym:true,word:"air",meaning:"空気",breakdown:"まわりの気体。breeze はそれが軽く動いている状態"},
     {synonym:true,word:"gust",meaning:"突風",breakdown:"急に強く吹く風。breeze は穏やかで続く風"},
     {synonym:true,word:"blow",meaning:"（風が）吹く",breakdown:"風が動くこと。breeze はその弱く心地よい風そのもの"}]},

  {id:1222,word:"desert",partOfSpeech:"名詞",meaning:"砂漠",
   meanings:["名|砂漠","他|（/dɪˈzɜːrt/ で）見捨てる"],
   pronunciation:"/ˈdezərt/",part:123,
   example:"Very few plants grow in this dry hot desert.",
   exampleJa:"この乾いた暑い砂漠では、ごくわずかな植物しか育たない。",
   example2:"They crossed the wide desert on strong young camels.",
   exampleJa2:"彼らは強い若いラクダに乗って、広い砂漠を横断した。",
   etymologyProcess:"de（離して）＋ ser（つなぐ）→ 人のつながりから切り離された土地は…？",
   etymologyConclusion:"de（離して）＋ ser（つなぐ）→ 人のつながりから切り離され、見捨てられた土地＝砂漠",
   why:"【なぜ】ラテン語 deserere は de（離して）＋ serere（つなぎ合わせる）で「つながりを断つ＝見捨てる」。見捨てられて人の住まない土地が desert（砂漠）です。動詞の desert（見捨てる）は同じ語で、アクセントの位置だけが変わります。\n【つながり】series（ひと続き）、insert（間に差し込む）も同じ ser の家族です。",
   relatedWords:[
     {word:"series",meaning:"ひと続き，連続",breakdown:"ser（つなぐ）→ 一つにつなげて並べたひと続き"},
     {word:"insert",meaning:"差し込む",breakdown:"in（中へ）＋ ser（つなぐ）→ 間に入れてつなぎ合わせる"},
     {synonym:true,word:"wasteland",meaning:"荒れ地",breakdown:"何も育たない土地。desert は雨の少ない砂の大地を指す"},
     {synonym:true,word:"oasis",meaning:"オアシス",breakdown:"砂漠の中の水のある所。desert はその周りの乾いた大地"}]},

  {id:1223,word:"fog",partOfSpeech:"名詞",meaning:"霧",
   meanings:["名|霧"],
   pronunciation:"/fɑːɡ/",part:123,
   example:"Thick fog covered the whole valley early this morning.",
   exampleJa:"濃い霧が今朝早く、谷全体を覆った。",
   example2:"The plane could not land because of the heavy fog.",
   exampleJa2:"その濃い霧のため、飛行機は着陸できなかった。",
   etymologyProcess:"fog（立ちこめる水けむり）→ 地面近くに立ちこめて視界をさえぎると…？",
   etymologyConclusion:"fog（立ちこめる水けむり）→ 地面近くに立ちこめて視界をさえぎる水の粒＝霧",
   hook:"語源ははっきりしない。foggy（霧の深い）とセットで覚える。",
   relatedWords:[
     {synonym:true,word:"mist",meaning:"かすみ，もや",breakdown:"薄いもや。fog は視界をさえぎるほど濃いものを指す"},
     {synonym:true,word:"cloud",meaning:"雲",breakdown:"空に浮かぶ水の粒。fog は地面近くに下りてきたもの"},
     {synonym:true,word:"haze",meaning:"かすみ",breakdown:"ぼんやりかすむこと。fog は水の粒が濃く立ちこめた状態"},
     {synonym:true,word:"smog",meaning:"スモッグ",breakdown:"smoke ＋ fog の合成語。煙が混じった濃い霧のこと"}]},

  {id:1224,word:"moisture",partOfSpeech:"名詞",meaning:"湿気，水分",
   meanings:["名|湿気，水分"],
   pronunciation:"/ˈmɔɪstʃər/",part:123,
   example:"Plants need both light and moisture to grow well.",
   exampleJa:"植物はよく育つために、光と湿気の両方を必要とする。",
   example2:"This cream keeps moisture in your dry winter skin.",
   exampleJa2:"このクリームは、冬の乾いた肌に水分を保ってくれる。",
   etymologyProcess:"moist（湿った）＋ ure（名詞）→ 空気や物にふくまれる水けは…？",
   etymologyConclusion:"moist（湿った）＋ ure（名詞）→ 空気や物の中にふくまれている水け＝湿気",
   relatedWords:[
     {word:"moist",meaning:"湿った",breakdown:"moist（湿った）→ ほどよく水けをふくんでいる"},
     {word:"moisten",meaning:"湿らせる",breakdown:"moist（湿った）＋ en（〜にする）→ 水けをふくませる"},
     {synonym:true,word:"humidity",meaning:"湿度",breakdown:"空気の湿り具合。moisture は水けそのものを指す"},
     {synonym:true,word:"damp",meaning:"湿った",breakdown:"じめじめした感じ。moisture はふくまれる水けを指す名詞"}]},

  {id:1225,word:"damp",partOfSpeech:"形容詞",meaning:"（じめじめと）湿った",
   meanings:["形|（じめじめと）湿った"],
   pronunciation:"/dæmp/",part:123,
   example:"The old basement feels cold and damp in winter.",
   exampleJa:"その古い地下室は、冬は冷たくじめじめと湿った感じがする。",
   example2:"Do not put damp clothes into the small closet.",
   exampleJa2:"湿った服を、その小さな押し入れに入れてはいけない。",
   etymologyProcess:"damp（水けむり）→ 水けむりを含んでじめじめしていると…？",
   etymologyConclusion:"damp（水けむり）→ 水けむりを含んでじめじめしている＝湿った",
   hook:"もとの意味は「水けむり・蒸気」。じめっと不快な湿り気が芯。",
   relatedWords:[
     {synonym:true,word:"moist",meaning:"湿った",breakdown:"ほどよい湿り気。damp はじめじめして不快な湿り気を指す"},
     {synonym:true,word:"wet",meaning:"ぬれた",breakdown:"水がついていること。damp は少し湿っている程度を指す"},
     {synonym:true,word:"humid",meaning:"（空気が）蒸し暑い",breakdown:"空気が湿っていること。damp は物が湿っていることにも使う"},
     {synonym:true,word:"moisture",meaning:"湿気",breakdown:"ふくまれる水け。damp はそれを帯びた状態を表す形容詞"}]},

  {id:1226,word:"path",partOfSpeech:"名詞",meaning:"小道，通り道",
   meanings:["名|小道，通り道","名|（進むべき）道すじ"],
   pronunciation:"/pæθ/",part:123,
   example:"A narrow path leads from the house to the river.",
   exampleJa:"細い小道が、家から川まで続いている。",
   example2:"We followed the steep mountain path for two hours.",
   exampleJa2:"私たちは2時間、険しい山の小道をたどった。",
   etymologyProcess:"paeth（踏み分け道）→ 人が歩いて踏み分けてできた細い道は…？",
   etymologyConclusion:"paeth（踏み分け道）→ 人が歩いて踏み分けてできた細い道＝小道",
   hook:"sympathy の path（感じる）とは同じつづりの別の語。",
   relatedWords:[
     {synonym:true,word:"trail",meaning:"山道；跡",breakdown:"引きずった跡からできた道。path は歩いて踏み分けた道"},
     {synonym:true,word:"track",meaning:"足跡；通り道",breakdown:"踏まれてできた跡。path は歩くための細い道を指す"},
     {synonym:true,word:"road",meaning:"道路",breakdown:"車の通る広い道。path は人が歩く細い道を指す"},
     {synonym:true,word:"lane",meaning:"小道，車線",breakdown:"区切られた細長い道。path は自然にできた細い道"}]},

  {id:1227,word:"trail",partOfSpeech:"名詞",meaning:"（山などの）小道；跡",
   meanings:["名|（山などの）小道","名|（通った）跡","他|引きずる；追跡する"],
   pronunciation:"/treɪl/",part:123,
   example:"The hiking trail goes all around the large lake.",
   exampleJa:"そのハイキングの小道は、大きな湖をぐるりと回っている。",
   example2:"The hunting dog followed the trail of the deer.",
   exampleJa2:"その猟犬は、シカの残した跡をたどった。",
   etymologyProcess:"trail（引きずる）→ 引きずった跡のように細く続く道は…？",
   etymologyConclusion:"trail（引きずる）→ 引きずった跡のように細く続いていく道＝山などの小道",
   hook:"もとの意味は「引きずる」。引きずった跡のように細く続く道が芯。",
   relatedWords:[
     {synonym:true,word:"path",meaning:"小道",breakdown:"歩いて踏み分けた道。trail は跡のように細く続く道を指す"},
     {synonym:true,word:"track",meaning:"足跡；通り道",breakdown:"踏まれてできた跡。trail は引きずった跡から生まれた道"},
     {synonym:true,word:"trace",meaning:"跡；たどる",breakdown:"かすかに残る印。trail は続いて残る跡や細い道を指す"},
     {synonym:true,word:"route",meaning:"道すじ",breakdown:"決められた通り道。trail は自然にできた細い山道を指す"}]},

  {id:1228,word:"stream",partOfSpeech:"名詞",meaning:"小川；流れ",
   meanings:["名|小川","名|（人・物の）流れ"],
   pronunciation:"/striːm/",part:123,
   example:"A clear stream runs behind my grandmother's old house.",
   exampleJa:"澄んだ小川が、祖母の古い家の裏を流れている。",
   example2:"A stream of people left the stadium after the game.",
   exampleJa2:"試合の後、人の流れが競技場を出ていった。",
   etymologyProcess:"stream（流れる）→ 絶えず流れ続けている細い水の筋は…？",
   etymologyConclusion:"stream（流れる）→ 絶えることなく流れ続けている細い水の筋＝小川",
   hook:"動画の「ストリーミング」も同じ。切れ目なく流れ続けるのが芯。",
   relatedWords:[
     {word:"streamline",meaning:"流線形にする；効率化する",breakdown:"stream（流れる）＋ line（線）→ 流れに沿った形にする"},
     {synonym:true,word:"river",meaning:"川",breakdown:"大きな川。stream はもっと細い流れを指す"},
     {synonym:true,word:"flow",meaning:"流れる",breakdown:"流れる動き。stream はその流れそのものを指す名詞"},
     {synonym:true,word:"current",meaning:"流れ，海流",breakdown:"水や空気の流れ。stream は地上を流れる細い川を指す"}]},

  {id:1229,word:"tide",partOfSpeech:"名詞",meaning:"潮（の満ち引き）",
   meanings:["名|潮（の満ち引き）","名|（世の）流れ，風潮"],
   pronunciation:"/taɪd/",part:123,
   example:"The tide comes in twice every single day here.",
   exampleJa:"ここでは、潮は毎日2回満ちてくる。",
   example2:"Fishermen always watch the tide before going out.",
   exampleJa2:"漁師たちは海へ出る前に、いつも潮を見る。",
   etymologyProcess:"tid（時）→ 決まった時刻ごとに満ち引きするものは…？",
   etymologyConclusion:"tid（時）→ 決まった時刻ごとに満ち引きしていく海の水＝潮",
   why:"【なぜ】古英語の tīd は「時・時刻」。海の水が決まった時刻に満ち引きすることから、その動きそのものを tide と呼ぶようになりました。\n【つながり】tidy（もとは「時にかなった」＝きちんとした）、tidings（その時々の知らせ）も同じ家族。time は遠い親戚です。Yuletide（クリスマスの時期）には「時」の意味が残っています。",
   relatedWords:[
     {word:"tidy",meaning:"きちんとした",breakdown:"tid（時）＋ y（形容詞）→ もとは「時にかなった」。そこから整った"},
     {word:"tidings",meaning:"知らせ，便り",breakdown:"tid（時）＋ ing（名詞）→ その時々に伝わってくる知らせ"},
     {synonym:true,word:"wave",meaning:"波",breakdown:"水面の上下。tide は1日の中で大きく満ち引きする動き"},
     {synonym:true,word:"current",meaning:"海流",breakdown:"水の流れ。tide は月の力で起こる満ち引きを指す"}]},

  {id:1230,word:"reef",partOfSpeech:"名詞",meaning:"礁（暗礁）",
   meanings:["名|礁（暗礁），岩礁"],
   pronunciation:"/riːf/",part:123,
   example:"Colorful fish swim around the coral reef near here.",
   exampleJa:"色とりどりの魚が、この近くのサンゴ礁のまわりを泳ぐ。",
   example2:"The old ship hit a reef near the small island.",
   exampleJa2:"その古い船は、小さな島の近くで暗礁に当たった。",
   etymologyProcess:"reef（海中の背）→ 海面近くまでせり上がった岩の高まりは…？",
   etymologyConclusion:"reef（海中の背）→ 海面近くまでせり上がった岩やサンゴの高まり＝礁",
   hook:"「コーラルリーフ（サンゴ礁）」でおなじみ。海中の背のような高まり。",
   relatedWords:[
     {synonym:true,word:"coral",meaning:"サンゴ",breakdown:"海の生き物。reef はそれが積み上がってできた高まりも指す"},
     {synonym:true,word:"rock",meaning:"岩",breakdown:"かたまりの岩。reef は海面近くに隠れた岩の連なり"},
     {synonym:true,word:"cliff",meaning:"がけ",breakdown:"陸の切り立った岩。reef は海中にひそむ岩の高まり"},
     {synonym:true,word:"shore",meaning:"岸，浜",breakdown:"陸と海の境。reef は海中にひそむ岩の連なりを指す"}]},

  {id:1231,word:"habitat",partOfSpeech:"名詞",meaning:"生息地",
   meanings:["名|（動植物の）生息地"],
   pronunciation:"/ˈhæbɪtæt/",part:124,
   example:"This forest is the habitat of many rare birds.",
   exampleJa:"この森は、多くの珍しい鳥の生息地だ。",
   example2:"Building new roads destroys the habitat of wild animals.",
   exampleJa2:"新しい道路を造ることは、野生動物の生息地を壊してしまう。",
   etymologyProcess:"habit（持ち続ける）→ その生き物が住み続けている場所は…？",
   etymologyConclusion:"habit（持ち続ける）→ その生き物がずっと住み続けている場所＝生息地",
   relatedWords:[
     {word:"habit",meaning:"習慣",breakdown:"habit（持ち続ける）→ ずっと持ち続けているふるまい方"},
     {word:"inhabit",meaning:"住む",breakdown:"in（中に）＋ habit（持ち続ける）→ その中に住み続ける"},
     {word:"inhabitant",meaning:"住民",breakdown:"in（中に）＋ habit（持ち続ける）＋ ant（人）→ そこに住み続ける人"},
     {word:"habitual",meaning:"習慣的な",breakdown:"habit（持ち続ける）＋ al（形容詞）→ 習慣として続いている"}]},

  {id:1232,word:"volcano",partOfSpeech:"名詞",meaning:"火山",
   meanings:["名|火山"],
   pronunciation:"/vɑːlˈkeɪnoʊ/",part:124,
   example:"The old volcano has not erupted for many centuries.",
   exampleJa:"その古い火山は、何世紀もの間噴火していない。",
   example2:"Many hot springs lie near this sleeping volcano.",
   exampleJa2:"多くの温泉が、この眠っている火山の近くにある。",
   etymologyProcess:"vulcan（火の神）→ 神が地下で働く仕事場と考えられた山は…？",
   etymologyConclusion:"vulcan（火の神）→ 火の神が働く仕事場と考えられた、火を噴く山＝火山",
   why:"【なぜ】ローマ神話の火と鍛冶の神ウルカーヌス（Vulcan）から。シチリア島の火を噴く山を、神が地下で鉄を打つ仕事場だと考えたことから volcano になりました。\n【つながり】ゴムを固くする加硫（vulcanize）も、同じ神の名から来ています。",
   relatedWords:[
     {synonym:true,word:"mountain",meaning:"山",breakdown:"高くそびえる山。volcano は火を噴く山だけを指す"},
     {word:"vulcanize",meaning:"（ゴムを）加硫する",breakdown:"vulcan（火の神）＋ ize（動詞）→ 火の力でゴムを固くする"},
     {synonym:true,word:"lava",meaning:"溶岩",breakdown:"流れ出る熱い岩。volcano はそれを噴き出す山を指す"},
     {synonym:true,word:"crater",meaning:"噴火口",breakdown:"山頂に開いた大きな穴。volcano は山ぜんたいを指す"}]},

  {id:1233,word:"mine",partOfSpeech:"名詞",meaning:"鉱山",
   meanings:["名|鉱山，坑道","他|採掘する"],
   pronunciation:"/maɪn/",part:124,
   example:"The old coal mine closed down about fifty years ago.",
   exampleJa:"その古い炭鉱は、およそ50年前に閉鎖された。",
   example2:"Workers dig deep into the mine every single morning.",
   exampleJa2:"作業員たちは毎朝、鉱山の奥深くまで掘り進む。",
   etymologyProcess:"mine（鉱石を掘る）→ 地中を掘って鉱石を取り出す場所は…？",
   etymologyConclusion:"mine（鉱石を掘る）→ 地中を掘って鉱石を取り出すための場所＝鉱山",
   hook:"「私のもの」の mine とは別の語。掘り出す場所であるのが芯。",
   relatedWords:[
     {word:"miner",meaning:"鉱夫",breakdown:"mine（鉱石を掘る）＋ er（人）→ 坑道で鉱石を掘り出す人"},
     {synonym:true,word:"dig",meaning:"掘る",breakdown:"土を掘ること。mine は鉱石を掘り出す場所や作業を指す"},
     {synonym:true,word:"cave",meaning:"洞穴",breakdown:"自然にできた穴。mine は人が掘って作った坑道を指す"},
     {synonym:true,word:"tunnel",meaning:"トンネル",breakdown:"通り抜けるための穴。mine は鉱石を取るための穴"}]},

  {id:1234,word:"swallow",partOfSpeech:"名詞",meaning:"ツバメ",
   meanings:["名|ツバメ","他|（同じつづりの別語で）飲み込む"],
   pronunciation:"/ˈswɑːloʊ/",part:124,
   example:"Swallows build their small nests under our house roof.",
   exampleJa:"ツバメは、私たちの家の屋根の下に小さな巣を作る。",
   example2:"A swallow flew low over the wet green rice field.",
   exampleJa2:"1羽のツバメが、ぬれた緑の田の上を低く飛んだ。",
   etymologyProcess:"swallow（飛びかう小鳥）→ 春に低く飛びかう尾の分かれた小鳥は…？",
   etymologyConclusion:"swallow（飛びかう小鳥）→ 春に低く飛びかう、尾の分かれた小鳥＝ツバメ",
   hook:"「飲み込む」の swallow とは、もともと別の語。つづりが同じだけ。",
   relatedWords:[
     {synonym:true,word:"bird",meaning:"鳥",breakdown:"鳥ぜんたい。swallow はその中の一種、ツバメを指す"},
     {synonym:true,word:"nest",meaning:"巣",breakdown:"鳥の住みか。swallow は軒下に巣を作る鳥として知られる"},
     {synonym:true,word:"sparrow",meaning:"スズメ",breakdown:"身近な小鳥。swallow は尾が分かれ、速く飛ぶ渡り鳥"},
     {synonym:true,word:"migrate",meaning:"渡る，移住する",breakdown:"季節ごとに移ること。swallow はそれをする代表的な鳥"}]},

  {id:1235,word:"web",partOfSpeech:"名詞",meaning:"クモの巣",
   meanings:["名|クモの巣","名|（the Web で）ウェブ"],
   pronunciation:"/web/",part:124,
   example:"A spider web hung between the two old branches.",
   exampleJa:"クモの巣が、2本の古い枝の間に張られていた。",
   example2:"Dew shone on the web early in the cold morning.",
   exampleJa2:"寒い朝早く、クモの巣に露が光っていた。",
   etymologyProcess:"web（網）→ 細い糸を編んで張りめぐらせたものは…？",
   etymologyConclusion:"web（網）→ 細い糸を編んで張りめぐらせた網＝クモの巣",
   relatedWords:[
     {word:"weave",meaning:"織る，編む",breakdown:"web（網）→ 糸を交差させて編み上げていく"},
     {synonym:true,word:"net",meaning:"網",breakdown:"糸を編んだ網。web はクモが張る細い網を指す"},
     {synonym:true,word:"spider",meaning:"クモ",breakdown:"web を張る虫。web はその張られた網のほうを指す"},
     {synonym:true,word:"thread",meaning:"糸",breakdown:"細い糸。web はそれを編んで作られた網のこと"}]},

  {id:1236,word:"mosquito",partOfSpeech:"名詞",meaning:"蚊",
   meanings:["名|蚊"],
   pronunciation:"/məˈskiːtoʊ/",part:124,
   example:"A mosquito bit my arm during the summer camp.",
   exampleJa:"夏のキャンプの間、蚊が私の腕を刺した。",
   example2:"Mosquitoes spread serious diseases in some warm countries.",
   exampleJa2:"蚊は、いくつかの暖かい国で重い病気を広める。",
   etymologyProcess:"mosc（ハエ）→ ハエを小さくしたような、血を吸う虫は…？",
   etymologyConclusion:"mosc（ハエ）→ ハエを小さくしたような、血を吸う小さな虫＝蚊",
   hook:"スペイン語の mosca（ハエ）＋ -ito（小さい）。「小バエ」が語源。",
   relatedWords:[
     {synonym:true,word:"fly",meaning:"ハエ",breakdown:"mosquito のもとになった虫。mosquito は血を吸う小さな虫"},
     {synonym:true,word:"insect",meaning:"昆虫",breakdown:"虫ぜんたい。mosquito はその中の血を吸う一種"},
     {synonym:true,word:"bite",meaning:"かむ，刺す",breakdown:"蚊に刺されることは英語で bite と言う。mosquito はその虫"},
     {synonym:true,word:"itch",meaning:"かゆい",breakdown:"刺された後の感じ。mosquito はそれを起こす虫を指す"}]},

  {id:1237,word:"cattle",partOfSpeech:"名詞",meaning:"（家畜の）ウシ",
   meanings:["名|（家畜の）ウシ，牛の群れ"],
   pronunciation:"/ˈkætl/",part:124,
   example:"The farmer keeps fifty cattle on his wide land.",
   exampleJa:"その農家は、広い土地で50頭のウシを飼っている。",
   example2:"Cattle graze quietly in the green spring field.",
   exampleJa2:"ウシたちが、緑の春の野原で静かに草を食べている。",
   etymologyProcess:"capit（頭）→ 昔、財産を頭数で数えた代表の家畜は…？",
   etymologyConclusion:"capit（頭）→ 昔は財産を頭数で数えた、その代表となる家畜＝ウシ",
   why:"【なぜ】ラテン語 capitale は「頭数で数える財産」。中世では家畜が最大の財産で、なかでもウシを指すようになりました。\n【つながり】capital（資本・首都）、chapter（章）も caput（頭）の家族。日本語でも牛を「1頭」と数えます。",
   relatedWords:[
     {word:"capital",meaning:"首都；資本",breakdown:"capit（頭）＋ al（形容詞）→ 国の頭にあたる町、元手となる頭金"},
     {word:"chapter",meaning:"章",breakdown:"chapt（頭）＋ er（もの）→ 本の各部分の頭にあたる見出し"},
     {word:"captain",meaning:"主将，船長",breakdown:"capt（頭）＋ ain（人）→ 集団の頭に立つ人"},
     {synonym:true,word:"livestock",meaning:"家畜",breakdown:"飼われる動物ぜんたい。cattle は特にウシの群れを指す"}]},

  {id:1238,word:"kitten",partOfSpeech:"名詞",meaning:"子ネコ",
   meanings:["名|子ネコ"],
   pronunciation:"/ˈkɪtn/",part:124,
   example:"The small kitten slept quietly on my warm lap.",
   exampleJa:"その小さな子ネコは、私の温かいひざで静かに眠った。",
   example2:"Our cat had four healthy kittens last warm spring.",
   exampleJa2:"うちのネコは、昨年の暖かい春に4匹の元気な子ネコを産んだ。",
   etymologyProcess:"kitten（小さいネコ）→ まだ育ちきっていないネコの子は…？",
   etymologyConclusion:"kitten（小さいネコ）→ まだ育ちきっていない、小さなネコの子＝子ネコ",
   hook:"古フランス語 chat（ネコ）の「小さいほう」の形から。puppy と対で覚える。",
   relatedWords:[
     {synonym:true,word:"cat",meaning:"ネコ",breakdown:"大人のネコ。kitten はまだ小さいその子どもを指す"},
     {synonym:true,word:"puppy",meaning:"子イヌ",breakdown:"イヌの子ども。kitten はネコの子どもを指す"},
     {synonym:true,word:"pet",meaning:"ペット",breakdown:"飼われる動物。kitten はその代表のひとつ"},
     {synonym:true,word:"cub",meaning:"（クマなどの）子",breakdown:"野生動物の子。kitten はネコの子に限って使う"}]},

  {id:1239,word:"organism",partOfSpeech:"名詞",meaning:"生物，有機体",
   meanings:["名|生物，有機体"],
   pronunciation:"/ˈɔːrɡənɪzəm/",part:124,
   example:"Every living organism needs water to survive and grow.",
   exampleJa:"あらゆる生物は、生き延びて育つために水を必要とする。",
   example2:"Scientists found tiny organisms deep in the dark sea.",
   exampleJa2:"科学者たちは、暗い海の深くで小さな生物を見つけた。",
   etymologyProcess:"organ（道具・器官）→ いくつもの器官が組み合わさって生きていると…？",
   etymologyConclusion:"organ（道具・器官）→ いくつもの器官が組み合わさって生きているもの＝生物",
   relatedWords:[
     {word:"organ",meaning:"臓器，器官",breakdown:"organ（道具・器官）→ 体の中で決まった働きをする部分"},
     {word:"organize",meaning:"まとめる，準備する",breakdown:"organ（道具・器官）＋ ize（動詞）→ 器官のようにきちんと働く形にする"},
     {word:"organic",meaning:"有機の；オーガニックの",breakdown:"organ（道具・器官）＋ ic（形容詞）→ 生き物の器官に関わる"},
     {word:"organization",meaning:"組織，団体",breakdown:"organ（道具・器官）＋ ation（名詞）→ 役割を分けて動く集まり"}]},

  {id:1240,word:"wildlife",partOfSpeech:"名詞",meaning:"野生生物",
   meanings:["名|野生生物"],
   pronunciation:"/ˈwaɪldlaɪf/",part:124,
   example:"This national park protects the wildlife of the area.",
   exampleJa:"この国立公園は、その地域の野生生物を守っている。",
   example2:"Climate change threatens wildlife all around the world.",
   exampleJa2:"気候変動は、世界中の野生生物を脅かしている。",
   etymologyProcess:"wild（野生の）＋ life（命）→ 人に飼われず自然の中で生きる命は…？",
   etymologyConclusion:"wild（野生の）＋ life（命）→ 人に飼われず、自然の中で生きている命＝野生生物",
   relatedWords:[
     {word:"wild",meaning:"野生の；荒々しい",breakdown:"wild（野生の）→ 人の手がまったく入っていない"},
     {word:"wilderness",meaning:"荒野",breakdown:"wild（野生の）＋ ness（名詞）→ 人の手の入らない広い土地"},
     {word:"life",meaning:"命，生活",breakdown:"life（命）→ 生きているということそのもの"},
     {word:"lifetime",meaning:"一生",breakdown:"life（命）＋ time（時間の区切り）→ 命のある間ぜんたい"}]},

  {id:1241,word:"beast",partOfSpeech:"名詞",meaning:"野獣，けもの",
   meanings:["名|野獣，けもの"],
   pronunciation:"/biːst/",part:125,
   example:"A wild beast lived deep in that dark old forest.",
   exampleJa:"1頭の野獣が、その暗い古い森の奥深くに住んでいた。",
   example2:"The old story tells about a beast and a princess.",
   exampleJa2:"その古い物語は、野獣と王女について語っている。",
   etymologyProcess:"besti（けもの）→ 人と違って理性を持たない荒々しい獣は…？",
   etymologyConclusion:"besti（けもの）→ 人と違って理性を持たない、荒々しい獣＝野獣",
   relatedWords:[
     {word:"bestial",meaning:"けもののような",breakdown:"besti（けもの）＋ al（形容詞）→ けもののように荒々しい"},
     {synonym:true,word:"animal",meaning:"動物",breakdown:"動物ぜんたい。beast は大きく荒々しい獣を指す"},
     {synonym:true,word:"monster",meaning:"怪物",breakdown:"想像上の恐ろしい生き物。beast は実在の荒々しい獣"},
     {synonym:true,word:"creature",meaning:"生き物",breakdown:"生き物ぜんたい。beast は人に対して「けもの」を指す"}]},

  {id:1242,word:"ape",partOfSpeech:"名詞",meaning:"類人猿",
   meanings:["名|類人猿（尾のない大きな猿）","他|まねる"],
   pronunciation:"/eɪp/",part:125,
   example:"Great apes share much of their DNA with humans.",
   exampleJa:"大型の類人猿は、DNAの多くを人間と共有している。",
   example2:"The zoo keeps two apes in a large open area.",
   exampleJa2:"その動物園は、広い開けた場所で2頭の類人猿を飼っている。",
   etymologyProcess:"ape（人に似た猿）→ 尾がなく人に近い姿をした大きな猿は…？",
   etymologyConclusion:"ape（人に似た猿）→ 尾がなく、人に近い姿をした大きな猿＝類人猿",
   hook:"語源ははっきりしない。動詞の ape は「人まねをする」。",
   relatedWords:[
     {synonym:true,word:"monkey",meaning:"サル",breakdown:"尾のあるサル。ape は尾がなく、人に近い大型の猿"},
     {synonym:true,word:"gorilla",meaning:"ゴリラ",breakdown:"ape の代表的な一種。ape はその仲間ぜんたいを指す"},
     {synonym:true,word:"primate",meaning:"霊長類",breakdown:"サルや人を含む大きな分類。ape はその中の類人猿"},
     {synonym:true,word:"human",meaning:"人間",breakdown:"ape といちばん近い生き物。ape は人以外の類人猿を指す"}]},

  {id:1243,word:"flock",partOfSpeech:"名詞",meaning:"（鳥・羊の）群れ",
   meanings:["名|（鳥・羊の）群れ","自|群がる"],
   pronunciation:"/flɑːk/",part:125,
   example:"A large flock of birds flew over the wide field.",
   exampleJa:"大きな鳥の群れが、広い野原の上を飛んでいった。",
   example2:"The farmer moved his flock to the higher green hill.",
   exampleJa2:"その農家は、羊の群れをより高い緑の丘へ移した。",
   etymologyProcess:"flock（ひとかたまりの集まり）→ 鳥や羊が寄り集まってひとまとまりになると…？",
   etymologyConclusion:"flock（ひとかたまりの集まり）→ 鳥や羊が寄り集まったひとかたまり＝群れ",
   hook:"鳥や羊に使う「群れ」。牛や馬の群れは herd と使い分ける。",
   relatedWords:[
     {synonym:true,word:"herd",meaning:"（牛・馬の）群れ",breakdown:"大型の家畜の群れ。flock は鳥や羊の群れに使う"},
     {synonym:true,word:"crowd",meaning:"人ごみ",breakdown:"人の集まり。flock は動物のひとかたまりを指す"},
     {synonym:true,word:"group",meaning:"集団",breakdown:"まとまりぜんたい。flock は自然に寄り集まった動物の群れ"},
     {synonym:true,word:"swarm",meaning:"（虫の）群れ",breakdown:"虫の大群。flock は鳥や羊のひとかたまりを指す"}]},

  {id:1244,word:"vein",partOfSpeech:"名詞",meaning:"静脈",
   meanings:["名|静脈","名|（葉の）葉脈"],
   pronunciation:"/veɪn/",part:125,
   example:"Blood returns to the heart through these thin veins.",
   exampleJa:"血は、これらの細い静脈を通って心臓へ戻る。",
   example2:"You can see blue veins under her pale thin skin.",
   exampleJa2:"彼女の青白い薄い肌の下に、青い静脈が見える。",
   etymologyProcess:"vena（血管）→ 体のすみから心臓へ血を運び戻す管は…？",
   etymologyConclusion:"vena（血管）→ 体のすみずみから心臓へ血を運び戻していく管＝静脈",
   hook:"ラテン語 vena（血管）から。葉の「葉脈」も英語では vein。",
   relatedWords:[
     {synonym:true,word:"artery",meaning:"動脈",breakdown:"vein と対になる管。心臓から血を送り出すほうを指す"},
     {synonym:true,word:"blood",meaning:"血",breakdown:"体をめぐる赤い液。vein はそれが通る管を指す"},
     {synonym:true,word:"vessel",meaning:"管；血管",breakdown:"液の通る管。vein はそのうち心臓へ戻る血の管"},
     {synonym:true,word:"nerve",meaning:"神経",breakdown:"体に信号を伝える筋。vein は血を運ぶ管のほうを指す"}]},

  {id:1245,word:"breed",partOfSpeech:"自動詞",meaning:"（動物が）繁殖する",
   meanings:["自|（動物が）繁殖する","他|（家畜など）を育てて増やす","名|品種"],
   pronunciation:"/briːd/",part:125,
   example:"These water birds breed near the river every spring.",
   exampleJa:"これらの水鳥は毎年春、川の近くで繁殖する。",
   example2:"The farm breeds horses for local riding schools.",
   exampleJa2:"その農場は、地元の乗馬学校のために馬を育てて増やしている。",
   etymologyProcess:"breed（温めて育てる）→ 卵や子を温めて育て、数を増やすと…？",
   etymologyConclusion:"breed（温めて育てる）→ 卵や子を温めて育て、仲間の数を増やす＝繁殖する",
   relatedWords:[
     {word:"brood",meaning:"ひと腹のひな；思い悩む",breakdown:"breed（温めて育てる）→ 親が温めて育てるひとかたまりのひな"},
     {synonym:true,word:"reproduce",meaning:"子孫を残す",breakdown:"子をつくること。breed は人が育てて増やす場合にも使う"},
     {synonym:true,word:"raise",meaning:"育てる",breakdown:"育て上げること。breed は子を産ませて増やすことを言う"},
     {synonym:true,word:"hatch",meaning:"かえる，孵化する",breakdown:"卵がかえること。breed はその前後を含めて数を増やすこと"}]},

  {id:1246,word:"reproduce",partOfSpeech:"自動詞",meaning:"子孫を残す；複製する",
   meanings:["自|子孫を残す，繁殖する","他|複製する，再現する"],
   pronunciation:"/ˌriːprəˈduːs/",part:125,
   example:"Most fish reproduce by laying many very small eggs.",
   exampleJa:"ほとんどの魚は、たくさんのとても小さな卵を産んで子孫を残す。",
   example2:"This new printer reproduces photo colors very clearly.",
   exampleJa2:"この新しいプリンターは、写真の色をとても鮮明に複製する。",
   etymologyProcess:"re（再び）＋ duc（導く）→ 同じ命をもう一度この世へ導き出すと…？",
   etymologyConclusion:"re（再び）＋ duc（導く）→ 同じ命をもう一度この世へ導き出す＝子孫を残す",
   relatedWords:[
     {word:"produce",meaning:"生産する",breakdown:"pro（前へ）＋ duc（導く）→ 前へ導き出して作り出す"},
     {word:"introduce",meaning:"紹介する；導入する",breakdown:"intro（中へ）＋ duc（導く）→ 中へ導き入れる"},
     {word:"conduct",meaning:"行う；指揮する",breakdown:"con（共に）＋ duc（導く）→ 共に導いて進めていく"},
     {word:"educate",meaning:"教育する",breakdown:"e（外へ）＋ duc（導く）→ 内にある力を外へ導き出す"}]},

  {id:1247,word:"talkative",partOfSpeech:"形容詞",meaning:"おしゃべりの",
   meanings:["形|おしゃべりの，話好きの"],
   pronunciation:"/ˈtɔːkətɪv/",part:125,
   example:"My little brother is very talkative at the dinner table.",
   exampleJa:"弟は、夕食の食卓でとてもおしゃべりだ。",
   example2:"The talkative guide told us many funny old stories.",
   exampleJa2:"そのおしゃべりな案内人は、面白い昔話をたくさん聞かせてくれた。",
   etymologyProcess:"tal（語る）＋ ive（形容詞）→ 語ることが好きでよくしゃべると…？",
   etymologyConclusion:"tal（語る）＋ ive（形容詞）→ 語ることが好きで、よくしゃべる＝おしゃべりの",
   relatedWords:[
     {word:"talk",meaning:"話す",breakdown:"tal（語る）→ 言葉をやりとりして話す"},
     {word:"tale",meaning:"物語",breakdown:"tal（語る）→ 語り伝えられてきたひとまとまりの話"},
     {word:"tell",meaning:"話す，伝える",breakdown:"tal（語る）→ 順を追って言葉で伝える"},
     {synonym:true,word:"chatty",meaning:"おしゃべりな",breakdown:"くだけた語。talkative は少し硬く、書き言葉でも使う"}]},

  {id:1248,word:"earnest",partOfSpeech:"形容詞",meaning:"真剣な，真面目な",
   meanings:["形|真剣な，真面目な"],
   pronunciation:"/ˈɜːrnɪst/",part:125,
   example:"She made an earnest effort to help her old friend.",
   exampleJa:"彼女は古い友人を助けようと、真剣な努力をした。",
   example2:"His earnest face showed how much he really cared.",
   exampleJa2:"彼の真剣な顔が、どれほど本気で気にかけているかを示していた。",
   etymologyProcess:"earnest（本気）→ ふざけずに本気で物事に向き合うと…？",
   etymologyConclusion:"earnest（本気）→ ふざけずに、本気で物事に向き合っている＝真剣な",
   hook:"earn（稼ぐ）とは別の語。in earnest（本格的に）の形でも使う。",
   relatedWords:[
     {synonym:true,word:"serious",meaning:"真剣な",breakdown:"まじめであること。earnest は熱意のこもった真剣さを指す"},
     {synonym:true,word:"sincere",meaning:"誠実な",breakdown:"うそがないこと。earnest は本気で打ち込む態度を指す"},
     {synonym:true,word:"eager",meaning:"熱心な",breakdown:"やりたくてたまらないこと。earnest は落ち着いた真剣さ"},
     {synonym:true,word:"honest",meaning:"正直な",breakdown:"うそをつかないこと。earnest は本気さのほうを表す"}]},

  {id:1249,word:"diligent",partOfSpeech:"形容詞",meaning:"勤勉な",
   meanings:["形|勤勉な，こつこつ努力する"],
   pronunciation:"/ˈdɪlɪdʒənt/",part:125,
   example:"He is a diligent student of the Chinese language.",
   exampleJa:"彼は、中国語の勤勉な学習者だ。",
   example2:"Diligent practice slowly turned her into a fine pianist.",
   exampleJa2:"勤勉な練習が、彼女をゆっくり立派なピアニストに変えた。",
   etymologyProcess:"dilig（心をこめる）→ 一つの仕事にこつこつ打ち込んでいくと…？",
   etymologyConclusion:"dilig（心をこめる）→ 一つの仕事に心をこめて、こつこつ打ち込む＝勤勉な",
   why:"【なぜ】ラテン語 diligere は dis（より分けて）＋ legere（選ぶ）で、「えり好んで大事にする・愛する」。愛するほど心をこめて取り組むことから「勤勉な」になりました。\n【つながり】select（より分けて選ぶ）、collect（拾い集める）も legere の家族です。",
   relatedWords:[
     {word:"diligence",meaning:"勤勉さ",breakdown:"dilig（心をこめる）＋ ence（名詞）→ 心をこめて打ち込むこと"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離して）＋ lect（拾う）→ より分けて拾い上げる"},
     {word:"collect",meaning:"集める",breakdown:"col（共に）＋ lect（拾う）→ 一か所へ拾い集める"},
     {synonym:true,word:"hardworking",meaning:"よく働く",breakdown:"よく働くこと。diligent はこつこつ続ける真面目さを指す"}]},

  {id:1250,word:"principal",partOfSpeech:"形容詞",meaning:"主要な，いちばん大事な",
   meanings:["形|主要な，いちばん大事な","名|校長"],
   pronunciation:"/ˈprɪnsəpl/",part:125,
   example:"Rice is the principal food in many Asian countries.",
   exampleJa:"米は、多くのアジアの国で主要な食べ物だ。",
   example2:"Our school principal spoke at the graduation ceremony yesterday.",
   exampleJa2:"私たちの学校の校長が、昨日の卒業式で話した。",
   etymologyProcess:"princip（第一の）＋ al（形容詞）→ 他より先に来ていちばん大事だと…？",
   etymologyConclusion:"princip（第一の）＋ al（形容詞）→ 他より先に来る、いちばん大事な＝主要な",
   why:"【なぜ】ラテン語 princeps は「第一の位にある者」。そこから「いちばん大事な」という形容詞になり、学校で第一の立場にある人＝校長も principal と呼ぶようになりました。\n【つながり】つづりの似た principle（原則）は「もとになる考え」。-pal なら「主要な・校長」、-ple なら「原則」と覚えます。",
   relatedWords:[
     {word:"principle",meaning:"原理，原則",breakdown:"princip（第一の）→ いちばん初めに置かれ、すべてのもとになる考え"},
     {word:"prince",meaning:"王子",breakdown:"prim（第一の）＋ cept（取る）→ 国で第一の地位を取る者"},
     {synonym:true,word:"main",meaning:"主な",breakdown:"いちばん大きいもの。principal は「第一に来る」ことを言う"},
     {synonym:true,word:"chief",meaning:"主要な；長",breakdown:"頭に立つもの。principal は順位の第一にあたることを言う"}]},
