  {id:551,word:"attach",partOfSpeech:"他動詞",meaning:"くっつける；添付する",
   meanings:["他|くっつける，取り付ける","他|（メールに）添付する"],
   pronunciation:"/əˈtætʃ/",part:56,
   example:"Please attach a recent photo to your application form.",
   exampleJa:"申込用紙に最近の写真をくっつけてください。",
   example2:"She attached a short note to the present for her friend.",
   exampleJa2:"彼女は友達へのプレゼントに短いメモをくっつけた。",
   etymologyProcess:"ad（〜へ）＋ tach（杭で留める）→ 相手のほうへ杭で留めると…？",
   etymologyConclusion:"ad（〜へ）＋ tach（杭で留める）→ 相手のほうへ杭を打ち込んでぴたりと留める＝くっつける",
   relatedWords:[
     {word:"detach",meaning:"取り外す",breakdown:"de（離して）＋ tach（杭で留める）→ 打った杭を抜いて切り離す"},
     {word:"attack",meaning:"攻撃する",breakdown:"ad（〜へ）＋ tack（杭で留める）→ 相手へ杭を打ち込むように襲いかかる"},
     {word:"attachment",meaning:"添付書類；愛着",breakdown:"ad（〜へ）＋ tach（杭で留める）＋ ment（名詞）→ 留めて離れないもの"},
     {synonym:true,word:"glue",meaning:"接着剤；のりで貼る",breakdown:"のりで面と面を貼る。attach は書類や部品を「留める」感じ"}]},

  {id:552,word:"connect",partOfSpeech:"他動詞・自動詞",meaning:"つなげる；乗り継ぐ",
   meanings:["他|（二つのものを）つなげる","自|（電車などが）連絡する"],
   pronunciation:"/kəˈnekt/",part:56,
   example:"This new bridge connects the island to the main city.",
   exampleJa:"この新しい橋が、その島を中心の町につなげている。",
   example2:"I connected my tablet to the classroom speaker before the show.",
   exampleJa2:"発表の前に、私はタブレットを教室のスピーカーにつなげた。",
   etymologyProcess:"con（共に）＋ nect（結ぶ）→ 離れた二つを一本に結ぶと…？",
   etymologyConclusion:"con（共に）＋ nect（結ぶ）→ 離れた二つを一本の糸で結び合わせる＝つなげる",
   relatedWords:[
     {word:"connection",meaning:"つながり，関係",breakdown:"con（共に）＋ nect（結ぶ）＋ ion（名詞）→ 結ばれてできたつながり"},
     {word:"disconnect",meaning:"接続を切る",breakdown:"dis（否定）＋ con（共に）＋ nect（結ぶ）→ 結んだ糸をほどいて切る"},
     {synonym:true,word:"join",meaning:"結び合わせる；加わる",breakdown:"二つを合わせて一つにする。connect は線や道で結ぶ感じ"},
     {synonym:true,word:"link",meaning:"関連づける；つながり",breakdown:"鎖の輪のようにつなぐ。connect より「関連」に重きがある"}]},

  {id:553,word:"relate",partOfSpeech:"他動詞",meaning:"関連づける；語って聞かせる",
   meanings:["他|（二つのことを）関連づける","他|（体験などを）語って聞かせる"],
   pronunciation:"/rɪˈleɪt/",part:56,
   example:"Scientists relate the rise in sea level to warmer oceans.",
   exampleJa:"科学者は海面の上昇を、海水温の上昇と関連づけている。",
   example2:"He related his long trip to India at the school festival.",
   exampleJa2:"彼は文化祭で、インドへの長い旅を語って聞かせた。",
   etymologyProcess:"re（戻す）＋ lat（運ぶ）→ 元へ運び戻して重ね合わせると…？",
   etymologyConclusion:"re（戻す）＋ lat（運ぶ）→ 話を元へ運び戻して別のことと重ね合わせる＝関連づける",
   relatedWords:[
     {word:"relation",meaning:"関係，間柄",breakdown:"re（戻す）＋ lat（運ぶ）＋ ion（名詞）→ 運び戻して生まれたつながり"},
     {word:"translate",meaning:"翻訳する",breakdown:"trans（越えて）＋ lat（運ぶ）→ 言葉を別の言語へ運び越す"},
     {word:"transfer",meaning:"移す；乗り換える",breakdown:"trans（越えて）＋ fer（運ぶ）→ 別の場所へ運び越して渡す"},
     {synonym:true,word:"compare",meaning:"比べる",breakdown:"二つを並べて違いを見る。relate は両者を結びつけて考える"}]},

  {id:554,word:"associate",partOfSpeech:"他動詞",meaning:"連想する；仲間として付き合う",
   meanings:["他|（あるものから）連想する","自|仲間として付き合う"],
   pronunciation:"/əˈsoʊsieɪt/",part:56,
   example:"Many people associate the smell of curry with summer camp.",
   exampleJa:"多くの人は、カレーのにおいから夏のキャンプを連想する。",
   example2:"I always associated that song with my last day of junior high.",
   exampleJa2:"私はいつもその歌から中学の最後の日を連想していた。",
   etymologyProcess:"ad（〜へ）＋ soci（仲間）＋ ate（動詞）→ 仲間のほうへ引き寄せると…？",
   etymologyConclusion:"ad（〜へ）＋ soci（仲間）＋ ate（動詞）→ あるものを仲間のほうへ引き寄せて結ぶ＝連想する",
   relatedWords:[
     {word:"social",meaning:"社会の；社交的な",breakdown:"soci（仲間）＋ al（〜の）→ 人が仲間として集まっているようす"},
     {word:"society",meaning:"社会",breakdown:"soci（仲間）＋ ty（名詞）→ 仲間として寄り集まってできた大きな輪"},
     {word:"association",meaning:"協会；連想",breakdown:"ad（〜へ）＋ soci（仲間）＋ ation（名詞）→ 仲間として結びついた集まり"},
     {synonym:true,word:"remind",meaning:"思い出させる",breakdown:"相手の記憶を呼び起こす。associate は自分の頭の中で結ぶ"}]},

  {id:555,word:"stick",partOfSpeech:"他動詞・自動詞",meaning:"貼り付ける；突き刺す",
   meanings:["他|貼り付ける，くっつける","他|突き刺す","自|くっついて離れない"],
   pronunciation:"/stɪk/",part:56,
   example:"Don't stick your gum under the desk in the classroom.",
   exampleJa:"教室の机の下にガムを貼り付けてはいけない。",
   example2:"She sticks a yellow memo on the fridge every single morning.",
   exampleJa2:"彼女は毎朝、冷蔵庫に黄色いメモを貼り付ける。",
   hook:"「刺す」と「くっつく」は1本の線。stick to ～ は「～をやり通す」。",
   etymologyProcess:"stick（突き刺す）→ 先を刺したようにぴたりと離れないのは…？",
   etymologyConclusion:"stick（突き刺す）→ 先を突き刺すようにぴたりと当てて離さない＝貼り付ける",
   relatedWords:[
     {word:"sticky",meaning:"ねばねばした",breakdown:"stick（突き刺す）＋ y（〜な状態の）→ 触ると刺さったように離れない"},
     {synonym:true,word:"attach",meaning:"くっつける",breakdown:"部品や書類をきちんと留める。stick はぺたっと貼る感じ"},
     {synonym:true,word:"paste",meaning:"のりで貼る",breakdown:"のりを塗って貼り付ける。stick は素材を選ばず広く使える"},
     {synonym:true,word:"pin",meaning:"ピンで留める",breakdown:"針で刺して留める。stick の「刺す」がそのまま道具になった語"}]},

  {id:556,word:"thief",partOfSpeech:"名詞",meaning:"泥棒，こそ泥",
   meanings:["名|泥棒，こそ泥"],
   pronunciation:"/θiːf/",part:56,
   example:"A thief took her wallet while she was reading a book.",
   exampleJa:"彼女が本を読んでいる間に、泥棒が財布を持っていった。",
   example2:"The police finally caught the thief who entered our school.",
   exampleJa2:"警察はついに、うちの学校に入った泥棒を捕まえた。",
   etymologyProcess:"thief（こっそり奪う者）→ 人目を盗んでそっと持ち去るのは…？",
   etymologyConclusion:"thief（こっそり奪う者）→ 人の目を盗んで音もなく物を持ち去る人＝泥棒",
   relatedWords:[
     {word:"theft",meaning:"窃盗",breakdown:"thef（こっそり奪う）＋ t（名詞）→ こっそり持ち去るという行いそのもの"},
     {synonym:true,word:"steal",meaning:"盗む",breakdown:"物をこっそり持ち去る動作。thief はそれをする人"},
     {synonym:true,word:"rob",meaning:"（人から）奪う",breakdown:"人や店から力ずくで奪う。steal は気づかれずに持ち去る"},
     {synonym:true,word:"burglar",meaning:"押し込み強盗",breakdown:"建物に忍び込む泥棒。thief は盗む人全般を指す"}]},

  {id:557,word:"crime",partOfSpeech:"名詞",meaning:"犯罪，罪",
   meanings:["名|犯罪，罪"],
   pronunciation:"/kraɪm/",part:56,
   example:"Stealing a bicycle is a crime, even if it looks old.",
   exampleJa:"自転車を盗むのは、古く見えても犯罪だ。",
   example2:"The number of crimes in this quiet town has fallen sharply.",
   exampleJa2:"この静かな町の犯罪の数は、大きく減っている。",
   etymologyProcess:"crim（罪に問う）→ 法にふれて人前に引き出される行いは…？",
   etymologyConclusion:"crim（罪に問う）→ 法にふれたとして人の前に引き出される行い＝犯罪",
   relatedWords:[
     {word:"criminal",meaning:"犯人；犯罪の",breakdown:"crim（罪に問う）＋ al（〜の）→ 罪に問われる側に立つ人"},
     {synonym:true,word:"offense",meaning:"違反，罪",breakdown:"規則にぶつかって傷つける行い。crime より軽い違反も含む"},
     {synonym:true,word:"sin",meaning:"（宗教上の）罪",breakdown:"神の教えにそむく罪。crime は国の法にそむく罪"},
     {synonym:true,word:"guilty",meaning:"有罪の；罪の意識がある",breakdown:"罪を負っている状態。crime を犯した結果の立場"}]},

  {id:558,word:"motive",partOfSpeech:"名詞",meaning:"動機，きっかけとなる気持ち",
   meanings:["名|動機，きっかけとなる気持ち"],
   pronunciation:"/ˈmoʊtɪv/",part:56,
   example:"The police could not find any motive for the strange act.",
   exampleJa:"警察はその奇妙な行いの動機を何も見つけられなかった。",
   example2:"Her motive for joining the club was simply to make friends.",
   exampleJa2:"彼女がその部に入った動機は、ただ友達を作ることだった。",
   etymologyProcess:"mot（動かす）＋ ive（〜な性質の）→ 心を内から動かす力は…？",
   etymologyConclusion:"mot（動かす）＋ ive（〜な性質の）→ 人の心を内側から動かして行動へ押し出す力＝動機",
   relatedWords:[
     {word:"motion",meaning:"動き，運動",breakdown:"mot（動かす）＋ ion（名詞）→ 物が場所を変えて動いていくこと"},
     {word:"motor",meaning:"モーター，発動機",breakdown:"mot（動かす）＋ or（もの）→ 力を生んで物を動かし続ける装置"},
     {word:"emotion",meaning:"感情",breakdown:"e（外へ）＋ mot（動かす）＋ ion（名詞）→ 心が外へ動き出して表に出るもの"},
     {word:"remote",meaning:"遠く離れた",breakdown:"re（後ろへ）＋ mot（動かす）→ 後ろへ動かされて遠くにある"}]},

  {id:559,word:"punish",partOfSpeech:"他動詞",meaning:"罰する",
   meanings:["他|罰する，こらしめる"],
   pronunciation:"/ˈpʌnɪʃ/",part:56,
   example:"The school will punish students who break the safety rules.",
   exampleJa:"学校は安全の規則を破った生徒を罰するだろう。",
   example2:"He was punished for coming to morning practice late again.",
   exampleJa2:"彼はまた朝練に遅れて来たことで罰せられた。",
   etymologyProcess:"pun（罰）＋ ish（〜にする）→ 悪い行いの償いを負わせるのは…？",
   etymologyConclusion:"pun（罰）＋ ish（〜にする）→ 悪いことをした人に償いを負わせる＝罰する",
   relatedWords:[
     {word:"punishment",meaning:"罰",breakdown:"pun（罰）＋ ish（〜にする）＋ ment（名詞）→ 償いとして与えられるもの"},
     {word:"penalty",meaning:"罰，罰金",breakdown:"pen（罰）＋ alty（名詞）→ 規則を破った人に課される重い罰"},
     {synonym:true,word:"fine",meaning:"罰金；罰金を科す",breakdown:"お金で払わせる罰。punish は罰を与える行為そのもの"},
     {synonym:true,word:"scold",meaning:"叱る",breakdown:"言葉できつく注意する。punish は実際に不利益を与える"}]},

  {id:560,word:"violate",partOfSpeech:"他動詞",meaning:"違反する；踏みにじる",
   meanings:["他|（規則・法を）違反する","他|（権利を）踏みにじる"],
   pronunciation:"/ˈvaɪəleɪt/",part:56,
   example:"Drivers who violate this rule must pay a large fine.",
   exampleJa:"この規則に違反する運転手は、高い罰金を払わなければならない。",
   example2:"The company violated the contract by hiding the test results.",
   exampleJa2:"その会社は検査結果を隠して契約に違反した。",
   etymologyProcess:"viol（力ずくで扱う）＋ ate（動詞）→ 決まりを力で踏みにじると…？",
   etymologyConclusion:"viol（力ずくで扱う）＋ ate（動詞）→ 決まりを力ずくで踏みにじって破る＝違反する",
   relatedWords:[
     {word:"violence",meaning:"暴力",breakdown:"viol（力ずくで扱う）＋ ence（名詞）→ 相手を力ずくで押さえつける荒さ"},
     {word:"violent",meaning:"暴力的な，激しい",breakdown:"viol（力ずくで扱う）＋ ent（〜している）→ 力まかせで荒れているようす"},
     {word:"violation",meaning:"違反",breakdown:"viol（力ずくで扱う）＋ ation（名詞）→ 決まりを踏みにじった行い"},
     {synonym:true,word:"break",meaning:"（約束・規則を）破る",breakdown:"約束や規則を壊す。violate は法や権利に使う硬い語"}]},

  {id:561,word:"legal",partOfSpeech:"形容詞",meaning:"合法の；法律に関する",
   meanings:["形|合法の，法律で認められた","形|法律に関する"],
   pronunciation:"/ˈliːɡl̩/",part:57,
   example:"In Japan it is legal to ride a bicycle at fifteen.",
   exampleJa:"日本では15歳で自転車に乗ることは合法だ。",
   example2:"Our teacher asked a lawyer for legal advice about the trip.",
   exampleJa2:"先生はその旅行について、弁護士に法律上の助言を求めた。",
   etymologyProcess:"leg（法）＋ al（〜の）→ 国の決まりのとおりで認められるのは…？",
   etymologyConclusion:"leg（法）＋ al（〜の）→ 国の決まりのわく内にきちんと収まっている＝合法の",
   relatedWords:[
     {word:"illegal",meaning:"違法の",breakdown:"il（否定）＋ leg（法）＋ al（〜の）→ 法のわくから外れている"},
     {word:"legislation",meaning:"法律，立法",breakdown:"leg（法）＋ lation（運ぶ）→ 法を運び入れて新しく定めること"},
     {word:"privilege",meaning:"特権",breakdown:"privi（個人の）＋ leg（法）→ その人だけに当てはまる特別な法"},
     {synonym:true,word:"lawful",meaning:"適法の",breakdown:"法にかなっている。legal のほうが日常でよく使われる"}]},

  {id:562,word:"enemy",partOfSpeech:"名詞",meaning:"敵",
   meanings:["名|敵，かたき"],
   pronunciation:"/ˈenəmi/",part:57,
   example:"The old castle was built to keep the enemy outside.",
   exampleJa:"その古い城は、敵を外に食い止めるために建てられた。",
   example2:"Lack of sleep is the greatest enemy of a good score.",
   exampleJa2:"睡眠不足は、よい点数にとって最大の敵だ。",
   etymologyProcess:"en（否定）＋ emy（友）→ 友ではなく害をなそうとするのは…？",
   etymologyConclusion:"en（否定）＋ emy（友）→ 友ではなく、こちらに害を与えようとする相手＝敵",
   relatedWords:[
     {word:"amateur",meaning:"アマチュア，素人",breakdown:"am（愛する）＋ ateur（人）→ 好きだからやる人。emy と同じ「友・愛」"},
     {synonym:true,word:"rival",meaning:"競争相手",breakdown:"同じ物を争う相手。enemy のような害意はない"},
     {synonym:true,word:"opponent",meaning:"対戦相手",breakdown:"試合や議論で向かい合う相手。enemy より中立的"},
     {synonym:true,word:"hostile",meaning:"敵意のある",breakdown:"相手を敵とみなす気持ち。enemy はその相手そのもの"}]},

  {id:563,word:"conflict",partOfSpeech:"名詞",meaning:"対立，衝突",
   meanings:["名|対立，衝突","名|（武力による）紛争"],
   pronunciation:"/ˈkɑːnflɪkt/",part:57,
   example:"A long conflict between the two countries finally came to an end.",
   exampleJa:"その二国間の長い対立が、ついに終わりを迎えた。",
   example2:"There was a small conflict between the two clubs over the gym.",
   exampleJa2:"体育館をめぐって、二つの部の間に小さな対立があった。",
   etymologyProcess:"con（共に）＋ flict（打つ）→ 両方が同時に打ち合うのは…？",
   etymologyConclusion:"con（共に）＋ flict（打つ）→ 両方が同時に打ち合って正面からぶつかること＝対立",
   relatedWords:[
     {word:"inflict",meaning:"（苦痛などを）与える",breakdown:"in（中へ）＋ flict（打つ）→ 相手の中へ打ち込むように苦痛を与える"},
     {synonym:true,word:"fight",meaning:"戦い；戦う",breakdown:"実際に手を出して争う。conflict は考えや立場のぶつかり合い"},
     {synonym:true,word:"quarrel",meaning:"口論する",breakdown:"言葉で言い争う。conflict は国や集団どうしにも使う"},
     {synonym:true,word:"dispute",meaning:"論争，紛争",breakdown:"どちらが正しいか争う。conflict は力のぶつかり合いも含む"}]},

  {id:564,word:"compete",partOfSpeech:"自動詞",meaning:"競争する，張り合う",
   meanings:["自|競争する，張り合う"],
   pronunciation:"/kəmˈpiːt/",part:57,
   example:"Small shops cannot easily compete with large online stores.",
   exampleJa:"小さな店は、大きな通販の店とは簡単に競争できない。",
   example2:"Ten schools competed for the first prize in the chorus contest.",
   exampleJa2:"合唱コンクールでは10校が優勝をめざして競争した。",
   etymologyProcess:"com（共に）＋ pet（求める）→ 同じ一つの物を共に求めると…？",
   etymologyConclusion:"com（共に）＋ pet（求める）→ 同じ一つのものを共に求めて張り合う＝競争する",
   relatedWords:[
     {word:"competition",meaning:"競争；大会",breakdown:"com（共に）＋ pet（求める）＋ ition（名詞）→ 同じ的を求めて張り合う場"},
     {word:"repeat",meaning:"繰り返す",breakdown:"re（何度も）＋ pet（求める）→ 同じことを何度も求めてなぞる"},
     {word:"appetite",meaning:"食欲",breakdown:"ad（〜へ）＋ pet（求める）→ 食べ物のほうへ体が強く求める気持ち"},
     {synonym:true,word:"rival",meaning:"競争相手",breakdown:"張り合う相手そのもの。compete はその動きを表す"}]},

  {id:565,word:"defeat",partOfSpeech:"他動詞",meaning:"打ち負かす",
   meanings:["他|打ち負かす，破る","名|敗北"],
   pronunciation:"/dɪˈfiːt/",part:57,
   example:"Our team defeated the strongest school in the final game.",
   exampleJa:"私たちのチームは決勝で最強の学校を打ち負かした。",
   example2:"A small country may defeat a larger one with better plans.",
   exampleJa2:"小さな国でも、よい計画があれば大国を打ち負かすことがある。",
   etymologyProcess:"de（逆に）＋ feat（作る）→ 相手が作り上げた物を崩すと…？",
   etymologyConclusion:"de（逆に）＋ feat（作る）→ 相手が作り上げた構えを逆に崩して倒す＝打ち負かす",
   relatedWords:[
     {word:"feat",meaning:"偉業，離れ業",breakdown:"feat（作る）→ ふつうの人には作り出せない大仕事"},
     {word:"factory",meaning:"工場",breakdown:"fact（作る）＋ ory（場所）→ 物を次々に作り出すための場所"},
     {synonym:true,word:"beat",meaning:"（試合で）負かす",breakdown:"打って勝つ。defeat のほうが硬く、戦争や選挙にも使う"},
     {synonym:true,word:"overcome",meaning:"克服する",breakdown:"困難を乗り越える。defeat は相手そのものを負かす"}]},

  {id:566,word:"victim",partOfSpeech:"名詞",meaning:"犠牲者，被害者",
   meanings:["名|犠牲者，被害者"],
   pronunciation:"/ˈvɪktɪm/",part:57,
   example:"Many victims of the earthquake still live in temporary houses.",
   exampleJa:"その地震の犠牲者の多くは、今も仮設住宅で暮らしている。",
   example2:"He became a victim of a trick message sent to his phone.",
   exampleJa2:"彼は携帯に送られてきた偽のメッセージの被害者になった。",
   hook:"fall victim to ～（～の犠牲になる）の形で覚える。もとは神へのいけにえ。",
   etymologyProcess:"victim（いけにえ）→ 自分のせいでなく傷つけられるのは…？",
   etymologyConclusion:"victim（いけにえ）→ 自分に落ち度がないのに差し出され傷つけられた人＝犠牲者",
   relatedWords:[
     {synonym:true,word:"survivor",meaning:"生存者",breakdown:"災害や事故を生きのびた人。victim は傷つけられた側"},
     {synonym:true,word:"sufferer",meaning:"苦しんでいる人",breakdown:"痛みを受け続ける人。victim は被害を受けた立場を指す"},
     {synonym:true,word:"target",meaning:"標的",breakdown:"ねらわれる的。victim は実際に害を受けてしまった人"},
     {synonym:true,word:"sacrifice",meaning:"犠牲；犠牲にする",breakdown:"神に差し出す行い。victim は差し出された側のもの"}]},

  {id:567,word:"obstacle",partOfSpeech:"名詞",meaning:"障害物，じゃまになるもの",
   meanings:["名|障害物，じゃまになるもの"],
   pronunciation:"/ˈɑːbstəkl̩/",part:57,
   example:"The biggest obstacle to his dream was a lack of money.",
   exampleJa:"彼の夢にとって最大の障害は、お金が足りないことだった。",
   example2:"Runners must jump over ten obstacles in this school race.",
   exampleJa2:"この校内レースでは、走者は10個の障害物を跳び越えねばならない。",
   etymologyProcess:"ob（向かい合って）＋ sta（立つ）→ 進む道の前に立つ物は…？",
   etymologyConclusion:"ob（向かい合って）＋ sta（立つ）＋ cle（もの）→ 行く手に向かい立ちふさがる物＝障害物",
   relatedWords:[
     {word:"stable",meaning:"安定した",breakdown:"sta（立つ）＋ able（できる）→ ぐらつかずに立っていられる"},
     {word:"constant",meaning:"絶え間ない",breakdown:"con（共に）＋ sta（立つ）＋ ant（〜な）→ ずっと同じ所に立ち続ける"},
     {synonym:true,word:"barrier",meaning:"障壁",breakdown:"行く手をさえぎる壁。obstacle は置かれた物や事情を指す"},
     {synonym:true,word:"difficulty",meaning:"困難",breakdown:"うまくいかないこと全般。obstacle は目に見えるじゃま物"}]},

  {id:568,word:"harm",partOfSpeech:"名詞",meaning:"害，悪い影響",
   meanings:["名|害，悪い影響","他|傷つける，害を与える"],
   pronunciation:"/hɑːrm/",part:57,
   example:"Too much salt can do real harm to your young body.",
   exampleJa:"塩の取りすぎは、若い体に本当の害を与えることがある。",
   example2:"A little noise during study does no harm to most students.",
   exampleJa2:"勉強中の少しの物音は、たいていの生徒には害がない。",
   etymologyProcess:"harm（傷つける）→ 体や心にあとを残してしまうのは…？",
   etymologyConclusion:"harm（傷つける）→ 体や心にじわじわと傷を残してしまう悪い働き＝害",
   relatedWords:[
     {word:"harmful",meaning:"有害な",breakdown:"harm（傷つける）＋ ful（満ちた）→ 害に満ちていて、ためにならない"},
     {word:"harmless",meaning:"無害な",breakdown:"harm（傷つける）＋ less（ない）→ 傷つける力がなく安心できる"},
     {synonym:true,word:"damage",meaning:"損害",breakdown:"物が壊れる被害。harm は体や心への悪い影響に多く使う"},
     {synonym:true,word:"injure",meaning:"けがをさせる",breakdown:"体に傷を負わせる。harm はもっと広く「悪い影響」を指す"}]},

  {id:569,word:"invade",partOfSpeech:"他動詞",meaning:"侵略する；（権利を）侵す",
   meanings:["他|（他国へ）侵略する，攻め込む","他|（権利・私生活を）侵す"],
   pronunciation:"/ɪnˈveɪd/",part:57,
   example:"The army invaded the small island early in the morning.",
   exampleJa:"軍はその小さな島に、朝早く侵略した。",
   example2:"Reporters should not invade the private life of a young player.",
   exampleJa2:"記者は若い選手の私生活を侵すべきではない。",
   etymologyProcess:"in（中へ）＋ vad（進む）→ 相手の領分へずかずか進むと…？",
   etymologyConclusion:"in（中へ）＋ vad（進む）→ 相手の領分の中へ断りなく踏み込んでいく＝侵略する",
   relatedWords:[
     {word:"invasion",meaning:"侵略，侵害",breakdown:"in（中へ）＋ vas（進む）＋ ion（名詞）→ 中へ踏み込む行いそのもの"},
     {word:"evade",meaning:"（巧みに）逃れる",breakdown:"e（外へ）＋ vad（進む）→ するりと外へ進んで身をかわす"},
     {word:"invader",meaning:"侵略者",breakdown:"in（中へ）＋ vad（進む）＋ er（人）→ 人の領分へ踏み込む側の人"},
     {synonym:true,word:"attack",meaning:"攻撃する",breakdown:"いきなり打ちかかる。invade は territory に入り込む点が中心"}]},

  {id:570,word:"endanger",partOfSpeech:"他動詞",meaning:"危険にさらす",
   meanings:["他|危険にさらす"],
   pronunciation:"/ɪnˈdeɪndʒər/",part:57,
   example:"Cutting down the forest endangers many kinds of wild birds.",
   exampleJa:"森を切り倒すことは、多くの種類の野鳥を危険にさらす。",
   example2:"Riding without a helmet endangers your own life every single day.",
   exampleJa2:"ヘルメットなしで乗ることは、毎日自分の命を危険にさらしている。",
   etymologyProcess:"en（〜にする）＋ danger（支配する力）→ 危険の中に置くと…？",
   etymologyConclusion:"en（〜にする）＋ danger（支配する力）→ 相手を危険に支配される所へ置く＝危険にさらす",
   relatedWords:[
     {word:"danger",meaning:"危険",breakdown:"danger（支配する力）→ 人を思いのままにできる力。そこから危険"},
     {word:"dangerous",meaning:"危険な",breakdown:"danger（支配する力）＋ ous（〜に満ちた）→ 危険に満ちているようす"},
     {word:"enlarge",meaning:"大きくする",breakdown:"en（〜にする）＋ large（大きい）→ 前より大きい形に変える"},
     {synonym:true,word:"threaten",meaning:"脅かす",breakdown:"害を加えそうな気配を見せる。endanger は実際に危険に置く"}]},

  {id:571,word:"interrupt",partOfSpeech:"他動詞",meaning:"中断する；話をさえぎる",
   meanings:["他|（続いていることを）中断する","他|（人の話を）さえぎる"],
   pronunciation:"/ˌɪntəˈrʌpt/",part:58,
   example:"A loud alarm interrupted our test in the middle of it.",
   exampleJa:"大きな警報が、試験の途中でそれを中断した。",
   example2:"Please do not interrupt me while I am explaining the rules.",
   exampleJa2:"私が規則を説明している間は、話をさえぎらないでください。",
   etymologyProcess:"inter（間の）＋ rupt（破る）→ 続く流れの間に割って入ると…？",
   etymologyConclusion:"inter（間の）＋ rupt（破る）→ 続いている流れの間に割り込んで断ち切る＝中断する",
   relatedWords:[
     {word:"erupt",meaning:"噴火する",breakdown:"e（外へ）＋ rupt（破る）→ 山が内から破れて外へ噴き出す"},
     {word:"corrupt",meaning:"腐敗した",breakdown:"com（すっかり）＋ rupt（破る）→ 中身がすっかり壊れて腐っている"},
     {synonym:true,word:"disturb",meaning:"じゃまをする",breakdown:"落ち着きを乱す。interrupt は進行を途中で止める"},
     {synonym:true,word:"pause",meaning:"一時止める",breakdown:"自分で一度止める。interrupt は外から割り込んで止める"}]},

  {id:572,word:"spoil",partOfSpeech:"他動詞",meaning:"台無しにする；甘やかす",
   meanings:["他|（楽しみなどを）台無しにする","他|（子どもを）甘やかす"],
   pronunciation:"/spɔɪl/",part:58,
   example:"Heavy rain spoiled our first day of the school trip.",
   exampleJa:"大雨が修学旅行の初日を台無しにした。",
   example2:"Do not spoil the ending of the movie for your friends.",
   exampleJa2:"映画の結末を友達に言って台無しにしないで。",
   hook:"spoil a child なら「甘やかしてだめにする」。食べ物が主語なら「腐る」。",
   etymologyProcess:"spoil（はぎ取る）→ よい所をはぎ取ってだめにするのは…？",
   etymologyConclusion:"spoil（はぎ取る）→ せっかくの中身からよい所をはぎ取ってだめにする＝台無しにする",
   relatedWords:[
     {word:"spoiled",meaning:"甘やかされた；腐った",breakdown:"spoil（はぎ取る）＋ ed（〜された）→ 本来のよさをはぎ取られた状態"},
     {synonym:true,word:"ruin",meaning:"だめにする",breakdown:"完全に崩してしまう。spoil は楽しみや味を損なう場面が多い"},
     {synonym:true,word:"destroy",meaning:"破壊する",breakdown:"形を壊してなくす。spoil は形が残っても価値が落ちる"},
     {synonym:true,word:"waste",meaning:"むだにする",breakdown:"使わずに捨てる。spoil は使えたはずの物をだめにする"}]},

  {id:573,word:"spectator",partOfSpeech:"名詞",meaning:"（競技の）観客",
   meanings:["名|（競技・催しの）観客，見物人"],
   pronunciation:"/ˈspekteɪtər/",part:58,
   example:"About five thousand spectators watched the final match yesterday.",
   exampleJa:"昨日の決勝戦は、約5千人の観客が見守った。",
   example2:"One spectator ran onto the field and stopped the game.",
   exampleJa2:"ひとりの観客が競技場に走り込み、試合を止めた。",
   etymologyProcess:"spect（見る）＋ ator（人）→ ただ見るために来ている人は…？",
   etymologyConclusion:"spect（見る）＋ ator（人）→ 自分は出ずに、見るために来ている人＝観客",
   relatedWords:[
     {word:"inspect",meaning:"検査する",breakdown:"in（中へ）＋ spect（見る）→ 中までのぞき込んで細かく調べる"},
     {word:"respect",meaning:"尊敬する",breakdown:"re（じっと）＋ spect（見る）→ 相手をじっと見返して大切に思う"},
     {synonym:true,word:"audience",meaning:"聴衆，観客",breakdown:"耳で聞く客。spectator は目で見る客を指す"},
     {synonym:true,word:"viewer",meaning:"視聴者",breakdown:"テレビなどを見る人。spectator は会場にいる客"}]},

  {id:574,word:"relative",partOfSpeech:"名詞",meaning:"親戚；比べてはじめて決まる",
   meanings:["名|親戚，身内","形|比べてはじめて決まる，相対的な"],
   pronunciation:"/ˈrelətɪv/",part:58,
   example:"All my relatives get together at my grandmother's house each summer.",
   exampleJa:"私の親戚はみな、毎年夏に祖母の家に集まる。",
   example2:"A close relative of hers works as a nurse in Osaka.",
   exampleJa2:"彼女の近い親戚のひとりは、大阪で看護師として働いている。",
   etymologyProcess:"re（戻す）＋ lat（運ぶ）＋ ive（〜な性質の）→ 血で結ばれた人は…？",
   etymologyConclusion:"re（戻す）＋ lat（運ぶ）＋ ive（〜な性質の）→ 同じ先祖へ運び戻せる間柄の人＝親戚",
   relatedWords:[
     {word:"relation",meaning:"関係，間柄",breakdown:"re（戻す）＋ lat（運ぶ）＋ ion（名詞）→ 運び戻して結ばれたつながり"},
     {word:"relatively",meaning:"比較的",breakdown:"re（戻す）＋ lat（運ぶ）＋ ly（副詞）→ 他へ引き比べてみると"},
     {synonym:true,word:"cousin",meaning:"いとこ",breakdown:"おじ・おばの子。relative はもっと広く身内全体を指す"},
     {synonym:true,word:"family",meaning:"家族",breakdown:"一緒に暮らす身内。relative は離れて住む身内も含む"}]},

  {id:575,word:"departure",partOfSpeech:"名詞",meaning:"出発",
   meanings:["名|出発，出港"],
   pronunciation:"/dɪˈpɑːrtʃər/",part:58,
   example:"The departure of our plane was delayed by two hours.",
   exampleJa:"私たちの飛行機の出発は、2時間遅れた。",
   example2:"Students should reach the gate ten minutes before departure.",
   exampleJa2:"生徒は出発の10分前には門に着いているべきだ。",
   etymologyProcess:"de（離して）＋ part（分ける）＋ ure（名詞）→ 身を分けて離れると…？",
   etymologyConclusion:"de（離して）＋ part（分ける）＋ ure（名詞）→ 今いる場所から身を分けて離れること＝出発",
   relatedWords:[
     {word:"depart",meaning:"出発する",breakdown:"de（離して）＋ part（分ける）→ その場から身を分けて出ていく"},
     {word:"apart",meaning:"離れて",breakdown:"ad（〜へ）＋ part（分ける）→ 分かれて別々の所にある"},
     {word:"particle",meaning:"粒子",breakdown:"part（分ける）＋ icle（小さいもの）→ 分けに分けた小さなかけら"},
     {synonym:true,word:"start",meaning:"始まり；出発する",breakdown:"物事の始まり全般。departure は場所を離れる出発"}]},

  {id:576,word:"destination",partOfSpeech:"名詞",meaning:"目的地，行き先",
   meanings:["名|目的地，行き先"],
   pronunciation:"/ˌdestɪˈneɪʃn̩/",part:58,
   example:"Our final destination on this trip is a small fishing town.",
   exampleJa:"この旅の最終的な目的地は、小さな漁師町だ。",
   example2:"Write your name and destination on the card at the desk.",
   exampleJa2:"受付のカードに名前と行き先を書いてください。",
   etymologyProcess:"de（すっかり）＋ stin（決める）→ 前もって決めてある行き先は…？",
   etymologyConclusion:"de（すっかり）＋ stin（決める）＋ ation（名詞）→ 出る前にすっかり決めてある行き着く先＝目的地",
   relatedWords:[
     {word:"destiny",meaning:"運命",breakdown:"de（すっかり）＋ stin（決める）＋ y（名詞）→ すっかり決められている行く末"},
     {synonym:true,word:"goal",meaning:"目標，ゴール",breakdown:"たどり着きたい所。destination は実際の到着地点"},
     {synonym:true,word:"arrival",meaning:"到着",breakdown:"着くことそのもの。destination は着く先の場所"},
     {synonym:true,word:"aim",meaning:"ねらい",breakdown:"心に定めた的。destination は地図に書ける場所を指す"}]},

  {id:577,word:"transportation",partOfSpeech:"名詞",meaning:"交通機関；輸送",
   meanings:["名|交通機関","名|輸送，運ぶこと"],
   pronunciation:"/ˌtrænspɔːrˈteɪʃn̩/",part:58,
   example:"Public transportation in this city runs until midnight every day.",
   exampleJa:"この市の公共交通機関は、毎日真夜中まで走っている。",
   example2:"Free transportation was offered to all the visiting team members.",
   exampleJa2:"訪れたチームの全員に、無料の交通手段が用意された。",
   etymologyProcess:"trans（越えて）＋ port（運ぶ）→ 人や物を越えて運ぶしくみは…？",
   etymologyConclusion:"trans（越えて）＋ port（運ぶ）＋ ation（名詞）→ 人や物を境を越えて運ぶしくみ＝交通機関",
   relatedWords:[
     {word:"transport",meaning:"輸送する",breakdown:"trans（越えて）＋ port（運ぶ）→ 遠くの場所へ運び越す"},
     {word:"export",meaning:"輸出する",breakdown:"ex（外へ）＋ port（運ぶ）→ 品物を国の外へ運び出す"},
     {word:"portable",meaning:"持ち運べる",breakdown:"port（運ぶ）＋ able（できる）→ 手で運べるくらい軽い"},
     {synonym:true,word:"traffic",meaning:"交通（量）",breakdown:"道を行き交う車や人。transportation は運ぶしくみ全体"}]},

  {id:578,word:"vehicle",partOfSpeech:"名詞",meaning:"車両，乗り物",
   meanings:["名|車両，乗り物","名|（考えを伝える）手段"],
   pronunciation:"/ˈviːəkl̩/",part:58,
   example:"No vehicle is allowed to enter this park after six.",
   exampleJa:"6時以降、この公園に乗り物が入ることは許されていない。",
   example2:"A strange vehicle with six wheels stopped in front of school.",
   exampleJa2:"車輪が6つある変わった車両が、学校の前に止まった。",
   etymologyProcess:"veh（運ぶ）＋ icle（小さいもの）→ 人や荷を載せて運ぶ物は…？",
   etymologyConclusion:"veh（運ぶ）＋ icle（小さいもの）→ 人や荷物を載せて地上を運ぶ道具＝車両",
   relatedWords:[
     {word:"article",meaning:"記事；品物",breakdown:"art（技）＋ icle（小さいもの）→ 手を加えて作った小さなひとまとまり"},
     {synonym:true,word:"transport",meaning:"輸送機関",breakdown:"運ぶしくみ全体。vehicle は一台ごとの乗り物"},
     {synonym:true,word:"truck",meaning:"トラック",breakdown:"荷物を運ぶ車。vehicle は車・バスなどをまとめた言い方"},
     {synonym:true,word:"means",meaning:"手段",breakdown:"目的に使う手だて。vehicle も「伝える手段」の意味を持つ"}]},

  {id:579,word:"baggage",partOfSpeech:"名詞",meaning:"手荷物",
   meanings:["名|手荷物，旅行かばん類"],
   pronunciation:"/ˈbæɡɪdʒ/",part:58,
   example:"She put her heavy baggage on the back seat of the car.",
   exampleJa:"彼女は重い手荷物を車の後部座席に置いた。",
   example2:"All baggage must be checked before you enter the gate.",
   exampleJa2:"すべての手荷物は、ゲートに入る前に検査されねばならない。",
   etymologyProcess:"bag（袋）＋ age（名詞）→ 旅で袋にまとめて持ち歩く物は…？",
   etymologyConclusion:"bag（袋）＋ age（名詞）→ 旅のあいだ袋にまとめて持ち歩く物のひとそろい＝手荷物",
   relatedWords:[
     {word:"bag",meaning:"かばん，袋",breakdown:"bag（袋）→ 口を閉じて物を入れて運べる入れ物"},
     {word:"package",meaning:"小包，包み",breakdown:"pack（包み）＋ age（名詞）→ 包んでひとまとめにした荷物"},
     {synonym:true,word:"luggage",meaning:"旅行かばん",breakdown:"英国でよく使う語。baggage は米国でよく使う"},
     {synonym:true,word:"suitcase",meaning:"スーツケース",breakdown:"衣類を入れる旅行かばん一つ。baggage は荷物全体"}]},

  {id:580,word:"via",partOfSpeech:"前置詞",meaning:"〜を経由して；〜を通じて",
   meanings:["前|〜を経由して","前|〜を通じて，〜の手段で"],
   pronunciation:"/ˈvaɪə/",part:58,
   example:"We flew from Tokyo to Rome via Paris last summer.",
   exampleJa:"去年の夏、私たちは東京からパリを経由してローマへ飛んだ。",
   example2:"The teacher sent the handout to us via the school app.",
   exampleJa2:"先生はそのプリントを、学校のアプリを通じて私たちに送った。",
   etymologyProcess:"via（道）→ その道を通って行くことを表すのは…？",
   etymologyConclusion:"via（道）→ 目的地までの途中でその道を通っていく＝〜を経由して",
   relatedWords:[
     {word:"obvious",meaning:"明らかな",breakdown:"ob（向かい合って）＋ via（道）＋ ous（形容詞）→ 道の真ん中にあって目に入る"},
     {word:"previous",meaning:"前の",breakdown:"pre（先に）＋ via（道）＋ ous（形容詞）→ 道を先に行っている"},
     {synonym:true,word:"through",meaning:"〜を通って",breakdown:"中を通り抜ける。via は「途中で寄る地点」を示す"},
     {synonym:true,word:"route",meaning:"経路",breakdown:"たどる道すじ。via はその道すじの通過点を示す前置詞"}]},

  {id:581,word:"lead",partOfSpeech:"他動詞・自動詞",meaning:"（結果として）至る；先に立って導く",
   meanings:["自|（結果として）〜に至る","他|先に立って導く，案内する"],
   pronunciation:"/liːd/",part:59,
   example:"Small daily efforts lead to a big change in the end.",
   exampleJa:"日々の小さな努力が、最後には大きな変化に至る。",
   example2:"This narrow path leads to the back gate of our school.",
   exampleJa2:"この細い道は、学校の裏門に通じている。",
   hook:"lead to ～ で「～という結果に至る」。lead A to B は「A を B へ導く」。",
   etymologyProcess:"lead（導く）→ 先頭で引っぱって行き着かせるのは…？",
   etymologyConclusion:"lead（導く）→ 先頭に立って引っぱっていき、ある所へ行き着かせる＝至る",
   relatedWords:[
     {word:"leader",meaning:"指導者",breakdown:"lead（導く）＋ er（人）→ 先頭に立って皆を引っぱる人"},
     {word:"mislead",meaning:"誤った方へ導く",breakdown:"mis（誤って）＋ lead（導く）→ 正しくない方へ引っぱっていく"},
     {synonym:true,word:"cause",meaning:"引き起こす",breakdown:"原因になる。lead to は結果まで「行き着く」流れを表す"},
     {synonym:true,word:"guide",meaning:"案内する",breakdown:"道を教えながら連れて行く。lead は自分が先頭を行く"}]},

  {id:582,word:"rise",partOfSpeech:"自動詞",meaning:"（ひとりでに）上がる，のぼる",
   meanings:["自|（ひとりでに）上がる，のぼる","名|上昇，増加"],
   pronunciation:"/raɪz/",part:59,
   example:"The sun rises a little earlier here in the early summer.",
   exampleJa:"ここでは初夏になると、太陽が少し早く上がる。",
   example2:"Prices of vegetables rise every time a big typhoon comes.",
   exampleJa2:"大きな台風が来るたびに、野菜の値段が上がる。",
   etymologyProcess:"rise（上がる）→ 誰の手も借りず下から上へ動くのは…？",
   etymologyConclusion:"rise（上がる）→ 誰かに持ち上げられず、自分で下から上へ動く＝上がる",
   relatedWords:[
     {word:"raise",meaning:"持ち上げる，上げる",breakdown:"raise（上がらせる）→ 物を手で下から持ち上げて高くする"},
     {word:"arise",meaning:"（問題が）生じる",breakdown:"ad（〜へ）＋ rise（上がる）→ 問題が表に立ち上がってくる"},
     {word:"sunrise",meaning:"日の出",breakdown:"sun（太陽）＋ rise（上がる）→ 太陽が地平線から立ち上がる時"},
     {synonym:true,word:"increase",meaning:"増える",breakdown:"数や量が増す。rise は位置や数値が上へ動く"}]},

  {id:583,word:"flow",partOfSpeech:"自動詞",meaning:"流れる",
   meanings:["自|（液体などが）流れる","名|流れ"],
   pronunciation:"/floʊ/",part:59,
   example:"This wide river flows slowly through the center of the town.",
   exampleJa:"この広い川は、町の中心をゆっくりと流れている。",
   example2:"Warm air flowed into the room when she opened the door.",
   exampleJa2:"彼女がドアを開けると、暖かい空気が部屋に流れ込んだ。",
   etymologyProcess:"flow（流れる）→ 切れ目なく低いほうへ動いていくのは…？",
   etymologyConclusion:"flow（流れる）→ 途切れずに、低いほうへ向かってなめらかに動く＝流れる",
   relatedWords:[
     {word:"flood",meaning:"洪水",breakdown:"flood（流れる）→ 川があふれて土地いっぱいに流れ広がること"},
     {word:"overflow",meaning:"あふれる",breakdown:"over（越えて）＋ flow（流れる）→ ふちを越えて外へ流れ出る"},
     {synonym:true,word:"stream",meaning:"小川；流れ",breakdown:"細く続く流れそのもの。flow はその動きを表す"},
     {synonym:true,word:"pour",meaning:"注ぐ；降り注ぐ",breakdown:"勢いよく流し出す。flow はひとりでに続く流れ"}]},

  {id:584,word:"burst",partOfSpeech:"自動詞",meaning:"破裂する，はじける",
   meanings:["自|破裂する，はじける","自|（感情が）急にあふれ出る"],
   pronunciation:"/bɜːrst/",part:59,
   example:"Balloons burst if you blow too much air into them.",
   exampleJa:"空気を入れすぎると、風船は破裂する。",
   example2:"The old water pipe burst during the coldest night of winter.",
   exampleJa2:"その古い水道管は、冬でいちばん寒い夜に破裂した。",
   hook:"過去形・過去分詞も burst。burst into tears は「急に泣き出す」。",
   etymologyProcess:"burst（はじけ破れる）→ 中の力に耐えきれなくなるのは…？",
   etymologyConclusion:"burst（はじけ破れる）→ 中の力に耐えきれず、一気にはじけて破れる＝破裂する",
   relatedWords:[
     {word:"outburst",meaning:"（感情の）爆発",breakdown:"out（外へ）＋ burst（はじけ破れる）→ こらえた気持ちが外へはじけ出る"},
     {synonym:true,word:"explode",meaning:"爆発する",breakdown:"音と炎を上げて飛び散る。burst は袋や管がはじける"},
     {synonym:true,word:"break",meaning:"壊れる",breakdown:"形が壊れる全般。burst は内側の圧力で破れる"},
     {synonym:true,word:"pop",meaning:"ポンとはじける",breakdown:"軽い音を立ててはじける。burst より小さく軽い感じ"}]},

  {id:585,word:"melt",partOfSpeech:"他動詞・自動詞",meaning:"（熱で）溶ける，溶かす",
   meanings:["自|（熱で）溶ける","他|（熱で）溶かす"],
   pronunciation:"/melt/",part:59,
   example:"The snow on the roof melts quickly on a sunny day.",
   exampleJa:"屋根の雪は、晴れた日にはすぐに溶ける。",
   example2:"Chocolate will melt if you leave it in your school bag.",
   exampleJa2:"チョコレートは通学かばんに入れておくと溶けてしまう。",
   hook:"熱で形をなくすのが melt、水に混ざって消えるのが dissolve。",
   etymologyProcess:"melt（やわらかくする）→ 熱で固さを失って形をなくすのは…？",
   etymologyConclusion:"melt（やわらかくする）→ 固かった物が熱でやわらかくなり、形をなくす＝溶ける",
   relatedWords:[
     {synonym:true,word:"dissolve",meaning:"（液体に）溶ける",breakdown:"水の中でばらばらになって見えなくなる。melt は熱でやわらぐ"},
     {synonym:true,word:"freeze",meaning:"凍る",breakdown:"melt の反対。冷えて固く動かなくなる"},
     {synonym:true,word:"soften",meaning:"やわらかくする",breakdown:"かたさをゆるめる。melt は形そのものがなくなるまで進む"},
     {synonym:true,word:"thaw",meaning:"（凍った物が）解ける",breakdown:"凍った物がゆるむ。melt は氷以外の固体にも使える"}]},

  {id:586,word:"commute",partOfSpeech:"自動詞",meaning:"通勤する，通学する",
   meanings:["自|通勤する，通学する","名|通勤（の道のり）"],
   pronunciation:"/kəˈmjuːt/",part:59,
   example:"My father commutes to his office by train every weekday.",
   exampleJa:"父は平日は毎日、電車で職場に通勤している。",
   example2:"She commuted for two hours each way during her first year.",
   exampleJa2:"彼女は1年目、片道2時間かけて通っていた。",
   etymologyProcess:"com（すっかり）＋ mut（変える）→ 券を定期に替えて毎日通うのは…？",
   etymologyConclusion:"com（すっかり）＋ mut（変える）→ 毎回の運賃を定期に替えて同じ道を行き来する＝通勤する",
   relatedWords:[
     {word:"commuter",meaning:"通勤者",breakdown:"com（すっかり）＋ mut（変える）＋ er（人）→ 定期で毎日同じ道を通う人"},
     {word:"mutual",meaning:"おたがいの",breakdown:"mut（変える）＋ ual（〜の）→ たがいに入れ替えて与え合う関係"},
     {synonym:true,word:"travel",meaning:"移動する",breakdown:"距離を移動する全般。commute は毎日決まった往復"},
     {synonym:true,word:"attend",meaning:"通う，出席する",breakdown:"学校や会に出る。commute は行き帰りの移動に目を向ける"}]},

  {id:587,word:"accompany",partOfSpeech:"他動詞",meaning:"一緒に行く，付き添う",
   meanings:["他|一緒に行く，付き添う","他|（音楽で）伴奏する"],
   pronunciation:"/əˈkʌmpəni/",part:59,
   example:"A teacher must accompany the students on the mountain hike.",
   exampleJa:"山歩きには、教師が生徒に付き添わなければならない。",
   example2:"Her father accompanied her to the hospital on Sunday morning.",
   exampleJa2:"日曜の朝、父親が彼女に付き添って病院へ行った。",
   etymologyProcess:"ad（〜へ）＋ com（共に）＋ pan（パン）→ パンを分け合う仲は…？",
   etymologyConclusion:"ad（〜へ）＋ com（共に）＋ pan（パン）→ パンを分け合う仲間としてそばを歩く＝一緒に行く",
   relatedWords:[
     {word:"company",meaning:"会社；同席の人",breakdown:"com（共に）＋ pan（パン）＋ y（名詞）→ パンを分け合う仲間の集まり"},
     {word:"companion",meaning:"仲間，連れ",breakdown:"com（共に）＋ pan（パン）＋ ion（名詞）→ パンを分け合って旅をする連れ"},
     {synonym:true,word:"follow",meaning:"ついて行く",breakdown:"後ろについて行く。accompany は横に並んで一緒に行く"},
     {synonym:true,word:"escort",meaning:"付き添う，護衛する",breakdown:"守りながら連れて行く。accompany は守る意味を含まない"}]},

  {id:588,word:"emit",partOfSpeech:"他動詞",meaning:"（光・熱・ガスを）出す，排出する",
   meanings:["他|（光・熱・ガスを）出す，排出する"],
   pronunciation:"/iˈmɪt/",part:59,
   example:"Cars emit a large amount of gas into the city air.",
   exampleJa:"車は大量のガスを町の空気中に排出する。",
   example2:"This small lamp emits a soft orange light at night.",
   exampleJa2:"この小さなランプは、夜になると柔らかいオレンジの光を出す。",
   etymologyProcess:"e（外へ）＋ mit（送る）→ 内にあるものを外へ送り出すのは…？",
   etymologyConclusion:"e（外へ）＋ mit（送る）→ 中にたまった光やガスを外へ送り出す＝排出する",
   relatedWords:[
     {word:"submit",meaning:"提出する",breakdown:"sub（下で）＋ mit（送る）→ 相手の下へ差し出すように送る"},
     {word:"permit",meaning:"許可する",breakdown:"per（すっかり）＋ mit（送る）→ すっかり通してよいと送り出す"},
     {word:"transmit",meaning:"送り届ける，伝える",breakdown:"trans（越えて）＋ mit（送る）→ 距離を越えて電波や情報を送る"},
     {synonym:true,word:"release",meaning:"放出する",breakdown:"押さえていた物を放つ。emit は光やガスが出続ける感じ"}]},

  {id:589,word:"progress",partOfSpeech:"名詞",meaning:"進歩，はかどること",
   meanings:["名|進歩，上達","名|（作業の）はかどり"],
   pronunciation:"/ˈprɑːɡres/",part:59,
   example:"She has made great progress in English since last April.",
   exampleJa:"彼女は去年の4月から英語で大きな進歩をとげた。",
   example2:"The progress of the building work was stopped by heavy snow.",
   exampleJa2:"建築工事のはかどりは、大雪によって止められた。",
   etymologyProcess:"pro（前へ）＋ gress（歩む）→ 一歩ずつ前へ歩んだ結果は…？",
   etymologyConclusion:"pro（前へ）＋ gress（歩む）→ 一歩ずつ前へ歩んで、前より先まで来ていること＝進歩",
   relatedWords:[
     {word:"congress",meaning:"議会，会議",breakdown:"con（共に）＋ gress（歩む）→ 皆が共に歩み寄って集まる場"},
     {word:"grade",meaning:"等級，学年",breakdown:"grad（歩み・段）→ 一段ずつ上がっていく段のひとつ"},
     {word:"aggressive",meaning:"攻撃的な",breakdown:"ad（〜へ）＋ gress（歩む）→ 相手へずんずん歩み寄っていく"},
     {synonym:true,word:"improvement",meaning:"改善",breakdown:"悪い所がよくなること。progress は先へ進んだ度合い"}]},

  {id:590,word:"advance",partOfSpeech:"名詞",meaning:"（技術などの）前進；前もっての",
   meanings:["名|（技術・研究の）前進，進展","自|前へ進む"],
   pronunciation:"/ədˈvæns/",part:59,
   example:"Recent advances in medicine have saved many young lives.",
   exampleJa:"近年の医学の前進は、多くの若い命を救ってきた。",
   example2:"Our army advanced slowly through the thick forest at night.",
   exampleJa2:"わが軍は夜、深い森の中をゆっくりと前へ進んだ。",
   etymologyProcess:"ad（〜へ）＋ van（前へ）→ 人より前のほうへ出ていくと…？",
   etymologyConclusion:"ad（〜へ）＋ van（前へ）→ 今いる所より前のほうへ一歩ずつ出ていくこと＝前進",
   relatedWords:[
     {word:"advantage",meaning:"有利な点",breakdown:"ad（〜へ）＋ van（前へ）＋ age（名詞）→ 人より前に出ている有利さ"},
     {word:"advanced",meaning:"上級の，進んだ",breakdown:"ad（〜へ）＋ van（前へ）＋ ed（〜された）→ 人より前へ進んだ段階の"},
     {synonym:true,word:"progress",meaning:"進歩",breakdown:"先へ進んだ度合い。advance は一歩前へ出る動きが中心"},
     {synonym:true,word:"improve",meaning:"改善する",breakdown:"質をよくする。advance は位置や段階が前へ動く"}]},

  {id:591,word:"deal",partOfSpeech:"自動詞",meaning:"（問題に）対処する；取引",
   meanings:["自|（問題・人に）対処する","名|取引，契約"],
   pronunciation:"/diːl/",part:60,
   example:"Our teacher knows how to deal with a noisy class.",
   exampleJa:"先生は、うるさいクラスにどう対処すればよいか知っている。",
   example2:"The city dealt with the flood damage faster than we expected.",
   exampleJa2:"市は思ったより早く、洪水の被害に対処した。",
   hook:"deal with ～ で「～に対処する」。a good deal of ～ は「かなりの量の～」。",
   etymologyProcess:"deal（分ける）→ 事を配り分けるように手を打つのは…？",
   etymologyConclusion:"deal（分ける）→ カードを配り分けるように、相手や問題ごとに手を打つ＝対処する",
   relatedWords:[
     {word:"dealer",meaning:"販売業者；カードを配る人",breakdown:"deal（分ける）＋ er（人）→ 品物やカードを分け配る人"},
     {synonym:true,word:"handle",meaning:"うまく扱う",breakdown:"手で操る感じ。deal with は問題に向き合って片づける"},
     {synonym:true,word:"manage",meaning:"何とかやりとげる",breakdown:"苦労して切り回す。deal は相手ごとに手を打つ"},
     {synonym:true,word:"cope",meaning:"（困難に）立ち向かう",breakdown:"苦しい状況に耐えて対応する。deal with より苦労の色が濃い"}]},

  {id:592,word:"handle",partOfSpeech:"他動詞",meaning:"（道具・人を）うまく扱う；取っ手",
   meanings:["他|（道具・人を）うまく扱う","名|取っ手，柄"],
   pronunciation:"/ˈhændl̩/",part:60,
   example:"Please handle these old glass plates with both your hands.",
   exampleJa:"この古いガラスの皿は、両手でうまく扱ってください。",
   example2:"She handled the angry customer calmly and solved the problem.",
   exampleJa2:"彼女は怒った客を落ち着いてうまく扱い、問題を解決した。",
   etymologyProcess:"hand（手）＋ le（もの）→ 手で握って思いどおりに動かすと…？",
   etymologyConclusion:"hand（手）＋ le（もの）→ 手で握って、思いどおりに動かす＝うまく扱う",
   relatedWords:[
     {word:"handful",meaning:"ひと握り",breakdown:"hand（手）＋ ful（満ちた）→ 手のひらいっぱいになるくらいの量"},
     {word:"handout",meaning:"配布資料",breakdown:"hand（手）＋ out（外へ）→ 手から外へ配っていく紙"},
     {word:"manual",meaning:"手作業の；手引き",breakdown:"manu（手）＋ al（〜の）→ 手で行う、手で扱うための"},
     {synonym:true,word:"operate",meaning:"操作する",breakdown:"機械を動かす。handle は人やもろい物にも使える"}]},

  {id:593,word:"treat",partOfSpeech:"他動詞",meaning:"（人を）ある態度で扱う；治療する",
   meanings:["他|（人を）ある態度で扱う","他|治療する","他|おごる"],
   pronunciation:"/triːt/",part:60,
   example:"You should treat every new member as an equal friend.",
   exampleJa:"新しい部員はみな、対等な友達として扱うべきだ。",
   example2:"The doctor treated his broken arm at the small clinic.",
   exampleJa2:"医師はその小さな診療所で、彼の折れた腕を治療した。",
   etymologyProcess:"treat（引く）→ 相手を手元へ引き受けて向き合うと…？",
   etymologyConclusion:"treat（引く）→ 相手を自分の手元へ引き受け、ある態度で向き合う＝扱う",
   relatedWords:[
     {word:"treatment",meaning:"扱い；治療",breakdown:"treat（引く）＋ ment（名詞）→ 相手への向き合い方そのもの"},
     {word:"attract",meaning:"引きつける",breakdown:"ad（〜へ）＋ tract（引く）→ 自分のほうへぐいと引き寄せる"},
     {word:"contract",meaning:"契約",breakdown:"con（共に）＋ tract（引く）→ 双方を一本の線で引き結んだ約束"},
     {synonym:true,word:"cure",meaning:"治す",breakdown:"病気を治しきる。treat は治そうと手当てする段階"}]},

  {id:594,word:"clue",partOfSpeech:"名詞",meaning:"手がかり，ヒント",
   meanings:["名|手がかり，ヒント"],
   pronunciation:"/kluː/",part:60,
   example:"The police found one small clue near the back door.",
   exampleJa:"警察は裏口の近くで、小さな手がかりを一つ見つけた。",
   example2:"This word gives you a clue about the writer's real feelings.",
   exampleJa2:"この語が、筆者の本当の気持ちについての手がかりになる。",
   hook:"もとは「糸玉」。迷宮でたどった糸のように、答えへ近づく一本の線。",
   etymologyProcess:"clue（糸玉）→ たどれば出口まで届く一本の線は…？",
   etymologyConclusion:"clue（糸玉）→ 迷路でたどった糸のように、答えへ導いてくれる一本の線＝手がかり",
   relatedWords:[
     {synonym:true,word:"hint",meaning:"ヒント，ほのめかし",breakdown:"それとなく示すもの。clue は謎を解く具体的な手がかり"},
     {synonym:true,word:"evidence",meaning:"証拠",breakdown:"事実を裏づける物。clue は答えへ向かう途中の目印"},
     {synonym:true,word:"sign",meaning:"しるし，兆候",breakdown:"何かを表す目印。clue は隠れた答えを探すときに使う"},
     {synonym:true,word:"trace",meaning:"痕跡",breakdown:"残された跡。clue はそこから推理を進められる跡"}]},

  {id:595,word:"restrict",partOfSpeech:"他動詞",meaning:"（自由・行動を）制限する",
   meanings:["他|（自由・行動を）制限する，制約する"],
   pronunciation:"/rɪˈstrɪkt/",part:60,
   example:"The school restricts the use of phones during class hours.",
   exampleJa:"学校は授業中の携帯の使用を制限している。",
   example2:"Heavy snow restricted our movement for almost three whole days.",
   exampleJa2:"大雪が、ほぼ3日間も私たちの行動を制限した。",
   etymologyProcess:"re（後ろへ）＋ strict（締めつける）→ 広がらぬよう締めると…？",
   etymologyConclusion:"re（後ろへ）＋ strict（締めつける）→ 広がろうとする動きを後ろから締めて狭める＝制限する",
   relatedWords:[
     {word:"strict",meaning:"厳しい",breakdown:"strict（締めつける）→ 決まりをきつく締めて、ゆるめない"},
     {word:"restriction",meaning:"制限，制約",breakdown:"re（後ろへ）＋ strict（締めつける）＋ ion（名詞）→ 締めて狭めた決まり"},
     {word:"district",meaning:"地区",breakdown:"dis（バラバラに）＋ strict（締めつける）→ 線で締め分けた区域"},
     {synonym:true,word:"limit",meaning:"限度を定める",breakdown:"上限を決める。restrict は自由そのものを狭める"}]},

  {id:596,word:"limit",partOfSpeech:"名詞",meaning:"限度，上限",
   meanings:["名|限度，上限","他|（数量の）上限を定める"],
   pronunciation:"/ˈlɪmɪt/",part:60,
   example:"The speed limit on this narrow road is forty kilometers.",
   exampleJa:"この狭い道の速度の上限は時速40キロだ。",
   example2:"There is no limit to what you can learn this year.",
   exampleJa2:"今年あなたが学べることに、限度はない。",
   etymologyProcess:"limit（境の土手）→ ここから先は越えられない境目は…？",
   etymologyConclusion:"limit（境の土手）→ 畑の境に築いた土手のように、越えてはいけない境目＝限度",
   relatedWords:[
     {word:"unlimited",meaning:"無制限の",breakdown:"un（否定）＋ limit（境の土手）＋ ed（〜された）→ 境が引かれていない"},
     {word:"eliminate",meaning:"取り除く",breakdown:"e（外へ）＋ limin（敷居）→ 敷居の外へ出して中から取り除く"},
     {synonym:true,word:"restrict",meaning:"制限する",breakdown:"自由を狭める動き。limit は数量の上限を示す"},
     {synonym:true,word:"maximum",meaning:"最大限",breakdown:"いちばん大きい値。limit は越えられない境目そのもの"}]},

  {id:597,word:"forbid",partOfSpeech:"他動詞",meaning:"（人に）禁じる",
   meanings:["他|（人に）禁じる，してはいけないと言う"],
   pronunciation:"/fərˈbɪd/",part:60,
   example:"The library forbids students to bring drinks inside the room.",
   exampleJa:"図書館は生徒が室内に飲み物を持ち込むことを禁じている。",
   example2:"Her parents forbid her to go out after nine at night.",
   exampleJa2:"彼女の両親は、夜9時以降の外出を彼女に禁じている。",
   etymologyProcess:"for（打ち消し）＋ bid（命じる）→ するなと言い渡すのは…？",
   etymologyConclusion:"for（打ち消し）＋ bid（命じる）→ 「するな」と打ち消しの側から命じる＝禁じる",
   relatedWords:[
     {word:"bid",meaning:"値をつける；言う",breakdown:"bid（命じる）→ 相手に言い渡す。競りでは値を言い渡す"},
     {word:"forget",meaning:"忘れる",breakdown:"for（打ち消し）＋ get（つかむ）→ つかんでいた記憶を打ち消す"},
     {synonym:true,word:"ban",meaning:"禁止する",breakdown:"公の力で禁じる。forbid は親や先生が個人に言う場合も多い"},
     {synonym:true,word:"prohibit",meaning:"（法で）禁止する",breakdown:"法律や規則で止める硬い語。forbid は口頭でも使う"}]},

  {id:598,word:"ban",partOfSpeech:"名詞",meaning:"（公の）禁止（令）",
   meanings:["名|（公の）禁止，禁止令","他|（公に）禁止する"],
   pronunciation:"/bæn/",part:60,
   example:"The city put a ban on smoking in all its parks.",
   exampleJa:"市はすべての公園での喫煙に禁止令を出した。",
   example2:"Many countries banned the sale of that dangerous toy.",
   exampleJa2:"多くの国が、その危険なおもちゃの販売を禁止した。",
   etymologyProcess:"ban（公に言い渡す）→ おおやけに言い渡して止めるのは…？",
   etymologyConclusion:"ban（公に言い渡す）→ みんなの前で「してはならない」と言い渡す決まり＝禁止令",
   relatedWords:[
     {word:"banish",meaning:"追放する",breakdown:"ban（公に言い渡す）＋ ish（〜にする）→ 出ていけと公に言い渡す"},
     {word:"abandon",meaning:"見捨てる",breakdown:"ad（〜へ）＋ ban（公に言い渡す）→ もう関わらないと言い放って手放す"},
     {synonym:true,word:"forbid",meaning:"禁じる",breakdown:"人に向かって禁じる。ban は公の決まりとして出される"},
     {synonym:true,word:"prohibition",meaning:"禁止",breakdown:"法による禁止の硬い語。ban は新聞などでよく使う"}]},

  {id:599,word:"refuse",partOfSpeech:"他動詞",meaning:"（申し出を）断る，拒む",
   meanings:["他|（申し出・要求を）断る，拒む"],
   pronunciation:"/rɪˈfjuːz/",part:60,
   example:"He refused the offer because the work was too dangerous.",
   exampleJa:"仕事が危険すぎたので、彼はその申し出を断った。",
   example2:"She refuses to answer any question about her private life.",
   exampleJa2:"彼女は私生活についての質問には、どれも答えるのを拒む。",
   etymologyProcess:"re（戻す）＋ fuse（注ぐ）→ 差し出された物を注ぎ返すと…？",
   etymologyConclusion:"re（戻す）＋ fuse（注ぐ）→ 差し出された物を相手のほうへ注ぎ返す＝断る",
   relatedWords:[
     {word:"refusal",meaning:"拒否",breakdown:"re（戻す）＋ fuse（注ぐ）＋ al（名詞）→ 受け取らずに返す行いそのもの"},
     {word:"confuse",meaning:"混乱させる",breakdown:"con（共に）＋ fuse（注ぐ）→ いろいろを一緒に注ぎ混ぜて分からなくする"},
     {synonym:true,word:"decline",meaning:"（丁寧に）辞退する",breakdown:"やわらかく断る。refuse ははっきりした拒否"},
     {synonym:true,word:"accept",meaning:"受け入れる",breakdown:"refuse の反対。差し出された物を受け取る"}]},

  {id:600,word:"reject",partOfSpeech:"他動詞",meaning:"（受け入れず）はねつける",
   meanings:["他|（案・応募を）はねつける，不採用にする"],
   pronunciation:"/rɪˈdʒekt/",part:60,
   example:"The company rejected his plan without reading it carefully.",
   exampleJa:"その会社は、彼の案をよく読まずにはねつけた。",
   example2:"My idea was rejected, but the teacher told me to try again.",
   exampleJa2:"私の考えははねつけられたが、先生はもう一度やれと言った。",
   etymologyProcess:"re（後ろへ）＋ ject（投げる）→ 差し出された物を投げ返すと…？",
   etymologyConclusion:"re（後ろへ）＋ ject（投げる）→ 差し出された物を後ろへ投げ返して受け取らない＝はねつける",
   relatedWords:[
     {word:"project",meaning:"計画；映し出す",breakdown:"pro（前へ）＋ ject（投げる）→ 先へ投げ出した計画や映像"},
     {word:"inject",meaning:"注射する",breakdown:"in（中へ）＋ ject（投げる）→ 体の中へ薬を勢いよく投げ入れる"},
     {word:"object",meaning:"反対する；物",breakdown:"op（向かい合って）＋ ject（投げる）→ 向かいへ投げ返して反対する"},
     {synonym:true,word:"refuse",meaning:"断る",breakdown:"申し出を受け取らない。reject は選んで落とす場面で多い"}]},

  {id:601,word:"persuade",partOfSpeech:"他動詞",meaning:"（話して）説得する",
   meanings:["他|（話して）説得する，説き伏せる"],
   pronunciation:"/pərˈsweɪd/",part:61,
   example:"She persuaded her father to buy a new bicycle for her.",
   exampleJa:"彼女は父を説得して、新しい自転車を買ってもらった。",
   example2:"We could not persuade him to join the morning practice.",
   exampleJa2:"私たちは彼を説得して朝練に参加させることはできなかった。",
   etymologyProcess:"per（すっかり）＋ suade（すすめる）→ 心が動くまですすめると…？",
   etymologyConclusion:"per（すっかり）＋ suade（すすめる）→ 相手の心がすっかり動くまですすめ続ける＝説得する",
   relatedWords:[
     {word:"persuasion",meaning:"説得",breakdown:"per（すっかり）＋ suas（すすめる）＋ ion（名詞）→ 心を動かしきること"},
     {word:"dissuade",meaning:"思いとどまらせる",breakdown:"dis（否定）＋ suade（すすめる）→ やめるほうをすすめて止める"},
     {synonym:true,word:"convince",meaning:"確信させる",breakdown:"頭で納得させる。persuade は行動まで起こさせる"},
     {synonym:true,word:"encourage",meaning:"励ます",breakdown:"勇気を与える。persuade は言葉で考えを変えさせる"}]},

  {id:602,word:"convince",partOfSpeech:"他動詞",meaning:"（証拠で）確信させる，納得させる",
   meanings:["他|（証拠で）確信させる，納得させる"],
   pronunciation:"/kənˈvɪns/",part:61,
   example:"His careful data convinced the teacher that the plan would work.",
   exampleJa:"彼の丁寧なデータは、その計画がうまくいくと先生を納得させた。",
   example2:"I am convinced that she will pass the exam this time.",
   exampleJa2:"私は今度こそ彼女が試験に受かると確信している。",
   etymologyProcess:"con（すっかり）＋ vinc（打ち勝つ）→ 相手の疑いに勝つと…？",
   etymologyConclusion:"con（すっかり）＋ vinc（打ち勝つ）→ 相手の疑いにすっかり打ち勝って信じ込ませる＝確信させる",
   relatedWords:[
     {word:"convincing",meaning:"説得力のある",breakdown:"con（すっかり）＋ vinc（打ち勝つ）＋ ing（形容詞）→ 疑いに勝つ力がある"},
     {word:"province",meaning:"州，地方",breakdown:"pro（前へ）＋ vinc（打ち勝つ）→ 攻め勝って治めた土地"},
     {synonym:true,word:"persuade",meaning:"説得する",breakdown:"行動を起こさせる。convince は頭で納得させる"},
     {synonym:true,word:"assure",meaning:"保証する，安心させる",breakdown:"大丈夫だと請け合う。convince は証拠で信じさせる"}]},

  {id:603,word:"inspire",partOfSpeech:"他動詞",meaning:"奮起させる；（考えを）わき起こさせる",
   meanings:["他|奮起させる，やる気を起こさせる","他|（考え・作品を）わき起こさせる"],
   pronunciation:"/ɪnˈspaɪər/",part:61,
   example:"Her speech inspired many students to start their own projects.",
   exampleJa:"彼女の演説は、多くの生徒を奮起させ、自分の企画を始めさせた。",
   example2:"The night sky inspired him to write a short poem.",
   exampleJa2:"夜空が彼を奮い立たせ、短い詩を書かせた。",
   etymologyProcess:"in（中へ）＋ spir（息をする）→ 相手の中へ息を吹き込むと…？",
   etymologyConclusion:"in（中へ）＋ spir（息をする）→ 相手の中へ新しい息を吹き込んで動かす＝奮起させる",
   relatedWords:[
     {word:"spirit",meaning:"精神，気力",breakdown:"spir（息をする）＋ it（もの）→ 体に吹き込まれた息。そこから心や気力"},
     {word:"expire",meaning:"期限が切れる",breakdown:"ex（外へ）＋ spir（息をする）→ 息を外へ吐ききって終わる"},
     {synonym:true,word:"encourage",meaning:"励ます",breakdown:"勇気を出させる。inspire は心に火をつける感じ"},
     {synonym:true,word:"motivate",meaning:"やる気にさせる",breakdown:"動機を与える。inspire は感動によって動かす"}]},

  {id:604,word:"discourage",partOfSpeech:"他動詞",meaning:"やる気をなくさせる",
   meanings:["他|やる気をなくさせる，落胆させる","他|（人に）思いとどまらせる"],
   pronunciation:"/dɪsˈkɜːrɪdʒ/",part:61,
   example:"One bad score should not discourage you from studying more.",
   exampleJa:"一度の悪い点で、もっと学ぶ気をなくしてはいけない。",
   example2:"The long rain discouraged the members of the tennis club.",
   exampleJa2:"長雨はテニス部の部員たちのやる気をなくさせた。",
   etymologyProcess:"dis（否定）＋ cour（心）＋ age（名詞）→ 心から勇気を抜くと…？",
   etymologyConclusion:"dis（否定）＋ cour（心）＋ age（名詞）→ 相手の心から勇気を抜き取ってしまう＝やる気をなくさせる",
   relatedWords:[
     {word:"courage",meaning:"勇気",breakdown:"cour（心）＋ age（名詞）→ 心の底からわき上がってくる力"},
     {word:"encourage",meaning:"励ます",breakdown:"en（〜にする）＋ cour（心）＋ age（名詞）→ 相手の心に勇気を入れてやる"},
     {word:"courageous",meaning:"勇敢な",breakdown:"cour（心）＋ age（名詞）＋ ous（〜に満ちた）→ 勇気に満ちているようす"},
     {synonym:true,word:"depress",meaning:"落ち込ませる",breakdown:"気分を押し下げる。discourage は行動する気を奪う"}]},

  {id:605,word:"promote",partOfSpeech:"他動詞",meaning:"促進する；昇進させる",
   meanings:["他|（成長・販売を）促進する","他|昇進させる"],
   pronunciation:"/prəˈmoʊt/",part:61,
   example:"Walking every day promotes good health in people of all ages.",
   exampleJa:"毎日歩くことは、どの年代の人の健康も促進する。",
   example2:"The company promoted her to manager after only three years.",
   exampleJa2:"その会社はわずか3年で彼女を部長に昇進させた。",
   etymologyProcess:"pro（前へ）＋ mot（動かす）→ 物事を前のほうへ動かすと…？",
   etymologyConclusion:"pro（前へ）＋ mot（動かす）→ 物事や人を前のほうへ動かして進みを助ける＝促進する",
   relatedWords:[
     {word:"promotion",meaning:"昇進；販売促進",breakdown:"pro（前へ）＋ mot（動かす）＋ ion（名詞）→ 前へ動かして位や売上を上げること"},
     {word:"motive",meaning:"動機",breakdown:"mot（動かす）＋ ive（〜な性質の）→ 心を内から動かして行動へ押し出す力"},
     {word:"remove",meaning:"取り除く",breakdown:"re（後ろへ）＋ mov（動かす）→ 元の場所から動かして外へ出す"},
     {synonym:true,word:"boost",meaning:"押し上げる",breakdown:"下から勢いよく上げる。promote はじわじわ後押しする"}]},

  {id:606,word:"boost",partOfSpeech:"他動詞",meaning:"（数量・勢いを）押し上げる",
   meanings:["他|（数量・勢い・自信を）押し上げる","名|押し上げ，後押し"],
   pronunciation:"/buːst/",part:61,
   example:"The new shop boosted the number of visitors to our town.",
   exampleJa:"新しい店が、町を訪れる人の数を押し上げた。",
   example2:"Winning one small game can boost a young player's confidence.",
   exampleJa2:"小さな試合に一つ勝つだけで、若い選手の自信は押し上がる。",
   hook:"下から「ぐいっと」持ち上げる感じ。売上・自信・電波などに使う。",
   etymologyProcess:"boost（下から押し上げる）→ 勢いよく下から持ち上げると…？",
   etymologyConclusion:"boost（下から押し上げる）→ 下から勢いよく持ち上げて数や勢いを増やす＝押し上げる",
   relatedWords:[
     {word:"booster",meaning:"補助装置；追加の一押し",breakdown:"boost（下から押し上げる）＋ er（もの）→ 下から力を加える装置"},
     {synonym:true,word:"increase",meaning:"増やす",breakdown:"数を増す。boost は一気に押し上げる勢いがある"},
     {synonym:true,word:"promote",meaning:"促進する",breakdown:"進みを助ける。boost は数値をぐっと上げる"},
     {synonym:true,word:"raise",meaning:"上げる",breakdown:"位置や値を上げる。boost は勢いよく短期間で上げる"}]},

  {id:607,word:"expand",partOfSpeech:"他動詞・自動詞",meaning:"（面積・規模を）拡大する",
   meanings:["他|（面積・規模を）拡大する","自|膨張する，広がる"],
   pronunciation:"/ɪkˈspænd/",part:61,
   example:"The company expanded its business into three other countries.",
   exampleJa:"その会社は事業を他の3か国へ拡大した。",
   example2:"Metal expands a little when it is heated over a fire.",
   exampleJa2:"金属は火で熱せられると少し膨張する。",
   etymologyProcess:"ex（外へ）＋ pand（広げる）→ たたんだ物を外へ開くと…？",
   etymologyConclusion:"ex（外へ）＋ pand（広げる）→ たたんであった物を外へ開いて大きくする＝拡大する",
   relatedWords:[
     {word:"expansion",meaning:"拡大，膨張",breakdown:"ex（外へ）＋ pans（広げる）＋ ion（名詞）→ 外へ開いて大きくなること"},
     {synonym:true,word:"enlarge",meaning:"大きくする",breakdown:"サイズを大きくする。expand は面積や規模が外へ広がる"},
     {synonym:true,word:"extend",meaning:"延長する",breakdown:"長さを伸ばす。expand は四方へふくらむ"},
     {synonym:true,word:"grow",meaning:"成長する",breakdown:"ひとりでに育つ。expand は意図して広げる場合も多い"}]},

  {id:608,word:"extend",partOfSpeech:"他動詞",meaning:"（期間・長さを）延長する",
   meanings:["他|（期間・長さを）延長する","他|（手・足を）伸ばす"],
   pronunciation:"/ɪkˈstend/",part:61,
   example:"The library extended its opening hours during the exam week.",
   exampleJa:"図書館は試験週間の間、開館時間を延長した。",
   example2:"He extended his arm and caught the ball just in time.",
   exampleJa2:"彼は腕を伸ばし、ぎりぎりでボールを捕まえた。",
   etymologyProcess:"ex（外へ）＋ tend（伸ばす）→ 端を外へぐっと伸ばすと…？",
   etymologyConclusion:"ex（外へ）＋ tend（伸ばす）→ 端を外のほうへ伸ばして、届く先を長くする＝延長する",
   relatedWords:[
     {word:"extension",meaning:"延長；内線",breakdown:"ex（外へ）＋ tens（伸ばす）＋ ion（名詞）→ 外へ伸ばして継ぎ足した部分"},
     {word:"intend",meaning:"〜するつもりだ",breakdown:"in（中へ）＋ tend（伸ばす）→ 心を的へぴんと伸ばして向ける"},
     {word:"attend",meaning:"出席する",breakdown:"ad（〜へ）＋ tend（伸ばす）→ 心をそちらへ伸ばして出向く"},
     {synonym:true,word:"lengthen",meaning:"長くする",breakdown:"長さを足す。extend は期間や範囲にも使える"}]},

  {id:609,word:"broaden",partOfSpeech:"他動詞",meaning:"（視野・幅を）広げる",
   meanings:["他|（視野・幅を）広げる","自|広がる"],
   pronunciation:"/ˈbrɔːdn̩/",part:61,
   example:"Traveling alone will broaden your view of the whole world.",
   exampleJa:"ひとり旅は、世界全体を見るあなたの視野を広げるだろう。",
   example2:"The city broadened the old road in front of our station.",
   exampleJa2:"市は駅前の古い道路の幅を広げた。",
   etymologyProcess:"broad（広い）＋ en（〜にする）→ 幅そのものを広くすると…？",
   etymologyConclusion:"broad（広い）＋ en（〜にする）→ 端から端までの幅を、もっと広い状態にする＝広げる",
   relatedWords:[
     {word:"broad",meaning:"幅の広い",breakdown:"broad（広い）→ 端から端までがゆったりしている"},
     {word:"broadcast",meaning:"放送する",breakdown:"broad（広い）＋ cast（投げる）→ 種をまくように広く投げ広める"},
     {word:"widen",meaning:"広くする",breakdown:"wid（広い）＋ en（〜にする）→ 幅を前より広い状態にする"},
     {synonym:true,word:"expand",meaning:"拡大する",breakdown:"四方へふくらむ。broaden は幅や視野が広がる"}]},

  {id:610,word:"spread",partOfSpeech:"他動詞・自動詞",meaning:"（うわさ・病気が）広まる；塗り広げる",
   meanings:["自|（うわさ・病気が）広まる","他|（一面に）広げる，塗り広げる"],
   pronunciation:"/spred/",part:61,
   example:"News of the accident spread through the school in minutes.",
   exampleJa:"事故の知らせは、数分で学校じゅうに広まった。",
   example2:"He spreads butter on his toast every morning before school.",
   exampleJa2:"彼は毎朝、登校前にトーストにバターを塗り広げる。",
   hook:"過去形も過去分詞も spread。「塗り広げる」も「うわさが広まる」も同じ形。",
   etymologyProcess:"spread（まき広げる）→ 一面にまいて行き渡らせるのは…？",
   etymologyConclusion:"spread（まき広げる）→ 一面にまいて、すみずみまで行き渡らせる＝広まる",
   relatedWords:[
     {word:"widespread",meaning:"広く行き渡った",breakdown:"wide（広い）＋ spread（まき広げる）→ 広い範囲にまき広げられた"},
     {synonym:true,word:"scatter",meaning:"まき散らす",breakdown:"ばらばらにまく。spread は面をおおうように広がる"},
     {synonym:true,word:"distribute",meaning:"配る",breakdown:"人に分け配る。spread はひとりでに広がる場合にも使う"},
     {synonym:true,word:"expand",meaning:"拡大する",breakdown:"規模が大きくなる。spread は面に沿って行き渡る"}]},

  {id:611,word:"tie",partOfSpeech:"他動詞",meaning:"（ひもで）縛る，結ぶ",
   meanings:["他|（ひもで）縛る，結ぶ","名|ネクタイ；同点"],
   pronunciation:"/taɪ/",part:62,
   example:"He tied the old newspapers together with a strong string.",
   exampleJa:"彼は古新聞を丈夫なひもで縛ってまとめた。",
   example2:"Please tie your hair back before you enter the kitchen.",
   exampleJa2:"台所に入る前に、髪を後ろで結んでください。",
   hook:"「同点」の意味もある。両者を結んで差がなくなる、と考えるとつながる。",
   etymologyProcess:"tie（結ぶ）→ 両端を結んで動けなくするのは…？",
   etymologyConclusion:"tie（結ぶ）→ ひもの両端を結び合わせて、動かないようにする＝縛る",
   relatedWords:[
     {word:"necktie",meaning:"ネクタイ",breakdown:"neck（首）＋ tie（結ぶ）→ 首に結んで前へたらす布"},
     {synonym:true,word:"bind",meaning:"縛る，束ねる",breakdown:"ぐるぐる巻いて留める硬い語。tie は結び目を作る"},
     {synonym:true,word:"knot",meaning:"結び目",breakdown:"ひもを結んでできた固まり。tie はその動作"},
     {synonym:true,word:"fasten",meaning:"しっかり留める",breakdown:"金具などで留める。tie はひもで結んで留める"}]},

  {id:612,word:"fasten",partOfSpeech:"他動詞",meaning:"（ベルトなどを）しっかり留める",
   meanings:["他|（ベルト・ボタンを）しっかり留める"],
   pronunciation:"/ˈfæsn̩/",part:62,
   example:"Please fasten your seat belt before the bus starts moving.",
   exampleJa:"バスが動き出す前に、シートベルトをしっかり留めてください。",
   example2:"She fastened the top button of her coat against the wind.",
   exampleJa2:"彼女は風よけに、コートの一番上のボタンをしっかり留めた。",
   etymologyProcess:"fast（しっかり固定した）＋ en（〜にする）→ 動かなくすると…？",
   etymologyConclusion:"fast（しっかり固定した）＋ en（〜にする）→ 動かないようにぴたりと留める＝しっかり留める",
   relatedWords:[
     {word:"fast",meaning:"速い；しっかり固定して",breakdown:"fast（しっかり固定した）→ もとは「しっかり」。離されない＝速い"},
     {synonym:true,word:"tie",meaning:"ひもで結ぶ",breakdown:"ひもで結ぶ。fasten は金具やボタンでも留められる"},
     {synonym:true,word:"lock",meaning:"鍵をかける",breakdown:"鍵で開かなくする。fasten は鍵がなくても留めること"},
     {synonym:true,word:"attach",meaning:"くっつける",breakdown:"別の物を付け足す。fasten はすでにある物を留める"}]},

  {id:613,word:"fix",partOfSpeech:"他動詞",meaning:"修理する；（日時を）決める",
   meanings:["他|修理する，直す","他|（日時・値段を）決める","他|しっかり取り付ける"],
   pronunciation:"/fɪks/",part:62,
   example:"My brother fixed the broken chair with a hammer and nails.",
   exampleJa:"兄は壊れた椅子を、金づちと釘で修理した。",
   example2:"We have not fixed the date of the school festival yet.",
   exampleJa2:"私たちはまだ文化祭の日取りを決めていない。",
   etymologyProcess:"fix（打ち込む）→ 釘を打ち込んで動かなくするのは…？",
   etymologyConclusion:"fix（打ち込む）→ 釘を打ち込むように、ぐらつく所をきちんと収めて動かなくする＝修理する",
   relatedWords:[
     {word:"fixed",meaning:"固定した，決まった",breakdown:"fix（打ち込む）＋ ed（〜された）→ 打ち込まれてもう動かない"},
     {word:"prefix",meaning:"接頭辞",breakdown:"pre（先に）＋ fix（打ち込む）→ 語の先に打ち込まれた部分"},
     {word:"suffix",meaning:"接尾辞",breakdown:"suf（下で）＋ fix（打ち込む）→ 語の後ろに打ち込まれた部分"},
     {synonym:true,word:"repair",meaning:"修理する",breakdown:"壊れた所を直す硬い語。fix は日常でよく使う"}]},

  {id:614,word:"install",partOfSpeech:"他動詞",meaning:"（機械・ソフトを）設置する",
   meanings:["他|（機械・設備を）設置する","他|（ソフトを）入れる"],
   pronunciation:"/ɪnˈstɔːl/",part:62,
   example:"The school installed new air conditioners in every classroom.",
   exampleJa:"学校はすべての教室に新しいエアコンを設置した。",
   example2:"I installed a free dictionary app on my old tablet.",
   exampleJa2:"私は古いタブレットに無料の辞書アプリを入れた。",
   etymologyProcess:"in（中へ）＋ stall（置き場）→ 決まった置き場へ据えると…？",
   etymologyConclusion:"in（中へ）＋ stall（置き場）→ 決められた置き場の中へ、きちんと据えつける＝設置する",
   relatedWords:[
     {word:"stall",meaning:"屋台；（機械が）止まる",breakdown:"stall（置き場）→ 家畜や品物を置く、仕切られた小さな場所"},
     {word:"installation",meaning:"設置",breakdown:"in（中へ）＋ stall（置き場）＋ ation（名詞）→ 置き場に据えつけること"},
     {synonym:true,word:"equip",meaning:"備え付ける",breakdown:"必要な道具をそろえる。install は一つずつ据える"},
     {synonym:true,word:"place",meaning:"置く",breakdown:"ただ置く。install は動くように据えて使えるようにする"}]},

  {id:615,word:"resist",partOfSpeech:"他動詞",meaning:"抵抗する；（誘惑を）我慢する",
   meanings:["他|（力・変化に）抵抗する","他|（誘惑を）我慢する"],
   pronunciation:"/rɪˈzɪst/",part:62,
   example:"The villagers resisted the plan to build a large dam.",
   exampleJa:"村人たちは大きなダムを建てる計画に抵抗した。",
   example2:"I could not resist the smell of freshly baked bread.",
   exampleJa2:"私は焼きたてのパンのにおいを我慢できなかった。",
   etymologyProcess:"re（後ろへ）＋ sist（立つ）→ 押されても踏ん張って立つと…？",
   etymologyConclusion:"re（後ろへ）＋ sist（立つ）→ 押されても後ろで踏ん張り、そのまま立ち続ける＝抵抗する",
   relatedWords:[
     {word:"assist",meaning:"手伝う",breakdown:"ad（〜へ）＋ sist（立つ）→ 相手のそばに立って力を貸す"},
     {word:"insist",meaning:"言い張る",breakdown:"in（上に）＋ sist（立つ）→ 自分の考えの上に立ち続けて譲らない"},
     {word:"consist",meaning:"〜から成る",breakdown:"con（共に）＋ sist（立つ）→ 部品が共に立って全体を作る"},
     {synonym:true,word:"endure",meaning:"耐える",breakdown:"苦しさに耐え続ける。resist は押し返す力が中心"}]},

  {id:616,word:"obey",partOfSpeech:"他動詞・自動詞",meaning:"（命令・規則に）従う",
   meanings:["他|（命令・規則に）従う","自|言うとおりにする"],
   pronunciation:"/oʊˈbeɪ/",part:62,
   example:"All drivers must obey the signs at this busy corner.",
   exampleJa:"すべての運転手は、この混んだ角では標識に従わねばならない。",
   example2:"The dog obeyed her voice and sat down at once.",
   exampleJa2:"その犬は彼女の声に従って、すぐに座った。",
   etymologyProcess:"ob（向かい合って）＋ ey（聞く）→ 耳を傾けてそのとおりにすると…？",
   etymologyConclusion:"ob（向かい合って）＋ ey（聞く）→ 相手に向き合って耳を傾け、言うとおりにする＝従う",
   relatedWords:[
     {word:"obedient",meaning:"従順な",breakdown:"ob（向かい合って）＋ edi（聞く）＋ ent（〜している）→ よく耳を傾けている"},
     {word:"disobey",meaning:"従わない",breakdown:"dis（否定）＋ ob（向かい合って）＋ ey（聞く）→ 言うことに耳を貸さない"},
     {word:"audience",meaning:"聴衆",breakdown:"aud（聞く）＋ ence（名詞）→ 耳を傾けるために集まった人々"},
     {synonym:true,word:"follow",meaning:"（規則に）従う",breakdown:"あとをたどる。obey は命令に対する服従が中心"}]},

  {id:617,word:"engage",partOfSpeech:"他動詞・自動詞",meaning:"（仕事に）従事する；引き込む",
   meanings:["自|（仕事・活動に）従事する","他|（関心を）引き込む"],
   pronunciation:"/ɪnˈɡeɪdʒ/",part:62,
   example:"Many students engage in volunteer work during the summer holidays.",
   exampleJa:"多くの生徒が夏休みの間、ボランティア活動に従事する。",
   example2:"The story engaged the children from the very first page.",
   exampleJa2:"その物語は最初の1ページから子どもたちを引き込んだ。",
   etymologyProcess:"en（中に）＋ gage（担保）→ 担保を差し入れて身を置くと…？",
   etymologyConclusion:"en（中に）＋ gage（担保）→ 担保を差し入れる約束をして、その仕事の中に身を置く＝従事する",
   relatedWords:[
     {word:"engagement",meaning:"婚約；約束",breakdown:"en（中に）＋ gage（担保）＋ ment（名詞）→ 担保を差し入れて結んだ約束"},
     {word:"wage",meaning:"賃金",breakdown:"wag（約束の担保）→ 働くという約束のしるしに渡されるお金"},
     {synonym:true,word:"involve",meaning:"巻き込む",breakdown:"中へ巻き込む。engage は自分から身を入れる場合が多い"},
     {synonym:true,word:"participate",meaning:"参加する",breakdown:"一員として加わる。engage は深く関わり続ける感じ"}]},

  {id:618,word:"bump",partOfSpeech:"自動詞",meaning:"（ドンと）ぶつかる",
   meanings:["自|（ドンと）ぶつかる","名|こぶ；でこぼこ"],
   pronunciation:"/bʌmp/",part:62,
   example:"He bumped into the door because he was reading a message.",
   exampleJa:"メッセージを読んでいたので、彼はドアにぶつかった。",
   example2:"Be careful not to bump your head on that low ceiling.",
   exampleJa2:"あの低い天井に頭をぶつけないよう気をつけて。",
   hook:"bump into ～ は「～にばったり出会う」。ドンという音がそのまま語になった。",
   etymologyProcess:"bump（ドンと当たる音）→ 音を立てて物に当たるのは…？",
   etymologyConclusion:"bump（ドンと当たる音）→ ドンと音を立てて物や人に当たってしまう＝ぶつかる",
   relatedWords:[
     {word:"bumper",meaning:"（車の）バンパー",breakdown:"bump（ドンと当たる音）＋ er（もの）→ ぶつかる衝撃を受け止める部品"},
     {synonym:true,word:"crash",meaning:"激突する",breakdown:"大きな音で激しくぶつかる。bump は軽い衝突"},
     {synonym:true,word:"collide",meaning:"衝突する",breakdown:"正面からぶつかる硬い語。bump は日常の軽い接触"},
     {synonym:true,word:"hit",meaning:"当たる，打つ",breakdown:"当てる全般。bump は思いがけず当たってしまう"}]},

  {id:619,word:"bend",partOfSpeech:"他動詞・自動詞",meaning:"曲げる；身をかがめる",
   meanings:["他|（まっすぐな物を）曲げる","自|身をかがめる"],
   pronunciation:"/bend/",part:62,
   example:"Do not bend this card, or the machine cannot read it.",
   exampleJa:"このカードを曲げないで。機械が読み取れなくなる。",
   example2:"She bends down to tie her shoes before every race.",
   exampleJa2:"彼女はどのレースの前にも、身をかがめて靴ひもを結ぶ。",
   hook:"過去形は bent。bend over は「かがむ」、bend the rules は「規則を曲げる」。",
   etymologyProcess:"bend（弓の弦を張る）→ 弓のように弧を描かせるのは…？",
   etymologyConclusion:"bend（弓の弦を張る）→ 弓に弦を張るように、まっすぐな物を弧の形にする＝曲げる",
   relatedWords:[
     {synonym:true,word:"curve",meaning:"曲線；曲がる",breakdown:"なめらかな曲線を描く。bend は力を加えて曲げる"},
     {synonym:true,word:"fold",meaning:"折りたたむ",breakdown:"折り目をつけて重ねる。bend は折り目をつけずに曲げる"},
     {synonym:true,word:"lean",meaning:"体を傾ける",breakdown:"体を斜めにする。bend は体そのものを折り曲げる"},
     {synonym:true,word:"bow",meaning:"おじぎする",breakdown:"敬意を表して上体を曲げる。bend は物にも使う"}]},

  {id:620,word:"hug",partOfSpeech:"他動詞",meaning:"抱きしめる",
   meanings:["他|抱きしめる","名|抱擁"],
   pronunciation:"/hʌɡ/",part:62,
   example:"She hugs her little brother every time he starts crying.",
   exampleJa:"彼女は弟が泣き出すたびに、彼を抱きしめる。",
   example2:"Players hug each other after winning a hard-fought final game.",
   exampleJa2:"選手たちは苦しい決勝に勝ったあと、たがいに抱きしめ合う。",
   hook:"give ～ a hug で「～をぎゅっと抱く」。もとは「なぐさめる」という意味。",
   etymologyProcess:"hug（なぐさめ包む）→ 両腕で包んで引き寄せるのは…？",
   etymologyConclusion:"hug（なぐさめ包む）→ 両腕で相手を包み込み、そっと引き寄せる＝抱きしめる",
   relatedWords:[
     {synonym:true,word:"embrace",meaning:"抱きしめる",breakdown:"腕の中に迎え入れる硬い語。hug は日常の気軽な抱擁"},
     {synonym:true,word:"hold",meaning:"抱える，持つ",breakdown:"手や腕で支える。hug は気持ちを込めて包み込む"},
     {synonym:true,word:"cuddle",meaning:"寄り添って抱く",breakdown:"長く寄り添って抱く。hug は一度ぎゅっと抱く動作"}]},

  {id:621,word:"stare",partOfSpeech:"自動詞",meaning:"（驚いて）じっと見つめる",
   meanings:["自|（驚いて・無遠慮に）じっと見つめる"],
   pronunciation:"/ster/",part:63,
   example:"The little boy stared at the huge fish in the tank.",
   exampleJa:"その小さな男の子は、水槽の巨大な魚をじっと見つめた。",
   example2:"Do not stare at people on the train; it is rude.",
   exampleJa2:"電車で人をじっと見つめてはいけない。失礼だから。",
   etymologyProcess:"stare（こわばる）→ 目を固めたまま動かさずにいるのは…？",
   etymologyConclusion:"stare（こわばる）→ 目が固まったように動かず、同じ所を見続ける＝じっと見つめる",
   relatedWords:[
     {word:"starve",meaning:"飢える",breakdown:"starv（こわばって死ぬ）→ 体がこわばるほど食べ物がない"},
     {synonym:true,word:"gaze",meaning:"見つめる",breakdown:"うっとり見とれる。stare は驚きや無遠慮さがある"},
     {synonym:true,word:"glare",meaning:"にらみつける",breakdown:"怒って強く見る。stare は感情が怒りとは限らない"},
     {synonym:true,word:"watch",meaning:"（動くものを）見る",breakdown:"動きを追って見る。stare は動かずに見続ける"}]},

  {id:622,word:"gaze",partOfSpeech:"自動詞",meaning:"（うっとり）見つめる",
   meanings:["自|（うっとり・じっと）見つめる","名|視線"],
   pronunciation:"/ɡeɪz/",part:63,
   example:"They gazed at the stars from the roof of the school.",
   exampleJa:"彼らは校舎の屋上から星をうっとりと見つめた。",
   example2:"She gazes out of the window whenever the class gets boring.",
   exampleJa2:"授業が退屈になると、彼女はいつも窓の外を見つめる。",
   hook:"gaze at ～ の形で使う。stare が無遠慮なら、gaze は見とれる感じ。",
   etymologyProcess:"gaze（目を注ぐ）→ 心を奪われて長く目を向けるのは…？",
   etymologyConclusion:"gaze（目を注ぐ）→ 心を奪われて、長いあいだ静かに目を注ぎ続ける＝見つめる",
   relatedWords:[
     {synonym:true,word:"stare",meaning:"じっと見つめる",breakdown:"驚きや無遠慮さがある。gaze は美しさに見とれる"},
     {synonym:true,word:"glance",meaning:"ちらりと見る",breakdown:"一瞬だけ見る。gaze は長く見つめ続ける"},
     {synonym:true,word:"admire",meaning:"見とれる，感心する",breakdown:"すばらしいと思う気持ち。gaze はその目の動き"}]},

  {id:623,word:"glance",partOfSpeech:"自動詞",meaning:"ちらりと見る",
   meanings:["自|ちらりと見る，ひと目見る","名|一瞥"],
   pronunciation:"/ɡlæns/",part:63,
   example:"He glanced at his watch and hurried toward the back gate.",
   exampleJa:"彼は時計をちらりと見て、裏門のほうへ急いだ。",
   example2:"Please glance over this page before you answer the questions.",
   exampleJa2:"問題に答える前に、このページにざっと目を通してください。",
   hook:"at a glance は「ひと目で」。光がすっとすべる速さが目の動きに重なる。",
   etymologyProcess:"glance（すべって光る）→ 目を一瞬だけ走らせるのは…？",
   etymologyConclusion:"glance（すべって光る）→ 光がすっとすべるように、目を短く走らせる＝ちらりと見る",
   relatedWords:[
     {synonym:true,word:"glimpse",meaning:"ちらりと目に入る",breakdown:"見ようとせず目に入る。glance は自分から見る動作"},
     {synonym:true,word:"peek",meaning:"のぞき見る",breakdown:"こっそりのぞく。glance は隠れずにさっと見る"},
     {synonym:true,word:"stare",meaning:"じっと見つめる",breakdown:"glance の反対。動かずに長く見続ける"}]},

  {id:624,word:"glimpse",partOfSpeech:"名詞",meaning:"ちらりと見えること",
   meanings:["名|ちらりと見えること，垣間見ること","他|ちらりと目にする"],
   pronunciation:"/ɡlɪmps/",part:63,
   example:"I caught a glimpse of the singer as the car passed.",
   exampleJa:"車が通り過ぎるとき、私はその歌手をちらりと見かけた。",
   example2:"This book gives us a glimpse of life a century ago.",
   exampleJa2:"この本は、百年前の暮らしを垣間見せてくれる。",
   hook:"catch a glimpse of ～（～をちらりと見かける）の形でほぼ決まって使う。",
   etymologyProcess:"glimpse（かすかに光る）→ 一瞬だけ光るように目に入るのは…？",
   etymologyConclusion:"glimpse（かすかに光る）→ 一瞬かすかに光るように、目の端に入ってくること＝ちらりと見えること",
   relatedWords:[
     {word:"glimmer",meaning:"かすかな光",breakdown:"glim（かすかに光る）＋ er（何度も）→ 弱い光がちらちら揺れること"},
     {synonym:true,word:"glance",meaning:"ちらりと見る",breakdown:"自分から短く見る。glimpse は向こうから目に入る"},
     {synonym:true,word:"sight",meaning:"見えること，光景",breakdown:"目に映るもの全般。glimpse は一瞬だけのそれ"}]},

  {id:625,word:"stretch",partOfSpeech:"他動詞・自動詞",meaning:"（引っ張って）伸ばす",
   meanings:["他|（引っ張って）伸ばす","自|伸びる；（土地が）広がる"],
   pronunciation:"/stretʃ/",part:63,
   example:"Please stretch your arms high above your head for ten seconds.",
   exampleJa:"10秒間、頭の上に高く腕を伸ばしてください。",
   example2:"This old sweater stretched after I washed it in hot water.",
   exampleJa2:"この古いセーターは、お湯で洗ったら伸びてしまった。",
   hook:"stretch out は「手足を伸ばす」。a stretch of ～ は「ひと続きの～」。",
   etymologyProcess:"stretch（ぴんと張る）→ ぴんと張って長さを増すのは…？",
   etymologyConclusion:"stretch（ぴんと張る）→ 両端を引っ張ってぴんと張り、長さや広さを増す＝伸ばす",
   relatedWords:[
     {synonym:true,word:"extend",meaning:"延長する",breakdown:"端を外へ伸ばす。stretch は引っ張る力を感じさせる"},
     {synonym:true,word:"expand",meaning:"拡大する",breakdown:"四方へふくらむ。stretch は一方向へ引き伸ばす"},
     {synonym:true,word:"reach",meaning:"手を伸ばして届く",breakdown:"届くところまで伸ばす。stretch は伸ばす動作そのもの"}]},

  {id:626,word:"stumble",partOfSpeech:"自動詞",meaning:"つまずく，よろめく",
   meanings:["自|つまずく，よろめく","自|（言葉に）つっかえる"],
   pronunciation:"/ˈstʌmbl̩/",part:63,
   example:"He stumbled on a stone and dropped all his books.",
   exampleJa:"彼は石につまずいて、本を全部落としてしまった。",
   example2:"She stumbled over the long word twice during her speech.",
   exampleJa2:"彼女は演説中、その長い単語で2回つっかえた。",
   hook:"stumble on ～ は「～に偶然出くわす」。足が引っかかるように出会う。",
   etymologyProcess:"stumble（よろめく）→ 足が引っかかって体が泳ぐのは…？",
   etymologyConclusion:"stumble（よろめく）→ 足が何かに引っかかり、体が前へ泳いでしまう＝つまずく",
   relatedWords:[
     {synonym:true,word:"trip",meaning:"つまずく",breakdown:"足を引っかける。stumble はその後よろめく所まで表す"},
     {synonym:true,word:"slip",meaning:"すべる",breakdown:"足がすべる。stumble は何かに引っかかって起こる"},
     {synonym:true,word:"fall",meaning:"転ぶ，落ちる",breakdown:"実際に倒れる。stumble は倒れる手前でよろめく"}]},

  {id:627,word:"press",partOfSpeech:"他動詞",meaning:"（ボタンなどを）押す",
   meanings:["他|（ボタン・物を）押す","他|アイロンをかける","名|報道機関"],
   pronunciation:"/pres/",part:63,
   example:"Press this red button if the machine stops during the test.",
   exampleJa:"検査中に機械が止まったら、この赤いボタンを押してください。",
   example2:"She pressed her shirt carefully the night before the interview.",
   exampleJa2:"彼女は面接の前夜、シャツに丁寧にアイロンをかけた。",
   etymologyProcess:"press（押す）→ 上から力をかけて押しつけるのは…？",
   etymologyConclusion:"press（押す）→ 上から力をかけ、平らになるまで押しつける＝押す",
   relatedWords:[
     {word:"impress",meaning:"感動させる",breakdown:"im（中へ）＋ press（押す）→ 心の中に型を押しつけて跡を残す"},
     {word:"express",meaning:"表現する",breakdown:"ex（外へ）＋ press（押す）→ 思いを外へ押し出して形にする"},
     {word:"pressure",meaning:"圧力",breakdown:"press（押す）＋ ure（名詞）→ 上からのしかかってくる力"},
     {synonym:true,word:"push",meaning:"押す",breakdown:"前へ動かすために押す。press は力をかけ続ける"}]},

  {id:628,word:"drag",partOfSpeech:"他動詞",meaning:"（重い物を）引きずる",
   meanings:["他|（重い物を）引きずる","他|（画面で）ドラッグする"],
   pronunciation:"/dræɡ/",part:63,
   example:"He drags the heavy box across the floor to the wall.",
   exampleJa:"彼は重い箱を床の上を引きずって壁際まで運ぶ。",
   example2:"Do not drag your feet when you walk in the hallway.",
   exampleJa2:"廊下を歩くとき、足を引きずらないで。",
   hook:"画面の「ドラッグ」と同じ語。持ち上げずに引きずる点が pull と違う。",
   etymologyProcess:"drag（引っぱる）→ 持ち上げず地面をこすらせて引くと…？",
   etymologyConclusion:"drag（引っぱる）→ 持ち上げずに地面をこすらせたまま引っ張っていく＝引きずる",
   relatedWords:[
     {word:"draw",meaning:"引く；描く",breakdown:"draw（引っぱる）→ 手前へ引っぱる。線を引っぱれば「描く」"},
     {synonym:true,word:"pull",meaning:"引っ張る",breakdown:"手前へ引く全般。drag は重くて引きずる感じ"},
     {synonym:true,word:"haul",meaning:"（力ずくで）運ぶ",breakdown:"重い物を力で運ぶ。drag は地面に接したまま引く"},
     {synonym:true,word:"tow",meaning:"（車などを）けん引する",breakdown:"ロープでつないで引く。drag は道具なしでも使う"}]},

  {id:629,word:"lean",partOfSpeech:"自動詞",meaning:"寄りかかる；体を傾ける",
   meanings:["自|寄りかかる","自|体を傾ける","形|やせた；脂肪の少ない"],
   pronunciation:"/liːn/",part:63,
   example:"Do not lean against the door while the train is moving.",
   exampleJa:"電車が動いている間は、ドアに寄りかからないでください。",
   example2:"She leaned forward to hear the teacher's quiet voice better.",
   exampleJa2:"彼女は先生の小さな声をよく聞こうと、体を前に傾けた。",
   hook:"lean on ～ は「～に寄りかかる」、そこから「～を頼る」の意味にもなる。",
   etymologyProcess:"lean（傾ける）→ 体を斜めにして何かに預けると…？",
   etymologyConclusion:"lean（傾ける）→ 体をまっすぐから斜めにして、何かに重みを預ける＝寄りかかる",
   relatedWords:[
     {word:"decline",meaning:"断る；減少する",breakdown:"de（下へ）＋ clin（傾く）→ 下へ傾く。そらせば「断る」"},
     {synonym:true,word:"rest",meaning:"（重みを）預ける",breakdown:"支えに預けて休ませる。lean は体を傾けて預ける"},
     {synonym:true,word:"bend",meaning:"曲げる，かがむ",breakdown:"体を折り曲げる。lean は伸ばしたまま傾ける"},
     {synonym:true,word:"tilt",meaning:"傾ける",breakdown:"物を斜めにする。lean は人が何かに身を預ける"}]},

  {id:630,word:"scratch",partOfSpeech:"他動詞",meaning:"（つめで）ひっかく",
   meanings:["他|（つめ・先で）ひっかく","名|かき傷"],
   pronunciation:"/skrætʃ/",part:63,
   example:"The cat scratched my hand when I tried to hold it.",
   exampleJa:"抱こうとしたとき、そのネコは私の手をひっかいた。",
   example2:"Please do not scratch the surface of this new desk.",
   exampleJa2:"この新しい机の表面をひっかかないでください。",
   hook:"from scratch は「ゼロから」。地面に引いた線＝出発点から始める、が元。",
   etymologyProcess:"scratch（かきむしる）→ つめで表面に筋をつけるのは…？",
   etymologyConclusion:"scratch（かきむしる）→ つめや先のとがった物で、表面をかいて筋をつける＝ひっかく",
   relatedWords:[
     {synonym:true,word:"scrape",meaning:"こすり取る",breakdown:"表面をこすって削る。scratch は細い線の傷をつける"},
     {synonym:true,word:"rub",meaning:"こする",breakdown:"平らに当ててこする。scratch は先のとがった物でかく"},
     {synonym:true,word:"itch",meaning:"かゆい",breakdown:"かきたくなる感じ。scratch はそれをかく動作"}]},

  {id:631,word:"bow",partOfSpeech:"自動詞",meaning:"おじぎする",
   meanings:["自|おじぎする，頭を下げる","名|おじぎ；弓"],
   pronunciation:"/baʊ/",part:64,
   example:"Japanese players bow to each other before the match begins.",
   exampleJa:"日本の選手は試合が始まる前に、たがいにおじぎをする。",
   example2:"The old singer bowed deeply when the audience kept clapping.",
   exampleJa2:"観客が拍手を続けると、その老歌手は深くおじぎをした。",
   etymologyProcess:"bow（弓なりに曲げる）→ 上体を弓のように曲げるのは…？",
   etymologyConclusion:"bow（弓なりに曲げる）→ 上体を弓のように前へ曲げて敬意を表す＝おじぎする",
   relatedWords:[
     {word:"elbow",meaning:"ひじ",breakdown:"ell（腕の長さ）＋ bow（弓なりに曲げる）→ 腕が弓なりに曲がる所"},
     {word:"rainbow",meaning:"虹",breakdown:"rain（雨）＋ bow（弓なりに曲げる）→ 雨上がりに出る弓の形の帯"},
     {synonym:true,word:"bend",meaning:"曲げる",breakdown:"物も体も曲げる。bow は敬意を表して上体を曲げる"},
     {synonym:true,word:"nod",meaning:"うなずく",breakdown:"頭だけを小さく振る。bow は上体ごと前へ倒す"}]},

  {id:632,word:"nod",partOfSpeech:"自動詞",meaning:"うなずく",
   meanings:["自|うなずく，会釈する","名|うなずき"],
   pronunciation:"/nɑːd/",part:64,
   example:"She nods every time the teacher explains a difficult point.",
   exampleJa:"先生が難しい点を説明するたび、彼女はうなずく。",
   example2:"He nodded slowly and then signed his name on the paper.",
   exampleJa2:"彼はゆっくりうなずき、それから紙に名前を書いた。",
   hook:"nod off は「うとうとする」。居眠りで頭がこくりと落ちる様子から。",
   etymologyProcess:"nod（頭を前へ倒す）→ 頭を軽く前へ倒して示すのは…？",
   etymologyConclusion:"nod（頭を前へ倒す）→ 頭を小さく前へ倒して「はい」の気持ちを示す＝うなずく",
   relatedWords:[
     {synonym:true,word:"agree",meaning:"賛成する",breakdown:"言葉で同意する。nod は頭の動きだけで同意を示す"},
     {synonym:true,word:"bow",meaning:"おじぎする",breakdown:"上体ごと曲げる。nod は頭だけを小さく動かす"},
     {synonym:true,word:"shake",meaning:"（首を）振る",breakdown:"nod の反対。左右に振って「いいえ」を示す"}]},

  {id:633,word:"sigh",partOfSpeech:"自動詞",meaning:"ため息をつく",
   meanings:["自|ため息をつく","名|ため息"],
   pronunciation:"/saɪ/",part:64,
   example:"She sighed when she saw the long line at the gate.",
   exampleJa:"門の前の長い列を見て、彼女はため息をついた。",
   example2:"He sighs every morning before he starts his math homework.",
   exampleJa2:"彼は毎朝、数学の宿題を始める前にため息をつく。",
   hook:"a sigh of relief は「安堵のため息」。つづりの gh は発音しない。",
   etymologyProcess:"sigh（深く息を吐く）→ 疲れや安心で長く息を吐くのは…？",
   etymologyConclusion:"sigh（深く息を吐く）→ 疲れや安心から、深く長い息をふっと吐き出す＝ため息をつく",
   relatedWords:[
     {synonym:true,word:"breathe",meaning:"呼吸する",breakdown:"息をする全般。sigh は感情のこもった一回の長い息"},
     {synonym:true,word:"groan",meaning:"うめく",breakdown:"苦しさで低い声を出す。sigh は声より息が中心"},
     {synonym:true,word:"gasp",meaning:"はっと息をのむ",breakdown:"驚いて息を吸う。sigh はゆっくり吐き出す"}]},

  {id:634,word:"yawn",partOfSpeech:"自動詞",meaning:"あくびをする",
   meanings:["自|あくびをする","名|あくび"],
   pronunciation:"/jɔːn/",part:64,
   example:"Several students yawned during the long afternoon meeting yesterday.",
   exampleJa:"昨日の長い午後の集会で、何人かの生徒があくびをした。",
   example2:"He yawns loudly whenever he stays up late playing games.",
   exampleJa2:"彼は夜ふかししてゲームをすると、いつも大きくあくびをする。",
   hook:"退屈なものを a yawn と呼ぶこともある。「あくびが出るほど退屈」。",
   etymologyProcess:"yawn（大きく口を開ける）→ 眠いとき口を開けて息を吸うと…？",
   etymologyConclusion:"yawn（大きく口を開ける）→ 眠いときや退屈なときに口を開けて息を吸い込む＝あくびをする",
   relatedWords:[
     {synonym:true,word:"gape",meaning:"ぽかんと口を開ける",breakdown:"驚いて口が開く。yawn は眠気から出る動作"},
     {synonym:true,word:"doze",meaning:"うとうとする",breakdown:"浅く眠る。yawn はその前ぶれとして出る"},
     {synonym:true,word:"stretch",meaning:"伸びをする",breakdown:"体を伸ばす。yawn とセットで出ることが多い"}]},

  {id:635,word:"sneeze",partOfSpeech:"自動詞",meaning:"くしゃみをする",
   meanings:["自|くしゃみをする","名|くしゃみ"],
   pronunciation:"/sniːz/",part:64,
   example:"He sneezed three times because of the dust in the room.",
   exampleJa:"部屋のほこりのせいで、彼は3回くしゃみをした。",
   example2:"She sneezes a lot every spring when the pollen comes.",
   exampleJa2:"彼女は花粉が飛ぶ春になると、よくくしゃみをする。",
   hook:"くしゃみをした人に Bless you. と声をかける習慣が英語圏にはある。",
   etymologyProcess:"sneeze（鼻から噴く）→ 鼻がむずむずして息を噴くのは…？",
   etymologyConclusion:"sneeze（鼻から噴く）→ 鼻がむずむずして、息を一気に鼻と口から噴き出す＝くしゃみをする",
   relatedWords:[
     {synonym:true,word:"cough",meaning:"せきをする",breakdown:"のどから息を出す。sneeze は鼻から勢いよく出る"},
     {synonym:true,word:"sniff",meaning:"鼻をすする",breakdown:"鼻から息を吸う。sneeze は一気に吐き出す"},
     {synonym:true,word:"allergy",meaning:"アレルギー",breakdown:"体が過剰に反応すること。sneeze はその症状の一つ"}]},

  {id:636,word:"bury",partOfSpeech:"他動詞",meaning:"（土の中に）埋める",
   meanings:["他|（土の中に）埋める","他|埋葬する"],
   pronunciation:"/ˈberi/",part:64,
   example:"Students bury a time capsule here before they leave school.",
   exampleJa:"生徒たちは卒業前に、ここにタイムカプセルを埋める。",
   example2:"The dog buried its bone under the tree in our garden.",
   exampleJa2:"その犬は庭の木の下に、自分の骨を埋めた。",
   hook:"発音は /ˈberi/ で berry と同じ。be buried in ～ は「～に没頭する」。",
   etymologyProcess:"bury（覆い隠す）→ 土をかぶせて見えなくするのは…？",
   etymologyConclusion:"bury（覆い隠す）→ 上から土をかぶせて、外から見えないようにする＝埋める",
   relatedWords:[
     {word:"burial",meaning:"埋葬",breakdown:"buri（覆い隠す）＋ al（名詞）→ 土をかぶせて葬ること"},
     {synonym:true,word:"hide",meaning:"隠す",breakdown:"見えないようにする全般。bury は土や物の下に入れる"},
     {synonym:true,word:"cover",meaning:"覆う",breakdown:"上からかぶせる。bury は中にすっかり入れてしまう"}]},

  {id:637,word:"perform",partOfSpeech:"他動詞",meaning:"（任務を）遂行する；演じる",
   meanings:["他|（任務・手術を）遂行する","他|演じる，演奏する"],
   pronunciation:"/pərˈfɔːrm/",part:64,
   example:"The doctor performed the difficult operation in only two hours.",
   exampleJa:"医師はその難しい手術を、わずか2時間で遂行した。",
   example2:"Our band will perform three songs at the school festival.",
   exampleJa2:"私たちのバンドは文化祭で3曲を演奏する予定だ。",
   etymologyProcess:"per（すっかり）＋ form（形）→ 決めた形を最後まで作ると…？",
   etymologyConclusion:"per（すっかり）＋ form（形）→ 決められた形を最後まですっかり作り上げる＝遂行する",
   relatedWords:[
     {word:"performance",meaning:"演技；成績",breakdown:"per（すっかり）＋ form（形）＋ ance（名詞）→ 形にしてみせた出来ばえ"},
     {word:"reform",meaning:"改革する",breakdown:"re（再び）＋ form（形）→ 古い形をこわして作り直す"},
     {word:"uniform",meaning:"制服",breakdown:"uni（1つの）＋ form（形）→ みんなが同じ一つの形になる服"},
     {synonym:true,word:"achieve",meaning:"成しとげる",breakdown:"目標に届く。perform は決まった内容をやりきる"}]},

  {id:638,word:"adopt",partOfSpeech:"他動詞",meaning:"（案・方法を）採用する",
   meanings:["他|（案・方法を）採用する","他|養子にする"],
   pronunciation:"/əˈdɑːpt/",part:64,
   example:"The school adopted a new way of grading this spring.",
   exampleJa:"学校はこの春、新しい採点の方法を採用した。",
   example2:"Many cities have adopted this simple rule to cut plastic waste.",
   exampleJa2:"多くの市が、プラスチックごみを減らすこの簡単な規則を採用した。",
   etymologyProcess:"ad（〜へ）＋ opt（選ぶ）→ 自分のほうへ選び取って入れると…？",
   etymologyConclusion:"ad（〜へ）＋ opt（選ぶ）→ たくさんの中から自分のほうへ選び取って迎え入れる＝採用する",
   relatedWords:[
     {word:"option",meaning:"選択肢",breakdown:"opt（選ぶ）＋ ion（名詞）→ 選ぶことのできる道の一つ"},
     {word:"optional",meaning:"任意の",breakdown:"opt（選ぶ）＋ ion（名詞）＋ al（〜の）→ 選んでも選ばなくてもよい"},
     {word:"adoption",meaning:"採用；養子縁組",breakdown:"ad（〜へ）＋ opt（選ぶ）＋ ion（名詞）→ 選び取って迎え入れること"},
     {synonym:true,word:"accept",meaning:"受け入れる",breakdown:"差し出された物を受け取る。adopt は自分から選んで取り入れる"}]},

  {id:639,word:"escape",partOfSpeech:"自動詞",meaning:"（危険から）逃れる",
   meanings:["自|（危険・場所から）逃れる，逃げ出す","名|脱出"],
   pronunciation:"/ɪˈskeɪp/",part:64,
   example:"Two birds escaped from the cage when the door opened.",
   exampleJa:"ドアが開いたとき、2羽の鳥がかごから逃げ出した。",
   example2:"Everyone escaped from the burning building without a single injury.",
   exampleJa2:"全員がけが一つなく、燃える建物から逃れた。",
   etymologyProcess:"es（外へ）＋ cape（マント）→ マントを脱ぎ捨てて抜け出すと…？",
   etymologyConclusion:"es（外へ）＋ cape（マント）→ つかまれたマントを脱ぎ捨てて外へ抜け出す＝逃れる",
   relatedWords:[
     {synonym:true,word:"cape",meaning:"ケープ，肩マント",breakdown:"肩からはおる、そでのない上着。escape の cape はこれ"},
     {synonym:true,word:"flee",meaning:"（危険から）逃げる",breakdown:"急いでその場を去る硬い語。escape は抜け出す点が中心"},
     {synonym:true,word:"avoid",meaning:"避ける",breakdown:"近づかないようにする。escape はすでに入った所から出る"},
     {synonym:true,word:"survive",meaning:"生き残る",breakdown:"危険を切り抜けて生きる。escape は場所から抜け出す"}]},

  {id:640,word:"scatter",partOfSpeech:"他動詞",meaning:"まき散らす",
   meanings:["他|まき散らす，ばらまく","自|（群れが）散らばる"],
   pronunciation:"/ˈskætər/",part:64,
   example:"The strong wind scattered the dry leaves across the whole yard.",
   exampleJa:"強い風が、乾いた落ち葉を庭じゅうにまき散らした。",
   example2:"Please do not scatter your papers all over the desk.",
   exampleJa2:"机じゅうに書類をまき散らさないでください。",
   hook:"一点から四方へばらばらに散らすのが scatter。spread は面をおおう。",
   etymologyProcess:"scatter（ばらまく）→ あちこちへばらばらに投げるのは…？",
   etymologyConclusion:"scatter（ばらまく）→ ひとかたまりの物を、あちこちへばらばらに投げ広げる＝まき散らす",
   relatedWords:[
     {synonym:true,word:"spread",meaning:"広げる",breakdown:"面をおおうように広がる。scatter はばらばらに散る"},
     {synonym:true,word:"sprinkle",meaning:"（粉・水を）振りかける",breakdown:"少しずつ振りかける。scatter はもっと広くまき散らす"},
     {synonym:true,word:"disperse",meaning:"（群衆を）散らす",breakdown:"集まりを解散させる硬い語。scatter は物にも使う"}]},

  {id:641,word:"fold",partOfSpeech:"他動詞",meaning:"折りたたむ",
   meanings:["他|折りたたむ，折り重ねる","名|折り目"],
   pronunciation:"/foʊld/",part:65,
   example:"Please fold this letter twice and put it in the envelope.",
   exampleJa:"この手紙を2回折りたたんで、封筒に入れてください。",
   example2:"She folded her uniform neatly before putting it in the bag.",
   exampleJa2:"彼女は制服をきちんと折りたたんでから、かばんに入れた。",
   etymologyProcess:"fold（重ねる）→ 面と面が重なるように曲げるのは…？",
   etymologyConclusion:"fold（重ねる）→ 紙や布を、面と面がぴたりと重なるように曲げる＝折りたたむ",
   relatedWords:[
     {word:"unfold",meaning:"広げる；（話が）展開する",breakdown:"un（取り去る）＋ fold（重ねる）→ 重なりを取り去って開く"},
     {synonym:true,word:"bend",meaning:"曲げる",breakdown:"弧を描かせる。fold は折り目をつけて重ねる"},
     {synonym:true,word:"wrap",meaning:"包む",breakdown:"まわりを覆う。fold は自分自身を重ねて小さくする"}]},

  {id:642,word:"hang",partOfSpeech:"他動詞",meaning:"（つるして）掛ける",
   meanings:["他|（つるして）掛ける","自|ぶら下がる"],
   pronunciation:"/hæŋ/",part:65,
   example:"Please hang your wet coat on the hook near the door.",
   exampleJa:"ぬれたコートは、ドアの近くのフックに掛けてください。",
   example2:"A large map hangs on the wall of our history room.",
   exampleJa2:"大きな地図が、歴史教室の壁に掛かっている。",
   hook:"hang out は「ぶらぶら過ごす」。「つるす」の過去形は hung。",
   etymologyProcess:"hang（ぶら下げる）→ 上で留めて下へ垂らすのは…？",
   etymologyConclusion:"hang（ぶら下げる）→ 上の一点で留めて、下へぶら下がった状態にする＝掛ける",
   relatedWords:[
     {word:"hanger",meaning:"ハンガー",breakdown:"hang（ぶら下げる）＋ er（もの）→ 服をぶら下げておくための道具"},
     {synonym:true,word:"suspend",meaning:"つるす；一時停止する",breakdown:"宙につるす硬い語。hang は日常でよく使う"},
     {synonym:true,word:"dangle",meaning:"ぶらぶら揺れる",breakdown:"ゆらゆら垂れる。hang は掛けて止まっている状態"}]},

  {id:643,word:"release",partOfSpeech:"他動詞",meaning:"解放する；（作品を）発表する",
   meanings:["他|（人・動物を）解放する","他|（作品・情報を）発表する"],
   pronunciation:"/rɪˈliːs/",part:65,
   example:"The zoo released two young birds back into the wild forest.",
   exampleJa:"動物園は2羽の若い鳥を、野生の森へ解放した。",
   example2:"The band will release its first album early next spring.",
   exampleJa2:"そのバンドは来年の春先に、初めてのアルバムを発表する。",
   etymologyProcess:"re（後ろへ）＋ lease（ゆるめる）→ 締めていた手をゆるめると…？",
   etymologyConclusion:"re（後ろへ）＋ lease（ゆるめる）→ 押さえていた手をゆるめて、自由に行かせる＝解放する",
   relatedWords:[
     {word:"relax",meaning:"くつろぐ",breakdown:"re（後ろへ）＋ lax（ゆるめる）→ 張っていた心や体をゆるめる"},
     {word:"lease",meaning:"賃貸借（契約）",breakdown:"lease（ゆるめる）→ 手をゆるめ、期間を決めて他人に使わせる"},
     {synonym:true,word:"free",meaning:"自由にする",breakdown:"束縛を解く。release は押さえていた力を抜く感じ"},
     {synonym:true,word:"publish",meaning:"出版する，公表する",breakdown:"世に出す。release は情報や作品を「放つ」感じ"}]},

  {id:644,word:"strike",partOfSpeech:"他動詞",meaning:"強く打つ；（考えが）心に浮かぶ",
   meanings:["他|強く打つ，ぶつかる","他|（考えが）ふと心に浮かぶ","名|ストライキ"],
   pronunciation:"/straɪk/",part:65,
   example:"Lightning may strike the tallest tree on this open hill.",
   exampleJa:"この開けた丘では、雷が一番高い木を打つことがある。",
   example2:"A good idea struck her while she was washing the dishes.",
   exampleJa2:"皿を洗っている間に、よい考えが彼女の心に浮かんだ。",
   hook:"過去形は struck。「ストライキ」「ストライク」も同じ語から来ている。",
   etymologyProcess:"strike（さっと走らせる）→ 勢いよく走らせて当てるのは…？",
   etymologyConclusion:"strike（さっと走らせる）→ 手や物を勢いよくさっと走らせて相手に当てる＝強く打つ",
   relatedWords:[
     {word:"stroke",meaning:"ひと打ち；なでること",breakdown:"strok（さっと走らせる）→ 一度さっと走らせる動きそのもの"},
     {synonym:true,word:"hit",meaning:"当てる，打つ",breakdown:"当てる全般。strike は勢いの強さが感じられる"},
     {synonym:true,word:"beat",meaning:"（続けて）打つ",breakdown:"何度も打つ。strike は一度の強い打撃"}]},

  {id:645,word:"beat",partOfSpeech:"他動詞",meaning:"（続けて）打つ；鼓動する",
   meanings:["他|（続けて）打つ，たたく","自|（心臓が）鼓動する","他|（試合で）負かす"],
   pronunciation:"/biːt/",part:65,
   example:"He beats the big drum at the front of the parade.",
   exampleJa:"彼は行列の先頭で大きな太鼓を打つ。",
   example2:"Her heart was beating fast before she went on the stage.",
   exampleJa2:"舞台に出る前、彼女の心臓は速く鼓動していた。",
   hook:"過去形 beat・過去分詞 beaten。心臓の鼓動も、相手を負かすのも同じ語。",
   etymologyProcess:"beat（打ちつける）→ 同じ所を何度も打ちつけるのは…？",
   etymologyConclusion:"beat（打ちつける）→ 同じ所を何度も規則正しく打ちつける＝（続けて）打つ",
   relatedWords:[
     {word:"heartbeat",meaning:"心拍，鼓動",breakdown:"heart（心臓）＋ beat（打ちつける）→ 心臓が打つ一回ずつの動き"},
     {synonym:true,word:"strike",meaning:"強く打つ",breakdown:"一度の強い打撃。beat は繰り返し打つ"},
     {synonym:true,word:"defeat",meaning:"打ち負かす",breakdown:"相手を負かす硬い語。beat は日常でよく使う"},
     {synonym:true,word:"hit",meaning:"当てる",breakdown:"一度当てる。beat は続けてたたく動き"}]},

  {id:646,word:"protect",partOfSpeech:"他動詞",meaning:"（危険から）守る",
   meanings:["他|（危険・害から）守る，保護する"],
   pronunciation:"/prəˈtekt/",part:65,
   example:"A helmet protects your head when you fall from a bicycle.",
   exampleJa:"ヘルメットは、自転車から落ちたとき頭を守ってくれる。",
   example2:"These trees were planted to protect the village from strong winds.",
   exampleJa2:"これらの木は、強い風から村を守るために植えられた。",
   etymologyProcess:"pro（前に）＋ tect（覆う）→ 前に覆いを立てて防ぐのは…？",
   etymologyConclusion:"pro（前に）＋ tect（覆う）→ 危険の来る前に覆いを立ててさえぎる＝守る",
   relatedWords:[
     {word:"protection",meaning:"保護",breakdown:"pro（前に）＋ tect（覆う）＋ ion（名詞）→ 前に立てた覆いそのもの"},
     {word:"detect",meaning:"探知する，見つける",breakdown:"de（離して）＋ tect（覆う）→ 覆いを取り去って中身を見つける"},
     {word:"detective",meaning:"探偵，刑事",breakdown:"de（離して）＋ tect（覆う）＋ ive（〜な性質の）→ 覆いを取る役の人"},
     {synonym:true,word:"defend",meaning:"守る，弁護する",breakdown:"攻撃を打ち返して守る。protect は覆ってかばう"}]},

  {id:647,word:"twist",partOfSpeech:"他動詞",meaning:"ねじる，ねじ曲げる",
   meanings:["他|ねじる，ねじ曲げる","他|（意味を）曲げる","名|ひねり，急展開"],
   pronunciation:"/twɪst/",part:65,
   example:"She twisted the cap hard, but the bottle would not open.",
   exampleJa:"彼女はふたを強くねじったが、瓶は開かなかった。",
   example2:"Do not twist my words; that is not what I said.",
   exampleJa2:"私の言葉をねじ曲げないで。そんなことは言っていない。",
   hook:"two（2）と同じ仲間。2本をより合わせる動きがもとの意味。",
   etymologyProcess:"twist（より合わせる）→ 2本をよるようにひねるのは…？",
   etymologyConclusion:"twist（より合わせる）→ 2本をより合わせるように、強くひねって形を変える＝ねじる",
   relatedWords:[
     {word:"twin",meaning:"ふたご",breakdown:"twi（二つ）→ 二つより合わさるように同じときに生まれた二人"},
     {synonym:true,word:"bend",meaning:"曲げる",breakdown:"弧を描かせる。twist は回しながらひねる"},
     {synonym:true,word:"turn",meaning:"回す",breakdown:"向きを変える。twist は力を入れてねじる"}]},

  {id:648,word:"skip",partOfSpeech:"他動詞・自動詞",meaning:"（順番・授業を）飛ばす，サボる",
   meanings:["他|（授業・食事を）サボる，抜かす","自|スキップする，跳ねる"],
   pronunciation:"/skɪp/",part:65,
   example:"You should not skip breakfast on the morning of a test.",
   exampleJa:"試験の朝に朝食を抜かしてはいけない。",
   example2:"He skipped the last class and went home to sleep.",
   exampleJa2:"彼は最後の授業をサボって、家に帰って寝た。",
   hook:"なわとびも skip。「軽く跳び越す」→「一つ飛ばす・サボる」とつながる。",
   etymologyProcess:"skip（軽く跳ぶ）→ 一つ跳び越して先へ行くのは…？",
   etymologyConclusion:"skip（軽く跳ぶ）→ 間にある一つを軽く跳び越して先へ進む＝飛ばす",
   relatedWords:[
     {synonym:true,word:"omit",meaning:"省く",breakdown:"わざと入れない硬い語。skip は軽く飛ばす感じ"},
     {synonym:true,word:"jump",meaning:"跳ぶ",breakdown:"高く跳ぶ。skip は軽く弾むように跳ぶ"},
     {synonym:true,word:"miss",meaning:"逃す，欠席する",breakdown:"結果として参加できない。skip は自分から飛ばす"}]},

  {id:649,word:"expose",partOfSpeech:"他動詞",meaning:"（危険・光に）さらす；暴露する",
   meanings:["他|（危険・光に）さらす","他|（秘密を）暴露する"],
   pronunciation:"/ɪkˈspoʊz/",part:65,
   example:"Do not expose this medicine to strong sunlight for long hours.",
   exampleJa:"この薬を長時間、強い日光にさらさないでください。",
   example2:"The report exposed the hidden problems of the old factory.",
   exampleJa2:"その報告は、古い工場の隠れた問題を暴露した。",
   etymologyProcess:"ex（外へ）＋ pos（置く）→ 覆いを取って外に置くと…？",
   etymologyConclusion:"ex（外へ）＋ pos（置く）→ 覆いを取り、外に置いて光や目に当たるようにする＝さらす",
   relatedWords:[
     {word:"exposure",meaning:"さらされること；露出",breakdown:"ex（外へ）＋ pos（置く）＋ ure（名詞）→ 外に置かれている状態"},
     {word:"oppose",meaning:"反対する",breakdown:"op（向かい合って）＋ pos（置く）→ 相手の向かいに身を置く"},
     {word:"propose",meaning:"提案する",breakdown:"pro（前へ）＋ pos（置く）→ 人の前に案を置いてみせる"},
     {synonym:true,word:"reveal",meaning:"明らかにする",breakdown:"覆いを外して見せる。expose は悪いことを暴く場合が多い"}]},

  {id:650,word:"stir",partOfSpeech:"他動詞",meaning:"かき混ぜる",
   meanings:["他|（スプーンなどで）かき混ぜる","他|（感情を）かき立てる"],
   pronunciation:"/stɜːr/",part:65,
   example:"Stir the soup slowly so that it does not burn.",
   exampleJa:"焦げないように、スープをゆっくりかき混ぜて。",
   example2:"His quiet speech stirred deep feelings in every listener there.",
   exampleJa2:"彼の静かな演説は、聞く人すべての心に深い感情をかき立てた。",
   hook:"stir-fry は「炒める」。心を stir すれば「気持ちをかき立てる」。",
   etymologyProcess:"stir（かき回す）→ 棒でぐるぐる回して混ぜるのは…？",
   etymologyConclusion:"stir（かき回す）→ スプーンや棒でぐるぐる回し、中身を動かして混ぜる＝かき混ぜる",
   relatedWords:[
     {synonym:true,word:"mix",meaning:"混ぜる",breakdown:"二つ以上を一つにする。stir は回してかき混ぜる動作"},
     {synonym:true,word:"blend",meaning:"混ぜ合わせる",breakdown:"境目がなくなるまで混ぜる。stir は軽く回すだけでもよい"},
     {synonym:true,word:"shake",meaning:"振る",breakdown:"容器ごと振って混ぜる。stir は中に入れて回す"}]},
