  {id:2151,word:"latitude",partOfSpeech:"名詞",meaning:"緯度；（行動・考え方の）自由の幅",
   meanings:["名|緯度","名|（行動・考え方の）自由の幅，許容範囲"],
   pronunciation:"/ˈlætɪtuːd/",part:216,
   example:"Tokyo and Los Angeles are at almost the same latitude.",
   exampleJa:"東京とロサンゼルスは、ほぼ同じ緯度にある。",
   example2:"Our teacher gives us a lot of latitude in choosing topics.",
   exampleJa2:"先生は、私たちがテーマを選ぶときに大きな自由の幅を与えてくれる。",
   etymologyProcess:"lati（広い）＋ tude（名詞）→ 地図の「幅」の向きで位置を表すと…？",
   etymologyConclusion:"lati（広い）＋ tude（名詞）→ 地図の「幅」の向き、南北のどこにいるかを表す度数＝緯度",
   why:"【なぜ】ラテン語 latitudo は「幅」。昔の地図では、知られていた世界が東西に長く、南北には幅が狭く描かれていました。そこで東西の位置を「長さ」の longitude（経度）、南北の位置を「幅」の latitude（緯度）と呼び分けたのです。\n【つながり】どちらも -tude で終わる名詞で、altitude（高度）も同じ形です。緯度と経度は組にして覚えましょう。",
   etymologyMore:["幅がある、ゆとりがある→（行動・考え方の）自由の幅，許容範囲"],
   relatedWords:[
     {word:"longitude",meaning:"経度",breakdown:"longi（長い）＋ tude（名詞）→ 東西に長く続く向きの位置"},
     {word:"altitude",meaning:"高度",breakdown:"alt（高い）＋ tude（名詞）→ 地面や海面からの高さ"},
     {synonym:true,word:"breadth",meaning:"幅，広さ",breakdown:"横の広がり。latitude はもと「幅」を表すラテン語"},
     {synonym:true,word:"wide",meaning:"幅の広い",breakdown:"latitude のもとの latus（幅の広い）と同じ意味の英語"}]},

  {id:2152,word:"odor",partOfSpeech:"名詞",meaning:"（不快な）におい，臭気",
   meanings:["名|（不快な）におい，臭気"],
   pronunciation:"/ˈoʊdər/",part:216,
   example:"A strange odor was coming from the old refrigerator.",
   exampleJa:"古い冷蔵庫から、変なにおいがしていた。",
   example2:"This spray removes the odor of sweat from sports shoes.",
   exampleJa2:"このスプレーは、運動靴から汗のにおいを取り除く。",
   etymologyProcess:"odor（におい）→ 鼻をつく、いやな感じの…？",
   etymologyConclusion:"odor（におい）→ 鼻をつく、いやな感じのにおい＝（不快な）におい，臭気",
   hook:"smell はよい・悪いどちらにも使う。odor はいやなにおいを指すことが多い。",
   relatedWords:[
     {word:"deodorant",meaning:"制汗剤，消臭剤",breakdown:"de（離れて）＋ odor（におい）＋ ant（もの）→ においを取り去るもの"},
     {word:"odorless",meaning:"においのない",breakdown:"odor（におい）＋ less（ない）→ 何のにおいもしない"},
     {synonym:true,word:"smell",meaning:"におい",breakdown:"においを表すふつうの語。よいにおいにも悪いにおいにも使う"},
     {synonym:true,word:"scent",meaning:"（よい）香り",breakdown:"花や香水のほのかなよい香り。odor とは逆の感じ"}]},

  {id:2153,word:"meadow",partOfSpeech:"名詞",meaning:"（干し草用の）草地，牧草地",
   meanings:["名|（干し草用の）草地，牧草地"],
   pronunciation:"/ˈmedoʊ/",part:216,
   example:"Cows were eating grass in the green meadow by the river.",
   exampleJa:"川沿いの緑の草地で、牛が草を食べていた。",
   example2:"We had a picnic in a meadow full of wild flowers.",
   exampleJa2:"私たちは、野の花でいっぱいの草地でピクニックをした。",
   etymologyProcess:"mead（刈った草）→ 牛や馬のえさにする草を刈り取る場所は…？",
   etymologyConclusion:"mead（刈った草）→ 干し草にする草を刈り取る広い原っぱ＝（干し草用の）草地，牧草地",
   hook:"mow（草を刈る）と同じ古英語の家族。牛や馬のえさにする草が生える野原。",
   relatedWords:[
     {synonym:true,word:"mow",meaning:"（草を）刈る",breakdown:"meadow と同じ古英語の家族。草を刈ること"},
     {synonym:true,word:"field",meaning:"野原，畑",breakdown:"広く開けた土地全般。meadow は草の生えた土地"},
     {synonym:true,word:"grass",meaning:"草，芝生",breakdown:"地面に生える草そのもの。meadow はその草が広がる場所"},
     {synonym:true,word:"pasture",meaning:"放牧地",breakdown:"家畜に草を食べさせる場所。meadow は干し草用に刈る"}]},

  {id:2154,word:"calamity",partOfSpeech:"名詞",meaning:"（突然ふりかかる）災難，大惨事",
   meanings:["名|（突然ふりかかる）災難，大惨事"],
   pronunciation:"/kəˈlæməti/",part:216,
   example:"The earthquake was the worst calamity in the town's history.",
   exampleJa:"その地震は、町の歴史で最悪の災難だった。",
   example2:"Losing my phone right before the trip felt like a calamity.",
   exampleJa2:"旅行の直前にスマホをなくしたのは、まるで災難のようだった。",
   etymologyProcess:"calamit（災い）→ 人々を突然おそう大きな…？",
   etymologyConclusion:"calamit（災い）→ 人々を突然おそう大きな不幸＝（突然ふりかかる）災難，大惨事",
   hook:"語源ははっきりしないラテン語。disaster・catastrophe と並ぶ「大きな不幸」の語。",
   relatedWords:[
     {synonym:true,word:"disaster",meaning:"災害，大惨事",breakdown:"地震や洪水など大きな災い。calamity とほぼ同じ"},
     {synonym:true,word:"catastrophe",meaning:"大災害",breakdown:"取り返しがつかないほどの大惨事。calamity より重い"},
     {synonym:true,word:"misfortune",meaning:"不運",breakdown:"運が悪いこと全般。calamity はもっと大きな不幸"},
     {synonym:true,word:"tragedy",meaning:"悲劇",breakdown:"人の死などを伴う悲しい出来事。劇の「悲劇」から"}]},

  {id:2155,word:"precipitation",partOfSpeech:"名詞",meaning:"降水，降水量；（化学）沈殿",
   meanings:["名|降水，降水量","名|（化学）沈殿"],
   pronunciation:"/prɪˌsɪpɪˈteɪʃən/",part:216,
   example:"Annual precipitation in this region is less than 300 millimeters.",
   exampleJa:"この地域の年間降水量は300ミリ未満だ。",
   example2:"The weather report says there is a 70 percent chance of precipitation.",
   exampleJa2:"天気予報によると、降水確率は70パーセントだ。",
   etymologyProcess:"pre（前へ）＋ capit（頭）＋ ation（名詞）→ 頭から真っ逆さまに空から…？",
   etymologyConclusion:"pre（前へ）＋ capit（頭）＋ ation（名詞）→ 頭から真っ逆さまに空から落ちてくるもの＝降水，降水量",
   spelling:"capit→cipit（母音が弱まった）",
   etymologyMore:["液体の底へ真っ逆さまに落ちる→（化学）沈殿"],
   relatedWords:[
     {word:"capital",meaning:"首都",breakdown:"capit（頭）＋ al（～に関する）→ 国の頭にあたる町"},
     {word:"captain",meaning:"キャプテン，船長",breakdown:"capt（頭）＋ ain（人）→ チームや船の頭に立つ人"},
     {word:"chief",meaning:"長，チーフ",breakdown:"chief（頭）→ 集団の頭に立つ人"},
     {synonym:true,word:"rainfall",meaning:"降雨量",breakdown:"雨だけの量。precipitation は雪やひょうも含む"}]},

  {id:2156,word:"meteor",partOfSpeech:"名詞",meaning:"流星，流れ星",
   meanings:["名|流星，流れ星"],
   pronunciation:"/ˈmiːtiər/",part:216,
   example:"We saw a bright meteor cross the night sky last night.",
   exampleJa:"昨夜、明るい流星が夜空を横切るのを見た。",
   example2:"Many people stayed up late to watch the meteor shower.",
   exampleJa2:"多くの人が、流星群を見ようと夜ふかしした。",
   etymologyProcess:"meteor（空高くにあるもの）→ 夜空で一瞬光って流れる…？",
   etymologyConclusion:"meteor（空高くにあるもの）→ 空高くで一瞬光って流れるもの＝流星，流れ星",
   hook:"正体は宇宙のちりが大気で燃える光。燃え残って地上に落ちた石は meteorite（隕石）。",
   relatedWords:[
     {word:"meteorite",meaning:"隕石",breakdown:"meteor（空高くにあるもの）＋ ite（もの）→ 空から落ちてきた石"},
     {word:"meteorology",meaning:"気象学",breakdown:"meteor（空高くにあるもの）＋ log（学問）→ 空の現象を調べる"},
     {synonym:true,word:"star",meaning:"星",breakdown:"夜空の星全般。meteor は一瞬で消える光"},
     {synonym:true,word:"shooting star",meaning:"流れ星",breakdown:"meteor のくだけた言い方。「撃ち出された星」"}]},

  {id:2157,word:"asteroid",partOfSpeech:"名詞",meaning:"小惑星",
   meanings:["名|小惑星"],
   pronunciation:"/ˈæstərɔɪd/",part:216,
   example:"Scientists are watching an asteroid that will pass near the earth.",
   exampleJa:"科学者たちは、地球の近くを通る小惑星を観測している。",
   example2:"Many scientists believe an asteroid caused the extinction of the dinosaurs.",
   exampleJa2:"多くの科学者は、小惑星が恐竜の絶滅を引き起こしたと考えている。",
   etymologyProcess:"aster（星）＋ oid（～のような形）→ 望遠鏡で星のように見える…？",
   etymologyConclusion:"aster（星）＋ oid（～のような形）→ 望遠鏡で星のように見える小さな天体＝小惑星",
   relatedWords:[
     {word:"disaster",meaning:"災害",breakdown:"dis（離れて）＋ aster（星）→ 幸運の星が離れて起きる大事故"},
     {word:"astronaut",meaning:"宇宙飛行士",breakdown:"astro（星）＋ naut（船乗り）→ 星の世界へ行く船乗り"},
     {word:"asterisk",meaning:"アステリスク（＊）",breakdown:"aster（星）＋ isk（小さい）→ 小さな星の形の記号"},
     {synonym:true,word:"star",meaning:"星",breakdown:"aster と遠い祖先が同じ英語の語"}]},

  {id:2158,word:"eclipse",partOfSpeech:"名詞",meaning:"（日・月の）食；影を薄くする",
   meanings:["名|（日・月の）食","他|（人気・重要性で）しのぐ，影を薄くする"],
   pronunciation:"/ɪˈklɪps/",part:216,
   example:"People around the world watched the solar eclipse through special glasses.",
   exampleJa:"世界中の人々が、特別なめがねで日食を見た。",
   example2:"The new phone quickly eclipsed all the older models in sales.",
   exampleJa2:"新しいスマホは、売り上げでたちまち古い機種すべての影を薄くした。",
   etymologyProcess:"ec（外へ）＋ lips（去る）→ 空の太陽や月が姿を消すと…？",
   etymologyConclusion:"ec（外へ）＋ lips（去る）→ 太陽や月の光が去り、姿が欠けて見えること＝（日・月の）食",
   etymologyMore:["ほかの光をさえぎって隠す→（人気・重要性で）しのぐ，影を薄くする"],
   relatedWords:[
     {word:"ellipse",meaning:"楕円",breakdown:"en（中へ）＋ lips（去る）→ 円から少し欠けた形"},
     {synonym:true,word:"shadow",meaning:"影",breakdown:"光がさえぎられてできる暗い部分。月食は地球の影"},
     {synonym:true,word:"hide",meaning:"隠す",breakdown:"見えないようにすること全般"},
     {synonym:true,word:"outshine",meaning:"～より輝く，しのぐ",breakdown:"out（～より）＋ shine（輝く）。eclipse と同じく相手を目立たなくする"}]},

  {id:2159,word:"glacier",partOfSpeech:"名詞",meaning:"氷河",
   meanings:["名|氷河"],
   pronunciation:"/ˈɡleɪʃər/",part:216,
   example:"The glacier has become much smaller because of global warming.",
   exampleJa:"地球温暖化のせいで、その氷河はずっと小さくなった。",
   example2:"We took a boat tour to see the glaciers in Alaska.",
   exampleJa2:"私たちはアラスカの氷河を見に、ボートツアーに参加した。",
   etymologyProcess:"glac（氷）＋ ier（もの）→ 山から少しずつ流れ下る巨大な氷は…？",
   etymologyConclusion:"glac（氷）＋ ier（もの）→ 山から少しずつ流れ下る巨大な氷のかたまり＝氷河",
   relatedWords:[
     {word:"glacial",meaning:"氷河の；氷のように冷たい",breakdown:"glac（氷）＋ al（～の）→ 氷のように冷たい"},
     {synonym:true,word:"ice",meaning:"氷",breakdown:"氷そのもの。glacier は陸の上を流れる巨大な氷"},
     {synonym:true,word:"iceberg",meaning:"氷山",breakdown:"海に浮かぶ氷のかたまり。氷河の先が割れて生まれる"},
     {synonym:true,word:"snow",meaning:"雪",breakdown:"積もった雪が押し固められて氷河の氷になる"}]},

  {id:2160,word:"peninsula",partOfSpeech:"名詞",meaning:"半島",
   meanings:["名|半島"],
   pronunciation:"/pəˈnɪnsələ/",part:216,
   example:"The Korean peninsula lies between the Sea of Japan and the Yellow Sea.",
   exampleJa:"朝鮮半島は、日本海と黄海の間にある。",
   example2:"Our school trip took us to a small peninsula with a lighthouse.",
   exampleJa2:"修学旅行で、私たちは灯台のある小さな半島に行った。",
   etymologyProcess:"pen（ほとんど）＋ insul（島）→ ほとんど島のような陸地は…？",
   etymologyConclusion:"pen（ほとんど）＋ insul（島）→ 三方を海に囲まれた、ほとんど島のような陸地＝半島",
   relatedWords:[
     {word:"isolate",meaning:"孤立させる",breakdown:"isol（島）＋ ate（～にする）→ 島のように一人きりにする"},
     {word:"insulate",meaning:"断熱する，絶縁する",breakdown:"insul（島）＋ ate（～にする）→ 島のように周りから切り離す"},
     {word:"isle",meaning:"島",breakdown:"isol（島）→ 詩や地名で使う「島」"},
     {synonym:true,word:"island",meaning:"島",breakdown:"見た目は似ているが古英語の別の家族。s は後から足された"}]},

  {id:2161,word:"hemisphere",partOfSpeech:"名詞",meaning:"（地球の）半球；（脳の）半球",
   meanings:["名|（地球・天球の）半球","名|（脳の左右の）半球"],
   pronunciation:"/ˈhemɪsfɪr/",part:217,
   example:"Australia is in the southern hemisphere, so December is summer there.",
   exampleJa:"オーストラリアは南半球にあるので、そこでは12月が夏だ。",
   example2:"For most people, the left hemisphere of the brain controls language.",
   exampleJa2:"多くの人では、脳の左半球が言葉をつかさどっている。",
   etymologyProcess:"hemi（半分）＋ sphere（球）→ まるい地球を半分に切ると…？",
   etymologyConclusion:"hemi（半分）＋ sphere（球）→ 地球を赤道などで半分に分けた片側＝（地球の）半球",
   etymologyMore:["丸い脳も左右半分に分かれる→（脳の左右の）半球"],
   relatedWords:[
     {word:"sphere",meaning:"球；範囲",breakdown:"sphere（球）→ どこから見てもまるい形"},
     {word:"atmosphere",meaning:"大気；雰囲気",breakdown:"atmo（蒸気）＋ sphere（球）→ 地球を包む空気の球"},
     {synonym:true,word:"half",meaning:"半分",breakdown:"hemi と同じ「半分」を表すふつうの英語"},
     {synonym:true,word:"globe",meaning:"地球儀；地球",breakdown:"まるい地球そのもの。hemisphere はその半分"}]},

  {id:2162,word:"lump",partOfSpeech:"名詞",meaning:"（形の定まらない）かたまり；こぶ",
   meanings:["名|（形の定まらない）かたまり","名|こぶ，しこり","他|（together）ひとまとめにする"],
   pronunciation:"/lʌmp/",part:217,
   example:"There were a few lumps of sugar left in the bowl.",
   exampleJa:"ボウルの中に、砂糖のかたまりがいくつか残っていた。",
   example2:"I got a lump on my head when I hit the door.",
   exampleJa2:"ドアにぶつけて、頭にこぶができた。",
   usage:["lump A together（A をひとまとめにして扱う）"],
   etymologyProcess:"lump（かたまり）→ ごろっとした形の決まらない…？",
   etymologyConclusion:"lump（かたまり）→ ごろっとした、形の決まらない小さな塊＝（形の定まらない）かたまり",
   hook:"a lump in one's throat は「のどのかたまり」＝胸がいっぱい。lump sum は一括払い。",
   etymologyMore:["体の表面にできたかたまり→こぶ，しこり","ばらばらの物を一つにまとめる→（together）ひとまとめにする"],
   relatedWords:[
     {synonym:true,word:"piece",meaning:"かけら，1つ",breakdown:"全体から分けた一部分。lump は丸っこいかたまり"},
     {synonym:true,word:"block",meaning:"（四角い）かたまり",breakdown:"角ばったかたまり。lump は形がでこぼこ"},
     {synonym:true,word:"bump",meaning:"こぶ；でこぼこ",breakdown:"ぶつけてできたこぶ。lump とほぼ同じ"},
     {synonym:true,word:"mass",meaning:"（大きな）かたまり",breakdown:"大きくまとまったかたまり。lump は小さめ"}]},

  {id:2163,word:"cluster",partOfSpeech:"名詞",meaning:"（同じ種類の物・人の）集まり，集団；房",
   meanings:["名|（同じ種類の物・人の）集まり，集団","名|（ブドウなどの）房","自|（around ～の周りに）群がる"],
   pronunciation:"/ˈklʌstər/",part:217,
   example:"A small cluster of houses stood at the foot of the mountain.",
   exampleJa:"山のふもとに、家の小さな集まりがあった。",
   example2:"Students clustered around the board to see the test results.",
   exampleJa2:"生徒たちはテストの結果を見ようと、掲示板の周りに群がった。",
   etymologyProcess:"clust（かたまり）→ 同じ種類のものがぎゅっと寄ると…？",
   etymologyConclusion:"clust（かたまり）→ 同じ種類のものがぎゅっと寄り集まったもの＝（同じ種類の物・人の）集まり，集団",
   hook:"ぎゅっと固まって集まるイメージ。星の集まり「星団」も cluster。",
   etymologyMore:["実がぎゅっと固まって付く→（ブドウなどの）房"],
   relatedWords:[
     {synonym:true,word:"clot",meaning:"（血などの）かたまり",breakdown:"cluster の親戚とされる古英語。固まったもの"},
     {synonym:true,word:"group",meaning:"集団，グループ",breakdown:"集まり全般。cluster は近くに密集している感じ"},
     {synonym:true,word:"crowd",meaning:"群衆",breakdown:"人の大きな群れ。cluster は小さなまとまり"},
     {synonym:true,word:"bunch",meaning:"束，房",breakdown:"ひとまとめにした束。バナナやブドウの房"}]},

  {id:2164,word:"offspring",partOfSpeech:"名詞",meaning:"（人・動物の）子，子孫",
   meanings:["名|（人・動物の）子，子孫"],
   pronunciation:"/ˈɔːfsprɪŋ/",part:217,
   example:"Most birds feed their offspring until they can fly.",
   exampleJa:"たいていの鳥は、飛べるようになるまで子にえさを与える。",
   example2:"All parents want the best for their offspring.",
   exampleJa2:"親はみな、子にとって最善のことを望むものだ。",
   etymologyProcess:"off（離れて）＋ spring（跳び出す）→ 親から離れて跳び出すのは…？",
   etymologyConclusion:"off（離れて）＋ spring（跳び出す）→ 親の体から離れて跳び出してきたもの＝（人・動物の）子，子孫",
   relatedWords:[
     {word:"spring",meaning:"泉；春；跳ねる",breakdown:"spring（跳び出す）→ 水が跳び出す泉、芽が跳び出す春"},
     {word:"springtime",meaning:"春（の季節）",breakdown:"spring（跳び出す）＋ time（時間の区切り）→ 芽が跳び出す季節"},
     {synonym:true,word:"child",meaning:"子ども",breakdown:"人の子ども。offspring は動物にも使う硬い語"},
     {synonym:true,word:"descendant",meaning:"子孫",breakdown:"何代も後に続く血筋の人。offspring は直接の子が中心"}]},

  {id:2165,word:"livestock",partOfSpeech:"名詞",meaning:"（集合的に）家畜",
   meanings:["名|（集合的に）家畜"],
   pronunciation:"/ˈlaɪvstɑːk/",part:217,
   example:"The farmers lost much of their livestock in the flood.",
   exampleJa:"農家の人たちは、洪水で家畜の多くを失った。",
   example2:"Raising livestock produces a large amount of greenhouse gas.",
   exampleJa2:"家畜を育てると、大量の温室効果ガスが出る。",
   etymologyProcess:"live（生きる）＋ stock（木の幹）→ 生きている「蓄え」とは…？",
   etymologyConclusion:"live（生きる）＋ stock（木の幹）→ 農家が生きた財産として蓄えておく動物たち＝（集合的に）家畜",
   why:"【なぜ】stock はもとは「木の幹」。幹から枝が次々に出るように、そこから物を出していく「蓄え・在庫」の意味になりました。昔の農家にとって牛や羊は大切な財産だったので、「生きている蓄え」で livestock と呼んだのです。\n【つながり】in stock（在庫がある）や stock market（株式市場）の stock も、この「蓄え」の意味です。",
   relatedWords:[
     {word:"alive",meaning:"生きている",breakdown:"live（生きる）→ 命のある状態で（頭の a は古い on）"},
     {word:"lively",meaning:"元気のよい",breakdown:"live（生きる）＋ ly（～のような）→ 生き生きとした"},
     {word:"stock",meaning:"在庫，蓄え",breakdown:"stock（木の幹）→ 幹のように元になる蓄え"},
     {synonym:true,word:"cattle",meaning:"（家畜の）ウシ",breakdown:"家畜のうち牛だけを指す。livestock は豚や羊も含む"}]},

  {id:2166,word:"carnivore",partOfSpeech:"名詞",meaning:"肉食動物",
   meanings:["名|肉食動物"],
   pronunciation:"/ˈkɑːrnɪvɔːr/",part:217,
   example:"Lions and tigers are carnivores that hunt other animals.",
   exampleJa:"ライオンやトラは、ほかの動物を狩る肉食動物だ。",
   example2:"My brother is a real carnivore and never eats vegetables.",
   exampleJa2:"兄は本物の肉食動物で、野菜をまったく食べない。",
   etymologyProcess:"carn（肉）＋ vor（食べる）→ 肉を食べて生きる…？",
   etymologyConclusion:"carn（肉）＋ vor（食べる）→ ほかの動物の肉を食べて生きる動物＝肉食動物",
   relatedWords:[
     {word:"herbivore",meaning:"草食動物",breakdown:"herb（草）＋ vor（食べる）→ 草を食べて生きる動物"},
     {word:"omnivore",meaning:"雑食動物",breakdown:"omni（すべて）＋ vor（食べる）→ 肉も草も何でも食べる"},
     {word:"carnival",meaning:"カーニバル，謝肉祭",breakdown:"carn（肉）→ 肉を断つ時期の前に、肉を食べて騒ぐ祭り"},
     {synonym:true,word:"meat",meaning:"肉",breakdown:"carn と同じ「肉」を表すふつうの英語"}]},

  {id:2167,word:"vertebrate",partOfSpeech:"名詞",meaning:"脊椎動物",
   meanings:["名|脊椎動物","形|脊椎のある"],
   pronunciation:"/ˈvɜːrtɪbrət/",part:217,
   example:"Fish, birds, and mammals are all vertebrates with a backbone.",
   exampleJa:"魚も鳥も哺乳類も、みな背骨のある脊椎動物だ。",
   example2:"Insects are not vertebrates because they have no backbone.",
   exampleJa2:"昆虫は背骨がないので、脊椎動物ではない。",
   etymologyProcess:"vert（回る）＋ ate（形容詞）→ 体をひねれる骨の節をもつのは…？",
   etymologyConclusion:"vert（回る）＋ ate（形容詞）→ 体を回してひねれる骨の節、背骨をもつ動物＝脊椎動物",
   why:"【なぜ】ラテン語 vertebra は「回るところ」で、背骨を作っている一つ一つの骨のこと。骨と骨のつなぎ目のおかげで体をひねったり曲げたりできます。その骨をもつ動物が vertebrate（脊椎動物）です。\n【つながり】頭に in（否定）を付けた invertebrate は、昆虫やイカのような背骨のない無脊椎動物です。",
   relatedWords:[
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ 向きを後ろへ回す"},
     {word:"advertise",meaning:"宣伝する",breakdown:"ad（～へ）＋ vert（回る）→ 人の注意をこちらへ向けさせる"},
     {word:"universe",meaning:"宇宙",breakdown:"uni（1つ）＋ vers（回る）→ 1つにまとまって回る全体"},
     {synonym:true,word:"backbone",meaning:"背骨",breakdown:"back（背中）＋ bone（骨）。vertebra がつながったもの"}]},

  {id:2168,word:"primate",partOfSpeech:"名詞",meaning:"霊長類（の動物）",
   meanings:["名|霊長類（の動物）"],
   pronunciation:"/ˈpraɪmeɪt/",part:217,
   example:"Chimpanzees are the primates most closely related to humans.",
   exampleJa:"チンパンジーは、人間にいちばん近い霊長類だ。",
   example2:"We learned about primates at the zoo on our school trip.",
   exampleJa2:"修学旅行で、動物園の霊長類について学んだ。",
   etymologyProcess:"prim（第一の）＋ ate（名詞）→ 動物の中で「第一の位」とされた仲間は…？",
   etymologyConclusion:"prim（第一の）＋ ate（名詞）→ 動物の中で第一の位に置かれたサルやヒトの仲間＝霊長類（の動物）",
   why:"【なぜ】18世紀の学者リンネが、ヒトやサルの仲間を「第一の位の動物」という意味で Primates と名づけました。当時は人間を生き物の最上位と考えていたためです。日本語の「霊長」も「万物の中でいちばん優れたもの」という意味です。\n【つながり】prime minister（首相）、primary school（小学校）も「第一の・最初の」の prim です。",
   relatedWords:[
     {word:"prime",meaning:"最も重要な",breakdown:"prim（第一の）→ 順位がいちばん上の"},
     {word:"primary",meaning:"最初の；主要な",breakdown:"prim（第一の）＋ ary（形容詞）→ 順番がいちばん先の"},
     {word:"prince",meaning:"王子",breakdown:"prim（第一の）＋ cap（つかむ）→ 第一の地位をつかむ人"},
     {synonym:true,word:"ape",meaning:"類人猿",breakdown:"ゴリラやチンパンジーなど尾のないサル。霊長類の一部"}]},

  {id:2169,word:"parasite",partOfSpeech:"名詞",meaning:"寄生虫，寄生生物；居候",
   meanings:["名|寄生虫，寄生生物","名|（他人に頼って暮らす）居候"],
   pronunciation:"/ˈpærəsaɪt/",part:217,
   example:"This parasite lives inside the stomach of some fish.",
   exampleJa:"この寄生虫は、ある種の魚の胃の中で生きている。",
   example2:"He was called a parasite because he never paid rent at his aunt's.",
   exampleJa2:"彼はおばの家で家賃を一度も払わなかったので、居候と呼ばれた。",
   etymologyProcess:"para（そばで）＋ site（食べ物）→ 人のそばで食べ物をもらう者は…？",
   etymologyConclusion:"para（そばで）＋ site（食べ物）→ ほかの生き物にくっついて養分をもらう生き物＝寄生虫，寄生生物",
   why:"【なぜ】ギリシャ語 parasitos は「人の食卓のそばで食べる者」。もとは、お世辞を言ってただでごちそうになる人を指しました。18世紀ごろから、ほかの生き物に取りついて養分をもらう生物にも使われるようになりました。\n【つながり】だから今も、人に頼って暮らす「居候」の意味が残っています。",
   relatedWords:[
     {word:"paragraph",meaning:"段落",breakdown:"para（そばで）＋ graph（書く）→ 区切りの横に印を書いた文のまとまり"},
     {word:"parallel",meaning:"平行の",breakdown:"para（そばで）＋ allel（互いに）→ 互いにそばを並んで走る"},
     {synonym:true,word:"virus",meaning:"ウイルス",breakdown:"生き物の細胞に入りこんで増える。これも他に頼って生きる"},
     {synonym:true,word:"worm",meaning:"（細長い）虫",breakdown:"ミミズなど。寄生虫にはこの形のものが多い"}]},

  {id:2170,word:"cortex",partOfSpeech:"名詞",meaning:"（脳などの）皮質",
   meanings:["名|（脳などの）皮質"],
   pronunciation:"/ˈkɔːrteks/",part:217,
   example:"The cortex of the brain helps us think and remember.",
   exampleJa:"脳の皮質は、私たちが考えたり記憶したりするのを助けている。",
   example2:"Scientists studied how the cortex changes as children grow.",
   exampleJa2:"科学者たちは、子どもの成長につれて皮質がどう変わるかを研究した。",
   etymologyProcess:"cortex（木の皮）→ 脳の表面を包むうすい部分は…？",
   etymologyConclusion:"cortex（木の皮）→ 木の皮のように器官の外側をおおう層＝（脳などの）皮質",
   hook:"大脳の表面のしわしわの部分が cerebral cortex（大脳皮質）。考える働きの中心。",
   relatedWords:[
     {synonym:true,word:"bark",meaning:"樹皮",breakdown:"木の皮を表すふつうの英語。cortex のもとの意味"},
     {synonym:true,word:"brain",meaning:"脳",breakdown:"頭の中の器官全体。cortex はその表面の層"},
     {synonym:true,word:"layer",meaning:"層",breakdown:"重なった一枚一枚。cortex は外側の層"},
     {synonym:true,word:"surface",meaning:"表面",breakdown:"sur（上に）＋ face（顔）。いちばん外側の面"}]},

  {id:2171,word:"sibling",partOfSpeech:"名詞",meaning:"（男女の区別なく）兄弟姉妹",
   meanings:["名|（男女の区別なく）兄弟姉妹（の1人）"],
   pronunciation:"/ˈsɪblɪŋ/",part:218,
   example:"Do you have any siblings, or are you an only child?",
   exampleJa:"兄弟姉妹はいますか、それとも一人っ子ですか。",
   example2:"My siblings and I often fight over the TV remote.",
   exampleJa2:"私と兄弟姉妹は、よくテレビのリモコンの取り合いをする。",
   etymologyProcess:"sib（親族）＋ ling（小さいもの）→ 同じ親から生まれた身内の子は…？",
   etymologyConclusion:"sib（親族）＋ ling（小さいもの）→ 同じ親から生まれた身内の子どもたち＝（男女の区別なく）兄弟姉妹",
   relatedWords:[
     {word:"gossip",meaning:"うわさ話",breakdown:"god（神）＋ sib（親族）→ 洗礼で結ばれた親しい身内どうしのおしゃべり"},
     {word:"seedling",meaning:"苗木，芽生え",breakdown:"seed（まかれるもの）＋ ling（小さいもの）→ 種から出た小さな芽"},
     {synonym:true,word:"brother",meaning:"兄，弟",breakdown:"男のきょうだい。sibling は男女どちらにも使える"},
     {synonym:true,word:"sister",meaning:"姉，妹",breakdown:"女のきょうだい。sibling は男女をまとめて言う"}]},

  {id:2172,word:"extrovert",partOfSpeech:"名詞",meaning:"外向的な人",
   meanings:["名|外向的な人","形|外向的な"],
   pronunciation:"/ˈekstrəvɜːrt/",part:218,
   example:"She is an extrovert who loves meeting new people.",
   exampleJa:"彼女は、新しい人に会うのが大好きな外向的な人だ。",
   example2:"Even extroverts sometimes need some time alone to relax.",
   exampleJa2:"外向的な人でも、ときには一人でくつろぐ時間が必要だ。",
   etymologyProcess:"extra（範囲の外へ）＋ vert（回る）→ 心が外の人へ向いている人は…？",
   etymologyConclusion:"extra（範囲の外へ）＋ vert（回る）→ 心が自分の外の人や物へ向いている人＝外向的な人",
   spelling:"extra→extro（introvert の intro にそろえた形）",
   relatedWords:[
     {word:"introvert",meaning:"内向的な人",breakdown:"intro（内へ）＋ vert（回る）→ 心が自分の内側へ向いている人"},
     {word:"advertise",meaning:"宣伝する",breakdown:"ad（～へ）＋ vert（回る）→ 人の注意をこちらへ向けさせる"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ 向きを後ろへ回す"},
     {synonym:true,word:"outgoing",meaning:"社交的な",breakdown:"out（外へ）＋ going（出ていく）。人づきあいが好きな"}]},

  {id:2173,word:"stigma",partOfSpeech:"名詞",meaning:"（社会的な）汚名，烙印",
   meanings:["名|（社会的な）汚名，烙印"],
   pronunciation:"/ˈstɪɡmə/",part:218,
   example:"There is still a social stigma attached to mental illness.",
   exampleJa:"心の病には、いまだに社会的な汚名がつきまとっている。",
   example2:"He studied hard to escape the stigma of failing the exam.",
   exampleJa2:"彼は、試験に落ちたという汚名を晴らそうと懸命に勉強した。",
   etymologyProcess:"stigma（焼き印）→ 体に押された消えない悪い印は…？",
   etymologyConclusion:"stigma（焼き印）→ 人に押しつけられた消えない悪い印＝（社会的な）汚名，烙印",
   hook:"古代ギリシャで、罪人や奴隷の体にとがった道具で付けた印から。日本語の「烙印」と同じ発想。",
   relatedWords:[
     {synonym:true,word:"shame",meaning:"恥",breakdown:"自分で感じる恥ずかしさ。stigma は社会から押される印"},
     {synonym:true,word:"disgrace",meaning:"不名誉",breakdown:"dis（否定）＋ grace（好意）。人からの好意を失うこと"},
     {synonym:true,word:"label",meaning:"ラベル；レッテル",breakdown:"人に貼られる決めつけ。stigma はとくに悪いレッテル"},
     {word:"stigmatize",meaning:"汚名を着せる",breakdown:"stigma（焼き印）＋ ize（～にする）→ 悪い印を押しつける"}]},

  {id:2174,word:"plight",partOfSpeech:"名詞",meaning:"（困った）窮状，苦境",
   meanings:["名|（困った）窮状，苦境"],
   pronunciation:"/plaɪt/",part:218,
   example:"The TV report showed the plight of people who lost their homes.",
   exampleJa:"そのテレビの報道は、家を失った人々の窮状を伝えた。",
   example2:"Our class raised money after learning about the plight of refugees.",
   exampleJa2:"私たちのクラスは、難民の窮状を知って募金を集めた。",
   etymologyProcess:"pli（折る）→ 折り目のようにこじれた「ありさま」は…？",
   etymologyConclusion:"pli（折る）→ 折り重なってもつれたような、困ったありさま＝（困った）窮状，苦境",
   spelling:"pli→pligh（gh は同じ音の別の語 plight「誓い」につられた）",
   why:"【なぜ】ラテン語 plicare（折る）から、古いフランス語で「折り目、たたみ方」の意味になり、さらに物事の「ありさま・状態」を表すようになりました。英語では悪い状態について使われることが多くなり、今では困りはてた状態＝窮状だけを指します。\n【つながり】apply（当てはめる）や reply（答える）も同じ pli（折る）の仲間です。",
   relatedWords:[
     {word:"apply",meaning:"申し込む；当てはめる",breakdown:"ad（～へ）＋ pli（折る）→ 相手のほうへ折り重ねて当てる"},
     {word:"reply",meaning:"返事をする",breakdown:"re（後ろへ）＋ pli（折る）→ 折り返して言葉を返す"},
     {word:"application",meaning:"申し込み；応用",breakdown:"ad（～へ）＋ pli（折る）＋ ation（名詞）→ 当てはめること"},
     {synonym:true,word:"trouble",meaning:"困ったこと",breakdown:"困りごと全般。plight は抜け出せないほどの苦境"}]},

  {id:2175,word:"turmoil",partOfSpeech:"名詞",meaning:"（社会・心の）動揺，混乱",
   meanings:["名|（社会・心の）動揺，混乱"],
   pronunciation:"/ˈtɜːrmɔɪl/",part:218,
   example:"The country was in turmoil after the unexpected election result.",
   exampleJa:"予想外の選挙結果のあと、その国は動揺していた。",
   example2:"My mind was in turmoil the night before the entrance exam.",
   exampleJa2:"入試の前の夜、私の心は動揺していた。",
   etymologyProcess:"turmoil（騒ぎ）→ 社会や心がかき乱された…？",
   etymologyConclusion:"turmoil（騒ぎ）→ 社会や心がかき乱されて落ち着かない状態＝（社会・心の）動揺，混乱",
   hook:"語源ははっきりしない。be in turmoil（動揺している，混乱している）の形でよく使う。",
   relatedWords:[
     {synonym:true,word:"chaos",meaning:"大混乱",breakdown:"まったく秩序のない状態。turmoil は激しく揺れ動く"},
     {synonym:true,word:"confusion",meaning:"混乱，当惑",breakdown:"con（共に）＋ fus（注ぐ）。ごちゃまぜになった状態"},
     {synonym:true,word:"disorder",meaning:"無秩序",breakdown:"dis（否定）＋ order（順序）。順序が乱れた状態"},
     {synonym:true,word:"trouble",meaning:"もめごと，困難",breakdown:"困りごと全般。turmoil は大きく揺れた状態"}]},

  {id:2176,word:"fallacy",partOfSpeech:"名詞",meaning:"（一般に信じられている）誤った考え，誤信",
   meanings:["名|（一般に信じられている）誤った考え，誤信","名|（推論・議論の）誤り"],
   pronunciation:"/ˈfæləsi/",part:218,
   example:"It is a fallacy that money always brings happiness.",
   exampleJa:"お金が必ず幸せをもたらすというのは、誤った考えだ。",
   example2:"Our teacher pointed out a fallacy in my essay.",
   exampleJa2:"先生は、私の作文の中の論理の誤りを指摘した。",
   etymologyProcess:"fail（期待を裏切る）＋ acy（名詞）→ 人をあざむき、信じる人を裏切る…？",
   etymologyConclusion:"fail（期待を裏切る）＋ acy（名詞）→ 正しそうに見えて人をあざむく考え＝（一般に信じられている）誤った考え，誤信",
   spelling:"fail→fall（ラテン語 fallere「だます」の形）",
   etymologyMore:["理屈のうえで人をあざむく→（推論・議論の）誤り"],
   relatedWords:[
     {word:"false",meaning:"誤った",breakdown:"fail（期待を裏切る）→ 人をあざむく、本当でない"},
     {word:"failure",meaning:"失敗",breakdown:"fail（期待を裏切る）＋ ure（名詞）→ 期待どおりにならないこと"},
     {word:"fault",meaning:"欠点；責任",breakdown:"fail（期待を裏切る）→ 期待を裏切るような欠け"},
     {synonym:true,word:"myth",meaning:"（根拠のない）通説，神話",breakdown:"広く信じられているが本当でない話"}]},

  {id:2177,word:"loophole",partOfSpeech:"名詞",meaning:"（法律・規則の）抜け穴",
   meanings:["名|（法律・規則の）抜け穴"],
   pronunciation:"/ˈluːpˌhoʊl/",part:218,
   example:"The company used a loophole in the law to avoid paying taxes.",
   exampleJa:"その会社は、法律の抜け穴を使って税金を払わずにすませた。",
   example2:"Students are always trying to find loopholes in the school rules.",
   exampleJa2:"生徒たちは、いつも校則の抜け穴を見つけようとしている。",
   etymologyProcess:"loop（壁の細い窓）＋ hole（穴）→ 城壁のすき間から外へ抜けるのは…？",
   etymologyConclusion:"loop（壁の細い窓）＋ hole（穴）→ 決まりの壁にあいた、すり抜けられるすき間＝（法律・規則の）抜け穴",
   why:"【なぜ】loophole はもとは、城の壁にあけた縦長の細いすき間。中の兵士はここから外をのぞいたり矢を放ったりしました。狭いすき間から外へ抜け出せることから、17世紀には「逃げ道」の意味になり、今では決まりの中のすり抜けられるところを指します。\n【つながり】この loop は「輪」の loop とは別の語と考えられています。",
   relatedWords:[
     {word:"hole",meaning:"穴",breakdown:"hole（穴）→ 中がくぼんだり、突き抜けたりしたところ"},
     {synonym:true,word:"gap",meaning:"すき間",breakdown:"物と物のあいだの空き。loophole は決まりのすき間"},
     {synonym:true,word:"exception",meaning:"例外",breakdown:"ex（外へ）＋ cept（取る）。決まりから外された場合"},
     {synonym:true,word:"escape",meaning:"逃げる；逃げ道",breakdown:"つかまった所から抜け出すこと。loophole は抜け道"}]},

  {id:2178,word:"congestion",partOfSpeech:"名詞",meaning:"（交通の）渋滞，混雑",
   meanings:["名|（交通の）渋滞，混雑","名|（鼻の）詰まり，充血"],
   pronunciation:"/kənˈdʒestʃən/",part:218,
   example:"Traffic congestion in big cities wastes a lot of time.",
   exampleJa:"大都市の交通渋滞は、多くの時間をむだにする。",
   example2:"The new subway line will reduce congestion at the station.",
   exampleJa2:"新しい地下鉄の路線は、駅の混雑を減らすだろう。",
   etymologyProcess:"con（共に）＋ gest（運ぶ）＋ ion（名詞）→ 一か所にどんどん運びこむと…？",
   etymologyConclusion:"con（共に）＋ gest（運ぶ）＋ ion（名詞）→ 一か所にどんどん運びこまれて詰まった状態＝（交通の）渋滞，混雑",
   etymologyMore:["体の中で血や液が詰まる→（鼻の）詰まり，充血"],
   relatedWords:[
     {word:"suggest",meaning:"提案する",breakdown:"sub（下で）＋ gest（運ぶ）→ 下からそっと考えを運ぶ"},
     {word:"digest",meaning:"消化する",breakdown:"dis（バラバラに）＋ gest（運ぶ）→ 食べ物を分けて運ぶ"},
     {word:"gesture",meaning:"身ぶり",breakdown:"gest（運ぶ）＋ ure（名詞）→ 体の運び方"},
     {synonym:true,word:"traffic jam",meaning:"交通渋滞",breakdown:"車がジャムのようにぎっしり詰まる。会話でよく使う"}]},

  {id:2179,word:"vacuum",partOfSpeech:"名詞",meaning:"真空；（心・活動の）空白",
   meanings:["名|真空","名|（心・活動の）空白","他|（掃除機で）掃除する"],
   pronunciation:"/ˈvækjuːm/",part:218,
   example:"Sound cannot travel through a vacuum like outer space.",
   exampleJa:"音は、宇宙空間のような真空の中を伝わることができない。",
   example2:"I vacuumed my room before my friends came over.",
   exampleJa2:"友達が来る前に、自分の部屋を掃除機で掃除した。",
   etymologyProcess:"vac（空の）→ 空気さえない空っぽの空間は…？",
   etymologyConclusion:"vac（空の）→ 空気さえない、中身が空っぽの空間＝真空",
   etymologyMore:["中身がなく空っぽ→（心・活動の）空白","空気を抜いた力で吸いこむ→（掃除機で）掃除する"],
   relatedWords:[
     {word:"vacation",meaning:"休暇",breakdown:"vac（空の）＋ ation（名詞）→ 仕事のない空いた期間"},
     {word:"vacant",meaning:"空いている",breakdown:"vac（空の）＋ ant（～な）→ 中にだれもいない"},
     {word:"avoid",meaning:"避ける",breakdown:"ex（外へ）＋ void（空の）→ 近づかず、そこを空けておく"},
     {synonym:true,word:"empty",meaning:"空の",breakdown:"中に何もないこと全般を表すふつうの語"}]},

  {id:2180,word:"digit",partOfSpeech:"名詞",meaning:"（0～9の）数字，桁",
   meanings:["名|（0～9の）数字，桁"],
   pronunciation:"/ˈdɪdʒɪt/",part:218,
   example:"My phone number has eleven digits including the area code.",
   exampleJa:"私の電話番号は、市外局番を含めて11桁だ。",
   example2:"Your password must contain at least one digit.",
   exampleJa2:"パスワードには、少なくとも1つ数字を入れなければならない。",
   etymologyProcess:"digit（指）→ 指を折って数える1つ1つの…？",
   etymologyConclusion:"digit（指）→ 指で数えられる0から9までの1つ1つ＝（0～9の）数字，桁",
   why:"【なぜ】ラテン語 digitus は「指」。人は昔から指を折って数を数えてきたので、10本の指で数えられる0から9までの一つ一つの数字を digit と呼ぶようになりました。そこから、数の位を表す「桁」の意味でも使います。\n【つながり】digital（デジタル）は、すべてを数字で表すこと。アナログの反対です。",
   relatedWords:[
     {word:"digital",meaning:"デジタルの",breakdown:"digit（指）＋ al（～の）→ 情報を数字で表す"},
     {synonym:true,word:"finger",meaning:"指",breakdown:"digit のもとの意味を表すふつうの英語"},
     {synonym:true,word:"number",meaning:"数，番号",breakdown:"数そのもの。digit は数を書くための1つ1つの文字"},
     {synonym:true,word:"figure",meaning:"数字",breakdown:"書かれた数字。double figures（2桁）のように使う"}]},

  {id:2181,word:"bulk",partOfSpeech:"名詞",meaning:"（the bulk of ～）～の大半；（大きな）かさ",
   meanings:["名|（the bulk of ～）～の大半","名|（大きな）かさ，容積","形|大量の，大口の"],
   pronunciation:"/bʌlk/",part:219,
   example:"The bulk of the work was done by the students themselves.",
   exampleJa:"その作業の大半は、生徒たち自身によって行われた。",
   example2:"Buying rice in bulk is cheaper in the long run.",
   exampleJa2:"米を大量にまとめて買うほうが、長い目で見れば安い。",
   usage:["the bulk of 名詞（～の大半）","in bulk（大量に，まとめて）"],
   etymologyProcess:"bulk（船の積み荷）→ 船いっぱいに積んだ荷のほとんどは…？",
   etymologyConclusion:"bulk（船の積み荷）→ 船いっぱいに積んだ荷のかさ、その大部分＝（the bulk of ～）～の大半",
   hook:"北欧の古い言葉で「船の積み荷」。形容詞 bulky は「かさばる，大きくて扱いにくい」。",
   etymologyMore:["積み荷がかさばる大きさ→（大きな）かさ，容積","積み荷をまるごと売り買いする→大量の，大口の"],
   relatedWords:[
     {synonym:true,word:"majority",meaning:"大多数",breakdown:"maj（大きい）＋ ity（名詞）。数の多いほう"},
     {synonym:true,word:"most",meaning:"大部分（の）",breakdown:"ふつうの「ほとんど」。the bulk of は硬い言い方"},
     {synonym:true,word:"volume",meaning:"量；体積",breakdown:"入る量や体積。bulk はかさばる大きさ"},
     {synonym:true,word:"mass",meaning:"（大きな）かたまり；大量",breakdown:"大きくまとまったもの。bulk と近い"}]},

  {id:2182,word:"longevity",partOfSpeech:"名詞",meaning:"長寿，長生き",
   meanings:["名|長寿，長生き","名|（物の）寿命の長さ，長もち"],
   pronunciation:"/lɑːnˈdʒevəti/",part:219,
   example:"Japan is famous for the longevity of its people.",
   exampleJa:"日本は、国民の長寿で有名だ。",
   example2:"Good food and enough sleep may be the secret of longevity.",
   exampleJa2:"よい食事と十分な睡眠が、長生きの秘訣かもしれない。",
   etymologyProcess:"longi（長い）＋ ev（生涯）＋ ity（名詞）→ 生涯が長く続くと…？",
   etymologyConclusion:"longi（長い）＋ ev（生涯）＋ ity（名詞）→ 生涯が長く続くこと＝長寿，長生き",
   spelling:"longi→long（うしろの母音が消えた）",
   etymologyMore:["物が使える期間が長く続く→（物の）寿命の長さ，長もち"],
   relatedWords:[
     {word:"longitude",meaning:"経度",breakdown:"longi（長い）＋ tude（名詞）→ 東西に長く続く向きの位置"},
     {word:"age",meaning:"年齢；時代",breakdown:"age（生きてきた時間）→ ev と同じ祖先のラテン語 aetas から。生きてきた年月"},
     {word:"medieval",meaning:"中世の",breakdown:"medi（中間）＋ ev（生涯）＋ al（～の）→ 真ん中の時代の"},
     {synonym:true,word:"lifespan",meaning:"寿命",breakdown:"life（命）＋ span（長さ）。生きられる期間"}]},

  {id:2183,word:"detour",partOfSpeech:"名詞",meaning:"回り道，迂回路",
   meanings:["名|回り道，迂回路","自|回り道をする"],
   pronunciation:"/ˈdiːtʊr/",part:219,
   example:"We had to take a detour because the bridge was closed.",
   exampleJa:"橋が通行止めだったので、私たちは回り道をしなければならなかった。",
   example2:"On the way home, we made a short detour to buy ice cream.",
   exampleJa2:"帰り道に、アイスを買いにちょっと回り道をした。",
   etymologyProcess:"de（離れて）＋ tour（回る）→ まっすぐの道から離れて回ると…？",
   etymologyConclusion:"de（離れて）＋ tour（回る）→ まっすぐの道から離れて、ぐるっと回っていく道＝回り道，迂回路",
   relatedWords:[
     {word:"tour",meaning:"旅行，ツアー",breakdown:"tour（回る）→ あちこちを回ってもどってくる旅"},
     {word:"tourist",meaning:"観光客",breakdown:"tour（回る）＋ ist（人）→ 名所を回る人"},
     {word:"turn",meaning:"回す；曲がる",breakdown:"tour（回る）→ ろくろを回すように向きを変える"},
     {synonym:true,word:"bypass",meaning:"バイパス，迂回路",breakdown:"by（そばを）＋ pass（通る）。町の中を通らない道"}]},

  {id:2184,word:"sewage",partOfSpeech:"名詞",meaning:"下水，汚水",
   meanings:["名|下水，汚水"],
   pronunciation:"/ˈsuːɪdʒ/",part:219,
   example:"The town's sewage used to flow straight into the river.",
   exampleJa:"その町の下水は、以前は川にそのまま流れこんでいた。",
   example2:"Our class visited a sewage treatment plant on a field trip.",
   exampleJa2:"私たちのクラスは、校外学習で下水処理場を見学した。",
   etymologyProcess:"ex（外へ）＋ aqu（水）＋ age（名詞）→ 汚れた水を外へ流すと…？",
   etymologyConclusion:"ex（外へ）＋ aqu（水）＋ age（名詞）→ 家や工場から外へ流し出される汚れた水＝下水，汚水",
   spelling:"ex＋aqu→sew（フランス語を通って大きく縮んだ）",
   why:"【なぜ】sewer（下水道）はフランス語から来た語で、もとはラテン語の ex（外へ）＋ aqua（水）＝「水を外へ流し出すところ」でした。これに名詞を作る -age が付いて、下水道を流れていく汚れた水そのものを sewage と呼ぶようになりました。\n【つながり】つづりは似ていても、縫う sew（ソウ）とは別の語です。sewage は「スーイッジ」と読みます。",
   relatedWords:[
     {word:"sewer",meaning:"下水道，下水管",breakdown:"ex（外へ）＋ aqu（水）＋ er（もの）→ 水を外へ流す管"},
     {word:"aquarium",meaning:"水族館",breakdown:"aqu（水）＋ arium（場所）→ 水の生き物を飼う場所"},
     {synonym:true,word:"waste",meaning:"廃棄物，ごみ",breakdown:"いらなくなった物全般。sewage は流される汚水"},
     {synonym:true,word:"drain",meaning:"排水管；排水する",breakdown:"水を流し出すこと。sewage はその汚れた水"}]},

  {id:2185,word:"landfill",partOfSpeech:"名詞",meaning:"（ごみの）埋め立て地",
   meanings:["名|（ごみの）埋め立て地","名|（ごみの）埋め立て"],
   pronunciation:"/ˈlændfɪl/",part:219,
   example:"Most of the town's trash goes to a landfill outside the city.",
   exampleJa:"町のごみのほとんどは、市の外にある埋め立て地に運ばれる。",
   example2:"Recycling reduces the amount of waste sent to landfills.",
   exampleJa2:"リサイクルは、埋め立て地へ送られるごみの量を減らす。",
   etymologyProcess:"land（土地）＋ fill（満たす）→ 地面のくぼみをごみで満たすと…？",
   etymologyConclusion:"land（土地）＋ fill（満たす）→ 地面のくぼみをごみで満たして埋めた場所＝（ごみの）埋め立て地",
   relatedWords:[
     {word:"fill",meaning:"満たす",breakdown:"fill（満たす）→ 入れ物をいっぱいにする"},
     {word:"fulfill",meaning:"果たす，実現する",breakdown:"ful（満ちた）＋ fill（満たす）→ 約束を満たしきる"},
     {word:"landscape",meaning:"景色",breakdown:"land（土地）＋ scape（ありさま）→ 土地の見えるありさま"},
     {synonym:true,word:"dump",meaning:"ごみ捨て場",breakdown:"ごみをどさっと捨てる場所。landfill は埋めて処理する"}]},

  {id:2186,word:"appliance",partOfSpeech:"名詞",meaning:"（家庭用の）電気器具",
   meanings:["名|（家庭用の）電気器具，器具"],
   pronunciation:"/əˈplaɪəns/",part:219,
   example:"We bought new kitchen appliances such as a microwave and a toaster.",
   exampleJa:"私たちは、電子レンジやトースターなど新しい台所の電気器具を買った。",
   example2:"Turn off electrical appliances when you are not using them.",
   exampleJa2:"使っていないときは、電気器具の電源を切りなさい。",
   etymologyProcess:"ad（～へ）＋ pli（折る）＋ ance（名詞）→ 用途に当てはめて使うものは…？",
   etymologyConclusion:"ad（～へ）＋ pli（折る）＋ ance（名詞）→ 暮らしの用途に当てはめて使う道具＝（家庭用の）電気器具",
   spelling:"ad→ap（次の p に合わせて変化）",
   why:"【なぜ】apply は「折り重ねてぴったり当てる」から「当てはめる・使う」の意味になりました。appliance はもともと「使うこと・使う手段」。そこから、特定の用途に使うための道具を指すようになり、今では冷蔵庫や洗濯機のような家庭の電気器具によく使います。\n【つながり】日本語の「アプリ」も application（当てはめて使うもの）の略です。",
   relatedWords:[
     {word:"apply",meaning:"申し込む；当てはめる",breakdown:"ad（～へ）＋ pli（折る）→ 相手のほうへ折り重ねて当てる"},
     {word:"reply",meaning:"返事をする",breakdown:"re（後ろへ）＋ pli（折る）→ 折り返して言葉を返す"},
     {word:"application",meaning:"申し込み；アプリ",breakdown:"ad（～へ）＋ pli（折る）＋ ation（名詞）→ 当てはめて使うもの"},
     {synonym:true,word:"device",meaning:"装置，機器",breakdown:"ある目的のための仕掛け。スマホなどにも使う"}]},

  {id:2187,word:"cuisine",partOfSpeech:"名詞",meaning:"（国・地域独特の）料理，料理法",
   meanings:["名|（国・地域独特の）料理，料理法"],
   pronunciation:"/kwɪˈziːn/",part:219,
   example:"Many tourists come to Japan to enjoy its traditional cuisine.",
   exampleJa:"多くの観光客が、伝統的な日本料理を楽しみに来日する。",
   example2:"My favorite restaurant serves Italian cuisine at low prices.",
   exampleJa2:"私のお気に入りのレストランは、イタリア料理を安く出してくれる。",
   etymologyProcess:"cuis（料理する）＋ ine（もの）→ 台所で作られる、その土地の…？",
   etymologyConclusion:"cuis（料理する）＋ ine（もの）→ その土地の台所で作られてきた料理＝（国・地域独特の）料理，料理法",
   relatedWords:[
     {word:"cook",meaning:"料理する；料理人",breakdown:"cuis（料理する）→ 火を通して食べ物を作る"},
     {word:"kitchen",meaning:"台所",breakdown:"cuis（料理する）→ 料理をする部屋"},
     {word:"biscuit",meaning:"ビスケット",breakdown:"bi（2つ）＋ cuis（料理する）→ 2度焼いて作る菓子"},
     {synonym:true,word:"dish",meaning:"（1皿の）料理",breakdown:"皿に盛った一品。cuisine は料理のスタイル全体"}]},

  {id:2188,word:"beverage",partOfSpeech:"名詞",meaning:"（水以外の）飲み物，飲料",
   meanings:["名|（水以外の）飲み物，飲料"],
   pronunciation:"/ˈbevərɪdʒ/",part:219,
   example:"Hot beverages such as coffee and tea are sold here.",
   exampleJa:"ここでは、コーヒーや紅茶などの温かい飲み物が売られている。",
   example2:"Alcoholic beverages are not allowed at the school festival.",
   exampleJa2:"文化祭では、アルコール飲料は禁止されている。",
   etymologyProcess:"bev（飲む）＋ age（名詞）→ 飲むために作られた…？",
   etymologyConclusion:"bev（飲む）＋ age（名詞）→ お茶やジュースなど飲むために作られたもの＝（水以外の）飲み物，飲料",
   relatedWords:[
     {word:"bib",meaning:"よだれかけ",breakdown:"bev（飲む）→ 飲むときに胸にかける布"},
     {synonym:true,word:"drink",meaning:"飲み物；飲む",breakdown:"ふつうの「飲み物」。beverage は店や表示で使う硬い語"},
     {synonym:true,word:"juice",meaning:"ジュース",breakdown:"果物をしぼった汁。beverage の一つ"},
     {synonym:true,word:"soft drink",meaning:"清涼飲料",breakdown:"アルコールを含まない飲み物"}]},

  {id:2189,word:"staple",partOfSpeech:"名詞",meaning:"（米・パンなどの）主食，主要食料品",
   meanings:["名|（米・パンなどの）主食，主要食料品","名|ホッチキスの針","形|主要な，基本的な"],
   pronunciation:"/ˈsteɪpəl/",part:219,
   example:"Rice has been a staple of the Japanese diet for centuries.",
   exampleJa:"米は何百年もの間、日本人の食事の主食であり続けてきた。",
   example2:"Put the pages in order and join them with a staple.",
   exampleJa2:"ページを順番にそろえて、ホッチキスの針でとめなさい。",
   etymologyProcess:"staple（市場）→ 市場でいつも売り買いされる、欠かせない…？",
   etymologyConclusion:"staple（市場）→ 市場でいつも売り買いされる、暮らしに欠かせない食べ物＝（米・パンなどの）主食，主要食料品",
   hook:"ホッチキスの針も staple。どちらもゲルマン語の「柱」から出た遠い親戚。",
   relatedWords:[
     {synonym:true,word:"rice",meaning:"米",breakdown:"日本やアジアの代表的な staple"},
     {synonym:true,word:"bread",meaning:"パン",breakdown:"ヨーロッパの代表的な staple"},
     {synonym:true,word:"basic",meaning:"基本的な",breakdown:"土台になる。staple は毎日欠かせない"},
     {synonym:true,word:"essential",meaning:"欠かせない",breakdown:"なくてはならない。staple は暮らしの必需品"}]},

  {id:2190,word:"scenario",partOfSpeech:"名詞",meaning:"（劇・映画の）筋書き，シナリオ",
   meanings:["名|（劇・映画の）筋書き，シナリオ","名|（予想される）事態，成り行き"],
   pronunciation:"/səˈnerioʊ/",part:219,
   example:"He wrote the scenario for a short film about high school life.",
   exampleJa:"彼は、高校生活を描いた短編映画の筋書きを書いた。",
   example2:"In the worst-case scenario, the game will be canceled because of rain.",
   exampleJa2:"最悪の成り行きでは、試合は雨で中止になるだろう。",
   etymologyProcess:"scen（舞台）＋ ario（もの）→ 舞台で演じる場面の流れを書くと…？",
   etymologyConclusion:"scen（舞台）＋ ario（もの）→ 舞台で演じる場面の流れを書き表したもの＝（劇・映画の）筋書き，シナリオ",
   etymologyMore:["この先の場面の流れを思い描く→（予想される）事態，成り行き"],
   relatedWords:[
     {word:"scene",meaning:"場面；現場",breakdown:"scen（舞台）→ 舞台の上の一場面"},
     {word:"scenic",meaning:"景色のよい",breakdown:"scen（舞台）＋ ic（形容詞）→ 舞台の背景のように美しい"},
     {synonym:true,word:"story",meaning:"物語，話",breakdown:"話の中身。scenario は演じるための筋書き"},
     {synonym:true,word:"script",meaning:"台本",breakdown:"せりふまで書いた台本。scenario は筋の流れ"}]},

  {id:2191,word:"autograph",partOfSpeech:"名詞",meaning:"（有名人の）サイン",
   meanings:["名|（有名人の）サイン","他|（本・写真などに）サインする"],
   pronunciation:"/ˈɔːtəɡræf/",part:220,
   example:"The fans waited outside to get the singer's autograph.",
   exampleJa:"ファンたちは、その歌手のサインをもらおうと外で待った。",
   example2:"The player autographed baseballs for the children after the game.",
   exampleJa2:"その選手は試合のあと、子どもたちのためにボールにサインした。",
   etymologyProcess:"auto（自分）＋ graph（書く）→ 自分の手で書いた名前は…？",
   etymologyConclusion:"auto（自分）＋ graph（書く）→ 有名人が自分の手で書いた名前＝（有名人の）サイン",
   relatedWords:[
     {word:"automobile",meaning:"自動車",breakdown:"auto（自分）＋ mob（動かす）→ 自分の力で動かせる車"},
     {word:"photograph",meaning:"写真",breakdown:"photo（光）＋ graph（書く）→ 光で書いた絵"},
     {word:"biography",meaning:"伝記",breakdown:"bio（生命）＋ graph（書く）→ 人の一生を書いたもの"},
     {synonym:true,word:"signature",meaning:"署名",breakdown:"書類や手紙に書く自分の名前"}]},

  {id:2192,word:"archive",partOfSpeech:"名詞",meaning:"（保存された）記録，公文書",
   meanings:["名|（保存された）記録，公文書","名|記録保管所","他|（記録・データを）保存する"],
   pronunciation:"/ˈɑːrkaɪv/",part:220,
   example:"Historians studied the archives of a small village in the Edo period.",
   exampleJa:"歴史学者たちは、江戸時代のある小さな村の記録を調べた。",
   example2:"You can archive old emails instead of deleting them.",
   exampleJa2:"古いメールは、削除する代わりに保存しておくことができる。",
   etymologyProcess:"arch（支配する）→ 国を治める役所にしまわれた書類は…？",
   etymologyConclusion:"arch（支配する）→ 国を治める役所に大切にしまわれた書類＝（保存された）記録，公文書",
   why:"【なぜ】ギリシャ語 arkheion は「政府の役所」で、arkhe（支配）から来ています。役所には法律や税の書類が大切にしまわれていたので、そこに保管された文書や、文書をしまっておく場所そのものを archive と呼ぶようになりました。\n【つながり】今ではパソコンやネットで古いデータを保存することも archive と言います。",
   etymologyMore:["記録をしまっておく場所→記録保管所","記録を大切にしまう→（記録・データを）保存する"],
   relatedWords:[
     {word:"monarch",meaning:"君主",breakdown:"mono（1つ）＋ arch（支配する）→ 1人で国を支配する人"},
     {word:"architect",meaning:"建築家",breakdown:"arch（主な）＋ tect（建てる）→ 建てる人たちの頭"},
     {synonym:true,word:"record",meaning:"記録",breakdown:"書きとめたもの全般。archive は保管された記録"},
     {synonym:true,word:"file",meaning:"ファイル，書類",breakdown:"書類をとじたもの。パソコンのデータのまとまりにも使う"}]},

  {id:2193,word:"rhetoric",partOfSpeech:"名詞",meaning:"（中身のない）美辞麗句；修辞法",
   meanings:["名|（中身のない）美辞麗句，大げさな言葉","名|修辞法，説得力のある話し方"],
   pronunciation:"/ˈretərɪk/",part:220,
   example:"The politician's speech was full of empty rhetoric.",
   exampleJa:"その政治家の演説は、中身のない美辞麗句ばかりだった。",
   example2:"In the debate club, we study rhetoric to persuade an audience.",
   exampleJa2:"ディベート部では、聞き手を説得するために修辞法を学んでいる。",
   etymologyProcess:"rhetor（演説する人）＋ ic（名詞）→ 演説家が使う飾った言葉は…？",
   etymologyConclusion:"rhetor（演説する人）＋ ic（名詞）→ 演説家が使う、飾り立てた言葉＝（中身のない）美辞麗句",
   why:"【なぜ】古代ギリシャでは、人前で人々を説得する話し方の技術が学問として教えられ、rhetoric（修辞学）と呼ばれました。ところが言葉を飾る技術ばかりが目立つようになると、中身がないのに立派そうに聞こえる言葉、という悪い意味でも使われるようになりました。\n【つながり】rhetorical question（修辞疑問）は、答えを求めずに主張を強める疑問文です。",
   etymologyMore:["人を動かす話し方の技術→修辞法，説得力のある話し方"],
   relatedWords:[
     {word:"rhetorical",meaning:"修辞的な",breakdown:"rhetor（演説する人）＋ ic（名詞）＋ al（～の）→ 言葉を飾った"},
     {synonym:true,word:"speech",meaning:"演説，スピーチ",breakdown:"人前で話すこと。rhetoric はその話し方の技術"},
     {synonym:true,word:"eloquence",meaning:"雄弁",breakdown:"e（外へ）＋ loqu（話す）。人の心を動かす話しぶり"},
     {synonym:true,word:"exaggeration",meaning:"誇張",breakdown:"ex（外へ）＋ agger（積み上げる）。話を大きく盛ること"}]},

  {id:2194,word:"connotation",partOfSpeech:"名詞",meaning:"（言外の）含み，言外の意味",
   meanings:["名|（言外の）含み，言外の意味"],
   pronunciation:"/ˌkɑːnəˈteɪʃən/",part:220,
   example:"The word cheap can have a negative connotation in English.",
   exampleJa:"英語では、cheap という語は否定的な含みをもつことがある。",
   example2:"Colors can have different connotations in different cultures.",
   exampleJa2:"色は、文化によって異なる言外の意味をもつことがある。",
   etymologyProcess:"con（共に）＋ nota（しるし）＋ tion（名詞）→ 言葉にいっしょに付いてくる「しるし」は…？",
   etymologyConclusion:"con（共に）＋ nota（しるし）＋ tion（名詞）→ 言葉の意味といっしょに付いてくる感じ＝（言外の）含み，言外の意味",
   relatedWords:[
     {word:"note",meaning:"メモ；注意",breakdown:"nota（しるし）→ 忘れないように付けたしるし"},
     {word:"notebook",meaning:"ノート",breakdown:"nota（しるし）＋ book（本）→ しるしを書きこむ帳面"},
     {word:"notable",meaning:"注目すべき",breakdown:"nota（しるし）＋ able（できる）→ しるしを付けておく価値がある"},
     {synonym:true,word:"nuance",meaning:"ニュアンス，微妙な違い",breakdown:"意味や感じのわずかな差。connotation は言葉が帯びる感じ"}]},

  {id:2195,word:"anecdote",partOfSpeech:"名詞",meaning:"（人物にまつわる）逸話，エピソード",
   meanings:["名|（人物にまつわる）逸話，エピソード"],
   pronunciation:"/ˈænɪkdoʊt/",part:220,
   example:"The teacher told us a funny anecdote about her school days.",
   exampleJa:"先生は、自分の学生時代の面白い逸話を話してくれた。",
   example2:"His speech was full of anecdotes about famous scientists.",
   exampleJa2:"彼の講演は、有名な科学者たちの逸話でいっぱいだった。",
   etymologyProcess:"ec（外へ）＋ dot（与える）→ 人に語り出される人物の小さな話は…？",
   etymologyConclusion:"ec（外へ）＋ dot（与える）→ 人から人へ語り出される、人物にまつわる小さな話＝（人物にまつわる）逸話，エピソード",
   why:"【なぜ】ギリシャ語 anekdota は ec（外へ）＋ dot（与える）＝「世に出す」に否定の an が付いた形で「世に出されていないもの」。6世紀の歴史家プロコピオスが宮廷の裏話を書いた本がこの名で知られ、そこから、公式の記録には載らない人物の面白い小話を指すようになりました。\n【つながり】日本語の「エピソード」とほぼ同じ意味で使えます。",
   relatedWords:[
     {word:"antidote",meaning:"解毒剤",breakdown:"anti（逆に）＋ dot（与える）→ 毒に逆らうために与える薬"},
     {word:"dose",meaning:"（薬の）1回分",breakdown:"dos（与える）→ 1回に与える薬の量"},
     {word:"donate",meaning:"寄付する",breakdown:"don（与える）＋ ate（動詞）→ 人のために与える"},
     {synonym:true,word:"episode",meaning:"エピソード，出来事",breakdown:"話の中の一場面。anecdote は人物の小話"}]},

  {id:2196,word:"lord",partOfSpeech:"名詞",meaning:"（封建時代の）領主，君主；（the Lord）神",
   meanings:["名|（封建時代の）領主，君主","名|（the Lord）神，主","名|（英国の）貴族，卿"],
   pronunciation:"/lɔːrd/",part:220,
   example:"The lord of the castle ruled over the farmers in the area.",
   exampleJa:"城の領主は、その地域の農民を支配していた。",
   example2:"Many people pray to the Lord every Sunday.",
   exampleJa2:"多くの人が、毎週日曜日に神に祈る。",
   etymologyProcess:"loaf（パン）＋ ward（見張る）→ 一家のパンを守る人は…？",
   etymologyConclusion:"loaf（パン）＋ ward（見張る）→ パンを守って人々を養う主人＝（封建時代の）領主，君主",
   spelling:"loaf＋ward→lord（古英語 hlaford が縮まった）",
   why:"【なぜ】古英語 hlaford は hlaf（パン）＋ weard（番人）で「パンの番人」。家の食べ物を管理し、家族や使用人を養う主人のことでした。そこから土地と人々を治める領主や君主の意味になり、キリスト教では神を「主」と呼ぶときにも使われました。\n【つながり】lady も hlaf（パン）から出た語で、もとは「パンをこねる人」＝家の女主人です。",
   etymologyMore:["人々を治める主人→（the Lord）神，主","身分の高い主人→（英国の）貴族，卿"],
   relatedWords:[
     {word:"lady",meaning:"婦人，淑女",breakdown:"loaf（パン）→ パンをこねる女主人"},
     {word:"guard",meaning:"守る；見張り",breakdown:"ward（見張る）→ 見張って守る"},
     {word:"award",meaning:"賞",breakdown:"ex（すっかり）＋ ward（見張る）→ よく見て決めて与える"},
     {synonym:true,word:"king",meaning:"王",breakdown:"国をおさめる王。lord は土地や人々を治める主人"}]},

  {id:2197,word:"saint",partOfSpeech:"名詞",meaning:"聖人",
   meanings:["名|聖人","名|聖人のような人"],
   pronunciation:"/seɪnt/",part:220,
   example:"Many churches in Europe are named after a saint.",
   exampleJa:"ヨーロッパの多くの教会は、聖人の名にちなんで名づけられている。",
   example2:"My grandmother is so kind that everyone calls her a saint.",
   exampleJa2:"祖母はとても優しいので、みんなから聖人のような人と呼ばれている。",
   etymologyProcess:"sanct（神聖な）→ 神に認められたきよらかな人は…？",
   etymologyConclusion:"sanct（神聖な）→ 神に認められた、けがれのない神聖な人＝聖人",
   spelling:"sanct→saint（フランス語を通って変化）",
   etymologyMore:["聖人のようにきよらか→聖人のような人"],
   relatedWords:[
     {word:"sanctuary",meaning:"聖域；保護区",breakdown:"sanct（神聖な）＋ ary（もの）→ 神聖で手を出せない場所"},
     {word:"sanction",meaning:"制裁；認可",breakdown:"sanct（神聖な）＋ ion（名詞）→ 神聖なものとして定めた決まり"},
     {synonym:true,word:"Santa Claus",meaning:"サンタクロース",breakdown:"Saint Nicholas（聖ニコラス）がなまった呼び名"},
     {synonym:true,word:"holy",meaning:"神聖な",breakdown:"sanct と同じ意味のふつうの英語"}]},

  {id:2198,word:"prophet",partOfSpeech:"名詞",meaning:"預言者",
   meanings:["名|預言者","名|（主義などの）提唱者"],
   pronunciation:"/ˈprɑːfɪt/",part:220,
   example:"The prophet warned the people that a great flood would come.",
   exampleJa:"その預言者は、大洪水が来ると人々に警告した。",
   example2:"In Islam, Muhammad is regarded as the last prophet.",
   exampleJa2:"イスラム教では、ムハンマドは最後の預言者とされている。",
   etymologyProcess:"pro（人前で）＋ phe（語る）→ 神の言葉を人前で語る人は…？",
   etymologyConclusion:"pro（人前で）＋ phe（語る）→ 神に代わって神の言葉を人前で語る人＝預言者",
   etymologyMore:["新しい考えを人前で語る→（主義などの）提唱者"],
   relatedWords:[
     {word:"prophecy",meaning:"予言",breakdown:"pro（人前で）＋ phe（語る）＋ cy（名詞）→ 先のことを語った言葉"},
     {word:"proclaim",meaning:"宣言する",breakdown:"pro（人前で）＋ claim（叫ぶ）→ 人前で大声で告げる"},
     {word:"protest",meaning:"抗議する",breakdown:"pro（人前で）＋ test（証言する）→ 人前で反対を述べる"},
     {synonym:true,word:"messenger",meaning:"使者，伝える人",breakdown:"知らせを運ぶ人。prophet は神の言葉を伝える"}]},

  {id:2199,word:"pilgrim",partOfSpeech:"名詞",meaning:"巡礼者",
   meanings:["名|巡礼者"],
   pronunciation:"/ˈpɪlɡrɪm/",part:220,
   example:"Thousands of pilgrims visit the old temple every year.",
   exampleJa:"毎年、何千人もの巡礼者がその古い寺を訪れる。",
   example2:"Our trip felt like a pilgrimage to the hometown of our favorite band.",
   exampleJa2:"その旅は、好きなバンドの故郷への巡礼のように感じられた。",
   etymologyProcess:"per（通して）＋ agri（畑）→ 畑を通り越して遠くから来た人は…？",
   etymologyConclusion:"per（通して）＋ agri（畑）→ 畑を越えて遠くから聖地を訪ねてくる旅人＝巡礼者",
   spelling:"per＋agri→pilgri（フランス語などを通って変化）",
   why:"【なぜ】ラテン語 peregrinus は per（通して）＋ ager（畑・土地）で「自分の土地の外から来た人」＝よそ者。中世には、聖地を目指して遠くから旅をしてくる信者がどこでも「よそ者」だったので、この語が巡礼者を指すようになりました。\n【つながり】pilgrimage（巡礼の旅）は、好きな作品の舞台を訪ねる「聖地巡礼」にも使えます。",
   relatedWords:[
     {word:"agriculture",meaning:"農業",breakdown:"agri（畑）＋ cult（耕す）→ 畑を耕すこと"},
     {word:"perfume",meaning:"香水",breakdown:"per（通して）＋ fume（煙）→ 煙を通して広がる香り"},
     {synonym:true,word:"traveler",meaning:"旅行者",breakdown:"旅をする人全般。pilgrim は聖地を目指す旅人"},
     {synonym:true,word:"stranger",meaning:"よそ者，見知らぬ人",breakdown:"よその土地の人。pilgrim のもとの意味に近い"}]},

  {id:2200,word:"salvation",partOfSpeech:"名詞",meaning:"（神による）救い，救済",
   meanings:["名|（神による）救い，救済","名|救いとなるもの［人］"],
   pronunciation:"/sælˈveɪʃən/",part:220,
   example:"Many people turned to religion in search of salvation.",
   exampleJa:"多くの人が、救いを求めて宗教に頼った。",
   example2:"For our weak team, the new coach was a real salvation.",
   exampleJa2:"弱い私たちのチームにとって、新しいコーチはまさに救いとなる人だった。",
   etymologyProcess:"sav（無事な）＋ ation（名詞）→ 危険や罪から無事にすることは…？",
   etymologyConclusion:"sav（無事な）＋ ation（名詞）→ 危険や罪から助け出して無事にすること＝（神による）救い，救済",
   spelling:"sav→salv（ラテン語 salvare の形）",
   etymologyMore:["人を無事にしてくれる→救いとなるもの［人］"],
   relatedWords:[
     {word:"save",meaning:"救う；たくわえる",breakdown:"sav（無事な）→ 危険から無事にする"},
     {word:"safe",meaning:"安全な",breakdown:"sav（無事な）→ 危険のない無事な"},
     {word:"safety",meaning:"安全",breakdown:"sav（無事な）＋ ty（名詞）→ 無事である状態"},
     {synonym:true,word:"rescue",meaning:"救助",breakdown:"危険から人を助け出すこと。salvation は魂の救いにも使う"}]},
