  {id:1801,word:"misleading",partOfSpeech:"形容詞",meaning:"誤解を招く，紛らわしい",
   meanings:["形|誤解を招く，紛らわしい"],
   pronunciation:"/ˌmɪsˈliːdɪŋ/",part:181,
   example:"The advertisement gave a misleading picture of the tiny hotel.",
   exampleJa:"その広告は、小さなホテルについて誤解を招く印象を与えた。",
   example2:"Be careful, because some headlines online are very misleading.",
   exampleJa2:"気をつけて。ネットの見出しの中には、とても誤解を招くものがある。",
   etymologyProcess:"mis（誤って）＋ lead（導く）→ まちがった方へ導いていくと…？",
   etymologyConclusion:"mis（誤って）＋ lead（導く）＋ ing（～している）→ 人をまちがった考えへ導いてしまう＝誤解を招く",
   relatedWords:[
     {word:"mislead",meaning:"誤解させる",breakdown:"mis（誤って）＋ lead（導く）→ 人をまちがった方向へ連れていく"},
     {word:"leader",meaning:"指導者，リーダー",breakdown:"lead（導く）＋ er（人）→ みんなの先に立って導く人"},
     {word:"mistake",meaning:"誤り，まちがい",breakdown:"mis（誤って）＋ take（取る）→ 取りちがえてしまうこと"},
     {synonym:true,word:"confusing",meaning:"まぎらわしい，わかりにくい",breakdown:"頭が混乱する。misleading はまちがった方へ思い込ませる"}]},

  {id:1802,word:"obscure",partOfSpeech:"形容詞",meaning:"はっきりしない，不明瞭な；無名の",
   meanings:["形|はっきりしない，不明瞭な","形|無名の，世に知られていない","他|覆い隠す，見えにくくする"],
   pronunciation:"/əbˈskjʊr/",part:181,
   example:"The meaning of the last line of the poem is still obscure.",
   exampleJa:"その詩の最後の行の意味は、今でもはっきりしない。",
   example2:"The band was obscure until their song became popular online.",
   exampleJa2:"そのバンドは、曲がネットで人気になるまで無名だった。",
   etymologyProcess:"ob（～に向かって）＋ scur（覆う）→ 上から覆いをかぶせると…？",
   etymologyConclusion:"ob（～に向かって）＋ scur（覆う）→ 覆いをかけられて暗く、中がよく見えない＝はっきりしない",
   etymologyMore:["暗がりにいて人目につかない→無名の，世に知られていない"],
   relatedWords:[
     {word:"obscurity",meaning:"不明瞭；無名",breakdown:"ob（～に向かって）＋ scur（覆う）＋ ity（名詞）→ 覆われて見えない状態"},
     {word:"obvious",meaning:"明らかな",breakdown:"ob（向かい合って）＋ vi（道）→ 道の真ん前にあって見落とせない"},
     {synonym:true,word:"unclear",meaning:"はっきりしない",breakdown:"ふつうの「はっきりしない」。obscure は暗く覆われた感じ"},
     {synonym:true,word:"vague",meaning:"あいまいな",breakdown:"輪郭がぼんやりしている。obscure は隠れて見えにくい"}]},

  {id:1803,word:"mature",partOfSpeech:"形容詞",meaning:"成熟した，大人びた",
   meanings:["形|成熟した，大人びた","形|（果実・ワインなどが）熟した","自|成熟する，熟す"],
   pronunciation:"/məˈtʃʊr/",part:181,
   example:"She is very mature for a girl of only fourteen.",
   exampleJa:"彼女はわずか14歳の少女にしては、とても成熟している。",
   example2:"The apples will fully mature on the trees by October.",
   exampleJa2:"りんごは10月までに、木の上で十分に熟すだろう。",
   etymologyProcess:"matur（熟した）→ 果実が時を待って食べごろになると…？",
   etymologyConclusion:"matur（熟した）→ 果実が熟すように、心や体が十分に育った＝成熟した",
   hook:"果物が「熟す」のも人が「大人になる」のも mature。時間をかけて中身が育つ感じ。",
   relatedWords:[
     {word:"immature",meaning:"未熟な，子どもっぽい",breakdown:"im（否定）＋ matur（熟した）→ まだ熟していない"},
     {word:"premature",meaning:"早すぎる",breakdown:"pre（先に）＋ matur（熟した）→ 熟す前に先走って来てしまう"},
     {synonym:true,word:"grown-up",meaning:"大人の；大人",breakdown:"育ちきった人。mature は考え方まで大人びていること"},
     {synonym:true,word:"ripe",meaning:"（果実が）熟した",breakdown:"食べごろの果物。mature は人にも果物にも使える"}]},

  {id:1804,word:"neat",partOfSpeech:"形容詞",meaning:"（身なり・字などが）きちんとした，こぎれいな",
   meanings:["形|（身なり・字などが）きちんとした，こぎれいな","形|（米口語）すてきな，いかした"],
   pronunciation:"/niːt/",part:181,
   example:"He always wears a neat white shirt to school.",
   exampleJa:"彼はいつもきちんとした白いシャツを着て登校する。",
   example2:"That's a neat idea! Let's try it at the school festival.",
   exampleJa2:"それはすてきな考えだね！文化祭でやってみよう。",
   etymologyProcess:"nit（輝く）→ ぴかぴかに光って汚れがないと…？",
   etymologyConclusion:"nit（輝く）→ ぴかぴかに光るほど汚れも乱れもない＝（身なり・字などが）きちんとした",
   spelling:"nit→neat（ラテン語 nitidus がフランス語 net を通って変化）",
   etymologyMore:["すっきり整って気持ちがいい→（米口語）すてきな，いかした"],
   relatedWords:[
     {word:"neatly",meaning:"きちんと",breakdown:"nit（輝く）＋ ly（副詞）→ ぴかぴかに整えて"},
     {word:"net",meaning:"正味の",breakdown:"nit（輝く）→ 汚れや余分をすっかり除いた中身だけの量"},
     {synonym:true,word:"tidy",meaning:"きちんと片づいた",breakdown:"部屋や物が片づいている。neat は見た目がこぎれい"},
     {synonym:true,word:"clean",meaning:"きれいな，清潔な",breakdown:"汚れがない。neat は汚れがなく形まで整っている"}]},

  {id:1805,word:"decent",partOfSpeech:"形容詞",meaning:"（世間並みに）まともな；かなりよい",
   meanings:["形|（世間並みに）まともな，ちゃんとした","形|（量・質が）かなりよい，悪くない","形|礼儀正しい，親切な"],
   pronunciation:"/ˈdiːsnt/",part:181,
   example:"Everyone deserves a decent place to live and enough food.",
   exampleJa:"誰もが、住むためのまともな場所と十分な食べ物を得るべきだ。",
   example2:"I got a decent score on the English test yesterday.",
   exampleJa2:"昨日の英語のテストでは、かなりよい点を取った。",
   etymologyProcess:"decen（ふさわしい）→ その場に似合っていると…？",
   etymologyConclusion:"decen（ふさわしい）→ その場にふさわしく、人前で恥ずかしくない＝（世間並みに）まともな",
   etymologyMore:["恥ずかしくない水準に届いている→（量・質が）かなりよい，悪くない"],
   relatedWords:[
     {word:"indecent",meaning:"下品な，みだらな",breakdown:"in（否定）＋ decen（ふさわしい）→ 人前にふさわしくない"},
     {word:"decency",meaning:"礼儀正しさ，良識",breakdown:"decen（ふさわしい）＋ cy（名詞）→ ふさわしくふるまう心"},
     {synonym:true,word:"proper",meaning:"適切な，ちゃんとした",breakdown:"決まりに合っている。decent は世間並みで恥ずかしくない"},
     {synonym:true,word:"polite",meaning:"礼儀正しい",breakdown:"言葉やふるまいがていねい。decent は人として恥ずかしくない"}]},

  {id:1806,word:"straightforward",partOfSpeech:"形容詞",meaning:"（説明などが）わかりやすい，簡単な；率直な",
   meanings:["形|（説明・作業が）わかりやすい，簡単な","形|（人・態度が）率直な，正直な"],
   pronunciation:"/ˌstreɪtˈfɔːrwərd/",part:181,
   example:"The instructions were straightforward, so we finished the test quickly.",
   exampleJa:"指示がわかりやすかったので、私たちはすぐにテストを終えた。",
   example2:"She gave me a straightforward answer about why she was angry.",
   exampleJa2:"彼女はなぜ怒っているのか、率直な答えを返してくれた。",
   etymologyProcess:"straight（まっすぐな）＋ forward（前へ）→ 回り道せずに前へ進むと…？",
   etymologyConclusion:"straight（まっすぐな）＋ forward（前へ）→ 回り道も迷いもなく、まっすぐ前へ進める＝（説明などが）わかりやすい",
   etymologyMore:["言葉を曲げずにまっすぐ出す→（人・態度が）率直な，正直な"],
   relatedWords:[
     {word:"straight",meaning:"まっすぐな；まっすぐに",breakdown:"straight（まっすぐな）→ 曲がらずに一直線に伸びる"},
     {word:"forward",meaning:"前へ",breakdown:"forward（前へ）→ 顔の向いているほうへ進む"},
     {word:"straighten",meaning:"まっすぐにする",breakdown:"straight（まっすぐな）＋ en（～にする）→ 曲がったものを直す"},
     {synonym:true,word:"simple",meaning:"簡単な，単純な",breakdown:"こみ入っていない。straightforward は迷わず進める"}]},

  {id:1807,word:"sophisticated",partOfSpeech:"形容詞",meaning:"洗練された；（機械などが）高度な",
   meanings:["形|洗練された，都会的な","形|（機械・技術などが）高度な，精巧な"],
   pronunciation:"/səˈfɪstɪkeɪtɪd/",part:181,
   example:"My aunt has very sophisticated taste in clothes and music.",
   exampleJa:"おばは、服や音楽についてとても洗練された趣味を持っている。",
   example2:"This robot uses highly sophisticated software to recognize people's faces.",
   exampleJa2:"このロボットは、人の顔を見分けるのに高度なソフトウェアを使っている。",
   etymologyProcess:"soph（知恵）＋ ist（人）→ 知恵者のように手を加えると…？",
   etymologyConclusion:"soph（知恵）＋ ist（人）＋ ate（～にする）→ 知恵を重ねて素朴さを抜け出した＝洗練された",
   why:"【なぜ】古代ギリシャの sophist（ソフィスト）は知恵を教える弁論の先生でしたが、のちに「へりくつ屋」の意味になりました。そこから sophisticate は「小細工して混ぜ物をする」、さらに「素朴さを失って世慣れる」を表し、20世紀に「洗練された」というよい意味へ変わりました。\n【つながり】philosophy（哲学）も soph（知恵）の仲間で、「知恵を愛する」が語源です。",
   etymologyMore:["人の知恵と手を幾重にも加えた→（機械・技術などが）高度な，精巧な"],
   relatedWords:[
     {word:"philosophy",meaning:"哲学",breakdown:"phil（愛する）＋ soph（知恵）→ 知恵を愛して考え抜く学問"},
     {word:"philosopher",meaning:"哲学者",breakdown:"phil（愛する）＋ soph（知恵）＋ er（人）→ 知恵を愛する人"},
     {synonym:true,word:"elegant",meaning:"上品な，優雅な",breakdown:"姿や動きが美しい。sophisticated は知識や経験で磨かれた感じ"},
     {synonym:true,word:"advanced",meaning:"進んだ，高度な",breakdown:"先へ進んでいる。sophisticated は作りが複雑で精巧"}]},

  {id:1808,word:"elaborate",partOfSpeech:"形容詞",meaning:"手の込んだ，入念な",
   meanings:["形|手の込んだ，入念な","自|（on ～について）詳しく述べる"],
   pronunciation:"/ɪˈlæbərət/",part:181,
   example:"They prepared an elaborate dinner for their parents' anniversary.",
   exampleJa:"彼らは両親の結婚記念日のために、手の込んだ夕食を用意した。",
   example2:"Could you elaborate on your plan a little more?",
   exampleJa2:"あなたの計画について、もう少し詳しく述べてもらえますか。",
   usage:["elaborate on 事（事について詳しく述べる）"],
   etymologyProcess:"e（外へ）＋ labor（働く）→ 働きに働いて作り出すと…？",
   etymologyConclusion:"e（外へ）＋ labor（働く）＋ ate（～にする）→ 手間をかけて働き、じっくり作り上げた＝手の込んだ",
   etymologyMore:["話にも手間をかけて作り込む→（on ～について）詳しく述べる"],
   relatedWords:[
     {word:"labor",meaning:"労働",breakdown:"labor（働く）→ 体を使って骨を折る仕事"},
     {word:"laboratory",meaning:"実験室",breakdown:"labor（働く）＋ ory（場所）→ 研究者が働く部屋"},
     {word:"collaborate",meaning:"協力する",breakdown:"col（共に）＋ labor（働く）＋ ate（～にする）→ 一緒に働く"},
     {synonym:true,word:"detailed",meaning:"詳しい，細かい",breakdown:"細部まで書かれている。elaborate は手間をかけて作り込んだ"}]},

  {id:1809,word:"prompt",partOfSpeech:"形容詞",meaning:"即座の，迅速な；促す",
   meanings:["形|即座の，迅速な","他|（人に…するよう）促す，引き起こす","名|（パソコンの）プロンプト"],
   pronunciation:"/prɑːmpt/",part:181,
   example:"Thank you for your prompt reply to my email.",
   exampleJa:"私のメールに即座の返信をくれてありがとう。",
   example2:"The heavy rain prompted the school to cancel the sports day.",
   exampleJa2:"大雨が、学校に運動会の中止を促した。",
   usage:["prompt 人 to do（人に～するよう促す）"],
   etymologyProcess:"pro（前へ）＋ empt（取る）→ すぐ前へ取り出せると…？",
   etymologyConclusion:"pro（前へ）＋ empt（取る）→ すぐ前へ取り出せるほど準備ができている＝即座の",
   spelling:"empt→mpt（promere で e が落ちた）",
   etymologyMore:["前へ引き出す→（人に…するよう）促す，引き起こす"],
   relatedWords:[
     {word:"example",meaning:"例",breakdown:"ex（外へ）＋ empt（取る）→ たくさんの中から取り出した一つ"},
     {word:"sample",meaning:"見本，サンプル",breakdown:"ex（外へ）＋ empt（取る）→ example が縮まった形。取り出した一部"},
     {word:"promptly",meaning:"すぐに，てきぱきと",breakdown:"pro（前へ）＋ empt（取る）＋ ly（副詞）→ すぐ取り出すように"},
     {synonym:true,word:"quick",meaning:"すばやい",breakdown:"動きが速い。prompt は求められてすぐ応じる"}]},

  {id:1810,word:"swift",partOfSpeech:"形容詞",meaning:"（動きが）すばやい，速い",
   meanings:["形|（動きが）すばやい，速い","形|（対応・反応が）迅速な，即座の"],
   pronunciation:"/swɪft/",part:181,
   example:"The swift runner caught up with the others in seconds.",
   exampleJa:"そのすばやいランナーは、数秒で他の選手に追いついた。",
   example2:"The government promised a swift response to the flood.",
   exampleJa2:"政府は洪水への迅速な対応を約束した。",
   etymologyProcess:"swift（すっと動く）→ 空をすっと滑るように動くと…？",
   etymologyConclusion:"swift（すっと動く）→ 鳥が空をすっと滑るように速く動く＝（動きが）すばやい",
   hook:"鳥のアマツバメも swift。空を飛び回る速さがそのまま名前になった。",
   relatedWords:[
     {word:"swiftly",meaning:"すばやく",breakdown:"swift（すっと動く）＋ ly（副詞）→ すっと速く"},
     {synonym:true,word:"quick",meaning:"すばやい",breakdown:"短い時間でさっと。swift はなめらかに速い"},
     {synonym:true,word:"fast",meaning:"速い",breakdown:"スピードが出ている。swift は軽やかな速さ"},
     {synonym:true,word:"rapid",meaning:"急速な",breakdown:"変化や流れが速い。swift は動きそのものが速い"}]},

  {id:1811,word:"mighty",partOfSpeech:"形容詞",meaning:"強大な，力強い",
   meanings:["形|強大な，力強い","形|（大きさが）巨大な，すさまじい"],
   pronunciation:"/ˈmaɪti/",part:182,
   example:"The mighty river flows through the center of the country.",
   exampleJa:"その強大な川は、国の中心部を流れている。",
   example2:"As the saying goes, the pen is mightier than the sword.",
   exampleJa2:"ことわざにあるとおり、ペンは剣よりも力強い。",
   etymologyProcess:"might（力）＋ y（形容詞）→ 力がみなぎっていると…？",
   etymologyConclusion:"might（力）＋ y（形容詞）→ あふれるほどの力を持っている＝強大な",
   relatedWords:[
     {word:"might",meaning:"力，勢力",breakdown:"might（力）→ 何かをやりとげられる大きな力"},
     {word:"almighty",meaning:"全能の",breakdown:"all（すっかり）＋ might（力）→ どんなこともできる力を持つ"},
     {synonym:true,word:"powerful",meaning:"力強い，強力な",breakdown:"力にあふれている。mighty は巨大さや威厳まで感じさせる"},
     {synonym:true,word:"strong",meaning:"強い",breakdown:"ふつうの「強い」。mighty は圧倒するほど強い"}]},

  {id:1812,word:"explicit",partOfSpeech:"形容詞",meaning:"はっきり述べられた，明示的な",
   meanings:["形|はっきり述べられた，明示的な","形|（性・暴力の表現が）露骨な"],
   pronunciation:"/ɪkˈsplɪsɪt/",part:182,
   example:"The rules were explicit: no phones are allowed during the exam.",
   exampleJa:"規則ははっきり述べられていた。試験中は携帯電話を使ってはいけない。",
   example2:"Please be more explicit about what you want me to do.",
   exampleJa2:"私に何をしてほしいのか、もっとはっきり言ってください。",
   etymologyProcess:"ex（外へ）＋ plic（折る）→ 折りたたんだものを外へ広げると…？",
   etymologyConclusion:"ex（外へ）＋ plic（折る）→ 折りたたんだ中身を外へ広げて見せる＝はっきり述べられた",
   relatedWords:[
     {word:"implicit",meaning:"暗黙の",breakdown:"im（中へ）＋ plic（折る）→ 中に折りこまれて表に出ない"},
     {word:"complicated",meaning:"複雑な",breakdown:"com（共に）＋ plic（折る）＋ ate（～にする）→ 何重にも折り重なる"},
     {word:"apply",meaning:"当てはめる；申し込む",breakdown:"ad（～へ）＋ pli（折る）→ 相手のほうへ折り重ねてくっつける"},
     {synonym:true,word:"clear",meaning:"はっきりした",breakdown:"ふつうの「はっきりした」。explicit は言葉ではっきり言ってある"}]},

  {id:1813,word:"authentic",partOfSpeech:"形容詞",meaning:"本物の，正真正銘の",
   meanings:["形|本物の，正真正銘の","形|（話・情報が）信頼できる，確かな"],
   pronunciation:"/ɔːˈθentɪk/",part:182,
   example:"This restaurant serves authentic Italian pizza baked in a wood oven.",
   exampleJa:"この店は、まき窯で焼いた本物のイタリアのピザを出している。",
   example2:"Experts say the old painting in the museum is not authentic.",
   exampleJa2:"専門家によると、美術館のその古い絵は本物ではない。",
   etymologyProcess:"auto（自分）＋ hent（行う）→ 本人が自分の手でやったと…？",
   etymologyConclusion:"auto（自分）＋ hent（行う）＋ ic（形容詞）→ 本人が自分の手で作った確かなもの＝本物の",
   why:"【なぜ】ギリシャ語 authentēs は「自分の手で事をなす人」。後半の成り立ちには不確かな点もあります。「本人が自ら手がけた」ものは写しでも偽物でもないので、「原本の」「権威ある」、さらに「本物の」という意味になりました。\n【つながり】auto（自分）は autograph（有名人のサイン）の auto。author（作者）は見た目が似ていますが別の語源です。",
   spelling:"auto→aut（o が落ちた）",
   relatedWords:[
     {word:"autograph",meaning:"（有名人の）サイン",breakdown:"auto（自分）＋ graph（書く）→ 本人が自分の手で書いた名前"},
     {word:"automobile",meaning:"自動車",breakdown:"auto（自分）＋ mob（動かす）→ 自分の力で動かせる車"},
     {synonym:true,word:"genuine",meaning:"本物の",breakdown:"生まれつきの本物。authentic は出どころが確かな本物"},
     {synonym:true,word:"real",meaning:"本当の，実在の",breakdown:"いちばんふつうの「本物の」。authentic は偽物でないと保証できる"}]},

  {id:1814,word:"wit",partOfSpeech:"名詞",meaning:"機知，ウィット",
   meanings:["名|機知，ウィット","名|（wits で）知恵，正気"],
   pronunciation:"/wɪt/",part:182,
   example:"Her quick wit made everyone in the classroom laugh.",
   exampleJa:"彼女のすばやい機知に、教室のみんなが笑った。",
   example2:"I was at my wits' end when I lost my passport.",
   exampleJa2:"パスポートをなくして、私は途方に暮れた。",
   usage:["at one's wits' end（途方に暮れて）"],
   etymologyProcess:"wit（知っている）→ ものをよく知っている頭の働きは…？",
   etymologyConclusion:"wit（知っている）→ よく知っていて、とっさにうまく言葉が出る頭の働き＝機知",
   etymologyMore:["物事を知り判断する頭の力→（wits で）知恵，正気"],
   hook:"日本語の「ウィットに富んだ会話」の wit。気のきいた一言がぱっと出る力。",
   relatedWords:[
     {word:"witness",meaning:"目撃者",breakdown:"wit（知っている）＋ ness（名詞）→ その場を見て知っている人"},
     {word:"wise",meaning:"賢い",breakdown:"wit（知っている）→ 多くを知っていて正しく判断できる"},
     {word:"witty",meaning:"機知に富んだ",breakdown:"wit（知っている）＋ y（形容詞）→ 気のきいた一言がすぐ出る"},
     {synonym:true,word:"humor",meaning:"ユーモア",breakdown:"人を笑わせる味わい。wit は頭の回転の速さが光る"}]},

  {id:1815,word:"thrive",partOfSpeech:"自動詞",meaning:"よく育つ，すくすく成長する",
   meanings:["自|よく育つ，すくすく成長する","自|（事業・町などが）栄える，繁盛する"],
   pronunciation:"/θraɪv/",part:182,
   example:"Tomatoes thrive in hot, sunny weather with plenty of water.",
   exampleJa:"トマトは、水が十分にある暑く晴れた天候でよく育つ。",
   example2:"Small shops in this town thrived thanks to the new station.",
   exampleJa2:"新しい駅のおかげで、この町の小さな店は繁盛した。",
   etymologyProcess:"thrive（つかみ取る）→ 自分の分をしっかりつかみ取ると…？",
   etymologyConclusion:"thrive（つかみ取る）→ 栄養や恵みをしっかりつかんで伸びていく＝よく育つ",
   etymologyMore:["人や店が勢いよく伸びる→（事業・町などが）栄える，繁盛する"],
   hook:"北欧の古い語から。植物がすくすく育つ姿を思い浮かべると、店や町の繁盛にもつながる。",
   relatedWords:[
     {word:"thrift",meaning:"倹約",breakdown:"thrive（つかみ取る）＋ t（名詞）→ つかんだ富をむだにせず守る"},
     {synonym:true,word:"grow",meaning:"育つ，成長する",breakdown:"ふつうの「育つ」。thrive は元気いっぱいに育つ"},
     {synonym:true,word:"flourish",meaning:"栄える，繁盛する",breakdown:"花が咲くように栄える。thrive は勢いよく伸びる"},
     {synonym:true,word:"succeed",meaning:"成功する",breakdown:"目的を果たす。thrive は続けて伸び続ける"}]},

  {id:1816,word:"dim",partOfSpeech:"形容詞",meaning:"（光が）薄暗い，ほの暗い",
   meanings:["形|（光が）薄暗い，ほの暗い","形|（記憶・見通しが）ぼんやりした","自|（明かりが）暗くなる"],
   pronunciation:"/dɪm/",part:182,
   example:"It was hard to read in the dim light of the candle.",
   exampleJa:"ろうそくの薄暗い光の中では、本を読むのが難しかった。",
   example2:"The lights in the theater dimmed as the movie began.",
   exampleJa2:"映画が始まると、劇場の明かりが暗くなった。",
   etymologyProcess:"dim（かすんだ）→ 光がかすんで弱まると…？",
   etymologyConclusion:"dim（かすんだ）→ 光が弱くかすんで、よく見えない＝（光が）薄暗い",
   etymologyMore:["かすんで輪郭が見えない→（記憶・見通しが）ぼんやりした"],
   hook:"照明を暗くするスイッチは dimmer（調光器）。光がすっと弱まる感じ。",
   relatedWords:[
     {word:"dimly",meaning:"ぼんやりと",breakdown:"dim（かすんだ）＋ ly（副詞）→ かすんでよく見えないように"},
     {synonym:true,word:"dark",meaning:"暗い",breakdown:"光がない。dim は少しだけ光があって薄暗い"},
     {synonym:true,word:"faint",meaning:"かすかな",breakdown:"音や光がかすか。dim は明かりが弱いこと"},
     {synonym:true,word:"vague",meaning:"ぼんやりした",breakdown:"考えや記憶があいまい。dim は光や記憶がかすむ"}]},

  {id:1817,word:"gloomy",partOfSpeech:"形容詞",meaning:"（空・場所が）どんよりと暗い；憂うつな",
   meanings:["形|（空・場所が）どんよりと暗い","形|（気分・見通しが）憂うつな，暗い"],
   pronunciation:"/ˈɡluːmi/",part:182,
   example:"It was a gloomy morning with dark clouds and heavy rain.",
   exampleJa:"黒い雲と激しい雨の、どんよりと暗い朝だった。",
   example2:"He looked gloomy after hearing his test results.",
   exampleJa2:"テストの結果を聞いて、彼は憂うつそうだった。",
   etymologyProcess:"gloom（どんより暗い）→ 空一面が暗く曇ると…？",
   etymologyConclusion:"gloom（どんより暗い）→ 雲が垂れこめて光が届かない＝（空・場所が）どんよりと暗い",
   etymologyMore:["空のどんよりが心にもかかる→（気分・見通しが）憂うつな，暗い"],
   hook:"語源ははっきりしない。gloom（暗がり；憂うつ）＋ y で、空も気分もどんより。",
   relatedWords:[
     {word:"gloom",meaning:"暗がり；憂うつ",breakdown:"gloom（どんより暗い）→ 光も元気も届かない暗さ"},
     {synonym:true,word:"dark",meaning:"暗い",breakdown:"光がない。gloomy は重たく沈んだ暗さ"},
     {synonym:true,word:"sad",meaning:"悲しい",breakdown:"ふつうの「悲しい」。gloomy は気分が重く沈む"},
     {synonym:true,word:"dim",meaning:"薄暗い",breakdown:"明かりが弱い。gloomy は雰囲気まで暗い"}]},

  {id:1818,word:"barren",partOfSpeech:"形容詞",meaning:"（土地が）不毛な，作物ができない",
   meanings:["形|（土地が）不毛な，作物ができない","形|（of ～が）なくて，何も生まない"],
   pronunciation:"/ˈbærən/",part:182,
   example:"Nothing could grow on the barren land after the long drought.",
   exampleJa:"長い干ばつのあと、その不毛な土地には何も育たなかった。",
   example2:"The long meeting was barren of any new ideas.",
   exampleJa2:"その長い会議からは、新しいアイデアが何も生まれなかった。",
   etymologyProcess:"barren（実らない）→ 種をまいても何も実らない土地は…？",
   etymologyConclusion:"barren（実らない）→ 種をまいても芽が出ず、何も実らない＝（土地が）不毛な",
   hook:"語源ははっきりしない。barren land（不毛の地）の形で、実りのなさを表す。",
   relatedWords:[
     {synonym:true,word:"dry",meaning:"乾いた",breakdown:"水気がない。barren は作物が育たない"},
     {synonym:true,word:"empty",meaning:"空の",breakdown:"中に何もない。barren は何も生み出さない"},
     {synonym:true,word:"bare",meaning:"むき出しの",breakdown:"覆うものがない。barren は草木も実りもない"},
     {synonym:true,word:"desert",meaning:"砂漠",breakdown:"雨の少ない土地。barren はその様子を表す形容詞"}]},

  {id:1819,word:"idle",partOfSpeech:"形容詞",meaning:"（機械などが）使われていない，（人が）何もしていない",
   meanings:["形|（機械などが）使われていない，（人が）何もしていない","形|怠けている，ぶらぶらしている","形|根拠のない，むだな"],
   pronunciation:"/ˈaɪdl/",part:182,
   example:"Many machines in the old factory are standing idle now.",
   exampleJa:"古い工場の多くの機械は、今は使われていない。",
   example2:"Don't stay idle all summer; find something useful to do.",
   exampleJa2:"夏じゅうぶらぶらしていないで、何か役に立つことを見つけなさい。",
   etymologyProcess:"idle（空っぽの）→ 中身が空っぽで働いていないと…？",
   etymologyConclusion:"idle（空っぽの）→ することが空っぽで、動かずに止まっている＝（機械などが）使われていない",
   etymologyMore:["中身のない話→根拠のない，むだな"],
   hook:"「アイドル（idol）」とは別の語。車のアイドリング（idling）は動かずに回っている状態。",
   relatedWords:[
     {word:"idleness",meaning:"怠けていること",breakdown:"idle（空っぽの）＋ ness（名詞）→ 何もせず過ごすこと"},
     {synonym:true,word:"lazy",meaning:"怠惰な",breakdown:"働く気がない。idle は今たまたま何もしていないことにも使う"},
     {synonym:true,word:"free",meaning:"暇な",breakdown:"予定がない。idle は動かずに止まっている"},
     {synonym:true,word:"unused",meaning:"使われていない",breakdown:"一度も使われていないことも。idle は今は止まっている"}]},

  {id:1820,word:"adverse",partOfSpeech:"形容詞",meaning:"（影響などが）有害な；不利な",
   meanings:["形|（影響などが）有害な，悪い","形|（状況が）不利な，逆の"],
   pronunciation:"/ædˈvɜːrs/",part:182,
   example:"Too much screen time can have adverse effects on your eyes.",
   exampleJa:"画面の見すぎは、目に有害な影響を与えることがある。",
   example2:"The game went ahead despite adverse weather conditions.",
   exampleJa2:"不利な天候にもかかわらず、試合は行われた。",
   etymologyProcess:"ad（～へ）＋ vers（回る）→ こちらへ向き直って立ちはだかると…？",
   etymologyConclusion:"ad（～へ）＋ vers（回る）→ こちらへ向き直って逆らうように働く＝（影響などが）有害な",
   etymologyMore:["向かい風のように逆らってくる→（状況が）不利な，逆の"],
   relatedWords:[
     {word:"reverse",meaning:"逆にする；逆の",breakdown:"re（後ろへ）＋ vers（回る）→ くるりと回して後ろ向きにする"},
     {word:"conversation",meaning:"会話",breakdown:"con（共に）＋ vers（回る）＋ ation（名詞）→ 言葉を行き来させる"},
     {word:"advertise",meaning:"宣伝する",breakdown:"ad（～へ）＋ vert（回る）→ 人の目をこちらへ向けさせる"},
     {synonym:true,word:"harmful",meaning:"有害な",breakdown:"害を与える。adverse は逆らうように悪く働く"}]},

  {id:1821,word:"tiresome",partOfSpeech:"形容詞",meaning:"うんざりする，飽き飽きする",
   meanings:["形|うんざりする，飽き飽きする","形|（人が）わずらわしい，面倒な"],
   pronunciation:"/ˈtaɪərsəm/",part:183,
   example:"Waiting in the long line at the bank was really tiresome.",
   exampleJa:"銀行の長い列で待つのは、本当にうんざりした。",
   example2:"His tiresome jokes made everyone at the party sigh.",
   exampleJa2:"彼のわずらわしい冗談に、パーティーの全員がため息をついた。",
   etymologyProcess:"tire（疲れさせる）＋ some（～を生む）→ 疲ればかり生むと…？",
   etymologyConclusion:"tire（疲れさせる）＋ some（～を生む）→ 同じことが続いて疲れを生む＝うんざりする",
   relatedWords:[
     {word:"tired",meaning:"疲れた；飽きた",breakdown:"tire（疲れさせる）＋ ed（～された）→ 疲れさせられた"},
     {word:"awesome",meaning:"すごい，最高の",breakdown:"awe（畏れ）＋ some（～を生む）→ 思わず畏れを生むほどすごい"},
     {word:"troublesome",meaning:"やっかいな",breakdown:"turb（かき乱す）＋ some（～を生む）→ 心をかき乱す面倒を生む"},
     {synonym:true,word:"boring",meaning:"退屈な",breakdown:"おもしろくない。tiresome は疲れてうんざりする"}]},

  {id:1822,word:"clumsy",partOfSpeech:"形容詞",meaning:"不器用な，よく物を落とす",
   meanings:["形|不器用な，よく物を落とす","形|（言動が）ぎこちない，下手な"],
   pronunciation:"/ˈklʌmzi/",part:183,
   example:"I'm so clumsy that I often drop my phone on the floor.",
   exampleJa:"私はとても不器用なので、よくスマホを床に落とす。",
   example2:"He made a clumsy attempt to apologize to her.",
   exampleJa2:"彼は彼女に、下手な謝り方をした。",
   etymologyProcess:"clums（かじかむ）＋ y（形容詞）→ 寒さで手がかじかむと…？",
   etymologyConclusion:"clums（かじかむ）＋ y（形容詞）→ 寒さでかじかんだ手のように思うように動かない＝不器用な",
   etymologyMore:["手が動かないように言葉も固まる→（言動が）ぎこちない，下手な"],
   relatedWords:[
     {word:"clumsily",meaning:"不器用に",breakdown:"clums（かじかむ）＋ ly（副詞）→ かじかんだ手のようにぎこちなく"},
     {synonym:true,word:"awkward",meaning:"ぎこちない",breakdown:"動きや場の空気がぎくしゃくする。clumsy は手先や体の動き"},
     {synonym:true,word:"careless",meaning:"不注意な",breakdown:"注意が足りない。clumsy は注意していても下手"},
     {synonym:true,word:"poor",meaning:"下手な",breakdown:"腕前がよくない。clumsy は動きがもたつく"}]},

  {id:1823,word:"foul",partOfSpeech:"形容詞",meaning:"（においなどが）胸の悪くなるような；反則",
   meanings:["形|（においなどが）胸の悪くなるような，悪臭のする","形|（天候・言葉が）ひどい，汚い","名|（スポーツの）反則，ファウル"],
   pronunciation:"/faʊl/",part:183,
   example:"A foul smell came from the trash can in the kitchen.",
   exampleJa:"台所のごみ箱から、胸の悪くなるようなにおいがした。",
   example2:"The referee called a foul when he pushed the goalkeeper.",
   exampleJa2:"彼がゴールキーパーを押したとき、審判は反則を取った。",
   etymologyProcess:"foul（腐った）→ 腐ったものが放つにおいは…？",
   etymologyConclusion:"foul（腐った）→ 腐ったような汚さで、においが鼻をつく＝（においなどが）胸の悪くなるような",
   etymologyMore:["汚いやり方でルールにそむく→（スポーツの）反則，ファウル"],
   hook:"野球やサッカーの「ファウル」も foul。鳥の fowl と同じ発音なので注意。",
   relatedWords:[
     {word:"filth",meaning:"汚れ，汚物",breakdown:"foul（腐った）＋ th（名詞）→ 腐ったような汚れ"},
     {synonym:true,word:"dirty",meaning:"汚い",breakdown:"ふつうの「汚い」。foul は吐き気がするほど汚い"},
     {synonym:true,word:"nasty",meaning:"不快な，いやな",breakdown:"いやな感じ全般。foul はにおいや汚さがひどい"},
     {synonym:true,word:"unpleasant",meaning:"不愉快な",breakdown:"気持ちよくない。foul はそれよりずっと強い"}]},

  {id:1824,word:"shabby",partOfSpeech:"形容詞",meaning:"（服・建物が）みすぼらしい，ぼろぼろの",
   meanings:["形|（服・建物が）みすぼらしい，ぼろぼろの","形|（扱いが）卑劣な，ひどい"],
   pronunciation:"/ˈʃæbi/",part:183,
   example:"He wore a shabby old coat with holes in the sleeves.",
   exampleJa:"彼は、袖に穴のあいたみすぼらしい古いコートを着ていた。",
   example2:"It was shabby of them to leave her out of the plan.",
   exampleJa2:"彼女を計画から外すなんて、彼らもひどいことをした。",
   etymologyProcess:"shab（かさぶた）＋ y（形容詞）→ かさぶただらけの姿は…？",
   etymologyConclusion:"shab（かさぶた）＋ y（形容詞）→ かさぶただらけのように傷んでいる＝（服・建物が）みすぼらしい",
   etymologyMore:["見た目だけでなく心まで貧しい→（扱いが）卑劣な，ひどい"],
   relatedWords:[
     {word:"shabbily",meaning:"みすぼらしく；ひどく",breakdown:"shab（かさぶた）＋ ly（副詞）→ 傷んだように"},
     {synonym:true,word:"old",meaning:"古い",breakdown:"年月がたった。shabby は古びて傷んでいる"},
     {synonym:true,word:"worn-out",meaning:"すり切れた",breakdown:"使いすぎてすり減った。shabby は見た目が貧相"},
     {synonym:true,word:"poor",meaning:"貧しい；粗末な",breakdown:"お金がない。shabby は見た目のみすぼらしさ"}]},

  {id:1825,word:"outrageous",partOfSpeech:"形容詞",meaning:"とんでもない，ひどく不当な",
   meanings:["形|とんでもない，ひどく不当な","形|（服装などが）奇抜な，度肝を抜く"],
   pronunciation:"/aʊtˈreɪdʒəs/",part:183,
   example:"The price of the tickets for the concert was outrageous.",
   exampleJa:"そのコンサートのチケットの値段は、とんでもなかった。",
   example2:"She wore an outrageous costume to the Halloween party.",
   exampleJa2:"彼女はハロウィーンのパーティーに奇抜な衣装で来た。",
   etymologyProcess:"ultra（越えて）＋ age（名詞）→ 限度を越えてしまうと…？",
   etymologyConclusion:"ultra（越えて）＋ age（名詞）＋ ous（～に満ちた）→ 許される限度を越えすぎている＝とんでもない",
   why:"【なぜ】見た目は out（外へ）＋ rage（激怒）ですが、実はちがいます。ラテン語 ultra（越えて）がフランス語 outre になり、outrage は「度を越すこと，行きすぎ」でした。あとから rage（激怒）と結びつけて感じられ、「人を激怒させるほどひどい」の意味が強まりました。\n【つながり】ultraviolet（紫外線）は紫の「向こう側」の光です。",
   spelling:"ultra→outr（フランス語 outre を通って変化）",
   etymologyMore:["常識の枠を越えて目立つ→（服装などが）奇抜な，度肝を抜く"],
   relatedWords:[
     {word:"outrage",meaning:"激しい怒り；暴挙",breakdown:"ultra（越えて）＋ age（名詞）→ 度を越したひどい行い"},
     {word:"ultraviolet",meaning:"紫外線の",breakdown:"ultra（越えて）＋ violet（紫）→ 紫の向こう側にある光"},
     {synonym:true,word:"shocking",meaning:"衝撃的な",breakdown:"人をびっくりさせる。outrageous は限度を越えて腹が立つ"},
     {synonym:true,word:"terrible",meaning:"ひどい",breakdown:"ひどい全般。outrageous は常識外れのひどさ"}]},

  {id:1826,word:"absurd",partOfSpeech:"形容詞",meaning:"理屈に合わない，ばかばかしい",
   meanings:["形|理屈に合わない，ばかばかしい"],
   pronunciation:"/əbˈsɜːrd/",part:183,
   example:"The idea that cats can speak English is absurd.",
   exampleJa:"猫が英語を話せるという考えは、理屈に合わない。",
   example2:"Wearing a thick winter coat in August looks absurd.",
   exampleJa2:"8月に厚い冬のコートを着るのは、ばかばかしく見える。",
   etymologyProcess:"ab（離れて）＋ surd（耳が聞こえない）→ 音程から外れて聞こえると…？",
   etymologyConclusion:"ab（離れて）＋ surd（耳が聞こえない）→ 調子外れで筋道から外れている＝理屈に合わない",
   why:"【なぜ】ラテン語 absurdus は「調子外れの，耳ざわりな」。surdus（耳が聞こえない）から来ていて、聞こえずに音程を外した歌のような状態です。音楽の「調子外れ」が、話や考えの「筋が通らない」に広がりました。\n【つながり】absurdity（不合理）も同じ語。ridiculous は「笑われるほど」ばかげていることに重点があります。",
   relatedWords:[
     {word:"absurdity",meaning:"不合理，ばかばかしさ",breakdown:"ab（離れて）＋ surd（耳が聞こえない）＋ ity（名詞）→ 調子外れなこと"},
     {synonym:true,word:"ridiculous",meaning:"ばかげた",breakdown:"笑われるほどばかげている。absurd は理屈が通らない"},
     {synonym:true,word:"silly",meaning:"ばかな，愚かな",breakdown:"子どもっぽくばかげている。absurd は筋が通らない"},
     {synonym:true,word:"strange",meaning:"奇妙な",breakdown:"ふつうでない。absurd はありえないほど筋が通らない"}]},

  {id:1827,word:"fragile",partOfSpeech:"形容詞",meaning:"壊れやすい，割れやすい",
   meanings:["形|壊れやすい，割れやすい","形|（体・関係が）弱い，不安定な"],
   pronunciation:"/ˈfrædʒl/",part:183,
   example:"Be careful with that box, because the glasses inside are fragile.",
   exampleJa:"その箱に気をつけて。中のグラスは壊れやすいから。",
   example2:"After his long illness, his health remained fragile for months.",
   exampleJa2:"長い病気のあと、彼の健康は何か月も不安定なままだった。",
   etymologyProcess:"frag（砕く）＋ ile（できる）→ すぐに砕くことができると…？",
   etymologyConclusion:"frag（砕く）＋ ile（できる）→ ちょっとした力で砕けてしまう＝壊れやすい",
   etymologyMore:["物だけでなく体や関係もすぐ崩れる→（体・関係が）弱い，不安定な"],
   relatedWords:[
     {word:"fragment",meaning:"破片，かけら",breakdown:"frag（砕く）＋ ment（名詞）→ 砕けて残ったかけら"},
     {word:"fraction",meaning:"一部分；分数",breakdown:"frag（砕く）＋ ion（名詞）→ 全体を砕いた一部"},
     {word:"frail",meaning:"か弱い",breakdown:"frag（砕く）→ 砕けそうなほど体が弱い"},
     {synonym:true,word:"weak",meaning:"弱い",breakdown:"力がない。fragile は少しの力で壊れる"}]},

  {id:1828,word:"vulnerable",partOfSpeech:"形容詞",meaning:"（攻撃・病気などに）傷つきやすい，やられやすい",
   meanings:["形|（攻撃・病気などに）傷つきやすい，やられやすい","形|（心が）無防備な，弱い立場の"],
   pronunciation:"/ˈvʌlnərəbl/",part:183,
   example:"Young children are vulnerable to heatstroke during the summer.",
   exampleJa:"幼い子どもは、夏のあいだ熱中症にやられやすい。",
   example2:"I felt vulnerable when I spoke about my dream in class.",
   exampleJa2:"クラスで自分の夢について話したとき、私は無防備な気持ちになった。",
   usage:["be vulnerable to 物（物に弱い，やられやすい）"],
   etymologyProcess:"vulner（傷つける）＋ able（できる）→ たやすく傷をつけられると…？",
   etymologyConclusion:"vulner（傷つける）＋ able（できる）→ 守りが弱く、すぐに傷をつけられてしまう＝（攻撃・病気などに）傷つきやすい",
   etymologyMore:["心を守るよろいを外している→（心が）無防備な，弱い立場の"],
   relatedWords:[
     {word:"vulnerability",meaning:"弱さ，もろさ",breakdown:"vulner（傷つける）＋ abil（できる）＋ ity（名詞）→ 傷つきやすさ"},
     {word:"invulnerable",meaning:"不死身の",breakdown:"in（否定）＋ vulner（傷つける）＋ able（できる）→ 傷つけられない"},
     {synonym:true,word:"weak",meaning:"弱い",breakdown:"力がない。vulnerable は外からの攻撃に弱い"},
     {synonym:true,word:"sensitive",meaning:"敏感な",breakdown:"刺激に反応しやすい。vulnerable は傷を受けやすい"}]},

  {id:1829,word:"static",partOfSpeech:"形容詞",meaning:"動きのない，静的な",
   meanings:["形|動きのない，静的な","名|静電気"],
   pronunciation:"/ˈstætɪk/",part:183,
   example:"The number of students in our town has stayed static for years.",
   exampleJa:"私たちの町の生徒数は、何年も動きのないままだ。",
   example2:"My hair stood up because of the static on my sweater.",
   exampleJa2:"セーターの静電気で、髪の毛が逆立った。",
   etymologyProcess:"sta（立つ）＋ ic（形容詞）→ その場に立ち止まったままだと…？",
   etymologyConclusion:"sta（立つ）＋ ic（形容詞）→ 一か所に立ったまま、少しも動かない＝動きのない",
   etymologyMore:["流れずにとどまっている電気→静電気"],
   relatedWords:[
     {word:"station",meaning:"駅",breakdown:"sta（立つ）＋ ion（名詞）→ 列車が止まって立つ場所"},
     {word:"stable",meaning:"安定した",breakdown:"sta（立つ）＋ able（できる）→ しっかり立っていられる"},
     {word:"status",meaning:"地位，状態",breakdown:"sta（立つ）→ 社会の中で立っている位置"},
     {synonym:true,word:"still",meaning:"静止した",breakdown:"じっとしている。static は変化しない状態が続く"}]},

  {id:1830,word:"innate",partOfSpeech:"形容詞",meaning:"生まれつきの，先天的な",
   meanings:["形|生まれつきの，先天的な"],
   pronunciation:"/ɪˈneɪt/",part:183,
   example:"She has an innate talent for both music and art.",
   exampleJa:"彼女には、音楽と美術の両方に生まれつきの才能がある。",
   example2:"Some scientists believe that language ability is innate in humans.",
   exampleJa2:"言語能力は人間に生まれつき備わっていると考える科学者もいる。",
   etymologyProcess:"in（中へ）＋ nat（生まれる）→ 生まれたときから中にあると…？",
   etymologyConclusion:"in（中へ）＋ nat（生まれる）→ 生まれたときから体の中に備わっている＝生まれつきの",
   relatedWords:[
     {word:"native",meaning:"生まれた土地の",breakdown:"nat（生まれる）＋ ive（形容詞）→ 生まれたところの"},
     {word:"nature",meaning:"自然；性質",breakdown:"nat（生まれる）＋ ure（もの）→ 生まれたままの姿"},
     {word:"nation",meaning:"国家，国民",breakdown:"nat（生まれる）＋ ion（名詞）→ 同じ土地に生まれた人々"},
     {synonym:true,word:"inborn",meaning:"生まれつきの",breakdown:"in（中に）＋ born（生まれた）の英語本来の語。innate とほぼ同じ"}]},

  {id:1831,word:"exotic",partOfSpeech:"形容詞",meaning:"（動植物が）外国産の，異国風の",
   meanings:["形|（動植物が）外国産の，異国風の","形|（雰囲気が）異国情緒のある，めずらしい"],
   pronunciation:"/ɪɡˈzɑːtɪk/",part:184,
   example:"The zoo keeps many exotic birds from the rain forests of South America.",
   exampleJa:"その動物園は、南米の熱帯雨林から来た外国産の鳥をたくさん飼っている。",
   example2:"The restaurant has an exotic atmosphere with colorful Moroccan lamps.",
   exampleJa2:"そのレストランは、色とりどりのモロッコのランプで異国情緒のある雰囲気だ。",
   etymologyProcess:"exo（外の）＋ ic（形容詞）→ 国の外からやって来たものは…？",
   etymologyConclusion:"exo（外の）＋ ic（形容詞）→ 自分の国の外からやって来た＝（動植物が）外国産の",
   relatedWords:[
     {word:"external",meaning:"外部の",breakdown:"ex（外へ）＋ al（形容詞）→ 外側にある"},
     {synonym:true,word:"foreign",meaning:"外国の",breakdown:"よその国の。exotic はめずらしさや魅力を感じさせる"},
     {synonym:true,word:"unusual",meaning:"めずらしい",breakdown:"ふつうでない。exotic は遠い国から来たようにめずらしい"},
     {synonym:true,word:"tropical",meaning:"熱帯の",breakdown:"暑い地域の。exotic な動植物は熱帯産のことが多い"}]},

  {id:1832,word:"tame",partOfSpeech:"形容詞",meaning:"（動物が）飼いならされた，人に慣れた",
   meanings:["形|（動物が）飼いならされた，人に慣れた","形|（話・試合などが）退屈な，刺激のない","他|飼いならす"],
   pronunciation:"/teɪm/",part:184,
   example:"The deer in this park are so tame that they eat from your hand.",
   exampleJa:"この公園の鹿はとても人に慣れていて、手から餌を食べる。",
   example2:"It took the farmer years to tame the wild horse.",
   exampleJa2:"その農夫がその野生の馬を飼いならすのに何年もかかった。",
   etymologyProcess:"tame（飼いならす）→ 野生の動物を家で育てると…？",
   etymologyConclusion:"tame（飼いならす）→ 野生の荒々しさが抜けて、人のそばで暮らせる＝（動物が）飼いならされた",
   etymologyMore:["荒々しさが抜けすぎて物足りない→（話・試合などが）退屈な，刺激のない"],
   hook:"wild（野生の）の反対と覚える。猛獣使いは tamer（飼いならす人）。",
   relatedWords:[
     {word:"tamer",meaning:"（猛獣を）ならす人",breakdown:"tame（飼いならす）＋ er（人）→ 動物を手なずける人"},
     {synonym:true,word:"gentle",meaning:"おとなしい，優しい",breakdown:"性格が穏やか。tame は人に慣らされておとなしい"},
     {synonym:true,word:"domestic",meaning:"（動物が）人に飼われた",breakdown:"dom（家）の仲間。家で飼う動物。tame は一頭一頭が慣れていること"},
     {synonym:true,word:"obedient",meaning:"従順な",breakdown:"言うことをよく聞く。tame は野生らしさが抜けた"}]},

  {id:1833,word:"manifest",partOfSpeech:"形容詞",meaning:"一目瞭然の，はっきり表れた",
   meanings:["形|一目瞭然の，はっきり表れた","他|（感情・性質を）はっきり示す，表す"],
   pronunciation:"/ˈmænɪfest/",part:184,
   example:"His nervousness was manifest in his shaking hands.",
   exampleJa:"彼の緊張は、震える手に一目瞭然だった。",
   example2:"Her talent for singing manifested itself at an early age.",
   exampleJa2:"彼女の歌の才能は、幼いころからはっきり表れていた。",
   etymologyProcess:"manu（手）→ 手でつかめるほどはっきりしていると…？",
   etymologyConclusion:"manu（手）→ 手でつかめるほど、はっきりそこにある＝一目瞭然の",
   why:"【なぜ】ラテン語 manifestus は、manus（手）に「つかまれた」「打たれた」を表す部分がついた語とされますが、後半ははっきりしません。もとは「現行犯で手につかまれた」、つまり言い逃れできないほど明らかな状態でした。そこから「誰の目にも明らかな」になりました。\n【つながり】manual（手動の）や manufacture（製造する）も manu（手）の仲間です。",
   spelling:"manu→mani（ラテン語 manifestus の形）",
   etymologyMore:["はっきり外へ見えるようにする→（感情・性質を）はっきり示す，表す"],
   relatedWords:[
     {word:"manual",meaning:"手動の；説明書",breakdown:"manu（手）＋ al（形容詞）→ 手で動かす"},
     {word:"manufacture",meaning:"製造する",breakdown:"manu（手）＋ fact（作る）→ もとは手で作ること"},
     {word:"manage",meaning:"なんとかやりとげる",breakdown:"man（手）＋ age（すること）→ 手綱を手で操る"},
     {synonym:true,word:"obvious",meaning:"明白な",breakdown:"誰が見ても明らか。manifest は外にはっきり表れている"}]},

  {id:1834,word:"dense",partOfSpeech:"形容詞",meaning:"密集した，（霧などが）濃い",
   meanings:["形|密集した，（霧などが）濃い","形|（文章が）内容の詰まった，難解な"],
   pronunciation:"/dens/",part:184,
   example:"The bus passed slowly through a dense forest in the mountains.",
   exampleJa:"バスは、山の中の木が密集した森をゆっくり通り抜けた。",
   example2:"The dense fog made it impossible to see the road ahead.",
   exampleJa2:"濃い霧で、前の道がまったく見えなくなった。",
   etymologyProcess:"dens（ぎっしり詰まった）→ すき間なく詰まっていると…？",
   etymologyConclusion:"dens（ぎっしり詰まった）→ すき間もないほどぎっしり詰まっている＝密集した",
   etymologyMore:["一文に中身がぎっしり詰まる→（文章が）内容の詰まった，難解な"],
   relatedWords:[
     {word:"density",meaning:"密度",breakdown:"dens（ぎっしり詰まった）＋ ity（名詞）→ どれだけ詰まっているか"},
     {word:"condense",meaning:"凝縮する",breakdown:"con（共に）＋ dens（ぎっしり詰まった）→ ぎゅっと詰めて固める"},
     {synonym:true,word:"thick",meaning:"厚い；濃い",breakdown:"厚みがある。dense は中身がすき間なく詰まる"},
     {synonym:true,word:"crowded",meaning:"混雑した",breakdown:"人でいっぱい。dense は人にも物にも使う"}]},

  {id:1835,word:"transparent",partOfSpeech:"形容詞",meaning:"透明な，すき通った",
   meanings:["形|透明な，すき通った","形|（組織・説明が）隠しごとのない，わかりやすい"],
   pronunciation:"/trænsˈpærənt/",part:184,
   example:"The bottle is made of transparent plastic, so you can see inside.",
   exampleJa:"そのびんは透明なプラスチックでできているので、中が見える。",
   example2:"The student council should be more transparent about its budget.",
   exampleJa2:"生徒会は予算について、もっと隠しごとのないようにすべきだ。",
   etymologyProcess:"trans（越えて）＋ pear（見えてくる）→ 向こう側まで見えると…？",
   etymologyConclusion:"trans（越えて）＋ pear（見えてくる）＋ ent（～している）→ 向こう側が透けて見える＝透明な",
   spelling:"pear→par（ラテン語 parere の形のまま）",
   etymologyMore:["中身が外から全部見える→（組織・説明が）隠しごとのない，わかりやすい"],
   relatedWords:[
     {word:"appear",meaning:"現れる",breakdown:"ad（～へ）＋ pear（見えてくる）→ こちらへ姿が見えてくる"},
     {word:"disappear",meaning:"消える",breakdown:"dis（否定）＋ ad（～へ）＋ pear（見えてくる）→ 見えなくなる"},
     {word:"transfer",meaning:"移す；乗り換える",breakdown:"trans（越えて）＋ fer（運ぶ）→ 向こう側へ運ぶ"},
     {synonym:true,word:"clear",meaning:"澄んだ，透明な",breakdown:"曇りがない。transparent は向こうが透けて見える"}]},

  {id:1836,word:"consistent",partOfSpeech:"形容詞",meaning:"（言動・質が）一貫した，ぶれない",
   meanings:["形|（言動・質が）一貫した，ぶれない","形|（with ～と）矛盾しない，一致する"],
   pronunciation:"/kənˈsɪstənt/",part:184,
   example:"He was a consistent player who scored in almost every game.",
   exampleJa:"彼はほとんど毎試合得点する、ぶれない一貫した選手だった。",
   example2:"Her story was consistent with what the witness said.",
   exampleJa2:"彼女の話は、目撃者の証言と矛盾しなかった。",
   usage:["be consistent with 事（事と矛盾しない）"],
   etymologyProcess:"con（共に）＋ sist（立つ）→ 全部がそろってしっかり立つと…？",
   etymologyConclusion:"con（共に）＋ sist（立つ）＋ ent（～している）→ 最初から最後までそろって立ち続ける＝（言動・質が）一貫した",
   etymologyMore:["二つの話がそろって立つ→（with ～と）矛盾しない，一致する"],
   relatedWords:[
     {word:"insist",meaning:"言い張る",breakdown:"in（上に）＋ sist（立つ）→ 自分の意見の上に立って動かない"},
     {word:"exist",meaning:"存在する",breakdown:"ex（外へ）＋ sist（立つ）→ 外に姿を現して立つ"},
     {word:"resist",meaning:"抵抗する",breakdown:"re（後ろへ）＋ sist（立つ）→ 押されても踏みとどまる"},
     {synonym:true,word:"steady",meaning:"安定した",breakdown:"ぐらつかない。consistent はいつも同じ調子を保つ"}]},

  {id:1837,word:"coherent",partOfSpeech:"形容詞",meaning:"（話・考えが）首尾一貫した，まとまりのある",
   meanings:["形|（話・考えが）首尾一貫した，まとまりのある"],
   pronunciation:"/koʊˈhɪrənt/",part:184,
   example:"She gave a clear and coherent explanation of the plan.",
   exampleJa:"彼女は計画について、わかりやすく首尾一貫した説明をした。",
   example2:"He was too tired to give a coherent answer to the question.",
   exampleJa2:"彼は疲れすぎて、その質問にまとまりのある答えができなかった。",
   etymologyProcess:"co（共に）＋ her（くっつく）→ 話の部分どうしがくっつき合うと…？",
   etymologyConclusion:"co（共に）＋ her（くっつく）＋ ent（～している）→ 話の部分どうしがしっかりくっついている＝（話・考えが）首尾一貫した",
   relatedWords:[
     {word:"adhere",meaning:"くっつく；固く守る",breakdown:"ad（～へ）＋ her（くっつく）→ 相手にぴたりとくっつく"},
     {word:"hesitate",meaning:"ためらう",breakdown:"hes（くっつく）＋ ate（動詞）→ その場にくっついて動けない"},
     {word:"cohesion",meaning:"結束，まとまり",breakdown:"co（共に）＋ hes（くっつく）＋ ion（名詞）→ くっつき合う力"},
     {synonym:true,word:"logical",meaning:"論理的な",breakdown:"理屈が通る。coherent は全体がまとまっている"}]},

  {id:1838,word:"universal",partOfSpeech:"形容詞",meaning:"普遍的な，誰にでも当てはまる",
   meanings:["形|普遍的な，誰にでも当てはまる","形|全員の，全体の"],
   pronunciation:"/ˌjuːnɪˈvɜːrsl/",part:184,
   example:"Music is a universal language that everyone can understand.",
   exampleJa:"音楽は、誰もが理解できる普遍的な言語だ。",
   example2:"The new rule received universal support from the students.",
   exampleJa2:"新しい規則は、生徒全員の支持を得た。",
   etymologyProcess:"uni（1つ）＋ vers（回る）→ 全部が1つにまとまって回ると…？",
   etymologyConclusion:"uni（1つ）＋ vers（回る）＋ al（形容詞）→ 世界全体が1つにまとまっている＝普遍的な",
   etymologyMore:["1つにまとめて誰も漏らさない→全員の，全体の"],
   relatedWords:[
     {word:"universe",meaning:"宇宙",breakdown:"uni（1つ）＋ vers（回る）→ 1つにまとまって回るすべて"},
     {word:"university",meaning:"大学",breakdown:"uni（1つ）＋ vers（回る）＋ ity（名詞）→ 教える者と学ぶ者の1つの集まり"},
     {word:"uniform",meaning:"制服",breakdown:"uni（1つ）＋ form（形）→ みんなが1つの形の服"},
     {synonym:true,word:"general",meaning:"一般的な",breakdown:"だいたい当てはまる。universal は例外なく当てはまる"}]},

  {id:1839,word:"underlying",partOfSpeech:"形容詞",meaning:"根底にある，隠れた",
   meanings:["形|根底にある，隠れた"],
   pronunciation:"/ˌʌndərˈlaɪɪŋ/",part:184,
   example:"We need to find the underlying cause of the problem.",
   exampleJa:"私たちは、その問題の根底にある原因を見つける必要がある。",
   example2:"The underlying message of the movie is the value of friendship.",
   exampleJa2:"その映画の根底にあるメッセージは、友情の大切さだ。",
   etymologyProcess:"under（下に）＋ lie（横たわる）→ 表面の下に横たわっていると…？",
   etymologyConclusion:"under（下に）＋ lie（横たわる）＋ ing（～している）→ 目に見える表面の下に横たわっている＝根底にある",
   relatedWords:[
     {word:"underground",meaning:"地下の",breakdown:"under（下に）＋ ground（底・地面）→ 地面の下の"},
     {word:"underline",meaning:"下線を引く",breakdown:"under（下に）＋ line（線）→ 文字の下に線を引く"},
     {word:"lie",meaning:"横たわる",breakdown:"lie（横たわる）→ 体を横にして休む"},
     {synonym:true,word:"basic",meaning:"基本的な",breakdown:"土台となる。underlying は表から見えない奥にある"}]},

  {id:1840,word:"spontaneous",partOfSpeech:"形容詞",meaning:"（計画なしに）自然にわき起こる，自発的な",
   meanings:["形|（計画なしに）自然にわき起こる，自発的な","形|（人が）その場の思いつきで動く"],
   pronunciation:"/spɑːnˈteɪniəs/",part:184,
   example:"The audience broke into spontaneous applause after her speech.",
   exampleJa:"彼女のスピーチのあと、聴衆から自然にわき起こる拍手が起きた。",
   example2:"Let's be spontaneous and go to the beach today!",
   exampleJa2:"今日は思いつきで海に行こうよ！",
   etymologyProcess:"spont（自分の意志で）＋ ous（形容詞）→ 誰にも言われずに起こると…？",
   etymologyConclusion:"spont（自分の意志で）＋ ous（形容詞）→ 誰に言われるでもなく、ひとりでに起こる＝（計画なしに）自然にわき起こる",
   etymologyMore:["その場で自分から動き出す→（人が）その場の思いつきで動く"],
   relatedWords:[
     {word:"spontaneously",meaning:"自然に，自発的に",breakdown:"spont（自分の意志で）＋ ous（形容詞）＋ ly（副詞）→ ひとりでに"},
     {synonym:true,word:"natural",meaning:"自然な",breakdown:"わざとらしくない。spontaneous は準備なくその場で起こる"},
     {synonym:true,word:"voluntary",meaning:"自発的な",breakdown:"自分の意志で進んでする。spontaneous は思わず起こる"},
     {synonym:true,word:"sudden",meaning:"突然の",breakdown:"急に起こる。spontaneous は計画なしに自然と起こる"}]},

  {id:1841,word:"mock",partOfSpeech:"形容詞",meaning:"模擬の，練習用の",
   meanings:["形|模擬の，練習用の","他|あざける，ばかにする"],
   pronunciation:"/mɑːk/",part:185,
   example:"We will take a mock exam in English next Monday.",
   exampleJa:"私たちは来週の月曜日に、英語の模擬試験を受ける。",
   example2:"It's not kind to mock people who make mistakes.",
   exampleJa2:"失敗した人をあざけるのは、優しいことではない。",
   etymologyProcess:"mock（まねてからかう）→ 本物をまねて作ったものは…？",
   etymologyConclusion:"mock（まねてからかう）→ 本物そっくりにまねて作った、練習のためのもの＝模擬の",
   hook:"語源ははっきりしない。人のまねをしてからかう→「あざける」とセットで覚える。",
   relatedWords:[
     {word:"mockery",meaning:"あざけり",breakdown:"mock（まねてからかう）→ まねをしてからかうこと"},
     {synonym:true,word:"practice",meaning:"練習（の）",breakdown:"くり返し慣れること。mock は本番をまねた練習"},
     {synonym:true,word:"fake",meaning:"にせの",breakdown:"だますためのにせもの。mock はまねたことが明らか"},
     {synonym:true,word:"tease",meaning:"からかう",breakdown:"軽くからかう。mock はばかにしてあざける"}]},

  {id:1842,word:"collective",partOfSpeech:"形容詞",meaning:"集団の，共同の",
   meanings:["形|集団の，共同の","名|共同体，共同組織"],
   pronunciation:"/kəˈlektɪv/",part:185,
   example:"Keeping the classroom clean is the collective responsibility of all students.",
   exampleJa:"教室をきれいに保つのは、生徒全員の共同の責任だ。",
   example2:"Our collective effort helped the team win the championship.",
   exampleJa2:"私たちの共同の努力のおかげで、チームは優勝できた。",
   etymologyProcess:"col（共に）＋ lect（拾う）→ みんなを一か所に拾い集めると…？",
   etymologyConclusion:"col（共に）＋ lect（拾う）＋ ive（形容詞）→ みんなを一つに拾い集めた＝集団の",
   relatedWords:[
     {word:"collect",meaning:"集める",breakdown:"col（共に）＋ lect（拾う）→ 拾って一か所にまとめる"},
     {word:"collection",meaning:"収集品，コレクション",breakdown:"col（共に）＋ lect（拾う）＋ ion（名詞）→ 集めたもの"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離れて）＋ lect（拾う）→ 分けて拾い上げる"},
     {synonym:true,word:"joint",meaning:"共同の",breakdown:"二人以上で一緒に。collective は集団全体で"}]},

  {id:1843,word:"vertical",partOfSpeech:"形容詞",meaning:"垂直の，縦の",
   meanings:["形|垂直の，縦の"],
   pronunciation:"/ˈvɜːrtɪkl/",part:185,
   example:"Draw a vertical line down the middle of the page.",
   exampleJa:"ページの真ん中に、上から下へ垂直の線を引きなさい。",
   example2:"Climbing that vertical cliff without a rope is very dangerous.",
   exampleJa2:"ロープなしであの垂直な崖を登るのは、とても危険だ。",
   etymologyProcess:"vert（回る）＋ ical（形容詞）→ 回るものの頂点から真下へ向かうと…？",
   etymologyConclusion:"vert（回る）＋ ical（形容詞）→ てっぺんから真下へ、まっすぐ立つ＝垂直の",
   why:"【なぜ】ラテン語 vertex は「渦，回転の中心」。そこから「頭のつむじ」、さらに「いちばん高いところ，頂点」を指すようになりました。頂点から真下へ下ろした線が vertical（垂直の）です。「回る」から直接ではなく、「頂点」をはさんで意味がつながっています。\n【つながり】数学の vertex（頂点）も同じ語。反対は horizontal（水平の）。",
   relatedWords:[
     {word:"vertex",meaning:"頂点",breakdown:"vert（回る）→ 回転の中心から、いちばん高い点"},
     {word:"advertise",meaning:"宣伝する",breakdown:"ad（～へ）＋ vert（回る）→ 人の目をこちらへ向けさせる"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ くるりと回して後ろ向きにする"},
     {synonym:true,word:"upright",meaning:"まっすぐ立った",breakdown:"倒れずに立っている。vertical は線や面が垂直"}]},

  {id:1844,word:"ongoing",partOfSpeech:"形容詞",meaning:"進行中の，継続中の",
   meanings:["形|進行中の，継続中の"],
   pronunciation:"/ˈɑːnɡoʊɪŋ/",part:185,
   example:"The investigation into the accident is still ongoing.",
   exampleJa:"その事故の調査は、まだ進行中だ。",
   example2:"There is an ongoing debate about school uniforms in our class.",
   exampleJa2:"私たちのクラスでは、制服について継続中の議論がある。",
   etymologyProcess:"go（行く）＋ ing（～している）→ 先へ先へと進み続けていると…？",
   etymologyConclusion:"go（行く）＋ ing（～している）→ 止まらずに先へと進み続けている＝進行中の",
   relatedWords:[
     {word:"undergo",meaning:"経験する，受ける",breakdown:"under（下に）＋ go（行く）→ 困難の下をくぐって進む"},
     {word:"going",meaning:"進行，行くこと",breakdown:"go（行く）＋ ing（～している）→ 進んでいること"},
     {synonym:true,word:"continuing",meaning:"続いている",breakdown:"途切れずに続く。ongoing は今まさに進んでいる"},
     {synonym:true,word:"current",meaning:"現在の",breakdown:"今の。ongoing は前から続いていて今も終わっていない"}]},

  {id:1845,word:"tender",partOfSpeech:"形容詞",meaning:"（肉などが）柔らかい；優しい",
   meanings:["形|（肉などが）柔らかい","形|優しい，思いやりのある","形|（体の部分が）触ると痛い"],
   pronunciation:"/ˈtendər/",part:185,
   example:"The beef was so tender that it melted in my mouth.",
   exampleJa:"その牛肉はとても柔らかくて、口の中でとろけた。",
   example2:"She gave the crying child a warm and tender smile.",
   exampleJa2:"彼女は泣いている子に、温かく優しい笑顔を向けた。",
   etymologyProcess:"tener（柔らかい）→ 若くてやわらかいものは…？",
   etymologyConclusion:"tener（柔らかい）→ 若い芽のようにやわらかく、傷つきやすい＝（肉などが）柔らかい",
   spelling:"tener→tender（フランス語 tendre を通って d が入った）",
   etymologyMore:["傷つきやすいものをそっと扱う→優しい，思いやりのある","やわらかく傷つきやすい→（体の部分が）触ると痛い"],
   hook:"tend（傾向がある）とは別の語。Love Me Tender の tender は「優しく」。",
   relatedWords:[
     {word:"tenderly",meaning:"優しく",breakdown:"tener（柔らかい）＋ ly（副詞）→ やわらかく、そっと"},
     {synonym:true,word:"soft",meaning:"柔らかい",breakdown:"ふつうの「柔らかい」。tender は肉などが食べやすく柔らかい"},
     {synonym:true,word:"gentle",meaning:"穏やかな，優しい",breakdown:"性格や動きが穏やか。tender は愛情がこもる"},
     {synonym:true,word:"kind",meaning:"親切な",breakdown:"人に親切。tender は相手をいたわる柔らかさ"}]},

  {id:1846,word:"upright",partOfSpeech:"形容詞",meaning:"（姿勢などが）まっすぐ立った；正直な",
   meanings:["形|（姿勢などが）まっすぐ立った","形|（人が）正直な，高潔な","副|まっすぐに，直立して"],
   pronunciation:"/ˈʌpraɪt/",part:185,
   example:"Please return your seat to the upright position before landing.",
   exampleJa:"着陸の前に、座席をまっすぐ立った位置に戻してください。",
   example2:"He was an upright man who never told a single lie.",
   exampleJa2:"彼は一度もうそをつかない、正直な人だった。",
   etymologyProcess:"up（上へ）＋ right（まっすぐ）→ 上へまっすぐ伸びると…？",
   etymologyConclusion:"up（上へ）＋ right（まっすぐ）→ 上に向かってまっすぐ伸びている＝（姿勢などが）まっすぐ立った",
   etymologyMore:["心が曲がらずまっすぐ→（人が）正直な，高潔な"],
   relatedWords:[
     {word:"right",meaning:"正しい；右の",breakdown:"right（まっすぐ）→ 曲がっていない、まっすぐで正しい"},
     {word:"upgrade",meaning:"性能を上げる",breakdown:"up（上へ）＋ grad（歩み・段）→ 一段上へ上げる"},
     {word:"upset",meaning:"ひっくり返す；動揺させる",breakdown:"up（上へ）＋ set（置く）→ 上下をひっくり返す"},
     {synonym:true,word:"honest",meaning:"正直な",breakdown:"うそをつかない。upright は行いまで正しくまっすぐ"}]},

  {id:1847,word:"ease",partOfSpeech:"名詞",meaning:"たやすさ，容易さ",
   meanings:["名|たやすさ，容易さ","名|気楽さ，くつろぎ","他|（痛み・不安を）和らげる"],
   pronunciation:"/iːz/",part:185,
   example:"She solved the difficult math problem with ease.",
   exampleJa:"彼女はその難しい数学の問題を、いともたやすく解いた。",
   example2:"This medicine will ease the pain in your knee.",
   exampleJa2:"この薬が、ひざの痛みを和らげるだろう。",
   usage:["with ease（たやすく）","at ease（くつろいで，安心して）"],
   etymologyProcess:"ease（楽）→ 楽にできる、ゆとりのある状態は…？",
   etymologyConclusion:"ease（楽）→ 力を入れなくても楽にできる、ゆとりのある状態＝たやすさ",
   etymologyMore:["心にゆとりがある→気楽さ，くつろぎ","重さを取って楽にする→（痛み・不安を）和らげる"],
   hook:"with ease は easily と同じ。easy（簡単な）の名詞と覚えるとよい。",
   relatedWords:[
     {word:"easy",meaning:"簡単な",breakdown:"ease（楽）＋ y（形容詞）→ 楽にできる"},
     {word:"disease",meaning:"病気",breakdown:"dis（否定）＋ ease（楽）→ 楽でない状態"},
     {word:"uneasy",meaning:"不安な",breakdown:"un（否定）＋ ease（楽）＋ y（形容詞）→ 心が楽でない"},
     {synonym:true,word:"comfort",meaning:"快適さ",breakdown:"心地よさ。ease は力まずにいられる楽さ"}]},

  {id:1848,word:"rust",partOfSpeech:"名詞",meaning:"（金属の）さび",
   meanings:["名|（金属の）さび","自|さびる"],
   pronunciation:"/rʌst/",part:185,
   example:"The old bike was covered with rust after years in the rain.",
   exampleJa:"その古い自転車は、何年も雨にさらされてさびだらけだった。",
   example2:"Iron will rust quickly if you leave it outside.",
   exampleJa2:"鉄は外に置いておくと、すぐにさびる。",
   etymologyProcess:"rust（赤くなる）→ 鉄が赤茶色に変わったものは…？",
   etymologyConclusion:"rust（赤くなる）→ 鉄の表面が赤茶色に変わってぼろぼろになる＝（金属の）さび",
   hook:"red（赤）と同じ古い家族の語。鉄が赤茶色になる様子そのもの。",
   relatedWords:[
     {word:"rusty",meaning:"さびた；（腕が）なまった",breakdown:"rust（赤くなる）＋ y（形容詞）→ さびついた"},
     {synonym:true,word:"red",meaning:"赤い",breakdown:"rust と同じ古英語の家族。さびの赤茶色"},
     {synonym:true,word:"stain",meaning:"しみ",breakdown:"表面についた汚れ。rust は金属そのものが変わる"},
     {synonym:true,word:"decay",meaning:"腐る，朽ちる",breakdown:"だんだん崩れる。rust は金属が朽ちること"}]},

  {id:1849,word:"stain",partOfSpeech:"名詞",meaning:"しみ，汚れ",
   meanings:["名|しみ，汚れ","他|しみをつける，汚す","名|（名声の）汚点"],
   pronunciation:"/steɪn/",part:185,
   example:"There is a coffee stain on my white school shirt.",
   exampleJa:"私の白い制服のシャツに、コーヒーのしみがある。",
   example2:"The spilled red wine stained the new carpet in the living room.",
   exampleJa2:"こぼれた赤ワインが、居間の新しいじゅうたんにしみをつけた。",
   etymologyProcess:"dis（離れて）＋ ting（染める）→ もとの色から離れると…？",
   etymologyConclusion:"dis（離れて）＋ ting（染める）→ もとの色から離れ、ちがう色がついた部分＝しみ",
   why:"【なぜ】stain は distain が縮まった語。古いフランス語 desteindre は「色を抜く，色あせさせる」でした。もとの色が抜けたり変わったりしてできたまだらな部分から、「しみ，汚れ」の意味になりました。\n【つながり】ting（染める）は tint（色合い）と同じ仲間。stainless（ステンレス）は「しみ・さびがつかない」鋼です。",
   spelling:"dis→s（di が消えた）、ting→tain（フランス語を通って変化）",
   etymologyMore:["名前についた消えない汚れ→（名声の）汚点"],
   relatedWords:[
     {word:"tint",meaning:"色合い",breakdown:"ting（染める）→ うっすら染めた色"},
     {word:"stainless",meaning:"さびない，ステンレスの",breakdown:"dis（離れて）＋ ting（染める）＋ less（ない）→ しみがつかない"},
     {synonym:true,word:"spot",meaning:"点，しみ",breakdown:"小さな点。stain は液体がしみこんだ汚れ"},
     {synonym:true,word:"dirt",meaning:"汚れ，泥",breakdown:"ほこりや泥。stain は洗ってもなかなか落ちない"}]},

  {id:1850,word:"rag",partOfSpeech:"名詞",meaning:"ぼろ切れ，布切れ",
   meanings:["名|ぼろ切れ，布切れ","名|（rags で）ぼろ服"],
   pronunciation:"/ræɡ/",part:185,
   example:"He wiped the oil off his hands with an old rag.",
   exampleJa:"彼は古いぼろ切れで、手についた油をふき取った。",
   example2:"In the story, the poor boy was dressed in rags.",
   exampleJa2:"その物語の中で、貧しい少年はぼろ服を着ていた。",
   etymologyProcess:"rag（ぼさぼさの切れ端）→ ほつれた布の切れ端は…？",
   etymologyConclusion:"rag（ぼさぼさの切れ端）→ 端がほつれてぼさぼさになった布＝ぼろ切れ",
   hook:"from rags to riches（ぼろ服から大金持ちへ）は成功物語の決まり文句。",
   relatedWords:[
     {word:"ragged",meaning:"ぼろぼろの",breakdown:"rag（ぼさぼさの切れ端）＋ ed（～された）→ ぼろになった"},
     {synonym:true,word:"cloth",meaning:"布",breakdown:"ふつうの布。rag は古くなった布切れ"},
     {synonym:true,word:"towel",meaning:"タオル",breakdown:"ふくための布。rag は捨てる前の古布"},
     {synonym:true,word:"shabby",meaning:"みすぼらしい",breakdown:"服や建物が傷んでいる。rag はその布切れ"}]},
