  {id:351,word:"pronounce",partOfSpeech:"他動詞",meaning:"発音する",
   meanings:["他|～を発音する","他|～を宣言する"],
   pronunciation:"/prəˈnaʊns/",part:36,
   example:"Our teacher asked me to pronounce the new word slowly.",
   exampleJa:"先生は私に、その新しい単語をゆっくり発音するように言った。",
   example2:"This name is spelled the same but pronounced differently here.",
   exampleJa2:"この名前はつづりは同じだが、ここでは違うように発音される。",
   etymologyProcess:"pro（前へ）＋ nounce（告げる）→ 人前で言葉をはっきり告げると…？",
   etymologyConclusion:"pro（前へ）＋ nounce（告げる）→ 人前で言葉をはっきり告げる口の動き＝発音する",
   relatedWords:[
     {word:"announce",meaning:"発表する",breakdown:"ad（〜へ）＋ nounce（告げる）→ 人々に向けて広く告げ知らせる"},
     {word:"announcement",meaning:"発表",breakdown:"ad（〜へ）＋ nounce（告げる）＋ ment（名詞）→ 告げ知らせる中身"},
     {word:"pronunciation",meaning:"発音",breakdown:"pro（前へ）＋ nounce（告げる）→ 口に出して告げたときの音の形"},
     {synonym:true,word:"spell",meaning:"つづる",breakdown:"文字の並びを示す。pronounce は音のほうを示す"}]},

  {id:352,word:"sign",partOfSpeech:"名詞",meaning:"兆候，しるし",
   meanings:["名|兆候，しるし","名|標識，看板","他|～に署名する"],
   pronunciation:"/saɪn/",part:36,
   example:"Dark clouds are often a sign of heavy rain coming.",
   exampleJa:"黒い雲は、強い雨が来る兆候であることが多い。",
   example2:"She showed no sign of nervousness before the piano contest.",
   exampleJa2:"彼女はピアノのコンクールの前、緊張のしるしを見せなかった。",
   etymologyProcess:"sign（しるし）→ 何かを知らせるために置かれた目印は…？",
   etymologyConclusion:"sign（しるし）→ 何かを知らせるために置かれた目印＝兆候，しるし",
   relatedWords:[
     {word:"signal",meaning:"合図",breakdown:"sign（しるし）＋ al（名詞）→ 相手に向けて送るしるし"},
     {word:"signature",meaning:"署名",breakdown:"sign（しるし）＋ ature（名詞）→ 自分のしるしとして書く名前"},
     {word:"design",meaning:"設計する",breakdown:"de（下へ）＋ sign（しるし）→ 作る前に形をしるしで書き記す"},
     {word:"significant",meaning:"重要な",breakdown:"sign（しるし）＋ fic（作る）→ はっきりしるしを作るほど目立つ"}]},

  {id:353,word:"mean",partOfSpeech:"他動詞",meaning:"意味する",
   meanings:["他|～を意味する","他|～するつもりである"],
   pronunciation:"/miːn/",part:36,
   example:"This red light means you must stop your bike here.",
   exampleJa:"この赤い光は、ここで自転車を止めなければならないことを意味する。",
   example2:"What did the teacher mean by that strange question?",
   exampleJa2:"先生はあの奇妙な質問で何を意味していたのですか。",
   etymologyProcess:"mean（心に思う）→ 心に思っていることを言葉にのせると…？",
   etymologyConclusion:"mean（心に思う）→ 心に思っていることを言葉にのせて伝える＝意味する",
   relatedWords:[
     {word:"meaning",meaning:"意味",breakdown:"mean（心に思う）＋ ing（名詞）→ 言葉にこめられた中身"},
     {word:"meaningful",meaning:"意味のある",breakdown:"mean（心に思う）＋ ful（満ちた）→ 中身がしっかり詰まっている"},
     {word:"meaningless",meaning:"無意味な",breakdown:"mean（心に思う）＋ less（ない）→ こめられた中身が空っぽだ"},
     {synonym:true,word:"imply",meaning:"暗に示す",breakdown:"言わずにほのめかす。mean は語そのものの中身"}]},

  {id:354,word:"publish",partOfSpeech:"他動詞",meaning:"出版する",
   meanings:["他|～を出版する","他|（記事など）を掲載する"],
   pronunciation:"/ˈpʌblɪʃ/",part:36,
   example:"That company will publish her first novel next spring.",
   exampleJa:"あの会社は来年の春、彼女の最初の小説を出版する。",
   example2:"Many books are published in this country every single year.",
   exampleJa2:"この国では毎年、非常に多くの本が出版されている。",
   etymologyProcess:"publ（人々）＋ ish（〜にする）→ 書いたものを人々のものにすると…？",
   etymologyConclusion:"publ（人々）＋ ish（〜にする）→ 書いたものを人々のもとへ送り出す＝出版する",
   relatedWords:[
     {word:"public",meaning:"公の",breakdown:"publ（人々）＋ ic（〜の）→ 人々みんなにかかわる"},
     {word:"publication",meaning:"出版物",breakdown:"publ（人々）＋ ation（名詞）→ 人々の前に出されたもの"},
     {word:"publicity",meaning:"知名度",breakdown:"publ（人々）＋ ity（名詞）→ 人々に知られている度合い"},
     {synonym:true,word:"print",meaning:"印刷する",breakdown:"紙に刷ること。publish は世に送り出すこと全体"}]},

  {id:355,word:"display",partOfSpeech:"他動詞",meaning:"展示する",
   meanings:["他|～を展示する，陳列する","他|（感情など）を表に出す","名|展示"],
   pronunciation:"/dɪˈspleɪ/",part:36,
   example:"The museum will display the old maps until next month.",
   exampleJa:"その博物館は来月まで、古い地図を展示する。",
   example2:"Our class displayed its artwork in the school hallway.",
   exampleJa2:"私たちのクラスは、学校の廊下に作品を展示した。",
   etymologyProcess:"dis（バラバラに）＋ pli（折る）→ たたんだものを開いて見せると…？",
   etymologyConclusion:"dis（バラバラに）＋ pli（折る）→ たたんだ布を広げて人の目にさらす＝展示する",
   relatedWords:[
     {word:"reply",meaning:"返事をする",breakdown:"re（戻す）＋ pli（折る）→ 相手の言葉を折り返して返す"},
     {word:"apply",meaning:"申し込む",breakdown:"ad（〜へ）＋ pli（折る）→ 願いを折りたたんで差し出す"},
     {word:"simple",meaning:"単純な",breakdown:"sim（1つ）＋ pli（折る）→ 一重に折っただけで入り組まない"},
     {synonym:true,word:"exhibit",meaning:"展示する",breakdown:"外へ持ち出して見せる。display は並べて見せること"}]},

  {id:356,word:"trust",partOfSpeech:"他動詞",meaning:"信頼する",
   meanings:["他|～を信頼する","名|信頼"],
   pronunciation:"/trʌst/",part:36,
   example:"I trust my old friends more than anyone else.",
   exampleJa:"私は昔からの友人を、ほかの誰よりも信頼している。",
   example2:"The coach was trusted by every member of the team.",
   exampleJa2:"その監督は、チームのすべての部員に信頼されていた。",
   etymologyProcess:"trust（しっかり固い）→ 木のように動かないものに身を預けると…？",
   etymologyConclusion:"trust（しっかり固い）→ 木のように動かないものに身を預ける＝信頼する",
   relatedWords:[
     {word:"distrust",meaning:"不信",breakdown:"dis（否定）＋ trust（しっかり固い）→ 固さを認められない"},
     {word:"entrust",meaning:"委ねる",breakdown:"en（中に）＋ trust（しっかり固い）→ 信頼の中に置いて任せる"},
     {synonym:true,word:"rely",meaning:"頼る",breakdown:"実際に頼りにする。trust は相手を信じる気持ちのほう"},
     {synonym:true,word:"believe",meaning:"信じる",breakdown:"話の中身を正しいと思う。trust は人そのものに頼る"}]},

  {id:357,word:"depend",partOfSpeech:"自動詞",meaning:"次第である",
   meanings:["自|（on ～）（～）次第である","自|（on ～）（～に）頼る"],
   pronunciation:"/dɪˈpend/",part:36,
   example:"Whether we play outside depends on tomorrow's weather.",
   exampleJa:"外で遊ぶかどうかは、明日の天気次第である。",
   example2:"Our success depended largely on the support of local people.",
   exampleJa2:"私たちの成功は、大部分は地元の人々の支え次第だった。",
   etymologyProcess:"de（下へ）＋ pend（重さを量る）→ はかりの皿のように下でゆれると…？",
   etymologyConclusion:"de（下へ）＋ pend（重さを量る）→ はかりの皿のように下にぶら下がる＝次第である",
   relatedWords:[
     {word:"independent",meaning:"独立した",breakdown:"in（否定）＋ de（下へ）＋ pend（重さを量る）→ 何にもぶら下がらない"},
     {word:"pendant",meaning:"ペンダント",breakdown:"pend（重さを量る）＋ ant（もの）→ はかりの皿のように下げる飾り"},
     {word:"expensive",meaning:"高価な",breakdown:"ex（外へ）＋ pens（重さを量る）→ 量って外へ払う額が大きい"},
     {synonym:true,word:"rely",meaning:"頼る",breakdown:"信じて任せる。depend は結果がそれで決まること"}]},

  {id:358,word:"rely",partOfSpeech:"自動詞",meaning:"頼る",
   meanings:["自|（on ～）（～に）頼る"],
   pronunciation:"/rɪˈlaɪ/",part:36,
   example:"Small children rely on adults for food and safety.",
   exampleJa:"小さな子どもは、食べ物や安全を大人に頼っている。",
   example2:"I relied on my notes during the difficult math test.",
   exampleJa2:"私は難しい数学のテストの間、自分のノートに頼った。",
   etymologyProcess:"re（戻す）＋ lig（結ぶ）→ 相手に自分をしっかり結びつけると…？",
   etymologyConclusion:"re（戻す）＋ lig（結ぶ）→ 相手に自分を結びつけて身を預ける＝頼る",
   relatedWords:[
     {word:"reliable",meaning:"信頼できる",breakdown:"re（戻す）＋ lig（結ぶ）→ 結びついても切れず、頼りになる"},
     {word:"religion",meaning:"宗教",breakdown:"re（戻す）＋ lig（結ぶ）→ 人と神を強く結び直すもの"},
     {word:"ally",meaning:"同盟国",breakdown:"ad（〜へ）＋ lig（結ぶ）→ 互いに結びついて味方になる"},
     {synonym:true,word:"trust",meaning:"信頼する",breakdown:"人そのものを信じる。rely は実際に頼りにすること"}]},

  {id:359,word:"pray",partOfSpeech:"自動詞",meaning:"祈る",
   meanings:["自|（for ～）（～を求めて）祈る","他|～を祈る"],
   pronunciation:"/preɪ/",part:36,
   example:"The villagers prayed for rain during the long dry summer.",
   exampleJa:"村人たちは、長く乾いた夏の間、雨を求めて祈った。",
   example2:"She prays every morning before leaving for school.",
   exampleJa2:"彼女は毎朝、学校へ出かける前に祈る。",
   etymologyProcess:"prec（願う）→ 神に向かって心から願いを差し出すと…？",
   etymologyConclusion:"prec（願う）→ 神に向かって心から願いを差し出す＝祈る",
   relatedWords:[
     {word:"prayer",meaning:"祈り",breakdown:"prec（願う）→ 神に願いを言葉にして捧げたもの"},
     {synonym:true,word:"wish",meaning:"願う",breakdown:"心で望むこと。pray は神仏に向かって願うこと"},
     {synonym:true,word:"hope",meaning:"望む",breakdown:"よい結果を待つこと。pray は願いを言葉にして捧げる"},
     {synonym:true,word:"beg",meaning:"懇願する",breakdown:"人に頭を下げて頼む。pray は相手が神仏のことが多い"}]},

  {id:360,word:"beg",partOfSpeech:"他動詞・自動詞",meaning:"懇願する",
   meanings:["他|（A to do）（Aに～してくれと）懇願する","自|（for ～）（～を）物乞いする"],
   pronunciation:"/beɡ/",part:36,
   example:"I beg you to keep this story a complete secret.",
   exampleJa:"この話を完全に秘密にしておいてくれと、あなたに懇願します。",
   example2:"He begged his parents to let him join the club.",
   exampleJa2:"彼は部活に入らせてくれと、両親に懇願した。",
   etymologyProcess:"beg（求めてすがる）→ 身を低くして相手にすがりつくと…？",
   etymologyConclusion:"beg（求めてすがる）→ 身を低くして相手にすがりつく＝懇願する",
   hook:"beg A to do（Aに～してくれと頼む）の形。I beg your pardon も同じ。",
   relatedWords:[
     {word:"beggar",meaning:"物乞いする人",breakdown:"beg（求めてすがる）＋ ar（人）→ 人にすがって施しを求める人"},
     {synonym:true,word:"plead",meaning:"嘆願する",breakdown:"改まって強く訴える。beg は必死に頼み込む感じ"},
     {synonym:true,word:"request",meaning:"要請する",breakdown:"きちんと求める。beg は身を低くして頼み込む"},
     {synonym:true,word:"pray",meaning:"祈る",breakdown:"神仏に願う。beg は相手が人であることが多い"}]},

  {id:361,word:"prefer",partOfSpeech:"他動詞",meaning:"より好む",
   meanings:["他|（A to B）（BよりAを）より好む","他|（to do）～するほうを好む"],
   pronunciation:"/prɪˈfɜːr/",part:37,
   example:"I prefer tea to coffee in the early morning.",
   exampleJa:"私は早朝には、コーヒーより紅茶をより好む。",
   example2:"She preferred to stay home rather than go shopping.",
   exampleJa2:"彼女は買い物に行くより、家にいるほうを好んだ。",
   etymologyProcess:"pre（先に）＋ fer（運ぶ）→ 二つのうち一方を先へ運び出すと…？",
   etymologyConclusion:"pre（先に）＋ fer（運ぶ）→ 二つのうち一方を先へ運び出して選ぶ＝より好む",
   relatedWords:[
     {word:"offer",meaning:"申し出る",breakdown:"of（相手のほうへ）＋ fer（運ぶ）→ 相手のほうへ差し出す"},
     {word:"transfer",meaning:"移す",breakdown:"trans（越えて）＋ fer（運ぶ）→ 境を越えて別の場所へ運ぶ"},
     {word:"preference",meaning:"好み",breakdown:"pre（先に）＋ fer（運ぶ）＋ ence（名詞）→ 先に選びたい気持ち"},
     {synonym:true,word:"choose",meaning:"選ぶ",breakdown:"実際に取り出すこと。prefer はどちらが好きかの気持ち"}]},

  {id:362,word:"weep",partOfSpeech:"自動詞",meaning:"しくしく泣く",
   meanings:["自|しくしく泣く","自|（涙を）流す"],
   pronunciation:"/wiːp/",part:37,
   example:"Many people weep at the end of that sad movie.",
   exampleJa:"多くの人が、あの悲しい映画の終わりでしくしく泣く。",
   example2:"She wept quietly when she heard the terrible news.",
   exampleJa2:"彼女はそのひどい知らせを聞いて、静かにしくしく泣いた。",
   etymologyProcess:"weep（涙を流す）→ 声をおさえて涙をこぼし続けると…？",
   etymologyConclusion:"weep（涙を流す）→ 声をおさえて涙をこぼし続ける＝しくしく泣く",
   hook:"weep–wept–wept と変化する。cry より静かに涙を流す感じ。",
   relatedWords:[
     {word:"weepy",meaning:"涙もろい",breakdown:"weep（涙を流す）＋ y（〜な状態の）→ すぐ涙が出てしまう"},
     {synonym:true,word:"cry",meaning:"泣く",breakdown:"声を出して泣く。weep は静かに涙を流すこと"},
     {synonym:true,word:"sob",meaning:"すすり泣く",breakdown:"息をつまらせて泣く。weep は涙が流れ続ける"},
     {synonym:true,word:"tear",meaning:"涙",breakdown:"目からこぼれる水。weep はそれを流す動きのほう"}]},

  {id:363,word:"hate",partOfSpeech:"他動詞",meaning:"嫌う",
   meanings:["他|～をひどく嫌う，憎む","他|（to do / doing）～するのを嫌がる"],
   pronunciation:"/heɪt/",part:37,
   example:"I hate waiting in long lines on very hot days.",
   exampleJa:"私はとても暑い日に、長い列で待つのを嫌う。",
   example2:"My brother hated vegetables when he was a small child.",
   exampleJa2:"兄は小さな子どものころ、野菜を嫌っていた。",
   etymologyProcess:"hate（激しい憎しみ）→ 相手を心の底から遠ざけたいと思うと…？",
   etymologyConclusion:"hate（激しい憎しみ）→ 相手を心の底から遠ざけたいと思う＝嫌う",
   relatedWords:[
     {word:"hatred",meaning:"憎しみ",breakdown:"hate（激しい憎しみ）→ 憎む気持ちそのものを指す名詞"},
     {word:"hateful",meaning:"憎らしい",breakdown:"hate（激しい憎しみ）＋ ful（満ちた）→ 憎しみを起こさせる"},
     {synonym:true,word:"dislike",meaning:"好きでない",breakdown:"好みに合わない程度。hate はもっと強い気持ち"},
     {synonym:true,word:"despise",meaning:"軽蔑する",breakdown:"見下して嫌う。hate は強く憎むこと"}]},

  {id:364,word:"worry",partOfSpeech:"自動詞",meaning:"心配する",
   meanings:["自|（about ～）（～について）心配する","他|～を心配させる","名|心配"],
   pronunciation:"/ˈwɜːri/",part:37,
   example:"My parents worry about my grades every single term.",
   exampleJa:"両親は毎学期、私の成績について心配する。",
   example2:"Don't worry about the test; you studied very hard.",
   exampleJa2:"テストのことは心配しないで。とても一生懸命に勉強したのだから。",
   etymologyProcess:"worry（首を絞める）→ 気がかりが心を締めつけて放さないと…？",
   etymologyConclusion:"worry（首を絞める）→ 気がかりが心を締めつけて放さない＝心配する",
   relatedWords:[
     {word:"worried",meaning:"心配そうな",breakdown:"worry（首を絞める）＋ ed（〜された）→ 心を締めつけられている"},
     {word:"worrisome",meaning:"気がかりな",breakdown:"worry（首を絞める）＋ some（〜を生む）→ 心配を生み出す"},
     {synonym:true,word:"anxious",meaning:"不安で",breakdown:"先が見えず落ち着かない。worry は考え続けること"},
     {synonym:true,word:"care",meaning:"気にかける",breakdown:"気を配ること。worry は悪い結果を思って悩む"}]},

  {id:365,word:"anxious",partOfSpeech:"形容詞",meaning:"心配して",
   meanings:["形|（about ～）（～を）心配して","形|（for ～ / to do）～を切望して"],
   pronunciation:"/ˈæŋkʃəs/",part:37,
   example:"She felt anxious about the interview all that long morning.",
   exampleJa:"彼女はその長い朝ずっと、面接について心配していた。",
   example2:"Anxious parents waited outside the exam hall for hours.",
   exampleJa2:"心配している親たちが、試験会場の外で何時間も待っていた。",
   etymologyProcess:"ang（締めつける）＋ ous（形容詞）→ 胸が締めつけられて落ち着かないと…？",
   etymologyConclusion:"ang（締めつける）＋ ous（形容詞）→ 胸が締めつけられて落ち着かない＝心配して",
   relatedWords:[
     {word:"anxiety",meaning:"不安",breakdown:"ang（締めつける）＋ ety（名詞）→ 胸が締めつけられる感じ"},
     {word:"anger",meaning:"怒り",breakdown:"ang（締めつける）＋ er（名詞）→ 胸が締めつけられて荒れる心"},
     {word:"angry",meaning:"怒って",breakdown:"ang（締めつける）＋ y（〜な状態の）→ 胸が締めつけられて荒れる"},
     {synonym:true,word:"nervous",meaning:"緊張して",breakdown:"神経が張りつめる。anxious は先の結果を気に病む"}]},

  {id:366,word:"satisfy",partOfSpeech:"他動詞",meaning:"満足させる",
   meanings:["他|～を満足させる","他|（条件など）を満たす"],
   pronunciation:"/ˈsætɪsfaɪ/",part:37,
   example:"Good grades alone do not satisfy her ambitious parents.",
   exampleJa:"良い成績だけでは、彼女の野心的な両親を満足させない。",
   example2:"The simple meal satisfied everyone at the camp site.",
   exampleJa2:"その質素な食事は、キャンプ場の全員を満足させた。",
   etymologyProcess:"satis（十分に）＋ fact（作る）→ 十分だと思える状態を作ってやると…？",
   etymologyConclusion:"satis（十分に）＋ fact（作る）→ 十分だと思える状態を相手に作ってやる＝満足させる",
   relatedWords:[
     {word:"satisfaction",meaning:"満足",breakdown:"satis（十分に）＋ fact（作る）→ 十分な状態を作ること"},
     {word:"satisfactory",meaning:"申し分のない",breakdown:"satis（十分に）＋ fact（作る）→ 十分だと言える出来である"},
     {word:"dissatisfied",meaning:"不満な",breakdown:"dis（否定）＋ satis（十分に）＋ fact（作る）→ 十分に作られていない"},
     {synonym:true,word:"please",meaning:"喜ばせる",breakdown:"気持ちを明るくする。satisfy は求めを十分に満たす"}]},

  {id:367,word:"annoy",partOfSpeech:"他動詞",meaning:"いらいらさせる",
   meanings:["他|～をいらいらさせる，悩ます"],
   pronunciation:"/əˈnɔɪ/",part:37,
   example:"Loud phone calls annoy the other people on crowded trains.",
   exampleJa:"大きな声の電話は、混んだ電車のほかの人をいらいらさせる。",
   example2:"I was annoyed by the noise from the next classroom.",
   exampleJa2:"私は隣の教室からの物音にいらいらさせられた。",
   etymologyProcess:"in（中に）＋ od（憎しみ）→ 相手の心に嫌な気持ちを植えつけると…？",
   etymologyConclusion:"in（中に）＋ od（憎しみ）→ 相手の心に嫌な気持ちを植えつける＝いらいらさせる",
   relatedWords:[
     {word:"annoying",meaning:"いらだたしい",breakdown:"in（中に）＋ od（憎しみ）＋ ing（形容詞）→ 嫌な気持ちを起こさせる"},
     {word:"annoyance",meaning:"いらだち",breakdown:"in（中に）＋ od（憎しみ）＋ ance（名詞）→ 心に起きた嫌な気持ち"},
     {synonym:true,word:"irritate",meaning:"いらつかせる",breakdown:"神経をこする。annoy は繰り返されて嫌になる感じ"},
     {synonym:true,word:"bother",meaning:"面倒をかける",breakdown:"手間をかけさせる。annoy は気持ちを乱すこと"}]},

  {id:368,word:"bother",partOfSpeech:"他動詞",meaning:"面倒をかける",
   meanings:["他|～に面倒をかける，～を悩ます","自|（to do）わざわざ～する"],
   pronunciation:"/ˈbɒðər/",part:37,
   example:"Sorry to bother you, but may I ask something now?",
   exampleJa:"面倒をかけてすみませんが、今少し聞いてもよいですか。",
   example2:"My little sister bothered me during the whole study session.",
   exampleJa2:"妹は勉強している間ずっと、私に面倒をかけた。",
   etymologyProcess:"bother（耳ざわりで悩ます）→ 耳もとでうるさくして手間をかけると…？",
   etymologyConclusion:"bother（耳ざわりで悩ます）→ 耳もとでうるさくして手間をかけさせる＝面倒をかける",
   hook:"Don't bother.（気にしないで）／ bother to do（わざわざ～する）。",
   relatedWords:[
     {word:"bothersome",meaning:"やっかいな",breakdown:"bother（耳ざわりで悩ます）＋ some（〜を生む）→ 面倒を生む"},
     {synonym:true,word:"trouble",meaning:"悩ませる",breakdown:"困った状態にする。bother は小さな手間をかけること"},
     {synonym:true,word:"disturb",meaning:"じゃまをする",breakdown:"落ち着きを乱す。bother は手間をかけて煩わせる"},
     {synonym:true,word:"annoy",meaning:"いらいらさせる",breakdown:"気持ちを乱す。bother は手間や迷惑のほうに重点"}]},

  {id:369,word:"disturb",partOfSpeech:"他動詞",meaning:"じゃまをする",
   meanings:["他|～のじゃまをする","他|（心）を乱す"],
   pronunciation:"/dɪˈstɜːrb/",part:37,
   example:"Please do not disturb the students during the long exam.",
   exampleJa:"長い試験の間、生徒のじゃまをしないでください。",
   example2:"His phone call disturbed my concentration on the homework.",
   exampleJa2:"彼の電話が、宿題への私の集中のじゃまをした。",
   etymologyProcess:"dis（バラバラに）＋ turb（かき乱す）→ 落ち着いているものをかき乱すと…？",
   etymologyConclusion:"dis（バラバラに）＋ turb（かき乱す）→ 落ち着いているものをかき乱す＝じゃまをする",
   relatedWords:[
     {word:"disturbance",meaning:"騒動",breakdown:"dis（バラバラに）＋ turb（かき乱す）→ かき乱された状態"},
     {word:"turbine",meaning:"タービン",breakdown:"turb（かき乱す）＋ ine（もの）→ 渦を巻いて回る機械"},
     {word:"trouble",meaning:"悩ませる",breakdown:"turb（かき乱す）→ 心をかき乱して困らせる"},
     {synonym:true,word:"interrupt",meaning:"さえぎる",breakdown:"話や作業を途中で切る。disturb は落ち着きを乱す"}]},

  {id:370,word:"frighten",partOfSpeech:"他動詞",meaning:"こわがらせる",
   meanings:["他|～をこわがらせる，おびえさせる"],
   pronunciation:"/ˈfraɪtən/",part:37,
   example:"Thunder often frightens small children in the middle of the night.",
   exampleJa:"雷はしばしば、真夜中に小さな子どもをこわがらせる。",
   example2:"The old empty house frightened us on our evening walk.",
   exampleJa2:"その古い空き家は、夕方の散歩中の私たちをこわがらせた。",
   etymologyProcess:"fright（おびえ）＋ en（〜にする）→ 相手の心を急に縮み上がらせると…？",
   etymologyConclusion:"fright（おびえ）＋ en（〜にする）→ 相手の心を急に縮み上がらせる＝こわがらせる",
   relatedWords:[
     {word:"fright",meaning:"恐怖",breakdown:"fright（おびえ）→ 突然おそってくる強い恐れ"},
     {word:"frightening",meaning:"恐ろしい",breakdown:"fright（おびえ）＋ ing（形容詞）→ 相手をこわがらせる"},
     {word:"frightened",meaning:"おびえた",breakdown:"fright（おびえ）＋ ed（〜された）→ こわがらされている"},
     {synonym:true,word:"scare",meaning:"おびえさせる",breakdown:"急に驚かせる。frighten は少し硬い言い方"}]},

  {id:371,word:"regret",partOfSpeech:"他動詞",meaning:"後悔する",
   meanings:["他|～を後悔する","名|後悔"],
   pronunciation:"/rɪˈɡret/",part:38,
   example:"I regret not studying harder for the entrance exam.",
   exampleJa:"私は入試のためにもっと勉強しなかったことを後悔している。",
   example2:"She regretted her rude words to her best friend.",
   exampleJa2:"彼女は親友への失礼な言葉を後悔した。",
   etymologyProcess:"re（何度も）＋ gret（泣く）→ 済んだことを思い返して何度も嘆くと…？",
   etymologyConclusion:"re（何度も）＋ gret（泣く）→ 済んだことを思い返して何度も嘆く＝後悔する",
   relatedWords:[
     {word:"regretful",meaning:"残念に思う",breakdown:"re（何度も）＋ gret（泣く）＋ ful（満ちた）→ 悔やむ気持ちに満ちた"},
     {word:"regrettable",meaning:"遺憾な",breakdown:"re（何度も）＋ gret（泣く）＋ able（できる）→ 悔やまずにいられない"},
     {synonym:true,word:"apologize",meaning:"謝る",breakdown:"相手に謝罪を言う。regret は自分の心の中の悔い"},
     {synonym:true,word:"repent",meaning:"悔い改める",breakdown:"過ちを悔いて改める。regret は悔やむ気持ち全般"}]},

  {id:372,word:"favor",partOfSpeech:"名詞",meaning:"親切な行為；頼み事",
   meanings:["名|親切な行為，頼み事","名|好意","他|～に賛成する"],
   pronunciation:"/ˈfeɪvər/",part:38,
   example:"He did me a favor by carrying my heavy bag.",
   exampleJa:"彼は重いかばんを運ぶという親切な行為をしてくれた。",
   example2:"May I ask you a favor before the class starts?",
   exampleJa2:"授業が始まる前に、一つ頼み事をしてもよいですか。",
   etymologyProcess:"fav（好意を寄せる）＋ or（もの）→ 相手に好意を寄せてしてやることは…？",
   etymologyConclusion:"fav（好意を寄せる）＋ or（もの）→ 相手に好意を寄せてしてやること＝親切な行為",
   relatedWords:[
     {word:"favorite",meaning:"大好きな",breakdown:"fav（好意を寄せる）＋ ite（もの）→ いちばん好意を寄せるもの"},
     {word:"favorable",meaning:"好意的な",breakdown:"fav（好意を寄せる）＋ able（できる）→ 好意を向けてもらえる"},
     {synonym:true,word:"kindness",meaning:"親切",breakdown:"優しさ全般。favor は具体的にしてあげる一つの行い"},
     {synonym:true,word:"help",meaning:"助け",breakdown:"手を貸すこと。favor は頼まれてする親切な行い"}]},

  {id:373,word:"interest",partOfSpeech:"名詞",meaning:"関心",
   meanings:["名|（in ～）（～への）関心，興味","名|利子","他|～に関心を持たせる"],
   pronunciation:"/ˈɪntrəst/",part:38,
   example:"She has a deep interest in traditional Japanese music.",
   exampleJa:"彼女は日本の伝統音楽に深い関心を持っている。",
   example2:"My interest in science grew after that summer camp.",
   exampleJa2:"科学への私の関心は、あの夏の合宿のあとで大きくなった。",
   etymologyProcess:"inter（間の）＋ esse（ある）→ 自分と物事の間に入り込んでくるものは…？",
   etymologyConclusion:"inter（間の）＋ esse（ある）→ 自分と物事の間に入り込んでくる心の動き＝関心",
   relatedWords:[
     {word:"interesting",meaning:"興味深い",breakdown:"inter（間の）＋ esse（ある）＋ ing（形容詞）→ 心の間に入り込む"},
     {word:"interested",meaning:"興味がある",breakdown:"inter（間の）＋ esse（ある）＋ ed（〜された）→ 心を引き入れられた"},
     {word:"essence",meaning:"本質",breakdown:"esse（ある）＋ ence（名詞）→ それが「ある」と言える中心"},
     {synonym:true,word:"curiosity",meaning:"好奇心",breakdown:"知りたい気持ち。interest は関わりたい気持ち"}]},

  {id:374,word:"pity",partOfSpeech:"名詞",meaning:"残念なこと",
   meanings:["名|残念なこと","名|哀れみ","他|～を気の毒に思う"],
   pronunciation:"/ˈpɪti/",part:38,
   example:"It is a pity that you cannot join our trip.",
   exampleJa:"あなたが旅行に参加できないのは残念なことだ。",
   example2:"What a pity we missed the last train home!",
   exampleJa2:"最終電車を逃したとは、なんと残念なことだろう。",
   etymologyProcess:"pi（敬い思いやる）＋ ty（名詞）→ 相手の不幸を思いやって胸が痛むと…？",
   etymologyConclusion:"pi（敬い思いやる）＋ ty（名詞）→ 相手の不幸を思いやって胸が痛むこと＝残念なこと",
   relatedWords:[
     {word:"pitiful",meaning:"哀れな",breakdown:"pi（敬い思いやる）＋ ful（満ちた）→ 思いやりを誘うほど気の毒だ"},
     {word:"pious",meaning:"信心深い",breakdown:"pi（敬い思いやる）＋ ous（形容詞）→ 神を敬う心に満ちている"},
     {synonym:true,word:"shame",meaning:"残念なこと",breakdown:"What a shame! も同じ意味。pity は同情の気持ちを含む"},
     {synonym:true,word:"sympathy",meaning:"同情",breakdown:"相手と同じ気持ちになる。pity は気の毒に思う気持ち"}]},

  {id:375,word:"due",partOfSpeech:"形容詞",meaning:"～が原因で",
   meanings:["形|（due to ～で）～が原因で","形|期限が来て"],
   pronunciation:"/duː/",part:38,
   example:"The delay was due to heavy snow in the mountains.",
   exampleJa:"遅れは、山地の大雪が原因だった。",
   example2:"Many accidents are due to careless use of smartphones.",
   exampleJa2:"多くの事故は、スマートフォンの不注意な使用が原因である。",
   etymologyProcess:"due（負っている）→ そのできごとに借りがあると考えると…？",
   etymologyConclusion:"due（負っている）→ そこに借りがあり、そこから来ている＝～が原因で",
   hook:"due to ～（～が原因で）の形。期限なら The report is due Friday.",
   relatedWords:[
     {word:"duty",meaning:"義務",breakdown:"due（負っている）＋ ty（名詞）→ 返さねばならないつとめ"},
     {synonym:true,word:"because",meaning:"なぜなら",breakdown:"あとに文が来る。due to のあとは名詞が来る"},
     {synonym:true,word:"owing",meaning:"～のせいで",breakdown:"owe（負う）から。owing to は due to とほぼ同じ"},
     {synonym:true,word:"thanks",meaning:"～のおかげで",breakdown:"thanks to は良い原因に使う。due to は良し悪しを問わない"}]},

  {id:376,word:"reason",partOfSpeech:"名詞",meaning:"理由",
   meanings:["名|（for ～）（～の）理由","名|理性"],
   pronunciation:"/ˈriːzən/",part:38,
   example:"Please tell me the reason for your long absence.",
   exampleJa:"長く休んだ理由を教えてください。",
   example2:"There is no good reason to change our plan now.",
   exampleJa2:"今、計画を変える良い理由はない。",
   etymologyProcess:"rat（計算する）→ 筋道を数え上げて示せるものは…？",
   etymologyConclusion:"rat（計算する）→ 筋道を数え上げて相手に示せるもの＝理由",
   relatedWords:[
     {word:"rate",meaning:"割合",breakdown:"rat（計算する）→ 数え上げて出した比の値"},
     {word:"ratio",meaning:"比",breakdown:"rat（計算する）→ 二つの数を計算して比べた割合"},
     {word:"rational",meaning:"理性的な",breakdown:"rat（計算する）＋ al（〜の）→ 筋道を計算して考える"},
     {synonym:true,word:"cause",meaning:"原因",breakdown:"結果を生むもと。reason は人が示す筋道のほう"}]},

  {id:377,word:"result",partOfSpeech:"名詞",meaning:"結果",
   meanings:["名|（of ～）（～の）結果","自|（from ～）（～から）生じる","自|（in ～）（～という）結果になる"],
   pronunciation:"/rɪˈzʌlt/",part:38,
   example:"The result of the experiment surprised the whole science class.",
   exampleJa:"その実験の結果は、理科のクラス全体を驚かせた。",
   example2:"Hard work usually results in better grades at school.",
   exampleJa2:"努力はふつう、学校でのより良い成績という結果になる。",
   etymologyProcess:"re（戻す）＋ sult（跳ぶ）→ 跳ね返って最後に現れてくるものは…？",
   etymologyConclusion:"re（戻す）＋ sult（跳ぶ）→ 原因から跳ね返って最後に現れるもの＝結果",
   relatedWords:[
     {word:"insult",meaning:"侮辱する",breakdown:"in（上に）＋ sult（跳ぶ）→ 相手に跳びかかって傷つける"},
     {synonym:true,word:"effect",meaning:"効果",breakdown:"原因が生む働き。result は最後に出てきた結末"},
     {synonym:true,word:"outcome",meaning:"成り行き",breakdown:"外へ出てきたもの。result より話し言葉に近い"},
     {synonym:true,word:"consequence",meaning:"（悪い）結果",breakdown:"あとから続いて起きること。result より硬い語"}]},

  {id:378,word:"effect",partOfSpeech:"名詞",meaning:"効果",
   meanings:["名|（on ～）（～への）効果，影響","名|効力"],
   pronunciation:"/ɪˈfekt/",part:38,
   example:"The new medicine had a quick effect on the patient.",
   exampleJa:"その新しい薬は、患者にすばやい効果があった。",
   example2:"Warming up before practice has a good effect on runners.",
   exampleJa2:"練習前の準備運動は、走る人に良い効果がある。",
   etymologyProcess:"ef（外へ）＋ fect（作る）→ 働きかけが外に作り出したものは…？",
   etymologyConclusion:"ef（外へ）＋ fect（作る）→ 働きかけが外にはっきり作り出したもの＝効果",
   relatedWords:[
     {word:"effective",meaning:"効果的な",breakdown:"ef（外へ）＋ fect（作る）＋ ive（形容詞）→ 結果をよく作り出す"},
     {word:"perfect",meaning:"完全な",breakdown:"per（すっかり）＋ fect（作る）→ すっかり作り終えて欠けがない"},
     {word:"affect",meaning:"影響を与える",breakdown:"ad（〜へ）＋ fect（作る）→ 外から働きかけて相手を動かす"},
     {synonym:true,word:"influence",meaning:"影響（力）",breakdown:"じわじわ及ぼす力。effect は現れた結果のほう"}]},

  {id:379,word:"influence",partOfSpeech:"名詞",meaning:"影響（力）",
   meanings:["名|（on ～）（～への）影響（力）","他|～に影響を与える"],
   pronunciation:"/ˈɪnfluəns/",part:38,
   example:"Her teacher had a strong influence on her future career.",
   exampleJa:"彼女の先生は、彼女の将来の仕事に強い影響を与えた。",
   example2:"Social media influences the way young people think today.",
   exampleJa2:"ソーシャルメディアは、今日の若者の考え方に影響を与えている。",
   etymologyProcess:"in（中へ）＋ flu（流れる）→ 相手の中へ静かに流れ込む力は…？",
   etymologyConclusion:"in（中へ）＋ flu（流れる）→ 相手の中へ静かに流れ込んで動かす力＝影響（力）",
   relatedWords:[
     {word:"fluent",meaning:"流ちょうな",breakdown:"flu（流れる）＋ ent（〜している）→ 言葉が水のように流れる"},
     {word:"influential",meaning:"影響力のある",breakdown:"in（中へ）＋ flu（流れる）＋ al（〜の）→ 流れ込む力が強い"},
     {word:"flu",meaning:"インフルエンザ",breakdown:"flu（流れる）→ 星の力が流れ込んで起きると考えられた病"},
     {synonym:true,word:"effect",meaning:"効果",breakdown:"現れた結果のほう。influence はじわじわ働く力"}]},

  {id:380,word:"end",partOfSpeech:"自動詞",meaning:"結局～することになる",
   meanings:["自|（end up doing で）結局～することになる","自|終わる","名|終わり"],
   pronunciation:"/end/",part:38,
   example:"We ended up walking home after missing the last bus.",
   exampleJa:"最終バスを逃して、私たちは結局歩いて帰ることになった。",
   example2:"If you rush, you may end up making more mistakes.",
   exampleJa2:"急ぐと、結局もっと多くの間違いをすることになるかもしれない。",
   etymologyProcess:"end（いちばん端）→ ものごとの端までたどり着いてみると…？",
   etymologyConclusion:"end（いちばん端）→ 進んだ末に端までたどり着く＝結局～することになる",
   relatedWords:[
     {word:"ending",meaning:"結末",breakdown:"end（いちばん端）＋ ing（名詞）→ 話のいちばん端の部分"},
     {word:"endless",meaning:"果てしない",breakdown:"end（いちばん端）＋ less（ない）→ 端がどこにも見つからない"},
     {word:"weekend",meaning:"週末",breakdown:"week（週）＋ end（いちばん端）→ 一週間のいちばん端"},
     {synonym:true,word:"finish",meaning:"終える",breakdown:"やり終えること。end は端に行き着いて止まること"}]},

  {id:381,word:"cause",partOfSpeech:"他動詞",meaning:"引き起こす",
   meanings:["他|～を引き起こす","名|原因"],
   pronunciation:"/kɔːz/",part:39,
   example:"Heavy rain caused serious damage to the old wooden bridge.",
   exampleJa:"大雨が、古い木造の橋に深刻な被害を引き起こした。",
   example2:"Smoking causes many kinds of illness in later life.",
   exampleJa2:"喫煙は、のちの人生で多くの種類の病気を引き起こす。",
   etymologyProcess:"cus（原因）→ ものごとの始まりとなってあとを動かすと…？",
   etymologyConclusion:"cus（原因）→ ものごとの始まりとなって、あとを動かす＝引き起こす",
   relatedWords:[
     {word:"accuse",meaning:"非難する",breakdown:"ad（〜へ）＋ cus（原因）→ 責めの原因を相手に向ける"},
     {word:"excuse",meaning:"言い訳",breakdown:"ex（外へ）＋ cus（原因）→ 責めの原因を外へ取り除く"},
     {word:"because",meaning:"なぜなら",breakdown:"be（〜によって）＋ cus（原因）→ その原因によって、と示す"},
     {synonym:true,word:"bring",meaning:"もたらす",breakdown:"bring about で「引き起こす」。cause は原因そのもの"}]},

  {id:382,word:"affect",partOfSpeech:"他動詞",meaning:"影響を与える",
   meanings:["他|～に影響を与える","他|（病気が）～を冒す"],
   pronunciation:"/əˈfekt/",part:39,
   example:"The typhoon affected train service across the whole region.",
   exampleJa:"台風は、地域全体の鉄道の運行に影響を与えた。",
   example2:"Lack of sleep affects your memory and your mood.",
   exampleJa2:"睡眠不足は、記憶と気分に影響を与える。",
   etymologyProcess:"ad（〜へ）＋ fect（作る）→ 相手に働きかけて変化を作り出すと…？",
   etymologyConclusion:"ad（〜へ）＋ fect（作る）→ 相手に働きかけて、変化を作り出す＝影響を与える",
   relatedWords:[
     {word:"effect",meaning:"効果",breakdown:"ef（外へ）＋ fect（作る）→ 外にはっきり現れた結果"},
     {word:"affection",meaning:"愛情",breakdown:"ad（〜へ）＋ fect（作る）＋ ion（名詞）→ 心に作られた温かい思い"},
     {word:"infect",meaning:"感染させる",breakdown:"in（中へ）＋ fect（作る）→ 体の中に病気を作り込む"},
     {synonym:true,word:"influence",meaning:"影響（力）",breakdown:"名詞で使うことが多い。affect は動詞で使う"}]},

  {id:383,word:"way",partOfSpeech:"名詞",meaning:"方法，やり方",
   meanings:["名|（to do）（～する）方法，やり方","名|道，道のり"],
   pronunciation:"/weɪ/",part:39,
   example:"There must be a better way to solve this problem.",
   exampleJa:"この問題を解決する、もっと良い方法があるはずだ。",
   example2:"She explained the way to use the new machine.",
   exampleJa2:"彼女は新しい機械を使う方法を説明した。",
   etymologyProcess:"way（道）→ 目的地まで通っていく道すじが表すものは…？",
   etymologyConclusion:"way（道）→ 目的地まで通っていく道すじ＝方法，やり方",
   relatedWords:[
     {word:"subway",meaning:"地下鉄",breakdown:"sub（下で）＋ way（道）→ 地面の下を通る道"},
     {word:"highway",meaning:"幹線道路",breakdown:"high（高い）＋ way（道）→ 高く土を盛って作った主要な道"},
     {synonym:true,word:"method",meaning:"方法",breakdown:"手順の決まったやり方。way はもっと広く使える"},
     {synonym:true,word:"means",meaning:"手段",breakdown:"目的を達する手だて。way は日常的な言い方"}]},

  {id:384,word:"manner",partOfSpeech:"名詞",meaning:"作法，ふるまい方",
   meanings:["名|作法，ふるまい方","名|（manners で）行儀"],
   pronunciation:"/ˈmænər/",part:39,
   example:"He spoke to the guests in a very polite manner.",
   exampleJa:"彼は客に、とても礼儀正しいふるまい方で話しかけた。",
   example2:"Table manners differ from country to country around the world.",
   exampleJa2:"食事の作法は、世界の国ごとに異なる。",
   etymologyProcess:"man（手）＋ er（もの）→ 手の使い方がそのまま表すものは…？",
   etymologyConclusion:"man（手）＋ er（もの）→ 手の使い方から広がった、ふるまいの型＝作法，ふるまい方",
   relatedWords:[
     {word:"manual",meaning:"手引き",breakdown:"man（手）＋ ual（〜の）→ 手で扱うための説明書"},
     {word:"manage",meaning:"経営する",breakdown:"man（手）＋ age（すること）→ 手で手綱をさばいて動かす"},
     {word:"manufacture",meaning:"製造する",breakdown:"man（手）＋ fact（作る）→ もともとは手で作り出すこと"},
     {synonym:true,word:"way",meaning:"方法",breakdown:"広く方法を指す。manner はふるまい方や作法"}]},

  {id:385,word:"purpose",partOfSpeech:"名詞",meaning:"目的",
   meanings:["名|（of ～）（～の）目的","名|（on purpose で）わざと"],
   pronunciation:"/ˈpɜːrpəs/",part:39,
   example:"The purpose of this meeting is to choose a leader.",
   exampleJa:"この会議の目的は、リーダーを選ぶことだ。",
   example2:"He came to Japan for the purpose of studying music.",
   exampleJa2:"彼は音楽を学ぶ目的で日本に来た。",
   etymologyProcess:"pur（前へ）＋ pos（置く）→ 自分の前に置いておくねらいは…？",
   etymologyConclusion:"pur（前へ）＋ pos（置く）→ 自分の前に置いて見すえるねらい＝目的",
   relatedWords:[
     {word:"propose",meaning:"提案する",breakdown:"pro（前へ）＋ pos（置く）→ 考えを人の前に置いて見せる"},
     {word:"compose",meaning:"構成する",breakdown:"com（共に）＋ pos（置く）→ いくつかを組み合わせて置く"},
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ion（名詞）→ 置かれている場所"},
     {synonym:true,word:"aim",meaning:"ねらい",breakdown:"ねらう的のこと。purpose は行いの目的そのもの"}]},

  {id:386,word:"sake",partOfSpeech:"名詞",meaning:"ため",
   meanings:["名|（for the sake of ～で）～のため"],
   pronunciation:"/seɪk/",part:39,
   example:"She moved to the countryside for the sake of her health.",
   exampleJa:"彼女は健康のために田舎へ引っ越した。",
   example2:"Please keep quiet for the sake of the other students.",
   exampleJa2:"ほかの生徒のために、静かにしていてください。",
   etymologyProcess:"sake（言い分・訴え）→ だれかの言い分を通そうとして動くと…？",
   etymologyConclusion:"sake（言い分・訴え）→ だれかの言い分を通そうとして動くこと＝ため",
   hook:"for the sake of ～／for ～'s sake（～のために）の形で使う。",
   relatedWords:[
     {synonym:true,word:"benefit",meaning:"利益",breakdown:"for the benefit of も「～のために」。sake は決まり文句"},
     {synonym:true,word:"purpose",meaning:"目的",breakdown:"for the purpose of は目的。sake は相手の利益のため"},
     {synonym:true,word:"behalf",meaning:"代わり",breakdown:"on behalf of は「～を代表して」。sake とは別の形"}]},

  {id:387,word:"right",partOfSpeech:"副詞",meaning:"ちょうど，まさに",
   meanings:["副|ちょうど，まさに","形|正しい","名|権利"],
   pronunciation:"/raɪt/",part:39,
   example:"The post office is right next to the old station.",
   exampleJa:"郵便局は、古い駅のちょうど隣にある。",
   example2:"He arrived right after the bell rang this morning.",
   exampleJa2:"彼は今朝、ベルが鳴ったちょうどあとに着いた。",
   etymologyProcess:"right（まっすぐ）→ ずれることなくまっすぐそこを指すと…？",
   etymologyConclusion:"right（まっすぐ）→ ずれることなくまっすぐそこを指す＝ちょうど，まさに",
   relatedWords:[
     {word:"correct",meaning:"正しい",breakdown:"com（強く）＋ rect（まっすぐ）→ 曲がりを直してまっすぐにする"},
     {word:"direct",meaning:"直接の",breakdown:"di（離れて）＋ rect（まっすぐ）→ よそへそれずまっすぐ向かう"},
     {word:"erect",meaning:"直立した",breakdown:"ex（外へ）＋ rect（まっすぐ）→ まっすぐ上へ立ち上がる"},
     {synonym:true,word:"exactly",meaning:"正確に",breakdown:"ぴったり合うこと。right は位置や時の「ちょうど」"}]},

  {id:388,word:"complete",partOfSpeech:"形容詞",meaning:"完全な",
   meanings:["形|完全な，欠けのない","他|～を完成させる"],
   pronunciation:"/kəmˈpliːt/",part:39,
   example:"The report is not complete without the final figures.",
   exampleJa:"最終の数字がなければ、その報告書は完全ではない。",
   example2:"She gave us a complete list of the club members.",
   exampleJa2:"彼女は部員の完全な名簿を私たちにくれた。",
   etymologyProcess:"com（すっかり）＋ ple（満たす）→ 欠けなくすっかり満たされていると…？",
   etymologyConclusion:"com（すっかり）＋ ple（満たす）→ 欠けなくすっかり満たされている＝完全な",
   relatedWords:[
     {word:"plenty",meaning:"たくさん",breakdown:"ple（満たす）＋ ty（名詞）→ いっぱいに満たされている量"},
     {word:"supplement",meaning:"補うもの",breakdown:"sub（下で）＋ ple（満たす）→ 下から足して満たすもの"},
     {word:"complement",meaning:"補ってそろえるもの",breakdown:"com（すっかり）＋ ple（満たす）→ 欠けた所を満たすもの"},
     {synonym:true,word:"whole",meaning:"全体の",breakdown:"欠けのない全部。complete は最後まで満たされた状態"}]},

  {id:389,word:"hardly",partOfSpeech:"副詞",meaning:"ほとんど～ない",
   meanings:["副|ほとんど～ない","副|（hardly ever で）めったに～ない"],
   pronunciation:"/ˈhɑːrdli/",part:39,
   example:"I could hardly hear the teacher from the back row.",
   exampleJa:"後ろの列からは、先生の声がほとんど聞こえなかった。",
   example2:"She hardly ever eats breakfast before going to school.",
   exampleJa2:"彼女は学校へ行く前、ほとんど朝食を食べない。",
   etymologyProcess:"hard（かたい）＋ ly（副詞）→ かたくて難しく、やっとしかできないと…？",
   etymologyConclusion:"hard（かたい）＋ ly（副詞）→ かたくて難しく、やっとしかできない＝ほとんど～ない",
   relatedWords:[
     {word:"hard",meaning:"かたい，難しい",breakdown:"hard（かたい）→ 力を入れても形が変わらない"},
     {word:"hardship",meaning:"苦難",breakdown:"hard（かたい）＋ ship（名詞）→ 耐えるのがかたく難しい状態"},
     {word:"harden",meaning:"かたくする",breakdown:"hard（かたい）＋ en（〜にする）→ かたい状態にする"},
     {synonym:true,word:"scarcely",meaning:"ほとんど～ない",breakdown:"hardly とほぼ同じ意味。少し硬い言い方"}]},

  {id:390,word:"almost",partOfSpeech:"副詞",meaning:"ほとんど",
   meanings:["副|ほとんど，もう少しで"],
   pronunciation:"/ˈɔːlmoʊst/",part:39,
   example:"Almost all the students finished the report on time.",
   exampleJa:"ほとんどすべての生徒が、時間どおりに報告書を終えた。",
   example2:"We are almost ready to leave for the airport.",
   exampleJa2:"私たちは空港へ出発する準備がほとんどできている。",
   etymologyProcess:"all（すっかり）＋ most（最も）→ 全部に最も近いところまで来ていると…？",
   etymologyConclusion:"all（すっかり）＋ most（最も）→ 全部に最も近いところまで来ている＝ほとんど",
   relatedWords:[
     {word:"always",meaning:"いつも",breakdown:"all（すっかり）＋ way（道）→ どの道のりもずっと続けて"},
     {word:"already",meaning:"すでに",breakdown:"all（すっかり）＋ ready（整った）→ すっかり用意が整って"},
     {synonym:true,word:"nearly",meaning:"ほぼ",breakdown:"almost とほぼ同じ。数字には nearly が好まれる"},
     {synonym:true,word:"practically",meaning:"事実上",breakdown:"ほぼそう言ってよい。almost は「もう少しで」"}]},

  {id:391,word:"partly",partOfSpeech:"副詞",meaning:"ある程度は",
   meanings:["副|ある程度は，一部分は"],
   pronunciation:"/ˈpɑːrtli/",part:40,
   example:"The accident was partly caused by the thick morning fog.",
   exampleJa:"その事故は、ある程度は朝の濃い霧によって引き起こされた。",
   example2:"I partly agree with your idea about the school trip.",
   exampleJa2:"修学旅行についてのあなたの考えに、ある程度は賛成だ。",
   etymologyProcess:"part（分ける）＋ ly（副詞）→ 全体ではなく分けた一部分だけだと…？",
   etymologyConclusion:"part（分ける）＋ ly（副詞）→ 全体ではなく分けた一部分だけ当てはまる＝ある程度は",
   relatedWords:[
     {word:"part",meaning:"部分",breakdown:"part（分ける）→ 全体から切り分けられた一つ"},
     {word:"partial",meaning:"部分的な",breakdown:"part（分ける）＋ al（〜の）→ 一部分だけにかかわる"},
     {word:"particle",meaning:"粒子",breakdown:"part（分ける）＋ icle（小さいもの）→ 細かく分けた小さなもの"},
     {synonym:true,word:"mostly",meaning:"主に",breakdown:"大部分がそうだということ。partly は一部だけ"}]},

  {id:392,word:"indeed",partOfSpeech:"副詞",meaning:"実際に",
   meanings:["副|実際に，本当に","副|（前の内容を受けて）それどころか"],
   pronunciation:"/ɪnˈdiːd/",part:40,
   example:"The view from the mountain top was beautiful indeed.",
   exampleJa:"山頂からの眺めは、実際に美しかった。",
   example2:"Indeed, many students find this subject quite difficult.",
   exampleJa2:"実際に、多くの生徒がこの科目をかなり難しいと感じている。",
   etymologyProcess:"in（中に）＋ deed（行い）→ 言葉だけでなく実際の行いで見ると…？",
   etymologyConclusion:"in（中に）＋ deed（行い）→ 言葉だけでなく実際の行いの中で確かだ＝実際に",
   relatedWords:[
     {word:"deed",meaning:"行い",breakdown:"deed（行い）→ 実際に行われた一つのおこない"},
     {word:"misdeed",meaning:"悪行",breakdown:"mis（誤って）＋ deed（行い）→ してはいけない行い"},
     {synonym:true,word:"really",meaning:"本当に",breakdown:"確かにそうだ。indeed は前の内容を強めて念を押す"},
     {synonym:true,word:"actually",meaning:"実は",breakdown:"事実を言い直すとき。indeed は強調に使う"}]},

  {id:393,word:"even",partOfSpeech:"副詞",meaning:"～でさえ",
   meanings:["副|～でさえ","副|（比較級を強めて）いっそう","形|平らな；偶数の"],
   pronunciation:"/ˈiːvən/",part:40,
   example:"Even young children can understand this simple picture book.",
   exampleJa:"幼い子どもでさえ、この簡単な絵本を理解できる。",
   example2:"He did not even say goodbye before leaving the room.",
   exampleJa2:"彼は部屋を出る前、さよならさえ言わなかった。",
   etymologyProcess:"even（平らな）→ 高さの差をなくして話を広げると…？",
   etymologyConclusion:"even（平らな）→ 高さの差をならして、意外なものまで含める＝～でさえ",
   hook:"even if / even though（たとえ～でも）。形容詞なら「偶数の」。",
   relatedWords:[
     {word:"evenly",meaning:"均等に",breakdown:"even（平らな）＋ ly（副詞）→ でこぼこなく等しく"},
     {word:"uneven",meaning:"でこぼこの",breakdown:"un（否定）＋ even（平らな）→ 平らになっていない"},
     {synonym:true,word:"still",meaning:"それでも",breakdown:"even so と近い。even は極端な例を挙げて強める"},
     {synonym:true,word:"also",meaning:"～もまた",breakdown:"単に付け加える。even は意外なものを付け加える"}]},

  {id:394,word:"exactly",partOfSpeech:"副詞",meaning:"正確に",
   meanings:["副|正確に，きっかり","副|（返事で）そのとおり"],
   pronunciation:"/ɪɡˈzæktli/",part:40,
   example:"Tell me exactly what happened after the class ended.",
   exampleJa:"授業が終わったあと何が起きたのか、正確に教えてください。",
   example2:"The train left exactly on time this cold winter morning.",
   exampleJa2:"その電車は、この寒い冬の朝、正確に時刻どおりに出発した。",
   etymologyProcess:"ex（外へ）＋ act（追い立てる）→ 最後まで追い込んで測り切ると…？",
   etymologyConclusion:"ex（外へ）＋ act（追い立てる）→ 最後まで追い込んで測り切りずれがない＝正確に",
   relatedWords:[
     {word:"exact",meaning:"正確な",breakdown:"ex（外へ）＋ act（追い立てる）→ 最後まで追い込んで測り切る"},
     {word:"action",meaning:"行動",breakdown:"act（追い立てる）＋ ion（名詞）→ 物事を前へ動かすこと"},
     {word:"active",meaning:"活発な",breakdown:"act（追い立てる）＋ ive（形容詞）→ 自分から物事を動かす"},
     {synonym:true,word:"precisely",meaning:"まさに",breakdown:"寸分たがわず。exactly とほぼ入れ替えて使える"}]},

  {id:395,word:"gradually",partOfSpeech:"副詞",meaning:"徐々に",
   meanings:["副|徐々に，少しずつ"],
   pronunciation:"/ˈɡrædʒuəli/",part:40,
   example:"The sky gradually turned red as the sun went down.",
   exampleJa:"日が沈むにつれ、空は徐々に赤くなった。",
   example2:"Her English improved gradually during the long summer vacation.",
   exampleJa2:"彼女の英語は、長い夏休みの間に徐々に上達した。",
   etymologyProcess:"grad（歩み・段）＋ ly（副詞）→ 階段を一段ずつ上るように進むと…？",
   etymologyConclusion:"grad（歩み・段）＋ ly（副詞）→ 階段を一段ずつ上るように進む＝徐々に",
   relatedWords:[
     {word:"gradual",meaning:"少しずつの",breakdown:"grad（歩み・段）＋ al（〜の）→ 一段ずつ進んでいく"},
     {word:"graduate",meaning:"卒業する",breakdown:"grad（歩み・段）＋ ate（動詞）→ 学びの段を上りきる"},
     {word:"grade",meaning:"学年，等級",breakdown:"grad（歩み・段）→ 一段ずつ上がっていく区切り"},
     {synonym:true,word:"slowly",meaning:"ゆっくり",breakdown:"速さが遅いこと。gradually は少しずつ変わること"}]},

  {id:396,word:"therefore",partOfSpeech:"副詞",meaning:"それゆえに",
   meanings:["副|それゆえに，したがって"],
   pronunciation:"/ˈðerfɔːr/",part:40,
   example:"It rained hard; therefore, the game was cancelled today.",
   exampleJa:"雨が強く降った。それゆえに、今日の試合は中止になった。",
   example2:"He studied very hard and therefore passed the difficult exam.",
   exampleJa2:"彼はとても熱心に勉強し、それゆえに難しい試験に合格した。",
   etymologyProcess:"there（そこ）＋ fore（前に）→ そこを土台にして話を前へ進めると…？",
   etymologyConclusion:"there（そこ）＋ fore（前に）→ そこを土台にして話を前へ進める＝それゆえに",
   relatedWords:[
     {word:"before",meaning:"～の前に",breakdown:"be（すっかり）＋ fore（前に）→ 時や場所の前のほうに"},
     {word:"foresee",meaning:"予見する",breakdown:"fore（前に）＋ see（見る）→ 先のことを前もって見る"},
     {synonym:true,word:"thus",meaning:"このように",breakdown:"硬い語。therefore と同じく結論を導く"},
     {synonym:true,word:"so",meaning:"だから",breakdown:"話し言葉で使う。therefore は書き言葉向き"}]},

  {id:397,word:"instead",partOfSpeech:"副詞",meaning:"代わりに",
   meanings:["副|代わりに","副|（instead of ～で）～の代わりに"],
   pronunciation:"/ɪnˈsted/",part:40,
   example:"The shop was closed, so we ate at home instead.",
   exampleJa:"店が閉まっていたので、私たちは代わりに家で食べた。",
   example2:"Instead of taking the bus, she walked to school today.",
   exampleJa2:"バスに乗る代わりに、彼女は今日学校まで歩いた。",
   etymologyProcess:"in（中に）＋ stead（場所）→ もとのものの場所にそのまま入ると…？",
   etymologyConclusion:"in（中に）＋ stead（場所）→ もとのものの場所にそのまま入る＝代わりに",
   relatedWords:[
     {word:"steady",meaning:"安定した",breakdown:"stead（場所）＋ y（〜な状態の）→ 場所から動かずしっかりする"},
     {word:"bedstead",meaning:"寝台の枠",breakdown:"bed（ベッド）＋ stead（場所）→ ベッドを置くための台"},
     {synonym:true,word:"rather",meaning:"むしろ",breakdown:"rather than と使う。instead は「その代わりに」"}]},

  {id:398,word:"until",partOfSpeech:"前置詞",meaning:"～まで",
   meanings:["前|（時）～まで（ずっと）","接|～するまで"],
   pronunciation:"/ənˈtɪl/",part:40,
   example:"We waited at the station until the rain finally stopped.",
   exampleJa:"雨がようやくやむまで、私たちは駅で待った。",
   example2:"The library stays open until eight every weekday evening.",
   exampleJa2:"図書館は平日の夕方、8時まで開いている。",
   etymologyProcess:"till（〜まで）→ ある時点に行き着くまでずっと続くと…？",
   etymologyConclusion:"till（〜まで）→ ある時点に行き着くまでずっと続く＝～まで",
   hook:"till はほぼ同じ意味。文の初めでは until が好まれる。",
   relatedWords:[
     {word:"till",meaning:"～まで",breakdown:"till（〜まで）→ until とほぼ同じ意味で使う短い語"},
     {synonym:true,word:"by",meaning:"～までに",breakdown:"期限の一点を指す。until は続くことを表す"},
     {synonym:true,word:"before",meaning:"～の前に",breakdown:"その時より前。until はその時まで続くこと"},
     {synonym:true,word:"while",meaning:"～する間",breakdown:"同時に進む期間。until は終わりの時点を示す"}]},

  {id:399,word:"besides",partOfSpeech:"前置詞",meaning:"～に加えて",
   meanings:["前|～に加えて","副|そのうえ"],
   pronunciation:"/bɪˈsaɪdz/",part:40,
   example:"Besides math, she is very good at English too.",
   exampleJa:"数学に加えて、彼女は英語もとても得意だ。",
   example2:"Many people besides our class joined the cleaning event.",
   exampleJa2:"私たちのクラスに加えて、多くの人が清掃活動に参加した。",
   etymologyProcess:"side（横）→ すでにあるものの横にもう一つ並べると…？",
   etymologyConclusion:"side（横）→ すでにあるものの横にもう一つ並べる＝～に加えて",
   hook:"besides は「加えて」、beside は「そばに」。s の有無で変わる。",
   relatedWords:[
     {word:"beside",meaning:"～のそばに",breakdown:"side（横）→ すぐ横の位置にあることを表す"},
     {word:"seaside",meaning:"海辺",breakdown:"sea（海）＋ side（横）→ 海のすぐ横にある場所"},
     {synonym:true,word:"moreover",meaning:"さらに",breakdown:"書き言葉で付け加える。besides は話し言葉にも使う"},
     {synonym:true,word:"except",meaning:"～を除いて",breakdown:"besides は加え、except は取り除く。逆の働き"}]},

  {id:400,word:"except",partOfSpeech:"前置詞",meaning:"～を除いて",
   meanings:["前|～を除いて","接|（except that SV）～という点を除いて"],
   pronunciation:"/ɪkˈsept/",part:40,
   example:"Everyone except Tom came to the club meeting yesterday.",
   exampleJa:"トムを除いて全員が、昨日の部活の集まりに来た。",
   example2:"The shop opens every day except Sunday and national holidays.",
   exampleJa2:"その店は、日曜と祝日を除いて毎日開いている。",
   etymologyProcess:"ex（外へ）＋ cept（取る）→ 全体の中から一つを外へ取り出すと…？",
   etymologyConclusion:"ex（外へ）＋ cept（取る）→ 全体の中から一つを外へ取り出す＝～を除いて",
   relatedWords:[
     {word:"accept",meaning:"受け入れる",breakdown:"ad（〜へ）＋ cept（取る）→ 自分のほうへ取り込む"},
     {word:"exception",meaning:"例外",breakdown:"ex（外へ）＋ cept（取る）＋ ion（名詞）→ 外へ取り出されたもの"},
     {word:"concept",meaning:"概念",breakdown:"com（共に）＋ cept（取る）→ いくつかをまとめて取り上げた考え"},
     {synonym:true,word:"but",meaning:"～を除いて",breakdown:"all but one のように使う。except と近い働き"}]},

  {id:401,word:"debate",partOfSpeech:"名詞",meaning:"討論",
   meanings:["名|（about / over ～）（～についての）討論","他|～を討論する"],
   pronunciation:"/dɪˈbeɪt/",part:41,
   example:"Our class held a debate about school uniforms yesterday.",
   exampleJa:"私たちのクラスは昨日、制服についての討論を行った。",
   example2:"The debate over the new law continued for many hours.",
   exampleJa2:"新しい法律をめぐる討論は、何時間も続いた。",
   etymologyProcess:"de（すっかり）＋ bat（打つ）→ 意見を正面からぶつけて打ち合うと…？",
   etymologyConclusion:"de（すっかり）＋ bat（打つ）→ 意見を正面からぶつけて打ち合うこと＝討論",
   relatedWords:[
     {word:"battle",meaning:"戦い",breakdown:"bat（打つ）→ 互いに打ち合ってぶつかること"},
     {word:"combat",meaning:"戦闘",breakdown:"com（共に）＋ bat（打つ）→ 向かい合って打ち合う"},
     {word:"batter",meaning:"打者",breakdown:"bat（打つ）＋ er（人）→ 何度も打つ人"},
     {synonym:true,word:"discussion",meaning:"話し合い",breakdown:"意見を出し合う。debate は賛成反対に分かれて争う"}]},

  {id:402,word:"criticize",partOfSpeech:"他動詞",meaning:"批判する",
   meanings:["他|～を批判する","他|～を批評する"],
   pronunciation:"/ˈkrɪtɪsaɪz/",part:41,
   example:"Many people criticized the plan to close the old library.",
   exampleJa:"多くの人が、古い図書館を閉鎖する計画を批判した。",
   example2:"Do not criticize others before you check the facts.",
   exampleJa2:"事実を確かめる前に、他人を批判してはいけない。",
   etymologyProcess:"crit（ふるい分ける）＋ ize（する）→ 良し悪しを分けて悪い点を言うと…？",
   etymologyConclusion:"crit（ふるい分ける）＋ ize（する）→ 良し悪しを分け、悪い点を言う＝批判する",
   relatedWords:[
     {word:"critic",meaning:"批評家",breakdown:"crit（ふるい分ける）→ 良し悪しを見分けて述べる人"},
     {word:"critical",meaning:"批判的な",breakdown:"crit（ふるい分ける）＋ al（〜の）→ 良し悪しを見分ける目を持つ"},
     {word:"crisis",meaning:"危機",breakdown:"crisis（分かれ目）→ 良し悪しがどちらに転ぶか分かれる時"},
     {synonym:true,word:"blame",meaning:"責める",breakdown:"責任があるとする。criticize は悪い点を指摘する"}]},

  {id:403,word:"accuse",partOfSpeech:"他動詞",meaning:"告発する",
   meanings:["他|（of ～）（～のことで）～を告発する，非難する"],
   pronunciation:"/əˈkjuːz/",part:41,
   example:"The police accused him of stealing the expensive bicycle.",
   exampleJa:"警察は、高価な自転車を盗んだとして彼を告発した。",
   example2:"She was accused of copying her friend's homework.",
   exampleJa2:"彼女は友人の宿題を写したとして告発された。",
   etymologyProcess:"ad（〜へ）＋ cus（原因）→ 責めの原因を相手に向けて突きつけると…？",
   etymologyConclusion:"ad（〜へ）＋ cus（原因）→ 責めの原因を相手に向けて突きつける＝告発する",
   relatedWords:[
     {word:"cause",meaning:"引き起こす",breakdown:"cus（原因）→ ものごとの始まりとなってあとを動かす"},
     {word:"excuse",meaning:"言い訳",breakdown:"ex（外へ）＋ cus（原因）→ 責めの原因を外へ取り除く"},
     {word:"because",meaning:"なぜなら",breakdown:"be（〜によって）＋ cus（原因）→ その原因によって、と示す"},
     {synonym:true,word:"blame",meaning:"責める",breakdown:"責任を負わせる。accuse は罪を正面から突きつける"}]},

  {id:404,word:"insist",partOfSpeech:"自動詞",meaning:"言い張る",
   meanings:["自|（on ～）（～を）言い張る","自|（that SV）～だと言い張る"],
   pronunciation:"/ɪnˈsɪst/",part:41,
   example:"She insists on walking to school even in heavy rain.",
   exampleJa:"彼女は大雨の中でさえ、学校まで歩くと言い張る。",
   example2:"He insisted that the answer on the board was wrong.",
   exampleJa2:"彼は、黒板の答えは間違っていると言い張った。",
   etymologyProcess:"in（上に）＋ sist（立つ）→ 自分の考えの上に立ち続けると…？",
   etymologyConclusion:"in（上に）＋ sist（立つ）→ 自分の考えの上に立ち続けて引かない＝言い張る",
   relatedWords:[
     {word:"exist",meaning:"存在する",breakdown:"ex（外へ）＋ sist（立つ）→ 外に姿を現して立っている"},
     {word:"resist",meaning:"抵抗する",breakdown:"re（後ろへ）＋ sist（立つ）→ 押し返すように立ちはだかる"},
     {word:"assist",meaning:"手伝う",breakdown:"ad（〜へ）＋ sist（立つ）→ そばに立って力を貸す"},
     {synonym:true,word:"claim",meaning:"主張する",breakdown:"当然のこととして述べる。insist は引かずに言い続ける"}]},

  {id:405,word:"object",partOfSpeech:"自動詞",meaning:"異議を唱える",
   meanings:["自|（to ～）（～に）異議を唱える，反対する","名|物体","名|目的"],
   pronunciation:"/əbˈdʒekt/",part:41,
   example:"Many parents objected to the new school rule strongly.",
   exampleJa:"多くの親が、新しい校則に強く異議を唱えた。",
   example2:"Nobody will object if we start the meeting early.",
   exampleJa2:"早く会議を始めても、だれも異議を唱えないだろう。",
   etymologyProcess:"ob（〜に向かって）＋ ject（投げる）→ 相手に向かって異を投げつけると…？",
   etymologyConclusion:"ob（〜に向かって）＋ ject（投げる）→ 相手に向かって異を投げつける＝異議を唱える",
   relatedWords:[
     {word:"project",meaning:"計画",breakdown:"pro（前へ）＋ ject（投げる）→ 先へ向けて投げ出す計画"},
     {word:"reject",meaning:"拒む",breakdown:"re（戻す）＋ ject（投げる）→ 受け取らずに投げ返す"},
     {word:"subject",meaning:"主題",breakdown:"sub（下で）＋ ject（投げる）→ 下に置かれて取り上げられるもの"},
     {synonym:true,word:"oppose",meaning:"反対する",breakdown:"正面から立ちはだかる。object は声に出して異を唱える"}]},

  {id:406,word:"protest",partOfSpeech:"自動詞",meaning:"抗議する",
   meanings:["自|（against ～）（～に）抗議する","名|抗議"],
   pronunciation:"/prəˈtest/",part:41,
   example:"Students protested against the sudden change in club rules.",
   exampleJa:"生徒たちは、部活の規則の突然の変更に抗議した。",
   example2:"Many citizens protest when taxes rise too quickly.",
   exampleJa2:"税金が急に上がりすぎると、多くの市民が抗議する。",
   etymologyProcess:"pro（人前で）＋ test（証言する）→ 人前ではっきり異議を述べると…？",
   etymologyConclusion:"pro（人前で）＋ test（証言する）→ 人前ではっきり異議を述べる＝抗議する",
   relatedWords:[
     {word:"testify",meaning:"証言する",breakdown:"test（証言する）＋ fy（する）→ 証人として事実を述べる"},
     {word:"contest",meaning:"競争",breakdown:"com（共に）＋ test（証言する）→ 互いに証人を立てて争う"},
     {synonym:true,word:"complain",meaning:"文句を言う",breakdown:"不満を述べる。protest は公に強く異を唱える"},
     {synonym:true,word:"object",meaning:"異議を唱える",breakdown:"反対を口にする。protest は行動を伴うことも多い"}]},

  {id:407,word:"controversial",partOfSpeech:"形容詞",meaning:"論争を招く",
   meanings:["形|論争を招く，賛否の分かれる"],
   pronunciation:"/ˌkɑːntrəˈvɜːrʃəl/",part:41,
   example:"The new plan became a controversial topic in our town.",
   exampleJa:"新しい計画は、私たちの町で論争を招く話題になった。",
   example2:"She wrote a controversial article about school uniforms.",
   exampleJa2:"彼女は制服について、論争を招く記事を書いた。",
   etymologyProcess:"contra（逆に）＋ vers（回る）→ 意見が逆を向いて回り出すと…？",
   etymologyConclusion:"contra（逆に）＋ vers（回る）→ 意見が逆を向いて回り、ぶつかり合う＝論争を招く",
   relatedWords:[
     {word:"controversy",meaning:"論争",breakdown:"contra（逆に）＋ vers（回る）→ 意見が逆を向いてぶつかること"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（戻す）＋ vers（回る）→ 向きを反対に回す"},
     {word:"convert",meaning:"変える",breakdown:"com（強く）＋ vers（回る）→ 向きを強く反対へ回す"},
     {synonym:true,word:"debatable",meaning:"議論の余地がある",breakdown:"賛否が分かれる。controversial はもっと強く争いになる"}]},

  {id:408,word:"bound",partOfSpeech:"形容詞",meaning:"きっと～する",
   meanings:["形|（to do）きっと～する，～する運命だ","形|（for ～）（～）行きの"],
   pronunciation:"/baʊnd/",part:41,
   example:"You are bound to feel nervous before your first speech.",
   exampleJa:"初めての演説の前は、きっと緊張するはずだ。",
   example2:"Prices are bound to rise again in the near future.",
   exampleJa2:"物価は近い将来、きっとまた上がるだろう。",
   etymologyProcess:"bind（縛る）→ そうなるように縛りつけられていると…？",
   etymologyConclusion:"bind（縛る）→ そうなるように縛りつけられて逃げられない＝きっと～する",
   hook:"be bound to do（きっと～する）。bind–bound–bound の過去分詞。",
   relatedWords:[
     {word:"bind",meaning:"縛る",breakdown:"bind（縛る）→ ひもでしっかり結びつける"},
     {word:"bond",meaning:"きずな",breakdown:"bind（縛る）→ 人と人を結びつけるもの"},
     {word:"bundle",meaning:"束",breakdown:"bind（縛る）→ まとめて縛った一つのかたまり"},
     {synonym:true,word:"certain",meaning:"確かな",breakdown:"be certain to do も同じ。bound は避けられない感じ"}]},

  {id:409,word:"bet",partOfSpeech:"他動詞・自動詞",meaning:"きっと～だと思う",
   meanings:["他|（that SV）きっと～だと思う","自|かけをする","名|かけ"],
   pronunciation:"/bet/",part:41,
   example:"I bet she will win the speech contest this year.",
   exampleJa:"彼女は今年、きっと弁論大会で優勝すると思う。",
   example2:"He bets that the rain will stop before noon today.",
   exampleJa2:"彼は、雨が正午前にきっとやむと思っている。",
   etymologyProcess:"bet（かけ金を置く）→ かけ金を置いてもよいほど確かだと思うと…？",
   etymologyConclusion:"bet（かけ金を置く）→ かけ金を置いてもよいほど確かだと思う＝きっと～だと思う",
   hook:"I bet (that) SV（きっと～だと思う）。You bet! は「もちろん」。",
   relatedWords:[
     {word:"betting",meaning:"かけ事",breakdown:"bet（かけ金を置く）＋ ing（名詞）→ かけ金を置く行い"},
     {synonym:true,word:"guess",meaning:"推測する",breakdown:"見当をつける。bet は自信をもって言い切る"},
     {synonym:true,word:"sure",meaning:"確信して",breakdown:"I'm sure と近い。bet はくだけた言い方"},
     {synonym:true,word:"wager",meaning:"かけ",breakdown:"かけ事を表す硬い語。bet は日常語"}]},

  {id:410,word:"demand",partOfSpeech:"他動詞",meaning:"要求する",
   meanings:["他|～を要求する","名|需要"],
   pronunciation:"/dɪˈmænd/",part:41,
   example:"The workers demanded better pay and shorter working hours.",
   exampleJa:"労働者たちは、より良い給料と短い労働時間を要求した。",
   example2:"Our teacher demands that we hand in reports on time.",
   exampleJa2:"先生は、報告書を期限どおりに提出することを要求する。",
   etymologyProcess:"de（すっかり）＋ mand（委ねる）→ すっかり委ねるよう強く求めると…？",
   etymologyConclusion:"de（すっかり）＋ mand（委ねる）→ 相手にすっかり委ねるよう強く求める＝要求する",
   relatedWords:[
     {word:"command",meaning:"命令する",breakdown:"com（強く）＋ mand（委ねる）→ 強く言いつけて委ねさせる"},
     {word:"mandatory",meaning:"義務的な",breakdown:"mand（委ねる）＋ ory（形容詞）→ 必ず従うよう言いつけられた"},
     {word:"recommend",meaning:"推薦する",breakdown:"re（再び）＋ mand（委ねる）→ 安心して委ねられると繰り返し勧める"},
     {synonym:true,word:"require",meaning:"必要とする",breakdown:"必要だから求める。demand は強く要求すること"}]},

  {id:411,word:"desire",partOfSpeech:"名詞",meaning:"願望",
   meanings:["名|（for ～ / to do）（～への）願望","他|～を強く望む"],
   pronunciation:"/dɪˈzaɪər/",part:42,
   example:"She had a strong desire to study abroad someday.",
   exampleJa:"彼女にはいつか留学したいという強い願望があった。",
   example2:"His desire for fame changed him into a different person.",
   exampleJa2:"名声への彼の願望は、彼を別人に変えた。",
   etymologyProcess:"de（離して）＋ sider（星）→ 星を見上げて届かぬものを求めると…？",
   etymologyConclusion:"de（離して）＋ sider（星）→ 星を見上げ、手の届かぬものを求める気持ち＝願望",
   relatedWords:[
     {word:"consider",meaning:"熟考する",breakdown:"com（共に）＋ sider（星）→ 星をよく見比べて先を占う"},
     {word:"desirable",meaning:"望ましい",breakdown:"de（離して）＋ sider（星）→ 心から求めたくなる"},
     {synonym:true,word:"wish",meaning:"願い",breakdown:"軽い願い。desire は強く心から求める気持ち"},
     {synonym:true,word:"ambition",meaning:"野心",breakdown:"高い地位への願い。desire は広く求める気持ち"}]},

  {id:412,word:"praise",partOfSpeech:"他動詞",meaning:"褒める",
   meanings:["他|（for ～）（～のことで）～を褒める","名|称賛"],
   pronunciation:"/preɪz/",part:42,
   example:"The coach praised the team for their hard work.",
   exampleJa:"監督はチームをその努力について褒めた。",
   example2:"Teachers often praise students who help their classmates.",
   exampleJa2:"先生は、級友を助ける生徒をよく褒める。",
   etymologyProcess:"preci（値打ち）→ 相手の値打ちを高く言い表すと…？",
   etymologyConclusion:"preci（値打ち）→ 相手の値打ちを高く見て言い表す＝褒める",
   relatedWords:[
     {word:"price",meaning:"値段",breakdown:"preci（値打ち）→ ものに付けられた値打ちの数字"},
     {word:"precious",meaning:"貴重な",breakdown:"preci（値打ち）＋ ous（形容詞）→ 値打ちに満ちている"},
     {word:"prize",meaning:"賞",breakdown:"preci（値打ち）→ 値打ちを認めて与えられるもの"},
     {synonym:true,word:"admire",meaning:"称賛する",breakdown:"心から感心する。praise は言葉にして褒める"}]},

  {id:413,word:"honor",partOfSpeech:"名詞",meaning:"名誉",
   meanings:["名|名誉，光栄","他|～に栄誉を与える"],
   pronunciation:"/ˈɑːnər/",part:42,
   example:"It is a great honor to speak at this ceremony.",
   exampleJa:"この式典で話すことは、大きな名誉です。",
   example2:"The soldier received the highest honor from his country.",
   exampleJa2:"その兵士は、国から最高の名誉を受けた。",
   etymologyProcess:"hon（誇り・敬い）＋ or（もの）→ 人から高く敬われて受けるものは…？",
   etymologyConclusion:"hon（誇り・敬い）＋ or（もの）→ 人から高く敬われて受けるもの＝名誉",
   relatedWords:[
     {word:"honest",meaning:"正直な",breakdown:"hon（誇り・敬い）→ 敬われるにふさわしく偽りがない"},
     {word:"honesty",meaning:"正直さ",breakdown:"hon（誇り・敬い）＋ ty（名詞）→ 偽りのない心"},
     {word:"honorable",meaning:"立派な",breakdown:"hon（誇り・敬い）＋ able（できる）→ 敬われるに値する"},
     {synonym:true,word:"pride",meaning:"誇り",breakdown:"自分で誇る気持ち。honor は人から受ける敬い"}]},

  {id:414,word:"chat",partOfSpeech:"自動詞",meaning:"おしゃべりする",
   meanings:["自|（with ～）（～と）おしゃべりする","名|おしゃべり"],
   pronunciation:"/tʃæt/",part:42,
   example:"She often chats with her neighbors near the front gate.",
   exampleJa:"彼女はよく正門の近くで、近所の人とおしゃべりする。",
   example2:"We chatted about the summer festival during the lunch break.",
   exampleJa2:"私たちは昼休みの間、夏祭りについておしゃべりした。",
   etymologyProcess:"chat（ぺちゃくちゃ）→ 軽い調子で気楽に言葉を交わすと…？",
   etymologyConclusion:"chat（ぺちゃくちゃ）→ 軽い調子で気楽に言葉を交わす＝おしゃべりする",
   hook:"chat with ～（～とおしゃべりする）。ネットの「チャット」と同語。",
   relatedWords:[
     {word:"chatter",meaning:"ぺちゃくちゃ話す",breakdown:"chat（ぺちゃくちゃ）＋ er（何度も）→ 休まず話し続ける"},
     {synonym:true,word:"talk",meaning:"話す",breakdown:"話すこと全般。chat は軽い雑談のこと"},
     {synonym:true,word:"gossip",meaning:"うわさ話",breakdown:"人のうわさをする。chat は話題を選ばない雑談"},
     {synonym:true,word:"converse",meaning:"会話する",breakdown:"改まった言い方。chat はくだけた言い方"}]},

  {id:415,word:"refer",partOfSpeech:"自動詞",meaning:"言及する",
   meanings:["自|（to ～）（～に）言及する","自|（to ～）（～を）参照する"],
   pronunciation:"/rɪˈfɜːr/",part:42,
   example:"She never refers to her own mistakes in public.",
   exampleJa:"彼女は人前で、自分の失敗に言及することはない。",
   example2:"The teacher referred to a famous novel during the class.",
   exampleJa2:"先生は授業中に、有名な小説に言及した。",
   etymologyProcess:"re（戻す）＋ fer（運ぶ）→ 話をそこへ運び戻して取り上げると…？",
   etymologyConclusion:"re（戻す）＋ fer（運ぶ）→ 話をそこへ運び戻して取り上げる＝言及する",
   relatedWords:[
     {word:"prefer",meaning:"より好む",breakdown:"pre（先に）＋ fer（運ぶ）→ 一方を先へ運び出して選ぶ"},
     {word:"transfer",meaning:"移す",breakdown:"trans（越えて）＋ fer（運ぶ）→ 境を越えて別の場所へ運ぶ"},
     {word:"reference",meaning:"参照",breakdown:"re（戻す）＋ fer（運ぶ）＋ ence（名詞）→ 戻って調べるもと"},
     {synonym:true,word:"mention",meaning:"述べる",breakdown:"直接目的語をとる。refer は to を使って指し示す"}]},

  {id:416,word:"mention",partOfSpeech:"他動詞",meaning:"（ついでに）述べる",
   meanings:["他|～を（ついでに）述べる，～に言及する"],
   pronunciation:"/ˈmenʃən/",part:42,
   example:"She mentioned the new club at the morning meeting.",
   exampleJa:"彼女は朝の集まりで、新しい部活のことに言及した。",
   example2:"Nobody mentions the old story in this village now.",
   exampleJa2:"今この村では、だれもその古い話に言及しない。",
   etymologyProcess:"mens（心）＋ ion（名詞）→ 心にあることを短く口に出すと…？",
   etymologyConclusion:"mens（心）＋ ion（名詞）→ 心にあることを短く口に出す＝（ついでに）述べる",
   relatedWords:[
     {word:"mental",meaning:"精神の",breakdown:"mens（心）＋ al（〜の）→ 心のはたらきにかかわる"},
     {word:"comment",meaning:"論評",breakdown:"com（共に）＋ mens（心）→ 心に浮かんだことを言い添える"},
     {synonym:true,word:"refer",meaning:"言及する",breakdown:"refer to の形で指す。mention は目的語を直接とる"},
     {synonym:true,word:"state",meaning:"述べる",breakdown:"はっきり述べる。mention は軽く触れる程度"}]},

  {id:417,word:"convey",partOfSpeech:"他動詞",meaning:"伝える",
   meanings:["他|（考え・気持ち）を伝える","他|～を運ぶ"],
   pronunciation:"/kənˈveɪ/",part:42,
   example:"Words alone cannot convey how grateful I feel today.",
   exampleJa:"言葉だけでは、今日どれほど感謝しているか伝えられない。",
   example2:"The letter conveyed her true feelings to her old friend.",
   exampleJa2:"その手紙は、彼女の本当の気持ちを古い友人に伝えた。",
   etymologyProcess:"com（共に）＋ via（道）→ 道を通って相手のもとまで運んでいくと…？",
   etymologyConclusion:"com（共に）＋ via（道）→ 道を通って相手のもとまで運んでいく＝伝える",
   relatedWords:[
     {word:"convoy",meaning:"護送隊",breakdown:"com（共に）＋ via（道）→ 同じ道を連れ立って行く一団"},
     {word:"previous",meaning:"以前の",breakdown:"pre（先に）＋ via（道）→ 先に道を行っている"},
     {word:"obvious",meaning:"明らかな",breakdown:"ob（〜に向かって）＋ via（道）→ 道の前にあって目につく"},
     {synonym:true,word:"deliver",meaning:"届ける",breakdown:"物を届ける。convey は考えや気持ちも運ぶ"}]},

  {id:418,word:"demonstrate",partOfSpeech:"他動詞",meaning:"はっきり示す",
   meanings:["他|～をはっきり示す","他|～を実演する"],
   pronunciation:"/ˈdemənstreɪt/",part:42,
   example:"The scientist demonstrated the danger of the new chemical.",
   exampleJa:"その科学者は、新しい化学物質の危険性をはっきり示した。",
   example2:"These results demonstrate that regular sleep improves memory.",
   exampleJa2:"これらの結果は、規則的な睡眠が記憶を高めることをはっきり示している。",
   etymologyProcess:"de（すっかり）＋ monstr（示す）→ 目の前ですっかり示してみせると…？",
   etymologyConclusion:"de（すっかり）＋ monstr（示す）→ 目の前ですっかり示してみせる＝はっきり示す",
   relatedWords:[
     {word:"monster",meaning:"怪物",breakdown:"monstr（示す）→ 不吉な前ぶれを示すものとされた姿"},
     {word:"demonstration",meaning:"実演",breakdown:"de（すっかり）＋ monstr（示す）＋ ion（名詞）→ はっきり示すこと"},
     {synonym:true,word:"prove",meaning:"証明する",breakdown:"正しいと示す。demonstrate は実際にやって見せる"},
     {synonym:true,word:"show",meaning:"見せる",breakdown:"見せること全般。demonstrate ははっきり示すこと"}]},

  {id:419,word:"emphasize",partOfSpeech:"他動詞",meaning:"強調する",
   meanings:["他|～を強調する"],
   pronunciation:"/ˈemfəsaɪz/",part:42,
   example:"The teacher emphasized the importance of daily review.",
   exampleJa:"先生は毎日の復習の大切さを強調した。",
   example2:"She always emphasizes that honesty matters more than speed.",
   exampleJa2:"彼女はいつも、正直さが速さより大切だと強調する。",
   etymologyProcess:"en（中に）＋ phas（見せる）→ 中身をくっきり見せて目立たせると…？",
   etymologyConclusion:"en（中に）＋ phas（見せる）→ 中身をくっきり見せて目立たせる＝強調する",
   relatedWords:[
     {word:"emphasis",meaning:"強調",breakdown:"en（中に）＋ phas（見せる）→ とくに目立たせている部分"},
     {word:"phase",meaning:"段階",breakdown:"phas（見せる）→ 月が見せる形の移り変わり"},
     {synonym:true,word:"stress",meaning:"力を入れて言う",breakdown:"emphasize とほぼ同じ使い方ができる"},
     {synonym:true,word:"highlight",meaning:"目立たせる",breakdown:"明るく照らして目立たせる。emphasize は言葉で強める"}]},

  {id:420,word:"exaggerate",partOfSpeech:"他動詞",meaning:"誇張する",
   meanings:["他|～を誇張する，大げさに言う"],
   pronunciation:"/ɪɡˈzædʒəreɪt/",part:42,
   example:"He tends to exaggerate the size of the fish.",
   exampleJa:"彼は魚の大きさを誇張する傾向がある。",
   example2:"Newspapers sometimes exaggerated the danger of the small storm.",
   exampleJa2:"新聞はときに、その小さな嵐の危険を誇張した。",
   etymologyProcess:"ex（外へ）＋ agger（積み上げる）→ 土を外へどんどん高く積み上げると…？",
   etymologyConclusion:"ex（外へ）＋ agger（積み上げる）→ 土を外へ高く積み上げて大きく見せる＝誇張する",
   relatedWords:[
     {word:"exaggeration",meaning:"誇張",breakdown:"ex（外へ）＋ agger（積み上げる）＋ ion（名詞）→ 大げさに盛ること"},
     {synonym:true,word:"overstate",meaning:"大げさに言う",breakdown:"言いすぎること。exaggerate と同じ働きをする"},
     {synonym:true,word:"boast",meaning:"自慢する",breakdown:"自分を大きく見せる。exaggerate は話を大きくする"},
     {synonym:true,word:"stretch",meaning:"引き伸ばす",breakdown:"stretch the truth で「話を盛る」。exaggerate と近い"}]},

  {id:421,word:"reply",partOfSpeech:"自動詞",meaning:"返事をする",
   meanings:["自|（to ～）（～に）返事をする","名|返事"],
   pronunciation:"/rɪˈplaɪ/",part:43,
   example:"Please reply to this message before Friday afternoon.",
   exampleJa:"金曜の午後までに、このメッセージに返事をしてください。",
   example2:"She replied to my email within a few minutes.",
   exampleJa2:"彼女は数分以内に、私のメールに返事をした。",
   etymologyProcess:"re（戻す）＋ pli（折る）→ 相手の言葉を折り返して戻すと…？",
   etymologyConclusion:"re（戻す）＋ pli（折る）→ 相手の言葉を折り返して戻す＝返事をする",
   relatedWords:[
     {word:"display",meaning:"展示する",breakdown:"dis（バラバラに）＋ pli（折る）→ たたんだ布を広げて見せる"},
     {word:"apply",meaning:"申し込む",breakdown:"ad（〜へ）＋ pli（折る）→ 願いを折りたたんで差し出す"},
     {word:"multiply",meaning:"掛ける",breakdown:"multi（多く）＋ pli（折る）→ 何重にも折り重ねて増やす"},
     {synonym:true,word:"answer",meaning:"答える",breakdown:"問いに答える。reply は受け取った言葉に返すこと"}]},

  {id:422,word:"respond",partOfSpeech:"自動詞",meaning:"返答する",
   meanings:["自|（to ～）（～に）返答する","自|（to ～）（～に）反応する"],
   pronunciation:"/rɪˈspɑːnd/",part:43,
   example:"She responds to every letter from her former students.",
   exampleJa:"彼女は教え子からのすべての手紙に返答する。",
   example2:"He responded to the difficult question with a smile.",
   exampleJa2:"彼はその難しい質問に、笑顔で返答した。",
   etymologyProcess:"re（戻す）＋ spond（誓う）→ 相手の言葉に対して誓い返すと…？",
   etymologyConclusion:"re（戻す）＋ spond（誓う）→ 相手の言葉に対して誓い返す＝返答する",
   relatedWords:[
     {word:"response",meaning:"返答",breakdown:"re（戻す）＋ spond（誓う）→ 返ってきた答えそのもの"},
     {word:"responsible",meaning:"責任がある",breakdown:"re（戻す）＋ spond（誓う）→ 問われたら答える立場にある"},
     {word:"correspond",meaning:"一致する",breakdown:"com（共に）＋ spond（誓う）→ 互いに答え合って合う"},
     {synonym:true,word:"reply",meaning:"返事をする",breakdown:"言葉を返す。respond は行動での反応も含む"}]},

  {id:423,word:"whisper",partOfSpeech:"自動詞",meaning:"ささやく",
   meanings:["自|ささやく","他|～をささやく"],
   pronunciation:"/ˈwɪspər/",part:43,
   example:"She whispered the answer into her friend's ear quietly.",
   exampleJa:"彼女は友人の耳に、静かに答えをささやいた。",
   example2:"Do not whisper during the important school ceremony.",
   exampleJa2:"大切な学校の式の間、ささやいてはいけない。",
   etymologyProcess:"whisper（かすれた息の音）→ 息だけの小さな声で話すと…？",
   etymologyConclusion:"whisper（かすれた息の音）→ 息だけの小さな声で話す＝ささやく",
   hook:"息の音をまねた語。whisper to ～ で「～にささやく」。",
   relatedWords:[
     {word:"whispering",meaning:"ささやき",breakdown:"whisper（かすれた息の音）＋ ing（名詞）→ 小声で話すこと"},
     {synonym:true,word:"murmur",meaning:"つぶやく",breakdown:"低くつぶやく。whisper は息だけの小声"},
     {synonym:true,word:"shout",meaning:"叫ぶ",breakdown:"大声を出す。whisper はちょうどその反対"},
     {synonym:true,word:"mutter",meaning:"ぶつぶつ言う",breakdown:"不満を低い声で。whisper は秘密を伝えるとき"}]},

  {id:424,word:"remark",partOfSpeech:"名詞",meaning:"発言",
   meanings:["名|（about ～）（～についての）発言","他|～と述べる"],
   pronunciation:"/rɪˈmɑːrk/",part:43,
   example:"His remark about the plan surprised everyone in the room.",
   exampleJa:"計画についての彼の発言は、部屋の全員を驚かせた。",
   example2:"She made a kind remark about my English speech.",
   exampleJa2:"彼女は私の英語のスピーチについて、優しい発言をした。",
   etymologyProcess:"re（強く）＋ mark（しるし）→ 心にしるしを付けて言葉にすると…？",
   etymologyConclusion:"re（強く）＋ mark（しるし）→ 心にしるしを付けて述べた一言＝発言",
   relatedWords:[
     {word:"mark",meaning:"しるし",breakdown:"mark（しるし）→ 目に留まるように付けた印"},
     {word:"remarkable",meaning:"目を引く",breakdown:"re（強く）＋ mark（しるし）＋ able（できる）→ 心にしるしが残る"},
     {word:"bookmark",meaning:"しおり",breakdown:"book（本）＋ mark（しるし）→ 本に付けておく目印"},
     {synonym:true,word:"comment",meaning:"論評",breakdown:"意見を述べること。remark は短い一言の発言"}]},

  {id:425,word:"observe",partOfSpeech:"他動詞",meaning:"観察する",
   meanings:["他|～を観察する","他|（規則）を守る"],
   pronunciation:"/əbˈzɜːrv/",part:43,
   example:"Students observed the moon through a large school telescope.",
   exampleJa:"生徒たちは、学校の大きな望遠鏡で月を観察した。",
   example2:"We observe the plants in the garden every morning.",
   exampleJa2:"私たちは毎朝、庭の植物を観察する。",
   etymologyProcess:"ob（〜に向かって）＋ serv（守る）→ 目を向けてじっと見守り続けると…？",
   etymologyConclusion:"ob（〜に向かって）＋ serv（守る）→ 目を向けてじっと見守り続ける＝観察する",
   relatedWords:[
     {word:"preserve",meaning:"保存する",breakdown:"pre（先に）＋ serv（守る）→ 先を見こして守り取っておく"},
     {word:"reserve",meaning:"予約する",breakdown:"re（後ろへ）＋ serv（守る）→ 後のために取り置いて守る"},
     {word:"observation",meaning:"観察",breakdown:"ob（〜に向かって）＋ serv（守る）＋ ion（名詞）→ じっと見守ること"},
     {synonym:true,word:"watch",meaning:"見守る",breakdown:"動くものを見る。observe は調べるように見る"}]},

  {id:426,word:"theory",partOfSpeech:"名詞",meaning:"理論",
   meanings:["名|理論，学説","名|（in theory で）理論上は"],
   pronunciation:"/ˈθiːəri/",part:43,
   example:"His theory about the disease was proved many years later.",
   exampleJa:"その病気についての彼の理論は、何年もあとに証明された。",
   example2:"In theory, this plan works well for every student.",
   exampleJa2:"理論上は、この計画はすべての生徒にうまくいく。",
   etymologyProcess:"theor（じっと見る）＋ y（名詞）→ 物事をじっと見つめて組み立てた考えは…？",
   etymologyConclusion:"theor（じっと見る）＋ y（名詞）→ 物事をじっと見つめて組み立てた考え＝理論",
   relatedWords:[
     {word:"theoretical",meaning:"理論上の",breakdown:"theor（じっと見る）＋ al（〜の）→ 頭の中の考えの上での"},
     {word:"theater",meaning:"劇場",breakdown:"theor（じっと見る）→ 人々がじっと見つめるための場所"},
     {synonym:true,word:"hypothesis",meaning:"仮説",breakdown:"確かめる前の仮の考え。theory は裏づけのある説明"},
     {synonym:true,word:"practice",meaning:"実践",breakdown:"実際に行うこと。theory は頭の中の組み立て"}]},

  {id:427,word:"analysis",partOfSpeech:"名詞",meaning:"分析",
   meanings:["名|（of ～）（～の）分析"],
   pronunciation:"/əˈnæləsɪs/",part:43,
   example:"Her analysis of the data changed our whole plan.",
   exampleJa:"彼女のデータの分析は、私たちの計画全体を変えた。",
   example2:"Careful analysis shows that the problem started much earlier.",
   exampleJa2:"注意深い分析は、問題がもっと早く始まっていたことを示す。",
   etymologyProcess:"ana（すっかり）＋ lys（ほどく）→ 絡んだものをすっかりほどいて調べると…？",
   etymologyConclusion:"ana（すっかり）＋ lys（ほどく）→ 絡んだものをすっかりほどいて調べること＝分析",
   relatedWords:[
     {word:"analyze",meaning:"分析する",breakdown:"ana（すっかり）＋ lys（ほどく）＋ ize（する）→ ほどいて調べる"},
     {word:"paralysis",meaning:"麻痺",breakdown:"para（そばで）＋ lys（ほどく）→ 体の働きがほどけて緩む"},
     {synonym:true,word:"solution",meaning:"解決",breakdown:"もつれを解いて答えを出すこと。analysis は分けて調べること"},
     {synonym:true,word:"study",meaning:"研究",breakdown:"調べること全般。analysis は細かく分けて調べること"}]},

  {id:428,word:"phenomenon",partOfSpeech:"名詞",meaning:"現象",
   meanings:["名|現象"],
   pronunciation:"/fəˈnɑːmɪnɑːn/",part:43,
   example:"This strange weather phenomenon happens only in winter here.",
   exampleJa:"この奇妙な気象現象は、ここでは冬にだけ起きる。",
   example2:"Scientists cannot explain the phenomenon in simple words.",
   exampleJa2:"科学者たちは、その現象を簡単な言葉で説明できない。",
   etymologyProcess:"phas（見せる）→ 目の前に姿を見せて起きるできごとは…？",
   etymologyConclusion:"phas（見せる）→ 目の前に姿を見せて起きるできごと＝現象",
   hook:"複数形は phenomena。単数と形が大きく変わるので注意。",
   relatedWords:[
     {word:"phenomenal",meaning:"驚くべき",breakdown:"phas（見せる）＋ al（〜の）→ 目を見張る姿を見せる"},
     {word:"emphasize",meaning:"強調する",breakdown:"en（中に）＋ phas（見せる）→ 中身をくっきり見せる"},
     {word:"phase",meaning:"段階",breakdown:"phas（見せる）→ 月が見せる形の移り変わり"},
     {synonym:true,word:"event",meaning:"出来事",breakdown:"起きたことがら。phenomenon は観察される現象"}]},

  {id:429,word:"device",partOfSpeech:"名詞",meaning:"装置",
   meanings:["名|装置，機器","名|工夫"],
   pronunciation:"/dɪˈvaɪs/",part:43,
   example:"This small device measures the temperature of the room.",
   exampleJa:"この小さな装置は、部屋の温度を測る。",
   example2:"Mobile devices have changed the way we study English.",
   exampleJa2:"携帯用の装置は、私たちが英語を学ぶ方法を変えた。",
   etymologyProcess:"de（離して）＋ vis（分ける）→ 仕事を切り分けて工夫した仕掛けは…？",
   etymologyConclusion:"de（離して）＋ vis（分ける）→ 仕事を切り分け、工夫して作った仕掛け＝装置",
   relatedWords:[
     {word:"divide",meaning:"分ける",breakdown:"di（離れて）＋ vis（分ける）→ 一つのものを切り離して二つにする"},
     {word:"division",meaning:"分割",breakdown:"di（離れて）＋ vis（分ける）＋ ion（名詞）→ 分けられた一つひとつ"},
     {word:"individual",meaning:"個人",breakdown:"in（否定）＋ vis（分ける）→ これ以上分けられないもの"},
     {synonym:true,word:"machine",meaning:"機械",breakdown:"大きな仕掛け。device は小さな道具や装置"}]},

  {id:430,word:"experiment",partOfSpeech:"名詞",meaning:"実験",
   meanings:["名|実験","自|（on ～）（～で）実験する"],
   pronunciation:"/ɪkˈsperɪmənt/",part:43,
   example:"The science experiment showed a surprising result today.",
   exampleJa:"その理科の実験は、今日驚くべき結果を示した。",
   example2:"We did an experiment with salt water in class.",
   exampleJa2:"私たちは授業で、塩水を使った実験を行った。",
   etymologyProcess:"ex（外へ）＋ peri（試す）→ 外へ出して実際に試してみると…？",
   etymologyConclusion:"ex（外へ）＋ peri（試す）→ 外へ出して実際に試してみること＝実験",
   relatedWords:[
     {word:"experience",meaning:"経験",breakdown:"ex（外へ）＋ peri（試す）＋ ence（名詞）→ 試して身についたもの"},
     {word:"expert",meaning:"熟練者",breakdown:"ex（外へ）＋ peri（試す）→ 何度も試して身につけた人"},
     {word:"peril",meaning:"危険",breakdown:"peri（試す）→ 身を試されるような危うい場面"},
     {synonym:true,word:"test",meaning:"検査",breakdown:"調べること。experiment は仮説を確かめる実験"}]},

  {id:431,word:"chemical",partOfSpeech:"名詞",meaning:"化学物質",
   meanings:["名|化学物質，薬品","形|化学の"],
   pronunciation:"/ˈkemɪkəl/",part:44,
   example:"This factory uses a dangerous chemical every single day.",
   exampleJa:"この工場は、危険な化学物質を毎日使っている。",
   example2:"Chemicals in the river killed many small fish.",
   exampleJa2:"川の中の化学物質が、多くの小さな魚を死なせた。",
   etymologyProcess:"chem（金属を溶かす術）＋ al（〜の）→ 金属を溶かす古い術が扱うものは…？",
   etymologyConclusion:"chem（金属を溶かす術）＋ al（〜の）→ 金属を溶かす古い術から生まれた物質＝化学物質",
   relatedWords:[
     {word:"chemistry",meaning:"化学",breakdown:"chem（金属を溶かす術）＋ ry（もの）→ 物質の変化を調べる学問"},
     {word:"chemist",meaning:"化学者",breakdown:"chem（金属を溶かす術）＋ ist（人）→ 物質の変化を調べる人"},
     {word:"alchemy",meaning:"錬金術",breakdown:"chem（金属を溶かす術）→ 卑金属を金に変えようとした古い術"},
     {synonym:true,word:"substance",meaning:"物質",breakdown:"ものの中身。chemical は化学的に作られた物質"}]},

  {id:432,word:"fuel",partOfSpeech:"名詞",meaning:"燃料",
   meanings:["名|燃料","他|～をあおる"],
   pronunciation:"/ˈfjuːəl/",part:44,
   example:"The old ship needs a lot of fuel every day.",
   exampleJa:"その古い船は、毎日たくさんの燃料を必要とする。",
   example2:"Wood was the main fuel in this village long ago.",
   exampleJa2:"昔この村では、木が主な燃料だった。",
   etymologyProcess:"focus（いろり・火）→ いろりにくべて燃やすものは…？",
   etymologyConclusion:"focus（いろり・火）→ いろりにくべて火を保たせるもの＝燃料",
   relatedWords:[
     {word:"focus",meaning:"焦点",breakdown:"focus（いろり・火）→ 光が集まって燃え立つ一点"},
     {word:"refuel",meaning:"燃料を補給する",breakdown:"re（再び）＋ focus（いろり・火）→ もう一度燃料を入れる"},
     {synonym:true,word:"gasoline",meaning:"ガソリン",breakdown:"車を走らせる燃料の一つ。fuel はその総称"},
     {synonym:true,word:"energy",meaning:"エネルギー",breakdown:"働きを生む力。fuel はその元になる燃えるもの"}]},

  {id:433,word:"nuclear",partOfSpeech:"形容詞",meaning:"原子力の",
   meanings:["形|原子力の，核の"],
   pronunciation:"/ˈnuːkliər/",part:44,
   example:"Many countries still depend on nuclear power for electricity.",
   exampleJa:"多くの国が、電気のためにいまだ原子力の発電に頼っている。",
   example2:"The nuclear plant near the coast was closed last year.",
   exampleJa2:"海岸近くの原子力の発電所は、昨年閉鎖された。",
   etymologyProcess:"nucle（木の実の核）＋ ar（〜の）→ ものの中心にある核にかかわると…？",
   etymologyConclusion:"nucle（木の実の核）＋ ar（〜の）→ ものの中心にある核にかかわる＝原子力の",
   relatedWords:[
     {word:"nucleus",meaning:"核",breakdown:"nucle（木の実の核）→ ものの中心にある小さなかたまり"},
     {synonym:true,word:"nut",meaning:"木の実",breakdown:"nuclear の元になった「木の実の核」のイメージが残る語"},
     {synonym:true,word:"atomic",meaning:"原子の",breakdown:"原子にかかわる。nuclear は原子核にかかわる"},
     {synonym:true,word:"radiation",meaning:"放射線",breakdown:"核から出る線。nuclear はその核にかかわる語"}]},

  {id:434,word:"statistics",partOfSpeech:"名詞",meaning:"統計",
   meanings:["名|統計，統計資料","名|統計学"],
   pronunciation:"/stəˈtɪstɪks/",part:44,
   example:"Recent statistics show that young people read fewer books.",
   exampleJa:"最近の統計は、若者が読む本が減っていることを示している。",
   example2:"He studied statistics to understand the survey results better.",
   exampleJa2:"彼は調査結果をよりよく理解するため、統計を学んだ。",
   etymologyProcess:"sta（立つ）＋ ics（学問）→ 国の成り立ちを数で表してみると…？",
   etymologyConclusion:"sta（立つ）＋ ics（学問）→ 国の成り立ちを数で表したもの＝統計",
   relatedWords:[
     {word:"state",meaning:"国家",breakdown:"sta（立つ）→ しっかり立っている一つのまとまり"},
     {word:"station",meaning:"駅",breakdown:"sta（立つ）＋ ion（名詞）→ 乗り物が立ち止まる場所"},
     {word:"statue",meaning:"像",breakdown:"sta（立つ）→ 立てて置かれた人の姿のかたち"},
     {synonym:true,word:"data",meaning:"データ",breakdown:"集めた数値そのもの。statistics はそれをまとめた統計"}]},

  {id:435,word:"pursue",partOfSpeech:"他動詞",meaning:"追い求める",
   meanings:["他|（目標など）を追い求める","他|～を追跡する"],
   pronunciation:"/pərˈsuː/",part:44,
   example:"She decided to pursue a career in medical science.",
   exampleJa:"彼女は医学の分野での仕事を追い求めることに決めた。",
   example2:"They pursued their dream of winning the national tournament.",
   exampleJa2:"彼らは全国大会で優勝するという夢を追い求めた。",
   etymologyProcess:"pur（前へ）＋ sue（追う）→ 前へ前へと追いかけ続けると…？",
   etymologyConclusion:"pur（前へ）＋ sue（追う）→ 前へ前へと追いかけ続ける＝追い求める",
   relatedWords:[
     {word:"pursuit",meaning:"追求",breakdown:"pur（前へ）＋ sue（追う）→ 追い求めることそのもの"},
     {word:"sue",meaning:"訴える",breakdown:"sue（追う）→ 法によって相手を追いかけ責任を求める"},
     {word:"suit",meaning:"訴訟",breakdown:"sue（追う）→ 相手を追いかけて裁きを求める手続き"},
     {synonym:true,word:"chase",meaning:"追いかける",breakdown:"走って追う。pursue は目標を長く追い続ける"}]},

  {id:436,word:"accomplish",partOfSpeech:"他動詞",meaning:"やり遂げる",
   meanings:["他|～をやり遂げる，成し遂げる"],
   pronunciation:"/əˈkɑːmplɪʃ/",part:44,
   example:"She accomplished her goal of running a full marathon.",
   exampleJa:"彼女はフルマラソンを走るという目標をやり遂げた。",
   example2:"We cannot accomplish this task without everyone's help.",
   exampleJa2:"みんなの助けなしには、私たちはこの仕事をやり遂げられない。",
   etymologyProcess:"ad（〜へ）＋ com（すっかり）＋ ple（満たす）→ 最後まで満たしきると…？",
   etymologyConclusion:"ad（〜へ）＋ com（すっかり）＋ ple（満たす）→ 最後まで満たしきる＝やり遂げる",
   relatedWords:[
     {word:"complete",meaning:"完全な",breakdown:"com（すっかり）＋ ple（満たす）→ 欠けなくすっかり満たされる"},
     {word:"accomplishment",meaning:"業績",breakdown:"ad（〜へ）＋ com（すっかり）＋ ple（満たす）→ やり遂げた中身"},
     {word:"supplement",meaning:"補うもの",breakdown:"sub（下で）＋ ple（満たす）→ 下から足して満たすもの"},
     {synonym:true,word:"achieve",meaning:"達成する",breakdown:"目標に届く。accomplish は最後までやり切ること"}]},

  {id:437,word:"overcome",partOfSpeech:"他動詞",meaning:"克服する",
   meanings:["他|（困難など）を克服する，乗り越える"],
   pronunciation:"/ˌoʊvərˈkʌm/",part:44,
   example:"Many students overcome test anxiety with careful daily preparation.",
   exampleJa:"多くの生徒は、毎日の入念な準備でテストの不安を克服する。",
   example2:"He overcame his fear of speaking in front of others.",
   exampleJa2:"彼は人前で話すことへの恐れを克服した。",
   etymologyProcess:"over（越えて）＋ come（来る）→ 困難の上を越えて向こうへ出ると…？",
   etymologyConclusion:"over（越えて）＋ come（来る）→ 困難の上を越えて向こう側へ出る＝克服する",
   relatedWords:[
     {word:"income",meaning:"収入",breakdown:"in（中へ）＋ come（来る）→ 自分のもとへ入ってくるもの"},
     {word:"outcome",meaning:"結果",breakdown:"out（外へ）＋ come（来る）→ 最後に外へ出てきたもの"},
     {word:"overflow",meaning:"あふれる",breakdown:"over（越えて）＋ flow（流れる）→ 縁を越えて流れ出る"},
     {synonym:true,word:"conquer",meaning:"征服する",breakdown:"力で打ち勝つ。overcome は困難を乗り越えること"}]},

  {id:438,word:"fulfill",partOfSpeech:"他動詞",meaning:"果たす",
   meanings:["他|（約束・義務）を果たす","他|（望み）をかなえる"],
   pronunciation:"/fʊlˈfɪl/",part:44,
   example:"She always fulfills her promises to her younger brother.",
   exampleJa:"彼女はいつも、弟への約束を果たす。",
   example2:"The new law fulfilled the hopes of many citizens.",
   exampleJa2:"新しい法律は、多くの市民の望みを果たした。",
   etymologyProcess:"ful（満ちた）＋ fill（満たす）→ 約束や務めをすっかり満たすと…？",
   etymologyConclusion:"ful（満ちた）＋ fill（満たす）→ 約束や務めをすっかり満たしきる＝果たす",
   relatedWords:[
     {word:"fill",meaning:"満たす",breakdown:"fill（満たす）→ 器をいっぱいになるまで入れる"},
     {word:"full",meaning:"いっぱいの",breakdown:"ful（満ちた）→ もうそれ以上入らない状態"},
     {word:"fulfillment",meaning:"達成感",breakdown:"ful（満ちた）＋ fill（満たす）＋ ment（名詞）→ 満たされた気持ち"},
     {synonym:true,word:"satisfy",meaning:"満足させる",breakdown:"求めを満たす。fulfill は約束や役目を果たすこと"}]},

  {id:439,word:"devote",partOfSpeech:"他動詞",meaning:"ささげる",
   meanings:["他|（A to B）（AをBに）ささげる"],
   pronunciation:"/dɪˈvoʊt/",part:44,
   example:"He devotes every weekend to volunteer work in town.",
   exampleJa:"彼は毎週末を、町での奉仕活動にささげている。",
   example2:"She devoted her whole life to helping sick children.",
   exampleJa2:"彼女は病気の子どもを助けることに、生涯をささげた。",
   etymologyProcess:"de（すっかり）＋ vot（誓う）→ 神にすっかり誓って差し出すと…？",
   etymologyConclusion:"de（すっかり）＋ vot（誓う）→ 神にすっかり誓って差し出す＝ささげる",
   relatedWords:[
     {word:"vote",meaning:"投票する",breakdown:"vot（誓う）→ 誓いを立てて自分の意思を示す"},
     {word:"devoted",meaning:"献身的な",breakdown:"de（すっかり）＋ vot（誓う）＋ ed（〜された）→ すっかりささげている"},
     {word:"vow",meaning:"誓い",breakdown:"vot（誓う）→ 固く約束するために立てる言葉"},
     {synonym:true,word:"dedicate",meaning:"ささげる",breakdown:"目的のために差し出す。devote とほぼ同じ使い方"}]},

  {id:440,word:"strive",partOfSpeech:"自動詞",meaning:"努力する",
   meanings:["自|（for ～ / to do）（～を目指して）努力する"],
   pronunciation:"/straɪv/",part:44,
   example:"We strive to improve our English every single day.",
   exampleJa:"私たちは毎日、英語を上達させようと努力する。",
   example2:"He strove for perfection in every painting he made.",
   exampleJa2:"彼は描くすべての絵で、完璧さを求めて努力した。",
   etymologyProcess:"striv（争う）→ 困難と争うように力を尽くすと…？",
   etymologyConclusion:"striv（争う）→ 困難と争うように力を尽くす＝努力する",
   hook:"strive–strove–striven。strive for / to do の形で使う。",
   relatedWords:[
     {word:"strife",meaning:"争い",breakdown:"striv（争う）→ 激しくぶつかり合うこと"},
     {synonym:true,word:"try",meaning:"試みる",breakdown:"やってみること。strive は苦しみながら強く努める"},
     {synonym:true,word:"struggle",meaning:"もがく",breakdown:"苦しんで戦う。strive は目標へ力を尽くすこと"},
     {synonym:true,word:"endeavor",meaning:"努力する",breakdown:"硬い語。strive と同じく強い努力を表す"}]},

  {id:441,word:"aim",partOfSpeech:"他動詞・自動詞",meaning:"ねらう",
   meanings:["自|（at ～ / to do）（～を）ねらう","他|（カメラ・銃）を向ける","名|ねらい"],
   pronunciation:"/eɪm/",part:45,
   example:"She aims to become a doctor in the near future.",
   exampleJa:"彼女は近い将来、医者になることをねらっている。",
   example2:"He aimed the camera at the flying bird carefully.",
   exampleJa2:"彼は注意深く、飛んでいる鳥にカメラのねらいを定めた。",
   etymologyProcess:"aim（値ぶみする）→ ねらいを見積もって的に定めると…？",
   etymologyConclusion:"aim（値ぶみする）→ 距離を見積もって的に狙いを定める＝ねらう",
   hook:"aim at ～（～をねらう）／ aim to do（～するつもりだ）。",
   relatedWords:[
     {word:"aimless",meaning:"目的のない",breakdown:"aim（値ぶみする）＋ less（ない）→ ねらいがどこにもない"},
     {synonym:true,word:"target",meaning:"的",breakdown:"ねらう的そのもの。aim はねらいを定める動き"},
     {synonym:true,word:"goal",meaning:"目標",breakdown:"たどり着きたい所。aim はそこへ向ける心づもり"},
     {synonym:true,word:"purpose",meaning:"目的",breakdown:"行いの目的。aim はねらいを定めることが中心"}]},

  {id:442,word:"challenge",partOfSpeech:"名詞",meaning:"難問，課題",
   meanings:["名|難問，課題","他|～に異議を唱える","他|（人）に挑む"],
   pronunciation:"/ˈtʃælɪndʒ/",part:45,
   example:"Learning a new language is a big challenge for everyone.",
   exampleJa:"新しい言語を学ぶことは、だれにとっても大きな難問だ。",
   example2:"The team faced many challenges during the long season.",
   exampleJa2:"そのチームは、長い試合期間の間に多くの課題に直面した。",
   etymologyProcess:"chall（言いがかり）→ 正面から立ちはだかって挑んでくるものは…？",
   etymologyConclusion:"chall（言いがかり）→ 正面から立ちはだかって挑んでくるもの＝難問，課題",
   hook:"日本語の「チャレンジ」と違い、名詞は「難題」の意味が中心。",
   relatedWords:[
     {word:"challenging",meaning:"手ごわい",breakdown:"chall（言いがかり）＋ ing（形容詞）→ こちらへ挑みかかってくる"},
     {word:"challenger",meaning:"挑戦者",breakdown:"chall（言いがかり）＋ er（人）→ 相手に正面から挑んでいく人"},
     {synonym:true,word:"difficulty",meaning:"困難",breakdown:"難しさそのもの。challenge は挑みがいのある難題"},
     {synonym:true,word:"task",meaning:"仕事",breakdown:"やるべき仕事。challenge は手ごわい課題のこと"}]},

  {id:443,word:"trial",partOfSpeech:"名詞",meaning:"試み",
   meanings:["名|試み，試験的な使用","名|裁判"],
   pronunciation:"/ˈtraɪəl/",part:45,
   example:"The new medicine is still in its first trial.",
   exampleJa:"その新しい薬は、まだ最初の試みの段階にある。",
   example2:"After many trials, they finally built a working robot.",
   exampleJa2:"多くの試みののち、彼らはついに動くロボットを作った。",
   etymologyProcess:"try（試す）＋ al（名詞）→ うまくいくか実際に試してみることは…？",
   etymologyConclusion:"try（試す）＋ al（名詞）→ うまくいくか実際に試してみること＝試み",
   relatedWords:[
     {word:"try",meaning:"試みる",breakdown:"try（試す）→ できるかどうか実際にやってみる"},
     {synonym:true,word:"test",meaning:"検査",breakdown:"調べるための試験。trial は実際にやってみる試み"},
     {synonym:true,word:"experiment",meaning:"実験",breakdown:"仮説を確かめる。trial は使ってみて確かめること"},
     {synonym:true,word:"attempt",meaning:"企て",breakdown:"やってみること。trial は結果を見るための試み"}]},

  {id:444,word:"dizzy",partOfSpeech:"形容詞",meaning:"めまいがして",
   meanings:["形|めまいがして，ふらふらして"],
   pronunciation:"/ˈdɪzi/",part:45,
   example:"I felt dizzy after standing up too quickly today.",
   exampleJa:"今日、急に立ち上がったあと、私はめまいがした。",
   example2:"She became dizzy in the hot and crowded room.",
   exampleJa2:"彼女は暑く混み合った部屋で、めまいがしてきた。",
   etymologyProcess:"dizzy（頭がぼんやりする）→ 頭がふらつき世界が回って見えると…？",
   etymologyConclusion:"dizzy（頭がぼんやりする）→ 頭がふらつき、世界が回って見える＝めまいがして",
   hook:"feel dizzy（めまいがする）の形で使うことが多い。",
   relatedWords:[
     {word:"dizziness",meaning:"めまい",breakdown:"dizzy（頭がぼんやりする）＋ ness（名詞）→ 頭がふらつく状態"},
     {synonym:true,word:"faint",meaning:"気を失う",breakdown:"意識がなくなる。dizzy はふらつく手前の状態"},
     {synonym:true,word:"sick",meaning:"気分が悪い",breakdown:"体調が悪い。dizzy は頭が回るように感じること"},
     {synonym:true,word:"unsteady",meaning:"ふらつく",breakdown:"足元が定まらない。dizzy は頭のふらつき"}]},

  {id:445,word:"appetite",partOfSpeech:"名詞",meaning:"食欲",
   meanings:["名|食欲","名|（for ～）（～への）強い欲求"],
   pronunciation:"/ˈæpɪtaɪt/",part:45,
   example:"The long walk gave the children a huge appetite.",
   exampleJa:"長い散歩は、子どもたちに大きな食欲を与えた。",
   example2:"He lost his appetite during the hot summer days.",
   exampleJa2:"彼は暑い夏の日々の間、食欲を失った。",
   etymologyProcess:"ad（〜へ）＋ pet（求める）→ 食べ物へ向かって強く求めると…？",
   etymologyConclusion:"ad（〜へ）＋ pet（求める）→ 食べ物へ向かって強く求める気持ち＝食欲",
   relatedWords:[
     {word:"compete",meaning:"競争する",breakdown:"com（共に）＋ pet（求める）→ 同じものを互いに求め合う"},
     {word:"repeat",meaning:"繰り返す",breakdown:"re（再び）＋ pet（求める）→ もう一度求めて同じことをする"},
     {word:"petition",meaning:"請願",breakdown:"pet（求める）＋ ion（名詞）→ 強く求めて差し出す願い"},
     {synonym:true,word:"hunger",meaning:"空腹",breakdown:"腹が減った状態。appetite は食べたいという気持ち"}]},

  {id:446,word:"starve",partOfSpeech:"自動詞",meaning:"餓死する",
   meanings:["自|餓死する，飢える"],
   pronunciation:"/stɑːrv/",part:45,
   example:"Wild animals may starve when the forest disappears.",
   exampleJa:"森が消えると、野生動物は餓死するかもしれない。",
   example2:"Thousands of people starved during that terrible long winter.",
   exampleJa2:"その恐ろしく長い冬の間、何千人もの人が餓死した。",
   etymologyProcess:"starv（こわばって死ぬ）→ 食べ物がなく体がこわばっていくと…？",
   etymologyConclusion:"starv（こわばって死ぬ）→ 食べ物がなく体がこわばって力尽きる＝餓死する",
   hook:"I'm starving. は「おなかがぺこぺこだ」という大げさな言い方。",
   relatedWords:[
     {word:"starvation",meaning:"飢餓",breakdown:"starv（こわばって死ぬ）＋ ation（名詞）→ 食べ物がない苦しみ"},
     {synonym:true,word:"hunger",meaning:"飢え",breakdown:"食べ物が足りない状態。starve はその末に死ぬこと"},
     {synonym:true,word:"famine",meaning:"飢饉",breakdown:"広い地域の食料不足。starve は一人ひとりの状態"},
     {synonym:true,word:"die",meaning:"死ぬ",breakdown:"命が尽きる。starve は食べ物がなくて死ぬこと"}]},

  {id:447,word:"mental",partOfSpeech:"形容詞",meaning:"精神の",
   meanings:["形|精神の，心の"],
   pronunciation:"/ˈmentəl/",part:45,
   example:"Good sleep is very important for your mental health.",
   exampleJa:"良い睡眠は、精神の健康にとってとても大切だ。",
   example2:"The coach talked about mental strength before the match.",
   exampleJa2:"監督は試合の前に、精神の強さについて話した。",
   etymologyProcess:"mens（心）＋ al（〜の）→ 体ではなく心のはたらきにかかわると…？",
   etymologyConclusion:"mens（心）＋ al（〜の）→ 体ではなく心のはたらきにかかわる＝精神の",
   relatedWords:[
     {word:"mention",meaning:"（ついでに）述べる",breakdown:"mens（心）＋ ion（名詞）→ 心にあることを短く口に出す"},
     {word:"comment",meaning:"論評",breakdown:"com（共に）＋ mens（心）→ 心に浮かんだことを言い添える"},
     {word:"mentality",meaning:"考え方",breakdown:"mens（心）＋ ity（名詞）→ その人の心のあり方"},
     {synonym:true,word:"physical",meaning:"身体の",breakdown:"体にかかわる。mental はその反対で心にかかわる"}]},

  {id:448,word:"rest",partOfSpeech:"名詞",meaning:"休憩",
   meanings:["名|休憩，休息","自|休む"],
   pronunciation:"/rest/",part:45,
   example:"You need a short rest after such hard practice.",
   exampleJa:"あんなに厳しい練習のあとは、短い休憩が必要だ。",
   example2:"The team took a rest under the big old tree.",
   exampleJa2:"チームは大きな古い木の下で休憩を取った。",
   etymologyProcess:"rest（立ち止まる）→ 動きを止めて力を取り戻すことは…？",
   etymologyConclusion:"rest（立ち止まる）→ 動きを止めて力を取り戻すこと＝休憩",
   hook:"the rest（残り）は別の語源の rest。意味の違いに注意。",
   relatedWords:[
     {word:"restless",meaning:"落ち着かない",breakdown:"rest（立ち止まる）＋ less（ない）→ 止まっていられない"},
     {word:"restful",meaning:"安らかな",breakdown:"rest（立ち止まる）＋ ful（満ちた）→ 落ち着いて休める"},
     {synonym:true,word:"break",meaning:"休み",breakdown:"作業を切る短い休み。rest は体を休めること"},
     {synonym:true,word:"relax",meaning:"くつろぐ",breakdown:"気持ちを緩める。rest は動きを止めて休むこと"}]},

  {id:449,word:"surgery",partOfSpeech:"名詞",meaning:"手術",
   meanings:["名|手術","名|外科"],
   pronunciation:"/ˈsɜːrdʒəri/",part:45,
   example:"He had surgery on his knee after the bad accident.",
   exampleJa:"彼はひどい事故のあと、ひざの手術を受けた。",
   example2:"The surgery lasted for more than five long hours.",
   exampleJa2:"その手術は、5時間以上もの長い間続いた。",
   etymologyProcess:"surg（手で働く）＋ ry（もの）→ 手を使って体を治す技は…？",
   etymologyConclusion:"surg（手で働く）＋ ry（もの）→ 手を使って体を切り開き治す技＝手術",
   relatedWords:[
     {word:"surgeon",meaning:"外科医",breakdown:"surg（手で働く）→ 手を使って体を治す医者"},
     {word:"surgical",meaning:"外科の",breakdown:"surg（手で働く）＋ al（〜の）→ 手術にかかわる"},
     {synonym:true,word:"operation",meaning:"手術",breakdown:"have an operation でも「手術を受ける」と言える"},
     {synonym:true,word:"treatment",meaning:"治療",breakdown:"治すこと全般。surgery は切り開いて治すこと"}]},

  {id:450,word:"disease",partOfSpeech:"名詞",meaning:"病気",
   meanings:["名|病気，疾患"],
   pronunciation:"/dɪˈziːz/",part:45,
   example:"This disease spreads quickly among young school children.",
   exampleJa:"この病気は、幼い学童の間ですばやく広がる。",
   example2:"Doctors are working hard to cure the rare disease.",
   exampleJa2:"医師たちは、そのまれな病気を治そうと懸命に働いている。",
   etymologyProcess:"dis（否定）＋ ease（楽）→ 体が楽でいられなくなってしまうと…？",
   etymologyConclusion:"dis（否定）＋ ease（楽）→ 体が楽でいられなくなった状態＝病気",
   relatedWords:[
     {word:"ease",meaning:"気楽さ",breakdown:"ease（楽）→ 力を入れずにいられる楽な状態"},
     {word:"easy",meaning:"簡単な",breakdown:"ease（楽）＋ y（〜な状態の）→ 苦もなくできる"},
     {word:"uneasy",meaning:"不安な",breakdown:"un（否定）＋ ease（楽）→ 心が楽でいられない"},
     {synonym:true,word:"illness",meaning:"病気",breakdown:"具合が悪い状態。disease は名前のついた病気"}]},
