  {id:651,word:"shake",partOfSpeech:"他動詞・自動詞",meaning:"振る；揺れる",
   meanings:["他|（手や容器を）振る","自|（建物などが）揺れる"],
   pronunciation:"/ʃeɪk/",part:66,
   example:"Please shake the bottle well before you open it.",
   exampleJa:"開ける前に、そのびんをよく振ってください。",
   example2:"The strong wind shook the windows of our classroom.",
   exampleJa2:"強い風が私たちの教室の窓を激しく揺さぶった。",
   etymologyProcess:"shake（揺さぶる）→ 手に持って前後に何度も動かすと…？",
   etymologyConclusion:"shake（揺さぶる）→ 手や体をつかんで前後左右に何度も動かす＝振る",
   relatedWords:[
     {word:"shaky",meaning:"ぐらぐらする；不安定な",breakdown:"shake（揺さぶる）＋ y（〜な状態の）→ 揺れて足もとが定まらない"},
     {word:"handshake",meaning:"握手",breakdown:"hand（手）＋ shake（揺さぶる）→ 手を取り合って上下に揺らすあいさつ"},
     {synonym:true,word:"tremble",meaning:"震える",breakdown:"寒さや怖さで体が細かく震える。shake は自分から振る動きも表す"},
     {synonym:true,word:"wave",meaning:"手を振る；波",breakdown:"波のように手を左右に振る。shake は上下に揺さぶる動き"}]},

  {id:652,word:"polish",partOfSpeech:"他動詞",meaning:"磨く；洗練する",
   meanings:["他|（表面を）磨く","他|（文章や技を）洗練する"],
   pronunciation:"/ˈpɑːlɪʃ/",part:66,
   example:"He polished his leather shoes before the school entrance ceremony.",
   exampleJa:"彼は入学式の前に、革靴を磨いた。",
   example2:"You should polish your speech until every sentence sounds natural.",
   exampleJa2:"どの文も自然に聞こえるまで、スピーチを磨くべきだ。",
   etymologyProcess:"pol（磨く）＋ ish（〜にする）→ 表面をこすってつやを出すと…？",
   etymologyConclusion:"pol（磨く）＋ ish（〜にする）→ 表面を布でこすって、つやつやに光らせる＝磨く",
   relatedWords:[
     {word:"polite",meaning:"礼儀正しい",breakdown:"pol（磨く）＋ ite（〜された）→ 角が取れて磨かれたふるまい"},
     {word:"polished",meaning:"磨かれた；洗練された",breakdown:"pol（磨く）＋ ish（〜にする）＋ ed（〜された）→ 磨き上げられた状態"},
     {synonym:true,word:"shine",meaning:"光る；輝かせる",breakdown:"光を放つ。polish はこすって光らせる動作そのもの"},
     {synonym:true,word:"rub",meaning:"こする",breakdown:"表面をこする。polish は「つやを出すために」こする"}]},

  {id:653,word:"attend",partOfSpeech:"他動詞・自動詞",meaning:"出席する；世話をする",
   meanings:["他|（会や授業に）出席する","自|（attend to で）世話をする"],
   pronunciation:"/əˈtend/",part:66,
   example:"More than fifty students attended the lecture on space travel.",
   exampleJa:"五十人を超える生徒が、宇宙旅行についての講義に出席した。",
   example2:"I will attend the club meeting after school tomorrow.",
   exampleJa2:"私は明日の放課後、部活のミーティングに出席するつもりだ。",
   etymologyProcess:"ad（〜へ）＋ tend（伸ばす）→ 心をその場へ伸ばしていくと…？",
   etymologyConclusion:"ad（〜へ）＋ tend（伸ばす）→ 心と体をその場へ伸ばして、そこに身を置く＝出席する",
   relatedWords:[
     {word:"tend",meaning:"〜しがちである",breakdown:"tend（伸ばす）→ 気持ちがある方向へ自然に伸びていく"},
     {word:"extend",meaning:"伸ばす，延長する",breakdown:"ex（外へ）＋ tend（伸ばす）→ 外へ向かってぐいと伸ばす"},
     {word:"attention",meaning:"注意，注目",breakdown:"ad（〜へ）＋ tend（伸ばす）＋ ion（名詞）→ 心をそこへ伸ばすこと"},
     {word:"intend",meaning:"意図する",breakdown:"in（中へ）＋ tend（伸ばす）→ 心を的の中へ伸ばして狙う"}]},

  {id:654,word:"imitate",partOfSpeech:"他動詞",meaning:"まねる",
   meanings:["他|（動作や話し方を）まねる"],
   pronunciation:"/ˈɪmɪteɪt/",part:66,
   example:"Young children often imitate the way their parents speak.",
   exampleJa:"幼い子どもは、親の話し方をまねることが多い。",
   example2:"He imitated our teacher's voice and made everyone laugh.",
   exampleJa2:"彼は先生の声をまねて、みんなを笑わせた。",
   etymologyProcess:"imit（似せる）＋ ate（動詞）→ 同じ形になるように似せると…？",
   etymologyConclusion:"imit（似せる）＋ ate（動詞）→ 目の前のものと同じ形・同じ動きに似せる＝まねる",
   relatedWords:[
     {word:"image",meaning:"像，イメージ",breakdown:"imag（似せた姿）→ 実物に似せて写し取った姿"},
     {word:"imagine",meaning:"想像する",breakdown:"imag（似せた姿）＋ ine（動詞）→ 心の中に似た姿を描き出す"},
     {word:"imitation",meaning:"模造品；まねること",breakdown:"imit（似せる）＋ ation（名詞）→ 似せて作ったもの"},
     {synonym:true,word:"copy",meaning:"写す；複製",breakdown:"そっくり写し取る。imitate は動作や話し方もまねる"}]},

  {id:655,word:"conduct",partOfSpeech:"他動詞",meaning:"（調査などを）行う；指揮する",
   meanings:["他|（調査や実験を）行う","他|（楽団を）指揮する"],
   pronunciation:"/kənˈdʌkt/",part:66,
   example:"Our class conducted a survey about sleep among high school students.",
   exampleJa:"私たちのクラスは、高校生の睡眠についての調査を行った。",
   example2:"The city will conduct a safety check on every old bridge.",
   exampleJa2:"市は古い橋すべてについて安全点検を行う予定だ。",
   etymologyProcess:"con（共に）＋ duct（導く）→ 全体をまとめて引っぱっていくと…？",
   etymologyConclusion:"con（共に）＋ duct（導く）→ 人や作業をまとめて引っぱり、最後まで導く＝行う",
   relatedWords:[
     {word:"introduce",meaning:"紹介する；導入する",breakdown:"intro（中へ）＋ duc（導く）→ 中へ手を引いて連れて入る"},
     {word:"produce",meaning:"生産する",breakdown:"pro（前へ）＋ duc（導く）→ 前へ引き出して形にする"},
     {word:"conductor",meaning:"指揮者；車掌",breakdown:"con（共に）＋ duct（導く）＋ or（人）→ 全体をまとめて導く人"},
     {word:"reduce",meaning:"減らす",breakdown:"re（後ろへ）＋ duc（導く）→ 後ろへ引き戻して小さくする"}]},

  {id:656,word:"struggle",partOfSpeech:"自動詞",meaning:"苦闘する；もがく",
   meanings:["自|（苦しみながら）苦闘する","自|（逃れようと）もがく"],
   pronunciation:"/ˈstrʌɡl/",part:66,
   example:"Many students struggle with math during their first school year.",
   exampleJa:"多くの生徒が、一年目に数学で苦闘する。",
   example2:"She struggled to open the heavy door of the gym.",
   exampleJa2:"彼女は体育館の重い扉を開けようと苦闘した。",
   etymologyProcess:"struggle（もがく）→ 手足をばたつかせて必死に抗うと…？",
   etymologyConclusion:"struggle（もがく）→ 力の差がある相手に、手足をばたつかせて必死に抗う＝苦闘する",
   hook:"struggle with A（Aに苦労する）／struggle to do（〜しようともがく）で覚える。",
   relatedWords:[
     {synonym:true,word:"strive",meaning:"努力する",breakdown:"目標に向かって懸命に励む。struggle は苦しさ・抵抗の感じが強い"},
     {synonym:true,word:"fight",meaning:"戦う",breakdown:"相手と戦う。struggle は勝ち目の薄い相手にもがく感じ"},
     {synonym:true,word:"resist",meaning:"抵抗する",breakdown:"押し返して抵抗する。struggle はもがきながら抗う感じ"},
     {synonym:true,word:"wrestle",meaning:"取っ組み合う",breakdown:"組み合ってねじる。struggle のもとの「もがく」に近い動き"}]},

  {id:657,word:"burn",partOfSpeech:"他動詞・自動詞",meaning:"燃える；焼く",
   meanings:["自|（炎を上げて）燃える","他|（火で）焼く，やけどさせる"],
   pronunciation:"/bɜːrn/",part:66,
   example:"Dry leaves burn quickly, so be careful near the fire.",
   exampleJa:"枯れ葉は早く燃えるので、火の近くでは気をつけて。",
   example2:"I burned my finger on the hot pan yesterday evening.",
   exampleJa2:"私は昨日の夕方、熱いフライパンで指を焼いた。",
   etymologyProcess:"burn（燃える）→ 炎を上げて、もとの形が失われていくと…？",
   etymologyConclusion:"burn（燃える）→ 炎を上げて熱を放ち、もとの形が失われていく＝燃える",
   relatedWords:[
     {word:"burning",meaning:"燃えている；燃えるような",breakdown:"burn（燃える）＋ ing（〜している）→ 今まさに炎を上げている"},
     {word:"sunburn",meaning:"日焼け",breakdown:"sun（太陽）＋ burn（燃える）→ 太陽に焼かれて肌が赤くなること"},
     {synonym:true,word:"flame",meaning:"炎",breakdown:"立ちのぼる炎そのもの。burn は燃えるという動きを表す"},
     {synonym:true,word:"melt",meaning:"溶ける",breakdown:"熱でやわらかくなる。burn は形が焼けて失われる"}]},

  {id:658,word:"cheat",partOfSpeech:"他動詞・自動詞",meaning:"だます；不正をする",
   meanings:["他|（ずるをして）だます","自|（試験などで）不正をする"],
   pronunciation:"/tʃiːt/",part:66,
   example:"The shop cheated many customers with fake gold rings.",
   exampleJa:"その店は偽の金の指輪で、多くの客をだました。",
   example2:"Never cheat during an exam, even if you feel nervous.",
   exampleJa2:"たとえ不安でも、試験中に不正をしてはいけない。",
   etymologyProcess:"cheat（横取りする）→ ずるいやり方で人のものを取ると…？",
   etymologyConclusion:"cheat（横取りする）→ ずるいやり方で人のものや点数を横取りする＝だます",
   hook:"もとは「財産の没収」。cheat A out of B（AからBをだまし取る）で覚える。",
   relatedWords:[
     {synonym:true,word:"trick",meaning:"だます；たくらみ",breakdown:"策を使ってだます。cheat は利益を横取りする点が中心"},
     {synonym:true,word:"deceive",meaning:"欺く",breakdown:"相手の目をそらして信じ込ませる。cheat より計画的で重い"},
     {synonym:true,word:"fool",meaning:"だます；ばか者",breakdown:"相手をばかにしてだます。cheat は金や点数をかすめ取る"},
     {word:"cheater",meaning:"不正をする人，詐欺師",breakdown:"cheat（横取りする）＋ er（人）→ ずるをして人のものを横取りする人"}]},

  {id:659,word:"participate",partOfSpeech:"自動詞",meaning:"参加する",
   meanings:["自|（活動や行事に）参加する"],
   pronunciation:"/pɑːrˈtɪsɪpeɪt/",part:66,
   example:"All the students participated in the school cleaning activity.",
   exampleJa:"生徒全員がその学校の清掃活動に参加した。",
   example2:"I want to participate in the speech contest this year.",
   exampleJa2:"私は今年のスピーチコンテストに参加したい。",
   etymologyProcess:"part（分ける）＋ cip（取る）＋ ate（動詞）→ 分け前を自分の手に取ると…？",
   etymologyConclusion:"part（分ける）＋ cip（取る）＋ ate（動詞）→ 全体の一部を自分の分として取り、その場に加わる＝参加する",
   relatedWords:[
     {word:"part",meaning:"部分；分ける",breakdown:"part（分ける）→ 全体を切り分けてできた一つ"},
     {word:"partner",meaning:"相手，仲間",breakdown:"part（分ける）＋ er（人）→ 分け前を共にする相手"},
     {word:"participant",meaning:"参加者",breakdown:"part（分ける）＋ cip（取る）＋ ant（人）→ 分け前を取って加わる人"},
     {word:"accept",meaning:"受け入れる",breakdown:"ad（〜へ）＋ cept（取る）→ 自分のほうへ引き取る"}]},

  {id:660,word:"exist",partOfSpeech:"自動詞",meaning:"存在する",
   meanings:["自|（そこに）存在する"],
   pronunciation:"/ɪɡˈzɪst/",part:66,
   example:"Scientists believe that water once existed on the planet Mars.",
   exampleJa:"科学者は、火星にかつて水が存在したと考えている。",
   example2:"Does a perfect answer exist for this difficult question?",
   exampleJa2:"この難しい問いに、完璧な答えは存在するのだろうか。",
   etymologyProcess:"ex（外へ）＋ sist（立つ）→ 外に姿を現して立っていると…？",
   etymologyConclusion:"ex（外へ）＋ sist（立つ）→ 外に姿を現して、そこに立っている＝存在する",
   relatedWords:[
     {word:"existence",meaning:"存在",breakdown:"ex（外へ）＋ sist（立つ）＋ ence（名詞）→ 外に立って在ること"},
     {word:"insist",meaning:"主張する",breakdown:"in（上に）＋ sist（立つ）→ 一点の上に立ち続けて譲らない"},
     {word:"resist",meaning:"抵抗する",breakdown:"re（後ろへ）＋ sist（立つ）→ 押し返すように立ちはだかる"},
     {word:"assist",meaning:"手伝う",breakdown:"ad（〜へ）＋ sist（立つ）→ そばに立って力を貸す"}]},

  {id:661,word:"arise",partOfSpeech:"自動詞",meaning:"（問題が）持ち上がる；生じる",
   meanings:["自|（問題や疑問が）持ち上がる"],
   pronunciation:"/əˈraɪz/",part:67,
   example:"Serious problems may arise if we ignore this small crack.",
   exampleJa:"この小さなひび割れを無視すれば、深刻な問題が持ち上がるかもしれない。",
   example2:"A question arose during the meeting about next year's budget.",
   exampleJa2:"来年度の予算について、会議中に疑問が持ち上がった。",
   etymologyProcess:"rise（上がる）→ 水面の下から何かが浮かび上がってくると…？",
   etymologyConclusion:"rise（上がる）→ 水中の泡が浮かび上がるように、問題が表に出てくる＝持ち上がる",
   relatedWords:[
     {word:"rise",meaning:"上がる，昇る",breakdown:"rise（上がる）→ 下から上へひとりでに動いていく"},
     {word:"raise",meaning:"上げる；育てる",breakdown:"raise（上がらせる）→ 力を加えて下から上へ持ち上げる"},
     {word:"sunrise",meaning:"日の出",breakdown:"sun（太陽）＋ rise（上がる）→ 太陽が地平線から上がること"},
     {synonym:true,word:"occur",meaning:"起こる",breakdown:"出来事が起こる。arise は問題や疑問が表に出てくる感じ"}]},

  {id:662,word:"occur",partOfSpeech:"自動詞",meaning:"（出来事が）起こる；ふと思い浮かぶ",
   meanings:["自|（事故などが）起こる","自|（it occurs to A で）ふと思い浮かぶ"],
   pronunciation:"/əˈkɜːr/",part:67,
   example:"Traffic accidents often occur at this dark corner at night.",
   exampleJa:"交通事故は夜、この暗い角でよく起こる。",
   example2:"It never occurred to me that he was telling a lie.",
   exampleJa2:"彼がうそをついているとは、私には少しも思い浮かばなかった。",
   etymologyProcess:"oc（〜に向かって）＋ curr（走る）→ 出来事が目の前へ走り寄ると…？",
   etymologyConclusion:"oc（〜に向かって）＋ curr（走る）→ 出来事が向こうから目の前へ走り寄ってくる＝起こる",
   relatedWords:[
     {word:"current",meaning:"現在の；流れ",breakdown:"curr（走る）＋ ent（〜している）→ 今まさに走って流れているもの"},
     {word:"course",meaning:"進路；課程",breakdown:"cours（走る）→ 走っていく道すじ"},
     {word:"occurrence",meaning:"出来事，発生",breakdown:"oc（〜に向かって）＋ curr（走る）＋ ence（名詞）→ 走り寄って起きたこと"},
     {word:"recur",meaning:"再び起こる",breakdown:"re（再び）＋ curr（走る）→ もう一度こちらへ走り戻ってくる"}]},

  {id:663,word:"involve",partOfSpeech:"他動詞",meaning:"巻き込む；（必然的に）含む",
   meanings:["他|（人を）巻き込む","他|（結果として）含む，伴う"],
   pronunciation:"/ɪnˈvɑːlv/",part:67,
   example:"The teacher tried to involve every student in the discussion.",
   exampleJa:"先生はすべての生徒を話し合いに巻き込もうとした。",
   example2:"He was involved in a serious traffic accident last winter.",
   exampleJa2:"彼は昨年の冬、深刻な交通事故に巻き込まれた。",
   etymologyProcess:"in（中へ）＋ volve（回す）→ 渦の中へぐるぐる巻き込むと…？",
   etymologyConclusion:"in（中へ）＋ volve（回す）→ 渦を巻くようにして、人や物を中へ引き込む＝巻き込む",
   relatedWords:[
     {word:"revolve",meaning:"回転する",breakdown:"re（何度も）＋ volve（回す）→ 同じところをぐるぐる回り続ける"},
     {word:"evolve",meaning:"進化する，発展する",breakdown:"e（外へ）＋ volve（回す）→ 巻物を外へ広げるように育っていく"},
     {word:"involvement",meaning:"かかわり，関与",breakdown:"in（中へ）＋ volve（回す）＋ ment（名詞）→ 中へ巻き込まれている状態"},
     {synonym:true,word:"include",meaning:"含む",breakdown:"囲いの中に入れて含む。involve は関わらせて巻き込む"}]},

  {id:664,word:"require",partOfSpeech:"他動詞",meaning:"必要とする；要求する",
   meanings:["他|（条件として）必要とする","他|（規則が）要求する"],
   pronunciation:"/rɪˈkwaɪr/",part:67,
   example:"This recipe requires three eggs and a cup of milk.",
   exampleJa:"このレシピは卵3個と牛乳1カップを必要とする。",
   example2:"The new job will require you to speak two languages.",
   exampleJa2:"その新しい仕事は、あなたが2か国語を話すことを必要とするだろう。",
   etymologyProcess:"re（強く）＋ quire（求める）→ 欠けたものを強く求めると…？",
   etymologyConclusion:"re（強く）＋ quire（求める）→ 欠けているものを、どうしても欲しいと強く求める＝必要とする",
   relatedWords:[
     {word:"request",meaning:"頼む；依頼",breakdown:"re（強く）＋ quest（求める）→ 相手に強く求めて頼み込む"},
     {word:"question",meaning:"質問；問う",breakdown:"quest（求める）＋ ion（名詞）→ 答えを求めること"},
     {word:"inquire",meaning:"尋ねる，問い合わせる",breakdown:"in（中へ）＋ quire（求める）→ 中身に踏み込んで答えを求める"},
     {word:"requirement",meaning:"必要条件",breakdown:"re（強く）＋ quire（求める）＋ ment（名詞）→ 強く求められる条件"}]},

  {id:665,word:"counterpart",partOfSpeech:"名詞",meaning:"対応する人［物］",
   meanings:["名|（別の組織で）対応する人，対応する物"],
   pronunciation:"/ˈkaʊntərpɑːrt/",part:67,
   example:"The Japanese prime minister met his counterpart from France yesterday.",
   exampleJa:"日本の首相は昨日、フランスの対応する人物と会談した。",
   example2:"This Japanese word has no exact counterpart in English.",
   exampleJa2:"この日本語には、英語に正確に対応する語がない。",
   etymologyProcess:"counter（向かい合う）＋ part（分ける）→ 割り符を向かい合わせると…？",
   etymologyConclusion:"counter（向かい合う）＋ part（分ける）→ 二つに割った割り符の、ぴたり合うもう片方＝対応する人",
   relatedWords:[
     {word:"apart",meaning:"離れて",breakdown:"ad（〜へ）＋ part（分ける）→ 切り分けられて別々になって"},
     {word:"partly",meaning:"部分的に",breakdown:"part（分ける）＋ ly（副詞）→ 分けたうちの一部だけ"},
     {word:"counter",meaning:"逆らう；反撃",breakdown:"counter（向かい合う）→ 正面から向かい合って受け止める"},
     {word:"particle",meaning:"粒子",breakdown:"part（分ける）＋ icle（小さいもの）→ 細かく分けた小さなかけら"}]},

  {id:666,word:"advent",partOfSpeech:"名詞",meaning:"（重要なものの）到来",
   meanings:["名|（時代を変えるものの）到来，出現"],
   pronunciation:"/ˈædvent/",part:67,
   example:"The advent of smartphones completely changed how people share news.",
   exampleJa:"スマートフォンの到来は、人々のニュースの共有の仕方を完全に変えた。",
   example2:"Farmers welcomed the advent of spring after the long winter.",
   exampleJa2:"農民たちは長い冬のあと、春の到来を喜んで迎えた。",
   etymologyProcess:"ad（〜へ）＋ vent（来る）→ 大きなものがこちらへやって来ると…？",
   etymologyConclusion:"ad（〜へ）＋ vent（来る）→ 時代を変えるものが、こちらへ向かってやって来ること＝到来",
   relatedWords:[
     {word:"event",meaning:"出来事，行事",breakdown:"e（外へ）＋ vent（来る）→ 外へ現れ出てくる出来事"},
     {word:"invent",meaning:"発明する",breakdown:"in（中へ）＋ vent（来る）→ 頭の中へ思いつきがやって来る"},
     {word:"adventure",meaning:"冒険",breakdown:"ad（〜へ）＋ vent（来る）＋ ure（もの）→ 何が来るかわからない出来事"},
     {word:"prevent",meaning:"防ぐ",breakdown:"pre（先に）＋ vent（来る）→ 先回りして、来る前に止める"}]},

  {id:667,word:"maintain",partOfSpeech:"他動詞",meaning:"維持する；主張し続ける",
   meanings:["他|（同じ状態を）維持する","他|（意見を）主張し続ける"],
   pronunciation:"/meɪnˈteɪn/",part:67,
   example:"The city maintains these old roads with a large budget.",
   exampleJa:"市は多額の予算でこれらの古い道路を維持している。",
   example2:"It is hard to maintain a good rhythm during long tests.",
   exampleJa2:"長い試験の間、よい調子を維持するのは難しい。",
   etymologyProcess:"man（手）＋ tain（保つ）→ 手でしっかり支えて持ち続けると…？",
   etymologyConclusion:"man（手）＋ tain（保つ）→ 手でしっかり支えて、同じ状態のまま持ち続ける＝維持する",
   relatedWords:[
     {word:"contain",meaning:"含む",breakdown:"con（共に）＋ tain（保つ）→ 中にまとめて保っている"},
     {word:"obtain",meaning:"得る",breakdown:"ob（〜に向かって）＋ tain（保つ）→ 手を伸ばしてつかみ、保つ"},
     {word:"manual",meaning:"手動の；手引き書",breakdown:"man（手）＋ ual（〜の）→ 手で行うこと、手で使う本"},
     {word:"maintenance",meaning:"維持，整備",breakdown:"man（手）＋ tain（保つ）＋ ance（名詞）→ 手で保ち続けること"}]},

  {id:668,word:"last",partOfSpeech:"自動詞",meaning:"（ある期間）続く",
   meanings:["自|（一定の期間）続く，もつ"],
   pronunciation:"/læst/",part:67,
   example:"The summer festival lasts for three days every August.",
   exampleJa:"その夏祭りは毎年8月に3日間続く。",
   example2:"Our club meeting lasted much longer than we had expected.",
   exampleJa2:"私たちの部活の会議は、予想よりずっと長く続いた。",
   etymologyProcess:"last（足あとをたどる）→ 足あとが途切れず先へ延びると…？",
   etymologyConclusion:"last（足あとをたどる）→ 足あとをたどるように、途切れずに先へ延びていく＝続く",
   hook:"last for 〜（〜の間もつ）の形で使う。「何日もつか」という長さの話。",
   relatedWords:[
     {word:"lasting",meaning:"長続きする",breakdown:"last（足あとをたどる）＋ ing（〜している）→ 途切れずに続いている"},
     {synonym:true,word:"continue",meaning:"続く，続ける",breakdown:"切らずに保ち続ける。last は「何日もつか」という長さの話"},
     {synonym:true,word:"remain",meaning:"残る，〜のままである",breakdown:"あとに残る。last は時間が途切れずに延びていく"},
     {synonym:true,word:"endure",meaning:"耐え続ける",breakdown:"苦しさに耐えて残る。last は苦しさの意味を含まない"}]},

  {id:669,word:"persist",partOfSpeech:"自動詞",meaning:"（あきらめずに）やり続ける；持続する",
   meanings:["自|（あきらめずに）やり続ける","自|（症状などが）持続する"],
   pronunciation:"/pərˈsɪst/",part:67,
   example:"She persisted with her violin practice despite many painful failures.",
   exampleJa:"彼女は何度もつらい失敗をしても、バイオリンの練習をやり続けた。",
   example2:"If the pain persists, you should visit a doctor soon.",
   exampleJa2:"痛みが持続するなら、すぐに医者に行くべきだ。",
   etymologyProcess:"per（すっかり）＋ sist（立つ）→ 最後まで立ったまま動かないと…？",
   etymologyConclusion:"per（すっかり）＋ sist（立つ）→ 終わりまでその場に立ち続けて、一歩も引かない＝やり続ける",
   relatedWords:[
     {word:"consist",meaning:"成り立つ",breakdown:"con（共に）＋ sist（立つ）→ いくつかが一緒に立って形を作る"},
     {word:"persistent",meaning:"しつこい；根気強い",breakdown:"per（すっかり）＋ sist（立つ）＋ ent（〜している）→ 最後まで立ち続けている"},
     {word:"stand",meaning:"立つ；耐える",breakdown:"sta（立つ）→ 足を地につけてまっすぐ立つ"},
     {word:"stable",meaning:"安定した",breakdown:"sta（立つ）＋ able（できる）→ ぐらつかずに立っていられる"}]},

  {id:670,word:"examine",partOfSpeech:"他動詞",meaning:"詳しく調べる；診察する",
   meanings:["他|（中身を）詳しく調べる","他|（医者が）診察する"],
   pronunciation:"/ɪɡˈzæmɪn/",part:67,
   example:"The doctor examined my throat and said it looked fine.",
   exampleJa:"医者は私ののどを詳しく調べ、問題なさそうだと言った。",
   example2:"We must examine these old letters before the museum opens.",
   exampleJa2:"博物館が開く前に、これらの古い手紙を詳しく調べなければならない。",
   etymologyProcess:"ex（外へ）＋ amin（はかりの針）→ 針の傾きをじっと見つめると…？",
   etymologyConclusion:"ex（外へ）＋ amin（はかりの針）→ はかりの針の傾きをじっと見て確かめる＝詳しく調べる",
   relatedWords:[
     {word:"examination",meaning:"試験；検査",breakdown:"ex（外へ）＋ amin（はかりの針）＋ ation（名詞）→ はかりにかけて調べること"},
     {synonym:true,word:"inspect",meaning:"点検する",breakdown:"中をのぞいて見る。examine はじっくり確かめる"},
     {synonym:true,word:"check",meaning:"確認する",breakdown:"合っているか軽く確かめる。examine はもっと詳しく調べる"},
     {synonym:true,word:"investigate",meaning:"（事件などを）捜査する",breakdown:"跡をたどって突き止める。examine は目の前のものを調べる"}]},

  {id:671,word:"gain",partOfSpeech:"他動詞",meaning:"（少しずつ）増す；獲得する",
   meanings:["他|（量や程度を）増す","他|（努力して）獲得する"],
   pronunciation:"/ɡeɪn/",part:68,
   example:"He gained five kilograms during the long cold winter.",
   exampleJa:"彼は長く寒い冬の間に、体重を5キロ増した。",
   example2:"The runner is gaining speed on the final part of the race.",
   exampleJa2:"その走者はレースの最後の区間で速度を増している。",
   etymologyProcess:"gain（狩りで得る）→ 野に出て少しずつ手もとに増やすと…？",
   etymologyConclusion:"gain（狩りで得る）→ 野に出て獲物をとるように、少しずつ手もとに積み増す＝増す",
   hook:"gain weight（体重が増える）／gain experience（経験を積む）で覚える。",
   relatedWords:[
     {word:"gainful",meaning:"もうかる，収入になる",breakdown:"gain（狩りで得る）＋ ful（満ちた）→ 得るものに満ちている"},
     {synonym:true,word:"earn",meaning:"（働いて）稼ぐ",breakdown:"働いた報いとして得る。gain は少しずつ積み増す感じ"},
     {synonym:true,word:"increase",meaning:"増える，増やす",breakdown:"量そのものが増える。gain は自分の手もとに増やす"},
     {synonym:true,word:"win",meaning:"勝ち取る",breakdown:"競って勝ち取る。gain は競わずに積み増す場合にも使う"}]},

  {id:672,word:"obtain",partOfSpeech:"他動詞",meaning:"（努力して）手に入れる",
   meanings:["他|（手続きや努力を経て）手に入れる"],
   pronunciation:"/əbˈteɪn/",part:68,
   example:"You must obtain permission before entering the science laboratory.",
   exampleJa:"理科実験室に入る前に、許可を手に入れなければならない。",
   example2:"He obtained the rare stamp at an old shop downtown.",
   exampleJa2:"彼は町の古い店で、その珍しい切手を手に入れた。",
   etymologyProcess:"ob（〜に向かって）＋ tain（保つ）→ 手を伸ばしてつかみ離さないと…？",
   etymologyConclusion:"ob（〜に向かって）＋ tain（保つ）→ 欲しいものへ手を伸ばしてつかみ、自分のものとして保つ＝手に入れる",
   relatedWords:[
     {word:"retain",meaning:"保ち続ける",breakdown:"re（後ろへ）＋ tain（保つ）→ 手放さずに引きとめておく"},
     {word:"continue",meaning:"続ける",breakdown:"con（共に）＋ tin（保つ）→ 切らずにつなげて保ち続ける"},
     {word:"obstacle",meaning:"障害物",breakdown:"ob（〜に向かって）＋ sta（立つ）＋ cle（もの）→ 行く手に立ちふさがるもの"},
     {synonym:true,word:"get",meaning:"得る",breakdown:"手に入れる一般の語。obtain は努力や手続きを経て得る"}]},

  {id:673,word:"acquire",partOfSpeech:"他動詞",meaning:"（時間をかけて）習得する；取得する",
   meanings:["他|（技能や言語を）習得する","他|（財産などを）取得する"],
   pronunciation:"/əˈkwaɪər/",part:68,
   example:"Children acquire their first language without studying grammar rules.",
   exampleJa:"子どもは文法規則を学ばずに母語を習得する。",
   example2:"She acquired a good sense of rhythm from years of dancing.",
   exampleJa2:"彼女は何年ものダンスからよいリズム感を習得した。",
   etymologyProcess:"ad（〜へ）＋ quire（求める）→ 自分のほうへ少しずつ求め寄せると…？",
   etymologyConclusion:"ad（〜へ）＋ quire（求める）→ 自分のほうへ少しずつ求め寄せて、身につける＝習得する",
   relatedWords:[
     {word:"require",meaning:"必要とする",breakdown:"re（強く）＋ quire（求める）→ 欠けているものを強く求める"},
     {word:"question",meaning:"質問；問う",breakdown:"quest（求める）＋ ion（名詞）→ 答えを求めること"},
     {word:"request",meaning:"頼む；依頼",breakdown:"re（強く）＋ quest（求める）→ 相手に強く求めて頼み込む"},
     {synonym:true,word:"learn",meaning:"学ぶ，覚える",breakdown:"学んで覚える。acquire は時間をかけて身についていく"}]},

  {id:674,word:"search",partOfSpeech:"他動詞・自動詞",meaning:"（くまなく）捜す",
   meanings:["他|（場所を）くまなく捜す","自|（search for で）捜し求める"],
   pronunciation:"/sɜːrtʃ/",part:68,
   example:"The police searched the whole park for the missing boy.",
   exampleJa:"警察は行方不明の少年を求めて公園中を捜した。",
   example2:"I searched my bag three times but could not find it.",
   exampleJa2:"私はかばんを3回捜したが、それを見つけられなかった。",
   etymologyProcess:"search（探す）→ 輪を描くように回りながら見て回ると…？",
   etymologyConclusion:"search（探す）→ 円を描くようにぐるぐる回り、すみずみまで見て回る＝捜す",
   relatedWords:[
     {word:"research",meaning:"研究，調査",breakdown:"re（何度も）＋ search（探す）→ 何度もぐるぐる回って調べ直す"},
     {word:"circle",meaning:"円，輪",breakdown:"circ（輪を描く）＋ le（もの）→ ぐるりと一周してできる線"},
     {word:"circulate",meaning:"循環する",breakdown:"circ（輪を描く）＋ ate（動詞）→ 輪を描いてぐるぐる回り続ける"},
     {synonym:true,word:"seek",meaning:"探し求める",breakdown:"求めて探す。search は場所をくまなく調べる動き"}]},

  {id:675,word:"logical",partOfSpeech:"形容詞",meaning:"論理的な，筋道の通った",
   meanings:["形|（話や考えが）論理的な"],
   pronunciation:"/ˈlɑːdʒɪkl/",part:68,
   example:"His explanation was clear and logical, so everyone understood it.",
   exampleJa:"彼の説明は明快で論理的だったので、みんなが理解した。",
   example2:"We need a logical reason before changing the club rules.",
   exampleJa2:"部のきまりを変える前に、論理的な理由が必要だ。",
   etymologyProcess:"log（言葉）＋ ic（〜の）＋ al（〜の）→ 言葉の筋道が通っていると…？",
   etymologyConclusion:"log（言葉）＋ ic（〜の）＋ al（〜の）→ 言葉が筋道どおりにきちんとつながっている＝論理的な",
   relatedWords:[
     {word:"logic",meaning:"論理，論理学",breakdown:"log（言葉）＋ ic（名詞）→ 言葉の筋道そのもの"},
     {word:"dialogue",meaning:"対話",breakdown:"dia（間で）＋ log（言葉）→ 二人の間を行き来する言葉"},
     {word:"apology",meaning:"謝罪",breakdown:"apo（離れて）＋ log（言葉）＋ y（名詞）→ 責めから離れるための言葉"},
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）＋ y（名詞）→ 生命について調べる学問"}]},

  {id:676,word:"scholarship",partOfSpeech:"名詞",meaning:"奨学金",
   meanings:["名|（学ぶ人に与えられる）奨学金"],
   pronunciation:"/ˈskɑːlərʃɪp/",part:68,
   example:"She won a scholarship to study music in Vienna next year.",
   exampleJa:"彼女は来年ウィーンで音楽を学ぶための奨学金を勝ち取った。",
   example2:"Many students apply for this scholarship every spring.",
   exampleJa2:"毎年春、多くの生徒がこの奨学金に応募する。",
   etymologyProcess:"schol（学びのひま）＋ ar（人）＋ ship（名詞）→ 学ぶ人を支えるお金は…？",
   etymologyConclusion:"schol（学びのひま）＋ ar（人）＋ ship（名詞）→ 学ぶひまを持てるように与えられるお金＝奨学金",
   relatedWords:[
     {word:"school",meaning:"学校",breakdown:"school（学校）→ もとは学ぶためのひまな時間を過ごす場"},
     {word:"scholar",meaning:"学者",breakdown:"schol（学びのひま）＋ ar（人）→ 学ぶひまを持ち続ける人"},
     {word:"hardship",meaning:"苦難",breakdown:"hard（かたい）＋ ship（名詞）→ かたく厳しい状態"},
     {synonym:true,word:"grant",meaning:"助成金",breakdown:"公的に与えられるお金。scholarship は学ぶ人に出るもの"}]},

  {id:677,word:"instruction",partOfSpeech:"名詞",meaning:"指示；使用説明書",
   meanings:["名|（やり方の）指示","名|（複数形で）使用説明書"],
   pronunciation:"/ɪnˈstrʌkʃn/",part:68,
   example:"Please follow the instructions written on the back of the box.",
   exampleJa:"箱の裏に書かれた指示に従ってください。",
   example2:"The teacher gave clear instructions before the science experiment.",
   exampleJa2:"先生は理科の実験の前に、はっきりした指示を出した。",
   etymologyProcess:"in（中へ）＋ struct（積み上げる）＋ ion（名詞）→ 頭の中へ順に積むと…？",
   etymologyConclusion:"in（中へ）＋ struct（積み上げる）＋ ion（名詞）→ 頭の中へ手順を順に積み上げて示すもの＝指示",
   relatedWords:[
     {word:"instruct",meaning:"指示する；教える",breakdown:"in（中へ）＋ struct（積み上げる）→ 頭の中へ知識を積み上げる"},
     {word:"structure",meaning:"構造，建物",breakdown:"struct（積み上げる）＋ ure（もの）→ 積み上げてできた組み立て"},
     {word:"construct",meaning:"建設する",breakdown:"con（共に）＋ struct（積み上げる）→ 材料を寄せ集めて積み上げる"},
     {word:"destroy",meaning:"破壊する",breakdown:"de（逆に）＋ stroy（積み上げる）→ 積み上げたものを逆に崩す"}]},

  {id:678,word:"determine",partOfSpeech:"他動詞",meaning:"決める；決定づける",
   meanings:["他|（方針や結果を）決める","他|（要因が）決定づける"],
   pronunciation:"/dɪˈtɜːrmɪn/",part:68,
   example:"The judges will determine the winner after the final round.",
   exampleJa:"審査員は最終ラウンドのあとに優勝者を決める。",
   example2:"Your daily habits determine your health more than anything else.",
   exampleJa2:"日々の習慣が、何よりもあなたの健康を決める。",
   etymologyProcess:"de（すっかり）＋ term（境界）＋ ine（動詞）→ ここまでと線を引くと…？",
   etymologyConclusion:"de（すっかり）＋ term（境界）＋ ine（動詞）→ ここまでとはっきり境界線を引いて区切る＝決める",
   relatedWords:[
     {word:"term",meaning:"用語；期間",breakdown:"term（境界）→ 意味や時間の、区切られた範囲"},
     {word:"terminal",meaning:"終点；端末",breakdown:"term（境界）＋ al（〜の）→ 線の終わりの境目にある場所"},
     {word:"determined",meaning:"決意の固い",breakdown:"de（すっかり）＋ term（境界）＋ ed（〜された）→ 心に線が引かれた状態"},
     {synonym:true,word:"decide",meaning:"決心する",breakdown:"迷いを切り落として決める。determine はきっぱり線を引く"}]},

  {id:679,word:"conclude",partOfSpeech:"他動詞",meaning:"結論を下す；締めくくる",
   meanings:["他|（考えの）結論を下す","他|（話や式を）締めくくる"],
   pronunciation:"/kənˈkluːd/",part:68,
   example:"The report concluded that more research was clearly needed.",
   exampleJa:"その報告書は、さらなる研究が明らかに必要だと結論を下した。",
   example2:"Let me conclude my speech with a short story about my dog.",
   exampleJa2:"うちの犬の短い話でスピーチを締めくくらせてください。",
   etymologyProcess:"con（すっかり）＋ clude（閉じる）→ 話をすっかり閉じてしまうと…？",
   etymologyConclusion:"con（すっかり）＋ clude（閉じる）→ 話をすっかり閉じて、最後の考えを言い切る＝結論を下す",
   relatedWords:[
     {word:"include",meaning:"含む",breakdown:"in（中へ）＋ clude（閉じる）→ 囲いの中へ閉じ込めて入れる"},
     {word:"exclude",meaning:"除外する",breakdown:"ex（外へ）＋ clude（閉じる）→ 外へ出して戸を閉める"},
     {word:"close",meaning:"閉じる；近い",breakdown:"clos（閉じる）→ すき間なくぴたりと閉める"},
     {word:"conclusion",meaning:"結論",breakdown:"con（すっかり）＋ clude（閉じる）＋ ion（名詞）→ 閉じて出た最後の考え"}]},

  {id:680,word:"distinguish",partOfSpeech:"他動詞",meaning:"区別する，見分ける",
   meanings:["他|（二つのものを）区別する，見分ける"],
   pronunciation:"/dɪˈstɪŋɡwɪʃ/",part:68,
   example:"Can you distinguish the twins by their voices alone?",
   exampleJa:"君は声だけであの双子を区別できますか。",
   example2:"Young children cannot easily distinguish dreams from real events.",
   exampleJa2:"幼い子どもは、夢と現実の出来事を簡単には区別できない。",
   etymologyProcess:"dis（バラバラに）＋ stingu（突き刺す）＋ ish（〜にする）→ 印を刺して分けると…？",
   etymologyConclusion:"dis（バラバラに）＋ stingu（突き刺す）＋ ish（〜にする）→ 針で印を刺し、別のものとして分ける＝区別する",
   relatedWords:[
     {word:"distinct",meaning:"はっきり異なる",breakdown:"dis（バラバラに）＋ stingu（突き刺す）→ 印で刺し分けられてはっきり違う"},
     {word:"instinct",meaning:"本能",breakdown:"in（中へ）＋ stingu（突き刺す）＋ t（名詞）→ 内側から突き動かす力"},
     {word:"sting",meaning:"刺す；針",breakdown:"sting（突き刺す）→ 針でちくりと突き刺す"},
     {synonym:true,word:"tell",meaning:"見分ける；言う",breakdown:"tell A from B で見分ける。distinguish は硬い言い方"}]},

  {id:681,word:"classify",partOfSpeech:"他動詞",meaning:"分類する",
   meanings:["他|（種類ごとに）分類する"],
   pronunciation:"/ˈklæsɪfaɪ/",part:69,
   example:"Scientists classify these insects into three different groups.",
   exampleJa:"科学者はこれらの昆虫を、3つの異なるグループに分類する。",
   example2:"The library classified the new books by subject last week.",
   exampleJa2:"図書館は先週、新しい本を主題によって分類した。",
   etymologyProcess:"class（学級）＋ fy（する）→ 同じ組ごとに分けて並べると…？",
   etymologyConclusion:"class（学級）＋ fy（する）→ 似たものを同じ組にまとめ、組ごとに分ける＝分類する",
   relatedWords:[
     {word:"class",meaning:"学級；等級",breakdown:"class（学級）→ 同じ仲間として集められた組"},
     {word:"classroom",meaning:"教室",breakdown:"class（学級）＋ room（部屋）→ 学級が集まる部屋"},
     {word:"classic",meaning:"一流の；古典",breakdown:"class（学級）＋ ic（〜の）→ 最上の組に入る優れたもの"},
     {word:"classification",meaning:"分類",breakdown:"class（学級）＋ fy（する）＋ ation（名詞）→ 組ごとに分けること"}]},

  {id:682,word:"estimate",partOfSpeech:"他動詞",meaning:"推定する，見積もる",
   meanings:["他|（数量や費用を）推定する，見積もる"],
   pronunciation:"/ˈestɪmeɪt/",part:69,
   example:"Experts estimate the cost of the new stadium at ten billion yen.",
   exampleJa:"専門家は新しい競技場の費用を100億円と推定している。",
   example2:"I estimated that the trip would take about five hours.",
   exampleJa2:"私はその旅行が約5時間かかると推定した。",
   etymologyProcess:"estim（値ぶみする）＋ ate（動詞）→ だいたいの値打ちをはかると…？",
   etymologyConclusion:"estim（値ぶみする）＋ ate（動詞）→ 目分量で、だいたいの値打ちや数をはかる＝推定する",
   relatedWords:[
     {word:"aim",meaning:"ねらう；目的",breakdown:"aim（値ぶみする）→ 値ぶみして狙いを定める"},
     {word:"estimation",meaning:"評価，見積もり",breakdown:"estim（値ぶみする）＋ ation（名詞）→ 値ぶみして出した結果"},
     {word:"esteem",meaning:"尊重する；尊敬",breakdown:"estim（値ぶみする）→ 高く値ぶみして大切に思う"},
     {synonym:true,word:"guess",meaning:"推測する",breakdown:"あてずっぽうで当てる。estimate は根拠を持って見積もる"}]},

  {id:683,word:"organize",partOfSpeech:"他動詞",meaning:"まとめる；主催する",
   meanings:["他|（順序よく）まとめる","他|（行事を）主催する"],
   pronunciation:"/ˈɔːrɡənaɪz/",part:69,
   example:"She organized her messy notes into five clear sections.",
   exampleJa:"彼女は散らかったノートを5つの明確な章にまとめた。",
   example2:"Our class will organize a charity concert for the local hospital.",
   exampleJa2:"私たちのクラスは地元の病院のために慈善コンサートを主催する予定だ。",
   etymologyProcess:"organ（道具・器官）＋ ize（する）→ 器官のように役割を配ると…？",
   etymologyConclusion:"organ（道具・器官）＋ ize（する）→ 体の器官のように、それぞれの役割を配って動かす＝まとめる",
   relatedWords:[
     {word:"organ",meaning:"器官；オルガン",breakdown:"organ（道具・器官）→ 決まった働きをする体の部品"},
     {word:"organic",meaning:"有機の；有機栽培の",breakdown:"organ（道具・器官）＋ ic（〜の）→ 生き物の体にかかわる"},
     {word:"organization",meaning:"組織，団体",breakdown:"organ（道具・器官）＋ ize（する）＋ ation（名詞）→ 役割を配って動く集まり"},
     {synonym:true,word:"arrange",meaning:"整える，手配する",breakdown:"順序よく並べる。organize は役割を配って動かす"}]},

  {id:684,word:"recognize",partOfSpeech:"他動詞",meaning:"（前に知っていて）見分ける；認める",
   meanings:["他|（見て）それだと見分ける","他|（正式に）認める"],
   pronunciation:"/ˈrekəɡnaɪz/",part:69,
   example:"I recognized him immediately by his bright red jacket.",
   exampleJa:"私は明るい赤い上着で、すぐに彼を見分けた。",
   example2:"Can you recognize these plants by the shape of their leaves?",
   exampleJa2:"あなたは葉の形でこれらの植物を見分けられますか。",
   etymologyProcess:"re（再び）＋ co（共に）＋ gn（知る）＋ ize（する）→ 前に知った姿と重なると…？",
   etymologyConclusion:"re（再び）＋ co（共に）＋ gn（知る）＋ ize（する）→ 前に知った姿と重なって、それだとわかる＝見分ける",
   relatedWords:[
     {word:"know",meaning:"知っている",breakdown:"know（知る）→ 頭の中にその姿が入っている"},
     {word:"ignore",meaning:"無視する",breakdown:"in（否定）＋ gn（知る）→ 知らないことにして相手にしない"},
     {word:"recognition",meaning:"認識；承認",breakdown:"re（再び）＋ gn（知る）＋ ition（名詞）→ 再び知って認めること"},
     {synonym:true,word:"notice",meaning:"気がつく",breakdown:"変化に気がつく。recognize は前に知ったものだと見分ける"}]},

  {id:685,word:"suppose",partOfSpeech:"他動詞",meaning:"（たぶん）〜だと思う；〜することになっている",
   meanings:["他|（根拠は弱いが）〜だと思う","他|（be supposed to で）〜することになっている"],
   pronunciation:"/səˈpoʊz/",part:69,
   example:"I suppose the train will be late because of the heavy snow.",
   exampleJa:"大雪のせいで電車は遅れるだろうと思う。",
   example2:"You are supposed to wear a uniform at this school.",
   exampleJa2:"この学校では制服を着ることになっている。",
   etymologyProcess:"sub（下で）＋ pos（置く）→ 話の土台を下にそっと置くと…？",
   etymologyConclusion:"sub（下で）＋ pos（置く）→ 話の土台になる考えを、下にそっと置いておく＝〜だと思う",
   relatedWords:[
     {word:"propose",meaning:"提案する",breakdown:"pro（前へ）＋ pos（置く）→ みんなの前へ考えを置いて見せる"},
     {word:"oppose",meaning:"反対する",breakdown:"op（向かい合って）＋ pos（置く）→ 向かい合う位置に自分を置く"},
     {word:"position",meaning:"位置；立場",breakdown:"pos（置く）＋ ition（名詞）→ 置かれている場所"},
     {word:"support",meaning:"支える",breakdown:"sub（下で）＋ port（運ぶ）→ 下から持ち上げて支える"}]},

  {id:686,word:"assume",partOfSpeech:"他動詞",meaning:"（証拠なしに）思い込む；引き受ける",
   meanings:["他|（確かめずに）思い込む","他|（責任や役目を）引き受ける"],
   pronunciation:"/əˈsuːm/",part:69,
   example:"Do not assume that everyone knows the new club rules.",
   exampleJa:"みんなが新しい部のきまりを知っていると思い込んではいけない。",
   example2:"She assumed the letter was from her grandmother in Osaka.",
   exampleJa2:"彼女はその手紙が大阪の祖母からのものだと思い込んだ。",
   etymologyProcess:"ad（〜へ）＋ sume（取る）→ 確かめずに自分のほうへ取り込むと…？",
   etymologyConclusion:"ad（〜へ）＋ sume（取る）→ 確かめないまま、そうだと自分の中へ取り込む＝思い込む",
   relatedWords:[
     {word:"consume",meaning:"消費する",breakdown:"con（すっかり）＋ sume（取る）→ すっかり取り尽くして使い切る"},
     {word:"resume",meaning:"再開する",breakdown:"re（再び）＋ sume（取る）→ 手放したものをもう一度取り上げる"},
     {word:"accept",meaning:"受け入れる",breakdown:"ad（〜へ）＋ cept（取る）→ 自分のほうへ引き取る"},
     {word:"assumption",meaning:"思い込み，前提",breakdown:"ad（〜へ）＋ sume（取る）＋ ion（名詞）→ 確かめずに取り込んだ考え"}]},

  {id:687,word:"care",partOfSpeech:"自動詞",meaning:"気にする；世話をする",
   meanings:["自|（care about で）気にする","自|（care for で）世話をする"],
   pronunciation:"/ker/",part:69,
   example:"I really care about what my friends think of me.",
   exampleJa:"私は友達が自分をどう思うかを本当に気にしている。",
   example2:"She cared for her sick grandfather for many long months.",
   exampleJa2:"彼女は病気の祖父を何か月も世話した。",
   etymologyProcess:"care（心配ごと）→ 心にひっかかって離れないでいると…？",
   etymologyConclusion:"care（心配ごと）→ 心にひっかかって離れず、そのことが頭から消えない＝気にする",
   relatedWords:[
     {word:"careful",meaning:"注意深い",breakdown:"care（心配ごと）＋ ful（満ちた）→ 気がかりでいっぱいで用心する"},
     {word:"careless",meaning:"不注意な",breakdown:"care（心配ごと）＋ less（ない）→ 気がかりがなく、うっかりしている"},
     {word:"caretaker",meaning:"世話をする人，管理人",breakdown:"care（心配ごと）＋ take（取る）＋ er（人）→ 世話を引き受ける人"},
     {synonym:true,word:"mind",meaning:"気にする，いやだと思う",breakdown:"Do you mind? のように気にする。care は大切に思う気持ち"}]},

  {id:688,word:"approve",partOfSpeech:"他動詞・自動詞",meaning:"（正式に）認める；賛成する",
   meanings:["他|（計画などを正式に）認める","自|（approve of で）賛成する"],
   pronunciation:"/əˈpruːv/",part:69,
   example:"The school finally approved our plan for a new club.",
   exampleJa:"学校はついに、私たちの新しい部の計画を認めた。",
   example2:"My parents do not approve of staying out after nine.",
   exampleJa2:"両親は9時以降に外にいることを認めない。",
   etymologyProcess:"ad（〜へ）＋ prove（試す）→ 試してよいものだと太鼓判を押すと…？",
   etymologyConclusion:"ad（〜へ）＋ prove（試す）→ 試したうえで、よいものだと太鼓判を押す＝認める",
   relatedWords:[
     {word:"prove",meaning:"証明する",breakdown:"prove（試す）→ 試して本当だと示す"},
     {word:"disapprove",meaning:"認めない，反対する",breakdown:"dis（否定）＋ ad（〜へ）＋ prove（試す）→ 試してよくないと判断する"},
     {word:"proof",meaning:"証拠",breakdown:"proof（試す）→ 試した結果として残るしるし"},
     {word:"approval",meaning:"承認，賛成",breakdown:"ad（〜へ）＋ prove（試す）＋ al（名詞）→ よいと認めること"}]},

  {id:689,word:"notice",partOfSpeech:"他動詞",meaning:"（変化に）気がつく",
   meanings:["他|（小さな変化に）気がつく"],
   pronunciation:"/ˈnoʊtɪs/",part:69,
   example:"Did you notice the new poster on the classroom wall?",
   exampleJa:"教室の壁の新しいポスターに気がつきましたか。",
   example2:"She noticed a small mistake in the printed schedule.",
   exampleJa2:"彼女は印刷された予定表の小さな誤りに気がついた。",
   etymologyProcess:"nota（しるし）＋ ice（名詞）→ 目や耳にしるしが引っかかると…？",
   etymologyConclusion:"nota（しるし）＋ ice（名詞）→ 目や耳に小さなしるしが引っかかり、心に留まる＝気がつく",
   relatedWords:[
     {word:"note",meaning:"メモ；書き留める",breakdown:"nota（しるし）→ 忘れないように残すしるし"},
     {word:"notebook",meaning:"ノート",breakdown:"nota（しるし）＋ book（本）→ しるしを書きつける本"},
     {word:"notable",meaning:"注目すべき",breakdown:"nota（しるし）＋ able（できる）→ しるしをつけて示せるほど目立つ"},
     {word:"notify",meaning:"知らせる，通知する",breakdown:"nota（しるし）＋ fy（する）→ しるしを示して相手に知らせる"}]},

  {id:690,word:"aware",partOfSpeech:"形容詞",meaning:"（状況に）気づいている",
   meanings:["形|（be aware of で）気づいている"],
   pronunciation:"/əˈwer/",part:69,
   example:"Are you aware of the danger of swimming in this river?",
   exampleJa:"この川で泳ぐ危険に気づいていますか。",
   example2:"Few students were aware that the deadline had already passed.",
   exampleJa2:"締め切りがすでに過ぎていることに気づいている生徒はほとんどいなかった。",
   etymologyProcess:"ware（見張る）→ 周りをずっと見張っていると…？",
   etymologyConclusion:"ware（見張る）→ 周りをずっと見張っていて、状況が頭に入っている＝気づいている",
   relatedWords:[
     {word:"beware",meaning:"用心する",breakdown:"ware（見張る）→ Be ware!（見張っていろ）が一語になった形"},
     {word:"wary",meaning:"用心深い",breakdown:"ware（見張る）＋ y（〜な状態の）→ 用心して目を配っている"},
     {word:"guard",meaning:"守る；警備",breakdown:"gard（見張る）→ 目を配って守る"},
     {synonym:true,word:"conscious",meaning:"意識している",breakdown:"頭ではっきり意識している。aware は状況が目に入っている"}]},

  {id:691,word:"conscious",partOfSpeech:"形容詞",meaning:"（はっきり）意識している",
   meanings:["形|（be conscious of で）意識している"],
   pronunciation:"/ˈkɑːnʃəs/",part:70,
   example:"Many students are conscious of how others see their clothes.",
   exampleJa:"多くの生徒は、他人が自分の服をどう見るかを意識している。",
   example2:"She became conscious of a strange smell in the kitchen.",
   exampleJa2:"彼女は台所の変なにおいを意識するようになった。",
   etymologyProcess:"con（共に）＋ sci（知る）＋ ous（形容詞）→ 頭の中で知っていると…？",
   etymologyConclusion:"con（共に）＋ sci（知る）＋ ous（形容詞）→ 自分に起きていることを頭ではっきり知っている＝意識している",
   relatedWords:[
     {word:"science",meaning:"科学",breakdown:"sci（知る）＋ ence（名詞）→ 筋道を立てて知ること"},
     {word:"conscience",meaning:"良心",breakdown:"con（共に）＋ sci（知る）＋ ence（名詞）→ 善悪を心の中で知る働き"},
     {word:"unconscious",meaning:"意識のない",breakdown:"un（否定）＋ con（共に）＋ sci（知る）→ 頭が何も知らない状態"},
     {synonym:true,word:"aware",meaning:"気づいている",breakdown:"状況が目に入っている。conscious は頭ではっきり意識する"}]},

  {id:692,word:"concerned",partOfSpeech:"形容詞",meaning:"心配している；関わっている",
   meanings:["形|（be concerned about で）心配している","形|（be concerned with で）関わっている"],
   pronunciation:"/kənˈsɜːrnd/",part:70,
   example:"Many parents are concerned about the safety of this road.",
   exampleJa:"多くの親が、この道路の安全を心配している。",
   example2:"The teacher looked concerned when she read my test answers.",
   exampleJa2:"先生は私のテストの答えを読んだとき、心配しているように見えた。",
   etymologyProcess:"con（共に）＋ cern（ふるい分ける）→ ふるいにかけて気になると…？",
   etymologyConclusion:"con（共に）＋ cern（ふるい分ける）→ ふるいにかけて選び出すほど気にかかる＝心配している",
   relatedWords:[
     {word:"concern",meaning:"心配；関わる",breakdown:"con（共に）＋ cern（ふるい分ける）→ ふるい分けて気にかけること"},
     {word:"certain",meaning:"確かな；ある〜",breakdown:"cert（ふるい分ける）＋ ain（〜の）→ ふるい分けてはっきりした"},
     {word:"secret",meaning:"秘密",breakdown:"se（離して）＋ cret（ふるい分ける）→ 選り分けて別にしまったもの"},
     {word:"discern",meaning:"見分ける",breakdown:"dis（バラバラに）＋ cern（ふるい分ける）→ ふるいにかけて違いを見分ける"}]},

  {id:693,word:"regard",partOfSpeech:"他動詞",meaning:"（〜と）みなす",
   meanings:["他|（regard A as B で）みなす"],
   pronunciation:"/rɪˈɡɑːrd/",part:70,
   example:"Many people regard him as the best player in Japan.",
   exampleJa:"多くの人が彼を、日本で最高の選手とみなしている。",
   example2:"The old temple is regarded as a national treasure.",
   exampleJa2:"その古い寺は国宝とみなされている。",
   etymologyProcess:"re（じっと）＋ gard（見張る）→ 相手をじっと見て位置づけると…？",
   etymologyConclusion:"re（じっと）＋ gard（見張る）→ 相手をじっと見て、どういうものかを位置づける＝みなす",
   relatedWords:[
     {word:"guard",meaning:"守る；警備",breakdown:"gard（見張る）→ 目を配って守る"},
     {word:"regarding",meaning:"〜に関して",breakdown:"re（じっと）＋ gard（見張る）＋ ing（〜している）→ そこへ目を向けて"},
     {word:"reward",meaning:"報酬；報いる",breakdown:"re（戻す）＋ ward（見張る）→ よく見て、見合うものを返す"},
     {synonym:true,word:"consider",meaning:"みなす；よく考える",breakdown:"星を見比べて考える。regard は「〜とみなす」の型が中心"}]},

  {id:694,word:"commit",partOfSpeech:"他動詞",meaning:"（身を）ゆだねる，専念する",
   meanings:["他|（commit oneself to で）専念する","他|（罪を）犯す"],
   pronunciation:"/kəˈmɪt/",part:70,
   example:"Students must commit themselves to daily practice to improve quickly.",
   exampleJa:"早く上達するには、生徒は毎日の練習に専念しなければならない。",
   example2:"She committed herself to the volunteer work for three years.",
   exampleJa2:"彼女は3年間、そのボランティア活動に専念した。",
   etymologyProcess:"com（共に）＋ mit（送る）→ 自分の身をまるごと送り渡すと…？",
   etymologyConclusion:"com（共に）＋ mit（送る）→ 自分の身を、まるごと相手や目標のほうへ送り渡す＝ゆだねる",
   relatedWords:[
     {word:"submit",meaning:"提出する；従う",breakdown:"sub（下で）＋ mit（送る）→ 相手の下へ差し出して送る"},
     {word:"permit",meaning:"許可する",breakdown:"per（すっかり）＋ mit（送る）→ 通り抜けさせて先へ送る"},
     {word:"mission",meaning:"任務；使節",breakdown:"mis（送る）＋ ion（名詞）→ 送り出されて負う役目"},
     {word:"commitment",meaning:"献身；約束",breakdown:"com（共に）＋ mit（送る）＋ ment（名詞）→ 身を送り渡して負う約束"}]},

  {id:695,word:"doubt",partOfSpeech:"他動詞",meaning:"（本当かどうか）疑う",
   meanings:["他|（本当かどうか）疑う"],
   pronunciation:"/daʊt/",part:70,
   example:"I doubt that he can finish the report by tomorrow morning.",
   exampleJa:"私は彼が明日の朝までに報告書を終えられるか疑っている。",
   example2:"No one doubted her story until the old photos appeared.",
   exampleJa2:"その古い写真が出てくるまで、誰も彼女の話を疑わなかった。",
   etymologyProcess:"dub（二つ）→ 心が二つに分かれて決めきれないと…？",
   etymologyConclusion:"dub（二つ）→ 心が二つに分かれ、どちらが本当なのか決めきれない＝疑う",
   relatedWords:[
     {word:"double",meaning:"2倍の",breakdown:"dub（二つ）＋ pli（折る）→ 二つに折り重ねて2倍にする"},
     {word:"doubtful",meaning:"疑わしい",breakdown:"dub（二つ）＋ ful（満ちた）→ 迷いでいっぱいの"},
     {word:"undoubtedly",meaning:"疑いなく",breakdown:"un（否定）＋ dub（二つ）＋ ly（副詞）→ 迷いが少しもなく"},
     {synonym:true,word:"suspect",meaning:"（悪いと）疑う",breakdown:"下からのぞき見て怪しむ。doubt は本当かどうかを疑う"}]},

  {id:696,word:"memorize",partOfSpeech:"他動詞",meaning:"暗記する",
   meanings:["他|（そのまま）暗記する"],
   pronunciation:"/ˈmeməraɪz/",part:70,
   example:"We had to memorize twenty English words every single day.",
   exampleJa:"私たちは毎日20個の英単語を暗記しなければならなかった。",
   example2:"He memorized the whole speech in only three days.",
   exampleJa2:"彼はたった3日でスピーチ全体を暗記した。",
   etymologyProcess:"memor（心にとどめる）＋ ize（する）→ そっくり心に刻みつけると…？",
   etymologyConclusion:"memor（心にとどめる）＋ ize（する）→ 言葉をそのまま心に刻みつけて離さない＝暗記する",
   relatedWords:[
     {word:"memory",meaning:"記憶",breakdown:"memor（心にとどめる）＋ y（名詞）→ 心にとどめてある中身"},
     {word:"remember",meaning:"覚えている，思い出す",breakdown:"re（再び）＋ memor（心にとどめる）→ もう一度心に呼び戻す"},
     {word:"memorial",meaning:"記念の；記念碑",breakdown:"memor（心にとどめる）＋ al（〜の）→ 心にとどめるためのもの"},
     {synonym:true,word:"learn",meaning:"覚える，学ぶ",breakdown:"学んで身につける。memorize は丸ごと覚え込む"}]},

  {id:697,word:"forgive",partOfSpeech:"他動詞",meaning:"許す",
   meanings:["他|（あやまちを）許す"],
   pronunciation:"/fərˈɡɪv/",part:70,
   example:"I will never forgive him for telling such a cruel lie.",
   exampleJa:"そんな残酷なうそをついた彼を、私は決して許さない。",
   example2:"Please forgive me for arriving late at your birthday party.",
   exampleJa2:"誕生日会に遅れて着いたことを許してください。",
   etymologyProcess:"for（打ち消し）＋ give（与える）→ 借りを数えるのをやめると…？",
   etymologyConclusion:"for（打ち消し）＋ give（与える）→ 相手の借りをなかったことにして、すっかり手放す＝許す",
   relatedWords:[
     {word:"give",meaning:"与える",breakdown:"give（与える）→ 自分の手から相手の手へ渡す"},
     {word:"forget",meaning:"忘れる",breakdown:"for（打ち消し）＋ get（つかむ）→ つかんでいたものを手放す"},
     {word:"forgiveness",meaning:"許し",breakdown:"for（打ち消し）＋ give（与える）＋ ness（名詞）→ 借りを手放すこと"},
     {synonym:true,word:"excuse",meaning:"大目に見る；言い訳",breakdown:"責めを外してやる。forgive は心から許す重い語"}]},

  {id:698,word:"grant",partOfSpeech:"他動詞",meaning:"（正式に）与える；認める",
   meanings:["他|（許可や権利を正式に）与える","他|（take A for granted で）当然と思う"],
   pronunciation:"/ɡrænt/",part:70,
   example:"The city granted permission to hold the festival downtown.",
   exampleJa:"市は町なかで祭りを開く許可を与えた。",
   example2:"We often take our parents' support for granted.",
   exampleJa2:"私たちはしばしば、親の支えを当然のことと思っている。",
   etymologyProcess:"grant（承知して与える）→ 願いを聞き入れて正式に渡すと…？",
   etymologyConclusion:"grant（承知して与える）→ 相手の願いを聞き入れ、正式に認めて渡す＝与える",
   hook:"take A for granted（Aを当然と思う）の形が最重要。「もらって当たり前」。",
   relatedWords:[
     {synonym:true,word:"permit",meaning:"許可する",breakdown:"通してよいと許す。grant は願いを聞き入れて正式に与える"},
     {synonym:true,word:"admit",meaning:"認める",breakdown:"中へ入れて認める。grant は相手の言い分を認めて渡す"},
     {synonym:true,word:"award",meaning:"賞を与える",breakdown:"審査して賞を与える。grant はお金や権利を正式に与える"},
     {synonym:true,word:"offer",meaning:"申し出る",breakdown:"自分から差し出す。grant は相手の願いに応じて与える"}]},

  {id:699,word:"recall",partOfSpeech:"他動詞",meaning:"（意識して）思い出す",
   meanings:["他|（記憶を）意識して思い出す"],
   pronunciation:"/rɪˈkɔːl/",part:70,
   example:"I cannot recall the name of that old song now.",
   exampleJa:"私は今、あの古い歌の名前を思い出せない。",
   example2:"She recalled the summer days she spent at her grandparents' house.",
   exampleJa2:"彼女は祖父母の家で過ごした夏の日々を思い出した。",
   etymologyProcess:"re（再び）＋ call（呼ぶ）→ 遠ざかった記憶を呼び戻すと…？",
   etymologyConclusion:"re（再び）＋ call（呼ぶ）→ 遠くへ行ってしまった記憶を、もう一度呼び戻す＝思い出す",
   relatedWords:[
     {word:"call",meaning:"呼ぶ；電話する",breakdown:"call（呼ぶ）→ 声を出して相手を引き寄せる"},
     {word:"calling",meaning:"天職；呼び声",breakdown:"call（呼ぶ）＋ ing（名詞）→ 呼ばれて就くべき務め"},
     {synonym:true,word:"remember",meaning:"覚えている，思い出す",breakdown:"覚えている状態も表す。recall は意識して呼び戻す"},
     {synonym:true,word:"remind",meaning:"思い出させる",breakdown:"相手に思い出させる。recall は自分で思い出す"}]},

  {id:700,word:"outlook",partOfSpeech:"名詞",meaning:"（ものの）考え方；見通し",
   meanings:["名|（ものの）考え方，見方","名|（先の）見通し"],
   pronunciation:"/ˈaʊtlʊk/",part:70,
   example:"Travel abroad can completely change a young person's outlook.",
   exampleJa:"海外旅行は、若者の考え方を完全に変えることがある。",
   example2:"The economic outlook for next year looks rather dark.",
   exampleJa2:"来年の経済の見通しは、かなり暗そうだ。",
   etymologyProcess:"out（外へ）＋ look（見る）→ 高い窓から外を見わたすと…？",
   etymologyConclusion:"out（外へ）＋ look（見る）→ 高いところから外を見わたして得られる眺めと見方＝考え方",
   relatedWords:[
     {word:"look",meaning:"見る；様子",breakdown:"look（見る）→ 目を向けて確かめる"},
     {word:"overlook",meaning:"見落とす；見渡す",breakdown:"over（越えて）＋ look（見る）→ 上を通り越して見てしまう"},
     {word:"outcome",meaning:"結果",breakdown:"out（外へ）＋ come（来る）→ 外へ出てきたもの"},
     {word:"outstanding",meaning:"傑出した",breakdown:"out（外へ）＋ sta（立つ）＋ ing（〜している）→ 外へ抜き出て立っている"}]},

  {id:701,word:"perspective",partOfSpeech:"名詞",meaning:"（ものの）見方，視点",
   meanings:["名|（ものの）見方，視点","名|（絵の）遠近法"],
   pronunciation:"/pərˈspektɪv/",part:71,
   example:"Reading history gives us a wider perspective on today's problems.",
   exampleJa:"歴史を読むことは、今日の問題についてより広い視点を与えてくれる。",
   example2:"Try to see this issue from your friend's perspective.",
   exampleJa2:"この問題を、友達の視点から見るようにしなさい。",
   etymologyProcess:"per（すっかり）＋ spect（見る）→ 奥行きまで見通せる立ち位置は…？",
   etymologyConclusion:"per（すっかり）＋ spect（見る）→ 奥行きまで見通せる、その人の立ち位置と見方＝視点",
   relatedWords:[
     {word:"inspect",meaning:"点検する",breakdown:"in（中へ）＋ spect（見る）→ 中までのぞき込んで調べる"},
     {word:"respect",meaning:"尊敬する",breakdown:"re（再び）＋ spect（見る）→ 何度も見直すほど価値を認める"},
     {word:"expect",meaning:"予期する",breakdown:"ex（外へ）＋ spect（見る）→ 外を見ながら来るのを待つ"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ ator（人）→ 見るために集まった人"}]},

  {id:702,word:"abandon",partOfSpeech:"他動詞",meaning:"見捨てる，捨て去る",
   meanings:["他|（人や場所を）見捨てる","他|（計画などを）捨て去る"],
   pronunciation:"/əˈbændən/",part:71,
   example:"They abandoned the old house after the big earthquake.",
   exampleJa:"彼らは大地震のあと、その古い家を見捨てた。",
   example2:"Never abandon your dream just because someone laughs at it.",
   exampleJa2:"誰かに笑われたというだけで、夢を見捨ててはいけない。",
   etymologyProcess:"ad（〜へ）＋ ban（公に言い渡す）→ 好きにしてよいと言い放つと…？",
   etymologyConclusion:"ad（〜へ）＋ ban（公に言い渡す）→ 好きにしてよいと公に言い放ち、手を放す＝見捨てる",
   relatedWords:[
     {word:"ban",meaning:"禁止する；禁止",breakdown:"ban（公に言い渡す）→ 公の場でだめだと言い渡す"},
     {word:"banish",meaning:"追放する",breakdown:"ban（公に言い渡す）＋ ish（〜にする）→ 出て行けと公に言い渡して追い出す"},
     {word:"abandonment",meaning:"放棄，遺棄",breakdown:"ad（〜へ）＋ ban（公に言い渡す）＋ ment（名詞）→ 手を放して捨てること"},
     {synonym:true,word:"desert",meaning:"見捨てる；砂漠",breakdown:"人を置き去りにする。abandon は物や計画も捨てる"}]},

  {id:703,word:"eliminate",partOfSpeech:"他動詞",meaning:"（不要なものを）排除する",
   meanings:["他|（不要なものを）排除する，取り除く"],
   pronunciation:"/ɪˈlɪmɪneɪt/",part:71,
   example:"The new machine eliminates most of the noise in the room.",
   exampleJa:"その新しい機械は、部屋の騒音の大半を排除する。",
   example2:"We should eliminate plastic bags from our daily life.",
   exampleJa2:"私たちは日常生活からレジ袋を排除すべきだ。",
   etymologyProcess:"e（外へ）＋ limin（敷居）＋ ate（動詞）→ 家の敷居の外へ追い出すと…？",
   etymologyConclusion:"e（外へ）＋ limin（敷居）＋ ate（動詞）→ 家の敷居の外へ追い出して、中に残さない＝排除する",
   relatedWords:[
     {word:"limit",meaning:"限界；制限する",breakdown:"limit（境の土手）→ ここまでという境の線"},
     {word:"preliminary",meaning:"予備の；予選",breakdown:"pre（先に）＋ limin（敷居）＋ ary（形容詞）→ 敷居をまたぐ前の"},
     {word:"elimination",meaning:"排除，除去",breakdown:"e（外へ）＋ limin（敷居）＋ ation（名詞）→ 外へ追い出すこと"},
     {synonym:true,word:"remove",meaning:"取り除く",breakdown:"その場から動かして取り除く。eliminate は完全になくす"}]},

  {id:704,word:"rid",partOfSpeech:"他動詞",meaning:"（じゃまなものを）処分する",
   meanings:["他|（get rid of で）処分する，厄介払いする"],
   pronunciation:"/rɪd/",part:71,
   example:"We must get rid of these broken chairs before Monday.",
   exampleJa:"月曜までに、これらの壊れたいすを処分しなければならない。",
   example2:"She wanted to rid her room of all the old magazines.",
   exampleJa2:"彼女は部屋から古い雑誌を全部処分したかった。",
   etymologyProcess:"rid（払いのける）→ じゃまなものをさっと払いのけると…？",
   etymologyConclusion:"rid（払いのける）→ 土地の木を切り払うように、じゃまなものを払いのける＝処分する",
   hook:"get rid of A（Aを処分する）がほぼすべて。be rid of なら「もう無い」。",
   relatedWords:[
     {word:"riddance",meaning:"厄介払い",breakdown:"rid（払いのける）＋ ance（名詞）→ じゃまを払いのけること"},
     {synonym:true,word:"remove",meaning:"取り除く",breakdown:"その場から動かす。rid はじゃま者を追い払う感じ"},
     {synonym:true,word:"clear",meaning:"片づける；澄んだ",breakdown:"じゃまを除いてすっきりさせる。rid と近い動き"},
     {synonym:true,word:"discard",meaning:"捨てる",breakdown:"いらない札を捨てる。get rid of は捨てる以外の方法も含む"}]},

  {id:705,word:"remove",partOfSpeech:"他動詞",meaning:"（その場から）取り除く",
   meanings:["他|（その場から）取り除く，移す"],
   pronunciation:"/rɪˈmuːv/",part:71,
   example:"Please remove all the books from the top shelf.",
   exampleJa:"いちばん上の棚から、本をすべて取り除いてください。",
   example2:"The stain was removed with a special cleaning liquid.",
   exampleJa2:"そのしみは、特別な洗浄液で取り除かれた。",
   etymologyProcess:"re（後ろへ）＋ mov（動かす）→ 元の場所から動かして遠ざけると…？",
   etymologyConclusion:"re（後ろへ）＋ mov（動かす）→ 今ある場所から動かして、そこから遠ざける＝取り除く",
   relatedWords:[
     {word:"move",meaning:"動く，動かす",breakdown:"mov（動かす）→ 場所や人の心を動かす"},
     {word:"movement",meaning:"動き；運動",breakdown:"mov（動かす）＋ ment（名詞）→ 動くこと、動かす働き"},
     {word:"motive",meaning:"動機",breakdown:"motive（動かす）→ 人の心を動かすもと"},
     {word:"removal",meaning:"除去，撤去",breakdown:"re（後ろへ）＋ mov（動かす）＋ al（名詞）→ 動かして遠ざけること"}]},

  {id:706,word:"resource",partOfSpeech:"名詞",meaning:"資源；（使える）手だて",
   meanings:["名|（天然の）資源","名|（使える）手だて，財源"],
   pronunciation:"/ˈriːsɔːrs/",part:71,
   example:"Japan has few natural resources, so it imports a lot.",
   exampleJa:"日本は天然資源が少ないので、多くを輸入している。",
   example2:"Water is the most important resource for every living thing.",
   exampleJa2:"水はすべての生き物にとって、最も重要な資源だ。",
   etymologyProcess:"re（再び）＋ source（わき出る）→ 泉のように何度もわき出ると…？",
   etymologyConclusion:"re（再び）＋ source（わき出る）→ 泉のように何度でもわき出て、人を助けるもの＝資源",
   relatedWords:[
     {word:"source",meaning:"源，出どころ",breakdown:"source（わき出る）→ 水がわき出るもとの場所"},
     {word:"resourceful",meaning:"機転がきく",breakdown:"re（再び）＋ source（わき出る）＋ ful（満ちた）→ 手だてが次々わき出る"},
     {synonym:true,word:"material",meaning:"材料，原料",breakdown:"物を作るもと。resource は使える元手全体を指す"},
     {synonym:true,word:"supply",meaning:"供給する；供給",breakdown:"必要なものを届ける。resource はその元になるもの"}]},

  {id:707,word:"conservation",partOfSpeech:"名詞",meaning:"（自然の）保護，保全",
   meanings:["名|（自然や資源の）保護，保全"],
   pronunciation:"/ˌkɑːnsərˈveɪʃn/",part:71,
   example:"Forest conservation is a serious problem in many countries today.",
   exampleJa:"森林の保護は、今日多くの国で深刻な問題だ。",
   example2:"Our club joined a river conservation project last summer.",
   exampleJa2:"私たちの部は昨年の夏、川の保護計画に加わった。",
   etymologyProcess:"con（すっかり）＋ serv（守る）＋ ation（名詞）→ 手をつけずに守り抜くと…？",
   etymologyConclusion:"con（すっかり）＋ serv（守る）＋ ation（名詞）→ 自然や資源に手をつけず、そのまま守り抜くこと＝保護",
   relatedWords:[
     {word:"conserve",meaning:"保存する，節約する",breakdown:"con（すっかり）＋ serv（守る）→ 減らさずにすっかり守る"},
     {word:"observe",meaning:"観察する；守る",breakdown:"ob（〜に向かって）＋ serv（守る）→ 目を向けてじっと見守る"},
     {word:"service",meaning:"奉仕，サービス",breakdown:"serv（仕える）＋ ice（名詞）→ 人に仕えてする働き"},
     {word:"reserve",meaning:"予約する；取っておく",breakdown:"re（後ろへ）＋ serv（守る）→ 後ろに取りのけて守っておく"}]},

  {id:708,word:"preserve",partOfSpeech:"他動詞",meaning:"（もとの姿のまま）保存する",
   meanings:["他|（傷まないように）保存する","他|（伝統や自然を）守る"],
   pronunciation:"/prɪˈzɜːrv/",part:71,
   example:"Salt was used to preserve meat before refrigerators existed.",
   exampleJa:"冷蔵庫がある前は、肉を保存するのに塩が使われた。",
   example2:"This town preserves many wooden houses from the Edo period.",
   exampleJa2:"この町は江戸時代の木造家屋を数多く保存している。",
   etymologyProcess:"pre（先に）＋ serv（守る）→ 傷む前に先回りして守ると…？",
   etymologyConclusion:"pre（先に）＋ serv（守る）→ 傷む前に先回りして守り、もとの姿のまま保つ＝保存する",
   relatedWords:[
     {word:"preservation",meaning:"保存，保護",breakdown:"pre（先に）＋ serv（守る）＋ ation（名詞）→ 先回りして守ること"},
     {word:"deserve",meaning:"値する",breakdown:"de（すっかり）＋ serv（仕える）→ すっかり仕えて受けるに値する"},
     {word:"servant",meaning:"使用人",breakdown:"serv（仕える）＋ ant（人）→ 人に仕える人"},
     {synonym:true,word:"keep",meaning:"保つ，取っておく",breakdown:"そのまま持ち続ける。preserve は傷まないように守る"}]},

  {id:709,word:"disaster",partOfSpeech:"名詞",meaning:"災害，大惨事",
   meanings:["名|（地震などの）災害，大惨事"],
   pronunciation:"/dɪˈzæstər/",part:71,
   example:"The earthquake was the worst natural disaster in our history.",
   exampleJa:"その地震は、我が国の歴史で最悪の自然災害だった。",
   example2:"Many volunteers helped the people after the disaster last year.",
   exampleJa2:"昨年の災害のあと、多くのボランティアが人々を助けた。",
   etymologyProcess:"dis（離れて）＋ aster（星）→ 幸運の星が離れてしまうと…？",
   etymologyConclusion:"dis（離れて）＋ aster（星）→ 幸運の星が離れてしまったために起きる大事故＝災害",
   relatedWords:[
     {word:"star",meaning:"星；スター",breakdown:"star（星）→ 夜空に光る星。aster と同じ家族の語"},
     {word:"disastrous",meaning:"悲惨な",breakdown:"dis（離れて）＋ aster（星）＋ ous（形容詞）→ 星に見放されたような"},
     {word:"astronomy",meaning:"天文学",breakdown:"astro（星）＋ nom（決まり）＋ y（名詞）→ 星の決まりを調べる学問"},
     {synonym:true,word:"accident",meaning:"事故",breakdown:"思いがけず落ちてくる出来事。disaster は被害がはるかに大きい"}]},

  {id:710,word:"planet",partOfSpeech:"名詞",meaning:"惑星",
   meanings:["名|（太陽のまわりを回る）惑星"],
   pronunciation:"/ˈplænɪt/",part:71,
   example:"Mars is the fourth planet from the sun in our system.",
   exampleJa:"火星は、私たちの星系で太陽から4番目の惑星だ。",
   example2:"Scientists are searching for planets similar to the Earth.",
   exampleJa2:"科学者は、地球に似た惑星を探している。",
   etymologyProcess:"planet（さまよう星）→ 空の中をふらふら動いて見えると…？",
   etymologyConclusion:"planet（さまよう星）→ 決まった場所にとどまらず、空をさまよって見える星＝惑星",
   hook:"ギリシャ語で「さまよう者」。夜空で位置を変えるから「惑う星」。",
   relatedWords:[
     {synonym:true,word:"star",meaning:"星",breakdown:"自分で光る星。planet はその光を受けて回る星"},
     {synonym:true,word:"satellite",meaning:"衛星",breakdown:"惑星のまわりを回る星。planet は太陽のまわりを回る"},
     {synonym:true,word:"orbit",meaning:"軌道",breakdown:"planet が通っていく輪のような道すじ"},
     {synonym:true,word:"universe",meaning:"宇宙",breakdown:"すべてを一つに合わせたもの。planet はその中の一つ"}]},

  {id:711,word:"environment",partOfSpeech:"名詞",meaning:"環境",
   meanings:["名|（自然の）環境","名|（人を取り巻く）環境，状況"],
   pronunciation:"/ɪnˈvaɪrənmənt/",part:72,
   example:"We must protect the environment for future generations.",
   exampleJa:"私たちは未来の世代のために環境を守らなければならない。",
   example2:"A quiet environment helps me concentrate on my homework.",
   exampleJa2:"静かな環境は、私が宿題に集中するのを助けてくれる。",
   etymologyProcess:"en（中に）＋ viron（輪）＋ ment（名詞）→ ぐるりと輪で囲まれた中は…？",
   etymologyConclusion:"en（中に）＋ viron（輪）＋ ment（名詞）→ 自分をぐるりと取り囲んでいるもの全体＝環境",
   relatedWords:[
     {word:"environmental",meaning:"環境の",breakdown:"en（中に）＋ viron（輪）＋ ment（名詞）＋ al（〜の）→ 取り囲むものの"},
     {word:"surround",meaning:"取り囲む",breakdown:"super（上から）＋ und（波打つ）→ 波のように周りへ広がって囲む"},
     {word:"enclose",meaning:"同封する；囲む",breakdown:"en（中に）＋ clos（閉じる）→ 囲いの中へ入れて閉じる"},
     {synonym:true,word:"surroundings",meaning:"周囲の状況",breakdown:"身のまわりのもの。environment は自然も含む広い語"}]},

  {id:712,word:"horizon",partOfSpeech:"名詞",meaning:"水平線，地平線",
   meanings:["名|（空と大地の境の）水平線，地平線"],
   pronunciation:"/həˈraɪzn/",part:72,
   example:"The sun slowly sank below the horizon over the sea.",
   exampleJa:"太陽は海の向こうの水平線の下へ、ゆっくり沈んだ。",
   example2:"We watched a small ship appear on the distant horizon.",
   exampleJa2:"私たちは遠い水平線に小さな船が現れるのを見た。",
   etymologyProcess:"horiz（境を定める）→ 空と海の境をぐるりと定めると…？",
   etymologyConclusion:"horiz（境を定める）→ 空と大地や海との境を、ぐるりと丸く定める線＝水平線",
   relatedWords:[
     {word:"horizontal",meaning:"水平の",breakdown:"horiz（境を定める）＋ al（〜の）→ 水平線のようにまっすぐ横の"},
     {synonym:true,word:"skyline",meaning:"空を背にした輪郭",breakdown:"空と建物の境の線。horizon は空と大地の境"},
     {synonym:true,word:"border",meaning:"境界，国境",breakdown:"土地と土地の境。horizon は目に見える空との境"},
     {synonym:true,word:"edge",meaning:"へり，端",breakdown:"ものの端。horizon は見わたせる限りの端"}]},

  {id:713,word:"layer",partOfSpeech:"名詞",meaning:"層，重なり",
   meanings:["名|（積み重なった）層，ひと重ね"],
   pronunciation:"/ˈleɪər/",part:72,
   example:"A thick layer of snow covered the school playground.",
   exampleJa:"厚い雪の層が、学校の運動場を覆っていた。",
   example2:"This cake has three layers of fresh cream inside.",
   exampleJa2:"このケーキの中には、3つの生クリームの層がある。",
   etymologyProcess:"lay（置く）＋ er（もの）→ 平らに置いたものが重なると…？",
   etymologyConclusion:"lay（置く）＋ er（もの）→ 平らに置いたものが、上へ上へと重なったひと重ね＝層",
   relatedWords:[
     {word:"lay",meaning:"置く，横たえる",breakdown:"lay（置く）→ 平らに寝かせて置く"},
     {word:"lie",meaning:"横たわる；ある",breakdown:"lay（置く）→ 自分から平らに横たわる"},
     {word:"law",meaning:"法律",breakdown:"law（置かれたもの）→ みなの前に置かれた決まり"},
     {synonym:true,word:"level",meaning:"水準；平らな",breakdown:"高さの段階。layer は重なった一枚一枚のこと"}]},

  {id:714,word:"agriculture",partOfSpeech:"名詞",meaning:"農業",
   meanings:["名|（作物を育てる）農業"],
   pronunciation:"/ˈæɡrɪˌkʌltʃər/",part:72,
   example:"In this small village, agriculture is still the main industry.",
   exampleJa:"この小さな村では、農業がいまだに主要な産業だ。",
   example2:"Modern agriculture uses machines and computers to grow rice.",
   exampleJa2:"現代の農業は、米を育てるのに機械とコンピューターを使う。",
   etymologyProcess:"agri（畑）＋ cult（耕す）＋ ure（名詞）→ 畑を耕して育てる仕事は…？",
   etymologyConclusion:"agri（畑）＋ cult（耕す）＋ ure（名詞）→ 畑を耕して作物を育てる仕事＝農業",
   relatedWords:[
     {word:"culture",meaning:"文化；栽培",breakdown:"cult（耕す）＋ ure（名詞）→ 心や土地を耕して育てたもの"},
     {word:"cultivate",meaning:"耕す；育てる",breakdown:"cult（耕す）＋ ate（動詞）→ 土を耕して作物を育てる"},
     {word:"agricultural",meaning:"農業の",breakdown:"agri（畑）＋ cult（耕す）＋ al（〜の）→ 畑を耕すことに関する"},
     {synonym:true,word:"farming",meaning:"農業，農作業",breakdown:"日常語での農業。agriculture は産業としての言い方"}]},

  {id:715,word:"crop",partOfSpeech:"名詞",meaning:"作物；収穫高",
   meanings:["名|（畑で育てる）作物","名|（一度の）収穫高"],
   pronunciation:"/krɑːp/",part:72,
   example:"Rice is the most important crop in this warm region.",
   exampleJa:"米は、この暖かい地域で最も重要な作物だ。",
   example2:"Bad weather destroyed most of the crops last summer.",
   exampleJa2:"悪天候が昨年の夏、作物の大半をだめにした。",
   etymologyProcess:"crop（植物の先っぽ）→ 実った先っぽを刈り取ると…？",
   etymologyConclusion:"crop（植物の先っぽ）→ 実った先っぽを刈り取って手に入れるもの＝作物",
   hook:"髪型の「クロップ」も「刈り込んだ先」。crop up なら「ひょっこり出る」。",
   relatedWords:[
     {synonym:true,word:"harvest",meaning:"収穫；収穫する",breakdown:"刈り入れの作業と時期。crop は刈り取られる作物そのもの"},
     {synonym:true,word:"grain",meaning:"穀物，粒",breakdown:"米や麦の粒。crop は畑で育てるもの全般"},
     {synonym:true,word:"field",meaning:"畑，野原",breakdown:"作物を育てる場所。crop はそこで採れるもの"},
     {synonym:true,word:"produce",meaning:"農産物；生産する",breakdown:"売り物としての農産物。crop は畑に立っている作物"}]},

  {id:716,word:"soil",partOfSpeech:"名詞",meaning:"土，土壌",
   meanings:["名|（作物が育つ）土，土壌"],
   pronunciation:"/sɔɪl/",part:72,
   example:"This rich soil is perfect for growing sweet tomatoes.",
   exampleJa:"この豊かな土は、甘いトマトを育てるのにうってつけだ。",
   example2:"Heavy rain washed away the soil from the steep hillside.",
   exampleJa2:"大雨が、急な丘の斜面から土を洗い流した。",
   etymologyProcess:"soil（地面）→ 作物が根を張る足の下の地面は…？",
   etymologyConclusion:"soil（地面）→ 作物が根を張る、足の下に広がる地面そのもの＝土",
   hook:"畑の「土」。同じ綴りで「汚す」という別の語もあるので注意。",
   relatedWords:[
     {synonym:true,word:"ground",meaning:"地面",breakdown:"足で踏む面。soil は作物を育てる土の中身"},
     {synonym:true,word:"earth",meaning:"土；地球",breakdown:"大地そのもの。soil は農業で言う「土壌」"},
     {synonym:true,word:"mud",meaning:"泥",breakdown:"水を含んだ土。soil は乾いた土も指す"},
     {synonym:true,word:"sand",meaning:"砂",breakdown:"細かい粒ばかりの土。soil は養分を含む"}]},

  {id:717,word:"weed",partOfSpeech:"名詞",meaning:"雑草",
   meanings:["名|（勝手に生える）雑草"],
   pronunciation:"/wiːd/",part:72,
   example:"We pulled up the weeds around the school flower bed.",
   exampleJa:"私たちは学校の花壇の周りの雑草を抜いた。",
   example2:"A single weed can spread across a whole field quickly.",
   exampleJa2:"1本の雑草が、あっという間に畑全体に広がることがある。",
   etymologyProcess:"weed（雑草）→ 頼まないのにどんどん生えてくる草は…？",
   etymologyConclusion:"weed（雑草）→ 植えてもいないのに、畑にどんどん生えてくる草＝雑草",
   hook:"weed out A で「Aをふるい落とす」。雑草を抜くイメージから。",
   relatedWords:[
     {synonym:true,word:"grass",meaning:"草，芝生",breakdown:"生えている草一般。weed は「じゃまな草」"},
     {synonym:true,word:"plant",meaning:"植物；植える",breakdown:"植物全体。weed は植えていないのに生える草"},
     {synonym:true,word:"root",meaning:"根",breakdown:"weed は root ごと抜かないと、またすぐ生える"},
     {synonym:true,word:"garden",meaning:"庭，菜園",breakdown:"手入れする場所。weed はそこに勝手に入り込む草"}]},

  {id:718,word:"pollen",partOfSpeech:"名詞",meaning:"花粉",
   meanings:["名|（花が作る）花粉"],
   pronunciation:"/ˈpɑːlən/",part:72,
   example:"Many people sneeze when the pollen count is very high.",
   exampleJa:"花粉の量がとても多いとき、多くの人がくしゃみをする。",
   example2:"Bees carry pollen from one flower to another all day.",
   exampleJa2:"ミツバチは一日中、花粉をある花から別の花へ運ぶ。",
   etymologyProcess:"pollen（細かい粉）→ 花が風に乗せて飛ばす粉は…？",
   etymologyConclusion:"pollen（細かい粉）→ 花が風や虫に乗せて飛ばす、こまかい黄色い粉＝花粉",
   relatedWords:[
     {word:"pollinate",meaning:"受粉させる",breakdown:"pollen（細かい粉）＋ ate（動詞）→ 花粉を運んでめしべにつける"},
     {synonym:true,word:"dust",meaning:"ほこり，粉",breakdown:"細かい粉一般。pollen は花が作る粉"},
     {synonym:true,word:"allergy",meaning:"アレルギー",breakdown:"pollen allergy で花粉症。体が過剰に反応すること"},
     {synonym:true,word:"blossom",meaning:"花；花が咲く",breakdown:"咲いた花。pollen はその花が作る粉"}]},

  {id:719,word:"drown",partOfSpeech:"自動詞",meaning:"溺れ死ぬ",
   meanings:["自|（水に沈んで）溺れ死ぬ"],
   pronunciation:"/draʊn/",part:72,
   example:"Two swimmers almost drowned in the river last summer.",
   exampleJa:"昨年の夏、2人の泳ぎ手が川で溺れ死ぬところだった。",
   example2:"Never swim alone, or you may drown in deep water.",
   exampleJa2:"決して一人で泳いではいけない。深い水で溺れ死ぬかもしれない。",
   etymologyProcess:"drown（水に沈める）→ 水の中で息ができなくなると…？",
   etymologyConclusion:"drown（水に沈める）→ 水の中に沈んだまま、息ができなくなる＝溺れ死ぬ",
   hook:"drink と同じ家族の語。「水をのみ込んでしまう」イメージでつながる。",
   relatedWords:[
     {synonym:true,word:"sink",meaning:"沈む",breakdown:"水の中へ沈む。drown は息ができなくなること"},
     {synonym:true,word:"rescue",meaning:"救助する",breakdown:"溺れた人を助け出す。drown はその前の危ない状態"},
     {synonym:true,word:"flood",meaning:"洪水；あふれる",breakdown:"水があふれる。drown は水に沈んで死ぬこと"},
     {synonym:true,word:"breathe",meaning:"呼吸する",breakdown:"drown は水の中で breathe できなくなること"}]},

  {id:720,word:"leak",partOfSpeech:"他動詞・自動詞",meaning:"漏れる；漏らす",
   meanings:["自|（水やガスが）漏れる","他|（秘密を）漏らす"],
   pronunciation:"/liːk/",part:72,
   example:"Water is leaking from the old pipe under the sink.",
   exampleJa:"流しの下の古い管から水が漏れている。",
   example2:"Someone leaked the test questions to the students last week.",
   exampleJa2:"先週、誰かが試験問題を生徒たちに漏らした。",
   etymologyProcess:"leak（すき間から漏れる）→ 小さな穴から少しずつこぼれると…？",
   etymologyConclusion:"leak（すき間から漏れる）→ 小さな穴やすき間から、中身が少しずつこぼれ出る＝漏れる",
   hook:"情報が「リーク」されるのも同じ語。穴からじわじわ出るイメージ。",
   relatedWords:[
     {word:"leakage",meaning:"漏れ，漏出",breakdown:"leak（すき間から漏れる）＋ age（名詞）→ 漏れ出ること"},
     {synonym:true,word:"drip",meaning:"したたる",breakdown:"ぽたぽた落ちる。leak はすき間から漏れ出ること"},
     {synonym:true,word:"spill",meaning:"こぼす",breakdown:"容器からこぼす。leak はすき間から勝手に出る"},
     {synonym:true,word:"pour",meaning:"注ぐ",breakdown:"わざと注ぐ。leak は意図せず出てしまう"}]},

  {id:721,word:"climate",partOfSpeech:"名詞",meaning:"気候",
   meanings:["名|（その土地の長期的な）気候"],
   pronunciation:"/ˈklaɪmət/",part:73,
   example:"The climate of this island is warm and very wet.",
   exampleJa:"この島の気候は暖かく、とても雨が多い。",
   example2:"Rapid climate change is affecting farmers all over the world.",
   exampleJa2:"急激な気候の変化が、世界中の農家に影響を与えている。",
   etymologyProcess:"clim（傾き）＋ ate（名詞）→ 地球の傾きで土地ごとに変わるのは…？",
   etymologyConclusion:"clim（傾き）＋ ate（名詞）→ 地球の傾きで土地ごとに決まる、長い目で見た天気＝気候",
   relatedWords:[
     {word:"climatic",meaning:"気候の",breakdown:"clim（傾き）＋ ic（〜の）→ 土地ごとの天気に関する"},
     {synonym:true,word:"weather",meaning:"天気",breakdown:"その日その日の天気。climate は何十年もの平均"},
     {synonym:true,word:"temperature",meaning:"気温，温度",breakdown:"暑さ寒さの度合い。climate はもっと広い天気の性格"},
     {synonym:true,word:"season",meaning:"季節",breakdown:"一年の区切り。climate は土地全体の天気の傾向"}]},

  {id:722,word:"atmosphere",partOfSpeech:"名詞",meaning:"大気；雰囲気",
   meanings:["名|（地球を包む）大気","名|（その場の）雰囲気"],
   pronunciation:"/ˈætməsfɪr/",part:73,
   example:"Carbon dioxide in the atmosphere keeps the earth warm.",
   exampleJa:"大気中の二酸化炭素が、地球を暖かく保っている。",
   example2:"The atmosphere in the classroom became very tense before the test.",
   exampleJa2:"テストの前、教室の雰囲気はとても張りつめたものになった。",
   etymologyProcess:"atmo（蒸気）＋ sphere（球）→ 地球をまるく包む気体は…？",
   etymologyConclusion:"atmo（蒸気）＋ sphere（球）→ 地球をまるく包んでいる気体の層＝大気",
   relatedWords:[
     {word:"sphere",meaning:"球；領域",breakdown:"sphere（球）→ まるい球の形をしたもの"},
     {word:"hemisphere",meaning:"半球",breakdown:"hemi（半分）＋ sphere（球）→ 球を半分にしたもの"},
     {synonym:true,word:"air",meaning:"空気",breakdown:"吸う空気。atmosphere は地球を包む層ぜんたい"},
     {synonym:true,word:"mood",meaning:"気分，雰囲気",breakdown:"その場の気分。atmosphere は場全体に漂う空気感"}]},

  {id:723,word:"forecast",partOfSpeech:"名詞",meaning:"予報，予測",
   meanings:["名|（天気などの）予報，予測","他|（先を）予測する"],
   pronunciation:"/ˈfɔːrkæst/",part:73,
   example:"The weather forecast says it will snow tomorrow morning.",
   exampleJa:"天気予報は、明日の朝に雪が降ると言っている。",
   example2:"Experts forecast a slow rise in food prices next year.",
   exampleJa2:"専門家は来年、食料品の値段が緩やかに上がると予測している。",
   etymologyProcess:"fore（前に）＋ cast（投げる）→ これから先へ考えを投げると…？",
   etymologyConclusion:"fore（前に）＋ cast（投げる）→ これから先のほうへ考えを投げて言い当てるもの＝予報",
   relatedWords:[
     {word:"broadcast",meaning:"放送する；放送",breakdown:"broad（広い）＋ cast（投げる）→ 広くばらまくように投げ出す"},
     {word:"foresee",meaning:"予見する",breakdown:"fore（前に）＋ see（見る）→ 先のほうを前もって見る"},
     {word:"forehead",meaning:"額（ひたい）",breakdown:"fore（前に）＋ head（頭）→ 頭のいちばん前にある面"},
     {synonym:true,word:"predict",meaning:"予言する，予測する",breakdown:"前もって言う。forecast は天気や数字の見通しに使う"}]},

  {id:724,word:"humid",partOfSpeech:"形容詞",meaning:"湿気が多い",
   meanings:["形|（空気が）湿気が多い，蒸し暑い"],
   pronunciation:"/ˈhjuːmɪd/",part:73,
   example:"Summer in Japan is very hot and extremely humid.",
   exampleJa:"日本の夏はとても暑く、非常に湿気が多い。",
   example2:"The air inside the greenhouse felt warm and humid.",
   exampleJa2:"温室の中の空気は、暖かく湿気が多く感じられた。",
   etymologyProcess:"hum（湿る）＋ id（〜な状態の）→ 空気が水気を含んでいると…？",
   etymologyConclusion:"hum（湿る）＋ id（〜な状態の）→ 空気が水気をたっぷり含んでべたつく＝湿気が多い",
   relatedWords:[
     {word:"humidity",meaning:"湿度，湿気",breakdown:"hum（湿る）＋ ity（名詞）→ 空気が水気を含む度合い"},
     {word:"humidifier",meaning:"加湿器",breakdown:"hum（湿る）＋ ify（する）＋ er（道具・人）→ 空気を湿らせる道具"},
     {synonym:true,word:"wet",meaning:"ぬれた",breakdown:"水でぬれている。humid は空気が水気を含む状態"},
     {synonym:true,word:"damp",meaning:"じめじめした",breakdown:"少しぬれている。humid は主に空気について言う"}]},

  {id:725,word:"tropical",partOfSpeech:"形容詞",meaning:"熱帯の",
   meanings:["形|（赤道近くの）熱帯の"],
   pronunciation:"/ˈtrɑːpɪkl/",part:73,
   example:"Bananas and mangoes grow well in warm tropical countries.",
   exampleJa:"バナナやマンゴーは、暖かい熱帯の国々でよく育つ。",
   example2:"We studied tropical rainforests in our geography class today.",
   exampleJa2:"私たちは今日、地理の授業で熱帯の雨林について学んだ。",
   etymologyProcess:"trop（向きを変える）＋ ic（〜の）＋ al（〜の）→ 太陽が折り返す線の内側は…？",
   etymologyConclusion:"trop（向きを変える）＋ ic（〜の）＋ al（〜の）→ 太陽が折り返す回帰線に挟まれた暑い地域の＝熱帯の",
   relatedWords:[
     {word:"tropic",meaning:"回帰線；熱帯",breakdown:"trop（向きを変える）＋ ic（名詞）→ 太陽が折り返す線"},
     {word:"trophy",meaning:"トロフィー",breakdown:"trop（向きを変える）＋ y（名詞）→ 敵を退かせた印として飾るもの"},
     {synonym:true,word:"equator",meaning:"赤道",breakdown:"地球を等分する線。tropical はその周りの暑い地帯"},
     {synonym:true,word:"humid",meaning:"湿気が多い",breakdown:"tropical な地域はたいてい humid でもある"}]},

  {id:726,word:"solar",partOfSpeech:"形容詞",meaning:"太陽の",
   meanings:["形|（太陽から来る）太陽の"],
   pronunciation:"/ˈsoʊlər/",part:73,
   example:"Our school put solar panels on the gym roof last year.",
   exampleJa:"私たちの学校は昨年、体育館の屋根に太陽光パネルを取りつけた。",
   example2:"The solar system has eight planets around one bright star.",
   exampleJa2:"太陽系には、1つの明るい恒星のまわりに8つの惑星がある。",
   etymologyProcess:"sol（太陽）＋ ar（〜の）→ 太陽から届く光や熱に関わると…？",
   etymologyConclusion:"sol（太陽）＋ ar（〜の）→ 太陽から届く光や熱に関わっている＝太陽の",
   relatedWords:[
     {word:"parasol",meaning:"日傘",breakdown:"sol（太陽）→ 日ざしを防いで身を守るための傘"},
     {word:"sunny",meaning:"晴れた",breakdown:"sun（太陽）＋ y（〜な状態の）→ 太陽がしっかり出ている"},
     {synonym:true,word:"lunar",meaning:"月の",breakdown:"月に関する。solar は太陽に関する"},
     {synonym:true,word:"energy",meaning:"エネルギー",breakdown:"solar energy で太陽のエネルギー、つまり太陽光発電の力"}]},

  {id:727,word:"species",partOfSpeech:"名詞",meaning:"（生物の）種",
   meanings:["名|（生物分類の）種"],
   pronunciation:"/ˈspiːʃiːz/",part:73,
   example:"This forest is home to many rare species of birds.",
   exampleJa:"この森は、多くの珍しい鳥の種のすみかだ。",
   example2:"Human activity has destroyed hundreds of animal species.",
   exampleJa2:"人間の活動が、何百もの動物の種を滅ぼしてきた。",
   etymologyProcess:"speci（種類）→ 見た目で分けられた生き物の仲間は…？",
   etymologyConclusion:"speci（種類）→ 見た目によって分けられる、生き物の仲間のまとまり＝種",
   relatedWords:[
     {word:"special",meaning:"特別な",breakdown:"speci（種類）＋ al（〜の）→ その種類だけの、他と違う"},
     {word:"specific",meaning:"特定の；具体的な",breakdown:"speci（種類）＋ fic（作る）→ 種類をはっきり区切った"},
     {word:"especially",meaning:"とりわけ",breakdown:"ex（外へ）＋ speci（種類）＋ ly（副詞）→ 他の種類から抜き出して"},
     {synonym:true,word:"kind",meaning:"種類",breakdown:"ふつうの「種類」。species は生物学で使う「種」"}]},

  {id:728,word:"pesticide",partOfSpeech:"名詞",meaning:"殺虫剤，農薬",
   meanings:["名|（害虫を殺す）殺虫剤，農薬"],
   pronunciation:"/ˈpestɪsaɪd/",part:73,
   example:"Some farmers use no pesticides on their vegetables at all.",
   exampleJa:"野菜に殺虫剤をまったく使わない農家もいる。",
   example2:"This pesticide can be dangerous to bees and small birds.",
   exampleJa2:"この殺虫剤は、ミツバチや小鳥にとって危険になりうる。",
   etymologyProcess:"pest（害虫）＋ cide（切る・殺す）→ 害虫を断ち切る薬は…？",
   etymologyConclusion:"pest（害虫）＋ cide（切る・殺す）→ 作物を荒らす害虫を断ち切るための薬＝殺虫剤",
   relatedWords:[
     {word:"pest",meaning:"害虫，害獣",breakdown:"pest（害虫）→ 作物や人に害を与える生き物"},
     {word:"decide",meaning:"決める",breakdown:"de（すっかり）＋ cide（切る・殺す）→ 迷いを切り落として決める"},
     {word:"precise",meaning:"正確な",breakdown:"pre（先に）＋ cis（切る）→ 先に切りそろえてきっちりした"},
     {synonym:true,word:"insect",meaning:"昆虫",breakdown:"体に切れ目のある虫。pesticide はこれを殺す薬"}]},

  {id:729,word:"extinct",partOfSpeech:"形容詞",meaning:"絶滅した",
   meanings:["形|（種が）絶滅した","形|（火山が）活動を止めた"],
   pronunciation:"/ɪkˈstɪŋkt/",part:73,
   example:"Many animals became extinct because of human activity.",
   exampleJa:"多くの動物が、人間の活動のせいで絶滅した。",
   example2:"This volcano has been extinct for about two thousand years.",
   exampleJa2:"この火山は約2千年の間、火が絶えたままだ。",
   etymologyProcess:"ex（外へ）＋ stingu（突き刺す）→ ともし火を突いて消してしまうと…？",
   etymologyConclusion:"ex（外へ）＋ stingu（突き刺す）→ ともし火を突いて消すように、種が絶えてしまった＝絶滅した",
   relatedWords:[
     {word:"extinguish",meaning:"（火を）消す",breakdown:"ex（外へ）＋ stingu（突き刺す）→ 火を突いて外へ追い出し、消す"},
     {word:"extinction",meaning:"絶滅",breakdown:"ex（外へ）＋ stingu（突き刺す）＋ ion（名詞）→ 火が消えるように絶えること"},
     {word:"distinguish",meaning:"区別する",breakdown:"dis（バラバラに）＋ stingu（突き刺す）→ 印を刺して別のものに分ける"},
     {synonym:true,word:"survive",meaning:"生き残る",breakdown:"生き延びる。extinct はその先で絶えてしまった状態"}]},

  {id:730,word:"feed",partOfSpeech:"他動詞",meaning:"えさを与える；養う",
   meanings:["他|（動物に）えさを与える","他|（家族を）養う"],
   pronunciation:"/fiːd/",part:73,
   example:"I feed my dog twice a day, in the morning and evening.",
   exampleJa:"私は犬に、朝と晩の1日2回えさを与える。",
   example2:"Please do not feed the birds in this small park.",
   exampleJa2:"この小さな公園では、鳥にえさを与えないでください。",
   etymologyProcess:"feed（食べ物を与える）→ 口へ食べ物を運んで育てると…？",
   etymologyConclusion:"feed（食べ物を与える）→ 動物や子どもの口へ食べ物を運んで育てる＝えさを与える",
   relatedWords:[
     {word:"food",meaning:"食べ物",breakdown:"feed（食べ物を与える）→ 与えられて口に入るもの"},
     {word:"feedback",meaning:"感想，反応",breakdown:"feed（食べ物を与える）＋ back（後ろ）→ 受け取ったものを返し送ること"},
     {synonym:true,word:"raise",meaning:"育てる；上げる",breakdown:"育て上げる。feed は食べ物を与える行為そのもの"},
     {synonym:true,word:"nourish",meaning:"栄養を与える",breakdown:"栄養で体を養う。feed はえさや食事を与える"}]},

  {id:731,word:"energetic",partOfSpeech:"形容詞",meaning:"活発な，精力的な",
   meanings:["形|（よく動く）活発な，精力的な"],
   pronunciation:"/ˌenərˈdʒetɪk/",part:74,
   example:"My grandmother is still energetic at the age of eighty.",
   exampleJa:"私の祖母は、80歳になってもまだ活発だ。",
   example2:"The energetic new coach changed our whole team very quickly.",
   exampleJa2:"その活発な新しいコーチは、私たちのチーム全体をとても素早く変えた。",
   etymologyProcess:"en（中に）＋ erg（働く）＋ ic（〜の）→ 体の中で力がよく働くと…？",
   etymologyConclusion:"en（中に）＋ erg（働く）＋ ic（〜の）→ 体の中で力がぐんぐん働いて動き回る＝活発な",
   relatedWords:[
     {word:"energy",meaning:"エネルギー，活力",breakdown:"en（中に）＋ erg（働く）＋ y（名詞）→ 中で働こうとする力"},
     {word:"synergy",meaning:"相乗効果",breakdown:"sym（共に）＋ erg（働く）＋ y（名詞）→ 一緒に働いて力が増すこと"},
     {word:"surgery",meaning:"手術",breakdown:"surg（手で働く）＋ ry（もの）→ 手で erg（働く）こと、つまり手術"},
     {synonym:true,word:"active",meaning:"活動的な",breakdown:"よく動く。energetic は力があふれている感じ"}]},

  {id:732,word:"greedy",partOfSpeech:"形容詞",meaning:"貪欲な，欲張りな",
   meanings:["形|（もっと欲しがる）貪欲な，欲張りな"],
   pronunciation:"/ˈɡriːdi/",part:74,
   example:"The greedy king took all the food from the village.",
   exampleJa:"その貪欲な王は、村から食べ物をすべて奪った。",
   example2:"Do not be greedy; leave some cake for your sister.",
   exampleJa2:"貪欲になってはいけない。妹にケーキを少し残しなさい。",
   etymologyProcess:"greed（むさぼる）＋ y（〜な状態の）→ もっともっとと欲しがると…？",
   etymologyConclusion:"greed（むさぼる）＋ y（〜な状態の）→ 足りているのに、もっともっとと欲しがる＝貪欲な",
   relatedWords:[
     {word:"greed",meaning:"貪欲，強欲",breakdown:"greed（むさぼる）→ もっと欲しいという抑えきれない気持ち"},
     {word:"greedily",meaning:"がつがつと",breakdown:"greed（むさぼる）＋ ly（副詞）→ むさぼるようなやり方で"},
     {synonym:true,word:"selfish",meaning:"利己的な",breakdown:"自分を優先する。greedy は「もっと欲しい」が中心"},
     {synonym:true,word:"generous",meaning:"気前のよい",breakdown:"惜しみなく与える。greedy はため込んで離さない"}]},

  {id:733,word:"brave",partOfSpeech:"形容詞",meaning:"勇敢な",
   meanings:["形|（危険にひるまない）勇敢な"],
   pronunciation:"/breɪv/",part:74,
   example:"The brave firefighter ran into the burning old building.",
   exampleJa:"その勇敢な消防士は、燃えている古い建物に駆け込んだ。",
   example2:"It was brave of her to speak in front of everyone.",
   exampleJa2:"みんなの前で話すとは、彼女は勇敢だった。",
   etymologyProcess:"brave（荒々しい）→ 危ないところへ荒々しく踏み込むと…？",
   etymologyConclusion:"brave（荒々しい）→ 危ないところへ荒々しく踏み込んで、ひるまない＝勇敢な",
   hook:"かけ声の「ブラボー（bravo）」と同じ家族。もとは「荒っぽい・見事な」。",
   relatedWords:[
     {word:"bravery",meaning:"勇気",breakdown:"brave（荒々しい）＋ ry（もの）→ ひるまず踏み込む心"},
     {word:"bravo",meaning:"ブラボー（よくやった）",breakdown:"brave（荒々しい）→ 見事だとほめる掛け声"},
     {synonym:true,word:"courage",meaning:"勇気",breakdown:"心から出る勇気。brave はその勇気を示す様子"},
     {synonym:true,word:"bold",meaning:"大胆な",breakdown:"思い切りがよい。brave は怖さに耐えて進む"}]},

  {id:734,word:"generous",partOfSpeech:"形容詞",meaning:"気前のよい",
   meanings:["形|（惜しまず与える）気前のよい"],
   pronunciation:"/ˈdʒenərəs/",part:74,
   example:"Our neighbor is very generous with his time and money.",
   exampleJa:"私たちの隣人は、時間もお金もとても気前がよい。",
   example2:"It was generous of you to share your lunch with me.",
   exampleJa2:"お弁当を分けてくれるなんて、あなたは気前がよかった。",
   etymologyProcess:"gener（生み出す）＋ ous（形容詞）→ よい家に生まれた人らしくふるまうと…？",
   etymologyConclusion:"gener（生み出す）＋ ous（形容詞）→ よい家柄の人らしく、惜しまず人に分け与える＝気前のよい",
   relatedWords:[
     {word:"generate",meaning:"生み出す",breakdown:"gener（生み出す）＋ ate（動詞）→ 新しく作り出す"},
     {word:"generation",meaning:"世代",breakdown:"gener（生み出す）＋ ation（名詞）→ 同じころに生み出された人たち"},
     {word:"gene",meaning:"遺伝子",breakdown:"gener（生み出す）→ 体を生み出す設計図のもと"},
     {synonym:true,word:"kind",meaning:"親切な",breakdown:"心がやさしい。generous は物やお金を惜しまない"}]},

  {id:735,word:"intellectual",partOfSpeech:"形容詞",meaning:"知的な",
   meanings:["形|（頭を使う）知的な"],
   pronunciation:"/ˌɪntəˈlektʃuəl/",part:74,
   example:"She has many intellectual interests besides her science studies.",
   exampleJa:"彼女は理科の勉強のほかにも、多くの知的な関心を持っている。",
   example2:"Chess is a highly intellectual game for two players.",
   exampleJa2:"チェスは2人で行う、非常に知的なゲームだ。",
   etymologyProcess:"inter（間の）＋ lect（拾う）＋ ual（〜の）→ 物事の間から選び拾うと…？",
   etymologyConclusion:"inter（間の）＋ lect（拾う）＋ ual（〜の）→ 物事の間から大事なものを選び拾う頭の働きの＝知的な",
   relatedWords:[
     {word:"collect",meaning:"集める",breakdown:"com（共に）＋ lect（拾う）→ あちこちから拾って一つに集める"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離して）＋ lect（拾う）→ より分けて拾い上げる"},
     {word:"intellect",meaning:"知性",breakdown:"inter（間の）＋ lect（拾う）→ 物事の間から選び拾う力"},
     {word:"intelligent",meaning:"頭のよい",breakdown:"inter（間の）＋ lect（拾う）＋ ent（〜している）→ 間から選び拾える"}]},

  {id:736,word:"curious",partOfSpeech:"形容詞",meaning:"好奇心が強い；奇妙な",
   meanings:["形|（知りたがる）好奇心が強い","形|（変わっていて）奇妙な"],
   pronunciation:"/ˈkjʊriəs/",part:74,
   example:"Children are naturally curious about everything around them.",
   exampleJa:"子どもは、周りのすべてに生まれつき好奇心が強い。",
   example2:"I was curious about how the old clock worked inside.",
   exampleJa2:"私はその古い時計の中がどう動くのか、好奇心が強くわいた。",
   etymologyProcess:"cur（気にかける）＋ ous（形容詞）→ 何でも気にかけて知りたがると…？",
   etymologyConclusion:"cur（気にかける）＋ ous（形容詞）→ 何でも気にかけて、知りたくてたまらない＝好奇心が強い",
   relatedWords:[
     {word:"cure",meaning:"治す；治療",breakdown:"cur（気にかける）→ 気にかけて手当てし、よくする"},
     {word:"curiosity",meaning:"好奇心",breakdown:"cur（気にかける）＋ ity（名詞）→ 気にかけて知りたがる気持ち"},
     {word:"accurate",meaning:"正確な",breakdown:"ad（〜へ）＋ cur（気にかける）＋ ate（形容詞）→ 細部まで気を配った"},
     {word:"secure",meaning:"安全な；確保する",breakdown:"se（離して）＋ cur（気にかける）→ 心配から離れている"}]},

  {id:737,word:"imaginative",partOfSpeech:"形容詞",meaning:"想像力豊かな",
   meanings:["形|（心に絵を描ける）想像力豊かな"],
   pronunciation:"/ɪˈmædʒɪnətɪv/",part:74,
   example:"Her imaginative stories won the school writing contest.",
   exampleJa:"彼女の想像力豊かな物語が、学校の作文コンテストで優勝した。",
   example2:"We need an imaginative solution to this difficult problem.",
   exampleJa2:"この難しい問題には、想像力豊かな解決策が必要だ。",
   etymologyProcess:"imag（似せた姿）＋ ative（形容詞）→ 心に絵を次々描けると…？",
   etymologyConclusion:"imag（似せた姿）＋ ative（形容詞）→ 心の中に絵を次々と描き出せる＝想像力豊かな",
   relatedWords:[
     {word:"image",meaning:"像，イメージ",breakdown:"imag（似せた姿）→ 実物に似せて写し取った姿"},
     {word:"imagine",meaning:"想像する",breakdown:"imag（似せた姿）＋ ine（動詞）→ 心の中に似た姿を描き出す"},
     {word:"imagination",meaning:"想像力",breakdown:"imag（似せた姿）＋ ation（名詞）→ 心に姿を描く力"},
     {word:"imitate",meaning:"まねる",breakdown:"imit（似せる）＋ ate（動詞）→ 同じ形・同じ動きに似せる"}]},

  {id:738,word:"afford",partOfSpeech:"他動詞",meaning:"（買う）余裕がある",
   meanings:["他|（金や時間の）余裕がある"],
   pronunciation:"/əˈfɔːrd/",part:74,
   example:"We cannot afford a new car this year at all.",
   exampleJa:"今年はまったく新しい車を買う余裕がない。",
   example2:"She could not afford to lose any more sleep.",
   exampleJa2:"彼女はこれ以上、眠りを削る余裕がなかった。",
   etymologyProcess:"ford（前へ進める）→ そこまで手を届かせられると…？",
   etymologyConclusion:"ford（前へ進める）→ お金や時間が足りていて、そこまで手を届かせられる＝余裕がある",
   relatedWords:[
     {word:"forth",meaning:"前へ，外へ",breakdown:"ford（前へ進める）→ 前のほうへ出ていく"},
     {word:"further",meaning:"さらに；促進する",breakdown:"ford（前へ進める）＋ er（より）→ もっと先へ進める"},
     {synonym:true,word:"manage",meaning:"何とかやりくりする",breakdown:"何とかやり遂げる。afford はお金や時間が足りている"},
     {synonym:true,word:"spare",meaning:"（時間を）割く；予備の",breakdown:"余分を割く。afford は余裕があってできること"}]},

  {id:739,word:"eager",partOfSpeech:"形容詞",meaning:"熱心な，したくてたまらない",
   meanings:["形|（be eager to do で）熱心な"],
   pronunciation:"/ˈiːɡər/",part:74,
   example:"The children were eager to open their birthday presents.",
   exampleJa:"子どもたちは、誕生日のプレゼントを開けることに熱心だった。",
   example2:"He is eager to join the basketball team next spring.",
   exampleJa2:"彼は来春、バスケットボール部に入ることに熱心だ。",
   etymologyProcess:"eag（鋭い）→ 気持ちが刃のように鋭くとがると…？",
   etymologyConclusion:"eag（鋭い）→ 気持ちが刃のように鋭くとがり、早くやりたくてうずうずする＝熱心な",
   relatedWords:[
     {word:"eagerly",meaning:"熱心に",breakdown:"eag（鋭い）＋ ly（副詞）→ 気持ちを鋭くとがらせて"},
     {word:"vinegar",meaning:"酢",breakdown:"vin（ぶどう酒）＋ eag（鋭い）→ 酸っぱく鋭くなったぶどう酒"},
     {synonym:true,word:"keen",meaning:"熱心な；鋭い",breakdown:"「鋭い」と「熱心」を両方持つ語。eager と発想が同じ"},
     {synonym:true,word:"enthusiastic",meaning:"熱狂的な",breakdown:"夢中になる。eager は「早くしたい」と前のめりな気持ち"}]},

  {id:740,word:"selfish",partOfSpeech:"形容詞",meaning:"利己的な，自分勝手な",
   meanings:["形|（自分中心の）利己的な，自分勝手な"],
   pronunciation:"/ˈselfɪʃ/",part:74,
   example:"It is selfish to keep the whole cake for yourself.",
   exampleJa:"ケーキを丸ごと自分のために取っておくのは利己的だ。",
   example2:"His selfish behavior upset everyone in the tennis club.",
   exampleJa2:"彼の利己的なふるまいは、テニス部のみんなを怒らせた。",
   etymologyProcess:"self（自分）→ 何でも自分中心にしてしまうと…？",
   etymologyConclusion:"self（自分）→ 何でも自分中心にして、人のことを考えない＝利己的な",
   relatedWords:[
     {word:"self",meaning:"自分自身",breakdown:"self（自分）→ ほかの誰でもない自分そのもの"},
     {word:"selfless",meaning:"無私の，献身的な",breakdown:"self（自分）＋ less（ない）→ 自分のことを考えに入れない"},
     {word:"selfishness",meaning:"わがまま",breakdown:"self（自分）＋ ness（名詞）→ 何でも自分中心にしてしまう性質"},
     {synonym:true,word:"greedy",meaning:"貪欲な",breakdown:"もっと欲しがる。selfish は人を気にかけないこと"}]},

  {id:741,word:"aggressive",partOfSpeech:"形容詞",meaning:"攻撃的な",
   meanings:["形|（相手に強く出る）攻撃的な"],
   pronunciation:"/əˈɡresɪv/",part:75,
   example:"His aggressive tone made the other students feel uncomfortable.",
   exampleJa:"彼の攻撃的な口調は、他の生徒を不快にさせた。",
   example2:"Some birds become aggressive when they protect their nests.",
   exampleJa2:"鳥の中には、巣を守るときに攻撃的になるものもいる。",
   etymologyProcess:"ad（〜へ）＋ gress（歩む）＋ ive（形容詞）→ 相手のほうへ踏み込むと…？",
   etymologyConclusion:"ad（〜へ）＋ gress（歩む）＋ ive（形容詞）→ 相手のほうへずかずか踏み込んでいく＝攻撃的な",
   relatedWords:[
     {word:"progress",meaning:"進歩；進む",breakdown:"pro（前へ）＋ gress（歩む）→ 前へ歩みを進めていく"},
     {word:"congress",meaning:"議会，会議",breakdown:"com（共に）＋ gress（歩む）→ みんなが歩み寄って集まる場"},
     {word:"grade",meaning:"等級；学年",breakdown:"grad（歩み・段）→ 一段ずつ上がっていく段階"},
     {word:"aggression",meaning:"攻撃，侵略",breakdown:"ad（〜へ）＋ gress（歩む）＋ ion（名詞）→ 相手へ踏み込むこと"}]},

  {id:742,word:"cruel",partOfSpeech:"形容詞",meaning:"残酷な",
   meanings:["形|（痛みを気にかけない）残酷な"],
   pronunciation:"/ˈkruːəl/",part:75,
   example:"It is cruel to leave a dog alone all day.",
   exampleJa:"犬を一日中ひとりにしておくのは残酷だ。",
   example2:"The cruel winter killed most of the young trees.",
   exampleJa2:"その残酷な冬が、若木の大半を枯らした。",
   etymologyProcess:"cru（生の血）→ 血を見ても平気でいられると…？",
   etymologyConclusion:"cru（生の血）→ 流れる血を見ても平気で、相手の痛みを気にしない＝残酷な",
   relatedWords:[
     {word:"crude",meaning:"粗い；原油の",breakdown:"cru（生の血）→ 手を加えていない、生のままの"},
     {word:"cruelty",meaning:"残酷さ",breakdown:"cru（生の血）＋ ty（名詞）→ 相手の痛みを気にかけない心"},
     {synonym:true,word:"harsh",meaning:"厳しい，きつい",breakdown:"容赦がない。cruel は苦しみを与えて平気なこと"},
     {synonym:true,word:"violent",meaning:"暴力的な",breakdown:"力で傷つける。cruel は心の冷たさを指す"}]},

  {id:743,word:"addicted",partOfSpeech:"形容詞",meaning:"中毒になっている",
   meanings:["形|（be addicted to で）中毒になっている"],
   pronunciation:"/əˈdɪktɪd/",part:75,
   example:"Many teenagers are addicted to their smartphones these days.",
   exampleJa:"近ごろ多くの10代が、スマートフォンに中毒になっている。",
   example2:"He became addicted to online games last cold winter.",
   exampleJa2:"彼は昨年の寒い冬、オンラインゲームに中毒になった。",
   etymologyProcess:"ad（〜へ）＋ dict（言う）＋ ed（〜された）→ そこへ引き渡すと言われると…？",
   etymologyConclusion:"ad（〜へ）＋ dict（言う）＋ ed（〜された）→ それに身を引き渡すと言い渡された状態＝中毒になっている",
   relatedWords:[
     {word:"predict",meaning:"予言する",breakdown:"pre（先に）＋ dict（言う）→ 起きる前に先に言う"},
     {word:"dictionary",meaning:"辞書",breakdown:"dict（言う）＋ ary（もの）→ 言葉の言い方を集めたもの"},
     {word:"dictate",meaning:"書き取らせる；命じる",breakdown:"dict（言う）＋ ate（動詞）→ 声に出して言い渡す"},
     {word:"addiction",meaning:"中毒，依存",breakdown:"ad（〜へ）＋ dict（言う）＋ ion（名詞）→ 身を引き渡してしまうこと"}]},

  {id:744,word:"stubborn",partOfSpeech:"形容詞",meaning:"頑固な",
   meanings:["形|（考えを変えない）頑固な"],
   pronunciation:"/ˈstʌbərn/",part:75,
   example:"My stubborn brother never admits that he is wrong.",
   exampleJa:"私の頑固な兄は、自分が間違っていると決して認めない。",
   example2:"She was too stubborn to ask anyone for help.",
   exampleJa2:"彼女は頑固すぎて、誰にも助けを求められなかった。",
   etymologyProcess:"stub（切り株）→ 抜こうとしてもびくとも動かないと…？",
   etymologyConclusion:"stub（切り株）→ 抜こうとしてもびくとも動かない切り株のようだ＝頑固な",
   hook:"語源ははっきりしないが、stub（切り株）と結びつけると覚えやすい。",
   relatedWords:[
     {word:"stub",meaning:"切り株；半券",breakdown:"stub（切り株）→ 切ったあとに短く残る部分"},
     {synonym:true,word:"firm",meaning:"かたい；断固とした",breakdown:"ゆるがない。stubborn は悪い意味で譲らないこと"},
     {synonym:true,word:"determined",meaning:"決意の固い",breakdown:"よい意味で譲らない。stubborn は困った頑固さ"},
     {synonym:true,word:"flexible",meaning:"融通のきく",breakdown:"よく曲がる。stubborn は曲がろうとしない"}]},

  {id:745,word:"bold",partOfSpeech:"形容詞",meaning:"大胆な；太字の",
   meanings:["形|（ためらわない）大胆な","形|（文字が）太字の"],
   pronunciation:"/boʊld/",part:75,
   example:"It was a bold decision to change the whole plan.",
   exampleJa:"計画全体を変えるのは、大胆な決断だった。",
   example2:"The title is printed in bold letters on the cover.",
   exampleJa2:"表題は表紙に太字で印刷されている。",
   etymologyProcess:"bold（ふくれ上がる）→ 気持ちがふくれて前に出ると…？",
   etymologyConclusion:"bold（ふくれ上がる）→ 気持ちがふくれ上がって、ためらわず前に出る＝大胆な",
   hook:"文字の「ボールド（太字）」も同じ語。線がふくらんで目立つイメージ。",
   relatedWords:[
     {word:"boldly",meaning:"大胆に",breakdown:"bold（ふくれ上がる）＋ ly（副詞）→ ためらわず前に出るやり方で"},
     {word:"boldness",meaning:"大胆さ",breakdown:"bold（ふくれ上がる）＋ ness（名詞）→ ひるまず前に出る性質"},
     {synonym:true,word:"brave",meaning:"勇敢な",breakdown:"怖さに耐えて進む。bold はためらいがないこと"},
     {synonym:true,word:"daring",meaning:"思い切った",breakdown:"あえて危険を冒す。bold と非常に近い語"}]},

  {id:746,word:"guilty",partOfSpeech:"形容詞",meaning:"有罪の；申し訳なく思う",
   meanings:["形|（裁判で）有罪の","形|（feel guilty で）申し訳なく思う"],
   pronunciation:"/ˈɡɪlti/",part:75,
   example:"The court found him guilty of stealing the old bicycle.",
   exampleJa:"裁判所は、古い自転車を盗んだとして彼を有罪とした。",
   example2:"I felt guilty about forgetting my best friend's birthday.",
   exampleJa2:"親友の誕生日を忘れて、私は申し訳なく思った。",
   etymologyProcess:"guilt（罪の負い目）＋ y（〜な状態の）→ 負い目を背負っていると…？",
   etymologyConclusion:"guilt（罪の負い目）＋ y（〜な状態の）→ 罪や負い目を背負っている状態＝有罪の",
   relatedWords:[
     {word:"guilt",meaning:"罪悪感；有罪",breakdown:"guilt（罪の負い目）→ 心にのしかかる負い目"},
     {word:"guiltless",meaning:"罪のない",breakdown:"guilt（罪の負い目）＋ less（ない）→ 負い目をまったく持たない"},
     {synonym:true,word:"innocent",meaning:"無実の",breakdown:"罪がない。guilty は罪や負い目を背負っている"},
     {synonym:true,word:"ashamed",meaning:"恥じている",breakdown:"人目が気になる恥。guilty は自分の罪を責める気持ち"}]},

  {id:747,word:"innocent",partOfSpeech:"形容詞",meaning:"無実の；無邪気な",
   meanings:["形|（罪を犯していない）無実の","形|（汚れを知らない）無邪気な"],
   pronunciation:"/ˈɪnəsnt/",part:75,
   example:"The judge declared that the young man was innocent.",
   exampleJa:"裁判官は、その若者が無実であると宣言した。",
   example2:"Her innocent smile made everyone in the room relax.",
   exampleJa2:"彼女の無邪気な笑顔は、部屋のみんなをくつろがせた。",
   etymologyProcess:"in（否定）＋ noc（傷つける）＋ ent（形容詞）→ 誰も傷つけていないと…？",
   etymologyConclusion:"in（否定）＋ noc（傷つける）＋ ent（形容詞）→ 誰のことも傷つけていない、きれいなままの＝無実の",
   relatedWords:[
     {word:"innocence",meaning:"無実；無邪気さ",breakdown:"in（否定）＋ noc（傷つける）＋ ence（名詞）→ 傷つけていないこと"},
     {synonym:true,word:"harm",meaning:"害；傷つける",breakdown:"相手に痛みや損を与えること。innocent はそれをしていない"},
     {synonym:true,word:"guilty",meaning:"有罪の",breakdown:"罪がある。innocent は罪がまったくない状態"},
     {synonym:true,word:"pure",meaning:"純粋な",breakdown:"混じりけがない。innocent は汚れを知らない"}]},

  {id:748,word:"sincere",partOfSpeech:"形容詞",meaning:"誠実な，心からの",
   meanings:["形|（裏表のない）誠実な，心からの"],
   pronunciation:"/sɪnˈsɪr/",part:75,
   example:"Please accept my sincere thanks for all your kind help.",
   exampleJa:"あなたの親切な助けすべてに、私の誠実な感謝をお受けください。",
   example2:"He gave a sincere apology to all his classmates.",
   exampleJa2:"彼はクラスメート全員に、誠実な謝罪をした。",
   etymologyProcess:"sin（1つ）＋ cer（育つ）→ 混ぜ物なしに育ったままだと…？",
   etymologyConclusion:"sin（1つ）＋ cer（育つ）→ 混ぜ物なしに一つのまま育った、まじりけのない＝誠実な",
   relatedWords:[
     {word:"increase",meaning:"増える，増やす",breakdown:"in（中へ）＋ creas（育つ）→ 中でぐんぐん育って大きくなる"},
     {word:"create",meaning:"創造する",breakdown:"creat（生み出す）→ 何もないところから新しく生み出す"},
     {word:"sincerely",meaning:"心から（手紙の結び）",breakdown:"sin（1つ）＋ cer（育つ）＋ ly（副詞）→ まじりけなく心から"},
     {synonym:true,word:"honest",meaning:"正直な",breakdown:"うそをつかない。sincere は気持ちに裏表がない"}]},

  {id:749,word:"modest",partOfSpeech:"形容詞",meaning:"謙虚な；控えめな",
   meanings:["形|（自分を誇らない）謙虚な","形|（量や大きさが）控えめな"],
   pronunciation:"/ˈmɑːdɪst/",part:75,
   example:"She is very modest about her success in the competition.",
   exampleJa:"彼女はその大会での成功について、とても謙虚だ。",
   example2:"He lives in a modest house near the small station.",
   exampleJa2:"彼は小さな駅の近くの、控えめな家に住んでいる。",
   etymologyProcess:"modus（ほどよさ）→ 自分をほどよい大きさに保っていると…？",
   etymologyConclusion:"modus（ほどよさ）→ 自分を大きく見せず、ほどよい大きさに保っている＝謙虚な",
   relatedWords:[
     {word:"mode",meaning:"やり方；様式",breakdown:"modus（ほどよさ）→ 決まったはかり方、決まったやり方"},
     {word:"moderate",meaning:"適度な；和らげる",breakdown:"modus（ほどよさ）＋ ate（形容詞）→ ほどよい量に収まった"},
     {word:"model",meaning:"模型；手本",breakdown:"modus（ほどよさ）＋ el（小さい）→ 寸法どおりに作った小さな形"},
     {synonym:true,word:"humble",meaning:"謙虚な；質素な",breakdown:"身を低くする。modest は自分を誇らないこと"}]},

  {id:750,word:"stupid",partOfSpeech:"形容詞",meaning:"ばかな，愚かな",
   meanings:["形|（頭が働かない）ばかな，愚かな"],
   pronunciation:"/ˈstuːpɪd/",part:75,
   example:"It was stupid of me to forget my umbrella again.",
   exampleJa:"また傘を忘れるとは、私はばかだった。",
   example2:"Do not ask such a stupid question in class.",
   exampleJa2:"授業でそんなばかな質問をしてはいけない。",
   etymologyProcess:"stup（打たれてぼうっとする）＋ id（〜な状態の）→ 頭が働かなくなると…？",
   etymologyConclusion:"stup（打たれてぼうっとする）＋ id（〜な状態の）→ 頭を打たれたようにぼうっとして働かない＝ばかな",
   relatedWords:[
     {word:"stupidity",meaning:"愚かさ",breakdown:"stup（打たれてぼうっとする）＋ ity（名詞）→ 頭が働かないこと"},
     {synonym:true,word:"stun",meaning:"ぼうぜんとさせる",breakdown:"別語源だが、衝撃で頭が真っ白になる点は stupid と同じ"},
     {synonym:true,word:"foolish",meaning:"愚かな",breakdown:"考えが足りない。stupid はもっと強く、失礼にもなる語"},
     {synonym:true,word:"silly",meaning:"ばかげた",breakdown:"子どもっぽくばかげている。stupid はきつい非難の語"}]}
