  {id:1351,word:"instance",partOfSpeech:"名詞",meaning:"例，実例",
   meanings:["名|例，実例","名|（for instance で）例えば"],
   pronunciation:"/ˈɪnstəns/",part:136,
   example:"Give me one clear instance of this serious problem.",
   exampleJa:"この深刻な問題の、はっきりした例を一つ挙げてください。",
   example2:"For instance, cats sleep much more than dogs do.",
   exampleJa2:"例えば、猫は犬よりずっと多く眠る。",
   etymologyProcess:"in（上に）＋ sta（立つ）→ 目の前に立って示される一つのものは…？",
   etymologyConclusion:"in（上に）＋ sta（立つ）→ 目の前に立って示される、一つの具体的なもの＝例",
   why:"【なぜ】ラテン語 instantia はもと「すぐそばに立つこと・さし迫ること」。中世の論理学で「反論として持ち出すもの」を指すようになり、そこから広く「例」になりました。\n【つながり】instant（すぐそばに立つ一瞬）、circumstance（まわりを取り巻いて立つもの）も同じ家族です。",
   relatedWords:[
     {word:"circumstance",meaning:"状況",breakdown:"circ（輪を描く）＋ sta（立つ）→ まわりを取り巻いて立っていること"},
     {word:"substance",meaning:"物質；中身",breakdown:"sub（下で）＋ sta（立つ）→ 見た目の下で全体を支える中身"},
     {word:"stand",meaning:"立つ",breakdown:"sta（立つ）→ 足を地につけてまっすぐ立つ"},
     {word:"stable",meaning:"安定した",breakdown:"sta（立つ）＋ able（できる）→ ぐらつかずに立っていられる"}]},

  {id:1352,word:"dialogue",partOfSpeech:"名詞",meaning:"会話，対話",
   meanings:["名|会話，対話","名|（劇や映画の）せりふ"],
   pronunciation:"/ˈdaɪəlɔːɡ/",part:136,
   example:"The quiet film has very little dialogue at all.",
   exampleJa:"その静かな映画には、会話がほとんどない。",
   example2:"Real dialogue between the two sides finally began yesterday.",
   exampleJa2:"両者の間の本当の対話が、昨日ついに始まった。",
   etymologyProcess:"dia（間で）＋ log（言葉）→ 二人の間を行き来する言葉なら…？",
   etymologyConclusion:"dia（間で）＋ log（言葉）→ 二人の間を行き来する言葉のやりとり＝会話",
   relatedWords:[
     {word:"dialect",meaning:"方言",breakdown:"dia（間で）＋ lect（拾う）→ その土地の人どうしで拾い交わす言葉"},
     {word:"logic",meaning:"論理",breakdown:"log（言葉）＋ ic（名詞）→ 言葉の筋道の立て方"},
     {word:"monologue",meaning:"独白",breakdown:"mono（1つ）＋ log（言葉）→ 一人だけで話し続ける言葉"},
     {word:"apologize",meaning:"謝る",breakdown:"apo（離れて）＋ log（言葉）→ 一歩下がって事情を述べる"}]},

  {id:1353,word:"usage",partOfSpeech:"名詞",meaning:"語法，使い方",
   meanings:["名|語法，使い方","名|使用量"],
   pronunciation:"/ˈjuːsɪdʒ/",part:136,
   example:"This dictionary explains the usage of each difficult word.",
   exampleJa:"この辞書は、それぞれの難しい語の語法を説明している。",
   example2:"Water usage rises sharply every hot dry summer.",
   exampleJa2:"水の使用量は、暑く乾いた夏ごとに急に増える。",
   etymologyProcess:"use（使う）＋ age（名詞）→ 実際にどう使われているかを表すと…？",
   etymologyConclusion:"use（使う）＋ age（名詞）→ 実際にどう使われているかという使われ方＝語法",
   relatedWords:[
     {word:"use",meaning:"使う",breakdown:"use（使う）→ 役に立てるために用いる"},
     {word:"useful",meaning:"役に立つ",breakdown:"use（使う）＋ ful（満ちた）→ 使いでがたっぷりある"},
     {word:"abuse",meaning:"乱用する，虐待する",breakdown:"ab（離れて）＋ use（使う）→ 正しい道から離れた使い方をする"},
     {synonym:true,word:"custom",meaning:"慣習",breakdown:"世のならわし。usage は実際の使われ方のほうを指す"}]},

  {id:1354,word:"vowel",partOfSpeech:"名詞",meaning:"母音",
   meanings:["名|母音"],
   pronunciation:"/ˈvaʊəl/",part:136,
   example:"English has five vowel letters but many more sounds.",
   exampleJa:"英語には5つの母音字があるが、音はもっとずっと多い。",
   example2:"Japanese uses only five simple basic vowel sounds.",
   exampleJa2:"日本語は、5つの基本的な母音の音しか使わない。",
   etymologyProcess:"voc（呼ぶ）→ 口をふさがずに声そのものが出る音なら…？",
   etymologyConclusion:"voc（呼ぶ）→ 口をふさがずに、声そのものが出ていく音＝母音",
   relatedWords:[
     {word:"voice",meaning:"声",breakdown:"voc（呼ぶ）→ 口から出して呼びかける音"},
     {word:"vocal",meaning:"声の，ボーカルの",breakdown:"voc（呼ぶ）＋ al（形容詞）→ 声に関わっている"},
     {word:"vocabulary",meaning:"語彙",breakdown:"voc（呼ぶ）＋ ary（集まり）→ 呼び名として使える語の集まり"},
     {word:"vocation",meaning:"天職",breakdown:"voc（呼ぶ）＋ ation（名詞）→ 天から呼ばれて就く仕事"}]},

  {id:1355,word:"pronoun",partOfSpeech:"名詞",meaning:"代名詞",
   meanings:["名|代名詞"],
   pronunciation:"/ˈproʊnaʊn/",part:136,
   example:"The pronoun she refers to my older sister here.",
   exampleJa:"ここでは、代名詞 she は私の姉を指している。",
   example2:"Choose the correct pronoun for each blank below.",
   exampleJa2:"下のそれぞれの空所に、正しい代名詞を選びなさい。",
   etymologyProcess:"pro（前へ）＋ noun（名前）→ 名前の代わりに前へ立てて使う語は…？",
   etymologyConclusion:"pro（前へ）＋ noun（名前）→ 名前の代わりに前へ立てて使う語＝代名詞",
   relatedWords:[
     {word:"noun",meaning:"名詞",breakdown:"noun（名前）→ 物や人の名前を表す語"},
     {word:"name",meaning:"名前",breakdown:"name（名前）→ 人や物を呼ぶための呼び名"},
     {word:"nominate",meaning:"指名する",breakdown:"noun（名前）＋ ate（動詞）→ 名前を挙げて選び出す"},
     {synonym:true,word:"adjective",meaning:"形容詞",breakdown:"名詞を説明する語。pronoun は名詞の代わりに使う語"}]},

  {id:1356,word:"accent",partOfSpeech:"名詞",meaning:"なまり；アクセント",
   meanings:["名|なまり，話しぶり","名|（語の）アクセント，強勢"],
   pronunciation:"/ˈæksent/",part:136,
   example:"She speaks English with a slight French accent.",
   exampleJa:"彼女はわずかなフランスのなまりで英語を話す。",
   example2:"Put the accent on the first syllable of this word.",
   exampleJa2:"この語では、最初の音節にアクセントを置きなさい。",
   etymologyProcess:"ad（〜へ）＋ cant（歌う）→ 言葉にそえて歌うように付ける調子は…？",
   etymologyConclusion:"ad（〜へ）＋ cant（歌う）→ 言葉にそえて、歌うように付ける調子＝なまり",
   why:"【なぜ】ラテン語 accentus は ad（〜へ）＋ cantus（歌）で、「言葉にそえる歌」。ギリシャ語の「声の調子」を訳した語です。そこから語の強弱や、その土地らしい話し方＝なまりになりました。\n【つながり】chant（節をつけて唱える）、enchant（歌いかけて魅了する）も同じ cant の家族です。",
   relatedWords:[
     {word:"chant",meaning:"詠唱する",breakdown:"cant（歌う）→ 節をつけて何度もくり返し唱える"},
     {word:"enchant",meaning:"魅了する",breakdown:"en（中に）＋ cant（歌う）→ 歌いかけて心を奪ってしまう"},
     {synonym:true,word:"dialect",meaning:"方言",breakdown:"その土地の言葉づかい。accent は発音のなまりのほうを指す"},
     {synonym:true,word:"stress",meaning:"強勢",breakdown:"語の中で強く読む所。accent はその印やなまりも指す"}]},

  {id:1357,word:"outline",partOfSpeech:"他動詞",meaning:"要点を述べる",
   meanings:["他|要点を述べる，概略を示す","名|輪郭；概要"],
   pronunciation:"/ˈaʊtlaɪn/",part:136,
   example:"Please outline your plan in three short clear sentences.",
   exampleJa:"あなたの計画の要点を、3つの短くはっきりした文で述べてください。",
   example2:"The teacher outlined the rules before the long test.",
   exampleJa2:"先生は、その長いテストの前に規則の要点を述べた。",
   etymologyProcess:"out（外へ）＋ line（線）→ 外側だけを線でなぞって大まかに示すと…？",
   etymologyConclusion:"out（外へ）＋ line（線）→ 外側だけを線でなぞって、大まかに示す＝要点を述べる",
   relatedWords:[
     {word:"line",meaning:"線；列",breakdown:"line（線）→ まっすぐに引かれた一本のすじ"},
     {word:"deadline",meaning:"締め切り",breakdown:"dead（動かない）＋ line（線）→ 越えたら動けなくなる境目の線"},
     {word:"underline",meaning:"下線を引く；強調する",breakdown:"under（下に）＋ line（線）→ 下に線を引いて目立たせる"},
     {synonym:true,word:"summarize",meaning:"要約する",breakdown:"短くまとめること。outline は大筋だけを示すことを言う"}]},

  {id:1358,word:"remote",partOfSpeech:"形容詞",meaning:"遠く離れた",
   meanings:["形|遠く離れた，へんぴな","形|（可能性が）ごくわずかな"],
   pronunciation:"/rɪˈmoʊt/",part:136,
   example:"They live in a remote village deep in the mountains.",
   exampleJa:"彼らは、山の奥深くの遠く離れた村に住んでいる。",
   example2:"The chance of rain is remote this whole afternoon.",
   exampleJa2:"今日の午後いっぱい、雨の可能性はごくわずかだ。",
   etymologyProcess:"re（後ろへ）＋ mot（動かす）→ ずっと後ろへ動かされて離れていると…？",
   etymologyConclusion:"re（後ろへ）＋ mot（動かす）→ ずっと後ろへ動かされて離れている＝遠く離れた",
   relatedWords:[
     {word:"motion",meaning:"動き",breakdown:"mot（動かす）＋ ion（名詞）→ 動いているということ"},
     {word:"emotion",meaning:"感情",breakdown:"e（外へ）＋ mot（動かす）→ 心が外へ動き出して表に現れるもの"},
     {word:"mobile",meaning:"動きやすい",breakdown:"mob（動かす）＋ ile（できる）→ 自由に動かすことができる"},
     {word:"remove",meaning:"取り除く",breakdown:"re（後ろへ）＋ mov（動かす）→ 元の場所から動かしてどける"}]},

  {id:1359,word:"ambition",partOfSpeech:"名詞",meaning:"願望，野望",
   meanings:["名|（強い）願望，野望"],
   pronunciation:"/æmˈbɪʃn/",part:136,
   example:"Her ambition is to become a great space engineer.",
   exampleJa:"彼女の願望は、偉大な宇宙技師になることだ。",
   example2:"He had great ambition even as a young boy.",
   exampleJa2:"彼は幼い少年のころから、大きな野望を持っていた。",
   etymologyProcess:"ambi（まわりを）＋ it（行く）→ 票を求めて回り歩くほど強く望むと…？",
   etymologyConclusion:"ambi（まわりを）＋ it（行く）→ 回り歩いてでも手に入れたいと望む心＝願望",
   why:"【なぜ】ラテン語 ambitio は「まわりを歩き回ること」。古代ローマで、候補者が票を求めて市民の間を回り歩いたことを指しました。そこから「強く手に入れたいと望む心」＝願望・野望になりました。\n【つながり】ambulance（もとは動き回る野戦病院）、exit（外へ行く）も同じ家族です。",
   relatedWords:[
     {word:"ambitious",meaning:"野心的な",breakdown:"ambi（まわりを）＋ it（行く）＋ ous（形容詞）→ 強く望んで動き回る"},
     {word:"transit",meaning:"通過，輸送",breakdown:"trans（越えて）＋ it（行く）→ 境を越えて行くこと"},
     {word:"exit",meaning:"出口",breakdown:"ex（外へ）＋ it（行く）→ 外へ出て行くところ"},
     {synonym:true,word:"desire",meaning:"強い願い",breakdown:"ほしがる気持ち。ambition は成し遂げたい大きな望みを指す"}]},

  {id:1360,word:"temper",partOfSpeech:"名詞",meaning:"気性，かんしゃく",
   meanings:["名|気性，気質","名|（短気な）かんしゃく"],
   pronunciation:"/ˈtempər/",part:136,
   example:"He has a very quick temper early in the morning.",
   exampleJa:"彼は朝早い時間、とても激しやすい気性だ。",
   example2:"She kept her temper during the whole long argument.",
   exampleJa2:"彼女は長い議論の間ずっと、気性を抑えてかっとならずにいた。",
   etymologyProcess:"temper（ほどよく混ぜる）→ 心の成分の混ざり具合を指すと…？",
   etymologyConclusion:"temper（ほどよく混ぜる）→ 心の成分がどう混ざっているかという生まれつきの調子＝気性",
   why:"【なぜ】ラテン語 temperare は「ほどよく混ぜる」。昔は体の中の四つの液の混ざり具合が性格を決めると考えられ、その「混ざり具合」がそのまま temper（気性）になりました。\n【つながり】temperature（熱と冷の混ざり具合＝温度）、temperate（ほどよい）も同じ家族です。",
   relatedWords:[
     {word:"temperature",meaning:"温度",breakdown:"temper（ほどよく混ぜる）＋ ure（名詞）→ 熱と冷の混ざり具合"},
     {word:"temperate",meaning:"温和な；節度ある",breakdown:"temper（ほどよく混ぜる）＋ ate（形容詞）→ ほどよく混ざっている"},
     {word:"temperament",meaning:"気質",breakdown:"temper（ほどよく混ぜる）＋ ment（名詞）→ 生まれつきの混ざり具合"},
     {synonym:true,word:"mood",meaning:"気分",breakdown:"その時々の気持ち。temper は生まれつきの気性のほうを指す"}]},

  {id:1361,word:"affection",partOfSpeech:"名詞",meaning:"愛情，優しい思い",
   meanings:["名|愛情，優しい思い"],
   pronunciation:"/əˈfekʃn/",part:137,
   example:"She showed deep affection for her old sick dog.",
   exampleJa:"彼女は、年老いた病気の犬に深い愛情を示した。",
   example2:"His long letters were full of warm quiet affection.",
   exampleJa2:"彼の長い手紙は、温かく静かな愛情に満ちていた。",
   etymologyProcess:"ad（〜へ）＋ fect（作る）→ 相手へ向かって心に作り出される思いなら…？",
   etymologyConclusion:"ad（〜へ）＋ fect（作る）→ 相手へ向かって心に作り出される温かい思い＝愛情",
   relatedWords:[
     {word:"affect",meaning:"影響する",breakdown:"ad（〜へ）＋ fect（作る）→ そこへ働きかけて変化を作る"},
     {word:"effect",meaning:"効果",breakdown:"ef（外へ）＋ fect（作る）→ 外へ作り出される結果"},
     {word:"perfect",meaning:"完全な",breakdown:"per（すっかり）＋ fect（作る）→ すっかり作り上げられている"},
     {word:"infect",meaning:"感染させる",breakdown:"in（中へ）＋ fect（作る）→ 体の中に入り込んで病を作り出す"}]},

  {id:1362,word:"enthusiasm",partOfSpeech:"名詞",meaning:"熱意，熱中",
   meanings:["名|熱意，熱中"],
   pronunciation:"/ɪnˈθuːziæzəm/",part:137,
   example:"The students showed great enthusiasm for the new project.",
   exampleJa:"生徒たちは、その新しい計画に大きな熱意を示した。",
   example2:"His enthusiasm for music never faded over the years.",
   exampleJa2:"彼の音楽への熱意は、年月がたっても薄れることがなかった。",
   etymologyProcess:"en（中に）＋ the（神）→ 神が中に入り込んだようにわき立つと…？",
   etymologyConclusion:"en（中に）＋ the（神）→ 神が中に入り込んだようにわき立つ気持ち＝熱意",
   why:"【なぜ】ギリシャ語 enthousiasmos は「神が中に入り込むこと」。神がかりになって夢中になる様子から、「熱意・熱中」になりました。\n【つながり】theology（神について調べる学問＝神学）も同じ the（神）の家族です。",
   relatedWords:[
     {word:"enthusiastic",meaning:"熱心な",breakdown:"en（中に）＋ the（神）＋ ic（形容詞）→ 神がかりのように夢中な"},
     {word:"theology",meaning:"神学",breakdown:"the（神）＋ log（学問）→ 神について調べる学問"},
     {synonym:true,word:"passion",meaning:"情熱",breakdown:"身を焦がす思い。enthusiasm はわき立つ意気込みを指す"},
     {synonym:true,word:"eagerness",meaning:"熱心さ",breakdown:"やりたくてたまらない気持ち。enthusiasm は夢中さを指す"}]},

  {id:1363,word:"rage",partOfSpeech:"名詞",meaning:"激怒",
   meanings:["名|激怒，猛烈な怒り"],
   pronunciation:"/reɪdʒ/",part:137,
   example:"He shook with rage when he heard the terrible news.",
   exampleJa:"そのひどい知らせを聞いたとき、彼は怒りで体を震わせた。",
   example2:"Her rage slowly cooled during the quiet evening walk.",
   exampleJa2:"彼女の怒りは、静かな夕方の散歩の間にゆっくり収まった。",
   etymologyProcess:"rab（狂う）→ 我を忘れるほど激しく燃え上がる怒りなら…？",
   etymologyConclusion:"rab（狂う）→ 我を忘れるほど激しく燃え上がってしまう怒り＝激怒",
   relatedWords:[
     {word:"rabies",meaning:"狂犬病",breakdown:"rab（狂う）→ 動物を狂わせてしまう恐ろしい病"},
     {synonym:true,word:"anger",meaning:"怒り",breakdown:"ふつうの怒り。rage は我を忘れるほど激しい怒りを指す"},
     {synonym:true,word:"fury",meaning:"激怒",breakdown:"ほぼ同じ意味。rage は燃え上がるような激しさを表す"},
     {synonym:true,word:"temper",meaning:"かんしゃく",breakdown:"怒りっぽい気性。rage はその場で爆発する激しい怒り"}]},

  {id:1364,word:"incredible",partOfSpeech:"形容詞",meaning:"信じられない",
   meanings:["形|信じられない，途方もない"],
   pronunciation:"/ɪnˈkredəbl/",part:137,
   example:"The view from the mountain top was simply incredible.",
   exampleJa:"山頂からの眺めは、ただただ信じられないほどだった。",
   example2:"She told us an incredible story about her long trip.",
   exampleJa2:"彼女は長い旅についての、信じられない話を聞かせてくれた。",
   etymologyProcess:"in（否定）＋ cred（信じる）＋ ible（できる）→ 本当かと疑うほどすごいと…？",
   etymologyConclusion:"in（否定）＋ cred（信じる）＋ ible（できる）→ とても信じることができない＝信じられない",
   relatedWords:[
     {word:"credit",meaning:"クレジット；信用",breakdown:"cred（信じる）＋ it（〜された）→ 後で払うと信じてもらえること"},
     {word:"credible",meaning:"信じられる",breakdown:"cred（信じる）＋ ible（できる）→ 信じることができる"},
     {word:"creed",meaning:"信条",breakdown:"cred（信じる）→ 信じて守ると決めた教え"},
     {synonym:true,word:"amazing",meaning:"驚くべき",breakdown:"頭がぽかんとなる驚き。incredible は信じがたいほどすごいこと"}]},

  {id:1365,word:"chuckle",partOfSpeech:"自動詞",meaning:"くすくす笑う",
   meanings:["自|（のどで低く）くすくす笑う"],
   pronunciation:"/ˈtʃʌkl/",part:137,
   example:"He chuckled quietly at the old family photo album.",
   exampleJa:"彼は古い家族写真のアルバムを見て、静かにくすくす笑った。",
   example2:"The children chuckle every single time they hear it.",
   exampleJa2:"子どもたちはそれを聞くたびに、毎回くすくす笑う。",
   etymologyProcess:"chuckle（のどで低く笑う）→ のどの奥で声を殺して小さく笑うと…？",
   etymologyConclusion:"chuckle（のどで低く笑う）→ のどの奥で声を殺して小さく笑う＝くすくす笑う",
   hook:"音をまねて生まれた語。のどの奥で「くっくっ」と低く笑う感じ。",
   relatedWords:[
     {synonym:true,word:"laugh",meaning:"笑う",breakdown:"声を出して笑うこと。chuckle は低く小さく笑うこと"},
     {synonym:true,word:"giggle",meaning:"くすくす笑う",breakdown:"かん高く笑うこと。chuckle はのどの奥で低く笑う"},
     {synonym:true,word:"smile",meaning:"ほほえむ",breakdown:"声を出さずに笑うこと。chuckle は小さな声が出る"},
     {synonym:true,word:"grin",meaning:"にやりと笑う",breakdown:"歯を見せて笑うこと。chuckle は低い笑い声を伴う"}]},

  {id:1366,word:"dare",partOfSpeech:"他動詞",meaning:"思い切って～する",
   meanings:["他|（to do）思い切って～する，あえて～する"],
   pronunciation:"/der/",part:137,
   example:"I did not dare to ask him that difficult question.",
   exampleJa:"私は怖くて、彼にその難しい質問をすることができなかった。",
   example2:"Few people dare to swim in this cold fast river.",
   exampleJa2:"この冷たく流れの速い川で思い切って泳ぐ人は、ほとんどいない。",
   etymologyProcess:"dare（あえてする）→ こわさを押しのけてあえて踏み出すと…？",
   etymologyConclusion:"dare（あえてする）→ こわさを押しのけて、あえて踏み出す＝思い切って～する",
   hook:"How dare you!（よくもまあ）は決まり文句。「あえてする」が芯。",
   relatedWords:[
     {synonym:true,word:"brave",meaning:"勇敢な",breakdown:"恐れず立ち向かうこと。dare は実際に踏み出す行いを言う"},
     {synonym:true,word:"risk",meaning:"危険をおかす",breakdown:"あえて危険を取ること。dare は恐れを押しのけて行うこと"},
     {synonym:true,word:"challenge",meaning:"挑む",breakdown:"難しいことに挑むこと。dare は思い切って踏み出すこと"},
     {synonym:true,word:"venture",meaning:"思い切ってやる",breakdown:"危険を承知で進むこと。dare とほぼ同じ向きの語"}]},

  {id:1367,word:"scream",partOfSpeech:"自動詞",meaning:"悲鳴を上げる",
   meanings:["自|悲鳴を上げる，かん高く叫ぶ"],
   pronunciation:"/skriːm/",part:137,
   example:"She screamed loudly when she suddenly saw the snake.",
   exampleJa:"彼女は突然ヘビを見たとき、大声で悲鳴を上げた。",
   example2:"Children scream with joy on the big roller coaster.",
   exampleJa2:"子どもたちは大きなジェットコースターで、喜びの悲鳴を上げる。",
   etymologyProcess:"scream（かん高く叫ぶ）→ 恐れや痛みでかん高い声を張り上げると…？",
   etymologyConclusion:"scream（かん高く叫ぶ）→ 恐れや痛みで、かん高い声を張り上げる＝悲鳴を上げる",
   hook:"音をまねて生まれた語。かん高く鋭い叫び声が芯にある。",
   relatedWords:[
     {synonym:true,word:"shout",meaning:"叫ぶ",breakdown:"大きな声を出すこと。scream はかん高く鋭い声を上げる"},
     {synonym:true,word:"yell",meaning:"叫ぶ，どなる",breakdown:"腹から声を張り上げること。scream はかん高い悲鳴を指す"},
     {synonym:true,word:"cry",meaning:"叫ぶ；泣く",breakdown:"声を上げること。scream は恐れや痛みのかん高い声"},
     {synonym:true,word:"shriek",meaning:"金切り声を上げる",breakdown:"ほぼ同じ意味。scream のほうが日常でよく使う語"}]},

  {id:1368,word:"soothe",partOfSpeech:"他動詞",meaning:"なだめる，やわらげる",
   meanings:["他|（人）をなだめる","他|（痛み）をやわらげる"],
   pronunciation:"/suːð/",part:137,
   example:"She soothed the crying baby with a soft gentle song.",
   exampleJa:"彼女は柔らかく優しい歌で、泣いている赤ちゃんをなだめた。",
   example2:"Warm tea can soothe a sore dry winter throat.",
   exampleJa2:"温かいお茶は、冬の痛む乾いたのどをやわらげてくれる。",
   etymologyProcess:"sooth（本当だと言う）→ そうだそうだと受け止めて気持ちを静めると…？",
   etymologyConclusion:"sooth（本当だと言う）→ そうだそうだと受け止めて気持ちを静める＝なだめる",
   why:"【なぜ】古英語の sōth は「本当の」。「そのとおりだ」と相手に同意してやることが相手を落ち着かせることにつながり、「なだめる」になりました。\n【つながり】soothsayer（本当のことを言う者＝予言者）に、今も元の意味が残っています。",
   relatedWords:[
     {word:"soothsayer",meaning:"予言者",breakdown:"sooth（本当だと言う）→ 本当のことを言い当てるとされた人"},
     {synonym:true,word:"calm",meaning:"落ち着かせる",breakdown:"静かにさせること。soothe は優しく慰めて静めることを言う"},
     {synonym:true,word:"comfort",meaning:"慰める",breakdown:"つらさをやわらげること。soothe は泣く子をなだめる感じ"},
     {synonym:true,word:"relieve",meaning:"やわらげる",breakdown:"苦しみを軽くすること。soothe はそっと静めることを言う"}]},

  {id:1369,word:"tempt",partOfSpeech:"他動詞",meaning:"誘惑する",
   meanings:["他|誘惑する，その気にさせる"],
   pronunciation:"/tempt/",part:137,
   example:"Sweet cakes always tempt me after a long hard day.",
   exampleJa:"甘いケーキは、長くつらい一日の後でいつも私を誘惑する。",
   example2:"Do not let easy money tempt you into cheating.",
   exampleJa2:"楽に手に入るお金が、あなたをごまかしへ誘惑するままにしてはいけない。",
   etymologyProcess:"tempt（試す）→ 心が動くかどうか試すようにさそうと…？",
   etymologyConclusion:"tempt（試す）→ 心が動くかどうか試すように、そっとさそう＝誘惑する",
   relatedWords:[
     {word:"attempt",meaning:"試み",breakdown:"ad（〜へ）＋ tempt（試す）→ できるかどうか手を伸ばして試すこと"},
     {word:"temptation",meaning:"誘惑",breakdown:"tempt（試す）＋ ation（名詞）→ 心を試しにさそってくるもの"},
     {synonym:true,word:"attract",meaning:"引きつける",breakdown:"引き寄せること。tempt は悪い方へさそう含みがある"},
     {synonym:true,word:"lure",meaning:"おびき寄せる",breakdown:"えさで誘うこと。tempt は心をゆさぶってさそうことを言う"}]},

  {id:1370,word:"scold",partOfSpeech:"他動詞",meaning:"叱る",
   meanings:["他|（子どもなどを）叱る"],
   pronunciation:"/skoʊld/",part:137,
   example:"The teacher scolded us for arriving so very late.",
   exampleJa:"先生は、私たちがとても遅く着いたことで叱った。",
   example2:"My mother never scolds me without a good reason.",
   exampleJa2:"母は、もっともな理由なしに私を叱ることは決してない。",
   etymologyProcess:"scold（言葉で責める）→ 悪い点をあげつらって強い言葉で責めると…？",
   etymologyConclusion:"scold（言葉で責める）→ 悪い点をあげつらい、強い言葉で責める＝叱る",
   hook:"古ノルド語の skald（詩人）から。詩で人をけなしたことが芯にある。",
   relatedWords:[
     {synonym:true,word:"blame",meaning:"責める",breakdown:"責任があるとすること。scold は面と向かって叱ることを言う"},
     {synonym:true,word:"criticize",meaning:"批判する",breakdown:"悪い点を指摘すること。scold は目下の相手を叱ること"},
     {synonym:true,word:"warn",meaning:"警告する",breakdown:"前もって知らせること。scold は起きた後で責めること"},
     {synonym:true,word:"tell off",meaning:"叱りつける",breakdown:"くだけた言い方。scold は少し硬く、書き言葉でも使う"}]},

  {id:1371,word:"oppress",partOfSpeech:"他動詞",meaning:"圧迫する，しいたげる",
   meanings:["他|圧迫する，しいたげる"],
   pronunciation:"/əˈpres/",part:138,
   example:"That government oppressed its own people for many years.",
   exampleJa:"あの政府は、何年もの間自国民を圧迫した。",
   example2:"Too many rules can oppress young creative minds.",
   exampleJa2:"多すぎる規則は、若く創造的な心を圧迫することがある。",
   etymologyProcess:"op（向かい合って）＋ press（押す）→ 上から押さえつけて自由を奪うと…？",
   etymologyConclusion:"op（向かい合って）＋ press（押す）→ 上から押さえつけて自由を奪う＝圧迫する",
   relatedWords:[
     {word:"press",meaning:"押す",breakdown:"press（押す）→ 上から力をかけて押しつける"},
     {word:"impress",meaning:"感銘を与える",breakdown:"im（中へ）＋ press（押す）→ 心の中に強く押し込む"},
     {word:"express",meaning:"表現する",breakdown:"ex（外へ）＋ press（押す）→ 思いを外へ押し出す"},
     {word:"depress",meaning:"憂うつにさせる",breakdown:"de（下へ）＋ press（押す）→ 気持ちを下へ押しつけて沈ませる"}]},

  {id:1372,word:"threaten",partOfSpeech:"他動詞",meaning:"脅かす，脅す",
   meanings:["他|脅かす，脅す","他|（危険が）迫る"],
   pronunciation:"/ˈθretn/",part:138,
   example:"Rising seas threaten many small island nations today.",
   exampleJa:"海面の上昇が、今日多くの小さな島国を脅かしている。",
   example2:"He threatened to call the police late that night.",
   exampleJa2:"彼はその夜遅く、警察を呼ぶと脅した。",
   etymologyProcess:"threat（押し迫る）＋ en（〜にする）→ 危害を加えると言って押し迫ると…？",
   etymologyConclusion:"threat（押し迫る）＋ en（〜にする）→ 危害を加えると言って押し迫る＝脅かす",
   relatedWords:[
     {word:"threat",meaning:"脅し，脅威",breakdown:"threat（押し迫る）→ 危害が押し迫ってくること"},
     {synonym:true,word:"warn",meaning:"警告する",breakdown:"危ないと知らせること。threaten は害を加えると言って迫る"},
     {synonym:true,word:"frighten",meaning:"こわがらせる",breakdown:"恐れを起こさせること。threaten は害を加えるとほのめかす"},
     {synonym:true,word:"endanger",meaning:"危険にさらす",breakdown:"危険な状態にすること。threaten は脅かして迫ることを言う"}]},

  {id:1373,word:"mourn",partOfSpeech:"自動詞",meaning:"嘆く，悼む",
   meanings:["自|（死を）嘆く，悼む","他|（死者）を悼む"],
   pronunciation:"/mɔːrn/",part:138,
   example:"The whole town mourned the death of its mayor.",
   exampleJa:"町全体が、市長の死を悼んだ。",
   example2:"They still mourn for their lost old childhood friend.",
   exampleJa2:"彼らは今も、亡くした幼なじみを悼んでいる。",
   etymologyProcess:"mourn（心にとどめて悲しむ）→ 失った人を心にとどめて深く悲しむと…？",
   etymologyConclusion:"mourn（心にとどめて悲しむ）→ 失った人を心にとどめて深く悲しむ＝悼む",
   hook:"語源ははっきりしない。memory（記憶）と同じ根とも言われる。",
   relatedWords:[
     {synonym:true,word:"grieve",meaning:"深く悲しむ",breakdown:"強い悲しみに沈むこと。mourn は死を悼むことに多く使う"},
     {synonym:true,word:"sorrow",meaning:"悲しみ",breakdown:"重く沈んだ悲しみ。mourn はそれを表す行いのほうを指す"},
     {synonym:true,word:"weep",meaning:"涙を流す",breakdown:"静かに泣くこと。mourn は悲しみを表す行い全体を指す"},
     {synonym:true,word:"miss",meaning:"いなくて寂しく思う",breakdown:"いない人を思うこと。mourn は死を悼んで深く悲しむこと"}]},

  {id:1374,word:"sacrifice",partOfSpeech:"他動詞",meaning:"犠牲にする",
   meanings:["他|犠牲にする，ささげる","名|犠牲"],
   pronunciation:"/ˈsækrɪfaɪs/",part:138,
   example:"She sacrificed her free time for the whole team.",
   exampleJa:"彼女はチーム全体のために、自分の自由な時間を犠牲にした。",
   example2:"Many students sacrifice sleep during the long exam week.",
   exampleJa2:"多くの生徒が、長い試験週間に睡眠を犠牲にする。",
   etymologyProcess:"sacr（神にささげる）＋ fic（作る）→ 大切なものを神にささげるものにすると…？",
   etymologyConclusion:"sacr（神にささげる）＋ fic（作る）→ 大切なものを、神にささげるものにする＝犠牲にする",
   relatedWords:[
     {word:"sacred",meaning:"神聖な",breakdown:"sacr（神にささげる）＋ ed（〜された）→ 神にささげられておかしがたい"},
     {word:"sacrament",meaning:"（教会の）秘跡",breakdown:"sacr（神にささげる）＋ ment（名詞）→ 神にささげる聖なる儀式"},
     {word:"perfect",meaning:"完全な",breakdown:"per（すっかり）＋ fect（作る）→ すっかり作り上げられている"},
     {synonym:true,word:"give up",meaning:"あきらめる",breakdown:"手放すこと。sacrifice はもっと大切なもののために手放すこと"}]},

  {id:1375,word:"curse",partOfSpeech:"名詞",meaning:"のろい；災いの元",
   meanings:["名|のろい","名|災いの元","他|のろう"],
   pronunciation:"/kɜːrs/",part:138,
   example:"The old story tells of a terrible ancient curse.",
   exampleJa:"その古い物語は、恐ろしい古代ののろいについて語っている。",
   example2:"Sudden fame can be a curse for young singers.",
   exampleJa2:"突然の名声は、若い歌手にとって災いの元になりうる。",
   etymologyProcess:"curse（のろいの言葉）→ 人に災いが降りかかるよう願う言葉なら…？",
   etymologyConclusion:"curse（のろいの言葉）→ 人に災いが降りかかるよう願う言葉と、その災い＝のろい",
   hook:"語源ははっきりしない。bless（祝福する）とちょうど逆の働きの語。",
   relatedWords:[
     {synonym:true,word:"spell",meaning:"呪文",breakdown:"となえる言葉。curse は災いを願うのろいの言葉を指す"},
     {synonym:true,word:"misfortune",meaning:"不運",breakdown:"不幸なめぐり合わせ。curse はのろいがもたらす災いを指す"},
     {synonym:true,word:"burden",meaning:"重荷",breakdown:"背負わされるつらさ。curse は災いの元になるものを指す"},
     {synonym:true,word:"swear",meaning:"ののしる，悪態をつく",breakdown:"荒い言葉を吐くこと。curse はそのための言葉そのものも指す"}]},

  {id:1376,word:"stem",partOfSpeech:"自動詞",meaning:"（from ～に）由来する",
   meanings:["自|（from ～に）由来する，～から生じる","名|（草木の）茎"],
   pronunciation:"/stem/",part:138,
   example:"Many problems stem from one simple small misunderstanding.",
   exampleJa:"多くの問題は、一つの単純で小さな誤解に由来する。",
   example2:"Her quiet confidence stems from years of daily practice.",
   exampleJa2:"彼女の静かな自信は、長年の毎日の練習に由来する。",
   etymologyProcess:"stem（立てる）→ 草の茎が根から立ち上がるように出てくると…？",
   etymologyConclusion:"stem（立てる）→ 草の茎が根から立ち上がるように、そこから出てくる＝由来する",
   hook:"stem from ～（～に由来する）の形で覚える。名詞の「茎」と同じ語。",
   why:"【なぜ】stem はもともと「木や草の茎」。すべての枝や葉が一本の茎から出ているように、物事の出どころをたどる言い方として「〜に由来する」が生まれました。\n【つながり】名詞の stem（茎）、言語学で言う「語幹」も同じ語です。",
   relatedWords:[
     {synonym:true,word:"derive",meaning:"由来する",breakdown:"もとから流れ出ること。stem は一本の茎のように出どころを示す"},
     {synonym:true,word:"originate",meaning:"始まる",breakdown:"そこから起こること。stem は出どころをたどる言い方"},
     {synonym:true,word:"root",meaning:"根，根源",breakdown:"物事のもと。stem はそこから立ち上がる茎にあたる"},
     {synonym:true,word:"result",meaning:"結果として起こる",breakdown:"result from も「〜から生じる」。stem は出どころを強く示す"}]},

  {id:1377,word:"trigger",partOfSpeech:"他動詞",meaning:"きっかけになる，引き起こす",
   meanings:["他|きっかけになる，引き起こす","名|引き金"],
   pronunciation:"/ˈtrɪɡər/",part:138,
   example:"Heavy rain can trigger a sudden mudslide around here.",
   exampleJa:"激しい雨は、この辺りで突然の土砂崩れのきっかけになりうる。",
   example2:"One small careless word triggered the whole long argument.",
   exampleJa2:"一つの小さな不用意な言葉が、長い議論全体のきっかけになった。",
   etymologyProcess:"trigger（引くもの）→ 引き金を引くように物事を始めさせると…？",
   etymologyConclusion:"trigger（引くもの）→ 引き金を引くように、物事を一気に始めさせる＝きっかけになる",
   hook:"銃の「引き金」がもとの意味。引いた瞬間に始まるのが芯。",
   relatedWords:[
     {synonym:true,word:"cause",meaning:"引き起こす",breakdown:"原因になること。trigger はその場で始めさせるきっかけを指す"},
     {synonym:true,word:"start",meaning:"始める",breakdown:"始めること。trigger は一気に動き出させるきっかけを言う"},
     {synonym:true,word:"spark",meaning:"火をつける，引き起こす",breakdown:"火花を散らすこと。trigger は引き金を引く瞬間の感じ"},
     {synonym:true,word:"set off",meaning:"引き起こす",breakdown:"作動させること。trigger は一気に動き出させることを言う"}]},

  {id:1378,word:"consequence",partOfSpeech:"名詞",meaning:"結果，影響",
   meanings:["名|（行いの）結果，影響"],
   pronunciation:"/ˈkɑːnsəkwens/",part:138,
   example:"He accepted the consequences of his own free choice.",
   exampleJa:"彼は自分の自由な選択の結果を受け入れた。",
   example2:"Small actions can have huge consequences much later.",
   exampleJa2:"小さな行いが、ずっと後でとても大きな結果をもたらすことがある。",
   etymologyProcess:"con（共に）＋ sequ（ついて行く）→ ある行いに必ずついてくるものは…？",
   etymologyConclusion:"con（共に）＋ sequ（ついて行く）→ ある行いのあとに必ずついてくるもの＝結果",
   relatedWords:[
     {word:"sequence",meaning:"順序，連続",breakdown:"sequ（ついて行く）＋ ence（名詞）→ 次々についていく並び"},
     {word:"subsequent",meaning:"続いて起こる",breakdown:"sub（下で）＋ sequ（ついて行く）→ すぐ後ろについて続いてくる"},
     {word:"pursue",meaning:"追い求める",breakdown:"pur（前へ）＋ sequ（ついて行く）→ 前へ前へと追いかけていく"},
     {synonym:true,word:"result",meaning:"結果",breakdown:"生じたこと。consequence は行いに必ずついてくる結果を指す"}]},

  {id:1379,word:"process",partOfSpeech:"名詞",meaning:"過程，手順",
   meanings:["名|過程，手順","他|処理する"],
   pronunciation:"/ˈprɑːses/",part:138,
   example:"Learning a language is a slow but steady process.",
   exampleJa:"言語を学ぶことは、ゆっくりだが着実な過程だ。",
   example2:"The whole process takes about three full working days.",
   exampleJa2:"その過程全体には、約3営業日まるまるかかる。",
   etymologyProcess:"pro（前へ）＋ cess（行く）→ 前へ一歩ずつ進んでいく道のりは…？",
   etymologyConclusion:"pro（前へ）＋ cess（行く）→ 前へ一歩ずつ進んでいく道のり＝過程",
   relatedWords:[
     {word:"proceed",meaning:"進む",breakdown:"pro（前へ）＋ ceed（行く）→ 止まらずに前へ進んでいく"},
     {word:"succeed",meaning:"成功する；後を継ぐ",breakdown:"suc（すぐ後に）＋ ceed（行く）→ すぐ後について行き着く"},
     {word:"exceed",meaning:"超える",breakdown:"ex（外へ）＋ ceed（行く）→ 決められた枠の外へ行ってしまう"},
     {word:"access",meaning:"接近；利用する権利",breakdown:"ac（〜へ）＋ cess（行く）→ そこへ行き着くための道"}]},

  {id:1380,word:"resort",partOfSpeech:"自動詞",meaning:"（to ～に）訴える，頼る",
   meanings:["自|（to ～に）訴える，頼る","名|行楽地，リゾート"],
   pronunciation:"/rɪˈzɔːrt/",part:138,
   example:"Never resort to violence in any difficult situation.",
   exampleJa:"どんな難しい状況でも、決して暴力に訴えてはいけない。",
   example2:"They had to resort to using a very old map.",
   exampleJa2:"彼らは、とても古い地図に頼らざるを得なかった。",
   etymologyProcess:"re（再び）＋ sorti（出る）→ ほかに道がなく何度もそこへ足を向けると…？",
   etymologyConclusion:"re（再び）＋ sorti（出る）→ ほかに道がなく、くり返しそこへ足を向けて頼る＝訴える",
   why:"【なぜ】古フランス語 resortir は re（再び）＋ sortir（出る）で「くり返しそこへ出向く」。名詞の「リゾート（行楽地）」も「人が何度も出かける所」から来ています。動詞では「ほかに道がなく、くり返しそこへ足を向ける」→「（最後の手段に）訴える・頼る」になりました。\n【つながり】re は return（戻る）と同じ「再び」です。",
   relatedWords:[
     {synonym:true,word:"rely",meaning:"頼る",breakdown:"あてにすること。resort はほかに手がなくて頼ることを言う"},
     {synonym:true,word:"turn to",meaning:"頼る",breakdown:"その人に向かうこと。resort は最後の手段として使うこと"},
     {word:"return",meaning:"戻る，返す",breakdown:"re（再び）＋ turn（回る）→ もとの所へもう一度向かう"},
     {synonym:true,word:"depend",meaning:"頼る，依存する",breakdown:"寄りかかること。resort はいよいよのときに頼ることを言う"}]},

  {id:1381,word:"formula",partOfSpeech:"名詞",meaning:"公式；決まったやり方",
   meanings:["名|（数学などの）公式","名|決まったやり方，処方"],
   pronunciation:"/ˈfɔːrmjələ/",part:139,
   example:"Every student must learn this simple math formula.",
   exampleJa:"どの生徒も、この単純な数学の公式を学ばなければならない。",
   example2:"There is no magic formula for real lasting success.",
   exampleJa2:"本当に長続きする成功に、魔法のような決まったやり方はない。",
   etymologyProcess:"form（形）＋ ula（小さいもの）→ 小さな決まった形にまとめると…？",
   etymologyConclusion:"form（形）＋ ula（小さいもの）→ 決まった形にはめた、短い言い方や式＝公式",
   relatedWords:[
     {word:"form",meaning:"形；形づくる",breakdown:"form（形）→ 目に見えるまとまった形"},
     {word:"reform",meaning:"改革する",breakdown:"re（再び）＋ form（形）→ もう一度よい形に作り直す"},
     {word:"uniform",meaning:"制服；均一の",breakdown:"uni（1つの）＋ form（形）→ みんな同じ一つの形"},
     {word:"inform",meaning:"知らせる",breakdown:"in（中へ）＋ form（形）→ 相手の頭の中に形を作ってやる"}]},

  {id:1382,word:"procedure",partOfSpeech:"名詞",meaning:"手続き，やり方の順序",
   meanings:["名|手続き，やり方の順序"],
   pronunciation:"/prəˈsiːdʒər/",part:139,
   example:"Follow the safety procedure before you start working here.",
   exampleJa:"ここで働き始める前に、安全の手続きに従ってください。",
   example2:"The application procedure takes about two full weeks.",
   exampleJa2:"申し込みの手続きには、約2週間まるまるかかる。",
   etymologyProcess:"pro（前へ）＋ ced（行く）→ 前へ進めていくための決まった段取りは…？",
   etymologyConclusion:"pro（前へ）＋ ced（行く）＋ ure（名詞）→ 前へ進めていくための決まった段取り＝手続き",
   relatedWords:[
     {word:"proceed",meaning:"進む",breakdown:"pro（前へ）＋ ceed（行く）→ 止まらずに前へ進んでいく"},
     {word:"process",meaning:"過程",breakdown:"pro（前へ）＋ cess（行く）→ 前へ一歩ずつ進んでいく道のり"},
     {word:"exceed",meaning:"超える",breakdown:"ex（外へ）＋ ceed（行く）→ 決められた枠の外へ行ってしまう"},
     {word:"precede",meaning:"先に行く，先立つ",breakdown:"pre（先に）＋ ced（行く）→ ほかより先に行く"}]},

  {id:1383,word:"extraordinary",partOfSpeech:"形容詞",meaning:"並外れた",
   meanings:["形|並外れた，異常な"],
   pronunciation:"/ɪkˈstrɔːrdəneri/",part:139,
   example:"She has an extraordinary memory for people's names.",
   exampleJa:"彼女は人の名前に対して、並外れた記憶力を持っている。",
   example2:"That was an extraordinary game from start to finish.",
   exampleJa2:"あれは、初めから終わりまで並外れた試合だった。",
   etymologyProcess:"extra（範囲の外へ）＋ ordinary（ふつうの）→ ふつうの枠の外に出ていると…？",
   etymologyConclusion:"extra（範囲の外へ）＋ ordinary（ふつうの）→ ふつうの枠の外に出ている＝並外れた",
   relatedWords:[
     {word:"ordinary",meaning:"ふつうの",breakdown:"ord（順序）＋ ary（形容詞）→ 決まった並びのとおりの"},
     {word:"extra",meaning:"余分の",breakdown:"extra（範囲の外へ）→ 決められた範囲の外にある分"},
     {word:"order",meaning:"順序；命令",breakdown:"ord（順序）→ きちんと並んでいる並び方"},
     {synonym:true,word:"remarkable",meaning:"注目すべき",breakdown:"目立つこと。extraordinary はふつうの枠を越えていることを言う"}]},

  {id:1384,word:"absolute",partOfSpeech:"形容詞",meaning:"絶対的な",
   meanings:["形|絶対的な，完全な"],
   pronunciation:"/ˈæbsəluːt/",part:139,
   example:"The old king had absolute power over the land.",
   exampleJa:"その老いた王は、国土に対して絶対的な力を持っていた。",
   example2:"There is no absolute truth in this difficult matter.",
   exampleJa2:"この難しい件に、絶対的な真実はない。",
   etymologyProcess:"ab（離れて）＋ solu（ほどく）→ 何からもほどかれて縛られていないと…？",
   etymologyConclusion:"ab（離れて）＋ solu（ほどく）→ 何からもほどかれ、縛られていない＝絶対的な",
   relatedWords:[
     {word:"solve",meaning:"解く，解決する",breakdown:"solve（ほどく）→ もつれをほどいて答えを出す"},
     {word:"solution",meaning:"解決；溶液",breakdown:"solu（ほどく）＋ ion（名詞）→ ほどけて解けた状態"},
     {word:"resolve",meaning:"解決する；決意する",breakdown:"re（すっかり）＋ solve（ほどく）→ もつれをすっかりほどく"},
     {word:"dissolve",meaning:"溶ける",breakdown:"dis（バラバラに）＋ solve（ほどく）→ ばらばらにほどけて液に混ざる"}]},

  {id:1385,word:"overwhelming",partOfSpeech:"形容詞",meaning:"圧倒的な",
   meanings:["形|圧倒的な，抗しがたい"],
   pronunciation:"/ˌoʊvərˈwelmɪŋ/",part:139,
   example:"The team won by an overwhelming margin yesterday.",
   exampleJa:"そのチームは昨日、圧倒的な差で勝った。",
   example2:"She felt overwhelming joy at the very good news.",
   exampleJa2:"彼女はそのとてもよい知らせに、圧倒的な喜びを感じた。",
   etymologyProcess:"over（越えて）＋ whelm（ひっくり返す）→ 上から覆ってひっくり返すほどだと…？",
   etymologyConclusion:"over（越えて）＋ whelm（ひっくり返す）→ 上から覆いかぶさってひっくり返すほどの＝圧倒的な",
   relatedWords:[
     {word:"overwhelm",meaning:"圧倒する",breakdown:"over（越えて）＋ whelm（ひっくり返す）→ 上から覆って押し流す"},
     {word:"overcome",meaning:"打ち勝つ",breakdown:"over（越えて）＋ come（来る）→ 上を越えて乗りこえる"},
     {word:"overload",meaning:"積みすぎる",breakdown:"over（越えて）＋ load（積んで運ぶ）→ 限度を越えて積む"},
     {synonym:true,word:"crushing",meaning:"圧倒的な，決定的な",breakdown:"押しつぶすほどの。overwhelming は覆い尽くす強さを言う"}]},

  {id:1386,word:"altogether",partOfSpeech:"副詞",meaning:"完全に；全部で",
   meanings:["副|完全に，まったく","副|全部で，合計で"],
   pronunciation:"/ˌɔːltəˈɡeðər/",part:139,
   example:"The new plan was altogether different from ours.",
   exampleJa:"その新しい計画は、私たちのものとは完全に違っていた。",
   example2:"Altogether, twenty students joined the summer English camp.",
   exampleJa2:"全部で20人の生徒が、夏の英語キャンプに参加した。",
   etymologyProcess:"all（すっかり）＋ gather（一つにまとめる）→ すっかり一つにまとめると…？",
   etymologyConclusion:"all（すっかり）＋ gather（一つにまとめる）→ すっかり一つにまとめて＝完全に",
   relatedWords:[
     {word:"gather",meaning:"集める",breakdown:"gather（一つにまとめる）→ ばらばらのものを一か所へ寄せる"},
     {word:"together",meaning:"一緒に",breakdown:"gather（一つにまとめる）→ 一つにまとまった形で"},
     {word:"already",meaning:"すでに",breakdown:"all（すっかり）＋ ready（整った）→ すっかり用意が整って"},
     {synonym:true,word:"completely",meaning:"完全に",breakdown:"すっかり。altogether は「全部で」の意味でも使える"}]},

  {id:1387,word:"entire",partOfSpeech:"形容詞",meaning:"すべての，全体の",
   meanings:["形|すべての，全体の"],
   pronunciation:"/ɪnˈtaɪər/",part:139,
   example:"He spent the entire day reading one long novel.",
   exampleJa:"彼は一日すべてを、一冊の長い小説を読んで過ごした。",
   example2:"The entire class agreed with her new bold idea.",
   exampleJa2:"クラス全体が、彼女の新しく大胆な考えに賛成した。",
   etymologyProcess:"in（否定）＋ tact（触れる）→ 誰にも手をつけられず欠けがないと…？",
   etymologyConclusion:"in（否定）＋ tact（触れる）→ 誰にも手をつけられず、欠けのないまま＝すべての",
   why:"【なぜ】ラテン語 integer は in（否定）＋ tangere（触れる）で「手をつけられていない」。一部も欠けていない、そのままの状態から「全体の・すべての」になりました。\n【つながり】integer（整数）、intact（損なわれていない）も同じ家族です。",
   relatedWords:[
     {word:"intact",meaning:"損なわれていない",breakdown:"in（否定）＋ tact（触れる）→ 誰にも触られていないままの"},
     {word:"integer",meaning:"整数",breakdown:"in（否定）＋ tact（触れる）→ 欠けのない、そのままの数"},
     {word:"contact",meaning:"接触；連絡する",breakdown:"con（共に）＋ tact（触れる）→ 互いに触れ合う"},
     {synonym:true,word:"whole",meaning:"全体の",breakdown:"欠けのないひとまとまり。entire は一部も欠けていないことを言う"}]},

  {id:1388,word:"tremendous",partOfSpeech:"形容詞",meaning:"すさまじい，ものすごい",
   meanings:["形|すさまじい，ものすごい"],
   pronunciation:"/trəˈmendəs/",part:139,
   example:"The storm caused tremendous damage to the small town.",
   exampleJa:"その嵐は、小さな町にすさまじい被害をもたらした。",
   example2:"He made a tremendous effort to finish in first.",
   exampleJa2:"彼は1位で終えるために、すさまじい努力をした。",
   etymologyProcess:"trem（震える）＋ ous（形容詞）→ 思わず震え上がるほど大きいと…？",
   etymologyConclusion:"trem（震える）＋ ous（形容詞）→ 思わず震え上がってしまうほど大きい＝すさまじい",
   relatedWords:[
     {word:"tremble",meaning:"震える",breakdown:"trem（震える）→ 寒さや恐れで体が小刻みに揺れ続ける"},
     {word:"tremor",meaning:"震え，小さな地震",breakdown:"trem（震える）＋ or（もの）→ 小刻みな揺れそのもの"},
     {synonym:true,word:"huge",meaning:"巨大な",breakdown:"とても大きいこと。tremendous は震え上がるほどの大きさ"},
     {synonym:true,word:"enormous",meaning:"巨大な",breakdown:"並外れて大きいこと。tremendous は勢いの強さも表す"}]},

  {id:1389,word:"sheer",partOfSpeech:"形容詞",meaning:"まったくの，とてつもない",
   meanings:["形|まったくの，純然たる","形|（がけが）切り立った"],
   pronunciation:"/ʃɪr/",part:139,
   example:"They won by sheer luck in the very last minute.",
   exampleJa:"彼らはまさに最後の1分に、まったくの幸運で勝った。",
   example2:"The sheer size of the building surprised everyone there.",
   exampleJa2:"その建物のとてつもない大きさが、そこにいたみんなを驚かせた。",
   etymologyProcess:"sheer（混じりけのない）→ ほかが何も混じらない状態を強めると…？",
   etymologyConclusion:"sheer（混じりけのない）→ ほかが何も混じっていない、純粋な＝まったくの",
   hook:"「まったくの〜」と強めるのに使う。sheer luck（まったくの幸運）。",
   relatedWords:[
     {synonym:true,word:"pure",meaning:"純粋な",breakdown:"混じりけがないこと。sheer は「まったくの」と強める働きが中心"},
     {synonym:true,word:"complete",meaning:"完全な",breakdown:"欠けがないこと。sheer はほかが混じらないことを強調する"},
     {synonym:true,word:"absolute",meaning:"絶対的な",breakdown:"何にも縛られないこと。sheer は「純粋に〜だけ」を強める"},
     {synonym:true,word:"utter",meaning:"まったくの",breakdown:"ほぼ同じ強め方。sheer は「大きさ」を強めるのにもよく使う"}]},

  {id:1390,word:"partial",partOfSpeech:"形容詞",meaning:"部分的な",
   meanings:["形|部分的な，一部の","形|えこひいきの"],
   pronunciation:"/ˈpɑːrʃl/",part:139,
   example:"We only have partial information about the traffic accident.",
   exampleJa:"私たちはその交通事故について、部分的な情報しか持っていない。",
   example2:"The old plan was only a partial success.",
   exampleJa2:"その古い計画は、部分的な成功にすぎなかった。",
   etymologyProcess:"part（分ける）＋ al（形容詞）→ 全体の一部分だけにとどまると…？",
   etymologyConclusion:"part（分ける）＋ al（形容詞）→ 全体の一部分だけにとどまっている＝部分的な",
   relatedWords:[
     {word:"part",meaning:"部分",breakdown:"part（分ける）→ 全体から分けられた一つ"},
     {word:"partner",meaning:"相棒",breakdown:"part（分ける）＋ er（人）→ 分け前を共にする相手"},
     {word:"portion",meaning:"1盛り；部分",breakdown:"porti（分ける）＋ ion（名詞）→ 全体から切り分けた取り分"},
     {word:"particle",meaning:"粒子",breakdown:"part（分ける）＋ icle（小さいもの）→ 分けに分けた小さなかけら"}]},

  {id:1391,word:"barely",partOfSpeech:"副詞",meaning:"かろうじて；ほとんど～ない",
   meanings:["副|かろうじて，やっと","副|ほとんど～ない"],
   pronunciation:"/ˈberli/",part:140,
   example:"He could barely see the road sign in the fog.",
   exampleJa:"彼は霧の中で、道路標識をかろうじて見ることができた。",
   example2:"She barely had time to eat any breakfast.",
   exampleJa2:"彼女には朝食を食べる時間がほとんどなかった。",
   etymologyProcess:"bare（むきだしの）＋ ly（副詞）→ 余分をはぎ取ったぎりぎりの分だと…？",
   etymologyConclusion:"bare（むきだしの）＋ ly（副詞）→ 余分をはぎ取った、ぎりぎりの分だけ＝かろうじて",
   relatedWords:[
     {word:"bare",meaning:"むきだしの",breakdown:"bare（むきだしの）→ 覆いが何もなく、そのまま見えている"},
     {word:"barefoot",meaning:"はだしの",breakdown:"bare（むきだしの）＋ foot（足）→ 靴をはかず足がむきだしの"},
     {synonym:true,word:"hardly",meaning:"ほとんど～ない",breakdown:"ほとんど～ない。barely は「やっと届いた」の意味でも使える"},
     {synonym:true,word:"scarcely",meaning:"ほとんど～ない",breakdown:"数が足りないこと。barely よりやや硬い言い方"}]},

  {id:1392,word:"approximately",partOfSpeech:"副詞",meaning:"およそ，約",
   meanings:["副|およそ，約"],
   pronunciation:"/əˈprɑːksɪmətli/",part:140,
   example:"The trip takes approximately three hours by fast train.",
   exampleJa:"その旅は、速い電車でおよそ3時間かかる。",
   example2:"Approximately half of the students walk to school.",
   exampleJa2:"生徒のおよそ半分が歩いて学校へ来る。",
   etymologyProcess:"ap（〜へ）＋ proxim（最も近い）→ 正しい数に最も近づけて言うと…？",
   etymologyConclusion:"ap（〜へ）＋ proxim（最も近い）→ 正しい数のすぐ近くまで寄せた言い方＝およそ",
   relatedWords:[
     {word:"approximate",meaning:"おおよその",breakdown:"ap（〜へ）＋ proxim（最も近い）→ 正しい値にできるだけ近づけた"},
     {word:"proximity",meaning:"近いこと，近さ",breakdown:"proxim（最も近い）＋ ity（名詞）→ すぐ近くにある状態"},
     {synonym:true,word:"about",meaning:"約",breakdown:"だいたいの数。approximately は書き言葉で使う硬い言い方"},
     {synonym:true,word:"roughly",meaning:"おおざっぱに",breakdown:"ざっくりした数。approximately はもう少し正確さをにおわせる"}]},

  {id:1393,word:"frequently",partOfSpeech:"副詞",meaning:"ひんぱんに，たびたび",
   meanings:["副|ひんぱんに，たびたび"],
   pronunciation:"/ˈfriːkwəntli/",part:140,
   example:"He frequently visits his grandparents in the countryside.",
   exampleJa:"彼はひんぱんに、田舎の祖父母を訪ねる。",
   example2:"This old machine frequently breaks down in winter.",
   exampleJa2:"この古い機械は、冬にたびたび故障する。",
   etymologyProcess:"frequ（ぎっしり詰まった）＋ ly（副詞）→ 短い間にぎっしり詰まって起こると…？",
   etymologyConclusion:"frequ（ぎっしり詰まった）＋ ly（副詞）→ 短い間にぎっしり詰まって起こる＝ひんぱんに",
   relatedWords:[
     {word:"frequent",meaning:"たびたびの",breakdown:"frequ（ぎっしり詰まった）＋ ent（形容詞）→ 間が空かず何度も起こる"},
     {word:"frequency",meaning:"頻度；周波数",breakdown:"frequ（ぎっしり詰まった）＋ ency（名詞）→ どれだけ詰まって起こるかの度合い"},
     {synonym:true,word:"often",meaning:"よく，しばしば",breakdown:"回数が多いこと。frequently はより改まった言い方"},
     {synonym:true,word:"regularly",meaning:"定期的に",breakdown:"決まった間隔で。frequently は間隔より回数の多さを言う"}]},

  {id:1394,word:"apparently",partOfSpeech:"副詞",meaning:"どうやら～らしい",
   meanings:["副|どうやら～らしい，見たところ"],
   pronunciation:"/əˈpærəntli/",part:140,
   example:"Apparently, the train was late because of heavy snow.",
   exampleJa:"どうやら、その電車は大雪のせいで遅れたらしい。",
   example2:"She apparently knew nothing about the sudden change.",
   exampleJa2:"彼女はどうやら、その急な変更について何も知らなかったらしい。",
   etymologyProcess:"ap（〜へ）＋ pear（見えてくる）→ 目の前に見えてくるかぎりでは…？",
   etymologyConclusion:"ap（〜へ）＋ pear（見えてくる）→ 目の前に見えてくるかぎりでは＝どうやら～らしい",
   relatedWords:[
     {word:"appear",meaning:"現れる；～に見える",breakdown:"ap（〜へ）＋ pear（見えてくる）→ 目の前に姿が見えてくる"},
     {word:"apparent",meaning:"明らかな；見かけの",breakdown:"ap（〜へ）＋ pear（見えてくる）→ ひと目で見てとれる"},
     {word:"disappear",meaning:"消える",breakdown:"dis（否定）＋ ap（〜へ）＋ pear（見えてくる）→ 見えていたものが見えなくなる"},
     {synonym:true,word:"seemingly",meaning:"見たところ",breakdown:"そう見えること。apparently は人から聞いた話にもよく使う"}]},

  {id:1395,word:"merely",partOfSpeech:"副詞",meaning:"単に～にすぎない",
   meanings:["副|単に，～にすぎない"],
   pronunciation:"/ˈmɪrli/",part:140,
   example:"He is merely a child, so please be kind.",
   exampleJa:"彼は単なる子どもにすぎないのだから、やさしくしてあげて。",
   example2:"That was merely a joke between two close friends.",
   exampleJa2:"あれは、仲のよい二人の間の冗談にすぎなかった。",
   etymologyProcess:"mere（それだけの）＋ ly（副詞）→ ほかが何もなくそれだけだと…？",
   etymologyConclusion:"mere（それだけの）＋ ly（副詞）→ ほかが何もなく、それだけ＝単に～にすぎない",
   relatedWords:[
     {word:"mere",meaning:"ほんの，単なる",breakdown:"mere（それだけの）→ ほかが混じらない、ただそれだけの"},
     {synonym:true,word:"only",meaning:"～だけ",breakdown:"それ以外にないこと。merely はやや硬い書き言葉"},
     {synonym:true,word:"simply",meaning:"ただ単に",breakdown:"複雑さがないこと。merely は「それだけ」と小ささを強める"},
     {synonym:true,word:"just",meaning:"ほんの",breakdown:"話し言葉でよく使う。merely は改まった場面で使う"}]},

  {id:1396,word:"nevertheless",partOfSpeech:"副詞",meaning:"それにもかかわらず",
   meanings:["副|それにもかかわらず，それでも"],
   pronunciation:"/ˌnevərðəˈles/",part:140,
   example:"The task was very hard; nevertheless, she finished it.",
   exampleJa:"その仕事はとても大変だったが、それでも彼女はやり終えた。",
   example2:"It rained hard. Nevertheless, the game continued as planned.",
   exampleJa2:"雨が激しく降った。それにもかかわらず、試合は予定どおり続いた。",
   etymologyProcess:"never（決して～ない）→ それでも決して打ち消されないとなると…？",
   etymologyConclusion:"never（決して～ない）→ 前のことがあっても決して打ち消されない＝それにもかかわらず",
   hook:"もとは never the less（それだけ少なくはならない）。「それでも」と続ける硬い言い方。",
   relatedWords:[
     {word:"never",meaning:"決して～ない",breakdown:"ne（否定）＋ ever（いつも）→ いつであっても～ない"},
     {synonym:true,word:"nonetheless",meaning:"それにもかかわらず",breakdown:"ほぼ同じ意味。nevertheless のほうがよく使われる"},
     {synonym:true,word:"however",meaning:"しかしながら",breakdown:"前と逆の内容を続ける。nevertheless は「それでもなお」と強い"},
     {synonym:true,word:"still",meaning:"それでも",breakdown:"話し言葉で使える軽い言い方。nevertheless は改まった場面向き"}]},

  {id:1397,word:"somehow",partOfSpeech:"副詞",meaning:"どうにかして；なぜか",
   meanings:["副|どうにかして，なんとか","副|なぜか，どういうわけか"],
   pronunciation:"/ˈsʌmhaʊ/",part:140,
   example:"We somehow managed to finish the work on time.",
   exampleJa:"私たちはどうにかして、その仕事を時間どおりに終えた。",
   example2:"Somehow she knew the answer without being told.",
   exampleJa2:"なぜか彼女は、教えられなくても答えを知っていた。",
   etymologyProcess:"som（何らかの）＋ how（どうやって）→ やり方がはっきりしないままだと…？",
   etymologyConclusion:"som（何らかの）＋ how（どうやって）→ やり方ははっきりしないが何らかの手で＝どうにかして",
   relatedWords:[
     {word:"somewhat",meaning:"いくぶん",breakdown:"som（何らかの）＋ what（何）→ 量ははっきりしないがいくらか"},
     {word:"somewhere",meaning:"どこかで",breakdown:"som（何らかの）＋ where（どこ）→ 場所ははっきりしないがどこかで"},
     {word:"someday",meaning:"いつか",breakdown:"som（何らかの）＋ day（日）→ 日ははっきりしないがいつかの日に"},
     {synonym:true,word:"anyhow",meaning:"とにかく",breakdown:"手段を問わないこと。somehow は「なぜか」の意味でも使える"}]},

  {id:1398,word:"thus",partOfSpeech:"副詞",meaning:"したがって；このように",
   meanings:["副|したがって，だから","副|このように"],
   pronunciation:"/ðʌs/",part:140,
   example:"The road was closed; thus we took another route.",
   exampleJa:"道路が閉鎖されていた。したがって私たちは別の道を通った。",
   example2:"He studied very hard and thus passed the exam.",
   exampleJa2:"彼はとても熱心に勉強し、したがって試験に合格した。",
   etymologyProcess:"thus（このように）→ 前に述べたやり方のとおりだとなると…？",
   etymologyConclusion:"thus（このように）→ 前に述べたやり方のとおりに、だから＝したがって",
   hook:"硬い書き言葉。so の改まった形と考えるとよい。",
   relatedWords:[
     {synonym:true,word:"therefore",meaning:"したがって",breakdown:"前の内容を理由にする。thus と同じくらい硬い言い方"},
     {synonym:true,word:"hence",meaning:"それゆえに",breakdown:"さらに硬い言い方。thus のほうが使う場面は広い"},
     {synonym:true,word:"so",meaning:"だから",breakdown:"話し言葉でよく使う。thus は書き言葉向き"},
     {synonym:true,word:"consequently",meaning:"その結果",breakdown:"結果であることを強める。thus はやり方や理由も表せる"}]},

  {id:1399,word:"afterward",partOfSpeech:"副詞",meaning:"あとで，その後",
   meanings:["副|あとで，その後"],
   pronunciation:"/ˈæftərwərd/",part:140,
   example:"We had dinner and afterward watched an old movie.",
   exampleJa:"私たちは夕食をとり、そのあとで古い映画を見た。",
   example2:"Shortly afterward, the rain stopped and the sun appeared.",
   exampleJa2:"その少しあとで雨がやみ、太陽が顔を出した。",
   etymologyProcess:"after（あとの）→ その時より後ろの方へ向かって進むと…？",
   etymologyConclusion:"after（あとの）→ その時より後ろの方へ向かって＝あとで",
   hook:"イギリス英語では afterwards と s がつくことが多い。",
   relatedWords:[
     {word:"afternoon",meaning:"午後",breakdown:"after（あとの）＋ noon（正午）→ 正午よりあとの時間"},
     {synonym:true,word:"later",meaning:"あとで",breakdown:"いちばんふつうの言い方。afterward は書き言葉でよく使う"},
     {synonym:true,word:"subsequently",meaning:"その後",breakdown:"かたい書き言葉。afterward より改まった場面で使う"},
     {synonym:true,word:"then",meaning:"それから",breakdown:"順番を示す軽い語。afterward は「そのあとで」と時間を強める"}]},

  {id:1400,word:"on behalf of",partOfSpeech:"熟語",meaning:"～を代表して，～のために",
   meanings:["熟|～を代表して，～のために"],
   pronunciation:"/ɑːn bɪˈhæf əv/",part:140,
   example:"She spoke on behalf of all the club members.",
   exampleJa:"彼女はクラブの全員を代表して話した。",
   example2:"I accepted the prize on behalf of my team.",
   exampleJa2:"私はチームを代表して、その賞を受け取った。",
   etymologyProcess:"half（側）→ その人の側に立って代わりを務めると…？",
   etymologyConclusion:"half（側）→ その人の側に立って、代わりを務める＝～を代表して",
   relatedWords:[
     {word:"half",meaning:"半分",breakdown:"half（側）→ 二つに分けた片方の側"},
     {word:"behalf",meaning:"（人の）側，利益",breakdown:"half（側）→ 味方として立つ側"},
     {synonym:true,word:"representing",meaning:"～を代表して",breakdown:"代表すること。on behalf of は熟語として文中で使う"},
     {synonym:true,word:"represent",meaning:"代表する",breakdown:"人の代わりに立つこと。on behalf of は副詞句として文に添える"}]},

  {id:1401,word:"assert",partOfSpeech:"他動詞",meaning:"断言する，強く主張する",
   meanings:["他|断言する，強く主張する"],
   pronunciation:"/əˈsɜːrt/",part:141,
   example:"You must assert your own opinion much more clearly.",
   exampleJa:"あなたは自分の意見を、もっとはっきり主張しなければならない。",
   example2:"He asserted that he had seen nothing at all.",
   exampleJa2:"彼は、何もまったく見ていないと断言した。",
   etymologyProcess:"as（〜へ）＋ ser（つなぐ）→ 自分の考えを相手にぴたりとつなげると…？",
   etymologyConclusion:"as（〜へ）＋ ser（つなぐ）→ 自分の考えをぴたりとつなげて言い切る＝断言する",
   relatedWords:[
     {word:"insert",meaning:"差しこむ",breakdown:"in（中へ）＋ ser（つなぐ）→ 間に差しこんでつなげる"},
     {word:"series",meaning:"連続，ひと続き",breakdown:"ser（つなぐ）→ 次々につながったひと続き"},
     {synonym:true,word:"claim",meaning:"主張する",breakdown:"自分の権利として言うこと。assert は強く言い切ることを言う"},
     {synonym:true,word:"declare",meaning:"宣言する",breakdown:"公に告げること。assert は自分の考えを押し出すことが中心"}]},

  {id:1402,word:"defy",partOfSpeech:"他動詞",meaning:"（命令などに）そむく，反抗する",
   meanings:["他|（命令などに）そむく，反抗する"],
   pronunciation:"/dɪˈfaɪ/",part:141,
   example:"He decided to defy his father's very strict rules.",
   exampleJa:"彼は、父親のとても厳しい規則にそむくことを決めた。",
   example2:"The little village defied the powerful king's order.",
   exampleJa2:"その小さな村は、力のある王の命令にそむいた。",
   etymologyProcess:"dis（否定）＋ fi（信じる）→ 信頼の約束を破って立ち向かうと…？",
   etymologyConclusion:"dis（否定）＋ fi（信じる）→ 信頼の約束を破り捨てて正面から立ち向かう＝そむく",
   relatedWords:[
     {word:"faith",meaning:"信頼，信仰",breakdown:"fi（信じる）＋ th（名詞）→ 相手を信じる心そのもの"},
     {word:"confide",meaning:"打ち明ける",breakdown:"con（共に）＋ fi（信じる）→ 相手を信じて秘密を預ける"},
     {word:"defiant",meaning:"反抗的な",breakdown:"dis（否定）＋ fi（信じる）＋ ant（〜な）→ 従わず立ち向かう態度の"},
     {synonym:true,word:"resist",meaning:"抵抗する",breakdown:"押し返すこと。defy は命令や権威に正面から逆らうことを言う"}]},

  {id:1403,word:"condemn",partOfSpeech:"他動詞",meaning:"（強く）非難する；刑を言い渡す",
   meanings:["他|（強く）非難する","他|（刑を）言い渡す"],
   pronunciation:"/kənˈdem/",part:141,
   example:"Many people condemn the company for hiding the truth.",
   exampleJa:"多くの人が、真実を隠したことでその会社を強く非難している。",
   example2:"The court condemned him to five years in prison.",
   exampleJa2:"裁判所は彼に、懲役5年の刑を言い渡した。",
   etymologyProcess:"con（強く）＋ demn（損失）→ 強く責めて損害の償いを言い渡すと…？",
   etymologyConclusion:"con（強く）＋ demn（損失）→ 強く責めて、損害の償いを言い渡す＝非難する",
   relatedWords:[
     {word:"damage",meaning:"損害",breakdown:"dam（損失）＋ age（名詞）→ 損なわれて減ってしまったもの"},
     {word:"damn",meaning:"ののしる；罰する",breakdown:"demn（損失）→ 損害の罰を言い渡してしまう"},
     {synonym:true,word:"blame",meaning:"責める",breakdown:"悪いと言うこと。condemn は公の場で強く責めることを言う"},
     {synonym:true,word:"criticize",meaning:"批判する",breakdown:"よしあしを論じること。condemn は完全に悪いと決めつける"}]},

  {id:1404,word:"cite",partOfSpeech:"他動詞",meaning:"（出典を示して）引用する",
   meanings:["他|引用する","他|（例や理由を）挙げる"],
   pronunciation:"/saɪt/",part:141,
   example:"You should cite the book you used in class.",
   exampleJa:"授業で使った本は、きちんと引用元として挙げるべきだ。",
   example2:"She cited three clear reasons for her final decision.",
   exampleJa2:"彼女は最終的な決定について、3つの明確な理由を挙げた。",
   etymologyProcess:"cit（呼び出す）→ 必要な言葉をその場に呼び出してくると…？",
   etymologyConclusion:"cit（呼び出す）→ 必要な言葉を、その場に呼び出してくる＝引用する",
   relatedWords:[
     {word:"excite",meaning:"興奮させる",breakdown:"ex（外へ）＋ cit（呼び出す）→ 気持ちを外へ呼び出してわき立たせる"},
     {word:"recite",meaning:"暗唱する",breakdown:"re（再び）＋ cit（呼び出す）→ 覚えた言葉をもう一度呼び出して唱える"},
     {word:"citation",meaning:"引用（文）",breakdown:"cit（呼び出す）＋ ation（名詞）→ 呼び出してきた言葉そのもの"},
     {synonym:true,word:"quote",meaning:"引用する",breakdown:"言葉をそのまま写すこと。cite は出典を示すことに重きを置く"}]},

  {id:1405,word:"illustrate",partOfSpeech:"他動詞",meaning:"（例で）説明する；さし絵を入れる",
   meanings:["他|（例で）説明する，示す","他|さし絵を入れる"],
   pronunciation:"/ˈɪləstreɪt/",part:141,
   example:"Let me illustrate my point with a simple example.",
   exampleJa:"簡単な例で、私の言いたいことを説明させてください。",
   example2:"This graph illustrates how the city population has changed.",
   exampleJa2:"このグラフは、市の人口がどう変化してきたかを示している。",
   etymologyProcess:"in（中へ）＋ lustr（照らす）→ 中まで光を当ててはっきり見せると…？",
   etymologyConclusion:"in（中へ）＋ lustr（照らす）→ 中まで光を当てて、はっきり見せる＝説明する",
   relatedWords:[
     {word:"illustration",meaning:"さし絵；実例",breakdown:"in（中へ）＋ lustr（照らす）＋ ation（名詞）→ 照らして見せたもの"},
     {word:"lustrous",meaning:"つやのある",breakdown:"lustr（照らす）＋ ous（形容詞）→ 光をつやつやと返す"},
     {synonym:true,word:"explain",meaning:"説明する",breakdown:"分かるように述べること。illustrate は例や絵で見せる"},
     {synonym:true,word:"demonstrate",meaning:"実演して示す",breakdown:"やって見せること。illustrate は例で分からせることが中心"}]},

  {id:1406,word:"refute",partOfSpeech:"他動詞",meaning:"論破する，反論する",
   meanings:["他|論破する，反論する"],
   pronunciation:"/rɪˈfjuːt/",part:141,
   example:"The scientist tried to refute the popular old theory.",
   exampleJa:"その科学者は、広く知られた古い説に反論しようとした。",
   example2:"He refuted the report with clear new evidence.",
   exampleJa2:"彼は明確な新しい証拠で、その報告を論破した。",
   etymologyProcess:"re（後ろへ）＋ fut（打つ）→ 相手の主張を打ち返して退けると…？",
   etymologyConclusion:"re（後ろへ）＋ fut（打つ）→ 相手の主張を打ち返して退ける＝論破する",
   relatedWords:[
     {word:"refutation",meaning:"反論，論破",breakdown:"re（後ろへ）＋ fut（打つ）＋ ation（名詞）→ 打ち返して退けること"},
     {synonym:true,word:"disprove",meaning:"誤りを証明する",breakdown:"間違いだと示すこと。refute は言い返して退けることを言う"},
     {synonym:true,word:"rebut",meaning:"反ばくする",breakdown:"言い返すこと。refute のほうが「証明して退ける」に近い"},
     {word:"refutable",meaning:"反論できる",breakdown:"re（後ろへ）＋ fut（打つ）＋ able（できる）→ 打ち返して退けられる"}]},

  {id:1407,word:"sue",partOfSpeech:"他動詞",meaning:"（裁判で）訴える",
   meanings:["他|（裁判で）訴える"],
   pronunciation:"/suː/",part:141,
   example:"They decided to sue the company for the damage.",
   exampleJa:"彼らはその損害について、会社を訴えることに決めた。",
   example2:"She sued the newspaper for printing a false story.",
   exampleJa2:"彼女は、うその記事を載せた新聞社を訴えた。",
   etymologyProcess:"sue（追う）→ 法の場まで相手を追いかけて責任を問うと…？",
   etymologyConclusion:"sue（追う）→ 法の場まで相手を追いかけて責任を問う＝訴える",
   relatedWords:[
     {word:"pursue",meaning:"追い求める",breakdown:"pur（前へ）＋ sue（追う）→ 前へ前へと追いかけ続ける"},
     {word:"suit",meaning:"訴訟；ひとそろい",breakdown:"suit（付き従う）→ 付き従って続くもの、追い求める手続き"},
     {synonym:true,word:"prosecute",meaning:"起訴する",breakdown:"国が罪を問うこと。sue は個人が損害を求めて訴えること"},
     {word:"sequence",meaning:"連続，順序",breakdown:"sequ（ついて行く）→ 後ろに続いてついて行く並び"}]},

  {id:1408,word:"articulate",partOfSpeech:"他動詞",meaning:"はっきり述べる，明確に話す",
   meanings:["他|はっきり述べる，明確に話す","形|考えをはっきり言える"],
   pronunciation:"/ɑːrˈtɪkjuleɪt/",part:141,
   example:"Try to articulate your ideas in simple clear words.",
   exampleJa:"自分の考えを、簡単ではっきりした言葉で述べてみなさい。",
   example2:"He articulated each word slowly so everyone understood.",
   exampleJa2:"彼はみんなが分かるように、一語一語ゆっくりはっきり発音した。",
   etymologyProcess:"articul（小さな関節）→ 言葉を関節ごとに区切って言うと…？",
   etymologyConclusion:"articul（小さな関節）→ 言葉を関節ごとに区切ってはっきり言う＝はっきり述べる",
   relatedWords:[
     {word:"article",meaning:"記事；品物",breakdown:"articul（小さな関節）→ 区切られた一つひとつのまとまり"},
     {word:"articulation",meaning:"はっきりした発音；関節",breakdown:"articul（小さな関節）＋ ation（名詞）→ 区切って組み立てたもの"},
     {synonym:true,word:"express",meaning:"表現する",breakdown:"外へ出すこと。articulate は区切ってはっきり言うことを言う"},
     {synonym:true,word:"state",meaning:"述べる",breakdown:"はっきり言うこと。articulate は言い方の明確さを強める"}]},

  {id:1409,word:"version",partOfSpeech:"名詞",meaning:"版；（個人の）解釈",
   meanings:["名|版，バージョン","名|（個人の）解釈，言い分"],
   pronunciation:"/ˈvɜːrʒn/",part:141,
   example:"This is the newest version of the popular game.",
   exampleJa:"これは、その人気ゲームの最新版だ。",
   example2:"Her version of the story was quite different.",
   exampleJa2:"その出来事についての彼女の言い分は、まったく違っていた。",
   etymologyProcess:"vers（回る）＋ ion（名詞）→ もとの形から向きを変えて作り直すと…？",
   etymologyConclusion:"vers（回る）＋ ion（名詞）→ もとの形から向きを変えて作り直したもの＝版",
   relatedWords:[
     {word:"convert",meaning:"変える，転換する",breakdown:"con（すっかり）＋ vers（回る）→ 向きをすっかり回して別のものにする"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ 向きを後ろへ回してあべこべにする"},
     {word:"universe",meaning:"宇宙",breakdown:"uni（1つ）＋ vers（回る）→ ひとつにまとまって回るもの全体"},
     {synonym:true,word:"edition",meaning:"版",breakdown:"本などの刷り。version は中身が少し違う別の形を指す"}]},

  {id:1410,word:"advocate",partOfSpeech:"他動詞",meaning:"主張する，提唱する；支持者",
   meanings:["他|主張する，提唱する","名|支持者，擁護者"],
   pronunciation:"/ˈædvəkeɪt/",part:141,
   example:"Many doctors advocate walking for at least thirty minutes.",
   exampleJa:"多くの医師が、少なくとも30分歩くことを提唱している。",
   example2:"She was a strong advocate of free school lunches.",
   exampleJa2:"彼女は、無料の学校給食の強力な支持者だった。",
   etymologyProcess:"ad（〜へ）＋ voc（呼ぶ）→ 味方になるようそばへ呼び寄せると…？",
   etymologyConclusion:"ad（〜へ）＋ voc（呼ぶ）→ 味方になるようそばへ呼び寄せて訴える＝主張する",
   relatedWords:[
     {word:"vocal",meaning:"声の；遠慮なく言う",breakdown:"voc（呼ぶ）＋ al（形容詞）→ 声を出して呼びかける"},
     {word:"vocation",meaning:"天職",breakdown:"voc（呼ぶ）＋ ation（名詞）→ 天から呼ばれて就く仕事"},
     {word:"provoke",meaning:"怒らせる，引き起こす",breakdown:"pro（前へ）＋ voc（呼ぶ）→ 相手の反応を前へ呼び出す"},
     {synonym:true,word:"support",meaning:"支持する",breakdown:"下から支えること。advocate は人前で強く訴えること"}]},

  {id:1411,word:"breakthrough",partOfSpeech:"名詞",meaning:"大きな進展，突破口",
   meanings:["名|大きな進展，突破口"],
   pronunciation:"/ˈbreɪkθruː/",part:142,
   example:"This new drug is a major medical breakthrough.",
   exampleJa:"この新しい薬は、医学上の大きな進展だ。",
   example2:"The team finally made a breakthrough in their research.",
   exampleJa2:"そのチームはついに、研究で大きな進展をもたらした。",
   etymologyProcess:"break（破る）＋ through（通して）→ 立ちふさがる壁を破って通り抜けると…？",
   etymologyConclusion:"break（破る）＋ through（通して）→ 立ちふさがる壁を破って通り抜けること＝大きな進展",
   relatedWords:[
     {word:"break",meaning:"壊す，破る",breakdown:"break（破る）→ 力をかけて割ったり壊したりする"},
     {word:"outbreak",meaning:"（病気などの）発生",breakdown:"break（破る）＋ out（外へ）→ 外へ破れ出るように一気に広がること"},
     {word:"breakdown",meaning:"故障；内訳",breakdown:"break（破る）＋ down（下へ）→ 壊れて動かなくなること"},
     {synonym:true,word:"discovery",meaning:"発見",breakdown:"見つけ出すこと。breakthrough は行き詰まりを破った進展を言う"}]},

  {id:1412,word:"evolution",partOfSpeech:"名詞",meaning:"進化，発展",
   meanings:["名|進化，発展"],
   pronunciation:"/ˌevəˈluːʃn/",part:142,
   example:"Darwin explained the evolution of living things carefully.",
   exampleJa:"ダーウィンは、生き物の進化をていねいに説明した。",
   example2:"The evolution of the smartphone changed our daily life.",
   exampleJa2:"スマートフォンの発展は、私たちの日常生活を変えた。",
   etymologyProcess:"e（外へ）＋ volut（巻く）→ 巻物を外へ巻き広げるように変わると…？",
   etymologyConclusion:"e（外へ）＋ volut（巻く）→ 巻物を外へ巻き広げるように少しずつ変わること＝進化",
   relatedWords:[
     {word:"evolve",meaning:"進化する",breakdown:"e（外へ）＋ volut（巻く）→ 巻き広げるように少しずつ変わっていく"},
     {word:"revolution",meaning:"革命；回転",breakdown:"re（再び）＋ volut（巻く）→ ぐるりと巻き返して世の中がひっくり返ること"},
     {word:"involve",meaning:"巻きこむ，含む",breakdown:"in（中へ）＋ volve（回す）→ 中へぐるぐると巻きこむ"},
     {synonym:true,word:"development",meaning:"発達",breakdown:"育って広がること。evolution は長い時間をかけた変化を言う"}]},

  {id:1413,word:"innovation",partOfSpeech:"名詞",meaning:"革新，新しい工夫",
   meanings:["名|革新，新しい工夫"],
   pronunciation:"/ˌɪnəˈveɪʃn/",part:142,
   example:"This company is famous for technological innovation worldwide.",
   exampleJa:"この会社は、技術の革新で世界的に有名だ。",
   example2:"Innovation often begins with a very simple question.",
   exampleJa2:"革新は多くの場合、とても単純な問いから始まる。",
   etymologyProcess:"in（中へ）＋ nov（新しい）→ 中に新しいものを入れて作り変えると…？",
   etymologyConclusion:"in（中へ）＋ nov（新しい）→ 中に新しいものを入れて作り変えること＝革新",
   relatedWords:[
     {word:"innovative",meaning:"革新的な",breakdown:"in（中へ）＋ nov（新しい）→ 新しさを取り入れている"},
     {word:"novel",meaning:"小説；目新しい",breakdown:"nov（新しい）→ これまでになく新しい話"},
     {word:"novice",meaning:"初心者",breakdown:"nov（新しい）→ 入ったばかりで新しい人"},
     {synonym:true,word:"invention",meaning:"発明",breakdown:"新しく作り出すこと。innovation は既存のものを大きく変えること"}]},

  {id:1414,word:"probe",partOfSpeech:"他動詞",meaning:"（深く）調べる；探査機",
   meanings:["他|（深く）調べる，探る","名|探査機；細い調査器具"],
   pronunciation:"/proʊb/",part:142,
   example:"Reporters began to probe the mayor's past business deals.",
   exampleJa:"記者たちは、市長の過去の取引を深く調べ始めた。",
   example2:"The space probe sent back clear pictures of Mars.",
   exampleJa2:"その探査機は、火星の鮮明な写真を送り返してきた。",
   etymologyProcess:"prob（試す）→ 中身を試すように深く探っていくと…？",
   etymologyConclusion:"prob（試す）→ 中身を試すように深く探っていく＝調べる",
   relatedWords:[
     {word:"prove",meaning:"証明する",breakdown:"prove（試す）→ 試して本当だと示す"},
     {word:"probable",meaning:"ありそうな",breakdown:"prob（試す）＋ able（できる）→ 試せば本当だと出そうな"},
     {word:"approve",meaning:"賛成する，承認する",breakdown:"ap（〜へ）＋ prove（試す）→ 試したうえでよしと認める"},
     {synonym:true,word:"investigate",meaning:"調査する",breakdown:"きちんと調べること。probe は奥まで探り出すことを言う"}]},

  {id:1415,word:"fluid",partOfSpeech:"名詞",meaning:"（気体も含む）流体，液体",
   meanings:["名|流体，液体","形|流動的な，変わりやすい"],
   pronunciation:"/ˈfluːɪd/",part:142,
   example:"Water is the most common fluid on our planet.",
   exampleJa:"水は、この惑星で最もありふれた流体だ。",
   example2:"The plans are still fluid and may change soon.",
   exampleJa2:"その計画はまだ流動的で、すぐに変わるかもしれない。",
   etymologyProcess:"flu（流れる）＋ id（〜な状態の）→ 形を変えて流れていくものなら…？",
   etymologyConclusion:"flu（流れる）＋ id（〜な状態の）→ 形を変えて流れていくもの＝流体",
   relatedWords:[
     {word:"fluent",meaning:"流ちょうな",breakdown:"flu（流れる）＋ ent（〜している）→ 言葉がよどみなく流れ出る"},
     {word:"influence",meaning:"影響",breakdown:"in（中へ）＋ flu（流れる）→ 相手の中へ流れこんで変える力"},
     {word:"fluctuate",meaning:"変動する",breakdown:"flu（流れる）＋ ate（動詞）→ 波のように流れて上下する"},
     {synonym:true,word:"liquid",meaning:"液体",breakdown:"水のような液。fluid は気体も含めた「流れるもの」を指す"}]},

  {id:1416,word:"particle",partOfSpeech:"名詞",meaning:"粒子，ごく小さな粒",
   meanings:["名|粒子，ごく小さな粒"],
   pronunciation:"/ˈpɑːrtɪkl/",part:142,
   example:"Dust particles float in the bright morning sunlight.",
   exampleJa:"ほこりの粒子が、明るい朝の日差しの中を漂っている。",
   example2:"Scientists study the tiny particles inside every atom.",
   exampleJa2:"科学者たちは、あらゆる原子の中にある小さな粒子を研究している。",
   etymologyProcess:"part（分ける）＋ icle（小さいもの）→ 分けに分けた末のかけらなら…？",
   etymologyConclusion:"part（分ける）＋ icle（小さいもの）→ 分けに分けた末の小さなかけら＝粒子",
   relatedWords:[
     {word:"part",meaning:"部分",breakdown:"part（分ける）→ 全体から分けられた一つ"},
     {word:"partial",meaning:"部分的な",breakdown:"part（分ける）＋ al（形容詞）→ 一部分だけにとどまっている"},
     {word:"particular",meaning:"特定の；細かい",breakdown:"part（分ける）＋ cul（小さい）→ 小さく分けた一つひとつの"},
     {synonym:true,word:"grain",meaning:"粒",breakdown:"砂や穀物の粒。particle はもっと小さく目に見えない粒も指す"}]},

  {id:1417,word:"gravity",partOfSpeech:"名詞",meaning:"重力；重大さ",
   meanings:["名|重力，引力","名|重大さ，深刻さ"],
   pronunciation:"/ˈɡrævəti/",part:142,
   example:"Gravity pulls every object toward the center of Earth.",
   exampleJa:"重力は、あらゆる物体を地球の中心へ引き寄せる。",
   example2:"Astronauts float because gravity is very weak in space.",
   exampleJa2:"宇宙では重力がとても弱いので、宇宙飛行士は浮かぶ。",
   etymologyProcess:"grav（重い）＋ ity（名詞）→ ものを重く引きつける力なら…？",
   etymologyConclusion:"grav（重い）＋ ity（名詞）→ ものを重く引きつける力＝重力",
   relatedWords:[
     {word:"grave",meaning:"重大な；墓",breakdown:"grav（重い）→ 重く受け止めるべき、深刻な"},
     {word:"grieve",meaning:"深く悲しむ",breakdown:"grav（重い）→ 心に重くのしかかって沈む"},
     {word:"aggravate",meaning:"悪化させる",breakdown:"ag（〜へ）＋ grav（重い）→ さらに重くして悪くする"},
     {synonym:true,word:"weight",meaning:"重さ",breakdown:"重さそのもの。gravity は重さを生み出す引きつける力"}]},

  {id:1418,word:"hypothesis",partOfSpeech:"名詞",meaning:"仮説",
   meanings:["名|仮説"],
   pronunciation:"/haɪˈpɑːθəsɪs/",part:142,
   example:"The scientist tested her new hypothesis many times.",
   exampleJa:"その科学者は、自分の新しい仮説を何度も検証した。",
   example2:"This hypothesis explains why the birds leave in autumn.",
   exampleJa2:"この仮説は、なぜ鳥たちが秋に去るのかを説明している。",
   etymologyProcess:"hypo（下に）＋ thes（置く）→ 話の土台として下に置く考えなら…？",
   etymologyConclusion:"hypo（下に）＋ thes（置く）→ 話の土台として下に置いておく考え＝仮説",
   relatedWords:[
     {word:"thesis",meaning:"論文；主張",breakdown:"thes（置く）→ 自分の考えを置いて示したもの"},
     {word:"synthesis",meaning:"合成，統合",breakdown:"syn（共に）＋ thes（置く）→ いくつかを合わせて一つに置くこと"},
     {word:"hypothetical",meaning:"仮定の",breakdown:"hypo（下に）＋ thes（置く）＋ ical（〜の）→ 仮に置いてみた話の"},
     {synonym:true,word:"theory",meaning:"理論",breakdown:"筋道立てた説明。hypothesis はまだ確かめていない仮の説"}]},

  {id:1419,word:"specimen",partOfSpeech:"名詞",meaning:"標本，見本",
   meanings:["名|標本，見本"],
   pronunciation:"/ˈspesɪmən/",part:142,
   example:"The museum displays many rare insect specimens from Asia.",
   exampleJa:"その博物館は、アジア産のめずらしい昆虫の標本を多数展示している。",
   example2:"She collected a water specimen from the deep lake.",
   exampleJa2:"彼女は、その深い湖から水の見本を採取した。",
   etymologyProcess:"spec（見る）→ よく見てもらうために取り分けた一つなら…？",
   etymologyConclusion:"spec（見る）→ よく見てもらうために取り分けた一つ＝標本",
   relatedWords:[
     {word:"inspect",meaning:"検査する",breakdown:"in（中へ）＋ spect（見る）→ 中までじっくり見る"},
     {word:"spectacle",meaning:"壮観；見もの",breakdown:"spect（見る）→ 思わず見入ってしまう光景"},
     {word:"aspect",meaning:"側面",breakdown:"ad（〜へ）＋ spect（見る）→ ある方向から見たときの姿"},
     {synonym:true,word:"sample",meaning:"見本",breakdown:"全体から取り出した一部。specimen は研究用の標本によく使う"}]},

  {id:1420,word:"microbe",partOfSpeech:"名詞",meaning:"微生物",
   meanings:["名|微生物"],
   pronunciation:"/ˈmaɪkroʊb/",part:142,
   example:"Tiny microbes live everywhere in the soil and water.",
   exampleJa:"小さな微生物は、土の中にも水の中にもどこにでもいる。",
   example2:"Some microbes help our bodies digest food properly.",
   exampleJa2:"一部の微生物は、私たちの体が食べ物をきちんと消化するのを助ける。",
   etymologyProcess:"micro（小さい）＋ bio（生命）→ 目に見えないほど小さな生き物なら…？",
   etymologyConclusion:"micro（小さい）＋ bio（生命）→ 目に見えないほど小さな生き物＝微生物",
   relatedWords:[
     {word:"microscope",meaning:"顕微鏡",breakdown:"micro（小さい）＋ scope（見る道具）→ 小さなものを見るための道具"},
     {word:"biology",meaning:"生物学",breakdown:"bio（生命）＋ log（学問）→ 生命について調べる学問"},
     {word:"microwave",meaning:"電子レンジ；マイクロ波",breakdown:"micro（小さい）＋ wave（波）→ 波長のごく短い電波"},
     {synonym:true,word:"germ",meaning:"細菌，病原菌",breakdown:"病気を起こす菌。microbe は小さな生き物全体を指す"}]},

  {id:1421,word:"poison",partOfSpeech:"名詞",meaning:"毒",
   meanings:["名|毒","他|毒を入れる，毒する"],
   pronunciation:"/ˈpɔɪzn/",part:143,
   example:"The old book says this plant contains strong poison.",
   exampleJa:"その古い本には、この植物には強い毒があると書かれている。",
   example2:"Someone put poison in the king's evening drink.",
   exampleJa2:"誰かが、王の夜の飲み物に毒を入れた。",
   etymologyProcess:"pot（飲む）→ 飲むと命を奪ってしまう飲み物なら…？",
   etymologyConclusion:"pot（飲む）→ 飲むと命を奪ってしまう恐ろしい飲み物＝毒",
   why:"【なぜ】ラテン語 potio は「飲むこと・飲み薬」。中世フランス語で「毒の飲み物」を指すようになり、英語では「毒」そのものを表す語になりました。\n【つながり】potion（魔法の飲み薬）は同じ語から来た、形を変えていない兄弟です。",
   relatedWords:[
     {word:"potion",meaning:"（魔法の）飲み薬",breakdown:"pot（飲む）＋ ion（名詞）→ 飲むために作られた液"},
     {word:"poisonous",meaning:"有毒な",breakdown:"pot（飲む）＋ ous（形容詞）→ 飲めば害になる毒をふくむ"},
     {synonym:true,word:"venom",meaning:"（ヘビなどの）毒",breakdown:"かみついて注ぐ毒。poison は口から入る毒も広く指す"},
     {synonym:true,word:"toxin",meaning:"毒素",breakdown:"生き物が作る毒。poison はふつうの言葉として広く使う"}]},

  {id:1422,word:"acid",partOfSpeech:"名詞",meaning:"酸；酸っぱい",
   meanings:["名|酸","形|酸っぱい，辛らつな"],
   pronunciation:"/ˈæsɪd/",part:143,
   example:"Lemon juice contains a mild acid that cleans well.",
   exampleJa:"レモンの果汁には、よごれをよく落とす弱い酸が含まれている。",
   example2:"Strong acid can burn your skin very quickly.",
   exampleJa2:"強い酸は、皮膚をあっという間に焼いてしまうことがある。",
   etymologyProcess:"acr（鋭い）→ 舌を刺すような鋭い味をもつものなら…？",
   etymologyConclusion:"acr（鋭い）→ 舌を刺すように鋭い味をもつもの＝酸",
   relatedWords:[
     {word:"acute",meaning:"鋭い；深刻な",breakdown:"acr（鋭い）→ 先がとがって鋭く、よく切れる"},
     {word:"eager",meaning:"熱心な",breakdown:"eag（鋭い）→ 気持ちが鋭くとがって前のめりな"},
     {synonym:true,word:"sour",meaning:"酸っぱい",breakdown:"すっぱい味。acid は化学の「酸」としても使う"},
     {synonym:true,word:"sharp",meaning:"鋭い，刺すような",breakdown:"刺すような感じ。acid は味や言葉の鋭さに使う"}]},

  {id:1423,word:"toxic",partOfSpeech:"形容詞",meaning:"有毒な",
   meanings:["形|有毒な，毒性の"],
   pronunciation:"/ˈtɑːksɪk/",part:143,
   example:"These old paints are highly toxic to small children.",
   exampleJa:"これらの古い塗料は、小さな子どもにとって非常に有毒だ。",
   example2:"The factory released toxic waste into the clean river.",
   exampleJa2:"その工場は、きれいな川へ有毒な廃棄物を流した。",
   etymologyProcess:"tox（弓矢に塗る毒）→ 体に入ると害をなすものなら…？",
   etymologyConclusion:"tox（弓矢に塗る毒）→ 体に入ると害をなす＝有毒な",
   relatedWords:[
     {word:"toxin",meaning:"毒素",breakdown:"tox（弓矢に塗る毒）→ 生き物が作り出す毒そのもの"},
     {word:"intoxicated",meaning:"酔った",breakdown:"in（中へ）＋ tox（弓矢に塗る毒）→ 毒が体に回ったような状態の"},
     {word:"detox",meaning:"解毒",breakdown:"de（離して）＋ tox（弓矢に塗る毒）→ 体から毒を離して抜くこと"},
     {synonym:true,word:"poisonous",meaning:"毒のある",breakdown:"毒をふくむこと。toxic は化学物質や環境にもよく使う"}]},

  {id:1424,word:"endeavor",partOfSpeech:"自動詞",meaning:"（懸命に）努力する",
   meanings:["自|（to do）懸命に努力する","名|努力，試み"],
   pronunciation:"/ɪnˈdevər/",part:143,
   example:"We must endeavor to finish the project on time.",
   exampleJa:"私たちは、その計画を期限どおりに終えるよう努力しなければならない。",
   example2:"She endeavored to help every student in her class.",
   exampleJa2:"彼女は、クラスのすべての生徒を助けようと努力した。",
   etymologyProcess:"en（〜にする）＋ dev（果たすべき務め）→ 自分の務めにして力を尽くすと…？",
   etymologyConclusion:"en（〜にする）＋ dev（果たすべき務め）→ 自分の務めにして力を尽くす＝努力する",
   relatedWords:[
     {word:"debt",meaning:"借金",breakdown:"deb（負う）→ 返す務めを負っているもの"},
     {word:"due",meaning:"支払うべき；当然の",breakdown:"due（負っている）→ 果たすべき務めがある"},
     {synonym:true,word:"strive",meaning:"努力する",breakdown:"苦しみながら励むこと。endeavor は改まった書き言葉"},
     {synonym:true,word:"try",meaning:"やってみる",breakdown:"ふつうの言い方。endeavor は本気で力を尽くすことを言う"}]},

  {id:1425,word:"doom",partOfSpeech:"名詞",meaning:"破滅，悪い運命",
   meanings:["名|破滅，悪い運命","他|（悪い運命に）運命づける"],
   pronunciation:"/duːm/",part:143,
   example:"Many people feared the doom of their old city.",
   exampleJa:"多くの人が、自分たちの古い都市の破滅を恐れた。",
   example2:"The plan was doomed from the very beginning.",
   exampleJa2:"その計画は、最初から失敗する運命にあった。",
   etymologyProcess:"doom（裁き）→ 変えられない裁きが下された先にあるものは…？",
   etymologyConclusion:"doom（裁き）→ 変えられない裁きが下された末の悪い結末＝破滅",
   hook:"古英語 dom（裁き）から。「下された判決は変えられない」が芯。",
   relatedWords:[
     {word:"doomed",meaning:"運命づけられた",breakdown:"doom（裁き）＋ ed（〜された）→ 悪い結末を言い渡された"},
     {synonym:true,word:"fate",meaning:"運命",breakdown:"定められた成り行き。doom は悪い結末にかぎって使う"},
     {synonym:true,word:"ruin",meaning:"破滅，荒廃",breakdown:"崩れ落ちること。doom はそこへ向かう定めを言う"},
     {synonym:true,word:"destruction",meaning:"破壊",breakdown:"壊されること。doom は避けられない悪い運命を指す"}]},

  {id:1426,word:"manufacture",partOfSpeech:"他動詞",meaning:"製造する",
   meanings:["他|（工場で）製造する","名|製造"],
   pronunciation:"/ˌmænjuˈfæktʃər/",part:143,
   example:"This factory manufactures parts for small electric cars.",
   exampleJa:"この工場は、小型の電気自動車の部品を製造している。",
   example2:"The company manufactured over one million phones last year.",
   exampleJa2:"その会社は昨年、100万台を超える電話を製造した。",
   etymologyProcess:"manu（手）＋ fact（作る）→ もとは手で作ること、今は工場で作ると…？",
   etymologyConclusion:"manu（手）＋ fact（作る）→ もとは手で作ること、今は工場で大量に作る＝製造する",
   relatedWords:[
     {word:"manual",meaning:"手動の；手引き書",breakdown:"manu（手）＋ al（形容詞）→ 手で行う"},
     {word:"manuscript",meaning:"原稿",breakdown:"manu（手）＋ scrib（書く）→ 手で書かれたもの"},
     {word:"factory",meaning:"工場",breakdown:"fact（作る）＋ ory（場所）→ ものを作るための場所"},
     {synonym:true,word:"produce",meaning:"生産する",breakdown:"作り出すこと。manufacture は工場での大量生産を指す"}]},

  {id:1427,word:"yield",partOfSpeech:"他動詞",meaning:"（作物・利益を）生み出す；屈する",
   meanings:["他|（作物・利益を）生み出す","自|（to ～に）屈する，譲る","名|収穫量"],
   pronunciation:"/jiːld/",part:143,
   example:"These wide fields yield a large crop every autumn.",
   exampleJa:"これらの広い畑は、毎年秋に多くの作物を生み出す。",
   example2:"He refused to yield to the strong pressure.",
   exampleJa2:"彼は、その強い圧力に屈することを拒んだ。",
   etymologyProcess:"yield（差し出す）→ 求めに応じて手もとのものを差し出すと…？",
   etymologyConclusion:"yield（差し出す）→ 求めに応じて手もとのものを差し出す＝生み出す",
   hook:"「差し出す」が芯。畑が作物を差し出す→収穫、相手に道を差し出す→屈する。",
   relatedWords:[
     {synonym:true,word:"produce",meaning:"生み出す",breakdown:"作り出すこと。yield は畑や投資が生み出す量に使う"},
     {synonym:true,word:"surrender",meaning:"降伏する",breakdown:"すっかり明け渡すこと。yield は押されて譲ることを言う"},
     {synonym:true,word:"submit",meaning:"従う，服従する",breakdown:"下について従うこと。yield はしぶしぶ譲る感じが強い"},
     {synonym:true,word:"give in",meaning:"折れる",breakdown:"くだけた言い方。yield は書き言葉でよく使う"}]},

  {id:1428,word:"duplicate",partOfSpeech:"他動詞",meaning:"複製する，二重にする",
   meanings:["他|複製する，二重にする","名|複製，控え"],
   pronunciation:"/ˈduːplɪkeɪt/",part:143,
   example:"Please duplicate this document for all the club members.",
   exampleJa:"この書類を、クラブの全員分に複製してください。",
   example2:"The machine duplicated the key in just one minute.",
   exampleJa2:"その機械は、わずか1分で鍵を複製した。",
   etymologyProcess:"du（2）＋ plic（折る）→ 同じものを二つに折り重ねて作ると…？",
   etymologyConclusion:"du（2）＋ plic（折る）→ 同じものを二つに折り重ねて作る＝複製する",
   relatedWords:[
     {word:"double",meaning:"2倍の",breakdown:"du（2）→ 同じものが二つ分ある"},
     {word:"complicated",meaning:"複雑な",breakdown:"com（共に）＋ plic（折る）→ 何重にも折り重なっている"},
     {word:"explicit",meaning:"明確な",breakdown:"ex（外へ）＋ plic（折る）→ 折りたたみを開いてはっきりさせた"},
     {synonym:true,word:"copy",meaning:"写す",breakdown:"同じものを作ること。duplicate はまったく同じ控えを作ること"}]},

  {id:1429,word:"assemble",partOfSpeech:"他動詞",meaning:"（部品を）組み立てる；集まる",
   meanings:["他|（部品を）組み立てる","自|（人が）集まる"],
   pronunciation:"/əˈsembl/",part:143,
   example:"The students assemble in the gym every Monday morning.",
   exampleJa:"生徒たちは毎週月曜の朝、体育館に集まる。",
   example2:"He assembled the new bookshelf without any help.",
   exampleJa2:"彼は誰の助けも借りずに、新しい本棚を組み立てた。",
   etymologyProcess:"as（〜へ）＋ simul（一緒に）→ ばらばらのものを一か所へ寄せると…？",
   etymologyConclusion:"as（〜へ）＋ simul（一緒に）→ ばらばらのものを一か所へ寄せ集める＝組み立てる",
   relatedWords:[
     {word:"assembly",meaning:"集会；組み立て",breakdown:"as（〜へ）＋ simul（一緒に）→ 一か所に集まること"},
     {word:"simultaneous",meaning:"同時の",breakdown:"simul（一緒に）＋ ous（形容詞）→ 同じ時に一緒に起こる"},
     {word:"similar",meaning:"似ている",breakdown:"simil（似ている）＋ ar（〜の）→ 形や性質が似ている"},
     {synonym:true,word:"gather",meaning:"集める",breakdown:"寄せ集めること。assemble は部品を組み上げる意味でも使う"}]},

  {id:1430,word:"mold",partOfSpeech:"名詞",meaning:"型；形づくる",
   meanings:["名|型，鋳型","他|型に入れて形づくる"],
   pronunciation:"/moʊld/",part:143,
   example:"The workers pour hot metal into a large mold.",
   exampleJa:"作業員たちは、熱い金属を大きな鋳型に流しこむ。",
   example2:"Good teachers help mold the character of young students.",
   exampleJa2:"よい教師は、若い生徒の人格を形づくる手助けをする。",
   etymologyProcess:"modul（小さなます）→ 形と大きさを決めるための器なら…？",
   etymologyConclusion:"modul（小さなます）→ 形と大きさを決めるための器＝型",
   relatedWords:[
     {word:"model",meaning:"模型；手本",breakdown:"modul（小さなます）→ 形を決めるためのひな型"},
     {word:"module",meaning:"（組み立て用の）単位",breakdown:"modul（小さなます）→ 決まった大きさのひとまとまり"},
     {synonym:true,word:"shape",meaning:"形づくる",breakdown:"形を与えること。mold は型に流しこんで作ることを言う"},
     {synonym:true,word:"cast",meaning:"鋳造する",breakdown:"型に流しこむこと。mold はその型そのものも指す"}]},

  {id:1431,word:"coin",partOfSpeech:"名詞",meaning:"硬貨；（新語を）作り出す",
   meanings:["名|硬貨，コイン","他|（新しい語を）作り出す"],
   pronunciation:"/kɔɪn/",part:144,
   example:"He put three old coins into the small box.",
   exampleJa:"彼は3枚の古い硬貨を、その小さな箱に入れた。",
   example2:"She coined a new word for this strange feeling.",
   exampleJa2:"彼女は、この奇妙な感情を表す新しい語を作り出した。",
   etymologyProcess:"coin（くさび）→ くさび形の型で打ち出した金属の板なら…？",
   etymologyConclusion:"coin（くさび）→ くさび形の型で打ち出した金属の板＝硬貨",
   hook:"型で打ち出すのが芯。新しい言葉を「打ち出す」→ 作り出す、にもなる。",
   relatedWords:[
     {word:"coinage",meaning:"貨幣；新しく作られた語",breakdown:"coin（くさび）＋ age（名詞）→ 型で打ち出して作られたもの"},
     {synonym:true,word:"currency",meaning:"通貨",breakdown:"世の中で通用するお金。coin は金属の硬貨を指す"},
     {synonym:true,word:"cash",meaning:"現金",breakdown:"紙幣も含む現金。coin は硬貨だけを指す"},
     {synonym:true,word:"change",meaning:"小銭；つり銭",breakdown:"細かいお金。coin は一枚一枚の硬貨のこと"}]},

  {id:1432,word:"therapy",partOfSpeech:"名詞",meaning:"（心身の）治療，療法",
   meanings:["名|（心身の）治療，療法"],
   pronunciation:"/ˈθerəpi/",part:144,
   example:"She started speech therapy after the serious accident.",
   exampleJa:"彼女は、その大きな事故のあとで言語療法を始めた。",
   example2:"Music therapy helps many patients relax and recover.",
   exampleJa2:"音楽療法は、多くの患者がくつろいで回復するのを助ける。",
   etymologyProcess:"therap（世話をする）→ そばで世話をして体や心を治すと…？",
   etymologyConclusion:"therap（世話をする）→ そばで世話をして体や心を治すこと＝治療",
   relatedWords:[
     {word:"therapist",meaning:"療法士",breakdown:"therap（世話をする）＋ ist（人）→ 治療のために世話をする人"},
     {word:"therapeutic",meaning:"治療の，効き目のある",breakdown:"therap（世話をする）＋ ic（〜の）→ 治すのに役立つ"},
     {synonym:true,word:"treatment",meaning:"治療",breakdown:"手当てをすること。therapy は続けて行う療法を指す"},
     {synonym:true,word:"cure",meaning:"治療法；治す",breakdown:"病気を治しきること。therapy は治す過程そのものを言う"}]},

  {id:1433,word:"injection",partOfSpeech:"名詞",meaning:"注射",
   meanings:["名|注射","名|（資金などの）投入"],
   pronunciation:"/ɪnˈdʒekʃn/",part:144,
   example:"The nurse gave the frightened boy a quick injection.",
   exampleJa:"看護師は、おびえた少年にすばやく注射をした。",
   example2:"This injection protects children from a serious disease.",
   exampleJa2:"この注射は、子どもを重い病気から守る。",
   etymologyProcess:"in（中へ）＋ ject（投げる）→ 体の中へ薬を勢いよく送りこむと…？",
   etymologyConclusion:"in（中へ）＋ ject（投げる）→ 体の中へ薬を勢いよく送りこむこと＝注射",
   relatedWords:[
     {word:"inject",meaning:"注射する，注入する",breakdown:"in（中へ）＋ ject（投げる）→ 中へ勢いよく送りこむ"},
     {word:"reject",meaning:"断る，拒否する",breakdown:"re（後ろへ）＋ ject（投げる）→ 受け取らず投げ返す"},
     {word:"project",meaning:"計画；投影する",breakdown:"pro（前へ）＋ ject（投げる）→ 先の方へ投げ出して示す"},
     {synonym:true,word:"shot",meaning:"注射",breakdown:"くだけた言い方。injection は医療の場で使う正式な語"}]},

  {id:1434,word:"dose",partOfSpeech:"名詞",meaning:"（薬の）1回分の量",
   meanings:["名|（薬の）1回分の量，服用量"],
   pronunciation:"/doʊs/",part:144,
   example:"Take one dose of this medicine after every meal.",
   exampleJa:"毎食後に、この薬を1回分ずつ飲んでください。",
   example2:"The doctor reduced the daily dose by half.",
   exampleJa2:"医師は、1日の服用量を半分に減らした。",
   etymologyProcess:"dos（与える）→ 一度に与えると決められた薬の量なら…？",
   etymologyConclusion:"dos（与える）→ 一度に与えると決められた薬の量＝1回分",
   relatedWords:[
     {word:"overdose",meaning:"過剰摂取",breakdown:"over（越えて）＋ dos（与える）→ 決めた量を越えて与えること"},
     {word:"dosage",meaning:"服用量の決め方",breakdown:"dos（与える）＋ age（名詞）→ どれだけ与えるかの決まり"},
     {synonym:true,word:"amount",meaning:"量",breakdown:"分量一般。dose は薬の1回分と決まった量を指す"},
     {synonym:true,word:"portion",meaning:"取り分，1人分",breakdown:"分けた一つ分。dose は薬や治療の量に使う"}]},

  {id:1435,word:"sanitation",partOfSpeech:"名詞",meaning:"公衆衛生，衛生設備",
   meanings:["名|公衆衛生，衛生設備"],
   pronunciation:"/ˌsænɪˈteɪʃn/",part:144,
   example:"Clean water and good sanitation prevent many serious diseases.",
   exampleJa:"きれいな水と整った衛生設備は、多くの重い病気を防ぐ。",
   example2:"The village finally got modern sanitation last year.",
   exampleJa2:"その村は昨年、ようやく近代的な衛生設備を手に入れた。",
   etymologyProcess:"sanit（健康な）＋ ation（名詞）→ 人々を健康に保つ仕組みなら…？",
   etymologyConclusion:"sanit（健康な）＋ ation（名詞）→ 人々を健康に保つための仕組み＝公衆衛生",
   relatedWords:[
     {word:"sanitary",meaning:"衛生的な",breakdown:"sanit（健康な）＋ ary（形容詞）→ 健康を保てるほど清潔な"},
     {word:"sane",meaning:"正気の",breakdown:"sanit（健康な）→ 心が健康で筋道が通っている"},
     {word:"insane",meaning:"正気でない",breakdown:"in（否定）＋ sanit（健康な）→ 心の健康が保たれていない"},
     {synonym:true,word:"hygiene",meaning:"衛生",breakdown:"清潔を保つこと。sanitation は社会の設備や仕組みを指す"}]},

  {id:1436,word:"germ",partOfSpeech:"名詞",meaning:"細菌，病原菌",
   meanings:["名|細菌，病原菌","名|芽，芽生え"],
   pronunciation:"/dʒɜːrm/",part:144,
   example:"Wash your hands well to remove all harmful germs.",
   exampleJa:"有害な細菌をすべて落とすために、手をよく洗いなさい。",
   example2:"Germs spread quickly in a crowded warm room.",
   exampleJa2:"細菌は、混み合った暖かい部屋ではすばやく広がる。",
   etymologyProcess:"germ（芽）→ 増えて広がっていく小さな芽のようなものなら…？",
   etymologyConclusion:"germ（芽）→ 増えて広がっていく小さな芽のようなもの＝細菌",
   relatedWords:[
     {word:"germinate",meaning:"発芽する",breakdown:"germ（芽）＋ ate（動詞）→ 種が芽を出して育ち始める"},
     {synonym:true,word:"bacteria",meaning:"バクテリア，細菌",breakdown:"学術的な語。germ は日常語として広く使う"},
     {synonym:true,word:"microbe",meaning:"微生物",breakdown:"小さな生き物全体。germ は病気を起こす菌を指すことが多い"},
     {synonym:true,word:"bug",meaning:"（口語で）ばい菌",breakdown:"くだけた言い方。germ のほうが広く使われる"}]},

  {id:1437,word:"tumor",partOfSpeech:"名詞",meaning:"腫瘍",
   meanings:["名|腫瘍"],
   pronunciation:"/ˈtuːmər/",part:144,
   example:"The doctor found a small tumor in his lung.",
   exampleJa:"医師は、彼の肺に小さな腫瘍を見つけた。",
   example2:"Most tumors of this kind are not dangerous.",
   exampleJa2:"この種類の腫瘍の多くは、危険ではない。",
   etymologyProcess:"tum（ふくれる）→ 体の中で不自然にふくれ上がった塊なら…？",
   etymologyConclusion:"tum（ふくれる）→ 体の中で不自然にふくれ上がった塊＝腫瘍",
   relatedWords:[
     {word:"tumult",meaning:"騒動，混乱",breakdown:"tum（ふくれる）→ 人々の気持ちがふくれ上がって起こる騒ぎ"},
     {synonym:true,word:"growth",meaning:"できもの；成長",breakdown:"できて大きくなるもの。tumor は医学で使う語"},
     {synonym:true,word:"lump",meaning:"しこり，かたまり",breakdown:"手で触れる塊。tumor は体内にできた腫れを指す"},
     {synonym:true,word:"mass",meaning:"かたまり",breakdown:"まとまった塊。tumor は病気としての腫れを言う"}]},

  {id:1438,word:"stroke",partOfSpeech:"名詞",meaning:"ひと打ち，ひとかき；脳卒中",
   meanings:["名|ひと打ち，ひとかき","名|脳卒中","他|やさしくなでる"],
   pronunciation:"/stroʊk/",part:144,
   example:"Her grandfather suddenly had a stroke last cold winter.",
   exampleJa:"彼女の祖父は、去年の寒い冬に突然、脳卒中になった。",
   example2:"He won the swimming race by a single stroke.",
   exampleJa2:"彼はわずかひとかきの差で、その水泳競技に勝った。",
   etymologyProcess:"stroke（ひと打ち）→ さっと一度打つ、なでる動きなら…？",
   etymologyConclusion:"stroke（ひと打ち）→ さっと一度打つ、またはなでる動き＝ひと打ち",
   hook:"脳卒中は「（見えない力に）ひと打ちされた」から来た言い方。",
   relatedWords:[
     {word:"strike",meaning:"打つ",breakdown:"strike（さっと走らせる）→ 手や道具をさっと走らせて当てる"},
     {synonym:true,word:"blow",meaning:"一撃",breakdown:"強く当たる打撃。stroke はひと続きの動きを指す"},
     {synonym:true,word:"hit",meaning:"打つこと",breakdown:"当てること。stroke は一回分の動作を数えるときに使う"},
     {synonym:true,word:"pat",meaning:"軽くたたく",breakdown:"軽く触れること。stroke は手をすべらせてなでること"}]},

  {id:1439,word:"agony",partOfSpeech:"名詞",meaning:"激しい苦痛，苦悶",
   meanings:["名|激しい苦痛，苦悶"],
   pronunciation:"/ˈæɡəni/",part:144,
   example:"He was in terrible agony after the bad fall.",
   exampleJa:"彼はひどく転んだあと、激しい苦痛に襲われていた。",
   example2:"She waited in agony for the final test results.",
   exampleJa2:"彼女は苦しい思いで、最終的な検査結果を待った。",
   etymologyProcess:"agon（競い合う闘い）→ 闘いのさなかのような激しい苦しみなら…？",
   etymologyConclusion:"agon（競い合う闘い）→ 闘いのさなかのような激しい苦しみ＝苦痛",
   relatedWords:[
     {word:"agonize",meaning:"苦しみもだえる",breakdown:"agon（競い合う闘い）＋ ize（動詞）→ 闘うように激しく苦しむ"},
     {word:"antagonist",meaning:"敵対者",breakdown:"anti（逆に）＋ agon（競い合う闘い）→ 向かい合って争う相手"},
     {synonym:true,word:"pain",meaning:"痛み",breakdown:"ふつうの痛み。agony は耐えがたいほど激しい苦しみ"},
     {synonym:true,word:"torment",meaning:"苦しみ，責め苦",breakdown:"長く続く責め苦。agony はその瞬間の激しさを言う"}]},

  {id:1440,word:"plague",partOfSpeech:"名詞",meaning:"疫病，伝染病",
   meanings:["名|疫病，伝染病","他|（長く）悩ます"],
   pronunciation:"/pleɪɡ/",part:144,
   example:"The terrible plague killed many people in old Europe.",
   exampleJa:"その恐ろしい疫病は、昔のヨーロッパで多くの人の命を奪った。",
   example2:"Money problems plagued the small company for years.",
   exampleJa2:"資金の問題が、その小さな会社を何年も悩ませた。",
   etymologyProcess:"plag（打撃）→ 人々を一度に打ちのめすものなら…？",
   etymologyConclusion:"plag（打撃）→ 人々を一度に打ちのめす病気＝疫病",
   hook:"「打撃」が芯。動詞では「しつこく打ち続ける」→ 悩ます。",
   relatedWords:[
     {synonym:true,word:"epidemic",meaning:"流行病",breakdown:"広がる病気。plague は特に死者の多い恐ろしい疫病を指す"},
     {synonym:true,word:"disease",meaning:"病気",breakdown:"病気一般。plague は一気に広がる大きな病を言う"},
     {synonym:true,word:"outbreak",meaning:"（病気の）発生",breakdown:"広がり始めること。plague は病気そのものを指す"},
     {synonym:true,word:"torment",meaning:"苦しめる",breakdown:"苦しめること。plague はしつこく悩ませ続けること"}]},

  {id:1441,word:"fatigue",partOfSpeech:"名詞",meaning:"疲労，疲れ",
   meanings:["名|疲労，疲れ"],
   pronunciation:"/fəˈtiːɡ/",part:145,
   example:"Long hours of hard study caused her serious fatigue.",
   exampleJa:"長時間の厳しい勉強が、彼女にひどい疲労をもたらした。",
   example2:"Drivers must take breaks to avoid dangerous fatigue.",
   exampleJa2:"運転手は、危険な疲労を避けるために休憩を取らなければならない。",
   etymologyProcess:"fatig（疲れさせる）→ 力を使い果たしてぐったりすると…？",
   etymologyConclusion:"fatig（疲れさせる）→ 力を使い果たしてぐったりした状態＝疲労",
   hook:"metal fatigue（金属疲労）のように、物が弱ることにも使う。",
   relatedWords:[
     {synonym:true,word:"tiredness",meaning:"疲れ",breakdown:"ふつうの疲れ。fatigue は重く長く続く疲れを指す"},
     {synonym:true,word:"exhaustion",meaning:"疲れ果てること",breakdown:"力が尽きること。fatigue はそこまで行かない疲れも指す"},
     {synonym:true,word:"weariness",meaning:"だるさ，倦怠",breakdown:"飽きを伴う疲れ。fatigue は体力の消耗を強く表す"},
     {synonym:true,word:"burnout",meaning:"燃え尽き",breakdown:"働きすぎて意欲を失うこと。fatigue は体の疲れが中心"}]},

  {id:1442,word:"diagnosis",partOfSpeech:"名詞",meaning:"診断",
   meanings:["名|診断"],
   pronunciation:"/ˌdaɪəɡˈnoʊsɪs/",part:145,
   example:"The doctor gave a clear diagnosis after many tests.",
   exampleJa:"医師は多くの検査のあと、はっきりした診断を下した。",
   example2:"An early diagnosis can save a patient's life.",
   exampleJa2:"早い診断が、患者の命を救うことがある。",
   etymologyProcess:"dia（間で）＋ gn（知る）→ いくつもの病気を見分けて知ると…？",
   etymologyConclusion:"dia（間で）＋ gn（知る）→ 似た病気を見分けて言い当てること＝診断",
   relatedWords:[
     {word:"diagnose",meaning:"診断する",breakdown:"dia（間で）＋ gn（知る）→ 症状からどの病気かを見分ける"},
     {word:"recognize",meaning:"見分ける，認める",breakdown:"re（再び）＋ gn（知る）→ もう一度見て同じものだと分かる"},
     {word:"diameter",meaning:"直径",breakdown:"dia（間で）＋ meter（測る）→ 円を横切って測った長さ"},
     {synonym:true,word:"assessment",meaning:"判定，評価",breakdown:"見きわめること。diagnosis は病気や不具合の特定を指す"}]},

  {id:1443,word:"mortality",partOfSpeech:"名詞",meaning:"死亡率；死すべき運命",
   meanings:["名|死亡率","名|死すべき運命"],
   pronunciation:"/mɔːrˈtæləti/",part:145,
   example:"The infant mortality rate has fallen sharply here.",
   exampleJa:"この地域では、乳児の死亡率が急激に下がっている。",
   example2:"The old poem reminds readers of human mortality.",
   exampleJa2:"その古い詩は、人がいつか死ぬ存在であることを読者に思い出させる。",
   etymologyProcess:"mort（死）＋ ity（名詞）→ どれだけ死んでいるかを表す数なら…？",
   etymologyConclusion:"mort（死）＋ ity（名詞）→ 死んでいくものの割合を表す数＝死亡率",
   relatedWords:[
     {word:"mortal",meaning:"死すべき；命にかかわる",breakdown:"mort（死）＋ al（形容詞）→ いつか死ぬ運命の"},
     {word:"immortal",meaning:"不死の",breakdown:"im（否定）＋ mort（死）→ 決して死ぬことがない"},
     {word:"mortgage",meaning:"住宅ローン，抵当",breakdown:"mort（死）＋ gage（担保）→ 払い終われば死ぬ（消える）約束"},
     {synonym:true,word:"death rate",meaning:"死亡率",breakdown:"分かりやすい言い方。mortality は統計や医学で使う語"}]},

  {id:1444,word:"nursing",partOfSpeech:"名詞",meaning:"看護",
   meanings:["名|看護，看護の仕事"],
   pronunciation:"/ˈnɜːrsɪŋ/",part:145,
   example:"She studied nursing at a famous city college.",
   exampleJa:"彼女は、有名な市立の大学で看護を学んだ。",
   example2:"Good nursing helped him recover much more quickly than expected.",
   exampleJa2:"よい看護のおかげで、彼は思ったよりずっと早く回復した。",
   etymologyProcess:"nurs（養い育てる）→ 弱った人をそばで養い世話をすると…？",
   etymologyConclusion:"nurs（養い育てる）→ 弱った人をそばで養い世話をすること＝看護",
   relatedWords:[
     {word:"nurse",meaning:"看護師；世話をする",breakdown:"nurs（養い育てる）→ 人を養い世話をする人"},
     {word:"nourish",meaning:"栄養を与える",breakdown:"nurs（養い育てる）→ 食べ物を与えて体を育てる"},
     {word:"nursery",meaning:"保育室；苗床",breakdown:"nurs（養い育てる）＋ ery（場所）→ 小さな子や苗を育てる場所"},
     {synonym:true,word:"care",meaning:"世話，介護",breakdown:"世話をすること。nursing は医療の知識を伴う看護を指す"}]},

  {id:1445,word:"chronic",partOfSpeech:"形容詞",meaning:"慢性の，長く続く",
   meanings:["形|慢性の，長く続く"],
   pronunciation:"/ˈkrɑːnɪk/",part:145,
   example:"He suffers from chronic pain in his lower back.",
   exampleJa:"彼は、腰に慢性の痛みを抱えている。",
   example2:"Chronic illness can change a person's whole life.",
   exampleJa2:"慢性の病気は、人の人生をまるごと変えてしまうことがある。",
   etymologyProcess:"chron（時）＋ ic（〜の）→ 長い時間にわたって続くものなら…？",
   etymologyConclusion:"chron（時）＋ ic（〜の）→ 長い時間にわたって続く＝慢性の",
   relatedWords:[
     {word:"chronicle",meaning:"年代記",breakdown:"chron（時）→ 時の順に書きとめた記録"},
     {word:"synchronize",meaning:"同時に動かす",breakdown:"syn（共に）＋ chron（時）→ 時をぴたりと合わせる"},
     {word:"chronological",meaning:"年代順の",breakdown:"chron（時）＋ ical（〜の）→ 時の流れの順に並んだ"},
     {synonym:true,word:"persistent",meaning:"しつこく続く",breakdown:"続いてやまないこと。chronic は病気や問題に多く使う"}]},

  {id:1446,word:"immune",partOfSpeech:"形容詞",meaning:"免疫がある；免れている",
   meanings:["形|（to ～に）免疫がある","形|（from ～を）免れている"],
   pronunciation:"/ɪˈmjuːn/",part:145,
   example:"Most adults are immune to this common childhood disease.",
   exampleJa:"大人のほとんどは、この子どもによくある病気に免疫がある。",
   example2:"No one is immune from making simple mistakes.",
   exampleJa2:"単純な間違いを免れる人など、誰もいない。",
   etymologyProcess:"im（否定）＋ mun（務め）→ 負わされるはずのものを負わずにすむと…？",
   etymologyConclusion:"im（否定）＋ mun（務め）→ 負わされるはずのものを負わずにすむ＝免疫がある",
   why:"【なぜ】ラテン語 immunis は「公の務め（税や労役）を負わない」。「負わなくてよい」→「影響を受けない」となり、19世紀の医学で「病気にかからない＝免疫がある」の意味が生まれました。\n【つながり】common（共通の）、community（共同体）は「務めを分け合う」側の語です。",
   relatedWords:[
     {word:"community",meaning:"共同体，地域社会",breakdown:"com（共に）＋ mun（分け合う）→ 務めを分け合う人の集まり"},
     {word:"common",meaning:"共通の，ふつうの",breakdown:"com（共に）＋ mun（分け合う）→ みんなで分け合っている"},
     {word:"municipal",meaning:"市の，自治体の",breakdown:"mun（務め）＋ cip（取る）→ 自分たちで町の務めを引き受ける"},
     {synonym:true,word:"resistant",meaning:"抵抗力のある",breakdown:"押し返す力があること。immune は影響をまったく受けないこと"}]},

  {id:1447,word:"terminal",partOfSpeech:"名詞",meaning:"終点，ターミナル；末期の",
   meanings:["名|終点，ターミナル；端末","形|（病気が）末期の"],
   pronunciation:"/ˈtɜːrmɪnl/",part:145,
   example:"Our bus arrived at the airport terminal on time.",
   exampleJa:"私たちのバスは、時間どおりに空港のターミナルに着いた。",
   example2:"The doctors sadly said his illness was terminal.",
   exampleJa2:"医師たちは残念そうに、彼の病気は末期だと告げた。",
   etymologyProcess:"term（境界）＋ al（形容詞）→ 路線や命の境目にあたる場所なら…？",
   etymologyConclusion:"term（境界）＋ al（形容詞）→ 路線や命の境目にあたる場所＝終点",
   relatedWords:[
     {word:"term",meaning:"期間；用語",breakdown:"term（境界）→ 始めと終わりで区切られたひと区切り"},
     {word:"determine",meaning:"決定する",breakdown:"de（すっかり）＋ term（境界）→ 境をすっかりはっきり決める"},
     {word:"terminate",meaning:"終わらせる",breakdown:"term（境界）＋ ate（動詞）→ 境のところまで来て終わりにする"},
     {synonym:true,word:"final",meaning:"最後の",breakdown:"いちばん終わりの。terminal は終点や末期という場所・段階を指す"}]},

  {id:1448,word:"sound",partOfSpeech:"形容詞",meaning:"健全な，しっかりした",
   meanings:["形|健全な，しっかりした","形|（考えが）筋の通った"],
   pronunciation:"/saʊnd/",part:145,
   example:"The old stone bridge is still structurally sound today.",
   exampleJa:"その古い石橋は、今も構造的にしっかりしている。",
   example2:"She gave me very sound advice about saving money.",
   exampleJa2:"彼女は貯金について、とても筋の通った助言をくれた。",
   etymologyProcess:"sanit（健康な）→ どこも痛んでいない、しっかりした状態なら…？",
   etymologyConclusion:"sanit（健康な）→ どこも痛んでおらず、しっかりしている＝健全な",
   why:"【なぜ】「健全な」の sound は、ラテン語 sanus（健康な）と同じ流れをくむ語です。「音」の sound とはまったく別の語で、たまたま同じ形になっただけなので、混同しないようにしましょう。\n【つながり】sane（正気の）、sanitary（衛生的な）が同じ家族です。",
   relatedWords:[
     {word:"sane",meaning:"正気の",breakdown:"sanit（健康な）→ 心が健康で筋道が通っている"},
     {word:"sanitary",meaning:"衛生的な",breakdown:"sanit（健康な）＋ ary（形容詞）→ 健康を保てるほど清潔な"},
     {synonym:true,word:"healthy",meaning:"健康な",breakdown:"体が元気なこと。sound は物や考えにも使える"},
     {synonym:true,word:"solid",meaning:"しっかりした",breakdown:"がっしりしていること。sound は傷んでいない健全さを言う"}]},

  {id:1449,word:"respiratory",partOfSpeech:"形容詞",meaning:"呼吸の，呼吸器の",
   meanings:["形|呼吸の，呼吸器の"],
   pronunciation:"/ˈrespərətɔːri/",part:145,
   example:"Smoking damages the respiratory system very badly over time.",
   exampleJa:"喫煙は、時間とともに呼吸器の働きをひどく損なう。",
   example2:"The small child has a mild respiratory infection.",
   exampleJa2:"その小さな子どもは、軽い呼吸器の感染症にかかっている。",
   etymologyProcess:"re（再び）＋ spir（息をする）→ 何度も息を吸っては吐くことなら…？",
   etymologyConclusion:"re（再び）＋ spir（息をする）→ 何度も息を吸っては吐くことにかかわる＝呼吸の",
   relatedWords:[
     {word:"respiration",meaning:"呼吸",breakdown:"re（再び）＋ spir（息をする）＋ ation（名詞）→ くり返し息をすること"},
     {word:"inspire",meaning:"ひらめきを与える",breakdown:"in（中へ）＋ spir（息をする）→ 心の中へ息を吹きこむ"},
     {word:"spirit",meaning:"精神，魂",breakdown:"spir（息をする）→ 体に息を通わせているもの"},
     {synonym:true,word:"breathing",meaning:"呼吸の",breakdown:"やさしい言い方。respiratory は医学で使う硬い語"}]},

  {id:1450,word:"choke",partOfSpeech:"他動詞",meaning:"窒息させる；詰まらせる",
   meanings:["他|窒息させる，息を詰まらせる","自|息が詰まる"],
   pronunciation:"/tʃoʊk/",part:145,
   example:"Small toys can easily choke a very little baby.",
   exampleJa:"小さなおもちゃは、幼い赤ちゃんの息を簡単に詰まらせる。",
   example2:"Thick smoke began to choke the trapped workers.",
   exampleJa2:"濃い煙が、閉じこめられた作業員たちの息を詰まらせ始めた。",
   etymologyProcess:"choke（のど）→ のどをふさいで息ができなくすると…？",
   etymologyConclusion:"choke（のど）→ のどをふさいで息ができなくする＝窒息させる",
   hook:"「のど」が芯。感動で声が詰まるときにも choke up と使う。",
   relatedWords:[
     {synonym:true,word:"suffocate",meaning:"窒息させる",breakdown:"空気を断つこと。choke はのどが詰まる場合に使う"},
     {synonym:true,word:"strangle",meaning:"絞め殺す",breakdown:"首を絞めること。choke は物が詰まる場合にも使える"},
     {synonym:true,word:"block",meaning:"ふさぐ",breakdown:"通り道をふさぐこと。choke は息の通り道に使う"},
     {synonym:true,word:"clog",meaning:"詰まらせる",breakdown:"管などが詰まること。choke は人や動物の息にも使う"}]},
