  {id:951,word:"puzzle",partOfSpeech:"他動詞",meaning:"当惑させる",
   meanings:["他|当惑させる，頭を悩ませる","名|パズル，難問"],
   pronunciation:"/ˈpʌzl/",part:96,
   example:"The strange question puzzled even the smartest students here.",
   exampleJa:"その奇妙な問いは、ここでいちばん賢い生徒さえ当惑させた。",
   example2:"I am still puzzled by his very strange answer.",
   exampleJa2:"私はいまだに、彼のとても奇妙な答えに当惑している。",
   etymologyProcess:"puzzle（頭を悩ませる）→ 答えが見えずに頭を悩ませると…？",
   etymologyConclusion:"puzzle（頭を悩ませる）→ 答えが見えないまま頭を悩ませてしまう＝当惑させる",
   hook:"語源ははっきりしないが、ジグソーパズルの「解けずに悩む」感じで覚える。",
   relatedWords:[
     {synonym:true,word:"confuse",meaning:"混乱させる",breakdown:"頭をごちゃごちゃにする。puzzle は解けない謎で悩ませる"},
     {synonym:true,word:"riddle",meaning:"なぞなぞ",breakdown:"解くために出される問い。puzzle は悩ませることそのものも指す"},
     {synonym:true,word:"mystery",meaning:"なぞ",breakdown:"わけの分からないこと。puzzle は頭を悩ませる具体的な問題"},
     {synonym:true,word:"baffle",meaning:"当惑させる",breakdown:"まったく歯が立たなくさせる。puzzle よりお手上げ感が強い"}]},

  {id:952,word:"confuse",partOfSpeech:"他動詞",meaning:"混乱させる",
   meanings:["他|混乱させる","他|（A with B）を混同する"],
   pronunciation:"/kənˈfjuːz/",part:96,
   example:"The long explanation confused most of the class.",
   exampleJa:"その長い説明は、クラスの大半を混乱させた。",
   example2:"People often confuse these two very similar Japanese words.",
   exampleJa2:"人はしばしば、この2つのとても似た日本語の語を混同する。",
   etymologyProcess:"con（共に）＋ fuse（注ぐ）→ いくつもを一緒に注ぎ込んでまぜると…？",
   etymologyConclusion:"con（共に）＋ fuse（注ぐ）→ いくつもの物を一緒に注ぎ込んでごちゃまぜにする＝混乱させる",
   relatedWords:[
     {word:"refuse",meaning:"断る",breakdown:"re（後ろへ）＋ fuse（注ぐ）→ 差し出されたものを注ぎ返す"},
     {word:"confusion",meaning:"混乱",breakdown:"con（共に）＋ fuse（注ぐ）＋ ion（名詞）→ 混ざり合ったごちゃごちゃの状態"},
     {word:"fuse",meaning:"溶け合う，融合させる",breakdown:"fuse（注ぐ）→ 熱で溶かして一つに流し込む"},
     {synonym:true,word:"puzzle",meaning:"当惑させる",breakdown:"解けない謎で悩ませる。confuse は頭をごちゃごちゃにする"}]},

  {id:953,word:"bore",partOfSpeech:"他動詞",meaning:"退屈させる",
   meanings:["他|退屈させる","名|退屈な人・こと"],
   pronunciation:"/bɔːr/",part:96,
   example:"Long speeches bore most of the students in this school.",
   exampleJa:"長い演説は、この学校の生徒の大半を退屈させる。",
   example2:"I was bored during the long rainy afternoon at home.",
   exampleJa2:"長い雨の午後、私は家で退屈していた。",
   etymologyProcess:"bore（うんざりさせる）→ 同じことのくり返しで気持ちがしぼむと…？",
   etymologyConclusion:"bore（うんざりさせる）→ 同じことのくり返しで気持ちをしぼませる＝退屈させる",
   hook:"語源は不明。穴をあける bore とは別語だが、単調さの絵で覚えると楽。",
   relatedWords:[
     {synonym:true,word:"tedious",meaning:"長くて退屈な",breakdown:"だらだら続いて飽きること。bore はその状態にさせる動き"},
     {synonym:true,word:"dull",meaning:"退屈な，さえない",breakdown:"刺激がない状態。bore はその状態にさせる動きを表す"},
     {synonym:true,word:"tire",meaning:"疲れさせる",breakdown:"体や心を消耗させる。bore は単調さで気持ちをしぼませる"},
     {synonym:true,word:"weary",meaning:"うんざりした",breakdown:"疲れ果てたようす。bore はその気分にさせる側の語"}]},

  {id:954,word:"frustrate",partOfSpeech:"他動詞",meaning:"欲求不満にさせる",
   meanings:["他|欲求不満にさせる，いらだたせる","他|（計画）をくじく"],
   pronunciation:"/ˈfrʌstreɪt/",part:96,
   example:"Repeated failures frustrated the members of the basketball team.",
   exampleJa:"くり返す失敗が、バスケットボール部の部員たちを欲求不満にさせた。",
   example2:"Slow internet often frustrates students doing their online homework.",
   exampleJa2:"遅いインターネットは、オンラインの宿題をする生徒をしばしば欲求不満にさせる。",
   etymologyProcess:"frustr（むだに）＋ ate（動詞）→ 努力をむだに終わらせると…？",
   etymologyConclusion:"frustr（むだに）＋ ate（動詞）→ 努力をむだに終わらせ、やり場のない思いにさせる＝欲求不満にさせる",
   relatedWords:[
     {word:"frustration",meaning:"欲求不満",breakdown:"frustr（むだに）＋ ation（名詞）→ むだに終わってたまる思い"},
     {word:"frustrating",meaning:"もどかしい",breakdown:"frustr（むだに）＋ ing（〜している）→ 努力がむだになっていく感じの"},
     {synonym:true,word:"annoy",meaning:"いらだたせる",breakdown:"うるさがらせること。frustrate は思いどおりにならずもやもやさせる"},
     {synonym:true,word:"discourage",meaning:"やる気をそぐ",breakdown:"勇気をくじくこと。frustrate はやり場のない不満をためさせる"}]},

  {id:955,word:"disappoint",partOfSpeech:"他動詞",meaning:"失望させる",
   meanings:["他|失望させる，がっかりさせる"],
   pronunciation:"/ˌdɪsəˈpɔɪnt/",part:96,
   example:"The ending of the movie disappointed many longtime fans.",
   exampleJa:"その映画の結末は、長年の多くのファンを失望させた。",
   example2:"I was disappointed by the results of the math test.",
   exampleJa2:"私は数学のテストの結果に失望した。",
   etymologyProcess:"dis（否定）＋ ap（〜へ）＋ point（地点）→ 決めた約束を外してしまうと…？",
   etymologyConclusion:"dis（否定）＋ ap（〜へ）＋ point（地点）→ 決めた約束の一点を外して期待を裏切る＝失望させる",
   why:"【なぜ】もとは appoint（役目に就ける）の打ち消しで、「任を解く」ことでした。任を解かれた側の落胆から、「期待を裏切る＝失望させる」へ移りました。\n【つながり】appoint（任命する）、appointment（面会の約束）と同じ家族。約束の一点を外す、と考えると覚えやすくなります。",
   relatedWords:[
     {word:"point",meaning:"点；要点",breakdown:"point（地点）→ とがった先が指し示す一つの点"},
     {word:"appoint",meaning:"任命する",breakdown:"ap（〜へ）＋ point（地点）→ 役目や日時を一点に決める"},
     {word:"appointment",meaning:"（面会の）約束",breakdown:"ap（〜へ）＋ point（地点）＋ ment（名詞）→ 日時を一点に決めること"},
     {word:"punctual",meaning:"時間を守る",breakdown:"punct（点）＋ al（形容詞）→ 決めた時刻の一点にぴたり合わせる"}]},

  {id:956,word:"embarrass",partOfSpeech:"他動詞",meaning:"恥ずかしい思いをさせる",
   meanings:["他|恥ずかしい思いをさせる，きまり悪くさせる"],
   pronunciation:"/ɪmˈbærəs/",part:96,
   example:"His loud joke embarrassed everyone at the quiet dinner.",
   exampleJa:"彼の大声の冗談は、静かな夕食の席のみんなに恥ずかしい思いをさせた。",
   example2:"She was embarrassed when she forgot her classmate's name.",
   exampleJa2:"彼女はクラスメートの名前を忘れたとき、恥ずかしい思いをした。",
   etymologyProcess:"em（中へ）＋ barr（棒）→ 行く手に棒を渡されて動けなくなると…？",
   etymologyConclusion:"em（中へ）＋ barr（棒）→ 行く手に棒を渡されて身動きできず、きまりが悪くなる＝恥ずかしい思いをさせる",
   relatedWords:[
     {word:"bar",meaning:"棒；さえぎる",breakdown:"barr（棒）→ 通り道に渡して通さないようにする棒"},
     {word:"barrier",meaning:"障壁，バリア",breakdown:"barr（棒）＋ er（もの）→ 行く手をさえぎるもの"},
     {word:"barricade",meaning:"バリケード",breakdown:"barr（棒）→ 棒を並べて道をふさいだもの"},
     {synonym:true,word:"ashamed",meaning:"恥じている",breakdown:"悪いことをしたと恥じる。embarrass はきまりの悪さを感じさせる"}]},

  {id:957,word:"ashamed",partOfSpeech:"形容詞",meaning:"恥じている",
   meanings:["形|（of ～で）～を恥じている"],
   pronunciation:"/əˈʃeɪmd/",part:96,
   example:"He felt ashamed of his rude words to her.",
   exampleJa:"彼は、彼女への失礼な言葉を恥じていた。",
   example2:"You should not be ashamed of such a small mistake.",
   exampleJa2:"そんな小さな失敗を恥じる必要はありません。",
   etymologyProcess:"shame（恥）→ 自分のしたことを恥じて顔を伏せると…？",
   etymologyConclusion:"shame（恥）→ 自分のしたことを恥じて顔を上げられないでいる＝恥じている",
   relatedWords:[
     {word:"shame",meaning:"恥；残念なこと",breakdown:"shame（恥）→ 人に見られたくない気持ち"},
     {word:"shameful",meaning:"恥ずべき",breakdown:"shame（恥）＋ ful（満ちた）→ 恥で満ちている"},
     {word:"shameless",meaning:"恥知らずな",breakdown:"shame（恥）＋ less（ない）→ 恥じる気持ちがまるでない"},
     {synonym:true,word:"guilty",meaning:"やましい",breakdown:"罪の意識があること。ashamed は自分を恥じる気持ちを表す"}]},

  {id:958,word:"uneasy",partOfSpeech:"形容詞",meaning:"不安な，落ち着かない",
   meanings:["形|不安な，落ち着かない"],
   pronunciation:"/ʌnˈiːzi/",part:96,
   example:"She felt uneasy about walking home alone at night.",
   exampleJa:"彼女は夜に一人で歩いて帰ることを不安に感じた。",
   example2:"An uneasy silence filled the room after that question.",
   exampleJa2:"その質問の後、不安な沈黙が部屋を満たした。",
   etymologyProcess:"un（否定）＋ ease（楽）＋ y（〜な状態の）→ 気持ちが楽にならないと…？",
   etymologyConclusion:"un（否定）＋ ease（楽）＋ y（〜な状態の）→ 気持ちが楽にならず落ち着かない＝不安な",
   relatedWords:[
     {word:"easy",meaning:"やさしい，楽な",breakdown:"ease（楽）＋ y（〜な状態の）→ 苦もなくできる"},
     {word:"ease",meaning:"楽；やわらげる",breakdown:"ease（楽）→ 力を入れずにすむ心地よさ"},
     {word:"disease",meaning:"病気",breakdown:"dis（否定）＋ ease（楽）→ 体が楽でいられない状態"},
     {synonym:true,word:"anxious",meaning:"心配な",breakdown:"先のことを気に病むこと。uneasy は落ち着かない感じが中心"}]},

  {id:959,word:"hesitate",partOfSpeech:"自動詞",meaning:"ためらう",
   meanings:["自|ためらう，ちゅうちょする"],
   pronunciation:"/ˈhezɪteɪt/",part:96,
   example:"Do not hesitate to ask your teacher for help.",
   exampleJa:"先生に助けを求めるのをためらわないでください。",
   example2:"She hesitated for a moment before opening the letter.",
   exampleJa2:"彼女はその手紙を開ける前に、少しの間ためらった。",
   etymologyProcess:"hes（くっつく）＋ ate（動詞）→ 足がくっついて前へ出られないと…？",
   etymologyConclusion:"hes（くっつく）＋ ate（動詞）→ 足が地にくっついたように前へ出られない＝ためらう",
   relatedWords:[
     {word:"adhere",meaning:"くっつく，固守する",breakdown:"ad（〜へ）＋ her（くっつく）→ ぴたりとくっついて離れない"},
     {word:"hesitation",meaning:"ためらい",breakdown:"hes（くっつく）＋ ation（名詞）→ 足が止まってしまうこと"},
     {word:"coherent",meaning:"筋の通った",breakdown:"co（共に）＋ her（くっつく）→ 話の各部が互いにくっついている"},
     {synonym:true,word:"pause",meaning:"一時止まる",breakdown:"動きを一度止めること。hesitate は迷って踏み出せないこと"}]},

  {id:960,word:"reluctant",partOfSpeech:"形容詞",meaning:"気が進まない",
   meanings:["形|気が進まない，しぶしぶの"],
   pronunciation:"/rɪˈlʌktənt/",part:96,
   example:"He was reluctant to speak in front of everyone.",
   exampleJa:"彼はみんなの前で話すのに気が進まなかった。",
   example2:"She gave a reluctant nod and left the room quietly.",
   exampleJa2:"彼女は気の進まないうなずきをして、静かに部屋を出た。",
   etymologyProcess:"re（後ろへ）＋ luct（もがく）→ 心の中で後ろへもがいていると…？",
   etymologyConclusion:"re（後ろへ）＋ luct（もがく）→ 引き返そうと心の中でもがいている＝気が進まない",
   relatedWords:[
     {word:"reluctance",meaning:"気の進まなさ",breakdown:"re（後ろへ）＋ luct（もがく）＋ ance（名詞）→ 後ろへ引こうとする気持ち"},
     {synonym:true,word:"unwilling",meaning:"したがらない",breakdown:"する気がないこと。reluctant は心の中でしぶっている感じ"},
     {synonym:true,word:"hesitate",meaning:"ためらう",breakdown:"迷って踏み出せないこと。reluctant はそもそも気が進まない状態"},
     {synonym:true,word:"struggle",meaning:"もがく",breakdown:"力を入れて抗うこと。reluctant は心の中で後ずさっている状態"}]},

  {id:961,word:"tremble",partOfSpeech:"自動詞",meaning:"震える",
   meanings:["自|（小刻みに）震える"],
   pronunciation:"/ˈtrembl/",part:97,
   example:"Her hands tremble a little before every big speech.",
   exampleJa:"彼女の手は、大きなスピーチの前にいつも少し震える。",
   example2:"The whole building trembled during the strong earthquake.",
   exampleJa2:"強い地震の間、建物全体が震えた。",
   etymologyProcess:"trem（震える）→ 体が小刻みに揺れ続けると…？",
   etymologyConclusion:"trem（震える）→ 寒さや恐れで体が小刻みに揺れ続ける＝震える",
   relatedWords:[
     {word:"tremendous",meaning:"すさまじい",breakdown:"trem（震える）＋ ous（形容詞）→ 思わず震え上がるほどの"},
     {word:"tremor",meaning:"震え，小さな地震",breakdown:"trem（震える）＋ or（もの）→ 小刻みな揺れそのもの"},
     {synonym:true,word:"shake",meaning:"揺れる",breakdown:"大きく揺れること。tremble は小刻みで止められない震え"},
     {synonym:true,word:"shiver",meaning:"身震いする",breakdown:"寒さでぶるっとすること。tremble は恐れや緊張でも起こる"}]},

  {id:962,word:"boast",partOfSpeech:"自動詞",meaning:"自慢する",
   meanings:["自|（about / of ～）（～を）自慢する"],
   pronunciation:"/boʊst/",part:97,
   example:"He often boasts about his older brother's success.",
   exampleJa:"彼はよく、兄の成功について自慢する。",
   example2:"She never boasted, even after winning the national contest.",
   exampleJa2:"彼女は全国大会で優勝した後でさえ、決して自慢しなかった。",
   etymologyProcess:"boast（大きく言う）→ 自分のことを実際より大きく話すと…？",
   etymologyConclusion:"boast（大きく言う）→ 自分のことを実際より大きくふくらませて話す＝自慢する",
   hook:"もとの意味は不明。胸をふくらませて話す姿で覚える。boast of ～。",
   relatedWords:[
     {synonym:true,word:"brag",meaning:"自慢する",breakdown:"くだけた言い方。boast は少し硬く、書き言葉でも使う"},
     {synonym:true,word:"proud",meaning:"誇りに思う",breakdown:"胸を張る気持ち。boast はそれを口に出して言うこと"},
     {synonym:true,word:"pride",meaning:"誇り",breakdown:"自分をよしとする気持ち。boast はそれを声に出す行い"},
     {synonym:true,word:"exaggerate",meaning:"大げさに言う",breakdown:"実際より大きく言うこと。boast は自分のことに限る"}]},

  {id:963,word:"jealous",partOfSpeech:"形容詞",meaning:"嫉妬した",
   meanings:["形|（of ～）（～に）嫉妬した，やきもちを焼いた"],
   pronunciation:"/ˈdʒeləs/",part:97,
   example:"He felt jealous when his best friend got the prize.",
   exampleJa:"親友が賞を取ったとき、彼は嫉妬した。",
   example2:"A jealous look crossed her face for just a second.",
   exampleJa2:"嫉妬した表情が、ほんの一瞬だけ彼女の顔をよぎった。",
   etymologyProcess:"jeal（熱い思い）＋ ous（形容詞）→ 取られまいとする熱い思いに焼かれると…？",
   etymologyConclusion:"jeal（熱い思い）＋ ous（形容詞）→ 取られまいとする熱い思いに焼かれている＝嫉妬した",
   why:"【なぜ】ギリシャ語 zelos は「熱い思い・熱意」。よい方へ向かえば zeal（熱意）、人と比べる方へ向かえば jealousy（嫉妬）になりました。同じ「熱さ」から二つの語が分かれたのです。\n【つながり】jealous は「取られたくない」、envy は「持っていてうらやましい」と向きが違います。",
   relatedWords:[
     {word:"jealousy",meaning:"嫉妬",breakdown:"jeal（熱い思い）＋ y（名詞）→ 取られまいとする熱い思い"},
     {word:"zeal",meaning:"熱意",breakdown:"zel（熱い思い）→ よい方へ向かった熱い思い"},
     {word:"zealous",meaning:"熱心な",breakdown:"zel（熱い思い）＋ ous（形容詞）→ 熱意に満ちている"},
     {synonym:true,word:"envy",meaning:"うらやむ",breakdown:"持っていない物をほしがること。jealous は取られたくない気持ち"}]},

  {id:964,word:"envy",partOfSpeech:"他動詞",meaning:"うらやましく思う",
   meanings:["他|うらやましく思う","名|ねたみ，うらやみ"],
   pronunciation:"/ˈenvi/",part:97,
   example:"Many students envy her natural talent for music.",
   exampleJa:"多くの生徒が、彼女の生まれつきの音楽の才能をうらやましく思う。",
   example2:"I envied my cousin for his long summer holiday.",
   exampleJa2:"私はいとこの長い夏休みをうらやましく思った。",
   etymologyProcess:"in（〜に）＋ vid（見る）→ 相手の持ち物をじっと見つめると…？",
   etymologyConclusion:"in（〜に）＋ vid（見る）→ 相手の持ち物をじっと見つめてほしくなる＝うらやましく思う",
   relatedWords:[
     {word:"video",meaning:"動画，ビデオ",breakdown:"vid（見る）→ 目で見るためのもの"},
     {word:"provide",meaning:"供給する",breakdown:"pro（前もって）＋ vid（見る）→ 先を見越して用意しておく"},
     {word:"evident",meaning:"明らかな",breakdown:"ex（外へ）＋ vid（見る）→ 外から見てすぐ分かる"},
     {word:"envious",meaning:"うらやましがる",breakdown:"in（〜に）＋ vid（見る）＋ ous（形容詞）→ じっと見てほしがる"}]},

  {id:965,word:"yell",partOfSpeech:"自動詞",meaning:"叫ぶ，どなる",
   meanings:["自|叫ぶ，どなる"],
   pronunciation:"/jel/",part:97,
   example:"Please do not yell at your little brother like that.",
   exampleJa:"そんなふうに弟に向かって叫ばないでください。",
   example2:"The fans yelled loudly when the team finally scored.",
   exampleJa2:"チームがついに得点したとき、ファンは大声で叫んだ。",
   etymologyProcess:"yell（大声を出す）→ 腹の底から声を張り上げると…？",
   etymologyConclusion:"yell（大声を出す）→ 腹の底から大きな声を張り上げる＝叫ぶ",
   hook:"応援の「エール」と同じ語。腹の底から声を張り上げることが芯。",
   relatedWords:[
     {synonym:true,word:"shout",meaning:"叫ぶ",breakdown:"大きな声を出すこと。yell はもっと荒々しく、感情がこもる"},
     {synonym:true,word:"scream",meaning:"悲鳴を上げる",breakdown:"かん高い声を上げること。yell は怒りや応援のときにも使う"},
     {synonym:true,word:"cheer",meaning:"声援を送る",breakdown:"励ますための声。yell はその声を張り上げる行いそのもの"},
     {synonym:true,word:"roar",meaning:"ほえる，どなる",breakdown:"腹に響く低い大声。yell はもっと短く鋭い叫び"}]},

  {id:966,word:"respect",partOfSpeech:"他動詞",meaning:"尊敬する",
   meanings:["他|尊敬する","名|尊敬","名|（in ～ respect で）点"],
   pronunciation:"/rɪˈspekt/",part:97,
   example:"Students respect that teacher for her honest advice.",
   exampleJa:"生徒たちは、正直な助言ゆえにその先生を尊敬している。",
   example2:"He is respected by everyone in this small town.",
   exampleJa2:"彼はこの小さな町のみんなに尊敬されている。",
   etymologyProcess:"re（再び）＋ spect（見る）→ 何度も見返すほど価値を認めると…？",
   etymologyConclusion:"re（再び）＋ spect（見る）→ 何度も見返すほどその人の価値を認める＝尊敬する",
   relatedWords:[
     {word:"expect",meaning:"期待する",breakdown:"ex（外へ）＋ spect（見る）→ 外を見ながら来るのを待つ"},
     {word:"inspect",meaning:"検査する",breakdown:"in（中へ）＋ spect（見る）→ 中までのぞき込んで調べる"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ ator（人）→ 見ているほうの人"},
     {word:"suspect",meaning:"疑う",breakdown:"sub（下で）＋ spect（見る）→ 下から探るように見る"}]},

  {id:967,word:"despair",partOfSpeech:"名詞",meaning:"絶望",
   meanings:["名|絶望","自|絶望する"],
   pronunciation:"/dɪˈsper/",part:97,
   example:"He felt deep despair after losing the final match.",
   exampleJa:"決勝戦に負けた後、彼は深い絶望を感じた。",
   example2:"In despair she sat down on the cold hard ground.",
   exampleJa2:"絶望の中で、彼女は冷たい固い地面に座り込んだ。",
   etymologyProcess:"de（離して）＋ sper（希望）→ 希望から引き離されてしまうと…？",
   etymologyConclusion:"de（離して）＋ sper（希望）→ 希望から完全に引き離されてしまった状態＝絶望",
   relatedWords:[
     {word:"desperate",meaning:"必死の；絶望的な",breakdown:"de（離して）＋ sper（希望）＋ ate（形容詞）→ 希望を失って後がない"},
     {word:"desperation",meaning:"必死さ，絶望",breakdown:"de（離して）＋ sper（希望）＋ ation（名詞）→ 希望を失って追いつめられること"},
     {synonym:true,word:"hopeless",meaning:"望みのない",breakdown:"望みが見えないようす。despair はその気持ちを指す名詞"},
     {synonym:true,word:"misery",meaning:"みじめさ",breakdown:"つらく苦しい状態。despair は望みを失った気持ちを指す"}]},

  {id:968,word:"emotion",partOfSpeech:"名詞",meaning:"感情",
   meanings:["名|感情，情緒"],
   pronunciation:"/ɪˈmoʊʃn/",part:97,
   example:"She could not hide her emotion during the farewell speech.",
   exampleJa:"彼女は別れのスピーチの間、感情を隠せなかった。",
   example2:"Music often brings strong emotion to the listener.",
   exampleJa2:"音楽はしばしば、聞く人に強い感情をもたらす。",
   etymologyProcess:"e（外へ）＋ mot（動かす）＋ ion（名詞）→ 心が外へ動き出すと…？",
   etymologyConclusion:"e（外へ）＋ mot（動かす）＋ ion（名詞）→ 心が外へ動き出して表に現れるもの＝感情",
   relatedWords:[
     {word:"motion",meaning:"動き",breakdown:"mot（動かす）＋ ion（名詞）→ 動いているということ"},
     {word:"motor",meaning:"モーター",breakdown:"mot（動かす）＋ or（もの）→ 物を動かすための装置"},
     {word:"remove",meaning:"取り除く",breakdown:"re（後ろへ）＋ mov（動かす）→ 元の場所から動かしてどける"},
     {word:"emotional",meaning:"感情的な",breakdown:"e（外へ）＋ mot（動かす）＋ al（形容詞）→ 心が外へ動きやすい"}]},

  {id:969,word:"sympathy",partOfSpeech:"名詞",meaning:"同情，思いやり",
   meanings:["名|同情，思いやり"],
   pronunciation:"/ˈsɪmpəθi/",part:97,
   example:"She showed deep sympathy for the injured young player.",
   exampleJa:"彼女はけがをした若い選手に深い同情を示した。",
   example2:"Our letters of sympathy reached the family very quickly.",
   exampleJa2:"私たちの同情の手紙は、とても早く家族に届いた。",
   etymologyProcess:"sym（共に）＋ path（感じる）→ 相手の痛みを共に感じると…？",
   etymologyConclusion:"sym（共に）＋ path（感じる）→ 相手の痛みを自分も共に感じること＝同情",
   relatedWords:[
     {word:"sympathetic",meaning:"同情的な",breakdown:"sym（共に）＋ path（感じる）＋ ic（形容詞）→ 共に感じる心がある"},
     {word:"pathetic",meaning:"哀れな",breakdown:"path（感じる）＋ etic（〜の）→ 胸に痛みを感じさせる"},
     {word:"symbol",meaning:"象徴，記号",breakdown:"sym（共に）＋ bol（投げる）→ 二つを重ね合わせて示すしるし"},
     {synonym:true,word:"pity",meaning:"あわれみ",breakdown:"かわいそうだと思う気持ち。sympathy は相手と同じ気持ちになること"}]},

  {id:970,word:"shame",partOfSpeech:"名詞",meaning:"恥；残念なこと",
   meanings:["名|恥，恥ずかしさ","名|（It is a shame で）残念なこと"],
   pronunciation:"/ʃeɪm/",part:97,
   example:"He felt great shame after breaking his important promise.",
   exampleJa:"大切な約束を破った後、彼は大きな恥を感じた。",
   example2:"It is a shame that you cannot join us tomorrow.",
   exampleJa2:"あなたが明日参加できないのは残念なことだ。",
   etymologyProcess:"shame（恥）→ 人目から身を隠したくなる気持ちは…？",
   etymologyConclusion:"shame（恥）→ 人に見られたくなくて身を隠したくなる気持ち＝恥",
   hook:"It is a shame that ... は「恥」ではなく「残念だ」。身を縮める感じが芯。",
   relatedWords:[
     {word:"ashamed",meaning:"恥じている",breakdown:"shame（恥）→ 恥じて顔を上げられないでいる"},
     {word:"shameful",meaning:"恥ずべき",breakdown:"shame（恥）＋ ful（満ちた）→ 恥で満ちている"},
     {word:"shameless",meaning:"恥知らずな",breakdown:"shame（恥）＋ less（ない）→ 恥じる気持ちがまるでない"},
     {synonym:true,word:"pity",meaning:"残念なこと",breakdown:"「残念」の意味では It is a pity that ... とほぼ同じ使い方をする"}]},

  {id:971,word:"confidence",partOfSpeech:"名詞",meaning:"自信",
   meanings:["名|自信","名|信頼"],
   pronunciation:"/ˈkɑːnfɪdəns/",part:98,
   example:"She spoke with great confidence in front of everyone.",
   exampleJa:"彼女はみんなの前で、大きな自信を持って話した。",
   example2:"Daily practice slowly built his confidence in playing the piano.",
   exampleJa2:"毎日の練習が、ピアノを弾くことへの彼の自信を少しずつ育てた。",
   etymologyProcess:"con（すっかり）＋ fid（信じる）→ 自分をすっかり信じきっていると…？",
   etymologyConclusion:"con（すっかり）＋ fid（信じる）→ 自分の力をすっかり信じきっている気持ち＝自信",
   relatedWords:[
     {word:"confident",meaning:"自信のある",breakdown:"con（すっかり）＋ fid（信じる）＋ ent（〜している）→ すっかり信じきっている"},
     {word:"faith",meaning:"信仰，信頼",breakdown:"fid（信じる）→ 疑わずにまっすぐ寄せる心"},
     {word:"fidelity",meaning:"忠実さ",breakdown:"fid（信じる）＋ ity（名詞）→ 信じられて裏切らないこと"},
     {synonym:true,word:"trust",meaning:"信頼",breakdown:"相手を信じて任せること。confidence は自分を信じる力も指す"}]},

  {id:972,word:"courage",partOfSpeech:"名詞",meaning:"勇気",
   meanings:["名|勇気"],
   pronunciation:"/ˈkɜːrɪdʒ/",part:98,
   example:"It takes real courage to admit your own mistakes.",
   exampleJa:"自分の失敗を認めるには、本当の勇気がいる。",
   example2:"She found the courage to speak in front of everyone.",
   exampleJa2:"彼女はみんなの前で話す勇気を出した。",
   etymologyProcess:"cour（心）＋ age（名詞）→ 恐れに負けず前へ出ようとする心の力は…？",
   etymologyConclusion:"cour（心）＋ age（名詞）→ 恐れに負けずに前へ出ようとする心の力＝勇気",
   relatedWords:[
     {word:"encourage",meaning:"励ます",breakdown:"en（中に）＋ cour（心）→ 相手の中に心を入れてやる"},
     {word:"discourage",meaning:"やる気をそぐ",breakdown:"dis（否定）＋ cour（心）→ 心をくじいてしまう"},
     {word:"cordial",meaning:"心からの",breakdown:"cord（心）＋ al（形容詞）→ 心の底から出ている"},
     {synonym:true,word:"brave",meaning:"勇敢な",breakdown:"恐れずに立ち向かうようす。courage はその力そのものを指す名詞"}]},

  {id:973,word:"passion",partOfSpeech:"名詞",meaning:"情熱",
   meanings:["名|情熱，熱愛"],
   pronunciation:"/ˈpæʃn/",part:98,
   example:"She has a real passion for classical piano music.",
   exampleJa:"彼女はクラシックのピアノ音楽に本当の情熱を持っている。",
   example2:"His passion for running kept him going every single day.",
   exampleJa2:"走ることへの情熱が、彼を毎日続けさせた。",
   etymologyProcess:"passi（耐える）＋ ion（名詞）→ 胸を焼くほどの激しい思いは…？",
   etymologyConclusion:"passi（耐える）＋ ion（名詞）→ 胸が焼けるほどの苦しみをも伴う強い思い＝情熱",
   why:"【なぜ】ラテン語 pati は「耐える・苦しむ」。キリストの受難を the Passion と言うのはこの意味です。そこから「胸を焼く激しい思い」という面が強まり、「情熱」「熱愛」へ広がりました。\n【つながり】patient（じっと耐える＝忍耐強い）、passive（されるがまま＝受動的な）も同じ家族です。",
   relatedWords:[
     {word:"patient",meaning:"忍耐強い；患者",breakdown:"pat（耐える）＋ ent（〜している）→ じっと耐えている"},
     {word:"passive",meaning:"受動的な",breakdown:"passi（耐える）＋ ive（形容詞）→ されるがままでいる"},
     {word:"passionate",meaning:"情熱的な",breakdown:"passi（耐える）＋ ate（形容詞）→ 胸を焼く思いに満ちている"},
     {synonym:true,word:"enthusiasm",meaning:"熱意",breakdown:"わき立つ意気込み。passion は身を焦がすほどの強い思い"}]},

  {id:974,word:"sorrow",partOfSpeech:"名詞",meaning:"悲しみ，嘆き",
   meanings:["名|（深く長い）悲しみ，嘆き"],
   pronunciation:"/ˈsɑːroʊ/",part:98,
   example:"Deep sorrow filled her heart after the sad news.",
   exampleJa:"その悲しい知らせの後、深い悲しみが彼女の心を満たした。",
   example2:"He hid his sorrow behind a very quiet smile.",
   exampleJa2:"彼はとても静かな笑顔の後ろに、悲しみを隠した。",
   etymologyProcess:"sorrow（嘆き）→ 失ったものを思って胸が重く沈むと…？",
   etymologyConclusion:"sorrow（嘆き）→ 失ったものを思って胸が重く沈みこむ気持ち＝悲しみ",
   hook:"sorry と似ているが別語源。sorry は sore（痛む）のほうから来た語。",
   relatedWords:[
     {synonym:true,word:"grief",meaning:"深い悲しみ",breakdown:"死などによる強い悲嘆。sorrow は長く続く沈んだ悲しみ"},
     {synonym:true,word:"sadness",meaning:"悲しさ",breakdown:"ふつうの悲しい気持ち。sorrow はもっと重く、書き言葉で使う"},
     {synonym:true,word:"regret",meaning:"後悔",breakdown:"してしまったことを悔やむ気持ち。sorrow は失ったことの悲しみ"},
     {synonym:true,word:"mourn",meaning:"嘆く",breakdown:"人の死を悲しむ行い。sorrow はその悲しみそのものを指す名詞"}]},

  {id:975,word:"ignore",partOfSpeech:"他動詞",meaning:"無視する",
   meanings:["他|無視する，知らないふりをする"],
   pronunciation:"/ɪɡˈnɔːr/",part:98,
   example:"Please do not ignore the warning on this sign.",
   exampleJa:"この標識の警告を無視しないでください。",
   example2:"He ignored my message for three whole days.",
   exampleJa2:"彼は丸3日間、私のメッセージを無視した。",
   etymologyProcess:"in（否定）＋ gnor（知る）→ 知らないふりをして取り合わないと…？",
   etymologyConclusion:"in（否定）＋ gnor（知る）→ 知らないことにして、わざと取り合わない＝無視する",
   relatedWords:[
     {synonym:true,word:"know",meaning:"知る",breakdown:"ラテン語の gnor とは遠い親戚。もとは同じ「知る」だった"},
     {word:"recognize",meaning:"見分ける，認める",breakdown:"re（再び）＋ co（共に）＋ gn（知る）→ 前に知ったものだと分かる"},
     {word:"ignorant",meaning:"無知の",breakdown:"in（否定）＋ gnor（知る）＋ ant（〜な）→ 知らないままでいる"},
     {synonym:true,word:"neglect",meaning:"おろそかにする",breakdown:"すべきことを放っておく。ignore は気づいてわざと取り合わない"}]},

  {id:976,word:"offend",partOfSpeech:"他動詞",meaning:"怒らせる，気を悪くさせる",
   meanings:["他|怒らせる，気を悪くさせる","自|（against ～）（～に）違反する"],
   pronunciation:"/əˈfend/",part:98,
   example:"His careless words offended several people at the meeting.",
   exampleJa:"彼の不注意な言葉は、会議で何人かを怒らせた。",
   example2:"I really did not mean to offend your best friend.",
   exampleJa2:"あなたの親友を怒らせるつもりは本当になかった。",
   etymologyProcess:"of（相手のほうへ）＋ fend（打つ）→ 相手の気持ちを打ちつけると…？",
   etymologyConclusion:"of（相手のほうへ）＋ fend（打つ）→ 相手のほうへ打ちつけて気持ちを傷つける＝怒らせる",
   relatedWords:[
     {word:"defend",meaning:"守る",breakdown:"de（離して）＋ fend（打つ）→ 打って敵を遠ざける"},
     {word:"offense",meaning:"違反；気分を害すること",breakdown:"of（相手のほうへ）＋ fend（打つ）→ 相手を打って傷つけること"},
     {word:"offensive",meaning:"不快な；攻撃的な",breakdown:"of（相手のほうへ）＋ fend（打つ）＋ ive（形容詞）→ 打ってくるような"},
     {synonym:true,word:"insult",meaning:"侮辱する",breakdown:"はっきり見下すこと。offend は結果として気分を害することも含む"}]},

  {id:977,word:"depress",partOfSpeech:"他動詞",meaning:"憂うつにさせる",
   meanings:["他|憂うつにさせる","他|（景気など）を落ち込ませる"],
   pronunciation:"/dɪˈpres/",part:98,
   example:"The long rainy season depresses many people in Japan.",
   exampleJa:"長い梅雨は、日本の多くの人を憂うつにさせる。",
   example2:"He was depressed by the news of the factory closure.",
   exampleJa2:"工場閉鎖の知らせに、彼は憂うつになった。",
   etymologyProcess:"de（下へ）＋ press（押す）→ 気持ちを下へ押しつけて沈ませると…？",
   etymologyConclusion:"de（下へ）＋ press（押す）→ 気持ちを下へ押しつけて沈ませてしまう＝憂うつにさせる",
   relatedWords:[
     {word:"press",meaning:"押す",breakdown:"press（押す）→ 上から力をかけて押しつける"},
     {word:"impress",meaning:"感銘を与える",breakdown:"im（中へ）＋ press（押す）→ 心の中に強く押し込む"},
     {word:"express",meaning:"表現する",breakdown:"ex（外へ）＋ press（押す）→ 思いを外へ押し出す"},
     {word:"pressure",meaning:"圧力",breakdown:"press（押す）＋ ure（名詞）→ 押しつけてくる力"}]},

  {id:978,word:"owe",partOfSpeech:"他動詞",meaning:"借りがある；～のおかげだ",
   meanings:["他|（金などの）借りがある","他|（owe A to B で）A は B のおかげだ"],
   pronunciation:"/oʊ/",part:98,
   example:"I still owe my older brother two thousand yen.",
   exampleJa:"私はまだ兄に2千円の借りがある。",
   example2:"She owes her success to years of quiet daily effort.",
   exampleJa2:"彼女の成功は、長年の地道な毎日の努力のおかげだ。",
   etymologyProcess:"owe（自分のものとして持つ）→ 返すべきものを相手から預かったままだと…？",
   etymologyConclusion:"owe（自分のものとして持つ）→ 返すべきものを相手のものとして持ったままでいる＝借りがある",
   why:"【なぜ】古英語 āgan はもともと「持っている」でした。相手のものを自分の手元に持っている状態が、「まだ返していない＝借りがある」へ移りました。\n【つながり】own（自分のものにする）、ought（āgan の古い過去形）が同じ家族です。",
   hook:"own（自分のものにする）と同じ語から。owe A to B の形で覚える。",
   relatedWords:[
     {word:"own",meaning:"自分の；所有する",breakdown:"owe（自分のものとして持つ）→ 自分のものとして手元に持っている"},
     {word:"ought",meaning:"～すべきだ",breakdown:"owe（自分のものとして持つ）→ owe の古い過去形。果たすべき負いがある"},
     {synonym:true,word:"borrow",meaning:"借りる",breakdown:"借りる行いそのもの。owe は借りが残っている状態を指す"},
     {synonym:true,word:"debt",meaning:"借金",breakdown:"返すべきお金。owe はそれを負っている状態を表す動詞"}]},

  {id:979,word:"fear",partOfSpeech:"名詞",meaning:"恐怖，恐れ",
   meanings:["名|恐怖，恐れ","他|恐れる"],
   pronunciation:"/fɪr/",part:98,
   example:"A sudden fear filled her heart in the dark forest.",
   exampleJa:"暗い森の中で、突然の恐怖が彼女の心を満たした。",
   example2:"Many people fear speaking in front of a large crowd.",
   exampleJa2:"多くの人は、大勢の前で話すことを恐れる。",
   etymologyProcess:"fear（突然の危難）→ 危ないものを前にして身がすくむと…？",
   etymologyConclusion:"fear（突然の危難）→ 危ないものを前にして身がすくむ気持ち＝恐怖",
   why:"【なぜ】古英語の fǣr は「突然の危難」そのものを指しました。危難に出会ったときの気持ちのほうへ意味が移り、「恐怖」になりました。\n【つながり】fearful（恐れに満ちた）、fearless（恐れ知らずの）。ドイツ語の Gefahr（危険）は、今も昔の意味を残しています。",
   relatedWords:[
     {word:"fearful",meaning:"恐ろしい；おびえた",breakdown:"fear（突然の危難）＋ ful（満ちた）→ 恐れで満ちている"},
     {word:"fearless",meaning:"恐れ知らずの",breakdown:"fear（突然の危難）＋ less（ない）→ 恐れる気持ちがない"},
     {synonym:true,word:"terror",meaning:"恐怖",breakdown:"身も凍るような激しい恐怖。fear はふつうの恐れ全般を指す"},
     {synonym:true,word:"anxiety",meaning:"不安",breakdown:"先を気に病む気持ち。fear ははっきりした対象への恐れ"}]},

  {id:980,word:"method",partOfSpeech:"名詞",meaning:"（順序立った）方法",
   meanings:["名|（順序立った）方法，やり方"],
   pronunciation:"/ˈmeθəd/",part:98,
   example:"This method works well for learning new English words.",
   exampleJa:"この方法は、新しい英単語を覚えるのによく効く。",
   example2:"Scientists tested a new method of cleaning sea water.",
   exampleJa2:"科学者たちは、海水をきれいにする新しい方法を試した。",
   etymologyProcess:"meta（後を追って）＋ hod（道）→ 目的まで順に追っていく道すじは…？",
   etymologyConclusion:"meta（後を追って）＋ hod（道）→ 目的まで順に追っていく決まった道すじ＝方法",
   relatedWords:[
     {word:"methodical",meaning:"きちんと順序立った",breakdown:"meta（後を追って）＋ hod（道）＋ al（形容詞）→ 決まった道すじをたどる"},
     {synonym:true,word:"way",meaning:"やり方，方法",breakdown:"ふつうの言い方。method は順序立った決まったやり方を指す"},
     {synonym:true,word:"system",meaning:"体系，仕組み",breakdown:"組み合わさった全体。method はそこに至る手順を指す"},
     {synonym:true,word:"approach",meaning:"取り組み方",breakdown:"近づき方・考え方。method は具体的な手順のほうを指す"}]},

  {id:981,word:"medium",partOfSpeech:"名詞",meaning:"媒体；中くらいのもの",
   meanings:["名|媒体，伝える手だて","形|中くらいの"],
   pronunciation:"/ˈmiːdiəm/",part:99,
   example:"Television is still a powerful medium for advertising.",
   exampleJa:"テレビは今も広告のための強力な媒体だ。",
   example2:"Social media has become the main medium for young people.",
   exampleJa2:"SNSは若い人にとって、主な媒体になった。",
   etymologyProcess:"medi（中間）→ 送り手と受け手の間に立って伝えるものは…？",
   etymologyConclusion:"medi（中間）→ 送り手と受け手の中間に立って伝えるもの＝媒体",
   relatedWords:[
     {word:"middle",meaning:"真ん中",breakdown:"middle（中間）→ 両端から等しく離れたところ"},
     {word:"immediately",meaning:"すぐに",breakdown:"im（否定）＋ medi（中間）→ 間に何も挟まずに"},
     {word:"media",meaning:"メディア，報道機関",breakdown:"medi（中間）→ 情報を伝える媒体の複数形"},
     {word:"means",meaning:"手段",breakdown:"medi（中間）→ 目的と自分の間に立って橋渡しするもの"}]},

  {id:982,word:"means",partOfSpeech:"名詞",meaning:"手段，手だて",
   meanings:["名|手段，手だて","名|（複数扱いで）財力"],
   pronunciation:"/miːnz/",part:99,
   example:"Email is a quick means of sending important news.",
   exampleJa:"電子メールは、大切な知らせを送る素早い手段だ。",
   example2:"They found a new means to reduce plastic waste.",
   exampleJa2:"彼らはプラスチックごみを減らす新しい手段を見つけた。",
   etymologyProcess:"medi（中間）→ 目的と自分の間に立つものは…？",
   etymologyConclusion:"medi（中間）→ 目的と自分の中間に立って橋渡ししてくれるもの＝手段",
   hook:"by means of ～（～によって）で覚える。単数でも複数でも s が付く。",
   why:"【なぜ】この means は「意味する mean」ではなく、「中ほどの」という別の mean から来ています。目的と自分のあいだ（なかほど）に立つものが「手段」です。\n【つながり】medium（媒体）や middle（真ん中）と発想が同じ。by means of ～（～によって）の形でよく使い、単数でも s が付きます。",
   relatedWords:[
     {word:"medium",meaning:"媒体",breakdown:"medi（中間）→ 送り手と受け手の間に立って伝えるもの"},
     {word:"middle",meaning:"真ん中",breakdown:"middle（中間）→ 両端から等しく離れたところ"},
     {synonym:true,word:"method",meaning:"方法",breakdown:"順序立った手順。means は目的に届くための道具や手だてを指す"},
     {synonym:true,word:"way",meaning:"やり方",breakdown:"広く「やり方」。means は by means of の形で手だてを表す"}]},

  {id:983,word:"extent",partOfSpeech:"名詞",meaning:"程度，広がり",
   meanings:["名|程度，広がり","名|範囲"],
   pronunciation:"/ɪkˈstent/",part:99,
   example:"To some extent I agree with your new opinion.",
   exampleJa:"ある程度までは、私はあなたの新しい意見に賛成だ。",
   example2:"Nobody knew the full extent of the storm damage.",
   exampleJa2:"誰も、その嵐の被害の全体の程度を知らなかった。",
   etymologyProcess:"ex（外へ）＋ tend（伸ばす）→ どこまで伸び広がっているかを測ると…？",
   etymologyConclusion:"ex（外へ）＋ tend（伸ばす）→ 外へどこまで伸び広がっているかという幅＝程度",
   relatedWords:[
     {word:"extend",meaning:"伸ばす，広げる",breakdown:"ex（外へ）＋ tend（伸ばす）→ 外へ向けて伸ばしていく"},
     {word:"tend",meaning:"傾向がある",breakdown:"tend（伸ばす）→ 心がそちらへ伸びていく"},
     {word:"attend",meaning:"出席する",breakdown:"ad（〜へ）＋ tend（伸ばす）→ 心をそちらへ伸ばして出向く"},
     {word:"extensive",meaning:"広範囲の",breakdown:"ex（外へ）＋ tend（伸ばす）＋ ive（形容詞）→ 外へ大きく広がった"}]},

  {id:984,word:"extremely",partOfSpeech:"副詞",meaning:"極度に，きわめて",
   meanings:["副|極度に，きわめて"],
   pronunciation:"/ɪkˈstriːmli/",part:99,
   example:"The final test was extremely difficult for most students.",
   exampleJa:"期末テストは、ほとんどの生徒にとって極度に難しかった。",
   example2:"She was extremely surprised by the sudden bad news.",
   exampleJa2:"彼女はその突然の悪い知らせに、極度に驚いた。",
   etymologyProcess:"extrem（いちばん外）＋ ly（副詞）→ 程度のいちばん外の端まで行くと…？",
   etymologyConclusion:"extrem（いちばん外）＋ ly（副詞）→ 程度のいちばん外の端まで振り切れるほど＝極度に",
   relatedWords:[
     {word:"extreme",meaning:"極端な",breakdown:"extrem（いちばん外）→ 端のいちばん外側にある"},
     {word:"extra",meaning:"余分の",breakdown:"extra（範囲の外へ）→ 決められた範囲の外にある分"},
     {synonym:true,word:"utterly",meaning:"まったく",breakdown:"すっかりそうであること。extremely は端まで振り切れた程度を表す"},
     {synonym:true,word:"very",meaning:"とても",breakdown:"ふつうの強め。extremely は端まで振り切れた強さを表す"}]},

  {id:985,word:"total",partOfSpeech:"形容詞",meaning:"全体の，合計の",
   meanings:["形|全体の，合計の","名|合計"],
   pronunciation:"/ˈtoʊtl/",part:99,
   example:"The total cost of the school trip was quite high.",
   exampleJa:"修学旅行の全体の費用は、かなり高かった。",
   example2:"Our team scored a total of twenty points yesterday.",
   exampleJa2:"私たちのチームは昨日、合計20点を取った。",
   etymologyProcess:"tot（すべて）＋ al（形容詞）→ 欠けなく全部を合わせると…？",
   etymologyConclusion:"tot（すべて）＋ al（形容詞）→ 欠けることなく全部を合わせた＝全体の",
   relatedWords:[
     {word:"totally",meaning:"まったく，完全に",breakdown:"tot（すべて）＋ ly（副詞）→ 全部そろって欠けがなく"},
     {word:"subtotal",meaning:"小計",breakdown:"sub（下で）＋ tot（すべて）→ 全体の下にある部分ごとの合計"},
     {synonym:true,word:"whole",meaning:"全体の",breakdown:"欠けのないひとまとまり。total は数を足し合わせた全部を指す"},
     {synonym:true,word:"entire",meaning:"すべての",breakdown:"手つかずでまるごと。total は合計としての全体を指す"}]},

  {id:986,word:"largely",partOfSpeech:"副詞",meaning:"大部分は，主として",
   meanings:["副|大部分は，主として"],
   pronunciation:"/ˈlɑːrdʒli/",part:99,
   example:"The plan largely depends on the weather next week.",
   exampleJa:"その計画は大部分が、来週の天気に左右される。",
   example2:"Our team largely ignored the coach's advice yesterday.",
   exampleJa2:"私たちのチームは昨日、監督の助言を大部分無視した。",
   etymologyProcess:"larg（たっぷりした）＋ ly（副詞）→ 大きな部分を占めているなら…？",
   etymologyConclusion:"larg（たっぷりした）＋ ly（副詞）→ 全体の大きな部分を占めるほどに＝大部分は",
   relatedWords:[
     {word:"large",meaning:"大きい",breakdown:"larg（たっぷりした）→ 場所や量がたっぷりある"},
     {word:"enlarge",meaning:"拡大する",breakdown:"en（〜にする）＋ larg（たっぷりした）→ もっと大きくする"},
     {synonym:true,word:"mostly",meaning:"たいてい，主に",breakdown:"ほとんどの場合。largely は割合として大部分を占めることを言う"},
     {synonym:true,word:"mainly",meaning:"主に",breakdown:"いちばんの理由として。largely は程度の大きさに重きがある"}]},

  {id:987,word:"moderate",partOfSpeech:"形容詞",meaning:"適度な，ほどよい",
   meanings:["形|適度な，ほどよい","形|穏健な"],
   pronunciation:"/ˈmɑːdərət/",part:99,
   example:"Moderate exercise every day keeps your body quite healthy.",
   exampleJa:"毎日の適度な運動は、体をかなり健康に保つ。",
   example2:"The price was moderate for such a good meal.",
   exampleJa2:"あれほどよい食事にしては、値段は適度だった。",
   etymologyProcess:"modus（ほどよさ）＋ ate（形容詞）→ ほどよい量に収まっていると…？",
   etymologyConclusion:"modus（ほどよさ）＋ ate（形容詞）→ ほどよい量にきちんと収まっている＝適度な",
   relatedWords:[
     {word:"model",meaning:"模型；手本",breakdown:"modus（ほどよさ）＋ el（小さい）→ 寸法どおりに作った小さな形"},
     {word:"modest",meaning:"控えめな",breakdown:"modus（ほどよさ）→ ほどよさを越えず控えめでいる"},
     {word:"modify",meaning:"修正する",breakdown:"modus（ほどよさ）＋ fy（する）→ ほどよい形に直す"},
     {synonym:true,word:"reasonable",meaning:"ほどよい，手ごろな",breakdown:"理屈に合ったほどよさ。moderate は量や程度のほどよさを言う"}]},

  {id:988,word:"somewhat",partOfSpeech:"副詞",meaning:"いくぶん，やや",
   meanings:["副|いくぶん，やや"],
   pronunciation:"/ˈsʌmwʌt/",part:99,
   example:"The situation has improved somewhat since last month.",
   exampleJa:"状況は先月から、いくぶん改善した。",
   example2:"He looked somewhat tired after the long train journey.",
   exampleJa2:"長い列車の旅の後、彼はいくぶん疲れて見えた。",
   etymologyProcess:"somewhat（いくらかは）→ 全部ではなく、いくらかの程度までなら…？",
   etymologyConclusion:"somewhat（いくらかは）→ 全部ではないが、いくらかの程度までは＝いくぶん",
   hook:"some（いくらか）＋ what（何）が固まった語。「いくらかは」と覚える。",
   relatedWords:[
     {synonym:true,word:"slightly",meaning:"わずかに",breakdown:"ごく少しだけ。somewhat はそれより少し幅のある「いくぶん」"},
     {synonym:true,word:"rather",meaning:"かなり，むしろ",breakdown:"思ったより強い程度。somewhat は控えめな程度を表す"},
     {synonym:true,word:"quite",meaning:"かなり",breakdown:"はっきり強い程度。somewhat は「少しは」と弱める語"},
     {synonym:true,word:"partly",meaning:"部分的に",breakdown:"一部分だけ。somewhat は程度が少しであることを言う"}]},

  {id:989,word:"subtle",partOfSpeech:"形容詞",meaning:"かすかな，微妙な",
   meanings:["形|かすかな，微妙な","形|（考えが）巧みな"],
   pronunciation:"/ˈsʌtl/",part:99,
   example:"There is a subtle difference between these two words.",
   exampleJa:"この2つの語の間には、かすかな違いがある。",
   example2:"She noticed a subtle change in his quiet voice.",
   exampleJa2:"彼女は、彼の静かな声のかすかな変化に気づいた。",
   etymologyProcess:"sub（下で）＋ til（織り糸）→ 細かく織られて目で追いにくいと…？",
   etymologyConclusion:"sub（下で）＋ til（織り糸）→ 細かく織られていて目で追いにくい＝かすかな",
   why:"【なぜ】ラテン語 subtilis は「細く織られた」。sub（下で）＋ tela（織り糸）で、織り目が細かすぎて目で追えない布のことでした。そこから「見分けがつかないほど細やかな」＝かすかな・微妙な、になりました。\n【つながり】発音は b を読まずに /ˈsʌtl/。tela はもとをたどれば texere（織る）から。textile（織物）と大もとが同じです。",
   relatedWords:[
     {word:"textile",meaning:"織物",breakdown:"tex（織る）→ 糸を細かく織って作った布"},
     {synonym:true,word:"slight",meaning:"わずかな",breakdown:"ごく小さいこと。subtle は細やかで気づきにくいことを言う"},
     {synonym:true,word:"delicate",meaning:"繊細な",breakdown:"壊れやすく細やか。subtle は見分けにくい細かさを指す"},
     {synonym:true,word:"faint",meaning:"かすかな",breakdown:"ぼんやり弱いこと。subtle は細かくて気づきにくいこと"}]},

  {id:990,word:"possibly",partOfSpeech:"副詞",meaning:"ひょっとすると",
   meanings:["副|ひょっとすると，もしかしたら"],
   pronunciation:"/ˈpɑːsəbli/",part:99,
   example:"He will possibly arrive before the concert actually begins.",
   exampleJa:"彼はひょっとすると、コンサートが実際に始まる前に着くだろう。",
   example2:"Possibly the train was delayed by the heavy snow.",
   exampleJa2:"ひょっとすると、電車は大雪で遅れたのかもしれない。",
   etymologyProcess:"poss（できる）＋ ly（副詞）→ 起こることもありうると言うなら…？",
   etymologyConclusion:"poss（できる）＋ ly（副詞）→ 起こることもありうるという弱い見込みで＝ひょっとすると",
   relatedWords:[
     {word:"possible",meaning:"可能な",breakdown:"poss（できる）＋ ible（できる）→ 実現する見込みがある"},
     {word:"possibility",meaning:"可能性",breakdown:"poss（できる）＋ ity（名詞）→ できるという見込みそのもの"},
     {synonym:true,word:"perhaps",meaning:"たぶん",breakdown:"半々くらいの見込み。possibly はもっと弱い「ひょっとすると」"},
     {synonym:true,word:"maybe",meaning:"もしかすると",breakdown:"話し言葉の言い方。possibly は少し硬く、見込みも弱い"}]},

  {id:991,word:"eventually",partOfSpeech:"副詞",meaning:"最終的に，ついに",
   meanings:["副|最終的に，ついに"],
   pronunciation:"/ɪˈventʃuəli/",part:100,
   example:"He eventually finished the long report late last night.",
   exampleJa:"彼は最終的に、昨夜遅くその長い報告書を書き終えた。",
   example2:"Eventually they agreed on a plan for the school festival.",
   exampleJa2:"最終的に、彼らは文化祭の計画について意見が一致した。",
   etymologyProcess:"e（外へ）＋ vent（来る）→ いろいろあった末に結果が出てくると…？",
   etymologyConclusion:"e（外へ）＋ vent（来る）→ いろいろあった末に結果が外へ出てくる＝最終的に",
   relatedWords:[
     {word:"event",meaning:"できごと，行事",breakdown:"e（外へ）＋ vent（来る）→ 外に現れ出てきたできごと"},
     {word:"invent",meaning:"発明する",breakdown:"in（上に）＋ vent（来る）→ 探していたものに行き当たって見つけ出す"},
     {word:"prevent",meaning:"防ぐ",breakdown:"pre（先に）＋ vent（来る）→ 先回りして来させないようにする"},
     {word:"adventure",meaning:"冒険",breakdown:"ad（〜へ）＋ vent（来る）＋ ure（名詞）→ 何が来るか分からない道行き"}]},

  {id:992,word:"necessarily",partOfSpeech:"副詞",meaning:"必ずしも",
   meanings:["副|（not とともに）必ずしも～でない"],
   pronunciation:"/ˌnesəˈserəli/",part:100,
   example:"Expensive food is not necessarily better for your body.",
   exampleJa:"高い食べ物が、必ずしも体によいとは限らない。",
   example2:"Winning does not necessarily mean you played very well.",
   exampleJa2:"勝つことは、必ずしもよいプレーをしたという意味ではない。",
   etymologyProcess:"ne（否定）＋ cess（行く）→ よけて通ることができないなら…？",
   etymologyConclusion:"ne（否定）＋ cess（行く）→ よけて通ることができないほど決まって＝必ずしも",
   why:"【なぜ】ラテン語 necesse は「避けて通れない」。ne（否定）＋ cedere（退く）と考えられていますが、確かなところは分かっていません。\n【つながり】necessary（必要な）、necessity（必要性）が同じ家族。not と組むと「必ずしも〜でない」という部分否定になります。",
   relatedWords:[
     {word:"necessary",meaning:"必要な",breakdown:"ne（否定）＋ cess（行く）→ よけて通ることができない"},
     {word:"access",meaning:"接近；利用する権利",breakdown:"ac（〜へ）＋ cess（行く）→ そこへ行き着くための道"},
     {word:"process",meaning:"過程",breakdown:"pro（前へ）＋ cess（行く）→ 前へ進んでいく道のり"},
     {word:"succeed",meaning:"成功する；後を継ぐ",breakdown:"suc（すぐ後に）＋ ceed（行く）→ すぐ後について行き着く"}]},

  {id:993,word:"frankly",partOfSpeech:"副詞",meaning:"率直に（言って）",
   meanings:["副|率直に（言って）"],
   pronunciation:"/ˈfræŋkli/",part:100,
   example:"Frankly, I do not agree with that new school rule.",
   exampleJa:"率直に言って、私はその新しい校則に賛成しない。",
   example2:"She spoke frankly about her own past mistakes.",
   exampleJa2:"彼女は自分の過去の失敗について、率直に話した。",
   etymologyProcess:"frank（自由な）＋ ly（副詞）→ 遠慮の縛りなく思ったままを言うと…？",
   etymologyConclusion:"frank（自由な）＋ ly（副詞）→ 遠慮の縛りなく思ったままを言うようす＝率直に",
   why:"【なぜ】frank はもともと「フランク族の」。中世のガリアではフランク族だけが自由民だったため「自由な」の意味になり、さらに「言いたいことを遠慮なく言える」＝率直な、へ移りました。\n【つながり】国名のフランス（France）も同じ語源。franchise（営業権）は「自由に商売してよい権利」のことです。",
   relatedWords:[
     {word:"frank",meaning:"率直な",breakdown:"frank（自由な）→ 遠慮の縛りなく思ったままを言う"},
     {word:"franchise",meaning:"営業権，フランチャイズ",breakdown:"frank（自由な）＋ ise（名詞）→ 自由に商売してよい権利"},
     {synonym:true,word:"honestly",meaning:"正直に言って",breakdown:"うそをつかずに。frankly は言いにくいことも隠さず言うこと"},
     {synonym:true,word:"openly",meaning:"包み隠さず",breakdown:"公然と。frankly は相手に率直な意見を言うときに使う"}]},

  {id:994,word:"ironically",partOfSpeech:"副詞",meaning:"皮肉なことに",
   meanings:["副|皮肉なことに"],
   pronunciation:"/aɪˈrɑːnɪkli/",part:100,
   example:"Ironically, the fire station itself burned down last night.",
   exampleJa:"皮肉なことに、消防署そのものが昨夜焼け落ちた。",
   example2:"The rain stopped, ironically, just after the game ended.",
   exampleJa2:"皮肉なことに、雨は試合が終わった直後にやんだ。",
   etymologyProcess:"iron（とぼける）＋ ly（副詞）→ わざと逆のことを言うようなちぐはぐさなら…？",
   etymologyConclusion:"iron（とぼける）＋ ly（副詞）→ わざと逆のことを言うようなちぐはぐさで＝皮肉なことに",
   why:"【なぜ】ギリシャ語 eirōneia は「とぼけて言うこと」。ソクラテスがわざと知らないふりをして相手に問い返した話し方から生まれた語です。そこから「言葉と中身が逆」＝皮肉、さらに「よりによって逆の結果になる」ことにも使われるようになりました。\n【つながり】金属の iron（鉄）とはまったく別の語。irony（皮肉）、ironic（皮肉な）が同じ家族です。",
   relatedWords:[
     {word:"irony",meaning:"皮肉",breakdown:"iron（とぼける）＋ y（名詞）→ わざと逆を言う言い方"},
     {word:"ironic",meaning:"皮肉な",breakdown:"iron（とぼける）＋ ic（形容詞）→ 言葉と中身がねじれている"},
     {synonym:true,word:"sarcastic",meaning:"いやみな",breakdown:"とげのある皮肉。ironic は結果のちぐはぐさにも使う"},
     {synonym:true,word:"unexpectedly",meaning:"思いがけず",breakdown:"予想外に。ironically は「よりによって逆に」という含みがある"}]},

  {id:995,word:"moreover",partOfSpeech:"副詞",meaning:"その上，さらに",
   meanings:["副|その上，さらに"],
   pronunciation:"/mɔːrˈoʊvər/",part:100,
   example:"The room is very small. Moreover, it has no window.",
   exampleJa:"その部屋はとても狭い。その上、窓がない。",
   example2:"He speaks three languages and, moreover, plays the violin.",
   exampleJa2:"彼は3か国語を話し、その上、バイオリンも弾く。",
   etymologyProcess:"more（もっと多く）＋ over（越えて）→ 今言ったことを越えて付け加えると…？",
   etymologyConclusion:"more（もっと多く）＋ over（越えて）→ 今言ったことを越えて、さらに付け加えて＝その上",
   relatedWords:[
     {word:"more",meaning:"もっと多くの",breakdown:"more（もっと多く）→ 今より量や数が増えている"},
     {word:"overcome",meaning:"打ち勝つ",breakdown:"over（越えて）＋ come（来る）→ 上を越えて乗りこえる"},
     {word:"overlook",meaning:"見落とす；見渡す",breakdown:"over（越えて）＋ look（見る）→ 上を越して見てしまう"},
     {synonym:true,word:"besides",meaning:"その上，加えて",breakdown:"話し言葉寄り。moreover は書き言葉で理由を重ねるときに使う"}]},

  {id:996,word:"otherwise",partOfSpeech:"副詞",meaning:"さもなければ",
   meanings:["副|さもなければ","副|その他の点では"],
   pronunciation:"/ˈʌðərwaɪz/",part:100,
   example:"Leave now; otherwise you will miss the last train.",
   exampleJa:"今出なさい。さもなければ終電に乗り遅れます。",
   example2:"The film was long, but otherwise it was excellent.",
   exampleJa2:"その映画は長かったが、その他の点ではすばらしかった。",
   etymologyProcess:"other（別の）＋ wise（やり方）→ 別のやり方をとった場合には…？",
   etymologyConclusion:"other（別の）＋ wise（やり方）→ 別のやり方をとった場合には＝さもなければ",
   relatedWords:[
     {word:"other",meaning:"別の，他の",breakdown:"other（別の）→ これとは違うもう一方"},
     {synonym:true,word:"wise",meaning:"賢い",breakdown:"-wise（やり方）と同じ根から。物事のやり方をよく知っていること"},
     {word:"likewise",meaning:"同様に",breakdown:"like（同じ形の）＋ wise（やり方）→ それと同じやり方で"},
     {synonym:true,word:"else",meaning:"ほかに",breakdown:"他のもの。otherwise は「そうでなければ」と条件をつなぐ"}]},

  {id:997,word:"regardless",partOfSpeech:"副詞",meaning:"（of ～）～に関係なく",
   meanings:["副|（of ～）～に関係なく，かまわずに"],
   pronunciation:"/rɪˈɡɑːrdləs/",part:100,
   example:"The game will start regardless of the weather tomorrow.",
   exampleJa:"試合は明日の天気に関係なく始まる。",
   example2:"Everyone can join regardless of age or past experience.",
   exampleJa2:"年齢や過去の経験に関係なく、誰でも参加できる。",
   etymologyProcess:"re（じっと）＋ gard（見張る）＋ less（ない）→ そちらを気にかけずに進むと…？",
   etymologyConclusion:"re（じっと）＋ gard（見張る）＋ less（ない）→ そちらを気にかけずに進んで＝～に関係なく",
   relatedWords:[
     {word:"regard",meaning:"みなす；敬意",breakdown:"re（じっと）＋ gard（見張る）→ じっと見つめて心にとめる"},
     {word:"guard",meaning:"守る",breakdown:"gard（見張る）→ 目を配って危険から守る"},
     {word:"reward",meaning:"報酬",breakdown:"re（戻す）＋ ward（見張る）→ よい働きを見てその分を返す"},
     {synonym:true,word:"despite",meaning:"～にもかかわらず",breakdown:"前置詞。regardless は of を伴って「〜に関係なく」"}]},

  {id:998,word:"worth",partOfSpeech:"形容詞",meaning:"～の価値がある",
   meanings:["形|～の価値がある","名|価値"],
   pronunciation:"/wɜːrθ/",part:100,
   example:"This old book is worth more than you think.",
   exampleJa:"この古い本は、あなたが思うより価値がある。",
   example2:"The long climb was worth the beautiful mountain view.",
   exampleJa2:"長い登りは、その美しい山の眺めの価値があった。",
   etymologyProcess:"worth（値打ち）→ それだけの値打ちに見合っているなら…？",
   etymologyConclusion:"worth（値打ち）→ それだけの値打ちに見合うものを持っている＝～の価値がある",
   hook:"be worth ～ing（～する価値がある）で覚える。後ろは名詞か動名詞。",
   relatedWords:[
     {word:"worthy",meaning:"値する，立派な",breakdown:"worth（値打ち）＋ y（形容詞）→ 値打ちにふさわしい"},
     {word:"worthless",meaning:"価値のない",breakdown:"worth（値打ち）＋ less（ない）→ 値打ちがまるでない"},
     {synonym:true,word:"valuable",meaning:"価値のある",breakdown:"高い値打ちがある。worth は「〜の価値がある」と量をそえて使う"},
     {synonym:true,word:"deserve",meaning:"値する",breakdown:"受けるに足ること。worth は be worth ～ing の形でよく使う"}]},

  {id:999,word:"according to",partOfSpeech:"熟語",meaning:"～によれば",
   meanings:["熟|～によれば","熟|～に従って"],
   pronunciation:"/əˈkɔːrdɪŋ tuː/",part:100,
   example:"According to the news, the typhoon will come tomorrow.",
   exampleJa:"ニュースによれば、台風は明日来る。",
   example2:"According to my teacher, this book is worth reading.",
   exampleJa2:"先生によれば、この本は読む価値がある。",
   etymologyProcess:"ad（〜へ）＋ cord（心）→ 相手の言うことに心を合わせると…？",
   etymologyConclusion:"ad（〜へ）＋ cord（心）→ 相手の言うことに心を合わせて述べると＝～によれば",
   relatedWords:[
     {word:"accord",meaning:"一致；一致する",breakdown:"ad（〜へ）＋ cord（心）→ 互いの心がぴたりと合う"},
     {word:"record",meaning:"記録する",breakdown:"re（再び）＋ cord（心）→ 心に呼び戻せるよう書き留める"},
     {word:"courage",meaning:"勇気",breakdown:"cour（心）＋ age（名詞）→ 恐れに負けず前へ出る心の力"},
     {synonym:true,word:"based on",meaning:"～に基づいて",breakdown:"よりどころにすること。according to は情報の出どころを示す"}]},

  {id:1000,word:"despite",partOfSpeech:"前置詞",meaning:"～にもかかわらず",
   meanings:["前|～にもかかわらず"],
   pronunciation:"/dɪˈspaɪt/",part:100,
   example:"Despite the heavy rain, the festival continued all day.",
   exampleJa:"激しい雨にもかかわらず、祭りは一日中続いた。",
   example2:"She kept smiling despite the terrible news that morning.",
   exampleJa2:"その朝のひどい知らせにもかかわらず、彼女は笑顔でいた。",
   etymologyProcess:"de（下へ）＋ spit（見る）→ 相手を見下ろして問題にしないと…？",
   etymologyConclusion:"de（下へ）＋ spit（見る）→ 相手を見下ろして問題にもしない＝～にもかかわらず",
   why:"【なぜ】もとの名詞 despite は「見下すこと・侮り」でした。「〜を物ともせず」という言い方から前置詞になり、「〜にもかかわらず」になりました。\n【つながり】spite（悪意）は despite が短くなった語。in spite of ～ は despite ～ とほぼ同じ意味です。",
   relatedWords:[
     {word:"spite",meaning:"悪意",breakdown:"de（下へ）＋ spit（見る）→ 相手を下に見ようとする気持ち"},
     {word:"despise",meaning:"軽蔑する",breakdown:"de（下へ）＋ spit（見る）→ 相手を下に見てさげすむ"},
     {word:"respect",meaning:"尊敬する",breakdown:"re（再び）＋ spect（見る）→ 何度も見返すほど価値を認める"},
     {synonym:true,word:"although",meaning:"～だけれども",breakdown:"節をつなぐ接続詞。despite の後ろは名詞や動名詞が来る"}]},

  {id:1001,word:"propose",partOfSpeech:"他動詞",meaning:"提案する",
   meanings:["他|提案する","自|結婚を申し込む"],
   pronunciation:"/prəˈpoʊz/",part:101,
   example:"She proposed a new plan for the school festival.",
   exampleJa:"彼女は文化祭の新しい計画を提案した。",
   example2:"I propose that we start the meeting at four.",
   exampleJa2:"会議を4時に始めることを提案します。",
   etymologyProcess:"pro（前へ）＋ pos（置く）→ 考えを相手の前に差し出して置くと…？",
   etymologyConclusion:"pro（前へ）＋ pos（置く）→ 自分の考えを相手の前に差し出して置く＝提案する",
   relatedWords:[
     {word:"oppose",meaning:"反対する",breakdown:"op（向かい合って）＋ pos（置く）→ 向かい合う位置に身を置く"},
     {word:"compose",meaning:"構成する；作曲する",breakdown:"com（共に）＋ pos（置く）→ 部品を共に置いて組み立てる"},
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ion（名詞）→ 置かれている場所"},
     {word:"purpose",meaning:"目的",breakdown:"pur（前へ）＋ pos（置く）→ 前に置いて目指すもの"}]},

  {id:1002,word:"dismiss",partOfSpeech:"他動詞",meaning:"退ける，取り合わない",
   meanings:["他|（意見など）を退ける，取り合わない","他|解散させる；解雇する"],
   pronunciation:"/dɪsˈmɪs/",part:101,
   example:"He dismissed my idea without even listening to it.",
   exampleJa:"彼は私の考えを、聞きもせずに退けた。",
   example2:"The teacher dismissed the class ten minutes early today.",
   exampleJa2:"先生は今日、10分早くクラスを解散させた。",
   etymologyProcess:"dis（離れて）＋ mis（送る）→ 向こうへ送り出して取り合わないと…？",
   etymologyConclusion:"dis（離れて）＋ mis（送る）→ 向こうへ送り出して、それ以上取り合わない＝退ける",
   relatedWords:[
     {word:"submit",meaning:"提出する",breakdown:"sub（下で）＋ mit（送る）→ 目上の人の下へ差し出す"},
     {word:"permit",meaning:"許可する",breakdown:"per（通して）＋ mit（送る）→ 通り抜けて行かせてやる"},
     {word:"mission",meaning:"任務",breakdown:"mis（送る）＋ ion（名詞）→ 送り出されて果たす役目"},
     {word:"transmit",meaning:"送り伝える",breakdown:"trans（越えて）＋ mit（送る）→ 境を越えて向こうへ送る"}]},

  {id:1003,word:"bless",partOfSpeech:"他動詞",meaning:"祝福する",
   meanings:["他|祝福する","他|（be blessed with で）～に恵まれている"],
   pronunciation:"/bles/",part:101,
   example:"The priest blessed the children before their long journey.",
   exampleJa:"神父は長い旅の前に、子どもたちを祝福した。",
   example2:"We were blessed with fine weather on sports day.",
   exampleJa2:"体育祭の日、私たちは晴天に恵まれた。",
   etymologyProcess:"bless（清める）→ 神の力で清めて幸いを願うと…？",
   etymologyConclusion:"bless（清める）→ 神の力で清め、幸いがあるようにと願う＝祝福する",
   why:"【なぜ】古英語の blētsian は「血をふりかけて清める」ことでした。もとは異教の儀式の言葉でしたが、聖書の翻訳で「神の恵みを与える」意味に使われ、「祝福する」になりました。\n【つながり】blood（血）と同じ根から出た語だと考えられています。blessing（恵み・ありがたいこと）も同じ家族です。",
   relatedWords:[
     {word:"blessing",meaning:"恵み，ありがたいこと",breakdown:"bless（清める）＋ ing（名詞）→ 清めて与えられる恵み"},
     {word:"blood",meaning:"血",breakdown:"blood（血）→ bless のもとになった「血」そのもの"},
     {synonym:true,word:"pray",meaning:"祈る",breakdown:"神に願うこと。bless は神の側から恵みを与えること"},
     {synonym:true,word:"praise",meaning:"ほめたたえる",breakdown:"よさをたたえること。bless は幸いを願って清めること"}]},

  {id:1004,word:"glory",partOfSpeech:"名詞",meaning:"栄光",
   meanings:["名|栄光，輝かしい誉れ"],
   pronunciation:"/ˈɡlɔːri/",part:101,
   example:"The team won great glory at the national championship.",
   exampleJa:"そのチームは全国大会で大きな栄光を勝ち取った。",
   example2:"He still remembers the glory of that final goal.",
   exampleJa2:"彼はいまだに、あの決勝ゴールの栄光を覚えている。",
   etymologyProcess:"glor（誉れ）＋ y（名詞）→ 大勢に認められて輝く誉れは…？",
   etymologyConclusion:"glor（誉れ）＋ y（名詞）→ 大勢に認められて輝きわたる誉れ＝栄光",
   relatedWords:[
     {word:"glorious",meaning:"輝かしい",breakdown:"glor（誉れ）＋ ous（形容詞）→ 誉れに満ちて輝いている"},
     {word:"glorify",meaning:"たたえる",breakdown:"glor（誉れ）＋ fy（する）→ 誉れを与えて輝かせる"},
     {synonym:true,word:"fame",meaning:"名声",breakdown:"広く知られること。glory は輝かしい誉れとしてたたえられること"},
     {synonym:true,word:"honor",meaning:"名誉",breakdown:"人からの敬い。glory はもっと華やかで輝かしい誉れ"}]},

  {id:1005,word:"compliment",partOfSpeech:"名詞",meaning:"褒め言葉",
   meanings:["名|褒め言葉，賛辞","他|褒める"],
   pronunciation:"/ˈkɑːmplɪmənt/",part:101,
   example:"She paid me a nice compliment about my speech.",
   exampleJa:"彼女は私のスピーチについて、うれしい褒め言葉をくれた。",
   example2:"His compliment made the shy student smile very brightly.",
   exampleJa2:"彼の褒め言葉が、内気な生徒をとても明るい笑顔にした。",
   etymologyProcess:"com（すっかり）＋ ple（満たす）→ 礼儀をすっかり満たす言葉は…？",
   etymologyConclusion:"com（すっかり）＋ ple（満たす）→ 礼儀をすっかり満たすために贈る言葉＝褒め言葉",
   why:"【なぜ】スペイン語の cumplimiento は「礼儀を果たすこと」。あいさつで相手を立てる決まり文句が、そのまま「褒め言葉」になりました。\n【つながり】complete（すっかり満たす）、supplement（下から補う）も同じ ple の家族。つづりの似た complement（補うもの）は別の語なので注意です。",
   relatedWords:[
     {word:"complete",meaning:"完全な",breakdown:"com（すっかり）＋ ple（満たす）→ すみずみまで満たされている"},
     {word:"supplement",meaning:"補うもの，サプリ",breakdown:"sup（下から）＋ ple（満たす）→ 足りない分を下から補うもの"},
     {word:"plenty",meaning:"たくさん",breakdown:"ple（満たす）＋ ty（名詞）→ 満ち足りているほどの量"},
     {synonym:true,word:"praise",meaning:"称賛",breakdown:"よさをたたえること。compliment はその場で伝える短い褒め言葉"}]},

  {id:1006,word:"feast",partOfSpeech:"名詞",meaning:"宴会，ごちそう",
   meanings:["名|宴会，ごちそう"],
   pronunciation:"/fiːst/",part:101,
   example:"The village held a great feast after the autumn harvest.",
   exampleJa:"村は秋の収穫の後、盛大な宴会を開いた。",
   example2:"Our family feast lasts for hours every New Year.",
   exampleJa2:"うちの家族の宴会は、毎年正月に何時間も続く。",
   etymologyProcess:"fest（祭り）→ ごちそうを並べて囲む集まりは…？",
   etymologyConclusion:"fest（祭り）→ 祭りの日にごちそうを並べて囲む集まり＝宴会",
   relatedWords:[
     {word:"festival",meaning:"祭り",breakdown:"fest（祭り）＋ al（形容詞）→ 祭りの日に開かれる催し"},
     {word:"festive",meaning:"お祝いの，浮き立つ",breakdown:"fest（祭り）＋ ive（形容詞）→ 祭りのようににぎやかな"},
     {word:"fiesta",meaning:"フィエスタ，祝祭",breakdown:"fest（祭り）→ スペイン語になった同じ語"},
     {synonym:true,word:"banquet",meaning:"宴会，晩さん会",breakdown:"改まった大きな宴。feast はごちそうを囲む集まり全般"}]},

  {id:1007,word:"declare",partOfSpeech:"他動詞",meaning:"宣言する",
   meanings:["他|宣言する，はっきり言う","他|（税関で）申告する"],
   pronunciation:"/dɪˈkler/",part:101,
   example:"The mayor will declare the new park open tomorrow.",
   exampleJa:"市長は明日、新しい公園の開園を宣言する。",
   example2:"She declared that she would never give up running.",
   exampleJa2:"彼女は、走ることを決してあきらめないと宣言した。",
   etymologyProcess:"de（すっかり）＋ clar（澄んだ）→ あいまいさをなくして言い切ると…？",
   etymologyConclusion:"de（すっかり）＋ clar（澄んだ）→ あいまいさをなくしてはっきり言い切る＝宣言する",
   relatedWords:[
     {word:"clear",meaning:"はっきりした，澄んだ",breakdown:"clar（澄んだ）→ にごりがなく向こうまで見通せる"},
     {word:"clarify",meaning:"はっきりさせる",breakdown:"clar（澄んだ）＋ fy（する）→ にごりを取って澄ませる"},
     {word:"clarity",meaning:"明快さ",breakdown:"clar（澄んだ）＋ ity（名詞）→ 澄んでいてよく分かること"},
     {synonym:true,word:"announce",meaning:"発表する",breakdown:"広く知らせること。declare は改まってはっきり言い切ること"}]},

  {id:1008,word:"highlight",partOfSpeech:"他動詞",meaning:"強調する，目立たせる",
   meanings:["他|強調する，目立たせる","名|見どころ，ハイライト"],
   pronunciation:"/ˈhaɪlaɪt/",part:101,
   example:"The report highlights the need for more sleep.",
   exampleJa:"その報告書は、もっと睡眠が必要であることを強調している。",
   example2:"Please highlight the important words in yellow pen.",
   exampleJa2:"大切な語を黄色いペンで強調してください。",
   etymologyProcess:"high（高い）→ ひときわ明るく高いところを示すと…？",
   etymologyConclusion:"high（高い）→ ひときわ明るいところとして示し、そこだけ目立たせる＝強調する",
   why:"【なぜ】highlight はもともと絵画の用語で、「絵の中でいちばん明るい部分（high light）」のことでした。そこから「いちばん目立つところ」、さらに動詞の「目立たせる・強調する」になりました。\n【つながり】試合の「ハイライト」は見どころ、蛍光ペンで highlight するのは目立たせること。どちらも「ひときわ明るい部分」から来ています。",
   relatedWords:[
     {word:"high",meaning:"高い",breakdown:"high（高い）→ 地面から上へ大きく離れている"},
     {word:"height",meaning:"高さ",breakdown:"high（高い）＋ th（名詞）→ どれだけ高いかを数で表したもの"},
     {word:"highly",meaning:"大いに",breakdown:"high（高い）＋ ly（副詞）→ 程度の高いところまで"},
     {synonym:true,word:"emphasize",meaning:"強調する",breakdown:"言葉で力を込めること。highlight は目立たせて示すこと"}]},

  {id:1009,word:"imply",partOfSpeech:"他動詞",meaning:"ほのめかす",
   meanings:["他|ほのめかす，暗に示す"],
   pronunciation:"/ɪmˈplaɪ/",part:101,
   example:"Do not imply that I am lying about this.",
   exampleJa:"私がこのことでうそをついているとほのめかさないでください。",
   example2:"Her very short answer implied that she was quite angry.",
   exampleJa2:"彼女のとても短い返事は、かなり怒っていることをほのめかしていた。",
   etymologyProcess:"im（中へ）＋ pli（折る）→ 言葉の中に意味を折り込むと…？",
   etymologyConclusion:"im（中へ）＋ pli（折る）→ 言葉の中に意味をそっと折り込んでおく＝ほのめかす",
   relatedWords:[
     {word:"apply",meaning:"申し込む；当てはめる",breakdown:"ad（〜へ）＋ pli（折る）→ そこへぴたりと折り重ねる"},
     {word:"reply",meaning:"返事する",breakdown:"re（後ろへ）＋ pli（折る）→ 相手のほうへ言葉を折り返す"},
     {word:"simple",meaning:"単純な",breakdown:"sim（1つ）＋ pli（折る）→ 折り目が1つしかない"},
     {word:"complicated",meaning:"複雑な",breakdown:"com（共に）＋ pli（折る）→ 何重にも折り重なっている"}]},

  {id:1010,word:"recite",partOfSpeech:"他動詞",meaning:"暗唱する",
   meanings:["他|暗唱する，朗読する"],
   pronunciation:"/rɪˈsaɪt/",part:101,
   example:"The students recite the poem every Monday morning.",
   exampleJa:"生徒たちは毎週月曜の朝に、その詩を暗唱する。",
   example2:"He recited the whole speech without looking at notes.",
   exampleJa2:"彼はメモを見ずに、スピーチ全体を暗唱した。",
   etymologyProcess:"re（再び）＋ cit（呼び出す）→ 覚えた言葉を呼び出して口に出すと…？",
   etymologyConclusion:"re（再び）＋ cit（呼び出す）→ 覚えた言葉を頭から呼び出して口に出す＝暗唱する",
   relatedWords:[
     {word:"cite",meaning:"引用する",breakdown:"cit（呼び出す）→ 必要なところを呼び出して示す"},
     {word:"excite",meaning:"わくわくさせる",breakdown:"ex（外へ）＋ cit（呼び出す）→ 気持ちを外へ呼び起こす"},
     {word:"recital",meaning:"リサイタル，独奏会",breakdown:"re（再び）＋ cit（呼び出す）＋ al（名詞）→ 覚えた曲を呼び出して演じる会"},
     {synonym:true,word:"memorize",meaning:"暗記する",breakdown:"頭に入れること。recite はそれを声に出して言うこと"}]},

  {id:1011,word:"ray",partOfSpeech:"名詞",meaning:"光線，一筋の光",
   meanings:["名|光線，一筋の光"],
   pronunciation:"/reɪ/",part:102,
   example:"A thin ray of sunlight came through the curtain.",
   exampleJa:"細い一筋の光線が、カーテンから差し込んできた。",
   example2:"The sun's rays feel very strong around noon here.",
   exampleJa2:"ここでは正午ごろ、太陽の光線がとても強く感じられる。",
   etymologyProcess:"radi（放射する）→ 中心からまっすぐ外へ細く伸びていくものは…？",
   etymologyConclusion:"radi（放射する）→ 中心からまっすぐ外へ伸びていく一筋の光＝光線",
   relatedWords:[
     {word:"radio",meaning:"ラジオ",breakdown:"radi（放射する）→ 電波を四方へ放って伝える仕組み"},
     {word:"radius",meaning:"半径",breakdown:"radi（放射する）→ 中心から外へまっすぐ伸びた長さ"},
     {word:"radiation",meaning:"放射線",breakdown:"radi（放射する）＋ ation（名詞）→ 中心から放たれて広がるもの"},
     {word:"radiator",meaning:"ラジエーター，暖房器",breakdown:"radi（放射する）＋ ator（装置）→ 熱を四方へ放つ装置"}]},

  {id:1012,word:"radiation",partOfSpeech:"名詞",meaning:"放射線",
   meanings:["名|放射線","名|放射，放出"],
   pronunciation:"/ˌreɪdiˈeɪʃn/",part:102,
   example:"Doctors use radiation to treat some kinds of cancer.",
   exampleJa:"医師はある種のがんを治すのに放射線を使う。",
   example2:"Radiation from the sun reaches the earth in minutes.",
   exampleJa2:"太陽からの放射は、数分で地球に届く。",
   etymologyProcess:"radi（放射する）＋ ation（名詞）→ 中心から四方へ放たれて広がるものは…？",
   etymologyConclusion:"radi（放射する）＋ ation（名詞）→ 中心から四方へ放たれて広がるエネルギー＝放射線",
   relatedWords:[
     {word:"ray",meaning:"光線",breakdown:"radi（放射する）→ 中心からまっすぐ外へ伸びる一筋の光"},
     {word:"radio",meaning:"ラジオ",breakdown:"radi（放射する）→ 電波を四方へ放って伝える仕組み"},
     {word:"radius",meaning:"半径",breakdown:"radi（放射する）→ 中心から外へまっすぐ伸びた長さ"},
     {synonym:true,word:"beam",meaning:"光線，ビーム",breakdown:"束になった光。radiation は目に見えないものも含む放射"}]},

  {id:1013,word:"laboratory",partOfSpeech:"名詞",meaning:"研究室，実験室",
   meanings:["名|研究室，実験室"],
   pronunciation:"/ˈlæbrətɔːri/",part:102,
   example:"The students did an experiment in the science laboratory.",
   exampleJa:"生徒たちは理科の実験室で実験をした。",
   example2:"Her father works in a large medical laboratory downtown.",
   exampleJa2:"彼女の父は、町の大きな医学研究所で働いている。",
   etymologyProcess:"labor（働く）＋ ory（場所）→ 手を動かして試しながら働く部屋は…？",
   etymologyConclusion:"labor（働く）＋ ory（場所）→ 手を動かして試しながら働くための部屋＝研究室",
   relatedWords:[
     {word:"labor",meaning:"労働",breakdown:"labor（働く）→ 体を使ってきつく働くこと"},
     {word:"collaborate",meaning:"協力する",breakdown:"col（共に）＋ labor（働く）→ 共に力を出し合って働く"},
     {word:"elaborate",meaning:"入念な；詳しく述べる",breakdown:"ex（外へ）＋ labor（働く）→ 手をかけて練り上げる"},
     {word:"laborious",meaning:"骨の折れる",breakdown:"labor（働く）＋ ous（形容詞）→ 働きづめになるほど手間がかかる"}]},

  {id:1014,word:"oxygen",partOfSpeech:"名詞",meaning:"酸素",
   meanings:["名|酸素"],
   pronunciation:"/ˈɑːksɪdʒən/",part:102,
   example:"Green plants produce oxygen during the bright daytime.",
   exampleJa:"緑の植物は、明るい昼間に酸素を作り出す。",
   example2:"Climbers carry extra oxygen on very high mountains.",
   exampleJa2:"登山者はとても高い山では、予備の酸素を持っていく。",
   etymologyProcess:"oxy（酸っぱい）＋ gen（生み出す）→ 酸を生み出すと考えられた気体は…？",
   etymologyConclusion:"oxy（酸っぱい）＋ gen（生み出す）→ 酸を生み出す気体と考えられて付いた名前＝酸素",
   why:"【なぜ】ラボアジエが「すべての酸を生み出す元素」と考えて、ギリシャ語の oxys（酸っぱい）＋ genes（生み出す）から名づけました。のちにこれは誤りだと分かりましたが、名前だけが残りました。\n【つながり】hydrogen（水を生む＝水素）、generate（生み出す）、gene（遺伝子）も同じ gen の家族です。",
   relatedWords:[
     {word:"generate",meaning:"生み出す",breakdown:"gener（生み出す）＋ ate（動詞）→ 新しく作り出す"},
     {word:"gene",meaning:"遺伝子",breakdown:"gen（生み出す）→ 体の特徴を生み出すもとになるもの"},
     {word:"hydrogen",meaning:"水素",breakdown:"hydro（水）＋ gen（生み出す）→ 燃えると水を生み出す気体"},
     {word:"oxide",meaning:"酸化物",breakdown:"oxy（酸っぱい）→ 酸素と結びついてできたもの"}]},

  {id:1015,word:"molecule",partOfSpeech:"名詞",meaning:"分子",
   meanings:["名|分子"],
   pronunciation:"/ˈmɑːlɪkjuːl/",part:102,
   example:"A single water molecule has two hydrogen atoms.",
   exampleJa:"1個の水の分子は、2個の水素原子を持っている。",
   example2:"Molecules move much faster when the temperature rises.",
   exampleJa2:"温度が上がると、分子はずっと速く動く。",
   etymologyProcess:"mol（かたまり）＋ cul（小さい）→ 物を作っているとても小さなかたまりは…？",
   etymologyConclusion:"mol（かたまり）＋ cul（小さい）→ 物を作っている、とても小さなかたまり＝分子",
   relatedWords:[
     {word:"molecular",meaning:"分子の",breakdown:"mol（かたまり）＋ cul（小さい）＋ ar（形容詞）→ 小さなかたまりに関わる"},
     {word:"demolish",meaning:"取り壊す",breakdown:"de（下へ）＋ mol（かたまり）→ 積み上げたかたまりを崩す"},
     {synonym:true,word:"atom",meaning:"原子",breakdown:"これ以上分けられない粒。molecule は原子が結びついたかたまり"},
     {synonym:true,word:"cell",meaning:"細胞",breakdown:"生き物を作る小部屋。molecule は物質を作る小さなかたまり"}]},

  {id:1016,word:"compound",partOfSpeech:"名詞",meaning:"化合物",
   meanings:["名|化合物","名|複合語"],
   pronunciation:"/ˈkɑːmpaʊnd/",part:102,
   example:"Water is a simple compound of hydrogen and oxygen.",
   exampleJa:"水は、水素と酸素の単純な化合物だ。",
   example2:"This new compound may help treat that serious disease.",
   exampleJa2:"この新しい化合物は、あの重い病気の治療に役立つかもしれない。",
   etymologyProcess:"com（共に）＋ pon（置く）→ いくつかを共に置いて組み合わせると…？",
   etymologyConclusion:"com（共に）＋ pon（置く）→ いくつかの元素を共に置いて組み合わせたもの＝化合物",
   relatedWords:[
     {word:"compose",meaning:"構成する；作曲する",breakdown:"com（共に）＋ pos（置く）→ 部品を共に置いて組み立てる"},
     {word:"component",meaning:"構成要素",breakdown:"com（共に）＋ pon（置く）＋ ent（もの）→ 共に置かれて全体を作る部品"},
     {word:"opponent",meaning:"相手，対戦者",breakdown:"op（向かい合って）＋ pon（置く）→ 向かい合う位置に置かれた人"},
     {synonym:true,word:"mixture",meaning:"混合物",breakdown:"混ぜただけのもの。compound は結びついて別の物になったもの"}]},

  {id:1017,word:"tissue",partOfSpeech:"名詞",meaning:"（生物の）組織",
   meanings:["名|（生物の）組織","名|ティッシュ，薄紙"],
   pronunciation:"/ˈtɪʃuː/",part:102,
   example:"Muscle tissue needs plenty of oxygen to work well.",
   exampleJa:"筋肉の組織は、よく働くために十分な酸素を必要とする。",
   example2:"The doctor carefully examined a small piece of tissue.",
   exampleJa2:"医師は小さな組織の一片を、注意深く調べた。",
   etymologyProcess:"tis（織る）→ 細い糸のように織り合わさって体を作るものは…？",
   etymologyConclusion:"tis（織る）→ 細い糸のように織り合わさって体を作っているもの＝組織",
   why:"【なぜ】もとのフランス語 tissu は「織られた布」。細い糸が織り合わさった布のように見えることから、生き物の「組織」に使われるようになりました。薄い紙のティッシュも「薄い織物」からです。\n【つながり】textile（織物）、text（もとは「織られたもの」＝文章）も同じ「織る」家族です。",
   relatedWords:[
     {word:"text",meaning:"本文，文章",breakdown:"tis（織る）→ 言葉を織り合わせて作ったもの"},
     {word:"textile",meaning:"織物",breakdown:"tex（織る）＋ ile（できる）→ 織って作ることのできる布"},
     {synonym:true,word:"cell",meaning:"細胞",breakdown:"生き物を作る小部屋。tissue は細胞が集まってできた組織"},
     {synonym:true,word:"organ",meaning:"臓器",breakdown:"働きを持つ器官。tissue はそれを作っている材料のほう"}]},

  {id:1018,word:"cell",partOfSpeech:"名詞",meaning:"細胞",
   meanings:["名|細胞","名|独房，小部屋","名|電池"],
   pronunciation:"/sel/",part:102,
   example:"The human body contains many billions of tiny cells.",
   exampleJa:"人の体は、何十億もの小さな細胞を含んでいる。",
   example2:"Each cell has a nucleus somewhere near its center.",
   exampleJa2:"それぞれの細胞は、中心の近くのどこかに核を持っている。",
   etymologyProcess:"cell（小部屋）→ 生き物の体を作るいちばん小さな部屋は…？",
   etymologyConclusion:"cell（小部屋）→ 生き物の体を作っている、いちばん小さな部屋＝細胞",
   why:"【なぜ】ラテン語 cella は「小部屋」。17世紀にフックがコルクを顕微鏡で見たとき、仕切られた小部屋がぎっしり並んでいるように見えたので cell と名づけました。\n【つながり】修道院の個室も刑務所の独房も cell。cellar（地下室）も同じ家族。携帯の cell phone は、電波の受け持ち区画を cell と呼ぶことから来ています。",
   relatedWords:[
     {word:"cellar",meaning:"地下室",breakdown:"cell（小部屋）＋ ar（もの）→ 地下にある蓄えの小部屋"},
     {word:"cellular",meaning:"細胞の；携帯電話の",breakdown:"cell（小部屋）＋ ar（形容詞）→ 小部屋に区切られている"},
     {synonym:true,word:"tissue",meaning:"組織",breakdown:"細胞が集まってできた層。cell はその一つ一つを指す"},
     {synonym:true,word:"atom",meaning:"原子",breakdown:"物質のいちばん小さな粒。cell は生き物のいちばん小さな単位"}]},

  {id:1019,word:"gene",partOfSpeech:"名詞",meaning:"遺伝子",
   meanings:["名|遺伝子"],
   pronunciation:"/dʒiːn/",part:102,
   example:"Genes decide the color of your eyes and hair.",
   exampleJa:"遺伝子は、目や髪の色を決める。",
   example2:"Scientists found a gene linked to that rare disease.",
   exampleJa2:"科学者たちは、あの珍しい病気と結びついた遺伝子を見つけた。",
   etymologyProcess:"gen（生み出す）→ 親から子へ特徴を生み出して伝えるものは…？",
   etymologyConclusion:"gen（生み出す）→ 親から子へ、体の特徴を生み出して伝えるもと＝遺伝子",
   relatedWords:[
     {word:"generate",meaning:"生み出す",breakdown:"gener（生み出す）＋ ate（動詞）→ 新しく作り出す"},
     {word:"generation",meaning:"世代",breakdown:"gener（生み出す）＋ ation（名詞）→ 生み出されて続く一つの代"},
     {word:"genetic",meaning:"遺伝の",breakdown:"gen（生み出す）＋ etic（〜の）→ 生まれつき受け継ぐことに関わる"},
     {word:"generous",meaning:"気前のよい",breakdown:"gener（生み出す）＋ ous（形容詞）→ よい生まれの者らしく惜しみない"}]},

  {id:1020,word:"substance",partOfSpeech:"名詞",meaning:"物質",
   meanings:["名|物質","名|中身，実質"],
   pronunciation:"/ˈsʌbstəns/",part:102,
   example:"This substance turns bright blue when you heat it.",
   exampleJa:"この物質は、熱すると明るい青色になる。",
   example2:"Scientists study the substance found inside the old meteorite.",
   exampleJa2:"科学者たちは、その古い隕石の中で見つかった物質を研究している。",
   etymologyProcess:"sub（下で）＋ sta（立つ）→ 見た目の下で全体を支えて立っているのは…？",
   etymologyConclusion:"sub（下で）＋ sta（立つ）＋ ance（名詞）→ 見た目の下で全体を支えて立っている中身＝物質",
   relatedWords:[
     {word:"stand",meaning:"立つ",breakdown:"sta（立つ）→ 足を地につけてまっすぐ立つ"},
     {word:"substantial",meaning:"かなりの；中身のある",breakdown:"sub（下で）＋ sta（立つ）＋ al（形容詞）→ 下でしっかり支えるほどの"},
     {word:"circumstance",meaning:"状況",breakdown:"circ（輪を描く）＋ sta（立つ）→ まわりを取り巻いて立っていること"},
     {word:"constant",meaning:"絶え間ない",breakdown:"con（共に）＋ sta（立つ）＋ ant（形容詞）→ ずっと同じ所に立ち続ける"}]},

  {id:1021,word:"solid",partOfSpeech:"形容詞",meaning:"固体の；中身の詰まった",
   meanings:["形|固体の","形|中身の詰まった，がっしりした","名|固体"],
   pronunciation:"/ˈsɑːlɪd/",part:103,
   example:"Ice is simply the solid form of ordinary water.",
   exampleJa:"氷は単に、ふつうの水の固体の形だ。",
   example2:"The old bridge rests on solid stone pillars.",
   exampleJa2:"その古い橋は、中身の詰まった石の柱の上に載っている。",
   etymologyProcess:"solid（ぎっしり詰まった）→ 中まですき間なく詰まっていると…？",
   etymologyConclusion:"solid（ぎっしり詰まった）→ 中まですき間なく詰まって形が崩れない＝固体の",
   hook:"「ソリッドな作り」＝がっしり。中までぎっしり詰まっている感じが芯。",
   relatedWords:[
     {synonym:true,word:"firm",meaning:"しっかりした",breakdown:"ぐらつかないこと。solid は中身が詰まっていることを言う"},
     {synonym:true,word:"hard",meaning:"固い",breakdown:"押しても形が変わらないこと。solid は気体・液体に対する状態"},
     {synonym:true,word:"stable",meaning:"安定した",breakdown:"ぐらつかず変わらないこと。solid は中身が詰まっていること"},
     {word:"consolidate",meaning:"統合する，固める",breakdown:"con（共に）＋ solid（ぎっしり詰まった）→ ばらばらのものを固めて一つにする"}]},

  {id:1022,word:"satellite",partOfSpeech:"名詞",meaning:"衛星",
   meanings:["名|衛星","名|人工衛星"],
   pronunciation:"/ˈsætəlaɪt/",part:103,
   example:"The moon is the only natural satellite of Earth.",
   exampleJa:"月は地球の唯一の自然の衛星だ。",
   example2:"They launched a new weather satellite last month.",
   exampleJa2:"彼らは先月、新しい気象衛星を打ち上げた。",
   etymologyProcess:"satel（付き添い）→ 惑星のそばに付き添ってまわり続けるものは…？",
   etymologyConclusion:"satel（付き添い）→ 惑星のそばに付き添って、まわり続けるもの＝衛星",
   hook:"「衛星放送」「衛星写真」で身近。惑星に付き添って回るものが芯。",
   why:"【なぜ】ラテン語 satelles は「護衛・付き添いの者」。ケプラーが木星のまわりを回る星を「木星の護衛」にたとえて satellite と呼んだことから、「衛星」になりました。\n【つながり】人工衛星も satellite。衛星放送やカーナビの GPS も、この satellite を使っています。",
   relatedWords:[
     {synonym:true,word:"moon",meaning:"月",breakdown:"地球の衛星そのもの。satellite は他の惑星のものも含む"},
     {synonym:true,word:"orbit",meaning:"軌道",breakdown:"回っていく道すじ。satellite はその道を回っているもの"},
     {synonym:true,word:"planet",meaning:"惑星",breakdown:"恒星のまわりを回る星。satellite はその惑星のまわりを回る"},
     {synonym:true,word:"guard",meaning:"護衛",breakdown:"satellite のもとの意味がこれ。付き添って守る者のこと"}]},

  {id:1023,word:"orbit",partOfSpeech:"名詞",meaning:"軌道",
   meanings:["名|軌道","他|～のまわりを回る"],
   pronunciation:"/ˈɔːrbɪt/",part:103,
   example:"The satellite moves in a wide orbit around Earth.",
   exampleJa:"その衛星は、地球のまわりの広い軌道を動く。",
   example2:"It takes the moon a month to complete its orbit.",
   exampleJa2:"月が軌道を一周するのには、1か月かかる。",
   etymologyProcess:"orb（輪）→ 天体がぐるりと描く輪の道すじは…？",
   etymologyConclusion:"orb（輪）→ 天体がぐるりと描いていく、輪の形の道すじ＝軌道",
   relatedWords:[
     {word:"orbital",meaning:"軌道の",breakdown:"orb（輪）＋ al（形容詞）→ 輪の道すじに関わる"},
     {synonym:true,word:"circle",meaning:"円，輪",breakdown:"丸い形。orbit は天体が回る決まった道すじを指す"},
     {synonym:true,word:"path",meaning:"通り道",breakdown:"通っていく道。orbit はぐるりと回って戻ってくる道すじ"},
     {word:"orb",meaning:"球，天体",breakdown:"orb（輪）→ まるい輪、まるい球そのもの"}]},

  {id:1024,word:"launch",partOfSpeech:"他動詞",meaning:"打ち上げる",
   meanings:["他|打ち上げる","他|（新商品・事業）を売り出す，始める"],
   pronunciation:"/lɔːntʃ/",part:103,
   example:"They will launch a new rocket next Tuesday morning.",
   exampleJa:"彼らは来週の火曜の朝、新しいロケットを打ち上げる。",
   example2:"The company launched a new smartphone last week.",
   exampleJa2:"その会社は先週、新しいスマートフォンを売り出した。",
   etymologyProcess:"lanc（槍）→ 槍を投げるように勢いよく空へ放つと…？",
   etymologyConclusion:"lanc（槍）→ 槍を投げるように、勢いよく空へ放つ＝打ち上げる",
   relatedWords:[
     {word:"lance",meaning:"槍",breakdown:"lanc（槍）→ 騎士が構えて突く長い槍"},
     {synonym:true,word:"release",meaning:"発売する；放つ",breakdown:"世に出すこと。launch は勢いよく始めることに重きがある"},
     {synonym:true,word:"shoot",meaning:"撃つ，放つ",breakdown:"勢いよく飛ばすこと。launch は大きなものを送り出す"},
     {synonym:true,word:"start",meaning:"始める",breakdown:"始めること。launch は大きな計画や商品を華々しく始める"}]},

  {id:1025,word:"attempt",partOfSpeech:"名詞",meaning:"（難しいことへの）試み",
   meanings:["名|（難しいことへの）試み，挑戦","他|試みる"],
   pronunciation:"/əˈtempt/",part:103,
   example:"His first attempt at the high jump clearly failed.",
   exampleJa:"走り高跳びでの彼の最初の試みは、はっきりと失敗した。",
   example2:"She will attempt the difficult climb again tomorrow morning.",
   exampleJa2:"彼女は明日の朝、もう一度その難しい登はんを試みる。",
   etymologyProcess:"ad（〜へ）＋ tempt（試す）→ できるかどうか手を伸ばして試すと…？",
   etymologyConclusion:"ad（〜へ）＋ tempt（試す）→ できるかどうか、そちらへ手を伸ばして試すこと＝難しいことへの試み",
   relatedWords:[
     {word:"tempt",meaning:"誘惑する",breakdown:"tempt（試す）→ 心が動くかどうか試しにさそう"},
     {word:"temptation",meaning:"誘惑",breakdown:"tempt（試す）＋ ation（名詞）→ 心を試しにさそってくるもの"},
     {synonym:true,word:"try",meaning:"試す",breakdown:"やってみること。attempt は少し硬く、難しいことに挑むときに使う"},
     {synonym:true,word:"effort",meaning:"努力",breakdown:"力を出すこと。attempt は実際にやってみる一回の試み"}]},

  {id:1026,word:"capacity",partOfSpeech:"名詞",meaning:"収容力，容量",
   meanings:["名|収容力，容量","名|（受け入れられる）能力"],
   pronunciation:"/kəˈpæsəti/",part:103,
   example:"This hall has a capacity of five hundred people.",
   exampleJa:"このホールは500人の収容力がある。",
   example2:"She has a great capacity for remembering people's names.",
   exampleJa2:"彼女は人の名前を覚える大きな能力を持っている。",
   etymologyProcess:"cap（つかむ）＋ ity（名詞）→ どれだけ抱えこめるかを表すと…？",
   etymologyConclusion:"cap（つかむ）＋ ity（名詞）→ どれだけつかんで抱えこめるかという大きさ＝収容力",
   relatedWords:[
     {word:"capable",meaning:"能力がある",breakdown:"cap（つかむ）＋ able（できる）→ しっかりつかんでやり切れる"},
     {word:"receive",meaning:"受け取る",breakdown:"re（後ろへ）＋ cept（取る）→ 差し出されたものを手に取る"},
     {word:"accept",meaning:"受け入れる",breakdown:"ac（〜へ）＋ cept（取る）→ 差し出されたほうへ手を出して取る"},
     {synonym:true,word:"ability",meaning:"能力",breakdown:"できる力。capacity は受け入れられる量や器の大きさを指す"}]},

  {id:1027,word:"capable",partOfSpeech:"形容詞",meaning:"（of ～）～する力がある",
   meanings:["形|（of ～）～する力がある，有能な"],
   pronunciation:"/ˈkeɪpəbl/",part:103,
   example:"She is capable of solving very difficult math problems.",
   exampleJa:"彼女はとても難しい数学の問題を解く力がある。",
   example2:"This small car is capable of carrying six people.",
   exampleJa2:"この小さな車は6人を運ぶ力がある。",
   etymologyProcess:"cap（つかむ）＋ able（できる）→ その仕事をしっかりつかんでやれると…？",
   etymologyConclusion:"cap（つかむ）＋ able（できる）→ その仕事をしっかりつかんでやり切れる＝～する力がある",
   relatedWords:[
     {word:"capacity",meaning:"収容力，容量",breakdown:"cap（つかむ）＋ ity（名詞）→ どれだけ抱えこめるかという大きさ"},
     {word:"capture",meaning:"捕らえる",breakdown:"cap（つかむ）＋ ure（名詞）→ つかまえて自分のものにする"},
     {word:"accept",meaning:"受け入れる",breakdown:"ac（〜へ）＋ cept（取る）→ 差し出されたほうへ手を出して取る"},
     {synonym:true,word:"able",meaning:"できる",breakdown:"「〜できる」の基本語。capable は of を伴って力量を表す"}]},

  {id:1028,word:"attain",partOfSpeech:"他動詞",meaning:"達成する，到達する",
   meanings:["他|達成する，到達する"],
   pronunciation:"/əˈteɪn/",part:103,
   example:"He finally attained his goal after five long years.",
   exampleJa:"彼は5年の長い年月の後、ついに目標を達成した。",
   example2:"Few students attain such a high score on this test.",
   exampleJa2:"このテストでそれほど高い点数を達成する生徒は、ほとんどいない。",
   etymologyProcess:"ad（〜へ）＋ tang（触れる）→ 目指したところまで手が届くと…？",
   etymologyConclusion:"ad（〜へ）＋ tang（触れる）→ 目指したところまで手が届いて触れる＝達成する",
   why:"【なぜ】attain の tain は「保つ」の tain ではなく、ラテン語 tangere「触れる」です。ad（〜へ）＋ tangere で「そこまで手が届いて触れる」。そこから「到達する・達成する」になりました。\n【つながり】contact（共に触れる＝接触）、tangible（触れられる）も同じ家族。maintain や contain の tain とは別の語です。",
   relatedWords:[
     {word:"contact",meaning:"接触；連絡する",breakdown:"con（共に）＋ tact（触れる）→ 互いに触れ合う"},
     {word:"tangible",meaning:"手で触れられる",breakdown:"tang（触れる）＋ ible（できる）→ 実際に触れることができる"},
     {word:"intact",meaning:"損なわれていない",breakdown:"in（否定）＋ tact（触れる）→ 誰にも触られていないままの"},
     {synonym:true,word:"achieve",meaning:"達成する",breakdown:"やり遂げること。attain は努力の末に手が届く感じが強い"}]},

  {id:1029,word:"desperate",partOfSpeech:"形容詞",meaning:"必死の",
   meanings:["形|必死の，死に物狂いの","形|絶望的な"],
   pronunciation:"/ˈdespərət/",part:103,
   example:"He made a desperate effort to save his friend.",
   exampleJa:"彼は友人を救おうと、必死の努力をした。",
   example2:"The team was desperate for just one more point.",
   exampleJa2:"チームは、あと1点だけがどうしても欲しくて必死だった。",
   etymologyProcess:"de（離して）＋ sper（希望）＋ ate（形容詞）→ 希望から切り離されると…？",
   etymologyConclusion:"de（離して）＋ sper（希望）＋ ate（形容詞）→ 希望から切り離され、なりふり構わない＝必死の",
   relatedWords:[
     {word:"despair",meaning:"絶望",breakdown:"de（離して）＋ sper（希望）→ 希望から完全に引き離された状態"},
     {word:"desperation",meaning:"必死さ，絶望",breakdown:"de（離して）＋ sper（希望）＋ ation（名詞）→ 追いつめられること"},
     {synonym:true,word:"hopeless",meaning:"望みのない",breakdown:"望みが見えないようす。desperate はなりふり構わず動くこと"},
     {synonym:true,word:"frantic",meaning:"半狂乱の",breakdown:"あわてふためくようす。desperate は追いつめられて必死なこと"}]},

  {id:1030,word:"dedicate",partOfSpeech:"他動詞",meaning:"捧げる",
   meanings:["他|（時間・人生）を捧げる","他|（作品）を献呈する"],
   pronunciation:"/ˈdedɪkeɪt/",part:103,
   example:"She dedicated her first book to her late grandmother.",
   exampleJa:"彼女は最初の本を、亡き祖母に捧げた。",
   example2:"He dedicates every weekend to practicing the guitar.",
   exampleJa2:"彼は毎週末をギターの練習に捧げている。",
   etymologyProcess:"de（すっかり）＋ dic（言う）→ これはあなたのものだと言い切ると…？",
   etymologyConclusion:"de（すっかり）＋ dic（言う）→ これはあなたのものだと言い切って差し出す＝捧げる",
   relatedWords:[
     {word:"dictionary",meaning:"辞書",breakdown:"dict（言う）＋ ary（集まり）→ 言葉の言い方を集めたもの"},
     {word:"predict",meaning:"予言する",breakdown:"pre（先に）＋ dict（言う）→ 起こる前に先に言う"},
     {word:"indicate",meaning:"示す",breakdown:"in（〜に）＋ dic（言う）→ これだと指さして言い当てる"},
     {word:"dictate",meaning:"書き取らせる；指図する",breakdown:"dict（言う）＋ ate（動詞）→ 言って相手に書き取らせる"}]},

  {id:1031,word:"pain",partOfSpeech:"名詞",meaning:"苦痛，痛み",
   meanings:["名|苦痛，痛み","名|（pains で）骨折り"],
   pronunciation:"/peɪn/",part:104,
   example:"She felt a sharp pain in her right knee.",
   exampleJa:"彼女は右のひざに鋭い苦痛を感じた。",
   example2:"The new medicine reduced his pain within ten minutes.",
   exampleJa2:"その新しい薬は、10分以内に彼の苦痛を和らげた。",
   etymologyProcess:"pain（罰）→ 罰のように突き刺さるつらさは…？",
   etymologyConclusion:"pain（罰）→ 体や心に、罰のように突き刺さってくるつらさ＝苦痛",
   why:"【なぜ】ラテン語 poena は「罰・罰金」でした。罰として受ける苦しみのほうへ意味が移り、「苦痛」そのものを指すようになりました。\n【つながり】punish（罰する）、penalty（罰則）も同じ家族。サッカーの「ペナルティ」も同じ語です。",
   relatedWords:[
     {word:"punish",meaning:"罰する",breakdown:"pun（罰）＋ ish（〜にする）→ 罰を与える"},
     {word:"penalty",meaning:"罰則，ペナルティ",breakdown:"pain（罰）＋ ty（名詞）→ 罰として課されるもの"},
     {word:"painful",meaning:"痛い，つらい",breakdown:"pain（罰）＋ ful（満ちた）→ 苦痛で満ちている"},
     {synonym:true,word:"ache",meaning:"うずく痛み",breakdown:"鈍く続く痛み。pain は鋭い痛みも心の痛みも指す"}]},

  {id:1032,word:"strain",partOfSpeech:"名詞",meaning:"負担，緊張",
   meanings:["名|（心身にかかる）負担，緊張","他|（体の一部）を痛める；緊張させる"],
   pronunciation:"/streɪn/",part:104,
   example:"The long working hours put a great strain on him.",
   exampleJa:"長い労働時間が、彼に大きな負担をかけた。",
   example2:"Too much screen time can strain your tired eyes.",
   exampleJa2:"画面の見すぎは、疲れた目に負担をかけることがある。",
   etymologyProcess:"strain（締めつける）→ ぴんと引き締められて限界に近づくと…？",
   etymologyConclusion:"strain（締めつける）→ ぴんと引き締められて限界に近づいていく力＝負担",
   relatedWords:[
     {word:"strict",meaning:"厳しい",breakdown:"strict（締めつける）→ ゆるみなくきつく締めつける"},
     {word:"restrict",meaning:"制限する",breakdown:"re（後ろへ）＋ strict（締めつける）→ 締めて引き戻し、外へ出さない"},
     {word:"stress",meaning:"圧力，強調",breakdown:"stress（締めつける）→ ぎゅっと締めつけてくる力"},
     {word:"district",meaning:"地区",breakdown:"dis（バラバラに）＋ strict（締めつける）→ 土地を区切った一まとまり"}]},

  {id:1033,word:"remedy",partOfSpeech:"名詞",meaning:"治療法；解決策",
   meanings:["名|治療法，薬","名|解決策"],
   pronunciation:"/ˈremədi/",part:104,
   example:"My grandmother knows an old remedy for bad colds.",
   exampleJa:"祖母はひどいかぜの古い治療法を知っている。",
   example2:"There is no easy remedy for this difficult problem.",
   exampleJa2:"この難しい問題に、簡単な解決策はない。",
   etymologyProcess:"re（再び）＋ med（治す）→ 元の健康な状態へ治し戻す手だては…？",
   etymologyConclusion:"re（再び）＋ med（治す）→ 元の健康な状態へ治し戻すための手だて＝治療法",
   relatedWords:[
     {word:"medicine",meaning:"薬；医学",breakdown:"medic（治す）＋ ine（もの）→ 体を治すためのもの"},
     {word:"medical",meaning:"医学の",breakdown:"medic（治す）＋ al（形容詞）→ 治すことに関わる"},
     {synonym:true,word:"cure",meaning:"治療する",breakdown:"病気を治すこと。remedy はそのための手だてを指す名詞"},
     {synonym:true,word:"treatment",meaning:"治療",breakdown:"手当てすること。remedy は効く手だてそのものを指す"}]},

  {id:1034,word:"pharmacy",partOfSpeech:"名詞",meaning:"薬局",
   meanings:["名|薬局","名|薬学"],
   pronunciation:"/ˈfɑːrməsi/",part:104,
   example:"You can buy this medicine at almost any pharmacy.",
   exampleJa:"この薬は、ほとんどどの薬局でも買える。",
   example2:"I picked up my medicine at the pharmacy after school.",
   exampleJa2:"私は放課後、薬局で自分の薬を受け取った。",
   etymologyProcess:"pharmac（薬）＋ y（名詞）→ 薬を調えて渡してくれる店は…？",
   etymologyConclusion:"pharmac（薬）＋ y（名詞）→ 薬を調えて手渡してくれる店＝薬局",
   relatedWords:[
     {word:"pharmacist",meaning:"薬剤師",breakdown:"pharmac（薬）＋ ist（人）→ 薬を調える仕事の人"},
     {word:"pharmacology",meaning:"薬理学",breakdown:"pharmac（薬）＋ log（学問）→ 薬の働きを調べる学問"},
     {synonym:true,word:"drugstore",meaning:"ドラッグストア",breakdown:"薬も日用品も売る店。pharmacy は処方薬を扱う薬局"},
     {synonym:true,word:"medicine",meaning:"薬",breakdown:"飲んで治すもの。pharmacy はそれを渡してくれる店のほう"}]},

  {id:1035,word:"physician",partOfSpeech:"名詞",meaning:"（改まった語で）医師",
   meanings:["名|（改まった語で）医師"],
   pronunciation:"/fɪˈzɪʃn/",part:104,
   example:"Her mother is a physician at the city hospital.",
   exampleJa:"彼女の母は、市立病院の医師だ。",
   example2:"The physician advised him to rest for one week.",
   exampleJa2:"その医師は彼に、1週間休むよう助言した。",
   etymologyProcess:"phys（自然）＋ ian（人）→ 体という自然のしくみを知って治す人は…？",
   etymologyConclusion:"phys（自然）＋ ian（人）→ 体という自然のしくみを知って治す人＝医師",
   relatedWords:[
     {word:"physics",meaning:"物理学",breakdown:"phys（自然）＋ ics（学問）→ 自然のきまりを調べる学問"},
     {word:"physical",meaning:"身体の；物理的な",breakdown:"physic（自然）＋ al（形容詞）→ 自然の体に関わる"},
     {synonym:true,word:"doctor",meaning:"医師",breakdown:"ふつうの言い方。physician は改まった場で使う硬い語"},
     {synonym:true,word:"surgeon",meaning:"外科医",breakdown:"手術をする医師。physician は手術をしないほうの医師"}]},

  {id:1036,word:"disorder",partOfSpeech:"名詞",meaning:"（体や心の）不調，障害",
   meanings:["名|（体や心の）不調，障害","名|無秩序，乱れ"],
   pronunciation:"/dɪsˈɔːrdər/",part:104,
   example:"He suffers from a rare kind of sleep disorder.",
   exampleJa:"彼は珍しい種類の睡眠の不調に苦しんでいる。",
   example2:"The small room was left in complete disorder.",
   exampleJa2:"その小さな部屋は、まったく無秩序な状態のままだった。",
   etymologyProcess:"dis（否定）＋ ord（順序）→ 体や心の順序が乱れてしまうと…？",
   etymologyConclusion:"dis（否定）＋ ord（順序）→ 本来の順序が乱れてうまく働かない状態＝不調",
   relatedWords:[
     {word:"order",meaning:"順序；命令；注文",breakdown:"ord（順序）→ きちんと並んでいる並び方"},
     {word:"ordinary",meaning:"ふつうの",breakdown:"ord（順序）＋ ary（形容詞）→ 決まった並びのとおりの"},
     {word:"orderly",meaning:"整然とした",breakdown:"ord（順序）＋ ly（〜のような）→ 順序どおりに整っている"},
     {synonym:true,word:"illness",meaning:"病気",breakdown:"体の具合が悪いこと。disorder はしくみの乱れのほうを指す"}]},

  {id:1037,word:"pregnant",partOfSpeech:"形容詞",meaning:"妊娠した",
   meanings:["形|妊娠した"],
   pronunciation:"/ˈpreɡnənt/",part:104,
   example:"She was pregnant with her first child back then.",
   exampleJa:"そのころ、彼女は最初の子を妊娠していた。",
   example2:"Pregnant women should avoid lifting very heavy things.",
   exampleJa2:"妊娠した女性は、とても重い物を持ち上げるのを避けるべきだ。",
   etymologyProcess:"pre（先に）＋ nat（生まれる）→ 生まれる前の子をおなかに宿すと…？",
   etymologyConclusion:"pre（先に）＋ nat（生まれる）→ 生まれる前の子をおなかに宿している＝妊娠した",
   relatedWords:[
     {word:"nature",meaning:"自然；性質",breakdown:"nat（生まれる）＋ ure（名詞）→ 生まれつき備わっているもの"},
     {word:"native",meaning:"生まれつきの，その土地の",breakdown:"nat（生まれる）＋ ive（形容詞）→ そこで生まれた"},
     {word:"nation",meaning:"国家",breakdown:"nat（生まれる）＋ ion（名詞）→ 同じ土地に生まれた人の集まり"},
     {synonym:true,word:"expecting",meaning:"出産予定の",breakdown:"やわらかい言い方。pregnant は医学の場でも使うふつうの語"}]},

  {id:1038,word:"clinical",partOfSpeech:"形容詞",meaning:"臨床の",
   meanings:["形|臨床の","形|（態度が）そっけない"],
   pronunciation:"/ˈklɪnɪkl/",part:104,
   example:"The new drug passed its first clinical trial last year.",
   exampleJa:"その新薬は昨年、最初の臨床試験に通った。",
   example2:"She already has ten years of clinical experience.",
   exampleJa2:"彼女はすでに10年の臨床の経験がある。",
   etymologyProcess:"clin（傾き）＋ al（形容詞）→ 病床のそばで直に患者を診るなら…？",
   etymologyConclusion:"clin（傾き）＋ al（形容詞）→ 病床のそばで実際に患者を診ることに関わる＝臨床の",
   why:"【なぜ】ギリシャ語 klinē は「横たわる寝台」。klinein（傾ける）から出た語で、体を傾けて横になる場所のことです。医者が病床のそばで直に患者を診ることを clinical と言うようになりました。\n【つながり】clinic（診療所）、incline（傾く）、recline（もたれる）も同じ家族。リクライニングシートの recline です。",
   relatedWords:[
     {word:"clinic",meaning:"診療所",breakdown:"clin（傾き）＋ ic（名詞）→ 病床のそばで患者を診る場所"},
     {word:"incline",meaning:"傾く，傾ける",breakdown:"in（中へ）＋ clin（傾き）→ 内側へ傾いていく"},
     {word:"decline",meaning:"断る；下がる",breakdown:"de（下へ）＋ clin（傾き）→ 下へ傾いて離れていく"},
     {word:"recline",meaning:"もたれる",breakdown:"re（後ろへ）＋ clin（傾き）→ 後ろへ傾けて体を預ける"}]},

  {id:1039,word:"heal",partOfSpeech:"他動詞",meaning:"いやす，治す",
   meanings:["他|いやす，治す","自|（傷が）治る"],
   pronunciation:"/hiːl/",part:104,
   example:"Time will heal the pain of losing a good friend.",
   exampleJa:"時が、よい友を失った苦痛をいやしてくれるだろう。",
   example2:"The deep cut healed slowly over about two weeks.",
   exampleJa2:"その深い切り傷は、2週間ほどかけてゆっくり治った。",
   etymologyProcess:"heal（丸ごと無事な）→ 体を丸ごと無事な形へ戻すと…？",
   etymologyConclusion:"heal（丸ごと無事な）→ 傷や病をふさいで、体を丸ごと無事な形に戻す＝治す",
   relatedWords:[
     {word:"health",meaning:"健康",breakdown:"heal（丸ごと無事な）＋ th（名詞）→ 体が丸ごと無事であること"},
     {word:"healthy",meaning:"健康な",breakdown:"heal（丸ごと無事な）＋ y（形容詞）→ 丸ごと無事な状態の"},
     {word:"whole",meaning:"全体の，欠けのない",breakdown:"heal（丸ごと無事な）→ 欠けたところがひとつもない"},
     {synonym:true,word:"cure",meaning:"治療する",breakdown:"病気を治すこと。heal は傷や心が自然にふさがることにも使う"}]},

  {id:1040,word:"infect",partOfSpeech:"他動詞",meaning:"感染させる",
   meanings:["他|感染させる，うつす"],
   pronunciation:"/ɪnˈfekt/",part:104,
   example:"Dirty water can infect people with very serious diseases.",
   exampleJa:"汚れた水は、人にとても重い病気を感染させることがある。",
   example2:"The small wound became infected after a few days.",
   exampleJa2:"その小さな傷は、数日後に感染を起こした。",
   etymologyProcess:"in（中へ）＋ fect（作る）→ 体の中に入り込んで病を作り出すと…？",
   etymologyConclusion:"in（中へ）＋ fect（作る）→ 体の中に入り込んで、そこに病を作り出す＝感染させる",
   relatedWords:[
     {word:"infection",meaning:"感染",breakdown:"in（中へ）＋ fect（作る）＋ ion（名詞）→ 中に入り込んで病を作ること"},
     {word:"perfect",meaning:"完全な",breakdown:"per（すっかり）＋ fect（作る）→ すっかり作り上げられている"},
     {word:"effect",meaning:"効果",breakdown:"ef（外へ）＋ fect（作る）→ 外へ作り出される結果"},
     {word:"affect",meaning:"影響する",breakdown:"ad（〜へ）＋ fect（作る）→ そこへ働きかけて変化を作る"}]},

  {id:1041,word:"ankle",partOfSpeech:"名詞",meaning:"足首",
   meanings:["名|足首"],
   pronunciation:"/ˈæŋkl/",part:105,
   example:"He twisted his ankle during the long soccer game.",
   exampleJa:"彼は長いサッカーの試合中に、足首をひねった。",
   example2:"Her ankle still hurts after that very long walk.",
   exampleJa2:"あのとても長い散歩の後、彼女の足首はまだ痛む。",
   etymologyProcess:"ank（曲がる）→ 足と脚が折れ曲がってつながるところは…？",
   etymologyConclusion:"ank（曲がる）→ 足と脚が折れ曲がってつながっているところ＝足首",
   relatedWords:[
     {word:"angle",meaning:"角，角度",breakdown:"angle（角）→ 二つの線が折れ曲がってできる角"},
     {word:"anchor",meaning:"いかり",breakdown:"ank（曲がる）→ 曲がった爪で海底に引っかけるもの"},
     {synonym:true,word:"wrist",meaning:"手首",breakdown:"手と腕のつなぎ目。ankle は足と脚のつなぎ目"},
     {synonym:true,word:"heel",meaning:"かかと",breakdown:"足の後ろの部分。ankle はその上にある曲がる関節"}]},

  {id:1042,word:"thumb",partOfSpeech:"名詞",meaning:"親指",
   meanings:["名|（手の）親指"],
   pronunciation:"/θʌm/",part:105,
   example:"He hurt his thumb while cutting the hard vegetables.",
   exampleJa:"彼は固い野菜を切っているときに、親指をけがした。",
   example2:"She held up her thumb after the very long race.",
   exampleJa2:"とても長いレースの後、彼女は親指を立ててみせた。",
   etymologyProcess:"thumb（ふくらんだもの）→ 手の指でいちばん太くふくらんだ指は…？",
   etymologyConclusion:"thumb（ふくらんだもの）→ 手の指の中でいちばん太くふくらんだ指＝親指",
   hook:"b は読まない。thumbnail（親指のつめ＝小さな見本画像）でおなじみ。",
   relatedWords:[
     {synonym:true,word:"finger",meaning:"指",breakdown:"手の指ぜんたい。thumb は特に太い親指だけを指す"},
     {synonym:true,word:"toe",meaning:"足の指",breakdown:"足のほうの指。thumb は手の親指に限って使う"},
     {synonym:true,word:"thumbnail",meaning:"親指のつめ；縮小画像",breakdown:"親指のつめほど小さいことから、小さな見本画像のこと"},
     {synonym:true,word:"palm",meaning:"手のひら",breakdown:"手の内側。thumb はそこから出ている太い指"}]},

  {id:1043,word:"forehead",partOfSpeech:"名詞",meaning:"額（ひたい）",
   meanings:["名|額（ひたい）"],
   pronunciation:"/ˈfɔːrhed/",part:105,
   example:"She put a cold towel on his very hot forehead.",
   exampleJa:"彼女は彼のとても熱い額に、冷たいタオルを当てた。",
   example2:"Sweat ran down his forehead during the long race.",
   exampleJa2:"長いレースの間、汗が彼の額を流れ落ちた。",
   etymologyProcess:"fore（前に）＋ head（頭）→ 頭のいちばん前の平らな面は…？",
   etymologyConclusion:"fore（前に）＋ head（頭）→ 頭のいちばん前に来ている平らな面＝額",
   relatedWords:[
     {word:"head",meaning:"頭",breakdown:"head（頭）→ 体のいちばん上にある部分"},
     {word:"before",meaning:"～の前に",breakdown:"fore（前に）→ 時間や場所の上で前に来るところ"},
     {word:"forecast",meaning:"予報",breakdown:"fore（前に）＋ cast（投げる）→ 先へ考えを投げて言い当てる"},
     {word:"headache",meaning:"頭痛",breakdown:"head（頭）＋ ache（痛み）→ 頭が痛むこと"}]},

  {id:1044,word:"chin",partOfSpeech:"名詞",meaning:"下あご",
   meanings:["名|下あご，あご先"],
   pronunciation:"/tʃɪn/",part:105,
   example:"He rested his chin on both of his hands.",
   exampleJa:"彼は両手に下あごを乗せた。",
   example2:"A small scar remains on the left side of her chin.",
   exampleJa2:"小さな傷あとが、彼女の下あごの左側に残っている。",
   etymologyProcess:"chin（あご）→ 顔のいちばん下に突き出ている部分は…？",
   etymologyConclusion:"chin（あご）→ 顔のいちばん下に前へ突き出ている部分＝下あご",
   hook:"鉄棒の「チンニング（chin-up）」は、下あごをバーまで上げる懸垂のこと。",
   relatedWords:[
     {synonym:true,word:"jaw",meaning:"あご（骨）",breakdown:"あごの骨ぜんたい。chin はその先の突き出た部分"},
     {synonym:true,word:"cheek",meaning:"ほお",breakdown:"顔の横のふくらみ。chin は顔のいちばん下の部分"},
     {synonym:true,word:"face",meaning:"顔",breakdown:"顔ぜんたい。chin はその下の端にあたる"},
     {synonym:true,word:"beard",meaning:"あごひげ",breakdown:"chin に生えるひげ。chin はそのひげが生える場所"}]},

  {id:1045,word:"chest",partOfSpeech:"名詞",meaning:"胸；大きな箱",
   meanings:["名|胸","名|（ふた付きの）大きな箱"],
   pronunciation:"/tʃest/",part:105,
   example:"He felt a strange sharp pain in his chest.",
   exampleJa:"彼は胸に、奇妙な鋭い痛みを感じた。",
   example2:"The old wooden chest was full of old letters.",
   exampleJa2:"その古い木の箱は、古い手紙でいっぱいだった。",
   etymologyProcess:"chest（箱）→ 心臓や肺をおさめた箱のような部分は…？",
   etymologyConclusion:"chest（箱）→ 心臓や肺をおさめている、箱のような体の部分＝胸",
   hook:"treasure chest（宝箱）と同じ語。「中身を守る箱」が芯にある。",
   why:"【なぜ】ラテン語 cista は「箱」。英語ではまず「ふた付きの大きな箱」の意味で使われ、16世紀ごろから「心臓や肺をおさめた箱」＝胸、の意味が生まれました。\n【つながり】宝箱を treasure chest、引き出しつきのたんすを chest of drawers と言うのは、今も残る「箱」の意味です。",
   relatedWords:[
     {synonym:true,word:"breast",meaning:"胸，乳房",breakdown:"胸の前面。chest はろっ骨に囲まれた胸ぜんたいを指す"},
     {synonym:true,word:"box",meaning:"箱",breakdown:"chest のもとの意味。今も treasure chest に残っている"},
     {synonym:true,word:"lung",meaning:"肺",breakdown:"胸の中にある臓器。chest はそれを入れている箱のほう"},
     {synonym:true,word:"rib",meaning:"ろっ骨",breakdown:"胸を囲んでいる骨。chest はその骨に囲まれた部分"}]},

  {id:1046,word:"breast",partOfSpeech:"名詞",meaning:"胸のふくらみ；乳房",
   meanings:["名|（体の前の）胸のふくらみ","名|乳房"],
   pronunciation:"/brest/",part:105,
   example:"The baby bird has soft feathers on its breast.",
   exampleJa:"そのひな鳥は、胸に柔らかい羽毛を持っている。",
   example2:"He put his hand on his breast and slowly bowed.",
   exampleJa2:"彼は胸に手を当てて、ゆっくりお辞儀をした。",
   etymologyProcess:"breast（ふくらむ）→ 体の前でふくらんでいる部分は…？",
   etymologyConclusion:"breast（ふくらむ）→ 体の前でふっくらとふくらんでいる部分＝胸のふくらみ",
   hook:"水泳の「ブレストストローク」は平泳ぎ、鶏の「むね肉」も breast。",
   relatedWords:[
     {synonym:true,word:"chest",meaning:"胸",breakdown:"ろっ骨に囲まれた部分。breast はその前面のふくらみ"},
     {synonym:true,word:"heart",meaning:"心臓；心",breakdown:"胸の中の臓器。breast は心の宿る場所としても使われる"},
     {synonym:true,word:"bosom",meaning:"胸元，ふところ",breakdown:"抱き寄せる胸元。breast は体の部分としての胸"},
     {synonym:true,word:"breaststroke",meaning:"平泳ぎ",breakdown:"胸を張って水をかく泳ぎ方。breast はその「胸」"}]},

  {id:1047,word:"lung",partOfSpeech:"名詞",meaning:"肺",
   meanings:["名|肺"],
   pronunciation:"/lʌŋ/",part:105,
   example:"Smoking damages the lungs over many long years.",
   exampleJa:"喫煙は、長い年月をかけて肺を傷つける。",
   example2:"He took a deep breath to fill his lungs.",
   exampleJa2:"彼は肺を満たすために、深く息を吸った。",
   etymologyProcess:"lung（軽いもの）→ 水に浮くほど軽い、息をする臓器は…？",
   etymologyConclusion:"lung（軽いもの）→ 空気を含んで水に浮くほど軽い、息をする臓器＝肺",
   hook:"複数形 lungs で使うことが多い。空気で軽い臓器、と覚える。",
   why:"【なぜ】古英語の lungen は、「軽い」を表す語と同じ根から出ています。動物の肺は空気を含んでいて水に浮くほど軽いので、この名がつきました。\n【つながり】英語で食用の肺を lights（軽いもの）と呼ぶのも同じ発想です。light（軽い）と遠い親戚にあたります。",
   relatedWords:[
     {synonym:true,word:"breath",meaning:"息",breakdown:"吸って吐く空気。lung はその空気を出し入れする臓器"},
     {synonym:true,word:"heart",meaning:"心臓",breakdown:"血を送り出す臓器。lung は空気をやりとりする臓器"},
     {word:"light",meaning:"軽い",breakdown:"light（軽い）→ lung と同じ「軽い」の根から出た語"},
     {synonym:true,word:"chest",meaning:"胸",breakdown:"lung が入っている場所。chest はその外側の箱にあたる"}]},

  {id:1048,word:"organ",partOfSpeech:"名詞",meaning:"臓器，器官",
   meanings:["名|臓器，器官","名|オルガン"],
   pronunciation:"/ˈɔːrɡən/",part:105,
   example:"The heart is the most important organ in the body.",
   exampleJa:"心臓は、体の中で最も重要な臓器だ。",
   example2:"Doctors carefully checked every organ during the examination.",
   exampleJa2:"医師たちは検査の間、すべての臓器を注意深く調べた。",
   etymologyProcess:"organ（道具・器官）→ 体の中で決まった働きをする部分は…？",
   etymologyConclusion:"organ（道具・器官）→ 体の中で決まった働きをする道具のような部分＝臓器",
   relatedWords:[
     {word:"organize",meaning:"まとめる，準備する",breakdown:"organ（道具・器官）＋ ize（動詞）→ 器官のようにきちんと働く形にする"},
     {word:"organism",meaning:"生物",breakdown:"organ（道具・器官）→ 器官が組み合わさって生きているもの"},
     {word:"organic",meaning:"有機の；オーガニックの",breakdown:"organ（道具・器官）＋ ic（形容詞）→ 生き物の器官に関わる"},
     {word:"organization",meaning:"組織，団体",breakdown:"organ（道具・器官）＋ ation（名詞）→ 役割を分けて動く集まり"}]},

  {id:1049,word:"vision",partOfSpeech:"名詞",meaning:"視力，視界；展望",
   meanings:["名|視力，視界","名|展望，先を見通す力"],
   pronunciation:"/ˈvɪʒn/",part:105,
   example:"Her vision became blurry after the long study session.",
   exampleJa:"長い勉強の後、彼女の視界はぼやけてしまった。",
   example2:"The new leader shared her vision for the future.",
   exampleJa2:"新しいリーダーは、未来への展望を語った。",
   etymologyProcess:"vis（見る）＋ ion（名詞）→ 目で物を見てとらえる力は…？",
   etymologyConclusion:"vis（見る）＋ ion（名詞）→ 目で物を見てとらえる力そのもの＝視力",
   relatedWords:[
     {word:"visible",meaning:"目に見える",breakdown:"vis（見る）＋ ible（できる）→ 見ることができる"},
     {word:"advise",meaning:"忠告する",breakdown:"ad（〜へ）＋ vis（見る）→ そちらを見るように言ってやる"},
     {word:"revise",meaning:"修正する",breakdown:"re（再び）＋ vis（見る）→ もう一度見直して直す"},
     {word:"supervise",meaning:"監督する",breakdown:"super（上から）＋ vis（見る）→ 上から全体を見張る"}]},

  {id:1050,word:"skeleton",partOfSpeech:"名詞",meaning:"骸骨，骨格",
   meanings:["名|骸骨，骨格"],
   pronunciation:"/ˈskelɪtn/",part:105,
   example:"The museum displays the skeleton of a huge dinosaur.",
   exampleJa:"その博物館は、巨大な恐竜の骸骨を展示している。",
   example2:"A strong skeleton supports the whole human body.",
   exampleJa2:"丈夫な骨格が、人の体全体を支えている。",
   etymologyProcess:"skelet（干からびた）→ 肉が落ちた後に残る骨組みは…？",
   etymologyConclusion:"skelet（干からびた）→ 肉が落ちて干からびた後に残る骨組み＝骸骨",
   hook:"「骨組みだけ」が芯。skeleton key（万能鍵）、skeleton staff（最小人員）。",
   relatedWords:[
     {synonym:true,word:"bone",meaning:"骨",breakdown:"一本一本の骨。skeleton はそれが組み合わさった全体"},
     {synonym:true,word:"frame",meaning:"骨組み，枠",breakdown:"支えるための組み。skeleton は体の骨組みを指す"},
     {synonym:true,word:"skull",meaning:"頭がい骨",breakdown:"頭の骨。skeleton は全身の骨組みぜんたいを指す"},
     {synonym:true,word:"structure",meaning:"構造",breakdown:"組み立て方ぜんたい。skeleton は支える骨組みそのもの"}]},
