  {id:751,word:"indifferent",partOfSpeech:"形容詞",meaning:"無関心で",
   meanings:["形|無関心で"],
   pronunciation:"/ɪnˈdɪfərənt/",part:76,
   example:"He seemed indifferent to the result of the match.",
   exampleJa:"彼はその試合の結果に無関心なようだった。",
   example2:"Do not be indifferent when a classmate needs your help.",
   exampleJa2:"クラスメートが助けを必要としているとき、無関心でいてはいけない。",
   etymologyProcess:"in（否定）＋ dis（離れて）＋ fer（運ぶ）→ 違いを感じないとしたら…？",
   etymologyConclusion:"in（否定）＋ dis（離れて）＋ fer（運ぶ）→ どちらへも心が動かず違いを感じない＝無関心で",
   relatedWords:[
     {word:"different",meaning:"異なった",breakdown:"dis（離れて）＋ fer（運ぶ）→ 別の方向へ離れた"},
     {word:"difference",meaning:"違い",breakdown:"dis（離れて）＋ fer（運ぶ）→ 二つが離れている点"},
     {word:"transfer",meaning:"移す",breakdown:"trans（越えて）＋ fer（運ぶ）→ 境界を越えて運ぶ"},
     {word:"prefer",meaning:"より好む",breakdown:"pre（先に）＋ fer（運ぶ）→ 心が先にそちらへ運ばれる"}]},

  {id:752,word:"punctual",partOfSpeech:"形容詞",meaning:"時間を守る",
   meanings:["形|時間を守る"],
   pronunciation:"/ˈpʌŋktʃuəl/",part:76,
   example:"She is always punctual for our morning club meetings.",
   exampleJa:"彼女は朝の部活の集まりに、いつも時間を守って来る。",
   example2:"Being punctual shows that you respect other people's time.",
   exampleJa2:"時間を守ることは、他人の時間を大切にしている証しになる。",
   etymologyProcess:"punct（点）＋ al（形容詞）→ 時刻という一点にぴたり合うと…？",
   etymologyConclusion:"punct（点）＋ al（形容詞）→ 決められた時刻という一点にぴたりと合わせる＝時間を守る",
   relatedWords:[
     {word:"point",meaning:"点；地点",breakdown:"punct（点）→ とがった先が指し示す一つの点"},
     {word:"appoint",meaning:"任命する",breakdown:"ad（〜へ）＋ punct（点）→ 日時や役目を一点に決める"},
     {word:"punctuation",meaning:"句読点",breakdown:"punct（点）＋ ation（名詞）→ 文に点を打って区切ること"},
     {synonym:true,word:"prompt",meaning:"即座の",breakdown:"待たせずすぐ動く。punctual は決めた時刻ちょうどに来ること"}]},

  {id:753,word:"coward",partOfSpeech:"名詞",meaning:"臆病者",
   meanings:["名|臆病者"],
   pronunciation:"/ˈkaʊərd/",part:76,
   example:"Everyone called him a coward for running away.",
   exampleJa:"逃げ出したことで、みんなは彼を臆病者と呼んだ。",
   example2:"Do not be a coward; tell the teacher the truth.",
   exampleJa2:"臆病者になってはいけない。先生に本当のことを言いなさい。",
   etymologyProcess:"cou（尾）→ 危ないときに尻尾を巻いてしまうのは…？",
   etymologyConclusion:"cou（尾）→ 危険を前にして尻尾を巻き、逃げ出してしまう人＝臆病者",
   relatedWords:[
     {word:"queue",meaning:"列；順番待ち",breakdown:"cou（尾）→ 長く伸びた尻尾のように続く人の列"},
     {word:"cowardly",meaning:"臆病な",breakdown:"cou（尾）＋ ly（〜のような）→ 尻尾を巻いた者のような"},
     {synonym:true,word:"timid",meaning:"おどおどした",breakdown:"気が小さく怖がり。coward は逃げ出す人そのものを指す名詞"},
     {synonym:true,word:"fear",meaning:"恐れ",breakdown:"怖いという気持ち。coward はその気持ちに負けてしまう人"}]},

  {id:754,word:"precise",partOfSpeech:"形容詞",meaning:"寸分たがわない，厳密な",
   meanings:["形|寸分たがわない，厳密な"],
   pronunciation:"/prɪˈsaɪs/",part:76,
   example:"We need the precise time of the train's arrival.",
   exampleJa:"私たちはその列車が到着する厳密な時刻を知る必要がある。",
   example2:"Her drawing of the insect was precise in every detail.",
   exampleJa2:"彼女が描いた昆虫の絵は、どの細部も厳密だった。",
   etymologyProcess:"pre（先に）＋ cis（切る）→ 余分を先に切り落とすと…？",
   etymologyConclusion:"pre（先に）＋ cis（切る）→ 余分なところを前もって切り落とし、きっちり削り出した＝厳密な",
   relatedWords:[
     {word:"scissors",meaning:"はさみ",breakdown:"cis（切る）＋ ors（もの）→ 二枚の刃ではさんで切る道具"},
     {word:"precision",meaning:"正確さ",breakdown:"pre（先に）＋ cis（切る）＋ ion（名詞）→ きっちり切りそろえてある度合い"},
     {word:"concise",meaning:"簡潔な",breakdown:"con（すっかり）＋ cis（切る）→ よけいな言葉をすっかり切り落とした"},
     {synonym:true,word:"exact",meaning:"きっかりの",breakdown:"ぴったり合っている。precise は細かい点まで削り込んだ感じ"}]},

  {id:755,word:"accurate",partOfSpeech:"形容詞",meaning:"誤りのない，正確な",
   meanings:["形|誤りのない，正確な"],
   pronunciation:"/ˈækjərət/",part:76,
   example:"Her answers on the history test were completely accurate.",
   exampleJa:"歴史のテストでの彼女の答えは、まったく誤りのないものだった。",
   example2:"We must keep an accurate record of every experiment.",
   exampleJa2:"私たちはすべての実験について誤りのない記録をつけなければならない。",
   etymologyProcess:"ac（〜へ）＋ cur（気にかける）＋ ate（形容詞）→ 細かく気を配って作ると…？",
   etymologyConclusion:"ac（〜へ）＋ cur（気にかける）＋ ate（形容詞）→ 細かいところまで気を配って仕上げた＝誤りのない",
   relatedWords:[
     {word:"cure",meaning:"治す",breakdown:"cur（気にかける）→ 病む人を気にかけて世話をする"},
     {word:"curious",meaning:"好奇心が強い",breakdown:"cur（気にかける）＋ ious（形容詞）→ 何にでも心を向けて気にする"},
     {word:"secure",meaning:"安全な",breakdown:"se（離れて）＋ cur（気にかける）→ 心配ごとから切り離されている"},
     {synonym:true,word:"correct",meaning:"正しい",breakdown:"答えが合っている。accurate は測った結果の狂いのなさを言う"}]},

  {id:756,word:"proper",partOfSpeech:"形容詞",meaning:"本来あるべき，ふさわしい",
   meanings:["形|本来あるべき，ふさわしい"],
   pronunciation:"/ˈprɑːpər/",part:76,
   example:"Wearing a tie is the proper way to attend the ceremony.",
   exampleJa:"ネクタイを締めるのが、その式に出るのにふさわしいやり方だ。",
   example2:"Put the dictionary back in its proper place on the shelf.",
   exampleJa2:"その辞書を、棚の本来あるべき場所に戻しなさい。",
   etymologyProcess:"propri（自分のもの）→ そのもの本来のあり方に合うと…？",
   etymologyConclusion:"propri（自分のもの）→ そのものが本来持っているあり方にかなっている＝本来あるべき",
   relatedWords:[
     {word:"property",meaning:"財産",breakdown:"propri（自分のもの）＋ ty（名詞）→ 自分のものとして持っているもの"},
     {word:"appropriate",meaning:"適切な",breakdown:"ad（〜へ）＋ propri（自分のもの）→ その場に自分のものとしてぴたり合う"},
     {word:"properly",meaning:"きちんと",breakdown:"propri（自分のもの）＋ ly（副詞）→ 本来のあり方どおりに"},
     {synonym:true,word:"suitable",meaning:"ふさわしい",breakdown:"目的に合っている。proper は本来そうあるべきだという感じ"}]},

  {id:757,word:"tidy",partOfSpeech:"形容詞",meaning:"（部屋や物が）きちんと片づいた",
   meanings:["形|（部屋や物が）きちんと片づいた"],
   pronunciation:"/ˈtaɪdi/",part:76,
   example:"Her desk is always tidy before class begins.",
   exampleJa:"彼女の机は、授業が始まる前はいつもきちんと片づいている。",
   example2:"Please keep the club room tidy after every practice.",
   exampleJa2:"練習のあとは毎回、部室をきちんと片づいた状態に保ってください。",
   etymologyProcess:"tid（時）＋ y（〜な状態の）→ 物があるべき所に収まると…？",
   etymologyConclusion:"tid（時）＋ y（〜な状態の）→ 時にかなって、物があるべき所に収まっている＝片づいた",
   relatedWords:[
     {word:"tide",meaning:"潮の満ち引き",breakdown:"tid（時）→ 決まった時刻に満ちては引く海の水"},
     {word:"untidy",meaning:"散らかった",breakdown:"un（否定）＋ tid（時）＋ y（〜な状態の）→ 整っていない"},
     {synonym:true,word:"neat",meaning:"こぎれいな",breakdown:"見た目がすっきりしている。tidy は片づけて整えた状態を言う"},
     {word:"tidiness",meaning:"整っていること",breakdown:"tid（時）＋ ness（名詞）→ 物があるべき所に収まっている状態"}]},

  {id:758,word:"efficient",partOfSpeech:"形容詞",meaning:"能率的な",
   meanings:["形|能率的な"],
   pronunciation:"/ɪˈfɪʃnt/",part:76,
   example:"This new machine is much more efficient than the old one.",
   exampleJa:"この新しい機械は、古いものよりずっと能率的だ。",
   example2:"We need an efficient way to clean the whole gym.",
   exampleJa2:"体育館全体を掃除する、能率的な方法が必要だ。",
   etymologyProcess:"ef（外へ）＋ fic（作る）＋ ient（〜な）→ 少ない力で結果を外へ出すと…？",
   etymologyConclusion:"ef（外へ）＋ fic（作る）＋ ient（〜な）→ 少ない力でどんどん結果を外へ作り出す＝能率的な",
   relatedWords:[
     {word:"effect",meaning:"効果",breakdown:"ef（外へ）＋ fect（作る）→ 外へ現れ出た結果"},
     {word:"factory",meaning:"工場",breakdown:"fact（作る）＋ ory（場所）→ 物を作り出す場所"},
     {word:"fiction",meaning:"作り話，小説",breakdown:"fic（作る）＋ ion（名詞）→ 頭の中で作り上げた話"},
     {synonym:true,word:"effective",meaning:"効果的な",breakdown:"ねらった結果が出る。efficient は手間や時間の無駄が少ない"}]},

  {id:759,word:"reasonable",partOfSpeech:"形容詞",meaning:"（筋が通っていて）納得できる",
   meanings:["形|（筋が通っていて）納得できる"],
   pronunciation:"/ˈriːznəbl/",part:76,
   example:"His explanation for being late sounded reasonable to everyone.",
   exampleJa:"遅刻した理由についての彼の説明は、みんなに納得できるものに聞こえた。",
   example2:"That shop sells good running shoes at reasonable prices.",
   exampleJa2:"あの店は、よいランニングシューズを納得できる値段で売っている。",
   etymologyProcess:"rat（計算する）＋ able（できる）→ 頭で筋道を計算できるなら…？",
   etymologyConclusion:"rat（計算する）＋ able（できる）→ reason（筋道）を頭で計算して受け入れられる＝納得できる",
   relatedWords:[
     {word:"reason",meaning:"理由",breakdown:"rat（計算する）→ 頭の中で筋道を数え上げたもの"},
     {word:"rate",meaning:"割合",breakdown:"rat（計算する）→ 数えて出した、全体に対する割合"},
     {word:"ratio",meaning:"比",breakdown:"rat（計算する）＋ io（〜にかかわる）→ 数え比べて出した関係"},
     {synonym:true,word:"fair",meaning:"公正な",breakdown:"かたよりがない。reasonable は筋道が通って受け入れられること"}]},

  {id:760,word:"significant",partOfSpeech:"形容詞",meaning:"（見過ごせないほど）重要な",
   meanings:["形|（見過ごせないほど）重要な"],
   pronunciation:"/sɪɡˈnɪfɪkənt/",part:76,
   example:"The team made significant progress during the summer camp.",
   exampleJa:"そのチームは夏合宿の間に、重要な進歩をとげた。",
   example2:"There is a significant difference between the two answers.",
   exampleJa2:"その2つの答えの間には、重要な違いがある。",
   etymologyProcess:"sign（しるし）＋ fic（作る）＋ ant（〜な）→ 意味のあるしるしを作ると…？",
   etymologyConclusion:"sign（しるし）＋ fic（作る）＋ ant（〜な）→ 何かを指し示すしるしになるほど意味がある＝重要な",
   relatedWords:[
     {word:"sign",meaning:"しるし",breakdown:"sign（しるし）→ 見ればその意味が分かる目印"},
     {word:"signal",meaning:"信号",breakdown:"sign（しるし）＋ al（名詞）→ 動きを知らせるしるし"},
     {word:"design",meaning:"設計する",breakdown:"de（下へ）＋ sign（しるし）→ 紙に印をつけて形を描き出す"},
     {synonym:true,word:"important",meaning:"（一般に）大切な",breakdown:"大切である。significant は無視できない意味や差があること"}]},

  {id:761,word:"precious",partOfSpeech:"形容詞",meaning:"貴重な",
   meanings:["形|貴重な"],
   pronunciation:"/ˈpreʃəs/",part:77,
   example:"This old watch is precious to my grandmother.",
   exampleJa:"この古い腕時計は、祖母にとって貴重なものだ。",
   example2:"Time before the exam is precious, so use it well.",
   exampleJa2:"試験前の時間は貴重だから、うまく使いなさい。",
   etymologyProcess:"preci（値打ち）＋ ous（形容詞）→ 代えのきかない値打ちなら…？",
   etymologyConclusion:"preci（値打ち）＋ ous（形容詞）→ 高い値打ちがあって、代えがきかない＝貴重な",
   relatedWords:[
     {word:"price",meaning:"値段",breakdown:"price（値打ち）→ 品物につけられた値打ちの数字"},
     {word:"prize",meaning:"賞",breakdown:"prize（値打ち）→ 値打ちを認めて手渡されるもの"},
     {word:"appreciate",meaning:"～のよさがわかる",breakdown:"ad（〜へ）＋ preci（値打ち）→ 値打ちを正しく見積もる"},
     {synonym:true,word:"valuable",meaning:"価値の高い",breakdown:"お金や役に立つ度合いが高い。precious は代えがきかない感じ"}]},

  {id:762,word:"essential",partOfSpeech:"形容詞",meaning:"不可欠な",
   meanings:["形|不可欠な"],
   pronunciation:"/ɪˈsenʃl/",part:77,
   example:"Water is essential for every living thing on Earth.",
   exampleJa:"水は地球上のすべての生き物にとって不可欠だ。",
   example2:"Daily practice is essential if you want to join the team.",
   exampleJa2:"チームに入りたいなら、毎日の練習が不可欠だ。",
   etymologyProcess:"esse（ある）＋ ial（形容詞）→ 無ければ成り立たないとしたら…？",
   etymologyConclusion:"esse（ある）＋ ial（形容詞）→ それが無いと、そのものが成り立たない＝不可欠な",
   relatedWords:[
     {word:"essence",meaning:"本質",breakdown:"esse（ある）＋ ence（名詞）→ そのものを「ある」ものにしている中心"},
     {word:"interest",meaning:"関心",breakdown:"inter（間の）＋ esse（ある）→ 人と物の間にあって心をつなぐもの"},
     {word:"present",meaning:"いる，ある",breakdown:"pre（先に）＋ esse（ある）→ 目の前にちゃんとある"},
     {synonym:true,word:"necessary",meaning:"必要な",breakdown:"無いと困る。essential はそれ抜きでは成り立たないほど"}]},

  {id:763,word:"fundamental",partOfSpeech:"形容詞",meaning:"根本的な",
   meanings:["形|根本的な"],
   pronunciation:"/ˌfʌndəˈmentl/",part:77,
   example:"Reading every day is a fundamental part of learning English.",
   exampleJa:"毎日読むことは、英語を学ぶうえで根本的な部分だ。",
   example2:"There is a fundamental difference between these two plans.",
   exampleJa2:"この2つの計画の間には、根本的な違いがある。",
   etymologyProcess:"fund（底）＋ ment（名詞）＋ al（形容詞）→ 建物の土台にあたる部分なら…？",
   etymologyConclusion:"fund（底）＋ ment（名詞）＋ al（形容詞）→ 建物の底の土台にあたるほど大もとの＝根本的な",
   relatedWords:[
     {word:"fund",meaning:"基金",breakdown:"fund（底）→ 事業を底から支えるお金"},
     {word:"foundation",meaning:"土台",breakdown:"fund（底）＋ ation（名詞）→ 建物を底で支えている部分"},
     {word:"found",meaning:"設立する",breakdown:"fund（底）→ 底に土台をすえて始める"},
     {synonym:true,word:"basic",meaning:"基本の",breakdown:"いちばんもとになる。fundamental はそれを外すと全部崩れるほど"}]},

  {id:764,word:"outweigh",partOfSpeech:"他動詞",meaning:"～に勝る",
   meanings:["他|～に勝る"],
   pronunciation:"/ˌaʊtˈweɪ/",part:77,
   example:"The benefits of this plan outweigh the costs.",
   exampleJa:"この計画の利点は、かかる費用に勝る。",
   example2:"For me, the joy of running outweighs the pain.",
   exampleJa2:"私にとって、走る喜びは痛みに勝る。",
   etymologyProcess:"out（外へ）＋ weigh（重さを量る）→ 天びんが自分のほうへ傾けば…？",
   etymologyConclusion:"out（外へ）＋ weigh（重さを量る）→ 天びんで相手より重く、外へはみ出すほど傾く＝～に勝る",
   relatedWords:[
     {word:"weigh",meaning:"重さを量る",breakdown:"weigh（重さを量る）→ 天びんに載せて重さを調べる"},
     {word:"weight",meaning:"重さ",breakdown:"weigh（重さを量る）＋ t（名詞）→ 量って出た重さ"},
     {word:"overweight",meaning:"太りすぎの",breakdown:"over（越えて）＋ weigh（重さを量る）＋ t（名詞）→ ふつうの重さを越えた"},
     {synonym:true,word:"exceed",meaning:"上回る",breakdown:"数や限度を超える。outweigh は重さや値打ちで上回ること"}]},

  {id:765,word:"critical",partOfSpeech:"形容詞",meaning:"（結果を左右するほど）重大な",
   meanings:["形|（結果を左右するほど）重大な"],
   pronunciation:"/ˈkrɪtɪkl/",part:77,
   example:"The next ten minutes are critical for the whole team.",
   exampleJa:"次の10分が、チーム全体にとって重大だ。",
   example2:"Sleep plays a critical role in our health.",
   exampleJa2:"睡眠は私たちの健康において重大な役割を果たす。",
   etymologyProcess:"crit（ふるい分ける）＋ al（形容詞）→ 運命を分ける分かれ目なら…？",
   etymologyConclusion:"crit（ふるい分ける）＋ al（形容詞）→ どちらに転ぶかをふるい分ける分かれ目にある＝重大な",
   relatedWords:[
     {word:"critic",meaning:"批評家",breakdown:"crit（ふるい分ける）＋ ic（名詞）→ 良し悪しをふるい分ける人"},
     {word:"criticize",meaning:"批判する",breakdown:"crit（ふるい分ける）＋ ize（動詞）→ 悪いところをふるい分けて言う"},
     {word:"crisis",meaning:"危機",breakdown:"cris（ふるい分ける）→ どちらに転ぶかが分かれる場面"},
     {synonym:true,word:"crucial",meaning:"決定的な",breakdown:"勝負を決める。critical は失敗すれば大ごとになる場面を指す"}]},

  {id:766,word:"serious",partOfSpeech:"形容詞",meaning:"（笑いごとでなく）深刻な",
   meanings:["形|（笑いごとでなく）深刻な"],
   pronunciation:"/ˈsɪriəs/",part:77,
   example:"The doctor said that his injury was quite serious.",
   exampleJa:"医師は、彼のけがはかなり深刻だと言った。",
   example2:"She has a serious problem with her science project.",
   exampleJa2:"彼女は理科の課題で深刻な問題を抱えている。",
   etymologyProcess:"seri（重々しい）＋ ous（形容詞）→ 笑って済ませられない重さなら…？",
   etymologyConclusion:"seri（重々しい）＋ ous（形容詞）→ 軽く笑って済ませられないほど重い＝深刻な",
   relatedWords:[
     {word:"seriously",meaning:"真剣に",breakdown:"seri（重々しい）＋ ly（副詞）→ 重く受け止めるようすで"},
     {synonym:true,word:"earnest",meaning:"まじめな",breakdown:"ふざけずに本気で取り組む。serious は事の重さのほうを指す"},
     {synonym:true,word:"grave",meaning:"由々しい",breakdown:"重くのしかかる。serious は笑って流せない重さを広く指す"},
     {synonym:true,word:"severe",meaning:"厳しい",breakdown:"程度がきつい。serious は結果が重大だというほうを指す"}]},

  {id:767,word:"complex",partOfSpeech:"形容詞",meaning:"（多くの要素がからんで）入り組んだ",
   meanings:["形|（多くの要素がからんで）入り組んだ"],
   pronunciation:"/ˈkɑːmpleks/",part:77,
   example:"The rules of this card game are quite complex.",
   exampleJa:"このカードゲームの規則は、かなり入り組んでいる。",
   example2:"Human feelings are more complex than we usually think.",
   exampleJa2:"人の感情は、ふつう考えるよりも入り組んでいる。",
   etymologyProcess:"com（共に）＋ plex（編み合わせる）→ 糸が何本も編み合わさると…？",
   etymologyConclusion:"com（共に）＋ plex（編み合わせる）→ 多くの糸が共に編み合わさってほどけない＝入り組んだ",
   relatedWords:[
     {word:"complexity",meaning:"複雑さ",breakdown:"com（共に）＋ plex（編み合わせる）＋ ity（名詞）→ 編み合わさり具合"},
     {word:"perplex",meaning:"当惑させる",breakdown:"per（すっかり）＋ plex（編み合わせる）→ 頭の中をすっかり編み絡ませる"},
     {synonym:true,word:"complicated",meaning:"ややこしい",breakdown:"手順が多くて面倒。complex は要素どうしの絡み合いを言う"},
     {synonym:true,word:"difficult",meaning:"難しい",breakdown:"やさしくない。complex は難しさの原因が絡み合いにあること"}]},

  {id:768,word:"complicated",partOfSpeech:"形容詞",meaning:"（手順や事情が）ややこしい",
   meanings:["形|（手順や事情が）ややこしい"],
   pronunciation:"/ˈkɑːmplɪkeɪtɪd/",part:77,
   example:"The rules for the school festival are far too complicated.",
   exampleJa:"学園祭の規則は、あまりにもややこしい。",
   example2:"Do not make this simple task any more complicated.",
   exampleJa2:"この簡単な作業を、これ以上ややこしくしないで。",
   etymologyProcess:"com（共に）＋ pli（折る）＋ ate（動詞）→ 何重にも折り重なると…？",
   etymologyConclusion:"com（共に）＋ pli（折る）＋ ate（動詞）→ 紙が何重にも折り重なり、開くのに手間がかかる＝ややこしい",
   relatedWords:[
     {word:"apply",meaning:"応用する",breakdown:"ad（〜へ）＋ pli（折る）→ 折り重ねて対象にぴたりと当てる"},
     {word:"reply",meaning:"返事をする",breakdown:"re（戻す）＋ pli（折る）→ 相手のほうへ折り返す"},
     {word:"multiply",meaning:"かけ算する",breakdown:"multi（多く）＋ pli（折る）→ 何重にも折り重ねて数を増やす"},
     {synonym:true,word:"tricky",meaning:"やっかいな",breakdown:"扱いにくい。complicated は手順が折り重なって多いこと"}]},

  {id:769,word:"delicate",partOfSpeech:"形容詞",meaning:"繊細な",
   meanings:["形|繊細な"],
   pronunciation:"/ˈdelɪkət/",part:77,
   example:"The delicate glass cup broke when she dropped it.",
   exampleJa:"その繊細なガラスのコップは、彼女が落としたときに割れた。",
   example2:"This is a delicate problem, so please speak carefully.",
   exampleJa2:"これは繊細な問題なので、慎重に話してください。",
   etymologyProcess:"delic（うっとりさせる）→ 上等で壊れやすいほど細やかなら…？",
   etymologyConclusion:"delic（うっとりさせる）→ うっとりするほど上等で、触れれば壊れそうに細やか＝繊細な",
   relatedWords:[
     {word:"delicious",meaning:"おいしい",breakdown:"delic（うっとりさせる）＋ ous（形容詞）→ うっとりするほど味がよい"},
     {word:"delight",meaning:"大喜び",breakdown:"delic（うっとりさせる）→ 心をうっとりさせてくれるもの"},
     {synonym:true,word:"fragile",meaning:"壊れやすい",breakdown:"力を加えると割れる。delicate は細やかで気を使う感じ"},
     {synonym:true,word:"sensitive",meaning:"敏感な",breakdown:"小さな刺激にも反応する。delicate は作りが細やかで傷つきやすい"}]},

  {id:770,word:"plain",partOfSpeech:"形容詞",meaning:"飾りけのない",
   meanings:["形|飾りけのない"],
   pronunciation:"/pleɪn/",part:77,
   example:"She wore a plain white shirt to the job interview.",
   exampleJa:"彼女は就職の面接に、飾りけのない白いシャツを着ていった。",
   example2:"He gave us a plain answer without making any excuses.",
   exampleJa2:"彼は言い訳もせず、飾りけのない率直な答えをくれた。",
   etymologyProcess:"plain（平らにする）→ でこぼこも飾りもない見た目なら…？",
   etymologyConclusion:"plain（平らにする）→ でこぼこも飾りもなく、そのまま平らに見通せる＝飾りけのない",
   relatedWords:[
     {word:"explain",meaning:"説明する",breakdown:"ex（外へ）＋ plain（平らにする）→ ややこしい話を平らにならして外に出す"},
     {word:"plane",meaning:"平面；飛行機",breakdown:"plane（平らにする）→ 平らな面。翼の平らな面から飛行機"},
     {word:"plainly",meaning:"はっきりと",breakdown:"plain（平らにする）＋ ly（副詞）→ でこぼこなく見通せるように"},
     {synonym:true,word:"simple",meaning:"簡素な",breakdown:"込み入っていない。plain は飾りがなく、ありのままなこと"}]},

  {id:771,word:"obvious",partOfSpeech:"形容詞",meaning:"（誰の目にも）明白な",
   meanings:["形|（誰の目にも）明白な"],
   pronunciation:"/ˈɑːbviəs/",part:78,
   example:"It is obvious that he forgot his homework again.",
   exampleJa:"彼がまた宿題を忘れたのは明白だ。",
   example2:"The answer was so obvious that everyone shouted it at once.",
   exampleJa2:"その答えはあまりに明白だったので、みんなが一斉に叫んだ。",
   etymologyProcess:"ob（〜に向かって）＋ via（道）＋ ous（形容詞）→ 道の真ん中にあれば…？",
   etymologyConclusion:"ob（〜に向かって）＋ via（道）＋ ous（形容詞）→ 通る道の真ん中にあって、いやでも目に入る＝明白な",
   relatedWords:[
     {word:"via",meaning:"～を経由して",breakdown:"via（道）→ その道を通って行く"},
     {word:"previous",meaning:"前の",breakdown:"pre（先に）＋ via（道）→ 先にその道を通っている"},
     {word:"deviate",meaning:"それる",breakdown:"de（離して）＋ via（道）＋ ate（動詞）→ 決まった道から外れていく"},
     {synonym:true,word:"clear",meaning:"はっきりした",breakdown:"よく見える。obvious は説明されなくても分かるほど"}]},

  {id:772,word:"remarkable",partOfSpeech:"形容詞",meaning:"注目すべき",
   meanings:["形|注目すべき"],
   pronunciation:"/rɪˈmɑːrkəbl/",part:78,
   example:"Her performance in the long race was truly remarkable.",
   exampleJa:"長いレースでの彼女の走りは、本当に注目すべきものだった。",
   example2:"The little town has made remarkable progress in ten years.",
   exampleJa2:"その小さな町は、10年で注目すべき進歩をとげた。",
   etymologyProcess:"re（何度も）＋ mark（しるし）＋ able（できる）→ 何度も心に印をつけたくなると…？",
   etymologyConclusion:"re（何度も）＋ mark（しるし）＋ able（できる）→ 何度も心にしるしをつけたくなる＝注目すべき",
   relatedWords:[
     {word:"mark",meaning:"しるし",breakdown:"mark（しるし）→ 目で見て分かるようにつけた印"},
     {word:"remark",meaning:"発言",breakdown:"re（何度も）＋ mark（しるし）→ 心に留めたことを口に出す"},
     {word:"landmark",meaning:"目印になる建物",breakdown:"land（土地）＋ mark（しるし）→ その土地の目印になるもの"},
     {synonym:true,word:"impressive",meaning:"印象的な",breakdown:"強く心に残る。remarkable はわざわざ口にしたくなるほど目立つこと"}]},

  {id:773,word:"outstanding",partOfSpeech:"形容詞",meaning:"傑出した",
   meanings:["形|傑出した"],
   pronunciation:"/ˌaʊtˈstændɪŋ/",part:78,
   example:"His outstanding performance on stage won the first prize.",
   exampleJa:"舞台での彼の傑出した演技が、一等賞を取った。",
   example2:"She is an outstanding player on our basketball team.",
   exampleJa2:"彼女は私たちのバスケットボール部で傑出した選手だ。",
   etymologyProcess:"out（外へ）＋ sta（立つ）＋ ing（形容詞）→ 列から一人だけ外へ出て立つと…？",
   etymologyConclusion:"out（外へ）＋ sta（立つ）＋ ing（形容詞）→ 並んだ中から一人だけ外へ抜け出て立つ＝傑出した",
   relatedWords:[
     {word:"stand",meaning:"立つ",breakdown:"sta（立つ）→ 足で地面をとらえて立つ"},
     {word:"statue",meaning:"像",breakdown:"sta（立つ）＋ ue（もの）→ 立たせてある人の形"},
     {word:"instant",meaning:"即座の",breakdown:"in（中に）＋ sta（立つ）→ すぐそこに立っている、その一瞬の"},
     {synonym:true,word:"excellent",meaning:"優れた",breakdown:"とてもよい。outstanding はまわりから頭一つ抜けていること"}]},

  {id:774,word:"various",partOfSpeech:"形容詞",meaning:"さまざまな",
   meanings:["形|さまざまな"],
   pronunciation:"/ˈveriəs/",part:78,
   example:"The library has books on various subjects for students.",
   exampleJa:"図書館には、生徒向けのさまざまな科目の本がある。",
   example2:"We tried various ways to solve that difficult problem.",
   exampleJa2:"私たちはその難しい問題を解くために、さまざまな方法を試した。",
   etymologyProcess:"vari（変わる）＋ ous（形容詞）→ 一つずつ違って同じでないなら…？",
   etymologyConclusion:"vari（変わる）＋ ous（形容詞）→ 一つ一つが少しずつ変わっていて同じでない＝さまざまな",
   relatedWords:[
     {word:"vary",meaning:"さまざまに変わる",breakdown:"vari（変わる）→ 中身が少しずつ移り変わる"},
     {word:"variety",meaning:"多様さ",breakdown:"vari（変わる）＋ ety（名詞）→ 変化に富んでいること"},
     {word:"invariable",meaning:"変わることのない",breakdown:"in（否定）＋ vari（変わる）＋ able（できる）→ どうやっても変わらない"},
     {synonym:true,word:"several",meaning:"いくつかの",breakdown:"数がいくつかある。various は中身の種類が違うことを言う"}]},

  {id:775,word:"diversity",partOfSpeech:"名詞",meaning:"多様性",
   meanings:["名|多様性"],
   pronunciation:"/daɪˈvɜːrsəti/",part:78,
   example:"Our school celebrates the diversity of its many students.",
   exampleJa:"私たちの学校は、大勢の生徒の多様性を大切にしている。",
   example2:"Diversity of opinion makes a class discussion much more interesting.",
   exampleJa2:"意見の多様性は、授業の話し合いをずっと面白くする。",
   etymologyProcess:"di（離れて）＋ vers（回る）＋ ity（名詞）→ めいめい別の方を向くと…？",
   etymologyConclusion:"di（離れて）＋ vers（回る）＋ ity（名詞）→ めいめいが別の方へ向き直っている状態＝多様性",
   relatedWords:[
     {word:"diverse",meaning:"多様な",breakdown:"di（離れて）＋ vers（回る）→ それぞれ別の方を向いている"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ 向きを後ろへ回す"},
     {word:"university",meaning:"大学",breakdown:"uni（1つ）＋ vers（回る）＋ ity（名詞）→ 学問が一つに回り集まった場"},
     {synonym:true,word:"variety",meaning:"多様さ",breakdown:"種類の多さ。diversity は違う者どうしが集まっている状態"}]},

  {id:776,word:"sort",partOfSpeech:"名詞",meaning:"（くだけた言い方で）種類，たぐい",
   meanings:["名|（くだけた言い方で）種類，たぐい"],
   pronunciation:"/sɔːrt/",part:78,
   example:"What sort of music do you listen to after school?",
   exampleJa:"放課後はどんな種類の音楽を聴きますか。",
   example2:"This sort of mistake happens to everyone at first.",
   exampleJa2:"この種類の間違いは、最初はだれにでも起こる。",
   etymologyProcess:"sort（くじで決まった取り分）→ 同じ組に分けられたまとまりは…？",
   etymologyConclusion:"sort（くじで決まった取り分）→ くじで分けられ、同じ組に入るひとまとまり＝種類",
   relatedWords:[
     {word:"sorcerer",meaning:"魔法使い",breakdown:"sort（くじで決まった取り分）＋ er（人）→ くじを引いて運命を操る人"},
     {word:"assorted",meaning:"詰め合わせの",breakdown:"ad（〜へ）＋ sort（くじで決まった取り分）→ 種類を寄せ集めた"},
     {synonym:true,word:"kind",meaning:"種類",breakdown:"同じ性質のまとまり。sort は「どんな類いか」と問うときに使う"},
     {synonym:true,word:"type",meaning:"型",breakdown:"典型となる型。sort はそれよりくだけた言い方"}]},

  {id:777,word:"marvelous",partOfSpeech:"形容詞",meaning:"驚くほどすばらしい",
   meanings:["形|驚くほどすばらしい"],
   pronunciation:"/ˈmɑːrvələs/",part:78,
   example:"We had a marvelous time at the summer festival.",
   exampleJa:"私たちは夏祭りで、驚くほどすばらしい時間を過ごした。",
   example2:"The view from the mountain top was simply marvelous.",
   exampleJa2:"山頂からの眺めは、ただただ驚くほどすばらしかった。",
   etymologyProcess:"mir（驚く）＋ ous（形容詞）→ 目を見張るほどの出来ばえなら…？",
   etymologyConclusion:"mir（驚く）＋ ous（形容詞）→ 目を見張って声も出ないほどの出来ばえ＝驚くほどすばらしい",
   relatedWords:[
     {word:"miracle",meaning:"奇跡",breakdown:"mir（驚く）＋ cle（もの）→ 目を見張るような出来事"},
     {word:"mirror",meaning:"鏡",breakdown:"mir（驚く）→ 自分の姿を映して見せる道具"},
     {word:"admire",meaning:"称賛する",breakdown:"ad（〜へ）＋ mir（驚く）→ 心を向けて驚き、感心する"},
     {synonym:true,word:"wonderful",meaning:"すばらしい",breakdown:"とてもよい。marvelous は驚きが混じったほめ方"}]},

  {id:778,word:"active",partOfSpeech:"形容詞",meaning:"積極的な",
   meanings:["形|積極的な"],
   pronunciation:"/ˈæktɪv/",part:78,
   example:"He is very active in the volunteer club at school.",
   exampleJa:"彼は学校のボランティア部でとても積極的だ。",
   example2:"She became active in the student council after the summer.",
   exampleJa2:"彼女は夏のあと、生徒会で積極的に活動するようになった。",
   etymologyProcess:"act（追い立てる）＋ ive（形容詞）→ 自分から体を動かしだすなら…？",
   etymologyConclusion:"act（追い立てる）＋ ive（形容詞）→ 自分で自分を追い立てて、どんどん動く＝積極的な",
   relatedWords:[
     {word:"act",meaning:"行動する",breakdown:"act（追い立てる）→ 自分を前へ追い立てて動く"},
     {word:"action",meaning:"行動",breakdown:"act（追い立てる）＋ ion（名詞）→ 実際に動くこと"},
     {word:"react",meaning:"反応する",breakdown:"re（戻す）＋ act（追い立てる）→ 受けた動きを相手へ押し返す"},
     {synonym:true,word:"eager",meaning:"熱心な",breakdown:"したくてたまらない。active は実際に体を動かしていること"}]},

  {id:779,word:"positive",partOfSpeech:"形容詞",meaning:"前向きな",
   meanings:["形|前向きな"],
   pronunciation:"/ˈpɑːzətɪv/",part:78,
   example:"Try to keep a positive attitude before the big game.",
   exampleJa:"大事な試合の前は、前向きな態度を保つようにしなさい。",
   example2:"Her positive words helped me through a very hard week.",
   exampleJa2:"彼女の前向きな言葉が、とてもつらい一週間を乗り切る助けになった。",
   etymologyProcess:"pos（置く）＋ itive（形容詞）→ 良い面のほうへ心を置けば…？",
   etymologyConclusion:"pos（置く）＋ itive（形容詞）→ 良い面のほうへ気持ちをしっかり置く＝前向きな",
   relatedWords:[
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ition（名詞）→ 置かれている場所"},
     {word:"oppose",meaning:"～に反対する",breakdown:"op（向かい合って）＋ pos（置く）→ 向かい側に身を置く"},
     {word:"compose",meaning:"構成する",breakdown:"com（共に）＋ pos（置く）→ いくつかを共に置いて組み立てる"},
     {synonym:true,word:"hopeful",meaning:"希望に満ちた",breakdown:"よい結果を望む。positive は考え方そのものが明るいこと"}]},

  {id:780,word:"pure",partOfSpeech:"形容詞",meaning:"純粋な",
   meanings:["形|純粋な"],
   pronunciation:"/pjʊr/",part:78,
   example:"This bottle contains pure water from a mountain spring.",
   exampleJa:"このびんには、山の泉から取った純粋な水が入っている。",
   example2:"Winning that game was pure joy for the whole team.",
   exampleJa2:"その試合に勝ったことは、チーム全体にとって純粋な喜びだった。",
   etymologyProcess:"pure（きよめた）→ 混ぜ物をすっかり取り去ると…？",
   etymologyConclusion:"pure（きよめた）→ 混ぜ物をすっかり取り去って、そのものだけにした＝純粋な",
   relatedWords:[
     {word:"purely",meaning:"純粋に",breakdown:"pure（きよめた）＋ ly（副詞）→ 混じりけのないようすで"},
     {word:"purify",meaning:"浄化する",breakdown:"pure（きよめた）＋ ify（する）→ 混ぜ物を取り除いてきれいにする"},
     {word:"purge",meaning:"取り除く",breakdown:"pure（きよめた）→ 汚れを追い立てて外へ払い、きれいにする"},
     {synonym:true,word:"clean",meaning:"きれいな",breakdown:"汚れがない。pure は他のものが混じっていないこと"}]},

  {id:781,word:"steady",partOfSpeech:"形容詞",meaning:"（ぐらつかず）着実な",
   meanings:["形|（ぐらつかず）着実な"],
   pronunciation:"/ˈstedi/",part:79,
   example:"He made steady progress in math this semester.",
   exampleJa:"彼は今学期、数学で着実な進歩をとげた。",
   example2:"Keep a steady pace and you will finish the race.",
   exampleJa2:"着実なペースを保てば、そのレースを走り切れるだろう。",
   etymologyProcess:"stead（立つ）＋ y（〜な状態の）→ ぐらつかず同じ調子を保つなら…？",
   etymologyConclusion:"stead（立つ）＋ y（〜な状態の）→ 足場にしっかり立ち、ぐらつかず同じ調子を保つ＝着実な",
   relatedWords:[
     {word:"instead",meaning:"代わりに",breakdown:"in（中へ）＋ stead（立つ）→ その場所に代わって立つ"},
     {word:"steadily",meaning:"着実に",breakdown:"stead（立つ）＋ ly（副詞）→ ぐらつかない足取りで"},
     {synonym:true,word:"constant",meaning:"変わらない",breakdown:"ずっと同じ。steady はぐらつかずに続く調子のこと"},
     {synonym:true,word:"firm",meaning:"しっかりした",breakdown:"ぐらつかない。steady は進み方が一定であることを言う"}]},

  {id:782,word:"flexible",partOfSpeech:"形容詞",meaning:"柔軟な",
   meanings:["形|柔軟な"],
   pronunciation:"/ˈfleksəbl/",part:79,
   example:"Our schedule is flexible, so we can change it later.",
   exampleJa:"私たちの予定は柔軟なので、あとで変更することができる。",
   example2:"Gymnasts must keep their bodies flexible every single day.",
   exampleJa2:"体操選手は毎日欠かさず、体を柔軟に保たなければならない。",
   etymologyProcess:"flex（曲げる）＋ ible（できる）→ 折れずに曲げられるなら…？",
   etymologyConclusion:"flex（曲げる）＋ ible（できる）→ 折れずに曲がり、形をその場に合わせられる＝柔軟な",
   relatedWords:[
     {word:"reflect",meaning:"～を反射する",breakdown:"re（後ろへ）＋ flect（曲げる）→ 光を後ろへ曲げ返す"},
     {word:"reflex",meaning:"反射",breakdown:"re（後ろへ）＋ flex（曲げる）→ 刺激が体で曲げ返される動き"},
     {word:"flexibility",meaning:"柔軟さ",breakdown:"flex（曲げる）＋ ible（できる）＋ ity（名詞）→ 曲げられる度合い"},
     {synonym:true,word:"elastic",meaning:"伸び縮みする",breakdown:"引っぱると伸びて戻る。flexible は折れずに曲がること"}]},

  {id:783,word:"ripe",partOfSpeech:"形容詞",meaning:"（果物が）熟した",
   meanings:["形|（果物が）熟した"],
   pronunciation:"/raɪp/",part:79,
   example:"These peaches are ripe enough to eat right now.",
   exampleJa:"これらの桃は、今すぐ食べられるほど熟している。",
   example2:"Wait until the tomatoes in the garden are fully ripe.",
   exampleJa2:"庭のトマトが十分に熟すまで待ちなさい。",
   etymologyProcess:"rip（刈り入れる）→ 刈り入れてよいほど育ちきると…？",
   etymologyConclusion:"rip（刈り入れる）→ 刈り入れてよいほど、実が十分に育ちきった＝熟した",
   relatedWords:[
     {word:"reap",meaning:"刈り取る",breakdown:"rip（刈り入れる）→ 実った作物を刈り入れる"},
     {word:"ripen",meaning:"熟す",breakdown:"rip（刈り入れる）＋ en（〜にする）→ 刈り入れられる状態になる"},
     {synonym:true,word:"mature",meaning:"成熟した",breakdown:"十分に育っている。ripe は果物が食べごろになったこと"},
     {synonym:true,word:"ready",meaning:"準備ができた",breakdown:"用意が整った。ripe は実が食べごろに育ちきったこと"}]},

  {id:784,word:"stable",partOfSpeech:"形容詞",meaning:"安定した",
   meanings:["形|安定した"],
   pronunciation:"/ˈsteɪbl/",part:79,
   example:"The ladder is stable, so you can climb it safely.",
   exampleJa:"そのはしごは安定しているので、安全に登ることができる。",
   example2:"His grades have been stable since he changed his habits.",
   exampleJa2:"習慣を変えてから、彼の成績は安定している。",
   etymologyProcess:"sta（立つ）＋ able（できる）→ 揺すられても立ち続けられるなら…？",
   etymologyConclusion:"sta（立つ）＋ able（できる）→ 揺すられても同じ場所に立ち続けられる＝安定した",
   relatedWords:[
     {word:"station",meaning:"駅",breakdown:"sta（立つ）＋ ion（名詞）→ 列車が立ち止まる場所"},
     {word:"establish",meaning:"～を確立する",breakdown:"sta（立つ）＋ ish（〜にする）→ 倒れないように、しっかり立たせる"},
     {word:"stability",meaning:"安定",breakdown:"sta（立つ）＋ able（できる）＋ ity（名詞）→ 立ち続けられる度合い"},
     {synonym:true,word:"steady",meaning:"着実な",breakdown:"ぐらつかず一定。stable は倒れずに同じ状態を保てること"}]},

  {id:785,word:"negative",partOfSpeech:"形容詞",meaning:"否定的な",
   meanings:["形|否定的な"],
   pronunciation:"/ˈneɡətɪv/",part:79,
   example:"His negative comments discouraged almost everyone in the group.",
   exampleJa:"彼の否定的な意見は、グループのほとんど全員をがっかりさせた。",
   example2:"Try not to be negative about your own new ideas.",
   exampleJa2:"自分の新しい考えについて、否定的にならないようにしなさい。",
   etymologyProcess:"neg（いいえと言う）＋ ative（形容詞）→ 何でも打ち消す側に立つなら…？",
   etymologyConclusion:"neg（いいえと言う）＋ ative（形容詞）→ 何を聞いても「いいえ」と打ち消す側に立つ＝否定的な",
   relatedWords:[
     {word:"deny",meaning:"～を否定する",breakdown:"de（強く）＋ ny（いいえと言う）→ 「そうではない」と強く言う"},
     {word:"neglect",meaning:"～を怠る",breakdown:"neg（いいえと言う）＋ lect（拾う）→ 拾わないと言って放っておく"},
     {synonym:true,word:"pessimistic",meaning:"悲観的な",breakdown:"悪いほうに考える。negative はまず打ち消す構えを取ること"},
     {synonym:true,word:"doubtful",meaning:"疑わしい",breakdown:"信じきれない。negative は初めから打ち消す構えのこと"}]},

  {id:786,word:"vague",partOfSpeech:"形容詞",meaning:"曖昧な",
   meanings:["形|曖昧な"],
   pronunciation:"/veɪɡ/",part:79,
   example:"His answer was too vague to help us decide anything.",
   exampleJa:"彼の答えは曖昧すぎて、私たちが何かを決める助けにならなかった。",
   example2:"I have only a vague memory of that hot summer.",
   exampleJa2:"あの暑い夏のことは、曖昧な記憶しか残っていない。",
   etymologyProcess:"vag（さまよう）→ 意味がふらふら定まらないなら…？",
   etymologyConclusion:"vag（さまよう）→ 意味がふらふらさまよって、どこにも定まらない＝曖昧な",
   relatedWords:[
     {word:"vagabond",meaning:"放浪者",breakdown:"vag（さまよう）→ 住む所を決めず歩き回る人"},
     {word:"vaguely",meaning:"漠然と",breakdown:"vag（さまよう）＋ ly（副詞）→ 輪郭が定まらないようすで"},
     {word:"extravagant",meaning:"度を越した",breakdown:"extra（範囲の外へ）＋ vag（さまよう）→ 枠の外までさまよい出る"},
     {synonym:true,word:"unclear",meaning:"はっきりしない",breakdown:"よく分からない。vague は輪郭そのものがぼやけていること"}]},

  {id:787,word:"weird",partOfSpeech:"形容詞",meaning:"変な",
   meanings:["形|変な"],
   pronunciation:"/wɪrd/",part:79,
   example:"A weird noise came from the old music room upstairs.",
   exampleJa:"上の階の古い音楽室から、変な物音が聞こえてきた。",
   example2:"It feels weird to wear our uniform on a Sunday.",
   exampleJa2:"日曜日に制服を着るのは変な感じがする。",
   hook:"「なんか変」というくだけた語。strange より、気味の悪さや違和感が強い。",
   etymologyProcess:"weird（運命）→ 人の力を越えた気配がすると…？",
   etymologyConclusion:"weird（運命）→ 人の力を越えた運命じみた気配がして、ふつうでない＝変な",
   relatedWords:[
     {synonym:true,word:"strange",meaning:"見慣れない",breakdown:"よそから来た、見慣れない。weird は不気味さが強く出る"},
     {synonym:true,word:"odd",meaning:"奇妙な",breakdown:"半端で割り切れない感じ。weird はぞくっとする気味悪さを伴う"},
     {synonym:true,word:"creepy",meaning:"ぞっとする",breakdown:"ぞわっとさせる。weird は不思議さのほうが前に出る"},
     {synonym:true,word:"unusual",meaning:"ふつうでない",breakdown:"めったにない。weird はそこに薄気味悪さが加わる"}]},

  {id:788,word:"rough",partOfSpeech:"形容詞",meaning:"（表面が）ざらざらした，粗い",
   meanings:["形|（表面が）ざらざらした，粗い"],
   pronunciation:"/rʌf/",part:79,
   example:"The surface of this old stone feels rough to the touch.",
   exampleJa:"この古い石の表面は、触るとざらざらして粗い。",
   example2:"The rough wall scratched my hand when I touched it.",
   exampleJa2:"そのざらざらした壁は、触ったとき私の手をひっかいた。",
   etymologyProcess:"rough（ざらざらした）→ 表面が整えられていないなら…？",
   etymologyConclusion:"rough（ざらざらした）→ 表面がざらついて、きちんと整えられていない＝粗い",
   relatedWords:[
     {word:"roughly",meaning:"おおよそ",breakdown:"rough（ざらざらした）＋ ly（副詞）→ 細かく整えず、ざっと"},
     {synonym:true,word:"uneven",meaning:"平らでない",breakdown:"高さがそろわない。rough は手ざわりのざらつきを指す"},
     {synonym:true,word:"coarse",meaning:"きめの粗い",breakdown:"粒が大きい。rough は触った感じのざらつきを言う"},
     {synonym:true,word:"bumpy",meaning:"でこぼこの",breakdown:"上下に揺れるほど凸凹。rough は表面のざらつきも含む"}]},

  {id:789,word:"severe",partOfSpeech:"形容詞",meaning:"容赦なく厳しい",
   meanings:["形|容赦なく厳しい"],
   pronunciation:"/sɪˈvɪr/",part:79,
   example:"That teacher is severe with students who arrive late.",
   exampleJa:"あの先生は、遅刻して来る生徒に容赦なく厳しい。",
   example2:"Winters in this small town are severe and very long.",
   exampleJa2:"この小さな町の冬は容赦なく厳しく、とても長い。",
   etymologyProcess:"sever（厳格な）→ 手加減がいっさいないとしたら…？",
   etymologyConclusion:"sever（厳格な）→ 手加減をいっさいせず、容赦なく相手に当たる＝容赦なく厳しい",
   relatedWords:[
     {word:"severely",meaning:"厳しく",breakdown:"sever（厳格な）＋ ly（副詞）→ 手加減なしのようすで"},
     {word:"persevere",meaning:"やり抜く",breakdown:"per（すっかり）＋ sever（厳格な）→ 自分に厳しいまま最後までやり通す"},
     {synonym:true,word:"strict",meaning:"厳しい",breakdown:"規則を曲げない。severe は程度そのものが容赦なくきついこと"},
     {synonym:true,word:"harsh",meaning:"手厳しい",breakdown:"耳や肌にきつい。severe は結果の重さまで含めて言う"}]},

  {id:790,word:"passive",partOfSpeech:"形容詞",meaning:"受動的な",
   meanings:["形|受動的な"],
   pronunciation:"/ˈpæsɪv/",part:79,
   example:"Many students stay passive during long group discussions.",
   exampleJa:"多くの生徒は、長いグループ討論の間ずっと受動的なままだ。",
   example2:"Watching videos is a passive way to spend your evening.",
   exampleJa2:"動画を見ることは、夜の過ごし方としては受動的だ。",
   etymologyProcess:"pat（耐える）＋ ive（形容詞）→ されるままに耐えるだけなら…？",
   etymologyConclusion:"pat（耐える）＋ ive（形容詞）→ 自分からは動かず、されるままに耐えている＝受動的な",
   relatedWords:[
     {word:"patient",meaning:"我慢強い；患者",breakdown:"pat（耐える）＋ ient（〜な）→ 痛みにじっと耐えている"},
     {word:"passion",meaning:"情熱",breakdown:"pat（耐える）＋ ion（名詞）→ 耐えがたいほど胸に迫る思い"},
     {synonym:true,word:"quiet",meaning:"おとなしい",breakdown:"静かにしている。passive は自分から動こうとしないこと"},
     {synonym:true,word:"inactive",meaning:"活動していない",breakdown:"動いていない。passive は他から働きかけられるのを待つ姿勢"}]},

  {id:791,word:"vain",partOfSpeech:"形容詞",meaning:"（努力が）むだな",
   meanings:["形|（努力が）むだな"],
   pronunciation:"/veɪn/",part:80,
   example:"All our efforts to find the lost key were in vain.",
   exampleJa:"なくした鍵を見つけようとした私たちの努力は、すべてむだだった。",
   example2:"He made a vain attempt to open the locked door.",
   exampleJa2:"彼は鍵のかかった扉を開けようと、むだな試みをした。",
   etymologyProcess:"vain（空の）→ 中身が空っぽで何も実らないなら…？",
   etymologyConclusion:"vain（空の）→ 中身が空っぽで、何の実りももたらさない＝むだな",
   relatedWords:[
     {word:"vanish",meaning:"消える",breakdown:"vain（空の）＋ ish（動詞をつくる）→ 空っぽになって消えてしまう"},
     {word:"vanity",meaning:"虚栄心",breakdown:"vain（空の）＋ ity（名詞）→ 中身のない見えを張る心"},
     {synonym:true,word:"fruitless",meaning:"実を結ばない",breakdown:"何も生まない。vain は努力がむだに終わることを言う"},
     {synonym:true,word:"useless",meaning:"役に立たない",breakdown:"役目を果たさない。vain は努力が実を結ばないこと"}]},

  {id:792,word:"fake",partOfSpeech:"形容詞",meaning:"偽の",
   meanings:["形|偽の"],
   pronunciation:"/feɪk/",part:80,
   example:"She bought a fake brand bag at a street shop.",
   exampleJa:"彼女は路上の店で、偽のブランドバッグを買った。",
   example2:"Please do not share that fake photo with your friends.",
   exampleJa2:"その偽の写真を、友達に広めないでください。",
   hook:"語源ははっきりしないが、「フェイクニュース」「フェイクファー」と結びつけると覚えやすい。",
   etymologyProcess:"fake（こしらえる）→ 本物らしく見せかけて作ると…？",
   etymologyConclusion:"fake（こしらえる）→ 本物らしく見せかけて、人をだますためにこしらえた＝偽の",
   relatedWords:[
     {synonym:true,word:"false",meaning:"誤った",breakdown:"事実と違う。fake は本物に似せて作った物のほうを指す"},
     {synonym:true,word:"artificial",meaning:"人工的な",breakdown:"人の手で作った。fake は本物だと偽る狙いがあること"},
     {synonym:true,word:"imitation",meaning:"模造品",breakdown:"まねて作った物。fake は本物だと思わせる狙いが強い"},
     {synonym:true,word:"counterfeit",meaning:"偽造の",breakdown:"紙幣や書類を似せて作る。fake はもっと広く日常で使う"}]},

  {id:793,word:"risky",partOfSpeech:"形容詞",meaning:"（やってみると）危険な，一か八かの",
   meanings:["形|（やってみると）危険な，一か八かの"],
   pronunciation:"/ˈrɪski/",part:80,
   example:"Crossing that old wooden bridge alone is very risky.",
   exampleJa:"あの古い木の橋を一人で渡るのは、とても危険だ。",
   example2:"It would be risky to go hiking in this weather.",
   exampleJa2:"この天気でハイキングに行くのは危険だろう。",
   etymologyProcess:"risk（切り立った岩）＋ y（〜な状態の）→ 岩の間を船で抜けるようなら…？",
   etymologyConclusion:"risk（切り立った岩）＋ y（〜な状態の）→ 切り立った岩の間を船で抜けるような＝危険な",
   relatedWords:[
     {word:"risk",meaning:"危険",breakdown:"risk（切り立った岩）→ 船をこわしかねない、海の岩"},
     {synonym:true,word:"dangerous",meaning:"危ない",breakdown:"害を受けるおそれがある。risky は自分で選んで踏み込む危うさ"},
     {synonym:true,word:"unsafe",meaning:"安全でない",breakdown:"守られていない。risky は失敗するかもしれない賭けの感じ"},
     {synonym:true,word:"reckless",meaning:"向こう見ずな",breakdown:"危険を考えず突っ込む。risky は事柄のほうが危ういこと"}]},

  {id:794,word:"odd",partOfSpeech:"形容詞",meaning:"奇妙な",
   meanings:["形|奇妙な"],
   pronunciation:"/ɑːd/",part:80,
   example:"There is something odd about his story today.",
   exampleJa:"今日の彼の話には、どこか奇妙なところがある。",
   example2:"It is odd that nobody answered the classroom phone.",
   exampleJa2:"教室の電話にだれも出なかったのは奇妙だ。",
   etymologyProcess:"odd（三角の先の余り）→ 対にならず一つだけ余ると…？",
   etymologyConclusion:"odd（三角の先の余り）→ 対にならず一つ余ってしまい、しっくりこない＝奇妙な",
   relatedWords:[
     {word:"odds",meaning:"見込み",breakdown:"odd（三角の先の余り）→ 釣り合わない差。賭けの倍率のこと"},
     {word:"oddly",meaning:"奇妙にも",breakdown:"odd（三角の先の余り）＋ ly（副詞）→ しっくりこないようすで"},
     {synonym:true,word:"strange",meaning:"見慣れない",breakdown:"見慣れない。odd は数が余るようにしっくりこない感じ"},
     {synonym:true,word:"unusual",meaning:"ふつうでない",breakdown:"めったにない。odd はどこかつじつまが合わない感じ"}]},

  {id:795,word:"ignorant",partOfSpeech:"形容詞",meaning:"無知の",
   meanings:["形|無知の"],
   pronunciation:"/ˈɪɡnərənt/",part:80,
   example:"He is completely ignorant of the club rules.",
   exampleJa:"彼は部の規則について、まったく無知だ。",
   example2:"We should not stay ignorant about news from abroad.",
   exampleJa2:"私たちは海外からの知らせについて、無知のままでいるべきではない。",
   etymologyProcess:"in（否定）＋ gn（知る）＋ ant（〜な）→ 知っていて当然のことを知らないと…？",
   etymologyConclusion:"in（否定）＋ gn（知る）＋ ant（〜な）→ 知っていて当然のことを何も知らない＝無知の",
   relatedWords:[
     {word:"ignore",meaning:"～を無視する",breakdown:"in（否定）＋ gn（知る）→ 知らないことにして放っておく"},
     {word:"know",meaning:"知る",breakdown:"know（知る）→ 頭の中にしっかり入れておく"},
     {word:"recognize",meaning:"（前に知っていて）見分ける",breakdown:"re（再び）＋ gn（知る）＋ ize（動詞）→ 前に知った姿をもう一度知る"},
     {synonym:true,word:"unaware",meaning:"気づいていない",breakdown:"気がついていない。ignorant は知識そのものが無いこと"}]},

  {id:796,word:"contrast",partOfSpeech:"名詞",meaning:"対比",
   meanings:["名|対比"],
   pronunciation:"/ˈkɑːntræst/",part:80,
   example:"The contrast between the two paintings is very clear.",
   exampleJa:"その2枚の絵の対比は、とてもはっきりしている。",
   example2:"The dark sky made a sharp contrast with the white snow.",
   exampleJa2:"暗い空は、白い雪との鋭い対比をなしていた。",
   etymologyProcess:"contra（逆に）＋ st（立つ）→ 二つを向かい合わせに立たせると…？",
   etymologyConclusion:"contra（逆に）＋ st（立つ）→ 二つを向かい合わせに立たせ、違いを目立たせること＝対比",
   relatedWords:[
     {word:"contrary",meaning:"反対の",breakdown:"contra（逆に）＋ ary（形容詞）→ 向かい合って逆を向いている"},
     {word:"contradict",meaning:"矛盾する",breakdown:"contra（逆に）＋ dict（言う）→ 前と逆のことを言う"},
     {word:"constant",meaning:"変わらない",breakdown:"con（共に）＋ st（立つ）→ ずっと同じ所に立ち続ける"},
     {synonym:true,word:"comparison",meaning:"比較",breakdown:"並べて似た点も見る。contrast は違いのほうを際立たせる"}]},

  {id:797,word:"valid",partOfSpeech:"形容詞",meaning:"（根拠があって）妥当な",
   meanings:["形|（根拠があって）妥当な"],
   pronunciation:"/ˈvælɪd/",part:80,
   example:"That is a valid reason for missing today's practice.",
   exampleJa:"それは今日の練習を休む、妥当な理由だ。",
   example2:"His argument sounds valid, but we still need more data.",
   exampleJa2:"彼の主張は妥当に聞こえるが、それでももっとデータが必要だ。",
   etymologyProcess:"val（力がある）＋ id（〜な状態の）→ 反論をはねのける力があれば…？",
   etymologyConclusion:"val（力がある）＋ id（〜な状態の）→ 反論をはねのける力があって通用する＝妥当な",
   relatedWords:[
     {word:"valuable",meaning:"価値の高い",breakdown:"val（力がある）＋ able（できる）→ 力を発揮して役に立てる"},
     {word:"invalid",meaning:"無効な",breakdown:"in（否定）＋ val（力がある）＋ id（〜な状態の）→ 通用する力がない"},
     {word:"evaluate",meaning:"～を評価する",breakdown:"ex（外へ）＋ valu（価値）＋ ate（動詞）→ 価値を引き出して見定める"},
     {synonym:true,word:"reasonable",meaning:"納得できる",breakdown:"筋が通る。valid は根拠が通用すると認められること"}]},

  {id:798,word:"rare",partOfSpeech:"形容詞",meaning:"珍しい",
   meanings:["形|珍しい"],
   pronunciation:"/rer/",part:80,
   example:"This kind of small bird is very rare in Japan.",
   exampleJa:"この種類の小さな鳥は、日本ではとても珍しい。",
   example2:"It is rare for him to be late for school.",
   exampleJa2:"彼が学校に遅れるのは珍しい。",
   etymologyProcess:"rar（まばらな）→ 数がまばらでめったに出会えないなら…？",
   etymologyConclusion:"rar（まばらな）→ 数がまばらにしかなく、めったに出会えない＝珍しい",
   relatedWords:[
     {word:"rarely",meaning:"めったに～ない",breakdown:"rar（まばらな）＋ ly（副詞）→ まばらにしか起こらないほど"},
     {word:"rarity",meaning:"珍しさ",breakdown:"rar（まばらな）＋ ity（名詞）→ まばらである度合い"},
     {synonym:true,word:"unusual",meaning:"ふつうでない",breakdown:"よくあることではない。rare は数そのものが少ないこと"},
     {synonym:true,word:"scarce",meaning:"乏しい",breakdown:"必要な量に足りない。rare はめったに見かけないこと"}]},

  {id:799,word:"casual",partOfSpeech:"形容詞",meaning:"気楽な",
   meanings:["形|気楽な"],
   pronunciation:"/ˈkæʒuəl/",part:80,
   example:"He wore casual clothes to the school open day.",
   exampleJa:"彼は学校公開日に、気楽な服装で来た。",
   example2:"They had a casual chat about their favorite video games.",
   exampleJa2:"彼らは好きなテレビゲームについて、気楽なおしゃべりをした。",
   etymologyProcess:"cas（落ちる）＋ al（形容詞）→ たまたま転がり込んだように構えないなら…？",
   etymologyConclusion:"cas（落ちる）＋ al（形容詞）→ たまたま転がり込んだ出来事のように、かまえない＝気楽な",
   relatedWords:[
     {word:"case",meaning:"場合",breakdown:"cas（落ちる）→ その身にたまたま降りかかった出来事"},
     {word:"accident",meaning:"事故",breakdown:"ad（〜へ）＋ cad（落ちる）→ ふいに降りかかってきた出来事"},
     {word:"casually",meaning:"何気なく",breakdown:"cas（落ちる）＋ ly（副詞）→ たまたまのように、さりげなく"},
     {synonym:true,word:"relaxed",meaning:"くつろいだ",breakdown:"力が抜けている。casual は形式ばらないことを言う"}]},

  {id:800,word:"available",partOfSpeech:"形容詞",meaning:"手に入る",
   meanings:["形|手に入る"],
   pronunciation:"/əˈveɪləbl/",part:80,
   example:"Tickets for the concert are available at the school office.",
   exampleJa:"そのコンサートのチケットは、学校の事務室で手に入る。",
   example2:"If the book is available, please borrow it for me.",
   exampleJa2:"その本が手に入るなら、私のために借りてきてください。",
   etymologyProcess:"ad（〜へ）＋ vail（役に立つ）＋ able（できる）→ 手もとに届いてすぐ使えるなら…？",
   etymologyConclusion:"ad（〜へ）＋ vail（役に立つ）＋ able（できる）→ 手もとまで届いて、すぐ使える＝手に入る",
   relatedWords:[
     {word:"avail",meaning:"役に立つ",breakdown:"ad（〜へ）＋ vail（役に立つ）→ 相手のほうへ力を差し出す"},
     {word:"value",meaning:"価値",breakdown:"valu（価値）→ 力があると認められた度合い"},
     {word:"prevail",meaning:"広く行き渡る",breakdown:"pre（前へ）＋ vail（役に立つ）→ 他より強い力で行き渡る"},
     {synonym:true,word:"ready",meaning:"すぐ使える",breakdown:"用意が整っている。available は必要なときに手が届くこと"}]},

  {id:801,word:"practical",partOfSpeech:"形容詞",meaning:"現実的な",
   meanings:["形|現実的な"],
   pronunciation:"/ˈpræktɪkl/",part:81,
   example:"We need a practical plan for the school festival.",
   exampleJa:"学園祭のための現実的な計画が必要だ。",
   example2:"His advice was practical and very easy to follow.",
   exampleJa2:"彼の助言は現実的で、とても実行しやすかった。",
   etymologyProcess:"prac（行う）＋ ical（〜の）→ 実際に行って役に立つなら…？",
   etymologyConclusion:"prac（行う）＋ ical（〜の）→ 頭の中だけでなく、実際に行って役に立つ＝現実的な",
   relatedWords:[
     {word:"practice",meaning:"練習",breakdown:"prac（行う）→ 実際に体を動かして繰り返すこと"},
     {word:"impractical",meaning:"実用的でない",breakdown:"in（否定）＋ prac（行う）＋ ical（〜の）→ 実際には行えない"},
     {synonym:true,word:"realistic",meaning:"現実に即した",breakdown:"現実に合っている。practical は実際に役立つかを見る"},
     {synonym:true,word:"useful",meaning:"役に立つ",breakdown:"役立つ。practical は手間なく実行できることまで含む"}]},

  {id:802,word:"abstract",partOfSpeech:"形容詞",meaning:"抽象的な",
   meanings:["形|抽象的な"],
   pronunciation:"/ˈæbstrækt/",part:81,
   example:"Love and freedom are abstract ideas, not real things.",
   exampleJa:"愛や自由は抽象的な考えであって、実在する物ではない。",
   example2:"His painting is far too abstract for me to understand.",
   exampleJa2:"彼の絵はあまりに抽象的すぎて、私には理解できない。",
   etymologyProcess:"ab（離れて）＋ tract（引く）→ 形だけを引き離して取り出すと…？",
   etymologyConclusion:"ab（離れて）＋ tract（引く）→ 中身から形や性質だけを引き離して取り出した＝抽象的な",
   relatedWords:[
     {word:"attract",meaning:"～を引きつける",breakdown:"ad（〜へ）＋ tract（引く）→ 自分のほうへ引き寄せる"},
     {word:"extract",meaning:"抜き出す",breakdown:"ex（外へ）＋ tract（引く）→ 中から外へ引っぱり出す"},
     {word:"tractor",meaning:"トラクター",breakdown:"tract（引く）＋ or（もの）→ 重い物を引いて動かす機械"},
     {synonym:true,word:"general",meaning:"一般的な",breakdown:"広くあてはまる。abstract は形のない考えのほうを指す"}]},

  {id:803,word:"brand-new",partOfSpeech:"形容詞",meaning:"新品の",
   meanings:["形|新品の"],
   pronunciation:"/ˌbrændˈnuː/",part:81,
   example:"He came to school with a brand-new bike today.",
   exampleJa:"彼は今日、新品の自転車で学校に来た。",
   example2:"My sister got a brand-new smartphone for her birthday.",
   exampleJa2:"姉は誕生日に、新品のスマートフォンをもらった。",
   etymologyProcess:"brand（燃える火）＋ new（新しい）→ 炉から出したばかりなら…？",
   etymologyConclusion:"brand（燃える火）＋ new（新しい）→ 炉から出したばかりで、火の跡もまだ新しい＝新品の",
   relatedWords:[
     {word:"brand",meaning:"銘柄",breakdown:"brand（燃える火）→ 焼き印で作り手を示したしるし"},
     {word:"new",meaning:"新しい",breakdown:"new（新しい）→ まだ一度も使われていない"},
     {word:"renew",meaning:"更新する",breakdown:"re（再び）＋ new（新しい）→ もう一度新しくする"},
     {synonym:true,word:"fresh",meaning:"新鮮な",breakdown:"できたて。brand-new は作ったばかり、買ったばかりの物"}]},

  {id:804,word:"secondhand",partOfSpeech:"形容詞",meaning:"中古の",
   meanings:["形|中古の"],
   pronunciation:"/ˌsekəndˈhænd/",part:81,
   example:"She bought a secondhand guitar at a small shop.",
   exampleJa:"彼女は小さな店で、中古のギターを買った。",
   example2:"Most of my textbooks are secondhand but still very clean.",
   exampleJa2:"私の教科書のほとんどは中古だが、それでもとてもきれいだ。",
   etymologyProcess:"sequ（ついて行く）＋ hand（手）→ 二番目の持ち主の手に渡ると…？",
   etymologyConclusion:"sequ（ついて行く）＋ hand（手）→ 最初の持ち主に続く、二番目の手に渡った＝中古の",
   relatedWords:[
     {word:"second",meaning:"2番目の",breakdown:"sequ（ついて行く）→ 一番のあとについて来るもの"},
     {word:"sequence",meaning:"連続",breakdown:"sequ（ついて行く）＋ ence（名詞）→ 次々とついて行く並び"},
     {word:"handle",meaning:"～をうまく扱う",breakdown:"hand（手）＋ le（もの）→ 手でつかむところ。手で扱う"},
     {synonym:true,word:"used",meaning:"使用済みの",breakdown:"一度使われた。secondhand は持ち主が二人目だということ"}]},

  {id:805,word:"rapid",partOfSpeech:"形容詞",meaning:"急速な",
   meanings:["形|急速な"],
   pronunciation:"/ˈræpɪd/",part:81,
   example:"The town has seen rapid growth in the last decade.",
   exampleJa:"その町は、この10年で急速な発展を見せてきた。",
   example2:"Rapid changes in weather can be dangerous for climbers.",
   exampleJa2:"天気の急速な変化は、登山者にとって危険なことがある。",
   etymologyProcess:"rap（さっと奪い取る）＋ id（〜な状態の）→ ひったくるような速さなら…？",
   etymologyConclusion:"rap（さっと奪い取る）＋ id（〜な状態の）→ 人の物をひったくるような速さで進む＝急速な",
   relatedWords:[
     {word:"raptor",meaning:"猛禽（もうきん）",breakdown:"rap（さっと奪い取る）＋ or（もの）→ 獲物をさらって行く鳥"},
     {word:"rapture",meaning:"有頂天",breakdown:"rap（さっと奪い取る）＋ ure（名詞）→ 心をさらわれた状態"},
     {synonym:true,word:"quick",meaning:"すばやい",breakdown:"動きが速い。rapid は進み方や変化の速さを言う"},
     {synonym:true,word:"swift",meaning:"迅速な",breakdown:"なめらかに速い。rapid は勢いよく進む速さのこと"}]},

  {id:806,word:"urgent",partOfSpeech:"形容詞",meaning:"緊急の",
   meanings:["形|緊急の"],
   pronunciation:"/ˈɜːrdʒənt/",part:81,
   example:"She received an urgent message from her mother.",
   exampleJa:"彼女は母から、緊急の知らせを受け取った。",
   example2:"This is urgent, so please answer as soon as possible.",
   exampleJa2:"これは緊急なので、できるだけ早く返事をしてください。",
   etymologyProcess:"urg（強く押す）＋ ent（〜している）→ 背中をぐいぐい押されると…？",
   etymologyConclusion:"urg（強く押す）＋ ent（〜している）→ 背中をぐいぐい押されて、待ったなし＝緊急の",
   relatedWords:[
     {word:"urge",meaning:"～するよう促す",breakdown:"urg（強く押す）→ 相手の背中をぐいと押してせかす"},
     {synonym:true,word:"emergency",meaning:"緊急事態",breakdown:"急に起きて手が離せない事態。urgent は今すぐ手を打つ必要があること"},
     {synonym:true,word:"pressing",meaning:"差し迫った",breakdown:"押し迫っている。urgent はすぐ手を打つ必要があること"},
     {synonym:true,word:"immediate",meaning:"即座の",breakdown:"間を置かない。urgent は急がないとまずい事情があること"}]},

  {id:807,word:"shallow",partOfSpeech:"形容詞",meaning:"浅い",
   meanings:["形|浅い"],
   pronunciation:"/ˈʃæloʊ/",part:81,
   example:"Children can play safely in this shallow river.",
   exampleJa:"子どもたちは、この浅い川で安全に遊ぶことができる。",
   example2:"The dish is too shallow to hold all of the soup.",
   exampleJa2:"その皿は浅すぎて、スープを全部は入れられない。",
   hook:"水・皿・話のどれにも使える。「上から底までが近い」が共通のイメージ。",
   etymologyProcess:"shallow（浅瀬）→ 底がすぐそこに見えるなら…？",
   etymologyConclusion:"shallow（浅瀬）→ 底がすぐそこにあって、上から底までの深さがない＝浅い",
   relatedWords:[
     {word:"shoal",meaning:"浅瀬",breakdown:"shallow（浅瀬）→ 水が浅くなっていて船が通れない所"},
     {synonym:true,word:"superficial",meaning:"うわべだけの",breakdown:"表面だけ。shallow は深さが足りないことを広く言う"},
     {synonym:true,word:"thin",meaning:"薄い",breakdown:"厚みがない。shallow は上から底までが近いこと"},
     {synonym:true,word:"low",meaning:"低い",breakdown:"高さがない。shallow は水や入れ物の深さが足りないこと"}]},

  {id:808,word:"sharp",partOfSpeech:"形容詞",meaning:"（変化が）急激な",
   meanings:["形|（変化が）急激な"],
   pronunciation:"/ʃɑːrp/",part:81,
   example:"There was a sharp rise in temperature this afternoon.",
   exampleJa:"今日の午後、気温の急激な上昇があった。",
   example2:"The graph shows a sharp drop after the summer holidays.",
   exampleJa2:"そのグラフは、夏休みのあとの急激な下降を示している。",
   etymologyProcess:"shar（切り分ける）→ すぱっと切り分けるような変わり方なら…？",
   etymologyConclusion:"shar（切り分ける）→ すぱっと切り分けるように、折れ線が一気に曲がる＝急激な",
   relatedWords:[
     {word:"share",meaning:"～を共有する",breakdown:"shar（切り分ける）→ 一つを切り分けて分け合う"},
     {word:"shore",meaning:"岸",breakdown:"shor（切り分ける）→ 陸と海を切り分けている線"},
     {word:"shirt",meaning:"シャツ",breakdown:"shir（切り分ける）→ 布を切って作った上着"},
     {synonym:true,word:"sudden",meaning:"突然の",breakdown:"前ぶれがない。sharp は変わり方の角度がきついこと"}]},

  {id:809,word:"calm",partOfSpeech:"形容詞",meaning:"落ち着いた",
   meanings:["形|落ち着いた"],
   pronunciation:"/kɑːm/",part:81,
   example:"She stayed calm during the sudden earthquake drill.",
   exampleJa:"彼女は突然の地震訓練の間も、落ち着いたままだった。",
   example2:"Take a deep breath and try to be calm again.",
   exampleJa2:"深呼吸をして、もう一度落ち着くようにしなさい。",
   hook:"海・天気・人の心のどれにも使える。「波立っていない」が共通のイメージ。",
   etymologyProcess:"calm（真昼の暑さ）→ 暑さで何も動かない昼下がりのようなら…？",
   etymologyConclusion:"calm（真昼の暑さ）→ 暑さで人も風も動かない昼下がりのように静か＝落ち着いた",
   relatedWords:[
     {synonym:true,word:"steady",meaning:"動じない",breakdown:"ぐらつかない。calm は波立たず静まっていること"},
     {synonym:true,word:"quiet",meaning:"静かな",breakdown:"音がしない。calm は心や海が波立っていないこと"},
     {synonym:true,word:"peaceful",meaning:"穏やかな",breakdown:"争いがない。calm は乱れずに静まっている状態"},
     {synonym:true,word:"relaxed",meaning:"くつろいだ",breakdown:"緊張がない。calm はあわてず静かでいられること"}]},

  {id:810,word:"naked",partOfSpeech:"形容詞",meaning:"裸の",
   meanings:["形|裸の"],
   pronunciation:"/ˈneɪkɪd/",part:81,
   example:"The baby lay naked on a soft white bath towel.",
   exampleJa:"赤ちゃんは柔らかい白いバスタオルの上で、裸で横になっていた。",
   example2:"You can see many stars here with the naked eye.",
   exampleJa2:"ここでは裸眼で、たくさんの星を見ることができる。",
   etymologyProcess:"nak（裸の）＋ ed（〜された）→ 身にまとう物が何もないなら…？",
   etymologyConclusion:"nak（裸の）＋ ed（〜された）→ 身にまとうものを何ひとつ着けていない＝裸の",
   relatedWords:[
     {word:"nude",meaning:"（絵画などの）裸体の",breakdown:"nud（裸の）→ ラテン語系の言い方。衣服をいっさい着けていない"},
     {synonym:true,word:"bare",meaning:"むき出しの",breakdown:"覆いがない。naked は衣服を着けていない体を言う"},
     {synonym:true,word:"uncovered",meaning:"覆われていない",breakdown:"覆いが外れている。naked は初めから何も着ていないこと"},
     {synonym:true,word:"exposed",meaning:"さらされた",breakdown:"外に出ている。naked は衣服を着けていない状態そのもの"}]},

  {id:811,word:"independent",partOfSpeech:"形容詞",meaning:"独立した",
   meanings:["形|独立した"],
   pronunciation:"/ˌɪndɪˈpendənt/",part:82,
   example:"She became independent soon after leaving high school.",
   exampleJa:"彼女は高校を出てすぐに独立した。",
   example2:"India became fully independent from Britain in 1947.",
   exampleJa2:"インドは1947年に、イギリスから完全に独立した。",
   etymologyProcess:"in（否定）＋ de（下へ）＋ pend（ぶら下がる）＋ ent（〜している）→ 誰にもぶら下がらないと…？",
   etymologyConclusion:"in（否定）＋ de（下へ）＋ pend（ぶら下がる）＋ ent（〜している）→ 誰にもぶら下がらず自分の足で立つ＝独立した",
   relatedWords:[
     {word:"depend",meaning:"頼る",breakdown:"de（下へ）＋ pend（ぶら下がる）→ 下にぶら下がって支えてもらう"},
     {word:"pendant",meaning:"ペンダント",breakdown:"pend（ぶら下がる）＋ ant（もの）→ 首から下げる飾り"},
     {word:"suspend",meaning:"一時中断する",breakdown:"sub（下で）＋ pend（ぶら下がる）→ 吊るしたまま宙で止めておく"},
     {synonym:true,word:"free",meaning:"自由な",breakdown:"しばられていない。independent は人に頼らず立てること"}]},

  {id:812,word:"tense",partOfSpeech:"形容詞",meaning:"張り詰めた",
   meanings:["形|張り詰めた"],
   pronunciation:"/tens/",part:82,
   example:"The atmosphere in the classroom became very tense.",
   exampleJa:"教室の空気は、とても張り詰めたものになった。",
   example2:"His shoulders felt tense before the final match started.",
   exampleJa2:"決勝戦が始まる前、彼の肩は張り詰めていた。",
   etymologyProcess:"tend（伸ばす）→ ぴんと引き伸ばされて切れそうなら…？",
   etymologyConclusion:"tend（伸ばす）→ ぴんと引き伸ばされて、今にも切れそうになっている＝張り詰めた",
   relatedWords:[
     {word:"extend",meaning:"（期間・長さを）延長する",breakdown:"ex（外へ）＋ tend（伸ばす）→ 外へ向けて長く伸ばす"},
     {word:"tension",meaning:"緊張",breakdown:"tend（伸ばす）＋ ion（名詞）→ ぴんと張っている状態"},
     {word:"intense",meaning:"激しい",breakdown:"in（中へ）＋ tend（伸ばす）→ 一点に向けてぐっと張り詰める"},
     {synonym:true,word:"nervous",meaning:"神経質な",breakdown:"不安でそわそわする。tense は体や空気が張り詰めていること"}]},

  {id:813,word:"narrow",partOfSpeech:"形容詞",meaning:"（幅が）狭い",
   meanings:["形|（幅が）狭い"],
   pronunciation:"/ˈnæroʊ/",part:82,
   example:"The path to the shrine is very narrow and dark.",
   exampleJa:"その神社へ続く道は、とても狭くて暗い。",
   example2:"We walked along a narrow street near the old castle.",
   exampleJa2:"私たちは古い城の近くの、狭い通りを歩いた。",
   hook:"narrow は「左右の幅」、thin は「太さ」。道や通路には narrow を使う。",
   etymologyProcess:"narrow（締めつける）→ 両側から締めつけられると…？",
   etymologyConclusion:"narrow（締めつける）→ 両側から締めつけられて、左右の幅がない＝狭い",
   relatedWords:[
     {synonym:true,word:"cramped",meaning:"窮屈な",breakdown:"詰め込まれて動けない。narrow は左右の幅そのものが小さいこと"},
     {synonym:true,word:"tight",meaning:"きつい",breakdown:"すき間がない。narrow は左右の幅が足りないこと"},
     {synonym:true,word:"thin",meaning:"細い",breakdown:"太さがない。narrow は道や通路の幅が小さいこと"},
     {synonym:true,word:"slim",meaning:"細身の",breakdown:"ほっそりしている。narrow は物の幅について言う"}]},

  {id:814,word:"vacant",partOfSpeech:"形容詞",meaning:"（席や部屋が）空いている",
   meanings:["形|（席や部屋が）空いている"],
   pronunciation:"/ˈveɪkənt/",part:82,
   example:"There are two vacant seats in the back row.",
   exampleJa:"後ろの列に、空いている席が2つある。",
   example2:"The house next door has been vacant for many years.",
   exampleJa2:"隣の家は、何年もずっと空いている。",
   etymologyProcess:"vac（空の）＋ ant（〜な）→ 中に誰もいないままなら…？",
   etymologyConclusion:"vac（空の）＋ ant（〜な）→ 中に人も物もおらず、からっぽのまま＝空いている",
   relatedWords:[
     {word:"vacation",meaning:"休暇",breakdown:"vac（空の）＋ ation（名詞）→ 予定を空っぽにすること"},
     {word:"evacuate",meaning:"避難させる",breakdown:"ex（外へ）＋ vac（空の）＋ ate（動詞）→ 中を空にして外へ出す"},
     {word:"vain",meaning:"（努力が）むだな",breakdown:"vain（空の）→ 中身が空っぽで、何も実らない"},
     {synonym:true,word:"empty",meaning:"空っぽの",breakdown:"中に何もない。vacant は使う人がいなくて空いていること"}]},

  {id:815,word:"vivid",partOfSpeech:"形容詞",meaning:"鮮明な",
   meanings:["形|鮮明な"],
   pronunciation:"/ˈvɪvɪd/",part:82,
   example:"I still have a vivid memory of that rainy day.",
   exampleJa:"私はあの雨の日の鮮明な記憶を、今も持っている。",
   example2:"The artist used vivid colors in every single painting.",
   exampleJa2:"その画家は、どの絵にも鮮明な色を使った。",
   etymologyProcess:"viv（生きる）＋ id（〜な状態の）→ 生きているようにくっきり見えると…？",
   etymologyConclusion:"viv（生きる）＋ id（〜な状態の）→ 今そこで生きているように、色も姿もくっきり＝鮮明な",
   relatedWords:[
     {word:"survive",meaning:"生き残る",breakdown:"sur（上を越えて）＋ viv（生きる）→ 危機を越えて生き続ける"},
     {word:"revive",meaning:"生き返る",breakdown:"re（再び）＋ viv（生きる）→ もう一度生き生きと動きだす"},
     {synonym:true,word:"bright",meaning:"明るい",breakdown:"光っている。vivid は色や記憶がくっきりしていること"},
     {synonym:true,word:"clear",meaning:"はっきりした",breakdown:"ぼやけていない。vivid は色や印象の強さのほうを言う"}]},

  {id:816,word:"awkward",partOfSpeech:"形容詞",meaning:"ぎこちない",
   meanings:["形|ぎこちない"],
   pronunciation:"/ˈɔːkwərd/",part:82,
   example:"There was an awkward silence after his sudden question.",
   exampleJa:"彼の突然の質問のあと、ぎこちない沈黙があった。",
   example2:"He felt awkward dancing in front of the whole class.",
   exampleJa2:"彼はクラス全員の前で踊るのを、ぎこちなく感じた。",
   hook:"もとは古ノルド語で「逆向きの」。体の向きも場の空気も「逆」だとぎこちない。",
   etymologyProcess:"awk（逆向きの）→ 向きが逆でしっくり動かせないなら…？",
   etymologyConclusion:"awk（逆向きの）→ 向きが逆で、しっくり動かせず不器用に見える＝ぎこちない",
   relatedWords:[
     {synonym:true,word:"stiff",meaning:"こわばった",breakdown:"体が固い。awkward は動きも空気もぎくしゃくすること"},
     {synonym:true,word:"clumsy",meaning:"不器用な",breakdown:"手つきがぎこちない。awkward は場の気まずさも表せる"},
     {synonym:true,word:"uncomfortable",meaning:"居心地が悪い",breakdown:"落ち着かない。awkward はどうふるまえばよいか分からない感じ"},
     {synonym:true,word:"embarrassing",meaning:"きまりが悪い",breakdown:"恥ずかしい思いをさせる。awkward は空気がぎくしゃくすること"}]},

  {id:817,word:"objective",partOfSpeech:"形容詞",meaning:"客観的な",
   meanings:["形|客観的な"],
   pronunciation:"/əbˈdʒektɪv/",part:82,
   example:"A good reporter must stay objective about every story.",
   exampleJa:"よい記者は、どの記事についても客観的でいなければならない。",
   example2:"Try to be objective when you judge your own work.",
   exampleJa2:"自分の作品を評価するときは、客観的であるようにしなさい。",
   etymologyProcess:"ob（〜に向かって）＋ ject（投げる）＋ ive（形容詞）→ 自分の外へ投げ出して眺めると…？",
   etymologyConclusion:"ob（〜に向かって）＋ ject（投げる）＋ ive（形容詞）→ 自分の外に投げ出し、一つの物として眺める＝客観的な",
   relatedWords:[
     {word:"object",meaning:"物体",breakdown:"ob（〜に向かって）＋ ject（投げる）→ 目の前に投げ出されている物"},
     {word:"project",meaning:"計画",breakdown:"pro（前へ）＋ ject（投げる）→ 先の方へ投げ出して描く計画"},
     {word:"reject",meaning:"（受け入れず）はねつける",breakdown:"re（後ろへ）＋ ject（投げる）→ 投げ返して受け取らない"},
     {synonym:true,word:"fair",meaning:"公正な",breakdown:"かたよりがない。objective は自分の気持ちを外して見ること"}]},

  {id:818,word:"manual",partOfSpeech:"形容詞",meaning:"手を使う",
   meanings:["形|手を使う"],
   pronunciation:"/ˈmænjuəl/",part:82,
   example:"This old camera has a manual focus ring.",
   exampleJa:"この古いカメラには、手を使ってピントを合わせるリングがある。",
   example2:"Manual work in the fields made his hands very strong.",
   exampleJa2:"畑での手を使う作業が、彼の手をとても強くした。",
   etymologyProcess:"manu（手）＋ al（形容詞）→ 機械まかせにせず人の手で行うなら…？",
   etymologyConclusion:"manu（手）＋ al（形容詞）→ 機械まかせにせず、人の手を動かして行う＝手を使う",
   relatedWords:[
     {word:"manage",meaning:"（道具・人を）うまく扱う",breakdown:"manu（手）＋ age（すること）→ 手で手綱をさばいて操る"},
     {word:"manufacture",meaning:"製造する",breakdown:"manu（手）＋ fact（作る）＋ ure（名詞）→ 手で作り出すこと"},
     {word:"manuscript",meaning:"原稿",breakdown:"manu（手）＋ scrib（書く）→ 手で書き写したもの"},
     {synonym:true,word:"handmade",meaning:"手作りの",breakdown:"手で作った。manual は手を動かして行う作業のことを言う"}]},

  {id:819,word:"alike",partOfSpeech:"形容詞",meaning:"（二つが）そっくりな",
   meanings:["形|（二つが）そっくりな"],
   pronunciation:"/əˈlaɪk/",part:82,
   example:"The twin sisters look very much alike in old photos.",
   exampleJa:"その双子の姉妹は、古い写真ではとてもそっくりに見える。",
   example2:"All the houses on this quiet street look alike.",
   exampleJa2:"この静かな通りの家は、どれもそっくりに見える。",
   etymologyProcess:"like（同じ形の）→ 二つを並べて同じ形に見えるなら…？",
   etymologyConclusion:"like（同じ形の）→ 二つを並べてみると、同じ形に重なって見える＝そっくりな",
   relatedWords:[
     {word:"like",meaning:"～のような",breakdown:"like（同じ形の）→ 同じ形をしている"},
     {word:"likely",meaning:"～しそうだ",breakdown:"like（同じ形の）＋ ly（形容詞）→ そうなる形にいかにも近い"},
     {word:"unlike",meaning:"～と違って",breakdown:"un（否定）＋ like（同じ形の）→ 同じ形ではない"},
     {synonym:true,word:"similar",meaning:"よく似た",breakdown:"似ている。alike は「二つが互いに似ている」と言い切る形"}]},

  {id:820,word:"alien",partOfSpeech:"形容詞",meaning:"異質な",
   meanings:["形|異質な"],
   pronunciation:"/ˈeɪliən/",part:82,
   example:"The custom felt completely alien to the new students.",
   exampleJa:"その習慣は、新入生には完全に異質に感じられた。",
   example2:"Deep snow is an alien sight in this warm country.",
   exampleJa2:"深い雪は、この暖かい国では異質な光景だ。",
   etymologyProcess:"ali（別の）→ よその世界から来たようになじまないと…？",
   etymologyConclusion:"ali（別の）→ よその世界から来たようで、まわりの何にもなじまない＝異質な",
   relatedWords:[
     {word:"alibi",meaning:"アリバイ",breakdown:"ali（別の）→ そのとき別の場所にいたという証明"},
     {word:"alienate",meaning:"遠ざける",breakdown:"ali（別の）＋ ate（動詞）→ 別のものとして扱い、遠ざける"},
     {synonym:true,word:"foreign",meaning:"外国の",breakdown:"よその国の。alien はなじめないほど異質だということ"},
     {synonym:true,word:"strange",meaning:"見慣れない",breakdown:"見慣れない。alien は自分たちの世界の外から来た感じ"}]},

  {id:821,word:"tend",partOfSpeech:"自動詞",meaning:"～する傾向にある",
   meanings:["自|～する傾向にある"],
   pronunciation:"/tend/",part:83,
   example:"Students tend to talk more in small discussion groups.",
   exampleJa:"生徒は少人数の話し合いのグループでは、より多く話す傾向にある。",
   example2:"Prices tend to rise just before the holiday season.",
   exampleJa2:"価格は休暇シーズンの直前に上がる傾向にある。",
   etymologyProcess:"tend（伸ばす）→ 気持ちがいつも同じ方へ伸びていくなら…？",
   etymologyConclusion:"tend（伸ばす）→ 気持ちや動きが、いつも同じ方へ伸びていく＝～する傾向にある",
   relatedWords:[
     {word:"intend",meaning:"～するつもりである",breakdown:"in（中へ）＋ tend（伸ばす）→ 心を目標へまっすぐ伸ばす"},
     {word:"attend",meaning:"出席する",breakdown:"ad（〜へ）＋ tend（伸ばす）→ 心をそちらへ伸ばして居合わせる"},
     {word:"tent",meaning:"テント",breakdown:"tend（伸ばす）→ 布をぴんと張って作る仮の家"},
     {synonym:true,word:"incline",meaning:"傾く",breakdown:"一方へ傾く。tend はいつもそちらへ向かうくせのこと"}]},

  {id:822,word:"deserve",partOfSpeech:"他動詞",meaning:"～に値する",
   meanings:["他|～に値する"],
   pronunciation:"/dɪˈzɜːrv/",part:83,
   example:"You deserve a long rest after all that hard work.",
   exampleJa:"あれだけ大変な働きをしたのだから、君は長い休みに値する。",
   example2:"He deserves the prize more than anyone else here.",
   exampleJa2:"彼はここにいるだれよりも、その賞に値する。",
   etymologyProcess:"de（すっかり）＋ serv（仕える）→ すっかり尽くしてきたなら…？",
   etymologyConclusion:"de（すっかり）＋ serv（仕える）→ すっかり尽くしてきたので、報いを受けるにふさわしい＝～に値する",
   relatedWords:[
     {word:"serve",meaning:"（飲食物）を出す",breakdown:"serv（仕える）→ 人のために働いて差し出す"},
     {word:"service",meaning:"（公共の）事業，サービス",breakdown:"serv（仕える）＋ ice（名詞）→ 人のために働くこと"},
     {word:"servant",meaning:"使用人",breakdown:"serv（仕える）＋ ant（人）→ 人に仕えて働く人"},
     {synonym:true,word:"merit",meaning:"～の価値がある",breakdown:"値打ちがある。deserve は努力の報いを受ける資格があること"}]},

  {id:823,word:"fragment",partOfSpeech:"名詞",meaning:"破片",
   meanings:["名|破片"],
   pronunciation:"/ˈfræɡmənt/",part:83,
   example:"A sharp fragment of glass was left on the floor.",
   exampleJa:"鋭いガラスの破片が、床に残っていた。",
   example2:"We found a fragment of an old clay pot there.",
   exampleJa2:"私たちはそこで、古い土器の破片を見つけた。",
   etymologyProcess:"frag（砕く）＋ ment（名詞）→ 砕けて飛び散った一部分なら…？",
   etymologyConclusion:"frag（砕く）＋ ment（名詞）→ 打ち砕かれて飛び散った、もとの一部分＝破片",
   relatedWords:[
     {word:"fragile",meaning:"壊れやすい",breakdown:"frag（砕く）→ 少し力を加えるとすぐ砕けてしまう"},
     {word:"fraction",meaning:"分数",breakdown:"frag（砕く）＋ ion（名詞）→ 全体を砕いて分けた一部分"},
     {word:"fracture",meaning:"骨折",breakdown:"frag（砕く）＋ ure（名詞）→ 骨が砕けてしまうこと"},
     {synonym:true,word:"piece",meaning:"かけら",breakdown:"一部分。fragment は壊れて飛び散ったかけらを指す"}]},

  {id:824,word:"range",partOfSpeech:"名詞",meaning:"範囲",
   meanings:["名|範囲"],
   pronunciation:"/reɪndʒ/",part:83,
   example:"This shop sells a wide range of sports shoes.",
   exampleJa:"この店は、幅広い範囲のスポーツシューズを売っている。",
   example2:"The price range for these used bikes is quite narrow.",
   exampleJa2:"これらの中古自転車の価格の範囲は、かなり狭い。",
   etymologyProcess:"rang（列に並べる）→ 並べた端から端までの広がりは…？",
   etymologyConclusion:"rang（列に並べる）→ 一列に並べたときの、端から端までの広がり＝範囲",
   relatedWords:[
     {word:"arrange",meaning:"整える",breakdown:"ad（〜へ）＋ rang（列に並べる）→ きちんと並べて整える"},
     {word:"rank",meaning:"階級",breakdown:"rang（列に並べる）→ 並んだ列の中での位置"},
     {word:"ranger",meaning:"森林警備隊員",breakdown:"rang（列に並べる）＋ er（人）→ 決まった区域を見回る人"},
     {synonym:true,word:"scope",meaning:"及ぶ範囲",breakdown:"手が届く広さ。range は端から端までの幅を言う"}]},

  {id:825,word:"scale",partOfSpeech:"名詞",meaning:"規模",
   meanings:["名|規模"],
   pronunciation:"/skeɪl/",part:83,
   example:"The scale of the festival grows bigger every year.",
   exampleJa:"その祭りの規模は、毎年大きくなっている。",
   example2:"We cannot really imagine the scale of the universe.",
   exampleJa2:"私たちは宇宙の規模を、本当には想像できない。",
   etymologyProcess:"scal（はしご）→ はしごの段で大きさを測ると…？",
   etymologyConclusion:"scal（はしご）→ はしごの段のように目盛りで測った、全体の大きさ＝規模",
   relatedWords:[
     {word:"escalator",meaning:"エスカレーター",breakdown:"ex（外へ）＋ scal（はしご）＋ ator（装置）→ 段が動いて人を上へ運ぶ"},
     {word:"escalate",meaning:"段階的に上がる",breakdown:"ex（外へ）＋ scal（はしご）＋ ate（動詞）→ 段を一つずつ上がっていく"},
     {synonym:true,word:"size",meaning:"大きさ",breakdown:"物の大きさ。scale は全体の広がりの大きさを言う"},
     {synonym:true,word:"extent",meaning:"及ぶ広さ",breakdown:"どこまで及ぶか。scale はその大きさの段階を言う"}]},

  {id:826,word:"unique",partOfSpeech:"形容詞",meaning:"特有の",
   meanings:["形|特有の"],
   pronunciation:"/juˈniːk/",part:83,
   example:"Every person has a unique way of speaking.",
   exampleJa:"人はだれでも、その人だけに特有の話し方を持っている。",
   example2:"This old temple has a unique roof design.",
   exampleJa2:"この古い寺は、特有の屋根の造りをしている。",
   etymologyProcess:"uni（1つ）＋ ique（形容詞）→ 世界にたった1つしかないなら…？",
   etymologyConclusion:"uni（1つ）＋ ique（形容詞）→ 世界にたった1つしかなく、代わりがきかない＝特有の",
   relatedWords:[
     {word:"uniform",meaning:"制服",breakdown:"uni（1つ）＋ form（形）→ みんなが同じ一つの形を身につける"},
     {word:"union",meaning:"組合",breakdown:"uni（1つ）＋ ion（名詞）→ 一つにまとまったもの"},
     {word:"universe",meaning:"宇宙",breakdown:"uni（1つ）＋ vers（回る）→ 一つに回り集まったすべて"},
     {synonym:true,word:"original",meaning:"独自の",breakdown:"もとから自分のもの。unique はほかに一つもないこと"}]},

  {id:827,word:"particular",partOfSpeech:"形容詞",meaning:"ある特定の",
   meanings:["形|ある特定の"],
   pronunciation:"/pərˈtɪkjələr/",part:83,
   example:"Is there a particular book you want to read today?",
   exampleJa:"今日あなたが読みたい、ある特定の本はありますか。",
   example2:"He still remembers that particular rainy day very clearly.",
   exampleJa2:"彼はある特定の雨の日を、今もとてもはっきり覚えている。",
   etymologyProcess:"part（分ける）＋ icle（小さいもの）＋ ar（形容詞）→ 全体から小さく切り分けると…？",
   etymologyConclusion:"part（分ける）＋ icle（小さいもの）＋ ar（形容詞）→ 全体から小さく切り分けて取り上げた＝ある特定の",
   relatedWords:[
     {word:"particle",meaning:"粒子",breakdown:"part（分ける）＋ icle（小さいもの）→ 細かく分けた小さな粒"},
     {word:"partly",meaning:"部分的に",breakdown:"part（分ける）＋ ly（副詞）→ 全体のうちの一部だけ"},
     {word:"apart",meaning:"離れて",breakdown:"ad（〜へ）＋ part（分ける）→ 分けて間を空ける"},
     {synonym:true,word:"certain",meaning:"ある～",breakdown:"はっきり決まった。particular はその一つを取り立てて指すこと"}]},

  {id:828,word:"typical",partOfSpeech:"形容詞",meaning:"典型的な",
   meanings:["形|典型的な"],
   pronunciation:"/ˈtɪpɪkl/",part:83,
   example:"This is a typical scene of a Japanese summer.",
   exampleJa:"これは日本の夏の、典型的な光景だ。",
   example2:"It is typical of him to arrive ten minutes early.",
   exampleJa2:"10分早く着くのは、彼の典型的なやり方だ。",
   etymologyProcess:"typ（打った跡）＋ ical（〜の）→ 同じ型で打ち出したようなら…？",
   etymologyConclusion:"typ（打った跡）＋ ical（〜の）→ 同じ型で打ち出したように、いかにもそれらしい＝典型的な",
   relatedWords:[
     {word:"type",meaning:"型",breakdown:"typ（打った跡）→ 同じ型から打ち出された仲間"},
     {word:"prototype",meaning:"試作品",breakdown:"pro（前へ）＋ typ（打った跡）→ いちばん先に打ち出したひな型"},
     {word:"typist",meaning:"タイピスト",breakdown:"typ（打った跡）＋ ist（人）→ 文字を打ち出していく人"},
     {synonym:true,word:"standard",meaning:"標準の",breakdown:"基準になる。typical はその仲間らしさをよく表していること"}]},

  {id:829,word:"general",partOfSpeech:"形容詞",meaning:"一般的な",
   meanings:["形|一般的な"],
   pronunciation:"/ˈdʒenrəl/",part:83,
   example:"The general opinion in class was against that plan.",
   exampleJa:"クラスの一般的な意見は、その計画に反対だった。",
   example2:"In general, students here study for two hours every day.",
   exampleJa2:"一般的に、ここの生徒は毎日2時間勉強する。",
   etymologyProcess:"gener（生み出す）＋ al（形容詞）→ 同じ生まれの仲間全部に当てはまると…？",
   etymologyConclusion:"gener（生み出す）＋ al（形容詞）→ 同じ生まれの仲間すべてに当てはまる＝一般的な",
   relatedWords:[
     {word:"generation",meaning:"世代",breakdown:"gener（生み出す）＋ ation（名詞）→ 同じころに生み出された人たち"},
     {word:"generous",meaning:"気前のよい",breakdown:"gener（生み出す）＋ ous（形容詞）→ よい生まれらしく惜しまず与える"},
     {word:"gene",meaning:"遺伝子",breakdown:"gener（生み出す）→ 親から子へ受け継がれ、体を生み出すもと"},
     {synonym:true,word:"common",meaning:"よく見られる",breakdown:"みんなに共通する。general は全体に当てはまることを言う"}]},

  {id:830,word:"ordinary",partOfSpeech:"形容詞",meaning:"平凡な",
   meanings:["形|平凡な"],
   pronunciation:"/ˈɔːrdneri/",part:83,
   example:"It was just an ordinary day at our school.",
   exampleJa:"それは私たちの学校での、ごく平凡な一日だった。",
   example2:"She looks ordinary, but she sings like a professional.",
   exampleJa2:"彼女は平凡に見えるが、プロのように歌う。",
   etymologyProcess:"ord（順序）＋ ary（形容詞）→ 決まった順序どおりで変わりばえしないと…？",
   etymologyConclusion:"ord（順序）＋ ary（形容詞）→ 決まった順序どおりで、変わったところがない＝平凡な",
   relatedWords:[
     {word:"order",meaning:"順序；注文する",breakdown:"ord（順序）→ 順序よく並べる。並べて頼む"},
     {word:"orderly",meaning:"整然とした",breakdown:"ord（順序）＋ ly（形容詞）→ 順序がきちんと守られている"},
     {word:"extraordinary",meaning:"並外れた",breakdown:"extra（範囲の外へ）＋ ord（順序）＋ ary（形容詞）→ ふつうの順序の外にある"},
     {synonym:true,word:"normal",meaning:"ふつうの",breakdown:"基準どおり。ordinary は特に目立つところがないこと"}]},

  {id:831,word:"account",partOfSpeech:"自動詞",meaning:"（for）占める",
   meanings:["自|（for）占める"],
   pronunciation:"/əˈkaʊnt/",part:84,
   example:"Rice accounts for most of the food eaten here.",
   exampleJa:"米が、ここで食べられている食料の大半を占める。",
   example2:"Sports clubs account for half of all school groups.",
   exampleJa2:"運動部が、学校の全部活の半分を占める。",
   etymologyProcess:"ad（〜へ）＋ count（数える）→ 全体のうち何割を数え上げるか…？",
   etymologyConclusion:"ad（〜へ）＋ count（数える）→ 全体を数え上げたとき、そのうちのどれだけに当たるか＝占める",
   relatedWords:[
     {word:"count",meaning:"数える",breakdown:"count（数える）→ 一つずつ数を数え上げる"},
     {word:"discount",meaning:"割引",breakdown:"dis（逆に）＋ count（数える）→ 数え戻して値段を引く"},
     {word:"accountant",meaning:"会計士",breakdown:"ad（〜へ）＋ count（数える）＋ ant（人）→ お金を数え上げる人"},
     {synonym:true,word:"occupy",meaning:"（場所を）占める",breakdown:"場所をふさぐ。account for は数のうえで割合を占めること"}]},

  {id:832,word:"calculate",partOfSpeech:"他動詞",meaning:"計算する",
   meanings:["他|計算する"],
   pronunciation:"/ˈkælkjuleɪt/",part:84,
   example:"Let's calculate the total cost of the school trip.",
   exampleJa:"修学旅行の総費用を計算しよう。",
   example2:"She calculated how many days were left before the exams.",
   exampleJa2:"彼女は試験まであと何日あるかを計算した。",
   etymologyProcess:"calcul（小石）＋ ate（動詞）→ 小石を並べて数を出すなら…？",
   etymologyConclusion:"calcul（小石）＋ ate（動詞）→ 小石を並べて動かし、数を出していく＝計算する",
   relatedWords:[
     {word:"calculator",meaning:"電卓",breakdown:"calcul（小石）＋ ator（装置）→ 小石の代わりに数を出す機械"},
     {word:"calculation",meaning:"計算",breakdown:"calcul（小石）＋ ation（名詞）→ 小石を動かして数を出すこと"},
     {word:"calcium",meaning:"カルシウム",breakdown:"calcul（小石）→ 石灰の小石にふくまれている成分"},
     {synonym:true,word:"compute",meaning:"（機械で）計算する",breakdown:"機械で数を出す。calculate は式を立てて数を求めること"}]},

  {id:833,word:"measure",partOfSpeech:"他動詞",meaning:"測る",
   meanings:["他|測る"],
   pronunciation:"/ˈmeʒər/",part:84,
   example:"Please measure the width of this desk very carefully.",
   exampleJa:"この机の幅を、とても注意深く測ってください。",
   example2:"We measured the rainfall every morning for one month.",
   exampleJa2:"私たちは1か月間、毎朝の雨量を測った。",
   etymologyProcess:"meas（測る）→ 目盛りを当てて数字にするなら…？",
   etymologyConclusion:"meas（測る）→ 目盛りを当てて、長さや量を数字にして表す＝測る",
   relatedWords:[
     {word:"meter",meaning:"メートル",breakdown:"meas（測る）→ 長さを測るときの基本の単位"},
     {word:"measurement",meaning:"寸法",breakdown:"meas（測る）＋ ment（名詞）→ 測って出した数"},
     {word:"immense",meaning:"巨大な",breakdown:"in（否定）＋ meas（測る）→ 測りきれないほど大きい"},
     {synonym:true,word:"weigh",meaning:"重さを量る",breakdown:"重さを調べる。measure は長さや量を目盛りで調べること"}]},

  {id:834,word:"decline",partOfSpeech:"自動詞",meaning:"（数や勢いが）減る",
   meanings:["自|（数や勢いが）減る"],
   pronunciation:"/dɪˈklaɪn/",part:84,
   example:"The number of students declines every year in this town.",
   exampleJa:"この町では、生徒の数が毎年減る。",
   example2:"Sales of paper maps have declined since smartphones appeared.",
   exampleJa2:"紙の地図の売り上げは、スマートフォンが現れてから減った。",
   etymologyProcess:"de（下へ）＋ clin（傾き）→ 右下がりに傾いていくと…？",
   etymologyConclusion:"de（下へ）＋ clin（傾き）→ グラフが右下がりに傾き、数や勢いが落ちていく＝減る",
   relatedWords:[
     {word:"climate",meaning:"気候",breakdown:"clim（傾き）→ 地球の傾きで決まる、その土地の天気"},
     {word:"incline",meaning:"傾く",breakdown:"in（中へ）＋ clin（傾き）→ 一方へぐっと傾く"},
     {word:"recline",meaning:"もたれる",breakdown:"re（後ろへ）＋ clin（傾き）→ 体を後ろへ傾ける"},
     {synonym:true,word:"decrease",meaning:"減少する",breakdown:"数が少なくなる。decline は右下がりに落ちていく感じ"}]},

  {id:835,word:"split",partOfSpeech:"他動詞",meaning:"（縦に）割る",
   meanings:["他|（縦に）割る"],
   pronunciation:"/splɪt/",part:84,
   example:"Let's split the cake into eight equal pieces.",
   exampleJa:"そのケーキを、8等分に割ろう。",
   example2:"The class was split into two teams for the game.",
   exampleJa2:"そのクラスは試合のために、2つのチームに割られた。",
   etymologyProcess:"split（裂く）→ 縦にまっすぐ裂いて分けると…？",
   etymologyConclusion:"split（裂く）→ 縦にまっすぐ裂いて、二つに分けてしまう＝割る",
   relatedWords:[
     {word:"splinter",meaning:"とげ",breakdown:"split（裂く）→ 裂けて飛び散った細い木のかけら"},
     {synonym:true,word:"divide",meaning:"分割する",breakdown:"分ける。split は力を入れて裂くように分けること"},
     {synonym:true,word:"crack",meaning:"ひびを入れる",breakdown:"割れ目が入る。split は最後まで裂けて二つになること"},
     {synonym:true,word:"separate",meaning:"分ける",breakdown:"離して別々にする。split は一つの物を裂いて分けること"}]},

  {id:836,word:"volume",partOfSpeech:"名詞",meaning:"容積",
   meanings:["名|容積"],
   pronunciation:"/ˈvɑːljuːm/",part:84,
   example:"The volume of this wooden box is about two liters.",
   exampleJa:"この木の箱の容積は、およそ2リットルだ。",
   example2:"We measured the volume of water left in the tank.",
   exampleJa2:"私たちはタンクに残った水の容積を測った。",
   etymologyProcess:"volve（回す）→ 巻物を巻いた太さで量ると…？",
   etymologyConclusion:"volve（回す）→ 巻物を巻いた太さのように、中に入る大きさ＝容積",
   relatedWords:[
     {word:"involve",meaning:"巻き込む",breakdown:"in（中へ）＋ volve（回す）→ 中へ巻き込んでしまう"},
     {word:"revolve",meaning:"回転する",breakdown:"re（何度も）＋ volve（回す）→ 同じ所をぐるぐる回る"},
     {word:"evolve",meaning:"進化する",breakdown:"ex（外へ）＋ volve（回す）→ 巻物を外へ広げるように変わっていく"},
     {synonym:true,word:"capacity",meaning:"収容量",breakdown:"入れられる量。volume は物が占める空間の大きさ"}]},

  {id:837,word:"proportion",partOfSpeech:"名詞",meaning:"比率",
   meanings:["名|比率"],
   pronunciation:"/prəˈpɔːrʃn/",part:84,
   example:"The proportion of students who joined the trip was large.",
   exampleJa:"その旅行に参加した生徒の比率は大きかった。",
   example2:"The proportion of boys to girls is almost equal here.",
   exampleJa2:"ここでは男子と女子の比率が、ほぼ等しい。",
   etymologyProcess:"pro（前へ）＋ part（分ける）→ 全体を分けたときの取り分なら…？",
   etymologyConclusion:"pro（前へ）＋ part（分ける）→ 全体を前に置いて分けたときの、取り分の大きさ＝比率",
   relatedWords:[
     {word:"part",meaning:"部分",breakdown:"part（分ける）→ 全体を分けたうちの一つ"},
     {word:"portion",meaning:"一人分",breakdown:"part（分ける）→ 全体から取り分けた分"},
     {word:"partner",meaning:"仲間",breakdown:"part（分ける）＋ er（人）→ 分け前を共にする相手"},
     {synonym:true,word:"ratio",meaning:"比",breakdown:"二つの数の比。proportion は全体に対する割合のこと"}]},

  {id:838,word:"dozen",partOfSpeech:"名詞",meaning:"ダース",
   meanings:["名|ダース"],
   pronunciation:"/ˈdʌzn/",part:84,
   example:"She bought a dozen eggs at the corner shop.",
   exampleJa:"彼女は角の店で、1ダースの卵を買った。",
   example2:"We need two dozen pencils for the whole class.",
   exampleJa2:"クラス全体で、2ダースの鉛筆が必要だ。",
   etymologyProcess:"du（2）＋ dec（10）→ 2と10を合わせた数でまとめると…？",
   etymologyConclusion:"du（2）＋ dec（10）→ 2と10を合わせた12を、ひとまとまりで数える＝ダース",
   relatedWords:[
     {word:"December",meaning:"12月",breakdown:"dec（10）→ 古いこよみで10番目だった月"},
     {word:"decade",meaning:"10年",breakdown:"dec（10）→ 10年をひとまとまりにした期間"},
     {word:"duo",meaning:"デュオ，2人組",breakdown:"du（2）→ 2人で組んで演じること"},
     {synonym:true,word:"twelve",meaning:"12",breakdown:"数の12。dozen は12個ひとまとまりとして数える言い方"}]},

  {id:839,word:"amount",partOfSpeech:"名詞",meaning:"（数えられない物の）量",
   meanings:["名|（数えられない物の）量"],
   pronunciation:"/əˈmaʊnt/",part:84,
   example:"We were all surprised by the amount of snow.",
   exampleJa:"私たちはみな、その雪の量に驚いた。",
   example2:"The amount of homework increased after the summer break.",
   exampleJa2:"宿題の量は、夏休みのあとに増えた。",
   etymologyProcess:"ad（〜へ）＋ mount（山）→ 積み上げて山にした大きさなら…？",
   etymologyConclusion:"ad（〜へ）＋ mount（山）→ 積み上げて山にしたときの、全体の大きさ＝量",
   relatedWords:[
     {word:"mountain",meaning:"山",breakdown:"mount（山）→ 高く盛り上がった土地"},
     {word:"mount",meaning:"登る",breakdown:"mount（山）→ 山を登るように上へ上がる"},
     {word:"surmount",meaning:"乗り越える",breakdown:"sur（上を越えて）＋ mount（山）→ 山を越えて向こうへ行く"},
     {synonym:true,word:"quantity",meaning:"分量",breakdown:"どれだけあるか。amount は数えられない物の全体量を言う"}]},

  {id:840,word:"mass",partOfSpeech:"名詞",meaning:"大量",
   meanings:["名|大量"],
   pronunciation:"/mæs/",part:84,
   example:"A mass of dark clouds covered the whole evening sky.",
   exampleJa:"大量の黒い雲が、夕方の空一面を覆った。",
   example2:"A mass of fans waited outside the gate after the concert.",
   exampleJa2:"コンサートのあと、大量のファンが門の外で待っていた。",
   etymologyProcess:"mass（こねた塊）→ こね固めた大きな塊のようなら…？",
   etymologyConclusion:"mass（こねた塊）→ こね固めた大きな塊のように、まとまってたくさんある＝大量",
   relatedWords:[
     {word:"massive",meaning:"大規模な",breakdown:"mass（こねた塊）＋ ive（形容詞）→ 大きな塊のように重く大きい"},
     {word:"amass",meaning:"ため込む",breakdown:"ad（〜へ）＋ mass（こねた塊）→ 一か所に寄せて塊にする"},
     {synonym:true,word:"heap",meaning:"積み重なった山",breakdown:"積み上げた山。mass はひと塊になった大きな量"},
     {synonym:true,word:"bulk",meaning:"大きなかさ",breakdown:"かさばる量。mass はまとまった塊としての量"}]},

  {id:841,word:"shortage",partOfSpeech:"名詞",meaning:"（必要な量に足りない）不足",
   meanings:["名|（必要な量に足りない）不足"],
   pronunciation:"/ˈʃɔːrtɪdʒ/",part:85,
   example:"The town faced a serious water shortage last summer.",
   exampleJa:"その町は昨年の夏、深刻な水不足に直面した。",
   example2:"A shortage of teachers is a problem in many schools.",
   exampleJa2:"教師の不足は、多くの学校で問題になっている。",
   etymologyProcess:"shor（切り分ける）＋ age（名詞）→ 必要な分から切り取られると…？",
   etymologyConclusion:"shor（切り分ける）＋ age（名詞）→ 必要なところから切り取られて、足りていない＝不足",
   relatedWords:[
     {word:"short",meaning:"短い",breakdown:"shor（切り分ける）→ 切り取られて長さが足りない"},
     {word:"shorten",meaning:"短くする",breakdown:"shor（切り分ける）＋ en（〜にする）→ 切って短くする"},
     {word:"shortly",meaning:"まもなく",breakdown:"shor（切り分ける）＋ ly（副詞）→ 短く切りつめた時間のうちに"},
     {synonym:true,word:"lack",meaning:"不足",breakdown:"足りないこと。shortage は必要な量に届かない不足の量を指す"}]},

  {id:842,word:"enormous",partOfSpeech:"形容詞",meaning:"莫大な",
   meanings:["形|莫大な"],
   pronunciation:"/ɪˈnɔːrməs/",part:85,
   example:"The company made an enormous profit last year.",
   exampleJa:"その会社は昨年、莫大な利益を上げた。",
   example2:"They spent an enormous amount of money on the stadium.",
   exampleJa2:"彼らはその競技場に、莫大な額のお金を使った。",
   etymologyProcess:"ex（外へ）＋ norm（決まり）＋ ous（形容詞）→ ふつうの決まりからはみ出すなら…？",
   etymologyConclusion:"ex（外へ）＋ norm（決まり）＋ ous（形容詞）→ ふつうの決まりの外へはみ出すほど大きい＝莫大な",
   relatedWords:[
     {word:"normal",meaning:"ふつうの",breakdown:"norm（決まり）＋ al（形容詞）→ 決まりどおりで、外れていない"},
     {word:"norm",meaning:"標準",breakdown:"norm（決まり）→ みんながそれに従う目安"},
     {word:"abnormal",meaning:"異常な",breakdown:"ab（離れて）＋ norm（決まり）＋ al（形容詞）→ 決まりから離れている"},
     {synonym:true,word:"huge",meaning:"巨大な",breakdown:"とても大きい。enormous はふつうの枠を越えた大きさ"}]},

  {id:843,word:"spare",partOfSpeech:"形容詞",meaning:"（いざという時の）予備の",
   meanings:["形|（いざという時の）予備の"],
   pronunciation:"/sper/",part:85,
   example:"Do you have a spare pencil that I can borrow?",
   exampleJa:"私が借りられる予備の鉛筆を持っていますか。",
   example2:"Keep a spare key in a safe place at home.",
   exampleJa2:"家の安全な場所に、予備の鍵を置いておきなさい。",
   hook:"a spare key・in my spare time の形で覚える。どちらも「今は使っていない余り」。",
   etymologyProcess:"spar（惜しんで取っておく）→ 使わずに取ってあるなら…？",
   etymologyConclusion:"spar（惜しんで取っておく）→ 今は使わず、惜しんで取ってある＝予備の",
   relatedWords:[
     {synonym:true,word:"extra",meaning:"余分の",breakdown:"よけいにある。spare はいざというとき用に取ってある物"},
     {synonym:true,word:"backup",meaning:"予備の控え",breakdown:"だめなとき代わりに使う。spare は初めから別に用意した物"},
     {synonym:true,word:"reserve",meaning:"取っておく",breakdown:"先のために確保する。spare は取っておいたその物を指す"}]},

  {id:844,word:"arrange",partOfSpeech:"他動詞",meaning:"手配する",
   meanings:["他|手配する"],
   pronunciation:"/əˈreɪndʒ/",part:85,
   example:"I will arrange a meeting with the new coach.",
   exampleJa:"私は新しいコーチとの会合を手配します。",
   example2:"He arranged everything for the school trip by himself.",
   exampleJa2:"彼は修学旅行のすべてを、自分ひとりで手配した。",
   etymologyProcess:"ad（〜へ）＋ rang（列に並べる）→ 順序よく並べて段取りを整えると…？",
   etymologyConclusion:"ad（〜へ）＋ rang（列に並べる）→ 必要なものを順序よく並べて、段取りを整える＝手配する",
   relatedWords:[
     {word:"range",meaning:"範囲",breakdown:"rang（列に並べる）→ 並べた端から端までの広がり"},
     {word:"rank",meaning:"階級",breakdown:"rang（列に並べる）→ 並んだ列の中での位置"},
     {synonym:true,word:"organize",meaning:"準備を整える",breakdown:"筋道立てて整える。arrange は必要な段取りをつけること"},
     {synonym:true,word:"prepare",meaning:"準備する",breakdown:"前もって用意する。arrange は人や物の手はずを整えること"}]},

  {id:845,word:"adapt",partOfSpeech:"自動詞",meaning:"適応する",
   meanings:["自|適応する"],
   pronunciation:"/əˈdæpt/",part:85,
   example:"Children adapt to a new school very quickly.",
   exampleJa:"子どもは新しい学校にとても早く適応する。",
   example2:"These desert plants have adapted to a very dry climate.",
   exampleJa2:"これらの砂漠の植物は、とても乾いた気候に適応してきた。",
   etymologyProcess:"ad（〜へ）＋ apt（ぴったり合う）→ 新しい場所にぴったり合うよう変わると…？",
   etymologyConclusion:"ad（〜へ）＋ apt（ぴったり合う）→ 新しい環境にぴったり合うよう、自分を作り変える＝適応する",
   relatedWords:[
     {word:"apt",meaning:"～しがちな",breakdown:"apt（ぴったり合う）→ その形にぴたりと当てはまる"},
     {word:"adapter",meaning:"アダプター",breakdown:"ad（〜へ）＋ apt（ぴったり合う）＋ er（道具・人）→ 合うようにつなぐ道具"},
     {word:"attitude",meaning:"態度，姿勢",breakdown:"apt（ぴったり合う）＋ tude（名詞）→ 場に合わせた体の構え"},
     {synonym:true,word:"adjust",meaning:"調整する",breakdown:"少し直して合わせる。adapt は自分のほうを作り変えること"}]},

  {id:846,word:"match",partOfSpeech:"自動詞",meaning:"調和する",
   meanings:["自|調和する"],
   pronunciation:"/mætʃ/",part:85,
   example:"Your shoes and your bag match very well today.",
   exampleJa:"今日は、あなたの靴とかばんがとてもよく調和している。",
   example2:"The color of these curtains matches the wall perfectly.",
   exampleJa2:"これらのカーテンの色は、壁と完璧に調和している。",
   etymologyProcess:"match（似合う相手）→ 二つが似合う相手どうしなら…？",
   etymologyConclusion:"match（似合う相手）→ 二つが似合う相手どうしで、ぴたりとそろう＝調和する",
   relatedWords:[
     {word:"mismatch",meaning:"不釣り合い",breakdown:"mis（誤って）＋ match（似合う相手）→ 相手として合っていないこと"},
     {word:"matchless",meaning:"比類のない",breakdown:"match（似合う相手）＋ less（ない）→ 並ぶ相手が一人もいない"},
     {synonym:true,word:"suit",meaning:"似合う",breakdown:"その人に合う。match は二つが互いにそろうこと"},
     {synonym:true,word:"harmonize",meaning:"調子を合わせる",breakdown:"音や色をそろえる。match は二つがぴたり釣り合うこと"}]},

  {id:847,word:"fit",partOfSpeech:"自動詞",meaning:"（大きさが）合う",
   meanings:["自|（大きさが）合う"],
   pronunciation:"/fɪt/",part:85,
   example:"These new running shoes fit well, so I bought them.",
   exampleJa:"この新しいランニングシューズはぴったり合ったので、私はそれを買った。",
   example2:"The last piece did not fit into the wooden puzzle.",
   exampleJa2:"最後の一片は、その木のパズルに合わなかった。",
   etymologyProcess:"fit（ぴたりと収まる）→ すき間も余りもなく収まるなら…？",
   etymologyConclusion:"fit（ぴたりと収まる）→ すき間も余りもなく、寸法どおりに収まる＝合う",
   relatedWords:[
     {word:"fitness",meaning:"健康な状態",breakdown:"fit（ぴたりと収まる）＋ ness（名詞）→ 体が目的にぴたり合っていること"},
     {word:"outfit",meaning:"ひとそろいの服",breakdown:"out（外へ）＋ fit（ぴたりと収まる）→ 外出にぴたり合う一式"},
     {synonym:true,word:"suit",meaning:"似合う",breakdown:"その人に合う。fit は大きさや形がぴたり合うこと"},
     {synonym:true,word:"match",meaning:"調和する",breakdown:"二つがそろう。fit は寸法がぴたりと収まること"}]},

  {id:848,word:"emergency",partOfSpeech:"名詞",meaning:"緊急事態",
   meanings:["名|緊急事態"],
   pronunciation:"/iˈmɜːrdʒənsi/",part:85,
   example:"Call this number in case of a real emergency.",
   exampleJa:"本当の緊急事態の場合には、この番号に電話しなさい。",
   example2:"Our school holds an emergency drill twice a year.",
   exampleJa2:"私たちの学校は、年に2回、緊急事態の訓練を行う。",
   etymologyProcess:"e（外へ）＋ merg（沈める）→ 沈んでいたものが急に浮かび出ると…？",
   etymologyConclusion:"e（外へ）＋ merg（沈める）→ 沈んでいたものが急に外へ浮かび出るような事態＝緊急事態",
   relatedWords:[
     {word:"emerge",meaning:"現れる",breakdown:"e（外へ）＋ merg（沈める）→ 沈んでいた所から外へ浮かび上がる"},
     {word:"merge",meaning:"合併する",breakdown:"merg（沈める）→ 二つを一つに沈め込んで溶け合わせる"},
     {word:"submerge",meaning:"水中に沈める",breakdown:"sub（下で）＋ merg（沈める）→ 水面の下へ沈める"},
     {synonym:true,word:"crisis",meaning:"危機",breakdown:"分かれ目になる場面。emergency は今すぐ動くべき急な事態"}]},

  {id:849,word:"occasion",partOfSpeech:"名詞",meaning:"（特別な）行事，場合",
   meanings:["名|（特別な）行事，場合"],
   pronunciation:"/əˈkeɪʒn/",part:85,
   example:"She wears that dress only on very special occasions.",
   exampleJa:"彼女はそのドレスを、とても特別な行事のときにしか着ない。",
   example2:"The concert was a great occasion for our whole town.",
   exampleJa2:"そのコンサートは、町全体にとって大きな行事だった。",
   etymologyProcess:"oc（〜に向かって）＋ cas（落ちる）＋ ion（名詞）→ たまたま降りかかる特別な時は…？",
   etymologyConclusion:"oc（〜に向かって）＋ cas（落ちる）＋ ion（名詞）→ その身にたまたま降りかかってくる、特別な時＝行事",
   relatedWords:[
     {word:"case",meaning:"場合",breakdown:"cas（落ちる）→ その身にたまたま降りかかった出来事"},
     {word:"casual",meaning:"気楽な",breakdown:"cas（落ちる）＋ al（形容詞）→ たまたま転がり込んだように構えない"},
     {word:"occasional",meaning:"時々の",breakdown:"oc（〜に向かって）＋ cas（落ちる）＋ al（形容詞）→ たまに降りかかる程度の"},
     {synonym:true,word:"event",meaning:"出来事",breakdown:"起こったこと。occasion は特別な意味を持つそのときを指す"}]},

  {id:850,word:"accidental",partOfSpeech:"形容詞",meaning:"偶然の",
   meanings:["形|偶然の"],
   pronunciation:"/ˌæksɪˈdentl/",part:85,
   example:"The fire was accidental, not started on purpose.",
   exampleJa:"その火事は偶然のもので、わざと起こされたのではなかった。",
   example2:"Their meeting at the station was completely accidental.",
   exampleJa2:"駅での彼らの出会いは、まったくの偶然のものだった。",
   etymologyProcess:"ac（〜へ）＋ cad（落ちる）＋ al（形容詞）→ ねらわずふいに降りかかると…？",
   etymologyConclusion:"ac（〜へ）＋ cad（落ちる）＋ al（形容詞）→ ねらったわけでなく、ふいに降りかかってきた＝偶然の",
   relatedWords:[
     {word:"accident",meaning:"事故",breakdown:"ac（〜へ）＋ cad（落ちる）→ ふいに降りかかってきた出来事"},
     {word:"case",meaning:"場合",breakdown:"cas（落ちる）→ その身にたまたま降りかかった出来事"},
     {word:"occasion",meaning:"（特別な）行事",breakdown:"oc（〜に向かって）＋ cas（落ちる）＋ ion（名詞）→ たまたま降りかかる特別な時"},
     {synonym:true,word:"unexpected",meaning:"思いがけない",breakdown:"予想していなかった。accidental はたまたまそうなったこと"}]},
