  {id:151,word:"pretend",partOfSpeech:"自動詞",meaning:"～するふりをする",
   meanings:["自|（to do / that SV）（～する/ ～である）ふりをする"],
   pronunciation:"/prɪˈtend/",part:16,
   example:"He pretended to be asleep when his mother came in.",
   exampleJa:"彼は母親が入ってきたとき、眠っているふりをした。",
   example2:"Don't pretend that you already know the answer to this.",
   exampleJa2:"これの答えをもう知っているふりをしてはいけない。",
   etymologyProcess:"pre（前へ）＋ tend（伸ばす）→ 本当の姿の前に作り物を…？",
   etymologyConclusion:"pre（前へ）＋ tend（伸ばす）→ 本当の自分の前に作り物を張り出して見せる＝ふりをする",
   relatedWords:[
     {word:"tend",meaning:"～する傾向がある",breakdown:"tend（伸ばす）→ 気持ちが自然にその方向へ伸びていく"},
     {word:"extend",meaning:"延長する",breakdown:"ex（外へ）＋ tend（伸ばす）→ 外へ向けて長く伸ばす"},
     {word:"attend",meaning:"出席する",breakdown:"ad（〜へ）＋ tend（伸ばす）→ 心をその場へ伸ばして向ける"},
     {word:"intend",meaning:"～するつもりだ",breakdown:"in（中へ）＋ tend（伸ばす）→ 心を目標へまっすぐ伸ばす"}]},

  {id:152,word:"behave",partOfSpeech:"自動詞",meaning:"ふるまう",
   meanings:["自|ふるまう"],
   pronunciation:"/bɪˈheɪv/",part:16,
   example:"Please behave well when we visit the old temple.",
   exampleJa:"古いお寺を訪ねるときは、きちんとふるまってください。",
   example2:"The children behaved badly during the long bus trip.",
   exampleJa2:"子どもたちは長いバス旅行の間、行儀悪くふるまった。",
   etymologyProcess:"be（すっかり）＋ have（持つ）→ 自分の身をしっかり持つと…？",
   etymologyConclusion:"be（すっかり）＋ have（持つ）→ 自分の身をしっかり持ちこなして人前に出す＝ふるまう",
   relatedWords:[
     {word:"have",meaning:"持つ",breakdown:"have（持つ）→ 手の中に抱えて自分のものにしている"},
     {word:"behavior",meaning:"ふるまい，行動",breakdown:"be（すっかり）＋ have（持つ）＋ ior（名詞）→ 身の持ち方そのもの"},
     {word:"misbehave",meaning:"行儀悪くする",breakdown:"mis（誤って）＋ be（すっかり）＋ have（持つ）→ 身の持ち方を誤る"},
     {synonym:true,word:"act",meaning:"行動する",breakdown:"その場でとる動きそのもの。behave は行儀の良し悪しまで含む"}]},

  {id:153,word:"bear",partOfSpeech:"他動詞",meaning:"～に耐える",
   meanings:["他|（can ―）～に耐える","他|～を持つ，運ぶ","他|～を産む"],
   pronunciation:"/ber/",part:16,
   example:"I cannot bear the noise from the construction site.",
   exampleJa:"私は工事現場からの騒音に耐えられない。",
   example2:"She bore the pain without saying a single word.",
   exampleJa2:"彼女は一言も言わずにその痛みに耐えた。",
   etymologyProcess:"bear（運ぶ）→ 重いものを背負ったまま…？",
   etymologyConclusion:"bear（運ぶ）→ 重いものを背負って、投げ出さずに運び続ける＝耐える",
   etymologyMore:["重い荷を背負って運ぶ→～を持つ，運ぶ","おなかで子を運んで世に出す→～を産む"],
   hook:"芯は「運ぶ」。重荷を運ぶ→耐える、子を運ぶ→産む、とつながる。",
   relatedWords:[
     {word:"birth",meaning:"誕生",breakdown:"bear（運ぶ）＋ th（名詞）→ 運んでいた子をこの世に出すこと"},
     {word:"burden",meaning:"重荷，負担",breakdown:"bear（運ぶ）＋ den（名詞）→ 運ばなければならない重さ"},
     {synonym:true,word:"stand",meaning:"我慢する",breakdown:"倒れずに立っていられる。bear は重さを背負って耐える"},
     {synonym:true,word:"carry",meaning:"運ぶ",breakdown:"物を運ぶ担当の語。bear は苦しさまで背負う感じが出る"}]},

  {id:154,word:"explore",partOfSpeech:"他動詞",meaning:"～を探検する",
   meanings:["他|～を探検する，（街など）を探索する","他|（問題など）を探る"],
   pronunciation:"/ɪkˈsplɔːr/",part:16,
   example:"They explored the old cave near the river yesterday.",
   exampleJa:"彼らは昨日、川の近くの古い洞窟を探検した。",
   example2:"Let's explore the museum before the concert starts.",
   exampleJa2:"コンサートが始まる前に博物館を探検しよう。",
   etymologyProcess:"ex（外へ）＋ plore（叫ぶ）→ 声を上げて未知の場所へ…？",
   etymologyConclusion:"ex（外へ）＋ plore（叫ぶ）→ 外へ声を上げながら未知の場所へ踏み込む＝探検する",
   relatedWords:[
     {word:"exit",meaning:"出口",breakdown:"ex（外へ）＋ ite（行く）→ 外へ出て行くためのところ"},
     {word:"export",meaning:"輸出する",breakdown:"ex（外へ）＋ port（運ぶ）→ 品物を国の外へ運び出す"},
     {word:"explode",meaning:"爆発する",breakdown:"ex（外へ）＋ plode（手を叩く）→ パンと打ち鳴らして外へ弾け出る"},
     {word:"explorer",meaning:"探検家",breakdown:"ex（外へ）＋ plore（叫ぶ）＋ er（人）→ 未知の外へ踏み出す人"}]},

  {id:155,word:"happen",partOfSpeech:"自動詞",meaning:"（偶然）起こる",
   meanings:["自|（to ～）（～に）起こる","自|（to do）偶然～する"],
   pronunciation:"/ˈhæpən/",part:16,
   example:"A strange thing happened on my way to school.",
   exampleJa:"学校へ行く途中で、おかしなことが起こった。",
   example2:"What will happen if we miss the last train?",
   exampleJa2:"最終電車に乗り遅れたら、何が起こるだろうか。",
   etymologyProcess:"hap（偶然）＋ en（〜にする）→ 運がふっと降ってくると…？",
   etymologyConclusion:"hap（偶然）＋ en（〜にする）→ 運がふっと降ってきて、思いがけないことが生じる＝起こる",
   relatedWords:[
     {word:"happy",meaning:"幸せな",breakdown:"hap（偶然）＋ y（形容詞）→ 良い偶然に恵まれた気分"},
     {word:"perhaps",meaning:"たぶん",breakdown:"per（すっかり）＋ hap（偶然）→ 偶然しだいで、そうかもしれない"},
     {word:"mishap",meaning:"ちょっとした災難",breakdown:"mis（誤って）＋ hap（偶然）→ 悪いほうに転んだ偶然"},
     {word:"happening",meaning:"出来事",breakdown:"hap（偶然）＋ en（〜にする）＋ ing（名詞）→ 偶然起きたことがら"}]},

  {id:156,word:"appear",partOfSpeech:"自動詞",meaning:"現れる",
   meanings:["自|現れる","自|（to be ～）～のように思える"],
   pronunciation:"/əˈpɪr/",part:16,
   example:"A rainbow appeared in the sky after the rain.",
   exampleJa:"雨のあと、空に虹が現れた。",
   example2:"She did not appear at the meeting yesterday.",
   exampleJa2:"彼女は昨日その会議に現れなかった。",
   etymologyProcess:"ad（〜へ）＋ pear（見えてくる）→ こちらの目の前に姿が…？",
   etymologyConclusion:"ad（〜へ）＋ pear（見えてくる）→ こちらの目の前に姿が出てきて見える＝現れる",
   etymologyMore:["目に映る姿がそう見える→（to be ～）～のように思える"],
   relatedWords:[
     {word:"appearance",meaning:"外見；出現",breakdown:"ad（〜へ）＋ pear（見えてくる）＋ ance（名詞）→ 目に見えてくる姿"},
     {word:"disappear",meaning:"消える",breakdown:"dis（否定）＋ ad（〜へ）＋ pear（見えてくる）→ 見えていた姿が消える"},
     {synonym:true,word:"show up",meaning:"現れる，姿を見せる",breakdown:"話し言葉で「現れる」。appear は書き言葉でも使える"},
     {synonym:true,word:"seem",meaning:"～のように思われる",breakdown:"そう感じられる。appear は目に見える形で感じられる"}]},

  {id:157,word:"remain",partOfSpeech:"自動詞",meaning:"～のままでいる",
   meanings:["自|～のままでいる","自|残る"],
   pronunciation:"/rɪˈmeɪn/",part:16,
   example:"The classroom remained quiet during the long math test.",
   exampleJa:"長い数学のテストの間、教室は静かなままだった。",
   example2:"The problem remains difficult even after a long discussion.",
   exampleJa2:"長い話し合いのあとも、その問題は難しいままでいる。",
   etymologyProcess:"re（後ろへ）＋ main（とどまる）→ みんなが去った後ろに…？",
   etymologyConclusion:"re（後ろへ）＋ main（とどまる）→ みんなが去った後ろにそのままとどまり続ける＝～のままでいる",
   relatedWords:[
     {word:"remainder",meaning:"残り",breakdown:"re（後ろへ）＋ main（とどまる）＋ der（名詞）→ 後ろに残ったぶん"},
     {word:"permanent",meaning:"永久的な",breakdown:"per（すっかり）＋ main（とどまる）→ ずっととどまり続ける"},
     {synonym:true,word:"stay",meaning:"とどまる",breakdown:"その場に居続ける。remain は状態が変わらず続くこと"},
     {word:"remains",meaning:"残り物；遺跡",breakdown:"re（後ろへ）＋ main（とどまる）→ 後に残ってとどまったもの"}]},

  {id:158,word:"survive",partOfSpeech:"自動詞",meaning:"生き残る",
   meanings:["自|生き残る","他|～から生き延びる，～の後も存続する"],
   pronunciation:"/sərˈvaɪv/",part:16,
   example:"Only two passengers survived after the terrible train accident.",
   exampleJa:"2人の乗客だけがそのひどい列車事故で生き残った。",
   example2:"These small plants can survive in very cold weather.",
   exampleJa2:"この小さな植物は、とても寒い気候でも生き残ることができる。",
   etymologyProcess:"sur（上を越えて）＋ viv（生きる）→ 危機を越えて向こう側まで…？",
   etymologyConclusion:"sur（上を越えて）＋ viv（生きる）→ 危機の山を越えて向こう側まで生き続ける＝生き残る",
   relatedWords:[
     {word:"survival",meaning:"生存",breakdown:"sur（上を越えて）＋ viv（生きる）＋ al（名詞）→ 越えて生き続けること"},
     {word:"revive",meaning:"よみがえる",breakdown:"re（再び）＋ viv（生きる）→ 消えかけた生気がもう一度戻る"},
     {word:"vivid",meaning:"鮮やかな",breakdown:"viv（生きる）＋ id（〜な状態の）→ 生きているように生き生きしている"},
     {synonym:true,word:"live",meaning:"生きる",breakdown:"いちばん日常の「生きる」。survive は危機を越えて生き残る"}]},

  {id:159,word:"belong",partOfSpeech:"自動詞",meaning:"所属している",
   meanings:["自|（to ～）（～に）所属している"],
   pronunciation:"/bɪˈlɔːŋ/",part:16,
   example:"This blue umbrella belongs to my younger sister.",
   exampleJa:"この青い傘は妹のものだ。",
   example2:"I want to belong to the soccer club next year.",
   exampleJa2:"私は来年サッカー部に所属したい。",
   etymologyProcess:"be（すっかり）＋ long（沿って続く）→ ぴったり沿って続くと…？",
   etymologyConclusion:"be（すっかり）＋ long（沿って続く）→ ある人や場所にぴったり沿って続く＝所属している",
   relatedWords:[
     {word:"long",meaning:"長い",breakdown:"long（沿って続く）→ 端から端までずっと沿って続いている"},
     {word:"length",meaning:"長さ",breakdown:"long（沿って続く）＋ th（名詞）→ 沿って続いている量"},
     {synonym:true,word:"member",meaning:"一員，メンバー",breakdown:"団体の一員。belong to ～ はその member であること"},
     {word:"belongings",meaning:"持ち物",breakdown:"be（すっかり）＋ long（沿って続く）＋ ings（名詞）→ 自分に付き従うもの"}]},

  {id:160,word:"represent",partOfSpeech:"他動詞",meaning:"～を代表する",
   meanings:["他|～を代表する","他|（記号などが）を表す","他|～を表現する"],
   pronunciation:"/ˌreprɪˈzent/",part:16,
   example:"She represented our school at the speech contest.",
   exampleJa:"彼女はスピーチ大会で私たちの学校を代表した。",
   example2:"This red line represents the school bus route.",
   exampleJa2:"この赤い線はスクールバスの経路を表す。",
   etymologyProcess:"re（再び）＋ pre（前へ）＋ sent（いる）→ いない人をもう一度人前に…？",
   etymologyConclusion:"re（再び）＋ pre（前へ）＋ sent（いる）→ その場にいない人をもう一度人前に立たせる＝代表する",
   etymologyMore:["形のないものを人前に出して示す→（記号などが）を表す","中身を人前に出して見せる→～を表現する"],
   relatedWords:[
     {word:"present",meaning:"現在の；出席して",breakdown:"pre（前へ）＋ sent（いる）→ 目の前にいる、今この場にある"},
     {word:"presence",meaning:"存在，居ること",breakdown:"pre（前へ）＋ sent（いる）＋ ence（名詞）→ その場にいること"},
     {word:"absent",meaning:"欠席の",breakdown:"ab（離れて）＋ sent（いる）→ その場から離れていて、ここにいない"},
     {word:"representative",meaning:"代表者",breakdown:"re（再び）＋ pre（前へ）＋ sent（いる）→ みんなの代わりに前に立つ人"}]},

  {id:161,word:"base",partOfSpeech:"他動詞",meaning:"～の基礎を置く",
   meanings:["他|～の基礎を置く","名|基礎（の部分），基盤","名|基地"],
   pronunciation:"/beɪs/",part:17,
   example:"The movie is based on a true war story.",
   exampleJa:"その映画は本当の戦争の話に基礎を置いている。",
   example2:"They based their plan on last year's sales data.",
   exampleJa2:"彼らは昨年の売り上げデータに計画の基礎を置いた。",
   etymologyProcess:"bas（踏み台・土台）→ 全体を下から支える台として…？",
   etymologyConclusion:"bas（踏み台・土台）→ 全体を下から支える台として、どっしり置く＝基礎を置く",
   etymologyMore:["全体を支えている一番下→基礎（の部分），基盤","活動を支える拠点→基地"],
   relatedWords:[
     {word:"basic",meaning:"基本的な",breakdown:"bas（踏み台・土台）＋ ic（形容詞）→ 土台にあたるところの"},
     {word:"basement",meaning:"地下室",breakdown:"bas（踏み台・土台）＋ ment（名詞）→ 建物のいちばん低いところ"},
     {word:"basis",meaning:"基礎，根拠",breakdown:"bas（踏み台・土台）→ 考えを乗せて支える土台"},
     {synonym:true,word:"foundation",meaning:"土台，基礎",breakdown:"建物を支える基礎。base より大がかりな土台を指す"}]},

  {id:162,word:"include",partOfSpeech:"他動詞",meaning:"～を含む",
   meanings:["他|～を含む"],
   pronunciation:"/ɪnˈkluːd/",part:17,
   example:"The price includes breakfast and free wifi at the hotel.",
   exampleJa:"その値段はホテルの朝食と無料Wi-Fiを含む。",
   example2:"Does this tour include lunch at the old castle?",
   exampleJa2:"この旅行は古い城での昼食を含みますか。",
   etymologyProcess:"in（中へ）＋ clude（閉じる）→ 囲いの中に閉じ込めると…？",
   etymologyConclusion:"in（中へ）＋ clude（閉じる）→ 囲いの中に閉じ込めて仲間の一つに入れる＝含む",
   relatedWords:[
     {word:"close",meaning:"閉じる",breakdown:"clos（閉じる）→ 開いていた口をぴたりと閉じる"},
     {word:"exclude",meaning:"除外する",breakdown:"ex（外へ）＋ clude（閉じる）→ 外へ締め出して中に入れない"},
     {word:"conclude",meaning:"結論を下す",breakdown:"con（すっかり）＋ clude（閉じる）→ 話をすっかり閉じてしめくくる"},
     {word:"disclose",meaning:"公表する",breakdown:"dis（否定）＋ clos（閉じる）→ 閉じていたものを開いて見せる"}]},

  {id:163,word:"contain",partOfSpeech:"他動詞",meaning:"～を含んでいる",
   meanings:["他|～を含んでいる，中に入れている","他|（主に否定で）～を抑える"],
   pronunciation:"/kənˈteɪn/",part:17,
   example:"This wooden box contains all of my old photos.",
   exampleJa:"この木の箱は私の古い写真を全部含んでいる。",
   example2:"The drink does not contain any sugar at all.",
   exampleJa2:"その飲み物は砂糖をまったく含んでいない。",
   etymologyProcess:"con（共に）＋ tin（保つ）→ 中身をまとめてしっかり…？",
   etymologyConclusion:"con（共に）＋ tin（保つ）→ 中身をひとまとめにして、こぼさず保つ＝含んでいる",
   etymologyMore:["あふれそうな気持ちを内に保つ→（主に否定で）～を抑える"],
   relatedWords:[
     {word:"continue",meaning:"続ける",breakdown:"con（共に）＋ tin（保つ）→ 切れないようにつなぎ保ち続ける"},
     {word:"container",meaning:"容器",breakdown:"con（共に）＋ tin（保つ）＋ er（もの）→ 中身をまとめて保つ入れ物"},
     {word:"maintain",meaning:"維持する",breakdown:"manu（手）＋ tin（保つ）→ 手で支えて同じ状態に保ち続ける"},
     {word:"obtain",meaning:"手に入れる",breakdown:"ob（〜に向かって）＋ tin（保つ）→ 手を伸ばして自分の側に保つ"}]},

  {id:164,word:"own",partOfSpeech:"形容詞",meaning:"自分自身の",
   meanings:["形|（所有格の後で）自分自身の","形|（名詞的に）自分自身のもの","他|～を所有している"],
   pronunciation:"/oʊn/",part:17,
   example:"I want my own room in the new house.",
   exampleJa:"新しい家では自分自身の部屋がほしい。",
   example2:"She cooked the whole dinner with her own hands.",
   exampleJa2:"彼女は夕食を全部、自分自身の手で作った。",
   etymologyProcess:"own（持っている）→ 手の中にしっかり持っているのは…？",
   etymologyConclusion:"own（持っている）→ ほかの誰でもなく自分の手の中に持っている＝自分自身の",
   etymologyMore:["持っていることを言い切る→～を所有している"],
   hook:"one's own の形で「自分自身の」。動詞なら「所有している」。",
   relatedWords:[
     {word:"owner",meaning:"持ち主",breakdown:"own（持っている）＋ er（人）→ それを自分のものとして持つ人"},
     {word:"ownership",meaning:"所有権",breakdown:"own（持っている）＋ ship（名詞）→ 持ち主である状態"},
     {synonym:true,word:"have",meaning:"持っている",breakdown:"いちばん広く使う「持つ」。own は所有者だと言い切る"},
     {synonym:true,word:"possess",meaning:"所有している",breakdown:"堅い場面の「所有する」。own は日常の言い方"}]},

  {id:165,word:"share",partOfSpeech:"他動詞",meaning:"～を共有する",
   meanings:["他|～を共有する","他|（考えなど）を（人に）伝える","名|共有","名|分け前"],
   pronunciation:"/ʃer/",part:17,
   example:"We share a small room with two other students.",
   exampleJa:"私たちはほかの2人の生徒と小さな部屋を共有している。",
   example2:"She shared her lunch with her hungry friend.",
   exampleJa2:"彼女はおなかをすかせた友達と昼食を共有した。",
   etymologyProcess:"shar（切り分ける）→ 一つのものを切り分けて…？",
   etymologyConclusion:"shar（切り分ける）→ 一つのものを切り分けて、みんなで一緒に持つ＝共有する",
   etymologyMore:["気持ちを切り分けて相手に渡す→（考えなど）を（人に）伝える","切り分けられた一つ分→分け前"],
   relatedWords:[
     {word:"short",meaning:"短い",breakdown:"shor（切り分ける）→ 切り取られて長さが足りない"},
     {word:"shirt",meaning:"シャツ",breakdown:"shir（切り分ける）→ 布を切って作った短い上着"},
     {synonym:true,word:"divide",meaning:"分ける",breakdown:"全体を分割する。share は分けて一緒に持つこと"},
     {synonym:true,word:"portion",meaning:"分け前，1人前",breakdown:"分けられた一人分。share した結果の一つ分"}]},

  {id:166,word:"collect",partOfSpeech:"他動詞",meaning:"（同種の物）を集める",
   meanings:["他|（同種の物）を集める","他|～を徴収する，回収する"],
   pronunciation:"/kəˈlekt/",part:17,
   example:"My brother collects old coins from many countries.",
   exampleJa:"兄は多くの国の古い硬貨を集めている。",
   example2:"The teacher collected the answer papers after the test.",
   exampleJa2:"先生はテストのあとで答案用紙を集めた。",
   etymologyProcess:"col（共に）＋ lect（拾う）→ ばらばらの物を一か所へ…？",
   etymologyConclusion:"col（共に）＋ lect（拾う）→ ばらばらの物を一か所へ拾い寄せる＝集める",
   relatedWords:[
     {word:"collection",meaning:"収集，コレクション",breakdown:"col（共に）＋ lect（拾う）＋ ion（名詞）→ 拾い集めたもののまとまり"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離して）＋ lect（拾う）→ 全体から離して拾い上げる"},
     {word:"elect",meaning:"（選挙で）選ぶ",breakdown:"e（外へ）＋ lect（拾う）→ 大勢の中から外へ拾い出す"},
     {word:"lecture",meaning:"講義",breakdown:"lect（拾う）＋ ure（名詞）→ 言葉を拾い読みして聞かせる場"}]},

  {id:167,word:"gather",partOfSpeech:"他動詞",meaning:"～をかき集める",
   meanings:["他|～をかき集める","自|集まる"],
   pronunciation:"/ˈɡæðər/",part:17,
   example:"She gathered dry leaves for the science class.",
   exampleJa:"彼女は理科の授業のために枯れ葉をかき集めた。",
   example2:"A large crowd gathered in front of the station.",
   exampleJa2:"大勢の人が駅前に集まった。",
   etymologyProcess:"gather（一つにまとめる）→ 散らばった物を手元へ…？",
   etymologyConclusion:"gather（一つにまとめる）→ 散らばった物を手元へ寄せて一つにする＝かき集める",
   etymologyMore:["人が一か所に寄り合う→集まる"],
   hook:"together（to＋gather）と同じ語。「一か所に寄せる」が芯。",
   relatedWords:[
     {word:"together",meaning:"一緒に",breakdown:"to（〜へ）＋ gather（一つにまとめる）→ 一か所に寄せ合って"},
     {word:"gathering",meaning:"集まり，会合",breakdown:"gather（一つにまとめる）＋ ing（名詞）→ 人が寄り集まった場"},
     {synonym:true,word:"collect",meaning:"集める",breakdown:"同種の物を計画的に集める。gather は散らばった物を寄せる"},
     {synonym:true,word:"crowd",meaning:"群衆",breakdown:"人が寄り集まったかたまり。gather した結果の姿"}]},

  {id:168,word:"history",partOfSpeech:"名詞",meaning:"歴史",
   meanings:["名|歴史","名|履歴，前歴，病歴"],
   pronunciation:"/ˈhɪstəri/",part:17,
   example:"We learn world history twice a week at school.",
   exampleJa:"私たちは学校で週に2回、世界の歴史を学ぶ。",
   example2:"The small town has a long and rich history.",
   exampleJa2:"その小さな町には長く豊かな歴史がある。",
   etymologyProcess:"histor（知っている人）＋ y（名詞）→ 見て知っている人が語り継いだのは…？",
   etymologyConclusion:"histor（知っている人）＋ y（名詞）→ 見て知っている人が語り継いできた出来事＝歴史",
   etymologyMore:["その人がたどってきた記録→履歴，前歴，病歴"],
   relatedWords:[
     {word:"story",meaning:"物語，話",breakdown:"histor（知っている人）→ 語り継がれた話。h が落ちた形"},
     {word:"historic",meaning:"歴史的な",breakdown:"histor（知っている人）＋ ic（形容詞）→ 語り継がれるほど重要な"},
     {word:"historian",meaning:"歴史家",breakdown:"histor（知っている人）＋ ian（人）→ 過去を調べて語る人"},
     {word:"prehistoric",meaning:"有史以前の",breakdown:"pre（前へ）＋ histor（知っている人）→ 記録が語られるより前の"}]},

  {id:169,word:"subject",partOfSpeech:"名詞",meaning:"（学校の）科目",
   meanings:["名|（学校の）科目","名|話題","名|被験者","形|（be ― to ～）～を受けやすい"],
   pronunciation:"/ˈsʌbdʒɪkt/",part:17,
   example:"My favorite subject is science at this school.",
   exampleJa:"この学校で私のいちばん好きな科目は理科だ。",
   example2:"Which subject do you want to study at university?",
   exampleJa2:"大学ではどの科目を勉強したいですか。",
   etymologyProcess:"sub（下で）＋ ject（投げる）→ 大きな枠の下に投げ入れられた一つは…？",
   etymologyConclusion:"sub（下で）＋ ject（投げる）→ 学問という枠の下に投げ入れた一区切り＝科目",
   etymologyMore:["話の枠の下に置かれたもの→話題","実験の枠の下に置かれた人→被験者"],
   relatedWords:[
     {word:"object",meaning:"物；反対する",breakdown:"ob（〜に向かって）＋ ject（投げる）→ 目の前に投げ出された物"},
     {word:"project",meaning:"計画，企画",breakdown:"pro（前へ）＋ ject（投げる）→ 先へ向けて投げ出す計画"},
     {word:"reject",meaning:"拒絶する",breakdown:"re（戻す）＋ ject（投げる）→ 投げ返して受け取らない"},
     {word:"injection",meaning:"注射",breakdown:"in（中へ）＋ ject（投げる）＋ ion（名詞）→ 体の中へ薬を投げ入れること"}]},

  {id:170,word:"education",partOfSpeech:"名詞",meaning:"教育",
   meanings:["名|教育"],
   pronunciation:"/ˌedʒuˈkeɪʃn/",part:17,
   example:"Good education helps children find their own dreams.",
   exampleJa:"良い教育は子どもが自分の夢を見つける助けになる。",
   example2:"She studied education at a university in Canada.",
   exampleJa2:"彼女はカナダの大学で教育を勉強した。",
   etymologyProcess:"e（外へ）＋ duc（導く）＋ ation（名詞）→ 中の力を外へ導き出すのは…？",
   etymologyConclusion:"e（外へ）＋ duc（導く）＋ ation（名詞）→ 子どもの中に眠る力を外へ導き出すこと＝教育",
   relatedWords:[
     {word:"educate",meaning:"教育する",breakdown:"e（外へ）＋ duc（導く）＋ ate（動詞）→ 内側の力を外へ導き出す"},
     {word:"introduce",meaning:"紹介する",breakdown:"intro（内へ）＋ duc（導く）→ 中へ導き入れて引き合わせる"},
     {word:"produce",meaning:"生産する",breakdown:"pro（前へ）＋ duc（導く）→ 前へ導き出して形にする"},
     {word:"reduce",meaning:"減らす",breakdown:"re（戻す）＋ duc（導く）→ 元の小ささへ導き戻す"}]},

  {id:171,word:"knowledge",partOfSpeech:"名詞",meaning:"知識",
   meanings:["名|知識，知っていること"],
   pronunciation:"/ˈnɑːlɪdʒ/",part:18,
   example:"Her knowledge of wild plants surprised the science teacher.",
   exampleJa:"野生植物についての彼女の知識は理科の先生を驚かせた。",
   example2:"You need some basic knowledge of computers for this job.",
   exampleJa2:"この仕事にはコンピュータの基本的な知識が必要だ。",
   etymologyProcess:"know（知る）＋ ledge（あり方）→ 知っている中身がたまると…？",
   etymologyConclusion:"know（知る）＋ ledge（あり方）→ 知っている中身が頭の中にたまったもの＝知識",
   relatedWords:[
     {word:"know",meaning:"知る",breakdown:"know（知る）→ 頭の中でそれが何かわかっている"},
     {word:"known",meaning:"知られた",breakdown:"know（知る）＋ n（〜された）→ みんなに知られている"},
     {word:"acknowledge",meaning:"認める",breakdown:"ad（〜へ）＋ know（知る）→ 知っていると相手へ向けて示す"},
     {synonym:true,word:"wisdom",meaning:"知恵",breakdown:"知識を使いこなす力。knowledge は知っている中身そのもの"}]},

  {id:172,word:"uniform",partOfSpeech:"名詞",meaning:"制服",
   meanings:["名|制服","形|同一の，一定の"],
   pronunciation:"/ˈjuːnɪfɔːrm/",part:18,
   example:"Our school uniform has a dark blue jacket.",
   exampleJa:"私たちの学校の制服には紺色の上着がある。",
   example2:"All the players wore the same uniform yesterday.",
   exampleJa2:"選手は全員、昨日は同じ制服を着ていた。",
   etymologyProcess:"uni（1つの）＋ form（形）→ 全員が同じ形の服を着ると…？",
   etymologyConclusion:"uni（1つの）＋ form（形）→ 集団の全員が同じ一つの形の服を着る＝制服",
   etymologyMore:["形が一つにそろっている→同一の，一定の"],
   relatedWords:[
     {word:"form",meaning:"形；形成する",breakdown:"form（形）→ 外から見える姿かたちそのもの"},
     {word:"unite",meaning:"団結する",breakdown:"uni（1つの）＋ ite（〜された）→ ばらばらの物が一つにされる"},
     {word:"unique",meaning:"独特の",breakdown:"uni（1つの）＋ ique（形容詞）→ ほかにない、ただ一つの"},
     {word:"formal",meaning:"正式な",breakdown:"form（形）＋ al（形容詞）→ 決まった形にきちんと従った"}]},

  {id:173,word:"grade",partOfSpeech:"名詞",meaning:"（小中高の）学年",
   meanings:["名|（小，中，高の）学年","名|等級","名|成績"],
   pronunciation:"/ɡreɪd/",part:18,
   example:"My sister is in the sixth grade this year.",
   exampleJa:"妹は今年、6年生の学年にいる。",
   example2:"Students in the higher grades practice sports after school.",
   exampleJa2:"上の学年の生徒は放課後にスポーツを練習する。",
   etymologyProcess:"grad（歩み・段）→ 一段ずつ上がっていく段の一つは…？",
   etymologyConclusion:"grad（歩み・段）→ 一段ずつ上がる階段の、今いる一段＝学年",
   etymologyMore:["品質を段で分けたもの→等級","出来ばえを段で表したもの→成績"],
   relatedWords:[
     {word:"gradually",meaning:"徐々に",breakdown:"grad（歩み・段）＋ al（形容詞）＋ ly（副詞）→ 一段ずつ進むように"},
     {word:"upgrade",meaning:"格上げする",breakdown:"up（上へ）＋ grad（歩み・段）→ 一段上へ引き上げる"},
     {word:"progress",meaning:"進歩する",breakdown:"pro（前へ）＋ gress（歩む）→ 前へ歩みを一段ずつ進める"},
     {synonym:true,word:"level",meaning:"水準，段階",breakdown:"高さの水準。grade は学年や等級としての段を指す"}]},

  {id:174,word:"senior",partOfSpeech:"名詞",meaning:"（高校・大学の）最上級生",
   meanings:["名|（高校， 大学の）最上級生","形|高齢者の","形|（地位が）上位の"],
   pronunciation:"/ˈsiːniər/",part:18,
   example:"The seniors will graduate from high school in March.",
   exampleJa:"最上級生たちは3月に高校を卒業する。",
   example2:"He is a senior at a high school in Osaka.",
   exampleJa2:"彼は大阪の高校の最上級生だ。",
   etymologyProcess:"sen（年をとった）＋ ior（より〜な）→ より年を重ねて上にいるのは…？",
   etymologyConclusion:"sen（年をとった）＋ ior（より〜な）→ より長く年を重ねて上にいる人＝最上級生",
   etymologyMore:["年を重ねている→高齢者の","年功で上に立つ→（地位が）上位の"],
   relatedWords:[
     {word:"junior",meaning:"年下の，下級の",breakdown:"jun（若い）＋ ior（より〜な）→ より若いほうの"},
     {word:"senate",meaning:"上院",breakdown:"sen（年をとった）＋ ate（名詞）→ 年長者が集まって決める場"},
     {word:"sir",meaning:"（男性への敬称）",breakdown:"sen（年をとった）→ 年上の人への呼びかけが縮まった形"},
     {synonym:true,word:"elder",meaning:"年長の",breakdown:"年上であること。senior は学年や地位が上の意味も持つ"}]},

  {id:175,word:"graduate",partOfSpeech:"自動詞",meaning:"卒業する",
   meanings:["自|（from ～）（～を）卒業する"],
   pronunciation:"/ˈɡrædʒueɪt/",part:18,
   example:"My older brother graduated from college last spring.",
   exampleJa:"兄は去年の春に大学を卒業した。",
   example2:"She will graduate from high school next March.",
   exampleJa2:"彼女は来年の3月に高校を卒業する。",
   etymologyProcess:"grad（歩み・段）＋ ate（動詞）→ 決められた段を上りきると…？",
   etymologyConclusion:"grad（歩み・段）＋ ate（動詞）→ 決められた段を最後まで上りきって外へ出る＝卒業する",
   relatedWords:[
     {word:"grade",meaning:"学年；等級",breakdown:"grad（歩み・段）→ 一段ずつ上がる階段の一段"},
     {word:"graduation",meaning:"卒業（式）",breakdown:"grad（歩み・段）＋ ation（名詞）→ 段を上りきること"},
     {word:"gradual",meaning:"徐々の",breakdown:"grad（歩み・段）＋ al（形容詞）→ 一段ずつ進むような"},
     {synonym:true,word:"finish",meaning:"終える",breakdown:"やり終える。graduate は学校の課程を正式に終えること"}]},

  {id:176,word:"decide",partOfSpeech:"他動詞",meaning:"～を決定する",
   meanings:["他|（to do）（～すること）を決定する，決心する","自|（on ～）（～を）決める"],
   pronunciation:"/dɪˈsaɪd/",part:18,
   example:"We decided to meet at the station at noon.",
   exampleJa:"私たちは正午に駅で会うことに決定した。",
   example2:"She decided the date of the school festival.",
   exampleJa2:"彼女は文化祭の日程を決定した。",
   etymologyProcess:"de（離して）＋ cis（切る）→ ほかの案を切り落とすと…？",
   etymologyConclusion:"de（離して）＋ cis（切る）→ ほかの案をすっぱり切り落として一つに絞る＝決定する",
   relatedWords:[
     {word:"decision",meaning:"決定",breakdown:"de（離して）＋ cis（切る）＋ ion（名詞）→ 切り落として決めたこと"},
     {word:"scissors",meaning:"はさみ",breakdown:"cis（切る）＋ ors（もの）→ 二枚の刃で物を切る道具"},
     {word:"precise",meaning:"正確な",breakdown:"pre（前へ）＋ cis（切る）→ 前もってきっちり切りそろえた"},
     {synonym:true,word:"choose",meaning:"選ぶ",breakdown:"並んだ中から選ぶ。decide は迷いを切り捨てて決める"}]},

  {id:177,word:"judge",partOfSpeech:"他動詞",meaning:"～を判断する",
   meanings:["他|～を判断する","名|裁判官，審判（員）"],
   pronunciation:"/dʒʌdʒ/",part:18,
   example:"Don't judge a person only by his old clothes.",
   exampleJa:"古い服だけでその人を判断してはいけない。",
   example2:"We should not judge people by their first words.",
   exampleJa2:"最初の一言で人を判断すべきではない。",
   etymologyProcess:"jur（正しい・法）＋ dict（言う）→ 何が正しいかを言い渡すのは…？",
   etymologyConclusion:"jur（正しい・法）＋ dict（言う）→ 何が正しいかを見きわめて言い渡す＝判断する",
   etymologyMore:["法廷で正しさを言い渡す人→裁判官，審判（員）"],
   relatedWords:[
     {word:"justice",meaning:"正義",breakdown:"jur（正しい・法）＋ ice（名詞）→ 正しさが世の中に通ること"},
     {word:"dictionary",meaning:"辞書",breakdown:"dict（言う）＋ ary（もの）→ 言葉の意味を言い並べた本"},
     {word:"judgment",meaning:"判断",breakdown:"jur（正しい・法）＋ dict（言う）＋ ment（名詞）→ 言い渡された結論"},
     {word:"prejudice",meaning:"偏見",breakdown:"pre（前へ）＋ jur（正しい・法）＋ dict（言う）→ 知る前の決めつけ"}]},

  {id:178,word:"quit",partOfSpeech:"他動詞",meaning:"～を（完全に）やめる",
   meanings:["他|～を（完全に）やめる"],
   pronunciation:"/kwɪt/",part:18,
   example:"He quit his part-time job at the cafe last month.",
   exampleJa:"彼は先月、カフェのアルバイトを完全にやめた。",
   example2:"My father decided to quit smoking this year.",
   exampleJa2:"父は今年たばこをやめると決めた。",
   etymologyProcess:"quit（静かにする）→ 動いていた手を止めて静かになると…？",
   etymologyConclusion:"quit（静かにする）→ 続けていた動きを止めて、そこから手を引く＝やめる",
   relatedWords:[
     {word:"quiet",meaning:"静かな",breakdown:"quit（静かにする）→ 音も動きも止まっている"},
     {word:"quite",meaning:"すっかり，かなり",breakdown:"quit（静かにする）→ すっかり片がついて動かない"},
     {synonym:true,word:"stop",meaning:"やめる，止まる",breakdown:"動きを止める。quit は続けてきたことを完全にやめる"},
     {synonym:true,word:"give up",meaning:"あきらめる",breakdown:"途中で投げ出す。quit は自分の意志で切り上げる"}]},

  {id:179,word:"retire",partOfSpeech:"自動詞",meaning:"引退する",
   meanings:["自|（from ～）（～を）引退する，退職する"],
   pronunciation:"/rɪˈtaɪər/",part:18,
   example:"My grandfather retired from the company five years ago.",
   exampleJa:"祖父は5年前にその会社を引退した。",
   example2:"She wants to retire early and travel around Asia.",
   exampleJa2:"彼女は早く引退してアジアを旅したいと思っている。",
   etymologyProcess:"re（後ろへ）＋ tir（引く）→ 第一線から身を後ろへ…？",
   etymologyConclusion:"re（後ろへ）＋ tir（引く）→ 第一線から自分の身を後ろへ引き下げる＝引退する",
   relatedWords:[
     {word:"retirement",meaning:"引退，退職",breakdown:"re（後ろへ）＋ tir（引く）＋ ment（名詞）→ 身を後ろへ引くこと"},
     {word:"retreat",meaning:"退く，撤退する",breakdown:"re（後ろへ）＋ treat（引く）→ 後ろへ身を引いて下がる"},
     {synonym:true,word:"quit",meaning:"やめる",breakdown:"自分からやめる。retire は年齢や区切りで職を退く"},
     {synonym:true,word:"leave",meaning:"去る",breakdown:"その場を去る。retire は仕事から正式に退くこと"}]},

  {id:180,word:"review",partOfSpeech:"名詞",meaning:"再検討",
   meanings:["名|再検討","名|（新聞などの）批評","名|復習"],
   pronunciation:"/rɪˈvjuː/",part:18,
   example:"We had a quick review of the last lesson.",
   exampleJa:"私たちは前回の授業をざっと再検討した。",
   example2:"Her review of the new movie was very kind.",
   exampleJa2:"新作映画についての彼女の批評はとても優しかった。",
   etymologyProcess:"re（再び）＋ vis（見る）→ もう一度ていねいに見直すのは…？",
   etymologyConclusion:"re（再び）＋ vis（見る）→ 一度通ったものをもう一度ていねいに見直すこと＝再検討",
   etymologyMore:["作品を見直して評を書く→（新聞などの）批評","習ったことを見直す→復習"],
   relatedWords:[
     {word:"view",meaning:"眺め；見方",breakdown:"vis（見る）→ 目に入ってくる眺めそのもの"},
     {word:"interview",meaning:"面接，インタビュー",breakdown:"inter（間の）＋ vis（見る）→ 二人の間で顔を見合って話す"},
     {word:"revise",meaning:"修正する",breakdown:"re（再び）＋ vis（見る）→ もう一度見て手を入れ直す"},
     {word:"supervise",meaning:"監督する",breakdown:"super（上から）＋ vis（見る）→ 上から全体を見張る"}]},

  {id:181,word:"choose",partOfSpeech:"他動詞",meaning:"～を選ぶ",
   meanings:["他|～を選ぶ","自|選ぶ"],
   pronunciation:"/tʃuːz/",part:19,
   example:"You can choose any color you like for this bag.",
   exampleJa:"このかばんは好きな色を選ぶことができる。",
   example2:"She chose the red one at the small shop.",
   exampleJa2:"彼女は小さな店で赤いものを選んだ。",
   etymologyProcess:"choos（味わってみる）→ あれこれ味わってから取るのは…？",
   etymologyConclusion:"choos（味わってみる）→ あれこれ味わってみて、気に入ったほうを取る＝選ぶ",
   hook:"choose → chose → chosen と変化する。つづりの o の数に注意。",
   relatedWords:[
     {word:"choice",meaning:"選択，選ぶこと",breakdown:"choos（味わってみる）→ 味わってみて選び取った結果そのもの"},
     {synonym:true,word:"pick",meaning:"選び取る",breakdown:"手でひょいと取り上げる。choose はよく考えて選ぶ"},
     {synonym:true,word:"select",meaning:"選び出す",breakdown:"多くの中から選び出す。choose より堅い場面で使う"},
     {synonym:true,word:"decide",meaning:"決める",breakdown:"迷いを切って決める。choose は並んだ中から取り出す"}]},

  {id:182,word:"imagine",partOfSpeech:"他動詞",meaning:"～を想像する",
   meanings:["他|～を想像する"],
   pronunciation:"/ɪˈmædʒɪn/",part:19,
   example:"Can you imagine your life without a smartphone?",
   exampleJa:"スマートフォンのない生活を想像できますか。",
   example2:"She imagined the blue sea while listening to music.",
   exampleJa2:"彼女は音楽を聴きながら青い海を想像した。",
   etymologyProcess:"imag（似せた姿）＋ ine（動詞）→ 頭の中に姿を描くのは…？",
   etymologyConclusion:"imag（似せた姿）＋ ine（動詞）→ 実物に似せた姿を頭の中に描いてみる＝想像する",
   relatedWords:[
     {word:"image",meaning:"像，イメージ",breakdown:"imag（似せた姿）→ 目や頭に浮かぶ姿そのもの"},
     {word:"imagination",meaning:"想像力",breakdown:"imag（似せた姿）＋ ation（名詞）→ 姿を思い描く力"},
     {word:"imaginary",meaning:"想像上の",breakdown:"imag（似せた姿）＋ ary（形容詞）→ 頭の中にしかない"},
     {synonym:true,word:"suppose",meaning:"～と思う，仮定する",breakdown:"仮に置いて考える。imagine は絵として思い描く"}]},

  {id:183,word:"guess",partOfSpeech:"他動詞",meaning:"～を推測する",
   meanings:["他|～を推測する","名|推測"],
   pronunciation:"/ɡes/",part:19,
   example:"Can you guess the price of this old watch?",
   exampleJa:"この古い時計の値段を推測できますか。",
   example2:"I guessed the answer and luckily it was right.",
   exampleJa2:"私は答えを推測したが、運よくそれは正しかった。",
   etymologyProcess:"guess（見当をつける）→ 確かな手がかりがないまま…？",
   etymologyConclusion:"guess（見当をつける）→ 確かな手がかりがないまま、えいやと見当をつける＝推測する",
   hook:"I guess は「たぶん～だと思う」。確信の弱さが guess の芯。",
   relatedWords:[
     {word:"guesswork",meaning:"当て推量",breakdown:"guess（見当をつける）＋ work（仕事）→ 当てずっぽうで進める作業"},
     {synonym:true,word:"imagine",meaning:"想像する",breakdown:"頭に絵を描く。guess は答えに見当をつける"},
     {synonym:true,word:"estimate",meaning:"見積もる",breakdown:"数量を計算して出す。guess は勘で当てにいく"},
     {synonym:true,word:"wonder",meaning:"～かなと思う",breakdown:"答えが気になる。guess は自分なりの答えを出す"}]},

  {id:184,word:"expect",partOfSpeech:"他動詞",meaning:"～を予期する",
   meanings:["他|～を予期する","他|（A of［from］ B）（B にA）を期待する","自|（be ―ing）（～を）身ごもっている"],
   pronunciation:"/ɪkˈspekt/",part:19,
   example:"We expect heavy rain in the afternoon today.",
   exampleJa:"私たちは今日の午後に大雨を予期している。",
   example2:"She expected a letter from her old friend.",
   exampleJa2:"彼女は古い友人からの手紙を予期していた。",
   etymologyProcess:"ex（外へ）＋ spect（見る）→ 外をじっと見ながら待つのは…？",
   etymologyConclusion:"ex（外へ）＋ spect（見る）→ 外をじっと見ながら来るはずのものを待つ＝予期する",
   etymologyMore:["相手にこうあってほしいと見込む→（B にA）を期待する"],
   relatedWords:[
     {word:"respect",meaning:"尊敬する",breakdown:"re（何度も）＋ spect（見る）→ 何度も見直すほど価値を認める"},
     {word:"spectator",meaning:"観客",breakdown:"spect（見る）＋ ator（人）→ じっと見ている人"},
     {word:"inspect",meaning:"検査する",breakdown:"in（中へ）＋ spect（見る）→ 中までのぞき込んで調べる"},
     {word:"expectation",meaning:"期待，予期",breakdown:"ex（外へ）＋ spect（見る）＋ ation（名詞）→ 外を見て待つ気持ち"}]},

  {id:185,word:"predict",partOfSpeech:"他動詞",meaning:"～を予測する",
   meanings:["他|～を予測する"],
   pronunciation:"/prɪˈdɪkt/",part:19,
   example:"No one can predict the weather a month ahead.",
   exampleJa:"1か月先の天気を予測できる人はいない。",
   example2:"Scientists predicted a big change in sea levels.",
   exampleJa2:"科学者たちは海面の大きな変化を予測した。",
   etymologyProcess:"pre（前もって）＋ dict（言う）→ 起こる前に先回りして…？",
   etymologyConclusion:"pre（前もって）＋ dict（言う）→ 起こる前に先回りして言い当てる＝予測する",
   relatedWords:[
     {word:"dictionary",meaning:"辞書",breakdown:"dict（言う）＋ ary（もの）→ 言葉の意味を言い並べた本"},
     {word:"prepare",meaning:"準備する",breakdown:"pre（前もって）＋ pare（用意する）→ 前もって整えておく"},
     {word:"prediction",meaning:"予測",breakdown:"pre（前もって）＋ dict（言う）＋ ion（名詞）→ 先回りして言ったこと"},
     {word:"contradict",meaning:"矛盾する",breakdown:"contra（逆に）＋ dict（言う）→ 逆のことを言う"}]},

  {id:186,word:"remember",partOfSpeech:"他動詞",meaning:"～を覚えている",
   meanings:["他|（doing）（過去にしたこと）を覚えている","他|（to do）（～すること）を覚えている","他|（me to ～）（～に）よろしく伝える"],
   pronunciation:"/rɪˈmembər/",part:19,
   example:"I remember meeting her at the summer festival.",
   exampleJa:"私は夏祭りで彼女に会ったことを覚えている。",
   example2:"Do you remember the name of that old song?",
   exampleJa2:"あの古い歌の名前を覚えていますか。",
   etymologyProcess:"re（再び）＋ memor（心にとどめる）→ 心にもう一度上らせるのは…？",
   etymologyConclusion:"re（再び）＋ memor（心にとどめる）→ 一度しまったことを心にもう一度上らせる＝覚えている",
   relatedWords:[
     {word:"memory",meaning:"記憶，思い出",breakdown:"memor（心にとどめる）＋ y（名詞）→ 心にとどめてある中身"},
     {word:"memorize",meaning:"暗記する",breakdown:"memor（心にとどめる）＋ ize（動詞）→ 心にしっかりとどめる"},
     {word:"memorial",meaning:"記念の，記念碑",breakdown:"memor（心にとどめる）＋ ial（形容詞）→ 忘れないためのもの"},
     {synonym:true,word:"recall",meaning:"思い出す",breakdown:"記憶を呼び戻す。remember は覚えている状態も指す"}]},

  {id:187,word:"remind",partOfSpeech:"他動詞",meaning:"～に思い出させる",
   meanings:["他|（A of B）（A）に（B のことを）思い出させる","他|（（人）to do）（人）に～するように念を押す"],
   pronunciation:"/rɪˈmaɪnd/",part:19,
   example:"This old song reminds me of my school days.",
   exampleJa:"この古い歌は私に学生時代を思い出させる。",
   example2:"Please remind me to call the doctor tomorrow morning.",
   exampleJa2:"明日の朝、医者に電話するよう私に念を押してください。",
   etymologyProcess:"re（再び）＋ mind（心）→ 相手の心にもう一度その事を…？",
   etymologyConclusion:"re（再び）＋ mind（心）→ 相手の心にもう一度その事を上らせてやる＝思い出させる",
   relatedWords:[
     {word:"mind",meaning:"心，精神",breakdown:"mind（心）→ 考えたり感じたりする場所"},
     {word:"mindful",meaning:"気をつけて",breakdown:"mind（心）＋ ful（満ちた）→ 心をそこへしっかり向けている"},
     {synonym:true,word:"remember",meaning:"覚えている",breakdown:"自分で思い出す。remind は人に思い出させる"},
     {synonym:true,word:"recall",meaning:"思い出す",breakdown:"記憶を呼び戻す。remind は外から引き金を与える"}]},

  {id:188,word:"realize",partOfSpeech:"他動詞",meaning:"～をはっきり理解する",
   meanings:["他|～を（はっきり）理解する","他|（夢，計画など）を実現する"],
   pronunciation:"/ˈriːəlaɪz/",part:19,
   example:"He realized his own mistake after the test ended.",
   exampleJa:"彼はテストが終わってから自分の間違いをはっきり理解した。",
   example2:"She did not realize how late it already was.",
   exampleJa2:"彼女はもうどれほど遅い時間かをはっきり理解していなかった。",
   etymologyProcess:"real（本当の）＋ ize（動詞）→ 頭の中のことを本当のこととして…？",
   etymologyConclusion:"real（本当の）＋ ize（動詞）→ 頭の中のことを本当のこととしてつかむ＝はっきり理解する",
   etymologyMore:["頭の中の夢を本当のことにする→（夢，計画など）を実現する"],
   relatedWords:[
     {word:"real",meaning:"本当の，現実の",breakdown:"real（本当の）→ 頭の中でなく実際にある"},
     {word:"really",meaning:"本当に",breakdown:"real（本当の）＋ ly（副詞）→ 本当のところを言うと"},
     {word:"reality",meaning:"現実",breakdown:"real（本当の）＋ ity（名詞）→ 本当にそうである状態"},
     {word:"realistic",meaning:"現実的な",breakdown:"real（本当の）＋ istic（形容詞）→ 現実にありそうな"}]},

  {id:189,word:"appreciate",partOfSpeech:"他動詞",meaning:"～のよさがわかる",
   meanings:["他|～のよさがわかる","他|～を（正しく）理解する","他|～に感謝する"],
   pronunciation:"/əˈpriːʃieɪt/",part:19,
   example:"Many visitors appreciate the beauty of this old garden.",
   exampleJa:"多くの訪問者がこの古い庭園の美しさのよさを味わっている。",
   example2:"I really appreciate your help with my homework.",
   exampleJa2:"宿題を手伝ってくれて本当に感謝しています。",
   etymologyProcess:"ad（〜へ）＋ preci（値打ち）→ そのものの値打ちをきちんと…？",
   etymologyConclusion:"ad（〜へ）＋ preci（値打ち）→ そのものの値打ちをきちんと見積もる＝よさがわかる",
   etymologyMore:["相手の行いの値打ちを認める→～に感謝する"],
   relatedWords:[
     {word:"price",meaning:"価格",breakdown:"preci（値打ち）→ 値打ちを数字で表したもの"},
     {word:"precious",meaning:"貴重な",breakdown:"preci（値打ち）＋ ous（形容詞）→ 値打ちがとても高い"},
     {word:"prize",meaning:"賞，賞品",breakdown:"preci（値打ち）→ 値打ちを認めて手渡すもの"},
     {synonym:true,word:"value",meaning:"～を重んじる",breakdown:"価値を認める。appreciate はよさが分かって味わう"}]},

  {id:190,word:"accept",partOfSpeech:"他動詞",meaning:"～を受け入れる",
   meanings:["他|～を受け入れる"],
   pronunciation:"/əkˈsept/",part:19,
   example:"She accepted the invitation to the birthday party.",
   exampleJa:"彼女は誕生日パーティーへの招待を受け入れた。",
   example2:"This school accepts twenty new students every April.",
   exampleJa2:"この学校は毎年4月に20人の新入生を受け入れる。",
   etymologyProcess:"ad（〜へ）＋ cept（取る）→ 差し出されたものを自分のほうへ…？",
   etymologyConclusion:"ad（〜へ）＋ cept（取る）→ 差し出されたものを自分のほうへ取り込む＝受け入れる",
   relatedWords:[
     {word:"except",meaning:"～を除いて",breakdown:"ex（外へ）＋ cept（取る）→ そこだけ外へ取り出しておく"},
     {word:"exception",meaning:"例外",breakdown:"ex（外へ）＋ cept（取る）＋ ion（名詞）→ 外へ取り出された例"},
     {word:"concept",meaning:"概念，考え",breakdown:"con（共に）＋ cept（取る）→ 頭の中にまとめて取り込んだ考え"},
     {synonym:true,word:"receive",meaning:"受け取る",breakdown:"届いた物を受け取る。accept は中身を認めて受け入れる"}]},

  {id:191,word:"consider",partOfSpeech:"他動詞",meaning:"～をよく考える",
   meanings:["他|～をよく考える，考慮する","他|（人の気持ち）を思いやる","他|（A （to be［as］)B)（A）を（B と）みなす"],
   pronunciation:"/kənˈsɪdər/",part:20,
   example:"We must consider the cost before we decide anything.",
   exampleJa:"何かを決める前に費用をよく考えなければならない。",
   example2:"She considered his advice for a long time.",
   exampleJa2:"彼女は彼の助言を長い間よく考えた。",
   etymologyProcess:"con（すっかり）＋ sider（星）→ 星を隅々まで見て占うように…？",
   etymologyConclusion:"con（すっかり）＋ sider（星）→ 星空を隅々まで見て占うように、じっくり見きわめる＝よく考える",
   relatedWords:[
     {word:"consideration",meaning:"考慮，思いやり",breakdown:"con（すっかり）＋ sider（星）＋ ation（名詞）→ じっくり見きわめること"},
     {word:"considerable",meaning:"かなりの",breakdown:"con（すっかり）＋ sider（星）＋ able（できる）→ 考えるに値するほど大きい"},
     {word:"desire",meaning:"強く望む",breakdown:"de（離して）＋ sider（星）→ 手の届かない星に思いを寄せる"},
     {synonym:true,word:"think",meaning:"考える",breakdown:"広く「考える」。consider は時間をかけて検討する"}]},

  {id:192,word:"mind",partOfSpeech:"他動詞",meaning:"～を気にする",
   meanings:["他|～を気にする，いやだと思う","名|精神，頭脳","名|（才能，知性のある）人"],
   pronunciation:"/maɪnd/",part:20,
   example:"I don't mind the noise from the busy street.",
   exampleJa:"私はにぎやかな通りからの騒音を気にしない。",
   example2:"Would you mind opening the window for me?",
   exampleJa2:"窓を開けていただくのは、いやでしょうか。",
   etymologyProcess:"mind（心）→ 心がそこに向いて引っかかると…？",
   etymologyConclusion:"mind（心）→ 心がそこに向いて引っかかり、いやだと感じる＝気にする",
   etymologyMore:["心のはたらく場所そのもの→精神，頭脳","すぐれた心の持ち主→（才能，知性のある）人"],
   hook:"Do you mind ～? に Yes と答えると「いやだ」の意味になる。",
   relatedWords:[
     {word:"remind",meaning:"思い出させる",breakdown:"re（再び）＋ mind（心）→ 相手の心にもう一度上らせる"},
     {word:"mindful",meaning:"気をつけて",breakdown:"mind（心）＋ ful（満ちた）→ 心をそこへしっかり向けている"},
     {synonym:true,word:"care",meaning:"気にかける",breakdown:"気にかける。mind は迷惑に感じるかどうかを言う"},
     {synonym:true,word:"worry",meaning:"心配する",breakdown:"先のことを心配する。mind は目の前の事が気になる"}]},

  {id:193,word:"wonder",partOfSpeech:"他動詞",meaning:"～かなと思う",
   meanings:["他|（wh―節 / if SV）～かなと思う","自|（at ～）（～に）驚く"],
   pronunciation:"/ˈwʌndər/",part:20,
   example:"I wonder why she was absent from school today.",
   exampleJa:"彼女が今日なぜ学校を休んだのかなと思う。",
   example2:"He wondered if the train would arrive on time.",
   exampleJa2:"彼は電車が時間どおりに着くのかなと思った。",
   etymologyProcess:"wonder（不思議に思う）→ 不思議に思って心の中で…？",
   etymologyConclusion:"wonder（不思議に思う）→ 不思議に思って、心の中で自分に問いかける＝～かなと思う",
   etymologyMore:["不思議さに打たれて立ち止まる→（at ～）（～に）驚く"],
   relatedWords:[
     {word:"wonderful",meaning:"すばらしい",breakdown:"wonder（不思議に思う）＋ ful（満ちた）→ 不思議なほどすばらしい"},
     {synonym:true,word:"guess",meaning:"推測する",breakdown:"見当をつける。wonder は答えを知りたくて問いかける"},
     {synonym:true,word:"doubt",meaning:"疑う",breakdown:"本当かなと疑う。wonder は答えを知りたい気持ち"},
     {synonym:true,word:"curious",meaning:"好奇心が強い",breakdown:"知りたくてたまらない。wonder はその気持ちで問うこと"}]},

  {id:194,word:"seem",partOfSpeech:"自動詞",meaning:"～のように思われる",
   meanings:["自|～のように思われる"],
   pronunciation:"/siːm/",part:20,
   example:"He seems tired after the long soccer practice.",
   exampleJa:"彼は長いサッカーの練習のあとで疲れているように思われる。",
   example2:"It seemed strange that nobody answered the phone.",
   exampleJa2:"誰も電話に出ないのは奇妙に思われた。",
   etymologyProcess:"seem（ふさわしく見える）→ 外から見てそれらしく映ると…？",
   etymologyConclusion:"seem（ふさわしく見える）→ 外から見て、いかにもそれらしく映る＝～のように思われる",
   hook:"seem to do / seem ＋形容詞 の形で使う。appear より主観寄り。",
   relatedWords:[
     {word:"seeming",meaning:"見かけの",breakdown:"seem（ふさわしく見える）＋ ing（形容詞）→ 見た目だけそう見える"},
     {synonym:true,word:"look",meaning:"～に見える",breakdown:"目で見た印象。seem は全体の感じからそう思われる"},
     {synonym:true,word:"appear",meaning:"～のように思える",breakdown:"外から見てそう思える。seem のほうが日常的"},
     {synonym:true,word:"apparently",meaning:"どうやら～らしい",breakdown:"見たところでは。seem を副詞にした言いかえ"}]},

  {id:195,word:"compare",partOfSpeech:"他動詞",meaning:"～を比較する",
   meanings:["他|（A with［to, and］ B）（A）を（B と）比較する","他|（A to B）（A）を（B に）例える","自|（with［to］～）（～に）匹敵する"],
   pronunciation:"/kəmˈper/",part:20,
   example:"Let's compare the two plans before the class meeting.",
   exampleJa:"学級会の前に2つの案を比較しよう。",
   example2:"She compared her answer with her friend's answer.",
   exampleJa2:"彼女は自分の答えを友達の答えと比較した。",
   etymologyProcess:"com（共に）＋ par（等しい）→ 二つを並べて釣り合うか…？",
   etymologyConclusion:"com（共に）＋ par（等しい）→ 二つを並べて、釣り合うかどうかを見る＝比較する",
   relatedWords:[
     {word:"pair",meaning:"一組，ペア",breakdown:"par（等しい）→ 等しいもの二つで一組になる"},
     {word:"comparison",meaning:"比較",breakdown:"com（共に）＋ par（等しい）＋ ison（名詞）→ 並べて見比べること"},
     {word:"peer",meaning:"同等の人，同輩",breakdown:"par（等しい）→ 立場が等しい仲間"},
     {synonym:true,word:"contrast",meaning:"対比する",breakdown:"違いを際立たせる。compare は似ている点も見る"}]},

  {id:196,word:"concentrate",partOfSpeech:"自動詞",meaning:"集中する",
   meanings:["自|（on ～）（～に）集中する","他|（A on B）（A）を（B に）集中させる"],
   pronunciation:"/ˈkɑːnsntreɪt/",part:20,
   example:"I cannot concentrate on my homework with music on.",
   exampleJa:"音楽をかけていると宿題に集中できない。",
   example2:"She concentrated on the game until the last minute.",
   exampleJa2:"彼女は最後の一分まで試合に集中した。",
   etymologyProcess:"con（共に）＋ centr（中心）→ 力を一つの中心へ…？",
   etymologyConclusion:"con（共に）＋ centr（中心）→ ばらけた力を一つの中心へ寄せ集める＝集中する",
   relatedWords:[
     {word:"center",meaning:"中心",breakdown:"centr（中心）→ 円のちょうどまん中の点"},
     {word:"central",meaning:"中心の",breakdown:"centr（中心）＋ al（形容詞）→ まん中に位置している"},
     {word:"concentration",meaning:"集中（力）",breakdown:"con（共に）＋ centr（中心）＋ ation（名詞）→ 一点に集まること"},
     {word:"eccentric",meaning:"風変わりな",breakdown:"ec（外へ）＋ centr（中心）→ 中心から外れている"}]},

  {id:197,word:"focus",partOfSpeech:"自動詞",meaning:"～に焦点を当てる",
   meanings:["自|（on ～）（～に）焦点を当てる，力を注ぐ","名|焦点"],
   pronunciation:"/ˈfoʊkəs/",part:20,
   example:"We should focus on the most important question first.",
   exampleJa:"まず最も大切な問いに焦点を当てるべきだ。",
   example2:"The class focused on English grammar this week.",
   exampleJa2:"そのクラスは今週、英文法に焦点を当てた。",
   etymologyProcess:"focus（いろり・火）→ 光が一点に集まるところへ…？",
   etymologyConclusion:"focus（いろり・火）→ 光が一点に集まるいろりのように、視線を一点へ寄せる＝焦点を当てる",
   hook:"もとはラテン語の「いろり（火をたく一点）」。光も注意も一点に集まる。",
   relatedWords:[
     {word:"focal",meaning:"焦点の",breakdown:"focus（いろり・火）＋ al（形容詞）→ 一点に集まる点にかかわる"},
     {synonym:true,word:"concentrate",meaning:"集中する",breakdown:"力を一点に集める。focus は視線や注意を合わせる"},
     {synonym:true,word:"center",meaning:"中心",breakdown:"まん中の点。focus は光や注意が集まる一点"},
     {synonym:true,word:"attention",meaning:"注意",breakdown:"向ける注意そのもの。focus はそれを一点に合わせる"}]},

  {id:198,word:"allow",partOfSpeech:"他動詞",meaning:"～を許可する",
   meanings:["他|（人が）～を許可する","他|（物が）～を可能にする"],
   pronunciation:"/əˈlaʊ/",part:20,
   example:"My parents allow me to use the computer at night.",
   exampleJa:"両親は私が夜にコンピュータを使うことを許可している。",
   example2:"Smoking is not allowed anywhere in this restaurant.",
   exampleJa2:"このレストランではどこでも喫煙は許可されていない。",
   etymologyProcess:"ad（〜へ）＋ loc（場所）→ 相手のために場所を空けると…？",
   etymologyConclusion:"ad（〜へ）＋ loc（場所）→ 相手のために場所を空けて、そこへ入れてやる＝許可する",
   relatedWords:[
     {word:"local",meaning:"その土地の",breakdown:"loc（場所）＋ al（形容詞）→ その場所に属している"},
     {word:"locate",meaning:"位置している",breakdown:"loc（場所）＋ ate（動詞）→ 場所を定めて置く"},
     {word:"location",meaning:"場所，位置",breakdown:"loc（場所）＋ ation（名詞）→ 置かれているところ"},
     {word:"allowance",meaning:"小遣い；手当",breakdown:"ad（〜へ）＋ loc（場所）＋ ance（名詞）→ その人の分として空けた枠"}]},

  {id:199,word:"admit",partOfSpeech:"他動詞",meaning:"～を認める",
   meanings:["他|～を認める","他|～の入場［入学］を許可する"],
   pronunciation:"/ədˈmɪt/",part:20,
   example:"She admits her mistake without making any excuse.",
   exampleJa:"彼女は言い訳をせずに自分の間違いを認める。",
   example2:"He finally admitted that he had broken the window.",
   exampleJa2:"彼はついに窓を割ったことを認めた。",
   etymologyProcess:"ad（〜へ）＋ mit（送る）→ 相手の言い分を自分の中へ…？",
   etymologyConclusion:"ad（〜へ）＋ mit（送る）→ 相手の言い分を自分の中へ送り入れて通す＝認める",
   etymologyMore:["人を中へ送り入れる→～の入場［入学］を許可する"],
   relatedWords:[
     {word:"mission",meaning:"任務，使命",breakdown:"mit（送る）＋ ion（名詞）→ 送り出されて負う務め"},
     {word:"permit",meaning:"許可する",breakdown:"per（すっかり）＋ mit（送る）→ 通り抜けるまで送り通す"},
     {word:"submit",meaning:"提出する",breakdown:"sub（下で）＋ mit（送る）→ 相手の下へ差し出して送る"},
     {word:"admission",meaning:"入場；認めること",breakdown:"ad（〜へ）＋ mit（送る）＋ ion（名詞）→ 中へ送り入れること"}]},

  {id:200,word:"ground",partOfSpeech:"名詞",meaning:"地面",
   meanings:["名|地面","名|根拠"],
   pronunciation:"/ɡraʊnd/",part:20,
   example:"The children sat on the wet ground after lunch.",
   exampleJa:"子どもたちは昼食のあと、ぬれた地面に座った。",
   example2:"Deep snow covered the ground around the old school.",
   exampleJa2:"深い雪が古い校舎のまわりの地面を覆った。",
   etymologyProcess:"ground（底・地面）→ 足で踏みしめる一番下の面は…？",
   etymologyConclusion:"ground（底・地面）→ 足で踏みしめる、世界の一番下の面＝地面",
   etymologyMore:["意見を下から支えている面→根拠"],
   hook:"「一番下で支える面」が芯。意見を支える底→根拠、へつながる。",
   relatedWords:[
     {word:"underground",meaning:"地下の",breakdown:"under（下に）＋ ground（底・地面）→ 地面よりさらに下にある"},
     {word:"background",meaning:"背景",breakdown:"back（後ろ）＋ ground（底・地面）→ 後ろに広がる地の部分"},
     {word:"playground",meaning:"運動場，遊び場",breakdown:"play（遊ぶ）＋ ground（底・地面）→ 遊ぶための地面"},
     {synonym:true,word:"floor",meaning:"床",breakdown:"建物の中の面。ground は屋外の地面を指す"}]},

  {id:201,word:"pollution",partOfSpeech:"名詞",meaning:"汚染，公害",
   meanings:["名|汚染，公害〈不可算〉"],
   pronunciation:"/pəˈluːʃn/",part:21,
   example:"Air pollution in this big city is getting worse.",
   exampleJa:"この大都市の大気汚染はひどくなってきている。",
   example2:"Factories near the river caused serious water pollution.",
   exampleJa2:"川の近くの工場が深刻な水質汚染を引き起こした。",
   etymologyProcess:"pollut（汚す）＋ ion（名詞）→ きれいだったものを汚すのは…？",
   etymologyConclusion:"pollut（汚す）＋ ion（名詞）→ きれいだった水や空気を汚してしまうこと＝汚染",
   relatedWords:[
     {word:"pollute",meaning:"汚染する",breakdown:"pollut（汚す）＋ e（動詞）→ きれいなものを汚してしまう"},
     {word:"pollutant",meaning:"汚染物質",breakdown:"pollut（汚す）＋ ant（もの）→ 汚す原因になる物質"},
     {synonym:true,word:"dirty",meaning:"汚い",breakdown:"見た目が汚い。pollution は環境が害されること"},
     {synonym:true,word:"waste",meaning:"廃棄物",breakdown:"捨てられるごみ。それが pollution を生む"}]},

  {id:202,word:"sight",partOfSpeech:"名詞",meaning:"目に入る光景",
   meanings:["名|目に入る光景","名|視力"],
   pronunciation:"/saɪt/",part:21,
   example:"The sight of the old castle surprised us all.",
   exampleJa:"その古い城の光景は私たち全員を驚かせた。",
   example2:"She lost her sight in an accident years ago.",
   exampleJa2:"彼女は何年も前の事故で視力を失った。",
   etymologyProcess:"see（見る）＋ t（名詞）→ 目に飛び込んでくる眺めは…？",
   etymologyConclusion:"see（見る）＋ t（名詞）→ 目に飛び込んでくる眺めのひとこま＝光景",
   etymologyMore:["目が見えるはたらきそのもの→視力"],
   relatedWords:[
     {word:"see",meaning:"見る，見える",breakdown:"see（見る）→ 目に入れてそれをとらえる"},
     {word:"sightseeing",meaning:"観光",breakdown:"sight（光景）＋ see（見る）→ 名所の光景を見て回ること"},
     {word:"insight",meaning:"洞察（力）",breakdown:"in（中へ）＋ sight（光景）→ 内側まで見通す目"},
     {synonym:true,word:"scene",meaning:"場面，現場",breakdown:"ひと続きの場面。sight は目に映った眺め"}]},

  {id:203,word:"view",partOfSpeech:"名詞",meaning:"（ある場所から見える）眺め",
   meanings:["名|（ある場所から見える）眺め，景色〈可算〉","名|見解，見方","他|（A as B）（A）を（B と）みなす"],
   pronunciation:"/vjuː/",part:21,
   example:"This room has a beautiful view of the sea.",
   exampleJa:"この部屋は海の美しい眺めがある。",
   example2:"We enjoyed the view from the top of the mountain.",
   exampleJa2:"私たちは山頂からの眺めを楽しんだ。",
   etymologyProcess:"vis（見る）→ 目の前いっぱいに広がって入ってくるのは…？",
   etymologyConclusion:"vis（見る）→ 目の前いっぱいに広がって入ってくるもの＝眺め",
   etymologyMore:["物事をどう見ているか→見解，見方"],
   relatedWords:[
     {word:"visible",meaning:"目に見える",breakdown:"vis（見る）＋ ible（できる）→ 目で見ることができる"},
     {word:"vision",meaning:"視力；未来像",breakdown:"vis（見る）＋ ion（名詞）→ 見えているもの、見通す力"},
     {word:"preview",meaning:"試写，下見",breakdown:"pre（前もって）＋ vis（見る）→ 本番の前に見ておくこと"},
     {synonym:true,word:"scenery",meaning:"風景，景色",breakdown:"広がる景色全体。view はある地点から見える眺め"}]},

  {id:204,word:"landscape",partOfSpeech:"名詞",meaning:"見渡す土地の風景",
   meanings:["名|見渡す土地の風景","名|（政治，社会の）情勢"],
   pronunciation:"/ˈlændskeɪp/",part:21,
   example:"The train window showed a beautiful winter landscape.",
   exampleJa:"列車の窓には美しい冬の風景が見えた。",
   example2:"Farmers slowly changed the landscape of this valley.",
   exampleJa2:"農民たちはこの谷の風景を少しずつ変えていった。",
   etymologyProcess:"land（土地）＋ scape（眺め）→ ひと目で見渡せる土地の…？",
   etymologyConclusion:"land（土地）＋ scape（眺め）→ ひと目で見渡せる土地のひと続きの眺め＝風景",
   etymologyMore:["見渡した社会全体の様子→（政治，社会の）情勢"],
   relatedWords:[
     {word:"land",meaning:"土地，陸",breakdown:"land（土地）→ 人が立って使う地面の広がり"},
     {word:"seascape",meaning:"海の風景",breakdown:"sea（海）＋ scape（眺め）→ 見渡したときの海の眺め"},
     {synonym:true,word:"view",meaning:"眺め",breakdown:"ある地点から見える眺め。landscape は土地全体の広がり"},
     {synonym:true,word:"scenery",meaning:"景色",breakdown:"自然の景色。landscape は絵のように切り取った風景"}]},

  {id:205,word:"nature",partOfSpeech:"名詞",meaning:"自然",
   meanings:["名|（無冠詞）自然","名|（～の）性質"],
   pronunciation:"/ˈneɪtʃər/",part:21,
   example:"We should protect nature for the next generation.",
   exampleJa:"私たちは次の世代のために自然を守るべきだ。",
   example2:"In spring, nature around the small village wakes up.",
   exampleJa2:"春になると、小さな村のまわりの自然が目を覚ます。",
   etymologyProcess:"nat（生まれる）＋ ure（名詞）→ 人の手を加えず生まれたままの姿は…？",
   etymologyConclusion:"nat（生まれる）＋ ure（名詞）→ 人の手を加えず、生まれたままに続いている世界＝自然",
   etymologyMore:["生まれつき持っているもの→（～の）性質"],
   relatedWords:[
     {word:"natural",meaning:"自然の；当然の",breakdown:"nat（生まれる）＋ al（形容詞）→ 生まれたままで無理がない"},
     {word:"native",meaning:"その土地生まれの",breakdown:"nat（生まれる）＋ ive（形容詞）→ その土地で生まれた"},
     {word:"nation",meaning:"国家，国民",breakdown:"nat（生まれる）＋ ion（名詞）→ 同じ地に生まれた人の集まり"},
     {word:"innate",meaning:"生まれつきの",breakdown:"in（中に）＋ nat（生まれる）→ 生まれた時から中にある"}]},

  {id:206,word:"seed",partOfSpeech:"名詞",meaning:"（植物の）種",
   meanings:["名|種","名|シード選手"],
   pronunciation:"/siːd/",part:21,
   example:"We put the small seeds into the warm soil.",
   exampleJa:"私たちは小さな種を暖かい土の中に入れた。",
   example2:"A single seed can grow into a huge tree.",
   exampleJa2:"たった一粒の種が巨大な木に育つことがある。",
   etymologyProcess:"seed（まかれるもの）→ 土にまかれて次の命になる粒は…？",
   etymologyConclusion:"seed（まかれるもの）→ 土にまかれて、次の命になる小さな粒＝種",
   etymologyMore:["強い選手を離して置き分ける→シード選手"],
   hook:"芯は「まく」。大会のシードも、強い選手を置き分けることから。",
   relatedWords:[
     {word:"seedling",meaning:"苗",breakdown:"seed（まかれるもの）＋ ling（小さいもの）→ 種から出た小さな苗"},
     {synonym:true,word:"plant",meaning:"植える；植物",breakdown:"種を土に植える動作。seed はその粒そのもの"},
     {synonym:true,word:"grain",meaning:"穀物；粒",breakdown:"食べるための小さな粒。seed はまけば芽が出る粒"},
     {synonym:true,word:"root",meaning:"根",breakdown:"seed から下へ伸びる部分。芽と根はセットで出る"}]},

  {id:207,word:"plant",partOfSpeech:"名詞",meaning:"植物",
   meanings:["名|植物","名|（大規模な）工場，発電所","他|～を植える"],
   pronunciation:"/plænt/",part:21,
   example:"This small plant needs water every other day.",
   exampleJa:"この小さな植物は1日おきに水が必要だ。",
   example2:"Many strange plants grow in the deep dark forest.",
   exampleJa2:"深く暗い森には多くの珍しい植物が生えている。",
   etymologyProcess:"plant（足で踏み込む）→ 苗を土に押し込んで根づかせたものは…？",
   etymologyConclusion:"plant（足で踏み込む）→ 苗を土に押し込んで根づかせたもの＝植物",
   etymologyMore:["設備を土地に据えつけた場所→（大規模な）工場，発電所","苗を土に押し込む→～を植える"],
   relatedWords:[
     {word:"plantation",meaning:"大農園",breakdown:"plant（足で踏み込む）＋ ation（名詞）→ 苗を植えつけた広い土地"},
     {word:"transplant",meaning:"移植する",breakdown:"trans（越えて）＋ plant（足で踏み込む）→ 別の場所へ移して植える"},
     {synonym:true,word:"tree",meaning:"木",breakdown:"背の高い植物。plant は草も木もまとめて指す"},
     {synonym:true,word:"grow",meaning:"育つ，育てる",breakdown:"伸びて大きくなる。plant は土に植えるところ"}]},

  {id:208,word:"bloom",partOfSpeech:"自動詞",meaning:"（花が）咲く",
   meanings:["自|（花が）咲く","名|開花"],
   pronunciation:"/bluːm/",part:21,
   example:"Cherry trees bloom in early April in this town.",
   exampleJa:"この町では桜の木は4月の初めに咲く。",
   example2:"The roses in her garden bloomed all summer long.",
   exampleJa2:"彼女の庭のバラは夏じゅうずっと咲いた。",
   etymologyProcess:"bloom（花・咲く）→ つぼみが開いて花の姿になると…？",
   etymologyConclusion:"bloom（花・咲く）→ かたいつぼみが開いて、花の姿になる＝咲く",
   hook:"in bloom で「咲いている」。blossom（果樹の花）も同じ仲間の語。",
   relatedWords:[
     {word:"blossom",meaning:"（果樹の）花；咲く",breakdown:"bloom（花・咲く）→ 果樹に咲く花。bloom と同じ仲間"},
     {word:"blooming",meaning:"花盛りの",breakdown:"bloom（花・咲く）＋ ing（形容詞）→ 花が開いている最中の"},
     {synonym:true,word:"flower",meaning:"花",breakdown:"花そのもの。bloom は花が開く動きを指す"},
     {synonym:true,word:"bud",meaning:"つぼみ",breakdown:"開く前のつぼみ。bloom はそれが開いた状態"}]},

  {id:209,word:"harvest",partOfSpeech:"名詞",meaning:"収穫",
   meanings:["名|収穫","他|～を収穫する","他|（臓器，体液など）を摘出する"],
   pronunciation:"/ˈhɑːrvɪst/",part:21,
   example:"The rice harvest was very good in this village.",
   exampleJa:"この村では米の収穫がとても良かった。",
   example2:"Farmers finished the harvest before the big typhoon came.",
   exampleJa2:"農家は大きな台風が来る前に収穫を終えた。",
   etymologyProcess:"harvest（刈り入れの秋）→ 秋に実った作物を刈り取るのは…？",
   etymologyConclusion:"harvest（刈り入れの秋）→ 秋に実った作物を刈り取って取り入れること＝収穫",
   hook:"もとは「秋」。刈り入れの季節が、そのまま収穫の意味になった。",
   relatedWords:[
     {word:"harvester",meaning:"収穫機；刈り入れ人",breakdown:"harvest（刈り入れの秋）＋ er（もの）→ 刈り取りをする機械や人"},
     {synonym:true,word:"crop",meaning:"作物",breakdown:"育てている作物。harvest はそれを刈り取ること"},
     {synonym:true,word:"autumn",meaning:"秋",breakdown:"刈り入れの季節。harvest はもともと「秋」を指した"},
     {synonym:true,word:"reap",meaning:"刈り取る",breakdown:"鎌で刈る動作。harvest は取り入れ全体を指す"}]},

  {id:210,word:"insect",partOfSpeech:"名詞",meaning:"昆虫",
   meanings:["名|昆虫"],
   pronunciation:"/ˈɪnsekt/",part:21,
   example:"Many insects come to the bright light at night.",
   exampleJa:"夜には多くの昆虫が明るい光に集まってくる。",
   example2:"The boy collected insects during the summer vacation.",
   exampleJa2:"その少年は夏休みの間に昆虫を集めた。",
   etymologyProcess:"in（中へ）＋ sect（切る）→ 体に切れ目が入った生き物は…？",
   etymologyConclusion:"in（中へ）＋ sect（切る）→ 体が切れ目でいくつにも区切られた小さな生き物＝昆虫",
   relatedWords:[
     {word:"section",meaning:"区分，部門",breakdown:"sect（切る）＋ ion（名詞）→ 切り分けられた一区切り"},
     {word:"sector",meaning:"部門，分野",breakdown:"sect（切る）＋ or（もの）→ 切り分けられた一区画"},
     {word:"intersection",meaning:"交差点",breakdown:"inter（間の）＋ sect（切る）＋ ion（名詞）→ 道が互いに切り合う所"},
     {synonym:true,word:"bug",meaning:"虫",breakdown:"話し言葉の「虫」。insect は生き物としての昆虫"}]},

  {id:211,word:"earthquake",partOfSpeech:"名詞",meaning:"地震",
   meanings:["名|地震"],
   pronunciation:"/ˈɜːrθkweɪk/",part:22,
   example:"A strong earthquake hit the small island last night.",
   exampleJa:"強い地震が昨夜その小さな島を襲った。",
   example2:"We practice what to do during a big earthquake.",
   exampleJa2:"私たちは大きな地震のときにどうするかを練習する。",
   etymologyProcess:"earth（大地）＋ quake（揺れる）→ 大地そのものが揺れ動くのは…？",
   etymologyConclusion:"earth（大地）＋ quake（揺れる）→ 足の下の大地そのものが揺れ動くこと＝地震",
   relatedWords:[
     {word:"earth",meaning:"地球；大地",breakdown:"earth（大地）→ 足元に広がる土の世界"},
     {word:"quake",meaning:"揺れる，震える",breakdown:"quake（揺れる）→ ぐらぐらと小刻みに震える"},
     {word:"earthworm",meaning:"ミミズ",breakdown:"earth（大地）＋ worm（虫）→ 土の中で暮らす虫"},
     {synonym:true,word:"shake",meaning:"揺れる，揺らす",breakdown:"ゆさゆさ動かす。quake は震えるような揺れ"}]},

  {id:212,word:"temperature",partOfSpeech:"名詞",meaning:"温度，気温",
   meanings:["名|温度，気温","名|体温"],
   pronunciation:"/ˈtemprətʃər/",part:22,
   example:"The temperature dropped below zero degrees last night.",
   exampleJa:"昨夜は気温が0度より下がった。",
   example2:"Please check the temperature of the water first.",
   exampleJa2:"まず水の温度を確かめてください。",
   etymologyProcess:"temper（ほどよく混ぜる）＋ ature（名詞）→ 熱と冷たさの混ざり具合は…？",
   etymologyConclusion:"temper（ほどよく混ぜる）＋ ature（名詞）→ 熱さと冷たさが混ざり合った具合＝温度",
   etymologyMore:["体の中の熱の具合→体温"],
   relatedWords:[
     {word:"temper",meaning:"気性",breakdown:"temper（ほどよく混ぜる）→ 心の成分の混ざり具合"},
     {word:"temperate",meaning:"温暖な；節度のある",breakdown:"temper（ほどよく混ぜる）＋ ate（形容詞）→ 暑さ寒さがほどよい"},
     {synonym:true,word:"degree",meaning:"度",breakdown:"温度を測る目盛り。temperature はその値そのもの"},
     {synonym:true,word:"fever",meaning:"（病気の）熱",breakdown:"病気で上がった体温。temperature は体温一般"}]},

  {id:213,word:"degree",partOfSpeech:"名詞",meaning:"（温度などの）度",
   meanings:["名|（温度などの）度","名|程度","名|学位"],
   pronunciation:"/dɪˈɡriː/",part:22,
   example:"Water freezes at zero degrees Celsius in this experiment.",
   exampleJa:"この実験では、水はセ氏0度で凍る。",
   example2:"The angle of this triangle is exactly ninety degrees.",
   exampleJa2:"この三角形の角はちょうど90度だ。",
   etymologyProcess:"de（下へ）＋ grad（歩み・段）→ 一段ずつ刻んだ目盛りの一つは…？",
   etymologyConclusion:"de（下へ）＋ grad（歩み・段）→ 上から一段ずつ下りながら刻んだ目盛りの一つ＝度",
   etymologyMore:["目盛りのどこまで進んだか→程度","学問の段を上りきった印→学位"],
   relatedWords:[
     {word:"grade",meaning:"学年；等級",breakdown:"grad（歩み・段）→ 一段ずつ上がる階段の一段"},
     {word:"gradual",meaning:"徐々の",breakdown:"grad（歩み・段）＋ al（形容詞）→ 一段ずつ進むような"},
     {synonym:true,word:"level",meaning:"水準",breakdown:"高さの水準。degree は目盛りで刻んだ一段"},
     {synonym:true,word:"extent",meaning:"程度，範囲",breakdown:"どこまで及ぶか。degree は目盛りで測った程度"}]},

  {id:214,word:"flood",partOfSpeech:"名詞",meaning:"洪水",
   meanings:["名|洪水","他|～を水浸しにする"],
   pronunciation:"/flʌd/",part:22,
   example:"The heavy rain caused a terrible flood last summer.",
   exampleJa:"その大雨は昨年の夏、ひどい洪水を引き起こした。",
   example2:"Many houses near the river were lost in the flood.",
   exampleJa2:"川の近くの多くの家が洪水で失われた。",
   etymologyProcess:"flood（流れる）→ 川の水があふれ出して土地を…？",
   etymologyConclusion:"flood（流れる）→ 川の水があふれ出して、土地いっぱいに広がること＝洪水",
   relatedWords:[
     {word:"flow",meaning:"流れる",breakdown:"flow（流れる）→ 水がすべるように進んでいく"},
     {word:"overflow",meaning:"あふれる",breakdown:"over（越えて）＋ flow（流れる）→ 縁を越えて外へ流れ出る"},
     {word:"floodgate",meaning:"水門",breakdown:"flood（流れる）＋ gate（門）→ 水の流れをせき止める門"},
     {synonym:true,word:"disaster",meaning:"災害",breakdown:"大きな災い。flood はそのうち水による災害"}]},

  {id:215,word:"freeze",partOfSpeech:"自動詞",meaning:"凍る",
   meanings:["自|凍る，凍りつく","他|～を凍らせる"],
   pronunciation:"/friːz/",part:22,
   example:"The pond in the park freezes every cold winter.",
   exampleJa:"公園の池は寒い冬には毎年凍る。",
   example2:"Water in the old pipes froze during the night.",
   exampleJa2:"古い水道管の中の水が夜の間に凍った。",
   etymologyProcess:"freez（凍りつく）→ 水が冷え切って固まり、動かなくなると…？",
   etymologyConclusion:"freez（凍りつく）→ 水が冷え切って固まり、まったく動かなくなる＝凍る",
   relatedWords:[
     {word:"frozen",meaning:"凍った，冷凍の",breakdown:"freez（凍りつく）＋ en（〜された）→ すっかり凍らされた"},
     {word:"freezer",meaning:"冷凍庫",breakdown:"freez（凍りつく）＋ er（もの）→ 凍らせておくための機械"},
     {word:"freezing",meaning:"凍るように寒い",breakdown:"freez（凍りつく）＋ ing（形容詞）→ 今にも凍りそうな"},
     {synonym:true,word:"melt",meaning:"溶ける",breakdown:"freeze の反対。固まったものが液体に戻る"}]},

  {id:216,word:"reflect",partOfSpeech:"他動詞",meaning:"～を反射する",
   meanings:["他|～を反射する","他|～を反映する","自|（on ～）（～を）熟考する"],
   pronunciation:"/rɪˈflekt/",part:22,
   example:"White walls reflect sunlight and keep the rooms cool.",
   exampleJa:"白い壁は日光を反射して部屋を涼しく保つ。",
   example2:"The calm lake reflects the mountains very clearly.",
   exampleJa2:"静かな湖が山々をとてもはっきりと映し出す。",
   etymologyProcess:"re（戻す）＋ flect（曲げる）→ 当たった光の向きを曲げて…？",
   etymologyConclusion:"re（戻す）＋ flect（曲げる）→ 当たった光の向きを曲げて、もと来たほうへ返す＝反射する",
   etymologyMore:["受けたものをそのまま返して見せる→～を反映する","考えを自分に折り返す→（～を）熟考する"],
   relatedWords:[
     {word:"flexible",meaning:"柔軟な",breakdown:"flect（曲げる）＋ ible（できる）→ 自由に曲げることができる"},
     {word:"flex",meaning:"（筋肉など）を曲げる",breakdown:"flect（曲げる）→ 関節や筋肉をぐいと曲げる"},
     {word:"reflection",meaning:"反射；反省",breakdown:"re（戻す）＋ flect（曲げる）＋ ion（名詞）→ 曲げ戻されたもの"},
     {synonym:true,word:"mirror",meaning:"鏡",breakdown:"光を返す道具。reflect はその働きそのもの"}]},

  {id:217,word:"polite",partOfSpeech:"形容詞",meaning:"礼儀正しい",
   meanings:["形|（人，言動が）礼儀正しい"],
   pronunciation:"/pəˈlaɪt/",part:22,
   example:"She is always polite to the older people here.",
   exampleJa:"彼女はここの年配の人々にいつも礼儀正しい。",
   example2:"It is not polite to speak with your mouth full.",
   exampleJa2:"口に物を入れたまま話すのは礼儀正しくない。",
   etymologyProcess:"pol（磨く）＋ ite（〜された）→ 角が取れるまで磨かれたふるまいは…？",
   etymologyConclusion:"pol（磨く）＋ ite（〜された）→ 角が取れるまで磨かれた、なめらかなふるまい＝礼儀正しい",
   relatedWords:[
     {word:"polish",meaning:"磨く",breakdown:"pol（磨く）→ こすってつやを出す"},
     {word:"impolite",meaning:"失礼な",breakdown:"im（否定）＋ pol（磨く）→ 磨かれていないふるまいの"},
     {synonym:true,word:"kind",meaning:"親切な",breakdown:"相手に優しい。polite は礼儀の形が整っている"},
     {synonym:true,word:"manner",meaning:"作法，態度",breakdown:"ふるまい方。polite はそれが磨かれている状態"}]},

  {id:218,word:"rude",partOfSpeech:"形容詞",meaning:"無礼な",
   meanings:["形|（言葉，行為が）無礼な，不作法な"],
   pronunciation:"/ruːd/",part:22,
   example:"It was rude of him to leave without saying goodbye.",
   exampleJa:"さよならも言わずに帰るとは、彼は無礼だった。",
   example2:"Don't be rude to the new student in our class.",
   exampleJa2:"クラスの新しい生徒に無礼な態度をとってはいけない。",
   etymologyProcess:"rud（荒削りの）→ 削っただけで磨いていないふるまいは…？",
   etymologyConclusion:"rud（荒削りの）→ 石を削っただけで磨いていない、ごつごつしたふるまい＝無礼な",
   hook:"polite（磨かれた）の反対で「荒削りのまま」。強い非難の語。",
   relatedWords:[
     {word:"rudely",meaning:"無礼に",breakdown:"rud（荒削りの）＋ ly（副詞）→ 荒削りのままのやり方で"},
     {word:"rudeness",meaning:"無礼",breakdown:"rud（荒削りの）＋ ness（名詞）→ 荒削りのままであること"},
     {synonym:true,word:"polite",meaning:"礼儀正しい",breakdown:"rude の反対。角が取れて磨かれたふるまい"},
     {synonym:true,word:"impolite",meaning:"失礼な",breakdown:"やわらかい言い方。rude はもっと強く非難する"}]},

  {id:219,word:"lonely",partOfSpeech:"形容詞",meaning:"孤独な",
   meanings:["形|孤独な"],
   pronunciation:"/ˈloʊnli/",part:22,
   example:"He felt lonely in his new school at first.",
   exampleJa:"彼は初めのうち、新しい学校で孤独だった。",
   example2:"The old empty house on the hill looks lonely.",
   exampleJa2:"丘の上の古い空き家は孤独に見える。",
   etymologyProcess:"lone（ひとりの）＋ ly（形容詞）→ ひとりきりで心細い感じは…？",
   etymologyConclusion:"lone（ひとりの）＋ ly（形容詞）→ ひとりきりで、そばに誰もいない心細さ＝孤独な",
   relatedWords:[
     {word:"lone",meaning:"ひとりの，孤立した",breakdown:"lone（ひとりの）→ 連れがなく、ぽつんと一つだけ"},
     {word:"alone",meaning:"1人で",breakdown:"all（すっかり）＋ one（1つ）→ まったく一人だけで"},
     {word:"loneliness",meaning:"孤独",breakdown:"lone（ひとりの）＋ ness（名詞）→ ひとりきりの心細さ"},
     {synonym:true,word:"sad",meaning:"悲しい",breakdown:"悲しい気持ち。lonely は一人でいてさびしい"}]},

  {id:220,word:"lazy",partOfSpeech:"形容詞",meaning:"怠惰な",
   meanings:["形|（やる気がなく）怠惰な，いい加減な","形|（名詞の前で）くつろいだ"],
   pronunciation:"/ˈleɪzi/",part:22,
   example:"He is too lazy to clean his own room.",
   exampleJa:"彼は怠惰すぎて自分の部屋を掃除しない。",
   example2:"Don't be lazy about your daily English practice.",
   exampleJa2:"毎日の英語の練習に怠惰であってはいけない。",
   etymologyProcess:"lazy（気だるい）→ 体も気持ちも重くて動きたくないのは…？",
   etymologyConclusion:"lazy（気だるい）→ 体も気持ちも重くて、動くのが面倒になる＝怠惰な",
   etymologyMore:["急がずだらりと過ごす→（名詞の前で）くつろいだ"],
   hook:"語源のはっきりしない語。だるくて動きたくない感じで覚える。",
   relatedWords:[
     {word:"laziness",meaning:"怠惰",breakdown:"lazy（気だるい）＋ ness（名詞）→ 動きたくない気分そのもの"},
     {word:"lazily",meaning:"のんびりと",breakdown:"lazy（気だるい）＋ ly（副詞）→ だるそうにゆっくりと"},
     {synonym:true,word:"idle",meaning:"何もしていない",breakdown:"手が空いている。lazy はやる気がなくて動かない"},
     {synonym:true,word:"diligent",meaning:"勤勉な",breakdown:"lazy の反対。こつこつ休まず取り組む"}]},

  {id:221,word:"strict",partOfSpeech:"形容詞",meaning:"厳しい",
   meanings:["形|厳しい"],
   pronunciation:"/strɪkt/",part:23,
   example:"Our school has very strict rules about hair color.",
   exampleJa:"私たちの学校には髪の色についてとても厳しい規則がある。",
   example2:"His father is strict about coming home early.",
   exampleJa2:"彼の父親は早く帰宅することに厳しい。",
   etymologyProcess:"strict（締めつける）→ ゆるみなくきつく締めつける態度は…？",
   etymologyConclusion:"strict（締めつける）→ ゆるみが出ないよう、きつく締めつけるような態度＝厳しい",
   relatedWords:[
     {word:"strictly",meaning:"厳しく，厳密に",breakdown:"strict（締めつける）＋ ly（副詞）→ ゆるみなくきっちりと"},
     {word:"restrict",meaning:"制限する",breakdown:"re（後ろへ）＋ strict（締めつける）→ 広がらないよう締めて押さえる"},
     {word:"district",meaning:"地区",breakdown:"dis（バラバラに）＋ strict（締めつける）→ 線で締め分けた区域"},
     {synonym:true,word:"severe",meaning:"厳しい，ひどい",breakdown:"程度がひどく厳しい。strict は規則にうるさい"}]},

  {id:222,word:"ugly",partOfSpeech:"形容詞",meaning:"醜い",
   meanings:["形|醜い"],
   pronunciation:"/ˈʌɡli/",part:23,
   example:"The old factory looks ugly from the station.",
   exampleJa:"その古い工場は駅から見ると醜い。",
   example2:"She painted an ugly monster for the school play.",
   exampleJa2:"彼女は学校の劇のために醜い怪物を描いた。",
   etymologyProcess:"ug（恐ろしい）＋ ly（形容詞）→ 見ると目をそむけたくなるのは…？",
   etymologyConclusion:"ug（恐ろしい）＋ ly（形容詞）→ 見ると恐ろしくて目をそむけたくなる＝醜い",
   relatedWords:[
     {word:"ugliness",meaning:"醜さ",breakdown:"ug（恐ろしい）＋ ness（名詞）→ 目をそむけたくなる見た目"},
     {synonym:true,word:"beautiful",meaning:"美しい",breakdown:"ugly の反対。見ていて心地よい"},
     {synonym:true,word:"terrible",meaning:"ひどい",breakdown:"ひどく悪い。ugly は見た目のひどさを言う"},
     {synonym:true,word:"plain",meaning:"地味な",breakdown:"飾り気がない。ugly ほど強い非難ではない"}]},

  {id:223,word:"intelligent",partOfSpeech:"形容詞",meaning:"知的な，賢い",
   meanings:["形|知的な，賢い"],
   pronunciation:"/ɪnˈtelɪdʒənt/",part:23,
   example:"Dolphins are very intelligent animals in the sea.",
   exampleJa:"イルカは海のとても知的な動物だ。",
   example2:"She gave an intelligent answer to a hard question.",
   exampleJa2:"彼女は難しい質問に知的な答えを返した。",
   etymologyProcess:"inter（間の）＋ lect（拾う）＋ ent（形容詞）→ 多くの中から要点を…？",
   etymologyConclusion:"inter（間の）＋ lect（拾う）＋ ent（形容詞）→ 多くの中から要点を拾い分けられる＝知的な",
   relatedWords:[
     {word:"collect",meaning:"集める",breakdown:"col（共に）＋ lect（拾う）→ ばらばらの物を一か所へ拾い寄せる"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離して）＋ lect（拾う）→ 全体から離して拾い上げる"},
     {word:"intelligence",meaning:"知能，情報",breakdown:"inter（間の）＋ lect（拾う）＋ ence（名詞）→ 要点を拾い分ける力"},
     {word:"intellectual",meaning:"知的な；知識人",breakdown:"inter（間の）＋ lect（拾う）＋ ual（形容詞）→ 頭で拾い分ける"}]},

  {id:224,word:"silly",partOfSpeech:"形容詞",meaning:"ばかな",
   meanings:["形|ばかな"],
   pronunciation:"/ˈsɪli/",part:23,
   example:"Don't ask such a silly question in class.",
   exampleJa:"授業でそんなばかな質問をしてはいけない。",
   example2:"We made a silly mistake in the first game.",
   exampleJa2:"私たちは最初の試合でばかな失敗をした。",
   etymologyProcess:"silly（もとは無邪気な）→ 世間を知らず考えが足りないのは…？",
   etymologyConclusion:"silly（もとは無邪気な）→ 無邪気さが行きすぎて、考えが足りない＝ばかな",
   hook:"もとは「幸せ・無邪気」。無邪気すぎる→考えが足りない、と移った。",
   relatedWords:[
     {word:"silliness",meaning:"ばかげたこと",breakdown:"silly（もとは無邪気な）＋ ness（名詞）→ 考えの足りないふるまい"},
     {synonym:true,word:"stupid",meaning:"ばかな，愚かな",breakdown:"頭の働きが鈍い。silly は子どもっぽくばかげている"},
     {synonym:true,word:"foolish",meaning:"愚かな",breakdown:"判断が愚か。silly は笑ってしまうようなばかさ"},
     {synonym:true,word:"serious",meaning:"真剣な",breakdown:"silly の反対。まじめに受け止めている"}]},

  {id:225,word:"nervous",partOfSpeech:"形容詞",meaning:"あがって，落ち着かない",
   meanings:["形|あがって，落ち着かない","形|神経質な，臆病な","形|（身体の）神経の"],
   pronunciation:"/ˈnɜːrvəs/",part:23,
   example:"She felt nervous before her first speech contest.",
   exampleJa:"彼女は初めてのスピーチ大会の前であがっていた。",
   example2:"Don't be nervous about the interview tomorrow morning.",
   exampleJa2:"明日の朝の面接であがってはいけない。",
   etymologyProcess:"nerv（神経）＋ ous（形容詞）→ 神経が糸のように張りつめると…？",
   etymologyConclusion:"nerv（神経）＋ ous（形容詞）→ 神経が糸のように張りつめる＝あがって，落ち着かない",
   relatedWords:[
     {word:"nerve",meaning:"神経",breakdown:"nerv（神経）→ 体じゅうに信号を伝える細い糸"},
     {word:"nervously",meaning:"不安そうに",breakdown:"nerv（神経）＋ ous（形容詞）＋ ly（副詞）→ 神経を張りつめた様子で"},
     {word:"nervousness",meaning:"緊張，あがること",breakdown:"nerv（神経）＋ ous（形容詞）＋ ness（名詞）→ 神経が張りつめた状態"},
     {synonym:true,word:"calm",meaning:"落ち着いた",breakdown:"nervous の反対。気持ちが静かに落ち着いている"}]},

  {id:226,word:"awake",partOfSpeech:"形容詞",meaning:"目を覚まして",
   meanings:["形|目を覚まして"],
   pronunciation:"/əˈweɪk/",part:23,
   example:"The baby was still awake at ten o'clock.",
   exampleJa:"赤ちゃんは10時になってもまだ目を覚ましていた。",
   example2:"I stayed awake all night to finish my report.",
   exampleJa2:"私はレポートを終えるため一晩中目を覚ましていた。",
   etymologyProcess:"wake（目覚める）→ 眠りから起き上がって目が…？",
   etymologyConclusion:"wake（目覚める）→ 眠りから起き上がって、目が開いたままでいる＝目を覚まして",
   hook:"a＋wake で「目が覚めている状態」。asleep（眠って）と対になる。",
   relatedWords:[
     {word:"wake",meaning:"目が覚める，起こす",breakdown:"wake（目覚める）→ 眠りから意識が戻ってくる"},
     {word:"awaken",meaning:"目覚めさせる",breakdown:"wake（目覚める）＋ en（〜にする）→ 眠っている人を起こす"},
     {synonym:true,word:"asleep",meaning:"眠って",breakdown:"awake の反対。眠り込んでいる状態"},
     {synonym:true,word:"alert",meaning:"油断のない",breakdown:"目を覚まして気を配る。awake は目が開いている状態"}]},

  {id:227,word:"alone",partOfSpeech:"副詞",meaning:"1人で",
   meanings:["副|1人で","形|（名詞＋alone）～だけ"],
   pronunciation:"/əˈloʊn/",part:23,
   example:"She walked home alone after the club activity.",
   exampleJa:"彼女は部活動のあと1人で歩いて帰った。",
   example2:"I don't want to live alone in a big city.",
   exampleJa2:"私は大都市で1人で暮らしたくない。",
   etymologyProcess:"all（すっかり）＋ one（1つ）→ ほかに誰もいない状態は…？",
   etymologyConclusion:"all（すっかり）＋ one（1つ）→ ほかに誰もおらず、まったく一人きり＝1人で",
   relatedWords:[
     {word:"lonely",meaning:"孤独な",breakdown:"lone（ひとりの）＋ ly（形容詞）→ ひとりきりで心細い"},
     {word:"lone",meaning:"ひとりの",breakdown:"lone（ひとりの）→ 連れがなく、ぽつんと一つだけ"},
     {word:"only",meaning:"ただ～だけ",breakdown:"one（1つ）＋ ly（形容詞）→ たった一つだけの"},
     {synonym:true,word:"by oneself",meaning:"自分だけで",breakdown:"alone の言いかえ。誰の助けも借りずに"}]},

  {id:228,word:"attitude",partOfSpeech:"名詞",meaning:"態度，姿勢",
   meanings:["名|態度，姿勢"],
   pronunciation:"/ˈætɪtuːd/",part:23,
   example:"His attitude toward study changed after the school trip.",
   exampleJa:"彼の勉強に対する態度は修学旅行のあとで変わった。",
   example2:"The teacher praised her positive attitude in class.",
   exampleJa2:"先生は授業での彼女の前向きな態度をほめた。",
   etymologyProcess:"apt（ぴったり合う）＋ tude（名詞）→ 相手に合わせて取る身構えは…？",
   etymologyConclusion:"apt（ぴったり合う）＋ tude（名詞）→ 相手や物事に合わせて取る心と体の身構え＝態度",
   relatedWords:[
     {word:"apt",meaning:"～しがちな；適切な",breakdown:"apt（ぴったり合う）→ その場にぴったりはまりやすい"},
     {word:"adapt",meaning:"適応する",breakdown:"ad（〜へ）＋ apt（ぴったり合う）→ 環境にぴったり合わせる"},
     {word:"aptitude",meaning:"素質，適性",breakdown:"apt（ぴったり合う）＋ tude（名詞）→ その仕事にぴったり合う力"},
     {synonym:true,word:"manner",meaning:"態度，作法",breakdown:"外に表れるふるまい。attitude は心の構えを指す"}]},

  {id:229,word:"character",partOfSpeech:"名詞",meaning:"性格",
   meanings:["名|性格，人柄","名|登場人物","名|文字"],
   pronunciation:"/ˈkærəktər/",part:23,
   example:"He has a kind and honest character like his father.",
   exampleJa:"彼は父親に似て優しく正直な性格をしている。",
   example2:"The main character in this novel is a young doctor.",
   exampleJa2:"この小説の主な登場人物は若い医者だ。",
   etymologyProcess:"charact（刻みつける）＋ er（もの）→ 心に刻み込まれて消えない印は…？",
   etymologyConclusion:"charact（刻みつける）＋ er（もの）→ その人の心に刻み込まれて消えない印＝性格",
   etymologyMore:["物語に刻みつけられた人物→登場人物","紙に刻みつけたしるし→文字"],
   relatedWords:[
     {word:"characteristic",meaning:"特性；特徴的な",breakdown:"charact（刻みつける）＋ istic（形容詞）→ 刻まれた印のような"},
     {word:"characterize",meaning:"特徴づける",breakdown:"charact（刻みつける）＋ ize（動詞）→ 目印を刻んで特徴を示す"},
     {synonym:true,word:"personality",meaning:"人格，個性",breakdown:"人としての個性全体。character は道徳的な中身も含む"},
     {synonym:true,word:"nature",meaning:"性質",breakdown:"生まれつきの性質。character は育って刻まれた性格"}]},

  {id:230,word:"characteristic",partOfSpeech:"名詞",meaning:"特性",
   meanings:["名|特性，特徴〈可算〉","形|特有の，特徴的な"],
   pronunciation:"/ˌkærəktəˈrɪstɪk/",part:23,
   example:"Long ears are a characteristic of this wild rabbit.",
   exampleJa:"長い耳はこの野ウサギの特性だ。",
   example2:"Patience is an important characteristic of good teachers.",
   exampleJa2:"忍耐強さは良い教師の大切な特性だ。",
   etymologyProcess:"charact（刻みつける）＋ istic（形容詞）→ その人や物に刻まれた目印は…？",
   etymologyConclusion:"charact（刻みつける）＋ istic（形容詞）→ その人や物に刻まれて、見分ける目印になるもの＝特性",
   relatedWords:[
     {word:"character",meaning:"性格，特徴",breakdown:"charact（刻みつける）＋ er（もの）→ 心に刻み込まれた印"},
     {word:"characterize",meaning:"特徴づける",breakdown:"charact（刻みつける）＋ ize（動詞）→ 目印を刻んで特徴を示す"},
     {synonym:true,word:"feature",meaning:"特徴",breakdown:"目立つ点。characteristic は性質としての特徴"},
     {synonym:true,word:"quality",meaning:"資質，質",breakdown:"備わっている性質。characteristic はそれを見分ける目印"}]},

  {id:231,word:"feature",partOfSpeech:"名詞",meaning:"目立つ特徴",
   meanings:["名|目立つ特徴","名|特集記事","他|～を特集する"],
   pronunciation:"/ˈfiːtʃər/",part:24,
   example:"The best feature of this phone is its camera.",
   exampleJa:"この電話の最も良い特徴はカメラだ。",
   example2:"Deep snow is a common feature of winter here.",
   exampleJa2:"深い雪はここの冬によくある特徴だ。",
   etymologyProcess:"fic（作る）＋ ture（名詞）→ 作られたときからある目立つ形は…？",
   etymologyConclusion:"fic（作る）＋ ture（名詞）→ 作られたときからそなわっている、目立つ形＝特徴",
   etymologyMore:["紙面の目玉として作られた記事→特集記事"],
   relatedWords:[
     {word:"fact",meaning:"事実",breakdown:"fic（作る）→ 実際に作られて起きたことがら"},
     {word:"factory",meaning:"工場",breakdown:"fic（作る）＋ ory（場所）→ 物を作るための場所"},
     {word:"manufacture",meaning:"製造する",breakdown:"manu（手）＋ fic（作る）→ 手や機械で作り出す"},
     {synonym:true,word:"characteristic",meaning:"特性",breakdown:"性質としての特徴。feature は目に見えて目立つ点"}]},

  {id:232,word:"detail",partOfSpeech:"名詞",meaning:"詳細",
   meanings:["名|詳細","名|（建物などの）細部"],
   pronunciation:"/ˈdiːteɪl/",part:24,
   example:"Please explain the details of your plan again.",
   exampleJa:"あなたの計画の詳細をもう一度説明してください。",
   example2:"She remembered every detail of that summer day.",
   exampleJa2:"彼女はあの夏の日の詳細をすべて覚えていた。",
   etymologyProcess:"de（すっかり）＋ tail（切る）→ 全体を細かく切り分けた一つ一つは…？",
   etymologyConclusion:"de（すっかり）＋ tail（切る）→ 全体を細かく切り分けた、その一つ一つ＝詳細",
   relatedWords:[
     {word:"tailor",meaning:"仕立て屋",breakdown:"tail（切る）＋ or（人）→ 布を切って服を作る人"},
     {word:"retail",meaning:"小売り",breakdown:"re（再び）＋ tail（切る）→ 品物を小さく切り分けて売る"},
     {word:"detailed",meaning:"詳しい",breakdown:"de（すっかり）＋ tail（切る）→ 細かく切り分けられている"},
     {synonym:true,word:"point",meaning:"点，要点",breakdown:"一つの点。detail は細かい点の一つ一つ"}]},

  {id:233,word:"advantage",partOfSpeech:"名詞",meaning:"利点",
   meanings:["名|（over ～）（～に対する）利点"],
   pronunciation:"/ədˈvæntɪdʒ/",part:24,
   example:"Living near the station is a big advantage.",
   exampleJa:"駅の近くに住んでいるのは大きな利点だ。",
   example2:"Tall players have an advantage in basketball games.",
   exampleJa2:"背の高い選手はバスケットボールの試合で利点がある。",
   etymologyProcess:"ad（〜へ）＋ van（前へ）→ 人より前に出られる有利さは…？",
   etymologyConclusion:"ad（〜へ）＋ van（前へ）→ ほかより一歩前に出られる有利な点＝利点",
   relatedWords:[
     {word:"advance",meaning:"前進する，進歩",breakdown:"ad（〜へ）＋ van（前へ）→ 一歩ずつ前へ進み出る"},
     {word:"advanced",meaning:"上級の，進んだ",breakdown:"ad（〜へ）＋ van（前へ）→ ほかより前へ進んだ段階の"},
     {word:"disadvantage",meaning:"不利な点",breakdown:"dis（否定）＋ ad（〜へ）＋ van（前へ）→ 前に出られない点"},
     {synonym:true,word:"benefit",meaning:"恩恵，利益",breakdown:"受け取る得。advantage は他より有利になる点"}]},

  {id:234,word:"fault",partOfSpeech:"名詞",meaning:"欠点",
   meanings:["名|（ちょっとした）欠点，不具合","名|（one's ―）責任","名|断層"],
   pronunciation:"/fɔːlt/",part:24,
   example:"The only fault of this car is its color.",
   exampleJa:"この車の唯一の欠点は色だ。",
   example2:"It was my fault that we missed the last bus.",
   exampleJa2:"私たちが最終バスに乗り遅れたのは私の責任だった。",
   etymologyProcess:"fail（期待を裏切る）→ 期待どおりでなく足りないところは…？",
   etymologyConclusion:"fail（期待を裏切る）→ 期待どおりにいかず、足りていないところ＝欠点",
   etymologyMore:["誰のせいで足りなかったかを指す→（one's ―）責任","地層が裂けてずれた所→断層"],
   relatedWords:[
     {word:"fail",meaning:"失敗する",breakdown:"fail（期待を裏切る）→ 期待どおりにできず終わる"},
     {word:"faulty",meaning:"欠陥のある",breakdown:"fail（期待を裏切る）＋ y（形容詞）→ 期待を裏切る不具合がある"},
     {word:"false",meaning:"誤った；偽の",breakdown:"fail（期待を裏切る）→ 本当であるはずを裏切っている"},
     {synonym:true,word:"mistake",meaning:"間違い",breakdown:"やり損ない。fault は誰のせいかまで表す"}]},

  {id:235,word:"quality",partOfSpeech:"名詞",meaning:"質",
   meanings:["名|質〈不可算〉","名|（通例―s）（人間の）資質"],
   pronunciation:"/ˈkwɑːləti/",part:24,
   example:"The quality of this paper is very high.",
   exampleJa:"この紙の質はとても高い。",
   example2:"We care about the quality more than the price.",
   exampleJa2:"私たちは値段よりも質を大切にしている。",
   etymologyProcess:"qual（どんな）＋ ity（名詞）→ それがどんなものかを決める中身は…？",
   etymologyConclusion:"qual（どんな）＋ ity（名詞）→ それがどんなものかを決めている中身＝質",
   etymologyMore:["その人がどんな人かを決める中身→（人間の）資質"],
   relatedWords:[
     {word:"quantity",meaning:"量",breakdown:"quant（どれだけ）＋ ity（名詞）→ どれだけあるかという数量"},
     {word:"qualify",meaning:"資格を与える",breakdown:"qual（どんな）＋ ify（する）→ どんな人かを認めて資格を与える"},
     {word:"qualified",meaning:"資格のある",breakdown:"qual（どんな）＋ ify（する）→ 条件に合うと認められた"},
     {synonym:true,word:"value",meaning:"価値",breakdown:"どれだけ値打ちがあるか。quality は中身の良し悪し"}]},

  {id:236,word:"correct",partOfSpeech:"形容詞",meaning:"正確な，正しい",
   meanings:["形|正確な，正しい","他|～を訂正する，矯正する"],
   pronunciation:"/kəˈrekt/",part:24,
   example:"Only one of these four answers is correct.",
   exampleJa:"この4つの答えのうち1つだけが正しい。",
   example2:"Please write the correct date on this form.",
   exampleJa2:"この用紙に正しい日付を書いてください。",
   etymologyProcess:"com（すっかり）＋ rect（まっすぐ）→ 曲がりをすっかり直すと…？",
   etymologyConclusion:"com（すっかり）＋ rect（まっすぐ）→ 曲がったところをすっかりまっすぐに直した＝正しい",
   etymologyMore:["曲がりをまっすぐ直す→～を訂正する，矯正する"],
   relatedWords:[
     {word:"direct",meaning:"直接の",breakdown:"di（離れて）＋ rect（まっすぐ）→ よそへ寄らずまっすぐ向かう"},
     {word:"rectangle",meaning:"長方形",breakdown:"rect（まっすぐ）＋ angle（角）→ 角がまっすぐ直角の形"},
     {word:"correction",meaning:"訂正",breakdown:"com（すっかり）＋ rect（まっすぐ）＋ ion（名詞）→ まっすぐ直すこと"},
     {synonym:true,word:"right",meaning:"正しい",breakdown:"正しい。correct は答えが合っていることを言う"}]},

  {id:237,word:"ideal",partOfSpeech:"形容詞",meaning:"理想的な",
   meanings:["形|理想的な，申し分のない","名|理想，理想的な姿"],
   pronunciation:"/aɪˈdiːəl/",part:24,
   example:"This park is an ideal place for a picnic.",
   exampleJa:"この公園はピクニックに理想的な場所だ。",
   example2:"Sunday morning is the ideal time to study.",
   exampleJa2:"日曜の朝は勉強するのに理想的な時間だ。",
   etymologyProcess:"ide（見える姿）＋ al（形容詞）→ 頭に思い描いた完璧な姿どおりなのは…？",
   etymologyConclusion:"ide（見える姿）＋ al（形容詞）→ 頭に思い描いた完璧な姿のとおりだ＝理想的な",
   relatedWords:[
     {word:"idea",meaning:"考え，思いつき",breakdown:"ide（見える姿）→ 頭の中に浮かんだ姿"},
     {word:"ideally",meaning:"理想的には",breakdown:"ide（見える姿）＋ al（形容詞）→ 思い描いた姿のとおりに言えば"},
     {word:"idol",meaning:"あこがれの人，偶像",breakdown:"ide（見える姿）→ 心に描いて拝む姿"},
     {synonym:true,word:"perfect",meaning:"完全な",breakdown:"欠けがない。ideal は思い描いた理想どおり"}]},

  {id:238,word:"fair",partOfSpeech:"形容詞",meaning:"公正な，公平な",
   meanings:["形|公正な，公平な","名|品評会，見本市"],
   pronunciation:"/fer/",part:24,
   example:"The rules of this game are fair to everyone.",
   exampleJa:"この試合の規則は全員に公平だ。",
   example2:"It is not fair to blame only one player.",
   exampleJa2:"一人の選手だけを責めるのは公平ではない。",
   etymologyProcess:"fair（美しい・整った）→ どちらにも傾かず整っているのは…？",
   etymologyConclusion:"fair（美しい・整った）→ どちらにも傾かず、形よく整っている＝公正な",
   hook:"芯は「整って美しい」。天気なら「晴れ」、人なら「公正」。",
   relatedWords:[
     {word:"fairly",meaning:"かなり；公平に",breakdown:"fair（美しい・整った）＋ ly（副詞）→ 偏らずほどよく"},
     {word:"fairness",meaning:"公正さ",breakdown:"fair（美しい・整った）＋ ness（名詞）→ 偏りがなく整っていること"},
     {word:"unfair",meaning:"不公平な",breakdown:"un（否定）＋ fair（美しい・整った）→ 一方に傾いている"},
     {synonym:true,word:"just",meaning:"公正な",breakdown:"法にかなって正しい。fair は偏りがないこと"}]},

  {id:239,word:"appropriate",partOfSpeech:"形容詞",meaning:"適切な",
   meanings:["形|適切な"],
   pronunciation:"/əˈproʊpriət/",part:24,
   example:"Jeans are not appropriate for this formal party.",
   exampleJa:"ジーンズはこの正式なパーティーには適切でない。",
   example2:"Choose an appropriate word for each blank below.",
   exampleJa2:"下のそれぞれの空所に適切な語を選びなさい。",
   etymologyProcess:"ad（〜へ）＋ propri（自分のもの）→ その場にしっくりはまるのは…？",
   etymologyConclusion:"ad（〜へ）＋ propri（自分のもの）→ その場にしっくりはまり、自分のものになじむ＝適切な",
   relatedWords:[
     {word:"proper",meaning:"適切な，ふさわしい",breakdown:"propri（自分のもの）→ そのものに本来そなわっている"},
     {word:"property",meaning:"財産；特性",breakdown:"propri（自分のもの）＋ ty（名詞）→ 自分のものとして持つもの"},
     {word:"appropriately",meaning:"適切に",breakdown:"ad（〜へ）＋ propri（自分のもの）→ 場にしっくり合う形で"},
     {synonym:true,word:"suitable",meaning:"ふさわしい",breakdown:"条件に合う。appropriate は場面にぴったり合う"}]},

  {id:240,word:"famous",partOfSpeech:"形容詞",meaning:"有名な",
   meanings:["形|（for one's ～）（～で）有名な","形|（as ～）（～として）有名な"],
   pronunciation:"/ˈfeɪməs/",part:24,
   example:"This small town is famous for its old bridge.",
   exampleJa:"この小さな町は古い橋で有名だ。",
   example2:"She became famous as a very young writer.",
   exampleJa2:"彼女はとても若い作家として有名になった。",
   etymologyProcess:"fam（語られる）＋ ous（形容詞）→ 多くの人の口にのぼるのは…？",
   etymologyConclusion:"fam（語られる）＋ ous（形容詞）→ 多くの人の口にのぼって語られている＝有名な",
   relatedWords:[
     {word:"fame",meaning:"名声",breakdown:"fam（語られる）→ 世間で語られることそのもの"},
     {word:"infamous",meaning:"悪名高い",breakdown:"in（否定）＋ fam（語られる）→ 悪いほうで語られている"},
     {word:"famously",meaning:"有名なことに",breakdown:"fam（語られる）＋ ous（形容詞）→ よく語られていることだが"},
     {synonym:true,word:"popular",meaning:"人気のある",breakdown:"みんなに好かれる。famous は名前が広く知られている"}]},

  {id:241,word:"elementary",partOfSpeech:"形容詞",meaning:"初歩的な，基本の",
   meanings:["形|初歩的な，基本の"],
   pronunciation:"/ˌelɪˈmentri/",part:25,
   example:"This book explains elementary math in an easy way.",
   exampleJa:"この本は初歩的な数学をやさしく説明している。",
   example2:"He teaches English at a small elementary school.",
   exampleJa2:"彼は小さな小学校で英語を教えている。",
   etymologyProcess:"element（要素）＋ ary（形容詞）→ 基本の要素だけでできているのは…？",
   etymologyConclusion:"element（要素）＋ ary（形容詞）→ いちばん基本の要素だけでできている＝初歩的な",
   relatedWords:[
     {word:"element",meaning:"要素，元素",breakdown:"element（要素）→ それ以上分けられない基本の部品"},
     {word:"elemental",meaning:"根本的な",breakdown:"element（要素）＋ al（形容詞）→ 基本の要素にかかわる"},
     {synonym:true,word:"basic",meaning:"基本的な",breakdown:"土台になる。elementary は学び始めの初歩の段階"},
     {synonym:true,word:"simple",meaning:"簡単な",breakdown:"複雑でない。elementary は初歩の内容であること"}]},

  {id:242,word:"major",partOfSpeech:"形容詞",meaning:"主要な",
   meanings:["形|主要な","自|（in ～）（～を）専攻する","名|専攻"],
   pronunciation:"/ˈmeɪdʒər/",part:25,
   example:"Traffic is a major problem in this old city.",
   exampleJa:"交通はこの古い都市の主要な問題だ。",
   example2:"She played a major role in the school play.",
   exampleJa2:"彼女は学校の劇で主要な役を演じた。",
   etymologyProcess:"maj（大きい）＋ or（より〜な）→ ほかより大きくて中心になるのは…？",
   etymologyConclusion:"maj（大きい）＋ or（より〜な）→ ほかより大きく、中心にすわっている＝主要な",
   etymologyMore:["大学で中心にすえて学ぶ分野→専攻"],
   relatedWords:[
     {word:"majority",meaning:"大多数",breakdown:"maj（大きい）＋ ity（名詞）→ 大きいほうのまとまり"},
     {word:"mayor",meaning:"市長",breakdown:"maj（大きい）→ 町でいちばん大きな役をになう人"},
     {synonym:true,word:"main",meaning:"主な",breakdown:"いちばん中心の。major は規模が大きく重要なこと"},
     {synonym:true,word:"minor",meaning:"小さいほうの",breakdown:"major の反対。重要でないほう"}]},

  {id:243,word:"matter",partOfSpeech:"自動詞",meaning:"重要である",
   meanings:["自|重要である","名|（修飾語を伴い）物質","名|（―s）事態，状況"],
   pronunciation:"/ˈmætər/",part:25,
   example:"Your health matters more than your test score.",
   exampleJa:"あなたの健康はテストの点数より重要である。",
   example2:"It does not matter if we arrive a little late.",
   exampleJa2:"少し遅れて着いても重要ではない（かまわない）。",
   etymologyProcess:"mater（母）→ 物事を生み出すもとの中身は…？",
   etymologyConclusion:"mater（母）→ 物事を生み出すもとの中身なので、放っておけない＝重要である",
   etymologyMore:["物を形づくっているもとのもの→物質","中身として問題になっていること→事態，状況"],
   relatedWords:[
     {word:"material",meaning:"材料，資料",breakdown:"mater（母）＋ ial（形容詞）→ 物を生み出すもとになるもの"},
     {word:"maternal",meaning:"母の，母親らしい",breakdown:"mater（母）＋ al（形容詞）→ 母にかかわる"},
     {synonym:true,word:"count",meaning:"重要である",breakdown:"数に入る＝重要である。matter とほぼ同じ使い方"},
     {synonym:true,word:"important",meaning:"重要な",breakdown:"形容詞の「重要な」。matter は動詞で「重要である」"}]},

  {id:244,word:"bright",partOfSpeech:"形容詞",meaning:"明るい",
   meanings:["形|明るい","形|（主に子どもや若者が）賢い"],
   pronunciation:"/braɪt/",part:25,
   example:"The kitchen is bright in the morning sun.",
   exampleJa:"その台所は朝日の中で明るい。",
   example2:"She wore a bright yellow raincoat to school.",
   exampleJa2:"彼女は明るい黄色のレインコートを着て学校へ行った。",
   etymologyProcess:"bright（輝く）→ 光がはっきり差してまぶしいのは…？",
   etymologyConclusion:"bright（輝く）→ 光がはっきり差してまぶしいほどだ＝明るい",
   etymologyMore:["頭に光がさしているよう→（主に子どもや若者が）賢い"],
   hook:"光が強い→「明るい」、頭に光がある→「賢い」。どちらも光の絵。",
   relatedWords:[
     {word:"brightly",meaning:"明るく",breakdown:"bright（輝く）＋ ly（副詞）→ 光がはっきり差すように"},
     {word:"brightness",meaning:"明るさ",breakdown:"bright（輝く）＋ ness（名詞）→ どれだけ光っているか"},
     {word:"brighten",meaning:"明るくする",breakdown:"bright（輝く）＋ en（〜にする）→ 光を強くして明るくする"},
     {synonym:true,word:"dark",meaning:"暗い",breakdown:"bright の反対。光が届いていない"}]},

  {id:245,word:"brilliant",partOfSpeech:"形容詞",meaning:"輝いている",
   meanings:["形|輝いている","形|すばらしい"],
   pronunciation:"/ˈbrɪliənt/",part:25,
   example:"The stars were brilliant in the winter sky.",
   exampleJa:"星々は冬の空に輝いていた。",
   example2:"She had a brilliant idea for the school festival.",
   exampleJa2:"彼女は文化祭のためのすばらしい考えを思いついた。",
   etymologyProcess:"brill（きらきら光る）＋ ant（〜な）→ 宝石のように光るのは…？",
   etymologyConclusion:"brill（きらきら光る）＋ ant（〜な）→ 宝石のようにきらきらと光を放っている＝輝いている",
   etymologyMore:["才能がきらめいている→すばらしい"],
   relatedWords:[
     {word:"brilliance",meaning:"輝き；優秀さ",breakdown:"brill（きらきら光る）＋ ance（名詞）→ きらきら光っていること"},
     {word:"brilliantly",meaning:"見事に",breakdown:"brill（きらきら光る）＋ ly（副詞）→ きらめくように見事に"},
     {synonym:true,word:"bright",meaning:"明るい",breakdown:"光が強い。brilliant はもっと強くきらめく"},
     {synonym:true,word:"shine",meaning:"輝く",breakdown:"光を放つ動き。brilliant はその状態を表す形容詞"}]},

  {id:246,word:"lively",partOfSpeech:"形容詞",meaning:"生き生きとした",
   meanings:["形|生き生きとした"],
   pronunciation:"/ˈlaɪvli/",part:25,
   example:"The market was lively early in the morning.",
   exampleJa:"その市場は朝早くから生き生きとしていた。",
   example2:"She gave a lively speech about her club activity.",
   exampleJa2:"彼女は部活動について生き生きとしたスピーチをした。",
   etymologyProcess:"live（生きる）＋ ly（形容詞）→ 生きる力があふれて動きがあるのは…？",
   etymologyConclusion:"live（生きる）＋ ly（形容詞）→ 生きている力があふれて動きがある＝生き生きとした",
   relatedWords:[
     {word:"live",meaning:"生きる，暮らす",breakdown:"live（生きる）→ 命があって動き続けている"},
     {word:"alive",meaning:"生きている",breakdown:"live（生きる）→ 命があって動いている状態にある"},
     {word:"liveliness",meaning:"活発さ",breakdown:"live（生きる）＋ ness（名詞）→ 生き生きしていること"},
     {synonym:true,word:"active",meaning:"活発な",breakdown:"よく動く。lively は明るく生気があること"}]},

  {id:247,word:"comfortable",partOfSpeech:"形容詞",meaning:"（物が）快適な",
   meanings:["形|（物が）快適な","形|（人が）心地よい"],
   pronunciation:"/ˈkʌmftəbl/",part:25,
   example:"This old chair is very comfortable to sit in.",
   exampleJa:"この古いいすは座るのにとても快適だ。",
   example2:"The small hotel room was clean and comfortable.",
   exampleJa2:"その小さなホテルの部屋は清潔で快適だった。",
   etymologyProcess:"com（すっかり）＋ fort（力）→ 力を抜いてくつろげるのは…？",
   etymologyConclusion:"com（すっかり）＋ fort（力）→ 体にすっかり力を添えてくれてくつろげる＝快適な",
   relatedWords:[
     {word:"comfort",meaning:"快適さ；慰める",breakdown:"com（すっかり）＋ fort（力）→ 弱った心に力を添える"},
     {word:"effort",meaning:"努力",breakdown:"ef（外へ）＋ fort（力）→ 力を外へ絞り出す"},
     {word:"force",meaning:"力，強いる",breakdown:"fort（力）→ 押し動かす力そのもの"},
     {synonym:true,word:"relaxed",meaning:"くつろいだ",breakdown:"緊張がほどけた。comfortable は居心地がよいこと"}]},

  {id:248,word:"pleasant",partOfSpeech:"形容詞",meaning:"（人にとって）心地よい",
   meanings:["形|（人にとって）楽しい，心地よい"],
   pronunciation:"/ˈpleznt/",part:25,
   example:"We had a pleasant time at the beach.",
   exampleJa:"私たちは浜辺で心地よい時間を過ごした。",
   example2:"A pleasant wind came through the open window.",
   exampleJa2:"心地よい風が開いた窓から入ってきた。",
   etymologyProcess:"pleas（喜ばせる）＋ ant（〜な）→ 相手の気持ちを喜ばせるのは…？",
   etymologyConclusion:"pleas（喜ばせる）＋ ant（〜な）→ 相手の気持ちを喜ばせてくれる＝心地よい",
   relatedWords:[
     {word:"please",meaning:"喜ばせる",breakdown:"pleas（喜ばせる）→ 相手の気持ちを明るくする"},
     {word:"pleasure",meaning:"喜び，楽しみ",breakdown:"pleas（喜ばせる）＋ ure（名詞）→ 喜ばされた気持ち"},
     {word:"unpleasant",meaning:"不快な",breakdown:"un（否定）＋ pleas（喜ばせる）→ 喜ばせてくれない"},
     {synonym:true,word:"comfortable",meaning:"快適な",breakdown:"体が楽であること。pleasant は気持ちが楽しい"}]},

  {id:249,word:"convenient",partOfSpeech:"形容詞",meaning:"都合がよい",
   meanings:["形|都合がよい","形|近くて便利がよい"],
   pronunciation:"/kənˈviːniənt/",part:25,
   example:"Is Monday afternoon convenient for you and your family?",
   exampleJa:"月曜の午後はあなたとご家族に都合がよいですか。",
   example2:"This app is convenient for checking train times.",
   exampleJa2:"このアプリは電車の時刻を調べるのに都合がよい。",
   etymologyProcess:"con（共に）＋ vent（来る）→ 必要なものが一緒に来てそろうと…？",
   etymologyConclusion:"con（共に）＋ vent（来る）→ 必要なものや時間が一緒に来てそろう＝都合がよい",
   relatedWords:[
     {word:"event",meaning:"出来事，行事",breakdown:"e（外へ）＋ vent（来る）→ 外に現れ出てくることがら"},
     {word:"invent",meaning:"発明する",breakdown:"in（中へ）＋ vent（来る）→ 頭の中に考えが降りてくる"},
     {word:"prevent",meaning:"妨げる",breakdown:"pre（先に）＋ vent（来る）→ 先回りして前に立ちふさがる"},
     {word:"convenience",meaning:"便利さ",breakdown:"con（共に）＋ vent（来る）＋ ence（名詞）→ 一緒にそろっていること"}]},

  {id:250,word:"false",partOfSpeech:"形容詞",meaning:"誤った",
   meanings:["形|誤った","形|偽の"],
   pronunciation:"/fɔːls/",part:25,
   example:"The story about the ghost turned out false.",
   exampleJa:"その幽霊の話は誤っていると分かった。",
   example2:"Mark each false sentence with a red pen.",
   exampleJa2:"誤った文にはそれぞれ赤ペンで印をつけなさい。",
   etymologyProcess:"fail（期待を裏切る）→ 本当であるはずを裏切っているのは…？",
   etymologyConclusion:"fail（期待を裏切る）→ 本当であるはずの期待を裏切っている＝誤った",
   etymologyMore:["本物のふりをして裏切る→偽の"],
   hook:"fault（欠点）と同じ仲間。true の反対で「事実を裏切る」。",
   relatedWords:[
     {word:"fail",meaning:"失敗する",breakdown:"fail（期待を裏切る）→ 期待どおりにできず終わる"},
     {word:"fault",meaning:"欠点；責任",breakdown:"fail（期待を裏切る）→ 期待どおりでなく足りないところ"},
     {word:"falsely",meaning:"誤って",breakdown:"fail（期待を裏切る）＋ ly（副詞）→ 事実を裏切る形で"},
     {synonym:true,word:"true",meaning:"本当の",breakdown:"false の反対。事実のとおりである"}]},
