  {id:1901,word:"thread",partOfSpeech:"名詞",meaning:"糸；（話の）筋道",
   meanings:["名|糸，縫い糸","名|（話・考えの）筋道","他|（針に）糸を通す"],
   pronunciation:"/θred/",part:191,
   example:"She passed a long thread through the eye of the needle.",
   exampleJa:"彼女は針の穴に長い糸を通した。",
   example2:"I lost the thread of the story halfway through the movie.",
   exampleJa2:"映画の途中で、私は話の筋道がわからなくなった。",
   etymologyProcess:"thread（ねじる）→ 細い繊維をねじり合わせると…？",
   etymologyConclusion:"thread（ねじる）→ 細い繊維をねじり合わせて作った細長いもの＝糸",
   etymologyMore:["1本の糸のように続いていく→（話・考えの）筋道"],
   hook:"throw（投げる）と同じ「ねじる」の家族。SNS の「スレッド」も話の糸が続いたもの。",
   relatedWords:[
     {word:"throw",meaning:"投げる",breakdown:"throw（ねじる）→ 体をひねって勢いよく投げ飛ばす"},
     {synonym:true,word:"string",meaning:"ひも，弦",breakdown:"糸より太いひも。thread は縫うための細い糸"},
     {synonym:true,word:"yarn",meaning:"毛糸，紡ぎ糸",breakdown:"編み物に使う太めの糸。thread は縫い糸"},
     {synonym:true,word:"rope",meaning:"ロープ，縄",breakdown:"何本もよった太い縄。thread はいちばん細い"}]},

  {id:1902,word:"ornament",partOfSpeech:"名詞",meaning:"飾り，装飾品",
   meanings:["名|飾り，装飾品","名|装飾","他|飾る"],
   pronunciation:"/ˈɔːrnəmənt/",part:191,
   example:"We hung colorful glass ornaments on the Christmas tree.",
   exampleJa:"私たちはクリスマスツリーに色とりどりのガラスの飾りをつるした。",
   example2:"These old vases are only for ornament, not for flowers.",
   exampleJa2:"これらの古い花瓶は装飾のためだけのもので、花を生けるためではない。",
   etymologyProcess:"orn（飾る）＋ ment（名詞）→ 飾るためのものは…？",
   etymologyConclusion:"orn（飾る）＋ ment（名詞）→ 見た目を美しくするために付けるもの＝飾り",
   relatedWords:[
     {word:"adorn",meaning:"飾る",breakdown:"ad（～へ）＋ orn（飾る）→ 物に飾りを付けて美しくする"},
     {word:"ornamental",meaning:"装飾用の",breakdown:"orn（飾る）＋ ment（名詞）＋ al（形容詞）→ 飾るための"},
     {synonym:true,word:"decoration",meaning:"飾り付け",breakdown:"部屋や行事の飾り付け全般。ornament は1つ1つの飾り物"},
     {synonym:true,word:"accessory",meaning:"アクセサリー",breakdown:"身に着ける小物。ornament は置いたりつるしたりする飾り"}]},

  {id:1903,word:"cosmetic",partOfSpeech:"名詞",meaning:"化粧品；表面的な",
   meanings:["名|（cosmetics で）化粧品","形|表面的な，うわべだけの","形|美容の，化粧用の"],
   pronunciation:"/kɑːzˈmetɪk/",part:191,
   example:"This shop sells cosmetics made from natural plant oils.",
   exampleJa:"この店は天然の植物油から作った化粧品を売っている。",
   example2:"The changes to the school rules were only cosmetic.",
   exampleJa2:"校則の変更は表面的なものにすぎなかった。",
   etymologyProcess:"cosm（整えること）＋ ic（～の）→ 見た目をきれいに整えるものは…？",
   etymologyConclusion:"cosm（整えること）＋ ic（～の）→ 顔や見た目をきれいに整えるための品＝化粧品",
   why:"【なぜ】ギリシャ語 kosmos は「きちんと整った状態」。そこから「きれいに飾ること」と、秩序正しく整った世界＝「宇宙」の2つの意味が生まれました。cosmetic は前者の「飾る技術」から来ています。\n【つながり】cosmos（宇宙）とは、ばらばらでなく整った世界のこと。化粧品と宇宙は「整える」でつながる親戚です。",
   etymologyMore:["見た目だけを整える→表面的な，うわべだけの"],
   relatedWords:[
     {word:"cosmos",meaning:"宇宙",breakdown:"cosm（整えること）→ 秩序正しく整った世界全体"},
     {word:"cosmopolitan",meaning:"国際的な",breakdown:"cosm（整えること）＋ polit（都市）→ 世界全体を自分の町とする"},
     {synonym:true,word:"makeup",meaning:"化粧",breakdown:"顔に施す化粧そのもの。cosmetics はそのための品物"},
     {synonym:true,word:"beauty",meaning:"美しさ",breakdown:"美しさ全般。cosmetic は見た目を整える手段"}]},

  {id:1904,word:"chamber",partOfSpeech:"名詞",meaning:"（特定の目的の）部屋，室",
   meanings:["名|（特定の目的の）部屋，室","名|議院，議会","名|（体や機械の）空洞，室"],
   pronunciation:"/ˈtʃeɪmbər/",part:191,
   example:"The king met his guests in a large chamber of the castle.",
   exampleJa:"王は城の大きな部屋で客人と会った。",
   example2:"The human heart has four chambers that pump blood.",
   exampleJa2:"人間の心臓には血液を送り出す4つの空洞がある。",
   etymologyProcess:"camer（丸天井の部屋）→ 丸い天井のある部屋は…？",
   etymologyConclusion:"camer（丸天井の部屋）→ 丸天井でおおわれた、特別な目的に使う部屋＝（特定の目的の）部屋",
   spelling:"camer→chamb（フランス語を通って変化）",
   etymologyMore:["議員が集まって話し合う部屋→議院，議会","壁で囲まれた小さな空間→（体や機械の）空洞，室"],
   relatedWords:[
     {word:"camera",meaning:"カメラ",breakdown:"camer（丸天井の部屋）→ 光を入れる「暗い部屋」の箱から"},
     {word:"comrade",meaning:"仲間，同志",breakdown:"camer（丸天井の部屋）→ 同じ部屋で寝起きする仲間"},
     {synonym:true,word:"room",meaning:"部屋",breakdown:"ふつうの部屋。chamber は特別な目的の部屋"},
     {synonym:true,word:"hall",meaning:"広間，ホール",breakdown:"人が集まる広い部屋。chamber は囲まれた一室"}]},

  {id:1905,word:"commodity",partOfSpeech:"名詞",meaning:"（取引される）商品，産物",
   meanings:["名|（取引される）商品，産物","名|役に立つもの，貴重なもの"],
   pronunciation:"/kəˈmɑːdəti/",part:191,
   example:"Coffee is an important commodity traded all over the world.",
   exampleJa:"コーヒーは世界中で取引される重要な商品だ。",
   example2:"Rice was an important commodity for farmers in old Japan.",
   exampleJa2:"昔の日本の農民にとって、米は大切な産物だった。",
   etymologyProcess:"com（すっかり）＋ modus（ほどよさ）→ ちょうど都合のよい物は…？",
   etymologyConclusion:"com（すっかり）＋ modus（ほどよさ）＋ ity（名詞）→ 暮らしにちょうど役立つ品物＝（取引される）商品",
   spelling:"modus→mod（語尾が落ちた）",
   why:"【なぜ】ラテン語 commodus は「寸法にぴったり合う」→「都合がよい，便利な」。その名詞 commoditas は「便利さ」でした。便利で役に立つものは人がほしがるので、やがて「売り買いされる品物」を指すようになりました。\n【つながり】accommodate（収容する）も「ぴったり合わせる」から。mode や moderate も同じ「ほどよさ」の仲間です。",
   relatedWords:[
     {word:"accommodate",meaning:"収容する",breakdown:"ad（～へ）＋ com（すっかり）＋ modus（ほどよさ）→ 人数に合わせて場所を整える"},
     {word:"moderate",meaning:"適度な",breakdown:"modus（ほどよさ）＋ ate（形容詞）→ ほどよいところにとどまる"},
     {word:"mode",meaning:"様式，モード",breakdown:"modus（ほどよさ）→ 物事の決まったやり方"},
     {synonym:true,word:"product",meaning:"製品",breakdown:"作られた品物。commodity は取引される原料や産物"}]},

  {id:1906,word:"dwell",partOfSpeech:"自動詞",meaning:"（ある場所に）住む，暮らす；くよくよ考える",
   meanings:["自|（ある場所に）住む，暮らす","自|（on ～を）くよくよ考える"],
   pronunciation:"/dwel/",part:191,
   example:"Many strange creatures dwell in the deep sea.",
   exampleJa:"深海には多くの奇妙な生き物が住んでいる。",
   example2:"Don't dwell on your mistakes; learn from them instead.",
   exampleJa2:"失敗をくよくよ考えるな。代わりにそこから学べ。",
   usage:["dwell in 場所（～に住む）","dwell on 事（～をくよくよ考える）"],
   etymologyProcess:"dwell（ぐずぐずとどまる）→ 1つの場所にとどまり続けると…？",
   etymologyConclusion:"dwell（ぐずぐずとどまる）→ 1つの場所に長くとどまって暮らす＝（ある場所に）住む",
   etymologyMore:["心が1つのことにとどまる→（on ～を）くよくよ考える"],
   hook:"live より硬い書き言葉。dwell on ～ の形では「～をくよくよ考える」になる。",
   relatedWords:[
     {word:"dweller",meaning:"住人",breakdown:"dwell（ぐずぐずとどまる）＋ er（人）→ そこに住みついている人"},
     {synonym:true,word:"live",meaning:"住む，生きる",breakdown:"ふつうの「住む」。dwell は硬い書き言葉"},
     {synonym:true,word:"reside",meaning:"居住する",breakdown:"re（後ろへ）＋ sid（座る）。公式な場面の「住む」"},
     {synonym:true,word:"stay",meaning:"滞在する",breakdown:"一時的にとどまる。dwell は長く暮らす"}]},

  {id:1907,word:"acoustic",partOfSpeech:"形容詞",meaning:"音響の，聴覚の",
   meanings:["形|音響の，聴覚の","形|（楽器が）電気を使わない，生音の","名|（acoustics で）音響効果"],
   pronunciation:"/əˈkuːstɪk/",part:191,
   example:"The new hall has special acoustic panels on its walls.",
   exampleJa:"新しいホールの壁には特別な音響用のパネルがある。",
   example2:"He played an acoustic guitar at the school festival.",
   exampleJa2:"彼は文化祭で生音のギターを弾いた。",
   etymologyProcess:"acous（聞く）＋ ic（～の）→ 耳で聞くことに関わるのは…？",
   etymologyConclusion:"acous（聞く）＋ ic（～の）→ 耳で聞く音の響きに関わる＝音響の",
   relatedWords:[
     {word:"acoustics",meaning:"音響効果",breakdown:"acous（聞く）＋ ic（名詞）→ 部屋での音の聞こえ方"},
     {synonym:true,word:"audio",meaning:"音声の",breakdown:"ラテン語 aud（聞く）から。acoustic はギリシャ語から"},
     {synonym:true,word:"sound",meaning:"音",breakdown:"音そのもの。acoustic は音の響き方に関わる"},
     {synonym:true,word:"hearing",meaning:"聴力",breakdown:"聞く力。acoustic は音を扱う側の話"}]},

  {id:1908,word:"recipe",partOfSpeech:"名詞",meaning:"（料理の）作り方，レシピ",
   meanings:["名|（料理の）作り方，レシピ","名|（for ～の）もと，秘訣"],
   pronunciation:"/ˈresəpi/",part:191,
   example:"My grandmother taught me her secret recipe for apple pie.",
   exampleJa:"祖母は私に、アップルパイの秘密の作り方を教えてくれた。",
   example2:"Staying up all night before a test is a recipe for failure.",
   exampleJa2:"テスト前に徹夜するのは失敗のもとだ。",
   usage:["a recipe for 物（～の作り方）","a recipe for 事（～を招くもと）"],
   etymologyProcess:"re（後ろへ）＋ cip（取る）→ 「これを取れ」と書いた紙は…？",
   etymologyConclusion:"re（後ろへ）＋ cip（取る）→ 「これを取れ」と材料を並べた指示書＝（料理の）作り方",
   why:"【なぜ】ラテン語 recipere（受け取る）の命令形 recipe は「取れ」。昔の医者は薬の処方を「Recipe（取れ）」と書き出してから材料を並べました。その書き出しの語が処方そのものを指し、やがて料理の作り方にも使われるようになりました。\n【つながり】receive（受け取る）や receipt（レシート）も同じ recipere から生まれた兄弟です。",
   etymologyMore:["こうすれば必ずそうなる手順→（for ～の）もと，秘訣"],
   relatedWords:[
     {word:"receive",meaning:"受け取る",breakdown:"re（後ろへ）＋ ceive（取る）→ 差し出された物を手元へ取る"},
     {word:"receipt",meaning:"レシート，領収書",breakdown:"re（後ろへ）＋ cept（取る）→ 代金を受け取った証の紙"},
     {word:"participate",meaning:"参加する",breakdown:"part（分ける）＋ cip（取る）→ 分けられた一部を受け持つ"},
     {synonym:true,word:"method",meaning:"方法",breakdown:"決まったやり方全般。recipe は材料と手順の書き付け"}]},

  {id:1909,word:"intake",partOfSpeech:"名詞",meaning:"（栄養などの）摂取量",
   meanings:["名|（栄養などの）摂取量","名|受け入れ人数","名|（空気・水の）取り入れ口"],
   pronunciation:"/ˈɪnteɪk/",part:191,
   example:"Doctors advise us to reduce our daily intake of sugar.",
   exampleJa:"医者は私たちに、1日の砂糖の摂取量を減らすよう勧めている。",
   example2:"The school's intake of new students grew this year.",
   exampleJa2:"その学校の新入生の受け入れ人数は今年増えた。",
   etymologyProcess:"in（中へ）＋ take（取る）→ 体の中へ取り入れる量は…？",
   etymologyConclusion:"in（中へ）＋ take（取る）→ 体の中へ取り入れた食べ物や栄養の量＝（栄養などの）摂取量",
   etymologyMore:["組織の中へ取り入れる人の数→受け入れ人数","空気や水を中へ取りこむ所→（空気・水の）取り入れ口"],
   relatedWords:[
     {word:"mistake",meaning:"まちがい",breakdown:"mis（誤って）＋ take（取る）→ ちがうものを取ってしまう"},
     {word:"overtake",meaning:"追い越す",breakdown:"over（越えて）＋ take（取る）→ 前の車を越えて先を取る"},
     {word:"take",meaning:"取る",breakdown:"take（取る）→ 手を伸ばしてつかみ取る"},
     {synonym:true,word:"consumption",meaning:"消費（量）",breakdown:"使ってなくす量。intake は体に取り入れる量"}]},

  {id:1910,word:"precede",partOfSpeech:"他動詞",meaning:"～より先に起こる，先行する",
   meanings:["他|～より先に起こる，先行する","他|（人の）前を行く"],
   pronunciation:"/prɪˈsiːd/",part:191,
   example:"A flash of lightning always precedes the sound of thunder.",
   exampleJa:"稲妻の光は、いつも雷の音より先に起こる。",
   example2:"The speech was preceded by a short video about our club.",
   exampleJa2:"スピーチに先立って、私たちの部についての短い動画が流れた。",
   etymologyProcess:"pre（先に）＋ ced（行く）→ ほかより先に行くと…？",
   etymologyConclusion:"pre（先に）＋ ced（行く）→ 時間や順番でほかより先に行く＝～より先に起こる",
   relatedWords:[
     {word:"proceed",meaning:"進む",breakdown:"pro（前へ）＋ ced（行く）→ 前へ向かって進んでいく"},
     {word:"access",meaning:"接近，利用",breakdown:"ad（～へ）＋ cess（行く）→ 目的の場所へ近づいていく"},
     {word:"exceed",meaning:"超える",breakdown:"ex（外へ）＋ ced（行く）→ 決まった線の外へ出ていく"},
     {word:"succeed",meaning:"あとを継ぐ；成功する",breakdown:"sub（下で）＋ ced（行く）→ 前の人のすぐ後に続いて行く"}]},

  {id:1911,word:"phase",partOfSpeech:"名詞",meaning:"（変化の）段階，局面",
   meanings:["名|（変化の）段階，局面","名|（月の）満ち欠けの相","他|（phase in/out で）段階的に導入［廃止］する"],
   pronunciation:"/feɪz/",part:192,
   example:"The building project has now entered its final phase.",
   exampleJa:"その建設計画は、いよいよ最後の段階に入った。",
   example2:"The moon goes through several phases every month.",
   exampleJa2:"月は毎月いくつかの満ち欠けの相を経ていく。",
   etymologyProcess:"phas（見せる）→ 月が日ごとに見せる姿は…？",
   etymologyConclusion:"phas（見せる）→ 変化の中でその時その時に見せる1つの姿＝（変化の）段階",
   why:"【なぜ】ギリシャ語 phasis は「現れ，見える姿」。もとは月や星が見せる形のことで、三日月・半月・満月と姿が移っていく様子を指しました。そこから、物事が移り変わっていく途中の「1つの段階」という意味に広がりました。\n【つながり】emphasize（強調する）は「中に見せる」、fantasy（ファンタジー）は「目に見せるもの」。どれも「見せる」の仲間です。",
   relatedWords:[
     {word:"emphasize",meaning:"強調する",breakdown:"em（中へ）＋ phas（見せる）→ はっきり目立つように見せる"},
     {word:"fantasy",meaning:"空想",breakdown:"phan（見せる）＋ y（名詞）→ 心の中に見せられる姿"},
     {word:"emphasis",meaning:"強調",breakdown:"em（中へ）＋ phas（見せる）→ 大事な点を目立たせること"},
     {synonym:true,word:"stage",meaning:"段階；舞台",breakdown:"進んでいく途中の一段。phase は移り変わる姿の1つ"}]},

  {id:1912,word:"priority",partOfSpeech:"名詞",meaning:"優先（事項）",
   meanings:["名|優先（事項），最も大事なこと","名|（over ～より）優先されること"],
   pronunciation:"/praɪˈɔːrəti/",part:192,
   example:"Safety is our top priority on every school trip.",
   exampleJa:"どの修学旅行でも、安全が私たちの最優先事項だ。",
   example2:"You should give priority to your health over your grades.",
   exampleJa2:"成績より健康を優先すべきだ。",
   usage:["give priority to 事（～を優先する）","take priority over 事（～より優先される）"],
   etymologyProcess:"pri（前の）＋ or（より～な）→ ほかより前に置くことは…？",
   etymologyConclusion:"pri（前の）＋ or（より～な）＋ ity（名詞）→ ほかより前に置いて先に扱うこと＝優先（事項）",
   relatedWords:[
     {word:"prior",meaning:"前の，先の",breakdown:"pri（前の）＋ or（より～な）→ ほかより前にある"},
     {word:"prime",meaning:"最も重要な",breakdown:"prim（第一の）→ いちばん前に来る"},
     {word:"primary",meaning:"主要な；初等の",breakdown:"prim（第一の）＋ ary（形容詞）→ 最初の段階の"},
     {synonym:true,word:"preference",meaning:"好み，優先",breakdown:"自分が好んで選ぶこと。priority は大事な順の先頭"}]},

  {id:1913,word:"premise",partOfSpeech:"名詞",meaning:"前提；（premises で）敷地",
   meanings:["名|前提","名|（premises で）敷地，構内"],
   pronunciation:"/ˈpremɪs/",part:192,
   example:"His whole argument is based on a false premise.",
   exampleJa:"彼の主張全体が、まちがった前提にもとづいている。",
   example2:"Smoking is not allowed anywhere on the school premises.",
   exampleJa2:"学校の敷地内では、どこでも喫煙は許されていない。",
   etymologyProcess:"pre（先に）＋ mis（送る）→ 話の先に送り出しておく考えは…？",
   etymologyConclusion:"pre（先に）＋ mis（送る）→ 結論より先に送り出して置いておく考え＝前提",
   etymologyMore:["証書の先頭で述べた家や土地→（premises で）敷地，構内"],
   relatedWords:[
     {word:"promise",meaning:"約束",breakdown:"pro（前へ）＋ mis（送る）→ 先に言葉を送り出しておく"},
     {word:"message",meaning:"伝言",breakdown:"mis（送る）＋ age（名詞）→ 相手へ送る言葉"},
     {word:"mission",meaning:"任務",breakdown:"mis（送る）＋ ion（名詞）→ 送り出されてやる仕事"},
     {synonym:true,word:"assumption",meaning:"思いこみ，仮定",breakdown:"確かめずに正しいとすること。premise は議論の土台"}]},

  {id:1914,word:"tomb",partOfSpeech:"名詞",meaning:"（大きな）墓，墓所",
   meanings:["名|（大きな）墓，墓所"],
   pronunciation:"/tuːm/",part:192,
   example:"Archaeologists found gold treasure inside the ancient tomb.",
   exampleJa:"考古学者たちは、古代の墓の中で金の財宝を発見した。",
   example2:"The tomb of the young pharaoh was found in 1922.",
   exampleJa2:"その若いファラオの墓は1922年に発見された。",
   etymologyProcess:"tomb（墓の塚）→ 土を盛り上げて作った場所は…？",
   etymologyConclusion:"tomb（墓の塚）→ 土や石を盛り上げて死者を納めた場所＝（大きな）墓",
   hook:"ギリシャ語の「塚」から。b は読まない。古墳やピラミッドのような大きな墓に使う。",
   relatedWords:[
     {word:"tombstone",meaning:"墓石",breakdown:"tomb（墓の塚）＋ stone（石）→ 墓に立てる石"},
     {synonym:true,word:"grave",meaning:"墓",breakdown:"地面を掘って埋めた墓。tomb は建物のような大きな墓"},
     {synonym:true,word:"cemetery",meaning:"共同墓地",breakdown:"たくさんの墓が集まった場所"},
     {synonym:true,word:"monument",meaning:"記念碑",breakdown:"人や出来事を記念して建てるもの"}]},

  {id:1915,word:"legend",partOfSpeech:"名詞",meaning:"伝説；伝説的人物",
   meanings:["名|伝説","名|（その道の）伝説的人物","名|（地図や図の）凡例"],
   pronunciation:"/ˈledʒənd/",part:192,
   example:"According to legend, a dragon once lived in this lake.",
   exampleJa:"伝説によると、かつてこの湖には竜が住んでいた。",
   example2:"That baseball player is a legend at our school.",
   exampleJa2:"あの野球選手は、私たちの学校では伝説的人物だ。",
   etymologyProcess:"lect（拾う・読む）→ 読み聞かせるべき昔の話は…？",
   etymologyConclusion:"lect（拾う・読む）→ 人々に読み聞かせて語り継がれた昔の話＝伝説",
   spelling:"lect→leg（ラテン語 legere の形のまま）",
   why:"【なぜ】ラテン語 legenda は「読まれるべきもの」。中世の修道院では、聖人の一生の物語を食事中に読み聞かせました。その物語は本当とも作り話ともつかない内容を含んでいたので、やがて「言い伝え，伝説」を指すようになりました。\n【つながり】lecture（講義）も「読み上げる」から。地図の「凡例」も「読むための説明」です。",
   etymologyMore:["語り継がれるほどの活躍をした人→（その道の）伝説的人物","地図を読むための説明書き→（地図や図の）凡例"],
   relatedWords:[
     {word:"lecture",meaning:"講義",breakdown:"lect（拾う・読む）＋ ure（名詞）→ 読み上げて教えること"},
     {word:"collect",meaning:"集める",breakdown:"com（共に）＋ lect（拾う）→ 1か所に拾い集める"},
     {word:"select",meaning:"選ぶ",breakdown:"se（離れて）＋ lect（拾う）→ 分けて拾い上げる"},
     {synonym:true,word:"myth",meaning:"神話",breakdown:"神々が出てくる話。legend は人や土地の言い伝え"}]},

  {id:1916,word:"masterpiece",partOfSpeech:"名詞",meaning:"傑作，名作",
   meanings:["名|傑作，名作"],
   pronunciation:"/ˈmæstərpiːs/",part:192,
   example:"The Mona Lisa is considered a masterpiece of Italian art.",
   exampleJa:"『モナ・リザ』はイタリア美術の傑作と考えられている。",
   example2:"Her short film was a small masterpiece that everyone loved.",
   exampleJa2:"彼女の短編映画は、みんなに愛された小さな名作だった。",
   etymologyProcess:"master（親方）＋ piece（一つの品）→ 親方になるための作品は…？",
   etymologyConclusion:"master（親方）＋ piece（一つの品）→ 一人前の親方と認められるほど見事な作品＝傑作",
   relatedWords:[
     {word:"master",meaning:"名人；習得する",breakdown:"master（親方）→ 技をきわめた人。技を身につける"},
     {word:"mister",meaning:"～さん（Mr.）",breakdown:"master（親方）→ 「親方」の呼びかけが軽くなった形"},
     {word:"piece",meaning:"1つ，1個",breakdown:"piece（一つの品）→ 全体から切り分けた1つ"},
     {synonym:true,word:"classic",meaning:"名作，古典",breakdown:"長く評価され続ける作品。masterpiece は出来ばえの最高さ"}]},

  {id:1917,word:"ritual",partOfSpeech:"名詞",meaning:"（宗教的な）儀式；お決まりの習慣",
   meanings:["名|（宗教的な）儀式","名|（決まって行う）習慣，お決まりの行動","形|儀式の"],
   pronunciation:"/ˈrɪtʃuəl/",part:192,
   example:"The priest performed an ancient ritual to bless the new temple.",
   exampleJa:"僧は新しい寺を清めるために、古くからの儀式を行った。",
   example2:"Stretching before practice has become a daily ritual for our team.",
   exampleJa2:"練習前のストレッチは、私たちのチームの毎日の習慣になった。",
   etymologyProcess:"rit（儀式）＋ al（～の）→ 決まった手順で行う儀式は…？",
   etymologyConclusion:"rit（儀式）＋ al（～の）→ 決まった手順どおりに行う神聖な式＝（宗教的な）儀式",
   etymologyMore:["同じ手順を毎回くり返す→（決まって行う）習慣，お決まりの行動"],
   relatedWords:[
     {word:"rite",meaning:"儀式，式典",breakdown:"rit（儀式）→ 決まった作法で行う式"},
     {synonym:true,word:"ceremony",meaning:"式典",breakdown:"入学式や結婚式などの式。ritual は手順の決まった儀式"},
     {synonym:true,word:"custom",meaning:"習慣，風習",breakdown:"社会で昔から続くならわし"},
     {synonym:true,word:"habit",meaning:"癖，習慣",breakdown:"個人の無意識の癖。ritual は意識して行う決まりごと"}]},

  {id:1918,word:"worship",partOfSpeech:"他動詞",meaning:"崇拝する，あがめる",
   meanings:["他|崇拝する，あがめる","名|礼拝，崇拝"],
   pronunciation:"/ˈwɜːrʃɪp/",part:192,
   example:"The ancient Egyptians worshiped the sun as a powerful god.",
   exampleJa:"古代エジプト人は、太陽を力強い神として崇拝した。",
   example2:"Many people visit places of worship on the weekend.",
   exampleJa2:"多くの人が週末に礼拝の場所を訪れる。",
   etymologyProcess:"worth（値打ち）＋ ship（名詞）→ この上ない値打ちを認めると…？",
   etymologyConclusion:"worth（値打ち）＋ ship（名詞）→ この上ない値打ちを認めて深く敬う＝崇拝する",
   etymologyMore:["神をあがめる集まり→礼拝，崇拝"],
   relatedWords:[
     {word:"worth",meaning:"価値がある",breakdown:"worth（値打ち）→ それだけの値打ちをもつ"},
     {word:"worthy",meaning:"ふさわしい",breakdown:"worth（値打ち）＋ y（形容詞）→ 値打ちに見合う"},
     {word:"friendship",meaning:"友情",breakdown:"friend（友）＋ ship（名詞）→ 友である状態"},
     {synonym:true,word:"respect",meaning:"尊敬する",breakdown:"人を立派だと敬う。worship は神のようにあがめる"}]},

  {id:1919,word:"doctrine",partOfSpeech:"名詞",meaning:"（宗教の）教義；主義",
   meanings:["名|（宗教の）教義","名|（政治上の）主義，原則"],
   pronunciation:"/ˈdɑːktrɪn/",part:192,
   example:"The monks studied the doctrine of their religion every day.",
   exampleJa:"僧たちは毎日、自分たちの宗教の教義を学んだ。",
   example2:"The Monroe Doctrine was announced by the United States in 1823.",
   exampleJa2:"モンロー主義は1823年にアメリカ合衆国によって発表された。",
   etymologyProcess:"doc（教える）＋ ine（もの）→ 教えとして伝えられるものは…？",
   etymologyConclusion:"doc（教える）＋ ine（もの）→ 信じる人たちに教えとして伝えられる考え＝（宗教の）教義",
   etymologyMore:["国が守るべき教えとして掲げる考え→（政治上の）主義，原則"],
   relatedWords:[
     {word:"doctor",meaning:"医者；博士",breakdown:"doc（教える）＋ or（人）→ 学問を教えられるほどの人"},
     {word:"document",meaning:"文書",breakdown:"doc（教える）＋ ment（名詞）→ 事実を教える証拠の書き物"},
     {word:"documentary",meaning:"記録映画",breakdown:"doc（教える）＋ ment（名詞）＋ ary（形容詞）→ 事実を伝える作品"},
     {synonym:true,word:"belief",meaning:"信念，信仰",breakdown:"個人が信じていること。doctrine は集団の公式の教え"}]},

  {id:1920,word:"legacy",partOfSpeech:"名詞",meaning:"（後世に残された）遺産，遺したもの",
   meanings:["名|（後世に残された）遺産，遺したもの","名|（遺言による）遺産"],
   pronunciation:"/ˈleɡəsi/",part:192,
   example:"The great scientist left a legacy of important discoveries.",
   exampleJa:"その偉大な科学者は、重要な発見という遺産を残した。",
   example2:"The coach's legacy lives on in the players he trained.",
   exampleJa2:"そのコーチが遺したものは、彼が育てた選手たちの中に生き続けている。",
   etymologyProcess:"leg（任じる）＋ acy（名詞）→ 死後に託して残すものは…？",
   etymologyConclusion:"leg（任じる）＋ acy（名詞）→ 後の人に託して残していくもの＝（後世に残された）遺産",
   why:"【なぜ】ラテン語 legare は「任命して送り出す」と「遺言で託す」の両方の意味をもちました。遺言で財産を託すことから legacy は「遺産」になり、今ではお金に限らず、業績や影響など「後の世に残したもの」全般に使われます。\n【つながり】delegate（代表者）は「任じて送り出された人」。colleague（同僚）も同じ語根です。",
   relatedWords:[
     {word:"delegate",meaning:"代表者",breakdown:"de（離れて）＋ leg（任じる）→ 任されて送り出された人"},
     {word:"colleague",meaning:"同僚",breakdown:"com（共に）＋ leg（任じる）→ 同じ役目を任された仲間"},
     {word:"college",meaning:"大学",breakdown:"com（共に）＋ leg（任じる）→ 同じ務めをもつ人の集まり"},
     {synonym:true,word:"heritage",meaning:"遺産",breakdown:"国や民族が受け継ぐ文化。legacy は個人が残したもの"}]},

  {id:1921,word:"sin",partOfSpeech:"名詞",meaning:"（宗教・道徳上の）罪",
   meanings:["名|（宗教・道徳上の）罪","名|（口語で）いけないこと，罰当たりなこと"],
   pronunciation:"/sɪn/",part:193,
   example:"Many religions teach that telling lies is a sin.",
   exampleJa:"多くの宗教は、うそをつくことは罪だと教えている。",
   example2:"It would be a sin to waste such delicious food.",
   exampleJa2:"こんなにおいしい食べ物をむだにするのは罰当たりなことだ。",
   etymologyProcess:"synn（罪）→ 神の教えにそむく行いは…？",
   etymologyConclusion:"synn（罪）→ 神の教えや道徳にそむく悪い行い＝（宗教・道徳上の）罪",
   spelling:"synn→sin（古英語の形から縮まった）",
   hook:"crime は法律を破る罪、sin は神や良心にそむく罪。区別して覚える。",
   relatedWords:[
     {word:"sinful",meaning:"罪深い",breakdown:"synn（罪）＋ ful（満ちた）→ 罪でいっぱいの"},
     {word:"sinner",meaning:"罪人",breakdown:"synn（罪）＋ er（人）→ 神にそむく罪を犯した人"},
     {synonym:true,word:"crime",meaning:"犯罪",breakdown:"法律を破る罪。sin は宗教や道徳の罪"},
     {synonym:true,word:"evil",meaning:"悪",breakdown:"悪いこと全般。sin は1つ1つの罪の行い"}]},

  {id:1922,word:"swear",partOfSpeech:"他動詞・自動詞",meaning:"誓う；ののしる",
   meanings:["他|誓う，宣誓する","自|（at ～を）ののしる，悪態をつく"],
   pronunciation:"/swer/",part:193,
   example:"I swear I will never tell anyone your secret.",
   exampleJa:"君の秘密は絶対にだれにも言わないと誓うよ。",
   example2:"The angry player began to swear at the referee.",
   exampleJa2:"怒った選手は審判をののしり始めた。",
   usage:["swear to do（～すると誓う）","swear at 人（～をののしる）"],
   etymologyProcess:"swear（誓いを立てる）→ 神にかけて言いきると…？",
   etymologyConclusion:"swear（誓いを立てる）→ 神の名にかけて本当だと言いきる＝誓う",
   etymologyMore:["神の名をむやみに口にする→（at ～を）ののしる，悪態をつく"],
   relatedWords:[
     {word:"answer",meaning:"答える",breakdown:"and（～に対して）＋ swear（誓いを立てる）→ 相手に向けて言い返す"},
     {synonym:true,word:"promise",meaning:"約束する",breakdown:"ふつうの約束。swear は神にかけて強く誓う"},
     {synonym:true,word:"vow",meaning:"誓う",breakdown:"心に固く誓う。swear は口に出して言いきる"},
     {synonym:true,word:"curse",meaning:"ののしる，呪う",breakdown:"不幸を願う言葉を投げる。swear at はきたない言葉"}]},

  {id:1923,word:"confess",partOfSpeech:"他動詞・自動詞",meaning:"白状する，打ち明ける",
   meanings:["他|白状する，打ち明ける","自|（to ～を）認める","他|（神に罪を）告白する"],
   pronunciation:"/kənˈfes/",part:193,
   example:"He finally confessed that he had broken the window.",
   exampleJa:"彼はとうとう、窓を割ったのは自分だと白状した。",
   example2:"I must confess I have never read this famous book.",
   exampleJa2:"正直に打ち明けると、私はこの有名な本を読んだことがない。",
   usage:["confess that SV（～だと白状する）","confess to 事（～を認める）"],
   etymologyProcess:"con（すっかり）＋ fess（告げる）→ 隠していたことを全部告げると…？",
   etymologyConclusion:"con（すっかり）＋ fess（告げる）→ 隠していたことをすっかり告げる＝白状する",
   relatedWords:[
     {word:"profession",meaning:"職業",breakdown:"pro（人前で）＋ fess（告げる）→ 人前で名乗る仕事"},
     {word:"professor",meaning:"教授",breakdown:"pro（人前で）＋ fess（告げる）＋ or（人）→ 人前で教えを述べる人"},
     {word:"confession",meaning:"告白",breakdown:"con（すっかり）＋ fess（告げる）＋ ion（名詞）→ 全部打ち明けること"},
     {synonym:true,word:"admit",meaning:"認める",breakdown:"事実を認める。confess は隠していた罪などを打ち明ける"}]},

  {id:1924,word:"carve",partOfSpeech:"他動詞",meaning:"彫る，刻む；（肉を）切り分ける",
   meanings:["他|彫る，刻む","他|（肉を）切り分ける","他|（道・地位を）切り開く"],
   pronunciation:"/kɑːrv/",part:193,
   example:"He carved his name into the old wooden desk.",
   exampleJa:"彼は古い木の机に自分の名前を彫った。",
   example2:"My father will carve the turkey at the dinner table.",
   exampleJa2:"父が夕食の席で七面鳥を切り分ける予定だ。",
   etymologyProcess:"carve（切りこむ）→ 刃物で少しずつ切りこむと…？",
   etymologyConclusion:"carve（切りこむ）→ 刃物で少しずつ切りこんで形や文字を作る＝彫る",
   etymologyMore:["刃物で切りこんで分ける→（肉を）切り分ける","障害を切りこんで進む→（道・地位を）切り開く"],
   hook:"ハロウィーンのかぼちゃも carve する。ナイフで削りながら形を作る動き。",
   relatedWords:[
     {word:"carving",meaning:"彫刻品",breakdown:"carve（切りこむ）＋ ing（名詞）→ 刃物で彫って作った物"},
     {synonym:true,word:"cut",meaning:"切る",breakdown:"切ること全般。carve は形を作るように切る"},
     {synonym:true,word:"engrave",meaning:"（文字を）刻む",breakdown:"硬い表面に細い線を刻む。carve は深く彫る"},
     {synonym:true,word:"slice",meaning:"薄く切る",breakdown:"パンなどを薄く切る。carve は大きな肉を切り分ける"}]},

  {id:1925,word:"murmur",partOfSpeech:"他動詞・自動詞",meaning:"つぶやく，小声で言う",
   meanings:["他|つぶやく，小声で言う","名|ささやき，（川や風の）さらさらいう音","名|（不満の）ぶつぶつ言う声"],
   pronunciation:"/ˈmɜːrmər/",part:193,
   example:"She murmured a quiet thank-you and left the room.",
   exampleJa:"彼女は小声でお礼をつぶやいて、部屋を出ていった。",
   example2:"We could hear the gentle murmur of the stream at night.",
   exampleJa2:"夜には小川のさらさらいう音が聞こえた。",
   etymologyProcess:"murmur（ざわざわという音）→ 低い声がもれ続けると…？",
   etymologyConclusion:"murmur（ざわざわという音）→ 低くはっきりしない声をもらし続ける＝つぶやく",
   etymologyMore:["低く続く音→ささやき，（川や風の）さらさらいう音","低い声で文句を言う→（不満の）ぶつぶつ言う声"],
   hook:"「ムルムル」という低い音をまねた語。同じ音を2回くり返して、続く感じを出している。",
   relatedWords:[
     {synonym:true,word:"whisper",meaning:"ささやく",breakdown:"息だけで相手に話す。murmur は低い声で独り言のように"},
     {synonym:true,word:"mutter",meaning:"ぶつぶつ言う",breakdown:"不満げに小声で言う。これも音から生まれた語"},
     {synonym:true,word:"mumble",meaning:"もぐもぐ言う",breakdown:"口をはっきり開けずに話す"},
     {word:"murmuring",meaning:"さざめき",breakdown:"murmur（ざわざわという音）＋ ing（名詞）→ 低く続く音"}]},

  {id:1926,word:"verbal",partOfSpeech:"形容詞",meaning:"言葉による；口頭の",
   meanings:["形|言葉による","形|口頭の","形|動詞の"],
   pronunciation:"/ˈvɜːrbl/",part:193,
   example:"Verbal bullying can hurt as much as physical violence.",
   exampleJa:"言葉によるいじめは、身体的な暴力と同じくらい人を傷つけることがある。",
   example2:"We made a verbal agreement, but nothing was written down.",
   exampleJa2:"私たちは口頭の約束をしたが、何も書き残されなかった。",
   etymologyProcess:"verb（言葉）＋ al（～の）→ 言葉を使って行うことは…？",
   etymologyConclusion:"verb（言葉）＋ al（～の）→ 手や力でなく言葉を使って行う＝言葉による",
   etymologyMore:["文字でなく口から出す言葉で→口頭の","文の中心となる「言葉」の品詞→動詞の"],
   relatedWords:[
     {word:"verb",meaning:"動詞",breakdown:"verb（言葉）→ 文の中心になる大事な言葉"},
     {word:"proverb",meaning:"ことわざ",breakdown:"pro（人前で）＋ verb（言葉）→ 人前で広く言われる言葉"},
     {word:"adverb",meaning:"副詞",breakdown:"ad（～へ）＋ verb（言葉）→ 動詞に添える言葉"},
     {synonym:true,word:"spoken",meaning:"話し言葉の",breakdown:"口で話される。verbal は言葉を使うこと全般"}]},

  {id:1927,word:"oral",partOfSpeech:"形容詞",meaning:"口頭の，口述の；口の",
   meanings:["形|口頭の，口述の","形|口の，口から入る"],
   pronunciation:"/ˈɔːrəl/",part:193,
   example:"We have an oral test in English class tomorrow.",
   exampleJa:"明日、英語の授業で口頭試験がある。",
   example2:"Brushing your teeth well is important for good oral health.",
   exampleJa2:"歯をよく磨くことは、口の健康のために大切だ。",
   etymologyProcess:"os（口）＋ al（～の）→ 口を使って行うことは…？",
   etymologyConclusion:"os（口）＋ al（～の）→ 書かずに口で言って伝える＝口頭の",
   spelling:"os→or（ラテン語 oris の形から）",
   etymologyMore:["口そのものに関わる→口の，口から入る"],
   relatedWords:[
     {word:"orally",meaning:"口頭で；口から",breakdown:"os（口）＋ al（～の）＋ ly（副詞）→ 口を使って"},
     {synonym:true,word:"spoken",meaning:"話し言葉の",breakdown:"口で話される言葉。oral は試験や発表でよく使う"},
     {synonym:true,word:"verbal",meaning:"言葉による",breakdown:"言葉を使うこと。oral は特に口で言うこと"},
     {synonym:true,word:"mouth",meaning:"口",breakdown:"ふつうの「口」。oral はその形容詞として使う"}]},

  {id:1928,word:"eloquent",partOfSpeech:"形容詞",meaning:"雄弁な，説得力のある",
   meanings:["形|雄弁な，説得力のある","形|（表情などが）多くを物語る"],
   pronunciation:"/ˈeləkwənt/",part:193,
   example:"She gave an eloquent speech about protecting the environment.",
   exampleJa:"彼女は環境保護について雄弁なスピーチをした。",
   example2:"His silence was more eloquent than any words could be.",
   exampleJa2:"彼の沈黙は、どんな言葉よりも多くを物語っていた。",
   etymologyProcess:"e（外へ）＋ loqu（話す）→ 言葉を外へどんどん出せる人は…？",
   etymologyConclusion:"e（外へ）＋ loqu（話す）＋ ent（形容詞）→ 思いを言葉にして見事に外へ話し出す＝雄弁な",
   etymologyMore:["言葉がなくても思いを外へ伝える→（表情などが）多くを物語る"],
   relatedWords:[
     {word:"eloquence",meaning:"雄弁",breakdown:"e（外へ）＋ loqu（話す）＋ ence（名詞）→ 見事に話す力"},
     {word:"colloquial",meaning:"話し言葉の",breakdown:"com（共に）＋ loqu（話す）→ 仲間どうしで話す言葉の"},
     {synonym:true,word:"fluent",meaning:"流ちょうな",breakdown:"言葉がすらすら流れ出る。eloquent は人の心を動かす"},
     {synonym:true,word:"persuasive",meaning:"説得力のある",breakdown:"相手をその気にさせる。eloquent は話し方の見事さ"}]},

  {id:1929,word:"linguistic",partOfSpeech:"形容詞",meaning:"言語の，言語学の",
   meanings:["形|言語の，言葉の","形|言語学の"],
   pronunciation:"/lɪŋˈɡwɪstɪk/",part:193,
   example:"Young children have amazing linguistic abilities that adults often lack.",
   exampleJa:"幼い子どもは、大人にはないことが多い驚くべき言語の能力をもっている。",
   example2:"Our class studied the linguistic differences between British and American English.",
   exampleJa2:"私たちのクラスは、イギリス英語とアメリカ英語の言語上の違いを学んだ。",
   etymologyProcess:"lingu（舌）＋ istic（形容詞）→ 舌を動かして話す言葉に関わるのは…？",
   etymologyConclusion:"lingu（舌）＋ istic（形容詞）→ 舌を動かして話す言葉に関わる＝言語の",
   relatedWords:[
     {word:"language",meaning:"言語",breakdown:"lingu（舌）＋ age（名詞）→ 舌を使って話すもの"},
     {word:"bilingual",meaning:"2か国語を話す",breakdown:"bi（2つ）＋ lingu（舌）→ 2つの舌をもつ"},
     {word:"linguist",meaning:"言語学者",breakdown:"lingu（舌）＋ ist（人）→ 言葉を研究する人"},
     {synonym:true,word:"verbal",meaning:"言葉による",breakdown:"言葉を使うこと。linguistic は言語のしくみに関わる"}]},

  {id:1930,word:"metaphor",partOfSpeech:"名詞",meaning:"隠喩，たとえ",
   meanings:["名|隠喩，たとえ","名|（for ～の）象徴"],
   pronunciation:"/ˈmetəfɔːr/",part:193,
   example:"The poet uses the sea as a metaphor for life.",
   exampleJa:"その詩人は海を人生の隠喩として使っている。",
   example2:"Our teacher explained the metaphor in the poem to us.",
   exampleJa2:"先生は私たちに、その詩の中のたとえを説明してくれた。",
   etymologyProcess:"metaphora（別の物へ運ぶ）→ 言葉を別の物事へ運ぶと…？",
   etymologyConclusion:"metaphora（別の物へ運ぶ）→ 言葉を別の物事へ運んで重ねて言う＝隠喩",
   why:"【なぜ】ギリシャ語 metapherein は「向こうへ運ぶ」。ある物事を表す言葉を、別の物事へ運んで使うことです。「人生は旅だ」と言えば、旅の言葉が人生へ運ばれています。「～のような」を使わずに重ねるので、日本語では「隠喩」と呼びます。\n【つながり】「～のような」を使うたとえは simile（直喩）。ラテン語の fer（運ぶ）とは遠い親戚です。",
   etymologyMore:["別の物事に重ねて表す→（for ～の）象徴"],
   relatedWords:[
     {word:"metaphorical",meaning:"比喩的な",breakdown:"metaphora（別の物へ運ぶ）＋ ical（形容詞）→ たとえを使った"},
     {synonym:true,word:"simile",meaning:"直喩",breakdown:"like や as を使うたとえ。metaphor は使わずに重ねる"},
     {synonym:true,word:"comparison",meaning:"比較，たとえ",breakdown:"2つを並べて比べること"},
     {synonym:true,word:"symbol",meaning:"象徴",breakdown:"形あるもので考えを表す。鳩は平和の symbol"}]},

  {id:1931,word:"prose",partOfSpeech:"名詞",meaning:"散文",
   meanings:["名|散文","名|文章，文体"],
   pronunciation:"/proʊz/",part:194,
   example:"The novel is written in simple but beautiful prose.",
   exampleJa:"その小説は、簡潔だが美しい散文で書かれている。",
   example2:"Our homework is to rewrite the old poem in modern prose.",
   exampleJa2:"宿題は、その古い詩を現代の散文に書き直すことだ。",
   etymologyProcess:"pro（前へ）＋ vers（回る）→ 折り返さずまっすぐ前へ進む文は…？",
   etymologyConclusion:"pro（前へ）＋ vers（回る）→ 行を折り返さず、まっすぐ前へ書き進める文＝散文",
   spelling:"pro＋vers→pros（縮まった）",
   why:"【なぜ】ラテン語 prosa oratio は「まっすぐ前を向いた話し方」。一方の詩 verse は、畑を耕す牛が端で向きを「回る」ように、決まった長さで行を折り返します。折り返さずに前へ前へと書き進める、ふつうの文章が prose です。\n【つながり】verse（詩の一行）、reverse（逆にする）、universe（宇宙）も「回る」の仲間です。",
   relatedWords:[
     {word:"verse",meaning:"詩，韻文",breakdown:"vers（回る）→ 決まった所で行が折り返す文"},
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ 後ろ向きに回す"},
     {word:"universe",meaning:"宇宙",breakdown:"uni（1つ）＋ vers（回る）→ 1つにまとまって回る全体"},
     {synonym:true,word:"poetry",meaning:"詩",breakdown:"リズムや行分けのある文。prose はふつうの文章"}]},

  {id:1932,word:"narrative",partOfSpeech:"名詞",meaning:"（出来事の）語り，話",
   meanings:["名|（出来事の）語り，話","形|物語の，物語風の"],
   pronunciation:"/ˈnærətɪv/",part:194,
   example:"The book gives a moving narrative of a boy's long journey.",
   exampleJa:"その本は、ある少年の長い旅の感動的な語りを伝えている。",
   example2:"Write a short narrative essay about your summer vacation.",
   exampleJa2:"夏休みについての短い物語風の作文を書きなさい。",
   etymologyProcess:"narr（語る）＋ ive（形容詞）→ 起きたことを順に語ると…？",
   etymologyConclusion:"narr（語る）＋ ive（形容詞）→ 起きた出来事を順を追って語ったもの＝（出来事の）語り",
   relatedWords:[
     {word:"narrator",meaning:"語り手，ナレーター",breakdown:"narr（語る）＋ or（人）→ 物語を語って聞かせる人"},
     {word:"narrate",meaning:"語る，ナレーションをする",breakdown:"narr（語る）＋ ate（動詞）→ 出来事を順に話す"},
     {synonym:true,word:"story",meaning:"物語，話",breakdown:"ふつうの「話」。narrative は語り方や構成も含む"},
     {synonym:true,word:"tale",meaning:"物語",breakdown:"語り継がれる話。narrative は出来事の語り"}]},

  {id:1933,word:"plot",partOfSpeech:"名詞",meaning:"（小説・映画の）筋；陰謀",
   meanings:["名|（小説・映画の）筋","名|陰謀，たくらみ","名|（小さな）区画の土地","他|たくらむ"],
   pronunciation:"/plɑːt/",part:194,
   example:"The plot of this movie was too hard to follow.",
   exampleJa:"この映画の筋は、ついていくのが難しすぎた。",
   example2:"The police discovered a plot to steal the famous painting.",
   exampleJa2:"警察は、その有名な絵を盗む陰謀を見つけた。",
   etymologyProcess:"plot（小さな土地）→ 区画を図に描き分けると…？",
   etymologyConclusion:"plot（小さな土地）→ 区画の図面のように、話の流れを描いた設計図＝（小説・映画の）筋",
   hook:"語源ははっきりしないが「区画→図面→筋書き」と広がったとされる。隠れた筋書きが陰謀。",
   relatedWords:[
     {synonym:true,word:"story",meaning:"物語，話",breakdown:"話そのもの。plot は話の出来事の組み立て"},
     {synonym:true,word:"scheme",meaning:"計画，たくらみ",breakdown:"入念な計画。悪い計画にも使う"},
     {synonym:true,word:"conspiracy",meaning:"共謀，陰謀",breakdown:"何人かで悪事を企てること"},
     {synonym:true,word:"plan",meaning:"計画",breakdown:"ふつうの計画。plot は秘密の悪い計画"}]},

  {id:1934,word:"draft",partOfSpeech:"名詞",meaning:"下書き，草稿",
   meanings:["名|下書き，草稿","他|下書きする，起草する","名|（the draft で）徴兵","名|すきま風"],
   pronunciation:"/dræft/",part:194,
   example:"I wrote the first draft of my essay last night.",
   exampleJa:"私は昨夜、作文の最初の下書きを書いた。",
   example2:"The student council drafted a new plan for the festival.",
   exampleJa2:"生徒会は文化祭の新しい計画を起草した。",
   etymologyProcess:"draw（引っぱる）→ ペンで線を引いてざっと描くと…？",
   etymologyConclusion:"draw（引っぱる）→ ペンで線を引いておおまかに書いたもの＝下書き",
   spelling:"draw→draf（古い綴り draught を経て変化）",
   why:"【なぜ】draft は draw（引く）の古い名詞形 draught から来ています。「線を引く」ことから「ざっと描いた図」＝下書き。「名簿から人を引き抜く」ことから「徴兵」。「空気が引きこまれて流れる」ことから「すきま風」。どれも「引く」の動きです。\n【つながり】drawer（引き出し）や drawing（線画）も draw の仲間です。",
   relatedWords:[
     {word:"draw",meaning:"描く；引く",breakdown:"draw（引っぱる）→ ペンを引いて線を描く"},
     {word:"drawer",meaning:"引き出し",breakdown:"draw（引っぱる）＋ er（もの）→ 手前へ引き出す箱"},
     {word:"drawing",meaning:"線画，スケッチ",breakdown:"draw（引っぱる）＋ ing（名詞）→ 線を引いて描いた絵"},
     {synonym:true,word:"sketch",meaning:"スケッチ",breakdown:"ざっと描いた絵。draft は文章や計画の下書き"}]},

  {id:1935,word:"manuscript",partOfSpeech:"名詞",meaning:"原稿；写本",
   meanings:["名|（手書き・タイプの）原稿","名|（印刷以前の手書きの）写本"],
   pronunciation:"/ˈmænjuskrɪpt/",part:194,
   example:"The author sent her manuscript to three different publishers.",
   exampleJa:"その作家は、自分の原稿を3つの出版社に送った。",
   example2:"Before printing, monks copied old manuscripts by hand.",
   exampleJa2:"印刷技術ができる前、修道士たちは古い写本を手で書き写した。",
   etymologyProcess:"manu（手）＋ script（書く）→ 手で書いたものは…？",
   etymologyConclusion:"manu（手）＋ script（書く）→ 印刷する前の、手で書いた文章＝原稿",
   etymologyMore:["印刷がない時代に手で写した本→（印刷以前の手書きの）写本"],
   relatedWords:[
     {word:"manual",meaning:"手動の；説明書",breakdown:"manu（手）＋ al（～の）→ 手を使う。手元に置く本"},
     {word:"manufacture",meaning:"製造する",breakdown:"manu（手）＋ fac（作る）→ もとは手で作ること"},
     {word:"describe",meaning:"描写する",breakdown:"de（下へ）＋ scrib（書く）→ 見たままを書き写す"},
     {word:"script",meaning:"台本",breakdown:"script（書く）→ せりふを書いたもの"}]},

  {id:1936,word:"paradox",partOfSpeech:"名詞",meaning:"逆説；矛盾したこと",
   meanings:["名|逆説","名|矛盾したこと［人］"],
   pronunciation:"/ˈpærədɑːks/",part:194,
   example:"It is a paradox that the more we rush, the slower we become.",
   exampleJa:"急げば急ぐほど遅くなるというのは逆説だ。",
   example2:"It's a strange paradox that I sometimes feel lonely in a crowd.",
   exampleJa2:"人ごみの中でときどき孤独を感じるのは、奇妙な逆説だ。",
   etymologyProcess:"para（そばで）＋ dox（考え）→ ふつうの考えのわきへそれると…？",
   etymologyConclusion:"para（そばで）＋ dox（考え）→ 常識の考えのわきへそれるが、実は真実を含む説＝逆説",
   why:"【なぜ】ギリシャ語 paradoxos は「世間の考え（doxa）のそばを通り過ぎた」＝予想の外にある、という意味。一見まちがっているようで、よく考えると正しいことを言う説が「逆説」です。「急がば回れ」はその典型です。\n【つながり】orthodox（正統の）は「正しい考え」。paragraph（段落）は「そばに書きこむ印」から来ています。",
   relatedWords:[
     {word:"orthodox",meaning:"正統の",breakdown:"ortho（正しい）＋ dox（考え）→ 正しいと認められた考えの"},
     {word:"paragraph",meaning:"段落",breakdown:"para（そばで）＋ graph（書く）→ 区切りのそばに書いた印から"},
     {word:"parallel",meaning:"平行の",breakdown:"para（そばで）＋ allel（互いに）→ 互いにそばを並んで進む"},
     {synonym:true,word:"contradiction",meaning:"矛盾",breakdown:"2つの話が食い違うこと。paradox は矛盾に見えて真実"}]},

  {id:1937,word:"slang",partOfSpeech:"名詞",meaning:"俗語，スラング",
   meanings:["名|俗語，スラング","名|（仲間内の）隠語"],
   pronunciation:"/slæŋ/",part:194,
   example:"Teenagers often use slang that their parents cannot understand.",
   exampleJa:"十代の若者は、親には理解できない俗語をよく使う。",
   example2:"The word was once slang, but now everyone uses it.",
   exampleJa2:"その語はかつては俗語だったが、今ではだれもが使う。",
   etymologyProcess:"slang（隠語）→ 仲間内だけで通じるくだけた言葉は…？",
   etymologyConclusion:"slang（隠語）→ 仲間内で通じる、くだけた言葉づかい＝俗語",
   hook:"18世紀の泥棒仲間の隠語から広まったとされるが、語源ははっきりしない。数えない名詞。",
   relatedWords:[
     {word:"slangy",meaning:"俗語っぽい",breakdown:"slang（隠語）＋ y（形容詞）→ くだけた言い方の多い"},
     {synonym:true,word:"jargon",meaning:"専門用語",breakdown:"ある仕事の仲間だけに通じる言葉"},
     {synonym:true,word:"dialect",meaning:"方言",breakdown:"地域ごとの言葉。slang は世代や仲間ごと"},
     {synonym:true,word:"idiom",meaning:"慣用句",breakdown:"決まった言い回し。slang はくだけた流行語"}]},

  {id:1938,word:"riddle",partOfSpeech:"名詞",meaning:"なぞなぞ；なぞ",
   meanings:["名|なぞなぞ","名|なぞ，不可解なこと"],
   pronunciation:"/ˈrɪdl/",part:194,
   example:"My little brother loves to ask me riddles at dinner.",
   exampleJa:"弟は夕食のときに、私になぞなぞを出すのが大好きだ。",
   example2:"Why the ship disappeared remains a riddle to this day.",
   exampleJa2:"その船がなぜ消えたのかは、今日までなぞのままだ。",
   etymologyProcess:"read（読み解く）→ 読み解いて答えを当てる問いは…？",
   etymologyConclusion:"read（読み解く）→ 言葉の意味を読み解いて答えを当てる問い＝なぞなぞ",
   spelling:"read→rid（古英語 rǣdels から変化）",
   etymologyMore:["答えが読み解けないままの事柄→なぞ，不可解なこと"],
   hook:"read（読む）と同じ家族。「なぞなぞを出す」は ask a riddle、「解く」は solve a riddle。",
   relatedWords:[
     {word:"read",meaning:"読む",breakdown:"read（読み解く）→ 書かれた文字の意味を読み取る"},
     {synonym:true,word:"puzzle",meaning:"パズル，難問",breakdown:"頭を使って解く問題。riddle は言葉遊びの問い"},
     {synonym:true,word:"mystery",meaning:"なぞ，神秘",breakdown:"説明のつかない不思議なこと"},
     {synonym:true,word:"quiz",meaning:"小テスト，クイズ",breakdown:"知識を問う問題。riddle はひねった問い"}]},

  {id:1939,word:"exhibit",partOfSpeech:"他動詞",meaning:"（作品を）展示する，出品する",
   meanings:["他|（作品を）展示する，出品する","他|（感情・性質を）示す","名|展示品"],
   pronunciation:"/ɪɡˈzɪbɪt/",part:194,
   example:"The museum will exhibit paintings by young local artists.",
   exampleJa:"その美術館は、地元の若い画家の絵を展示する予定だ。",
   example2:"The patient exhibited clear signs of a high fever.",
   exampleJa2:"その患者は、高熱のはっきりした兆候を示していた。",
   etymologyProcess:"ex（外へ）＋ hibit（持つ）→ 持っている物を外へ差し出すと…？",
   etymologyConclusion:"ex（外へ）＋ hibit（持つ）→ 持っている作品を人の前へ差し出して見せる＝（作品を）展示する",
   etymologyMore:["内にあるものを外へ見せる→（感情・性質を）示す"],
   relatedWords:[
     {word:"exhibition",meaning:"展覧会",breakdown:"ex（外へ）＋ hibit（持つ）＋ ion（名詞）→ 作品を並べて見せる会"},
     {word:"prohibit",meaning:"禁止する",breakdown:"pro（前に）＋ hibit（持つ）→ 前に立ちはだかって止める"},
     {word:"habit",meaning:"習慣，癖",breakdown:"habit（持ち続ける）→ 身に持ち続けているやり方"},
     {synonym:true,word:"display",meaning:"展示する",breakdown:"広げて見せる。exhibit は展覧会などで公開する"}]},

  {id:1940,word:"portray",partOfSpeech:"他動詞",meaning:"（絵・文章で）描き出す；（役を）演じる",
   meanings:["他|（絵・文章で）描き出す，描写する","他|（役を）演じる","他|（as ～として）描く"],
   pronunciation:"/pɔːrˈtreɪ/",part:194,
   example:"The painting portrays a young woman reading a letter.",
   exampleJa:"その絵は、手紙を読む若い女性を描き出している。",
   example2:"In the movie, he portrays a famous scientist.",
   exampleJa2:"その映画で、彼は有名な科学者を演じている。",
   usage:["portray A as B（AをBとして描く）"],
   etymologyProcess:"pro（前へ）＋ tract（引く）→ 姿を前へ引き出すと…？",
   etymologyConclusion:"pro（前へ）＋ tract（引く）→ 人や物の姿を線で前へ引き出す＝（絵・文章で）描き出す",
   spelling:"pro→por、tract→tray（フランス語を通って変化）",
   etymologyMore:["人物の姿を舞台や画面に描き出す→（役を）演じる"],
   relatedWords:[
     {word:"portrait",meaning:"肖像画",breakdown:"pro（前へ）＋ tract（引く）→ 人の姿を引き出して描いた絵"},
     {word:"attract",meaning:"引きつける",breakdown:"ad（～へ）＋ tract（引く）→ 自分のほうへ引き寄せる"},
     {word:"tractor",meaning:"トラクター",breakdown:"tract（引く）＋ or（もの）→ 重い農機具を引っぱる車"},
     {synonym:true,word:"depict",meaning:"描く",breakdown:"de（下へ）＋ pict（描く）。絵や言葉で細かく表す"}]},

  {id:1941,word:"depict",partOfSpeech:"他動詞",meaning:"（絵や言葉で）描く，表す",
   meanings:["他|（絵や言葉で）描く，表す","他|（as ～として）描く"],
   pronunciation:"/dɪˈpɪkt/",part:195,
   example:"The film depicts daily life in a small fishing village.",
   exampleJa:"その映画は、小さな漁村の日々の暮らしを描いている。",
   example2:"In this picture, the artist depicted his own family at dinner.",
   exampleJa2:"この絵の中で、画家は夕食をとる自分の家族を描いた。",
   usage:["depict A as B（AをBとして描く）"],
   etymologyProcess:"de（下へ）＋ pict（描く）→ 紙の上に写し取ると…？",
   etymologyConclusion:"de（下へ）＋ pict（描く）→ 見たものを紙の上に細かく写し取る＝（絵や言葉で）描く",
   relatedWords:[
     {word:"picture",meaning:"絵，写真",breakdown:"pict（描く）＋ ure（名詞）→ 描かれたもの"},
     {word:"paint",meaning:"（絵の具で）描く",breakdown:"pict（描く）→ 絵の具で色をつけて描く"},
     {word:"picturesque",meaning:"絵のように美しい",breakdown:"pict（描く）＋ esque（～のような）→ 絵に描いたような"},
     {synonym:true,word:"portray",meaning:"描き出す",breakdown:"人物の姿を描き出す。depict は場面や様子を細かく描く"}]},

  {id:1942,word:"landmark",partOfSpeech:"名詞",meaning:"目印（となる建物），名所；画期的な出来事",
   meanings:["名|目印（となる建物），名所","名|（歴史上の）画期的な出来事","形|画期的な"],
   pronunciation:"/ˈlændmɑːrk/",part:195,
   example:"Tokyo Tower is a famous landmark in the center of the city.",
   exampleJa:"東京タワーは、その都市の中心にある有名な名所だ。",
   example2:"The first moon landing was a landmark in human history.",
   exampleJa2:"初めての月面着陸は、人類の歴史における画期的な出来事だった。",
   etymologyProcess:"land（土地）＋ mark（しるし）→ 土地のしるしになるものは…？",
   etymologyConclusion:"land（土地）＋ mark（しるし）→ その土地で道しるべになる目立つ建物＝目印（となる建物）",
   etymologyMore:["歴史の流れの中で目立つしるし→（歴史上の）画期的な出来事"],
   relatedWords:[
     {word:"landscape",meaning:"風景",breakdown:"land（土地）＋ scape（ありさま）→ 土地の見わたせる様子"},
     {word:"mark",meaning:"しるし，印",breakdown:"mark（しるし）→ 見分けるために付けたもの"},
     {word:"trademark",meaning:"商標",breakdown:"trade（商売）＋ mark（しるし）→ 商品に付ける会社のしるし"},
     {word:"remark",meaning:"発言；述べる",breakdown:"re（再び）＋ mark（しるし）→ 気づいた点に印を付けて言う"}]},

  {id:1943,word:"tease",partOfSpeech:"他動詞",meaning:"からかう，冷やかす",
   meanings:["他|からかう，冷やかす","他|（動物を）いじめる，じらす"],
   pronunciation:"/tiːz/",part:195,
   example:"My classmates like to tease me about my new haircut.",
   exampleJa:"クラスメートは、私の新しい髪型のことでからかうのが好きだ。",
   example2:"Don't tease the dog, or it might bite you.",
   exampleJa2:"犬をいじめてはいけない。かみつかれるかもしれないよ。",
   etymologyProcess:"tease（毛をすいてほぐす）→ しつこくつついて毛羽立たせると…？",
   etymologyConclusion:"tease（毛をすいてほぐす）→ しつこくつついて相手の心を毛羽立たせる＝からかう",
   hook:"映画の「ティーザー（予告）」も tease から。見る人をじらして気を引く。",
   relatedWords:[
     {word:"teaser",meaning:"（じらす）予告",breakdown:"tease（毛をすいてほぐす）＋ er（もの）→ 見る人をじらす短い予告"},
     {synonym:true,word:"joke",meaning:"冗談を言う",breakdown:"笑わせる冗談。tease は相手を材料にする"},
     {synonym:true,word:"mock",meaning:"あざける",breakdown:"ばかにして笑う。tease より悪意が強い"},
     {synonym:true,word:"bully",meaning:"いじめる",breakdown:"弱い者を傷つける。tease は軽いからかいも含む"}]},

  {id:1944,word:"delight",partOfSpeech:"他動詞",meaning:"大喜びさせる；大きな喜び",
   meanings:["他|大喜びさせる，楽しませる","名|大きな喜び，楽しみ"],
   pronunciation:"/dɪˈlaɪt/",part:195,
   example:"The clown's funny tricks delighted all the children at the party.",
   exampleJa:"道化師のおもしろい芸は、パーティーの子どもたちみんなを大喜びさせた。",
   example2:"To my delight, I passed the entrance exam.",
   exampleJa2:"うれしいことに、私は入学試験に合格した。",
   usage:["be delighted with 事（～を大いに喜ぶ）","be delighted to do（喜んで～する）","to 人's delight（人がうれしいことに）"],
   etymologyProcess:"de（すっかり）＋ lac（誘いこむ）→ 心をすっかり引きこむと…？",
   etymologyConclusion:"de（すっかり）＋ lac（誘いこむ）→ 心をすっかり引きこんで楽しませる＝大喜びさせる",
   spelling:"lac→light（light に似せて綴りが変えられた）",
   etymologyMore:["心が引きこまれて満たされる気持ち→大きな喜び，楽しみ"],
   relatedWords:[
     {word:"delicious",meaning:"とてもおいしい",breakdown:"de（すっかり）＋ lac（誘いこむ）→ 舌をすっかり引きこむ味"},
     {word:"delightful",meaning:"とても楽しい",breakdown:"de（すっかり）＋ lac（誘いこむ）＋ ful（満ちた）→ 喜びに満ちた"},
     {synonym:true,word:"please",meaning:"喜ばせる",breakdown:"ふつうに満足させる。delight は大いに喜ばせる"},
     {synonym:true,word:"joy",meaning:"喜び",breakdown:"心からの喜び。delight は楽しさがはじける喜び"}]},

  {id:1945,word:"astonish",partOfSpeech:"他動詞",meaning:"（ひどく）驚かせる，びっくりさせる",
   meanings:["他|（ひどく）驚かせる，びっくりさせる"],
   pronunciation:"/əˈstɑːnɪʃ/",part:195,
   example:"The magician's final trick astonished everyone in the hall.",
   exampleJa:"手品師の最後の手品は、会場の全員をひどく驚かせた。",
   example2:"I was astonished to hear that my shy friend won the speech contest.",
   exampleJa2:"内気な友人が弁論大会で優勝したと聞いて、私はびっくりした。",
   usage:["be astonished at 事（～にひどく驚く）","be astonished to do（～して驚く）"],
   etymologyProcess:"ex（外へ）＋ tonare（雷が鳴る）→ 雷に打たれたようになると…？",
   etymologyConclusion:"ex（外へ）＋ tonare（雷が鳴る）→ 雷に打たれたように気が抜けるほど驚かせる＝（ひどく）驚かせる",
   spelling:"ex→as、tonare→ton（フランス語を通って変化）",
   relatedWords:[
     {word:"astonishment",meaning:"驚き",breakdown:"ex（外へ）＋ tonare（雷が鳴る）＋ ment（名詞）→ 雷に打たれたような驚き"},
     {word:"stun",meaning:"気絶させる；呆然とさせる",breakdown:"tonare（雷が鳴る）→ 雷に打たれたように動けなくする"},
     {synonym:true,word:"surprise",meaning:"驚かせる",breakdown:"ふつうに驚かせる。astonish は信じられないほど"},
     {synonym:true,word:"amaze",meaning:"びっくりさせる",breakdown:"感心するほど驚かせる"}]},

  {id:1946,word:"dread",partOfSpeech:"他動詞",meaning:"ひどく恐れる，～するのがとても怖い",
   meanings:["他|ひどく恐れる，～するのがとても怖い","名|（先のことへの）強い不安，恐怖"],
   pronunciation:"/dred/",part:195,
   example:"Many students dread the day of the final exam.",
   exampleJa:"多くの生徒が、期末試験の日をひどく恐れている。",
   example2:"I'm dreading going to the dentist next week.",
   exampleJa2:"来週歯医者に行くのが、とても怖い。",
   usage:["dread doing（～するのをひどく恐れる）"],
   etymologyProcess:"dread（おびえる）→ これから来ることにおびえると…？",
   etymologyConclusion:"dread（おびえる）→ これから起こることを考えておびえる＝ひどく恐れる",
   etymologyMore:["先のことにおびえる気持ち→（先のことへの）強い不安，恐怖"],
   hook:"古英語から続く語。fear は今の恐怖、dread は「これから来る嫌なこと」への恐れ。",
   relatedWords:[
     {word:"dreadful",meaning:"ひどい，恐ろしい",breakdown:"dread（おびえる）＋ ful（満ちた）→ 恐れでいっぱいになる"},
     {synonym:true,word:"fear",meaning:"恐れる",breakdown:"ふつうの「恐れる」。dread は先のことを強く恐れる"},
     {synonym:true,word:"terror",meaning:"恐怖",breakdown:"身がすくむほどの激しい恐怖"},
     {synonym:true,word:"worry",meaning:"心配する",breakdown:"気にかかって不安になる。dread はもっと強い"}]},

  {id:1947,word:"attribute",partOfSpeech:"他動詞",meaning:"（結果を～の）おかげ［せい］だと考える，～に帰する",
   meanings:["他|（to ～の）おかげ［せい］だと考える，～に帰する","名|特性，属性"],
   pronunciation:"/əˈtrɪbjuːt/",part:195,
   example:"She attributes her success to hard work and good luck.",
   exampleJa:"彼女は自分の成功を、努力と幸運のおかげだとしている。",
   example2:"Patience is an important attribute of a good teacher.",
   exampleJa2:"忍耐強さは、よい教師の大切な特性だ。",
   usage:["attribute A to B（AをBのせい・おかげとする）"],
   etymologyProcess:"ad（～へ）＋ tribut（割り当てる）→ 結果をある原因へ割り当てると…？",
   etymologyConclusion:"ad（～へ）＋ tribut（割り当てる）→ 起きた結果をある原因へ割り当てる＝（結果を～の）おかげ［せい］だと考える",
   spelling:"ad→at（後ろの t に合わせて変化）",
   etymologyMore:["その人や物に割り当てられた性質→特性，属性"],
   relatedWords:[
     {word:"contribute",meaning:"貢献する",breakdown:"con（共に）＋ tribut（割り当てる）→ みんなで分担して出し合う"},
     {word:"distribute",meaning:"配る",breakdown:"dis（バラバラに）＋ tribut（割り当てる）→ 分けて割り当てる"},
     {word:"tribute",meaning:"賛辞，敬意のしるし",breakdown:"tribut（割り当てる）→ 相手に差し出す贈り物"},
     {synonym:true,word:"blame",meaning:"（悪いことを）～のせいにする",breakdown:"悪い結果の責任を負わせる。attribute はよい結果にも使う"}]},

  {id:1948,word:"console",partOfSpeech:"他動詞",meaning:"慰める，元気づける",
   meanings:["他|慰める，元気づける"],
   pronunciation:"/kənˈsoʊl/",part:195,
   example:"She tried to console her friend after they lost the game.",
   exampleJa:"試合に負けたあと、彼女は友達を慰めようとした。",
   example2:"Nothing could console him when his old dog died.",
   exampleJa2:"年老いた犬が死んだとき、何ものも彼を慰めることはできなかった。",
   etymologyProcess:"con（すっかり）＋ solari（慰める）→ 悲しむ人の心をすっかり包むと…？",
   etymologyConclusion:"con（すっかり）＋ solari（慰める）→ 悲しんでいる人の心をすっかりやわらげる＝慰める",
   spelling:"solari→sol（語尾が落ちた）",
   relatedWords:[
     {word:"consolation",meaning:"慰め",breakdown:"con（すっかり）＋ solari（慰める）＋ ation（名詞）→ 心をやわらげるもの"},
     {word:"solace",meaning:"慰め，癒やし",breakdown:"solari（慰める）→ つらい心をやわらげるもの"},
     {synonym:true,word:"comfort",meaning:"慰める",breakdown:"苦しみを軽くする。console は悲しみや失望に使う"},
     {synonym:true,word:"cheer",meaning:"元気づける",breakdown:"明るく励ます。cheer up の形でよく使う"}]},

  {id:1949,word:"arouse",partOfSpeech:"他動詞",meaning:"（感情・関心を）呼び起こす，かき立てる",
   meanings:["他|（感情・関心を）呼び起こす，かき立てる","他|（眠りから）目覚めさせる"],
   pronunciation:"/əˈraʊz/",part:195,
   example:"The strange noise from the attic aroused my curiosity.",
   exampleJa:"屋根裏からの奇妙な物音が、私の好奇心をかき立てた。",
   example2:"His rude comments will arouse anger among the students.",
   exampleJa2:"彼の失礼な発言は、生徒たちの怒りを呼び起こすだろう。",
   etymologyProcess:"rouse（奮い立たせる）→ 眠っている気持ちをたたき起こすと…？",
   etymologyConclusion:"rouse（奮い立たせる）→ 眠っていた気持ちをたたき起こす＝（感情・関心を）呼び起こす",
   etymologyMore:["眠っている人をたたき起こす→（眠りから）目覚めさせる"],
   hook:"語源のはっきりしない rouse（起こす）に a を付けた形。rise（上がる）とは別の語。",
   relatedWords:[
     {word:"rouse",meaning:"目覚めさせる，奮起させる",breakdown:"rouse（奮い立たせる）→ 眠っている人をたたき起こす"},
     {synonym:true,word:"awaken",meaning:"目覚めさせる",breakdown:"眠りや意識を起こす。arouse は感情によく使う"},
     {synonym:true,word:"stir",meaning:"かき混ぜる；かき立てる",breakdown:"液体をかき回すように心を動かす"},
     {synonym:true,word:"provoke",meaning:"（怒りを）引き起こす",breakdown:"pro（前へ）＋ vok（呼ぶ）。相手をわざと刺激する"}]},

  {id:1950,word:"distract",partOfSpeech:"他動詞",meaning:"（気を散らして）注意をそらす",
   meanings:["他|（気を散らして）注意をそらす","他|気晴らしをさせる"],
   pronunciation:"/dɪˈstrækt/",part:195,
   example:"Loud music can distract you from your homework.",
   exampleJa:"大きな音楽は、宿題から注意をそらしてしまうことがある。",
   example2:"I was distracted by my phone during the class.",
   exampleJa2:"私は授業中、スマホに気を取られていた。",
   usage:["distract 人 from 事（人の注意を～からそらす）"],
   etymologyProcess:"dis（離れて）＋ tract（引く）→ 注意を別の方へ引き離すと…？",
   etymologyConclusion:"dis（離れて）＋ tract（引く）→ 向けていた注意を別の方へ引き離す＝（気を散らして）注意をそらす",
   etymologyMore:["悩みから心を引き離す→気晴らしをさせる"],
   relatedWords:[
     {word:"attract",meaning:"引きつける",breakdown:"ad（～へ）＋ tract（引く）→ 自分のほうへ引き寄せる"},
     {word:"subtract",meaning:"引き算する",breakdown:"sub（下で）＋ tract（引く）→ 下から引き抜いて減らす"},
     {word:"tractor",meaning:"トラクター",breakdown:"tract（引く）＋ or（もの）→ 重い農機具を引っぱる車"},
     {synonym:true,word:"divert",meaning:"（注意を）そらす",breakdown:"di（離れて）＋ vert（回る）。向きを変えさせる"}]},
