  {id:1551,word:"inequality",partOfSpeech:"名詞",meaning:"不平等，格差",
   meanings:["名|不平等，格差"],
   pronunciation:"/ˌɪnɪˈkwɑːləti/",part:156,
   example:"The report shows growing inequality between rich and poor families.",
   exampleJa:"その報告書は、裕福な家庭と貧しい家庭の不平等が広がっていることを示している。",
   example2:"Many young people are fighting against gender inequality.",
   exampleJa2:"多くの若者が男女の格差と闘っている。",
   etymologyProcess:"in（否定）＋ equ（等しい）＋ ity（名詞）→ 等しくない状態なら…？",
   etymologyConclusion:"in（否定）＋ equ（等しい）＋ ity（名詞）→ 人々の扱いや持ち物が等しくない状態＝不平等",
   relatedWords:[
     {word:"equal",meaning:"等しい",breakdown:"equ（等しい）＋ al（形容詞）→ 大きさや価値が同じ"},
     {word:"equality",meaning:"平等",breakdown:"equ（等しい）＋ al（形容詞）＋ ity（名詞）→ みんなが等しいこと"},
     {word:"equator",meaning:"赤道",breakdown:"equ（等しい）＋ ator（もの）→ 地球を南北に等しく分ける線"},
     {synonym:true,word:"gap",meaning:"格差，すき間",breakdown:"二つの間の開き。inequality は不公平な状態そのもの"}]},

  {id:1552,word:"equivalent",partOfSpeech:"形容詞",meaning:"（価値や意味が）同等の",
   meanings:["形|（to ～と）同等の","名|同等のもの，相当するもの"],
   pronunciation:"/ɪˈkwɪvələnt/",part:156,
   example:"Ten thousand yen is roughly equivalent to seventy dollars.",
   exampleJa:"1万円は、およそ70ドルと同等の額だ。",
   example2:"There is no exact English equivalent for this Japanese word.",
   exampleJa2:"この日本語にぴったり相当する英語はない。",
   etymologyProcess:"equ（等しい）＋ val（力がある）＋ ent（～している）→ 同じだけの力を持っていると…？",
   etymologyConclusion:"equ（等しい）＋ val（力がある）＋ ent（～している）→ 同じだけの力や値打ちを持つ＝（価値や意味が）同等の",
   relatedWords:[
     {word:"equal",meaning:"等しい",breakdown:"equ（等しい）＋ al（形容詞）→ 大きさや価値が同じ"},
     {word:"valid",meaning:"有効な",breakdown:"val（力がある）＋ id（～な状態の）→ 効き目の力を持っている"},
     {word:"value",meaning:"価値",breakdown:"valu（価値）→ どれだけの力や値打ちがあるか"},
     {synonym:true,word:"same",meaning:"同じ",breakdown:"まったく同一。equivalent は別物だが値打ちが等しい"}]},

  {id:1553,word:"compatible",partOfSpeech:"形容詞",meaning:"（互いに）両立できる，相性がよい",
   meanings:["形|（with ～と）両立できる，相性がよい","形|（機械などが）互換性のある"],
   pronunciation:"/kəmˈpætəbl/",part:156,
   example:"Is this charger compatible with my new phone?",
   exampleJa:"この充電器は、私の新しいスマホと両立できる（使える）だろうか。",
   example2:"My two roommates are not compatible at all.",
   exampleJa2:"私のルームメイト2人は、まったく相性がよくない。",
   etymologyProcess:"com（共に）＋ pat（耐える）＋ ible（できる）→ 一緒にいても耐えられると…？",
   etymologyConclusion:"com（共に）＋ pat（耐える）＋ ible（できる）→ 一緒にいても互いにがまんできる＝（互いに）両立できる",
   why:"【なぜ】ラテン語 compati は「共に苦しむ・同じ気持ちになる」。中世には「一緒にいてもうまくやっていける」という意味で使われ、そこから「両立できる・相性がよい」になりました。今は機械どうしが一緒に使える「互換性がある」にも使います。\n【つながり】patient（耐える）、compassion（共に苦しむ→思いやり）も同じ pat の家族です。",
   relatedWords:[
     {word:"patient",meaning:"がまん強い；患者",breakdown:"pat（耐える）＋ ent（～している）→ 苦しみに耐えている"},
     {word:"compassion",meaning:"思いやり",breakdown:"com（共に）＋ passi（耐える）＋ ion（名詞）→ 相手と共に苦しむ気持ち"},
     {word:"incompatible",meaning:"両立しない",breakdown:"in（否定）＋ com（共に）＋ pat（耐える）＋ ible（できる）→ 共にいられない"},
     {synonym:true,word:"suitable",meaning:"適した",breakdown:"目的に合っていること。compatible は二つがうまく合う"}]},

  {id:1554,word:"identical",partOfSpeech:"形容詞",meaning:"まったく同じ，同一の",
   meanings:["形|（to / with ～と）まったく同じ，同一の","形|うり二つの"],
   pronunciation:"/aɪˈdentɪkl/",part:156,
   example:"The twins wore identical jackets to the party.",
   exampleJa:"双子はパーティーにまったく同じ上着を着てきた。",
   example2:"Your answer is identical to Ken's, word for word.",
   exampleJa2:"君の答えは、ケンの答えと一語一語までそっくり同じだ。",
   etymologyProcess:"ident（同じ）＋ ical（～の）→ まったく同じものだと…？",
   etymologyConclusion:"ident（同じ）＋ ical（～の）→ 見分けがつかないほど中身も形もそろった＝まったく同じ",
   relatedWords:[
     {word:"identity",meaning:"身元；独自性",breakdown:"ident（同じ）＋ ity（名詞）→ ずっと同じその人であること"},
     {word:"identify",meaning:"特定する",breakdown:"ident（同じ）＋ ify（する）→ それと同じものだと確かめる"},
     {synonym:true,word:"same",meaning:"同じ",breakdown:"ふつうの「同じ」。identical は細部まで完全に同じ"},
     {synonym:true,word:"similar",meaning:"似ている",breakdown:"似てはいるが違う点もある。identical は違いがない"}]},

  {id:1555,word:"correspond",partOfSpeech:"自動詞",meaning:"（with / to ～と）一致する；文通する",
   meanings:["自|（with / to ～と）一致する，対応する","自|（with ～と）文通する"],
   pronunciation:"/ˌkɔːrəˈspɑːnd/",part:156,
   example:"Your story does not correspond with the facts.",
   exampleJa:"君の話は事実と一致しない。",
   example2:"I corresponded with a pen pal in Canada for years.",
   exampleJa2:"私はカナダのペンフレンドと何年も文通した。",
   etymologyProcess:"com（共に）＋ re（戻す）＋ spond（誓う）→ 互いに約束を返し合うと…？",
   etymologyConclusion:"com（共に）＋ re（戻す）＋ spond（誓う）→ 互いに応え合ってぴったり合う＝（with / to ～と）一致する",
   relatedWords:[
     {word:"respond",meaning:"応答する",breakdown:"re（戻す）＋ spond（誓う）→ 約束を返すように答える"},
     {word:"response",meaning:"反応",breakdown:"re（戻す）＋ spons（誓う）→ 返ってきた答え"},
     {word:"responsible",meaning:"責任がある",breakdown:"re（戻す）＋ spons（誓う）＋ ible（できる）→ 約束に応えられる"},
     {synonym:true,word:"match",meaning:"一致する",breakdown:"ぴったり合うこと。correspond は二つが対応していること"}]},

  {id:1556,word:"random",partOfSpeech:"形容詞",meaning:"無作為の，でたらめな",
   meanings:["形|無作為の，でたらめな","熟|（at random で）無作為に，手当たりしだいに"],
   pronunciation:"/ˈrændəm/",part:156,
   example:"The teacher chose five random students to answer.",
   exampleJa:"先生は答える生徒を無作為に5人選んだ。",
   example2:"The computer picks the winner's name at random.",
   exampleJa2:"コンピューターが当選者の名前を無作為に選ぶ。",
   etymologyProcess:"random（勢いまかせに走る）→ ねらいを定めず勢いで選ぶと…？",
   etymologyConclusion:"random（勢いまかせに走る）→ ねらいも順序もなく勢いまかせの＝無作為の",
   hook:"古いフランス語 randon（勢い・猛スピード）から。at random（手当たりしだいに）で使う。",
   relatedWords:[
     {synonym:true,word:"arbitrary",meaning:"勝手な",breakdown:"決まりがなく気まま。random は偶然にまかせる"},
     {synonym:true,word:"accidental",meaning:"偶然の",breakdown:"たまたま起きた。random は選び方に決まりがない"},
     {synonym:true,word:"haphazard",meaning:"行き当たりばったりの",breakdown:"計画がなく雑な。random はむしろ公平な選び方にも使う"},
     {synonym:true,word:"chance",meaning:"偶然",breakdown:"運のなりゆき。by chance は「たまたま」、at random は「無作為に」"}]},

  {id:1557,word:"warrior",partOfSpeech:"名詞",meaning:"戦士，武人",
   meanings:["名|戦士，武人"],
   pronunciation:"/ˈwɔːriər/",part:156,
   example:"The brave warrior protected the village from enemies.",
   exampleJa:"勇敢な戦士は敵から村を守った。",
   example2:"In the game, you play as a young warrior.",
   exampleJa2:"そのゲームでは、若い戦士としてプレイする。",
   etymologyProcess:"war（戦い）→ 戦いに身をささげる人は…？",
   etymologyConclusion:"war（戦い）→ 戦いを仕事とし、命をかけて戦う人＝戦士",
   relatedWords:[
     {word:"war",meaning:"戦争",breakdown:"war（戦い）→ 国どうしの大きな戦い"},
     {word:"warfare",meaning:"戦争（行為）",breakdown:"war（戦い）＋ fare（やっていく）→ 戦いをやっていくこと"},
     {synonym:true,word:"soldier",meaning:"兵士",breakdown:"軍隊に属する兵。warrior は古くからの勇ましい戦士"},
     {synonym:true,word:"fighter",meaning:"戦う人",breakdown:"戦う人全般。warrior は古風で力強い言い方"}]},

  {id:1558,word:"assault",partOfSpeech:"名詞",meaning:"暴行；襲撃",
   meanings:["名|暴行","名|（軍の）襲撃","他|～に暴行する，～を襲撃する"],
   pronunciation:"/əˈsɔːlt/",part:156,
   example:"The man was arrested for assault after the fight.",
   exampleJa:"その男はけんかのあと、暴行の罪で逮捕された。",
   example2:"The army launched an assault on the enemy's base at dawn.",
   exampleJa2:"軍は夜明けに敵の基地への襲撃を始めた。",
   etymologyProcess:"ad（～へ）＋ sault（跳ぶ）→ 相手に向かって飛びかかると…？",
   etymologyConclusion:"ad（～へ）＋ sault（跳ぶ）→ 相手に向かっていきなり飛びかかる＝暴行",
   relatedWords:[
     {word:"result",meaning:"結果",breakdown:"re（後ろへ）＋ sult（跳ぶ）→ はね返って出てきたもの"},
     {word:"insult",meaning:"侮辱する",breakdown:"in（上に）＋ sult（跳ぶ）→ 相手の上に飛び乗って踏みつける"},
     {synonym:true,word:"attack",meaning:"攻撃",breakdown:"攻撃全般。assault は人への暴力や急な襲撃"},
     {synonym:true,word:"violence",meaning:"暴力",breakdown:"暴力全般。assault は法律で罪になる暴行"}]},

  {id:1559,word:"troop",partOfSpeech:"名詞",meaning:"（troops で）軍隊，部隊；群れ",
   meanings:["名|（troops で）軍隊，部隊","名|（人や動物の）群れ"],
   pronunciation:"/truːp/",part:156,
   example:"The government sent troops to protect the border.",
   exampleJa:"政府は国境を守るため軍隊を送った。",
   example2:"A troop of monkeys came down from the mountain.",
   exampleJa2:"サルの群れが山から降りてきた。",
   etymologyProcess:"troop（群れ）→ 兵が群れになって動くと…？",
   etymologyConclusion:"troop（群れ）→ 兵が群れのようにまとまって動く集団＝（troops で）軍隊",
   hook:"フランス語 troupe（群れ）から。劇団の「一座（トループ）」も同じ語。",
   relatedWords:[
     {synonym:true,word:"army",meaning:"陸軍，軍隊",breakdown:"国の軍全体。troops は実際に送られる兵たち"},
     {synonym:true,word:"soldier",meaning:"兵士",breakdown:"兵一人ひとり。troops はその集まり"},
     {synonym:true,word:"group",meaning:"集団",breakdown:"集まり全般。troop は動物の群れにも使う"},
     {synonym:true,word:"unit",meaning:"部隊，単位",breakdown:"まとまった一団。troop もほぼ同じ意味で使う"}]},

  {id:1560,word:"shield",partOfSpeech:"名詞",meaning:"盾；守るもの",
   meanings:["名|盾；守るもの","他|（from ～から）～を守る"],
   pronunciation:"/ʃiːld/",part:156,
   example:"The knight raised his shield to stop the arrow.",
   exampleJa:"騎士は矢を防ぐために盾を掲げた。",
   example2:"Good sunglasses shield your eyes from strong summer sunlight.",
   exampleJa2:"よいサングラスは、夏の強い日光から目を守る。",
   etymologyProcess:"shield（板で身を守るもの）→ 攻撃を受け止める板は…？",
   etymologyConclusion:"shield（板で身を守るもの）→ 攻撃を受け止めて体を守る板＝盾",
   hook:"古英語 scield（割った板）から。「シールド」として日本語でも使う。",
   relatedWords:[
     {synonym:true,word:"protect",meaning:"守る",breakdown:"守ること全般。shield は間に入って防ぐ"},
     {synonym:true,word:"guard",meaning:"見張る，守る",breakdown:"見張って守ること。shield は盾のように遮る"},
     {synonym:true,word:"defend",meaning:"防御する",breakdown:"攻撃から守ること。shield は覆って守る"},
     {synonym:true,word:"cover",meaning:"覆う",breakdown:"上からかぶせること。shield は危険を防ぐために覆う"}]},

  {id:1561,word:"torture",partOfSpeech:"名詞",meaning:"拷問；ひどい苦しみ",
   meanings:["名|拷問","名|ひどい苦しみ","他|～を拷問にかける，ひどく苦しめる"],
   pronunciation:"/ˈtɔːrtʃər/",part:157,
   example:"International law strictly bans the use of torture.",
   exampleJa:"国際法は拷問を使うことを厳しく禁じている。",
   example2:"Waiting for the test results was pure torture.",
   exampleJa2:"テストの結果を待つのは、まさにひどい苦しみだった。",
   etymologyProcess:"tort（ねじる）＋ ure（名詞）→ 体をねじり上げて苦しめると…？",
   etymologyConclusion:"tort（ねじる）＋ ure（名詞）→ 体をねじり上げて痛めつけること＝拷問",
   relatedWords:[
     {word:"distort",meaning:"ゆがめる",breakdown:"dis（バラバラに）＋ tort（ねじる）→ ねじって形を崩す"},
     {word:"torch",meaning:"たいまつ",breakdown:"tort（ねじる）→ わらをねじって作った明かり"},
     {word:"torment",meaning:"苦痛；苦しめる",breakdown:"tort（ねじる）＋ ment（名詞）→ ねじり上げる責め苦"},
     {synonym:true,word:"agony",meaning:"激しい苦痛",breakdown:"耐えがたい痛み。torture は人がわざと与える苦しみ"}]},

  {id:1562,word:"dispute",partOfSpeech:"名詞",meaning:"（激しい）論争，紛争",
   meanings:["名|（激しい）論争，紛争","他|～に異議を唱える"],
   pronunciation:"/dɪˈspjuːt/",part:157,
   example:"The two countries have a long dispute over the island.",
   exampleJa:"両国はその島をめぐって長い論争をしている。",
   example2:"Nobody on either team disputed the referee's final decision.",
   exampleJa2:"どちらのチームにも、審判の最終判断に異議を唱える人はいなかった。",
   etymologyProcess:"dis（バラバラに）＋ pute（考える）→ 考えがバラバラに分かれてぶつかると…？",
   etymologyConclusion:"dis（バラバラに）＋ pute（考える）→ 考えが分かれて激しくぶつかり合うこと＝（激しい）論争",
   relatedWords:[
     {word:"compute",meaning:"計算する",breakdown:"com（共に）＋ pute（考える）→ 数を合わせて見積もる"},
     {word:"reputation",meaning:"評判",breakdown:"re（何度も）＋ pute（考える）＋ ation（名詞）→ 人々がくり返し考えた評価"},
     {word:"deputy",meaning:"代理人",breakdown:"de（離して）＋ pute（考える）→ 自分の代わりと見なして任された人"},
     {synonym:true,word:"argument",meaning:"口論，議論",breakdown:"言い争い全般。dispute は長く続く正式な争い"}]},

  {id:1563,word:"combat",partOfSpeech:"名詞",meaning:"戦闘；（他動詞で）～と闘う",
   meanings:["名|戦闘","他|（犯罪や病気など）と闘う，～を防止する"],
   pronunciation:"/ˈkɑːmbæt/",part:157,
   example:"Many young soldiers died in combat during the war.",
   exampleJa:"戦争中、多くの若い兵士が戦闘で命を落とした。",
   example2:"The city is using cameras to combat crime.",
   exampleJa2:"市は犯罪と闘うためにカメラを使っている。",
   etymologyProcess:"com（共に）＋ bat（打つ）→ 互いに打ち合うと…？",
   etymologyConclusion:"com（共に）＋ bat（打つ）→ 敵と味方が互いに打ち合うこと＝戦闘",
   relatedWords:[
     {word:"battle",meaning:"戦い",breakdown:"bat（打つ）＋ le（もの）→ 打ち合う戦い"},
     {word:"debate",meaning:"討論",breakdown:"de（すっかり）＋ bat（打つ）→ 言葉で打ち合って論じる"},
     {word:"combatant",meaning:"戦闘員",breakdown:"com（共に）＋ bat（打つ）＋ ant（人）→ 打ち合いに加わる人"},
     {synonym:true,word:"fight",meaning:"戦い",breakdown:"戦い全般。combat は武器を使った本格的な戦闘"}]},

  {id:1564,word:"tactics",partOfSpeech:"名詞",meaning:"戦術，作戦",
   meanings:["名|戦術，作戦","名|（tactic で）手段，策"],
   pronunciation:"/ˈtæktɪks/",part:157,
   example:"The coach changed our tactics in the second half.",
   exampleJa:"コーチは後半にチームの戦術を変えた。",
   example2:"Scaring people is not a good sales tactic.",
   exampleJa2:"人をこわがらせるのは、よい販売の手段ではない。",
   etymologyProcess:"tactic（兵を並べる）→ 戦場で兵をどう並べて動かすかは…？",
   etymologyConclusion:"tactic（兵を並べる）→ その場で兵をうまく並べて動かす方法＝戦術",
   hook:"ギリシャ語 taktika（兵の並べ方）から。「タクティクス」とそのまま使う。",
   relatedWords:[
     {word:"tactical",meaning:"戦術的な",breakdown:"tactic（兵を並べる）＋ al（形容詞）→ 並べ方をうまく考えた"},
     {synonym:true,word:"strategy",meaning:"戦略",breakdown:"長い目で見た全体の計画。tactics はその場の動かし方"},
     {synonym:true,word:"method",meaning:"方法",breakdown:"やり方全般。tactics は勝つための具体的な手"},
     {synonym:true,word:"maneuver",meaning:"作戦行動",breakdown:"軍や車の巧みな動き。tactics はその動かし方の計画"}]},

  {id:1565,word:"quarrel",partOfSpeech:"自動詞",meaning:"口論する，言い争う",
   meanings:["自|（with ～と）口論する，言い争う","名|口論，けんか"],
   pronunciation:"/ˈkwɔːrəl/",part:157,
   example:"The brothers often quarrel about who uses the computer.",
   exampleJa:"兄弟はだれがパソコンを使うかでよく口論する。",
   example2:"We had a quarrel, but we made up the next day.",
   exampleJa2:"私たちはけんかをしたが、次の日に仲直りした。",
   etymologyProcess:"quarrel（不満を訴える）→ 不満をぶつけ合って言い争うと…？",
   etymologyConclusion:"quarrel（不満を訴える）→ 互いに不満をぶつけて言い争う＝口論する",
   hook:"ラテン語 querella（不平・訴え）から。殴り合いでなく口げんかに使う。",
   relatedWords:[
     {synonym:true,word:"argue",meaning:"言い争う",breakdown:"理由を挙げて言い合う。quarrel は感情的なけんか"},
     {synonym:true,word:"fight",meaning:"けんかする",breakdown:"殴り合いにも口げんかにも使う。quarrel は口だけ"},
     {synonym:true,word:"dispute",meaning:"論争",breakdown:"長く続く正式な争い。quarrel は身近な言い争い"},
     {synonym:true,word:"bicker",meaning:"つまらない口げんかをする",breakdown:"ささいなことで言い合う。quarrel より軽い"}]},

  {id:1566,word:"contend",partOfSpeech:"自動詞",meaning:"（with ～と）戦う，競う；主張する",
   meanings:["自|（with / for ～と・を求めて）戦う，競う","他|（that 節で）～と主張する"],
   pronunciation:"/kənˈtend/",part:157,
   example:"Five teams will contend for the championship this year.",
   exampleJa:"今年は5チームが優勝を目指して戦う。",
   example2:"Scientists contend that the problem is getting worse.",
   exampleJa2:"科学者たちは、その問題が悪化していると主張している。",
   etymologyProcess:"con（強く）＋ tend（伸ばす）→ 手を強く伸ばして取り合うと…？",
   etymologyConclusion:"con（強く）＋ tend（伸ばす）→ 力いっぱい手を伸ばして取り合う＝（with ～と）戦う",
   relatedWords:[
     {word:"extend",meaning:"伸ばす",breakdown:"ex（外へ）＋ tend（伸ばす）→ 外へ長く伸ばす"},
     {word:"pretend",meaning:"ふりをする",breakdown:"pre（前へ）＋ tend（伸ばす）→ 前へ差し出して見せかける"},
     {word:"intend",meaning:"つもりである",breakdown:"in（中へ）＋ tend（伸ばす）→ 心をそちらへ伸ばす"},
     {synonym:true,word:"compete",meaning:"競う",breakdown:"勝とうと争うこと。contend はより激しく戦う"}]},

  {id:1567,word:"slaughter",partOfSpeech:"他動詞",meaning:"虐殺する；（家畜を）処理する",
   meanings:["他|～を虐殺する","他|（家畜）を処理する","名|虐殺"],
   pronunciation:"/ˈslɔːtər/",part:157,
   example:"Soldiers slaughtered hundreds of people in the village.",
   exampleJa:"兵士たちはその村で何百人もの人を虐殺した。",
   example2:"The farmers slaughter their pigs for meat in the winter.",
   exampleJa2:"農家は冬に豚を食肉用に処理する。",
   etymologyProcess:"slaughter（打ち殺す）→ 大勢を次々に打ち殺すと…？",
   etymologyConclusion:"slaughter（打ち殺す）→ 大勢の人や動物を次々に殺す＝虐殺する",
   hook:"古ノルド語 slátr（屠った肉）から。一度に大勢を殺すときに使う。",
   relatedWords:[
     {synonym:true,word:"kill",meaning:"殺す",breakdown:"殺すこと全般。slaughter は大量に残酷に殺す"},
     {synonym:true,word:"massacre",meaning:"大虐殺",breakdown:"無抵抗の人々を大勢殺すこと。slaughter とほぼ同じ"},
     {synonym:true,word:"murder",meaning:"殺人",breakdown:"一人を計画的に殺すこと。slaughter は大量の殺し"},
     {word:"slay",meaning:"殺す",breakdown:"slay（打ち殺す）→ 打って命を奪う（古い言い方）"}]},

  {id:1568,word:"suppress",partOfSpeech:"他動詞",meaning:"（反乱などを）鎮圧する；抑える",
   meanings:["他|（反乱など）を鎮圧する","他|（感情など）を抑える","他|（情報）を隠す"],
   pronunciation:"/səˈpres/",part:157,
   example:"The army was sent to suppress the rebellion.",
   exampleJa:"反乱を鎮圧するために軍が送られた。",
   example2:"She suppressed a laugh during the serious meeting.",
   exampleJa2:"彼女はまじめな会議の間、笑いを抑えた。",
   etymologyProcess:"sup（下から）＋ press（押す）→ 下へ押さえこんで動けなくすると…？",
   etymologyConclusion:"sup（下から）＋ press（押す）→ 力で押さえつけて動けなくする＝（反乱などを）鎮圧する",
   relatedWords:[
     {word:"press",meaning:"押す",breakdown:"press（押す）→ 力を加えて押しつける"},
     {word:"express",meaning:"表現する",breakdown:"ex（外へ）＋ press（押す）→ 気持ちを外へ押し出す"},
     {word:"depress",meaning:"落ちこませる",breakdown:"de（下へ）＋ press（押す）→ 気分を下へ押し下げる"},
     {synonym:true,word:"crush",meaning:"押しつぶす",breakdown:"力でつぶすこと。suppress は動きを止めて抑えこむ"}]},

  {id:1569,word:"surrender",partOfSpeech:"自動詞",meaning:"降伏する；（他動詞で）引き渡す",
   meanings:["自|（to ～に）降伏する","他|～を引き渡す，手放す"],
   pronunciation:"/səˈrendər/",part:157,
   example:"After weeks of fighting, the enemy soldiers decided to surrender.",
   exampleJa:"何週間もの戦いのすえ、敵の兵士たちは降伏することにした。",
   example2:"He surrendered his passport to the police at the airport.",
   exampleJa2:"彼は空港で警察にパスポートを引き渡した。",
   etymologyProcess:"sur（上から）＋ render（渡す）→ 自分のすべてを相手の手に渡すと…？",
   etymologyConclusion:"sur（上から）＋ render（渡す）→ 武器も身も相手の手に渡してしまう＝降伏する",
   relatedWords:[
     {word:"render",meaning:"（ある状態に）する；与える",breakdown:"render（渡す）→ 相手へ渡して、ある状態にする"},
     {word:"rent",meaning:"家賃；賃借りする",breakdown:"rent（定期的な支払い）→ 決まった日に払い渡すお金"},
     {synonym:true,word:"give up",meaning:"あきらめる",breakdown:"やめてしまうこと。surrender は敵に負けを認める"},
     {synonym:true,word:"yield",meaning:"屈する",breakdown:"力に押されて従うこと。surrender は完全に降参する"}]},

  {id:1570,word:"hostile",partOfSpeech:"形容詞",meaning:"敵意のある，反対の",
   meanings:["形|（to ～に）敵意のある","形|（to ～に）強く反対の","形|（環境が）厳しい"],
   pronunciation:"/ˈhɑːstl/",part:157,
   example:"The villagers were hostile to strangers from the city.",
   exampleJa:"村人たちは都会から来たよそ者に敵意を持っていた。",
   example2:"Plants cannot grow in such a hostile desert environment.",
   exampleJa2:"植物はそんな厳しい砂漠の環境では育たない。",
   etymologyProcess:"hostil（敵の）→ 相手を敵として見ると…？",
   etymologyConclusion:"hostil（敵の）→ 相手を敵と見なしてにらむ＝敵意のある",
   relatedWords:[
     {word:"hostility",meaning:"敵意",breakdown:"hostil（敵の）＋ ity（名詞）→ 敵として見る気持ち"},
     {synonym:true,word:"unfriendly",meaning:"不親切な",breakdown:"やさしくないこと。hostile ははっきり敵視する"},
     {synonym:true,word:"aggressive",meaning:"攻撃的な",breakdown:"自分から攻めかかる。hostile は敵意を持った状態"},
     {synonym:true,word:"opposed",meaning:"反対して",breakdown:"考えに反対していること。hostile はより強い敵意"}]},

  {id:1571,word:"wreck",partOfSpeech:"名詞",meaning:"（事故のあとの）残骸；難破船",
   meanings:["名|（事故のあとの）残骸","名|難破船","他|～をめちゃめちゃに壊す"],
   pronunciation:"/rek/",part:158,
   example:"Divers found the wreck of an old ship on the seabed.",
   exampleJa:"ダイバーたちは海底で古い船の残骸を見つけた。",
   example2:"The storm wrecked many houses along the coast.",
   exampleJa2:"嵐は海岸沿いの多くの家をめちゃめちゃに壊した。",
   etymologyProcess:"wreck（打ち上げられたもの）→ 嵐で壊れて浜に流れ着いたものは…？",
   etymologyConclusion:"wreck（打ち上げられたもの）→ 壊れて浜に打ち上げられた船や車の残り＝（事故のあとの）残骸",
   hook:"古ノルド語から入った語。w は発音しない。shipwreck（難破）の形でもよく使う。",
   relatedWords:[
     {synonym:true,word:"ruins",meaning:"廃墟",breakdown:"崩れた建物の跡。wreck は船や車など乗り物の残骸"},
     {synonym:true,word:"remains",meaning:"残り",breakdown:"残ったもの全般。wreck は事故で壊れた残り"},
     {synonym:true,word:"destroy",meaning:"破壊する",breakdown:"壊すこと全般。wreck はめちゃめちゃに壊す"},
     {synonym:true,word:"debris",meaning:"破片，がれき",breakdown:"散らばったかけら。wreck は壊れた本体"}]},

  {id:1572,word:"toll",partOfSpeech:"名詞",meaning:"（事故などの）死者数；通行料",
   meanings:["名|（事故などの）死者数，被害","名|（道路などの）通行料"],
   pronunciation:"/toʊl/",part:158,
   example:"The death toll from the earthquake rose to three hundred.",
   exampleJa:"その地震による死者数は300人に上った。",
   example2:"We paid a toll to use the new highway.",
   exampleJa2:"私たちは新しい高速道路を使うのに通行料を払った。",
   etymologyProcess:"toll（取り立てる料金）→ 災害が命という形で取り立てた数は…？",
   etymologyConclusion:"toll（取り立てる料金）→ 災害が人々から取り立てた命の数＝（事故などの）死者数",
   hook:"もとは「通行料」。take a toll on ～（～に大きな被害を与える）も覚える。",
   relatedWords:[
     {synonym:true,word:"fee",meaning:"料金",breakdown:"支払う料金全般。toll は道や橋を通る料金"},
     {synonym:true,word:"charge",meaning:"料金",breakdown:"サービスなどの料金。toll は道路や橋を通る料金"},
     {synonym:true,word:"fare",meaning:"運賃",breakdown:"乗り物の料金。toll は道路や橋の料金"},
     {synonym:true,word:"damage",meaning:"損害",breakdown:"受けた被害。take a toll で「被害を与える」"}]},

  {id:1573,word:"disrupt",partOfSpeech:"他動詞",meaning:"（活動などを）混乱させて妨げる",
   meanings:["他|（活動など）を混乱させて妨げる，中断させる"],
   pronunciation:"/dɪsˈrʌpt/",part:158,
   example:"A heavy snowstorm disrupted train services across the country.",
   exampleJa:"大雪が全国の列車の運行を混乱させ、止めてしまった。",
   example2:"Please do not disrupt the class by talking loudly.",
   exampleJa2:"大声で話して授業のじゃまをしないでください。",
   etymologyProcess:"dis（バラバラに）＋ rupt（破る）→ 流れをバラバラに破ると…？",
   etymologyConclusion:"dis（バラバラに）＋ rupt（破る）→ 順調な流れをバラバラに破ってしまう＝（活動などを）混乱させて妨げる",
   relatedWords:[
     {word:"interrupt",meaning:"じゃまをする",breakdown:"inter（間の）＋ rupt（破る）→ 話の間に割りこんで破る"},
     {word:"erupt",meaning:"噴火する",breakdown:"e（外へ）＋ rupt（破る）→ 山が内から破れて外へ噴き出す"},
     {word:"bankrupt",meaning:"倒産した",breakdown:"bank（両替台）＋ rupt（破る）→ 両替台をこわされた"},
     {synonym:true,word:"disturb",meaning:"じゃまする",breakdown:"静けさを乱すこと。disrupt は流れを止めるほど乱す"}]},

  {id:1574,word:"interfere",partOfSpeech:"自動詞",meaning:"（with ～を）邪魔する；（in ～に）干渉する",
   meanings:["自|（with ～を）邪魔する","自|（in ～に）干渉する，口出しする"],
   pronunciation:"/ˌɪntərˈfɪr/",part:158,
   example:"Loud music from next door can interfere with your sleep.",
   exampleJa:"隣の家からの大きな音楽は、睡眠を邪魔することがある。",
   example2:"My parents never interfered in my choice of university.",
   exampleJa2:"両親は私の大学選びに一度も口出ししなかった。",
   etymologyProcess:"inter（間の）＋ fere（打つ）→ 二つの間に入って打ちかかると…？",
   etymologyConclusion:"inter（間の）＋ fere（打つ）→ 間に割って入って打ちかかる＝（with ～を）邪魔する",
   relatedWords:[
     {word:"international",meaning:"国際的な",breakdown:"inter（間の）＋ nation（国家）＋ al（形容詞）→ 国と国の間の"},
     {synonym:true,word:"hinder",meaning:"妨げる",breakdown:"進むのを遅らせる。interfere は間に割りこんでじゃまする"},
     {synonym:true,word:"disturb",meaning:"じゃまする",breakdown:"静けさを乱すこと。interfere は間に入ってじゃまする"},
     {synonym:true,word:"meddle",meaning:"おせっかいを焼く",breakdown:"関係ないことに首を出す。interfere in とほぼ同じ"}]},

  {id:1575,word:"confront",partOfSpeech:"他動詞",meaning:"（困難などが）立ちはだかる；～に立ち向かう",
   meanings:["他|（困難などが）～に立ちはだかる","他|～に立ち向かう，直面する"],
   pronunciation:"/kənˈfrʌnt/",part:158,
   example:"Many problems confront the new government this year.",
   exampleJa:"今年、多くの問題が新しい政府に立ちはだかる。",
   example2:"She finally confronted her fear of speaking in public.",
   exampleJa2:"彼女はついに人前で話すことへの恐れに立ち向かった。",
   etymologyProcess:"con（共に）＋ front（前）→ 前と前を向け合うと…？",
   etymologyConclusion:"con（共に）＋ front（前）→ 相手と真正面から顔を向け合う＝（困難などが）立ちはだかる",
   relatedWords:[
     {word:"front",meaning:"前面，正面",breakdown:"front（前）→ いちばん前に出ている面"},
     {word:"frontier",meaning:"国境地帯",breakdown:"frontier（国の前のはし）→ 国のいちばん前の境目"},
     {word:"confrontation",meaning:"対立",breakdown:"con（共に）＋ front（前）＋ ation（名詞）→ 真正面からぶつかること"},
     {synonym:true,word:"face",meaning:"直面する",breakdown:"向き合うこと。confront はより正面から対決する"}]},

  {id:1576,word:"explode",partOfSpeech:"自動詞",meaning:"爆発する；（感情が）爆発する",
   meanings:["自|爆発する","自|（感情が）爆発する","他|～を爆発させる"],
   pronunciation:"/ɪkˈsploʊd/",part:158,
   example:"The old gas tank could explode at any moment.",
   exampleJa:"その古いガスタンクはいつ爆発してもおかしくない。",
   example2:"He exploded with anger when he saw the mess.",
   exampleJa2:"彼は散らかりようを見て怒りを爆発させた。",
   etymologyProcess:"ex（外へ）＋ plod（拍手する）→ 手をたたいて舞台から外へ追い出すと…？",
   etymologyConclusion:"ex（外へ）＋ plod（拍手する）→ 大きな音を立てて外へはじけ飛ぶ＝爆発する",
   why:"【なぜ】ラテン語 explodere は ex（外へ）＋ plaudere（手をたたく）で、もとは「手をたたいてやじり、役者を舞台から追い出す」こと。そこから「大きな音で追い出す」になり、17世紀には「やじって退ける」の意味で使われ、18世紀の終わりごろに「大きな音を立てて外へはじける」＝爆発する、になりました。\n【つながり】applaud（拍手する）が同じ家族。拍手と爆発の音をつなげて覚えよう。",
   relatedWords:[
     {word:"applaud",meaning:"拍手する",breakdown:"ad（～へ）＋ plaud（拍手する）→ 相手に向けて手をたたく"},
     {word:"explosion",meaning:"爆発",breakdown:"ex（外へ）＋ plod（拍手する）＋ ion（名詞）→ 外へはじけ飛ぶこと"},
     {word:"plausible",meaning:"もっともらしい",breakdown:"plaus（拍手する）＋ ible（できる）→ 拍手してもよさそうな"},
     {synonym:true,word:"burst",meaning:"破裂する",breakdown:"内から破れること。explode は激しく音を立ててはじける"}]},

  {id:1577,word:"collide",partOfSpeech:"自動詞",meaning:"（with ～と）衝突する；（意見が）ぶつかる",
   meanings:["自|（with ～と）衝突する","自|（意見などが）ぶつかる"],
   pronunciation:"/kəˈlaɪd/",part:158,
   example:"Two trucks collided on the icy road this morning.",
   exampleJa:"今朝、凍った道で2台のトラックが衝突した。",
   example2:"Their opinions often collide during our weekly club meetings.",
   exampleJa2:"毎週の部の会議では、彼らの意見がよくぶつかる。",
   etymologyProcess:"col（共に）＋ lid（ぶつける）→ 互いにぶつけ合うと…？",
   etymologyConclusion:"col（共に）＋ lid（ぶつける）→ 互いに勢いよくぶつかり合う＝（with ～と）衝突する",
   relatedWords:[
     {word:"collision",meaning:"衝突",breakdown:"col（共に）＋ lis（ぶつける）＋ ion（名詞）→ ぶつかり合うこと"},
     {synonym:true,word:"hit",meaning:"ぶつかる，打つ",breakdown:"ぶつかること全般。collide は2つが互いにぶつかり合う"},
     {synonym:true,word:"crash",meaning:"衝突する",breakdown:"激しくぶつかって壊れる。collide はぶつかること自体"},
     {synonym:true,word:"clash",meaning:"衝突する，対立する",breakdown:"音を立ててぶつかる。意見の対立にも使う"}]},

  {id:1578,word:"nephew",partOfSpeech:"名詞",meaning:"甥（おい）",
   meanings:["名|甥（おい）"],
   pronunciation:"/ˈnefjuː/",part:158,
   example:"My nephew is starting elementary school this spring.",
   exampleJa:"私の甥はこの春、小学校に入学する。",
   example2:"She has three nephews and one niece in Osaka.",
   exampleJa2:"彼女には大阪に甥が3人、姪が1人いる。",
   etymologyProcess:"nephew（孫・子孫）→ きょうだいの息子は…？",
   etymologyConclusion:"nephew（孫・子孫）→ 自分のきょうだいの息子＝甥（おい）",
   hook:"ラテン語 nepos（孫）から。女性形は niece（姪）。セットで覚える。",
   relatedWords:[
     {word:"niece",meaning:"姪（めい）",breakdown:"niece（孫娘・子孫）→ 子孫の中でも、きょうだいの娘"},
     {word:"nepotism",meaning:"身内びいき",breakdown:"nepot（孫・甥）＋ ism（主義）→ 甥や孫ばかりえこひいきする"},
     {synonym:true,word:"relative",meaning:"親戚",breakdown:"親戚全般。nephew はその中のきょうだいの息子"}]},

  {id:1579,word:"infant",partOfSpeech:"名詞",meaning:"乳児，赤ん坊",
   meanings:["名|乳児，赤ん坊","形|乳児の；初期の"],
   pronunciation:"/ˈɪnfənt/",part:158,
   example:"The nurse carefully held the newborn infant in her arms.",
   exampleJa:"看護師は生まれたばかりの乳児を両腕で大切に抱いた。",
   example2:"This seat is designed for infants under one year old.",
   exampleJa2:"この座席は1歳未満の赤ん坊用に作られている。",
   etymologyProcess:"in（否定）＋ fant（話す）→ まだ話せない小さな子は…？",
   etymologyConclusion:"in（否定）＋ fant（話す）→ まだ言葉を話せないほど小さな子＝乳児",
   relatedWords:[
     {word:"infancy",meaning:"幼年時代；初期",breakdown:"in（否定）＋ fant（話す）＋ cy（名詞）→ まだ話せないころ"},
     {word:"fable",meaning:"寓話",breakdown:"fa（話す）＋ ble（もの）→ 語り伝えられる話"},
     {synonym:true,word:"baby",meaning:"赤ちゃん",breakdown:"ふつうの言い方。infant は医学や法律で使うかたい語"},
     {synonym:true,word:"newborn",meaning:"新生児",breakdown:"生まれたばかりの子。infant は1歳くらいまでの子"}]},

  {id:1580,word:"spouse",partOfSpeech:"名詞",meaning:"配偶者",
   meanings:["名|配偶者"],
   pronunciation:"/spaʊs/",part:158,
   example:"Please write the name of your spouse on this form.",
   exampleJa:"この用紙に配偶者の名前を書いてください。",
   example2:"Employees and their spouses are invited to the party.",
   exampleJa2:"社員とその配偶者がパーティーに招かれている。",
   etymologyProcess:"spous（誓う）→ 結婚を誓い合った相手は…？",
   etymologyConclusion:"spous（誓う）→ 結婚を誓い合った相手＝配偶者",
   relatedWords:[
     {word:"respond",meaning:"応答する",breakdown:"re（戻す）＋ spond（誓う）→ 約束を返すように答える"},
     {word:"sponsor",meaning:"スポンサー，後援者",breakdown:"spons（誓う）＋ or（人）→ 支払いを誓って引き受ける人"},
     {synonym:true,word:"partner",meaning:"パートナー",breakdown:"連れ合い全般。spouse は法律上の結婚相手"},
     {word:"responsible",meaning:"責任がある",breakdown:"re（戻す）＋ spons（誓う）＋ ible（できる）→ 誓った約束に応えられる"}]},

  {id:1581,word:"heir",partOfSpeech:"名詞",meaning:"（財産や地位の）相続人，跡継ぎ",
   meanings:["名|（to ～の）相続人，跡継ぎ"],
   pronunciation:"/er/",part:159,
   example:"The young prince is the only heir to the throne.",
   exampleJa:"その若い王子は、王位のただ一人の相続人だ。",
   example2:"She became the heir to her grandfather's large fortune.",
   exampleJa2:"彼女は祖父の莫大な財産の跡継ぎになった。",
   etymologyProcess:"heir（受け継ぐ人）→ 亡くなった人の財産や地位を受け継ぐのは…？",
   etymologyConclusion:"heir（受け継ぐ人）→ 亡くなった人の財産や地位を受け継ぐ人＝（財産や地位の）相続人",
   hook:"h は発音せず air と同じ音。女性形は heiress。",
   relatedWords:[
     {word:"inherit",meaning:"相続する",breakdown:"in（中へ）＋ herit（受け継ぐ）→ 財産を自分の中へ受け継ぐ"},
     {word:"heritage",meaning:"遺産",breakdown:"herit（受け継ぐ）＋ age（名詞）→ 受け継がれてきたもの"},
     {word:"heredity",meaning:"遺伝",breakdown:"hered（受け継ぐ）＋ ity（名詞）→ 親から性質を受け継ぐこと"},
     {synonym:true,word:"successor",meaning:"後継者",breakdown:"地位のあとを継ぐ人。heir は財産の相続にも使う"}]},

  {id:1582,word:"folk",partOfSpeech:"名詞",meaning:"（folks で）人々；家族",
   meanings:["名|（folk / folks で）人々","名|（one's folks で）家族，両親","形|民間の，民俗の"],
   pronunciation:"/foʊk/",part:159,
   example:"The old folks in this village still speak the local dialect.",
   exampleJa:"この村の年配の人々は、今も土地の方言を話す。",
   example2:"I'm going home to visit my folks this weekend.",
   exampleJa2:"今週末は実家に帰って家族に会うつもりだ。",
   etymologyProcess:"folk（民衆）→ ふつうに暮らす人たちの集まりは…？",
   etymologyConclusion:"folk（民衆）→ ふつうに暮らしている人たちの集まり＝（folks で）人々",
   hook:"l は発音しない。「フォークソング（民謡）」の folk。",
   relatedWords:[
     {word:"folklore",meaning:"民間伝承",breakdown:"folk（民衆）＋ lore（知恵）→ 民衆に伝わる言い伝え"},
     {synonym:true,word:"people",meaning:"人々",breakdown:"ふつうの言い方。folks は親しみをこめたくだけた言い方"},
     {synonym:true,word:"family",meaning:"家族",breakdown:"家族全般。my folks は「うちの家族・両親」"},
     {synonym:true,word:"public",meaning:"一般の人々",breakdown:"社会全体の人々。folk は庶民の感じが強い"}]},

  {id:1583,word:"peer",partOfSpeech:"名詞",meaning:"同輩，（年齢や立場が）同じ仲間",
   meanings:["名|同輩，（年齢や立場が）同じ仲間","自|（at ～を）じっと見る"],
   pronunciation:"/pɪr/",part:159,
   example:"Teenagers often care a lot about what their peers think.",
   exampleJa:"十代の若者は、同輩がどう思うかをとても気にすることが多い。",
   example2:"The old man peered at the small letters on the sign.",
   exampleJa2:"老人は看板の小さな文字をじっと見た。",
   etymologyProcess:"peer（等しい）→ 年齢や立場が自分と等しい人は…？",
   etymologyConclusion:"peer（等しい）→ 年齢や立場が自分と等しい人＝同輩",
   hook:"「じっと見る」の peer は語源の違う別の語。同輩の peer は par（等しい）の仲間。",
   relatedWords:[
     {word:"compare",meaning:"比べる",breakdown:"com（共に）＋ par（等しい）→ 並べて等しいか見る"},
     {word:"peerless",meaning:"比べるものがない",breakdown:"peer（等しい）＋ less（ない）→ 肩を並べる者がいない"},
     {synonym:true,word:"classmate",meaning:"同級生",breakdown:"同じクラスの人。peer は年齢や立場が同じ人全般"},
     {synonym:true,word:"colleague",meaning:"同僚",breakdown:"同じ職場の仲間。peer は職場に限らない"}]},

  {id:1584,word:"recipient",partOfSpeech:"名詞",meaning:"受取人，受け取る人",
   meanings:["名|受取人，（賞などを）受け取る人"],
   pronunciation:"/rɪˈsɪpiənt/",part:159,
   example:"Write the recipient's address clearly on the envelope.",
   exampleJa:"封筒に受取人の住所をはっきり書きなさい。",
   example2:"She was the youngest recipient of the science prize.",
   exampleJa2:"彼女はその科学賞を受け取った最年少の人だった。",
   etymologyProcess:"re（戻す）＋ cip（取る）＋ ent（人）→ 送られてきたものを手元へ取る側の人は…？",
   etymologyConclusion:"re（戻す）＋ cip（取る）＋ ent（人）→ 送られてきたものを手元に受け取る人＝受取人",
   relatedWords:[
     {word:"receive",meaning:"受け取る",breakdown:"re（戻す）＋ ceive（取る）→ 手元へ取りこむ"},
     {word:"accept",meaning:"受け入れる",breakdown:"ad（～へ）＋ cept（取る）→ 差し出されたものを取る"},
     {word:"participate",meaning:"参加する",breakdown:"part（分ける）＋ cip（取る）＋ ate（動詞）→ 分けた一部を受け持つ"},
     {word:"receiver",meaning:"受け取る人；受話器",breakdown:"re（戻す）＋ ceive（取る）＋ er（人）→ 手元へ受け取る人・もの"}]},

  {id:1585,word:"navigate",partOfSpeech:"他動詞・自動詞",meaning:"（船や飛行機の）進路を決める，航行する",
   meanings:["他|（船など）の進路を決める，～を操縦する","自|航行する","他|（サイトなど）の中を移動する"],
   pronunciation:"/ˈnævɪɡeɪt/",part:159,
   example:"Sailors once used the stars to navigate across the ocean.",
   exampleJa:"昔の船乗りは星を使って大洋を渡る進路を決めた。",
   example2:"This app helps you navigate the busy streets of Tokyo.",
   exampleJa2:"このアプリは、東京のにぎやかな通りで道案内をしてくれる。",
   etymologyProcess:"nav（船）＋ ig（行う）＋ ate（動詞）→ 船を動かして行く先を決めると…？",
   etymologyConclusion:"nav（船）＋ ig（行う）＋ ate（動詞）→ 船を動かし、行く道を決めて進む＝（船や飛行機の）進路を決める",
   relatedWords:[
     {word:"navy",meaning:"海軍",breakdown:"nav（船）＋ y（集まり）→ 軍の船の集まり"},
     {word:"naval",meaning:"海軍の",breakdown:"nav（船）＋ al（形容詞）→ 船や海軍に関する"},
     {word:"navigation",meaning:"航海；ナビ",breakdown:"nav（船）＋ ig（行う）＋ ation（名詞）→ 進路を決めて進むこと"},
     {synonym:true,word:"steer",meaning:"かじを取る",breakdown:"向きを操ること。navigate は道を決めて進む"}]},

  {id:1586,word:"flee",partOfSpeech:"自動詞",meaning:"（危険から）逃げる，逃れる",
   meanings:["自|（危険から）逃げる，逃れる","他|～から逃げる"],
   pronunciation:"/fliː/",part:159,
   example:"Thousands of people had to flee the burning city.",
   exampleJa:"何千人もの人が燃える町から逃げなければならなかった。",
   example2:"The thief fled before the police arrived at the store.",
   exampleJa2:"警察が店に着く前に、泥棒は逃げた。",
   etymologyProcess:"flee（急いで逃げ去る）→ 危険から急いで離れると…？",
   etymologyConclusion:"flee（急いで逃げ去る）→ 危険から急いで遠くへ離れる＝（危険から）逃げる",
   hook:"古英語 fleon から。過去形・過去分詞は fled。fly（飛ぶ）とは別の語。",
   relatedWords:[
     {synonym:true,word:"escape",meaning:"逃げる",breakdown:"つかまった状態から抜け出す。flee は危険から遠ざかる"},
     {synonym:true,word:"run away",meaning:"走って逃げる",breakdown:"くだけた言い方。flee はかたい語"},
     {synonym:true,word:"evacuate",meaning:"避難する",breakdown:"命令に従って安全な所へ移る。flee は急いで逃げる"},
     {synonym:true,word:"retreat",meaning:"退く",breakdown:"軍などが後ろへ下がる。flee は必死に逃げ出す"}]},

  {id:1587,word:"retreat",partOfSpeech:"自動詞",meaning:"退く，撤退する",
   meanings:["自|退く，撤退する","名|撤退；隠れ家"],
   pronunciation:"/rɪˈtriːt/",part:159,
   example:"The army had to retreat after losing the battle.",
   exampleJa:"軍は戦いに負けて退かなければならなかった。",
   example2:"The cabin in the mountains is our quiet summer retreat.",
   exampleJa2:"山の小屋は、私たちの静かな夏の隠れ家だ。",
   etymologyProcess:"re（後ろへ）＋ treat（引く）→ 後ろへ身を引くと…？",
   etymologyConclusion:"re（後ろへ）＋ treat（引く）→ 前に出ていた所から後ろへ身を引く＝退く",
   relatedWords:[
     {word:"treat",meaning:"扱う",breakdown:"treat（引く）→ 手で引き回すように相手を扱う"},
     {word:"attract",meaning:"引きつける",breakdown:"ad（～へ）＋ tract（引く）→ 自分のほうへ引き寄せる"},
     {word:"extract",meaning:"取り出す",breakdown:"ex（外へ）＋ tract（引く）→ 中から外へ引き出す"},
     {synonym:true,word:"withdraw",meaning:"引っ込める，撤退する",breakdown:"引き下げること。retreat は負けて後ろへ下がる感じ"}]},

  {id:1588,word:"crawl",partOfSpeech:"自動詞",meaning:"這って進む；のろのろ進む",
   meanings:["自|這って進む","自|（車などが）のろのろ進む"],
   pronunciation:"/krɔːl/",part:159,
   example:"The baby began to crawl across the living room floor.",
   exampleJa:"赤ちゃんは居間の床を這って進み始めた。",
   example2:"Traffic crawled along the highway during the holiday rush.",
   exampleJa2:"連休の混雑で、高速道路の車はのろのろ進んだ。",
   etymologyProcess:"crawl（ひっかくように這う）→ 手とひざで床をかくように進むと…？",
   etymologyConclusion:"crawl（ひっかくように這う）→ 手とひざで床をかくように進む＝這って進む",
   hook:"古ノルド語から。水泳の「クロール」も水をかいて這うように進むことから。",
   relatedWords:[
     {synonym:true,word:"creep",meaning:"忍び寄る，這う",breakdown:"そっとゆっくり進む。crawl は手足をついて這う"},
     {synonym:true,word:"slide",meaning:"すべる",breakdown:"表面をすべる。crawl は手足を動かして進む"},
     {synonym:true,word:"inch",meaning:"少しずつ進む",breakdown:"じりじり少しずつ動く。crawl は這う・のろのろ進む"},
     {synonym:true,word:"plod",meaning:"とぼとぼ歩く",breakdown:"重い足どりでゆっくり進む。crawl は這うほど遅い"}]},

  {id:1589,word:"hover",partOfSpeech:"自動詞",meaning:"空中にとどまる；うろつく",
   meanings:["自|空中にとどまる","自|（近くを）うろつく","自|（数値などが）上下する"],
   pronunciation:"/ˈhʌvər/",part:159,
   example:"A helicopter hovered over the building for an hour.",
   exampleJa:"ヘリコプターが1時間、建物の上の空中にとどまっていた。",
   example2:"In January, temperatures here hover around zero degrees at night.",
   exampleJa2:"1月、このあたりの夜の気温は0度前後を上下する。",
   etymologyProcess:"hover（ただよってとどまる）→ 空中の同じ所にじっと浮かんでいると…？",
   etymologyConclusion:"hover（ただよってとどまる）→ 空中の同じ所にじっと浮かんでいる＝空中にとどまる",
   hook:"中英語 hoveren から。ホバリング（ヘリの空中停止）で日本語にもなっている。",
   relatedWords:[
     {synonym:true,word:"float",meaning:"浮かぶ",breakdown:"水や空中に浮くこと。hover は一か所にとどまる"},
     {synonym:true,word:"hang in the air",meaning:"宙に浮かぶ",breakdown:"空中にとどまる様子。hover は自分の力で浮く"},
     {synonym:true,word:"linger",meaning:"ぐずぐず残る",breakdown:"去らずに残ること。hover はそばでうろうろする"},
     {synonym:true,word:"hang",meaning:"ぶら下がる，漂う",breakdown:"上からつられている。hover は自分の力で浮く"}]},

  {id:1590,word:"drift",partOfSpeech:"自動詞",meaning:"漂う，押し流される",
   meanings:["自|漂う，押し流される","自|（人が）なんとなく移る","名|漂流；（雪の）吹きだまり"],
   pronunciation:"/drɪft/",part:159,
   example:"The small boat began to drift slowly out to sea.",
   exampleJa:"その小舟はゆっくりと沖へ漂い始めた。",
   example2:"After graduation, the two friends slowly drifted apart.",
   exampleJa2:"卒業後、その二人の友だちはだんだん疎遠になっていった。",
   etymologyProcess:"drift（押し流される）→ 風や水に押されて流されていくと…？",
   etymologyConclusion:"drift（押し流される）→ 自分の力でなく風や水に押されて流れていく＝漂う",
   hook:"drive（追い立てる）と同じゲルマン語の仲間。drift apart は「疎遠になる」。",
   relatedWords:[
     {synonym:true,word:"float",meaning:"浮かぶ",breakdown:"水に浮くこと。drift は浮いて流されていく"},
     {synonym:true,word:"wander",meaning:"さまよう",breakdown:"あてもなく歩き回る。drift は流されるまま移る"},
     {synonym:true,word:"flow",meaning:"流れる",breakdown:"水そのものが流れる。drift は水に運ばれる"},
     {word:"drive",meaning:"追い立てる；運転する",breakdown:"drive（追い立てる）→ 前へ押し進める。drift は押し流された結果"}]},

  {id:1591,word:"alter",partOfSpeech:"他動詞・自動詞",meaning:"（部分的に）変える，作り変える",
   meanings:["他|～を（部分的に）変える，作り変える","自|変わる"],
   pronunciation:"/ˈɔːltər/",part:160,
   example:"The tailor can alter the length of your pants.",
   exampleJa:"その仕立て屋はズボンの丈を変えることができる。",
   example2:"The town has altered a lot since I was a child.",
   exampleJa2:"その町は私が子どものころからずいぶん変わった。",
   etymologyProcess:"alter（別の）→ 今とは別の形にすると…？",
   etymologyConclusion:"alter（別の）→ 全体はそのままに、一部を別の形にする＝（部分的に）変える",
   relatedWords:[
     {word:"alternative",meaning:"代わりの（もの）",breakdown:"alter（別の）＋ ive（形容詞）→ もう一つ別の選べるもの"},
     {word:"alternate",meaning:"交互の",breakdown:"alter（別の）＋ ate（形容詞）→ 一つおきに別のものが来る"},
     {word:"alien",meaning:"外国の；宇宙人",breakdown:"ali（別の）＋ en（～された）→ よその別の世界から来た"},
     {synonym:true,word:"change",meaning:"変える",breakdown:"変えること全般。alter は一部だけ手を加える"}]},

  {id:1592,word:"convert",partOfSpeech:"他動詞・自動詞",meaning:"転換する，作り変える；改宗させる",
   meanings:["他|（into ～に）転換する，作り変える","他|～を改宗させる","自|変わる"],
   pronunciation:"/kənˈvɜːrt/",part:160,
   example:"They plan to convert the old factory into a museum.",
   exampleJa:"彼らは古い工場を博物館に転換する予定だ。",
   example2:"The solar panels on the roof convert sunlight into electricity for the school.",
   exampleJa2:"屋根の太陽光パネルが、日光を学校で使う電気に変えている。",
   etymologyProcess:"con（すっかり）＋ vert（回る）→ すっかり向きを回して別物にすると…？",
   etymologyConclusion:"con（すっかり）＋ vert（回る）→ すっかり向きを変えて別のものにする＝転換する",
   relatedWords:[
     {word:"reverse",meaning:"逆にする",breakdown:"re（後ろへ）＋ vers（回る）→ 後ろ向きに回す"},
     {word:"version",meaning:"版，型",breakdown:"vers（回る）＋ ion（名詞）→ 形を変えて作ったもの"},
     {word:"conversation",meaning:"会話",breakdown:"con（共に）＋ vers（回る）＋ ation（名詞）→ 顔を向け合ってやりとりすること"},
     {synonym:true,word:"transform",meaning:"変形させる",breakdown:"形をがらりと変える。convert は用途を変える"}]},

  {id:1593,word:"overtake",partOfSpeech:"他動詞",meaning:"追い越す；（不意に）襲う",
   meanings:["他|～を追い越す","他|（不幸などが）～を不意に襲う"],
   pronunciation:"/ˌoʊvərˈteɪk/",part:160,
   example:"Never try to overtake another car on a sharp curve.",
   exampleJa:"急カーブで別の車を追い越そうとしてはいけない。",
   example2:"China overtook Japan as the world's second largest economy.",
   exampleJa2:"中国は日本を追い越して、世界第2位の経済大国になった。",
   etymologyProcess:"over（越えて）＋ take（取る）→ 前を行く相手の上を越えて取ると…？",
   etymologyConclusion:"over（越えて）＋ take（取る）→ 追いついて前の相手を越え、先を取る＝追い越す",
   relatedWords:[
     {word:"undertake",meaning:"引き受ける",breakdown:"under（下に）＋ take（取る）→ 仕事の下へ入って担ぎ取る"},
     {word:"overcome",meaning:"克服する",breakdown:"over（越えて）＋ come（来る）→ 困難を越えて向こうへ来る"},
     {word:"overlook",meaning:"見落とす",breakdown:"over（越えて）＋ look（見る）→ 上を越して見てしまい気づかない"},
     {synonym:true,word:"pass",meaning:"追い越す，通り過ぎる",breakdown:"横を通り過ぎる。overtake は追いついて前に出る"}]},

  {id:1594,word:"dispatch",partOfSpeech:"他動詞",meaning:"（人を）派遣する；（物を）発送する",
   meanings:["他|（人）を派遣する","他|（物）を発送する","名|派遣；発送"],
   pronunciation:"/dɪˈspætʃ/",part:160,
   example:"The government will dispatch doctors to the disaster area.",
   exampleJa:"政府は被災地に医師を派遣する予定だ。",
   example2:"Your order was dispatched from our warehouse this morning.",
   exampleJa2:"ご注文の品は今朝、倉庫から発送されました。",
   etymologyProcess:"dispatch（すばやく片づけて送り出す）→ 急いで人や物を送り出すと…？",
   etymologyConclusion:"dispatch（すばやく片づけて送り出す）→ 用のある場所へ急いで送り出す＝（人を）派遣する",
   hook:"イタリア語・スペイン語から入った語で、はじめの形ははっきりしない。send より急ぐ感じ。",
   relatedWords:[
     {synonym:true,word:"send",meaning:"送る",breakdown:"送ること全般。dispatch は目的のために急いで送る"},
     {synonym:true,word:"ship",meaning:"発送する",breakdown:"荷物を送り出すこと。dispatch は人を送る場合にも使う"},
     {synonym:true,word:"deliver",meaning:"配達する",breakdown:"相手に届けること。dispatch は送り出す側の動き"},
     {synonym:true,word:"deploy",meaning:"配備する",breakdown:"軍などを配置すること。dispatch は現場へ送ること"}]},

  {id:1595,word:"shrink",partOfSpeech:"自動詞",meaning:"縮む，減る",
   meanings:["自|縮む，減る","他|～を縮ませる"],
   pronunciation:"/ʃrɪŋk/",part:160,
   example:"My wool sweater will shrink if I wash it in hot water.",
   exampleJa:"ウールのセーターは、お湯で洗うと縮むだろう。",
   example2:"The number of students in rural schools keeps shrinking.",
   exampleJa2:"田舎の学校の生徒数は減り続けている。",
   etymologyProcess:"shrink（しわが寄って縮む）→ しわが寄って小さくなると…？",
   etymologyConclusion:"shrink（しわが寄って縮む）→ しわが寄って大きさや量が小さくなる＝縮む",
   hook:"古英語 scrincan から。過去形は shrank、過去分詞は shrunk。",
   relatedWords:[
     {synonym:true,word:"decrease",meaning:"減る",breakdown:"数や量が減ること。shrink は大きさが縮む感じも出る"},
     {synonym:true,word:"contract",meaning:"収縮する",breakdown:"ぎゅっと縮まる。shrink は小さくなること全般"},
     {synonym:true,word:"reduce",meaning:"減らす",breakdown:"意図して減らす。shrink は自然に縮む"},
     {synonym:true,word:"decline",meaning:"減少する",breakdown:"下向きに減ること。shrink は規模が小さくなる"}]},

  {id:1596,word:"wither",partOfSpeech:"自動詞",meaning:"（植物が）しおれる；衰える",
   meanings:["自|（植物が）しおれる，枯れる","自|衰える"],
   pronunciation:"/ˈwɪðər/",part:160,
   example:"The flowers began to wither in the hot afternoon sun.",
   exampleJa:"花は暑い午後の日差しでしおれ始めた。",
   example2:"Her hopes slowly withered as the months went by.",
   exampleJa2:"月日がたつにつれ、彼女の希望はだんだん衰えた。",
   etymologyProcess:"wither（天気にさらされる）→ 日光や風にさらされ続けると…？",
   etymologyConclusion:"wither（天気にさらされる）→ 日光や風にさらされて水気を失う＝（植物が）しおれる",
   hook:"weather（天気）が変化した語とされる。天気にやられてしおれる、と覚える。",
   relatedWords:[
     {synonym:true,word:"fade",meaning:"色あせる",breakdown:"色や光が薄れる。wither は水気を失ってしおれる"},
     {synonym:true,word:"die",meaning:"死ぬ，枯れる",breakdown:"命がなくなる。wither はその手前の弱った状態"},
     {synonym:true,word:"dry up",meaning:"干上がる",breakdown:"水分がなくなる。wither は植物が弱ってしぼむ"},
     {synonym:true,word:"decline",meaning:"衰える",breakdown:"勢いが落ちる。wither は希望などが消えていく"}]},

  {id:1597,word:"descend",partOfSpeech:"自動詞",meaning:"降りる，下る",
   meanings:["自|降りる，下る","他|（階段など）を降りる","自|（be descended from で）～の子孫である"],
   pronunciation:"/dɪˈsend/",part:160,
   example:"The plane began to descend toward the airport.",
   exampleJa:"飛行機は空港に向かって降り始めた。",
   example2:"We descended the mountain slowly because the path was icy.",
   exampleJa2:"道が凍っていたので、私たちはゆっくり山を下った。",
   etymologyProcess:"de（下へ）＋ scend（登る）→ 登るのと逆に下へ向かうと…？",
   etymologyConclusion:"de（下へ）＋ scend（登る）→ 登ってきた所から下へ向かって行く＝降りる",
   relatedWords:[
     {word:"ascend",meaning:"登る",breakdown:"ad（～へ）＋ scend（登る）→ 上へ向かって登る"},
     {word:"descendant",meaning:"子孫",breakdown:"de（下へ）＋ scend（登る）＋ ant（人）→ 家系を下っていく人"},
     {word:"scale",meaning:"目盛り；規模",breakdown:"scal（はしご）→ はしごの段のように並んだ目盛り"},
     {synonym:true,word:"go down",meaning:"降りる",breakdown:"ふつうの言い方。descend はかたい語"}]},

  {id:1598,word:"accelerate",partOfSpeech:"他動詞・自動詞",meaning:"加速する，速める",
   meanings:["自|加速する","他|～を速める"],
   pronunciation:"/əkˈseləreɪt/",part:160,
   example:"The car began to accelerate as it left the town.",
   exampleJa:"車は町を出ると加速し始めた。",
   example2:"The new policy accelerated the growth of small businesses.",
   exampleJa2:"新しい政策は中小企業の成長を速めた。",
   etymologyProcess:"ac（～へ）＋ celer（速い）＋ ate（動詞）→ 速いほうへ向かわせると…？",
   etymologyConclusion:"ac（～へ）＋ celer（速い）＋ ate（動詞）→ どんどん速いほうへ持っていく＝加速する",
   relatedWords:[
     {word:"accelerator",meaning:"アクセル",breakdown:"ac（～へ）＋ celer（速い）＋ ator（もの）→ 車を速くするペダル"},
     {word:"acceleration",meaning:"加速",breakdown:"ac（～へ）＋ celer（速い）＋ ation（名詞）→ 速くなること"},
     {synonym:true,word:"speed up",meaning:"速める",breakdown:"ふつうの言い方。accelerate はかたい語"},
     {synonym:true,word:"hasten",meaning:"急がせる",breakdown:"物事を早めること。accelerate は速度を上げる"}]},

  {id:1599,word:"fluctuate",partOfSpeech:"自動詞",meaning:"（上下に）変動する",
   meanings:["自|（上下に）変動する"],
   pronunciation:"/ˈflʌktʃueɪt/",part:160,
   example:"Vegetable prices fluctuate a lot depending on the weather.",
   exampleJa:"野菜の値段は天候によって大きく変動する。",
   example2:"His mood fluctuated wildly before the big exam.",
   exampleJa2:"大事な試験の前、彼の気分は激しく上下した。",
   etymologyProcess:"fluct（波）＋ ate（動詞）→ 波のように上がったり下がったりすると…？",
   etymologyConclusion:"fluct（波）＋ ate（動詞）→ 波のように上がったり下がったりする＝（上下に）変動する",
   relatedWords:[
     {word:"fluid",meaning:"液体",breakdown:"flu（流れる）＋ id（～な状態の）→ 流れる状態のもの"},
     {word:"influence",meaning:"影響",breakdown:"in（中へ）＋ flu（流れる）＋ ence（名詞）→ 中へ流れこんで働く力"},
     {word:"fluent",meaning:"流ちょうな",breakdown:"flu（流れる）＋ ent（～している）→ 言葉がすらすら流れる"},
     {synonym:true,word:"vary",meaning:"変わる",breakdown:"いろいろに変わること。fluctuate は上下をくり返す"}]},

  {id:1600,word:"distort",partOfSpeech:"他動詞",meaning:"歪める，ねじ曲げる",
   meanings:["他|（形や事実）を歪める，ねじ曲げる"],
   pronunciation:"/dɪˈstɔːrt/",part:160,
   example:"Some newspapers distort the facts to sell more copies.",
   exampleJa:"事実を歪めて売り上げを伸ばそうとする新聞もある。",
   example2:"The old mirror distorted my face in a funny way.",
   exampleJa2:"その古い鏡は、私の顔をおかしな形に歪めた。",
   etymologyProcess:"dis（バラバラに）＋ tort（ねじる）→ ねじって形をくずすと…？",
   etymologyConclusion:"dis（バラバラに）＋ tort（ねじる）→ ねじって本来の形をくずしてしまう＝歪める",
   relatedWords:[
     {word:"torture",meaning:"拷問",breakdown:"tort（ねじる）＋ ure（名詞）→ 体をねじり上げて痛めつけること"},
     {word:"torch",meaning:"たいまつ",breakdown:"tort（ねじる）→ わらをねじって作った明かり"},
     {word:"torment",meaning:"苦痛；苦しめる",breakdown:"tort（ねじる）＋ ment（名詞）→ ねじり上げる責め苦"},
     {synonym:true,word:"twist",meaning:"ねじる，曲げる",breakdown:"ねじること。distort は形や事実を正しくなくする"}]},

  {id:1601,word:"crack",partOfSpeech:"自動詞",meaning:"ひびが入る，割れる",
   meanings:["自|ひびが入る，割れる","他|～にひびを入れる；（難問）を解く","名|ひび，割れ目"],
   pronunciation:"/kræk/",part:161,
   example:"The ice on the pond began to crack under his feet.",
   exampleJa:"彼の足元で、池の氷にひびが入り始めた。",
   example2:"It took the police a year to crack the case.",
   exampleJa2:"警察がその事件を解決するのに1年かかった。",
   etymologyProcess:"crack（パキッという音）→ パキッと鳴って表面に筋が走ると…？",
   etymologyConclusion:"crack（パキッという音）→ パキッと鳴って表面に割れ目が走る＝ひびが入る",
   hook:"古英語 cracian から。割れる音をまねた語。「クラッカー」も割るとパキッと鳴る。",
   relatedWords:[
     {synonym:true,word:"break",meaning:"壊れる，割れる",breakdown:"壊れること全般。crack はひびが入るだけのことも多い"},
     {synonym:true,word:"split",meaning:"裂ける",breakdown:"二つに分かれる。crack は筋状の割れ目ができる"},
     {synonym:true,word:"shatter",meaning:"粉々に割れる",breakdown:"こなごなになる。crack はひびの段階"},
     {synonym:true,word:"solve",meaning:"解く",breakdown:"問題を解くこと。crack は難問を解き明かす"}]},

  {id:1602,word:"transition",partOfSpeech:"名詞",meaning:"（段階の）移行，過渡期",
   meanings:["名|（段階の）移行，移り変わり","名|過渡期"],
   pronunciation:"/trænˈzɪʃn/",part:161,
   example:"The transition from high school to college can be difficult.",
   exampleJa:"高校から大学への移行は難しいことがある。",
   example2:"The country is in a period of political transition.",
   exampleJa2:"その国は政治の過渡期にある。",
   etymologyProcess:"trans（越えて）＋ it（行く）＋ ion（名詞）→ ある状態から次の状態へ越えて行くと…？",
   etymologyConclusion:"trans（越えて）＋ it（行く）＋ ion（名詞）→ ある段階から次の段階へ越えて行くこと＝（段階の）移行",
   relatedWords:[
     {word:"transit",meaning:"通過，輸送",breakdown:"trans（越えて）＋ it（行く）→ 向こうへ越えて行くこと"},
     {word:"exit",meaning:"出口",breakdown:"ex（外へ）＋ it（行く）→ 外へ出ていくところ"},
     {word:"initial",meaning:"最初の",breakdown:"in（中へ）＋ it（行く）＋ al（形容詞）→ いちばん先に中へ入る"},
     {synonym:true,word:"shift",meaning:"転換，移り変わり",breakdown:"向きや位置の変化。transition は段階を移る過程"}]},

  {id:1603,word:"game-changer",partOfSpeech:"名詞",meaning:"状況を一変させるもの，革命的なこと",
   meanings:["名|状況を一変させるもの，革命的なこと"],
   pronunciation:"/ˈɡeɪmˌtʃeɪndʒər/",part:161,
   example:"The smartphone was a real game-changer for how we communicate.",
   exampleJa:"スマートフォンは、私たちの連絡の取り方を一変させるものだった。",
   example2:"Our new coach turned out to be a game-changer for the team.",
   exampleJa2:"新しいコーチは、チームにとって状況を一変させる存在になった。",
   etymologyProcess:"game（試合）＋ chang（取りかえる）＋ er（もの）→ 試合の流れそのものを変えてしまうのは…？",
   etymologyConclusion:"game（試合）＋ chang（取りかえる）＋ er（もの）→ 試合の流れそのものをひっくり返すもの＝状況を一変させるもの",
   relatedWords:[
     {word:"change",meaning:"変える",breakdown:"chang（取りかえる）→ 別のものに取りかえる"},
     {word:"exchange",meaning:"交換する",breakdown:"ex（外へ）＋ chang（取りかえる）→ 手元の物を出して取りかえる"},
     {synonym:true,word:"breakthrough",meaning:"大発見，突破口",breakdown:"壁を破る新しい発見。game-changer は流れを変えるもの"},
     {synonym:true,word:"revolution",meaning:"革命",breakdown:"大きくひっくり返すこと。game-changer はくだけた言い方"}]},

  {id:1604,word:"reinforce",partOfSpeech:"他動詞",meaning:"補強する，強化する",
   meanings:["他|～を補強する，強化する"],
   pronunciation:"/ˌriːɪnˈfɔːrs/",part:161,
   example:"Workers used steel bars to reinforce the old bridge.",
   exampleJa:"作業員たちは鉄の棒を使って古い橋を補強した。",
   example2:"The experience reinforced her belief in hard work.",
   exampleJa2:"その経験で、努力が大切だという彼女の信念はいっそう強化された。",
   etymologyProcess:"re（再び）＋ in（中に）＋ force（力）→ もう一度中に力を入れると…？",
   etymologyConclusion:"re（再び）＋ in（中に）＋ force（力）→ もう一度中に力を足して強くする＝補強する",
   relatedWords:[
     {word:"enforce",meaning:"施行する",breakdown:"en（～にする）＋ force（力）→ 決まりに力を持たせる"},
     {word:"effort",meaning:"努力",breakdown:"ex（外へ）＋ fort（力）→ 力を外へ出しきること"},
     {word:"comfort",meaning:"慰め；快適さ",breakdown:"com（強く）＋ fort（力）→ 心に力をつけてやること"},
     {synonym:true,word:"strengthen",meaning:"強くする",breakdown:"強くすること全般。reinforce は足りない所を足して強める"}]},

  {id:1605,word:"foster",partOfSpeech:"他動詞",meaning:"（才能などを）育成する；（里子を）育てる",
   meanings:["他|（才能や関係など）を育成する，促進する","他|（里子）を育てる","形|里親の"],
   pronunciation:"/ˈfɔːstər/",part:161,
   example:"Our school tries to foster creativity in every student.",
   exampleJa:"私たちの学校は、すべての生徒の創造力を育成しようとしている。",
   example2:"The couple fostered two young children for several years.",
   exampleJa2:"その夫婦は数年間、2人の幼い子どもを里子として育てた。",
   etymologyProcess:"foster（食べ物を与える）→ 食べさせて大きく育てると…？",
   etymologyConclusion:"foster（食べ物を与える）→ 食べさせて面倒を見て大きく育てる＝（才能などを）育成する",
   hook:"古英語 fostor（食べ物）から。food と同じ仲間。foster parents は「里親」。",
   relatedWords:[
     {synonym:true,word:"nurture",meaning:"育てる",breakdown:"大切に育てること。foster は発達をうながす"},
     {synonym:true,word:"encourage",meaning:"励ます，促す",breakdown:"勇気づけること。foster は長く育てていく"},
     {synonym:true,word:"promote",meaning:"促進する",breakdown:"前へ進めること。foster は育つのを助ける"},
     {synonym:true,word:"raise",meaning:"育てる",breakdown:"子どもを育てる。foster は実の子でない子を育てる"}]},

  {id:1606,word:"breakdown",partOfSpeech:"名詞",meaning:"（機能の）崩壊，故障；内訳",
   meanings:["名|（機能の）崩壊，故障","名|（心身の）衰弱","名|内訳，分析"],
   pronunciation:"/ˈbreɪkdaʊn/",part:161,
   example:"The breakdown of the old system caused a lot of confusion.",
   exampleJa:"古い仕組みの崩壊は、大きな混乱を引き起こした。",
   example2:"Our bus had a breakdown on the way to the stadium.",
   exampleJa2:"スタジアムへ向かう途中で、私たちのバスが故障した。",
   etymologyProcess:"break（破る）＋ down（下へ）→ 破れて下へくずれ落ちると…？",
   etymologyConclusion:"break（破る）＋ down（下へ）→ 仕組みが破れて下へくずれ落ちる＝（機能の）崩壊",
   relatedWords:[
     {word:"break",meaning:"壊す",breakdown:"break（破る）→ 力を加えてばらばらにする"},
     {word:"outbreak",meaning:"（戦争などの）発生",breakdown:"out（外へ）＋ break（破る）→ 破って外へ噴き出すこと"},
     {word:"download",meaning:"ダウンロードする",breakdown:"down（下へ）＋ load（積んで運ぶ）→ データを手元へ下ろす"},
     {synonym:true,word:"failure",meaning:"故障，失敗",breakdown:"うまく働かないこと。breakdown は完全に止まる"}]},

  {id:1607,word:"collapse",partOfSpeech:"自動詞",meaning:"崩壊する，倒れる",
   meanings:["自|崩壊する，崩れ落ちる","自|（人が）倒れる","名|崩壊"],
   pronunciation:"/kəˈlæps/",part:161,
   example:"The old bridge could collapse in a strong earthquake.",
   exampleJa:"強い地震が来れば、その古い橋は崩壊するかもしれない。",
   example2:"The runner collapsed just after crossing the finish line.",
   exampleJa2:"その走者はゴールした直後に倒れた。",
   etymologyProcess:"col（共に）＋ lapse（すべり落ちる）→ 全体が一緒にすべり落ちると…？",
   etymologyConclusion:"col（共に）＋ lapse（すべり落ちる）→ 全体が一度にすべり落ちてくずれる＝崩壊する",
   relatedWords:[
     {word:"lapse",meaning:"（ちょっとした）誤り；経過",breakdown:"lapse（すべり落ちる）→ うっかりすべり落ちること"},
     {word:"elapse",meaning:"（時が）経つ",breakdown:"e（外へ）＋ lapse（すべり落ちる）→ 時がすべるように過ぎ去る"},
     {synonym:true,word:"fall down",meaning:"倒れる",breakdown:"下へ倒れる。collapse は全体が崩れる"},
     {synonym:true,word:"crumble",meaning:"ぼろぼろに崩れる",breakdown:"少しずつ崩れる。collapse は一気に崩れる"}]},

  {id:1608,word:"render",partOfSpeech:"他動詞",meaning:"（O を C に）する；与える",
   meanings:["他|（render O C で）O を C にする","他|～を与える，提供する"],
   pronunciation:"/ˈrendər/",part:161,
   example:"The heavy rain rendered the road impossible to use.",
   exampleJa:"大雨のせいで、その道路は使えなくなった。",
   example2:"We thank you for the services rendered to our school.",
   exampleJa2:"本校に与えてくださったご支援に感謝いたします。",
   etymologyProcess:"render（渡す）→ ある状態を相手に渡して変えてしまうと…？",
   etymologyConclusion:"render（渡す）→ ある状態を相手に渡して、そのように変えてしまう＝（O を C に）する",
   why:"【なぜ】ラテン語 reddere は re（戻す）＋ dare（与える）で「返す・渡す」。フランス語 rendre を通って英語に入りました。「相手に渡す」から「ある状態にして渡す」＝O を C にする、の意味が生まれました。\n【つながり】surrender（すべてを渡す→降伏する）、rent（払い渡すお金）も同じ家族です。",
   relatedWords:[
     {word:"surrender",meaning:"降伏する",breakdown:"sur（上から）＋ render（渡す）→ 武器も身も相手に渡す"},
     {word:"rendition",meaning:"演奏，表現",breakdown:"render（渡す）＋ ion（名詞）→ 曲を聴き手に渡すこと"},
     {synonym:true,word:"make",meaning:"（O を C に）する",breakdown:"ふつうの言い方。render はかたい語"},
     {synonym:true,word:"provide",meaning:"提供する",breakdown:"必要なものを与える。render はかたい言い方"}]},

  {id:1609,word:"impair",partOfSpeech:"他動詞",meaning:"（能力などを）低下させる，損なう",
   meanings:["他|（能力など）を低下させる，損なう"],
   pronunciation:"/ɪmˈper/",part:161,
   example:"Lack of sleep can impair your ability to concentrate.",
   exampleJa:"睡眠不足は集中する力を低下させることがある。",
   example2:"His hearing was impaired by years of loud music.",
   exampleJa2:"長年の大音量の音楽で、彼の聴力は損なわれた。",
   etymologyProcess:"impair（より悪くする）→ 今よりも悪い状態にすると…？",
   etymologyConclusion:"impair（より悪くする）→ 力や働きを今より悪い状態にする＝（能力などを）低下させる",
   why:"【なぜ】ラテン語 pejor（より悪い）から作られた impejorare（悪くする）が、フランス語 empeirer を通って入りました。今の綴りの pair は「一対」の pair とは関係ありません。\n【つながり】pejorative（軽蔑的な）が pejor の仲間。visually impaired（目の不自由な）の形でもよく使います。",
   relatedWords:[
     {word:"impairment",meaning:"障害，損傷",breakdown:"impair（より悪くする）＋ ment（名詞）→ 働きが悪くなった状態"},
     {synonym:true,word:"damage",meaning:"損害を与える",breakdown:"傷つけること全般。impair は働きを弱める"},
     {synonym:true,word:"weaken",meaning:"弱める",breakdown:"力を弱くする。impair は能力が落ちること"},
     {synonym:true,word:"harm",meaning:"害する",breakdown:"害を与えること。impair は機能を損なう"}]},

  {id:1610,word:"undermine",partOfSpeech:"他動詞",meaning:"（徐々に）弱める，むしばむ",
   meanings:["他|（自信や地位など）を徐々に弱める，むしばむ"],
   pronunciation:"/ˌʌndərˈmaɪn/",part:161,
   example:"Constant criticism from parents can undermine a child's confidence.",
   exampleJa:"親からいつも批判されていると、子どもの自信は弱められてしまうことがある。",
   example2:"The scandal undermined public trust in the government.",
   exampleJa2:"そのスキャンダルは、政府への国民の信頼を弱めた。",
   etymologyProcess:"under（下に）＋ mine（鉱石を掘る）→ 城壁の下を掘り進めると…？",
   etymologyConclusion:"under（下に）＋ mine（鉱石を掘る）→ 下から少しずつ掘ってくずしていく＝（徐々に）弱める",
   why:"【なぜ】中世の戦いでは、城を攻めるとき城壁の下にトンネルを掘り、土台を崩して壁を倒しました。この「下を掘る」が undermine のもとの意味。そこから「気づかれないうちに土台を崩す」＝徐々に弱める、になりました。\n【つながり】mine（鉱山）、mineral（鉱物）は「掘る」の仲間。地雷を mine と呼ぶのも、地下に掘って埋めたことから。",
   relatedWords:[
     {word:"mineral",meaning:"鉱物",breakdown:"mine（鉱石を掘る）＋ al（名詞）→ 掘り出したもの"},
     {word:"understand",meaning:"理解する",breakdown:"under（下に）＋ stand（立つ）→ 物事の下に立ち、根っこからつかむ"},
     {word:"undertake",meaning:"引き受ける",breakdown:"under（下に）＋ take（取る）→ 仕事の下へ入って担ぎ取る"},
     {synonym:true,word:"weaken",meaning:"弱める",breakdown:"弱くすること全般。undermine は気づかれないうちに弱める"}]},

  {id:1611,word:"cope",partOfSpeech:"自動詞",meaning:"（with ～に）うまく対処する",
   meanings:["自|（with ～に）うまく対処する，何とか切り抜ける"],
   pronunciation:"/koʊp/",part:162,
   example:"Many students find it hard to cope with exam stress.",
   exampleJa:"試験のストレスにうまく対処するのが難しいと感じる生徒は多い。",
   example2:"The small hospital could not cope with so many patients.",
   exampleJa2:"その小さな病院では、それほど多くの患者にうまく対処しきれなかった。",
   etymologyProcess:"cope（打ち合う）→ 困難と打ち合って負けずにいると…？",
   etymologyConclusion:"cope（打ち合う）→ 困難と打ち合いながら何とか持ちこたえる＝（with ～に）うまく対処する",
   hook:"古いフランス語 coper（打つ）から。cope with ～ の形でひとまとまりに覚える。",
   relatedWords:[
     {synonym:true,word:"deal with",meaning:"対処する",breakdown:"問題を処理する。cope with は苦労してしのぐ感じ"},
     {synonym:true,word:"handle",meaning:"扱う",breakdown:"うまく扱うこと。cope は大変な状況を切り抜ける"},
     {synonym:true,word:"manage",meaning:"何とかやる",breakdown:"何とかやりくりする。cope とほぼ同じ感じで使う"},
     {synonym:true,word:"get by",meaning:"何とかやっていく",breakdown:"くだけた言い方。cope は困難に対処する"}]},

  {id:1612,word:"tackle",partOfSpeech:"他動詞",meaning:"（難しい問題に）取り組む；タックルする",
   meanings:["他|（難しい問題など）に取り組む","他|～にタックルする","名|道具一式"],
   pronunciation:"/ˈtækl/",part:162,
   example:"The government must tackle the problem of rising prices.",
   exampleJa:"政府は物価上昇の問題に取り組まなければならない。",
   example2:"He tackled the player and took the ball away.",
   exampleJa2:"彼はその選手にタックルしてボールを奪った。",
   etymologyProcess:"tackle（道具一式）→ 道具から「つかむ」意味が生まれ、相手に組みつくと…？",
   etymologyConclusion:"tackle（道具一式）→ 相手に組みつくように、難題に正面から組みつく＝（難しい問題に）取り組む",
   hook:"もとは「釣り道具・船の滑車」。組みついて取り押さえる意味から「取り組む」へ。",
   relatedWords:[
     {synonym:true,word:"deal with",meaning:"対処する",breakdown:"処理すること。tackle は正面から立ち向かう"},
     {synonym:true,word:"address",meaning:"取り組む",breakdown:"問題として扱う。tackle より少しかたい"},
     {synonym:true,word:"handle",meaning:"扱う",breakdown:"うまく処理する。tackle は難題に挑む"},
     {synonym:true,word:"confront",meaning:"立ち向かう",breakdown:"正面から向き合う。tackle は解決へ動き出す"}]},

  {id:1613,word:"demolish",partOfSpeech:"他動詞",meaning:"（建物を）取り壊す；（説を）くつがえす",
   meanings:["他|（建物）を取り壊す","他|（説など）をくつがえす"],
   pronunciation:"/dɪˈmɑːlɪʃ/",part:162,
   example:"The city plans to demolish the old stadium next year.",
   exampleJa:"市は来年、古い競技場を取り壊す予定だ。",
   example2:"New evidence from the lab demolished his theory completely.",
   exampleJa2:"研究所から出た新しい証拠が、彼の説を完全にくつがえした。",
   etymologyProcess:"de（逆に）＋ mol（かたまり）＋ ish（～にする）→ 積み上げたかたまりを逆にくずすと…？",
   etymologyConclusion:"de（逆に）＋ mol（かたまり）＋ ish（～にする）→ 積み上げたかたまりをくずして平らにする＝（建物を）取り壊す",
   relatedWords:[
     {word:"molecule",meaning:"分子",breakdown:"mol（かたまり）＋ cule（小さいもの）→ 小さなかたまり"},
     {word:"demolition",meaning:"取り壊し",breakdown:"de（逆に）＋ mol（かたまり）＋ ion（名詞）→ 建物をくずすこと"},
     {synonym:true,word:"destroy",meaning:"破壊する",breakdown:"壊すこと全般。demolish は建物を計画的に壊す"},
     {synonym:true,word:"tear down",meaning:"取り壊す",breakdown:"ふつうの言い方。demolish はかたい語"}]},

  {id:1614,word:"confine",partOfSpeech:"他動詞",meaning:"閉じ込める；（範囲を）限定する",
   meanings:["他|～を閉じ込める","他|（to ～に）限定する"],
   pronunciation:"/kənˈfaɪn/",part:162,
   example:"The sick dog was confined to a small cage.",
   exampleJa:"病気の犬は小さなおりに閉じ込められた。",
   example2:"Please confine your speech to five minutes or less.",
   exampleJa2:"スピーチは5分以内に限定してください。",
   etymologyProcess:"con（共に）＋ fin（終わり）→ 境目の内側に閉じこめると…？",
   etymologyConclusion:"con（共に）＋ fin（終わり）→ 境目で囲んだ内側から出さない＝閉じ込める",
   relatedWords:[
     {word:"final",meaning:"最後の",breakdown:"fin（終わり）＋ al（形容詞）→ いちばん終わりの"},
     {word:"finish",meaning:"終える",breakdown:"fin（終わり）＋ ish（～にする）→ 終わりにする"},
     {word:"define",meaning:"定義する",breakdown:"de（すっかり）＋ fin（終わり）→ 意味の境目をはっきり決める"},
     {synonym:true,word:"limit",meaning:"制限する",breakdown:"範囲を決めること。confine は中に閉じこめる"}]},

  {id:1615,word:"designate",partOfSpeech:"他動詞",meaning:"（正式に）指定する，任命する",
   meanings:["他|～を（正式に）指定する","他|（as ～に）任命する"],
   pronunciation:"/ˈdezɪɡneɪt/",part:162,
   example:"The area was designated as a national park in 1950.",
   exampleJa:"その地域は1950年に国立公園に指定された。",
   example2:"The teacher will designate a leader for each group.",
   exampleJa2:"先生は各グループのリーダーを指定（指名）するだろう。",
   etymologyProcess:"de（下へ）＋ sign（しるし）＋ ate（動詞）→ これだとしるしをつけて示すと…？",
   etymologyConclusion:"de（下へ）＋ sign（しるし）＋ ate（動詞）→ これだとしるしをつけて正式に示す＝（正式に）指定する",
   relatedWords:[
     {word:"sign",meaning:"しるし；署名する",breakdown:"sign（しるし）→ 目に見える印"},
     {word:"signal",meaning:"合図",breakdown:"sign（しるし）＋ al（名詞）→ しるしで伝えるもの"},
     {word:"design",meaning:"設計する",breakdown:"de（下へ）＋ sign（しるし）→ 図にしるしを書きこむ"},
     {synonym:true,word:"appoint",meaning:"任命する",breakdown:"役に就かせる。designate は正式に名指しする"}]},

  {id:1616,word:"regulate",partOfSpeech:"他動詞",meaning:"規制する；調整する",
   meanings:["他|～を（規則で）規制する","他|（温度など）を調整する"],
   pronunciation:"/ˈreɡjuleɪt/",part:162,
   example:"The government strictly regulates the sale of medicine.",
   exampleJa:"政府は薬の販売を厳しく規制している。",
   example2:"This machine helps regulate the temperature of the room.",
   exampleJa2:"この機械は部屋の温度を調整するのに役立つ。",
   etymologyProcess:"regul（まっすぐな棒）＋ ate（動詞）→ 定規を当ててまっすぐに整えると…？",
   etymologyConclusion:"regul（まっすぐな棒）＋ ate（動詞）→ 定規を当てるように決まりで整える＝規制する",
   relatedWords:[
     {word:"regular",meaning:"規則正しい",breakdown:"regul（まっすぐな棒）＋ ar（形容詞）→ 定規のようにきちんとした"},
     {word:"regulation",meaning:"規則",breakdown:"regul（まっすぐな棒）＋ ation（名詞）→ 整えるための決まり"},
     {word:"reign",meaning:"治世",breakdown:"reg（治める）→ 王として国を治めること"},
     {synonym:true,word:"control",meaning:"管理する",breakdown:"思いどおりに操る。regulate は決まりで整える"}]},

  {id:1617,word:"refrain",partOfSpeech:"自動詞",meaning:"（from ～を）控える，慎む",
   meanings:["自|（from ～を）控える，慎む","名|（歌の）くり返し部分"],
   pronunciation:"/rɪˈfreɪn/",part:162,
   example:"Please refrain from using your phone during the concert.",
   exampleJa:"コンサート中は携帯電話の使用を控えてください。",
   example2:"He refrained from saying anything rude to his boss.",
   exampleJa2:"彼は上司に失礼なことを言うのを慎んだ。",
   etymologyProcess:"refrain（手綱で引き止める）→ 手綱を後ろへ引いて自分を止めると…？",
   etymologyConclusion:"refrain（手綱で引き止める）→ 手綱を引くように自分の動きを抑える＝（from ～を）控える",
   hook:"refrain from ～ing の形で使う。掲示や放送の「ご遠慮ください」の言い方。",
   why:"【なぜ】ラテン語 refrenare は re（後ろへ）＋ frenum（馬のくつわ・手綱）で、「手綱を引いて馬を止める」こと。馬を抑えるように自分の気持ちや行動を抑えることから、「控える・慎む」になりました。\n【つながり】歌の「リフレイン（くり返し部分）」は、つづりが同じだけで別の語源（「くだけて返る」の意味）です。",
   relatedWords:[
     {synonym:true,word:"avoid",meaning:"避ける",breakdown:"近づかないこと。refrain は自分から我慢して控える"},
     {synonym:true,word:"abstain",meaning:"慎む，棄権する",breakdown:"かたい言い方。refrain とほぼ同じ"},
     {synonym:true,word:"hold back",meaning:"抑える",breakdown:"くだけた言い方。refrain はていねいな依頼に使う"},
     {synonym:true,word:"restrain",meaning:"抑える",breakdown:"自分や相手の動きを抑えつける。refrain は自分から控える"}]},

  {id:1618,word:"prohibit",partOfSpeech:"他動詞",meaning:"（法や規則で）禁じる",
   meanings:["他|（法や規則で）～を禁じる"],
   pronunciation:"/proʊˈhɪbɪt/",part:162,
   example:"The new law prohibits smoking in all restaurants and cafes.",
   exampleJa:"新しい法律は、すべてのレストランとカフェでの喫煙を禁じている。",
   example2:"Students are prohibited from using phones during tests.",
   exampleJa2:"生徒はテスト中に携帯電話を使うことを禁じられている。",
   etymologyProcess:"pro（前へ）＋ hibit（持つ）→ 前に手を出して止めておくと…？",
   etymologyConclusion:"pro（前へ）＋ hibit（持つ）→ 前に手を出して押しとどめる＝（法や規則で）禁じる",
   relatedWords:[
     {word:"exhibit",meaning:"展示する",breakdown:"ex（外へ）＋ hibit（持つ）→ 外へ持ち出して見せる"},
     {word:"inhibit",meaning:"抑制する",breakdown:"in（中へ）＋ hibit（持つ）→ 中に押さえておく"},
     {word:"habit",meaning:"習慣",breakdown:"habit（持ち続ける）→ ずっと持ち続けているやり方"},
     {synonym:true,word:"ban",meaning:"禁止する",breakdown:"公式に禁じる。prohibit は法や規則で禁じる"}]},

  {id:1619,word:"halt",partOfSpeech:"他動詞・自動詞",meaning:"止める，止まる",
   meanings:["他|～を止める","自|止まる","名|停止"],
   pronunciation:"/hɔːlt/",part:162,
   example:"The strike could halt production at the factory.",
   exampleJa:"ストライキで工場の生産が止まるかもしれない。",
   example2:"The referee halted the game because of the heavy rain.",
   exampleJa2:"大雨のため、審判は試合を止めた。",
   etymologyProcess:"halt（立ち止まる）→ 進むのをやめてその場にとどまると…？",
   etymologyConclusion:"halt（立ち止まる）→ 進むのをやめてその場にぴたりととどまる＝止める",
   hook:"ドイツ語 halten（保つ）の軍隊用語 Halt machen（止まる）から。号令「Halt!」でおなじみ。",
   relatedWords:[
     {synonym:true,word:"stop",meaning:"止める",breakdown:"ふつうの言い方。halt は急に完全に止める"},
     {synonym:true,word:"pause",meaning:"一時停止する",breakdown:"少しの間止まる。halt は止めたままにする"},
     {synonym:true,word:"suspend",meaning:"一時停止する",breakdown:"一時的にやめる。halt は動きをぴたりと止める"},
     {synonym:true,word:"cease",meaning:"やめる",breakdown:"かたい言い方で終わること。halt は急な停止"}]},

  {id:1620,word:"constraint",partOfSpeech:"名詞",meaning:"制約，制限",
   meanings:["名|制約，制限"],
   pronunciation:"/kənˈstreɪnt/",part:162,
   example:"Time constraints forced us to shorten the meeting.",
   exampleJa:"時間の制約のため、私たちは会議を短くしなければならなかった。",
   example2:"Budget constraints stopped the city from building a new pool.",
   exampleJa2:"予算の制約で、市は新しいプールを作れなかった。",
   etymologyProcess:"con（共に）＋ strain（締めつける）→ まわりからぎゅっと締めつけると…？",
   etymologyConclusion:"con（共に）＋ strain（締めつける）→ まわりからぎゅっと締めつけて自由を狭めるもの＝制約",
   relatedWords:[
     {word:"strict",meaning:"厳しい",breakdown:"strict（締めつける）→ ゆるみを許さず、きつく締める"},
     {word:"restrict",meaning:"制限する",breakdown:"re（強く）＋ strict（締めつける）→ 範囲を強く締めて外へ出さない"},
     {word:"strain",meaning:"負担；緊張",breakdown:"strain（締めつける）→ 引っぱられて張りつめた状態"},
     {synonym:true,word:"limitation",meaning:"限界，制限",breakdown:"ここまでという限り。constraint は外から縛るもの"}]},

  {id:1621,word:"stimulate",partOfSpeech:"他動詞",meaning:"刺激する，活発にする",
   meanings:["他|～を刺激する，活発にする","他|（to do するよう）～を励ます"],
   pronunciation:"/ˈstɪmjuleɪt/",part:163,
   example:"Lower taxes may stimulate the economy of the region.",
   exampleJa:"減税はその地域の経済を刺激するかもしれない。",
   example2:"Good books stimulated her interest in science as a child.",
   exampleJa2:"子どものころ、良い本が彼女の科学への興味を刺激した。",
   etymologyProcess:"stimul（突き棒）＋ ate（動詞）→ 突き棒でつついて動かすと…？",
   etymologyConclusion:"stimul（突き棒）＋ ate（動詞）→ 突き棒でつつくように動きを起こさせる＝刺激する",
   why:"【なぜ】ラテン語 stimulus は、牛や馬をつついて歩かせる先のとがった「突き棒」。そこから「つついて動かす」＝刺激する、になりました。\n【つながり】stimulus（刺激）はそのまま英語でも使います。つつかれて目が覚める感じが、今の「活発にする」の意味に残っています。",
   relatedWords:[
     {word:"stimulus",meaning:"刺激",breakdown:"stimul（突き棒）→ つついて動きを起こすもの"},
     {word:"stimulation",meaning:"刺激すること",breakdown:"stimul（突き棒）＋ ation（名詞）→ つついて動かすこと"},
     {synonym:true,word:"encourage",meaning:"励ます，促す",breakdown:"勇気づけること。stimulate は動きや働きを起こす"},
     {synonym:true,word:"boost",meaning:"押し上げる",breakdown:"勢いをつけて上げる。stimulate は活動を起こす"}]},

  {id:1622,word:"animate",partOfSpeech:"他動詞",meaning:"活気づける；アニメにする",
   meanings:["他|～を活気づける","他|～をアニメにする"],
   pronunciation:"/ˈænɪmeɪt/",part:163,
   example:"Her funny stories always animate the dinner table.",
   exampleJa:"彼女のおかしな話は、いつも夕食の席を活気づける。",
   example2:"Last year the studio animated a famous picture book.",
   exampleJa2:"昨年、そのスタジオは有名な絵本をアニメにした。",
   etymologyProcess:"anim（命・息）＋ ate（動詞）→ 命の息を吹きこむと…？",
   etymologyConclusion:"anim（命・息）＋ ate（動詞）→ 命の息を吹きこんで生き生きさせる＝活気づける",
   relatedWords:[
     {word:"animal",meaning:"動物",breakdown:"anim（命・息）＋ al（名詞）→ 息をして生きているもの"},
     {word:"animation",meaning:"アニメ；活気",breakdown:"anim（命・息）＋ ation（名詞）→ 絵に命を吹きこんだもの"},
     {word:"inanimate",meaning:"命のない",breakdown:"in（否定）＋ anim（命・息）＋ ate（形容詞）→ 命の息が通っていない"},
     {synonym:true,word:"enliven",meaning:"活気づける",breakdown:"生き生きさせる。animate とほぼ同じ"}]},

  {id:1623,word:"spur",partOfSpeech:"他動詞",meaning:"（人を）駆り立てる，拍車をかける",
   meanings:["他|～を駆り立てる，拍車をかける","名|拍車；刺激"],
   pronunciation:"/spɜːr/",part:163,
   example:"Low prices may spur more people to buy electric cars.",
   exampleJa:"安い値段が、もっと多くの人を電気自動車の購入へ駆り立てるかもしれない。",
   example2:"His failure spurred him to work even harder.",
   exampleJa2:"失敗が、彼をいっそうの努力へと駆り立てた。",
   etymologyProcess:"spur（馬のかかとの拍車）→ かかとの金具で馬の腹をけると…？",
   etymologyConclusion:"spur（馬のかかとの拍車）→ かかとの金具で馬をけって走らせる＝（人を）駆り立てる",
   hook:"古英語 spura から。on the spur of the moment は「その場の勢いで」。",
   relatedWords:[
     {synonym:true,word:"motivate",meaning:"やる気にさせる",breakdown:"やる気を起こさせる。spur は急に強くかき立てる"},
     {synonym:true,word:"drive",meaning:"駆り立てる",breakdown:"強く押し進める。spur は刺激して速める"},
     {synonym:true,word:"prompt",meaning:"促す",breakdown:"行動のきっかけになる。spur はより勢いがある"},
     {synonym:true,word:"encourage",meaning:"励ます",breakdown:"勇気づけること。spur は強く後押しする"}]},

  {id:1624,word:"urge",partOfSpeech:"他動詞",meaning:"（強く）促す，せき立てる",
   meanings:["他|（to do するよう）～を強くせき立てる，促す","名|強い衝動"],
   pronunciation:"/ɜːrdʒ/",part:163,
   example:"Doctors urge people to wash their hands often.",
   exampleJa:"医師たちは人々に、こまめに手を洗うよう強く促している。",
   example2:"My coach urged me to keep running until the finish line.",
   exampleJa2:"コーチは私に、ゴールまで走り続けるよう促した。",
   etymologyProcess:"urg（強く押す）→ 後ろから強く押して急がせると…？",
   etymologyConclusion:"urg（強く押す）→ 後ろから強く押して急がせる＝（強く）促す",
   relatedWords:[
     {word:"urgent",meaning:"緊急の",breakdown:"urg（強く押す）＋ ent（～している）→ 強く押しせまっている"},
     {word:"urgency",meaning:"緊急性",breakdown:"urg（強く押す）＋ ency（名詞）→ 押しせまっている状態"},
     {synonym:true,word:"encourage",meaning:"励ます",breakdown:"勇気づけること。urge はもっと強く迫る"},
     {synonym:true,word:"press",meaning:"迫る",breakdown:"押しつけて求める。urge とほぼ同じ"}]},

  {id:1625,word:"compel",partOfSpeech:"他動詞",meaning:"（無理に）～させる",
   meanings:["他|（to do するよう）～に無理にさせる","他|（be compelled to do で）～せざるを得ない"],
   pronunciation:"/kəmˈpel/",part:163,
   example:"No one can compel you to join a club you dislike.",
   exampleJa:"嫌いな部に入ることを、だれもあなたに無理にさせることはできない。",
   example2:"The heavy rain compelled us to cancel the picnic.",
   exampleJa2:"大雨のせいで、私たちはピクニックを中止せざるを得なかった。",
   etymologyProcess:"com（強く）＋ pel（押しやる）→ 強く押しやって動かすと…？",
   etymologyConclusion:"com（強く）＋ pel（押しやる）→ 強く押しやって否応なく動かす＝（無理に）～させる",
   relatedWords:[
     {word:"expel",meaning:"追い出す",breakdown:"ex（外へ）＋ pel（押しやる）→ 外へ押し出す"},
     {word:"propel",meaning:"推進する",breakdown:"pro（前へ）＋ pel（押しやる）→ 前へ押し進める"},
     {word:"compulsory",meaning:"強制的な，義務の",breakdown:"com（強く）＋ puls（押しやる）＋ ory（形容詞）→ 押しつけられた"},
     {synonym:true,word:"force",meaning:"強いる",breakdown:"力ずくでさせる。compel は状況がそうさせる場合にも使う"}]},

  {id:1626,word:"blur",partOfSpeech:"他動詞・自動詞",meaning:"ぼやかす，ぼやける",
   meanings:["他|～をぼやかす","自|ぼやける","名|ぼんやりしたもの"],
   pronunciation:"/blɜːr/",part:163,
   example:"Tears began to blur her vision as she read the letter.",
   exampleJa:"手紙を読むうちに、涙で彼女の視界がぼやけ始めた。",
   example2:"The line between work and home life has blurred.",
   exampleJa2:"仕事と家庭生活の境目がぼやけてきている。",
   etymologyProcess:"blur（にじんだしみ）→ インクがにじんで形がはっきりしなくなると…？",
   etymologyConclusion:"blur（にじんだしみ）→ しみがにじんで形がはっきりしなくなる＝ぼやかす",
   hook:"16世紀の「しみ・汚れ」から。語源ははっきりしない。写真の「ブレ」をイメージ。",
   relatedWords:[
     {synonym:true,word:"fade",meaning:"ぼんやり消える",breakdown:"だんだん薄れる。blur は輪郭がにじむ"},
     {synonym:true,word:"cloud",meaning:"曇らせる",breakdown:"くもらせてはっきりしなくする。blur とほぼ同じ"},
     {synonym:true,word:"obscure",meaning:"見えにくくする",breakdown:"隠してわかりにくくする。blur は輪郭がぼける"},
     {synonym:true,word:"smudge",meaning:"にじませる",breakdown:"こすってにじませる。blur はもっと広くぼやける"}]},

  {id:1627,word:"divert",partOfSpeech:"他動詞",meaning:"（進路や注意を）そらす",
   meanings:["他|（進路など）をそらす，変える","他|（注意など）をそらす"],
   pronunciation:"/daɪˈvɜːrt/",part:163,
   example:"Police had to divert traffic because of the accident.",
   exampleJa:"事故のため、警察は車の流れを別の道へそらさなければならなかった。",
   example2:"He told a joke to divert attention from his mistake.",
   exampleJa2:"彼は自分のミスから注意をそらすために冗談を言った。",
   etymologyProcess:"di（離れて）＋ vert（回る）→ 向きを回して別のほうへ離すと…？",
   etymologyConclusion:"di（離れて）＋ vert（回る）→ 向きを回して本来の道から離す＝（進路や注意を）そらす",
   relatedWords:[
     {word:"convert",meaning:"転換する",breakdown:"con（すっかり）＋ vert（回る）→ すっかり向きを変える"},
     {word:"diverse",meaning:"さまざまな",breakdown:"di（離れて）＋ vers（回る）→ それぞれ別の方向へ向いた"},
     {word:"advertise",meaning:"宣伝する",breakdown:"ad（～へ）＋ vert（回る）→ 人の目をこちらへ向けさせる"},
     {synonym:true,word:"distract",meaning:"気をそらす",breakdown:"注意を散らす。divert は向きを変えてそらす"}]},

  {id:1628,word:"reverse",partOfSpeech:"他動詞",meaning:"逆にする，逆転させる；くつがえす",
   meanings:["他|～を逆にする，逆転させる","他|（決定など）をくつがえす","名|逆，反対"],
   pronunciation:"/rɪˈvɜːrs/",part:163,
   example:"The new manager tried to reverse the company's losses.",
   exampleJa:"新しい経営者は、会社の赤字の流れを逆転させようとした。",
   example2:"The court reversed its earlier decision last week.",
   exampleJa2:"裁判所は先週、以前の判決をくつがえした。",
   etymologyProcess:"re（後ろへ）＋ vers（回る）→ 向きを後ろへ回すと…？",
   etymologyConclusion:"re（後ろへ）＋ vers（回る）→ 向きをくるりと後ろへ回す＝逆にする",
   relatedWords:[
     {word:"version",meaning:"版，型",breakdown:"vers（回る）＋ ion（名詞）→ 形を変えて作ったもの"},
     {word:"universe",meaning:"宇宙",breakdown:"uni（1つの）＋ vers（回る）→ 1つの方向へ向けてまとめられた全体"},
     {word:"converse",meaning:"正反対",breakdown:"con（すっかり）＋ vers（回る）→ すっかりひっくり返したもの"},
     {synonym:true,word:"invert",meaning:"逆さにする",breakdown:"上下を入れかえる。reverse は向きや流れを逆にする"}]},

  {id:1629,word:"overshadow",partOfSpeech:"他動詞",meaning:"影を薄くさせる，見劣りさせる",
   meanings:["他|～の影を薄くさせる，見劣りさせる","他|～に暗い影を落とす"],
   pronunciation:"/ˌoʊvərˈʃædoʊ/",part:163,
   example:"Her brilliant younger sister always seemed to overshadow her.",
   exampleJa:"才能あふれる妹のかげで、彼女はいつも影が薄く見えた。",
   example2:"The school celebration was overshadowed by some sad news.",
   exampleJa2:"学校の祝賀会には、悲しい知らせが暗い影を落とした。",
   etymologyProcess:"over（越えて）＋ shadow（影）→ 上から覆いかぶさって影を落とすと…？",
   etymologyConclusion:"over（越えて）＋ shadow（影）→ 上から影を落として相手を目立たなくする＝影を薄くさせる",
   relatedWords:[
     {word:"shadow",meaning:"影",breakdown:"shadow（影）→ 光がさえぎられてできる暗い形"},
     {word:"overcome",meaning:"克服する",breakdown:"over（越えて）＋ come（来る）→ 困難を越えて向こうへ来る"},
     {word:"overlook",meaning:"見落とす",breakdown:"over（越えて）＋ look（見る）→ 上を越して見てしまい気づかない"},
     {synonym:true,word:"outshine",meaning:"～より輝く",breakdown:"相手より目立つ。overshadow は相手を暗くする"}]},

  {id:1630,word:"worsen",partOfSpeech:"他動詞・自動詞",meaning:"悪化させる，悪化する",
   meanings:["他|～を悪化させる","自|悪化する"],
   pronunciation:"/ˈwɜːrsn/",part:163,
   example:"Stress can worsen many kinds of health problems.",
   exampleJa:"ストレスは多くの種類の健康問題を悪化させることがある。",
   example2:"The weather worsened as we climbed higher up the mountain.",
   exampleJa2:"山を高く登るにつれて、天気は悪化した。",
   etymologyProcess:"worse（より悪い）＋ en（～にする）→ 今よりもっと悪くすると…？",
   etymologyConclusion:"worse（より悪い）＋ en（～にする）→ 今よりもっと悪い状態にする＝悪化させる",
   relatedWords:[
     {word:"worse",meaning:"より悪い",breakdown:"worse（より悪い）→ bad の比較級"},
     {word:"worst",meaning:"最も悪い",breakdown:"worse（より悪い）→ いちばん悪い"},
     {synonym:true,word:"aggravate",meaning:"悪化させる",breakdown:"重くしてさらに悪くする。worsen はより一般的"},
     {synonym:true,word:"deteriorate",meaning:"悪化する",breakdown:"だんだん質が落ちる。worsen はふつうの言い方"}]},

  {id:1631,word:"jeopardize",partOfSpeech:"他動詞",meaning:"（地位や安全を）危うくする",
   meanings:["他|（地位や安全など）を危うくする，危険にさらす"],
   pronunciation:"/ˈdʒepərdaɪz/",part:164,
   example:"One careless mistake could jeopardize your whole career.",
   exampleJa:"たった一つの不注意なミスが、あなたの経歴全体を危うくしかねない。",
   example2:"Smoking jeopardized his chances of making the team.",
   exampleJa2:"喫煙が、彼がチームに入れる見込みを危うくした。",
   etymologyProcess:"jeopard（五分五分の勝負）＋ ize（動詞）→ 勝つか負けるか分からない勝負に出すと…？",
   etymologyConclusion:"jeopard（五分五分の勝負）＋ ize（動詞）→ 大事なものを勝敗の分からない勝負にかける＝（地位や安全を）危うくする",
   why:"【なぜ】古いフランス語 jeu parti は「分かれた勝負」、つまり勝ち負けが五分五分の試合のこと。そこから英語の jeopardy が「どちらに転ぶか分からない危険」になりました。大切なものをその危険にさらすのが jeopardize です。\n【つながり】in jeopardy（危険にさらされて）の形でもよく使います。アメリカのクイズ番組の名前にもなっています。",
   relatedWords:[
     {word:"jeopardy",meaning:"危険",breakdown:"jeopard（五分五分の勝負）＋ y（名詞）→ どちらに転ぶか分からない危うさ"},
     {synonym:true,word:"endanger",meaning:"危険にさらす",breakdown:"危険な目にあわせる。jeopardize は成功や地位を危うくする"},
     {synonym:true,word:"risk",meaning:"危険にさらす",breakdown:"失うかもしれないことをする。jeopardize はより深刻"},
     {synonym:true,word:"threaten",meaning:"おびやかす",breakdown:"危害を加えそうになる。jeopardize は危うくする"}]},

  {id:1632,word:"supplement",partOfSpeech:"他動詞",meaning:"補う，追加する",
   meanings:["他|～を補う，追加する","名|補足；栄養補助食品"],
   pronunciation:"/ˈsʌplɪment/",part:164,
   example:"Many students supplement their income with part-time jobs.",
   exampleJa:"多くの学生は、アルバイトで収入を補っている。",
   example2:"She supplements her diet with vitamins every morning.",
   exampleJa2:"彼女は毎朝、ビタミン剤で食事の栄養を補っている。",
   etymologyProcess:"sup（下から）＋ ple（満たす）＋ ment（名詞）→ 足りない所を下から満たすと…？",
   etymologyConclusion:"sup（下から）＋ ple（満たす）＋ ment（名詞）→ 足りない所を下から満たすもの、それを加える＝補う",
   relatedWords:[
     {word:"supply",meaning:"供給する",breakdown:"sup（下から）＋ ply（満たす）→ 足りない所を下から満たす"},
     {word:"complete",meaning:"完成させる",breakdown:"com（すっかり）＋ ple（満たす）→ すっかり満たして仕上げる"},
     {word:"plenty",meaning:"たくさん",breakdown:"ple（満たす）＋ ty（名詞）→ 満ちあふれるほどの量"},
     {synonym:true,word:"add",meaning:"加える",breakdown:"付け足すこと全般。supplement は足りない所を補う"}]},

  {id:1633,word:"pose",partOfSpeech:"他動詞・自動詞",meaning:"（問題や危険を）もたらす；（質問を）出す",
   meanings:["他|（問題や危険）をもたらす","他|（質問）を出す","自|ポーズをとる"],
   pronunciation:"/poʊz/",part:164,
   example:"Rising sea levels pose a serious threat to island nations.",
   exampleJa:"海面の上昇は、島国に深刻な脅威をもたらしている。",
   example2:"The students posed for a photo in front of the gate.",
   exampleJa2:"生徒たちは門の前で写真のためにポーズをとった。",
   etymologyProcess:"pos（置く）→ 問題を目の前にどんと置くと…？",
   etymologyConclusion:"pos（置く）→ 問題や危険を相手の前にどんと置く＝（問題や危険を）もたらす",
   why:"【なぜ】フランス語 poser は、もとはラテン語 pausare（休む・止まる）から来た語ですが、意味の近いラテン語 ponere（置く）の形 positus とまざり、「置く」の意味で使われるようになりました。「問題を置く」から「問題をもたらす・質問を出す」、「体を止めて置く」から「ポーズをとる」になりました。\n【つながり】propose（前に置く→提案する）なども「置く」の仲間です。",
   relatedWords:[
     {word:"propose",meaning:"提案する",breakdown:"pro（前へ）＋ pos（置く）→ 考えを人前に置く"},
     {word:"expose",meaning:"さらす",breakdown:"ex（外へ）＋ pos（置く）→ 外に置いて見えるようにする"},
     {word:"position",meaning:"位置",breakdown:"pos（置く）＋ ion（名詞）→ 置かれている場所"},
     {synonym:true,word:"present",meaning:"示す，もたらす",breakdown:"目の前に出す。pose は問題や危険をもたらす"}]},

  {id:1634,word:"induce",partOfSpeech:"他動詞",meaning:"（ある状態を）引き起こす，誘発する；説得して～させる",
   meanings:["他|（ある状態）を誘発する，引き起こす","他|（to do するよう）～を説得する"],
   pronunciation:"/ɪnˈduːs/",part:164,
   example:"Some medicines can induce sleep within half an hour.",
   exampleJa:"薬の中には、30分以内に眠りを引き起こすものもある。",
   example2:"Nothing could induce him to change his mind.",
   exampleJa2:"何を言っても、彼に考えを変えさせることはできなかった。",
   etymologyProcess:"in（中へ）＋ duc（導く）→ ある状態の中へ導き入れると…？",
   etymologyConclusion:"in（中へ）＋ duc（導く）→ ある状態の中へ導き入れる＝（ある状態を）引き起こす",
   relatedWords:[
     {word:"produce",meaning:"生産する",breakdown:"pro（前へ）＋ duc（導く）→ 前へ導き出して生み出す"},
     {word:"reduce",meaning:"減らす",breakdown:"re（戻す）＋ duc（導く）→ 元の小さい状態へ導き戻す"},
     {word:"introduce",meaning:"紹介する",breakdown:"intro（中へ）＋ duc（導く）→ 人を輪の中へ導く"},
     {synonym:true,word:"cause",meaning:"引き起こす",breakdown:"原因となること。induce は薬などでわざと起こす"}]},

  {id:1635,word:"betray",partOfSpeech:"他動詞",meaning:"裏切る；（秘密を）もらす",
   meanings:["他|～を裏切る","他|（秘密）をもらす","他|（感情など）を思わず表す"],
   pronunciation:"/bɪˈtreɪ/",part:164,
   example:"I will never betray a friend who trusts me.",
   exampleJa:"私は、自分を信じてくれる友だちを決して裏切らない。",
   example2:"His shaking voice betrayed how nervous he was.",
   exampleJa2:"震える声で、彼がどれほど緊張しているかが表れてしまった。",
   etymologyProcess:"be（すっかり）＋ tray（引き渡す）→ 味方を敵の手にすっかり引き渡すと…？",
   etymologyConclusion:"be（すっかり）＋ tray（引き渡す）→ 味方を敵の手に引き渡してしまう＝裏切る",
   relatedWords:[
     {word:"traitor",meaning:"裏切り者",breakdown:"trait（引き渡す）＋ or（人）→ 味方を敵に引き渡す人"},
     {word:"tradition",meaning:"伝統",breakdown:"tra（向こうへ）＋ dit（与える）＋ ion（名詞）→ 次の世代へ引き渡されたもの"},
     {synonym:true,word:"deceive",meaning:"だます",breakdown:"うそで信じこませる。betray は信頼を裏切る"},
     {synonym:true,word:"let down",meaning:"がっかりさせる",breakdown:"期待を裏切る軽い言い方。betray は深刻な裏切り"}]},

  {id:1636,word:"bully",partOfSpeech:"他動詞",meaning:"いじめる，おどす",
   meanings:["他|～をいじめる，おどす","名|いじめっ子"],
   pronunciation:"/ˈbʊli/",part:164,
   example:"Nobody should ever bully a classmate for being different.",
   exampleJa:"違っているという理由でクラスメートをいじめてはいけない。",
   example2:"The school started a program to stop bullying.",
   exampleJa2:"その学校はいじめをなくすための取り組みを始めた。",
   etymologyProcess:"bully（いばる男）→ 強い者がいばって弱い者を押さえつけると…？",
   etymologyConclusion:"bully（いばる男）→ 強い立場の者が弱い者をいばって苦しめる＝いじめる",
   hook:"オランダ語 boel（恋人）からで、もとは「いい人」。やがて「いばる乱暴者」に変わった。",
   relatedWords:[
     {synonym:true,word:"harass",meaning:"嫌がらせをする",breakdown:"しつこく困らせる。bully は力で弱い者をいじめる"},
     {synonym:true,word:"tease",meaning:"からかう",breakdown:"ふざけてからかう。bully はもっと悪質"},
     {synonym:true,word:"threaten",meaning:"おどす",breakdown:"害を加えると言っておどす。bully はくり返し苦しめる"},
     {synonym:true,word:"pick on",meaning:"いじめる",breakdown:"くだけた言い方。bully とほぼ同じ"}]},

  {id:1637,word:"disregard",partOfSpeech:"他動詞",meaning:"（注意すべきものを）無視する，軽視する",
   meanings:["他|（注意すべきもの）を無視する，軽視する","名|無視，軽視"],
   pronunciation:"/ˌdɪsrɪˈɡɑːrd/",part:164,
   example:"Some drivers disregard the speed limit on this road.",
   exampleJa:"この道路では、制限速度を無視する運転手もいる。",
   example2:"He acted with complete disregard for his own safety.",
   exampleJa2:"彼は自分の身の安全をまったく軽視して行動した。",
   etymologyProcess:"dis（否定）＋ re（戻す）＋ gard（見張る）→ 気をつけて見ることをしないと…？",
   etymologyConclusion:"dis（否定）＋ re（戻す）＋ gard（見張る）→ 気にかけて見ることをしない＝（注意すべきものを）無視する",
   relatedWords:[
     {word:"regard",meaning:"みなす；配慮",breakdown:"re（戻す）＋ gard（見張る）→ 振り返ってよく見る"},
     {word:"guard",meaning:"見張る",breakdown:"gard（見張る）→ 気をつけて守る"},
     {word:"reward",meaning:"報酬",breakdown:"re（戻す）＋ ward（見張る）→ よく見て返してやるもの"},
     {synonym:true,word:"ignore",meaning:"無視する",breakdown:"わざと知らないふりをする。disregard はかたい言い方"}]},

  {id:1638,word:"squeeze",partOfSpeech:"他動詞・自動詞",meaning:"搾る，ぎゅっと握る；押しこむ",
   meanings:["他|～を搾る，ぎゅっと握る","他|（into ～に）押しこむ","自|（into ～に）無理に入りこむ"],
   pronunciation:"/skwiːz/",part:164,
   example:"Squeeze half a lemon over the fish before eating.",
   exampleJa:"食べる前に、魚の上でレモンを半分搾りなさい。",
   example2:"Ten of us squeezed into the tiny elevator.",
   exampleJa2:"私たち10人は小さなエレベーターに押しこまれるように乗った。",
   etymologyProcess:"squeeze（ぎゅっと押しつぶす）→ 両側から強く押して中身を出すと…？",
   etymologyConclusion:"squeeze（ぎゅっと押しつぶす）→ 両側から強く押して中身を出す＝搾る",
   hook:"古英語 cwysan（押しつぶす）から来たらしい。「スクイーズ」はレモン搾りでも使う。",
   relatedWords:[
     {synonym:true,word:"press",meaning:"押す",breakdown:"力を加えて押す。squeeze は両側からぎゅっと押す"},
     {synonym:true,word:"wring",meaning:"しぼる，ねじる",breakdown:"ねじってしぼる。squeeze は押してしぼる"},
     {synonym:true,word:"crush",meaning:"押しつぶす",breakdown:"形がなくなるまでつぶす。squeeze は中身を出す"},
     {synonym:true,word:"grip",meaning:"しっかり握る",breakdown:"つかんで離さない。squeeze は強く握りしめる"}]},

  {id:1639,word:"rub",partOfSpeech:"他動詞",meaning:"こする，すりこむ",
   meanings:["他|～をこする，すりこむ","自|すれる"],
   pronunciation:"/rʌb/",part:164,
   example:"She had to rub her tired eyes after studying all night.",
   exampleJa:"彼女は徹夜で勉強したあと、疲れた目をこすらずにいられなかった。",
   example2:"He rubbed some cream onto his dry hands.",
   exampleJa2:"彼は乾いた手にクリームをすりこんだ。",
   etymologyProcess:"rub（こすりつける）→ 表面を何度も行き来させると…？",
   etymologyConclusion:"rub（こすりつける）→ 手などを表面に当てて何度も行き来させる＝こする",
   hook:"中英語 rubben から。低地ドイツ語の似た語と関係があるらしい。",
   relatedWords:[
     {synonym:true,word:"scratch",meaning:"引っかく",breakdown:"つめでかく。rub は手のひらなどでこする"},
     {synonym:true,word:"wipe",meaning:"ふく",breakdown:"よごれをふき取る。rub は強くこする"},
     {synonym:true,word:"polish",meaning:"磨く",breakdown:"つやが出るまでこする。rub はこする動作全般"},
     {synonym:true,word:"stroke",meaning:"なでる",breakdown:"やさしくなでる。rub は押し当ててこする"}]},

  {id:1640,word:"smash",partOfSpeech:"他動詞・自動詞",meaning:"粉々に割る，粉砕する",
   meanings:["他|～を粉々に割る，粉砕する","自|粉々に割れる","名|大ヒット"],
   pronunciation:"/smæʃ/",part:164,
   example:"The angry man smashed the window with a rock.",
   exampleJa:"怒った男は石で窓を粉々に割った。",
   example2:"The glass fell and smashed on the kitchen floor.",
   exampleJa2:"グラスが落ちて、台所の床で粉々に割れた。",
   etymologyProcess:"smash（ガシャンという音）→ ガシャンと強く打ちつけて割ると…？",
   etymologyConclusion:"smash（ガシャンという音）→ ガシャンと強く打ちつけてばらばらにする＝粉々に割る",
   hook:"18世紀ごろの音まね語。テニスの「スマッシュ」も強く打ちつける打ち方。",
   relatedWords:[
     {synonym:true,word:"break",meaning:"壊す",breakdown:"壊すこと全般。smash は勢いよく粉々にする"},
     {synonym:true,word:"shatter",meaning:"粉々にする",breakdown:"ガラスなどが粉々に砕ける。smash は強く打つ感じ"},
     {synonym:true,word:"wreck",meaning:"めちゃめちゃに壊す",breakdown:"全体をだめにする。smash は打ちつけて粉々にする"},
     {synonym:true,word:"crush",meaning:"押しつぶす",breakdown:"押してつぶす。smash は打ちつけて割る"}]},

  {id:1641,word:"insert",partOfSpeech:"他動詞",meaning:"差し込む，挿入する",
   meanings:["他|（into ～に）差し込む，挿入する"],
   pronunciation:"/ɪnˈsɜːrt/",part:165,
   example:"Insert the card into the machine and enter your number.",
   exampleJa:"カードを機械に差し込んで、番号を入力してください。",
   example2:"The editor inserted a new paragraph into my essay.",
   exampleJa2:"編集者は私の作文に新しい段落を挿入した。",
   etymologyProcess:"in（中へ）＋ ser（つなぐ）→ 中へつなぎ入れると…？",
   etymologyConclusion:"in（中へ）＋ ser（つなぐ）→ すき間の中へ入れてつなぎこむ＝差し込む",
   relatedWords:[
     {word:"series",meaning:"シリーズ，連続",breakdown:"ser（つなぐ）＋ ies（名詞）→ 次々につながったもの"},
     {word:"desert",meaning:"見捨てる",breakdown:"de（離して）＋ ser（つなぐ）→ つながりを断って離れる"},
     {word:"insertion",meaning:"挿入",breakdown:"in（中へ）＋ ser（つなぐ）＋ ion（名詞）→ 中へつなぎ入れること"},
     {synonym:true,word:"put in",meaning:"入れる",breakdown:"ふつうの言い方。insert はすき間に差し込む"}]},

  {id:1642,word:"detach",partOfSpeech:"他動詞",meaning:"切り離す，取り外す",
   meanings:["他|（from ～から）切り離す，取り外す"],
   pronunciation:"/dɪˈtætʃ/",part:165,
   example:"You can detach the hood from this jacket.",
   exampleJa:"この上着からフードを切り離すことができる。",
   example2:"Please detach the bottom part of the form and return it.",
   exampleJa2:"用紙の下の部分を切り離して返送してください。",
   etymologyProcess:"de（離して）＋ tach（杭で留める）→ 留めてあったものを外して離すと…？",
   etymologyConclusion:"de（離して）＋ tach（杭で留める）→ 留めてあったものを外して離す＝切り離す",
   relatedWords:[
     {word:"attach",meaning:"取り付ける",breakdown:"ad（～へ）＋ tach（杭で留める）→ 相手のほうへ留めつける"},
     {word:"detached",meaning:"一戸建ての；超然とした",breakdown:"de（離して）＋ tach（杭で留める）＋ ed（～された）→ 離されている"},
     {word:"attachment",meaning:"愛着；添付ファイル",breakdown:"ad（～へ）＋ tach（杭で留める）＋ ment（名詞）→ 付いているもの"},
     {synonym:true,word:"remove",meaning:"取り外す",breakdown:"取り去ること全般。detach はつながった部分を外す"}]},

  {id:1643,word:"withdraw",partOfSpeech:"他動詞・自動詞",meaning:"撤退させる，引っ込める；（お金を）引き出す",
   meanings:["他|（軍隊など）を撤退させる，～を引っ込める","他|（預金）を引き出す","自|撤退する，身を引く"],
   pronunciation:"/wɪðˈdrɔː/",part:165,
   example:"The country decided to withdraw its troops from the area.",
   exampleJa:"その国はその地域から軍隊を撤退させることを決めた。",
   example2:"I withdrew some money from the bank yesterday.",
   exampleJa2:"昨日、私は銀行からお金を少し引き出した。",
   etymologyProcess:"with（後ろへ）＋ draw（引っぱる）→ 前に出ていたものを後ろへ引っぱると…？",
   etymologyConclusion:"with（後ろへ）＋ draw（引っぱる）→ 前に出ていたものを後ろへ引き戻す＝撤退させる",
   relatedWords:[
     {word:"draw",meaning:"引く；描く",breakdown:"draw（引っぱる）→ 手前へ引く、線を引いて描く"},
     {word:"drawer",meaning:"引き出し",breakdown:"draw（引っぱる）＋ er（もの）→ 引っぱり出す箱"},
     {word:"withstand",meaning:"耐える",breakdown:"with（後ろへ）＋ stand（立つ）→ 押されても逆らって立つ"},
     {synonym:true,word:"retreat",meaning:"退く",breakdown:"負けて後ろへ下がる。withdraw は自分から引き下げる"}]},

  {id:1644,word:"compile",partOfSpeech:"他動詞",meaning:"（資料を集めて）編集する，作成する",
   meanings:["他|（資料を集めて）～を編集する，作成する"],
   pronunciation:"/kəmˈpaɪl/",part:165,
   example:"The students compiled a list of local history sites.",
   exampleJa:"生徒たちは地元の史跡の一覧を編集した。",
   example2:"It took two years to compile this dictionary.",
   exampleJa2:"この辞書を編集して作るのに2年かかった。",
   etymologyProcess:"com（共に）＋ pil（かき集める）→ 資料をあちこちから一か所へかき集めると…？",
   etymologyConclusion:"com（共に）＋ pil（かき集める）→ あちこちの資料をかき集めて一つにする＝（資料を集めて）編集する",
   why:"【なぜ】ラテン語 compilare は「根こそぎ持ち去る・かき集める」。英語ではあちこちの資料を集めて一つにまとめる意味で使われ、「編集する」になりました。pile（積み重ね）とは本来別の語ですが、似た形から結びつけて覚えられてきました。\n【つながり】コンピューターの「コンパイル」も、命令をまとめて機械語にすることです。",
   relatedWords:[
     {word:"compilation",meaning:"編集（したもの）",breakdown:"com（共に）＋ pil（かき集める）＋ ation（名詞）→ かき集めてまとめたもの"},
     {synonym:true,word:"gather",meaning:"集める",breakdown:"寄せ集めること全般。compile は集めて本や一覧にする"},
     {synonym:true,word:"collect",meaning:"集める",breakdown:"集めること全般。compile は集めて一冊にする"},
     {synonym:true,word:"edit",meaning:"編集する",breakdown:"手を入れて直すこと。compile は集めて作る"}]},

  {id:1645,word:"browse",partOfSpeech:"他動詞・自動詞",meaning:"（本や店などを）拾い読みする，見て回る",
   meanings:["自|（本や店で）拾い読みする，見て回る","他|（ネット）を閲覧する"],
   pronunciation:"/braʊz/",part:165,
   example:"I like to browse in bookstores on weekends.",
   exampleJa:"週末は本屋で本を拾い読みして回るのが好きだ。",
   example2:"He browsed the internet for cheap flights to Hawaii.",
   exampleJa2:"彼はハワイ行きの安い航空券を探してネットを見て回った。",
   etymologyProcess:"browse（若芽を食べる）→ 牛が若芽をあちこち少しずつ食べると…？",
   etymologyConclusion:"browse（若芽を食べる）→ あちこちの若芽を少しずつつまむように見る＝（本や店などを）拾い読みする",
   hook:"古いフランス語 brost（若芽）から。パソコンの「ブラウザ」はネットを見て回るソフト。",
   relatedWords:[
     {synonym:true,word:"skim",meaning:"ざっと読む",breakdown:"大事な所だけさっと読む。browse は気ままに見る"},
     {synonym:true,word:"look around",meaning:"見て回る",breakdown:"ふつうの言い方。browse は店や本を見て回る"},
     {synonym:true,word:"scan",meaning:"ざっと目を通す",breakdown:"さっと見わたす。browse はのんびり見る"},
     {synonym:true,word:"surf",meaning:"（ネットを）見て回る",breakdown:"サイトを次々に見る。browse とほぼ同じ"}]},

  {id:1646,word:"manipulate",partOfSpeech:"他動詞",meaning:"（人や情報を）操る；（巧みに）操作する",
   meanings:["他|（人や情報）を操る","他|（機械など）を巧みに操作する"],
   pronunciation:"/məˈnɪpjuleɪt/",part:165,
   example:"Some advertisers try hard to manipulate people's feelings.",
   exampleJa:"人々の感情を必死に操ろうとする広告主もいる。",
   example2:"The robot can manipulate tiny parts with great care.",
   exampleJa2:"そのロボットは小さな部品をとても慎重に操作できる。",
   etymologyProcess:"manip（ひと握り）＋ ate（動詞）→ 手の中にひと握りつかんで思うように動かすと…？",
   etymologyConclusion:"manip（ひと握り）＋ ate（動詞）→ 手の中につかんで思いのままに動かす＝（人や情報を）操る",
   relatedWords:[
     {word:"manual",meaning:"手の；説明書",breakdown:"manu（手）＋ al（形容詞）→ 手で行う"},
     {word:"manufacture",meaning:"製造する",breakdown:"manu（手）＋ fact（作る）→ もとは手で作ること"},
     {word:"manipulation",meaning:"操作；ごまかし",breakdown:"manip（ひと握り）＋ ation（名詞）→ 手で思いのままに動かすこと"},
     {synonym:true,word:"control",meaning:"支配する",breakdown:"思いどおりに動かす。manipulate はずるく操る感じ"}]},

  {id:1647,word:"implement",partOfSpeech:"他動詞",meaning:"（計画を）実行する，実施する",
   meanings:["他|（計画や政策）を実行する，実施する"],
   pronunciation:"/ˈɪmplɪment/",part:165,
   example:"The school will implement the new rules next April.",
   exampleJa:"学校は来年の4月から新しい規則を実行する。",
   example2:"The plan was implemented without any serious problems.",
   exampleJa2:"その計画は大きな問題もなく実施された。",
   etymologyProcess:"im（中へ）＋ ple（満たす）＋ ment（名詞）→ 計画の中身を満たして形にすると…？",
   etymologyConclusion:"im（中へ）＋ ple（満たす）＋ ment（名詞）→ 計画の中身を満たして、実際に形にしていく＝（計画を）実行する",
   relatedWords:[
     {word:"complete",meaning:"完成させる",breakdown:"com（すっかり）＋ ple（満たす）→ すっかり満たして仕上げる"},
     {word:"supplement",meaning:"補う",breakdown:"sup（下から）＋ ple（満たす）→ 足りない所を下から満たす"},
     {word:"plenty",meaning:"たくさん",breakdown:"ple（満たす）＋ ty（名詞）→ 満ちあふれるほどの量"},
     {synonym:true,word:"carry out",meaning:"実行する",breakdown:"ふつうの言い方。implement は政策などに使うかたい語"}]},

  {id:1648,word:"execute",partOfSpeech:"他動詞",meaning:"（計画を）遂行する；処刑する",
   meanings:["他|（計画や命令）を遂行する","他|～を処刑する"],
   pronunciation:"/ˈeksɪkjuːt/",part:165,
   example:"The team executed the plan perfectly in the final game.",
   exampleJa:"チームは決勝戦でその作戦を完ぺきに遂行した。",
   example2:"In the past, many criminals were executed in public.",
   exampleJa2:"昔は多くの犯罪者が人前で処刑された。",
   etymologyProcess:"ex（外へ）＋ secu（ついて行く）→ 最後までついて行ってやりとげると…？",
   etymologyConclusion:"ex（外へ）＋ secu（ついて行く）→ 最後までついて行ってやりとげる＝（計画を）遂行する",
   why:"【なぜ】ラテン語 exsequi は ex（外へ＝最後まで）＋ sequi（ついて行く）で「最後までやりとげる」。中世では「判決を最後まで実行する」という意味でも使われ、死刑の判決を実行することから「処刑する」の意味が生まれました。\n【つながり】executive（重役＝実行する人）、sequence（連続）も同じ家族。「エグゼクティブ」は決めたことを実行する人です。",
   relatedWords:[
     {word:"executive",meaning:"重役，経営者",breakdown:"ex（外へ）＋ secu（ついて行く）＋ ive（～な性質の）→ 決めたことを実行する人"},
     {word:"sequence",meaning:"連続，順序",breakdown:"sequ（ついて行く）＋ ence（名詞）→ 次々についてくるもの"},
     {word:"consequence",meaning:"結果",breakdown:"con（共に）＋ sequ（ついて行く）＋ ence（名詞）→ あとについてくるもの"},
     {synonym:true,word:"perform",meaning:"行う",breakdown:"何かをやること。execute は計画どおりやりとげる"}]},

  {id:1649,word:"host",partOfSpeech:"他動詞",meaning:"主催する，（客を）迎えてもてなす",
   meanings:["他|（行事）を主催する","他|（客）を迎えてもてなす"],
   pronunciation:"/hoʊst/",part:165,
   example:"Japan will host the international conference next year.",
   exampleJa:"日本は来年、その国際会議を主催する。",
   example2:"Our family hosted an exchange student last summer.",
   exampleJa2:"去年の夏、うちは留学生を迎えてもてなした。",
   etymologyProcess:"host（客をもてなす）→ 客を迎えて会を開く側になると…？",
   etymologyConclusion:"host（客をもてなす）→ 客を迎えてもてなす側として会を開く＝主催する",
   relatedWords:[
     {word:"hospital",meaning:"病院",breakdown:"hosp（客をもてなす）＋ al（名詞）→ 旅人をもてなし世話した家"},
     {word:"hotel",meaning:"ホテル",breakdown:"hotel（客をもてなす）→ 旅人を泊めてもてなす所"},
     {word:"hospitality",meaning:"おもてなし",breakdown:"hosp（客をもてなす）＋ ity（名詞）→ 客をもてなす心"},
     {synonym:true,word:"organize",meaning:"計画して開く",breakdown:"準備して行う。host は会場となり客を迎える"}]},

  {id:1650,word:"mount",partOfSpeech:"他動詞・自動詞",meaning:"据え付ける；（徐々に）増える",
   meanings:["他|～を据え付ける","自|（徐々に）増える，高まる","他|（馬や自転車）に乗る"],
   pronunciation:"/maʊnt/",part:165,
   example:"We plan to mount a TV on the living room wall.",
   exampleJa:"私たちは居間の壁にテレビを据え付ける予定だ。",
   example2:"Pressure on the team mounted as the final approached.",
   exampleJa2:"決勝が近づくにつれて、チームへの重圧は高まった。",
   etymologyProcess:"mount（山）→ 山の上に上がるように、台の上に載せると…？",
   etymologyConclusion:"mount（山）→ 台の上にしっかり載せて固定する＝据え付ける",
   why:"【なぜ】ラテン語 mons（山）から、フランス語 monter（上がる・登る）が生まれました。「上に上がる」から「馬に乗る」、「上に載せて固定する」＝据え付ける、「山のように積み上がる」＝増える、と意味が広がりました。\n【つながり】mountain（山）、amount（量＝積み上がった合計）も同じ家族です。",
   relatedWords:[
     {word:"mountain",meaning:"山",breakdown:"mount（山）＋ ain（～の）→ 高くそびえる山"},
     {word:"amount",meaning:"量，総額",breakdown:"ad（～へ）＋ mount（山）→ 山のように積み上がった合計"},
     {word:"surmount",meaning:"乗り越える",breakdown:"sur（上を越えて）＋ mount（山）→ 山の上を越えて行く"},
     {synonym:true,word:"install",meaning:"設置する",breakdown:"機械などを取り付ける。mount は台や壁に固定する"}]},
